gem5: mem/ruby/profiler/AddressProfiler.cc File Reference
mem/ruby/profiler/AddressProfiler.cc File Reference
#include <vector>
#include "base/stl_helpers.hh"
#include "mem/protocol/RubyRequest.hh"
#include "mem/ruby/profiler/AddressProfiler.hh"
#include "mem/ruby/profiler/Profiler.hh"
#include "mem/ruby/system/System.hh"
Typedefs
typedef AddressProfiler::AddressMap AddressMap
Functions
AccessTraceForAddress & lookupTraceForAddress (const Address &addr, AddressMap &record_map)
void printSorted (ostream &out, int num_of_sequencers, const AddressMap &record_map, string description)
Typedef Documentation
typedef AddressProfiler::AddressMap AddressMap
Definition at line 38 of file AddressProfiler.cc.
Function Documentation
AccessTraceForAddress& lookupTraceForAddress (const Address & addr, AddressMap & record_map)
Definition at line 44 of file AddressProfiler.cc.
References ArmISA::i, MipsISA::r, and AccessTraceForAddress::setAddress().
Referenced by AddressProfiler::addTraceSample(), and AddressProfiler::profileRetry().
void printSorted (ostream & out, int num_of_sequencers, const AddressMap & record_map, string description)
Definition at line 66 of file AddressProfiler.cc.
References Histogram::add(), g_system_ptr, Profiler::getAllInstructions(), RubySystem::getProfiler(), AccessTraceForAddress::getTotal(), AccessTraceForAddress::getTouchedBy(), ArmISA::i, ArmISA::j, and AccessTraceForAddress::less_equal().