gem5: arch/arm/linux/process.cc File Reference
arch/arm/linux/process.cc File Reference
#include "arch/arm/linux/linux.hh"
#include "arch/arm/linux/process.hh"
#include "arch/arm/isa_traits.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/linux/linux.hh"
#include "sim/process.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
static SyscallReturn unameFunc32 (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target uname() handler.
static SyscallReturn unameFunc64 (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target uname() handler.
static SyscallReturn setTLSFunc32 (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target set_tls() handler.
static SyscallReturn setTLSFunc64 (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Variables
static SyscallDesc syscallDescs32 []
static SyscallDesc syscallDescs64 []
static SyscallDesc privSyscallDescs32 []
static SyscallDesc privSyscallDescs64 []
Function Documentation
static SyscallReturn setTLSFunc32 (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target set_tls() handler.
Definition at line 98 of file process.cc.
References ArmLinuxProcess32::commPage, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, ArmISA::MISCREG_TPIDRURO, ThreadContext::setMiscReg(), and SETranslatingPortProxy::writeBlob().
static SyscallReturn setTLSFunc64 (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Definition at line 111 of file process.cc.
References LiveProcess::getSyscallArg(), MipsISA::index, ArmISA::MISCREG_TPIDRRO_EL0, and ThreadContext::setMiscReg().
static SyscallReturn unameFunc32 (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target uname() handler.
Definition at line 62 of file process.cc.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and name().
static SyscallReturn unameFunc64 (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target uname() handler.
Definition at line 80 of file process.cc.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and name().
Variable Documentation
SyscallDesc privSyscallDescs32[] [static]
Initial value:
 {
     SyscallDesc("breakpoint", unimplementedFunc),
     SyscallDesc("cacheflush", unimplementedFunc),
     SyscallDesc("usr26", unimplementedFunc),
     SyscallDesc("usr32", unimplementedFunc),
     SyscallDesc("set_tls", setTLSFunc32)
}
Definition at line 1573 of file process.cc.
SyscallDesc privSyscallDescs64[] [static]
Initial value:
 {
     SyscallDesc("unallocated", unimplementedFunc),
     SyscallDesc("cacheflush", unimplementedFunc),
     SyscallDesc("unallocated", unimplementedFunc),
     SyscallDesc("unallocated", unimplementedFunc),
     SyscallDesc("set_tls", setTLSFunc64)
}
Definition at line 1582 of file process.cc.
SyscallDesc syscallDescs32[] [static]
Definition at line 121 of file process.cc.
SyscallDesc syscallDescs64[] [static]
Definition at line 490 of file process.cc.