gem5: arch/x86/types.cc File Reference
arch/x86/types.cc File Reference
#include "arch/x86/types.hh"
#include "sim/serialize.hh"
Functions
template<>
void paramOut (ostream &os, const string &name, ExtMachInst const &machInst)
template<>
void paramIn (Checkpoint *cp, const string &section, const string &name, ExtMachInst &machInst)
Function Documentation
template<> void paramIn (Checkpoint * cp, const string & section, const string & name, ExtMachInst & machInst) [inline]
Definition at line 69 of file types.cc.
References X86ISA::ExtMachInst::addrSize, X86ISA::ExtMachInst::displacement, X86ISA::ExtMachInst::dispSize, X86ISA::ExtMachInst::immediate, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::modRM, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, X86ISA::ExtMachInst::rex, X86ISA::ExtMachInst::sib, X86ISA::ExtMachInst::stackSize, and X86ISA::ExtMachInst::type.
Referenced by paramIn(), Globals::unserialize(), EventQueue::unserialize(), FuncPageTable::unserialize(), MultiLevelPageTable< ISAOps >::unserialize(), X86ISA::PS2Mouse::unserialize(), X86ISA::PS2Keyboard::unserialize(), Iob::unserialize(), Sinic::Device::unserialize(), PciDevice::unserialize(), iGbReg::Regs::unserialize(), CopyEngineReg::ChanRegs::unserialize(), CopyEngineReg::Regs::unserialize(), VGic::unserialize(), Pl011::unserialize(), ArchTimer::unserialize(), VirtIODeviceBase::unserialize(), VirtQueue::unserialize(), SparcISA::TLB::unserialize(), and ArmISA::TlbEntry::unserialize().
template<> void paramOut (ostream & os, const string & name, ExtMachInst const & machInst) [inline]
Definition at line 39 of file types.cc.
References X86ISA::ExtMachInst::addrSize, X86ISA::ExtMachInst::displacement, X86ISA::ExtMachInst::dispSize, X86ISA::ExtMachInst::immediate, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::modRM, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, X86ISA::ExtMachInst::rex, X86ISA::ExtMachInst::sib, X86ISA::ExtMachInst::stackSize, and X86ISA::ExtMachInst::type.
Referenced by paramOut(), Ticked::serialize(), Globals::serialize(), FuncPageTable::serialize(), MultiLevelPageTable< ISAOps >::serialize(), X86ISA::PS2Mouse::serialize(), X86ISA::PS2Keyboard::serialize(), Iob::serialize(), Sinic::Device::serialize(), PciDevice::serialize(), iGbReg::Regs::serialize(), LinkDelayEvent::serialize(), CopyEngineReg::ChanRegs::serialize(), CopyEngineReg::Regs::serialize(), Pl011::serialize(), GenericTimerMem::serialize(), GenericTimer::serialize(), ArchTimer::serialize(), VirtIODeviceBase::serialize(), Random::serialize(), and ArmISA::TlbEntry::serialize().