gem5: arch/arm/freebsd/process.cc File Reference
arch/arm/freebsd/process.cc File Reference
#include "arch/arm/freebsd/process.hh"
#include <sys/mman.h>
#include <sys/param.h>
#include <sys/syscall.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#include <utime.h>
#include "arch/arm/freebsd/freebsd.hh"
#include "arch/arm/isa_traits.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/freebsd/freebsd.hh"
#include "sim/process.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
static SyscallReturn issetugidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
static SyscallReturn sysctlFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Variables
static SyscallDesc syscallDescs32 []
static SyscallDesc syscallDescs64 []
Function Documentation
static SyscallReturn issetugidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Definition at line 55 of file process.cc.
static SyscallReturn sysctlFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Definition at line 63 of file process.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and MipsISA::index.
Variable Documentation
SyscallDesc syscallDescs32[] [static]
Definition at line 106 of file process.cc.
SyscallDesc syscallDescs64[] [static]
Definition at line 657 of file process.cc.