gem5: base/misc.cc File Reference
base/misc.cc File Reference
#include <cstdlib>
#include <cstring>
#include <string>
#include "base/cprintf.hh"
#include "base/hostinfo.hh"
#include "base/misc.hh"
#include "base/output.hh"
#include "base/trace.hh"
#include "base/types.hh"
#include "sim/core.hh"
Functions
static void newline_if_needed (std::ostream &stream, const char *format)
void __exit_epilogue (int code, const char *func, const char *file, int line, const char *format)
void __base_message_epilogue (std::ostream &stream, bool verbose, const char *func, const char *file, int line, const char *format)
Variables
bool want_warn = true
bool want_info = true
bool want_hack = true
bool warn_verbose = false
bool info_verbose = false
bool hack_verbose = false
Function Documentation
void __base_message_epilogue (std::ostream & stream, bool verbose, const char * func, const char * file, int line, const char * format)
Definition at line 100 of file misc.cc.
References ccprintf(), curTick(), and newline_if_needed().
Referenced by __base_message().
void __exit_epilogue (int code, const char * func, const char * file, int line, const char * format)
Definition at line 81 of file misc.cc.
References ccprintf(), curTick(), X86ISA::exit, memUsage(), and newline_if_needed().
Referenced by __exit_message().
static void newline_if_needed (std::ostream & stream, const char * format) [static]
Definition at line 67 of file misc.cc.
Referenced by __base_message_epilogue(), and __exit_epilogue().
Variable Documentation
bool hack_verbose = false
Definition at line 64 of file misc.cc.
bool info_verbose = false
Definition at line 63 of file misc.cc.
bool want_hack = true
Definition at line 60 of file misc.cc.
bool want_info = true
Definition at line 59 of file misc.cc.
bool want_warn = true
Definition at line 58 of file misc.cc.
bool warn_verbose = false
Definition at line 62 of file misc.cc.