gem5: base/bitfield.hh File Reference
base/bitfield.hh File Reference
#include "base/types.hh"
Defines
#define __has_builtin(foo) 0
Functions
uint64_t mask (int nbits)
Generate a 64-bit mask of 'nbits' 1s, right justified.
template<class T >
T bits (T val, int first, int last)
Extract the bitfield from position 'first' to 'last' (inclusive) from 'val' and right justify it.
template<class T >
T bits (T val, int bit)
Extract the bit from this position from 'val' and right justify it.
template<class T >
T mbits (T val, int first, int last)
Mask off the given bits in place like bits() but without shifting.
uint64_t mask (int first, int last)
template<int N>
uint64_t sext (uint64_t val)
Sign-extend an N-bit value to 64 bits.
template<class T , class B >
T insertBits (T val, int first, int last, B bit_val)
Return val with bits first to last set to bit_val.
template<class T , class B >
T insertBits (T val, int bit, B bit_val)
Overloaded for access to only one bit in value.
template<class T , class B >
void replaceBits (T &val, int first, int last, B bit_val)
A convenience function to replace bits first to last of val with bit_val in place.
template<class T , class B >
void replaceBits (T &val, int bit, B bit_val)
Overloaded function to allow to access only 1 bit.
int findMsbSet (uint64_t val)
Returns the bit position of the MSB that is set in the input.
int findLsbSet (uint64_t val)
Returns the bit position of the LSB that is set in the input.
template<class T >
bool isPow2 (T v)
Checks if a number is a power of two, or zero.
int popCount (uint64_t val)
Returns the number of set ones in the provided value.
Define Documentation
#define __has_builtin (foo) 0
Function Documentation
template<class T > T bits (T val, int bit) [inline]
Extract the bit from this position from 'val' and right justify it.
Definition at line 67 of file bitfield.hh.
References bits().
template<class T > T bits (T val, int first, int last) [inline]
Extract the bitfield from position 'first' to 'last' (inclusive) from 'val' and right justify it.
MSB is numbered 63, LSB is 0.
Definition at line 55 of file bitfield.hh.
References ArmISA::mask.
Referenced by SparcISA::PageTableEntry::_size(), ArmISA::TableWalker::LongDescriptor::af(), ArmISA::TableWalker::LongDescriptor::ap(), ArmISA::TableWalker::L2Descriptor::ap(), ArmISA::TableWalker::L1Descriptor::ap(), ArmISA::TableWalker::LongDescriptor::apTable(), ArmISA::ArmStaticInst::ArmStaticInst(), ArmISA::TableWalker::LongDescriptor::attrIndx(), bits(), ArmISA::TableWalker::checkAddrSizeFaultAArch64(), X86ISA::Interrupts::checkInterrupts(), X86ISA::Interrupts::checkInterruptsRaw(), AddrRange::contains(), ArmISA::TableWalker::LongDescriptor::contiguousHint(), SparcISA::PageTableEntry::cp(), ArmISA::ArmStaticInst::cpsrWriteByInstr(), SparcISA::PageTableEntry::cv(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL2Descriptor(), ArmISA::TableWalker::L1Descriptor::domain(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), MipsISA::dspDpaq(), MipsISA::dspDpsq(), MipsISA::dspExtp(), MipsISA::dspExtpd(), MipsISA::dspExtr(), MipsISA::dspPick(), MipsISA::dspShll(), MipsISA::dspShra(), MipsISA::dspShrl(), ArmISA::EndBitUnion(), iGbReg::TxdOp::eop(), ArmISA::ArmStaticInst::extendReg64(), findLsbSet(), findMsbSet(), findNegative(), ArmISA::fpToBits(), MultiGrainBloomFilter::get_page_index(), BitfieldBackend::BitfieldBase< Type >::getBits(), iGbReg::TxdOp::getCso(), iGbReg::TxdOp::getCss(), ArmISA::AbortFault< T >::getFsr(), iGbReg::TxdOp::getLen(), X86ISA::Interrupts::getRegArrayBit(), Sparc32LiveProcess::getSyscallArg(), iGbReg::TxdOp::getTsoLen(), iGbReg::TxdOp::getType(), X86ISA::I8259::getVector(), ArmISA::TableWalker::LongDescriptor::global(), ArmISA::TableWalker::L2Descriptor::global(), ArmISA::TableWalker::L1Descriptor::global(), iGbReg::TxdOp::hdrlen(), iGbReg::TxdOp::ic(), iGbReg::TxdOp::ide(), SparcISA::PageTableEntry::ie(), iGbReg::TxdOp::ifcs(), X86ISA::X86_64LiveProcess::initState(), PowerISA::PowerStaticInst::insertCRField(), ArmISA::TableWalker::L2Descriptor::invalid(), iGbReg::TxdOp::ip(), iGbReg::TxdOp::ipcse(), iGbReg::TxdOp::ipcso(), iGbReg::TxdOp::ipcss(), PowerISA::FloatOp::isDenormalized(), PowerISA::FloatOp::isInfinity(), iGbReg::TxdOp::isLegacy(), PowerISA::FloatOp::isNan(), PowerISA::FloatOp::isNegative(), PowerISA::FloatOp::isNormalized(), PowerISA::FloatOp::isQnan(), ArmISA::SecureMonitorCall::iss(), ArmISA::UndefinedInstruction::iss(), PowerISA::FloatOp::isSnan(), PowerISA::FloatOp::isZero(), iGbReg::TxdOp::ixsm(), ArmISA::TableWalker::L2Descriptor::large(), SparcISA::PageTableEntry::locked(), ArmISA::MacroMemOp::MacroMemOp(), SparcISA::TLB::MakeTsbPtr(), ArmISA::TableWalker::LongDescriptor::memAttr(), ArmISA::TableWalker::memAttrs(), ArmISA::TableWalker::memAttrsAArch64(), ArmISA::TableWalker::memAttrsLPAE(), SparcISA::Decoder::moreBytes(), iGbReg::TxdOp::mss(), ArmISA::TableWalker::LongDescriptor::nextDescAddr(), SparcISA::PageTableEntry::nofault(), ArmISA::TableWalker::LongDescriptor::pfn(), ArmISA::TableWalker::L2Descriptor::pfn(), ArmISA::TableWalker::L1Descriptor::pfn(), SparcISA::PageTableEntry::pfn(), SparcISA::PageTableEntry::populate(), ArmISA::PredImmOp::PredImmOp(), MsrBase::printMsrBase(), SparcISA::PageTableEntry::priv(), ArmISA::Decoder::process(), X86ISA::PS2Keyboard::processData(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TableWalker::LongDescriptor::pxn(), ArmISA::TableWalker::LongDescriptor::pxnTable(), IdeController::readConfig(), Pl390::readCpu(), SparcISA::ISA::readMiscRegNoEffect(), DRAMCtrl::reorderQueue(), X86ISA::I8259::requestInterrupt(), Sp804::Timer::restartCounter(), iGbReg::TxdOp::rs(), ArmISA::TableWalker::LongDescriptor::rw(), ArmISA::TableWalker::LongDescriptor::rwTable(), ArmISA::ArmStaticInst::saturateOp(), ArmISA::TableWalker::LongDescriptor::secure(), ArmISA::TableWalker::L1Descriptor::secure(), ArmISA::TableWalker::LongDescriptor::secureTable(), PciDevice::serialize(), SparcISA::ISA::setFSReg(), X86ISA::Interrupts::setReg(), ArmISA::ArmFault::setSyndrome(), SparcLiveProcess::setSyscallReturn(), setThreadArea32Func(), sext(), ArmISA::TableWalker::LongDescriptor::sh(), ArmISA::TableWalker::L2Descriptor::shareable(), ArmISA::TableWalker::L1Descriptor::shareable(), ArmISA::ArmStaticInst::shiftReg64(), SparcISA::PageTableEntry::sideffect(), X86ISA::I8259::signalInterrupt(), ArmISA::simd_modified_imm(), MipsISA::simdPack(), MipsISA::simdUnpack(), ArmISA::ArmStaticInst::spsrWriteByInstr(), X86ISA::Walker::WalkerState::stepWalk(), ArmISA::TableWalker::L1Descriptor::supersection(), iGbReg::TxdOp::tcp(), ArmISA::TableWalker::L2Descriptor::texcb(), ArmISA::TableWalker::L1Descriptor::texcb(), Trace::InstPBTrace::traceInst(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), SparcISA::TLB::translateInst(), X86ISA::TLB::translateInt(), iGbReg::TxdOp::tse(), iGbReg::TxdOp::tucse(), iGbReg::TxdOp::tucso(), iGbReg::TxdOp::tucss(), iGbReg::TxdOp::txsm(), ArmISA::TableWalker::LongDescriptor::type(), PciDevice::unserialize(), Pl390::updateIntState(), ArmISA::TLB::updateMiscReg(), ArmISA::TableWalker::LongDescriptor::user(), ArmISA::TableWalker::LongDescriptor::userTable(), iGbReg::TxdOp::utcmd(), SparcISA::TteTag::va(), SparcISA::PageTableEntry::valid(), SparcISA::TteTag::valid(), ArmISA::vcvtFpFpH(), ArmISA::vcvtFpHFp(), ArmISA::vfp_modified_imm(), iGbReg::TxdOp::vle(), SparcISA::PageTableEntry::writable(), X86ISA::I8259::write(), X86ISA::I8237::write(), IGbE::write(), CopyEngine::write(), RealViewCtrl::write(), Pl390::writeDistributor(), Iob::writeIob(), Iob::writeJBus(), X86ISA::I82094AA::writeReg(), ArmISA::TableWalker::LongDescriptor::xn(), ArmISA::TableWalker::L2Descriptor::xn(), ArmISA::TableWalker::L1Descriptor::xn(), and ArmISA::TableWalker::LongDescriptor::xnTable().
int findLsbSet (uint64_t val) [inline]
Returns the bit position of the LSB that is set in the input.
Definition at line 168 of file bitfield.hh.
References bits().
Referenced by UFSHostDevice::requestHandler().
int findMsbSet (uint64_t val) [inline]
Returns the bit position of the MSB that is set in the input.
Definition at line 151 of file bitfield.hh.
References bits().
Referenced by CopyEngine::CopyEngine(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), X86ISA::Interrupts::findRegArrayMSB(), X86ISA::I8259::getVector(), X86ISA::I8259::handleEOI(), and X86ISA::I8259::write().
template<class T , class B > T insertBits (T val, int bit, B bit_val) [inline]
Overloaded for access to only one bit in value.
Definition at line 121 of file bitfield.hh.
References insertBits().
template<class T , class B > T insertBits (T val, int first, int last, B bit_val) [inline]
Return val with bits first to last set to bit_val.
Definition at line 108 of file bitfield.hh.
References ArmISA::mask.
Referenced by GenericTimerMem::ctrlWrite(), MipsISA::dspDpaq(), MipsISA::dspDpsq(), MipsISA::dspExtp(), MipsISA::dspExtpd(), MipsISA::dspExtr(), MipsISA::dspMaq(), MipsISA::dspMulsaq(), MipsISA::dspPrecrq(), MipsISA::dspPrecrqu(), insertBits(), replaceBits(), and GenericTimerMem::timerWrite().
template<class T > bool isPow2 (T v) [inline]
Checks if a number is a power of two, or zero.
Definition at line 186 of file bitfield.hh.
Referenced by SnoopFilter::lookupRequest(), and SnoopFilter::lookupSnoop().
uint64_t mask (int first, int last) [inline]
Definition at line 85 of file bitfield.hh.
References LL, and mbits().
uint64_t mask (int nbits) [inline]
Generate a 64-bit mask of 'nbits' 1s, right justified.
Definition at line 41 of file bitfield.hh.
References LL, and ULL.
template<class T > T mbits (T val, int first, int last) [inline]
Mask off the given bits in place like bits() but without shifting.
msb = 63, lsb = 0
Definition at line 79 of file bitfield.hh.
References ArmISA::mask.
Referenced by IGbE::TxDescCache::actionAfterWb(), ArmISA::TableWalker::doLongDescriptor(), SparcISA::TLB::doMmuRegWrite(), SparcISA::TLB::GetTsbPtr(), ArmISA::TableWalker::L1Descriptor::l2Addr(), SparcISA::TLB::MakeTsbPtr(), mask(), ArmISA::TableWalker::LongDescriptor::nextTableAddr(), ArmISA::TableWalker::LongDescriptor::paddr(), ArmISA::TableWalker::L2Descriptor::paddr(), ArmISA::TableWalker::L1Descriptor::paddr(), SparcISA::PageTableEntry::paddr(), SparcISA::PageTableEntry::populate(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), Pl390::readDistributor(), SparcISA::ISA::readMiscReg(), SparcISA::ISA::setMiscReg(), SparcISA::TlbEntry::TlbEntry(), X86ISA::TLB::translateInt(), Pl390::writeDistributor(), and SparcISA::TLB::writeTagAccess().
int popCount (uint64_t val) [inline]
Returns the number of set ones in the provided value.
PD algorithm from http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel
Definition at line 196 of file bitfield.hh.
References Stats::sum().
template<class T , class B > void replaceBits (T & val, int bit, B bit_val) [inline]
Overloaded function to allow to access only 1 bit.
Definition at line 142 of file bitfield.hh.
References insertBits().
template<class T , class B > void replaceBits (T & val, int first, int last, B bit_val) [inline]
A convenience function to replace bits first to last of val with bit_val in place.
Definition at line 133 of file bitfield.hh.
References insertBits().
Referenced by MipsISA::ISA::configCP(), ArmISA::EndBitUnion(), DramGen::genStartAddr(), DramRotGen::getNextPacket(), DramGen::getNextPacket(), X86ISA::IntelMP::IntAssignment::IntAssignment(), ArmISA::MacroMemOp::MacroMemOp(), DRAMCtrl::minBankPrep(), X86ISA::IntelMP::Processor::Processor(), BitfieldBackend::BitfieldBase< Type >::setBits(), iGbReg::TxdOp::setDd(), ArmISA::vcvtFpFpH(), ArmISA::vcvtFpHFp(), X86ISA::I8237::write(), and IdeController::writeConfig().
template<int N> uint64_t sext (uint64_t val) [inline]
Sign-extend an N-bit value to 64 bits.
Definition at line 96 of file bitfield.hh.
References bits(), and ArmISA::mask.
Referenced by BitfieldBackend::SignedBitfieldTypes< Type >::SignedBitfield< first, last >::operator const int64_t().