gem5: cpu/testers/rubytest/Check.hh File Reference
cpu/testers/rubytest/Check.hh File Reference
#include <iostream>
#include "cpu/testers/rubytest/RubyTester.hh"
#include "mem/protocol/RubyAccessMode.hh"
#include "mem/protocol/TesterStatus.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/Global.hh"
Classes
class Check
Functions
std::ostream & operator<< (std::ostream &out, const Check &obj)
Variables
const int CHECK_SIZE_BITS = 2
const int CHECK_SIZE = (1 << CHECK_SIZE_BITS)
Function Documentation
std::ostream& operator<< (std::ostream & out, const Check & obj) [inline]
Definition at line 83 of file Check.hh.
References Check::print().
Variable Documentation
const int CHECK_SIZE = (1 << CHECK_SIZE_BITS)
Definition at line 44 of file Check.hh.
Referenced by CheckTable::addCheck(), CheckTable::CheckTable(), Check::initiateCheck(), Check::initiateFlush(), and Check::performCallback().
const int CHECK_SIZE_BITS = 2
Definition at line 43 of file Check.hh.
Referenced by CheckTable::addCheck().