gem5: MrsOp Class Reference
MrsOp Class Reference
#include <misc.hh>
Protected Member Functions
MrsOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
Detailed Description
Definition at line 45 of file misc.hh.
Constructor & Destructor Documentation
MrsOp::MrsOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest) [inline, protected]
Definition at line 50 of file misc.hh.
Member Function Documentation
std::string MrsOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 45 of file misc.cc.
References dest, ArmISA::i, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_SPSR, MiscRegClass, StaticInst::numSrcRegs(), ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), regIdxToClass(), StaticInst::srcRegIdx(), and ArmISA::ss.
Member Data Documentation
IntRegIndex MrsOp::dest [protected]
Definition at line 48 of file misc.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/misc.hh
arch/arm/insts/misc.cc