gem5: VirtDescriptor Class Reference
VirtDescriptor Class Reference
VirtIO descriptor (chain) wrapper.
#include <base.hh>
Public Types
typedef uint16_t Index
Descriptor index in virtqueue.
Public Member Functions
VirtIO Descriptor <-> Queue Interface
VirtDescriptor (PortProxy &memProxy, VirtQueue &queue, Index index)
Create a descriptor wrapper.
VirtDescriptor (VirtDescriptor &&other) noexcept
~VirtDescriptor () noexcept
VirtDescriptor & operator= (VirtDescriptor &&rhs) noexcept
Index index () const
Get the descriptor's index into the virtqueue.
void update ()
Populate this descriptor with data from the guest.
void updateChain ()
Populate this descriptor chain with data from the guest.
Debug interfaces
void dump () const
Dump the contents of a descriptor.
void dumpChain () const
Dump the contents of a descriptor chain starting at this descriptor.
Device Model Interfaces
void read (size_t offset, uint8_t *dst, size_t size) const
Read the contents of a descriptor.
void write (size_t offset, const uint8_t *src, size_t size)
Write to the contents of a descriptor.
size_t size () const
Retrieve the size of this descriptor.
bool hasNext () const
Is this descriptor chained to another descriptor?
VirtDescriptor * next () const
Get the pointer to the next descriptor in a chain.
bool isIncoming () const
Check if this is a read-only descriptor (incoming data).
bool isOutgoing () const
Check if this is a write-only descriptor (outgoing data).
void chainRead (size_t offset, uint8_t *dst, size_t size) const
Read the contents of a descriptor chain.
void chainWrite (size_t offset, const uint8_t *src, size_t size)
Write to a descriptor chain.
size_t chainSize () const
Retrieve the size of this descriptor chain.
Private Member Functions
VirtDescriptor ()
VirtDescriptor (const VirtDescriptor &other)
Private Attributes
PortProxy * memProxy
Pointer to memory proxy.
VirtQueue * queue
Pointer to virtqueue owning this descriptor.
Index _index
Index in virtqueue.
vring_desc desc
Underlying descriptor.
Detailed Description
VirtIO descriptor (chain) wrapper.
Communication in VirtIO takes place by sending and receiving chains of so called descriptors using device queues. The queue is responsible for sending a descriptor chain from the guest to the host and later sending it back to the guest. The descriptor chain itself can be thought of as a linked list of buffers (descriptors) that are read only (isIncoming() is true) or write only (isOutgoing() is true). A single chain may contain any mix of input and output buffers.
The descriptor wrapper is normally only instantiated by the virtqueue wrapper (VirtQueue) and should never be instantiated in device models. The VirtQueue also ensures that the descriptor wrapper is re-populated with new data from the guest by calling updateChain() whenever a new descriptor chain is passed to the host (VirtQueue::consumeDescriptor()). The updateChain() method automatically does some sanity checks on the descriptor chain to detect loops.
Definition at line 134 of file base.hh.
Member Typedef Documentation
typedef uint16_t VirtDescriptor::Index
Descriptor index in virtqueue.
Definition at line 138 of file base.hh.
Constructor & Destructor Documentation
VirtDescriptor::VirtDescriptor (PortProxy & memProxy, VirtQueue & queue, Index index)
Create a descriptor wrapper.
Parameters:
memProxy Proxy to the guest physical memory.
queue Queue owning this descriptor.
index Index within the queue.
Definition at line 44 of file base.cc.
VirtDescriptor::VirtDescriptor (VirtDescriptor && other)
VirtDescriptor::~VirtDescriptor ()
VirtDescriptor::VirtDescriptor () [private]
VirtDescriptor::VirtDescriptor (const VirtDescriptor & other) [private]
Member Function Documentation
void VirtDescriptor::chainRead (size_t offset, uint8_t * dst, size_t size) const
Read the contents of a descriptor chain.
This method reads the specified number of bytes from a descriptor chain starting at the this descriptor plus an offset in bytes. The method automatically follows the links in the descriptor chain.
Parameters:
offset Offset into the chain (in bytes).
dst Pointer to destination buffer.
size Size (in bytes).
Referenced by VirtIO9PBase::FSQueue::onNotifyDescriptor(), VirtIOConsole::TermTransQueue::onNotifyDescriptor(), VirtIOBlock::RequestQueue::onNotifyDescriptor(), and VirtIOBlock::write().
size_t VirtDescriptor::chainSize () const
Retrieve the size of this descriptor chain.
This method gets the size of a descriptor chain starting at this descriptor.
Returns:
Size of descriptor chain in bytes.
Referenced by VirtIOConsole::TermTransQueue::onNotifyDescriptor(), and VirtIOBlock::RequestQueue::onNotifyDescriptor().
void VirtDescriptor::chainWrite (size_t offset, const uint8_t * src, size_t size)
Write to a descriptor chain.
This method writes the specified number of bytes to a descriptor chain starting at the this descriptor plus an offset in bytes. The method automatically follows the links in the descriptor chain.
Parameters:
offset Offset into the chain (in bytes).
src Pointer to source buffer.
size Size (in bytes).
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor(), VirtIOBlock::read(), VirtIO9PBase::sendRMsg(), and VirtIOConsole::TermRecvQueue::trySend().
void VirtDescriptor::dump () const
Dump the contents of a descriptor.
void VirtDescriptor::dumpChain () const
Dump the contents of a descriptor chain starting at this descriptor.
bool VirtDescriptor::hasNext () const [inline]
Is this descriptor chained to another descriptor?
Returns:
true if there is a next pointer, false otherwise.
Definition at line 236 of file base.hh.
References desc, vring_desc::flags, and VRING_DESC_F_NEXT.
Index VirtDescriptor::index () const [inline]
Get the descriptor's index into the virtqueue.
Definition at line 160 of file base.hh.
References _index.
Referenced by VirtQueue::produceDescriptor().
bool VirtDescriptor::isIncoming () const [inline]
Check if this is a read-only descriptor (incoming data).
Definition at line 246 of file base.hh.
References isOutgoing().
bool VirtDescriptor::isOutgoing () const [inline]
Check if this is a write-only descriptor (outgoing data).
Definition at line 248 of file base.hh.
References desc, vring_desc::flags, and VRING_DESC_F_WRITE.
Referenced by isIncoming(), and VirtIO9PBase::sendRMsg().
VirtDescriptor* VirtDescriptor::next () const
Get the pointer to the next descriptor in a chain.
Returns:
Pointer to the next descriptor or NULL if this is the last element in a chain.
Referenced by VirtIO9PBase::sendRMsg().
VirtDescriptor& VirtDescriptor::operator= (VirtDescriptor && rhs)
void VirtDescriptor::read (size_t offset, uint8_t * dst, size_t size) const
Read the contents of a descriptor.
This method copies the contents of a descriptor into a buffer within gem5. Devices should typically use chainRead() instead as it automatically follows the descriptor chain to read the desired number of bytes.
See also:
chainRead
Parameters:
offset Offset into the descriptor.
dst Destination buffer.
size Amount of data to read (in bytes).
size_t VirtDescriptor::size () const [inline]
Retrieve the size of this descriptor.
This method gets the size of a single descriptor. For incoming data, it corresponds to the amount of data that can be read from the descriptor. For outgoing data, it corresponds to the amount of data that can be written to it.
See also:
chainSize
Returns:
Size of descriptor in bytes.
Definition at line 229 of file base.hh.
References desc, and vring_desc::len.
Referenced by VirtIO9PBase::FSQueue::onNotifyDescriptor(), VirtIOConsole::TermTransQueue::onNotifyDescriptor(), VirtIOBlock::RequestQueue::onNotifyDescriptor(), and VirtIOConsole::TermRecvQueue::trySend().
void VirtDescriptor::update ()
Populate this descriptor with data from the guest.
void VirtDescriptor::updateChain ()
Populate this descriptor chain with data from the guest.
Referenced by VirtQueue::consumeDescriptor().
void VirtDescriptor::write (size_t offset, const uint8_t * src, size_t size)
Write to the contents of a descriptor.
This method copies the contents of a descriptor into a buffer within gem5. Devices should typically use chainWrite() instead as it automatically follows the descriptor chain to read the desired number of bytes.
See also:
chainWrite
Parameters:
offset Offset into the descriptor.
src Source buffer.
size Amount of data to read (in bytes).
Member Data Documentation
Index VirtDescriptor::_index [private]
Index in virtqueue.
Definition at line 300 of file base.hh.
Referenced by index().
vring_desc VirtDescriptor::desc [private]
Underlying descriptor.
Definition at line 303 of file base.hh.
Referenced by hasNext(), isOutgoing(), and size().
PortProxy* VirtDescriptor::memProxy [private]
Pointer to memory proxy.
Definition at line 295 of file base.hh.
VirtQueue* VirtDescriptor::queue [private]
Pointer to virtqueue owning this descriptor.
Definition at line 297 of file base.hh.
The documentation for this class was generated from the following files:
dev/virtio/base.hh
dev/virtio/base.cc