gem5: MemCmd Class Reference
MemCmd Class Reference
#include <packet.hh>
Classes
struct CommandInfo
Structure that defines attributes and other data associated with a Command.
Public Types
enum Command {
InvalidCmd, ReadReq, ReadResp, ReadRespWithInvalidate,
WriteReq, WriteResp, Writeback, SoftPFReq,
HardPFReq, SoftPFResp, HardPFResp, WriteInvalidateReq,
WriteInvalidateResp, UpgradeReq, SCUpgradeReq, UpgradeResp,
SCUpgradeFailReq, UpgradeFailResp, ReadExReq, ReadExResp,
LoadLockedReq, StoreCondReq, StoreCondFailReq, StoreCondResp,
SwapReq, SwapResp, MessageReq, MessageResp,
InvalidDestError, BadAddressError, FunctionalReadError, FunctionalWriteError,
PrintReq, FlushReq, InvalidationReq, NUM_MEM_CMDS
}
List of all commands associated with a packet.
Public Member Functions
bool isRead () const
bool isWrite () const
bool isUpgrade () const
bool isRequest () const
bool isResponse () const
bool needsExclusive () const
bool needsResponse () const
bool isInvalidate () const
bool isWriteInvalidate () const
bool hasData () const
Check if this particular packet type carries payload data.
bool isLLSC () const
bool isSWPrefetch () const
bool isHWPrefetch () const
bool isPrefetch () const
bool isError () const
bool isPrint () const
bool isFlush () const
const Command responseCommand () const
const std::string & toString () const
Return the string to a cmd given by idx.
int toInt () const
MemCmd (Command _cmd)
MemCmd (int _cmd)
MemCmd ()
bool operator== (MemCmd c2) const
bool operator!= (MemCmd c2) const
Private Types
enum Attribute {
IsRead, IsWrite, IsUpgrade, IsInvalidate,
NeedsExclusive, IsRequest, IsResponse, NeedsResponse,
IsSWPrefetch, IsHWPrefetch, IsLlsc, HasData,
IsError, IsPrint, IsFlush, NUM_COMMAND_ATTRIBUTES
}
List of command attributes.
Private Member Functions
bool testCmdAttrib (MemCmd::Attribute attrib) const
Private Attributes
Command cmd
Static Private Attributes
static const CommandInfo commandInfo []
Array to map Command enum to associated info.
Friends
class Packet
Detailed Description
Definition at line 73 of file packet.hh.
Member Enumeration Documentation
enum MemCmd::Attribute [private]
List of command attributes.
Enumerator:
IsRead
Data flows from responder to requester.
IsWrite
Data flows from requester to responder.
IsUpgrade
IsInvalidate
NeedsExclusive
Requires exclusive copy to complete in-cache.
IsRequest
Issued by requester.
IsResponse
Issue by responder.
NeedsResponse
Requester needs response from target.
IsSWPrefetch
IsHWPrefetch
IsLlsc
Alpha/MIPS LL or SC access.
HasData
There is an associated payload.
IsError
Error response.
IsPrint
Print state matching address (for debugging).
IsFlush
Flush the address from caches.
NUM_COMMAND_ATTRIBUTES
Definition at line 130 of file packet.hh.
enum MemCmd::Command
List of all commands associated with a packet.
Enumerator:
InvalidCmd
ReadReq
ReadResp
ReadRespWithInvalidate
WriteReq
WriteResp
Writeback
SoftPFReq
HardPFReq
SoftPFResp
HardPFResp
WriteInvalidateReq
WriteInvalidateResp
UpgradeReq
SCUpgradeReq
UpgradeResp
SCUpgradeFailReq
UpgradeFailResp
ReadExReq
ReadExResp
LoadLockedReq
StoreCondReq
StoreCondFailReq
StoreCondResp
SwapReq
SwapResp
MessageReq
MessageResp
InvalidDestError
BadAddressError
FunctionalReadError
FunctionalWriteError
PrintReq
FlushReq
InvalidationReq
NUM_MEM_CMDS
Definition at line 81 of file packet.hh.
Constructor & Destructor Documentation
MemCmd::MemCmd (Command _cmd) [inline]
Definition at line 216 of file packet.hh.
MemCmd::MemCmd (int _cmd) [inline]
Definition at line 217 of file packet.hh.
MemCmd::MemCmd () [inline]
Definition at line 218 of file packet.hh.
Member Function Documentation
bool MemCmd::hasData () const [inline]
Check if this particular packet type carries payload data.
Note that this does not reflect if the data pointer of the packet is valid or not.
Definition at line 196 of file packet.hh.
References HasData, and testCmdAttrib().
Referenced by Packet::hasData().
bool MemCmd::isError () const [inline]
Definition at line 202 of file packet.hh.
References IsError, and testCmdAttrib().
Referenced by Packet::isError().
bool MemCmd::isFlush () const [inline]
Definition at line 204 of file packet.hh.
References IsFlush, and testCmdAttrib().
Referenced by Packet::isFlush().
bool MemCmd::isHWPrefetch () const [inline]
Definition at line 199 of file packet.hh.
References IsHWPrefetch, and testCmdAttrib().
bool MemCmd::isInvalidate () const [inline]
Definition at line 187 of file packet.hh.
References IsInvalidate, and testCmdAttrib().
Referenced by Packet::isInvalidate().
bool MemCmd::isLLSC () const [inline]
Definition at line 197 of file packet.hh.
References IsLlsc, and testCmdAttrib().
Referenced by Packet::isLLSC().
bool MemCmd::isPrefetch () const [inline]
Definition at line 200 of file packet.hh.
References IsHWPrefetch, IsSWPrefetch, and testCmdAttrib().
bool MemCmd::isPrint () const [inline]
Definition at line 203 of file packet.hh.
References IsPrint, and testCmdAttrib().
Referenced by Packet::isPrint().
bool MemCmd::isRead () const [inline]
Definition at line 180 of file packet.hh.
References IsRead, and testCmdAttrib().
Referenced by TraceGen::getNextPacket(), Packet::isRead(), and StackDistCalc::update().
bool MemCmd::isRequest () const [inline]
Definition at line 183 of file packet.hh.
References IsRequest, and testCmdAttrib().
Referenced by Packet::isRequest().
bool MemCmd::isResponse () const [inline]
Definition at line 184 of file packet.hh.
References IsResponse, and testCmdAttrib().
Referenced by Packet::isResponse().
bool MemCmd::isSWPrefetch () const [inline]
Definition at line 198 of file packet.hh.
References IsSWPrefetch, and testCmdAttrib().
Referenced by Cache::recvTimingReq(), and Cache::recvTimingResp().
bool MemCmd::isUpgrade () const [inline]
Definition at line 182 of file packet.hh.
References IsUpgrade, and testCmdAttrib().
Referenced by Packet::isUpgrade().
bool MemCmd::isWrite () const [inline]
Definition at line 181 of file packet.hh.
References IsWrite, and testCmdAttrib().
Referenced by BaseGen::getPacket(), Packet::isWrite(), and StackDistCalc::update().
bool MemCmd::isWriteInvalidate () const [inline]
Definition at line 188 of file packet.hh.
References IsInvalidate, IsWrite, and testCmdAttrib().
Referenced by Packet::isWriteInvalidate().
bool MemCmd::needsExclusive () const [inline]
Definition at line 185 of file packet.hh.
References NeedsExclusive, and testCmdAttrib().
Referenced by Packet::needsExclusive().
bool MemCmd::needsResponse () const [inline]
Definition at line 186 of file packet.hh.
References NeedsResponse, and testCmdAttrib().
Referenced by Packet::needsResponse().
bool MemCmd::operator!= (MemCmd c2) const [inline]
Definition at line 221 of file packet.hh.
References cmd.
bool MemCmd::operator== (MemCmd c2) const [inline]
Definition at line 220 of file packet.hh.
References cmd.
const Command MemCmd::responseCommand () const [inline]
Definition at line 207 of file packet.hh.
References cmd, commandInfo, and MemCmd::CommandInfo::response.
Referenced by TimingSimpleCPU::buildSplitPacket(), and Packet::makeResponse().
bool MemCmd::testCmdAttrib (MemCmd::Attribute attrib) const [inline, private]
Definition at line 173 of file packet.hh.
References MemCmd::CommandInfo::attributes, cmd, and commandInfo.
Referenced by hasData(), isError(), isFlush(), isHWPrefetch(), isInvalidate(), isLLSC(), isPrefetch(), isPrint(), isRead(), isRequest(), isResponse(), isSWPrefetch(), isUpgrade(), isWrite(), isWriteInvalidate(), needsExclusive(), and needsResponse().
int MemCmd::toInt () const [inline]
Definition at line 214 of file packet.hh.
References cmd.
Referenced by Packet::cmdToIndex().
const std::string& MemCmd::toString () const [inline]
Return the string to a cmd given by idx.
Definition at line 213 of file packet.hh.
References cmd, commandInfo, and MemCmd::CommandInfo::str.
Referenced by Packet::cmdString(), MessageSlavePort::recvAtomic(), Minor::LSQ::recvTimingResp(), BaseXBar::regStats(), and BaseCache::regStats().
Friends And Related Function Documentation
friend class Packet [friend]
Definition at line 75 of file packet.hh.
Member Data Documentation
Command MemCmd::cmd [private]
Definition at line 170 of file packet.hh.
Referenced by operator!=(), operator==(), TraceGen::InputStream::read(), responseCommand(), testCmdAttrib(), toInt(), and toString().
const MemCmd::CommandInfo MemCmd::commandInfo [static, private]
Array to map Command enum to associated info.
Definition at line 166 of file packet.hh.
Referenced by responseCommand(), testCmdAttrib(), and toString().
The documentation for this class was generated from the following files:
mem/packet.hh
mem/packet.cc