gem5: MemCheckerMonitor::MonitorSlavePort Class Reference
MemCheckerMonitor::MonitorSlavePort Class Reference
This is the slave port of the communication monitor.
Public Member Functions
MonitorSlavePort (const std::string &_name, MemCheckerMonitor &_mon)
Protected Member Functions
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
bool recvTimingSnoopResp (PacketPtr pkt)
Receive a timing snoop response from the master port.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Private Attributes
MemCheckerMonitor & mon
Detailed Description
This is the slave port of the communication monitor.
All recv functions call a function in MemCheckerMonitor, where the send function of the master port is called. Besides this, these functions can also perform actions for capturing statistics.
Definition at line 159 of file mem_checker_monitor.hh.
Constructor & Destructor Documentation
MemCheckerMonitor::MonitorSlavePort::MonitorSlavePort (const std::string & _name, MemCheckerMonitor & _mon) [inline]
Definition at line 164 of file mem_checker_monitor.hh.
Member Function Documentation
AddrRangeList MemCheckerMonitor::MonitorSlavePort::getAddrRanges () const [inline, protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 190 of file mem_checker_monitor.hh.
References MemCheckerMonitor::getAddrRanges(), and mon.
Tick MemCheckerMonitor::MonitorSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 175 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvAtomic().
void MemCheckerMonitor::MonitorSlavePort::recvFunctional (PacketPtr pkt) [inline, protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 170 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvFunctional().
void MemCheckerMonitor::MonitorSlavePort::recvRespRetry () [inline, protected, virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 195 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvRespRetry().
bool MemCheckerMonitor::MonitorSlavePort::recvTimingReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 180 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvTimingReq().
bool MemCheckerMonitor::MonitorSlavePort::recvTimingSnoopResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop response from the master port.
Reimplemented from SlavePort.
Definition at line 185 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvTimingSnoopResp().
Member Data Documentation
MemCheckerMonitor& MemCheckerMonitor::MonitorSlavePort::mon [private]
Definition at line 202 of file mem_checker_monitor.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvRespRetry(), recvTimingReq(), and recvTimingSnoopResp().
The documentation for this class was generated from the following file:
mem/mem_checker_monitor.hh