gem5: Event Class Reference
Event Class Reference
#include <eventq.hh>
Public Member Functions
Event (Priority p=Default_Pri, Flags f=0)
virtual ~Event ()
virtual const std::string name () const
virtual const char * description () const
Return a C string describing the event.
void dump () const
Dump the current event data.
virtual void process ()=0
bool scheduled () const
Determine if the current event is scheduled.
void squash ()
Squash the current event.
bool squashed () const
Check whether the event is squashed.
bool isExitEvent () const
See if this is a SimExitEvent (without resorting to RTTI).
Tick when () const
Get the time that the event is scheduled.
Priority priority () const
Get the event priority.
virtual BaseGlobalEvent * globalEvent ()
If this is part of a GlobalEvent, return the pointer to the Global Event.
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
virtual void unserialize (Checkpoint *cp, const std::string &section, EventQueue *eventq)
This function is required to support restoring from checkpoints when running with multiple queues.
Protected Member Functions
Flags getFlags () const
Accessor for flags.
bool isFlagSet (Flags _flags) const
void setFlags (Flags _flags)
Accessor for flags.
void clearFlags (Flags _flags)
void clearFlags ()
virtual void trace (const char *action)
trace event activity
Private Member Functions
void setWhen (Tick when, EventQueue *q)
bool initialized () const
Static Private Member Functions
static Event * insertBefore (Event *event, Event *curr)
static Event * removeItem (Event *event, Event *last)
Private Attributes
Event * nextBin
Event * nextInBin
Tick _when
timestamp when event should be processed
Priority _priority
event priority
Flags flags
Counter instance
This event's unique ID.
EventQueue * queue
queue to which this event belongs (though it may or may not be scheduled on this queue yet)
Static Private Attributes
static Counter instanceCounter = 0
Global counter to generate unique IDs for Event instances.
Friends
class EventQueue
Detailed Description
Definition at line 183 of file eventq.hh.
Constructor & Destructor Documentation
Event::Event (Priority p = Default_Pri, Flags f = 0) [inline]
Definition at line 290 of file eventq.hh.
References curTick(), ArmISA::f, instance, instanceCounter, EventBase::PublicWrite, and queue.
Referenced by DelayFunction().
Event::~Event () [virtual]
Definition at line 79 of file eventq.cc.
References flags, and scheduled().
Member Function Documentation
void Event::clearFlags () [inline, protected]
Definition at line 276 of file eventq.hh.
References Flags< T >::clear(), flags, and EventBase::PublicWrite.
void Event::clearFlags (Flags _flags) [inline, protected]
Definition at line 269 of file eventq.hh.
References Flags< T >::clear(), flags, Flags< T >::noneSet(), and EventBase::PublicWrite.
const char * Event::description () const [virtual]
Return a C string describing the event.
This string should not* be dynamically allocated; just a const char array describing the event class.
Reimplemented in MipsISA::ISA::CP0Event, BaseKvmCPU::TickEvent, DefaultCommit< Impl >::TrapEvent, FullO3CPU< Impl >::TickEvent, DefaultFetch< Impl >::FinishTranslationEvent, InstructionQueue< Impl >::FUCompletion, LSQUnit< Impl >::WritebackEvent, EndQuiesceEvent, AtomicSimpleCPU::TickEvent, TimingSimpleCPU::TimingCPUPort::TickEvent, TimingSimpleCPU::IcachePort::ITickEvent, TimingSimpleCPU::IprEvent, RubyDirectedTester::DirectedStartEvent, NetworkTest::TickEvent, RubyTester::CheckStartEvent, Pl390::PostIntEvent, VGic::PostVIntEvent, EtherBus::DoneEvent, EtherTap::TxEvent, Intel8254Timer::Counter::CounterEvent, MC146818::RTCEvent, MC146818::RTCTickEvent, Uart8250::IntrEvent, FLIP::UpdatePriorityEvent, Sequencer::SequencerWakeupEvent, EventWrapper< T, F >, LocalSimLoopExitEvent, CountedExitEvent, EventWrapper< EnergyCtrl,&EnergyCtrl::updatePLAck >, EventWrapper< IGbE,&IGbE::tidvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::writeDone >, EventWrapper< TableWalker,&TableWalker::doL2LongDescriptorWrapper >, EventWrapper< TableWalker,&TableWalker::doL0LongDescriptorWrapper >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshotCycle >, EventWrapper< MemTest,&MemTest::tick >, EventWrapper< TxDescCache,&TxDescCache::nullCallback >, EventWrapper< NSGigE,&NSGigE::txEventTransmit >, EventWrapper< UFSHostDevice,&UFSHostDevice::taskStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::readGarbage >, EventWrapper< SimpleMemory,&SimpleMemory::release >, EventWrapper< PL031,&PL031::counterMatch >, EventWrapper< Timer,&Timer::watchdogAtZero >, EventWrapper< Rank,&Rank::processRefreshEvent >, EventWrapper< TableWalker,&TableWalker::doL3LongDescriptorWrapper >, EventWrapper< DescCache,&DescCache::wbComplete >, EventWrapper< MasterPort,&MasterPort::sendRetryResp >, EventWrapper< Pl011,&Pl011::generateInterrupt >, EventWrapper< DRAMSim2,&DRAMSim2::sendResponse >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::finalizeSnapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer >, EventWrapper< MemTest,&MemTest::noRequest >, EventWrapper< ArchTimer,&ArchTimer::counterLimitReached >, EventWrapper< TxDescCache,&TxDescCache::pktComplete >, EventWrapper< DescCache,&DescCache::writeback1 >, EventWrapper< Rank,&Rank::processPowerEvent >, EventWrapper< TableWalker,&TableWalker::doL1LongDescriptorWrapper >, EventWrapper< IdeDisk,&IdeDisk::dmaReadDone >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeCopyBytesComplete >, EventWrapper< DmaPort,&DmaPort::sendDma >, EventWrapper< Timer,&Timer::counterAtZero >, EventWrapper< TableWalker,&TableWalker::doL1DescriptorWrapper >, EventWrapper< CommMonitor,&CommMonitor::samplePeriodic >, EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone >, EventWrapper< UFSHostDevice,&UFSHostDevice::transferStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::SCSIStart >, EventWrapper< Pl050,&Pl050::generateInterrupt >, EventWrapper< Device,&Device::txEventTransmit >, EventWrapper< HDLcd,&HDLcd::startFrame >, EventWrapper< Rank,&Rank::processPrechargeEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeStatusComplete >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::readCopyBytesComplete >, EventWrapper< IGbE,&IGbE::delayIntEvent >, EventWrapper< NSGigE,&NSGigE::rxDmaWriteDone >, EventWrapper< Pl111,&Pl111::fillFifo >, EventWrapper< DRAMSim2,&DRAMSim2::tick >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaWrite >, EventWrapper< DRAMCtrl,&DRAMCtrl::processNextReqEvent >, EventWrapper< RxDescCache,&RxDescCache::pktSplitDone >, EventWrapper< IGbE,&IGbE::radvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::finalUTP >, EventWrapper< HDLcd,&HDLcd::generateInterrupt >, EventWrapper< TableWalker,&TableWalker::doL2DescriptorWrapper >, EventWrapper< Link,&Link::txDone >, EventWrapper< IdeDisk,&IdeDisk::doDmaRead >, EventWrapper< DRAMCtrl,&DRAMCtrl::processRespondEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchDescComplete >, EventWrapper< Walker,&Walker::startWalkWrapper >, EventWrapper< IGbE,&IGbE::tadvProcess >, EventWrapper< NSGigE,&NSGigE::rxKick >, EventWrapper< SimpleMemory,&SimpleMemory::dequeue >, EventWrapper< Layer,&Layer::releaseLayer >, EventWrapper< TrafficGen,&TrafficGen::update >, EventWrapper< NSGigE,&NSGigE::txKick >, EventWrapper< HDLcd,&HDLcd::renderPixel >, EventWrapper< HDLcd,&HDLcd::endFrame >, EventWrapper< TableWalker,&TableWalker::processWalkWrapper >, EventWrapper< DescCache,&DescCache::fetchDescriptors1 >, EventWrapper< IGbE,&IGbE::tick >, EventWrapper< NSGigE,&NSGigE::txDmaWriteDone >, EventWrapper< NSGigE,&NSGigE::rxDmaReadDone >, EventWrapper< HDLcd,&HDLcd::fillPixelBuffer >, EventWrapper< Rank,&Rank::processActivateEvent >, EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone >, EventWrapper< BridgeSlavePort,&BridgeSlavePort::trySendTiming >, EventWrapper< TimingSimpleCPU,&TimingSimpleCPU::fetch >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchAddrComplete >, EventWrapper< UFSHostDevice,&UFSHostDevice::readDone >, EventWrapper< Device,&Device::txDmaDone >, EventWrapper< CacheSlavePort,&CacheSlavePort::processSendRetry >, EventWrapper< MemTest,&MemTest::noResponse >, EventWrapper< BridgeMasterPort,&BridgeMasterPort::trySendTiming >, EventWrapper< IGbE,&IGbE::rdtrProcess >, EventWrapper< NSGigE,&NSGigE::txDmaReadDone >, EventWrapper< Pl111,&Pl111::generateInterrupt >, EventWrapper< Timer,&Timer::timerAtZero >, EventWrapper< RxDescCache,&RxDescCache::pktComplete >, EventWrapper< TxDescCache,&TxDescCache::headerComplete >, EventWrapper< Root,&Root::timeSync >, EventWrapper< Pl111,&Pl111::readFramebuffer >, EventWrapper< Device,&Device::rxDmaDone >, EventWrapper< FlashDevice,&FlashDevice::actionComplete >, EventWrapper< PacketQueue,&PacketQueue::processSendEvent >, and EventWrapper< DescCache,&DescCache::fetchComplete >.
Definition at line 424 of file eventq.cc.
Referenced by DelayFunction(), dump(), and trace().
void Event::dump () const
Dump the current event data.
Definition at line 445 of file eventq.cc.
References _priority, cprintf(), description(), flags, name(), scheduled(), and when().
Referenced by EventQueue::debugVerify(), EventQueue::dump(), and DVFSHandler::UpdateEvent::updatePerfLevel().
Flags Event::getFlags () const [inline, protected]
Accessor for flags.
Definition at line 248 of file eventq.hh.
References flags, and EventBase::PublicRead.
virtual BaseGlobalEvent* Event::globalEvent () [inline, virtual]
If this is part of a GlobalEvent, return the pointer to the Global Event.
By default, there is no GlobalEvent, so return NULL. (Overridden in GlobalEvent::BarrierEvent.)
Reimplemented in BaseGlobalEvent::BarrierEvent.
Definition at line 350 of file eventq.hh.
Referenced by simulate().
bool Event::initialized () const [inline, private]
Definition at line 240 of file eventq.hh.
References flags, EventBase::Initialized, and EventBase::InitMask.
Referenced by EventQueue::deschedule(), EventQueue::reschedule(), and EventQueue::schedule().
Event * Event::insertBefore (Event * event, Event * curr) [static, private]
Definition at line 97 of file eventq.cc.
References nextBin, and nextInBin.
Referenced by EventQueue::insert().
bool Event::isExitEvent () const [inline]
See if this is a SimExitEvent (without resorting to RTTI).
Definition at line 339 of file eventq.hh.
References flags, EventBase::IsExitEvent, and Flags< T >::isSet().
bool Event::isFlagSet (Flags _flags) const [inline, protected]
Definition at line 254 of file eventq.hh.
References flags, Flags< T >::isSet(), Flags< T >::noneSet(), and EventBase::PublicRead.
Referenced by BaseGlobalEvent::BarrierEvent::~BarrierEvent().
const std::string Event::name () const [virtual]
Implements Serializable.
Reimplemented in HDLcd::DmaDoneEvent, EventWrapper< T, F >, EventWrapper< EnergyCtrl,&EnergyCtrl::updatePLAck >, EventWrapper< IGbE,&IGbE::tidvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::writeDone >, EventWrapper< TableWalker,&TableWalker::doL2LongDescriptorWrapper >, EventWrapper< TableWalker,&TableWalker::doL0LongDescriptorWrapper >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshotCycle >, EventWrapper< MemTest,&MemTest::tick >, EventWrapper< TxDescCache,&TxDescCache::nullCallback >, EventWrapper< NSGigE,&NSGigE::txEventTransmit >, EventWrapper< UFSHostDevice,&UFSHostDevice::taskStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::readGarbage >, EventWrapper< SimpleMemory,&SimpleMemory::release >, EventWrapper< PL031,&PL031::counterMatch >, EventWrapper< Timer,&Timer::watchdogAtZero >, EventWrapper< Rank,&Rank::processRefreshEvent >, EventWrapper< TableWalker,&TableWalker::doL3LongDescriptorWrapper >, EventWrapper< DescCache,&DescCache::wbComplete >, EventWrapper< MasterPort,&MasterPort::sendRetryResp >, EventWrapper< Pl011,&Pl011::generateInterrupt >, EventWrapper< DRAMSim2,&DRAMSim2::sendResponse >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::finalizeSnapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer >, EventWrapper< MemTest,&MemTest::noRequest >, EventWrapper< ArchTimer,&ArchTimer::counterLimitReached >, EventWrapper< TxDescCache,&TxDescCache::pktComplete >, EventWrapper< DescCache,&DescCache::writeback1 >, EventWrapper< Rank,&Rank::processPowerEvent >, EventWrapper< TableWalker,&TableWalker::doL1LongDescriptorWrapper >, EventWrapper< IdeDisk,&IdeDisk::dmaReadDone >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeCopyBytesComplete >, EventWrapper< DmaPort,&DmaPort::sendDma >, EventWrapper< Timer,&Timer::counterAtZero >, EventWrapper< TableWalker,&TableWalker::doL1DescriptorWrapper >, EventWrapper< CommMonitor,&CommMonitor::samplePeriodic >, EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone >, EventWrapper< UFSHostDevice,&UFSHostDevice::transferStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::SCSIStart >, EventWrapper< Pl050,&Pl050::generateInterrupt >, EventWrapper< Device,&Device::txEventTransmit >, EventWrapper< HDLcd,&HDLcd::startFrame >, EventWrapper< Rank,&Rank::processPrechargeEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeStatusComplete >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::readCopyBytesComplete >, EventWrapper< IGbE,&IGbE::delayIntEvent >, EventWrapper< NSGigE,&NSGigE::rxDmaWriteDone >, EventWrapper< Pl111,&Pl111::fillFifo >, EventWrapper< DRAMSim2,&DRAMSim2::tick >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaWrite >, EventWrapper< DRAMCtrl,&DRAMCtrl::processNextReqEvent >, EventWrapper< RxDescCache,&RxDescCache::pktSplitDone >, EventWrapper< IGbE,&IGbE::radvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::finalUTP >, EventWrapper< HDLcd,&HDLcd::generateInterrupt >, EventWrapper< TableWalker,&TableWalker::doL2DescriptorWrapper >, EventWrapper< Link,&Link::txDone >, EventWrapper< IdeDisk,&IdeDisk::doDmaRead >, EventWrapper< DRAMCtrl,&DRAMCtrl::processRespondEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchDescComplete >, EventWrapper< Walker,&Walker::startWalkWrapper >, EventWrapper< IGbE,&IGbE::tadvProcess >, EventWrapper< NSGigE,&NSGigE::rxKick >, EventWrapper< SimpleMemory,&SimpleMemory::dequeue >, EventWrapper< Layer,&Layer::releaseLayer >, EventWrapper< TrafficGen,&TrafficGen::update >, EventWrapper< NSGigE,&NSGigE::txKick >, EventWrapper< HDLcd,&HDLcd::renderPixel >, EventWrapper< HDLcd,&HDLcd::endFrame >, EventWrapper< TableWalker,&TableWalker::processWalkWrapper >, EventWrapper< DescCache,&DescCache::fetchDescriptors1 >, EventWrapper< IGbE,&IGbE::tick >, EventWrapper< NSGigE,&NSGigE::txDmaWriteDone >, EventWrapper< NSGigE,&NSGigE::rxDmaReadDone >, EventWrapper< HDLcd,&HDLcd::fillPixelBuffer >, EventWrapper< Rank,&Rank::processActivateEvent >, EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone >, EventWrapper< BridgeSlavePort,&BridgeSlavePort::trySendTiming >, EventWrapper< TimingSimpleCPU,&TimingSimpleCPU::fetch >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchAddrComplete >, EventWrapper< UFSHostDevice,&UFSHostDevice::readDone >, EventWrapper< Device,&Device::txDmaDone >, EventWrapper< CacheSlavePort,&CacheSlavePort::processSendRetry >, EventWrapper< MemTest,&MemTest::noResponse >, EventWrapper< BridgeMasterPort,&BridgeMasterPort::trySendTiming >, EventWrapper< IGbE,&IGbE::rdtrProcess >, EventWrapper< NSGigE,&NSGigE::txDmaReadDone >, EventWrapper< Pl111,&Pl111::generateInterrupt >, EventWrapper< Timer,&Timer::timerAtZero >, EventWrapper< RxDescCache,&RxDescCache::pktComplete >, EventWrapper< TxDescCache,&TxDescCache::headerComplete >, EventWrapper< Root,&Root::timeSync >, EventWrapper< Pl111,&Pl111::readFramebuffer >, EventWrapper< Device,&Device::rxDmaDone >, EventWrapper< FlashDevice,&FlashDevice::actionComplete >, EventWrapper< PacketQueue,&PacketQueue::processSendEvent >, and EventWrapper< DescCache,&DescCache::fetchComplete >.
Definition at line 86 of file eventq.cc.
References csprintf(), and instance.
Referenced by dump().
Priority Event::priority () const [inline]
Get the event priority.
Definition at line 345 of file eventq.hh.
References _priority.
Referenced by EventQueue::debugVerify(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
virtual void Event::process () [pure virtual]
Implemented in MipsISA::ISA::CP0Event, BaseRemoteGDB::TrapEvent, BaseRemoteGDB::SingleStepEvent, CpuEventWrapper< T, F >, BaseKvmCPU::TickEvent, Minor::LSQ::SplitDataRequest::TranslationEvent, DefaultCommit< Impl >::TrapEvent, FullO3CPU< Impl >::TickEvent, DefaultFetch< Impl >::FinishTranslationEvent, InstructionQueue< Impl >::FUCompletion, LSQUnit< Impl >::WritebackEvent, EndQuiesceEvent, AtomicSimpleCPU::TickEvent, TimingSimpleCPU::IcachePort::ITickEvent, TimingSimpleCPU::IprEvent, RubyDirectedTester::DirectedStartEvent, NetworkTest::TickEvent, RubyTester::CheckStartEvent, Pl390::PostIntEvent, HDLcd::DmaDoneEvent, VGic::PostVIntEvent, EtherBus::DoneEvent, LinkDelayEvent, EtherTap::TxEvent, Intel8254Timer::Counter::CounterEvent, MC146818::RTCEvent, MC146818::RTCTickEvent, Uart8250::IntrEvent, FLIP::UpdatePriorityEvent, FLIPProfiler::SamplingEvent, LRUProfiler::SamplingEvent, StubSlavePort::ResponseEvent, Consumer::ConsumerEvent, RubyMemoryControl::MemCntrlEvent, Sequencer::SequencerWakeupEvent, RubySystem::RubyEvent, PythonEvent, DVFSHandler::UpdateEvent, EventWrapper< T, F >, GlobalEvent::BarrierEvent, GlobalSyncEvent::BarrierEvent, LocalSimLoopExitEvent, CountedDrainEvent, CountedExitEvent, Ticked::ClockEvent, EventWrapper< EnergyCtrl,&EnergyCtrl::updatePLAck >, EventWrapper< IGbE,&IGbE::tidvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::writeDone >, EventWrapper< TableWalker,&TableWalker::doL2LongDescriptorWrapper >, EventWrapper< TableWalker,&TableWalker::doL0LongDescriptorWrapper >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshotCycle >, EventWrapper< MemTest,&MemTest::tick >, EventWrapper< TxDescCache,&TxDescCache::nullCallback >, EventWrapper< NSGigE,&NSGigE::txEventTransmit >, EventWrapper< UFSHostDevice,&UFSHostDevice::taskStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::readGarbage >, EventWrapper< SimpleMemory,&SimpleMemory::release >, EventWrapper< PL031,&PL031::counterMatch >, EventWrapper< Timer,&Timer::watchdogAtZero >, EventWrapper< Rank,&Rank::processRefreshEvent >, EventWrapper< TableWalker,&TableWalker::doL3LongDescriptorWrapper >, EventWrapper< DescCache,&DescCache::wbComplete >, EventWrapper< MasterPort,&MasterPort::sendRetryResp >, EventWrapper< Pl011,&Pl011::generateInterrupt >, EventWrapper< DRAMSim2,&DRAMSim2::sendResponse >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::finalizeSnapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer >, EventWrapper< MemTest,&MemTest::noRequest >, EventWrapper< ArchTimer,&ArchTimer::counterLimitReached >, EventWrapper< TxDescCache,&TxDescCache::pktComplete >, EventWrapper< DescCache,&DescCache::writeback1 >, EventWrapper< Rank,&Rank::processPowerEvent >, EventWrapper< TableWalker,&TableWalker::doL1LongDescriptorWrapper >, EventWrapper< IdeDisk,&IdeDisk::dmaReadDone >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeCopyBytesComplete >, EventWrapper< DmaPort,&DmaPort::sendDma >, EventWrapper< Timer,&Timer::counterAtZero >, EventWrapper< TableWalker,&TableWalker::doL1DescriptorWrapper >, EventWrapper< CommMonitor,&CommMonitor::samplePeriodic >, EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone >, EventWrapper< UFSHostDevice,&UFSHostDevice::transferStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::SCSIStart >, EventWrapper< Pl050,&Pl050::generateInterrupt >, EventWrapper< Device,&Device::txEventTransmit >, EventWrapper< HDLcd,&HDLcd::startFrame >, EventWrapper< Rank,&Rank::processPrechargeEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeStatusComplete >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::readCopyBytesComplete >, EventWrapper< IGbE,&IGbE::delayIntEvent >, EventWrapper< NSGigE,&NSGigE::rxDmaWriteDone >, EventWrapper< Pl111,&Pl111::fillFifo >, EventWrapper< DRAMSim2,&DRAMSim2::tick >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaWrite >, EventWrapper< DRAMCtrl,&DRAMCtrl::processNextReqEvent >, EventWrapper< RxDescCache,&RxDescCache::pktSplitDone >, EventWrapper< IGbE,&IGbE::radvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::finalUTP >, EventWrapper< HDLcd,&HDLcd::generateInterrupt >, EventWrapper< TableWalker,&TableWalker::doL2DescriptorWrapper >, EventWrapper< Link,&Link::txDone >, EventWrapper< IdeDisk,&IdeDisk::doDmaRead >, EventWrapper< DRAMCtrl,&DRAMCtrl::processRespondEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchDescComplete >, EventWrapper< Walker,&Walker::startWalkWrapper >, EventWrapper< IGbE,&IGbE::tadvProcess >, EventWrapper< NSGigE,&NSGigE::rxKick >, EventWrapper< SimpleMemory,&SimpleMemory::dequeue >, EventWrapper< Layer,&Layer::releaseLayer >, EventWrapper< TrafficGen,&TrafficGen::update >, EventWrapper< NSGigE,&NSGigE::txKick >, EventWrapper< HDLcd,&HDLcd::renderPixel >, EventWrapper< HDLcd,&HDLcd::endFrame >, EventWrapper< TableWalker,&TableWalker::processWalkWrapper >, EventWrapper< DescCache,&DescCache::fetchDescriptors1 >, EventWrapper< IGbE,&IGbE::tick >, EventWrapper< NSGigE,&NSGigE::txDmaWriteDone >, EventWrapper< NSGigE,&NSGigE::rxDmaReadDone >, EventWrapper< HDLcd,&HDLcd::fillPixelBuffer >, EventWrapper< Rank,&Rank::processActivateEvent >, EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone >, EventWrapper< BridgeSlavePort,&BridgeSlavePort::trySendTiming >, EventWrapper< TimingSimpleCPU,&TimingSimpleCPU::fetch >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchAddrComplete >, EventWrapper< UFSHostDevice,&UFSHostDevice::readDone >, EventWrapper< Device,&Device::txDmaDone >, EventWrapper< CacheSlavePort,&CacheSlavePort::processSendRetry >, EventWrapper< MemTest,&MemTest::noResponse >, EventWrapper< BridgeMasterPort,&BridgeMasterPort::trySendTiming >, EventWrapper< IGbE,&IGbE::rdtrProcess >, EventWrapper< NSGigE,&NSGigE::txDmaReadDone >, EventWrapper< Pl111,&Pl111::generateInterrupt >, EventWrapper< Timer,&Timer::timerAtZero >, EventWrapper< RxDescCache,&RxDescCache::pktComplete >, EventWrapper< TxDescCache,&TxDescCache::headerComplete >, EventWrapper< Root,&Root::timeSync >, EventWrapper< Pl111,&Pl111::readFramebuffer >, EventWrapper< Device,&Device::rxDmaDone >, EventWrapper< FlashDevice,&FlashDevice::actionComplete >, EventWrapper< PacketQueue,&PacketQueue::processSendEvent >, and EventWrapper< DescCache,&DescCache::fetchComplete >.
Referenced by DelayFunction().
Event * Event::removeItem (Event * event, Event * last) [static, private]
Definition at line 141 of file eventq.cc.
References nextBin, nextInBin, and panic.
Referenced by EventQueue::remove().
bool Event::scheduled () const [inline]
Determine if the current event is scheduled.
Definition at line 330 of file eventq.hh.
References flags, Flags< T >::isSet(), and EventBase::Scheduled.
Referenced by DRAMSim2::accessAndRespond(), FlashDevice::accessDevice(), DRAMCtrl::activateBank(), AtomicSimpleCPU::activateContext(), BaseKvmCPU::activateContext(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), IGbE::chkInterrupt(), Intel8254Timer::Counter::CounterEvent::clocksLeft(), IGbE::cpuPostInt(), EventQueue::deschedule(), BaseRemoteGDB::descheduleInstCommitEvent(), DmaPort::dmaAction(), Pl111::dmaDone(), HDLcd::dmaDone(), RubyMemoryControl::drain(), DRAMCtrl::drain(), IGbE::drain(), FlashDevice::drain(), TrafficGen::drain(), TimingSimpleCPU::drain(), AtomicSimpleCPU::drain(), FullO3CPU< Impl >::drain(), BaseKvmCPU::drain(), TimingSimpleCPU::drainResume(), AtomicSimpleCPU::drainResume(), FullO3CPU< Impl >::drainResume(), BaseKvmCPU::drainResume(), dump(), RubyMemoryControl::enqueueMemRef(), IGbE::ethRxPkt(), IGbE::DescCache< T >::fetchDescriptors(), Minor::LSQ::SplitDataRequest::finish(), DefaultFetch< Impl >::finishTranslation(), IGbE::DescCache< iGbReg::RxDesc >::hasOutstandingEvents(), IGbE::TxDescCache::hasOutstandingEvents(), IGbE::RxDescCache::hasOutstandingEvents(), Sequencer::insertRequest(), Sequencer::isDeadlockEventScheduled(), TimingSimpleCPU::isDrained(), DefaultFetch< Impl >::isDrained(), RubyMemoryControl::issueRequest(), DVFSHandler::perfLevel(), IGbE::TxDescCache::pktComplete(), IGbE::RxDescCache::pktComplete(), IGbE::postInterrupt(), DRAMCtrl::prechargeBank(), EtherTap::process(), BaseRemoteGDB::SingleStepEvent::process(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::Rank::processPowerEvent(), DRAMCtrl::Rank::processRefreshEvent(), DRAMCtrl::processRespondEvent(), UFSHostDevice::readDevice(), Pl111::readFramebuffer(), SimpleMemory::recvTimingReq(), TimingSimpleCPU::DcachePort::recvTimingResp(), TimingSimpleCPU::IcachePort::recvTimingResp(), X86ISA::Walker::recvTimingResp(), BaseXBar::Layer< SrcType, DstType >::releaseLayer(), HDLcd::renderPixel(), EventQueue::reschedule(), IGbE::restartClock(), Sp804::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), CpuLocalTimer::Timer::restartWatchdogCounter(), PL031::resyncMatch(), EtherTap::retransmit(), NSGigE::rxKick(), PacketQueue::schedSendEvent(), EventQueue::schedule(), Uart8250::IntrEvent::scheduleIntr(), DRAMCtrl::Rank::schedulePowerEvent(), FullO3CPU< O3CPUImpl >::scheduleTickEvent(), FLIP::scheduleUpdatePriorityEvent(), DmaPort::sendDma(), DRAMSim2::sendResponse(), Sinic::Device::serialize(), IGbE::serialize(), IGbE::DescCache< T >::serialize(), Sp804::Timer::serialize(), CpuLocalTimer::Timer::serialize(), PL031::serialize(), Pl111::serialize(), HDLcd::serialize(), ArchTimer::serialize(), EnergyCtrl::serialize(), ThreadState::serialize(), SparcISA::ISA::serialize(), BaseCache::CacheSlavePort::setBlocked(), SparcISA::ISA::setFSReg(), Pl011::setInterrupts(), BaseRemoteGDB::setSingleStep(), Ticked::start(), Pl111::startDma(), HDLcd::startFrame(), MC146818::startup(), Ticked::stop(), AtomicSimpleCPU::suspendContext(), BaseKvmCPU::suspendContext(), TimingSimpleCPU::switchOut(), AtomicSimpleCPU::switchOut(), BaseKvmCPU::switchOut(), AtomicSimpleCPU::takeOverFrom(), FullO3CPU< Impl >::takeOverFrom(), BaseKvmCPU::takeOverFrom(), NetworkTest::tick(), FullO3CPU< Impl >::tick(), UFSHostDevice::transferHandler(), NSGigE::transmit(), FullO3CPU< Impl >::tryDrain(), NSGigE::txKick(), MipsISA::ISA::CP0Event::unscheduleEvent(), FullO3CPU< O3CPUImpl >::unscheduleTickEvent(), ArchTimer::updateCounter(), Pl050::updateIntStatus(), FullO3CPU< Impl >::wakeCPU(), RubyMemoryControl::wakeup(), Uart8250::write(), Intel8254Timer::Counter::write(), EnergyCtrl::write(), IGbE::DescCache< T >::writeback(), MC146818::writeData(), UFSHostDevice::writeDevice(), AtomicSimpleCPU::~AtomicSimpleCPU(), and ~Event().
void Event::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Reimplemented in LocalSimLoopExitEvent.
Definition at line 245 of file eventq.cc.
References _priority, _when, flags, and SERIALIZE_SCALAR.
void Event::setFlags (Flags _flags) [inline, protected]
Accessor for flags.
Definition at line 262 of file eventq.hh.
References flags, Flags< T >::noneSet(), EventBase::PublicWrite, and Flags< T >::set().
Referenced by EventWrapper< DescCache,&DescCache::fetchComplete >::EventWrapper().
void Event::setWhen (Tick when, EventQueue * q) [inline, private]
Definition at line 228 of file eventq.hh.
References _when, curTick(), and queue.
void Event::squash () [inline]
Squash the current event.
Definition at line 333 of file eventq.hh.
References flags, Flags< T >::set(), and EventBase::Squashed.
Referenced by Sinic::Base::cpuIntrClear(), NSGigE::cpuIntrClear(), Sinic::Base::cpuIntrPost(), NSGigE::cpuIntrPost(), MipsISA::ISA::CP0Event::unscheduleEvent(), and FullO3CPU< O3CPUImpl >::unscheduleTickEvent().
bool Event::squashed () const [inline]
Check whether the event is squashed.
Definition at line 336 of file eventq.hh.
References flags, Flags< T >::isSet(), and EventBase::Squashed.
Referenced by FullO3CPU< O3CPUImpl >::scheduleTickEvent(), and FLIP::scheduleUpdatePriorityEvent().
void Event::trace (const char * action) [protected, virtual]
trace event activity
Definition at line 430 of file eventq.cc.
References description(), DPRINTFN, and when().
virtual void Event::unserialize (Checkpoint * cp, const std::string & section, EventQueue * eventq) [virtual]
This function is required to support restoring from checkpoints when running with multiple queues.
Since we still have not thrashed out all the details on checkpointing, this function is most likely to be revisited in future.
Reimplemented in LocalSimLoopExitEvent.
virtual void Event::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Reimplemented in LocalSimLoopExitEvent.
Tick Event::when () const [inline]
Get the time that the event is scheduled.
Definition at line 342 of file eventq.hh.
References _when.
Referenced by FlashDevice::accessDevice(), FlashDevice::actionComplete(), DRAMCtrl::activateBank(), FlashDevice::checkDrain(), Intel8254Timer::Counter::CounterEvent::clocksLeft(), EventQueue::debugVerify(), dump(), EventQueue::nextTick(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), DRAMCtrl::prechargeBank(), Sp804::Timer::read(), CpuLocalTimer::Timer::read(), PacketQueue::schedSendEvent(), DRAMCtrl::Rank::schedulePowerEvent(), Sinic::Device::serialize(), Sinic::Base::serialize(), IGbE::serialize(), IGbE::DescCache< T >::serialize(), VGic::serialize(), Sp804::Timer::serialize(), CpuLocalTimer::Timer::serialize(), PL031::serialize(), Pl111::serialize(), HDLcd::serialize(), Pl390::serialize(), ArchTimer::serialize(), EnergyCtrl::serialize(), ThreadState::serialize(), SparcISA::ISA::serialize(), and trace().
Friends And Related Function Documentation
friend class EventQueue [friend]
Definition at line 185 of file eventq.hh.
Member Data Documentation
Priority Event::_priority [private]
event priority
Definition at line 204 of file eventq.hh.
Referenced by dump(), priority(), and serialize().
Tick Event::_when [private]
timestamp when event should be processed
Definition at line 203 of file eventq.hh.
Referenced by serialize(), setWhen(), and when().
Flags Event::flags [private]
Definition at line 205 of file eventq.hh.
Referenced by clearFlags(), EventQueue::deschedule(), dump(), getFlags(), initialized(), isExitEvent(), isFlagSet(), scheduled(), serialize(), EventQueue::serviceOne(), setFlags(), squash(), squashed(), and ~Event().
Counter Event::instance [private]
This event's unique ID.
We can also use pointer values for this but they're not consistent across runs making debugging more difficult. Thus we use a global counter value when debugging.
Definition at line 215 of file eventq.hh.
Referenced by Event(), and name().
Counter Event::instanceCounter = 0 [static, private]
Global counter to generate unique IDs for Event instances.
Definition at line 209 of file eventq.hh.
Referenced by Event().
Event* Event::nextBin [private]
Definition at line 197 of file eventq.hh.
Referenced by EventQueue::debugVerify(), EventQueue::dump(), EventQueue::insert(), insertBefore(), EventQueue::remove(), removeItem(), and EventQueue::serviceOne().
Event* Event::nextInBin [private]
Definition at line 198 of file eventq.hh.
Referenced by EventQueue::debugVerify(), EventQueue::dump(), insertBefore(), removeItem(), and EventQueue::serviceOne().
EventQueue* Event::queue [private]
queue to which this event belongs (though it may or may not be scheduled on this queue yet)
Definition at line 219 of file eventq.hh.
Referenced by Event(), EventQueue::remove(), and setWhen().
The documentation for this class was generated from the following files:
sim/eventq.hh
sim/eventq.cc