gem5: SnapMemCtrl::SnapMemCtrlMasterPort Class Reference
SnapMemCtrl::SnapMemCtrlMasterPort Class Reference
#include <snap_mem_ctrl.hh>
Public Member Functions
SnapMemCtrlMasterPort (const std::string &_name, SnapMemCtrl *ctrl)
virtual bool isSnooping () const
Determine if this master port is snooping or not.
Protected Member Functions
virtual AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
virtual void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
virtual void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the slave port.
virtual Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from the slave port.
Protected Attributes
SnapMemCtrl * ctrl
Private Attributes
MasterPacketQueue queue
Detailed Description
Definition at line 39 of file snap_mem_ctrl.hh.
Constructor & Destructor Documentation
SnapMemCtrl::SnapMemCtrlMasterPort::SnapMemCtrlMasterPort (const std::string & _name, SnapMemCtrl * ctrl)
Definition at line 5 of file snap_mem_ctrl.cc.
Member Function Documentation
AddrRangeList SnapMemCtrl::SnapMemCtrlMasterPort::getAddrRanges () const [protected, virtual]
Get the address ranges of the connected slave port.
Reimplemented from MasterPort.
Definition at line 11 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::getAddrRanges().
virtual bool SnapMemCtrl::SnapMemCtrlMasterPort::isSnooping () const [inline, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented from MasterPort.
Reimplemented in SnapMemCtrl::SnapMemCtrlMasterSnapPort.
Definition at line 50 of file snap_mem_ctrl.hh.
Tick SnapMemCtrl::SnapMemCtrlMasterPort::recvAtomicSnoop (PacketPtr pkt) [protected, virtual]
Receive an atomic snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 31 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvAtomicSnoop().
void SnapMemCtrl::SnapMemCtrlMasterPort::recvFunctionalSnoop (PacketPtr pkt) [protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 21 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvFunctionalSnoop().
bool SnapMemCtrl::SnapMemCtrlMasterPort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Reimplemented in SnapMemCtrl::SnapMemCtrlMasterSnapPort.
Definition at line 16 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvTimingResp().
void SnapMemCtrl::SnapMemCtrlMasterPort::recvTimingSnoopReq (PacketPtr pkt) [protected, virtual]
Receive a timing snoop request from the slave port.
Reimplemented from MasterPort.
Definition at line 26 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvTimingSnoopReq().
Member Data Documentation
SnapMemCtrl* SnapMemCtrl::SnapMemCtrlMasterPort::ctrl [protected]
Definition at line 42 of file snap_mem_ctrl.hh.
Referenced by getAddrRanges(), recvAtomicSnoop(), recvFunctionalSnoop(), SnapMemCtrl::SnapMemCtrlMasterSnapPort::recvTimingResp(), recvTimingResp(), and recvTimingSnoopReq().
MasterPacketQueue SnapMemCtrl::SnapMemCtrlMasterPort::queue [private]
Definition at line 40 of file snap_mem_ctrl.hh.
The documentation for this class was generated from the following files:
mem/snapmem/snap_mem_ctrl.hh
mem/snapmem/snap_mem_ctrl.cc