gem5: BaseRemoteGDB::SingleStepEvent Class Reference
BaseRemoteGDB::SingleStepEvent Class Reference
#include <remote_gdb.hh>
Public Member Functions
SingleStepEvent (BaseRemoteGDB *g)
void process ()
Protected Attributes
BaseRemoteGDB * gdb
Detailed Description
Definition at line 212 of file remote_gdb.hh.
Constructor & Destructor Documentation
BaseRemoteGDB::SingleStepEvent::SingleStepEvent (BaseRemoteGDB * g) [inline]
Definition at line 218 of file remote_gdb.hh.
Member Function Documentation
void BaseRemoteGDB::SingleStepEvent::process () [virtual]
Implements Event.
Definition at line 266 of file remote_gdb.cc.
References gdb, Event::scheduled(), BaseRemoteGDB::scheduleInstCommitEvent(), BaseRemoteGDB::singleStepEvent, and BaseRemoteGDB::trap().
Member Data Documentation
BaseRemoteGDB* BaseRemoteGDB::SingleStepEvent::gdb [protected]
Definition at line 215 of file remote_gdb.hh.
Referenced by process().
The documentation for this class was generated from the following files:
base/remote_gdb.hh
base/remote_gdb.cc