gem5: ArmISA::TableWalker::LongDescriptor Class Reference
ArmISA::TableWalker::LongDescriptor Class Reference
Long-descriptor format (LPAE).
#include <table_walker.hh>
Public Types
enum EntryType { Invalid, Table, Block, Page }
Descriptor type.
Public Member Functions
virtual uint64_t getRawData () const
virtual std::string dbgHeader () const
bool secure (bool have_security, WalkerState *currState) const
Returns true if this entry targets the secure physical address map.
EntryType type () const
Return the descriptor type.
uint8_t offsetBits () const
Return the bit width of the page/block offset.
Addr pfn () const
Return the physical frame, bits shifted right.
Addr paddr (Addr va) const
Return the complete physical address given a VA.
Addr paddr () const
Return the physical address of the entry.
Addr nextTableAddr () const
Return the address of the next page table.
Addr nextDescAddr (Addr va) const
Return the address of the next descriptor.
bool xn () const
Is execution allowed on this mapping?
bool pxn () const
Is privileged execution allowed on this mapping? (LPAE only).
bool contiguousHint () const
Contiguous hint bit.
bool global (WalkerState *currState) const
Is the translation global (no asid used)?
bool af () const
Returns true if the access flag (AF) is set.
uint8_t sh () const
2-bit shareability field
uint8_t ap () const
2-bit access protection flags
bool rw () const
Read/write access protection flag.
bool user () const
User/privileged level access protection flag.
TlbEntry::DomainType domain () const
uint8_t attrIndx () const
Attribute index.
uint8_t memAttr () const
Memory attributes, only used by stage 2 translations.
void setAf ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
bool secureTable () const
Whether the subsequent levels of lookup are secure.
uint8_t apTable () const
Two bit access protection flags for subsequent levels of lookup.
uint8_t rwTable () const
R/W protection flag for subsequent levels of lookup.
uint8_t userTable () const
User/privileged mode protection flag for subsequent levels of lookup.
bool xnTable () const
Is execution allowed on subsequent lookup levels?
bool pxnTable () const
Is privileged execution allowed on subsequent lookup levels?
Static Public Member Functions
static uint8_t ap (bool rw, bool user)
Return the AP bits as compatible with the AP[2:0] format.
Public Attributes
uint64_t data
The raw bits of the entry.
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
bool aarch64
True if the current lookup is performed in AArch64 state.
GrainSize grainSize
Width of the granule size in bits.
Detailed Description
Long-descriptor format (LPAE).
Definition at line 374 of file table_walker.hh.
Member Enumeration Documentation
enum ArmISA::TableWalker::LongDescriptor::EntryType
Descriptor type.
Enumerator:
Invalid
Table
Block
Page
Definition at line 377 of file table_walker.hh.
Member Function Documentation
bool ArmISA::TableWalker::LongDescriptor::af () const [inline]
Returns true if the access flag (AF) is set.
Definition at line 563 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
static uint8_t ArmISA::TableWalker::LongDescriptor::ap (bool rw, bool user) [inline, static]
Return the AP bits as compatible with the AP[2:0] format.
Utility function used to simplify the code in the TLB for performing permission checks.
Definition at line 601 of file table_walker.hh.
uint8_t ArmISA::TableWalker::LongDescriptor::ap () const [inline, virtual]
2-bit access protection flags
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 577 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor(), and ArmISA::TableWalker::insertTableEntry().
uint8_t ArmISA::TableWalker::LongDescriptor::apTable () const [inline]
Two bit access protection flags for subsequent levels of lookup.
Definition at line 649 of file table_walker.hh.
References bits(), data, Table, and type().
uint8_t ArmISA::TableWalker::LongDescriptor::attrIndx () const [inline]
Attribute index.
Definition at line 614 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::insertTableEntry(), and ArmISA::TableWalker::memAttrsLPAE().
bool ArmISA::TableWalker::LongDescriptor::contiguousHint () const [inline]
Contiguous hint bit.
Definition at line 538 of file table_walker.hh.
References bits(), Block, data, Page, and type().
virtual std::string ArmISA::TableWalker::LongDescriptor::dbgHeader () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 396 of file table_walker.hh.
References ArmISA::L3, ArmISA::TableWalker::DescriptorBase::lookupLevel, Page, and type().
bool ArmISA::TableWalker::LongDescriptor::dirty () const [inline]
This entry needs to be written back to memory.
Definition at line 636 of file table_walker.hh.
References _dirty.
TlbEntry::DomainType ArmISA::TableWalker::LongDescriptor::domain () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 606 of file table_walker.hh.
References Block, Page, and type().
virtual uint64_t ArmISA::TableWalker::LongDescriptor::getRawData () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 391 of file table_walker.hh.
References data.
bool ArmISA::TableWalker::LongDescriptor::global (WalkerState * currState) const [inline, virtual]
Is the translation global (no asid used)?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 545 of file table_walker.hh.
References ArmISA::TableWalker::WalkerState::aarch64, bits(), Block, data, ArmISA::TableWalker::WalkerState::el, ArmISA::EL2, ArmISA::EL3, ArmISA::TableWalker::WalkerState::isSecure, Page, ArmISA::TableWalker::WalkerState::secureLookup, and type().
uint8_t ArmISA::TableWalker::LongDescriptor::memAttr () const [inline]
Memory attributes, only used by stage 2 translations.
Definition at line 621 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::memAttrsLPAE().
Addr ArmISA::TableWalker::LongDescriptor::nextDescAddr (Addr va) const [inline]
Return the address of the next descriptor.
Definition at line 505 of file table_walker.hh.
References aarch64, bits(), grainSize, ArmISA::L1, ArmISA::TableWalker::DescriptorBase::lookupLevel, nextTableAddr(), ArmISA::pa, ArmISA::stride, Table, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
Addr ArmISA::TableWalker::LongDescriptor::nextTableAddr () const [inline]
Return the address of the next page table.
Definition at line 495 of file table_walker.hh.
References aarch64, data, grainSize, mbits(), Table, and type().
Referenced by nextDescAddr().
uint8_t ArmISA::TableWalker::LongDescriptor::offsetBits () const [inline, virtual]
Return the bit width of the page/block offset.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 441 of file table_walker.hh.
References Block, ArmISA::TableWalker::Grain16KB, ArmISA::TableWalker::Grain4KB, ArmISA::TableWalker::Grain64KB, grainSize, ArmISA::L1, ArmISA::TableWalker::DescriptorBase::lookupLevel, Page, panic, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor(), paddr(), and pfn().
Addr ArmISA::TableWalker::LongDescriptor::paddr () const [inline]
Return the physical address of the entry.
Definition at line 487 of file table_walker.hh.
References aarch64, data, mbits(), and offsetBits().
Addr ArmISA::TableWalker::LongDescriptor::paddr (Addr va) const [inline]
Return the complete physical address given a VA.
Definition at line 478 of file table_walker.hh.
References aarch64, data, mbits(), ArmISA::n, and offsetBits().
Addr ArmISA::TableWalker::LongDescriptor::pfn () const [inline, virtual]
Return the physical frame, bits shifted right.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 470 of file table_walker.hh.
References aarch64, bits(), data, and offsetBits().
bool ArmISA::TableWalker::LongDescriptor::pxn () const [inline]
Is privileged execution allowed on this mapping? (LPAE only).
Definition at line 531 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor(), and ArmISA::TableWalker::insertTableEntry().
bool ArmISA::TableWalker::LongDescriptor::pxnTable () const [inline]
Is privileged execution allowed on subsequent lookup levels?
Definition at line 678 of file table_walker.hh.
References bits(), data, Table, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
bool ArmISA::TableWalker::LongDescriptor::rw () const [inline]
Read/write access protection flag.
Definition at line 585 of file table_walker.hh.
References bits(), Block, data, Page, and type().
uint8_t ArmISA::TableWalker::LongDescriptor::rwTable () const [inline]
R/W protection flag for subsequent levels of lookup.
Definition at line 656 of file table_walker.hh.
References bits(), data, Table, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
bool ArmISA::TableWalker::LongDescriptor::secure (bool have_security, WalkerState * currState) const [inline, virtual]
Returns true if this entry targets the secure physical address map.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 411 of file table_walker.hh.
References bits(), Block, data, Page, ArmISA::TableWalker::WalkerState::secureLookup, and type().
bool ArmISA::TableWalker::LongDescriptor::secureTable () const [inline]
Whether the subsequent levels of lookup are secure.
Definition at line 642 of file table_walker.hh.
References bits(), data, Table, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
void ArmISA::TableWalker::LongDescriptor::setAf () [inline]
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 629 of file table_walker.hh.
References _dirty, and data.
uint8_t ArmISA::TableWalker::LongDescriptor::sh () const [inline]
2-bit shareability field
Definition at line 570 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::insertTableEntry(), and ArmISA::TableWalker::memAttrsLPAE().
EntryType ArmISA::TableWalker::LongDescriptor::type () const [inline]
Return the descriptor type.
Definition at line 424 of file table_walker.hh.
References bits(), Block, data, ArmISA::TableWalker::Grain4KB, grainSize, Invalid, ArmISA::L0, ArmISA::L2, ArmISA::L3, ArmISA::TableWalker::DescriptorBase::lookupLevel, Page, and Table.
Referenced by af(), ap(), apTable(), attrIndx(), contiguousHint(), dbgHeader(), ArmISA::TableWalker::doLongDescriptor(), domain(), global(), memAttr(), nextDescAddr(), nextTableAddr(), offsetBits(), pxn(), pxnTable(), rw(), rwTable(), secure(), secureTable(), sh(), user(), userTable(), xn(), and xnTable().
bool ArmISA::TableWalker::LongDescriptor::user () const [inline]
User/privileged level access protection flag.
Definition at line 592 of file table_walker.hh.
References bits(), Block, data, Page, and type().
uint8_t ArmISA::TableWalker::LongDescriptor::userTable () const [inline]
User/privileged mode protection flag for subsequent levels of lookup.
Definition at line 664 of file table_walker.hh.
References bits(), data, Table, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
bool ArmISA::TableWalker::LongDescriptor::xn () const [inline, virtual]
Is execution allowed on this mapping?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 524 of file table_walker.hh.
References bits(), Block, data, Page, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
bool ArmISA::TableWalker::LongDescriptor::xnTable () const [inline]
Is execution allowed on subsequent lookup levels?
Definition at line 671 of file table_walker.hh.
References bits(), data, Table, and type().
Referenced by ArmISA::TableWalker::doLongDescriptor().
Member Data Documentation
bool ArmISA::TableWalker::LongDescriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 389 of file table_walker.hh.
Referenced by dirty(), and setAf().
bool ArmISA::TableWalker::LongDescriptor::aarch64
True if the current lookup is performed in AArch64 state.
Definition at line 418 of file table_walker.hh.
Referenced by nextDescAddr(), nextTableAddr(), paddr(), pfn(), ArmISA::TableWalker::processWalkAArch64(), and ArmISA::TableWalker::processWalkLPAE().
uint64_t ArmISA::TableWalker::LongDescriptor::data
The raw bits of the entry.
Definition at line 385 of file table_walker.hh.
Referenced by af(), ap(), apTable(), attrIndx(), contiguousHint(), ArmISA::TableWalker::doLongDescriptor(), getRawData(), global(), memAttr(), nextTableAddr(), paddr(), pfn(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), pxn(), pxnTable(), rw(), rwTable(), secure(), secureTable(), setAf(), sh(), type(), user(), userTable(), xn(), and xnTable().
GrainSize ArmISA::TableWalker::LongDescriptor::grainSize
Width of the granule size in bits.
Definition at line 421 of file table_walker.hh.
Referenced by nextDescAddr(), nextTableAddr(), offsetBits(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), and type().
The documentation for this class was generated from the following file:
arch/arm/table_walker.hh