gem5: Stats::ValueBase< Derived > Class Template Reference
Stats::ValueBase< Derived > Class Template Reference
#include <statistics.hh>
Public Member Functions
ValueBase ()
~ValueBase ()
template<class T >
Derived & scalar (T &value)
template<class T >
Derived & functor (T &func)
template<class T , class V >
Derived & method (T *obj, V(T::*method)() const)
Extended functor that calls the specified method of the provided object.
Counter value ()
Result result () const
Result total () const
size_type size () const
std::string str () const
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
void prepare ()
void reset ()
Reset the stat to the default state.
Private Attributes
ProxyInfo * proxy
Detailed Description
template<class Derived>
class Stats::ValueBase< Derived >
Definition at line 800 of file statistics.hh.
Constructor & Destructor Documentation
template<class Derived> Stats::ValueBase< Derived >::ValueBase () [inline]
Definition at line 806 of file statistics.hh.
template<class Derived> Stats::ValueBase< Derived >::~ValueBase () [inline]
Definition at line 807 of file statistics.hh.
Member Function Documentation
template<class Derived> bool Stats::ValueBase< Derived >::check () const [inline]
Check that this stat has been set up properly and is ready for use.
Returns:
true for success
Reimplemented from Stats::InfoAccess.
Definition at line 850 of file statistics.hh.
template<class Derived> template<class T > Derived& Stats::ValueBase< Derived >::functor (T & func) [inline]
Definition at line 820 of file statistics.hh.
Referenced by Stats::Global::Global(), and StatTest::init().
template<class Derived> template<class T , class V > Derived& Stats::ValueBase< Derived >::method (T * obj, V(T::*)() const method) [inline]
Extended functor that calls the specified method of the provided object.
Parameters:
obj Pointer to the object whose method should be called.
method Pointer of the function / method of the object.
Returns:
Updated stats item.
Definition at line 836 of file statistics.hh.
Referenced by VoltageDomain::regStats().
template<class Derived> void Stats::ValueBase< Derived >::prepare () [inline]
Definition at line 851 of file statistics.hh.
template<class Derived> void Stats::ValueBase< Derived >::reset () [inline]
Reset the stat to the default state.
Reimplemented from Stats::InfoAccess.
Definition at line 852 of file statistics.hh.
template<class Derived> Result Stats::ValueBase< Derived >::result () const [inline]
Definition at line 844 of file statistics.hh.
template<class Derived> template<class T > Derived& Stats::ValueBase< Derived >::scalar (T & value) [inline]
Definition at line 811 of file statistics.hh.
Referenced by Stats::Global::Global(), and ClockDomain::regStats().
template<class Derived> size_type Stats::ValueBase< Derived >::size () const [inline]
Definition at line 846 of file statistics.hh.
template<class Derived> std::string Stats::ValueBase< Derived >::str () const [inline]
Definition at line 848 of file statistics.hh.
template<class Derived> Result Stats::ValueBase< Derived >::total () const [inline]
Definition at line 845 of file statistics.hh.
template<class Derived> Counter Stats::ValueBase< Derived >::value () [inline]
Definition at line 843 of file statistics.hh.
Referenced by CommMonitor::samplePeriodic().
template<class Derived> bool Stats::ValueBase< Derived >::zero () const [inline]
Returns:
true if this stat has a value and satisfies its requirement as a prereq
Reimplemented from Stats::InfoAccess.
Definition at line 849 of file statistics.hh.
Member Data Documentation
template<class Derived> ProxyInfo* Stats::ValueBase< Derived >::proxy [private]
Definition at line 803 of file statistics.hh.
Referenced by Stats::ValueBase< Value >::check(), Stats::ValueBase< Value >::functor(), Stats::ValueBase< Value >::method(), Stats::ValueBase< Value >::result(), Stats::ValueBase< Value >::scalar(), Stats::ValueBase< Value >::size(), Stats::ValueBase< Value >::str(), Stats::ValueBase< Value >::total(), Stats::ValueBase< Value >::value(), Stats::ValueBase< Value >::zero(), and Stats::ValueBase< Value >::~ValueBase().
The documentation for this class was generated from the following file:
base/statistics.hh