gem5: ExternalSlave Class Reference
ExternalSlave Class Reference
#include <external_slave.hh>
Classes
class Handler
class Port
Derive from this class to create an external port interface.
Public Member Functions
ExternalSlave (ExternalSlaveParams *params)
BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
SlavePort interface.
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
Static Public Member Functions
static void registerHandler (const std::string &handler_name, Handler *handler)
Register a handler which can provide ports with port_type == handler_name.
Protected Attributes
Port * externalPort
The peer port for the gem5 port "port".
std::string portName
Name of the bound port.
std::string portType
Key to select a port handler.
std::string portData
Handler-specific port configuration.
AddrRangeList addrRanges
The Range of addresses supported by the devices on the external side of this port.
Static Protected Attributes
static std::map< std::string,
Handler * > portHandlers
Registered handlers.
Detailed Description
Definition at line 66 of file external_slave.hh.
Constructor & Destructor Documentation
ExternalSlave::ExternalSlave (ExternalSlaveParams * params)
Definition at line 188 of file external_slave.cc.
References portHandlers, and registerHandler().
Member Function Documentation
BaseSlavePort & ExternalSlave::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
SlavePort interface.
Responds only to port "port"
Reimplemented from MemObject.
Definition at line 202 of file external_slave.cc.
References DPRINTF, externalPort, fatal, portData, portHandlers, portName, and portType.
void ExternalSlave::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 230 of file external_slave.cc.
References externalPort, fatal, BaseSlavePort::isConnected(), SimObject::name(), and SlavePort::sendRangeChange().
void ExternalSlave::registerHandler (const std::string & handler_name, Handler * handler) [static]
Register a handler which can provide ports with port_type == handler_name.
Definition at line 248 of file external_slave.cc.
References portHandlers.
Referenced by ExternalSlave().
Member Data Documentation
AddrRangeList ExternalSlave::addrRanges [protected]
The Range of addresses supported by the devices on the external side of this port.
Definition at line 118 of file external_slave.hh.
Referenced by ExternalSlave::Port::getAddrRanges().
Port* ExternalSlave::externalPort [protected]
The peer port for the gem5 port "port".
Definition at line 105 of file external_slave.hh.
Referenced by getSlavePort(), and init().
std::string ExternalSlave::portData [protected]
Handler-specific port configuration.
Definition at line 114 of file external_slave.hh.
Referenced by getSlavePort().
std::map< std::string, ExternalSlave::Handler * > ExternalSlave::portHandlers [static, protected]
Registered handlers.
Handlers are chosen using the port_type parameter on ExternalSlaves. port_types form a global namespace across the simulation and so handlers are registered into a global structure
Definition at line 124 of file external_slave.hh.
Referenced by ExternalSlave(), getSlavePort(), and registerHandler().
std::string ExternalSlave::portName [protected]
Name of the bound port.
This will be name() + ".port"
Definition at line 108 of file external_slave.hh.
Referenced by getSlavePort().
std::string ExternalSlave::portType [protected]
Key to select a port handler.
Definition at line 111 of file external_slave.hh.
Referenced by getSlavePort().
The documentation for this class was generated from the following files:
mem/external_slave.hh
mem/external_slave.cc