gem5: SnapMemCtrl Class Reference
SnapMemCtrl Class Reference
#include <snap_mem_ctrl.hh>
Classes
class AddressGenerationUnit
class AddressTable
class SnapMemCtrlMasterPort
class SnapMemCtrlMasterSnapPort
class SnapMemCtrlSlavePort
Public Types
typedef SnapMemCtrlParams Params
Public Member Functions
SnapMemCtrl (const Params *params)
void regStats ()
Register statistics for this object.
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
void snapshot ()
void snapshotCycle ()
void finalizeSnapshot ()
Public Attributes
EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshot > snapshotEvent
EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshotCycle > snapshotCycleEvent
EventWrapper< SnapMemCtrl,&SnapMemCtrl::finalizeSnapshot > finalizeSnapshotEvent
Protected Attributes
SnapMemCtrlMasterPort masterPort
SnapMemCtrlMasterSnapPort masterSnapPort
Private Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
virtual AddrRangeList getAddrRanges () const
virtual bool recvTimingReq (PacketPtr pkt)
virtual Tick recvAtomic (PacketPtr pkt)
virtual Tick recvAtomicSnoop (PacketPtr pkt)
virtual void recvFunctional (PacketPtr pkt)
virtual void recvFunctionalSnoop (PacketPtr pkt)
virtual bool recvTimingSnoopReq (PacketPtr pkt)
virtual bool recvTimingSnapperPort (PacketPtr pkt)
Addr translateUnitAddr (Addr addr)
bool filterSnapReadResponsePacket (PacketPtr pkt)
void catchSnapReadResponsePacket (PacketPtr pkt)
void filterWriteRequestPacket (PacketPtr pkt)
void catchWriteRequestPacket (PacketPtr pkt)
void sendReadPacketToNormalMemory ()
void suspendCPUs ()
void resumeCPUs ()
Private Attributes
const AddrRangeList addrRanges
const Tick snapInterval
const uint64_t unitSize
unsigned int cacheLineSize
AddressTable wat
AddressTable scat
AddressGenerationUnit agu
System * system
MasterID mid
std::vector< BaseCPU * > basecpus
Stats::Scalar snapshotCycles
Stats::Formula snapshotSeconds
Stats::Scalar countSnapshots
Stats::Scalar writtenAddressTableSize
Stats::Formula writtenAddressTableSizePerSnapshots
Stats::Scalar snoopedRequests
Stats::Scalar snoopedWriteRequests
Stats::Scalar snoopedUpgradeRequests
Detailed Description
Definition at line 15 of file snap_mem_ctrl.hh.
Member Typedef Documentation
typedef SnapMemCtrlParams SnapMemCtrl::Params
Reimplemented from MemObject.
Definition at line 19 of file snap_mem_ctrl.hh.
Constructor & Destructor Documentation
SnapMemCtrl::SnapMemCtrl (const Params * params)
Definition at line 73 of file snap_mem_ctrl.cc.
References System::cacheLineSize(), cacheLineSize, curTick(), inform, SimObject::name(), EventManager::schedule(), snapInterval, snapshotEvent, and system.
Member Function Documentation
void SnapMemCtrl::catchSnapReadResponsePacket (PacketPtr pkt) [private]
Definition at line 183 of file snap_mem_ctrl.cc.
References cacheLineSize, Packet::getAddr(), SnapMemCtrl::AddressTable::isExist(), masterSnapPort, mid, ClockedObject::nextCycle(), Packet::req, scat, QueuedMasterPort::schedTimingReq(), and MemCmd::WriteReq.
Referenced by recvTimingResp().
void SnapMemCtrl::catchWriteRequestPacket (PacketPtr pkt) [private]
Definition at line 195 of file snap_mem_ctrl.cc.
References X86ISA::addr, Packet::getAddr(), Packet::isRequest(), Packet::isUpgrade(), Packet::isWrite(), SnapMemCtrl::AddressTable::push(), snoopedRequests, snoopedUpgradeRequests, snoopedWriteRequests, translateUnitAddr(), and wat.
Referenced by recvTimingSnoopReq().
bool SnapMemCtrl::filterSnapReadResponsePacket (PacketPtr pkt) [private]
void SnapMemCtrl::filterWriteRequestPacket (PacketPtr pkt) [private]
void SnapMemCtrl::finalizeSnapshot ()
Definition at line 306 of file snap_mem_ctrl.cc.
References curTick(), inform, SimObject::name(), resumeCPUs(), EventManager::schedule(), snapInterval, and snapshotEvent.
AddrRangeList SnapMemCtrl::getAddrRanges () const [private, virtual]
Definition at line 136 of file snap_mem_ctrl.cc.
References addrRanges.
Referenced by SnapMemCtrl::SnapMemCtrlSlavePort::getAddrRanges(), and SnapMemCtrl::SnapMemCtrlMasterPort::getAddrRanges().
BaseMasterPort & SnapMemCtrl::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 314 of file snap_mem_ctrl.cc.
References masterPort, and masterSnapPort.
void SnapMemCtrl::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 95 of file snap_mem_ctrl.cc.
References System::getMasterId(), inform, mid, SimObject::name(), and system.
Tick SnapMemCtrl::recvAtomic (PacketPtr pkt) [private, virtual]
Definition at line 168 of file snap_mem_ctrl.cc.
References curTick().
Referenced by SnapMemCtrl::SnapMemCtrlSlavePort::recvAtomic().
Tick SnapMemCtrl::recvAtomicSnoop (PacketPtr pkt) [private, virtual]
Definition at line 163 of file snap_mem_ctrl.cc.
References curTick().
Referenced by SnapMemCtrl::SnapMemCtrlMasterPort::recvAtomicSnoop().
void SnapMemCtrl::recvFunctional (PacketPtr pkt) [private, virtual]
Definition at line 173 of file snap_mem_ctrl.cc.
Referenced by SnapMemCtrl::SnapMemCtrlSlavePort::recvFunctional().
void SnapMemCtrl::recvFunctionalSnoop (PacketPtr pkt) [private, virtual]
Definition at line 178 of file snap_mem_ctrl.cc.
Referenced by SnapMemCtrl::SnapMemCtrlMasterPort::recvFunctionalSnoop().
bool SnapMemCtrl::recvTimingReq (PacketPtr pkt) [private, virtual]
Definition at line 146 of file snap_mem_ctrl.cc.
Referenced by SnapMemCtrl::SnapMemCtrlSlavePort::recvTimingReq().
bool SnapMemCtrl::recvTimingResp (PacketPtr pkt) [private, virtual]
Definition at line 151 of file snap_mem_ctrl.cc.
References catchSnapReadResponsePacket().
Referenced by SnapMemCtrl::SnapMemCtrlMasterPort::recvTimingResp().
bool SnapMemCtrl::recvTimingSnapperPort (PacketPtr pkt) [private, virtual]
Definition at line 208 of file snap_mem_ctrl.cc.
References SnapMemCtrl::AddressTable::erase(), Packet::getAddr(), Packet::req, and scat.
Referenced by SnapMemCtrl::SnapMemCtrlMasterSnapPort::recvTimingResp().
bool SnapMemCtrl::recvTimingSnoopReq (PacketPtr pkt) [private, virtual]
Definition at line 157 of file snap_mem_ctrl.cc.
References catchWriteRequestPacket().
Referenced by SnapMemCtrl::SnapMemCtrlMasterPort::recvTimingSnoopReq().
void SnapMemCtrl::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 103 of file snap_mem_ctrl.cc.
References ClockedObject::clockPeriod(), countSnapshots, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), SimClock::Int::s, snapshotCycles, snapshotSeconds, snoopedRequests, snoopedUpgradeRequests, snoopedWriteRequests, writtenAddressTableSize, and writtenAddressTableSizePerSnapshots.
void SnapMemCtrl::resumeCPUs () [private]
Definition at line 250 of file snap_mem_ctrl.cc.
References basecpus, ArmISA::i, inform, ArmISA::j, and SimObject::name().
Referenced by finalizeSnapshot().
void SnapMemCtrl::sendReadPacketToNormalMemory () [private]
Definition at line 281 of file snap_mem_ctrl.cc.
References agu, Packet::allocate(), cacheLineSize, ClockedObject::clockEdge(), SnapMemCtrl::AddressGenerationUnit::init(), SnapMemCtrl::AddressGenerationUnit::isComplete(), SnapMemCtrl::AddressTable::isEmpty(), SnapMemCtrl::AddressTable::isExist(), SnapMemCtrl::AddressTable::isFull(), masterPort, mid, SnapMemCtrl::AddressGenerationUnit::pop(), SnapMemCtrl::AddressTable::pop(), SnapMemCtrl::AddressTable::push(), MemCmd::ReadReq, scat, QueuedMasterPort::schedTimingReq(), unitSize, and wat.
Referenced by snapshotCycle().
void SnapMemCtrl::snapshot ()
Definition at line 217 of file snap_mem_ctrl.cc.
References countSnapshots, curTick(), SnapMemCtrl::AddressTable::getSize(), inform, System::isTimingMode(), SimObject::name(), ClockedObject::nextCycle(), EventManager::schedule(), snapInterval, snapshotCycleEvent, snapshotEvent, suspendCPUs(), system, unitSize, wat, and writtenAddressTableSize.
void SnapMemCtrl::snapshotCycle ()
Definition at line 265 of file snap_mem_ctrl.cc.
References agu, curTick(), finalizeSnapshotEvent, inform, SnapMemCtrl::AddressGenerationUnit::isComplete(), SnapMemCtrl::AddressTable::isEmpty(), SimObject::name(), ClockedObject::nextCycle(), scat, EventManager::schedule(), sendReadPacketToNormalMemory(), snapshotCycleEvent, snapshotCycles, and wat.
void SnapMemCtrl::suspendCPUs () [private]
Definition at line 235 of file snap_mem_ctrl.cc.
References basecpus, ArmISA::i, inform, ArmISA::j, and SimObject::name().
Referenced by snapshot().
Addr SnapMemCtrl::translateUnitAddr (Addr addr) [private]
Definition at line 141 of file snap_mem_ctrl.cc.
References unitSize.
Referenced by catchWriteRequestPacket().
Member Data Documentation
const AddrRangeList SnapMemCtrl::addrRanges [private]
Definition at line 81 of file snap_mem_ctrl.hh.
Referenced by getAddrRanges().
AddressGenerationUnit SnapMemCtrl::agu [private]
Definition at line 156 of file snap_mem_ctrl.hh.
Referenced by sendReadPacketToNormalMemory(), and snapshotCycle().
std::vector<BaseCPU*> SnapMemCtrl::basecpus [private]
Definition at line 160 of file snap_mem_ctrl.hh.
Referenced by resumeCPUs(), and suspendCPUs().
unsigned int SnapMemCtrl::cacheLineSize [private]
Definition at line 84 of file snap_mem_ctrl.hh.
Referenced by catchSnapReadResponsePacket(), sendReadPacketToNormalMemory(), and SnapMemCtrl().
Stats::Scalar SnapMemCtrl::countSnapshots [private]
Definition at line 167 of file snap_mem_ctrl.hh.
Referenced by regStats(), and snapshot().
EventWrapper<SnapMemCtrl, &SnapMemCtrl::finalizeSnapshot> SnapMemCtrl::finalizeSnapshotEvent
Definition at line 35 of file snap_mem_ctrl.hh.
Referenced by snapshotCycle().
SnapMemCtrlMasterPort SnapMemCtrl::masterPort [protected]
Definition at line 76 of file snap_mem_ctrl.hh.
Referenced by getMasterPort(), and sendReadPacketToNormalMemory().
SnapMemCtrlMasterSnapPort SnapMemCtrl::masterSnapPort [protected]
Definition at line 77 of file snap_mem_ctrl.hh.
Referenced by catchSnapReadResponsePacket(), and getMasterPort().
MasterID SnapMemCtrl::mid [private]
Definition at line 159 of file snap_mem_ctrl.hh.
Referenced by catchSnapReadResponsePacket(), init(), and sendReadPacketToNormalMemory().
AddressTable SnapMemCtrl::scat [private]
Definition at line 125 of file snap_mem_ctrl.hh.
Referenced by catchSnapReadResponsePacket(), recvTimingSnapperPort(), sendReadPacketToNormalMemory(), and snapshotCycle().
const Tick SnapMemCtrl::snapInterval [private]
Definition at line 82 of file snap_mem_ctrl.hh.
Referenced by finalizeSnapshot(), SnapMemCtrl(), and snapshot().
EventWrapper<SnapMemCtrl, &SnapMemCtrl::snapshotCycle> SnapMemCtrl::snapshotCycleEvent
Definition at line 34 of file snap_mem_ctrl.hh.
Referenced by snapshot(), and snapshotCycle().
Stats::Scalar SnapMemCtrl::snapshotCycles [private]
Definition at line 165 of file snap_mem_ctrl.hh.
Referenced by regStats(), and snapshotCycle().
EventWrapper<SnapMemCtrl, &SnapMemCtrl::snapshot> SnapMemCtrl::snapshotEvent
Definition at line 33 of file snap_mem_ctrl.hh.
Referenced by finalizeSnapshot(), SnapMemCtrl(), and snapshot().
Stats::Formula SnapMemCtrl::snapshotSeconds [private]
Definition at line 166 of file snap_mem_ctrl.hh.
Referenced by regStats().
Stats::Scalar SnapMemCtrl::snoopedRequests [private]
Definition at line 170 of file snap_mem_ctrl.hh.
Referenced by catchWriteRequestPacket(), and regStats().
Stats::Scalar SnapMemCtrl::snoopedUpgradeRequests [private]
Definition at line 172 of file snap_mem_ctrl.hh.
Referenced by catchWriteRequestPacket(), and regStats().
Stats::Scalar SnapMemCtrl::snoopedWriteRequests [private]
Definition at line 171 of file snap_mem_ctrl.hh.
Referenced by catchWriteRequestPacket(), and regStats().
System* SnapMemCtrl::system [private]
Definition at line 158 of file snap_mem_ctrl.hh.
Referenced by init(), SnapMemCtrl(), and snapshot().
const uint64_t SnapMemCtrl::unitSize [private]
Definition at line 83 of file snap_mem_ctrl.hh.
Referenced by sendReadPacketToNormalMemory(), snapshot(), and translateUnitAddr().
AddressTable SnapMemCtrl::wat [private]
Definition at line 123 of file snap_mem_ctrl.hh.
Referenced by catchWriteRequestPacket(), sendReadPacketToNormalMemory(), snapshot(), and snapshotCycle().
Stats::Scalar SnapMemCtrl::writtenAddressTableSize [private]
Definition at line 168 of file snap_mem_ctrl.hh.
Referenced by regStats(), and snapshot().
Stats::Formula SnapMemCtrl::writtenAddressTableSizePerSnapshots [private]
Definition at line 169 of file snap_mem_ctrl.hh.
Referenced by regStats().
The documentation for this class was generated from the following files:
mem/snapmem/snap_mem_ctrl.hh
mem/snapmem/snap_mem_ctrl.cc