gem5: MipsISA::MipsFaultBase Class Reference
MipsISA::MipsFaultBase Class Reference
#include <faults.hh>
Classes
struct FaultVals
Public Member Functions
void setExceptionState (ThreadContext *, uint8_t)
virtual FaultVect offset (ThreadContext *tc) const =0
virtual ExcCode code () const =0
virtual FaultVect base (ThreadContext *tc) const
FaultVect vect (ThreadContext *tc) const
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Detailed Description
Definition at line 76 of file faults.hh.
Member Function Documentation
virtual FaultVect MipsISA::MipsFaultBase::base (ThreadContext * tc) const [inline, virtual]
Definition at line 90 of file faults.hh.
References MipsISA::MISCREG_EBASE, MipsISA::MISCREG_STATUS, ThreadContext::readMiscReg(), and ArmISA::status.
Referenced by vect().
virtual ExcCode MipsISA::MipsFaultBase::code () const [pure virtual]
Implemented in MipsISA::MipsFault< T >, MipsISA::AddressErrorFault, MipsISA::TlbFault< T >, MipsISA::TlbModifiedFault, MipsISA::MipsFault< IntegerOverflowFault >, MipsISA::MipsFault< SoftResetFault >, MipsISA::MipsFault< TrapFault >, MipsISA::MipsFault< DspStateDisabledFault >, MipsISA::MipsFault< NonMaskableInterrupt >, MipsISA::MipsFault< MachineCheckFault >, MipsISA::MipsFault< AddressErrorFault >, MipsISA::MipsFault< ThreadFault >, MipsISA::MipsFault< CoprocessorUnusableFault >, MipsISA::MipsFault< ResetFault >, MipsISA::MipsFault< TlbRefillFault >, MipsISA::MipsFault< ReservedInstructionFault >, MipsISA::MipsFault< BreakpointFault >, MipsISA::MipsFault< TlbModifiedFault >, MipsISA::MipsFault< InterruptFault >, MipsISA::MipsFault< TlbInvalidFault >, MipsISA::MipsFault< SystemCallFault >, MipsISA::TlbFault< TlbRefillFault >, MipsISA::TlbFault< TlbModifiedFault >, and MipsISA::TlbFault< TlbInvalidFault >.
Referenced by invoke().
void MipsISA::MipsFaultBase::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from FaultBase.
Reimplemented in MipsISA::ResetFault, MipsISA::SoftResetFault, MipsISA::NonMaskableInterrupt, MipsISA::CoprocessorUnusableFault, MipsISA::AddressFault< T >, MipsISA::TlbFault< T >, MipsISA::AddressFault< AddressErrorFault >, MipsISA::AddressFault< TlbRefillFault >, MipsISA::AddressFault< TlbModifiedFault >, MipsISA::AddressFault< TlbInvalidFault >, MipsISA::TlbFault< TlbRefillFault >, MipsISA::TlbFault< TlbModifiedFault >, and MipsISA::TlbFault< TlbInvalidFault >.
Definition at line 134 of file faults.cc.
References code(), DPRINTF, FullSystem, FaultBase::name(), panic, ThreadContext::pcState(), setExceptionState(), and vect().
virtual FaultVect MipsISA::MipsFaultBase::offset (ThreadContext * tc) const [pure virtual]
Implemented in MipsISA::MipsFault< T >, MipsISA::InterruptFault, MipsISA::TlbRefillFault, MipsISA::MipsFault< IntegerOverflowFault >, MipsISA::MipsFault< SoftResetFault >, MipsISA::MipsFault< TrapFault >, MipsISA::MipsFault< DspStateDisabledFault >, MipsISA::MipsFault< NonMaskableInterrupt >, MipsISA::MipsFault< MachineCheckFault >, MipsISA::MipsFault< AddressErrorFault >, MipsISA::MipsFault< ThreadFault >, MipsISA::MipsFault< CoprocessorUnusableFault >, MipsISA::MipsFault< ResetFault >, MipsISA::MipsFault< TlbRefillFault >, MipsISA::MipsFault< ReservedInstructionFault >, MipsISA::MipsFault< BreakpointFault >, MipsISA::MipsFault< TlbModifiedFault >, MipsISA::MipsFault< InterruptFault >, MipsISA::MipsFault< TlbInvalidFault >, and MipsISA::MipsFault< SystemCallFault >.
Referenced by vect().
void MipsISA::MipsFaultBase::setExceptionState (ThreadContext * tc, uint8_t excCode)
Definition at line 102 of file faults.cc.
References DPRINTF, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_EPC, MipsISA::MISCREG_SRSCTL, MipsISA::MISCREG_STATUS, GenericISA::SimplePCState< MachInst >::npc(), GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), ThreadContext::readMiscReg(), ThreadContext::setMiscRegNoEffect(), and ArmISA::status.
Referenced by invoke(), and MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState().
FaultVect MipsISA::MipsFaultBase::vect (ThreadContext * tc) const [inline]
Definition at line 100 of file faults.hh.
References base(), and offset().
Referenced by MipsISA::TlbFault< TlbInvalidFault >::invoke(), MipsISA::ResetFault::invoke(), and invoke().
The documentation for this class was generated from the following files:
arch/mips/faults.hh
arch/mips/faults.cc