gem5: CommMonitor::MonitorSlavePort Class Reference
CommMonitor::MonitorSlavePort Class Reference
This is the slave port of the communication monitor.
Public Member Functions
MonitorSlavePort (const std::string &_name, CommMonitor &_mon)
Protected Member Functions
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
bool recvTimingSnoopResp (PacketPtr pkt)
Receive a timing snoop response from the master port.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Private Attributes
CommMonitor & mon
Detailed Description
This is the slave port of the communication monitor.
All recv functions call a function in CommMonitor, where the send function of the master port is called. Besides this, these functions can also perform actions for capturing statistics.
Definition at line 196 of file comm_monitor.hh.
Constructor & Destructor Documentation
CommMonitor::MonitorSlavePort::MonitorSlavePort (const std::string & _name, CommMonitor & _mon) [inline]
Definition at line 201 of file comm_monitor.hh.
Member Function Documentation
AddrRangeList CommMonitor::MonitorSlavePort::getAddrRanges () const [inline, protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 227 of file comm_monitor.hh.
References CommMonitor::getAddrRanges(), and mon.
Tick CommMonitor::MonitorSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 212 of file comm_monitor.hh.
References mon, and CommMonitor::recvAtomic().
void CommMonitor::MonitorSlavePort::recvFunctional (PacketPtr pkt) [inline, protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 207 of file comm_monitor.hh.
References mon, and CommMonitor::recvFunctional().
void CommMonitor::MonitorSlavePort::recvRespRetry () [inline, protected, virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 232 of file comm_monitor.hh.
References mon, and CommMonitor::recvRespRetry().
bool CommMonitor::MonitorSlavePort::recvTimingReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 217 of file comm_monitor.hh.
References mon, and CommMonitor::recvTimingReq().
bool CommMonitor::MonitorSlavePort::recvTimingSnoopResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop response from the master port.
Reimplemented from SlavePort.
Definition at line 222 of file comm_monitor.hh.
References mon, and CommMonitor::recvTimingSnoopResp().
Member Data Documentation
CommMonitor& CommMonitor::MonitorSlavePort::mon [private]
Definition at line 239 of file comm_monitor.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvRespRetry(), recvTimingReq(), and recvTimingSnoopResp().
The documentation for this class was generated from the following file:
mem/comm_monitor.hh