gem5: X86ISA::StartupInterrupt Class Reference
X86ISA::StartupInterrupt Class Reference
#include <faults.hh>
Public Member Functions
StartupInterrupt (uint8_t _vector)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Detailed Description
Definition at line 408 of file faults.hh.
Constructor & Destructor Documentation
X86ISA::StartupInterrupt::StartupInterrupt (uint8_t _vector) [inline]
Definition at line 411 of file faults.hh.
Member Function Documentation
void X86ISA::StartupInterrupt::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from X86ISA::X86FaultBase.
Definition at line 291 of file faults.cc.
References DPRINTF, X86ISA::MISCREG_CS, X86ISA::MISCREG_CS_BASE, X86ISA::MISCREG_CS_EFF_BASE, X86ISA::MISCREG_CS_LIMIT, X86ISA::MISCREG_M5_REG, panic, ThreadContext::pcState(), ThreadContext::readMiscReg(), X86ISA::RealMode, ThreadContext::setMiscReg(), and X86ISA::X86FaultBase::vector.
The documentation for this class was generated from the following files:
arch/x86/faults.hh
arch/x86/faults.cc