gem5: SaturatingCounter Class Reference
SaturatingCounter Class Reference
#include <sat_counter.hh>
Public Member Functions
SaturatingCounter (unsigned int _max, unsigned int _start=0)
virtual void increment (unsigned int n=1)
virtual void decrement (unsigned int n=1)
virtual void reset ()
SaturatingCounter operator++ (int)
SaturatingCounter operator-- (int)
operator unsigned int ()
operator int ()
operator double ()
operator long ()
operator std::string ()
bool isMax ()
bool isMin ()
Private Member Functions
void check_set (unsigned int n)
Private Attributes
unsigned int max
unsigned int counter
unsigned int start
Detailed Description
Definition at line 4 of file sat_counter.hh.
Constructor & Destructor Documentation
SaturatingCounter::SaturatingCounter (unsigned int _max, unsigned int _start = 0) [inline]
Definition at line 16 of file sat_counter.hh.
References check_set().
Member Function Documentation
void SaturatingCounter::check_set (unsigned int n) [inline, private]
Definition at line 10 of file sat_counter.hh.
References counter, and max.
Referenced by SaturatingCounter().
virtual void SaturatingCounter::decrement (unsigned int n = 1) [inline, virtual]
Reimplemented in ConservativeStateMachine, and ConservativeSaturatingCounter.
Definition at line 24 of file sat_counter.hh.
References counter, and ArmISA::n.
Referenced by ConservativeSaturatingCounter::decrement(), and operator--().
virtual void SaturatingCounter::increment (unsigned int n = 1) [inline, virtual]
Reimplemented in ConservativeSaturatingCounter.
Definition at line 20 of file sat_counter.hh.
References counter, max, and ArmISA::n.
Referenced by ConservativeSaturatingCounter::increment(), and operator++().
bool SaturatingCounter::isMax () [inline]
Definition at line 47 of file sat_counter.hh.
Referenced by ConservativeSaturatingCounter::increment().
bool SaturatingCounter::isMin () [inline]
Definition at line 48 of file sat_counter.hh.
Referenced by ConservativeSaturatingCounter::decrement().
SaturatingCounter::operator double () [inline]
Definition at line 43 of file sat_counter.hh.
References counter.
SaturatingCounter::operator int () [inline]
Definition at line 42 of file sat_counter.hh.
References counter.
SaturatingCounter::operator long () [inline]
Definition at line 44 of file sat_counter.hh.
References counter.
SaturatingCounter::operator std::string () [inline]
Definition at line 45 of file sat_counter.hh.
References counter.
SaturatingCounter::operator unsigned int () [inline]
Definition at line 41 of file sat_counter.hh.
References counter.
SaturatingCounter SaturatingCounter::operator++ (int) [inline]
Definition at line 31 of file sat_counter.hh.
References counter, increment(), and max.
SaturatingCounter SaturatingCounter::operator-- (int) [inline]
Definition at line 36 of file sat_counter.hh.
References counter, decrement(), and max.
virtual void SaturatingCounter::reset () [inline, virtual]
Definition at line 29 of file sat_counter.hh.
References counter, and start.
Referenced by ConservativeStateMachine::decrement().
Member Data Documentation
unsigned int SaturatingCounter::counter [private]
Definition at line 7 of file sat_counter.hh.
Referenced by check_set(), decrement(), increment(), operator double(), operator int(), operator long(), operator std::string(), operator unsigned int(), operator++(), operator--(), and reset().
unsigned int SaturatingCounter::max [private]
Definition at line 6 of file sat_counter.hh.
Referenced by check_set(), increment(), operator++(), and operator--().
unsigned int SaturatingCounter::start [private]
Definition at line 8 of file sat_counter.hh.
Referenced by reset().
The documentation for this class was generated from the following file:
mem/cache/tags/sat_counter.hh