gem5: DVFSHandler Class Reference
DVFSHandler Class Reference
DVFS Handler class, maintains a list of all the domains it can handle.
#include <dvfs_handler.hh>
Classes
struct UpdateEvent
Update performance level event, encapsulates all the required information for a future call to change a domain's performance level.
Public Types
typedef DVFSHandlerParams Params
typedef SrcClockDomain::DomainID DomainID
typedef SrcClockDomain::PerfLevel PerfLevel
Public Member Functions
DVFSHandler (const Params *p)
uint32_t numDomains () const
Get the number of domains assigned to this DVFS handler.
DomainID domainID (uint32_t index) const
Get the n-th domain ID, from the domains managed by this handler.
bool validDomainID (DomainID domain_id) const
Check whether a domain ID is known to the handler or not.
Tick transLatency () const
Get transition latency to switch between performance levels.
bool perfLevel (DomainID domain_id, PerfLevel perf_level)
Set a new performance level for the specified domain.
PerfLevel perfLevel (DomainID domain_id) const
Get the current performance level of a domain.
Tick clkPeriodAtPerfLevel (DomainID domain_id, PerfLevel perf_level) const
Read the clock period of the specified domain at the specified performance level.
double voltageAtPerfLevel (DomainID domain_id, PerfLevel perf_level) const
Read the voltage of the specified domain at the specified performance level.
PerfLevel numPerfLevels (PerfLevel domain_id) const
Get the total number of available performance levels.
bool isEnabled () const
Check enable status of the DVFS handler, when the handler is disabled, no request should be sent to the handler.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Types
typedef std::map< DomainID,
SrcClockDomain * > Domains
typedef std::map< DomainID,
UpdateEvent > UpdatePerfLevelEvents
Private Member Functions
SrcClockDomain * findDomain (DomainID domain_id) const
Search for a domain based on the domain ID.
Private Attributes
Domains domains
std::vector< DomainID > domainIDList
List of IDs avaiable in the domain list.
SrcClockDomain * sysClkDomain
Clock domain of the system the handler is instantiated.
bool enableHandler
Disabling the DVFS handler ensures that all the DVFS migration requests are ignored.
const Tick _transLatency
This corresponds to the maximum transition latency associated with the hardware transitioning from a particular performance level to the other.
UpdatePerfLevelEvents updatePerfLevelEvents
Map from domain IDs -> perf level update events, records in-flight change requests per domain ID.
Detailed Description
DVFS Handler class, maintains a list of all the domains it can handle.
Each entry of that list is an object of the DomainConfig class, and the handler uses the methods provided by that class to get access to the configuration of each domain. The handler is responsible for setting/getting clock periods and voltages from clock/voltage domains. The handler acts the bridge between software configurable information for each domain as provided to the controller and the hardware implementation details for those domains.
Definition at line 74 of file dvfs_handler.hh.
Member Typedef Documentation
typedef SrcClockDomain::DomainID DVFSHandler::DomainID
Definition at line 80 of file dvfs_handler.hh.
typedef std::map<DomainID, SrcClockDomain*> DVFSHandler::Domains [private]
Definition at line 205 of file dvfs_handler.hh.
typedef DVFSHandlerParams DVFSHandler::Params
Reimplemented from SimObject.
Definition at line 77 of file dvfs_handler.hh.
typedef SrcClockDomain::PerfLevel DVFSHandler::PerfLevel
Definition at line 81 of file dvfs_handler.hh.
typedef std::map<DomainID, UpdateEvent> DVFSHandler::UpdatePerfLevelEvents [private]
Definition at line 280 of file dvfs_handler.hh.
Constructor & Destructor Documentation
DVFSHandler::DVFSHandler (const Params * p)
Definition at line 58 of file dvfs_handler.cc.
References ArmISA::d, SrcClockDomain::domainID(), domainIDList, domains, DVFSHandler::UpdateEvent::dvfsHandler, SrcClockDomain::emptyDomainID, fatal_if, SimObject::name(), sysClkDomain, and updatePerfLevelEvents.
Member Function Documentation
Tick DVFSHandler::clkPeriodAtPerfLevel (DomainID domain_id, PerfLevel perf_level) const [inline]
Read the clock period of the specified domain at the specified performance level.
Parameters:
domain_id Domain ID to query
perf_level Performance level of interest
Returns:
Clock period in ticks for the requested performance level of the respective domain
Definition at line 138 of file dvfs_handler.hh.
References SrcClockDomain::clkPeriodAtPerfLevel(), ArmISA::d, findDomain(), ArmISA::n, SimObject::name(), SrcClockDomain::numPerfLevels(), and warn.
Referenced by EnergyCtrl::read().
DVFSHandler::DomainID DVFSHandler::domainID (uint32_t index) const
Get the n-th domain ID, from the domains managed by this handler.
Returns:
Domain ID
Definition at line 94 of file dvfs_handler.cc.
References domainIDList, domains, fatal_if, and numDomains().
Referenced by EnergyCtrl::read().
SrcClockDomain* DVFSHandler::findDomain (DomainID domain_id) const [inline, private]
Search for a domain based on the domain ID.
Parameters:
domain_id Domain ID to search for
Returns:
Pointer to the source clock domain with matching ID.
Definition at line 224 of file dvfs_handler.hh.
References domains, and panic_if.
Referenced by clkPeriodAtPerfLevel(), numPerfLevels(), perfLevel(), DVFSHandler::UpdateEvent::updatePerfLevel(), and voltageAtPerfLevel().
bool DVFSHandler::isEnabled () const [inline]
Check enable status of the DVFS handler, when the handler is disabled, no request should be sent to the handler.
Returns:
True, if the handler is enabled
Definition at line 199 of file dvfs_handler.hh.
References enableHandler.
Referenced by perfLevel(), EnergyCtrl::read(), EnergyCtrl::startup(), validDomainID(), and EnergyCtrl::write().
uint32_t DVFSHandler::numDomains () const [inline]
Get the number of domains assigned to this DVFS handler.
Returns:
Number of domains
Definition at line 87 of file dvfs_handler.hh.
References domainIDList.
Referenced by domainID(), and EnergyCtrl::read().
PerfLevel DVFSHandler::numPerfLevels (PerfLevel domain_id) const [inline]
Get the total number of available performance levels.
Parameters:
domain_id Domain ID to query
Returns:
Number of performance levels that where configured for the respective domain
Definition at line 189 of file dvfs_handler.hh.
References findDomain(), and SrcClockDomain::numPerfLevels().
Referenced by EnergyCtrl::read().
PerfLevel DVFSHandler::perfLevel (DomainID domain_id) const [inline]
Get the current performance level of a domain.
While a change request is in-flight, will return the current (i.e. old, unmodified) value.
Parameters:
domain_id Domain ID to query
Returns:
Current performance level of the specified domain
Definition at line 125 of file dvfs_handler.hh.
References findDomain(), isEnabled(), and SrcClockDomain::perfLevel().
bool DVFSHandler::perfLevel (DomainID domain_id, PerfLevel perf_level)
Set a new performance level for the specified domain.
The actual update will be delayed by transLatency().
Parameters:
domain_id Software visible ID of the domain to be configured
perf_level Requested performance level (0 - fast, >0 slower)
Returns:
status whether the setting was successful
Definition at line 118 of file dvfs_handler.cc.
References _transLatency, curTick(), ArmISA::d, EventManager::deschedule(), DPRINTF, findDomain(), isEnabled(), DVFSHandler::UpdateEvent::perfLevelToSet, EventManager::schedule(), Event::scheduled(), updatePerfLevelEvents, and warn.
Referenced by EnergyCtrl::read(), and EnergyCtrl::write().
void DVFSHandler::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 173 of file dvfs_handler.cc.
References arrayParamOut(), enableHandler, MipsISA::event, SERIALIZE_SCALAR, and updatePerfLevelEvents.
Tick DVFSHandler::transLatency () const [inline]
Get transition latency to switch between performance levels.
Returns:
Transition latency
Definition at line 106 of file dvfs_handler.hh.
References _transLatency.
Referenced by EnergyCtrl::read(), and EnergyCtrl::write().
void DVFSHandler::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 201 of file dvfs_handler.cc.
References arrayParamIn(), DVFSHandler::UpdateEvent::dvfsHandler, enableHandler, MipsISA::event, ArmISA::i, EventManager::schedule(), UNSERIALIZE_SCALAR, updatePerfLevelEvents, and warn.
bool DVFSHandler::validDomainID (DomainID domain_id) const
Check whether a domain ID is known to the handler or not.
Parameters:
domain_id Domain ID to check
Returns:
Domain ID known to handler?
Definition at line 105 of file dvfs_handler.cc.
References domains, isEnabled(), and warn.
Referenced by EnergyCtrl::write().
double DVFSHandler::voltageAtPerfLevel (DomainID domain_id, PerfLevel perf_level) const [inline]
Read the voltage of the specified domain at the specified performance level.
Parameters:
domain_id Domain ID to query
perf_level Performance level of interest
Returns:
Voltage for the requested performance level of the respective domain
Definition at line 159 of file dvfs_handler.hh.
References ArmISA::d, DPRINTF, findDomain(), ArmISA::n, SimObject::name(), VoltageDomain::numVoltages(), VoltageDomain::voltage(), ClockDomain::voltageDomain(), and warn.
Referenced by EnergyCtrl::read().
Member Data Documentation
const Tick DVFSHandler::_transLatency [private]
This corresponds to the maximum transition latency associated with the hardware transitioning from a particular performance level to the other.
Definition at line 242 of file dvfs_handler.hh.
Referenced by perfLevel(), and transLatency().
std::vector<DomainID> DVFSHandler::domainIDList [private]
List of IDs avaiable in the domain list.
Definition at line 211 of file dvfs_handler.hh.
Referenced by domainID(), DVFSHandler(), and numDomains().
Domains DVFSHandler::domains [private]
Definition at line 206 of file dvfs_handler.hh.
Referenced by domainID(), DVFSHandler(), findDomain(), and validDomainID().
bool DVFSHandler::enableHandler [private]
Disabling the DVFS handler ensures that all the DVFS migration requests are ignored.
Domains remain at their default frequency and voltage.
Definition at line 235 of file dvfs_handler.hh.
Referenced by isEnabled(), serialize(), and unserialize().
SrcClockDomain* DVFSHandler::sysClkDomain [private]
Clock domain of the system the handler is instantiated.
Definition at line 216 of file dvfs_handler.hh.
Referenced by DVFSHandler().
UpdatePerfLevelEvents DVFSHandler::updatePerfLevelEvents [private]
Map from domain IDs -> perf level update events, records in-flight change requests per domain ID.
Definition at line 285 of file dvfs_handler.hh.
Referenced by DVFSHandler(), perfLevel(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
sim/dvfs_handler.hh
sim/dvfs_handler.cc