gem5: SnapMemCtrl::AddressTable Class Reference
SnapMemCtrl::AddressTable Class Reference
Public Member Functions
AddressTable (int _size)
AddressTable ()
bool isFull ()
void push (Addr addr)
Addr pop ()
void erase (Addr addr)
bool isExist (Addr addr)
bool isEmpty ()
uint64_t getSize ()
Private Attributes
int size
std::set< Addr > table
Detailed Description
Definition at line 106 of file snap_mem_ctrl.hh.
Constructor & Destructor Documentation
SnapMemCtrl::AddressTable::AddressTable (int _size) [inline]
Definition at line 111 of file snap_mem_ctrl.hh.
References size, and table.
SnapMemCtrl::AddressTable::AddressTable () [inline]
Definition at line 112 of file snap_mem_ctrl.hh.
References size, and table.
Member Function Documentation
void SnapMemCtrl::AddressTable::erase (Addr addr) [inline]
Definition at line 116 of file snap_mem_ctrl.hh.
References table.
Referenced by pop(), and SnapMemCtrl::recvTimingSnapperPort().
uint64_t SnapMemCtrl::AddressTable::getSize () [inline]
Definition at line 119 of file snap_mem_ctrl.hh.
References table.
Referenced by SnapMemCtrl::snapshot().
bool SnapMemCtrl::AddressTable::isEmpty () [inline]
Definition at line 118 of file snap_mem_ctrl.hh.
References table.
Referenced by SnapMemCtrl::sendReadPacketToNormalMemory(), and SnapMemCtrl::snapshotCycle().
bool SnapMemCtrl::AddressTable::isExist (Addr addr) [inline]
Definition at line 117 of file snap_mem_ctrl.hh.
References table.
Referenced by SnapMemCtrl::catchSnapReadResponsePacket(), and SnapMemCtrl::sendReadPacketToNormalMemory().
bool SnapMemCtrl::AddressTable::isFull () [inline]
Definition at line 113 of file snap_mem_ctrl.hh.
References size, and table.
Referenced by push(), and SnapMemCtrl::sendReadPacketToNormalMemory().
Addr SnapMemCtrl::AddressTable::pop () [inline]
Definition at line 115 of file snap_mem_ctrl.hh.
References X86ISA::addr, erase(), and table.
Referenced by SnapMemCtrl::sendReadPacketToNormalMemory().
void SnapMemCtrl::AddressTable::push (Addr addr) [inline]
Definition at line 114 of file snap_mem_ctrl.hh.
References isFull(), and table.
Referenced by SnapMemCtrl::catchWriteRequestPacket(), and SnapMemCtrl::sendReadPacketToNormalMemory().
Member Data Documentation
int SnapMemCtrl::AddressTable::size [private]
Definition at line 108 of file snap_mem_ctrl.hh.
Referenced by AddressTable(), and isFull().
std::set<Addr> SnapMemCtrl::AddressTable::table [private]
Definition at line 109 of file snap_mem_ctrl.hh.
Referenced by AddressTable(), erase(), getSize(), isEmpty(), isExist(), isFull(), pop(), and push().
The documentation for this class was generated from the following file:
mem/snapmem/snap_mem_ctrl.hh