gem5: BaseCache Class Reference
BaseCache Class Reference
A basic cache interface.
#include <base.hh>
Classes
class CacheMasterPort
A cache master port is used for the memory-side port of the cache, and in addition to the basic timing port that only sends response packets through a transmit list, it also offers the ability to schedule and send request packets (requests & writebacks).
class CacheSlavePort
A cache slave port is used for the CPU-side port of the cache, and it is basically a simple timing port that uses a transmit list for responses to the CPU (or connected master).
Public Types
enum BlockedCause { Blocked_NoMSHRs = MSHRQueue_MSHRs, Blocked_NoWBBuffers = MSHRQueue_WriteBuffer, Blocked_NoTargets, NUM_BLOCKED_CAUSES }
Reasons for caches to be blocked.
enum RequestCause { Request_MSHR = MSHRQueue_MSHRs, Request_WB = MSHRQueue_WriteBuffer, Request_PF, NUM_REQUEST_CAUSES }
Reasons for cache to request a bus.
typedef BaseCacheParams Params
Public Member Functions
virtual void regStats ()
Register stats for this object.
BaseCache (const Params *p)
~BaseCache ()
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
virtual BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
unsigned getBlockSize () const
Query block size of a cache.
Addr blockAlign (Addr addr) const
const AddrRangeList & getAddrRanges () const
MSHR * allocateMissBuffer (PacketPtr pkt, Tick time, bool requestBus)
MSHR * allocateWriteBuffer (PacketPtr pkt, Tick time, bool requestBus)
bool isBlocked () const
Returns true if the cache is blocked for accesses.
void setBlocked (BlockedCause cause)
Marks the access path of the cache as blocked for the given cause.
void clearBlocked (BlockedCause cause)
Marks the cache as unblocked for the given cause.
void requestMemSideBus (RequestCause cause, Tick time)
Request the master bus for the given cause and time.
void deassertMemSideBusRequest (RequestCause cause)
Clear the master bus request for the given cause.
virtual unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
virtual bool inCache (Addr addr, bool is_secure) const =0
virtual bool inMissQueue (Addr addr, bool is_secure) const =0
void incMissCount (PacketPtr pkt)
void incHitCount (PacketPtr pkt)
Public Attributes
System * system
System we are currently operating in.
Stats::Vector hits [MemCmd::NUM_MEM_CMDS]
Number of hits per thread for each type of command.
Stats::Formula demandHits
Number of hits for demand accesses.
Stats::Formula overallHits
Number of hit for all accesses.
Stats::Vector misses [MemCmd::NUM_MEM_CMDS]
Number of misses per thread for each type of command.
Stats::Formula demandMisses
Number of misses for demand accesses.
Stats::Formula overallMisses
Number of misses for all accesses.
Stats::Vector missLatency [MemCmd::NUM_MEM_CMDS]
Total number of cycles per thread/command spent waiting for a miss.
Stats::Formula demandMissLatency
Total number of cycles spent waiting for demand misses.
Stats::Formula overallMissLatency
Total number of cycles spent waiting for all misses.
Stats::Formula accesses [MemCmd::NUM_MEM_CMDS]
The number of accesses per command and thread.
Stats::Formula demandAccesses
The number of demand accesses.
Stats::Formula overallAccesses
The number of overall accesses.
Stats::Formula missRate [MemCmd::NUM_MEM_CMDS]
The miss rate per command and thread.
Stats::Formula demandMissRate
The miss rate of all demand accesses.
Stats::Formula overallMissRate
The miss rate for all accesses.
Stats::Formula avgMissLatency [MemCmd::NUM_MEM_CMDS]
The average miss latency per command and thread.
Stats::Formula demandAvgMissLatency
The average miss latency for demand misses.
Stats::Formula overallAvgMissLatency
The average miss latency for all misses.
Stats::Vector blocked_cycles
The total number of cycles blocked for each blocked cause.
Stats::Vector blocked_causes
The number of times this cache blocked for each blocked cause.
Stats::Formula avg_blocked
The average number of cycles blocked for each blocked cause.
Stats::Scalar fastWrites
The number of fast writes (WH64) performed.
Stats::Scalar cacheCopies
The number of cache copies performed.
Stats::Vector writebacks
Number of blocks written back per thread.
Stats::Vector mshr_hits [MemCmd::NUM_MEM_CMDS]
Number of misses that hit in the MSHRs per command and thread.
Stats::Formula demandMshrHits
Demand misses that hit in the MSHRs.
Stats::Formula overallMshrHits
Total number of misses that hit in the MSHRs.
Stats::Vector mshr_misses [MemCmd::NUM_MEM_CMDS]
Number of misses that miss in the MSHRs, per command and thread.
Stats::Formula demandMshrMisses
Demand misses that miss in the MSHRs.
Stats::Formula overallMshrMisses
Total number of misses that miss in the MSHRs.
Stats::Vector mshr_uncacheable [MemCmd::NUM_MEM_CMDS]
Number of misses that miss in the MSHRs, per command and thread.
Stats::Formula overallMshrUncacheable
Total number of misses that miss in the MSHRs.
Stats::Vector mshr_miss_latency [MemCmd::NUM_MEM_CMDS]
Total cycle latency of each MSHR miss, per command and thread.
Stats::Formula demandMshrMissLatency
Total cycle latency of demand MSHR misses.
Stats::Formula overallMshrMissLatency
Total cycle latency of overall MSHR misses.
Stats::Vector mshr_uncacheable_lat [MemCmd::NUM_MEM_CMDS]
Total cycle latency of each MSHR miss, per command and thread.
Stats::Formula overallMshrUncacheableLatency
Total cycle latency of overall MSHR misses.
Stats::Formula mshrMissRate [MemCmd::NUM_MEM_CMDS]
The miss rate in the MSHRs pre command and thread.
Stats::Formula demandMshrMissRate
The demand miss rate in the MSHRs.
Stats::Formula overallMshrMissRate
The overall miss rate in the MSHRs.
Stats::Formula avgMshrMissLatency [MemCmd::NUM_MEM_CMDS]
The average latency of an MSHR miss, per command and thread.
Stats::Formula demandAvgMshrMissLatency
The average latency of a demand MSHR miss.
Stats::Formula overallAvgMshrMissLatency
The average overall latency of an MSHR miss.
Stats::Formula avgMshrUncacheableLatency [MemCmd::NUM_MEM_CMDS]
The average latency of an MSHR miss, per command and thread.
Stats::Formula overallAvgMshrUncacheableLatency
The average overall latency of an MSHR miss.
Stats::Vector mshr_cap_events
The number of times a thread hit its MSHR cap.
Stats::Vector soft_prefetch_mshr_full
The number of times software prefetches caused the MSHR to block.
Stats::Scalar mshr_no_allocate_misses
Protected Member Functions
MSHR * allocateBufferInternal (MSHRQueue *mq, Addr addr, int size, PacketPtr pkt, Tick time, bool requestBus)
Allocate a buffer, passing the time indicating when schedule an event to the queued port to go and ask the MSHR and write queue if they have packets to send.
void markInServiceInternal (MSHR *mshr, bool pending_dirty_resp)
virtual void memWriteback ()=0
Write back dirty blocks in the cache using functional accesses.
virtual void memInvalidate ()=0
Invalidates all blocks in the cache.
virtual bool isDirty () const =0
Determine if there are any dirty blocks in the cache.
bool inRange (Addr addr) const
Determine if an address is in the ranges covered by this cache.
Protected Attributes
CacheSlavePort * cpuSidePort
CacheMasterPort * memSidePort
MSHRQueue mshrQueue
Miss status registers.
MSHRQueue writeBuffer
Write/writeback buffer.
const unsigned blkSize
Block size of this cache.
const Cycles lookupLatency
The latency of tag lookup of a cache.
const Cycles forwardLatency
This is the forward latency of the cache.
const Cycles fillLatency
The latency to fill a cache block.
const Cycles responseLatency
The latency of sending reponse to its upper level cache/core on a linefill.
const int numTarget
The number of targets for each MSHR.
const bool forwardSnoops
Do we forward snoops from mem side port through to cpu side port?
const bool isTopLevel
Is this cache a toplevel cache (e.g.
uint8_t blocked
Bit vector of the blocking reasons for the access path.
uint64_t order
Increasing order number assigned to each incoming request.
Cycles blockedCycle
Stores time the cache blocked for statistics.
MSHR * noTargetMSHR
Pointer to the MSHR that has no targets.
Counter missCount
The number of misses to trigger an exit event.
const AddrRangeList addrRanges
The address range to which the cache responds on the CPU side.
Private Types
enum MSHRQueueIndex { MSHRQueue_MSHRs, MSHRQueue_WriteBuffer }
Indexes to enumerate the MSHR queues.
Detailed Description
A basic cache interface.
Implements some common functions for speed.
Definition at line 79 of file base.hh.
Member Typedef Documentation
typedef BaseCacheParams BaseCache::Params
Reimplemented from MemObject.
Definition at line 483 of file base.hh.
Member Enumeration Documentation
enum BaseCache::BlockedCause
Reasons for caches to be blocked.
Enumerator:
Blocked_NoMSHRs
Blocked_NoWBBuffers
Blocked_NoTargets
NUM_BLOCKED_CAUSES
Definition at line 93 of file base.hh.
enum BaseCache::MSHRQueueIndex [private]
Indexes to enumerate the MSHR queues.
Enumerator:
MSHRQueue_MSHRs
MSHRQueue_WriteBuffer
Definition at line 84 of file base.hh.
enum BaseCache::RequestCause
Reasons for cache to request a bus.
Enumerator:
Request_MSHR
Request_WB
Request_PF
NUM_REQUEST_CAUSES
Definition at line 103 of file base.hh.
Constructor & Destructor Documentation
BaseCache::BaseCache (const Params * p)
Definition at line 68 of file base.cc.
BaseCache::~BaseCache () [inline]
Definition at line 485 of file base.hh.
Member Function Documentation
MSHR* BaseCache::allocateBufferInternal (MSHRQueue * mq, Addr addr, int size, PacketPtr pkt, Tick time, bool requestBus) [inline, protected]
Allocate a buffer, passing the time indicating when schedule an event to the queued port to go and ask the MSHR and write queue if they have packets to send.
allocateBufferInternal() function is called in:
MSHR allocateWriteBuffer (unchached write forwarded to WriteBuffer);
MSHR allocateMissBuffer (miss in MSHR queue);
Definition at line 215 of file base.hh.
References MSHRQueue::allocate(), blockAlign(), MSHRQueue::index, MSHRQueue::isFull(), order, requestMemSideBus(), and setBlocked().
Referenced by allocateMissBuffer(), and allocateWriteBuffer().
MSHR* BaseCache::allocateMissBuffer (PacketPtr pkt, Tick time, bool requestBus) [inline]
Definition at line 510 of file base.hh.
References allocateBufferInternal(), blkSize, blockAlign(), Packet::getAddr(), and mshrQueue.
Referenced by Cache::getNextMSHR(), and Cache::recvTimingReq().
MSHR* BaseCache::allocateWriteBuffer (PacketPtr pkt, Tick time, bool requestBus) [inline]
Definition at line 517 of file base.hh.
References allocateBufferInternal(), blkSize, blockAlign(), Packet::getAddr(), Packet::isRead(), Packet::isWrite(), and writeBuffer.
Referenced by Cache::recvTimingReq(), and Cache::recvTimingResp().
Addr BaseCache::blockAlign (Addr addr) const [inline]
Definition at line 505 of file base.hh.
References blkSize.
Referenced by allocateBufferInternal(), allocateMissBuffer(), allocateWriteBuffer(), Cache::functionalAccess(), Cache::getBusPacket(), Cache::getNextMSHR(), Cache::recvTimingReq(), and Cache::recvTimingSnoopReq().
void BaseCache::clearBlocked (BlockedCause cause) [inline]
Marks the cache as unblocked for the given cause.
This also clears the blocked flags in the appropriate interfaces.
Parameters:
cause The newly unblocked cause.
Warning:
Calling this function can cause a blocked request on the bus to access the cache. The cache must be in a state to handle that request.
Definition at line 557 of file base.hh.
References blocked, blocked_cycles, blockedCycle, BaseCache::CacheSlavePort::clearBlocked(), cpuSidePort, ClockedObject::curCycle(), and DPRINTF.
Referenced by Cache::getTimingPacket(), markInServiceInternal(), Cache::recvTimingResp(), and Cache::squash().
void BaseCache::deassertMemSideBusRequest (RequestCause cause) [inline]
Clear the master bus request for the given cause.
Parameters:
cause The request reason to clear.
Definition at line 582 of file base.hh.
Referenced by Cache::markInService(), and QueuedPrefetcher::notify().
unsigned int BaseCache::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 778 of file base.cc.
References X86ISA::count, cpuSidePort, DPRINTF, MSHRQueue::drain(), QueuedSlavePort::drain(), QueuedMasterPort::drain(), Drainable::Drained, Drainable::Draining, memSidePort, mshrQueue, Drainable::setDrainState(), and writeBuffer.
const AddrRangeList& BaseCache::getAddrRanges () const [inline]
Definition at line 508 of file base.hh.
References addrRanges.
Referenced by Cache::CpuSidePort::getAddrRanges().
unsigned BaseCache::getBlockSize () const [inline]
Query block size of a cache.
Returns:
The block size
Definition at line 499 of file base.hh.
References blkSize.
Referenced by BasePrefetcher::setCache().
BaseMasterPort & BaseCache::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 137 of file base.cc.
References memSidePort.
BaseSlavePort & BaseCache::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 147 of file base.cc.
References cpuSidePort.
virtual bool BaseCache::inCache (Addr addr, bool is_secure) const [pure virtual]
Implemented in Cache.
Referenced by BasePrefetcher::inCache().
void BaseCache::incHitCount (PacketPtr pkt) [inline]
Definition at line 608 of file base.hh.
References Packet::cmdToIndex(), hits, Request::masterId(), System::maxMasters(), Packet::req, and system.
Referenced by Cache::access().
void BaseCache::incMissCount (PacketPtr pkt) [inline]
Definition at line 597 of file base.hh.
References Packet::cmdToIndex(), exitSimLoop(), Request::incAccessDepth(), Request::masterId(), System::maxMasters(), missCount, misses, Packet::req, and system.
Referenced by Cache::access().
void BaseCache::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 129 of file base.cc.
References cpuSidePort, fatal, BaseMasterPort::isConnected(), BaseSlavePort::isConnected(), memSidePort, SimObject::name(), and SlavePort::sendRangeChange().
virtual bool BaseCache::inMissQueue (Addr addr, bool is_secure) const [pure virtual]
Implemented in Cache.
Referenced by BasePrefetcher::inMissQueue().
bool BaseCache::inRange (Addr addr) const [protected]
Determine if an address is in the ranges covered by this cache.
This is useful to filter snoops.
Parameters:
addr Address to check against
Returns:
If the address in question is in range
Definition at line 157 of file base.cc.
References addrRanges, and MipsISA::r.
Referenced by Cache::recvAtomicSnoop(), and Cache::recvTimingSnoopReq().
bool BaseCache::isBlocked () const [inline]
Returns true if the cache is blocked for accesses.
Definition at line 528 of file base.hh.
References blocked.
virtual bool BaseCache::isDirty () const [protected, pure virtual]
Determine if there are any dirty blocks in the cache.
Returns:
true if at least one block is dirty, false otherwise.
Implemented in Cache.
void BaseCache::markInServiceInternal (MSHR * mshr, bool pending_dirty_resp) [inline, protected]
Definition at line 236 of file base.hh.
References clearBlocked(), MSHRQueue::index, MSHRQueue::isFull(), MSHRQueue::markInService(), and MSHR::queue.
Referenced by Cache::markInService().
virtual void BaseCache::memInvalidate () [protected, pure virtual]
Invalidates all blocks in the cache.
Dirty cache lines will not be written back to memory. Make sure to call functionalWriteback() first if you want the to write them to memory.
Reimplemented from Drainable.
Implemented in Cache.
virtual void BaseCache::memWriteback () [protected, pure virtual]
Write back dirty blocks in the cache using functional accesses.
Reimplemented from Drainable.
Implemented in Cache.
void BaseCache::regStats () [virtual]
Register stats for this object.
Reimplemented from SimObject.
Reimplemented in Cache.
Definition at line 168 of file base.cc.
References accesses, avg_blocked, avgMissLatency, avgMshrMissLatency, avgMshrUncacheableLatency, blocked_causes, blocked_cycles, Blocked_NoMSHRs, Blocked_NoTargets, cacheCopies, demandAccesses, demandAvgMissLatency, demandAvgMshrMissLatency, demandHits, demandMisses, demandMissLatency, demandMissRate, demandMshrHits, demandMshrMisses, demandMshrMissLatency, demandMshrMissRate, fastWrites, System::getMasterName(), hits, ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), System::maxMasters(), misses, missLatency, missRate, mshr_cap_events, mshr_hits, mshr_miss_latency, mshr_misses, mshr_no_allocate_misses, mshr_uncacheable, mshr_uncacheable_lat, mshrMissRate, Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), Stats::nonan, Stats::nozero, NUM_BLOCKED_CAUSES, MemCmd::NUM_MEM_CMDS, overallAccesses, overallAvgMissLatency, overallAvgMshrMissLatency, overallAvgMshrUncacheableLatency, overallHits, overallMisses, overallMissLatency, overallMissRate, overallMshrHits, overallMshrMisses, overallMshrMissLatency, overallMshrMissRate, overallMshrUncacheable, overallMshrUncacheableLatency, soft_prefetch_mshr_full, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), SUM_DEMAND, SUM_NON_DEMAND, system, MemCmd::toString(), Stats::total, and writebacks.
void BaseCache::requestMemSideBus (RequestCause cause, Tick time) [inline]
Request the master bus for the given cause and time.
Parameters:
cause The reason for the request.
time The time to make the request.
Definition at line 573 of file base.hh.
References memSidePort, and BaseCache::CacheMasterPort::requestBus().
Referenced by allocateBufferInternal(), Cache::recvTimingReq(), and Cache::recvTimingResp().
void BaseCache::setBlocked (BlockedCause cause) [inline]
Marks the access path of the cache as blocked for the given cause.
This also sets the blocked flag in the slave interface.
Parameters:
cause The reason for the cache blocking.
Definition at line 538 of file base.hh.
References blocked, blocked_causes, blockedCycle, cpuSidePort, ClockedObject::curCycle(), DPRINTF, and BaseCache::CacheSlavePort::setBlocked().
Referenced by allocateBufferInternal(), and Cache::recvTimingReq().
Member Data Documentation
const AddrRangeList BaseCache::addrRanges [protected]
The address range to which the cache responds on the CPU side.
Normally this is all possible memory addresses.
Definition at line 333 of file base.hh.
Referenced by getAddrRanges(), and inRange().
const unsigned BaseCache::blkSize [protected]
Block size of this cache.
Definition at line 276 of file base.hh.
Referenced by Cache::access(), allocateMissBuffer(), allocateWriteBuffer(), blockAlign(), Cache::Cache(), Cache::doTimingSupplyResponse(), Cache::functionalAccess(), getBlockSize(), Cache::getBusPacket(), Cache::handleFill(), Cache::handleSnoop(), Cache::promoteWholeLineWrites(), Cache::recvTimingResp(), Cache::satisfyCpuSideRequest(), Cache::writebackBlk(), and Cache::writebackVisitor().
uint8_t BaseCache::blocked [protected]
Bit vector of the blocking reasons for the access path.
See also:
BlockedCause
Definition at line 316 of file base.hh.
Referenced by clearBlocked(), isBlocked(), Cache::CpuSidePort::recvTimingReq(), and setBlocked().
Cycles BaseCache::blockedCycle [protected]
Stores time the cache blocked for statistics.
Definition at line 322 of file base.hh.
Referenced by clearBlocked(), and setBlocked().
CacheSlavePort* BaseCache::cpuSidePort [protected]
Definition at line 195 of file base.hh.
Referenced by Cache::Cache(), clearBlocked(), drain(), Cache::functionalAccess(), getSlavePort(), Cache::getTimingPacket(), Cache::handleSnoop(), init(), Cache::recvTimingReq(), Cache::recvTimingResp(), setBlocked(), and Cache::~Cache().
const Cycles BaseCache::fillLatency [protected]
The latency to fill a cache block.
Definition at line 292 of file base.hh.
Referenced by Cache::handleFill().
const Cycles BaseCache::forwardLatency [protected]
This is the forward latency of the cache.
It occurs when there is a cache miss and a request is forwarded downstream, in particular an outbound miss.
Definition at line 289 of file base.hh.
Referenced by Cache::doTimingSupplyResponse(), Cache::recvAtomicSnoop(), Cache::recvTimingReq(), Cache::recvTimingResp(), and Cache::recvTimingSnoopResp().
const bool BaseCache::forwardSnoops [protected]
Do we forward snoops from mem side port through to cpu side port?
Definition at line 305 of file base.hh.
Referenced by Cache::functionalAccess(), Cache::getTimingPacket(), and Cache::handleSnoop().
const bool BaseCache::isTopLevel [protected]
Is this cache a toplevel cache (e.g.
L1, I/O cache). If so we should never try to forward ownership and similar optimizations to the cpu side
Definition at line 310 of file base.hh.
Referenced by Cache::promoteWholeLineWrites(), Cache::recvAtomic(), Cache::recvTimingReq(), Cache::recvTimingResp(), and Cache::satisfyCpuSideRequest().
const Cycles BaseCache::lookupLatency [protected]
The latency of tag lookup of a cache.
It occurs when there is an access to the cache.
Definition at line 282 of file base.hh.
Referenced by Cache::access(), Cache::recvAtomic(), and Cache::recvTimingReq().
CacheMasterPort* BaseCache::memSidePort [protected]
Definition at line 196 of file base.hh.
Referenced by Cache::Cache(), Cache::doTimingSupplyResponse(), drain(), Cache::functionalAccess(), getMasterPort(), init(), Cache::recvAtomic(), Cache::recvTimingReq(), Cache::recvTimingSnoopResp(), requestMemSideBus(), Cache::writebackVisitor(), and Cache::~Cache().
Counter BaseCache::missCount [protected]
The number of misses to trigger an exit event.
Definition at line 328 of file base.hh.
Referenced by incMissCount().
MSHRQueue BaseCache::mshrQueue [protected]
Miss status registers.
Definition at line 201 of file base.hh.
Referenced by Cache::allocateBlock(), allocateMissBuffer(), drain(), Cache::functionalAccess(), Cache::getNextMSHR(), Cache::inMissQueue(), Cache::nextMSHRReadyTime(), Cache::outstandingMisses(), Cache::recvTimingReq(), Cache::recvTimingResp(), Cache::recvTimingSnoopReq(), and Cache::squash().
MSHR* BaseCache::noTargetMSHR [protected]
Pointer to the MSHR that has no targets.
Definition at line 325 of file base.hh.
Referenced by Cache::recvTimingReq(), Cache::recvTimingResp(), and Cache::squash().
const int BaseCache::numTarget [protected]
The number of targets for each MSHR.
Definition at line 302 of file base.hh.
Referenced by Cache::recvTimingReq(), and Cache::recvTimingSnoopReq().
uint64_t BaseCache::order [protected]
Increasing order number assigned to each incoming request.
Definition at line 319 of file base.hh.
Referenced by allocateBufferInternal(), Cache::recvTimingReq(), and Cache::recvTimingSnoopReq().
const Cycles BaseCache::responseLatency [protected]
The latency of sending reponse to its upper level cache/core on a linefill.
The responseLatency parameter captures this latency.
Definition at line 299 of file base.hh.
Referenced by Cache::recvTimingResp().
System* BaseCache::system
System we are currently operating in.
Definition at line 337 of file base.hh.
Referenced by Cache::functionalAccess(), Cache::getNextMSHR(), incHitCount(), incMissCount(), BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), Cache::recvAtomic(), Cache::recvAtomicSnoop(), Cache::CpuSidePort::recvTimingReq(), Cache::recvTimingReq(), Cache::recvTimingResp(), Cache::recvTimingSnoopReq(), Cache::recvTimingSnoopResp(), BaseTags::regStats(), and regStats().
MSHRQueue BaseCache::writeBuffer [protected]
Write/writeback buffer.
Definition at line 204 of file base.hh.
Referenced by allocateWriteBuffer(), drain(), Cache::functionalAccess(), Cache::getNextMSHR(), Cache::nextMSHRReadyTime(), and Cache::recvTimingSnoopReq().
The documentation for this class was generated from the following files:
mem/cache/base.hh
mem/cache/base.cc