gem5: BaseCache::CacheSlavePort Class Reference
BaseCache::CacheSlavePort Class Reference
A cache slave port is used for the CPU-side port of the cache, and it is basically a simple timing port that uses a transmit list for responses to the CPU (or connected master).
#include <base.hh>
Public Member Functions
void setBlocked ()
Do not accept any new requests.
void clearBlocked ()
Return to normal operation and accept new requests.
bool isBlocked () const
Protected Member Functions
CacheSlavePort (const std::string &_name, BaseCache *_cache, const std::string &_label)
Protected Attributes
RespPacketQueue queue
A normal packet queue used to store responses.
bool blocked
bool mustSendRetry
Private Member Functions
void processSendRetry ()
Private Attributes
EventWrapper< CacheSlavePort,&CacheSlavePort::processSendRetry > sendRetryEvent
Detailed Description
A cache slave port is used for the CPU-side port of the cache, and it is basically a simple timing port that uses a transmit list for responses to the CPU (or connected master).
In addition, it has the functionality to block the port for incoming requests. If blocked, the port will issue a retry once unblocked.
Definition at line 161 of file base.hh.
Constructor & Destructor Documentation
BaseCache::CacheSlavePort::CacheSlavePort (const std::string & _name, BaseCache * _cache, const std::string & _label) [protected]
Definition at line 60 of file base.cc.
Member Function Documentation
void BaseCache::CacheSlavePort::clearBlocked ()
Return to normal operation and accept new requests.
Definition at line 107 of file base.cc.
References blocked, curTick(), DPRINTF, mustSendRetry, Port::owner, EventManager::schedule(), and sendRetryEvent.
Referenced by BaseCache::clearBlocked().
bool BaseCache::CacheSlavePort::isBlocked () const [inline]
Definition at line 172 of file base.hh.
References blocked.
void BaseCache::CacheSlavePort::processSendRetry () [private]
Definition at line 119 of file base.cc.
References DPRINTF, mustSendRetry, and SlavePort::sendRetryReq().
void BaseCache::CacheSlavePort::setBlocked ()
Do not accept any new requests.
Definition at line 92 of file base.cc.
References blocked, EventManager::deschedule(), DPRINTF, mustSendRetry, Port::owner, Event::scheduled(), and sendRetryEvent.
Referenced by BaseCache::setBlocked().
Member Data Documentation
bool BaseCache::CacheSlavePort::blocked [protected]
Definition at line 182 of file base.hh.
Referenced by clearBlocked(), isBlocked(), and setBlocked().
bool BaseCache::CacheSlavePort::mustSendRetry [protected]
Definition at line 184 of file base.hh.
Referenced by clearBlocked(), processSendRetry(), and setBlocked().
RespPacketQueue BaseCache::CacheSlavePort::queue [protected]
A normal packet queue used to store responses.
Definition at line 180 of file base.hh.
EventWrapper<CacheSlavePort, &CacheSlavePort::processSendRetry> BaseCache::CacheSlavePort::sendRetryEvent [private]
Definition at line 191 of file base.hh.
Referenced by clearBlocked(), and setBlocked().
The documentation for this class was generated from the following files:
mem/cache/base.hh
mem/cache/base.cc