gem5: Cache::CacheReqPacketQueue Class Reference
Cache::CacheReqPacketQueue Class Reference
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
#include <cache.hh>
Public Member Functions
CacheReqPacketQueue (Cache &cache, MasterPort &port, SnoopRespPacketQueue &snoop_resp_queue, const std::string &label)
virtual void sendDeferredPacket ()
Override the normal sendDeferredPacket and do not only consider the transmit list (used for responses), but also requests.
Protected Attributes
Cache & cache
SnoopRespPacketQueue & snoopRespQueue
Detailed Description
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
This queue has a pointer to our specific cache implementation and is used by the MemSidePort.
Definition at line 121 of file cache.hh.
Constructor & Destructor Documentation
Cache::CacheReqPacketQueue::CacheReqPacketQueue (Cache & cache, MasterPort & port, SnoopRespPacketQueue & snoop_resp_queue, const std::string & label) [inline]
Definition at line 131 of file cache.hh.
Member Function Documentation
void Cache::CacheReqPacketQueue::sendDeferredPacket () [virtual]
Override the normal sendDeferredPacket and do not only consider the transmit list (used for responses), but also requests.
Reimplemented from PacketQueue.
Definition at line 2209 of file cache_impl.hh.
References cache, PacketQueue::deferredPacketReadyTime(), DPRINTF, Packet::getAddr(), Cache::getTimingPacket(), PacketQueue::hasAddr(), MSHR::isForwardNoResponse(), Cache::markInService(), ReqPacketQueue::masterPort, MaxTick, Packet::memInhibitAsserted(), Cache::nextMSHRReadyTime(), PacketQueue::schedSendEvent(), Packet::senderState, MasterPort::sendTimingReq(), Packet::sharedAsserted(), snoopRespQueue, and PacketQueue::waitingOnRetry.
Member Data Documentation
Cache& Cache::CacheReqPacketQueue::cache [protected]
Definition at line 126 of file cache.hh.
Referenced by sendDeferredPacket().
SnoopRespPacketQueue& Cache::CacheReqPacketQueue::snoopRespQueue [protected]
Definition at line 127 of file cache.hh.
Referenced by sendDeferredPacket().
The documentation for this class was generated from the following files:
mem/cache/cache.hh
mem/cache/cache_impl.hh