gem5: X86ISA::Walker Class Reference
X86ISA::Walker Class Reference
#include <pagetable_walker.hh>
Classes
class WalkerPort
struct WalkerSenderState
class WalkerState
Public Types
typedef X86PagetableWalkerParams Params
Public Member Functions
Fault start (ThreadContext *_tc, BaseTLB::Translation *translation, RequestPtr req, BaseTLB::Mode mode)
Fault startFunctional (ThreadContext *_tc, Addr &addr, unsigned &logBytes, BaseTLB::Mode mode)
BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
void setTLB (TLB *_tlb)
const Params * params () const
Walker (const Params *params)
Protected Member Functions
void startWalkWrapper ()
bool recvTimingResp (PacketPtr pkt)
void recvReqRetry ()
bool sendTiming (WalkerState *sendingState, PacketPtr pkt)
Protected Attributes
WalkerPort port
std::list< WalkerState * > currStates
WalkerState funcState
TLB * tlb
System * sys
MasterID masterId
unsigned numSquashable
EventWrapper< Walker,&Walker::startWalkWrapper > startWalkWrapperEvent
Event used to call startWalkWrapper.
Friends
class WalkerPort
class WalkerState
Detailed Description
Definition at line 58 of file pagetable_walker.hh.
Member Typedef Documentation
typedef X86PagetableWalkerParams X86ISA::Walker::Params
Reimplemented from MemObject.
Definition at line 195 of file pagetable_walker.hh.
Constructor & Destructor Documentation
X86ISA::Walker::Walker (const Params * params) [inline]
Definition at line 203 of file pagetable_walker.hh.
Member Function Documentation
BaseMasterPort & X86ISA::Walker::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 170 of file pagetable_walker.cc.
References port.
Referenced by X86ISA::TLB::getMasterPort().
const Params* X86ISA::Walker::params () const [inline]
Reimplemented from MemObject.
Definition at line 198 of file pagetable_walker.hh.
References SimObject::_params.
void X86ISA::Walker::recvReqRetry () [protected]
Definition at line 142 of file pagetable_walker.cc.
References currStates, X86ISA::Walker::WalkerState::isRetrying(), and X86ISA::Walker::WalkerState::retry().
Referenced by X86ISA::Walker::WalkerPort::recvReqRetry().
bool X86ISA::Walker::recvTimingResp (PacketPtr pkt) [protected]
Definition at line 108 of file pagetable_walker.cc.
References ClockedObject::clockEdge(), currStates, Packet::popSenderState(), X86ISA::Walker::WalkerState::recvPacket(), EventManager::schedule(), Event::scheduled(), X86ISA::Walker::WalkerSenderState::senderWalk, and startWalkWrapperEvent.
Referenced by X86ISA::Walker::WalkerPort::recvTimingResp().
bool X86ISA::Walker::sendTiming (WalkerState * sendingState, PacketPtr pkt) [protected]
Definition at line 153 of file pagetable_walker.cc.
References Packet::popSenderState(), port, Packet::pushSenderState(), and MasterPort::sendTimingReq().
Referenced by X86ISA::Walker::WalkerState::sendPackets().
void X86ISA::Walker::setTLB (TLB * _tlb) [inline]
Definition at line 190 of file pagetable_walker.hh.
References tlb.
Referenced by X86ISA::TLB::TLB().
Fault X86ISA::Walker::start (ThreadContext * _tc, BaseTLB::Translation * translation, RequestPtr req, BaseTLB::Mode mode)
Definition at line 69 of file pagetable_walker.cc.
References currStates, DPRINTF, X86ISA::Walker::WalkerState::initState(), X86ISA::Walker::WalkerState::isTiming(), System::isTimingMode(), X86ISA::Walker::WalkerState::startWalk(), sys, and WalkerState.
Referenced by X86ISA::TLB::translate().
Fault X86ISA::Walker::startFunctional (ThreadContext * _tc, Addr & addr, unsigned & logBytes, BaseTLB::Mode mode)
Definition at line 94 of file pagetable_walker.cc.
References funcState, X86ISA::Walker::WalkerState::initState(), and X86ISA::Walker::WalkerState::startFunctional().
Referenced by X86ISA::RemoteGDB::acc().
void X86ISA::Walker::startWalkWrapper () [protected]
Definition at line 190 of file pagetable_walker.cc.
References currStates, DPRINTF, BaseTLB::Translation::finish(), Request::getVaddr(), X86ISA::Walker::WalkerState::mode, numSquashable, X86ISA::Walker::WalkerState::req, BaseTLB::Translation::squashed(), X86ISA::Walker::WalkerState::startWalk(), X86ISA::Walker::WalkerState::tc, X86ISA::Walker::WalkerState::translation, and X86ISA::Walker::WalkerState::wasStarted().
Friends And Related Function Documentation
friend class WalkerPort [friend]
Definition at line 76 of file pagetable_walker.hh.
friend class WalkerState [friend]
Definition at line 143 of file pagetable_walker.hh.
Referenced by start().
Member Data Documentation
std::list<WalkerState *> X86ISA::Walker::currStates [protected]
Definition at line 146 of file pagetable_walker.hh.
Referenced by recvReqRetry(), recvTimingResp(), start(), and startWalkWrapper().
WalkerState X86ISA::Walker::funcState [protected]
Definition at line 148 of file pagetable_walker.hh.
Referenced by startFunctional().
MasterID X86ISA::Walker::masterId [protected]
Definition at line 170 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::WalkerState::setupWalk(), and X86ISA::Walker::WalkerState::stepWalk().
unsigned X86ISA::Walker::numSquashable [protected]
Definition at line 173 of file pagetable_walker.hh.
Referenced by startWalkWrapper().
WalkerPort X86ISA::Walker::port [protected]
Definition at line 77 of file pagetable_walker.hh.
Referenced by getMasterPort(), sendTiming(), X86ISA::Walker::WalkerState::startFunctional(), and X86ISA::Walker::WalkerState::startWalk().
EventWrapper<Walker, &Walker::startWalkWrapper> X86ISA::Walker::startWalkWrapperEvent [protected]
Event used to call startWalkWrapper.
Definition at line 181 of file pagetable_walker.hh.
Referenced by recvTimingResp().
System* X86ISA::Walker::sys [protected]
Definition at line 169 of file pagetable_walker.hh.
Referenced by start().
TLB* X86ISA::Walker::tlb [protected]
Definition at line 168 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::WalkerState::recvPacket(), setTLB(), and X86ISA::Walker::WalkerState::stepWalk().
The documentation for this class was generated from the following files:
arch/x86/pagetable_walker.hh
arch/x86/pagetable_walker.cc