gem5: ArmISA::UndefinedInstruction Class Reference
ArmISA::UndefinedInstruction Class Reference
#include <faults.hh>
Public Member Functions
UndefinedInstruction (ExtMachInst _machInst, bool _unknown, const char *_mnemonic=NULL, bool _disabled=false)
UndefinedInstruction (ExtMachInst _machInst, uint32_t _iss, ExceptionClass _overrideEc, const char *_mnemonic=NULL)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
bool routeToHyp (ThreadContext *tc) const
ExceptionClass ec (ThreadContext *tc) const
uint32_t iss () const
Protected Attributes
bool unknown
bool disabled
ExceptionClass overrideEc
const char * mnemonic
Detailed Description
Definition at line 257 of file faults.hh.
Constructor & Destructor Documentation
ArmISA::UndefinedInstruction::UndefinedInstruction (ExtMachInst _machInst, bool _unknown, const char * _mnemonic = NULL, bool _disabled = false) [inline]
Definition at line 266 of file faults.hh.
ArmISA::UndefinedInstruction::UndefinedInstruction (ExtMachInst _machInst, uint32_t _iss, ExceptionClass _overrideEc, const char * _mnemonic = NULL) [inline]
Definition at line 274 of file faults.hh.
Member Function Documentation
ExceptionClass ArmISA::UndefinedInstruction::ec (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFaultVals< UndefinedInstruction >.
Definition at line 835 of file faults.cc.
References ArmISA::ArmFault::FaultVals::ec, ArmISA::EC_INVALID, overrideEc, and ArmISA::ArmFaultVals< UndefinedInstruction >::vals.
void ArmISA::UndefinedInstruction::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 709 of file faults.cc.
References disabled, FullSystem, ArmISA::ArmFault::machInst, mnemonic, panic, and unknown.
uint32_t ArmISA::UndefinedInstruction::iss () const [virtual]
Reimplemented from ArmISA::ArmFaultVals< UndefinedInstruction >.
Definition at line 747 of file faults.cc.
References bits(), ArmISA::EC_INVALID, ArmISA::ArmFault::issRaw, ArmISA::ArmFault::machInst, and overrideEc.
bool ArmISA::UndefinedInstruction::routeToHyp (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 731 of file faults.cc.
References ArmISA::cpsr, ArmISA::inSecureState(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_SCR, ArmISA::MODE_HYP, ArmISA::MODE_USER, ThreadContext::readMiscRegNoEffect(), and ArmISA::scr.
Member Data Documentation
bool ArmISA::UndefinedInstruction::disabled [protected]
Definition at line 261 of file faults.hh.
Referenced by invoke().
const char* ArmISA::UndefinedInstruction::mnemonic [protected]
Definition at line 263 of file faults.hh.
Referenced by invoke().
ExceptionClass ArmISA::UndefinedInstruction::overrideEc [protected]
Definition at line 262 of file faults.hh.
Referenced by ec(), and iss().
bool ArmISA::UndefinedInstruction::unknown [protected]
Definition at line 260 of file faults.hh.
Referenced by invoke().
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc