gem5: AlphaISA::RemoteGDB Class Reference
AlphaISA::RemoteGDB Class Reference
#include <remote_gdb.hh>
Public Member Functions
RemoteGDB (System *system, ThreadContext *context)
Protected Member Functions
void getregs ()
void setregs ()
bool acc (Addr addr, size_t len)
bool write (Addr addr, size_t size, const char *data)
bool insertHardBreak (Addr addr, size_t len)
Detailed Description
Definition at line 48 of file remote_gdb.hh.
Constructor & Destructor Documentation
RemoteGDB::RemoteGDB (System * system, ThreadContext * context)
Definition at line 148 of file remote_gdb.cc.
References BaseRemoteGDB::GdbRegCache::bytes(), BaseRemoteGDB::gdbregs, and BaseRemoteGDB::GdbRegCache::regs.
Member Function Documentation
bool RemoteGDB::acc (Addr addr, size_t len) [protected, virtual]
This code says that all accesses to palcode (instruction and data) are valid since there isn't a va->pa mapping because palcode is accessed physically. At some point this should probably be cleaned up but there is no easy way to do it.
Implements BaseRemoteGDB.
Definition at line 158 of file remote_gdb.cc.
References BaseRemoteGDB::context, DPRINTF, FullSystem, ThreadContext::getPhysProxy(), AlphaISA::IPR_PALtemp20, AlphaISA::IsK0Seg(), AlphaISA::K0SegBase, AlphaISA::kernel_pte_lookup(), System::memSize(), AlphaISA::PageBytes, panic, AlphaISA::PcPAL(), ThreadContext::readMiscRegNoEffect(), AlphaISA::RoundPage(), BaseRemoteGDB::system, AlphaISA::TruncPage(), and AlphaISA::PageTableEntry::valid().
void RemoteGDB::getregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 211 of file remote_gdb.cc.
References BaseRemoteGDB::GdbRegCache::bytes(), BaseRemoteGDB::context, BaseRemoteGDB::gdbregs, ArmISA::i, KGDB_REG_F0, KGDB_REG_PC, AlphaISA::NumFloatArchRegs, AlphaISA::NumIntArchRegs, AlphaISA::PcPAL(), ThreadContext::pcState(), ThreadContext::readFloatRegBits(), ThreadContext::readIntReg(), AlphaISA::reg_redir, BaseRemoteGDB::GdbRegCache::regs, and BaseRemoteGDB::GdbRegCache::regs64.
bool RemoteGDB::insertHardBreak (Addr addr, size_t len) [protected, virtual]
Reimplemented from BaseRemoteGDB.
Definition at line 274 of file remote_gdb.cc.
References warn_once.
void RemoteGDB::setregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 237 of file remote_gdb.cc.
References BaseRemoteGDB::context, BaseRemoteGDB::gdbregs, ArmISA::i, KGDB_REG_F0, KGDB_REG_PC, AlphaISA::NumFloatArchRegs, AlphaISA::NumIntArchRegs, AlphaISA::PcPAL(), ThreadContext::pcState(), AlphaISA::reg_redir, BaseRemoteGDB::GdbRegCache::regs64, ThreadContext::setFloatRegBits(), and ThreadContext::setIntReg().
bool RemoteGDB::write (Addr addr, size_t size, const char * data) [protected, virtual]
Reimplemented from BaseRemoteGDB.
Definition at line 260 of file remote_gdb.cc.
References BaseRemoteGDB::write().
The documentation for this class was generated from the following files:
arch/alpha/remote_gdb.hh
arch/alpha/remote_gdb.cc