gem5: RubyDirectedTester::CpuPort Class Reference
RubyDirectedTester::CpuPort Class Reference
#include <RubyDirectedTester.hh>
Public Member Functions
CpuPort (const std::string &_name, RubyDirectedTester *_tester, PortID _id)
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
virtual void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Private Attributes
RubyDirectedTester * tester
Detailed Description
Definition at line 50 of file RubyDirectedTester.hh.
Constructor & Destructor Documentation
RubyDirectedTester::CpuPort::CpuPort (const std::string & _name, RubyDirectedTester * _tester, PortID _id) [inline]
Definition at line 56 of file RubyDirectedTester.hh.
Member Function Documentation
virtual void RubyDirectedTester::CpuPort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 63 of file RubyDirectedTester.hh.
References Port::name(), and panic.
bool RubyDirectedTester::CpuPort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 93 of file RubyDirectedTester.cc.
References Packet::getAddr(), RubyDirectedTester::hitCallback(), Packet::req, and tester.
Member Data Documentation
RubyDirectedTester* RubyDirectedTester::CpuPort::tester [private]
Definition at line 53 of file RubyDirectedTester.hh.
Referenced by recvTimingResp().
The documentation for this class was generated from the following files:
cpu/testers/directedtest/RubyDirectedTester.hh
cpu/testers/directedtest/RubyDirectedTester.cc