gem5: KvmGic Class Reference
KvmGic Class Reference
In-kernel GIC model.
#include <gic.hh>
Public Member Functions
KvmGic (const KvmGicParams *p)
~KvmGic ()
void startup () M5_ATTR_OVERRIDE
startup() is the final initialization call before simulation.
void drainResume () M5_ATTR_OVERRIDE
Resume execution after a successful drain.
void serialize (std::ostream &os) M5_ATTR_OVERRIDE
void unserialize (Checkpoint *cp, const std::string &sec) M5_ATTR_OVERRIDE
AddrRangeList getAddrRanges () const
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) M5_ATTR_OVERRIDE
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) M5_ATTR_OVERRIDE
Pure virtual function that the device must implement.
void sendInt (uint32_t num) M5_ATTR_OVERRIDE
Post an interrupt from a device that is connected to the GIC.
void clearInt (uint32_t num) M5_ATTR_OVERRIDE
Clear an interrupt from a device that is connected to the GIC.
void sendPPInt (uint32_t num, uint32_t cpu) M5_ATTR_OVERRIDE
Interface call for private peripheral interrupts.
void clearPPInt (uint32_t num, uint32_t cpu) M5_ATTR_OVERRIDE
Protected Member Functions
void verifyMemoryMode () const
Do memory mode sanity checks.
void setIntState (uint8_t type, uint8_t vcpu, uint16_t irq, bool high)
Update the kernel's VGIC interrupt state.
Protected Attributes
System & system
System this interrupt controller belongs to.
KvmVM & vm
VM for this system.
KvmDevice kdev
Kernel interface to the GIC.
const AddrRange distRange
Address range for the distributor interface.
const AddrRange cpuRange
Address range for the CPU interfaces.
const AddrRangeList addrRanges
Union of all memory.
Detailed Description
In-kernel GIC model.
When using a KVM-based CPU model, it is possible to offload GIC emulation to the kernel. This reduces some overheads when the guest accesses the GIC and makes it possible to use in-kernel architected/generic timer emulation.
This device uses interfaces with the kernel GicV2 model that is documented in Documentation/virtual/kvm/devices/arm-vgic.txt in the Linux kernel sources.
This GIC model has the following known limitations:
Checkpointing is not supported.
This model only works with kvm. Simulated CPUs are not supported since this would require the kernel to inject interrupt into the simulated CPU.
This GIC model cannot be used with simulated CPUs!
Definition at line 73 of file gic.hh.
Constructor & Destructor Documentation
KvmGic::KvmGic (const KvmGicParams * p)
Definition at line 47 of file gic.cc.
References cpuRange, and distRange.
KvmGic::~KvmGic ()
Member Function Documentation
void KvmGic::clearInt (uint32_t num) [virtual]
Clear an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC may de-assert it's CPU line.
Parameters:
num number of interrupt to send
Implements BaseGic.
void KvmGic::clearPPInt (uint32_t num, uint32_t cpu) [virtual]
Implements BaseGic.
void KvmGic::drainResume () [inline, virtual]
Resume execution after a successful drain.
Note:
This method is normally only called from the simulation scripts.
Reimplemented from Drainable.
Definition at line 80 of file gic.hh.
References verifyMemoryMode().
AddrRangeList KvmGic::getAddrRanges () const [inline, virtual]
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns:
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 86 of file gic.hh.
References addrRanges.
Tick KvmGic::read (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
void KvmGic::sendInt (uint32_t num) [virtual]
Post an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC will pass this interrupt on through to a CPU.
Parameters:
num number of interrupt to send
Implements BaseGic.
void KvmGic::sendPPInt (uint32_t num, uint32_t cpu) [virtual]
Interface call for private peripheral interrupts.
Parameters:
num number of interrupt to send
cpu CPU to forward interrupt to
Implements BaseGic.
void KvmGic::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
void KvmGic::setIntState (uint8_t type, uint8_t vcpu, uint16_t irq, bool high) [protected]
Update the kernel's VGIC interrupt state.
Parameters:
type Interrupt type (KVM_ARM_IRQ_TYPE_PPI/KVM_ARM_IRQ_TYPE_SPI)
vcpu CPU id within KVM (ignored for SPIs)
irq Interrupt number
high True to signal an interrupt, false to clear it.
void KvmGic::startup () [inline, virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 79 of file gic.hh.
References verifyMemoryMode().
void KvmGic::unserialize (Checkpoint * cp, const std::string & sec) [virtual]
Reimplemented from Serializable.
void KvmGic::verifyMemoryMode () const [protected]
Do memory mode sanity checks.
This method only really exists to warn users that try to switch to a simulate CPU. There is no fool proof method to detect simulated CPUs, but checking that we're in atomic mode and bypassing caches should be robust enough.
Referenced by drainResume(), and startup().
Tick KvmGic::write (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Member Data Documentation
const AddrRangeList KvmGic::addrRanges [protected]
Union of all memory.
Definition at line 130 of file gic.hh.
Referenced by getAddrRanges().
const AddrRange KvmGic::cpuRange [protected]
Address range for the CPU interfaces.
Definition at line 128 of file gic.hh.
Referenced by KvmGic().
const AddrRange KvmGic::distRange [protected]
Address range for the distributor interface.
Definition at line 126 of file gic.hh.
Referenced by KvmGic().
KvmDevice KvmGic::kdev [protected]
Kernel interface to the GIC.
Definition at line 123 of file gic.hh.
System& KvmGic::system [protected]
System this interrupt controller belongs to.
Definition at line 119 of file gic.hh.
KvmVM& KvmGic::vm [protected]
VM for this system.
Definition at line 121 of file gic.hh.
The documentation for this class was generated from the following files:
arch/arm/kvm/gic.hh
arch/arm/kvm/gic.cc