gem5: SimpleMemory::MemoryPort Class Reference
SimpleMemory::MemoryPort Class Reference
Public Member Functions
MemoryPort (const std::string &_name, SimpleMemory &_memory)
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Private Attributes
SimpleMemory & memory
Detailed Description
Definition at line 85 of file simple_mem.hh.
Constructor & Destructor Documentation
SimpleMemory::MemoryPort::MemoryPort (const std::string & _name, SimpleMemory & _memory)
Definition at line 255 of file simple_mem.cc.
Member Function Documentation
AddrRangeList SimpleMemory::MemoryPort::getAddrRanges () const [protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 261 of file simple_mem.cc.
References AbstractMemory::getAddrRange(), and memory.
Tick SimpleMemory::MemoryPort::recvAtomic (PacketPtr pkt) [protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 269 of file simple_mem.cc.
References memory, and SimpleMemory::recvAtomic().
void SimpleMemory::MemoryPort::recvFunctional (PacketPtr pkt) [protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 275 of file simple_mem.cc.
References memory, and SimpleMemory::recvFunctional().
void SimpleMemory::MemoryPort::recvRespRetry () [protected, virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 287 of file simple_mem.cc.
References memory, and SimpleMemory::recvRespRetry().
bool SimpleMemory::MemoryPort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 281 of file simple_mem.cc.
References memory, and SimpleMemory::recvTimingReq().
Member Data Documentation
SimpleMemory& SimpleMemory::MemoryPort::memory [private]
Definition at line 90 of file simple_mem.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvRespRetry(), and recvTimingReq().
The documentation for this class was generated from the following files:
mem/simple_mem.hh
mem/simple_mem.cc