gem5: DRAMSim2 Class Reference
DRAMSim2 Class Reference
#include <dramsim2.hh>
Classes
class MemoryPort
The memory port has to deal with its own flow control to avoid having unbounded storage that is implicitly created in the port itself.
Public Types
typedef DRAMSim2Params Params
Public Member Functions
DRAMSim2 (const Params *p)
void readComplete (unsigned id, uint64_t addr, uint64_t cycle)
Read completion callback.
void writeComplete (unsigned id, uint64_t addr, uint64_t cycle)
Write completion callback.
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
virtual BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
virtual void init ()
Initialise this memory.
virtual void startup ()
startup() is the final initialization call before simulation.
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
void recvFunctional (PacketPtr pkt)
bool recvTimingReq (PacketPtr pkt)
void recvRespRetry ()
Private Member Functions
unsigned int nbrOutstanding () const
void accessAndRespond (PacketPtr pkt)
When a packet is ready, use the "access()" method in AbstractMemory to actually create the response packet, and send it back to the outside world requestor.
void sendResponse ()
void tick ()
Progress the controller one clock cycle.
Private Attributes
MemoryPort port
DRAMSim2Wrapper wrapper
The actual DRAMSim2 wrapper.
bool retryReq
Is the connected port waiting for a retry from us.
bool retryResp
Are we waiting for a retry for sending a response.
Tick startTick
Keep track of when the wrapper is started.
m5::hash_map< Addr, std::queue
< PacketPtr > > outstandingReads
Keep track of what packets are outstanding per address, and do so separately for reads and writes.
m5::hash_map< Addr, std::queue
< PacketPtr > > outstandingWrites
unsigned int nbrOutstandingReads
Count the number of outstanding transactions so that we can block any further requests until there is space in DRAMSim2 and the sending queue we need to buffer the response packets.
unsigned int nbrOutstandingWrites
std::deque< PacketPtr > responseQueue
Queue to hold response packets until we can send them back.
DrainManager * drainManager
If we need to drain, keep the drain manager around until we're done here.
EventWrapper< DRAMSim2,&DRAMSim2::sendResponse > sendResponseEvent
Event to schedule sending of responses.
EventWrapper< DRAMSim2,&DRAMSim2::tick > tickEvent
Event to schedule clock ticks.
std::vector< PacketPtr > pendingDelete
Detailed Description
Definition at line 55 of file dramsim2.hh.
Member Typedef Documentation
typedef DRAMSim2Params DRAMSim2::Params
Reimplemented from AbstractMemory.
Definition at line 177 of file dramsim2.hh.
Constructor & Destructor Documentation
DRAMSim2::DRAMSim2 (const Params * p)
Definition at line 48 of file dramsim2.cc.
References DRAMSim2Wrapper::clockPeriod(), DPRINTF, DRAMSim2Wrapper::printStats(), DRAMSim2Wrapper::queueSize(), readComplete(), Stats::registerDumpCallback(), Stats::registerResetCallback(), DRAMSim2Wrapper::resetStats(), DRAMSim2Wrapper::setCallbacks(), wrapper, and writeComplete().
Member Function Documentation
void DRAMSim2::accessAndRespond (PacketPtr pkt) [private]
When a packet is ready, use the "access()" method in AbstractMemory to actually create the response packet, and send it back to the outside world requestor.
Parameters:
pkt The packet from the outside world
Definition at line 260 of file dramsim2.cc.
References AbstractMemory::access(), curTick(), DPRINTF, Packet::getAddr(), Packet::headerDelay, Packet::isResponse(), Packet::needsResponse(), Packet::payloadDelay, pendingDelete, responseQueue, retryResp, EventManager::schedule(), Event::scheduled(), and sendResponseEvent.
Referenced by readComplete(), and recvTimingReq().
unsigned int DRAMSim2::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 363 of file dramsim2.cc.
References Drainable::Drained, Drainable::Draining, drainManager, nbrOutstanding(), and Drainable::setDrainState().
BaseSlavePort & DRAMSim2::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 353 of file dramsim2.cc.
References port.
void DRAMSim2::init () [virtual]
Initialise this memory.
Reimplemented from AbstractMemory.
Definition at line 81 of file dramsim2.cc.
References DRAMSim2Wrapper::burstSize(), System::cacheLineSize(), fatal, BaseSlavePort::isConnected(), SimObject::name(), port, SlavePort::sendRangeChange(), AbstractMemory::system(), and wrapper.
unsigned int DRAMSim2::nbrOutstanding () const [private]
Definition at line 139 of file dramsim2.cc.
References nbrOutstandingReads, nbrOutstandingWrites, and responseQueue.
Referenced by drain(), recvTimingReq(), sendResponse(), tick(), and writeComplete().
void DRAMSim2::readComplete (unsigned id, uint64_t addr, uint64_t cycle)
Read completion callback.
Parameters:
id Channel id of the responder
addr Address of the request
cycle Internal cycle count of DRAMSim2
Definition at line 297 of file dramsim2.cc.
References accessAndRespond(), DRAMSim2Wrapper::clockPeriod(), curTick(), divCeil(), DPRINTF, nbrOutstandingReads, SimClock::Int::ns, outstandingReads, MipsISA::p, startTick, and wrapper.
Referenced by DRAMSim2().
Tick DRAMSim2::recvAtomic (PacketPtr pkt) [protected]
Definition at line 160 of file dramsim2.cc.
References AbstractMemory::access(), and Packet::memInhibitAsserted().
Referenced by DRAMSim2::MemoryPort::recvAtomic().
void DRAMSim2::recvFunctional (PacketPtr pkt) [protected]
Definition at line 169 of file dramsim2.cc.
References Packet::checkFunctional(), AbstractMemory::functionalAccess(), ArmISA::i, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), and responseQueue.
Referenced by DRAMSim2::MemoryPort::recvFunctional().
void DRAMSim2::recvRespRetry () [protected]
Definition at line 250 of file dramsim2.cc.
References DPRINTF, retryResp, and sendResponse().
Referenced by DRAMSim2::MemoryPort::recvRespRetry().
bool DRAMSim2::recvTimingReq (PacketPtr pkt) [protected]
Definition at line 183 of file dramsim2.cc.
References accessAndRespond(), DRAMSim2Wrapper::canAccept(), DPRINTF, DRAMSim2Wrapper::enqueue(), Packet::getAddr(), Packet::isRead(), Packet::isWrite(), Packet::memInhibitAsserted(), nbrOutstanding(), nbrOutstandingReads, nbrOutstandingWrites, outstandingReads, outstandingWrites, pendingDelete, DRAMSim2Wrapper::queueSize(), retryReq, wrapper, and X86ISA::x.
Referenced by DRAMSim2::MemoryPort::recvTimingReq().
void DRAMSim2::sendResponse () [private]
Definition at line 106 of file dramsim2.cc.
References curTick(), DPRINTF, drainManager, nbrOutstanding(), nbrOutstandingReads, nbrOutstandingWrites, port, responseQueue, retryResp, EventManager::schedule(), Event::scheduled(), sendResponseEvent, SlavePort::sendTimingResp(), and DrainManager::signalDrainDone().
Referenced by recvRespRetry().
void DRAMSim2::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 97 of file dramsim2.cc.
References ClockedObject::clockEdge(), curTick(), EventManager::schedule(), startTick, and tickEvent.
void DRAMSim2::tick () [private]
Progress the controller one clock cycle.
Definition at line 145 of file dramsim2.cc.
References DRAMSim2Wrapper::clockPeriod(), curTick(), nbrOutstanding(), SimClock::Int::ns, port, DRAMSim2Wrapper::queueSize(), retryReq, EventManager::schedule(), SlavePort::sendRetryReq(), DRAMSim2Wrapper::tick(), tickEvent, and wrapper.
void DRAMSim2::writeComplete (unsigned id, uint64_t addr, uint64_t cycle)
Write completion callback.
Parameters:
id Channel id of the responder
addr Address of the request
cycle Internal cycle count of DRAMSim2
Definition at line 325 of file dramsim2.cc.
References DRAMSim2Wrapper::clockPeriod(), curTick(), divCeil(), DPRINTF, drainManager, nbrOutstanding(), nbrOutstandingWrites, SimClock::Int::ns, outstandingWrites, MipsISA::p, DrainManager::signalDrainDone(), startTick, and wrapper.
Referenced by DRAMSim2().
Member Data Documentation
DrainManager* DRAMSim2::drainManager [private]
If we need to drain, keep the drain manager around until we're done here.
Definition at line 139 of file dramsim2.hh.
Referenced by drain(), sendResponse(), and writeComplete().
unsigned int DRAMSim2::nbrOutstandingReads [private]
Count the number of outstanding transactions so that we can block any further requests until there is space in DRAMSim2 and the sending queue we need to buffer the response packets.
Definition at line 125 of file dramsim2.hh.
Referenced by nbrOutstanding(), readComplete(), recvTimingReq(), and sendResponse().
unsigned int DRAMSim2::nbrOutstandingWrites [private]
Definition at line 126 of file dramsim2.hh.
Referenced by nbrOutstanding(), recvTimingReq(), sendResponse(), and writeComplete().
m5::hash_map<Addr, std::queue<PacketPtr> > DRAMSim2::outstandingReads [private]
Keep track of what packets are outstanding per address, and do so separately for reads and writes.
This is done so that we can return the right packet on completion from DRAMSim.
Definition at line 117 of file dramsim2.hh.
Referenced by readComplete(), and recvTimingReq().
m5::hash_map<Addr, std::queue<PacketPtr> > DRAMSim2::outstandingWrites [private]
Definition at line 118 of file dramsim2.hh.
Referenced by recvTimingReq(), and writeComplete().
std::vector<PacketPtr> DRAMSim2::pendingDelete [private]
Todo:
this is a temporary workaround until the 4-phase code is committed. upstream caches needs this packet until true is returned, so hold onto it for deletion until a subsequent call
Definition at line 173 of file dramsim2.hh.
Referenced by accessAndRespond(), and recvTimingReq().
MemoryPort DRAMSim2::port [private]
Definition at line 89 of file dramsim2.hh.
Referenced by getSlavePort(), init(), sendResponse(), and tick().
std::deque<PacketPtr> DRAMSim2::responseQueue [private]
Queue to hold response packets until we can send them back.
This is needed as DRAMSim2 unconditionally passes responses back without any flow control.
Definition at line 133 of file dramsim2.hh.
Referenced by accessAndRespond(), nbrOutstanding(), recvFunctional(), and sendResponse().
bool DRAMSim2::retryReq [private]
Is the connected port waiting for a retry from us.
Definition at line 99 of file dramsim2.hh.
Referenced by recvTimingReq(), and tick().
bool DRAMSim2::retryResp [private]
Are we waiting for a retry for sending a response.
Definition at line 104 of file dramsim2.hh.
Referenced by accessAndRespond(), recvRespRetry(), and sendResponse().
EventWrapper<DRAMSim2, &DRAMSim2::sendResponse> DRAMSim2::sendResponseEvent [private]
Event to schedule sending of responses.
Definition at line 157 of file dramsim2.hh.
Referenced by accessAndRespond(), and sendResponse().
Tick DRAMSim2::startTick [private]
Keep track of when the wrapper is started.
Definition at line 109 of file dramsim2.hh.
Referenced by readComplete(), startup(), and writeComplete().
EventWrapper<DRAMSim2, &DRAMSim2::tick> DRAMSim2::tickEvent [private]
Event to schedule clock ticks.
Definition at line 167 of file dramsim2.hh.
Referenced by startup(), and tick().
DRAMSim2Wrapper DRAMSim2::wrapper [private]
The actual DRAMSim2 wrapper.
Definition at line 94 of file dramsim2.hh.
Referenced by DRAMSim2(), init(), readComplete(), recvTimingReq(), tick(), and writeComplete().
The documentation for this class was generated from the following files:
mem/dramsim2.hh
mem/dramsim2.cc