gem5: GDBListener Class Reference
GDBListener Class Reference
#include <remote_gdb.hh>
Classes
class InputEvent
Public Member Functions
GDBListener (BaseRemoteGDB *g, int p)
~GDBListener ()
void accept ()
void listen ()
std::string name ()
Protected Attributes
InputEvent * inputEvent
ListenSocket listener
BaseRemoteGDB * gdb
int port
Friends
class InputEvent
Detailed Description
Definition at line 290 of file remote_gdb.hh.
Constructor & Destructor Documentation
GDBListener::GDBListener (BaseRemoteGDB * g, int p)
Definition at line 178 of file remote_gdb.cc.
References gdb, and BaseRemoteGDB::listener.
GDBListener::~GDBListener ()
Definition at line 185 of file remote_gdb.cc.
References inputEvent.
Member Function Documentation
void GDBListener::accept ()
Definition at line 228 of file remote_gdb.cc.
References ListenSocket::accept(), BaseRemoteGDB::attach(), gdb, BaseRemoteGDB::isattached(), ListenSocket::islistening(), listener, and panic.
Referenced by debugger(), GDBListener::InputEvent::process(), and System::registerThreadContext().
void GDBListener::listen ()
Definition at line 198 of file remote_gdb.cc.
References ListenSocket::allDisabled(), ccprintf(), curTick(), DPRINTF, gdb, ListenSocket::getfd(), InputEvent, inputEvent, ListenSocket::listen(), listener, name(), BaseRemoteGDB::number, pollQueue, port, PollQueue::schedule(), and warn_once.
Referenced by System::registerThreadContext().
string GDBListener::name ()
Definition at line 192 of file remote_gdb.cc.
References gdb, and BaseRemoteGDB::name().
Referenced by listen().
Friends And Related Function Documentation
friend class InputEvent [friend]
Definition at line 303 of file remote_gdb.hh.
Referenced by listen().
Member Data Documentation
BaseRemoteGDB* GDBListener::gdb [protected]
Definition at line 308 of file remote_gdb.hh.
Referenced by accept(), GDBListener(), listen(), and name().
InputEvent* GDBListener::inputEvent [protected]
Definition at line 304 of file remote_gdb.hh.
Referenced by listen(), and ~GDBListener().
ListenSocket GDBListener::listener [protected]
Definition at line 307 of file remote_gdb.hh.
Referenced by accept(), and listen().
int GDBListener::port [protected]
Definition at line 309 of file remote_gdb.hh.
Referenced by listen().
The documentation for this class was generated from the following files:
base/remote_gdb.hh
base/remote_gdb.cc