gem5: Minor::MinorActivityRecorder Class Reference
Minor::MinorActivityRecorder Class Reference
ActivityRecorder with a Ticked interface.
#include <activity.hh>
Public Member Functions
void evaluate ()
Ticked interface.
void minorTrace () const
MinorActivityRecorder (const std::string &name, int num_stages, int longest_latency)
Detailed Description
ActivityRecorder with a Ticked interface.
Definition at line 56 of file activity.hh.
Constructor & Destructor Documentation
Minor::MinorActivityRecorder::MinorActivityRecorder (const std::string & name, int num_stages, int longest_latency) [inline]
Definition at line 64 of file activity.hh.
Member Function Documentation
void Minor::MinorActivityRecorder::evaluate () [inline]
Ticked interface.
Definition at line 60 of file activity.hh.
References ActivityRecorder::advance().
Referenced by Minor::Pipeline::evaluate().
void Minor::MinorActivityRecorder::minorTrace () const
Definition at line 49 of file activity.cc.
References ActivityRecorder::getActivityCount(), ActivityRecorder::getNumStages(), ActivityRecorder::getStageActive(), and MINORTRACE.
Referenced by Minor::Pipeline::minorTrace().
The documentation for this class was generated from the following files:
cpu/minor/activity.hh
cpu/minor/activity.cc