gem5: ArmISA::DataXCondSelOp Class Reference
ArmISA::DataXCondSelOp Class Reference
#include <data64.hh>
Protected Member Functions
DataXCondSelOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, IntRegIndex _op2, ConditionCode _condCode)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
IntRegIndex op1
IntRegIndex op2
ConditionCode condCode
Detailed Description
Definition at line 238 of file data64.hh.
Constructor & Destructor Documentation
ArmISA::DataXCondSelOp::DataXCondSelOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, IntRegIndex _op2, ConditionCode _condCode) [inline, protected]
Definition at line 244 of file data64.hh.
Member Function Documentation
std::string ArmISA::DataXCondSelOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 188 of file data64.cc.
References ccprintf(), condCode, dest, op1, op2, ArmISA::ArmStaticInst::printCondition(), ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
ConditionCode ArmISA::DataXCondSelOp::condCode [protected]
Definition at line 242 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataXCondSelOp::dest [protected]
Definition at line 241 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataXCondSelOp::op1 [protected]
Definition at line 241 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataXCondSelOp::op2 [protected]
Definition at line 241 of file data64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/data64.hh
arch/arm/insts/data64.cc