gem5: DMASequencer::MemSlavePort Class Reference
DMASequencer::MemSlavePort Class Reference
#include <DMASequencer.hh>
Public Member Functions
MemSlavePort (const std::string &_name, DMASequencer *_port, PortID id, RubySystem *_ruby_system, bool _access_backing_store)
void hitCallback (PacketPtr pkt)
void evictionCallback (const Address &address)
Protected Member Functions
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Private Member Functions
bool isPhysMemAddress (Addr addr) const
Private Attributes
RespPacketQueue queue
RubySystem * ruby_system
bool access_backing_store
Detailed Description
Definition at line 66 of file DMASequencer.hh.
Constructor & Destructor Documentation
DMASequencer::MemSlavePort::MemSlavePort (const std::string & _name, DMASequencer * _port, PortID id, RubySystem * _ruby_system, bool _access_backing_store)
Definition at line 76 of file DMASequencer.cc.
References DPRINTF.
Member Function Documentation
void DMASequencer::MemSlavePort::evictionCallback (const Address & address)
AddrRangeList DMASequencer::MemSlavePort::getAddrRanges () const [inline, protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 89 of file DMASequencer.hh.
void DMASequencer::MemSlavePort::hitCallback (PacketPtr pkt)
Definition at line 205 of file DMASequencer.cc.
References AbstractMemory::access(), access_backing_store, ClockedObject::clockPeriod(), curTick(), DPRINTF, g_system_ptr, RubySystem::getPhysMem(), Packet::isFlush(), Packet::isLLSC(), Packet::makeResponse(), Packet::needsResponse(), ruby_system, and QueuedSlavePort::schedTimingResp().
Referenced by DMASequencer::ruby_hit_callback().
bool DMASequencer::MemSlavePort::isPhysMemAddress (Addr addr) const [private]
Definition at line 233 of file DMASequencer.cc.
References System::isMemAddr(), Port::owner, and DMASequencer::system.
Referenced by recvTimingReq().
Tick DMASequencer::MemSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 83 of file DMASequencer.hh.
References panic.
void DMASequencer::MemSlavePort::recvFunctional (PacketPtr pkt) [inline, protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 86 of file DMASequencer.hh.
References panic.
bool DMASequencer::MemSlavePort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 86 of file DMASequencer.cc.
References Packet::cmdString(), DPRINTF, Packet::getAddr(), RubySystem::getBlockSizeBytes(), Packet::getSize(), Port::id, isPhysMemAddress(), Packet::memInhibitAsserted(), Port::owner, and panic.
Member Data Documentation
bool DMASequencer::MemSlavePort::access_backing_store [private]
Definition at line 71 of file DMASequencer.hh.
Referenced by hitCallback().
RespPacketQueue DMASequencer::MemSlavePort::queue [private]
Definition at line 69 of file DMASequencer.hh.
RubySystem* DMASequencer::MemSlavePort::ruby_system [private]
Definition at line 70 of file DMASequencer.hh.
Referenced by hitCallback().
The documentation for this class was generated from the following files:
mem/ruby/system/DMASequencer.hh
mem/ruby/system/DMASequencer.cc