gem5: ArmISA::PrefetchAbort Class Reference
ArmISA::PrefetchAbort Class Reference
#include <faults.hh>
Public Member Functions
PrefetchAbort (Addr _addr, uint8_t _source, bool _stage2=false, ArmFault::TranMethod _tranMethod=ArmFault::UnknownTran)
ExceptionClass ec (ThreadContext *tc) const
bool routeToMonitor (ThreadContext *tc) const
bool routeToHyp (ThreadContext *tc) const
Static Public Attributes
static const MiscRegIndex FsrIndex = MISCREG_IFSR
static const MiscRegIndex FarIndex = MISCREG_IFAR
static const MiscRegIndex HFarIndex = MISCREG_HIFAR
Detailed Description
Definition at line 418 of file faults.hh.
Constructor & Destructor Documentation
ArmISA::PrefetchAbort::PrefetchAbort (Addr _addr, uint8_t _source, bool _stage2 = false, ArmFault::TranMethod _tranMethod = ArmFault::UnknownTran) [inline]
Definition at line 425 of file faults.hh.
Member Function Documentation
ExceptionClass ArmISA::PrefetchAbort::ec (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFaultVals< PrefetchAbort >.
Definition at line 1061 of file faults.cc.
References ArmISA::EC_PREFETCH_ABORT_CURR_EL, ArmISA::EC_PREFETCH_ABORT_LOWER_EL, ArmISA::ArmFault::fromEL, ArmISA::MISCREG_SPSR_HYP, ArmISA::MODE_HYP, ThreadContext::readMiscReg(), ArmISA::ArmFault::to64, and ArmISA::ArmFault::toEL.
bool ArmISA::PrefetchAbort::routeToHyp (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 1098 of file faults.cc.
References ArmISA::cpsr, ArmISA::ArmFault::DebugEvent, ArmISA::inSecureState(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_HDCR, ArmISA::MISCREG_SCR, ArmISA::MODE_HYP, ArmISA::MODE_USER, ThreadContext::readMiscRegNoEffect(), ArmISA::scr, ArmISA::AbortFault< PrefetchAbort >::source, ArmISA::AbortFault< PrefetchAbort >::stage2, and ArmISA::ArmFault::SynchronousExternalAbort.
bool ArmISA::PrefetchAbort::routeToMonitor (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFaultVals< PrefetchAbort >.
Definition at line 1086 of file faults.cc.
References ArmISA::ArmFault::from64, ArmISA::AbortFault< PrefetchAbort >::isMMUFault(), ArmISA::MISCREG_SCR, ArmISA::MISCREG_SCR_EL3, ThreadContext::readMiscRegNoEffect(), and ArmISA::scr.
Member Data Documentation
const MiscRegIndex ArmISA::PrefetchAbort::FarIndex = MISCREG_IFAR [static]
Definition at line 422 of file faults.hh.
const MiscRegIndex ArmISA::PrefetchAbort::FsrIndex = MISCREG_IFSR [static]
Definition at line 421 of file faults.hh.
const MiscRegIndex ArmISA::PrefetchAbort::HFarIndex = MISCREG_HIFAR [static]
Definition at line 423 of file faults.hh.
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc