gem5: AddressCountTable Class Reference
AddressCountTable Class Reference
#include <addr_tables.hh>
Public Member Functions
AddressCountTable ()
void increment (Addr addr, uint64_t n=1)
void insert (Addr addr, uint64_t n=0)
void remove (Addr addr)
bool isExist (const Addr addr) const
const uint64_t getCount (Addr addr) const
std::vector< Addr > allAddress ()
void clearAll ()
uint64_t & operator[] (const Addr addr)
Private Attributes
std::unordered_map< Addr,
uint64_t > ct
Friends
class AddressCountTableVisitor
Detailed Description
Definition at line 31 of file addr_tables.hh.
Constructor & Destructor Documentation
AddressCountTable::AddressCountTable () [inline]
Definition at line 37 of file addr_tables.hh.
References clearAll().
Member Function Documentation
std::vector<Addr> AddressCountTable::allAddress () [inline]
Definition at line 75 of file addr_tables.hh.
References ct.
void AddressCountTable::clearAll () [inline]
Definition at line 86 of file addr_tables.hh.
References ct.
Referenced by AddressCountTable().
const uint64_t AddressCountTable::getCount (Addr addr) const [inline]
Definition at line 68 of file addr_tables.hh.
References ct, and panic.
void AddressCountTable::increment (Addr addr, uint64_t n = 1) [inline]
Definition at line 41 of file addr_tables.hh.
References ct, ArmISA::n, and panic.
void AddressCountTable::insert (Addr addr, uint64_t n = 0) [inline]
Definition at line 48 of file addr_tables.hh.
References ct, isExist(), ArmISA::n, and panic.
bool AddressCountTable::isExist (const Addr addr) const [inline]
Definition at line 61 of file addr_tables.hh.
References ct.
Referenced by insert().
uint64_t& AddressCountTable::operator[] (const Addr addr) [inline]
Definition at line 88 of file addr_tables.hh.
References ct.
void AddressCountTable::remove (Addr addr) [inline]
Definition at line 54 of file addr_tables.hh.
References X86ISA::addr, ct, and panic.
Friends And Related Function Documentation
friend class AddressCountTableVisitor [friend]
Definition at line 92 of file addr_tables.hh.
Member Data Documentation
std::unordered_map<Addr, uint64_t> AddressCountTable::ct [private]
Definition at line 34 of file addr_tables.hh.
Referenced by allAddress(), clearAll(), getCount(), increment(), insert(), isExist(), operator[](), and remove().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/addr_tables.hh