gem5: VirtIO9PBase::FSQueue Class Reference
VirtIO9PBase::FSQueue Class Reference
Virtqueue for 9p requests.
#include <fs9p.hh>
Public Member Functions
FSQueue (PortProxy &proxy, uint16_t size, VirtIO9PBase &_parent)
virtual ~FSQueue ()
void onNotifyDescriptor (VirtDescriptor *desc)
Notify queue of pending incoming descriptor.
std::string name () const
Protected Attributes
VirtIO9PBase & parent
Detailed Description
Virtqueue for 9p requests.
Definition at line 147 of file fs9p.hh.
Constructor & Destructor Documentation
VirtIO9PBase::FSQueue::FSQueue (PortProxy & proxy, uint16_t size, VirtIO9PBase & _parent) [inline]
Definition at line 150 of file fs9p.hh.
virtual VirtIO9PBase::FSQueue::~FSQueue () [inline, virtual]
Definition at line 152 of file fs9p.hh.
Member Function Documentation
std::string VirtIO9PBase::FSQueue::name () const [inline]
Definition at line 156 of file fs9p.hh.
References SimObject::name(), and parent.
void VirtIO9PBase::FSQueue::onNotifyDescriptor (VirtDescriptor * desc) [virtual]
Notify queue of pending incoming descriptor.
This method is called by the default implementation of onNotify() to notify the device model of pending data in a descriptor chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented from VirtQueue.
Definition at line 135 of file fs9p.cc.
References VirtDescriptor::chainRead(), DPRINTF, VirtIO9PBase::dumpMsg(), p9toh(), parent, VirtIO9PBase::pendingTransactions, VirtIO9PBase::recvTMsg(), and VirtDescriptor::size().
Member Data Documentation
VirtIO9PBase& VirtIO9PBase::FSQueue::parent [protected]
Definition at line 159 of file fs9p.hh.
Referenced by name(), and onNotifyDescriptor().
The documentation for this class was generated from the following files:
dev/virtio/fs9p.hh
dev/virtio/fs9p.cc