gem5: VirtIODeviceBase Class Reference
VirtIODeviceBase Class Reference
Base class for all VirtIO-based devices.
#include <base.hh>
Public Types
typedef uint16_t QueueID
typedef uint32_t FeatureBits
typedef uint16_t VirtAddress
This is a VirtQueue address as exposed through the low-level interface. The address needs to be multiplied by the page size (seems to be hardcoded to 4096 in the spec) to get the real physical address.
typedef uint16_t DeviceId
Device Type (sometimes known as subsystem ID).
Public Member Functions
BitUnion8 (DeviceStatus) Bitfield< 7 > failed
EndBitUnion (DeviceStatus) typedef VirtIODeviceBaseParams Params
VirtIODeviceBase (Params *params, DeviceId id, size_t config_size, FeatureBits features)
virtual ~VirtIODeviceBase ()
SimObject Interfaces
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Optional VirtIO Interfaces
virtual void readConfig (PacketPtr pkt, Addr cfgOffset)
Read from the configuration space of a device.
virtual void writeConfig (PacketPtr pkt, Addr cfgOffset)
Write to the configuration space of a device.
virtual void reset ()
Driver-request device reset.
Public Attributes
Bitfield< 2 > driver_ok
Bitfield< 1 > driver
Bitfield< 0 > acknowledge
Protected Member Functions
Device Model Helpers
void readConfigBlob (PacketPtr pkt, Addr cfgOffset, const uint8_t *cfg)
Read configuration data from a device structure.
void writeConfigBlob (PacketPtr pkt, Addr cfgOffset, uint8_t *cfg)
Write configuration data to a device structure.
Private Member Functions
const VirtQueue & getCurrentQueue () const
Convenience method to get the currently selected queue.
VirtQueue & getCurrentQueue ()
Convenience method to get the currently selected queue.
Private Attributes
DeviceStatus _deviceStatus
Status of the device.
QueueID _queueSelect
Queue select register (set by guest).
std::vector< VirtQueue * > _queues
List of virtual queues supported by this device.
Callback * transKick
Callbacks to kick the guest through the transport layer.
VirtIO Transport Interfaces
const DeviceId deviceId
Device ID (sometimes known as subsystem ID).
const size_t configSize
Size of the device's configuration space.
const FeatureBits deviceFeatures
Feature set offered by the device.
void registerKickCallback (Callback *c)
Register a callback to kick the guest through the transport interface.
void onNotify (QueueID index)
Driver is requesting service.
void setQueueSelect (QueueID idx)
Change currently active queue.
QueueID getQueueSelect () const
Get the currently active queue.
void setQueueAddress (uint32_t address)
Change the host physical address of the currently active queue.
uint32_t getQueueAddress () const
Get the host physical address of the currently active queue.
uint16_t getQueueSize () const
Get the size (descriptors) of the currently active queue.
void setDeviceStatus (DeviceStatus status)
Update device status and optionally reset device.
DeviceStatus getDeviceStatus () const
Retrieve the device status.
void setGuestFeatures (FeatureBits features)
Set feature bits accepted by the guest driver.
FeatureBits getGuestFeatures () const
Get features accepted by the guest driver.
Device Model Interfaces
FeatureBits guestFeatures
Feature set accepted by the guest.
void kick ()
Inform the guest of available buffers.
void registerQueue (VirtQueue &queue)
Register a new VirtQueue with the device model.
Detailed Description
Base class for all VirtIO-based devices.
This class implements the functionality of the VirtIO 0.9.5 specification. This version of VirtIO is also known as "legacy" in the VirtIO 1.0 specification from OASIS.
See also:
https://github.com/rustyrussell/virtio-spec
http://docs.oasis-open.org/virtio/virtio/v1.0/virtio-v1.0.html
Definition at line 569 of file base.hh.
Member Typedef Documentation
typedef uint16_t VirtIODeviceBase::DeviceId
Device Type (sometimes known as subsystem ID).
Definition at line 581 of file base.hh.
typedef uint32_t VirtIODeviceBase::FeatureBits
Definition at line 573 of file base.hh.
typedef uint16_t VirtIODeviceBase::QueueID
Definition at line 572 of file base.hh.
typedef uint16_t VirtIODeviceBase::VirtAddress
This is a VirtQueue address as exposed through the low-level interface. The address needs to be multiplied by the page size (seems to be hardcoded to 4096 in the spec) to get the real physical address.
Definition at line 579 of file base.hh.
Constructor & Destructor Documentation
VirtIODeviceBase::VirtIODeviceBase (Params * params, DeviceId id, size_t config_size, FeatureBits features)
Definition at line 323 of file base.cc.
VirtIODeviceBase::~VirtIODeviceBase () [virtual]
Definition at line 334 of file base.cc.
Member Function Documentation
VirtIODeviceBase::BitUnion8 (DeviceStatus)
VirtIODeviceBase::EndBitUnion (DeviceStatus)
VirtQueue & VirtIODeviceBase::getCurrentQueue () [private]
Convenience method to get the currently selected queue.
Definition at line 456 of file base.cc.
References _queues, _queueSelect, and panic.
const VirtQueue & VirtIODeviceBase::getCurrentQueue () const [private]
Convenience method to get the currently selected queue.
Definition at line 447 of file base.cc.
References _queues, _queueSelect, and panic.
Referenced by getQueueAddress(), getQueueSize(), and setQueueAddress().
DeviceStatus VirtIODeviceBase::getDeviceStatus () const [inline]
Retrieve the device status.
Returns:
Device status.
Definition at line 830 of file base.hh.
References _deviceStatus.
Referenced by PciVirtIO::read().
FeatureBits VirtIODeviceBase::getGuestFeatures () const [inline]
Get features accepted by the guest driver.
Returns:
Currently active features.
Definition at line 845 of file base.hh.
References guestFeatures.
Referenced by PciVirtIO::read().
uint32_t VirtIODeviceBase::getQueueAddress () const
Get the host physical address of the currently active queue.
Note:
The new address is specified in multiples of the page size (fixed to 4096 bytes in the standard). For example, if the address 10 is selected, the actual host physical address will be 40960.
See also:
setQueueSelect
getQueueSelect
Returns:
Address of the currently active queue (in pages).
Definition at line 471 of file base.cc.
References VirtQueue::ALIGN_BITS, and getCurrentQueue().
Referenced by PciVirtIO::read().
QueueID VirtIODeviceBase::getQueueSelect () const [inline]
Get the currently active queue.
The transport interface works on a queue at a time. The currently active queue is decided by the value of the queue select field in a device.
Returns:
The ID of the currently active queue.
Definition at line 775 of file base.hh.
References _queueSelect.
Referenced by PciVirtIO::read().
uint16_t VirtIODeviceBase::getQueueSize () const [inline]
Get the size (descriptors) of the currently active queue.
Returns:
Size of the currently active queue in number of descriptors.
Definition at line 813 of file base.hh.
References getCurrentQueue(), and VirtQueue::getSize().
Referenced by PciVirtIO::read().
void VirtIODeviceBase::kick () [inline, protected]
Inform the guest of available buffers.
When a device model has finished processing incoming buffers (after onNotify has been called), it typically needs to inform the guest that there are new pending outgoing buffers. The method used to inform the guest is transport dependent, but is typically through an interrupt. Device models call this method to tell the transport interface to notify the guest.
Definition at line 621 of file base.hh.
References Callback::process(), and transKick.
Referenced by VirtIOConsole::TermTransQueue::onNotifyDescriptor(), VirtIOBlock::RequestQueue::onNotifyDescriptor(), VirtIO9PBase::sendRMsg(), and VirtIOConsole::TermRecvQueue::trySend().
void VirtIODeviceBase::onNotify (QueueID index)
Driver is requesting service.
This method is called by the underlying hardware interface (e.g., PciVirtIO or MmmioVirtIO) to notify a device of pending incoming descriptors.
Parameters:
index ID of the queue with pending actions.
Definition at line 374 of file base.cc.
References _queues, DPRINTF, and panic.
Referenced by PciVirtIO::write().
void VirtIODeviceBase::readConfig (PacketPtr pkt, Addr cfgOffset) [virtual]
Read from the configuration space of a device.
This method is called by the transport interface to read data from a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning:
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters:
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
Reimplemented in VirtIOBlock, VirtIOConsole, and VirtIO9PBase.
Definition at line 410 of file base.cc.
References panic.
Referenced by PciVirtIO::read().
void VirtIODeviceBase::readConfigBlob (PacketPtr pkt, Addr cfgOffset, const uint8_t * cfg) [protected]
Read configuration data from a device structure.
Parameters:
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
cfg Device configuration
Definition at line 422 of file base.cc.
References configSize, Packet::getSize(), Packet::makeResponse(), panic, and Packet::setData().
Referenced by VirtIO9PBase::readConfig(), VirtIOConsole::readConfig(), and VirtIOBlock::readConfig().
void VirtIODeviceBase::registerKickCallback (Callback * c) [inline]
Register a callback to kick the guest through the transport interface.
Parameters:
c Callback into transport interface.
Definition at line 738 of file base.hh.
References transKick.
Referenced by PciVirtIO::PciVirtIO().
void VirtIODeviceBase::registerQueue (VirtQueue & queue) [protected]
Register a new VirtQueue with the device model.
Devices typically register at least one VirtQueue to use for communication with the guest. This must be done from the constructor since the number of queues are assumed to be constant throughout the lifetime of the device.
Warning:
This method may only be called from the device model constructor.
Definition at line 479 of file base.cc.
References _queues.
Referenced by VirtIO9PBase::VirtIO9PBase(), VirtIOBlock::VirtIOBlock(), and VirtIOConsole::VirtIOConsole().
void VirtIODeviceBase::reset () [virtual]
Driver-request device reset.
The device driver may reset a device by writing zero to the device status register (using setDeviceStatus()), which causes this method to be called. Device models overriding this method must ensure that the reset method of the base class is called when the device is reset.
Note:
Always call the reset method of the base class from device-specific reset methods.
Definition at line 363 of file base.cc.
References _deviceStatus, _queues, _queueSelect, guestFeatures, and ArmISA::i.
Referenced by setDeviceStatus().
void VirtIODeviceBase::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Reimplemented in VirtIO9PProxy.
Definition at line 339 of file base.cc.
References _deviceStatus, _queues, _queueSelect, csprintf(), guestFeatures, ArmISA::i, SimObject::name(), Serializable::nameOut(), paramOut(), and SERIALIZE_SCALAR.
void VirtIODeviceBase::setDeviceStatus (DeviceStatus status)
Update device status and optionally reset device.
The special device status of 0 is used to reset the device by calling reset().
Parameters:
status New device status.
Definition at line 400 of file base.cc.
References _deviceStatus, DPRINTF, and reset().
Referenced by PciVirtIO::write().
void VirtIODeviceBase::setGuestFeatures (FeatureBits features)
Set feature bits accepted by the guest driver.
This enables a subset of the features offered by the device model through the getGuestFeatures() interface.
Definition at line 386 of file base.cc.
References deviceFeatures, DPRINTF, guestFeatures, and panic.
Referenced by PciVirtIO::write().
void VirtIODeviceBase::setQueueAddress (uint32_t address)
Change the host physical address of the currently active queue.
Note:
The new address is specified in multiples of the page size (fixed to 4096 bytes in the standard). For example, if the address 10 is selected, the actual host physical address will be 40960.
See also:
setQueueSelect
getQueueSelect
Parameters:
address New address of the currently active queue (in pages).
Definition at line 465 of file base.cc.
References VirtQueue::ALIGN_SIZE, getCurrentQueue(), and VirtQueue::setAddress().
Referenced by PciVirtIO::write().
void VirtIODeviceBase::setQueueSelect (QueueID idx) [inline]
Change currently active queue.
The transport interface works on a queue at a time. The currently active queue is decided by the value of the queue select field in a device.
Parameters:
idx ID of the queue to select.
Definition at line 765 of file base.hh.
References _queueSelect.
Referenced by PciVirtIO::write().
void VirtIODeviceBase::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Reimplemented in VirtIO9PProxy.
Definition at line 351 of file base.cc.
References _deviceStatus, _queues, _queueSelect, csprintf(), guestFeatures, ArmISA::i, paramIn(), ArmISA::status, and UNSERIALIZE_SCALAR.
void VirtIODeviceBase::writeConfig (PacketPtr pkt, Addr cfgOffset) [virtual]
Write to the configuration space of a device.
This method is called by the transport interface to write data into a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning:
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters:
pkt Write request packet.
cfgOffset Offset into the device's configuration space.
Definition at line 416 of file base.cc.
References panic.
Referenced by PciVirtIO::write().
void VirtIODeviceBase::writeConfigBlob (PacketPtr pkt, Addr cfgOffset, uint8_t * cfg) [protected]
Write configuration data to a device structure.
Parameters:
pkt Write request packet.
cfgOffset Offset into the device's configuration space.
cfg Device configuration
Definition at line 434 of file base.cc.
References configSize, Packet::getSize(), Packet::makeResponse(), panic, and Packet::writeData().
Member Data Documentation
DeviceStatus VirtIODeviceBase::_deviceStatus [private]
Status of the device.
See also:
getDeviceStatus
setDeviceStatus
Definition at line 869 of file base.hh.
Referenced by getDeviceStatus(), reset(), serialize(), setDeviceStatus(), and unserialize().
std::vector<VirtQueue *> VirtIODeviceBase::_queues [private]
List of virtual queues supported by this device.
Definition at line 875 of file base.hh.
Referenced by getCurrentQueue(), onNotify(), registerQueue(), reset(), serialize(), and unserialize().
QueueID VirtIODeviceBase::_queueSelect [private]
Queue select register (set by guest).
Definition at line 872 of file base.hh.
Referenced by getCurrentQueue(), getQueueSelect(), reset(), serialize(), setQueueSelect(), and unserialize().
Bitfield<0> VirtIODeviceBase::acknowledge
Definition at line 587 of file base.hh.
const size_t VirtIODeviceBase::configSize
Size of the device's configuration space.
Definition at line 851 of file base.hh.
Referenced by PciVirtIO::PciVirtIO(), readConfigBlob(), VirtIO9PBase::VirtIO9PBase(), and writeConfigBlob().
const FeatureBits VirtIODeviceBase::deviceFeatures
Feature set offered by the device.
Definition at line 854 of file base.hh.
Referenced by PciVirtIO::read(), and setGuestFeatures().
const DeviceId VirtIODeviceBase::deviceId
Device ID (sometimes known as subsystem ID).
Definition at line 848 of file base.hh.
Referenced by PciVirtIO::PciVirtIO().
Bitfield<1> VirtIODeviceBase::driver
Definition at line 586 of file base.hh.
Bitfield<2> VirtIODeviceBase::driver_ok
Definition at line 585 of file base.hh.
FeatureBits VirtIODeviceBase::guestFeatures [protected]
Feature set accepted by the guest.
When the guest starts the driver for the device, it starts by negotiating features. The device first offers a set of features (see deviceFeatures), the driver then notifies the device of which features it accepted. The base class will automatically accept any feature set that is a subset of the features offered by the device.
Definition at line 650 of file base.hh.
Referenced by getGuestFeatures(), reset(), serialize(), setGuestFeatures(), and unserialize().
Callback* VirtIODeviceBase::transKick [private]
Callbacks to kick the guest through the transport layer.
Definition at line 878 of file base.hh.
Referenced by kick(), and registerKickCallback().
The documentation for this class was generated from the following files:
dev/virtio/base.hh
dev/virtio/base.cc