gem5: FLIPProfiler Class Reference
FLIPProfiler Class Reference
#include <flip_prof.hh>
Classes
class SamplingEvent
Public Types
typedef FLIPProfilerParams Params
Convenience typedef.
Public Member Functions
FLIPProfiler (const Params *p)
virtual void startup ()
startup() is the final initialization call before simulation.
virtual void regStats ()
Register local statistics.
virtual BlkType * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
virtual BlkType * findVictim (Addr addr)
Find an invalid block to evict for the address provided.
virtual void insertBlock (PacketPtr pkt, BlkType *blk)
Insert the new block into the cache.
virtual void invalidate (BlkType *blk)
Invalidate the given block.
bool should_be_profiled (BlkType *blk) const
void sampling ()
Private Attributes
BaseTagsProfiler * profilers
Tick interval
SamplingEvent * se
Detailed Description
Definition at line 15 of file flip_prof.hh.
Member Typedef Documentation
typedef FLIPProfilerParams FLIPProfiler::Params
Convenience typedef.
Reimplemented from FLIP.
Definition at line 34 of file flip_prof.hh.
Constructor & Destructor Documentation
FLIPProfiler::FLIPProfiler (const Params * p)
Definition at line 16 of file flip_prof.cc.
References BaseTagsProfiler::add(), ClockedObject::clockEdge(), BaseSetAssoc::getBlockSize(), inform, interval, SimObject::name(), BaseSetAssoc::numSets, profilers, and se.
Member Function Documentation
BaseSetAssoc::BlkType * FLIPProfiler::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Reimplemented from FLIP.
Definition at line 43 of file flip_prof.cc.
References BaseTagsProfiler::access(), profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, should_be_profiled(), and CacheBlk::tag.
BaseSetAssoc::BlkType * FLIPProfiler::findVictim (Addr addr) [virtual]
Find an invalid block to evict for the address provided.
If there are no invalid blocks, this will return the block in the least-recently-used position.
Parameters:
addr The addr to a find a replacement candidate for.
Returns:
The candidate block.
Reimplemented from FLIP.
Definition at line 56 of file flip_prof.cc.
References profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, should_be_profiled(), CacheBlk::tag, and BaseTagsProfiler::victim().
void FLIPProfiler::insertBlock (PacketPtr pkt, BlkType * blk) [virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Reimplemented from FLIP.
Definition at line 69 of file flip_prof.cc.
References BaseTagsProfiler::insert(), profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, and CacheBlk::tag.
void FLIPProfiler::invalidate (BlkType * blk) [virtual]
Invalidate the given block.
Parameters:
blk The block to invalidate.
Reimplemented from FLIP.
Definition at line 77 of file flip_prof.cc.
References profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, CacheBlk::tag, and BaseTagsProfiler::victim().
void FLIPProfiler::regStats () [virtual]
Register local statistics.
Reimplemented from FLIP.
Definition at line 36 of file flip_prof.cc.
References profilers, and BaseTagsProfiler::regStats().
void FLIPProfiler::sampling () [inline]
Definition at line 48 of file flip_prof.hh.
References curTick(), interval, profilers, BaseTagsProfiler::sampling(), EventManager::schedule(), and se.
Referenced by FLIPProfiler::SamplingEvent::process().
bool FLIPProfiler::should_be_profiled (BlkType * blk) const
Definition at line 86 of file flip_prof.cc.
References CacheBlk::isValid().
Referenced by accessBlock(), and findVictim().
void FLIPProfiler::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from FLIP.
Definition at line 30 of file flip_prof.cc.
References curTick(), interval, EventManager::schedule(), and se.
Member Data Documentation
Tick FLIPProfiler::interval [private]
Definition at line 19 of file flip_prof.hh.
Referenced by FLIPProfiler(), sampling(), and startup().
BaseTagsProfiler* FLIPProfiler::profilers [private]
Definition at line 18 of file flip_prof.hh.
Referenced by accessBlock(), findVictim(), FLIPProfiler(), insertBlock(), invalidate(), regStats(), and sampling().
SamplingEvent* FLIPProfiler::se [private]
Definition at line 32 of file flip_prof.hh.
Referenced by FLIPProfiler(), sampling(), and startup().
The documentation for this class was generated from the following files:
mem/cache/tags/flip_prof.hh
mem/cache/tags/flip_prof.cc