gem5: CacheBlkPrintWrapper Class Reference
CacheBlkPrintWrapper Class Reference
Simple class to provide virtual print() method on cache blocks without allocating a vtable pointer for every single cache block.
#include <blk.hh>
Public Member Functions
CacheBlkPrintWrapper (CacheBlk *_blk)
virtual ~CacheBlkPrintWrapper ()
void print (std::ostream &o, int verbosity=0, const std::string &prefix="") const
Private Attributes
CacheBlk * blk
Detailed Description
Simple class to provide virtual print() method on cache blocks without allocating a vtable pointer for every single cache block.
Just wrap the CacheBlk object in an instance of this before passing to a function that requires a Printable object.
Definition at line 392 of file blk.hh.
Constructor & Destructor Documentation
CacheBlkPrintWrapper::CacheBlkPrintWrapper (CacheBlk * _blk) [inline]
Definition at line 396 of file blk.hh.
virtual CacheBlkPrintWrapper::~CacheBlkPrintWrapper () [inline, virtual]
Definition at line 397 of file blk.hh.
Member Function Documentation
void CacheBlkPrintWrapper::print (std::ostream & o, int verbosity = 0, const std::string & prefix = "") const [virtual]
Implements Printable.
Definition at line 45 of file blk.cc.
References blk, ccprintf(), CacheBlk::isDirty(), CacheBlk::isSecure(), CacheBlk::isValid(), and CacheBlk::isWritable().
Member Data Documentation
CacheBlk* CacheBlkPrintWrapper::blk [private]
Definition at line 394 of file blk.hh.
Referenced by print().
The documentation for this class was generated from the following files:
mem/cache/blk.hh
mem/cache/blk.cc