gem5: Terminal Class Reference
Terminal Class Reference
#include <terminal.hh>
Classes
class DataEvent
class ListenEvent
Public Types
typedef TerminalParams Params
Public Member Functions
void regDataAvailCallback (Callback *c)
Register a data available callback into the transport layer.
Terminal (const Params *p)
~Terminal ()
void data ()
void read (uint8_t &c)
size_t read (uint8_t *buf, size_t len)
void write (uint8_t c)
size_t write (const uint8_t *buf, size_t len)
void detach ()
uint8_t in ()
uint64_t console_in ()
void out (char c)
bool dataAvailable ()
Protected Member Functions
void listen (int port)
void accept ()
Protected Attributes
Callback * termDataAvail
Currently registered transport layer callbacks.
ListenEvent * listenEvent
DataEvent * dataEvent
int number
int data_fd
ListenSocket listener
CircleBuf txbuf
CircleBuf rxbuf
std::ostream * outfile
Friends
class ListenEvent
class DataEvent
Detailed Description
Definition at line 51 of file terminal.hh.
Member Typedef Documentation
typedef TerminalParams Terminal::Params
Reimplemented from SimObject.
Definition at line 101 of file terminal.hh.
Constructor & Destructor Documentation
Terminal::Terminal (const Params * p)
Definition at line 109 of file terminal.cc.
References OutputDirectory::create(), OutputDirectory::find(), listen(), outfile, and simout.
Terminal::~Terminal ()
Definition at line 128 of file terminal.cc.
References data_fd, dataEvent, and listenEvent.
Member Function Documentation
void Terminal::accept () [protected]
Definition at line 181 of file terminal.cc.
References ListenSocket::accept(), atomic_write(), ccprintf(), data_fd, DataEvent, dataEvent, DPRINTFN, ArmISA::fd, ListenSocket::islistening(), listener, SimObject::name(), number, panic, pollQueue, CircleBuf::readall(), PollQueue::schedule(), txbuf, and write().
Referenced by Terminal::ListenEvent::process().
uint64_t Terminal::console_in ()
Definition at line 299 of file terminal.cc.
References dataAvailable(), DPRINTF, CircleBuf::empty(), in(), MORE_PENDING, RECEIVE_NONE, RECEIVE_SUCCESS, and rxbuf.
Referenced by AlphaBackdoor::read().
void Terminal::data ()
Definition at line 228 of file terminal.cc.
References ArmISA::len, Callback::process(), read(), rxbuf, termDataAvail, and CircleBuf::write().
Referenced by Terminal::DataEvent::process().
bool Terminal::dataAvailable () [inline]
Definition at line 156 of file terminal.hh.
References CircleBuf::empty(), and rxbuf.
Referenced by console_in(), Uart8250::read(), Pl011::read(), VirtIOConsole::TermRecvQueue::trySend(), and Uart8250::write().
void Terminal::detach ()
Definition at line 213 of file terminal.cc.
References data_fd, dataEvent, DPRINTFN, number, pollQueue, and PollQueue::remove().
Referenced by Terminal::DataEvent::process(), read(), and write().
uint8_t Terminal::in ()
Definition at line 285 of file terminal.cc.
References ArmISA::c, DPRINTF, CircleBuf::empty(), CircleBuf::read(), and rxbuf.
Referenced by console_in(), Uart8250::read(), Pl011::read(), and VirtIOConsole::TermRecvQueue::trySend().
void Terminal::listen (int port) [protected]
Definition at line 156 of file terminal.cc.
References ListenSocket::allDisabled(), ccprintf(), DPRINTF, ListenSocket::getfd(), ListenSocket::listen(), listener, ListenEvent, listenEvent, SimObject::name(), pollQueue, PollQueue::schedule(), and warn_once.
Referenced by Terminal().
void Terminal::out (char c)
Definition at line 317 of file terminal.cc.
References data_fd, DPRINTF, DTRACE, outfile, txbuf, write(), and CircleBuf::write().
Referenced by VirtIOConsole::TermTransQueue::onNotifyDescriptor(), Uart8250::write(), Pl011::write(), and AlphaBackdoor::write().
size_t Terminal::read (uint8_t * buf, size_t len)
Definition at line 243 of file terminal.cc.
References data_fd, detach(), DPRINTFN, panic, and read().
void Terminal::read (uint8_t & c) [inline]
Definition at line 125 of file terminal.hh.
References read().
Referenced by data(), and read().
void Terminal::regDataAvailCallback (Callback * c)
Register a data available callback into the transport layer.
The terminal needs to call the underlying transport layer to inform it of available data. The transport layer uses this method to register a callback that informs it of pending data.
Parameters:
c Callback instance from transport layer.
Definition at line 141 of file terminal.cc.
References fatal, and termDataAvail.
Referenced by Uart::Uart(), and VirtIOConsole::VirtIOConsole().
size_t Terminal::write (const uint8_t * buf, size_t len)
Definition at line 267 of file terminal.cc.
References atomic_write(), data_fd, detach(), and panic.
void Terminal::write (uint8_t c) [inline]
Definition at line 127 of file terminal.hh.
References write().
Referenced by accept(), out(), and write().
Friends And Related Function Documentation
friend class DataEvent [friend]
Definition at line 93 of file terminal.hh.
Referenced by accept().
friend class ListenEvent [friend]
Definition at line 80 of file terminal.hh.
Referenced by listen().
Member Data Documentation
int Terminal::data_fd [protected]
Definition at line 98 of file terminal.hh.
Referenced by accept(), detach(), out(), read(), write(), and ~Terminal().
DataEvent* Terminal::dataEvent [protected]
Definition at line 94 of file terminal.hh.
Referenced by accept(), detach(), and ~Terminal().
ListenSocket Terminal::listener [protected]
Definition at line 106 of file terminal.hh.
Referenced by accept(), and listen().
ListenEvent* Terminal::listenEvent [protected]
Definition at line 81 of file terminal.hh.
Referenced by listen(), and ~Terminal().
int Terminal::number [protected]
Definition at line 97 of file terminal.hh.
Referenced by accept(), and detach().
std::ostream* Terminal::outfile [protected]
Definition at line 114 of file terminal.hh.
Referenced by out(), and Terminal().
CircleBuf Terminal::rxbuf [protected]
Definition at line 113 of file terminal.hh.
Referenced by console_in(), data(), dataAvailable(), and in().
Callback* Terminal::termDataAvail [protected]
Currently registered transport layer callbacks.
Definition at line 67 of file terminal.hh.
Referenced by data(), and regDataAvailCallback().
CircleBuf Terminal::txbuf [protected]
Definition at line 112 of file terminal.hh.
Referenced by accept(), and out().
The documentation for this class was generated from the following files:
dev/terminal.hh
dev/terminal.cc