gem5: Stats::VectorDistribution Class Reference
Stats::VectorDistribution Class Reference
["Statistic Types"]
A vector of distributions.
#include <statistics.hh>
Public Member Functions
VectorDistribution & init (size_type size, Counter min, Counter max, Counter bkt)
Initialize storage and parameters for this distribution.
Detailed Description
A vector of distributions.
See also:
VectorDistBase, DistStor
Definition at line 2593 of file statistics.hh.
Member Function Documentation
VectorDistribution& Stats::VectorDistribution::init (size_type size, Counter min, Counter max, Counter bkt) [inline]
Initialize storage and parameters for this distribution.
Parameters:
size The size of the vector (the number of distributions).
min The minimum value of the distribution.
max The maximum value of the distribution.
bkt The number of values in each bucket.
Returns:
A reference to this distribution.
Definition at line 2605 of file statistics.hh.
References Stats::DistStor::Params::bucket_size, Stats::DistStor::Params::buckets, Stats::VectorDistBase< VectorDistribution, DistStor >::doInit(), Stats::DistStor::Params::max, Stats::DistStor::Params::min, and Stats::InfoAccess::setParams().
Referenced by StatTest::init().
The documentation for this class was generated from the following file:
base/statistics.hh