gem5: BaseSetAssoc Class Reference
BaseSetAssoc Class Reference
A BaseSetAssoc cache tag store.
#include <base_set_assoc.hh>
Public Types
typedef CacheBlk BlkType
Typedef the block type used in this tag store.
typedef std::list< BlkType * > BlkList
Typedef for a list of pointers to the local block class.
typedef CacheSet< CacheBlk > SetType
Typedef the set type used in this tag store.
typedef BaseSetAssocParams Params
Convenience typedef.
Public Member Functions
BaseSetAssoc (const Params *p)
Construct and initialize this tag store.
virtual ~BaseSetAssoc ()
Destructor.
unsigned getBlockSize () const
Return the block size.
unsigned getSubBlockSize () const
Return the subblock size.
void invalidate (CacheBlk *blk)
Invalidate the given block.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
CacheBlk * findBlock (Addr addr, bool is_secure) const
Finds the given address in the cache, do not update replacement data.
CacheBlk * findVictim (Addr addr)
Find an invalid block to evict for the address provided.
void insertBlock (PacketPtr pkt, CacheBlk *blk)
Insert the new block into the cache.
Addr extractTag (Addr addr) const
Generate the tag from the given address.
int extractSet (Addr addr) const
Calculate the set index from the address.
Addr blkAlign (Addr addr) const
Align an address to the block size.
Addr regenerateBlkAddr (Addr tag, unsigned set) const
Regenerate the block address from the tag.
virtual void clearLocks ()
iterated through all blocks and clear all locks Needed to clear all lock tracking at once
virtual void cleanupRefs ()
Called at end of simulation to complete average block reference stats.
virtual std::string print () const
Print all tags used.
virtual void computeStats ()
Called prior to dumping stats to compute task occupancy.
void forEachBlk (CacheBlkVisitor &visitor) M5_ATTR_OVERRIDE
Visit each block in the tag store and apply a visitor to the block.
Protected Attributes
const unsigned assoc
The associativity of the cache.
const unsigned numSets
The number of sets in the cache.
const bool sequentialAccess
Whether tags and data are accessed sequentially.
SetType * sets
The cache sets.
BlkType * blks
The cache blocks.
uint8_t * dataBlks
The data blocks, 1 per cache block.
int setShift
The amount to shift the address to get the set.
int tagShift
The amount to shift the address to get the tag.
unsigned setMask
Mask out all bits that aren't part of the set index.
unsigned blkMask
Mask out all bits that aren't part of the block offset.
Detailed Description
A BaseSetAssoc cache tag store.
See also:
gem5 Memory System
The BaseSetAssoc tags provide a base, as well as the functionality common to any set associative tags. Any derived class must implement the methods related to the specifics of the actual replacment policy. These are:
BlkType* accessBlock(); BlkType* findVictim(); void insertBlock(); void invalidate();
Definition at line 76 of file base_set_assoc.hh.
Member Typedef Documentation
typedef std::list<BlkType*> BaseSetAssoc::BlkList
Typedef for a list of pointers to the local block class.
Definition at line 82 of file base_set_assoc.hh.
typedef CacheBlk BaseSetAssoc::BlkType
Typedef the block type used in this tag store.
Definition at line 80 of file base_set_assoc.hh.
typedef BaseSetAssocParams BaseSetAssoc::Params
Convenience typedef.
Reimplemented from BaseTags.
Reimplemented in BIP, DIP, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Definition at line 115 of file base_set_assoc.hh.
typedef CacheSet<CacheBlk> BaseSetAssoc::SetType
Typedef the set type used in this tag store.
Definition at line 84 of file base_set_assoc.hh.
Constructor & Destructor Documentation
BaseSetAssoc::BaseSetAssoc (const Params * p)
Construct and initialize this tag store.
Todo:
Make warmup percentage a parameter.
Definition at line 56 of file base_set_assoc.cc.
References CacheSet< Blktype >::assoc, assoc, blkMask, CacheSet< Blktype >::blks, blks, BaseTags::blkSize, CacheBlk::data, dataBlks, fatal, floorLog2(), ArmISA::i, CacheBlk::invalidate(), isPowerOf2(), CacheBlk::isTouched, ArmISA::j, BaseTags::numBlocks, numSets, CacheBlk::set, setMask, sets, setShift, CacheBlk::size, CacheBlk::tag, tagShift, BaseTags::warmupBound, and CacheBlk::whenReady.
BaseSetAssoc::~BaseSetAssoc () [virtual]
Destructor.
Definition at line 115 of file base_set_assoc.cc.
References blks, dataBlks, and sets.
Member Function Documentation
CacheBlk* BaseSetAssoc::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [inline, virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Implements BaseTags.
Reimplemented in DIP, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Definition at line 175 of file base_set_assoc.hh.
References BaseTags::accessLatency, assoc, BaseTags::cache, curTick(), BaseTags::dataAccesses, extractSet(), extractTag(), CacheSet< Blktype >::findBlk(), CacheBlk::refCount, sequentialAccess, sets, BaseTags::tagAccesses, ClockedObject::ticksToCycles(), and CacheBlk::whenReady.
Addr BaseSetAssoc::blkAlign (Addr addr) const [inline]
Align an address to the block size.
Parameters:
addr the address to align.
Returns:
The block address.
Definition at line 319 of file base_set_assoc.hh.
References blkMask.
void BaseSetAssoc::cleanupRefs () [virtual]
Called at end of simulation to complete average block reference stats.
Reimplemented from BaseTags.
Definition at line 157 of file base_set_assoc.cc.
References assoc, blks, ArmISA::i, numSets, CacheBlk::refCount, BaseTags::sampledRefs, and BaseTags::totalRefs.
void BaseSetAssoc::clearLocks () [virtual]
iterated through all blocks and clear all locks Needed to clear all lock tracking at once
Reimplemented from BaseTags.
Definition at line 132 of file base_set_assoc.cc.
References blks, CacheBlk::clearLoadLocks(), ArmISA::i, and BaseTags::numBlocks.
void BaseSetAssoc::computeStats () [virtual]
Called prior to dumping stats to compute task occupancy.
Reimplemented from BaseTags.
Definition at line 168 of file base_set_assoc.cc.
References BaseTags::ageTaskId, assoc, blks, curTick(), ArmISA::i, ArmISA::j, SimClock::Int::ms, numSets, ContextSwitchTaskId::NumTaskId, BaseTags::occupanciesTaskId, CacheBlk::task_id, and SimClock::Int::us.
int BaseSetAssoc::extractSet (Addr addr) const [inline, virtual]
Calculate the set index from the address.
Parameters:
addr The address to get the set from.
Returns:
The set index of the address.
Implements BaseTags.
Definition at line 309 of file base_set_assoc.hh.
References setMask, and setShift.
Referenced by DIP::accessBlock(), accessBlock(), findBlock(), RandomRepl::findVictim(), LRU::findVictim(), FLIP::findVictim(), findVictim(), LRU::insertBlock(), FLIP::insertBlock(), DIP::insertBlock(), BIP::insertBlock(), DIP::insertBlock_bip(), and DIP::insertBlock_lru().
Addr BaseSetAssoc::extractTag (Addr addr) const [inline, virtual]
Generate the tag from the given address.
Parameters:
addr The address to get the tag from.
Returns:
The tag of the address.
Implements BaseTags.
Definition at line 299 of file base_set_assoc.hh.
References tagShift.
Referenced by accessBlock(), findBlock(), and insertBlock().
CacheBlk * BaseSetAssoc::findBlock (Addr addr, bool is_secure) const [virtual]
Finds the given address in the cache, do not update replacement data.
i.e. This is a no-side-effect find of a block.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
Returns:
Pointer to the cache block if found.
Implements BaseTags.
Definition at line 123 of file base_set_assoc.cc.
References extractSet(), extractTag(), CacheSet< Blktype >::findBlk(), and sets.
CacheBlk* BaseSetAssoc::findVictim (Addr addr) [inline, virtual]
Find an invalid block to evict for the address provided.
If there are no invalid blocks, this will return the block in the least-recently-used position.
Parameters:
addr The addr to a find a replacement candidate for.
Returns:
The candidate block.
Implements BaseTags.
Reimplemented in FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Definition at line 224 of file base_set_assoc.hh.
References assoc, CacheSet< Blktype >::blks, extractSet(), ArmISA::i, CacheBlk::isValid(), and sets.
void BaseSetAssoc::forEachBlk (CacheBlkVisitor & visitor) [inline, virtual]
Visit each block in the tag store and apply a visitor to the block.
The visitor should be a function (or object that behaves like a function) that takes a cache block reference as its parameter and returns a bool. A visitor can request the traversal to be stopped by returning false, returning true causes it to be called for the next block in the tag store.
Parameters:
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 368 of file base_set_assoc.hh.
References assoc, blks, ArmISA::i, and numSets.
unsigned BaseSetAssoc::getBlockSize () const [inline]
Return the block size.
Returns:
the block size.
Definition at line 132 of file base_set_assoc.hh.
References BaseTags::blkSize.
Referenced by FLIPProfiler::FLIPProfiler(), and LRUProfiler::LRUProfiler().
unsigned BaseSetAssoc::getSubBlockSize () const [inline]
Return the subblock size.
In the case of BaseSetAssoc it is always the block size.
Returns:
The block size.
Definition at line 143 of file base_set_assoc.hh.
References BaseTags::blkSize.
void BaseSetAssoc::insertBlock (PacketPtr pkt, CacheBlk * blk) [inline, virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Implements BaseTags.
Reimplemented in BIP, DIP, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Definition at line 245 of file base_set_assoc.hh.
References X86ISA::addr, BaseTags::cache, curTick(), BaseTags::dataAccesses, extractTag(), Packet::getAddr(), CacheBlk::invalidate(), CacheBlk::isTouched, CacheBlk::isValid(), Request::masterId(), System::maxMasters(), BaseTags::occupancies, CacheBlk::refCount, BaseTags::replacements, Packet::req, BaseTags::sampledRefs, CacheBlk::srcMasterId, X86ISA::system, BaseCache::system, CacheBlk::tag, BaseTags::tagAccesses, BaseTags::tagsInUse, CacheBlk::task_id, Request::taskId(), CacheBlk::tickInserted, BaseTags::totalRefs, Stats::ScalarBase< Derived, Stor >::value(), BaseTags::warmedUp, BaseTags::warmupBound, and BaseTags::warmupCycle.
void BaseSetAssoc::invalidate (CacheBlk * blk) [inline, virtual]
Invalidate the given block.
Parameters:
blk The block to invalidate.
Implements BaseTags.
Reimplemented in FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Definition at line 152 of file base_set_assoc.hh.
References BaseTags::cache, curTick(), Request::invldMasterId, CacheBlk::isValid(), System::maxMasters(), BaseTags::occupancies, CacheBlk::srcMasterId, BaseCache::system, BaseTags::tagsInUse, CacheBlk::task_id, CacheBlk::tickInserted, and ContextSwitchTaskId::Unknown.
std::string BaseSetAssoc::print () const [virtual]
Print all tags used.
Implements BaseTags.
Definition at line 140 of file base_set_assoc.cc.
References assoc, CacheSet< Blktype >::blks, csprintf(), ArmISA::i, CacheBlk::isValid(), ArmISA::j, numSets, CacheBlk::print(), and sets.
Addr BaseSetAssoc::regenerateBlkAddr (Addr tag, unsigned set) const [inline, virtual]
Regenerate the block address from the tag.
Parameters:
tag The tag of the block.
set The set of the block.
Returns:
The block address.
Implements BaseTags.
Definition at line 330 of file base_set_assoc.hh.
References setShift, and tagShift.
Referenced by LRUProfiler::accessBlock(), LRU::accessBlock(), FLIPProfiler::accessBlock(), DIP::accessBlock(), RandomRepl::findVictim(), LRUProfiler::findVictim(), LRU::findVictim(), FLIPProfiler::findVictim(), FLIP::findVictim(), LRUProfiler::insertBlock(), FLIPProfiler::insertBlock(), LRUProfiler::invalidate(), and FLIPProfiler::invalidate().
Member Data Documentation
const unsigned BaseSetAssoc::assoc [protected]
The associativity of the cache.
Definition at line 89 of file base_set_assoc.hh.
Referenced by FLIP::accessBlock(), accessBlock(), BaseSetAssoc(), cleanupRefs(), computeStats(), RandomRepl::findVictim(), LRU::findVictim(), FLIP::findVictim(), findVictim(), forEachBlk(), print(), and FLIP::regStats().
unsigned BaseSetAssoc::blkMask [protected]
Mask out all bits that aren't part of the block offset.
Definition at line 110 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), and blkAlign().
BlkType* BaseSetAssoc::blks [protected]
The cache blocks.
Definition at line 99 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), cleanupRefs(), clearLocks(), computeStats(), forEachBlk(), and ~BaseSetAssoc().
uint8_t* BaseSetAssoc::dataBlks [protected]
The data blocks, 1 per cache block.
Definition at line 101 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), and ~BaseSetAssoc().
const unsigned BaseSetAssoc::numSets [protected]
The number of sets in the cache.
Definition at line 91 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), DIP::checkConstituency(), cleanupRefs(), computeStats(), DIP::DIP(), FLIPProfiler::FLIPProfiler(), forEachBlk(), LRUProfiler::LRUProfiler(), and print().
const bool BaseSetAssoc::sequentialAccess [protected]
Whether tags and data are accessed sequentially.
Definition at line 93 of file base_set_assoc.hh.
Referenced by accessBlock().
unsigned BaseSetAssoc::setMask [protected]
Mask out all bits that aren't part of the set index.
Definition at line 108 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), and extractSet().
SetType* BaseSetAssoc::sets [protected]
The cache sets.
Definition at line 96 of file base_set_assoc.hh.
Referenced by LRU::accessBlock(), FLIP::accessBlock(), DIP::accessBlock(), accessBlock(), BaseSetAssoc(), findBlock(), RandomRepl::findVictim(), LRU::findVictim(), FLIP::findVictim(), findVictim(), LRU::insertBlock(), FLIP::insertBlock(), BIP::insertBlock(), DIP::insertBlock_bip(), DIP::insertBlock_lru(), LRU::invalidate(), FLIP::invalidate(), print(), and ~BaseSetAssoc().
int BaseSetAssoc::setShift [protected]
The amount to shift the address to get the set.
Definition at line 104 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), extractSet(), and regenerateBlkAddr().
int BaseSetAssoc::tagShift [protected]
The amount to shift the address to get the tag.
Definition at line 106 of file base_set_assoc.hh.
Referenced by BaseSetAssoc(), extractTag(), and regenerateBlkAddr().
The documentation for this class was generated from the following files:
mem/cache/tags/base_set_assoc.hh
mem/cache/tags/base_set_assoc.cc