gem5: Router_d Class Reference
Router_d Class Reference
#include <Router_d.hh>
Public Types
typedef GarnetRouter_dParams Params
Public Member Functions
Router_d (const Params *p)
~Router_d ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void addInPort (NetworkLink_d *link, CreditLink_d *credit_link)
void addOutPort (NetworkLink_d *link, const NetDest &routing_table_entry, int link_weight, CreditLink_d *credit_link)
int get_num_vcs ()
int get_num_vnets ()
int get_vc_per_vnet ()
int get_num_inports ()
int get_num_outports ()
int get_id ()
void init_net_ptr (GarnetNetwork_d *net_ptr)
GarnetNetwork_d * get_net_ptr ()
std::vector< InputUnit_d * > & get_inputUnit_ref ()
std::vector< OutputUnit_d * > & get_outputUnit_ref ()
void update_sw_winner (int inport, flit_d *t_flit)
void update_incredit (int in_port, int in_vc, int credit)
void route_req (flit_d *t_flit, InputUnit_d *in_unit, int invc)
void vcarb_req ()
void swarb_req ()
void printFaultVector (std::ostream &out)
void printAggregateFaultProbability (std::ostream &out)
void regStats ()
Register statistics for this object.
void collateStats ()
void resetStats ()
Reset statistics associated with this object.
bool get_fault_vector (int temperature, float fault_vector[])
bool get_aggregate_fault_probability (int temperature, float *aggregate_fault_prob)
uint32_t functionalWrite (Packet *)
Private Attributes
int m_virtual_networks
int m_num_vcs
int m_vc_per_vnet
GarnetNetwork_d * m_network_ptr
std::vector< InputUnit_d * > m_input_unit
std::vector< OutputUnit_d * > m_output_unit
RoutingUnit_d * m_routing_unit
VCallocator_d * m_vc_alloc
SWallocator_d * m_sw_alloc
Switch_d * m_switch
Stats::Scalar m_buffer_reads
Stats::Scalar m_buffer_writes
Stats::Scalar m_sw_local_arbiter_activity
Stats::Scalar m_sw_global_arbiter_activity
Stats::Scalar m_vc_local_arbiter_activity
Stats::Scalar m_vc_global_arbiter_activity
Stats::Scalar m_crossbar_activity
Detailed Description
Definition at line 54 of file Router_d.hh.
Member Typedef Documentation
typedef GarnetRouter_dParams Router_d::Params
Reimplemented from BasicRouter.
Definition at line 57 of file Router_d.hh.
Constructor & Destructor Documentation
Router_d::Router_d (const Params * p)
Definition at line 46 of file Router_d.cc.
References m_input_unit, m_num_vcs, m_output_unit, m_routing_unit, m_sw_alloc, m_switch, m_vc_alloc, m_vc_per_vnet, and m_virtual_networks.
Router_d::~Router_d ()
Definition at line 62 of file Router_d.cc.
References m5::stl_helpers::deletePointers(), m_input_unit, m_output_unit, m_routing_unit, m_sw_alloc, m_switch, and m_vc_alloc.
Member Function Documentation
void Router_d::addInPort (NetworkLink_d * link, CreditLink_d * credit_link)
Definition at line 83 of file Router_d.cc.
References InputUnit_d::getCreditQueue(), m_input_unit, InputUnit_d::set_credit_link(), InputUnit_d::set_in_link(), NetworkLink_d::setLinkConsumer(), and NetworkLink_d::setSourceQueue().
void Router_d::addOutPort (NetworkLink_d * link, const NetDest & routing_table_entry, int link_weight, CreditLink_d * credit_link)
Definition at line 97 of file Router_d.cc.
References RoutingUnit_d::addRoute(), RoutingUnit_d::addWeight(), OutputUnit_d::getOutQueue(), m_output_unit, m_routing_unit, OutputUnit_d::set_credit_link(), OutputUnit_d::set_out_link(), NetworkLink_d::setLinkConsumer(), and NetworkLink_d::setSourceQueue().
void Router_d::collateStats ()
Definition at line 186 of file Router_d.cc.
References Switch_d::get_crossbar_count(), SWallocator_d::get_global_arbit_count(), VCallocator_d::get_global_arbit_count(), SWallocator_d::get_local_arbit_count(), VCallocator_d::get_local_arbit_count(), ArmISA::i, ArmISA::j, m_buffer_reads, m_buffer_writes, m_crossbar_activity, m_input_unit, m_sw_alloc, m_sw_global_arbiter_activity, m_sw_local_arbiter_activity, m_switch, m_vc_alloc, m_vc_global_arbiter_activity, m_vc_local_arbiter_activity, and m_virtual_networks.
uint32_t Router_d::functionalWrite (Packet * pkt)
Definition at line 243 of file Router_d.cc.
References Switch_d::functionalWrite(), ArmISA::i, m_input_unit, m_output_unit, and m_switch.
bool Router_d::get_aggregate_fault_probability (int temperature, float * aggregate_fault_prob) [inline]
Definition at line 100 of file Router_d.hh.
References BaseGarnetNetwork::fault_model, FaultModel::fault_prob(), BasicRouter::m_id, and m_network_ptr.
Referenced by printAggregateFaultProbability().
bool Router_d::get_fault_vector (int temperature, float fault_vector[]) [inline]
Definition at line 96 of file Router_d.hh.
References BaseGarnetNetwork::fault_model, FaultModel::fault_vector(), BasicRouter::m_id, and m_network_ptr.
int Router_d::get_id () [inline]
Definition at line 72 of file Router_d.hh.
References BasicRouter::m_id.
Referenced by GarnetNetwork_d::init().
std::vector<InputUnit_d *>& Router_d::get_inputUnit_ref () [inline]
Definition at line 80 of file Router_d.hh.
References m_input_unit.
Referenced by VCallocator_d::init(), and SWallocator_d::init().
GarnetNetwork_d* Router_d::get_net_ptr () [inline]
Definition at line 79 of file Router_d.hh.
References m_network_ptr.
Referenced by SWallocator_d::arbitrate_inports(), VCallocator_d::arbitrate_invcs(), SWallocator_d::is_candidate_inport(), VCallocator_d::is_invc_candidate(), and OutputUnit_d::OutputUnit_d().
int Router_d::get_num_inports () [inline]
Definition at line 70 of file Router_d.hh.
References m_input_unit.
Referenced by VCallocator_d::init(), Switch_d::init(), SWallocator_d::init(), and GarnetNetwork_d::init().
int Router_d::get_num_outports () [inline]
Definition at line 71 of file Router_d.hh.
References m_output_unit.
Referenced by VCallocator_d::init(), SWallocator_d::init(), and GarnetNetwork_d::init().
int Router_d::get_num_vcs () [inline]
Definition at line 67 of file Router_d.hh.
References m_num_vcs.
Referenced by InputUnit_d::InputUnit_d(), OutputUnit_d::OutputUnit_d(), SWallocator_d::SWallocator_d(), Switch_d::Switch_d(), and VCallocator_d::VCallocator_d().
int Router_d::get_num_vnets () [inline]
Definition at line 68 of file Router_d.hh.
References m_virtual_networks.
std::vector<OutputUnit_d *>& Router_d::get_outputUnit_ref () [inline]
Definition at line 81 of file Router_d.hh.
References m_output_unit.
Referenced by VCallocator_d::init(), Switch_d::init(), and SWallocator_d::init().
int Router_d::get_vc_per_vnet () [inline]
Definition at line 69 of file Router_d.hh.
References m_vc_per_vnet.
Referenced by GarnetNetwork_d::init(), InputUnit_d::InputUnit_d(), SWallocator_d::SWallocator_d(), and VCallocator_d::VCallocator_d().
void Router_d::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BasicRouter.
Definition at line 73 of file Router_d.cc.
References Switch_d::init(), SWallocator_d::init(), VCallocator_d::init(), m_sw_alloc, m_switch, and m_vc_alloc.
void Router_d::init_net_ptr (GarnetNetwork_d * net_ptr) [inline]
Definition at line 74 of file Router_d.hh.
References m_network_ptr.
Referenced by GarnetNetwork_d::GarnetNetwork_d().
void Router_d::printAggregateFaultProbability (std::ostream & out)
Definition at line 232 of file Router_d.cc.
References BASELINE_TEMPERATURE_CELCIUS, get_aggregate_fault_probability(), and BasicRouter::m_id.
Referenced by GarnetNetwork_d::init().
void Router_d::printFaultVector (std::ostream & out)
Referenced by GarnetNetwork_d::init().
void Router_d::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 147 of file Router_d.cc.
References m_buffer_reads, m_buffer_writes, m_crossbar_activity, m_sw_global_arbiter_activity, m_sw_local_arbiter_activity, m_vc_global_arbiter_activity, m_vc_local_arbiter_activity, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::nozero.
void Router_d::resetStats () [virtual]
Reset statistics associated with this object.
Reimplemented from SimObject.
Definition at line 204 of file Router_d.cc.
References ArmISA::i, ArmISA::j, m_input_unit, and m_virtual_networks.
void Router_d::route_req (flit_d * t_flit, InputUnit_d * in_unit, int invc)
Definition at line 116 of file Router_d.cc.
References m_routing_unit, and RoutingUnit_d::RC_stage().
Referenced by InputUnit_d::wakeup().
void Router_d::swarb_req ()
Definition at line 128 of file Router_d.cc.
References ClockedObject::clockEdge(), m_sw_alloc, and Consumer::scheduleEventAbsolute().
Referenced by VCallocator_d::arbitrate_outvcs(), and InputUnit_d::wakeup().
void Router_d::update_incredit (int in_port, int in_vc, int credit)
Definition at line 134 of file Router_d.cc.
References m_input_unit.
Referenced by OutputUnit_d::decrement_credit(), OutputUnit_d::update_vc(), and OutputUnit_d::wakeup().
void Router_d::update_sw_winner (int inport, flit_d * t_flit)
Definition at line 140 of file Router_d.cc.
References ClockedObject::clockEdge(), m_switch, Consumer::scheduleEventAbsolute(), and Switch_d::update_sw_winner().
Referenced by SWallocator_d::arbitrate_outports().
void Router_d::vcarb_req ()
Definition at line 122 of file Router_d.cc.
References ClockedObject::clockEdge(), m_vc_alloc, and Consumer::scheduleEventAbsolute().
Referenced by RoutingUnit_d::RC_stage().
Member Data Documentation
Stats::Scalar Router_d::m_buffer_reads [private]
Definition at line 120 of file Router_d.hh.
Referenced by collateStats(), and regStats().
Stats::Scalar Router_d::m_buffer_writes [private]
Definition at line 121 of file Router_d.hh.
Referenced by collateStats(), and regStats().
Stats::Scalar Router_d::m_crossbar_activity [private]
Definition at line 129 of file Router_d.hh.
Referenced by collateStats(), and regStats().
std::vector<InputUnit_d *> Router_d::m_input_unit [private]
Definition at line 112 of file Router_d.hh.
Referenced by addInPort(), collateStats(), functionalWrite(), get_inputUnit_ref(), get_num_inports(), resetStats(), Router_d(), update_incredit(), and ~Router_d().
GarnetNetwork_d* Router_d::m_network_ptr [private]
Definition at line 110 of file Router_d.hh.
Referenced by get_aggregate_fault_probability(), get_fault_vector(), get_net_ptr(), and init_net_ptr().
int Router_d::m_num_vcs [private]
Definition at line 109 of file Router_d.hh.
Referenced by get_num_vcs(), and Router_d().
std::vector<OutputUnit_d *> Router_d::m_output_unit [private]
Definition at line 113 of file Router_d.hh.
Referenced by addOutPort(), functionalWrite(), get_num_outports(), get_outputUnit_ref(), Router_d(), and ~Router_d().
RoutingUnit_d* Router_d::m_routing_unit [private]
Definition at line 114 of file Router_d.hh.
Referenced by addOutPort(), route_req(), Router_d(), and ~Router_d().
SWallocator_d* Router_d::m_sw_alloc [private]
Definition at line 116 of file Router_d.hh.
Referenced by collateStats(), init(), Router_d(), swarb_req(), and ~Router_d().
Stats::Scalar Router_d::m_sw_global_arbiter_activity [private]
Definition at line 124 of file Router_d.hh.
Referenced by collateStats(), and regStats().
Stats::Scalar Router_d::m_sw_local_arbiter_activity [private]
Definition at line 123 of file Router_d.hh.
Referenced by collateStats(), and regStats().
Switch_d* Router_d::m_switch [private]
Definition at line 117 of file Router_d.hh.
Referenced by collateStats(), functionalWrite(), init(), Router_d(), update_sw_winner(), and ~Router_d().
VCallocator_d* Router_d::m_vc_alloc [private]
Definition at line 115 of file Router_d.hh.
Referenced by collateStats(), init(), Router_d(), vcarb_req(), and ~Router_d().
Stats::Scalar Router_d::m_vc_global_arbiter_activity [private]
Definition at line 127 of file Router_d.hh.
Referenced by collateStats(), and regStats().
Stats::Scalar Router_d::m_vc_local_arbiter_activity [private]
Definition at line 126 of file Router_d.hh.
Referenced by collateStats(), and regStats().
int Router_d::m_vc_per_vnet [private]
Definition at line 109 of file Router_d.hh.
Referenced by get_vc_per_vnet(), and Router_d().
int Router_d::m_virtual_networks [private]
Definition at line 109 of file Router_d.hh.
Referenced by collateStats(), get_num_vnets(), resetStats(), and Router_d().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/Router_d.hh
mem/ruby/network/garnet/fixed-pipeline/Router_d.cc