gem5: Serializable Class Reference
Serializable Class Reference
Basic support for object serialization.
#include <serialize.hh>
Public Member Functions
Serializable ()
virtual ~Serializable ()
virtual const std::string name () const =0
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
Static Public Member Functions
static Serializable * create (Checkpoint *cp, const std::string &section)
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (Checkpoint *cp)
Static Public Attributes
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions
void nameOut (std::ostream &os)
void nameOut (std::ostream &os, const std::string &_name)
Detailed Description
Basic support for object serialization.
Note:
Many objects that support serialization need to be put in a consistent state when serialization takes place. We refer to the action of forcing an object into a consistent state as 'draining'. Objects that need draining inherit from Drainable. See Drainable for more information.
Definition at line 181 of file serialize.hh.
Constructor & Destructor Documentation
Serializable::Serializable ()
Definition at line 467 of file serialize.cc.
Serializable::~Serializable () [virtual]
Definition at line 471 of file serialize.cc.
Member Function Documentation
static Serializable* Serializable::create (Checkpoint * cp, const std::string & section) [static]
Referenced by EventQueue::unserialize().
virtual const std::string Serializable::name () const [pure virtual]
Implemented in SimpleTrace, HDLcd::DmaDoneEvent, Kernel::Statistics, PhysicalMemory, Event, EventQueue, EventWrapper< T, F >, Globals, SimObject, EventWrapper< EnergyCtrl,&EnergyCtrl::updatePLAck >, EventWrapper< IGbE,&IGbE::tidvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::writeDone >, EventWrapper< TableWalker,&TableWalker::doL2LongDescriptorWrapper >, EventWrapper< TableWalker,&TableWalker::doL0LongDescriptorWrapper >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshotCycle >, EventWrapper< MemTest,&MemTest::tick >, EventWrapper< TxDescCache,&TxDescCache::nullCallback >, EventWrapper< NSGigE,&NSGigE::txEventTransmit >, EventWrapper< UFSHostDevice,&UFSHostDevice::taskStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::readGarbage >, EventWrapper< SimpleMemory,&SimpleMemory::release >, EventWrapper< PL031,&PL031::counterMatch >, EventWrapper< Timer,&Timer::watchdogAtZero >, EventWrapper< Rank,&Rank::processRefreshEvent >, EventWrapper< TableWalker,&TableWalker::doL3LongDescriptorWrapper >, EventWrapper< DescCache,&DescCache::wbComplete >, EventWrapper< MasterPort,&MasterPort::sendRetryResp >, EventWrapper< Pl011,&Pl011::generateInterrupt >, EventWrapper< DRAMSim2,&DRAMSim2::sendResponse >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::finalizeSnapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer >, EventWrapper< MemTest,&MemTest::noRequest >, EventWrapper< ArchTimer,&ArchTimer::counterLimitReached >, EventWrapper< TxDescCache,&TxDescCache::pktComplete >, EventWrapper< DescCache,&DescCache::writeback1 >, EventWrapper< Rank,&Rank::processPowerEvent >, EventWrapper< TableWalker,&TableWalker::doL1LongDescriptorWrapper >, EventWrapper< IdeDisk,&IdeDisk::dmaReadDone >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeCopyBytesComplete >, EventWrapper< DmaPort,&DmaPort::sendDma >, EventWrapper< Timer,&Timer::counterAtZero >, EventWrapper< TableWalker,&TableWalker::doL1DescriptorWrapper >, EventWrapper< CommMonitor,&CommMonitor::samplePeriodic >, EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone >, EventWrapper< UFSHostDevice,&UFSHostDevice::transferStart >, EventWrapper< UFSHostDevice,&UFSHostDevice::SCSIStart >, EventWrapper< Pl050,&Pl050::generateInterrupt >, EventWrapper< Device,&Device::txEventTransmit >, EventWrapper< HDLcd,&HDLcd::startFrame >, EventWrapper< Rank,&Rank::processPrechargeEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::writeStatusComplete >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::readCopyBytesComplete >, EventWrapper< IGbE,&IGbE::delayIntEvent >, EventWrapper< NSGigE,&NSGigE::rxDmaWriteDone >, EventWrapper< Pl111,&Pl111::fillFifo >, EventWrapper< DRAMSim2,&DRAMSim2::tick >, EventWrapper< SnapMemCtrl,&SnapMemCtrl::snapshot >, EventWrapper< IdeDisk,&IdeDisk::doDmaWrite >, EventWrapper< DRAMCtrl,&DRAMCtrl::processNextReqEvent >, EventWrapper< RxDescCache,&RxDescCache::pktSplitDone >, EventWrapper< IGbE,&IGbE::radvProcess >, EventWrapper< UFSHostDevice,&UFSHostDevice::finalUTP >, EventWrapper< HDLcd,&HDLcd::generateInterrupt >, EventWrapper< TableWalker,&TableWalker::doL2DescriptorWrapper >, EventWrapper< Link,&Link::txDone >, EventWrapper< IdeDisk,&IdeDisk::doDmaRead >, EventWrapper< DRAMCtrl,&DRAMCtrl::processRespondEvent >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchDescComplete >, EventWrapper< Walker,&Walker::startWalkWrapper >, EventWrapper< IGbE,&IGbE::tadvProcess >, EventWrapper< NSGigE,&NSGigE::rxKick >, EventWrapper< SimpleMemory,&SimpleMemory::dequeue >, EventWrapper< Layer,&Layer::releaseLayer >, EventWrapper< TrafficGen,&TrafficGen::update >, EventWrapper< NSGigE,&NSGigE::txKick >, EventWrapper< HDLcd,&HDLcd::renderPixel >, EventWrapper< HDLcd,&HDLcd::endFrame >, EventWrapper< TableWalker,&TableWalker::processWalkWrapper >, EventWrapper< DescCache,&DescCache::fetchDescriptors1 >, EventWrapper< IGbE,&IGbE::tick >, EventWrapper< NSGigE,&NSGigE::txDmaWriteDone >, EventWrapper< NSGigE,&NSGigE::rxDmaReadDone >, EventWrapper< HDLcd,&HDLcd::fillPixelBuffer >, EventWrapper< Rank,&Rank::processActivateEvent >, EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone >, EventWrapper< BridgeSlavePort,&BridgeSlavePort::trySendTiming >, EventWrapper< TimingSimpleCPU,&TimingSimpleCPU::fetch >, EventWrapper< CopyEngineChannel,&CopyEngineChannel::fetchAddrComplete >, EventWrapper< UFSHostDevice,&UFSHostDevice::readDone >, EventWrapper< Device,&Device::txDmaDone >, EventWrapper< CacheSlavePort,&CacheSlavePort::processSendRetry >, EventWrapper< MemTest,&MemTest::noResponse >, EventWrapper< BridgeMasterPort,&BridgeMasterPort::trySendTiming >, EventWrapper< IGbE,&IGbE::rdtrProcess >, EventWrapper< NSGigE,&NSGigE::txDmaReadDone >, EventWrapper< Pl111,&Pl111::generateInterrupt >, EventWrapper< Timer,&Timer::timerAtZero >, EventWrapper< RxDescCache,&RxDescCache::pktComplete >, EventWrapper< TxDescCache,&TxDescCache::headerComplete >, EventWrapper< Root,&Root::timeSync >, EventWrapper< Pl111,&Pl111::readFramebuffer >, EventWrapper< Device,&Device::rxDmaDone >, EventWrapper< FlashDevice,&FlashDevice::actionComplete >, EventWrapper< PacketQueue,&PacketQueue::processSendEvent >, and EventWrapper< DescCache,&DescCache::fetchComplete >.
void Serializable::nameOut (std::ostream & os, const std::string & _name) [protected]
void Serializable::nameOut (std::ostream & os) [protected]
Referenced by Globals::serialize(), Iob::serialize(), IGbE::serialize(), CopyEngine::serialize(), VGic::serialize(), Sp804::serialize(), CpuLocalTimer::serialize(), GenericTimerMem::serialize(), GenericTimer::serialize(), VirtIODeviceBase::serialize(), ArmISA::PMU::serialize(), SparcISA::TLB::serialize(), Process::serialize(), and SimObject::serializeAll().
virtual void Serializable::serialize (std::ostream & os) [virtual]
Reimplemented in AlphaISA::Interrupts, AlphaISA::ISA, AlphaISA::Kernel::Statistics, AlphaISA::TLB, ArmISA::Interrupts, ArmISA::ISA, KvmGic, ArmISA::PMU, ArmISA::TLB, MipsISA::Interrupts, MipsISA::TLB, PowerISA::TLB, SparcISA::Interrupts, SparcISA::ISA, SparcISA::TLB, X86ISA::Interrupts, X86ISA::ISA, X86ISA::TLB, TrafficGen, AlphaBackdoor, Tsunami, TsunamiCChip, TsunamiIO, TsunamiPChip, EnergyCtrl, FlashDevice, GenericTimer, GenericTimerMem, Pl390, HDLcd, Pl050, Pl011, Pl111, PL031, RealViewCtrl, CpuLocalTimer, Sp804, UFSHostDevice, VGic, CopyEngine, CowDiskImage, EtherLink, EtherTap, I2CBus, IGbE, IdeController, IdeDisk, Malta, MaltaCChip, MaltaIO, MaltaPChip, NSGigE, PciDevice, Sinic::Base, Sinic::Device, DumbTOD, Iob, MmDisk, Uart8250, VirtIODeviceBase, VirtIO9PProxy, X86ISA::Cmos, X86ISA::I8042, X86ISA::I82094AA, X86ISA::I8237, X86ISA::I8254, X86ISA::I8259, X86ISA::Speaker, Kernel::Statistics, Cache, PhysicalMemory, RubySystem, SrcClockDomain, DVFSHandler, Event, EventQueue, Process, Root, LocalSimLoopExitEvent, System, TickedObject, and VoltageDomain.
Referenced by SimObject::serializeAll().
static void Serializable::serializeAll (const std::string & cpt_dir) [static]
Referenced by debug_serialize(), and serializeAll().
virtual void Serializable::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented in AlphaISA::Interrupts, AlphaISA::ISA, AlphaISA::Kernel::Statistics, AlphaISA::TLB, ArmISA::Interrupts, ArmISA::ISA, KvmGic, ArmISA::PMU, ArmISA::TLB, MipsISA::Interrupts, MipsISA::TLB, PowerISA::TLB, SparcISA::Interrupts, SparcISA::ISA, SparcISA::TLB, X86ISA::Interrupts, X86ISA::ISA, X86ISA::TLB, TrafficGen, AlphaBackdoor, Tsunami, TsunamiCChip, TsunamiIO, TsunamiPChip, EnergyCtrl, FlashDevice, GenericTimer, GenericTimerMem, Pl390, HDLcd, Pl050, Pl011, Pl111, PL031, RealViewCtrl, CpuLocalTimer, Sp804, UFSHostDevice, VGic, CopyEngine, CowDiskImage, EtherLink, EtherTap, I2CBus, IGbE, IdeController, IdeDisk, Malta, MaltaCChip, MaltaIO, MaltaPChip, NSGigE, PciDevice, Sinic::Base, Sinic::Device, DumbTOD, Iob, Uart8250, VirtIODeviceBase, VirtIO9PProxy, X86ISA::Cmos, X86ISA::I8042, X86ISA::I82094AA, X86ISA::I8237, X86ISA::I8254, X86ISA::I8259, X86ISA::Speaker, Kernel::Statistics, Cache, PhysicalMemory, RubySystem, SrcClockDomain, DVFSHandler, Event, EventQueue, Process, Root, Globals, LocalSimLoopExitEvent, System, TickedObject, and VoltageDomain.
Referenced by SimObject::loadState().
void Serializable::unserializeGlobals (Checkpoint * cp) [static]
Definition at line 504 of file serialize.cc.
References Globals::name(), and Globals::unserialize().
Referenced by unserializeGlobals().
Member Data Documentation
int Serializable::ckptCount = 0 [static]
Definition at line 199 of file serialize.hh.
int Serializable::ckptMaxCount = 0 [static]
Definition at line 200 of file serialize.hh.
int Serializable::ckptPrevCount = -1 [static]
Definition at line 201 of file serialize.hh.
The documentation for this class was generated from the following files:
sim/serialize.hh
sim/serialize.cc