gem5: QueuedMasterPort Class Reference
QueuedMasterPort Class Reference
The QueuedMasterPort combines two queues, a request queue and a snoop response queue, that both share the same port.
#include <qport.hh>
Public Member Functions
QueuedMasterPort (const std::string &name, MemObject *owner, ReqPacketQueue &req_queue, SnoopRespPacketQueue &snoop_resp_queue, PortID id=InvalidPortID)
Create a QueuedPort with a given name, owner, and a supplied implementation of two packet queues.
virtual ~QueuedMasterPort ()
void schedTimingReq (PacketPtr pkt, Tick when)
Schedule the sending of a timing request.
void schedTimingSnoopResp (PacketPtr pkt, Tick when, bool force_order=false)
Schedule the sending of a timing snoop response.
bool checkFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
unsigned int drain (DrainManager *dm)
Protected Member Functions
void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
void recvRetrySnoopResp ()
Called by the slave port if sendTimingSnoopResp was called on this master port (causing recvTimingSnoopResp to be called on the slave port) and was unsuccesful.
Protected Attributes
ReqPacketQueue & reqQueue
Packet queue used to store outgoing requests.
SnoopRespPacketQueue & snoopRespQueue
Packet queue used to store outgoing snoop responses.
Detailed Description
The QueuedMasterPort combines two queues, a request queue and a snoop response queue, that both share the same port.
The flow control for requests and snoop responses are completely independent, and so each queue manages its own flow control (retries).
Definition at line 109 of file qport.hh.
Constructor & Destructor Documentation
QueuedMasterPort::QueuedMasterPort (const std::string & name, MemObject * owner, ReqPacketQueue & req_queue, SnoopRespPacketQueue & snoop_resp_queue, PortID id = InvalidPortID) [inline]
Create a QueuedPort with a given name, owner, and a supplied implementation of two packet queues.
The external definition of the queues enables e.g. the cache to implement a specific queue behaviuor in a subclass, and provide the latter to the QueuePort constructor.
Definition at line 133 of file qport.hh.
virtual QueuedMasterPort::~QueuedMasterPort () [inline, virtual]
Definition at line 141 of file qport.hh.
Member Function Documentation
bool QueuedMasterPort::checkFunctional (PacketPtr pkt) [inline]
Check the list of buffered packets against the supplied functional request.
Definition at line 164 of file qport.hh.
References PacketQueue::checkFunctional(), reqQueue, and snoopRespQueue.
Referenced by Cache::functionalAccess(), and AbstractController::functionalMemoryWrite().
unsigned int QueuedMasterPort::drain (DrainManager * dm) [inline]
Definition at line 170 of file qport.hh.
References PacketQueue::drain(), reqQueue, and snoopRespQueue.
Referenced by BaseCache::drain(), and RubyPort::getChildDrainCount().
void QueuedMasterPort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 120 of file qport.hh.
References reqQueue, and PacketQueue::retry().
void QueuedMasterPort::recvRetrySnoopResp () [inline, protected, virtual]
Called by the slave port if sendTimingSnoopResp was called on this master port (causing recvTimingSnoopResp to be called on the slave port) and was unsuccesful.
Reimplemented from MasterPort.
Definition at line 122 of file qport.hh.
References PacketQueue::retry(), and snoopRespQueue.
void QueuedMasterPort::schedTimingReq (PacketPtr pkt, Tick when) [inline]
Schedule the sending of a timing request.
Parameters:
pkt Packet to send
when Absolute time (in ticks) to send packet
Definition at line 149 of file qport.hh.
References reqQueue, and PacketQueue::schedSendTiming().
Referenced by SnapMemCtrl::catchSnapReadResponsePacket(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), AbstractController::queueMemoryWritePartial(), X86ISA::IntDevice::IntMasterPort::sendMessage(), and SnapMemCtrl::sendReadPacketToNormalMemory().
void QueuedMasterPort::schedTimingSnoopResp (PacketPtr pkt, Tick when, bool force_order = false) [inline]
Schedule the sending of a timing snoop response.
Parameters:
pkt Packet to send
when Absolute time (in ticks) to send packet
Definition at line 158 of file qport.hh.
References PacketQueue::schedSendTiming(), and snoopRespQueue.
Referenced by Cache::doTimingSupplyResponse(), and Cache::recvTimingSnoopResp().
Member Data Documentation
ReqPacketQueue& QueuedMasterPort::reqQueue [protected]
Packet queue used to store outgoing requests.
Reimplemented in MessageMasterPort, AbstractController::MemoryPort, RubyPort::MemMasterPort, and RubyPort::PioMasterPort.
Definition at line 115 of file qport.hh.
Referenced by checkFunctional(), drain(), recvReqRetry(), BaseCache::CacheMasterPort::requestBus(), and schedTimingReq().
SnoopRespPacketQueue& QueuedMasterPort::snoopRespQueue [protected]
Packet queue used to store outgoing snoop responses.
Reimplemented in MessageMasterPort, AbstractController::MemoryPort, RubyPort::MemMasterPort, and RubyPort::PioMasterPort.
Definition at line 118 of file qport.hh.
Referenced by checkFunctional(), drain(), recvRetrySnoopResp(), and schedTimingSnoopResp().
The documentation for this class was generated from the following file:
mem/qport.hh