gem5: IdeDisk Class Reference
IdeDisk Class Reference
IDE Disk device model.
#include <ide_disk.hh>
Public Types
typedef IdeDiskParams Params
Public Member Functions
IdeDisk (const Params *p)
~IdeDisk ()
Delete the data buffer.
void reset (int id)
Reset the device state.
void regStats ()
Register Statistics.
void setController (IdeController *c)
Set the controller for this device.
void readCommand (const Addr offset, int size, uint8_t *data)
void readControl (const Addr offset, int size, uint8_t *data)
void writeCommand (const Addr offset, int size, const uint8_t *data)
void writeControl (const Addr offset, int size, const uint8_t *data)
void startDma (const uint32_t &prdTableBase)
void abortDma ()
Protected Attributes
IdeController * ctrl
The IDE controller for this disk.
DiskImage * image
The image that contains the data of this disk.
int diskDelay
The disk delay in microseconds.
Private Member Functions
void startCommand ()
void intrPost ()
void intrClear ()
void doDmaTransfer ()
void doDmaDataRead ()
void doDmaRead ()
void doDmaDataWrite ()
void doDmaWrite ()
void dmaPrdReadDone ()
void dmaReadDone ()
void dmaWriteDone ()
void readDisk (uint32_t sector, uint8_t *data)
void writeDisk (uint32_t sector, uint8_t *data)
void updateState (DevAction_t action)
bool isBSYSet ()
bool isIENSet ()
bool isDEVSelect ()
void setComplete ()
uint32_t getLBABase ()
Addr pciToDma (Addr pciAddr)
void serialize (std::ostream &os)
Serialize this object to the given output stream.
void unserialize (Checkpoint *cp, const std::string &section)
Reconstruct the state of this object from a checkpoint.
Private Attributes
struct ataparams driveID
Drive identification structure for this disk.
uint8_t * dataBuffer
Data buffer for transfers.
uint32_t cmdBytes
Number of bytes in command data transfer.
uint32_t cmdBytesLeft
Number of bytes left in command data transfer.
uint32_t drqBytesLeft
Number of bytes left in DRQ block.
uint32_t curSector
Current sector in access.
CommandReg_t cmdReg
Command block registers.
uint8_t status
Status register.
bool nIENBit
Interrupt enable bit.
DevState_t devState
Device state.
DmaState_t dmaState
Dma state.
bool dmaRead
Dma transaction is a read.
uint32_t curPrdAddr
PRD table base address.
PrdTableEntry curPrd
PRD entry.
int devID
Device ID (master=0/slave=1).
bool intrPending
Interrupt pending.
bool dmaAborted
DMA Aborted.
Stats::Scalar dmaReadFullPages
Stats::Scalar dmaReadBytes
Stats::Scalar dmaReadTxs
Stats::Scalar dmaWriteFullPages
Stats::Scalar dmaWriteBytes
Stats::Scalar dmaWriteTxs
EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer > dmaTransferEvent
ChunkGenerator * dmaReadCG
EventWrapper< IdeDisk,&IdeDisk::doDmaRead > dmaReadWaitEvent
ChunkGenerator * dmaWriteCG
EventWrapper< IdeDisk,&IdeDisk::doDmaWrite > dmaWriteWaitEvent
EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone > dmaPrdReadEvent
EventWrapper< IdeDisk,&IdeDisk::dmaReadDone > dmaReadEvent
EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone > dmaWriteEvent
Friends
class EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer >
class EventWrapper< IdeDisk,&IdeDisk::doDmaRead >
class EventWrapper< IdeDisk,&IdeDisk::doDmaWrite >
class EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone >
class EventWrapper< IdeDisk,&IdeDisk::dmaReadDone >
class EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone >
Detailed Description
IDE Disk device model.
Definition at line 207 of file ide_disk.hh.
Member Typedef Documentation
typedef IdeDiskParams IdeDisk::Params
Reimplemented from SimObject.
Definition at line 263 of file ide_disk.hh.
Constructor & Destructor Documentation
IdeDisk::IdeDisk (const Params * p)
Definition at line 68 of file ide_disk.cc.
References ataparams::atap_ata_major, ataparams::atap_capabilities1, ataparams::atap_capacity, ataparams::atap_curmulti, ataparams::atap_curmulti_valid, ataparams::atap_cylinders, ataparams::atap_dmamode_supp, ataparams::atap_extensions, ataparams::atap_heads, ataparams::atap_hwreset_res, ataparams::atap_model, ataparams::atap_multi, ataparams::atap_piomode_supp, ataparams::atap_sectors, ataparams::atap_udmamode_supp, driveID, image, MAX_MULTSECT, reset(), DiskImage::size(), and WDC_VER_ATA7.
IdeDisk::~IdeDisk ()
Delete the data buffer.
Definition at line 135 of file ide_disk.cc.
References dataBuffer.
Member Function Documentation
void IdeDisk::abortDma ()
Definition at line 608 of file ide_disk.cc.
References ACT_CMD_ERROR, devState, Dma_Idle, dmaState, panic, Prepare_Data_Dma, Transfer_Data_Dma, and updateState().
void IdeDisk::dmaPrdReadDone () [private]
Definition at line 354 of file ide_disk.cc.
References ACT_CMD_ERROR, cmdBytesLeft, curPrd, curPrdAddr, curSector, dmaAborted, dmaRead, doDmaDataRead(), doDmaDataWrite(), DPRINTF, PrdTableEntry::getBaseAddr(), PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), pciToDma(), SectorSize, and updateState().
void IdeDisk::dmaReadDone () [private]
Definition at line 460 of file ide_disk.cc.
References ACT_DMA_DONE, cmdBytesLeft, curPrd, curSector, dataBuffer, Dma_Idle, dmaState, doDmaTransfer(), PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), SectorSize, updateState(), and writeDisk().
Referenced by doDmaRead().
void IdeDisk::dmaWriteDone () [private]
Definition at line 547 of file ide_disk.cc.
References ACT_DMA_DONE, cmdBytesLeft, curPrd, Dma_Idle, dmaState, doDmaTransfer(), DPRINTF, PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), and updateState().
Referenced by doDmaWrite().
void IdeDisk::doDmaDataRead () [private]
Todo:
we need to figure out what the delay actually will be
Definition at line 378 of file ide_disk.cc.
References curPrd, curTick(), diskDelay, dmaReadWaitEvent, DPRINTF, PrdTableEntry::getByteCount(), EventManager::schedule(), and SectorSize.
Referenced by dmaPrdReadDone().
void IdeDisk::doDmaDataWrite () [private]
Todo:
we need to figure out what the delay actually will be
Definition at line 483 of file ide_disk.cc.
References cmdBytesLeft, curPrd, curSector, curTick(), dataBuffer, diskDelay, dmaWriteWaitEvent, DPRINTF, PrdTableEntry::getByteCount(), MAX_DMA_SIZE, readDisk(), EventManager::schedule(), and SectorSize.
Referenced by dmaPrdReadDone().
void IdeDisk::doDmaRead () [private]
Definition at line 421 of file ide_disk.cc.
References ACT_CMD_ERROR, ChunkGenerator::addr(), ChunkGenerator::complete(), ctrl, curPrd, curTick(), dataBuffer, DMA_BACKOFF_PERIOD, dmaAborted, DmaDevice::dmaPending(), DmaDevice::dmaRead(), dmaReadBytes, dmaReadCG, dmaReadDone(), dmaReadFullPages, dmaReadTxs, dmaReadWaitEvent, ChunkGenerator::done(), DPRINTF, PrdTableEntry::getBaseAddr(), PrdTableEntry::getByteCount(), Drainable::getDrainState(), MAX_DMA_SIZE, ChunkGenerator::next(), AlphaISA::PageBytes, pciToDma(), Drainable::Running, EventManager::schedule(), ChunkGenerator::size(), and updateState().
void IdeDisk::doDmaTransfer () [private]
Definition at line 333 of file ide_disk.cc.
References ACT_CMD_ERROR, ctrl, curPrd, curPrdAddr, curTick(), devState, DMA_BACKOFF_PERIOD, Dma_Transfer, dmaAborted, DmaDevice::dmaPending(), dmaPrdReadEvent, DmaDevice::dmaRead(), dmaState, dmaTransferEvent, DPRINTF, PrdTableEntry::entry, Drainable::getDrainState(), panic, Drainable::Running, EventManager::schedule(), Transfer_Data_Dma, and updateState().
Referenced by dmaReadDone(), and dmaWriteDone().
void IdeDisk::doDmaWrite () [private]
Definition at line 506 of file ide_disk.cc.
References ACT_CMD_ERROR, ChunkGenerator::addr(), ChunkGenerator::complete(), ctrl, curPrd, curTick(), dataBuffer, DMA_BACKOFF_PERIOD, dmaAborted, DmaDevice::dmaPending(), DmaDevice::dmaWrite(), dmaWriteBytes, dmaWriteCG, dmaWriteDone(), dmaWriteFullPages, dmaWriteTxs, dmaWriteWaitEvent, ChunkGenerator::done(), DPRINTF, PrdTableEntry::getBaseAddr(), PrdTableEntry::getByteCount(), Drainable::getDrainState(), PrdTableEntry::getEOT(), MAX_DMA_SIZE, ChunkGenerator::next(), AlphaISA::PageBytes, pciToDma(), Drainable::Running, EventManager::schedule(), ChunkGenerator::size(), and updateState().
uint32_t IdeDisk::getLBABase () [inline, private]
Definition at line 360 of file ide_disk.hh.
References cmdReg, CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::head, and CommandReg::sec_num.
Referenced by startCommand().
void IdeDisk::intrClear () [private]
Definition at line 749 of file ide_disk.cc.
References ctrl, DPRINTF, PciDevice::intrClear(), intrPending, and panic.
Referenced by updateState().
void IdeDisk::intrPost () [private]
Definition at line 734 of file ide_disk.cc.
References ctrl, DPRINTF, intrPending, IdeController::intrPost(), and panic.
Referenced by updateState().
bool IdeDisk::isBSYSet () [inline, private]
Definition at line 346 of file ide_disk.hh.
References status, and STATUS_BSY_BIT.
bool IdeDisk::isDEVSelect () [private]
Definition at line 186 of file ide_disk.cc.
References ctrl, and IdeController::isDiskSelected().
Referenced by updateState().
bool IdeDisk::isIENSet () [inline, private]
Definition at line 347 of file ide_disk.hh.
References nIENBit.
Referenced by updateState().
Addr IdeDisk::pciToDma (Addr pciAddr) [inline, private]
Definition at line 192 of file ide_disk.cc.
References ctrl, panic, and PciDevice::pciToDma().
Referenced by dmaPrdReadDone(), doDmaRead(), doDmaWrite(), and startDma().
void IdeDisk::readCommand (const Addr offset, int size, uint8_t * data)
Definition at line 205 of file ide_disk.cc.
References ACT_DATA_READ_SHORT, ACT_STAT_READ, cmdReg, CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::data, DATA_OFFSET, DPRINTF, CommandReg::drive, DRIVE_OFFSET, CommandReg::error, ERROR_OFFSET, HCYL_OFFSET, LCYL_OFFSET, NSECTOR_OFFSET, panic, CommandReg::sec_count, CommandReg::sec_num, SECTOR_OFFSET, status, STATUS_OFFSET, and updateState().
void IdeDisk::readControl (const Addr offset, int size, uint8_t * data)
Definition at line 251 of file ide_disk.cc.
References ALTSTAT_OFFSET, DPRINTF, panic, and status.
void IdeDisk::readDisk (uint32_t sector, uint8_t * data) [private]
Definition at line 566 of file ide_disk.cc.
References image, SimObject::name(), panic, DiskImage::read(), and SectorSize.
Referenced by doDmaDataWrite(), and updateState().
void IdeDisk::regStats () [virtual]
Register Statistics.
Reimplemented from SimObject.
Definition at line 390 of file ide_disk.cc.
References dmaReadBytes, dmaReadFullPages, dmaReadTxs, dmaWriteBytes, dmaWriteFullPages, dmaWriteTxs, SimObject::name(), and Stats::DataWrap< Derived, InfoProxyType >::name().
void IdeDisk::reset (int id)
Reset the device state.
Definition at line 142 of file ide_disk.cc.
References cmdBytes, cmdBytesLeft, cmdReg, curPrd, curPrdAddr, curSector, dataBuffer, DEV0, DEV1, Device_Idle_NS, Device_Idle_S, devID, devState, Dma_Idle, dmaAborted, dmaRead, dmaState, drqBytesLeft, PrdTableEntry::entry, CommandReg::error, intrPending, MAX_DMA_SIZE, panic, status, and STATUS_DRDY_BIT.
Referenced by IdeDisk(), and updateState().
void IdeDisk::serialize (std::ostream & os) [private, virtual]
Serialize this object to the given output stream.
Parameters:
os The stream to serialize to.
Reimplemented from Serializable.
void IdeDisk::setComplete () [inline, private]
Definition at line 350 of file ide_disk.hh.
References status, STATUS_DRDY_BIT, and STATUS_SEEK_BIT.
Referenced by updateState().
void IdeDisk::setController (IdeController * c) [inline]
Set the controller for this device.
Parameters:
c The IDE controller
Definition at line 285 of file ide_disk.hh.
References ctrl, and panic.
void IdeDisk::startCommand () [private]
Todo:
make this a scheduled event to simulate disk delay
Definition at line 620 of file ide_disk.cc.
References ACT_CMD_COMPLETE, ACT_DATA_READY, ACT_DMA_READY, ACT_NONE, cmdBytes, cmdBytesLeft, cmdReg, CommandReg::command, Command_Execution, curSector, CommandReg::cyl_high, CommandReg::cyl_low, devState, dmaRead, DPRINTF, CommandReg::drive, DRIVE_LBA_BIT, getLBABase(), CommandReg::head, image, panic, Prepare_Data_Dma, Prepare_Data_In, Prepare_Data_Out, CommandReg::sec_count, CommandReg::sec_num, SectorSize, SET_FEATURES, DiskImage::size(), status, STATUS_BSY_BIT, STATUS_DF_BIT, STATUS_DRQ_BIT, updateState(), WDCC_FLUSHCACHE, WDCC_IDENTIFY, WDCC_IDLE, WDCC_IDP, WDCC_READ, WDCC_READDMA, WDCC_READMULTI, WDCC_RECAL, WDCC_SETMULTI, WDCC_STANDBY_IMMED, WDCC_WRITE, WDCC_WRITEDMA, WDCC_WRITEMULTI, WDSF_READ_NATIVE_MAX, WDSF_SEEK, and WDSF_VERIFY.
Referenced by updateState().
void IdeDisk::startDma (const uint32_t & prdTableBase)
Definition at line 590 of file ide_disk.cc.
References curPrdAddr, curTick(), devState, Dma_Start, Dma_Transfer, dmaState, dmaTransferEvent, panic, pciToDma(), EventManager::schedule(), Transfer_Data_Dma, and ULL.
void IdeDisk::unserialize (Checkpoint * cp, const std::string & section) [private, virtual]
Reconstruct the state of this object from a checkpoint.
Parameters:
cp The checkpoint to use.
section The section name describing this object.
Reimplemented from Serializable.
void IdeDisk::updateState (DevAction_t action) [private]
Todo:
change this to a scheduled event to simulate disk delay
Todo:
change this to a scheduled event to simulate disk delay
Definition at line 767 of file ide_disk.cc.
References ACT_CMD_COMPLETE, ACT_CMD_ERROR, ACT_CMD_WRITE, ACT_DATA_READ_BYTE, ACT_DATA_READ_SHORT, ACT_DATA_READY, ACT_DATA_WRITE_BYTE, ACT_DATA_WRITE_SHORT, ACT_DMA_DONE, ACT_DMA_READY, ACT_SELECT_WRITE, ACT_SRST_CLEAR, ACT_SRST_SET, ACT_STAT_READ, cmdBytes, cmdBytesLeft, cmdReg, CommandReg::command, Command_Execution, ctrl, curSector, CommandReg::data, Data_Ready_INTRQ_In, Data_Ready_INTRQ_Out, dataBuffer, Device_Dma_Abort, Device_Idle_NS, Device_Idle_S, Device_Idle_SI, Device_Srst, devID, devState, Dma_Idle, Dma_Start, dmaAborted, dmaState, DPRINTF, driveID, drqBytesLeft, intrClear(), intrPending, intrPost(), isDEVSelect(), isIENSet(), MAX_DMA_SIZE, panic, Prepare_Data_Dma, Prepare_Data_In, Prepare_Data_Out, readDisk(), reset(), SectorSize, setComplete(), IdeController::setDmaComplete(), startCommand(), status, STATUS_BSY_BIT, STATUS_DRQ_BIT, STATUS_SEEK_BIT, Transfer_Data_Dma, Transfer_Data_In, Transfer_Data_Out, WDCC_IDENTIFY, and writeDisk().
Referenced by abortDma(), dmaPrdReadDone(), dmaReadDone(), dmaWriteDone(), doDmaRead(), doDmaTransfer(), doDmaWrite(), readCommand(), startCommand(), writeCommand(), and writeControl().
void IdeDisk::writeCommand (const Addr offset, int size, const uint8_t * data)
Definition at line 261 of file ide_disk.cc.
References ACT_CMD_WRITE, ACT_DATA_WRITE_SHORT, ACT_SELECT_WRITE, cmdReg, CommandReg::command, COMMAND_OFFSET, CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::data, DATA_OFFSET, DPRINTF, CommandReg::drive, DRIVE_OFFSET, FEATURES_OFFSET, HCYL_OFFSET, LCYL_OFFSET, NSECTOR_OFFSET, panic, CommandReg::sec_count, CommandReg::sec_num, SECTOR_OFFSET, and updateState().
void IdeDisk::writeControl (const Addr offset, int size, const uint8_t * data)
Definition at line 309 of file ide_disk.cc.
References ACT_SRST_CLEAR, ACT_SRST_SET, CONTROL_IEN_BIT, CONTROL_OFFSET, CONTROL_RST_BIT, Device_Srst, devState, DPRINTF, nIENBit, panic, and updateState().
void IdeDisk::writeDisk (uint32_t sector, uint8_t * data) [private]
Definition at line 576 of file ide_disk.cc.
References image, SimObject::name(), panic, SectorSize, and DiskImage::write().
Referenced by dmaReadDone(), and updateState().
Friends And Related Function Documentation
friend class EventWrapper< IdeDisk,&IdeDisk::dmaPrdReadDone > [friend]
Definition at line 327 of file ide_disk.hh.
friend class EventWrapper< IdeDisk,&IdeDisk::dmaReadDone > [friend]
Definition at line 331 of file ide_disk.hh.
friend class EventWrapper< IdeDisk,&IdeDisk::dmaWriteDone > [friend]
Definition at line 335 of file ide_disk.hh.
friend class EventWrapper< IdeDisk,&IdeDisk::doDmaRead > [friend]
Definition at line 316 of file ide_disk.hh.
friend class EventWrapper< IdeDisk,&IdeDisk::doDmaTransfer > [friend]
Definition at line 309 of file ide_disk.hh.
friend class EventWrapper< IdeDisk,&IdeDisk::doDmaWrite > [friend]
Definition at line 323 of file ide_disk.hh.
Member Data Documentation
uint32_t IdeDisk::cmdBytes [private]
Number of bytes in command data transfer.
Definition at line 225 of file ide_disk.hh.
Referenced by reset(), startCommand(), and updateState().
uint32_t IdeDisk::cmdBytesLeft [private]
Number of bytes left in command data transfer.
Definition at line 227 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), dmaReadDone(), dmaWriteDone(), doDmaDataWrite(), reset(), startCommand(), and updateState().
CommandReg_t IdeDisk::cmdReg [private]
Command block registers.
Definition at line 233 of file ide_disk.hh.
Referenced by getLBABase(), readCommand(), reset(), startCommand(), updateState(), and writeCommand().
IdeController* IdeDisk::ctrl [protected]
The IDE controller for this disk.
Definition at line 211 of file ide_disk.hh.
Referenced by doDmaRead(), doDmaTransfer(), doDmaWrite(), intrClear(), intrPost(), isDEVSelect(), pciToDma(), setController(), and updateState().
PrdTableEntry IdeDisk::curPrd [private]
PRD entry.
Definition at line 247 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), dmaReadDone(), dmaWriteDone(), doDmaDataRead(), doDmaDataWrite(), doDmaRead(), doDmaTransfer(), doDmaWrite(), and reset().
uint32_t IdeDisk::curPrdAddr [private]
PRD table base address.
Definition at line 245 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), doDmaTransfer(), reset(), and startDma().
uint32_t IdeDisk::curSector [private]
Current sector in access.
Definition at line 231 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), dmaReadDone(), doDmaDataWrite(), reset(), startCommand(), and updateState().
uint8_t* IdeDisk::dataBuffer [private]
Data buffer for transfers.
Definition at line 223 of file ide_disk.hh.
Referenced by dmaReadDone(), doDmaDataWrite(), doDmaRead(), doDmaWrite(), reset(), updateState(), and ~IdeDisk().
int IdeDisk::devID [private]
Device ID (master=0/slave=1).
Definition at line 249 of file ide_disk.hh.
Referenced by reset(), and updateState().
DevState_t IdeDisk::devState [private]
Device state.
Definition at line 239 of file ide_disk.hh.
Referenced by abortDma(), doDmaTransfer(), reset(), startCommand(), startDma(), updateState(), and writeControl().
int IdeDisk::diskDelay [protected]
The disk delay in microseconds.
Definition at line 217 of file ide_disk.hh.
Referenced by doDmaDataRead(), and doDmaDataWrite().
bool IdeDisk::dmaAborted [private]
DMA Aborted.
Definition at line 253 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), doDmaRead(), doDmaTransfer(), doDmaWrite(), reset(), and updateState().
EventWrapper<IdeDisk, &IdeDisk::dmaPrdReadDone> IdeDisk::dmaPrdReadEvent [private]
Definition at line 328 of file ide_disk.hh.
Referenced by doDmaTransfer().
bool IdeDisk::dmaRead [private]
Dma transaction is a read.
Definition at line 243 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), reset(), and startCommand().
Stats::Scalar IdeDisk::dmaReadBytes [private]
Definition at line 256 of file ide_disk.hh.
Referenced by doDmaRead(), and regStats().
ChunkGenerator* IdeDisk::dmaReadCG [private]
Definition at line 315 of file ide_disk.hh.
Referenced by doDmaRead().
EventWrapper<IdeDisk, &IdeDisk::dmaReadDone> IdeDisk::dmaReadEvent [private]
Definition at line 332 of file ide_disk.hh.
Stats::Scalar IdeDisk::dmaReadFullPages [private]
Definition at line 255 of file ide_disk.hh.
Referenced by doDmaRead(), and regStats().
Stats::Scalar IdeDisk::dmaReadTxs [private]
Definition at line 257 of file ide_disk.hh.
Referenced by doDmaRead(), and regStats().
EventWrapper<IdeDisk, &IdeDisk::doDmaRead> IdeDisk::dmaReadWaitEvent [private]
Definition at line 317 of file ide_disk.hh.
Referenced by doDmaDataRead(), and doDmaRead().
DmaState_t IdeDisk::dmaState [private]
Dma state.
Definition at line 241 of file ide_disk.hh.
Referenced by abortDma(), dmaReadDone(), dmaWriteDone(), doDmaTransfer(), reset(), startDma(), and updateState().
EventWrapper<IdeDisk, &IdeDisk::doDmaTransfer> IdeDisk::dmaTransferEvent [private]
Definition at line 310 of file ide_disk.hh.
Referenced by doDmaTransfer(), and startDma().
Stats::Scalar IdeDisk::dmaWriteBytes [private]
Definition at line 259 of file ide_disk.hh.
Referenced by doDmaWrite(), and regStats().
ChunkGenerator* IdeDisk::dmaWriteCG [private]
Definition at line 322 of file ide_disk.hh.
Referenced by doDmaWrite().
EventWrapper<IdeDisk, &IdeDisk::dmaWriteDone> IdeDisk::dmaWriteEvent [private]
Definition at line 336 of file ide_disk.hh.
Stats::Scalar IdeDisk::dmaWriteFullPages [private]
Definition at line 258 of file ide_disk.hh.
Referenced by doDmaWrite(), and regStats().
Stats::Scalar IdeDisk::dmaWriteTxs [private]
Definition at line 260 of file ide_disk.hh.
Referenced by doDmaWrite(), and regStats().
EventWrapper<IdeDisk, &IdeDisk::doDmaWrite> IdeDisk::dmaWriteWaitEvent [private]
Definition at line 324 of file ide_disk.hh.
Referenced by doDmaDataWrite(), and doDmaWrite().
struct ataparams IdeDisk::driveID [read, private]
Drive identification structure for this disk.
Definition at line 221 of file ide_disk.hh.
Referenced by IdeDisk(), and updateState().
uint32_t IdeDisk::drqBytesLeft [private]
Number of bytes left in DRQ block.
Definition at line 229 of file ide_disk.hh.
Referenced by reset(), and updateState().
DiskImage* IdeDisk::image [protected]
The image that contains the data of this disk.
Definition at line 213 of file ide_disk.hh.
Referenced by IdeDisk(), readDisk(), startCommand(), and writeDisk().
bool IdeDisk::intrPending [private]
Interrupt pending.
Definition at line 251 of file ide_disk.hh.
Referenced by intrClear(), intrPost(), reset(), and updateState().
bool IdeDisk::nIENBit [private]
Interrupt enable bit.
Definition at line 237 of file ide_disk.hh.
Referenced by isIENSet(), and writeControl().
uint8_t IdeDisk::status [private]
Status register.
Definition at line 235 of file ide_disk.hh.
Referenced by isBSYSet(), readCommand(), readControl(), reset(), setComplete(), startCommand(), and updateState().
The documentation for this class was generated from the following files:
dev/ide_disk.hh
dev/ide_disk.cc