gem5: SystemCounter Class Reference
SystemCounter Class Reference
Global system counter.
#include <generic_timer.hh>
Public Member Functions
SystemCounter ()
uint64_t value () const
Returns the current value of the physical counter.
uint64_t freq () const
Returns the counter frequency.
void setFreq (uint32_t freq)
Sets the counter frequency.
Tick period () const
Returns the counter period.
void setKernelControl (uint32_t val)
uint32_t getKernelControl ()
void serialize (std::ostream &os) const
void unserialize (Checkpoint *cp, const std::string &section)
Protected Attributes
uint64_t _freq
Counter frequency (as specified by CNTFRQ).
Tick _period
Cached copy of the counter period (inverse of the frequency).
Tick _resetTick
Tick when the counter was reset.
uint32_t _regCntkctl
Private Member Functions
SystemCounter (const SystemCounter &c)
Detailed Description
Global system counter.
It is shared by the architected timers.
Todo:
: implement memory-mapped controls
Definition at line 61 of file generic_timer.hh.
Constructor & Destructor Documentation
SystemCounter::SystemCounter ()
Definition at line 50 of file generic_timer.cc.
References setFreq().
SystemCounter::SystemCounter (const SystemCounter & c) [private]
Member Function Documentation
uint64_t SystemCounter::freq () const [inline]
Returns the counter frequency.
Definition at line 85 of file generic_timer.hh.
References _freq.
Referenced by GenericTimerMem::ctrlRead(), GenericTimer::readMiscReg(), and GenericTimerMem::timerRead().
uint32_t SystemCounter::getKernelControl () [inline]
Definition at line 94 of file generic_timer.hh.
References _regCntkctl.
Referenced by GenericTimer::readMiscReg().
Tick SystemCounter::period () const [inline]
Returns the counter period.
Definition at line 91 of file generic_timer.hh.
References _period.
Referenced by ArchTimer::updateCounter().
void SystemCounter::serialize (std::ostream & os) const
Definition at line 69 of file generic_timer.cc.
References _freq, _period, _regCntkctl, _resetTick, and SERIALIZE_SCALAR.
Referenced by GenericTimerMem::serialize(), and GenericTimer::serialize().
void SystemCounter::setFreq (uint32_t freq)
Sets the counter frequency.
Parameters:
freq frequency in Hz.
Definition at line 57 of file generic_timer.cc.
References _freq, _period, _resetTick, curTick(), SimClock::Frequency, and warn_once.
Referenced by SystemCounter().
void SystemCounter::setKernelControl (uint32_t val) [inline]
Definition at line 93 of file generic_timer.hh.
References _regCntkctl.
void SystemCounter::unserialize (Checkpoint * cp, const std::string & section)
Definition at line 78 of file generic_timer.cc.
References _freq, _period, _regCntkctl, _resetTick, UNSERIALIZE_OPT_SCALAR, and UNSERIALIZE_SCALAR.
Referenced by GenericTimerMem::unserialize(), and GenericTimer::unserialize().
uint64_t SystemCounter::value () const [inline]
Returns the current value of the physical counter.
Definition at line 77 of file generic_timer.hh.
References _freq, _period, _resetTick, and curTick().
Referenced by ArchTimer::value().
Member Data Documentation
uint64_t SystemCounter::_freq [protected]
Counter frequency (as specified by CNTFRQ).
Definition at line 65 of file generic_timer.hh.
Referenced by freq(), serialize(), setFreq(), unserialize(), and value().
Tick SystemCounter::_period [protected]
Cached copy of the counter period (inverse of the frequency).
Definition at line 67 of file generic_timer.hh.
Referenced by period(), serialize(), setFreq(), unserialize(), and value().
uint32_t SystemCounter::_regCntkctl [protected]
Definition at line 71 of file generic_timer.hh.
Referenced by getKernelControl(), serialize(), setKernelControl(), and unserialize().
Tick SystemCounter::_resetTick [protected]
Tick when the counter was reset.
Definition at line 69 of file generic_timer.hh.
Referenced by serialize(), setFreq(), unserialize(), and value().
The documentation for this class was generated from the following files:
dev/arm/generic_timer.hh
dev/arm/generic_timer.cc