gem5: MemCheckerMonitor::MonitorMasterPort Class Reference
MemCheckerMonitor::MonitorMasterPort Class Reference
This is the master port of the communication monitor.
Public Member Functions
MonitorMasterPort (const std::string &_name, MemCheckerMonitor &_mon)
Protected Member Functions
void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from the slave port.
bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the slave port.
void recvRangeChange ()
Called to receive an address range change from the peer slave port.
bool isSnooping () const
Determine if this master port is snooping or not.
void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Private Attributes
MemCheckerMonitor & mon
Detailed Description
This is the master port of the communication monitor.
All recv functions call a function in MemCheckerMonitor, where the send function of the slave port is called. Besides this, these functions can also perform actions for capturing statistics.
Definition at line 98 of file mem_checker_monitor.hh.
Constructor & Destructor Documentation
MemCheckerMonitor::MonitorMasterPort::MonitorMasterPort (const std::string & _name, MemCheckerMonitor & _mon) [inline]
Definition at line 103 of file mem_checker_monitor.hh.
Member Function Documentation
bool MemCheckerMonitor::MonitorMasterPort::isSnooping () const [inline, protected, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented from MasterPort.
Definition at line 134 of file mem_checker_monitor.hh.
References MemCheckerMonitor::isSnooping(), and mon.
Tick MemCheckerMonitor::MonitorMasterPort::recvAtomicSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 114 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvAtomicSnoop().
void MemCheckerMonitor::MonitorMasterPort::recvFunctionalSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 109 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvFunctionalSnoop().
void MemCheckerMonitor::MonitorMasterPort::recvRangeChange () [inline, protected, virtual]
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 129 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvRangeChange().
void MemCheckerMonitor::MonitorMasterPort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 139 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvReqRetry().
bool MemCheckerMonitor::MonitorMasterPort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 119 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvTimingResp().
void MemCheckerMonitor::MonitorMasterPort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop request from the slave port.
Reimplemented from MasterPort.
Definition at line 124 of file mem_checker_monitor.hh.
References mon, and MemCheckerMonitor::recvTimingSnoopReq().
Member Data Documentation
MemCheckerMonitor& MemCheckerMonitor::MonitorMasterPort::mon [private]
Definition at line 146 of file mem_checker_monitor.hh.
Referenced by isSnooping(), recvAtomicSnoop(), recvFunctionalSnoop(), recvRangeChange(), recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
The documentation for this class was generated from the following file:
mem/mem_checker_monitor.hh