gem5: ArmISA::Reset Class Reference
ArmISA::Reset Class Reference
#include <faults.hh>
Public Member Functions
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Detailed Description
Definition at line 250 of file faults.hh.
Member Function Documentation
void ArmISA::Reset::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 681 of file faults.cc.
References ThreadContext::clearArchRegs(), ArmISA::cpsr, FullSystem, ThreadContext::getCpuPtr(), ArmISA::getMPIDR(), ThreadContext::getSystemPtr(), ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), ArmSystem::highestELIs64(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_VMPIDR, ArmISA::MODE_HYP, MipsISA::pc, ThreadContext::pcState(), ThreadContext::readMiscReg(), ArmSystem::resetAddr64(), and ThreadContext::setMiscReg().
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc