gem5: Pl050 Class Reference
Pl050 Class Reference
#include <kmi.hh>
Public Types
typedef Pl050Params Params
Public Member Functions
const Params * params () const
Pl050 (const Params *p)
virtual Tick read (PacketPtr pkt)
Pure virtual function that the device must implement.
virtual Tick write (PacketPtr pkt)
Pure virtual function that the device must implement.
virtual void mouseAt (uint16_t x, uint16_t y, uint8_t buttons)
called whenever the mouse moves or it's button state changes buttons is a simple mask with each button (0-8) corresponding to a bit position in the byte with 1 being down and 0 being up
virtual void keyPress (uint32_t key, bool down)
Called when the vnc server receives a key press event from the client.
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
Protected Member Functions
BitUnion8 (ControlReg) Bitfield< 0 > force_clock_low
EndBitUnion (ControlReg) ControlReg control
control register
BitUnion8 (StatusReg) Bitfield< 0 > data_in
KMI status register.
EndBitUnion (StatusReg) StatusReg status
BitUnion8 (InterruptReg) Bitfield< 0 > rx
EndBitUnion (InterruptReg) InterruptReg interrupts
interrupt status register.
void updateIntStatus ()
Update the status of the interrupt registers and schedule an interrupt if required.
void generateInterrupt ()
Function to generate interrupt.
void processCommand (uint8_t byte)
Handle a command sent to the kmi and respond appropriately.
Protected Attributes
Bitfield< 1 > force_data_low
Bitfield< 2 > enable
Bitfield< 3 > txint_enable
Bitfield< 4 > rxint_enable
Bitfield< 5 > type
Bitfield< 1 > clk_in
Bitfield< 2 > rxparity
Bitfield< 3 > rxbusy
Bitfield< 4 > rxfull
Bitfield< 5 > txbusy
Bitfield< 6 > txempty
uint8_t clkdiv
clock divisor register This register is just kept around to satisfy reads after driver does writes.
Bitfield< 1 > tx
InterruptReg rawInterrupts
raw interrupt register (unmasked)
int ackNext
If the controller should ignore the next data byte and acknowledge it.
bool shiftDown
is the shift key currently down
VncInput * vnc
The vnc server we're connected to (if any).
bool driverInitialized
If the linux driver has initialized the device yet and thus can we send mouse data.
EventWrapper< Pl050,&Pl050::generateInterrupt > intEvent
Wrapper to create an event out of the thing.
std::list< uint8_t > rxQueue
Receive queue.
Static Protected Attributes
static const int kmiCr = 0x000
static const int kmiStat = 0x004
static const int kmiData = 0x008
static const int kmiClkDiv = 0x00C
static const int kmiISR = 0x010
Detailed Description
Definition at line 57 of file kmi.hh.
Member Typedef Documentation
typedef Pl050Params Pl050::Params
Reimplemented from AmbaIntDevice.
Definition at line 145 of file kmi.hh.
Constructor & Destructor Documentation
Pl050::Pl050 (const Params * p)
Definition at line 53 of file kmi.cc.
References VncInput::setKeyboard(), VncInput::setMouse(), and vnc.
Member Function Documentation
Pl050::BitUnion8 (InterruptReg) [protected]
Pl050::BitUnion8 (StatusReg) [protected]
KMI status register.
Pl050::BitUnion8 (ControlReg) [protected]
Pl050::EndBitUnion (InterruptReg) [protected]
interrupt status register.
Pl050::EndBitUnion (StatusReg) [protected]
Pl050::EndBitUnion (ControlReg) [protected]
control register
void Pl050::generateInterrupt () [protected]
Function to generate interrupt.
Definition at line 256 of file kmi.cc.
References DPRINTF, AmbaIntDevice::gic, AmbaIntDevice::intNum, and BaseGic::sendInt().
void Pl050::keyPress (uint32_t key, bool down) [virtual]
Called when the vnc server receives a key press event from the client.
Parameters:
key the key passed is an x11 keysym
down is the key now down or up?
Implements VncKeyboard.
Definition at line 296 of file kmi.cc.
References Ps2::keys, Ps2::keySymToPs2(), rxQueue, shiftDown, and updateIntStatus().
void Pl050::mouseAt (uint16_t x, uint16_t y, uint8_t buttons) [virtual]
called whenever the mouse moves or it's button state changes buttons is a simple mask with each button (0-8) corresponding to a bit position in the byte with 1 being down and 0 being up
Parameters:
x the x position of the mouse
y the y position of the mouse
buttos the button state as described above
Implements VncMouse.
Definition at line 266 of file kmi.cc.
References driverInitialized, rxQueue, updateIntStatus(), VncInput::videoHeight(), VncInput::videoWidth(), and vnc.
const Params* Pl050::params () const [inline]
Reimplemented from BasicPioDevice.
Definition at line 147 of file kmi.hh.
References SimObject::_params.
Referenced by processCommand().
void Pl050::processCommand (uint8_t byte) [protected]
Handle a command sent to the kmi and respond appropriately.
Definition at line 170 of file kmi.cc.
References Ps2::Ack, ackNext, Ps2::Disable, driverInitialized, Ps2::Enable, Ps2::KeyboardId, Ps2::MouseId, panic, params(), Ps2::Ps2Reset, Ps2::ReadId, rxQueue, Ps2::SelfTestPass, Ps2::SetDefaults, Ps2::SetRate, Ps2::SetResolution, Ps2::SetScaling1_1, Ps2::SetScaling1_2, Ps2::SetStatusLed, Ps2::StatusRequest, Ps2::TouchKitId, Ps2::TpReadId, and updateIntStatus().
Referenced by write().
Tick Pl050::read (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 67 of file kmi.cc.
References AmbaPioDevice::ambaId, clkdiv, DPRINTF, Packet::get(), Packet::getAddr(), Packet::getSize(), kmiClkDiv, kmiCr, kmiData, kmiISR, kmiStat, Packet::makeAtomicResponse(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, AmbaDevice::readId(), rxQueue, Packet::set(), ArmISA::status, updateIntStatus(), and warn.
void Pl050::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 311 of file kmi.cc.
References ackNext, arrayParamOut(), clkdiv, driverInitialized, rawInterrupts, rxQueue, SERIALIZE_SCALAR, shiftDown, and ArmISA::status.
void Pl050::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 334 of file kmi.cc.
References ackNext, arrayParamIn(), clkdiv, driverInitialized, rawInterrupts, rxQueue, shiftDown, ArmISA::status, and UNSERIALIZE_SCALAR.
void Pl050::updateIntStatus () [protected]
Update the status of the interrupt registers and schedule an interrupt if required.
Definition at line 238 of file kmi.cc.
References curTick(), DPRINTF, AmbaIntDevice::intDelay, intEvent, rawInterrupts, rxQueue, EventManager::schedule(), and Event::scheduled().
Referenced by keyPress(), mouseAt(), processCommand(), read(), and write().
Tick Pl050::write (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 137 of file kmi.cc.
References clkdiv, DPRINTF, Packet::get(), Packet::getAddr(), Packet::getSize(), kmiClkDiv, kmiCr, kmiData, Packet::makeAtomicResponse(), BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, processCommand(), updateIntStatus(), and warn.
Member Data Documentation
int Pl050::ackNext [protected]
If the controller should ignore the next data byte and acknowledge it.
The driver is attempting to setup some feature we don't care about
Definition at line 113 of file kmi.hh.
Referenced by processCommand(), serialize(), and unserialize().
Bitfield<1> Pl050::clk_in [protected]
Definition at line 82 of file kmi.hh.
uint8_t Pl050::clkdiv [protected]
clock divisor register This register is just kept around to satisfy reads after driver does writes.
The divsor does nothing, as we're not actually signaling ps2 serial commands to anything.
Definition at line 97 of file kmi.hh.
Referenced by read(), serialize(), unserialize(), and write().
bool Pl050::driverInitialized [protected]
If the linux driver has initialized the device yet and thus can we send mouse data.
Definition at line 123 of file kmi.hh.
Referenced by mouseAt(), processCommand(), serialize(), and unserialize().
Bitfield<2> Pl050::enable [protected]
Definition at line 69 of file kmi.hh.
Bitfield<1> Pl050::force_data_low [protected]
Definition at line 68 of file kmi.hh.
EventWrapper<Pl050, &Pl050::generateInterrupt> Pl050::intEvent [protected]
Wrapper to create an event out of the thing.
Definition at line 133 of file kmi.hh.
Referenced by updateIntStatus().
const int Pl050::kmiClkDiv = 0x00C [static, protected]
Definition at line 63 of file kmi.hh.
Referenced by read(), and write().
const int Pl050::kmiCr = 0x000 [static, protected]
Definition at line 60 of file kmi.hh.
Referenced by read(), and write().
const int Pl050::kmiData = 0x008 [static, protected]
Definition at line 62 of file kmi.hh.
Referenced by read(), and write().
const int Pl050::kmiISR = 0x010 [static, protected]
Definition at line 64 of file kmi.hh.
Referenced by read().
const int Pl050::kmiStat = 0x004 [static, protected]
Definition at line 61 of file kmi.hh.
Referenced by read().
InterruptReg Pl050::rawInterrupts [protected]
raw interrupt register (unmasked)
Definition at line 108 of file kmi.hh.
Referenced by serialize(), unserialize(), and updateIntStatus().
Bitfield<3> Pl050::rxbusy [protected]
Definition at line 84 of file kmi.hh.
Bitfield<4> Pl050::rxfull [protected]
Definition at line 85 of file kmi.hh.
Bitfield<4> Pl050::rxint_enable [protected]
Definition at line 71 of file kmi.hh.
Bitfield<2> Pl050::rxparity [protected]
Definition at line 83 of file kmi.hh.
std::list<uint8_t> Pl050::rxQueue [protected]
Receive queue.
This list contains all the pending commands that need to be sent to the driver
Definition at line 138 of file kmi.hh.
Referenced by keyPress(), mouseAt(), processCommand(), read(), serialize(), unserialize(), and updateIntStatus().
bool Pl050::shiftDown [protected]
is the shift key currently down
Definition at line 116 of file kmi.hh.
Referenced by keyPress(), serialize(), and unserialize().
Bitfield<1> Pl050::tx [protected]
Definition at line 101 of file kmi.hh.
Bitfield<5> Pl050::txbusy [protected]
Definition at line 86 of file kmi.hh.
Bitfield<6> Pl050::txempty [protected]
Definition at line 87 of file kmi.hh.
Bitfield<3> Pl050::txint_enable [protected]
Definition at line 70 of file kmi.hh.
Bitfield<5> Pl050::type [protected]
Definition at line 72 of file kmi.hh.
VncInput* Pl050::vnc [protected]
The vnc server we're connected to (if any).
Definition at line 119 of file kmi.hh.
Referenced by mouseAt(), and Pl050().
The documentation for this class was generated from the following files:
dev/arm/kmi.hh
dev/arm/kmi.cc