gem5: RubyPort Class Reference
RubyPort Class Reference
#include <RubyPort.hh>
Classes
class MemMasterPort
class MemSlavePort
class PioMasterPort
class PioSlavePort
struct SenderState
Public Types
typedef RubyPortParams Params
Public Member Functions
RubyPort (const Params *p)
virtual ~RubyPort ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
virtual RequestStatus makeRequest (PacketPtr pkt)=0
virtual int outstandingCount () const =0
virtual bool isDeadlockEventScheduled () const =0
virtual void descheduleDeadlockEvent ()=0
void setController (AbstractController *_cntrl)
uint32_t getId ()
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Protected Member Functions
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
void ruby_eviction_callback (const Address &address)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
Protected Attributes
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
System * system
Private Types
typedef std::vector
< MemSlavePort * >::iterator CpuPortIter
Vector of M5 Ports attached to this Ruby port.
Private Member Functions
void addToRetryList (MemSlavePort *port)
unsigned int getChildDrainCount (DrainManager *dm)
Private Attributes
PioMasterPort pioMasterPort
PioSlavePort pioSlavePort
MemMasterPort memMasterPort
MemSlavePort memSlavePort
unsigned int gotAddrRanges
std::vector< MemSlavePort * > slave_ports
std::vector< PioMasterPort * > master_ports
DrainManager * drainManager
std::vector< MemSlavePort * > retryList
Detailed Description
Definition at line 57 of file RubyPort.hh.
Member Typedef Documentation
typedef std::vector<MemSlavePort *>::iterator RubyPort::CpuPortIter [private]
Vector of M5 Ports attached to this Ruby port.
Definition at line 205 of file RubyPort.hh.
typedef RubyPortParams RubyPort::Params
Reimplemented from MemObject.
Reimplemented in Sequencer.
Definition at line 143 of file RubyPort.hh.
Constructor & Destructor Documentation
RubyPort::RubyPort (const Params * p)
Definition at line 53 of file RubyPort.cc.
References csprintf(), ArmISA::i, m_version, master_ports, SimObject::name(), and slave_ports.
virtual RubyPort::~RubyPort () [inline, virtual]
Definition at line 145 of file RubyPort.hh.
Member Function Documentation
void RubyPort::addToRetryList (MemSlavePort * port) [inline, private]
Definition at line 189 of file RubyPort.hh.
References retryList.
virtual void RubyPort::descheduleDeadlockEvent () [pure virtual]
Implemented in RubyPortProxy, and Sequencer.
Referenced by drain().
unsigned int RubyPort::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 428 of file RubyPort.cc.
References descheduleDeadlockEvent(), DPRINTF, Drainable::Drained, Drainable::Draining, drainManager, getChildDrainCount(), isDeadlockEventScheduled(), outstandingCount(), and Drainable::setDrainState().
unsigned int RubyPort::getChildDrainCount (DrainManager * dm) [private]
Definition at line 403 of file RubyPort.cc.
References X86ISA::count, DPRINTF, QueuedMasterPort::drain(), BaseMasterPort::isConnected(), master_ports, memMasterPort, MipsISA::p, and slave_ports.
Referenced by drain().
uint32_t RubyPort::getId () [inline]
Definition at line 164 of file RubyPort.hh.
References m_version.
BaseMasterPort & RubyPort::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 89 of file RubyPort.cc.
References master_ports, memMasterPort, panic, and pioMasterPort.
BaseSlavePort & RubyPort::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 114 of file RubyPort.cc.
References memSlavePort, panic, pioSlavePort, and slave_ports.
void RubyPort::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in RubyPortProxy.
Definition at line 81 of file RubyPort.cc.
References AbstractController::getMandatoryQueue(), m_controller, m_mandatory_q_ptr, and MessageBuffer::setSender().
virtual bool RubyPort::isDeadlockEventScheduled () const [pure virtual]
Implemented in RubyPortProxy, and Sequencer.
Referenced by drain().
virtual RequestStatus RubyPort::makeRequest (PacketPtr pkt) [pure virtual]
Implemented in RubyPortProxy, and Sequencer.
virtual int RubyPort::outstandingCount () const [pure virtual]
Implemented in RubyPortProxy, and Sequencer.
Referenced by drain(), and testDrainComplete().
bool RubyPort::recvTimingResp (PacketPtr pkt, PortID master_port_id) [protected]
Called by the PIO port when receiving a timing response.
Parameters:
pkt Response packet
master_port_id Port id of the PIO port
Returns:
Whether successfully sent
void RubyPort::ruby_eviction_callback (const Address & address) [protected]
Definition at line 542 of file RubyPort.cc.
References DPRINTF, Request::funcMasterId, Address::getAddress(), MemCmd::InvalidationReq, MipsISA::p, and slave_ports.
Referenced by Sequencer::evictionCallback().
void RubyPort::ruby_hit_callback (PacketPtr pkt) [protected]
Definition at line 340 of file RubyPort.cc.
References Packet::cmdString(), DPRINTF, Packet::getAddr(), ArmISA::i, System::isMemAddr(), Packet::isRequest(), Packet::popSenderState(), retryList, safe_cast(), system, and testDrainComplete().
Referenced by Sequencer::hitCallback().
void RubyPort::setController (AbstractController * _cntrl) [inline]
Definition at line 163 of file RubyPort.hh.
References m_controller.
void RubyPort::testDrainComplete () [protected]
Definition at line 387 of file RubyPort.cc.
References DPRINTF, drainManager, outstandingCount(), and DrainManager::signalDrainDone().
Referenced by ruby_hit_callback().
Member Data Documentation
DrainManager* RubyPort::drainManager [private]
Definition at line 209 of file RubyPort.hh.
Referenced by drain(), and testDrainComplete().
unsigned int RubyPort::gotAddrRanges [private]
Definition at line 202 of file RubyPort.hh.
Referenced by RubyPort::PioMasterPort::recvRangeChange().
AbstractController* RubyPort::m_controller [protected]
Definition at line 183 of file RubyPort.hh.
Referenced by init(), setController(), and Sequencer::writeCallback().
MessageBuffer* RubyPort::m_mandatory_q_ptr [protected]
Definition at line 184 of file RubyPort.hh.
Referenced by init(), Sequencer::issueRequest(), and Sequencer::writeCallback().
bool RubyPort::m_usingRubyTester [protected]
Definition at line 185 of file RubyPort.hh.
Referenced by Sequencer::hitCallback().
uint32_t RubyPort::m_version [protected]
Definition at line 182 of file RubyPort.hh.
Referenced by getId(), Sequencer::handleLlsc(), Sequencer::hitCallback(), Sequencer::issueRequest(), RubyPort(), and Sequencer::wakeup().
std::vector<PioMasterPort *> RubyPort::master_ports [private]
Definition at line 207 of file RubyPort.hh.
Referenced by RubyPort::PioSlavePort::getAddrRanges(), getChildDrainCount(), getMasterPort(), RubyPort::PioSlavePort::recvTimingReq(), and RubyPort().
MemMasterPort RubyPort::memMasterPort [private]
Definition at line 200 of file RubyPort.hh.
Referenced by getChildDrainCount(), and getMasterPort().
MemSlavePort RubyPort::memSlavePort [private]
Definition at line 201 of file RubyPort.hh.
Referenced by getSlavePort().
PioMasterPort RubyPort::pioMasterPort [private]
Definition at line 198 of file RubyPort.hh.
Referenced by getMasterPort().
PioSlavePort RubyPort::pioSlavePort [private]
Definition at line 199 of file RubyPort.hh.
Referenced by getSlavePort(), RubyPort::PioMasterPort::recvRangeChange(), and RubyPort::PioMasterPort::recvTimingResp().
std::vector<MemSlavePort *> RubyPort::retryList [private]
Definition at line 215 of file RubyPort.hh.
Referenced by addToRetryList(), and ruby_hit_callback().
std::vector<MemSlavePort *> RubyPort::slave_ports [private]
Definition at line 206 of file RubyPort.hh.
Referenced by getChildDrainCount(), getSlavePort(), ruby_eviction_callback(), and RubyPort().
System* RubyPort::system [protected]
Definition at line 186 of file RubyPort.hh.
Referenced by RubyPort::MemSlavePort::isPhysMemAddress(), Sequencer::makeRequest(), and ruby_hit_callback().
The documentation for this class was generated from the following files:
mem/ruby/system/RubyPort.hh
mem/ruby/system/RubyPort.cc