gem5: Named Class Reference
Named Class Reference
#include <trace.hh>
Public Member Functions
Named (const std::string &name_)
const std::string & name () const
Protected Attributes
const std::string _name
Detailed Description
Definition at line 139 of file trace.hh.
Constructor & Destructor Documentation
Named::Named (const std::string & name_) [inline]
Definition at line 145 of file trace.hh.
Member Function Documentation
const std::string& Named::name () const [inline]
Definition at line 148 of file trace.hh.
References _name.
Referenced by Minor::Fetch1::handleTLBResponse(), Minor::LSQ::StoreBuffer::insert(), Minor::LSQ::LSQ(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::push(), Minor::Fetch1::recvTimingResp(), and Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::reserve().
Member Data Documentation
const std::string Named::_name [protected]
Definition at line 142 of file trace.hh.
Referenced by name().
The documentation for this class was generated from the following file:
base/trace.hh