gem5: ArmISA::TableWalker::L1Descriptor Class Reference
ArmISA::TableWalker::L1Descriptor Class Reference
#include <table_walker.hh>
Public Types
enum EntryType { Ignore, PageTable, Section, Reserved }
Type of page table entry ARM DDI 0406B: B3-8.
Public Member Functions
L1Descriptor ()
Default ctor.
virtual uint64_t getRawData () const
virtual std::string dbgHeader () const
virtual uint8_t offsetBits () const
EntryType type () const
bool supersection () const
Is the page a Supersection (16MB)?
Addr paddr () const
Return the physcal address of the entry, bits in position.
Addr paddr (Addr va) const
Return the physcal address of the entry, bits in position.
Addr pfn () const
Return the physical frame, bits shifted right.
bool global (WalkerState *currState) const
Is the translation global (no asid used)?
bool xn () const
Is the translation not allow execution?
uint8_t ap () const
Three bit access protection flags.
TlbEntry::DomainType domain () const
Domain Client/Manager: ARM DDI 0406B: B3-31.
Addr l2Addr () const
Address of L2 descriptor if it exists.
uint8_t texcb () const
Memory region attributes: ARM DDI 0406B: B3-32.
bool shareable () const
If the section is shareable.
void setAp0 ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
bool secure (bool have_security, WalkerState *currState) const
Returns true if this entry targets the secure physical address map.
Public Attributes
uint32_t data
The raw bits of the entry.
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Detailed Description
Definition at line 91 of file table_walker.hh.
Member Enumeration Documentation
enum ArmISA::TableWalker::L1Descriptor::EntryType
Type of page table entry ARM DDI 0406B: B3-8.
Enumerator:
Ignore
PageTable
Section
Reserved
Definition at line 94 of file table_walker.hh.
Constructor & Destructor Documentation
ArmISA::TableWalker::L1Descriptor::L1Descriptor () [inline]
Default ctor.
Definition at line 109 of file table_walker.hh.
References ArmISA::L1, and ArmISA::TableWalker::DescriptorBase::lookupLevel.
Member Function Documentation
uint8_t ArmISA::TableWalker::L1Descriptor::ap () const [inline, virtual]
Three bit access protection flags.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 177 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor().
virtual std::string ArmISA::TableWalker::L1Descriptor::dbgHeader () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 119 of file table_walker.hh.
bool ArmISA::TableWalker::L1Descriptor::dirty () const [inline]
This entry needs to be written back to memory.
Definition at line 220 of file table_walker.hh.
References _dirty.
TlbEntry::DomainType ArmISA::TableWalker::L1Descriptor::domain () const [inline, virtual]
Domain Client/Manager: ARM DDI 0406B: B3-31.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 183 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL2Descriptor(), and ArmISA::TableWalker::L2Descriptor::domain().
virtual uint64_t ArmISA::TableWalker::L1Descriptor::getRawData () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 114 of file table_walker.hh.
References data.
bool ArmISA::TableWalker::L1Descriptor::global (WalkerState * currState) const [inline, virtual]
Is the translation global (no asid used)?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 165 of file table_walker.hh.
References bits(), and data.
Addr ArmISA::TableWalker::L1Descriptor::l2Addr () const [inline]
Address of L2 descriptor if it exists.
Definition at line 189 of file table_walker.hh.
References data, and mbits().
Referenced by ArmISA::TableWalker::doL1Descriptor().
virtual uint8_t ArmISA::TableWalker::L1Descriptor::offsetBits () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 124 of file table_walker.hh.
Addr ArmISA::TableWalker::L1Descriptor::paddr (Addr va) const [inline]
Return the physcal address of the entry, bits in position.
Definition at line 148 of file table_walker.hh.
References data, mbits(), panic, and supersection().
Addr ArmISA::TableWalker::L1Descriptor::paddr () const [inline]
Return the physcal address of the entry, bits in position.
Definition at line 141 of file table_walker.hh.
References data, mbits(), panic, and supersection().
Addr ArmISA::TableWalker::L1Descriptor::pfn () const [inline, virtual]
Return the physical frame, bits shifted right.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 157 of file table_walker.hh.
References bits(), data, panic, and supersection().
bool ArmISA::TableWalker::L1Descriptor::secure (bool have_security, WalkerState * currState) const [inline, virtual]
Returns true if this entry targets the secure physical address map.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 229 of file table_walker.hh.
References bits(), data, PageTable, and type().
Referenced by ArmISA::TableWalker::L2Descriptor::secure().
void ArmISA::TableWalker::L1Descriptor::setAp0 () [inline]
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 213 of file table_walker.hh.
References _dirty, and data.
bool ArmISA::TableWalker::L1Descriptor::shareable () const [inline, virtual]
If the section is shareable.
See texcb() comment.
Reimplemented from ArmISA::TableWalker::DescriptorBase.
Definition at line 205 of file table_walker.hh.
References bits(), and data.
bool ArmISA::TableWalker::L1Descriptor::supersection () const [inline]
Is the page a Supersection (16MB)?
Definition at line 135 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor(), paddr(), and pfn().
uint8_t ArmISA::TableWalker::L1Descriptor::texcb () const [inline, virtual]
Memory region attributes: ARM DDI 0406B: B3-32.
These bits are largly ignored by M5 and only used to provide the illusion that the memory system cares about anything but cachable vs. uncachable.
Reimplemented from ArmISA::TableWalker::DescriptorBase.
Definition at line 199 of file table_walker.hh.
References bits(), and data.
EntryType ArmISA::TableWalker::L1Descriptor::type () const [inline]
Definition at line 129 of file table_walker.hh.
References data.
Referenced by ArmISA::TableWalker::doL1Descriptor(), and secure().
bool ArmISA::TableWalker::L1Descriptor::xn () const [inline, virtual]
Is the translation not allow execution?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 171 of file table_walker.hh.
References bits(), and data.
Member Data Documentation
bool ArmISA::TableWalker::L1Descriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 106 of file table_walker.hh.
Referenced by dirty(), and setAp0().
uint32_t ArmISA::TableWalker::L1Descriptor::data
The raw bits of the entry.
Definition at line 102 of file table_walker.hh.
Referenced by ap(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL1DescriptorWrapper(), domain(), getRawData(), global(), l2Addr(), paddr(), pfn(), ArmISA::TableWalker::processWalk(), secure(), setAp0(), shareable(), supersection(), texcb(), type(), and xn().
The documentation for this class was generated from the following file:
arch/arm/table_walker.hh