gem5: Intel8254Timer::Counter Class Reference
Intel8254Timer::Counter Class Reference
Counter element for PIT.
#include <intel_8254_timer.hh>
Classes
class CounterEvent
Event for counter interrupt.
Public Member Functions
Counter (Intel8254Timer *p, const std::string &name, unsigned int num)
void latchCount ()
Latch the current count (if one is not already latched).
int currentCount ()
Get the current count for this counter.
void setRW (int rw_val)
Set the read/write mode.
void setMode (int mode_val)
Set operational mode.
void setBCD (int bcd_val)
Set count encoding.
uint8_t read ()
Read a count byte.
void write (const uint8_t data)
Write a count byte.
bool outputHigh ()
Is the output high?
void serialize (const std::string &base, std::ostream &os)
Serialize this object to the given output stream.
void unserialize (const std::string &base, Checkpoint *cp, const std::string &section)
Reconstruct the state of this object from a checkpoint.
void startup ()
Start ticking.
Private Types
enum { LSB, MSB }
Set of values for read_byte and write_byte.
Private Member Functions
const std::string & name () const
Private Attributes
std::string _name
unsigned int num
CounterEvent event
bool running
True after startup is called.
uint16_t initial_count
Initial count value.
uint16_t latched_count
Latched count.
uint16_t period
Interrupt period.
Tick offset
When to start ticking.
uint8_t mode
Current mode of operation.
bool output_high
Output goes high when the counter reaches zero.
bool latch_on
State of the count latch.
uint8_t read_byte
Determine which byte of a 16-bit count value to read/write.
uint8_t write_byte
Intel8254Timer * parent
Pointer to container.
Detailed Description
Counter element for PIT.
Definition at line 81 of file intel_8254_timer.hh.
Member Enumeration Documentation
anonymous enum [private]
Set of values for read_byte and write_byte.
Enumerator:
LSB
MSB
Definition at line 142 of file intel_8254_timer.hh.
Constructor & Destructor Documentation
Intel8254Timer::Counter::Counter (Intel8254Timer * p, const std::string & name, unsigned int num)
Member Function Documentation
int Intel8254Timer::Counter::currentCount ()
Get the current count for this counter.
Definition at line 122 of file intel_8254_timer.cc.
References mode, Intel8254Timer::RateGen, Intel8254Timer::SquareWave, and warn_once.
Referenced by latchCount(), and read().
void Intel8254Timer::Counter::latchCount ()
Latch the current count (if one is not already latched).
Definition at line 111 of file intel_8254_timer.cc.
References currentCount(), latch_on, latched_count, LSB, and read_byte.
Referenced by Intel8254Timer::writeControl().
const std::string& Intel8254Timer::Counter::name () const [inline, private]
Definition at line 111 of file intel_8254_timer.hh.
References _name.
bool Intel8254Timer::Counter::outputHigh ()
Is the output high?
Definition at line 226 of file intel_8254_timer.cc.
References output_high.
Referenced by Intel8254Timer::outputHigh().
uint8_t Intel8254Timer::Counter::read ()
Read a count byte.
Definition at line 136 of file intel_8254_timer.cc.
References X86ISA::count, currentCount(), latch_on, latched_count, LSB, MSB, panic, and read_byte.
Referenced by Intel8254Timer::readCounter().
void Intel8254Timer::Counter::serialize (const std::string & base, std::ostream & os)
Serialize this object to the given output stream.
Parameters:
base The base name of the counter object.
os The stream to serialize to.
void Intel8254Timer::Counter::setBCD (int bcd_val)
Set count encoding.
Definition at line 219 of file intel_8254_timer.cc.
References panic.
Referenced by Intel8254Timer::writeControl().
void Intel8254Timer::Counter::setMode (int mode_val)
Set operational mode.
Definition at line 209 of file intel_8254_timer.cc.
References Intel8254Timer::InitTc, mode, panic, Intel8254Timer::RateGen, and Intel8254Timer::SquareWave.
Referenced by Intel8254Timer::writeControl().
void Intel8254Timer::Counter::setRW (int rw_val)
Set the read/write mode.
Definition at line 202 of file intel_8254_timer.cc.
References panic, and Intel8254Timer::TwoPhase.
Referenced by Intel8254Timer::writeControl().
void Intel8254Timer::Counter::startup ()
Start ticking.
Definition at line 269 of file intel_8254_timer.cc.
References curTick(), event, offset, parent, period, running, and EventManager::schedule().
Referenced by Intel8254Timer::startup().
void Intel8254Timer::Counter::unserialize (const std::string & base, Checkpoint * cp, const std::string & section)
Reconstruct the state of this object from a checkpoint.
Parameters:
base The base name of the counter object.
cp The checkpoint use.
section The section name of this object
void Intel8254Timer::Counter::write (const uint8_t data)
Write a count byte.
Definition at line 170 of file intel_8254_timer.cc.
References EventManager::deschedule(), event, initial_count, LSB, mode, MSB, offset, output_high, parent, period, Intel8254Timer::RateGen, running, Event::scheduled(), Intel8254Timer::SquareWave, and write_byte.
Referenced by Intel8254Timer::writeCounter().
Member Data Documentation
std::string Intel8254Timer::Counter::_name [private]
Definition at line 110 of file intel_8254_timer.hh.
Referenced by name().
CounterEvent Intel8254Timer::Counter::event [private]
Definition at line 115 of file intel_8254_timer.hh.
Referenced by startup(), and write().
uint16_t Intel8254Timer::Counter::initial_count [private]
Initial count value.
Definition at line 121 of file intel_8254_timer.hh.
Referenced by write().
bool Intel8254Timer::Counter::latch_on [private]
State of the count latch.
Definition at line 139 of file intel_8254_timer.hh.
Referenced by latchCount(), and read().
uint16_t Intel8254Timer::Counter::latched_count [private]
Latched count.
Definition at line 124 of file intel_8254_timer.hh.
Referenced by latchCount(), and read().
uint8_t Intel8254Timer::Counter::mode [private]
Current mode of operation.
Definition at line 133 of file intel_8254_timer.hh.
Referenced by currentCount(), Intel8254Timer::Counter::CounterEvent::process(), setMode(), and write().
unsigned int Intel8254Timer::Counter::num [private]
Definition at line 113 of file intel_8254_timer.hh.
Referenced by Intel8254Timer::Counter::CounterEvent::process().
Tick Intel8254Timer::Counter::offset [private]
When to start ticking.
Definition at line 130 of file intel_8254_timer.hh.
Referenced by startup(), and write().
bool Intel8254Timer::Counter::output_high [private]
Output goes high when the counter reaches zero.
Definition at line 136 of file intel_8254_timer.hh.
Referenced by outputHigh(), Intel8254Timer::Counter::CounterEvent::process(), and write().
Intel8254Timer* Intel8254Timer::Counter::parent [private]
Pointer to container.
Definition at line 148 of file intel_8254_timer.hh.
Referenced by Intel8254Timer::Counter::CounterEvent::process(), Intel8254Timer::Counter::CounterEvent::setTo(), startup(), and write().
uint16_t Intel8254Timer::Counter::period [private]
Interrupt period.
Definition at line 127 of file intel_8254_timer.hh.
Referenced by Intel8254Timer::Counter::CounterEvent::process(), startup(), and write().
uint8_t Intel8254Timer::Counter::read_byte [private]
Determine which byte of a 16-bit count value to read/write.
Definition at line 145 of file intel_8254_timer.hh.
Referenced by latchCount(), and read().
bool Intel8254Timer::Counter::running [private]
True after startup is called.
Definition at line 118 of file intel_8254_timer.hh.
Referenced by startup(), and write().
uint8_t Intel8254Timer::Counter::write_byte [private]
Definition at line 145 of file intel_8254_timer.hh.
Referenced by write().
The documentation for this class was generated from the following files:
dev/intel_8254_timer.hh
dev/intel_8254_timer.cc