gem5: Stats::VectorDistBase< Derived, Stor > Class Template Reference
Stats::VectorDistBase< Derived, Stor > Class Template Reference
#include <statistics.hh>
Public Types
typedef VectorDistInfoProxy
< Derived > Info
typedef Stor Storage
typedef Stor::Params Params
typedef DistProxy< Derived > Proxy
Public Member Functions
VectorDistBase ()
~VectorDistBase ()
Proxy operator[] (off_type index)
size_type size () const
bool zero () const
void prepare ()
bool check () const
Check that this stat has been set up properly and is ready for use.
Protected Member Functions
Storage * data (off_type index)
const Storage * data (off_type index) const
void doInit (size_type s)
Protected Attributes
Storage * storage
size_type _size
Friends
class DistProxy< Derived >
class DataWrapVec< Derived, VectorDistInfoProxy >
Detailed Description
template<class Derived, class Stor>
class Stats::VectorDistBase< Derived, Stor >
Definition at line 1892 of file statistics.hh.
Member Typedef Documentation
template<class Derived, class Stor> typedef VectorDistInfoProxy<Derived> Stats::VectorDistBase< Derived, Stor >::Info
Reimplemented from Stats::DataWrapVec< Derived, VectorDistInfoProxy >.
Definition at line 1895 of file statistics.hh.
template<class Derived, class Stor> typedef Stor::Params Stats::VectorDistBase< Derived, Stor >::Params
Definition at line 1897 of file statistics.hh.
template<class Derived, class Stor> typedef DistProxy<Derived> Stats::VectorDistBase< Derived, Stor >::Proxy
Definition at line 1898 of file statistics.hh.
template<class Derived, class Stor> typedef Stor Stats::VectorDistBase< Derived, Stor >::Storage
Definition at line 1896 of file statistics.hh.
Constructor & Destructor Documentation
template<class Derived, class Stor> Stats::VectorDistBase< Derived, Stor >::VectorDistBase () [inline]
Definition at line 1937 of file statistics.hh.
template<class Derived, class Stor> Stats::VectorDistBase< Derived, Stor >::~VectorDistBase () [inline]
Definition at line 1941 of file statistics.hh.
Member Function Documentation
template<class Derived, class Stor> bool Stats::VectorDistBase< Derived, Stor >::check () const [inline]
Check that this stat has been set up properly and is ready for use.
Returns:
true for success
Reimplemented from Stats::InfoAccess.
Definition at line 1983 of file statistics.hh.
template<class Derived, class Stor> const Storage* Stats::VectorDistBase< Derived, Stor >::data (off_type index) const [inline, protected]
Definition at line 1914 of file statistics.hh.
template<class Derived, class Stor> Storage* Stats::VectorDistBase< Derived, Stor >::data (off_type index) [inline, protected]
Definition at line 1908 of file statistics.hh.
Referenced by Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::prepare(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::zero(), and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::~VectorDistBase().
template<class Derived, class Stor> void Stats::VectorDistBase< Derived, Stor >::doInit (size_type s) [inline, protected]
Definition at line 1920 of file statistics.hh.
template<class Derived, class Stor> Proxy Stats::VectorDistBase< Derived, Stor >::operator[] (off_type index) [inline]
Definition at line 1951 of file statistics.hh.
template<class Derived, class Stor> void Stats::VectorDistBase< Derived, Stor >::prepare () [inline]
Reimplemented from Stats::DataWrapVec< Derived, VectorDistInfoProxy >.
Definition at line 1973 of file statistics.hh.
template<class Derived, class Stor> size_type Stats::VectorDistBase< Derived, Stor >::size () const [inline]
Definition at line 1958 of file statistics.hh.
Referenced by Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::operator[](), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::prepare(), and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::zero().
template<class Derived, class Stor> bool Stats::VectorDistBase< Derived, Stor >::zero () const [inline]
Returns:
true if this stat has a value and satisfies its requirement as a prereq
Reimplemented from Stats::InfoAccess.
Definition at line 1964 of file statistics.hh.
Friends And Related Function Documentation
template<class Derived, class Stor> friend class DataWrapVec< Derived, VectorDistInfoProxy > [friend]
Definition at line 1900 of file statistics.hh.
template<class Derived, class Stor> friend class DistProxy< Derived > [friend]
Definition at line 1899 of file statistics.hh.
Member Data Documentation
template<class Derived, class Stor> size_type Stats::VectorDistBase< Derived, Stor >::_size [protected]
Definition at line 1904 of file statistics.hh.
Referenced by Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::doInit(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::size(), and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::~VectorDistBase().
template<class Derived, class Stor> Storage* Stats::VectorDistBase< Derived, Stor >::storage [protected]
Definition at line 1903 of file statistics.hh.
Referenced by Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::check(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::data(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::doInit(), and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::~VectorDistBase().
The documentation for this class was generated from the following file:
base/statistics.hh