gem5: GarnetNetwork_d Class Reference
GarnetNetwork_d Class Reference
#include <GarnetNetwork_d.hh>
Public Types
typedef GarnetNetwork_dParams Params
Public Member Functions
GarnetNetwork_d (const Params *p)
~GarnetNetwork_d ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
int getBuffersPerDataVC ()
int getBuffersPerCtrlVC ()
void collateStats ()
void regStats ()
Register statistics for this object.
void print (std::ostream &out) const
VNET_type get_vnet_type (int vc)
void makeOutLink (SwitchID src, NodeID dest, BasicLink *link, LinkDirection direction, const NetDest &routing_table_entry)
void makeInLink (NodeID src, SwitchID dest, BasicLink *link, LinkDirection direction, const NetDest &routing_table_entry)
void makeInternalLink (SwitchID src, SwitchID dest, BasicLink *link, LinkDirection direction, const NetDest &routing_table_entry)
uint32_t functionalWrite (Packet *pkt)
Function for performing a functional write.
Private Member Functions
void checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type)
GarnetNetwork_d (const GarnetNetwork_d &obj)
GarnetNetwork_d & operator= (const GarnetNetwork_d &obj)
Private Attributes
std::vector< VNET_type > m_vnet_type
std::vector< Router_d * > m_routers
std::vector< NetworkLink_d * > m_links
std::vector< CreditLink_d * > m_creditlinks
std::vector< NetworkInterface_d * > m_nis
int m_buffers_per_data_vc
int m_buffers_per_ctrl_vc
Stats::Scalar m_average_link_utilization
Stats::Vector m_average_vc_load
Detailed Description
Definition at line 48 of file GarnetNetwork_d.hh.
Member Typedef Documentation
typedef GarnetNetwork_dParams GarnetNetwork_d::Params
Reimplemented from BaseGarnetNetwork.
Definition at line 51 of file GarnetNetwork_d.hh.
Constructor & Destructor Documentation
GarnetNetwork_d::GarnetNetwork_d (const Params * p)
Definition at line 47 of file GarnetNetwork_d.cc.
References ArmISA::i, NetworkInterface_d::init_net_ptr(), Router_d::init_net_ptr(), m_buffers_per_ctrl_vc, m_buffers_per_data_vc, m_nis, m_routers, Network::m_virtual_networks, m_vnet_type, PowerISA::ni, NULL_VNET_, and safe_cast().
GarnetNetwork_d::~GarnetNetwork_d ()
Definition at line 109 of file GarnetNetwork_d.cc.
References m5::stl_helpers::deletePointers(), m_creditlinks, m_links, m_nis, and m_routers.
GarnetNetwork_d::GarnetNetwork_d (const GarnetNetwork_d & obj) [private]
Member Function Documentation
void GarnetNetwork_d::checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type) [private, virtual]
Implements BaseGarnetNetwork.
void GarnetNetwork_d::collateStats () [virtual]
Reimplemented from BaseGarnetNetwork.
Definition at line 224 of file GarnetNetwork_d.cc.
References ClockedObject::curCycle(), g_ruby_start, ArmISA::i, ArmISA::j, m_average_link_utilization, m_average_vc_load, m_links, and m_routers.
uint32_t GarnetNetwork_d::functionalWrite (Packet * pkt) [virtual]
Function for performing a functional write.
The return value indicates the number of messages that were written.
Reimplemented from Network.
Definition at line 257 of file GarnetNetwork_d.cc.
References ArmISA::i, m_links, m_nis, and m_routers.
VNET_type GarnetNetwork_d::get_vnet_type (int vc) [inline]
Definition at line 65 of file GarnetNetwork_d.hh.
References BaseGarnetNetwork::getVCsPerVnet(), and m_vnet_type.
Referenced by OutVcState_d::OutVcState_d().
int GarnetNetwork_d::getBuffersPerCtrlVC () [inline]
Definition at line 58 of file GarnetNetwork_d.hh.
References m_buffers_per_ctrl_vc.
Referenced by init(), and OutVcState_d::OutVcState_d().
int GarnetNetwork_d::getBuffersPerDataVC () [inline]
Definition at line 57 of file GarnetNetwork_d.hh.
References m_buffers_per_data_vc.
Referenced by init(), and OutVcState_d::OutVcState_d().
void GarnetNetwork_d::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BaseGarnetNetwork.
Definition at line 78 of file GarnetNetwork_d.cc.
References Topology::createLinks(), FaultModel::declare_router(), BaseGarnetNetwork::fault_model, Router_d::get_id(), Router_d::get_num_inports(), Router_d::get_num_outports(), Router_d::get_vc_per_vnet(), getBuffersPerCtrlVC(), getBuffersPerDataVC(), ArmISA::i, BaseGarnetNetwork::isFaultModelEnabled(), ArmISA::M5_VAR_USED, Network::m_fromNetQueues, m_nis, Network::m_nodes, m_routers, Network::m_toNetQueues, Network::m_topology_ptr, Router_d::printAggregateFaultProbability(), Router_d::printFaultVector(), and safe_cast().
void GarnetNetwork_d::makeInLink (NodeID src, SwitchID dest, BasicLink * link, LinkDirection direction, const NetDest & routing_table_entry) [virtual]
Implements Network.
Definition at line 125 of file GarnetNetwork_d.cc.
References GarnetExtLink_d::m_credit_links, m_creditlinks, m_links, GarnetExtLink_d::m_network_links, m_nis, Network::m_nodes, m_routers, and safe_cast().
void GarnetNetwork_d::makeInternalLink (SwitchID src, SwitchID dest, BasicLink * link, LinkDirection direction, const NetDest & routing_table_entry) [virtual]
Implements Network.
Definition at line 174 of file GarnetNetwork_d.cc.
References GarnetIntLink_d::m_credit_links, m_creditlinks, m_links, GarnetIntLink_d::m_network_links, m_routers, BasicLink::m_weight, and safe_cast().
void GarnetNetwork_d::makeOutLink (SwitchID src, NodeID dest, BasicLink * link, LinkDirection direction, const NetDest & routing_table_entry) [virtual]
Implements Network.
Definition at line 149 of file GarnetNetwork_d.cc.
References GarnetExtLink_d::m_credit_links, m_creditlinks, m_links, GarnetExtLink_d::m_network_links, m_nis, Network::m_nodes, m_routers, BasicLink::m_weight, and safe_cast().
GarnetNetwork_d& GarnetNetwork_d::operator= (const GarnetNetwork_d & obj) [private]
Reimplemented from Network.
void GarnetNetwork_d::print (std::ostream & out) const [virtual]
Implements Network.
Referenced by operator<<().
void GarnetNetwork_d::regStats () [virtual]
Register statistics for this object.
Reimplemented from BaseGarnetNetwork.
Definition at line 210 of file GarnetNetwork_d.cc.
References Stats::VectorBase< Derived, Stor >::init(), m_average_link_utilization, m_average_vc_load, BaseGarnetNetwork::m_vcs_per_vnet, Network::m_virtual_networks, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, Stats::oneline, Stats::pdf, and Stats::total.
Member Data Documentation
Stats::Scalar GarnetNetwork_d::m_average_link_utilization [private]
Definition at line 103 of file GarnetNetwork_d.hh.
Referenced by collateStats(), and regStats().
Stats::Vector GarnetNetwork_d::m_average_vc_load [private]
Definition at line 104 of file GarnetNetwork_d.hh.
Referenced by collateStats(), and regStats().
int GarnetNetwork_d::m_buffers_per_ctrl_vc [private]
Definition at line 100 of file GarnetNetwork_d.hh.
Referenced by GarnetNetwork_d(), and getBuffersPerCtrlVC().
int GarnetNetwork_d::m_buffers_per_data_vc [private]
Definition at line 99 of file GarnetNetwork_d.hh.
Referenced by GarnetNetwork_d(), and getBuffersPerDataVC().
std::vector<CreditLink_d *> GarnetNetwork_d::m_creditlinks [private]
Definition at line 96 of file GarnetNetwork_d.hh.
Referenced by makeInLink(), makeInternalLink(), makeOutLink(), and ~GarnetNetwork_d().
std::vector<NetworkLink_d *> GarnetNetwork_d::m_links [private]
Definition at line 95 of file GarnetNetwork_d.hh.
Referenced by collateStats(), functionalWrite(), makeInLink(), makeInternalLink(), makeOutLink(), and ~GarnetNetwork_d().
std::vector<NetworkInterface_d *> GarnetNetwork_d::m_nis [private]
Definition at line 97 of file GarnetNetwork_d.hh.
Referenced by functionalWrite(), GarnetNetwork_d(), init(), makeInLink(), makeOutLink(), and ~GarnetNetwork_d().
std::vector<Router_d *> GarnetNetwork_d::m_routers [private]
Definition at line 94 of file GarnetNetwork_d.hh.
Referenced by collateStats(), functionalWrite(), GarnetNetwork_d(), init(), makeInLink(), makeInternalLink(), makeOutLink(), and ~GarnetNetwork_d().
std::vector<VNET_type > GarnetNetwork_d::m_vnet_type [private]
Definition at line 93 of file GarnetNetwork_d.hh.
Referenced by GarnetNetwork_d(), and get_vnet_type().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/GarnetNetwork_d.hh
mem/ruby/network/garnet/fixed-pipeline/GarnetNetwork_d.cc