gem5: ArmISA::TableWalker::L2Descriptor Class Reference
ArmISA::TableWalker::L2Descriptor Class Reference
Level 2 page table descriptor.
#include <table_walker.hh>
Public Member Functions
L2Descriptor ()
Default ctor.
L2Descriptor (L1Descriptor &parent)
virtual uint64_t getRawData () const
virtual std::string dbgHeader () const
virtual TlbEntry::DomainType domain () const
bool secure (bool have_security, WalkerState *currState) const
virtual uint8_t offsetBits () const
bool invalid () const
Is the entry invalid.
bool large () const
What is the size of the mapping?
bool xn () const
Is execution allowed on this mapping?
bool global (WalkerState *currState) const
Is the translation global (no asid used)?
uint8_t ap () const
Three bit access protection flags.
uint8_t texcb () const
Memory region attributes: ARM DDI 0406B: B3-32.
Addr pfn () const
Return the physical frame, bits shifted right.
Addr paddr (Addr va) const
Return complete physical address given a VA.
bool shareable () const
If the section is shareable.
void setAp0 ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
Public Attributes
uint32_t data
The raw bits of the entry.
L1Descriptor * l1Parent
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Detailed Description
Level 2 page table descriptor.
Definition at line 242 of file table_walker.hh.
Constructor & Destructor Documentation
ArmISA::TableWalker::L2Descriptor::L2Descriptor () [inline]
Default ctor.
Definition at line 253 of file table_walker.hh.
References ArmISA::L2, and ArmISA::TableWalker::DescriptorBase::lookupLevel.
ArmISA::TableWalker::L2Descriptor::L2Descriptor (L1Descriptor & parent) [inline]
Definition at line 258 of file table_walker.hh.
References ArmISA::L2, and ArmISA::TableWalker::DescriptorBase::lookupLevel.
Member Function Documentation
uint8_t ArmISA::TableWalker::L2Descriptor::ap () const [inline, virtual]
Three bit access protection flags.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 314 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor().
virtual std::string ArmISA::TableWalker::L2Descriptor::dbgHeader () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 269 of file table_walker.hh.
bool ArmISA::TableWalker::L2Descriptor::dirty () const [inline]
This entry needs to be written back to memory.
Definition at line 358 of file table_walker.hh.
References _dirty.
virtual TlbEntry::DomainType ArmISA::TableWalker::L2Descriptor::domain () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 274 of file table_walker.hh.
References ArmISA::TableWalker::L1Descriptor::domain(), and l1Parent.
virtual uint64_t ArmISA::TableWalker::L2Descriptor::getRawData () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 264 of file table_walker.hh.
References data.
bool ArmISA::TableWalker::L2Descriptor::global (WalkerState * currState) const [inline, virtual]
Is the translation global (no asid used)?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 308 of file table_walker.hh.
References bits(), and data.
bool ArmISA::TableWalker::L2Descriptor::invalid () const [inline]
Is the entry invalid.
Definition at line 290 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor().
bool ArmISA::TableWalker::L2Descriptor::large () const [inline]
What is the size of the mapping?
Definition at line 296 of file table_walker.hh.
References bits(), and data.
Referenced by offsetBits(), paddr(), pfn(), texcb(), and xn().
virtual uint8_t ArmISA::TableWalker::L2Descriptor::offsetBits () const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 284 of file table_walker.hh.
References large().
Addr ArmISA::TableWalker::L2Descriptor::paddr (Addr va) const [inline]
Return complete physical address given a VA.
Definition at line 334 of file table_walker.hh.
References data, large(), and mbits().
Addr ArmISA::TableWalker::L2Descriptor::pfn () const [inline, virtual]
Return the physical frame, bits shifted right.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 328 of file table_walker.hh.
References bits(), data, and large().
bool ArmISA::TableWalker::L2Descriptor::secure (bool have_security, WalkerState * currState) const [inline, virtual]
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 279 of file table_walker.hh.
References l1Parent, and ArmISA::TableWalker::L1Descriptor::secure().
void ArmISA::TableWalker::L2Descriptor::setAp0 () [inline]
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 351 of file table_walker.hh.
References _dirty, and data.
bool ArmISA::TableWalker::L2Descriptor::shareable () const [inline, virtual]
If the section is shareable.
See texcb() comment.
Reimplemented from ArmISA::TableWalker::DescriptorBase.
Definition at line 343 of file table_walker.hh.
References bits(), and data.
uint8_t ArmISA::TableWalker::L2Descriptor::texcb () const [inline, virtual]
Memory region attributes: ARM DDI 0406B: B3-32.
Reimplemented from ArmISA::TableWalker::DescriptorBase.
Definition at line 320 of file table_walker.hh.
References bits(), data, and large().
bool ArmISA::TableWalker::L2Descriptor::xn () const [inline, virtual]
Is execution allowed on this mapping?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 302 of file table_walker.hh.
References bits(), data, and large().
Member Data Documentation
bool ArmISA::TableWalker::L2Descriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 250 of file table_walker.hh.
Referenced by dirty(), and setAp0().
uint32_t ArmISA::TableWalker::L2Descriptor::data
The raw bits of the entry.
Definition at line 245 of file table_walker.hh.
Referenced by ap(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL2Descriptor(), getRawData(), global(), invalid(), large(), paddr(), pfn(), setAp0(), shareable(), texcb(), and xn().
L1Descriptor* ArmISA::TableWalker::L2Descriptor::l1Parent
Definition at line 246 of file table_walker.hh.
Referenced by domain(), and secure().
The documentation for this class was generated from the following file:
arch/arm/table_walker.hh