gem5: PacketQueue Class Reference
PacketQueue Class Reference
A packet queue is a class that holds deferred packets and later sends them using the associated slave port or master port.
#include <packet_queue.hh>
Classes
class DeferredPacket
A deferred packet, buffered to transmit later.
Public Member Functions
virtual const std::string name () const =0
Provide a name to simplify debugging.
size_t size () const
Get the size of the queue.
Tick deferredPacketReadyTime () const
Get the next packet ready time.
bool hasAddr (Addr addr) const
Check if a packets address exists in the queue.
bool checkFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
void schedSendEvent (Tick when)
Schedule a send event if we are not already waiting for a retry.
void schedSendTiming (PacketPtr pkt, Tick when, bool force_order=false)
Add a packet to the transmit list, and schedule a send event.
void retry ()
Retry sending a packet from the queue.
unsigned int drain (DrainManager *dm)
Determine if an object needs draining and register a DrainManager.
Protected Member Functions
bool deferredPacketReady () const
Check whether we have a packet ready to go on the transmit list.
virtual void sendDeferredPacket ()
Attempt to send a packet.
virtual bool sendTiming (PacketPtr pkt)=0
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
PacketQueue (EventManager &_em, const std::string &_label)
Create a packet queue, linked to an event manager, and a label that will be used for functional print request packets.
virtual ~PacketQueue ()
Virtual desctructor since the class may be used as a base class.
Protected Attributes
const std::string label
Label to use for print request packets label stack.
bool waitingOnRetry
Remember whether we're awaiting a retry.
Private Types
typedef std::list< DeferredPacket > DeferredPacketList
Private Member Functions
void processSendEvent ()
Used to schedule sending of deferred packets.
Private Attributes
DeferredPacketList transmitList
A list of outgoing packets.
EventManager & em
The manager which is used for the event queue.
EventWrapper< PacketQueue,&PacketQueue::processSendEvent > sendEvent
Event used to call processSendEvent.
DrainManager * drainManager
If we need to drain, keep the drain manager around until we're done here.
Detailed Description
A packet queue is a class that holds deferred packets and later sends them using the associated slave port or master port.
Definition at line 65 of file packet_queue.hh.
Member Typedef Documentation
typedef std::list<DeferredPacket> PacketQueue::DeferredPacketList [private]
Definition at line 78 of file packet_queue.hh.
Constructor & Destructor Documentation
PacketQueue::PacketQueue (EventManager & _em, const std::string & _label) [protected]
Create a packet queue, linked to an event manager, and a label that will be used for functional print request packets.
Parameters:
_em Event manager used for scheduling this queue
_label Label to push on the label stack for print request packets
Definition at line 51 of file packet_queue.cc.
PacketQueue::~PacketQueue () [protected, virtual]
Virtual desctructor since the class may be used as a base class.
Definition at line 57 of file packet_queue.cc.
Member Function Documentation
bool PacketQueue::checkFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
Definition at line 83 of file packet_queue.cc.
References Packet::checkFunctional(), ArmISA::i, label, Packet::popLabel(), Packet::pushLabel(), and transmitList.
Referenced by QueuedMasterPort::checkFunctional(), QueuedSlavePort::checkFunctional(), SimpleTimingPort::recvFunctional(), RubyMemoryControl::MemoryPort::recvFunctional(), and DRAMCtrl::MemoryPort::recvFunctional().
bool PacketQueue::deferredPacketReady () const [inline, protected]
Check whether we have a packet ready to go on the transmit list.
Definition at line 105 of file packet_queue.hh.
References curTick(), and transmitList.
Referenced by sendDeferredPacket().
Tick PacketQueue::deferredPacketReadyTime () const [inline]
Get the next packet ready time.
Definition at line 155 of file packet_queue.hh.
References MaxTick, and transmitList.
Referenced by sendDeferredPacket(), and Cache::CacheReqPacketQueue::sendDeferredPacket().
unsigned int PacketQueue::drain (DrainManager * drainManager) [virtual]
Determine if an object needs draining and register a DrainManager.
When draining the state of an object, the simulator calls drain with a pointer to a drain manager. If the object does not need further simulation to drain internal buffers, it switched to the Drained state and returns 0, otherwise it switches to the Draining state and returns the number of times that it will call Event::process() on the drain event. Most objects are expected to return either 0 or 1.
Note:
An object that has entered the Drained state can be disturbed by other objects in the system and consequently be forced to enter the Draining state again. The simulator therefore repeats the draining process until all objects return 0 on the first call to drain().
Parameters:
drainManager DrainManager to use to inform the simulator when draining has completed.
Returns:
0 if the object is ready for serialization now, >0 if it needs further simulation.
Implements Drainable.
Definition at line 248 of file packet_queue.cc.
References DPRINTF, drainManager, and transmitList.
Referenced by QueuedMasterPort::drain(), and QueuedSlavePort::drain().
bool PacketQueue::hasAddr (Addr addr) const
Check if a packets address exists in the queue.
Definition at line 71 of file packet_queue.cc.
References MipsISA::p, and transmitList.
Referenced by Cache::CacheReqPacketQueue::sendDeferredPacket().
virtual const std::string PacketQueue::name () const [pure virtual]
Provide a name to simplify debugging.
Returns:
A complete name, appended to module and port
Implemented in ReqPacketQueue, SnoopRespPacketQueue, and RespPacketQueue.
Referenced by retry(), and schedSendTiming().
void PacketQueue::processSendEvent () [private]
Used to schedule sending of deferred packets.
Definition at line 241 of file packet_queue.cc.
References sendDeferredPacket(), and waitingOnRetry.
void PacketQueue::retry ()
Retry sending a packet from the queue.
Note that this is not necessarily the same packet if something has been added with an earlier time stamp.
Definition at line 62 of file packet_queue.cc.
References DPRINTF, name(), sendDeferredPacket(), and waitingOnRetry.
Referenced by QueuedMasterPort::recvReqRetry(), QueuedSlavePort::recvRespRetry(), and QueuedMasterPort::recvRetrySnoopResp().
void PacketQueue::schedSendEvent (Tick when)
Schedule a send event if we are not already waiting for a retry.
If the requested time is before an already scheduled send event, the event will be rescheduled. If MaxTick is passed, no event is scheduled. Instead, if we are idle and asked to drain then check and signal drained.
Parameters:
when time to schedule an event
Definition at line 176 of file packet_queue.cc.
References curTick(), DPRINTF, drainManager, em, MaxTick, EventManager::reschedule(), EventManager::schedule(), Event::scheduled(), sendEvent, DrainManager::signalDrainDone(), transmitList, waitingOnRetry, and Event::when().
Referenced by BaseCache::CacheMasterPort::requestBus(), schedSendTiming(), sendDeferredPacket(), and Cache::CacheReqPacketQueue::sendDeferredPacket().
void PacketQueue::schedSendTiming (PacketPtr pkt, Tick when, bool force_order = false)
Add a packet to the transmit list, and schedule a send event.
Parameters:
pkt Packet to send
when Absolute time (in ticks) to send packet
force_order Do not reorder packets despite timing, but keep them in insertion order.
Definition at line 103 of file packet_queue.cc.
References Packet::cmdString(), curTick(), DPRINTF, Packet::getAddr(), Packet::getSize(), ArmISA::i, Packet::isExpressSnoop(), name(), panic, schedSendEvent(), and transmitList.
Referenced by QueuedMasterPort::schedTimingReq(), QueuedSlavePort::schedTimingResp(), and QueuedMasterPort::schedTimingSnoopResp().
void PacketQueue::sendDeferredPacket () [protected, virtual]
Attempt to send a packet.
Note that a subclass of the PacketQueue can override this method and thus change the behaviour (as done by the cache for the request queue). The default implementation sends the head of the transmit list. The caller must guarantee that the list is non-empty and that the head packet is scheduled for curTick() (or earlier).
Reimplemented in Cache::CacheReqPacketQueue.
Definition at line 211 of file packet_queue.cc.
References deferredPacketReady(), deferredPacketReadyTime(), PacketQueue::DeferredPacket::pkt, schedSendEvent(), sendTiming(), transmitList, and waitingOnRetry.
Referenced by processSendEvent(), and retry().
virtual bool PacketQueue::sendTiming (PacketPtr pkt) [protected, pure virtual]
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
Implemented in ReqPacketQueue, SnoopRespPacketQueue, and RespPacketQueue.
Referenced by sendDeferredPacket().
size_t PacketQueue::size () const [inline]
Get the size of the queue.
Definition at line 150 of file packet_queue.hh.
References transmitList.
Member Data Documentation
DrainManager* PacketQueue::drainManager [private]
If we need to drain, keep the drain manager around until we're done here.
Definition at line 94 of file packet_queue.hh.
Referenced by drain(), and schedSendEvent().
EventManager& PacketQueue::em [private]
The manager which is used for the event queue.
Definition at line 84 of file packet_queue.hh.
Referenced by schedSendEvent().
const std::string PacketQueue::label [protected]
Label to use for print request packets label stack.
Definition at line 99 of file packet_queue.hh.
Referenced by checkFunctional(), RespPacketQueue::name(), SnoopRespPacketQueue::name(), and ReqPacketQueue::name().
EventWrapper<PacketQueue, &PacketQueue::processSendEvent> PacketQueue::sendEvent [private]
Event used to call processSendEvent.
Definition at line 90 of file packet_queue.hh.
Referenced by schedSendEvent().
DeferredPacketList PacketQueue::transmitList [private]
A list of outgoing packets.
Definition at line 81 of file packet_queue.hh.
Referenced by checkFunctional(), deferredPacketReady(), deferredPacketReadyTime(), drain(), hasAddr(), schedSendEvent(), schedSendTiming(), sendDeferredPacket(), and size().
bool PacketQueue::waitingOnRetry [protected]
Remember whether we're awaiting a retry.
Definition at line 102 of file packet_queue.hh.
Referenced by processSendEvent(), retry(), schedSendEvent(), sendDeferredPacket(), and Cache::CacheReqPacketQueue::sendDeferredPacket().
The documentation for this class was generated from the following files:
mem/packet_queue.hh
mem/packet_queue.cc