gem5: I2CBus Class Reference
I2CBus Class Reference
#include <i2cbus.hh>
Public Member Functions
I2CBus (const I2CBusParams *p)
4KB - see e.g.
virtual Tick read (PacketPtr pkt)
Reads will always be to SB_CONTROLS.
virtual Tick write (PacketPtr pkt)
The default i2c bus driver used by the realview pbx board writes to this device one bit at a time.
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
Protected Types
enum I2CState { IDLE, RECEIVING_ADDR, RECEIVING_DATA, SENDING_DATA }
Protected Member Functions
void updateSignals (PacketPtr pkt)
Update data (sda) and clock (scl) to match any transitions specified by pkt.
bool isClockSet (PacketPtr pkt) const
Clock set check.
bool isStart (PacketPtr pkt) const
i2c start signal check
bool isEnd (PacketPtr pkt) const
i2c end signal check
Protected Attributes
uint8_t scl
I2C clock wire (0, 1).
uint8_t sda
I2C data wire (0, 1).
enum I2CState state
State used by I2CBus::write to determine what stage of an i2c transmission it is currently in.
int currBit
Order of the bit of the current message that is being sent or received (0 - 7).
uint8_t i2cAddr
Key used to access a device in the slave devices map.
uint8_t message
8-bit buffer used to send and receive messages bit by bit.
std::map< uint8_t, I2CDevice * > devices
All the slave i2c devices that are connected to this bus.
Static Protected Attributes
static const int SB_CONTROLS = 0x0
Read [and Set] serial control bits: Bit [0] is SCL Bit [1] is SDA.
static const int SB_CONTROLC = 0x4
Clear control bits.
Detailed Description
Definition at line 54 of file i2cbus.hh.
Member Enumeration Documentation
enum I2CBus::I2CState [protected]
Enumerator:
IDLE
RECEIVING_ADDR
RECEIVING_DATA
SENDING_DATA
Definition at line 58 of file i2cbus.hh.
Constructor & Destructor Documentation
I2CBus::I2CBus (const I2CBusParams * p)
4KB - see e.g.
http://infocenter.arm.com/help/topic/com.arm.doc.dui0440b/Bbajihec.html
Definition at line 54 of file i2cbus.cc.
References ArmISA::d, and devices.
Member Function Documentation
bool I2CBus::isClockSet (PacketPtr pkt) const [protected]
Clock set check.
Parameters:
pkt memory request packet
Returns:
true if pkt indicates that scl transition from 0 to 1
Definition at line 192 of file i2cbus.cc.
References Packet::get(), Packet::getAddr(), BasicPioDevice::pioAddr, and SB_CONTROLS.
Referenced by write().
bool I2CBus::isEnd (PacketPtr pkt) const [protected]
i2c end signal check
Parameters:
pkt memory request packet
Returns:
true if pkt indicates stopping the current transmission
Definition at line 208 of file i2cbus.cc.
References Packet::get(), Packet::getAddr(), BasicPioDevice::pioAddr, SB_CONTROLS, and scl.
Referenced by write().
bool I2CBus::isStart (PacketPtr pkt) const [protected]
i2c start signal check
Parameters:
pkt memory request packet
Returns:
true if pkt indicates a new transmission
Definition at line 200 of file i2cbus.cc.
References Packet::get(), Packet::getAddr(), BasicPioDevice::pioAddr, SB_CONTROLC, and scl.
Referenced by write().
Tick I2CBus::read (PacketPtr pkt) [virtual]
Reads will always be to SB_CONTROLS.
The kernel wants to know the state of sda and scl.
Implements PioDevice.
Definition at line 70 of file i2cbus.cc.
References Packet::getAddr(), Packet::makeAtomicResponse(), BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, SB_CONTROLS, scl, sda, and Packet::set().
void I2CBus::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 215 of file i2cbus.cc.
References currBit, DPRINTF, i2cAddr, message, scl, sda, SERIALIZE_ENUM, SERIALIZE_SCALAR, and state.
void I2CBus::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 227 of file i2cbus.cc.
References currBit, DPRINTF, i2cAddr, message, scl, sda, state, UNSERIALIZE_ENUM, and UNSERIALIZE_SCALAR.
void I2CBus::updateSignals (PacketPtr pkt) [protected]
Update data (sda) and clock (scl) to match any transitions specified by pkt.
Parameters:
pkt memory request packet
Definition at line 172 of file i2cbus.cc.
References Packet::get(), Packet::getAddr(), BasicPioDevice::pioAddr, SB_CONTROLC, SB_CONTROLS, scl, and sda.
Referenced by write().
Tick I2CBus::write (PacketPtr pkt) [virtual]
The default i2c bus driver used by the realview pbx board writes to this device one bit at a time.
To facilitate making new i2c devices, i2cBus::write takes care of the low-level details of the i2c protocol. See the I2C Specification [1] for a detailed description of the protocol.
[1] - http://www.nxp.com/documents/user_manual/UM10204.pdf
Implements PioDevice.
Definition at line 89 of file i2cbus.cc.
References currBit, ArmISA::d, devices, Packet::getAddr(), i2cAddr, IDLE, isClockSet(), isEnd(), isStart(), message, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, RECEIVING_ADDR, RECEIVING_DATA, SB_CONTROLC, SB_CONTROLS, sda, SENDING_DATA, state, and updateSignals().
Member Data Documentation
int I2CBus::currBit [protected]
Order of the bit of the current message that is being sent or received (0 - 7).
Definition at line 91 of file i2cbus.hh.
Referenced by serialize(), unserialize(), and write().
std::map<uint8_t, I2CDevice*> I2CBus::devices [protected]
All the slave i2c devices that are connected to this bus.
Each device has an address that points to the actual device.
Definition at line 108 of file i2cbus.hh.
Referenced by I2CBus(), and write().
uint8_t I2CBus::i2cAddr [protected]
Key used to access a device in the slave devices map.
This is the same address that is specified in kernel board initialization code (e.g., arch/arm/mach-realview/core.c).
Definition at line 98 of file i2cbus.hh.
Referenced by serialize(), unserialize(), and write().
uint8_t I2CBus::message [protected]
8-bit buffer used to send and receive messages bit by bit.
Definition at line 101 of file i2cbus.hh.
Referenced by serialize(), unserialize(), and write().
const int I2CBus::SB_CONTROLC = 0x4 [static, protected]
Clear control bits.
Analogous to SB_CONTROLS
Definition at line 74 of file i2cbus.hh.
Referenced by isStart(), updateSignals(), and write().
const int I2CBus::SB_CONTROLS = 0x0 [static, protected]
Read [and Set] serial control bits: Bit [0] is SCL Bit [1] is SDA.
http://infocenter.arm.com/help/topic/com.arm.doc.dui0440b/Bbajdjeg.html
Definition at line 72 of file i2cbus.hh.
Referenced by isClockSet(), isEnd(), read(), updateSignals(), and write().
uint8_t I2CBus::scl [protected]
I2C clock wire (0, 1).
Definition at line 77 of file i2cbus.hh.
Referenced by isEnd(), isStart(), read(), serialize(), unserialize(), and updateSignals().
uint8_t I2CBus::sda [protected]
I2C data wire (0, 1).
Definition at line 79 of file i2cbus.hh.
Referenced by read(), serialize(), unserialize(), updateSignals(), and write().
enum I2CState I2CBus::state [protected]
State used by I2CBus::write to determine what stage of an i2c transmission it is currently in.
Definition at line 85 of file i2cbus.hh.
Referenced by serialize(), unserialize(), and write().
The documentation for this class was generated from the following files:
dev/i2cbus.hh
dev/i2cbus.cc