gem5: Trace::ExeTracerRecord Class Reference
Trace::ExeTracerRecord Class Reference
#include <exetrace.hh>
Public Member Functions
ExeTracerRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
void traceInst (const StaticInstPtr &inst, bool ran)
void dump ()
virtual void dumpTicks (std::ostream &outs)
Detailed Description
Definition at line 47 of file exetrace.hh.
Constructor & Destructor Documentation
Trace::ExeTracerRecord::ExeTracerRecord (Tick _when, ThreadContext * _thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst = NULL) [inline]
Definition at line 50 of file exetrace.hh.
Member Function Documentation
void Trace::ExeTracerRecord::dump () [virtual]
Implements Trace::InstRecord.
Reimplemented in Trace::NativeTraceRecord.
Definition at line 146 of file exetrace.cc.
References Trace::InstRecord::macroStaticInst, Trace::InstRecord::staticInst, and traceInst().
virtual void Trace::ExeTracerRecord::dumpTicks (std::ostream & outs) [virtual]
Referenced by traceInst().
void Trace::ExeTracerRecord::traceInst (const StaticInstPtr & inst, bool ran)
Definition at line 59 of file exetrace.cc.
References Trace::InstRecord::addr, ccprintf(), Trace::InstRecord::cp_seq, Trace::InstRecord::cp_seq_valid, csprintf(), Trace::InstRecord::data, Trace::InstRecord::data_status, Trace::InstRecord::DataInvalid, debugSymbolTable, dumpTicks(), Trace::InstRecord::fetch_seq, Trace::InstRecord::fetch_seq_valid, SymbolTable::findNearestSymbol(), FullSystem, ThreadContext::getCpuPtr(), AlphaISA::getExecutingAsid(), Trace::InstRecord::getMemValid(), AlphaISA::inUserMode(), Trace::output(), Trace::InstRecord::pc, Trace::InstRecord::predicate, Trace::InstRecord::thread, and ThreadContext::threadId().
Referenced by Trace::ArmNativeTrace::check(), and dump().
The documentation for this class was generated from the following files:
cpu/exetrace.hh
cpu/exetrace.cc