gem5: X86ISA::Walker::WalkerState Class Reference
X86ISA::Walker::WalkerState Class Reference
#include <pagetable_walker.hh>
Public Member Functions
WalkerState (Walker *_walker, BaseTLB::Translation *_translation, RequestPtr _req, bool _isFunctional=false)
void initState (ThreadContext *_tc, BaseTLB::Mode _mode, bool _isTiming=false)
Fault startWalk ()
Fault startFunctional (Addr &addr, unsigned &logBytes)
bool recvPacket (PacketPtr pkt)
bool isRetrying ()
bool wasStarted ()
bool isTiming ()
void retry ()
std::string name () const
Protected Attributes
Walker * walker
ThreadContext * tc
RequestPtr req
State state
State nextState
int dataSize
bool enableNX
unsigned inflight
TlbEntry entry
PacketPtr read
std::vector< PacketPtr > writes
Fault timingFault
TLB::Translation * translation
BaseTLB::Mode mode
bool functional
bool timing
bool retrying
bool started
Private Types
enum State {
Ready, Waiting, LongPML4, LongPDP,
LongPD, LongPTE, PAEPDP, PAEPD,
PAEPTE, PSEPD, PD, PTE
}
Private Member Functions
void setupWalk (Addr vaddr)
Fault stepWalk (PacketPtr &write)
void sendPackets ()
void endWalk ()
Fault pageFault (bool present)
Friends
class Walker
Detailed Description
Definition at line 80 of file pagetable_walker.hh.
Member Enumeration Documentation
enum X86ISA::Walker::WalkerState::State [private]
Enumerator:
Ready
Waiting
LongPML4
LongPDP
LongPD
LongPTE
PAEPDP
PAEPD
PAEPTE
PSEPD
PD
PTE
Definition at line 84 of file pagetable_walker.hh.
Constructor & Destructor Documentation
X86ISA::Walker::WalkerState::WalkerState (Walker * _walker, BaseTLB::Translation * _translation, RequestPtr _req, bool _isFunctional = false) [inline]
Definition at line 115 of file pagetable_walker.hh.
Member Function Documentation
void X86ISA::Walker::WalkerState::endWalk () [private]
Definition at line 536 of file pagetable_walker.cc.
References nextState, read, Ready, and Packet::req.
Referenced by stepWalk().
void X86ISA::Walker::WalkerState::initState (ThreadContext * _tc, BaseTLB::Mode _mode, bool _isTiming = false)
Definition at line 179 of file pagetable_walker.cc.
References mode, Ready, started, state, tc, and timing.
Referenced by X86ISA::Walker::start(), and X86ISA::Walker::startFunctional().
bool X86ISA::Walker::WalkerState::isRetrying ()
Definition at line 681 of file pagetable_walker.cc.
References retrying.
Referenced by X86ISA::Walker::recvReqRetry().
bool X86ISA::Walker::WalkerState::isTiming ()
Definition at line 687 of file pagetable_walker.cc.
References timing.
Referenced by X86ISA::Walker::start().
std::string X86ISA::Walker::WalkerState::name () const [inline]
Definition at line 133 of file pagetable_walker.hh.
References SimObject::name(), and walker.
Fault X86ISA::Walker::WalkerState::pageFault (bool present) [private]
Definition at line 706 of file pagetable_walker.cc.
References DPRINTF, enableNX, entry, BaseTLB::Execute, X86ISA::MISCREG_M5_REG, mode, BaseTLB::Read, ThreadContext::readMiscRegNoEffect(), and tc.
Referenced by stepWalk().
bool X86ISA::Walker::WalkerState::recvPacket (PacketPtr pkt)
Definition at line 593 of file pagetable_walker.cc.
References BaseTLB::Translation::finish(), Packet::headerDelay, inflight, Packet::isRead(), Packet::isResponse(), mode, nextState, Packet::payloadDelay, read, Ready, req, sendPackets(), state, stepWalk(), tc, timingFault, X86ISA::Walker::tlb, X86ISA::TLB::translate(), translation, Waiting, walker, and writes.
Referenced by X86ISA::Walker::recvTimingResp().
void X86ISA::Walker::WalkerState::retry ()
Definition at line 699 of file pagetable_walker.cc.
References retrying, and sendPackets().
Referenced by X86ISA::Walker::recvReqRetry().
void X86ISA::Walker::WalkerState::sendPackets () [private]
Definition at line 648 of file pagetable_walker.cc.
References inflight, read, retrying, X86ISA::Walker::sendTiming(), walker, and writes.
Referenced by recvPacket(), retry(), and startWalk().
void X86ISA::Walker::WalkerState::setupWalk (Addr vaddr) [private]
Definition at line 545 of file pagetable_walker.cc.
References X86ISA::addr, Packet::allocate(), dataSize, enableNX, entry, LongPML4, X86ISA::Walker::masterId, X86ISA::MISCREG_CR3, X86ISA::MISCREG_CR4, X86ISA::MISCREG_EFER, nextState, PAEPDP, PD, Request::PHYSICAL, PSEPD, read, ThreadContext::readMiscRegNoEffect(), MemCmd::ReadReq, Ready, Flags< T >::set(), state, tc, Request::UNCACHEABLE, and walker.
Referenced by startFunctional(), and startWalk().
Fault X86ISA::Walker::WalkerState::startFunctional (Addr & addr, unsigned & logBytes)
Definition at line 250 of file pagetable_walker.cc.
References entry, nextState, X86ISA::Walker::port, read, Ready, MasterPort::sendFunctional(), setupWalk(), started, state, stepWalk(), and walker.
Referenced by X86ISA::Walker::startFunctional().
Fault X86ISA::Walker::WalkerState::startWalk ()
Definition at line 221 of file pagetable_walker.cc.
References Request::getVaddr(), nextState, X86ISA::Walker::port, read, Ready, req, MasterPort::sendAtomic(), sendPackets(), setupWalk(), started, state, stepWalk(), timing, timingFault, Waiting, and walker.
Referenced by X86ISA::Walker::start(), and X86ISA::Walker::startWalkWrapper().
Fault X86ISA::Walker::WalkerState::stepWalk (PacketPtr & write) [private]
Definition at line 274 of file pagetable_walker.cc.
References bits(), Packet::cmd, dataSize, DPRINTF, enableNX, endWalk(), entry, BaseTLB::Execute, functional, Packet::get(), Request::getFlags(), Packet::getSize(), X86ISA::TLB::insert(), LongPD, LongPDP, LongPML4, LongPTE, X86ISA::mask, X86ISA::Walker::masterId, mode, nextState, PAEPD, PAEPDP, PAEPTE, pageFault(), panic, PD, PSEPD, PTE, read, MemCmd::ReadReq, Ready, Packet::req, Packet::set(), Flags< T >::set(), state, X86ISA::Walker::tlb, Request::UNCACHEABLE, MipsISA::vaddr, Waiting, walker, and MemCmd::WriteReq.
Referenced by recvPacket(), startFunctional(), and startWalk().
bool X86ISA::Walker::WalkerState::wasStarted ()
Definition at line 693 of file pagetable_walker.cc.
References started.
Referenced by X86ISA::Walker::startWalkWrapper().
Friends And Related Function Documentation
friend class Walker [friend]
Definition at line 82 of file pagetable_walker.hh.
Member Data Documentation
int X86ISA::Walker::WalkerState::dataSize [protected]
Definition at line 101 of file pagetable_walker.hh.
Referenced by setupWalk(), and stepWalk().
bool X86ISA::Walker::WalkerState::enableNX [protected]
Definition at line 102 of file pagetable_walker.hh.
Referenced by pageFault(), setupWalk(), and stepWalk().
TlbEntry X86ISA::Walker::WalkerState::entry [protected]
Definition at line 104 of file pagetable_walker.hh.
Referenced by pageFault(), setupWalk(), startFunctional(), and stepWalk().
bool X86ISA::Walker::WalkerState::functional [protected]
Definition at line 110 of file pagetable_walker.hh.
Referenced by stepWalk().
unsigned X86ISA::Walker::WalkerState::inflight [protected]
Definition at line 103 of file pagetable_walker.hh.
Referenced by recvPacket(), and sendPackets().
BaseTLB::Mode X86ISA::Walker::WalkerState::mode [protected]
Definition at line 109 of file pagetable_walker.hh.
Referenced by initState(), pageFault(), recvPacket(), X86ISA::Walker::startWalkWrapper(), and stepWalk().
State X86ISA::Walker::WalkerState::nextState [protected]
Definition at line 100 of file pagetable_walker.hh.
Referenced by endWalk(), recvPacket(), setupWalk(), startFunctional(), startWalk(), and stepWalk().
PacketPtr X86ISA::Walker::WalkerState::read [protected]
Definition at line 105 of file pagetable_walker.hh.
Referenced by endWalk(), recvPacket(), sendPackets(), setupWalk(), startFunctional(), startWalk(), and stepWalk().
RequestPtr X86ISA::Walker::WalkerState::req [protected]
Definition at line 98 of file pagetable_walker.hh.
Referenced by recvPacket(), startWalk(), and X86ISA::Walker::startWalkWrapper().
bool X86ISA::Walker::WalkerState::retrying [protected]
Definition at line 112 of file pagetable_walker.hh.
Referenced by isRetrying(), retry(), and sendPackets().
bool X86ISA::Walker::WalkerState::started [protected]
Definition at line 113 of file pagetable_walker.hh.
Referenced by initState(), startFunctional(), startWalk(), and wasStarted().
State X86ISA::Walker::WalkerState::state [protected]
Definition at line 99 of file pagetable_walker.hh.
Referenced by initState(), recvPacket(), setupWalk(), startFunctional(), startWalk(), and stepWalk().
ThreadContext* X86ISA::Walker::WalkerState::tc [protected]
Definition at line 97 of file pagetable_walker.hh.
Referenced by initState(), pageFault(), recvPacket(), setupWalk(), and X86ISA::Walker::startWalkWrapper().
bool X86ISA::Walker::WalkerState::timing [protected]
Definition at line 111 of file pagetable_walker.hh.
Referenced by initState(), isTiming(), and startWalk().
Fault X86ISA::Walker::WalkerState::timingFault [protected]
Definition at line 107 of file pagetable_walker.hh.
Referenced by recvPacket(), and startWalk().
TLB::Translation* X86ISA::Walker::WalkerState::translation [protected]
Definition at line 108 of file pagetable_walker.hh.
Referenced by recvPacket(), and X86ISA::Walker::startWalkWrapper().
Walker* X86ISA::Walker::WalkerState::walker [protected]
Definition at line 96 of file pagetable_walker.hh.
Referenced by name(), recvPacket(), sendPackets(), setupWalk(), startFunctional(), startWalk(), and stepWalk().
std::vector<PacketPtr> X86ISA::Walker::WalkerState::writes [protected]
Definition at line 106 of file pagetable_walker.hh.
Referenced by recvPacket(), and sendPackets().
The documentation for this class was generated from the following files:
arch/x86/pagetable_walker.hh
arch/x86/pagetable_walker.cc