gem5: Minor::Fetch2 Class Reference
Minor::Fetch2 Class Reference
This stage receives lines of data from Fetch1, separates them into instructions and passes them to Decode.
#include <fetch2.hh>
Public Member Functions
Fetch2 (const std::string &name, MinorCPU &cpu_, MinorCPUParams &params, Latch< ForwardLineData >::Output inp_, Latch< BranchData >::Output branchInp_, Latch< BranchData >::Input predictionOut_, Latch< ForwardInstData >::Input out_, Reservable &next_stage_input_buffer)
void evaluate ()
Pass on input/buffer data to the output if you can.
void minorTrace () const
bool isDrained ()
Is this stage drained? For Fetch2, draining is initiated by Execute halting Fetch1 causing Fetch2 to naturally drain.
Public Attributes
InputBuffer< ForwardLineData > inputBuffer
Protected Member Functions
const ForwardLineData * getInput ()
Get a piece of data to work on from the inputBuffer, or 0 if there is no data.
void popInput ()
Pop an element off the input buffer, if there are any.
void dumpAllInput ()
Dump the whole contents of the input buffer.
void updateBranchPrediction (const BranchData &branch)
Update local branch prediction structures from feedback from Execute.
void predictBranch (MinorDynInstPtr inst, BranchData &branch)
Predicts branches for the given instruction.
Protected Attributes
MinorCPU & cpu
Pointer back to the containing CPU.
Latch< ForwardLineData >::Output inp
Input port carrying lines from Fetch1.
Latch< BranchData >::Output branchInp
Input port carrying branches from Execute.
Latch< BranchData >::Input predictionOut
Output port carrying predictions back to Fetch1.
Latch< ForwardInstData >::Input out
Output port carrying instructions into Decode.
Reservable & nextStageReserve
Interface to reserve space in the next stage.
unsigned int outputWidth
Width of output of this stage/input of next in instructions.
bool processMoreThanOneInput
If true, more than one input word can be processed each cycle if there is room in the output to contain its processed data.
BPredUnit & branchPredictor
Branch predictor passed from Python configuration.
unsigned int inputIndex
Data members after this line are cycle-to-cycle state.
TheISA::PCState pc
Remembered program counter value.
bool havePC
PC is currently valid.
InstSeqNum lastStreamSeqNum
Stream sequence number of the last seen line used to identify changes of instruction stream.
InstSeqNum fetchSeqNum
Fetch2 is the source of fetch sequence numbers.
InstSeqNum expectedStreamSeqNum
Stream sequence number remembered from last time the predictionSeqNum changed.
InstSeqNum predictionSeqNum
Fetch2 is the source of prediction sequence numbers.
bool blocked
Blocked indication for report.
Detailed Description
This stage receives lines of data from Fetch1, separates them into instructions and passes them to Decode.
Definition at line 61 of file fetch2.hh.
Constructor & Destructor Documentation
Minor::Fetch2::Fetch2 (const std::string & name, MinorCPU & cpu_, MinorCPUParams & params, Latch< ForwardLineData >::Output inp_, Latch< BranchData >::Output branchInp_, Latch< BranchData >::Input predictionOut_, Latch< ForwardInstData >::Input out_, Reservable & next_stage_input_buffer)
Definition at line 54 of file fetch2.cc.
References fatal, and outputWidth.
Member Function Documentation
void Minor::Fetch2::dumpAllInput () [protected]
Dump the whole contents of the input buffer.
Useful after a prediction changes control flow
Definition at line 114 of file fetch2.cc.
References DPRINTF, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), inputBuffer, inputIndex, and popInput().
Referenced by evaluate().
void Minor::Fetch2::evaluate ()
Pass on input/buffer data to the output if you can.
Reserve a slot in the next stage and output data
Definition at line 230 of file fetch2.cc.
References ActivityRecorder::activateStage(), ActivityRecorder::activity(), MinorCPU::activityRecorder, AlphaISA::advancePC(), blocked, branchInp, Minor::Reservable::canReserve(), cpu, DPRINTF, DTRACE, dumpAllInput(), expectedStreamSeqNum, Minor::ForwardLineData::fault, Minor::Pipeline::Fetch2StageId, fetchSeqNum, ThreadContext::getDecoderPtr(), getInput(), BigEndianGuest::gtoh(), havePC, Minor::ForwardLineData::id, inp, inputBuffer, inputIndex, Minor::ForwardInstData::insts, Minor::BranchData::isBubble(), Minor::ForwardInstData::isBubble(), Minor::ForwardLineData::isFault(), Minor::BranchData::isStreamChange(), lastStreamSeqNum, Minor::ForwardLineData::line, Minor::ForwardLineData::lineBaseAddr, Minor::ForwardLineData::lineWidth, nextStageReserve, out, outputWidth, pc, Minor::ForwardLineData::pc, popInput(), predictBranch(), predictionOut, Minor::InstId::predictionSeqNum, predictionSeqNum, processMoreThanOneInput, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::pushTail(), Minor::Reservable::reserve(), Minor::ForwardInstData::resize(), Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::setTail(), Minor::InstId::streamSeqNum, Minor::InstId::threadId, and updateBranchPrediction().
Referenced by Minor::Pipeline::evaluate().
const ForwardLineData * Minor::Fetch2::getInput () [protected]
Get a piece of data to work on from the inputBuffer, or 0 if there is no data.
Definition at line 92 of file fetch2.cc.
References Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::front(), and inputBuffer.
Referenced by evaluate().
bool Minor::Fetch2::isDrained ()
Is this stage drained? For Fetch2, draining is initiated by Execute halting Fetch1 causing Fetch2 to naturally drain.
Branch predictions are ignored by Fetch1 during halt
Definition at line 522 of file fetch2.cc.
References Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), inp, inputBuffer, and predictionOut.
Referenced by Minor::Pipeline::isDrained().
void Minor::Fetch2::minorTrace () const
Definition at line 530 of file fetch2.cc.
References blocked, havePC, inputBuffer, inputIndex, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::minorTrace(), MINORTRACE, out, and predictionSeqNum.
Referenced by Minor::Pipeline::minorTrace().
void Minor::Fetch2::popInput () [protected]
Pop an element off the input buffer, if there are any.
Definition at line 103 of file fetch2.cc.
References Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::ForwardLineData::freeLine(), Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::front(), inputBuffer, inputIndex, and Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::pop().
Referenced by dumpAllInput(), and evaluate().
void Minor::Fetch2::predictBranch (MinorDynInstPtr inst, BranchData & branch) [protected]
Predicts branches for the given instruction.
Updates the instruction's predicted... fields and also the branch which carries the prediction to Fetch1
Definition at line 181 of file fetch2.cc.
References Minor::BranchData::BranchPrediction, branchPredictor, DPRINTF, expectedStreamSeqNum, BPredUnit::predict(), predictionSeqNum, and Minor::BranchData::target.
Referenced by evaluate().
void Minor::Fetch2::updateBranchPrediction (const BranchData & branch) [protected]
Update local branch prediction structures from feedback from Execute.
Definition at line 124 of file fetch2.cc.
References Minor::BranchData::BadlyPredictedBranch, Minor::BranchData::BadlyPredictedBranchTarget, Minor::BranchData::BranchPrediction, branchPredictor, Minor::BranchData::CorrectlyPredictedBranch, DPRINTF, Minor::BranchData::HaltFetch, Minor::BranchData::inst, Minor::BranchData::Interrupt, Minor::BranchData::NoBranch, Minor::BranchData::reason, BPredUnit::squash(), Minor::BranchData::SuspendThread, Minor::BranchData::target, Minor::BranchData::UnpredictedBranch, BPredUnit::update(), and Minor::BranchData::WakeupFetch.
Referenced by evaluate().
Member Data Documentation
bool Minor::Fetch2::blocked [protected]
Blocked indication for report.
Definition at line 137 of file fetch2.hh.
Referenced by evaluate(), and minorTrace().
Latch<BranchData>::Output Minor::Fetch2::branchInp [protected]
Input port carrying branches from Execute.
This is a snoop of the data provided to F1.
Definition at line 72 of file fetch2.hh.
Referenced by evaluate().
BPredUnit& Minor::Fetch2::branchPredictor [protected]
Branch predictor passed from Python configuration.
Definition at line 91 of file fetch2.hh.
Referenced by predictBranch(), and updateBranchPrediction().
MinorCPU& Minor::Fetch2::cpu [protected]
Pointer back to the containing CPU.
Definition at line 65 of file fetch2.hh.
Referenced by evaluate().
InstSeqNum Minor::Fetch2::expectedStreamSeqNum [protected]
Stream sequence number remembered from last time the predictionSeqNum changed.
Lines should only be discarded when their predictionSeqNums disagree with Fetch2::predictionSeqNum *and* they are from the same stream that bore that prediction number
Definition at line 129 of file fetch2.hh.
Referenced by evaluate(), and predictBranch().
InstSeqNum Minor::Fetch2::fetchSeqNum [protected]
Fetch2 is the source of fetch sequence numbers.
These represent the sequence that instructions were extracted from fetched lines.
Definition at line 123 of file fetch2.hh.
Referenced by evaluate().
bool Minor::Fetch2::havePC [protected]
PC is currently valid.
Initially false, gets set to true when a change-of-stream line is received and false again when lines are discarded for any reason
Definition at line 115 of file fetch2.hh.
Referenced by evaluate(), and minorTrace().
Latch<ForwardLineData>::Output Minor::Fetch2::inp [protected]
Input port carrying lines from Fetch1.
Definition at line 68 of file fetch2.hh.
Referenced by evaluate(), and isDrained().
InputBuffer<ForwardLineData> Minor::Fetch2::inputBuffer
Definition at line 95 of file fetch2.hh.
Referenced by dumpAllInput(), evaluate(), getInput(), isDrained(), minorTrace(), and popInput().
unsigned int Minor::Fetch2::inputIndex [protected]
Data members after this line are cycle-to-cycle state.
Index into an incompletely processed input line that instructions are to be extracted from
Definition at line 102 of file fetch2.hh.
Referenced by dumpAllInput(), evaluate(), minorTrace(), and popInput().
InstSeqNum Minor::Fetch2::lastStreamSeqNum [protected]
Stream sequence number of the last seen line used to identify changes of instruction stream.
Definition at line 119 of file fetch2.hh.
Referenced by evaluate().
Reservable& Minor::Fetch2::nextStageReserve [protected]
Interface to reserve space in the next stage.
Definition at line 81 of file fetch2.hh.
Referenced by evaluate().
Latch<ForwardInstData>::Input Minor::Fetch2::out [protected]
Output port carrying instructions into Decode.
Definition at line 78 of file fetch2.hh.
Referenced by evaluate(), and minorTrace().
unsigned int Minor::Fetch2::outputWidth [protected]
Width of output of this stage/input of next in instructions.
Definition at line 84 of file fetch2.hh.
Referenced by evaluate(), and Fetch2().
TheISA::PCState Minor::Fetch2::pc [protected]
Remembered program counter value.
Between contiguous lines, this is just updated with advancePC. For lines following changes of stream, a new PC must be loaded and havePC be set. havePC is needed to accomodate instructions which span across lines meaning that Fetch2 and the decoder need to remember a PC value and a partially-offered instruction from the previous line
Definition at line 110 of file fetch2.hh.
Referenced by evaluate().
Latch<BranchData>::Input Minor::Fetch2::predictionOut [protected]
Output port carrying predictions back to Fetch1.
Definition at line 75 of file fetch2.hh.
Referenced by evaluate(), and isDrained().
InstSeqNum Minor::Fetch2::predictionSeqNum [protected]
Fetch2 is the source of prediction sequence numbers.
These represent predicted changes of control flow sources from branch prediction in Fetch2.
Definition at line 134 of file fetch2.hh.
Referenced by evaluate(), minorTrace(), and predictBranch().
bool Minor::Fetch2::processMoreThanOneInput [protected]
If true, more than one input word can be processed each cycle if there is room in the output to contain its processed data.
Definition at line 88 of file fetch2.hh.
Referenced by evaluate().
The documentation for this class was generated from the following files:
cpu/minor/fetch2.hh
cpu/minor/fetch2.cc