gem5: Minor::Queue< ElemType, ReportTraits, BubbleTraits > Class Template Reference
Minor::Queue< ElemType, ReportTraits, BubbleTraits > Class Template Reference
Wrapper for a queue type to act as a pipeline stage input queue.
#include <buffers.hh>
Public Member Functions
Queue (const std::string &name, const std::string &data_name, unsigned int capacity_)
virtual ~Queue ()
void push (ElemType &data)
Push an element into the buffer if it isn't a bubble.
void clearReservedSpace ()
Clear all allocated space.
void freeReservation ()
Clear a single reserved slot.
void reserve ()
Reserve space in the queue for future pushes.
bool canReserve () const
Can a slot be reserved?
unsigned int totalSpace () const
Number of slots available in an empty buffer.
unsigned int occupiedSpace () const
Number of slots already occupied in this buffer.
unsigned int reservedSpace () const
Number of slots which are reserved.
unsigned int remainingSpace () const
Number of slots yet to fill in this buffer.
unsigned int unreservedRemainingSpace () const
Like remainingSpace but does not count reserved spaces.
ElemType & front ()
Head value.
const ElemType & front () const
void pop ()
Pop the head item.
bool empty () const
Is the queue empty?
void minorTrace () const
Private Attributes
std::deque< ElemType > queue
unsigned int numReservedSlots
Number of slots currently reserved for future (reservation respecting) pushes.
unsigned int capacity
Need this here as queues usually don't have a limited capacity.
std::string dataName
Name to use for the data in MinorTrace.
Detailed Description
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>>
class Minor::Queue< ElemType, ReportTraits, BubbleTraits >
Wrapper for a queue type to act as a pipeline stage input queue.
Handles capacity management, bubble value suppression and provides reporting.
In an ideal world, ElemType would be derived from ReportIF and BubbleIF, but here we use traits and allow the Adaptors ReportTraitsAdaptor and BubbleTraitsAdaptor to work on data which *does* directly implement those interfaces.
Definition at line 392 of file buffers.hh.
Constructor & Destructor Documentation
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> Minor::Queue< ElemType, ReportTraits, BubbleTraits >::Queue (const std::string & name, const std::string & data_name, unsigned int capacity_) [inline]
Definition at line 408 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> virtual Minor::Queue< ElemType, ReportTraits, BubbleTraits >::~Queue () [inline, virtual]
Definition at line 416 of file buffers.hh.
Member Function Documentation
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::Queue< ElemType, ReportTraits, BubbleTraits >::canReserve () const [inline, virtual]
Can a slot be reserved?
Implements Minor::Reservable.
Definition at line 460 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::Queue< ElemType, ReportTraits, BubbleTraits >::clearReservedSpace () [inline]
Clear all allocated space.
Be careful how this is used
Definition at line 438 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty () const [inline]
Is the queue empty?
Definition at line 499 of file buffers.hh.
Referenced by Minor::Execute::commit(), Minor::Fetch1::evaluate(), Minor::Execute::evaluate(), Minor::LSQ::findResponse(), Minor::Execute::instIsHeadInst(), Minor::LSQ::isDrained(), Minor::Execute::isDrained(), Minor::LSQ::moveFromRequestsToTransfers(), Minor::Fetch1::moveFromRequestsToTransfers(), Minor::LSQ::needsToTick(), Minor::Fetch1::popAndDiscard(), Minor::LSQ::popResponse(), Minor::Fetch1::recvReqRetry(), Minor::LSQ::step(), Minor::Fetch1::stepQueues(), Minor::LSQ::tryToSendToTransfers(), and Minor::Fetch1::tryToSendToTransfers().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::Queue< ElemType, ReportTraits, BubbleTraits >::freeReservation () [inline, virtual]
Clear a single reserved slot.
Implements Minor::Reservable.
Definition at line 441 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::push().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> const ElemType& Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front () const [inline]
Definition at line 493 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> ElemType& Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front () [inline]
Head value.
Like std::queue::front
Definition at line 491 of file buffers.hh.
Referenced by Minor::Execute::commit(), Minor::Fetch1::evaluate(), Minor::Execute::evaluate(), Minor::LSQ::findResponse(), Minor::Execute::instIsHeadInst(), Minor::LSQ::moveFromRequestsToTransfers(), Minor::Fetch1::moveFromRequestsToTransfers(), Minor::LSQ::needsToTick(), Minor::Fetch1::popAndDiscard(), Minor::LSQ::popResponse(), Minor::Fetch1::recvReqRetry(), Minor::LSQ::step(), Minor::Fetch1::stepQueues(), Minor::LSQ::tryToSendToTransfers(), and Minor::Fetch1::tryToSendToTransfers().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::Queue< ElemType, ReportTraits, BubbleTraits >::minorTrace () const [inline]
Definition at line 502 of file buffers.hh.
Referenced by Minor::LSQ::minorTrace(), Minor::Fetch1::minorTrace(), and Minor::Execute::minorTrace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::occupiedSpace () const [inline]
Number of slots already occupied in this buffer.
Definition at line 466 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::minorTrace(), and Minor::Fetch1::numInFlightFetches().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::Queue< ElemType, ReportTraits, BubbleTraits >::pop () [inline]
Pop the head item.
Like std::queue::pop
Definition at line 496 of file buffers.hh.
Referenced by Minor::Execute::commit(), Minor::LSQ::moveFromRequestsToTransfers(), Minor::Fetch1::moveFromRequestsToTransfers(), Minor::Fetch1::popAndDiscard(), and Minor::LSQ::popResponse().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::Queue< ElemType, ReportTraits, BubbleTraits >::push (ElemType & data) [inline]
Push an element into the buffer if it isn't a bubble.
Bubbles are just discarded. It is assummed that any push into a queue with reserved space intends to take that space
Definition at line 423 of file buffers.hh.
Referenced by Minor::Fetch1::fetchLine(), Minor::Execute::issue(), Minor::LSQ::moveFromRequestsToTransfers(), Minor::Fetch1::moveFromRequestsToTransfers(), Minor::LSQ::pushFailedRequest(), and Minor::LSQ::pushRequest().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::remainingSpace () const [inline]
Number of slots yet to fill in this buffer.
This doesn't include reservation.
Definition at line 474 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::Queue< ElemType, ReportTraits, BubbleTraits >::reserve () [inline, virtual]
Reserve space in the queue for future pushes.
Enquiries about space in the queue using unreservedRemainingSpace will only tell about space which is not full and not reserved.
Implements Minor::Reservable.
Definition at line 451 of file buffers.hh.
Referenced by Minor::Fetch1::fetchLine().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::reservedSpace () const [inline]
Number of slots which are reserved.
Definition at line 469 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::minorTrace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::totalSpace () const [inline]
Number of slots available in an empty buffer.
Definition at line 463 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::minorTrace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::unreservedRemainingSpace () const [inline]
Like remainingSpace but does not count reserved spaces.
Definition at line 483 of file buffers.hh.
Referenced by Minor::LSQ::canRequest(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::canReserve(), Minor::LSQ::moveFromRequestsToTransfers(), Minor::LSQ::needsToTick(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::reserve(), and Minor::LSQ::tryToSendToTransfers().
Member Data Documentation
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::capacity [private]
Need this here as queues usually don't have a limited capacity.
Definition at line 402 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::push(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::remainingSpace(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::totalSpace(), and Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::unreservedRemainingSpace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> std::string Minor::Queue< ElemType, ReportTraits, BubbleTraits >::dataName [private]
Name to use for the data in MinorTrace.
Definition at line 405 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::minorTrace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::Queue< ElemType, ReportTraits, BubbleTraits >::numReservedSlots [private]
Number of slots currently reserved for future (reservation respecting) pushes.
Definition at line 399 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::clearReservedSpace(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::freeReservation(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::reserve(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::reservedSpace(), and Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::unreservedRemainingSpace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> std::deque<ElemType> Minor::Queue< ElemType, ReportTraits, BubbleTraits >::queue [private]
Definition at line 395 of file buffers.hh.
Referenced by Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::empty(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::front(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::minorTrace(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::occupiedSpace(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::pop(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::push(), Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::remainingSpace(), and Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >::unreservedRemainingSpace().
The documentation for this class was generated from the following file:
cpu/minor/buffers.hh