gem5: LRUProfiler Class Reference
LRUProfiler Class Reference
#include <lru_prof.hh>
Classes
class SamplingEvent
Public Types
typedef LRUProfilerParams Params
Convenience typedef.
Public Member Functions
LRUProfiler (const Params *p)
virtual void startup ()
startup() is the final initialization call before simulation.
virtual void regStats ()
Register local statistics.
virtual BlkType * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
virtual CacheBlk * findVictim (Addr addr)
Find an invalid block to evict for the address provided.
virtual void insertBlock (PacketPtr pkt, BlkType *blk)
Insert the new block into the cache.
virtual void invalidate (BlkType *blk)
Invalidate the given block.
bool should_be_profiled (BlkType *blk) const
void sampling ()
Private Attributes
BaseTagsProfiler * profilers
Tick interval
SamplingEvent * se
Detailed Description
Definition at line 16 of file lru_prof.hh.
Member Typedef Documentation
typedef LRUProfilerParams LRUProfiler::Params
Convenience typedef.
Reimplemented from LRU.
Definition at line 35 of file lru_prof.hh.
Constructor & Destructor Documentation
LRUProfiler::LRUProfiler (const Params * p)
Definition at line 16 of file lru_prof.cc.
References BaseTagsProfiler::add(), ClockedObject::clockEdge(), BaseSetAssoc::getBlockSize(), inform, interval, SimObject::name(), BaseSetAssoc::numSets, profilers, and se.
Member Function Documentation
BaseSetAssoc::BlkType * LRUProfiler::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Reimplemented from LRU.
Definition at line 43 of file lru_prof.cc.
References BaseTagsProfiler::access(), profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, should_be_profiled(), and CacheBlk::tag.
BaseSetAssoc::BlkType * LRUProfiler::findVictim (Addr addr) [virtual]
Find an invalid block to evict for the address provided.
If there are no invalid blocks, this will return the block in the least-recently-used position.
Parameters:
addr The addr to a find a replacement candidate for.
Returns:
The candidate block.
Reimplemented from LRU.
Definition at line 56 of file lru_prof.cc.
References profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, should_be_profiled(), CacheBlk::tag, and BaseTagsProfiler::victim().
void LRUProfiler::insertBlock (PacketPtr pkt, BlkType * blk) [virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Reimplemented from LRU.
Definition at line 69 of file lru_prof.cc.
References BaseTagsProfiler::insert(), profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, and CacheBlk::tag.
void LRUProfiler::invalidate (BlkType * blk) [virtual]
Invalidate the given block.
Parameters:
blk The block to invalidate.
Reimplemented from LRU.
Definition at line 77 of file lru_prof.cc.
References profilers, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, CacheBlk::tag, and BaseTagsProfiler::victim().
void LRUProfiler::regStats () [virtual]
Register local statistics.
Reimplemented from BaseTags.
Definition at line 36 of file lru_prof.cc.
References profilers, and BaseTagsProfiler::regStats().
void LRUProfiler::sampling () [inline]
Definition at line 49 of file lru_prof.hh.
References curTick(), interval, profilers, BaseTagsProfiler::sampling(), EventManager::schedule(), and se.
Referenced by LRUProfiler::SamplingEvent::process().
bool LRUProfiler::should_be_profiled (BlkType * blk) const
Definition at line 86 of file lru_prof.cc.
References CacheBlk::isValid().
Referenced by accessBlock(), and findVictim().
void LRUProfiler::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 30 of file lru_prof.cc.
References curTick(), interval, EventManager::schedule(), and se.
Member Data Documentation
Tick LRUProfiler::interval [private]
Definition at line 20 of file lru_prof.hh.
Referenced by LRUProfiler(), sampling(), and startup().
BaseTagsProfiler* LRUProfiler::profilers [private]
Definition at line 19 of file lru_prof.hh.
Referenced by accessBlock(), findVictim(), insertBlock(), invalidate(), LRUProfiler(), regStats(), and sampling().
SamplingEvent* LRUProfiler::se [private]
Definition at line 33 of file lru_prof.hh.
Referenced by LRUProfiler(), sampling(), and startup().
The documentation for this class was generated from the following files:
mem/cache/tags/lru_prof.hh
mem/cache/tags/lru_prof.cc