gem5: BaseGlobalEvent::BarrierEvent Class Reference
BaseGlobalEvent::BarrierEvent Class Reference
The base class for the local events that will synchronize threads to perform the global event.
#include <global_event.hh>
Public Member Functions
virtual BaseGlobalEvent * globalEvent ()
If this is part of a GlobalEvent, return the pointer to the Global Event.
Protected Member Functions
BarrierEvent (BaseGlobalEvent *global_event, Priority p, Flags f)
~BarrierEvent ()
bool globalBarrier ()
Protected Attributes
BaseGlobalEvent * _globalEvent
Friends
class BaseGlobalEvent
Detailed Description
The base class for the local events that will synchronize threads to perform the global event.
This class is abstract, since it derives from the abstract Event class but still does not define the required process() method.
Definition at line 78 of file global_event.hh.
Constructor & Destructor Documentation
BaseGlobalEvent::BarrierEvent::BarrierEvent (BaseGlobalEvent * global_event, Priority p, Flags f) [inline, protected]
Definition at line 83 of file global_event.hh.
BaseGlobalEvent::BarrierEvent::~BarrierEvent () [protected]
Definition at line 112 of file global_event.cc.
References _globalEvent, EventBase::AutoDelete, BaseGlobalEvent::barrierEvent, and Event::isFlagSet().
Member Function Documentation
bool BaseGlobalEvent::BarrierEvent::globalBarrier () [inline, protected]
Definition at line 92 of file global_event.hh.
References _globalEvent, BaseGlobalEvent::barrier, curEventQueue(), and Barrier::wait().
Referenced by GlobalSyncEvent::BarrierEvent::process(), and GlobalEvent::BarrierEvent::process().
virtual BaseGlobalEvent* BaseGlobalEvent::BarrierEvent::globalEvent () [inline, virtual]
If this is part of a GlobalEvent, return the pointer to the Global Event.
By default, there is no GlobalEvent, so return NULL. (Overridden in GlobalEvent::BarrierEvent.)
Reimplemented from Event.
Definition at line 107 of file global_event.hh.
References _globalEvent.
Friends And Related Function Documentation
friend class BaseGlobalEvent [friend]
Definition at line 90 of file global_event.hh.
Member Data Documentation
BaseGlobalEvent* BaseGlobalEvent::BarrierEvent::_globalEvent [protected]
Definition at line 81 of file global_event.hh.
Referenced by globalBarrier(), globalEvent(), GlobalSyncEvent::BarrierEvent::process(), GlobalEvent::BarrierEvent::process(), and ~BarrierEvent().
The documentation for this class was generated from the following files:
sim/global_event.hh
sim/global_event.cc