gem5: Bitmap Class Reference
Bitmap Class Reference
#include <bitmap.hh>
Classes
struct BmpPixel32
struct CompleteV1Header
struct FileHeader
struct InfoHeaderV1
Public Member Functions
Bitmap (const FrameBuffer *fb)
Create a bitmap that takes data in a given mode & size and outputs to an ostream.
~Bitmap ()
void write (std::ostream &bmp) const
Write the frame buffer data into the provided ostream.
Private Types
typedef BmpPixel32 PixelType
Private Member Functions
const CompleteV1Header getCompleteHeader () const
Private Attributes
struct Bitmap::FileHeader M5_ATTR_PACKED
struct Bitmap::InfoHeaderV1 M5_ATTR_PACKED
struct Bitmap::CompleteV1Header M5_ATTR_PACKED
struct Bitmap::BmpPixel32 M5_ATTR_PACKED
const FrameBuffer & fb
Detailed Description
Definition at line 56 of file bitmap.hh.
Member Typedef Documentation
typedef BmpPixel32 Bitmap::PixelType [private]
Definition at line 118 of file bitmap.hh.
Constructor & Destructor Documentation
Bitmap::Bitmap (const FrameBuffer * fb)
Create a bitmap that takes data in a given mode & size and outputs to an ostream.
Definition at line 50 of file bitmap.cc.
Bitmap::~Bitmap ()
Definition at line 55 of file bitmap.cc.
Member Function Documentation
const Bitmap::CompleteV1Header Bitmap::getCompleteHeader () const [private]
Definition at line 60 of file bitmap.cc.
References FrameBuffer::area(), fb, FrameBuffer::height(), and FrameBuffer::width().
Referenced by write().
void Bitmap::write (std::ostream & bmp) const
Write the frame buffer data into the provided ostream.
Parameters:
bmp stream to write to
Definition at line 93 of file bitmap.cc.
References fb, getCompleteHeader(), FrameBuffer::height(), FrameBuffer::pixel(), FrameBuffer::width(), and X86ISA::x.
Referenced by Pl111::dmaDone(), and HDLcd::endFrame().
Member Data Documentation
const FrameBuffer& Bitmap::fb [private]
Definition at line 122 of file bitmap.hh.
Referenced by getCompleteHeader(), and write().
struct Bitmap::BmpPixel32 Bitmap::M5_ATTR_PACKED [private]
struct Bitmap::CompleteV1Header Bitmap::M5_ATTR_PACKED [private]
struct Bitmap::InfoHeaderV1 Bitmap::M5_ATTR_PACKED [private]
struct Bitmap::FileHeader Bitmap::M5_ATTR_PACKED [private]
The documentation for this class was generated from the following files:
base/bitmap.hh
base/bitmap.cc