gem5: DIP Class Reference
DIP Class Reference
#include <dip.hh>
Public Types
typedef DIPParams Params
Convenience typedef.
Public Member Functions
DIP (const Params *p)
Construct and initialize this tag store.
~DIP ()
Destructor.
virtual void checkConstituency ()
virtual unsigned int getConstituencyID (int set)
virtual unsigned int getConstituencyOffset (int set)
virtual bool isDedicatedLRU (int set)
virtual bool isDedicatedBIP (int set)
virtual void setSampling (BlkType *blk, int set)
virtual BlkType * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
virtual void insertBlock (PacketPtr pkt, BlkType *blk)
Insert the new block into the cache.
virtual void insertBlock_bip (PacketPtr pkt, BlkType *blk)
virtual void insertBlock_lru (PacketPtr pkt, BlkType *blk)
virtual void regStats ()
Register local statistics.
Public Attributes
Stats::Formula num_dedicated_sets
Stats::Formula num_all_dedicated_sets
Private Attributes
PolicySelector psel
unsigned int numDedicatedSets
unsigned int numAllDedicatedSets
unsigned int numSetsInConstituency
Detailed Description
Definition at line 15 of file dip.hh.
Member Typedef Documentation
typedef DIPParams DIP::Params
Convenience typedef.
Reimplemented from BIP.
Definition at line 26 of file dip.hh.
Constructor & Destructor Documentation
DIP::DIP (const Params * p)
Construct and initialize this tag store.
Definition at line 10 of file dip.cc.
References checkConstituency(), inform, SimObject::name(), numAllDedicatedSets, numDedicatedSets, BaseSetAssoc::numSets, and numSetsInConstituency.
DIP::~DIP () [inline]
Destructor.
Definition at line 42 of file dip.hh.
Member Function Documentation
BaseSetAssoc::BlkType * DIP::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Reimplemented from LRU.
Definition at line 121 of file dip.cc.
References DPRINTF, BaseSetAssoc::extractSet(), CacheSet< Blktype >::moveToHead(), BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, BaseSetAssoc::sets, setSampling(), and CacheBlk::tag.
void DIP::checkConstituency () [virtual]
Definition at line 22 of file dip.cc.
References fatal, ArmISA::i, inform, isDedicatedBIP(), isDedicatedLRU(), numAllDedicatedSets, and BaseSetAssoc::numSets.
Referenced by DIP().
unsigned int DIP::getConstituencyID (int set) [virtual]
Definition at line 68 of file dip.cc.
References numSetsInConstituency.
Referenced by isDedicatedBIP(), and isDedicatedLRU().
unsigned int DIP::getConstituencyOffset (int set) [virtual]
Definition at line 74 of file dip.cc.
References numSetsInConstituency.
Referenced by isDedicatedBIP(), and isDedicatedLRU().
void DIP::insertBlock (PacketPtr pkt, BlkType * blk) [virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Reimplemented from BIP.
Definition at line 162 of file dip.cc.
References BIP::all_insertions, BaseSetAssoc::extractSet(), Packet::getAddr(), insertBlock_bip(), insertBlock_lru(), isDedicatedBIP(), isDedicatedLRU(), PolicySelector::isOver(), and psel.
void DIP::insertBlock_bip (PacketPtr pkt, BlkType * blk) [virtual]
Definition at line 139 of file dip.cc.
References BIP::epsilon_counter, BIP::epsilon_denominator, BIP::epsilon_numerator, BaseSetAssoc::extractSet(), Packet::getAddr(), CacheSet< Blktype >::moveToHead(), BIP::mru_insertions, and BaseSetAssoc::sets.
Referenced by insertBlock().
void DIP::insertBlock_lru (PacketPtr pkt, BlkType * blk) [virtual]
Definition at line 154 of file dip.cc.
References BaseSetAssoc::extractSet(), Packet::getAddr(), CacheSet< Blktype >::moveToHead(), BIP::mru_insertions, and BaseSetAssoc::sets.
Referenced by insertBlock().
bool DIP::isDedicatedBIP (int set) [virtual]
Definition at line 95 of file dip.cc.
References getConstituencyID(), getConstituencyOffset(), numSetsInConstituency, and ArmISA::offset.
Referenced by checkConstituency(), insertBlock(), and setSampling().
bool DIP::isDedicatedLRU (int set) [virtual]
Definition at line 80 of file dip.cc.
References getConstituencyID(), getConstituencyOffset(), numSetsInConstituency, and ArmISA::offset.
Referenced by checkConstituency(), insertBlock(), and setSampling().
void DIP::regStats () [virtual]
Register local statistics.
Reimplemented from BIP.
Definition at line 47 of file dip.cc.
References SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), num_all_dedicated_sets, num_dedicated_sets, numAllDedicatedSets, numDedicatedSets, psel, and PolicySelector::regStats().
void DIP::setSampling (BlkType * blk, int set) [virtual]
Definition at line 110 of file dip.cc.
References PolicySelector::decrement(), PolicySelector::increment(), isDedicatedBIP(), isDedicatedLRU(), and psel.
Referenced by accessBlock().
Member Data Documentation
Stats::Formula DIP::num_all_dedicated_sets
Definition at line 32 of file dip.hh.
Referenced by regStats().
Stats::Formula DIP::num_dedicated_sets
Definition at line 31 of file dip.hh.
Referenced by regStats().
unsigned int DIP::numAllDedicatedSets [private]
Definition at line 21 of file dip.hh.
Referenced by checkConstituency(), DIP(), and regStats().
unsigned int DIP::numDedicatedSets [private]
Definition at line 20 of file dip.hh.
Referenced by DIP(), and regStats().
unsigned int DIP::numSetsInConstituency [private]
Definition at line 22 of file dip.hh.
Referenced by DIP(), getConstituencyID(), getConstituencyOffset(), isDedicatedBIP(), and isDedicatedLRU().
PolicySelector DIP::psel [private]
Definition at line 19 of file dip.hh.
Referenced by insertBlock(), regStats(), and setSampling().
The documentation for this class was generated from the following files:
mem/cache/tags/dip.hh
mem/cache/tags/dip.cc