gem5: LinkDelayEvent Class Reference
LinkDelayEvent Class Reference
Public Member Functions
LinkDelayEvent ()
LinkDelayEvent (EtherLink::Link *link, EthPacketPtr pkt)
void process ()
virtual void serialize (ostream &os)
void unserialize (Checkpoint *cp, const string &section)
void unserialize (Checkpoint *cp, const string &section, EventQueue *eventq)
Static Public Member Functions
static Serializable * createForUnserialize (Checkpoint *cp, const string &section)
Protected Attributes
EtherLink::Link * link
EthPacketPtr packet
Detailed Description
Definition at line 131 of file etherlink.cc.
Constructor & Destructor Documentation
LinkDelayEvent::LinkDelayEvent ()
Definition at line 232 of file etherlink.cc.
Referenced by createForUnserialize().
LinkDelayEvent::LinkDelayEvent (EtherLink::Link * link, EthPacketPtr pkt)
Definition at line 237 of file etherlink.cc.
Member Function Documentation
Serializable * LinkDelayEvent::createForUnserialize (Checkpoint * cp, const string & section) [static]
Definition at line 282 of file etherlink.cc.
References LinkDelayEvent().
void LinkDelayEvent::process () [virtual]
Implements Event.
Definition at line 243 of file etherlink.cc.
References link, packet, and EtherLink::Link::txComplete().
void LinkDelayEvent::serialize (ostream & os) [virtual]
Definition at line 249 of file etherlink.cc.
References link, EtherLink::Link::number, packet, paramOut(), EtherLink::Link::parent, SERIALIZE_OBJPTR, and SERIALIZE_SCALAR.
void LinkDelayEvent::unserialize (Checkpoint * cp, const string & section, EventQueue * eventq)
Definition at line 264 of file etherlink.cc.
References EtherLink::link, link, packet, unserialize(), UNSERIALIZE_OBJPTR, and UNSERIALIZE_SCALAR.
void LinkDelayEvent::unserialize (Checkpoint * cp, const string & section) [inline]
Definition at line 145 of file etherlink.cc.
Referenced by unserialize().
Member Data Documentation
EtherLink::Link* LinkDelayEvent::link [protected]
Definition at line 134 of file etherlink.cc.
Referenced by process(), serialize(), and unserialize().
EthPacketPtr LinkDelayEvent::packet [protected]
Definition at line 135 of file etherlink.cc.
Referenced by process(), serialize(), and unserialize().
The documentation for this class was generated from the following file:
dev/etherlink.cc