gem5: DmaPort Class Reference
DmaPort Class Reference
#include <dma_device.hh>
Classes
struct DmaReqState
Public Member Functions
DmaPort (MemObject *dev, System *s)
RequestPtr dmaAction (Packet::Command cmd, Addr addr, int size, Event *event, uint8_t *data, Tick delay, Request::Flags flag=0)
bool dmaPending () const
unsigned int drain (DrainManager *drainManger)
Protected Member Functions
bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
void queueDma (PacketPtr pkt)
Private Member Functions
void trySendTimingReq ()
Take the first packet of the transmit list and attempt to send it as a timing request.
void sendDma ()
For timing, attempt to send the first item on the transmit list, and if it is successful and there are more packets waiting, then schedule the sending of the next packet.
void handleResp (PacketPtr pkt, Tick delay=0)
Handle a response packet by updating the corresponding DMA request state to reflect the bytes received, and also update the pending request counter.
Private Attributes
MemObject * device
The device that owns this port.
std::deque< PacketPtr > transmitList
Use a deque as we never do any insertion or removal in the middle.
EventWrapper< DmaPort,&DmaPort::sendDma > sendEvent
Event used to schedule a future sending from the transmit list.
System * sys
The system that device/port are in.
const MasterID masterId
Id for all requests.
uint32_t pendingCount
Number of outstanding packets the dma port has.
DrainManager * drainManager
If we need to drain, keep the drain event around until we're done here.
bool inRetry
If the port is currently waiting for a retry before it can send whatever it is that it's sending.
Detailed Description
Definition at line 54 of file dma_device.hh.
Constructor & Destructor Documentation
DmaPort::DmaPort (MemObject * dev, System * s)
Definition at line 51 of file dma_device.cc.
Member Function Documentation
RequestPtr DmaPort::dmaAction (Packet::Command cmd, Addr addr, int size, Event * event, uint8_t * data, Tick delay, Request::Flags flag = 0)
Definition at line 157 of file dma_device.cc.
References System::cacheLineSize(), Packet::dataStatic(), ContextSwitchTaskId::DMA, DPRINTF, masterId, queueDma(), Event::scheduled(), sendDma(), Packet::senderState, sys, and Request::taskId().
Referenced by DmaDevice::dmaRead(), DmaDevice::dmaWrite(), CopyEngine::CopyEngineChannel::fetchDescriptor(), ArmISA::TableWalker::fetchDescriptor(), CopyEngine::CopyEngineChannel::fetchNextAddr(), Pl111::fillFifo(), HDLcd::fillPixelBuffer(), ArmISA::Stage2MMU::Stage2Translation::finish(), ArmISA::TableWalker::processWalkAArch64(), CopyEngine::CopyEngineChannel::readCopyBytes(), UFSHostDevice::readDevice(), CopyEngine::CopyEngineChannel::writeCompletionStatus(), CopyEngine::CopyEngineChannel::writeCopyBytes(), and UFSHostDevice::writeDevice().
bool DmaPort::dmaPending () const [inline]
Definition at line 148 of file dma_device.hh.
References pendingCount.
Referenced by DmaDevice::dmaPending().
unsigned int DmaPort::drain (DrainManager * drainManger)
Definition at line 140 of file dma_device.cc.
References DPRINTF, drainManager, and pendingCount.
Referenced by PciDevice::drain(), IGbE::drain(), DmaDevice::drain(), CopyEngine::drain(), CopyEngine::CopyEngineChannel::drain(), UFSHostDevice::drain(), and ArmISA::Stage2MMU::drain().
void DmaPort::handleResp (PacketPtr pkt, Tick delay = 0) [private]
Handle a response packet by updating the corresponding DMA request state to reflect the bytes received, and also update the pending request counter.
If the DMA request that this packet is part of is complete, then signal the completion event if present, potentially with a delay added to it.
Parameters:
pkt Response packet to handler
delay Additional delay for scheduling the completion event
Definition at line 59 of file dma_device.cc.
References Packet::cmdString(), curTick(), device, ContextSwitchTaskId::DMA, DPRINTF, drainManager, Packet::getAddr(), Request::getSize(), Packet::isResponse(), pendingCount, Packet::req, EventManager::schedule(), Packet::senderState, and DrainManager::signalDrainDone().
Referenced by recvTimingResp(), and sendDma().
void DmaPort::queueDma (PacketPtr pkt) [protected]
Definition at line 199 of file dma_device.cc.
References pendingCount, and transmitList.
Referenced by dmaAction().
void DmaPort::recvReqRetry () [protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 150 of file dma_device.cc.
References transmitList, and trySendTimingReq().
bool DmaPort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 105 of file dma_device.cc.
References handleResp(), Request::isUncacheable(), Packet::memInhibitAsserted(), Packet::req, and Packet::sharedAsserted().
void DmaPort::sendDma () [private]
For timing, attempt to send the first item on the transmit list, and if it is successful and there are more packets waiting, then schedule the sending of the next packet.
For atomic, simply send and process everything on the transmit list.
Definition at line 238 of file dma_device.cc.
References ContextSwitchTaskId::DMA, DPRINTF, Request::getPaddr(), Request::getSize(), handleResp(), inRetry, System::isAtomicMode(), System::isTimingMode(), panic, Packet::req, Event::scheduled(), MasterPort::sendAtomic(), sendEvent, sys, transmitList, and trySendTimingReq().
Referenced by dmaAction().
void DmaPort::trySendTimingReq () [private]
Take the first packet of the transmit list and attempt to send it as a timing request.
If it is successful, schedule the sending of the next packet, otherwise remember that we are waiting for a retry.
Definition at line 209 of file dma_device.cc.
References ClockedObject::clockEdge(), Packet::cmdString(), device, ContextSwitchTaskId::DMA, DPRINTF, Packet::getAddr(), inRetry, EventManager::schedule(), sendEvent, MasterPort::sendTimingReq(), and transmitList.
Referenced by recvReqRetry(), and sendDma().
Member Data Documentation
MemObject* DmaPort::device [private]
The device that owns this port.
Definition at line 108 of file dma_device.hh.
Referenced by handleResp(), and trySendTimingReq().
DrainManager* DmaPort::drainManager [private]
If we need to drain, keep the drain event around until we're done here.
Definition at line 128 of file dma_device.hh.
Referenced by drain(), and handleResp().
bool DmaPort::inRetry [private]
If the port is currently waiting for a retry before it can send whatever it is that it's sending.
Definition at line 132 of file dma_device.hh.
Referenced by sendDma(), and trySendTimingReq().
const MasterID DmaPort::masterId [private]
Id for all requests.
Definition at line 121 of file dma_device.hh.
Referenced by dmaAction().
uint32_t DmaPort::pendingCount [private]
Number of outstanding packets the dma port has.
Definition at line 124 of file dma_device.hh.
Referenced by dmaPending(), drain(), handleResp(), and queueDma().
EventWrapper<DmaPort, &DmaPort::sendDma> DmaPort::sendEvent [private]
Event used to schedule a future sending from the transmit list.
Definition at line 114 of file dma_device.hh.
Referenced by sendDma(), and trySendTimingReq().
System* DmaPort::sys [private]
The system that device/port are in.
This is used to select which mode we are currently operating in.
Definition at line 118 of file dma_device.hh.
Referenced by dmaAction(), and sendDma().
std::deque<PacketPtr> DmaPort::transmitList [private]
Use a deque as we never do any insertion or removal in the middle.
Definition at line 111 of file dma_device.hh.
Referenced by queueDma(), recvReqRetry(), sendDma(), and trySendTimingReq().
The documentation for this class was generated from the following files:
dev/dma_device.hh
dev/dma_device.cc