gem5: BaseSlavePort Class Reference
BaseSlavePort Class Reference
A BaseSlavePort is a protocol-agnostic slave port, responsible only for the structural connection to a master port.
#include <port.hh>
Public Member Functions
BaseMasterPort & getMasterPort () const
bool isConnected () const
Protected Member Functions
BaseSlavePort (const std::string &name, MemObject *owner, PortID id=InvalidPortID)
virtual ~BaseSlavePort ()
Protected Attributes
BaseMasterPort * _baseMasterPort
Detailed Description
A BaseSlavePort is a protocol-agnostic slave port, responsible only for the structural connection to a master port.
Definition at line 139 of file port.hh.
Constructor & Destructor Documentation
BaseSlavePort::BaseSlavePort (const std::string & name, MemObject * owner, PortID id = InvalidPortID) [protected]
Definition at line 88 of file port.cc.
BaseSlavePort::~BaseSlavePort () [protected, virtual]
Definition at line 94 of file port.cc.
Member Function Documentation
BaseMasterPort & BaseSlavePort::getMasterPort () const
Definition at line 99 of file port.cc.
References _baseMasterPort, Port::name(), and panic.
Referenced by MessageSlavePort::recvAtomic().
bool BaseSlavePort::isConnected () const
Definition at line 109 of file port.cc.
References _baseMasterPort.
Referenced by CxxConfigManager::bindPort(), SimpleMemory::init(), MemCheckerMonitor::init(), ExternalSlave::init(), DRAMSim2::init(), DRAMCtrl::init(), CommMonitor::init(), Bridge::init(), AddrMapper::init(), PciDevice::init(), PioDevice::init(), and BaseCache::init().
Member Data Documentation
BaseMasterPort* BaseSlavePort::_baseMasterPort [protected]
Definition at line 144 of file port.hh.
Referenced by SlavePort::bind(), getMasterPort(), isConnected(), and SlavePort::unbind().
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc