gem5: Minor::Reservable Class Reference
Minor::Reservable Class Reference
Base class for space reservation requestable objects.
#include <buffers.hh>
Public Member Functions
virtual bool canReserve () const =0
Can a slot be reserved?
virtual void reserve ()=0
Reserve a slot in whatever structure this is attached to.
virtual void freeReservation ()=0
Free a reserved slot.
Detailed Description
Base class for space reservation requestable objects.
Definition at line 368 of file buffers.hh.
Member Function Documentation
virtual bool Minor::Reservable::canReserve () const [pure virtual]
Can a slot be reserved?
Implemented in Minor::Queue< ElemType, ReportTraits, BubbleTraits >, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >, Minor::Queue< ForwardInstData, ReportTraitsAdaptor< ForwardInstData >, BubbleTraitsAdaptor< ForwardInstData > >, Minor::Queue< QueuedInst, ReportTraitsAdaptor< QueuedInst > >, Minor::Queue< ForwardLineData, ReportTraitsAdaptor< ForwardLineData >, BubbleTraitsAdaptor< ForwardLineData > >, Minor::Queue< FetchRequestPtr, ReportTraitsPtrAdaptor< FetchRequestPtr >, NoBubbleTraits< FetchRequestPtr > >, Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >, Minor::InputBuffer< ForwardLineData >, and Minor::InputBuffer< ForwardInstData >.
Referenced by Minor::Fetch2::evaluate(), Minor::Fetch1::evaluate(), and Minor::Decode::evaluate().
virtual void Minor::Reservable::freeReservation () [pure virtual]
Free a reserved slot.
Implemented in Minor::Queue< ElemType, ReportTraits, BubbleTraits >, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >, Minor::Queue< ForwardInstData, ReportTraitsAdaptor< ForwardInstData >, BubbleTraitsAdaptor< ForwardInstData > >, Minor::Queue< QueuedInst, ReportTraitsAdaptor< QueuedInst > >, Minor::Queue< ForwardLineData, ReportTraitsAdaptor< ForwardLineData >, BubbleTraitsAdaptor< ForwardLineData > >, Minor::Queue< FetchRequestPtr, ReportTraitsPtrAdaptor< FetchRequestPtr >, NoBubbleTraits< FetchRequestPtr > >, Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >, Minor::InputBuffer< ForwardLineData >, and Minor::InputBuffer< ForwardInstData >.
Referenced by Minor::Fetch1::evaluate().
virtual void Minor::Reservable::reserve () [pure virtual]
Reserve a slot in whatever structure this is attached to.
Implemented in Minor::Queue< ElemType, ReportTraits, BubbleTraits >, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >, Minor::Queue< ForwardInstData, ReportTraitsAdaptor< ForwardInstData >, BubbleTraitsAdaptor< ForwardInstData > >, Minor::Queue< QueuedInst, ReportTraitsAdaptor< QueuedInst > >, Minor::Queue< ForwardLineData, ReportTraitsAdaptor< ForwardLineData >, BubbleTraitsAdaptor< ForwardLineData > >, Minor::Queue< FetchRequestPtr, ReportTraitsPtrAdaptor< FetchRequestPtr >, NoBubbleTraits< FetchRequestPtr > >, Minor::Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > >, Minor::InputBuffer< ForwardLineData >, and Minor::InputBuffer< ForwardInstData >.
Referenced by Minor::Fetch2::evaluate(), Minor::Fetch1::evaluate(), and Minor::Decode::evaluate().
The documentation for this class was generated from the following file:
cpu/minor/buffers.hh