gem5: DRAMCtrl::MemoryPort Class Reference
DRAMCtrl::MemoryPort Class Reference
Public Member Functions
MemoryPort (const std::string &name, DRAMCtrl &_memory)
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
bool recvTimingReq (PacketPtr)
Receive a timing request from the master port.
virtual AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Private Attributes
RespPacketQueue queue
DRAMCtrl & memory
Detailed Description
Definition at line 95 of file dram_ctrl.hh.
Constructor & Destructor Documentation
DRAMCtrl::MemoryPort::MemoryPort (const std::string & name, DRAMCtrl & _memory)
Definition at line 2242 of file dram_ctrl.cc.
Member Function Documentation
AddrRangeList DRAMCtrl::MemoryPort::getAddrRanges () const [protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 2248 of file dram_ctrl.cc.
References AbstractMemory::getAddrRange(), and memory.
Tick DRAMCtrl::MemoryPort::recvAtomic (PacketPtr pkt) [protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 2271 of file dram_ctrl.cc.
References memory, and DRAMCtrl::recvAtomic().
void DRAMCtrl::MemoryPort::recvFunctional (PacketPtr pkt) [protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 2256 of file dram_ctrl.cc.
References PacketQueue::checkFunctional(), memory, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), queue, and DRAMCtrl::recvFunctional().
bool DRAMCtrl::MemoryPort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 2277 of file dram_ctrl.cc.
References memory, and DRAMCtrl::recvTimingReq().
Member Data Documentation
DRAMCtrl& DRAMCtrl::MemoryPort::memory [private]
Definition at line 99 of file dram_ctrl.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), and recvTimingReq().
RespPacketQueue DRAMCtrl::MemoryPort::queue [private]
Definition at line 98 of file dram_ctrl.hh.
Referenced by recvFunctional().
The documentation for this class was generated from the following files:
mem/dram_ctrl.hh
mem/dram_ctrl.cc