gem5: MSHR::TargetList Class Reference
MSHR::TargetList Class Reference
#include <mshr.hh>
Public Member Functions
TargetList ()
void resetFlags ()
bool isReset () const
void add (PacketPtr pkt, Tick readyTime, Counter order, Target::Source source, bool markPending)
void replaceUpgrades ()
void clearDownstreamPending ()
bool checkFunctional (PacketPtr pkt)
void print (std::ostream &os, int verbosity, const std::string &prefix) const
Public Attributes
bool needsExclusive
bool hasUpgrade
Detailed Description
Definition at line 118 of file mshr.hh.
Constructor & Destructor Documentation
MSHR::TargetList::TargetList ()
Definition at line 74 of file mshr.cc.
Member Function Documentation
void MSHR::TargetList::add (PacketPtr pkt, Tick readyTime, Counter order, Target::Source source, bool markPending) [inline]
Definition at line 80 of file mshr.cc.
References Packet::cmd, MSHR::downstreamPending, Packet::findNextSenderState(), MSHR::Target::FromSnoop, hasUpgrade, Packet::isUpgrade(), needsExclusive, Packet::needsExclusive(), and MemCmd::StoreCondReq.
Referenced by MSHR::allocate(), MSHR::allocateTarget(), and MSHR::handleSnoop().
bool MSHR::TargetList::checkFunctional (PacketPtr pkt)
Definition at line 162 of file mshr.cc.
References Packet::checkFunctional(), and ArmISA::t.
Referenced by MSHR::checkFunctional().
void MSHR::TargetList::clearDownstreamPending ()
Definition at line 142 of file mshr.cc.
References MSHR::clearDownstreamPending(), and ArmISA::t.
Referenced by MSHR::clearDownstreamPending(), MSHR::handleFill(), and MSHR::markInService().
bool MSHR::TargetList::isReset () const [inline]
Definition at line 126 of file mshr.hh.
References hasUpgrade, and needsExclusive.
Referenced by MSHR::allocate(), and MSHR::deallocate().
void MSHR::TargetList::print (std::ostream & os, int verbosity, const std::string & prefix) const
Definition at line 175 of file mshr.cc.
References ccprintf(), MSHR::Target::FromCPU, MSHR::Target::FromPrefetcher, MSHR::Target::FromSnoop, ArmISA::s, and ArmISA::t.
Referenced by MSHR::print().
void MSHR::TargetList::replaceUpgrades ()
Definition at line 128 of file mshr.cc.
References hasUpgrade, replaceUpgrade(), and ArmISA::t.
Referenced by MSHR::handleSnoop().
void MSHR::TargetList::resetFlags () [inline]
Definition at line 125 of file mshr.hh.
References hasUpgrade, and needsExclusive.
Referenced by MSHR::deallocate(), MSHR::handleFill(), and MSHR::promoteDeferredTargets().
Member Data Documentation
bool MSHR::TargetList::hasUpgrade
Definition at line 122 of file mshr.hh.
Referenced by add(), isReset(), replaceUpgrades(), and resetFlags().
bool MSHR::TargetList::needsExclusive
Definition at line 121 of file mshr.hh.
Referenced by add(), MSHR::handleFill(), MSHR::handleSnoop(), isReset(), MSHR::markInService(), MSHR::needsExclusive(), and resetFlags().
The documentation for this class was generated from the following files:
mem/cache/mshr.hh
mem/cache/mshr.cc