gem5: Minor::FUPipeline Class Reference
Minor::FUPipeline Class Reference
A functional unit configured from a MinorFU object.
#include <func_unit.hh>
Public Member Functions
FUPipeline (const std::string &name, const MinorFU &description_, ClockedObject &timeSource_)
Cycles cyclesBeforeInsert ()
How many cycles must from curCycle before insertion into the pipeline is allowed.
bool canInsert () const
Can an instruction be inserted now?
MinorFUTiming * findTiming (const StaticInstPtr &inst)
Find the extra timing information for this instruction.
void advance ()
Step the pipeline.
Public Attributes
const MinorFU & description
Functional unit description that this pipeline implements.
ClockedObject & timeSource
An FUPipeline needs access to curCycle, use this timing source.
std::bitset< Num_OpClasses > capabilityList
Set of operation classes supported by this FU.
std::vector< bool > cantForwardFromFUIndices
FUs which this pipeline can't receive a forwarded (i.e.
Cycles nextInsertCycle
When can a new instruction be inserted into the pipeline? This is an absolute cycle time unless it is 0 in which case the an instruction can be pushed straightaway.
Detailed Description
A functional unit configured from a MinorFU object.
Definition at line 224 of file func_unit.hh.
Constructor & Destructor Documentation
Minor::FUPipeline::FUPipeline (const std::string & name, const MinorFU & description_, ClockedObject & timeSource_)
Definition at line 112 of file func_unit.cc.
References FuncUnit::addCapability(), cantForwardFromFUIndices, MinorFU::cantForwardFromFUIndices, description, DPRINTFS, DTRACE, ArmISA::i, ArmISA::j, MinorFUTiming::mask, MinorFUTiming::match, MinorOpClassSet::opClasses, MinorFU::opClasses, MinorFU::opLat, MinorFUTiming::srcRegsRelativeLats, and MinorFU::timings.
Member Function Documentation
void Minor::FUPipeline::advance ()
Step the pipeline.
Allow multiple steps?
Reimplemented from Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >.
Definition at line 184 of file func_unit.cc.
References Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::alreadyPushed(), ClockedObject::curCycle(), description, MinorFU::issueLat, nextInsertCycle, Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::stalled, and timeSource.
Referenced by Minor::Execute::evaluate().
bool Minor::FUPipeline::canInsert () const
Can an instruction be inserted now?
Definition at line 178 of file func_unit.cc.
References ClockedObject::curCycle(), nextInsertCycle, and timeSource.
Referenced by Minor::Execute::issue().
Cycles Minor::FUPipeline::cyclesBeforeInsert ()
How many cycles must from curCycle before insertion into the pipeline is allowed.
Definition at line 169 of file func_unit.cc.
References ClockedObject::curCycle(), nextInsertCycle, and timeSource.
Referenced by Minor::Execute::issue().
MinorFUTiming * Minor::FUPipeline::findTiming (const StaticInstPtr & inst)
Find the extra timing information for this instruction.
Returns NULL if no decode info. is found
Definition at line 202 of file func_unit.cc.
References MinorFUTiming::description, description, DPRINTFS, ArmISA::i, MinorFUTiming::mask, MinorFUTiming::match, MinorFUTiming::provides(), and MinorFU::timings.
Referenced by Minor::Execute::issue().
Member Data Documentation
std::vector<bool> Minor::FUPipeline::cantForwardFromFUIndices
FUs which this pipeline can't receive a forwarded (i.e.
relative latency != 0) result from
Definition at line 238 of file func_unit.hh.
Referenced by FUPipeline(), and Minor::Execute::issue().
std::bitset<Num_OpClasses> Minor::FUPipeline::capabilityList
Set of operation classes supported by this FU.
Reimplemented from FuncUnit.
Definition at line 234 of file func_unit.hh.
const MinorFU& Minor::FUPipeline::description
Functional unit description that this pipeline implements.
Definition at line 228 of file func_unit.hh.
Referenced by advance(), findTiming(), FUPipeline(), and Minor::Execute::issue().
Cycles Minor::FUPipeline::nextInsertCycle
When can a new instruction be inserted into the pipeline? This is an absolute cycle time unless it is 0 in which case the an instruction can be pushed straightaway.
Definition at line 244 of file func_unit.hh.
Referenced by advance(), canInsert(), and cyclesBeforeInsert().
ClockedObject& Minor::FUPipeline::timeSource
An FUPipeline needs access to curCycle, use this timing source.
Definition at line 231 of file func_unit.hh.
Referenced by advance(), canInsert(), and cyclesBeforeInsert().
The documentation for this class was generated from the following files:
cpu/minor/func_unit.hh
cpu/minor/func_unit.cc