gem5: MasterPort Class Reference
MasterPort Class Reference
A MasterPort is a specialisation of a BaseMasterPort, which implements the default protocol for the three different level of transport functions.
#include <port.hh>
Public Member Functions
MasterPort (const std::string &name, MemObject *owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (BaseSlavePort &slave_port)
Bind this master port to a slave port.
void unbind ()
Unbind this master port and the associated slave port.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctional (PacketPtr pkt)
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Protected Member Functions
virtual Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from the slave port.
virtual void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
virtual bool recvTimingResp (PacketPtr pkt)=0
Receive a timing response from the slave port.
virtual void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the slave port.
virtual void recvReqRetry ()=0
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
virtual void recvRetrySnoopResp ()
Called by the slave port if sendTimingSnoopResp was called on this master port (causing recvTimingSnoopResp to be called on the slave port) and was unsuccesful.
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Private Attributes
SlavePort * _slavePort
Friends
class SlavePort
Detailed Description
A MasterPort is a specialisation of a BaseMasterPort, which implements the default protocol for the three different level of transport functions.
In addition to the basic functionality of sending packets, it also has functions to receive range changes or determine if the port is snooping or not.
Definition at line 167 of file port.hh.
Constructor & Destructor Documentation
MasterPort::MasterPort (const std::string & name, MemObject * owner, PortID id = InvalidPortID)
Master port.
Definition at line 117 of file port.cc.
MasterPort::~MasterPort () [virtual]
Definition at line 122 of file port.cc.
Member Function Documentation
void MasterPort::bind (BaseSlavePort & slave_port) [virtual]
Bind this master port to a slave port.
This also does the mirror action and binds the slave port to the master port.
Implements BaseMasterPort.
Definition at line 127 of file port.cc.
References BaseMasterPort::_baseSlavePort, _slavePort, SlavePort::bind(), fatal, and Port::name().
AddrRangeList MasterPort::getAddrRanges () const
Get the address ranges of the connected slave port.
Reimplemented in SnapMemCtrl::SnapMemCtrlMasterPort.
Definition at line 159 of file port.cc.
References _slavePort, and SlavePort::getAddrRanges().
Referenced by MemCheckerMonitor::getAddrRanges(), CommMonitor::getAddrRanges(), and BadAddrEvent::process().
virtual bool MasterPort::isSnooping () const [inline, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented in FullO3CPU< Impl >::DcachePort, AtomicSimpleCPU::AtomicCPUDPort, TimingSimpleCPU::DcachePort, AddrMapper::MapperMasterPort, BaseCache::CacheMasterPort, CoherentXBar::CoherentXBarMasterPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, SnapMemCtrl::SnapMemCtrlMasterPort, and SnapMemCtrl::SnapMemCtrlMasterSnapPort.
Definition at line 254 of file port.hh.
Referenced by SlavePort::isSnooping().
void MasterPort::printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
For debugging.
Definition at line 199 of file port.cc.
References Request::funcMasterId, MemCmd::PrintReq, Packet::senderState, and sendFunctional().
Referenced by NetworkTest::printAddr(), TimingSimpleCPU::printAddr(), and AtomicSimpleCPU::printAddr().
virtual Tick MasterPort::recvAtomicSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic snoop request packet from the slave port.
Reimplemented in AtomicSimpleCPU::AtomicCPUPort, AtomicSimpleCPU::AtomicCPUDPort, MemTest::CpuPort, TrafficGen::TrafficGenPort, AddrMapper::MapperMasterPort, CoherentXBar::CoherentXBarMasterPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, and SnapMemCtrl::SnapMemCtrlMasterPort.
Definition at line 271 of file port.hh.
References Port::name(), and panic.
Referenced by SlavePort::sendAtomicSnoop().
virtual void MasterPort::recvFunctionalSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented in FullO3CPU< Impl >::DcachePort, AtomicSimpleCPU::AtomicCPUDPort, TimingSimpleCPU::DcachePort, MemTest::CpuPort, TrafficGen::TrafficGenPort, AddrMapper::MapperMasterPort, CoherentXBar::CoherentXBarMasterPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, and SnapMemCtrl::SnapMemCtrlMasterPort.
Definition at line 280 of file port.hh.
References Port::name(), and panic.
Referenced by SlavePort::sendFunctionalSnoop().
virtual void MasterPort::recvRangeChange () [inline, protected, virtual]
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented in AddrMapper::MapperMasterPort, CoherentXBar::CoherentXBarMasterPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, NoncoherentXBar::NoncoherentXBarMasterPort, RubyPort::MemMasterPort, and RubyPort::PioMasterPort.
Definition at line 322 of file port.hh.
Referenced by SlavePort::sendRangeChange().
virtual void MasterPort::recvReqRetry () [protected, pure virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implemented in X86ISA::Walker::WalkerPort, BaseKvmCPU::KVMCpuPort, Minor::Fetch1::IcachePort, Minor::LSQ::DcachePort, FullO3CPU< Impl >::IcachePort, FullO3CPU< Impl >::DcachePort, AtomicSimpleCPU::AtomicCPUPort, TimingSimpleCPU::IcachePort, TimingSimpleCPU::DcachePort, RubyDirectedTester::CpuPort, MemTest::CpuPort, NetworkTest::CpuPort, RubyTester::CpuPort, TrafficGen::TrafficGenPort, DmaPort, AddrMapper::MapperMasterPort, Bridge::BridgeMasterPort, CoherentXBar::CoherentXBarMasterPort, CoherentXBar::SnoopRespPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, NoncoherentXBar::NoncoherentXBarMasterPort, QueuedMasterPort, and System::SystemPort.
Referenced by SlavePort::sendRetryReq().
virtual void MasterPort::recvRetrySnoopResp () [inline, protected, virtual]
Called by the slave port if sendTimingSnoopResp was called on this master port (causing recvTimingSnoopResp to be called on the slave port) and was unsuccesful.
Reimplemented in QueuedMasterPort.
Definition at line 310 of file port.hh.
References Port::name(), and panic.
Referenced by SlavePort::sendRetrySnoopResp().
virtual bool MasterPort::recvTimingResp (PacketPtr pkt) [protected, pure virtual]
Receive a timing response from the slave port.
Implemented in X86ISA::Walker::WalkerPort, BaseKvmCPU::KVMCpuPort, Minor::Fetch1::IcachePort, Minor::LSQ::DcachePort, FullO3CPU< Impl >::IcachePort, FullO3CPU< Impl >::DcachePort, AtomicSimpleCPU::AtomicCPUPort, TimingSimpleCPU::IcachePort, TimingSimpleCPU::DcachePort, RubyDirectedTester::CpuPort, MemTest::CpuPort, NetworkTest::CpuPort, RubyTester::CpuPort, TrafficGen::TrafficGenPort, DmaPort, AddrMapper::MapperMasterPort, Bridge::BridgeMasterPort, CoherentXBar::CoherentXBarMasterPort, CoherentXBar::SnoopRespPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, MessageMasterPort, NoncoherentXBar::NoncoherentXBarMasterPort, AbstractController::MemoryPort, RubyPort::MemMasterPort, RubyPort::PioMasterPort, SnapMemCtrl::SnapMemCtrlMasterPort, SnapMemCtrl::SnapMemCtrlMasterSnapPort, and System::SystemPort.
Referenced by SlavePort::sendTimingResp().
virtual void MasterPort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop request from the slave port.
Reimplemented in MinorCPU::MinorCPUPort, Minor::LSQ::DcachePort, FullO3CPU< Impl >::IcachePort, FullO3CPU< Impl >::DcachePort, TimingSimpleCPU::TimingCPUPort, TimingSimpleCPU::DcachePort, MemTest::CpuPort, TrafficGen::TrafficGenPort, AddrMapper::MapperMasterPort, CoherentXBar::CoherentXBarMasterPort, CommMonitor::MonitorMasterPort, MemCheckerMonitor::MonitorMasterPort, and SnapMemCtrl::SnapMemCtrlMasterPort.
Definition at line 293 of file port.hh.
References Port::name(), and panic.
Referenced by SlavePort::sendTimingSnoopReq().
Tick MasterPort::sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Parameters:
pkt Packet to send.
Returns:
Estimated latency of access.
Definition at line 165 of file port.cc.
References _slavePort, Packet::isRequest(), and SlavePort::recvAtomic().
Referenced by BaseKvmCPU::doMMIOAccess(), X86KvmCPU::handleKvmExitIO(), ArmISA::Stage2MMU::readDataUntimed(), AtomicSimpleCPU::readMem(), MemCheckerMonitor::recvAtomic(), CommMonitor::recvAtomic(), Cache::recvAtomic(), Bridge::BridgeSlavePort::recvAtomic(), AddrMapper::recvAtomic(), DmaPort::sendDma(), X86ISA::IntDevice::IntMasterPort::sendMessage(), MemTest::sendPkt(), X86ISA::Walker::WalkerState::startWalk(), AtomicSimpleCPU::tick(), and AtomicSimpleCPU::writeMem().
void MasterPort::sendFunctional (PacketPtr pkt)
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Parameters:
pkt Packet to send.
Definition at line 172 of file port.cc.
References _slavePort, Packet::isRequest(), and SlavePort::recvFunctional().
Referenced by ArmISA::TableWalker::fetchDescriptor(), Cache::functionalAccess(), AbstractController::functionalMemoryRead(), AbstractController::functionalMemoryWrite(), printAddr(), ArmISA::TableWalker::processWalkAArch64(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), PortProxy::readBlob(), ArmISA::Stage2MMU::readDataUntimed(), CheckerCPU::readMem(), MemCheckerMonitor::recvFunctional(), CommMonitor::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), AddrMapper::recvFunctional(), X86ISA::Walker::WalkerState::startFunctional(), MemTest::tick(), Checker< Impl >::verify(), Cache::writebackVisitor(), and PortProxy::writeBlob().
void MasterPort::sendRetryResp () [virtual]
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Note that this is virtual so that the "fake" snoop response port in the coherent crossbar can override the behaviour.
Reimplemented in CoherentXBar::SnoopRespPort.
Definition at line 193 of file port.cc.
References _slavePort, and SlavePort::recvRespRetry().
Referenced by MemCheckerMonitor::recvRespRetry(), CommMonitor::recvRespRetry(), AddrMapper::recvRespRetry(), and BaseXBar::RespLayer::sendRetry().
bool MasterPort::sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvReqRetry at which point it can re-issue a sendTimingReq.
Parameters:
pkt Packet to send.
Returns:
If the send was succesful or not.
Definition at line 179 of file port.cc.
References _slavePort, Packet::isRequest(), and SlavePort::recvTimingReq().
Referenced by NetworkTest::doRetry(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), SeriesRequestGenerator::initiate(), InvalidateGenerator::initiate(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), LSQUnit< Impl >::read(), TrafficGen::recvReqRetry(), TimingSimpleCPU::DcachePort::recvReqRetry(), TimingSimpleCPU::IcachePort::recvReqRetry(), MemTest::recvRetry(), LSQUnit< Impl >::recvRetry(), MemCheckerMonitor::recvTimingReq(), CommMonitor::recvTimingReq(), Cache::recvTimingReq(), AddrMapper::recvTimingReq(), Cache::CacheReqPacketQueue::sendDeferredPacket(), TimingSimpleCPU::sendFetch(), NetworkTest::sendPkt(), MemTest::sendPkt(), LSQUnit< Impl >::sendStore(), ReqPacketQueue::sendTiming(), X86ISA::Walker::sendTiming(), Bridge::BridgeMasterPort::trySendTiming(), DmaPort::trySendTimingReq(), Minor::LSQ::tryToSend(), Minor::Fetch1::tryToSend(), and TrafficGen::update().
bool MasterPort::sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvRetrySnoop at which point it can re-issue a sendTimingSnoopResp.
Parameters:
pkt Packet to send.
Definition at line 186 of file port.cc.
References _slavePort, Packet::isResponse(), and SlavePort::recvTimingSnoopResp().
Referenced by MemCheckerMonitor::recvTimingSnoopResp(), CommMonitor::recvTimingSnoopResp(), AddrMapper::recvTimingSnoopResp(), and SnoopRespPacketQueue::sendTiming().
void MasterPort::unbind () [virtual]
Unbind this master port and the associated slave port.
Implements BaseMasterPort.
Definition at line 148 of file port.cc.
References BaseMasterPort::_baseSlavePort, _slavePort, Port::name(), panic, and SlavePort::unbind().
Friends And Related Function Documentation
friend class SlavePort [friend]
Definition at line 170 of file port.hh.
Member Data Documentation
SlavePort* MasterPort::_slavePort [private]
Definition at line 174 of file port.hh.
Referenced by bind(), getAddrRanges(), sendAtomic(), sendFunctional(), sendRetryResp(), sendTimingReq(), sendTimingSnoopResp(), and unbind().
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc