gem5: Minor::Pipeline Class Reference
Minor::Pipeline Class Reference
The constructed pipeline.
#include <pipeline.hh>
Public Types
enum StageId {
CPUStageId = 0, Fetch1StageId, Fetch2StageId, DecodeStageId,
ExecuteStageId, Num_StageId
}
Enumerated ids of the 'stages' for the activity recorder.
Public Member Functions
Pipeline (MinorCPU &cpu_, MinorCPUParams &params)
void wakeupFetch ()
Wake up the Fetch unit.
unsigned int drain (DrainManager *manager)
Try to drain the CPU.
void drainResume ()
bool isDrained ()
Test to see if the CPU is drained.
void evaluate ()
A custom evaluate allows report in the right place (between stages and pipeline advance).
void countCycles (Cycles delta) M5_ATTR_OVERRIDE
Callback to handle cycle statistics and probes.
void minorTrace () const
MinorCPU::MinorCPUPort & getInstPort ()
Functions below here are BaseCPU operations passed on to pipeline stages.
MinorCPU::MinorCPUPort & getDataPort ()
Return the DcachePort belonging to Execute for the CPU.
MinorActivityRecorder * getActivityRecorder ()
To give the activity recorder to the CPU.
Public Attributes
bool needToSignalDrained
True after drain is called but draining isn't complete.
Protected Attributes
MinorCPU & cpu
bool allow_idling
Allow cycles to be skipped when the pipeline is idle.
Latch< ForwardLineData > f1ToF2
Latch< BranchData > f2ToF1
Latch< ForwardInstData > f2ToD
Latch< ForwardInstData > dToE
Latch< BranchData > eToF1
Execute execute
Decode decode
Fetch2 fetch2
Fetch1 fetch1
MinorActivityRecorder activityRecorder
Activity recording for the pipeline.
Detailed Description
The constructed pipeline.
Kept out of MinorCPU to keep the interface between the CPU and its grubby implementation details clean.
Definition at line 71 of file pipeline.hh.
Member Enumeration Documentation
enum Minor::Pipeline::StageId
Enumerated ids of the 'stages' for the activity recorder.
Enumerator:
CPUStageId
Fetch1StageId
Fetch2StageId
DecodeStageId
ExecuteStageId
Num_StageId
Definition at line 97 of file pipeline.hh.
Constructor & Destructor Documentation
Minor::Pipeline::Pipeline (MinorCPU & cpu_, MinorCPUParams & params)
Definition at line 55 of file pipeline.cc.
References cpu, and fatal.
Member Function Documentation
void Minor::Pipeline::countCycles (Cycles delta) [inline, virtual]
Callback to handle cycle statistics and probes.
This callback is called at the beginning of a new cycle active cycle and when restarting the ticked object. The delta parameter indicates the number of cycles elapsed since the previous call is normally '1' unless the object has been stopped and restarted.
Parameters:
delta Number of cycles since the previous call.
Reimplemented from Ticked.
Definition at line 129 of file pipeline.hh.
References cpu.
unsigned int Minor::Pipeline::drain (DrainManager * manager)
Try to drain the CPU.
Definition at line 196 of file pipeline.cc.
References DPRINTF, Minor::Execute::drain(), execute, isDrained(), and needToSignalDrained.
Referenced by MinorCPU::drain().
void Minor::Pipeline::drainResume ()
Definition at line 212 of file pipeline.cc.
References DPRINTF, Minor::Execute::drainResume(), and execute.
Referenced by MinorCPU::drainResume().
void Minor::Pipeline::evaluate () [virtual]
A custom evaluate allows report in the right place (between stages and pipeline advance).
Implements Ticked.
Definition at line 123 of file pipeline.cc.
References ActivityRecorder::active(), activityRecorder, allow_idling, cpu, CPUStageId, ActivityRecorder::deactivateStage(), decode, DecodeStageId, DPRINTF, dToE, DTRACE, eToF1, Minor::MinorActivityRecorder::evaluate(), Minor::Latch< Data >::evaluate(), Minor::Fetch1::evaluate(), Minor::Fetch2::evaluate(), Minor::Decode::evaluate(), Minor::Execute::evaluate(), execute, ExecuteStageId, f1ToF2, f2ToD, f2ToF1, fetch1, Fetch1StageId, fetch2, Fetch2StageId, isDrained(), minorTrace(), needToSignalDrained, MinorCPU::signalDrainDone(), and Ticked::stop().
MinorActivityRecorder* Minor::Pipeline::getActivityRecorder () [inline]
To give the activity recorder to the CPU.
Definition at line 145 of file pipeline.hh.
References activityRecorder.
Referenced by MinorCPU::MinorCPU().
MinorCPU::MinorCPUPort & Minor::Pipeline::getDataPort ()
Return the DcachePort belonging to Execute for the CPU.
Definition at line 184 of file pipeline.cc.
References execute, and Minor::Execute::getDcachePort().
Referenced by MinorCPU::getDataPort().
MinorCPU::MinorCPUPort & Minor::Pipeline::getInstPort ()
Functions below here are BaseCPU operations passed on to pipeline stages.
Return the IcachePort belonging to Fetch1 for the CPU
Definition at line 178 of file pipeline.cc.
References fetch1, and Minor::Fetch1::getIcachePort().
Referenced by MinorCPU::getInstPort().
bool Minor::Pipeline::isDrained ()
Test to see if the CPU is drained.
Definition at line 219 of file pipeline.cc.
References decode, DPRINTF, dToE, Minor::Latch< Data >::empty(), execute, f1ToF2, f2ToD, f2ToF1, fetch1, fetch2, Minor::Execute::isDrained(), Minor::Decode::isDrained(), Minor::Fetch2::isDrained(), and Minor::Fetch1::isDrained().
Referenced by drain(), and evaluate().
void Minor::Pipeline::minorTrace () const
Definition at line 108 of file pipeline.cc.
References activityRecorder, decode, dToE, eToF1, execute, f1ToF2, f2ToD, f2ToF1, fetch1, fetch2, Minor::MinorActivityRecorder::minorTrace(), Minor::Execute::minorTrace(), Minor::Decode::minorTrace(), Minor::Fetch2::minorTrace(), Minor::Latch< Data >::minorTrace(), and Minor::Fetch1::minorTrace().
Referenced by evaluate().
void Minor::Pipeline::wakeupFetch ()
Wake up the Fetch unit.
This is needed on thread activation esp. after quiesce wakeup
Definition at line 190 of file pipeline.cc.
References execute, and Minor::Execute::wakeupFetch().
Referenced by MinorCPU::activateContext().
Member Data Documentation
MinorActivityRecorder Minor::Pipeline::activityRecorder [protected]
Activity recording for the pipeline.
This is access through the CPU by the pipeline stages but belongs to the Pipeline as it is the cleanest place to initialise it
Definition at line 93 of file pipeline.hh.
Referenced by evaluate(), getActivityRecorder(), and minorTrace().
bool Minor::Pipeline::allow_idling [protected]
Allow cycles to be skipped when the pipeline is idle.
Definition at line 77 of file pipeline.hh.
Referenced by evaluate().
MinorCPU& Minor::Pipeline::cpu [protected]
Definition at line 74 of file pipeline.hh.
Referenced by countCycles(), evaluate(), and Pipeline().
Decode Minor::Pipeline::decode [protected]
Definition at line 86 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
Latch<ForwardInstData> Minor::Pipeline::dToE [protected]
Definition at line 82 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
Latch<BranchData> Minor::Pipeline::eToF1 [protected]
Definition at line 83 of file pipeline.hh.
Referenced by evaluate(), and minorTrace().
Execute Minor::Pipeline::execute [protected]
Definition at line 85 of file pipeline.hh.
Referenced by drain(), drainResume(), evaluate(), getDataPort(), isDrained(), minorTrace(), and wakeupFetch().
Latch<ForwardLineData> Minor::Pipeline::f1ToF2 [protected]
Definition at line 79 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
Latch<ForwardInstData> Minor::Pipeline::f2ToD [protected]
Definition at line 81 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
Latch<BranchData> Minor::Pipeline::f2ToF1 [protected]
Definition at line 80 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
Fetch1 Minor::Pipeline::fetch1 [protected]
Definition at line 88 of file pipeline.hh.
Referenced by evaluate(), getInstPort(), isDrained(), and minorTrace().
Fetch2 Minor::Pipeline::fetch2 [protected]
Definition at line 87 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
bool Minor::Pipeline::needToSignalDrained
True after drain is called but draining isn't complete.
Definition at line 107 of file pipeline.hh.
Referenced by drain(), and evaluate().
The documentation for this class was generated from the following files:
cpu/minor/pipeline.hh
cpu/minor/pipeline.cc