gem5: ArmISA::Stage2MMU::Stage2Translation Class Reference
ArmISA::Stage2MMU::Stage2Translation Class Reference
This translation class is used to trigger the data fetch once a timing translation returns the translated physical address.
#include <stage2_mmu.hh>
Public Member Functions
Stage2Translation (Stage2MMU &_parent, uint8_t *_data, Event *_event, Addr _oVAddr)
void markDelayed ()
Signal that the translation has been delayed due to a hw page table walk.
void finish (const Fault &fault, RequestPtr req, ThreadContext *tc, BaseTLB::Mode mode)
void setVirt (Addr vaddr, int size, Request::Flags flags, int masterId)
Fault translateTiming (ThreadContext *tc)
Public Attributes
Fault fault
Private Attributes
uint8_t * data
int numBytes
Request req
Event * event
Stage2MMU & parent
Addr oVAddr
Detailed Description
This translation class is used to trigger the data fetch once a timing translation returns the translated physical address.
Definition at line 70 of file stage2_mmu.hh.
Constructor & Destructor Documentation
Stage2MMU::Stage2Translation::Stage2Translation (Stage2MMU & _parent, uint8_t * _data, Event * _event, Addr _oVAddr)
Definition at line 112 of file stage2_mmu.cc.
Member Function Documentation
void Stage2MMU::Stage2Translation::finish (const Fault & fault, RequestPtr req, ThreadContext * tc, BaseTLB::Mode mode) [virtual]
Implements BaseTLB::Translation.
Definition at line 120 of file stage2_mmu.cc.
References ArmISA::ArmFault::annotate(), data, DmaPort::dmaAction(), event, fault, ThreadContext::getCpuPtr(), Request::getFlags(), Request::getPaddr(), ArmISA::Stage2MMU::getPort(), Flags< T >::isSet(), Request::NO_ACCESS, numBytes, ArmISA::ArmFault::OVA, oVAddr, parent, MemCmd::ReadReq, and ArmISA::ArmFault::S1PTW.
void ArmISA::Stage2MMU::Stage2Translation::markDelayed () [inline, virtual]
Signal that the translation has been delayed due to a hw page table walk.
Implements BaseTLB::Translation.
Definition at line 87 of file stage2_mmu.hh.
void ArmISA::Stage2MMU::Stage2Translation::setVirt (Addr vaddr, int size, Request::Flags flags, int masterId) [inline]
Definition at line 93 of file stage2_mmu.hh.
References numBytes, req, and Request::setVirt().
Referenced by ArmISA::Stage2MMU::readDataTimed().
Fault ArmISA::Stage2MMU::Stage2Translation::translateTiming (ThreadContext * tc) [inline]
Definition at line 99 of file stage2_mmu.hh.
References parent, BaseTLB::Read, req, ArmISA::Stage2MMU::stage2Tlb(), and ArmISA::TLB::translateTiming().
Referenced by ArmISA::Stage2MMU::readDataTimed().
Member Data Documentation
uint8_t* ArmISA::Stage2MMU::Stage2Translation::data [private]
Definition at line 73 of file stage2_mmu.hh.
Referenced by finish().
Event* ArmISA::Stage2MMU::Stage2Translation::event [private]
Definition at line 76 of file stage2_mmu.hh.
Referenced by finish().
Fault ArmISA::Stage2MMU::Stage2Translation::fault
Definition at line 81 of file stage2_mmu.hh.
Referenced by ArmISA::TableWalker::fetchDescriptor(), and finish().
int ArmISA::Stage2MMU::Stage2Translation::numBytes [private]
Definition at line 74 of file stage2_mmu.hh.
Referenced by finish(), and setVirt().
Addr ArmISA::Stage2MMU::Stage2Translation::oVAddr [private]
Definition at line 78 of file stage2_mmu.hh.
Referenced by finish().
Stage2MMU& ArmISA::Stage2MMU::Stage2Translation::parent [private]
Definition at line 77 of file stage2_mmu.hh.
Referenced by finish(), and translateTiming().
Request ArmISA::Stage2MMU::Stage2Translation::req [private]
Definition at line 75 of file stage2_mmu.hh.
Referenced by setVirt(), and translateTiming().
The documentation for this class was generated from the following files:
arch/arm/stage2_mmu.hh
arch/arm/stage2_mmu.cc