gem5: ArmISA::MemoryEx64 Class Reference
ArmISA::MemoryEx64 Class Reference
#include <mem64.hh>
Protected Member Functions
MemoryEx64 (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _base, IntRegIndex _result)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex result
Detailed Description
Definition at line 225 of file mem64.hh.
Constructor & Destructor Documentation
ArmISA::MemoryEx64::MemoryEx64 (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _base, IntRegIndex _result) [inline, protected]
Definition at line 230 of file mem64.hh.
Member Function Documentation
std::string ArmISA::MemoryEx64::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 171 of file mem64.cc.
References ArmISA::Memory64::base, ccprintf(), ArmISA::Memory64::dest, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), result, and ArmISA::ss.
Member Data Documentation
IntRegIndex ArmISA::MemoryEx64::result [protected]
Definition at line 228 of file mem64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/mem64.hh
arch/arm/insts/mem64.cc