gem5: RubySystem::RubyEvent Class Reference
RubySystem::RubyEvent Class Reference
#include <System.hh>
Public Member Functions
RubyEvent (RubySystem *_ruby_system)
Private Member Functions
void process ()
Private Attributes
RubySystem * ruby_system
Detailed Description
Definition at line 52 of file System.hh.
Constructor & Destructor Documentation
RubySystem::RubyEvent::RubyEvent (RubySystem * _ruby_system) [inline]
Definition at line 55 of file System.hh.
References ruby_system.
Member Function Documentation
void RubySystem::RubyEvent::process () [private, virtual]
Implements Event.
Definition at line 329 of file System.cc.
References CacheRecorder::enqueueNextFetchRequest(), CacheRecorder::enqueueNextFlushRequest(), RubySystem::getCooldownEnabled(), RubySystem::getWarmupEnabled(), RubySystem::m_cache_recorder, and ruby_system.
Member Data Documentation
RubySystem* RubySystem::RubyEvent::ruby_system [private]
Definition at line 62 of file System.hh.
Referenced by process(), and RubyEvent().
The documentation for this class was generated from the following files:
mem/ruby/system/System.hh
mem/ruby/system/System.cc