gem5: Stats::SparseHistBase< Derived, Stor > Class Template Reference
Stats::SparseHistBase< Derived, Stor > Class Template Reference
["Statistic Types"]
Implementation of a sparse histogram stat.
#include <statistics.hh>
Public Types
typedef SparseHistInfoProxy
< Derived > Info
typedef Stor Storage
typedef Stor::Params Params
Public Member Functions
SparseHistBase ()
template<typename U >
void sample (const U &v, int n=1)
Add a value to the distribtion n times.
size_type size () const
Return the number of entries in this stat.
bool zero () const
Return true if no samples have been added.
void prepare ()
void reset ()
Reset stat value to default.
Protected Member Functions
Storage * data ()
Retrieve the storage.
const Storage * data () const
Retrieve a const pointer to the storage.
void doInit ()
Protected Attributes
char storage [sizeof(Storage)]
The storage for this stat.
Detailed Description
template<class Derived, class Stor>
class Stats::SparseHistBase< Derived, Stor >
Implementation of a sparse histogram stat.
The storage class is determined by the Storage template.
Definition at line 2700 of file statistics.hh.
Member Typedef Documentation
template<class Derived, class Stor> typedef SparseHistInfoProxy<Derived> Stats::SparseHistBase< Derived, Stor >::Info
Reimplemented from Stats::DataWrap< Derived, SparseHistInfoProxy >.
Definition at line 2703 of file statistics.hh.
template<class Derived, class Stor> typedef Stor::Params Stats::SparseHistBase< Derived, Stor >::Params
Definition at line 2705 of file statistics.hh.
template<class Derived, class Stor> typedef Stor Stats::SparseHistBase< Derived, Stor >::Storage
Definition at line 2704 of file statistics.hh.
Constructor & Destructor Documentation
template<class Derived, class Stor> Stats::SparseHistBase< Derived, Stor >::SparseHistBase () [inline]
Definition at line 2740 of file statistics.hh.
Member Function Documentation
template<class Derived, class Stor> const Storage* Stats::SparseHistBase< Derived, Stor >::data () const [inline, protected]
Retrieve a const pointer to the storage.
Returns:
A const pointer to the storage object for this stat.
Definition at line 2727 of file statistics.hh.
template<class Derived, class Stor> Storage* Stats::SparseHistBase< Derived, Stor >::data () [inline, protected]
Retrieve the storage.
Returns:
The storage object for this stat.
Definition at line 2717 of file statistics.hh.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::prepare(), Stats::SparseHistBase< SparseHistogram, SparseHistStor >::reset(), Stats::SparseHistBase< SparseHistogram, SparseHistStor >::sample(), Stats::SparseHistBase< SparseHistogram, SparseHistStor >::size(), and Stats::SparseHistBase< SparseHistogram, SparseHistStor >::zero().
template<class Derived, class Stor> void Stats::SparseHistBase< Derived, Stor >::doInit () [inline, protected]
Definition at line 2733 of file statistics.hh.
template<class Derived, class Stor> void Stats::SparseHistBase< Derived, Stor >::prepare () [inline]
Definition at line 2763 of file statistics.hh.
template<class Derived, class Stor> void Stats::SparseHistBase< Derived, Stor >::reset () [inline]
Reset stat value to default.
Reimplemented from Stats::InfoAccess.
Definition at line 2773 of file statistics.hh.
template<class Derived, class Stor> template<typename U > void Stats::SparseHistBase< Derived, Stor >::sample (const U & v, int n = 1) [inline]
Add a value to the distribtion n times.
Calls sample on the storage class.
Parameters:
v The value to add.
n The number of times to add it, defaults to 1.
Definition at line 2749 of file statistics.hh.
Referenced by CommMonitor::recvTimingReq(), StatTest::run(), and StackDistCalc::update().
template<class Derived, class Stor> size_type Stats::SparseHistBase< Derived, Stor >::size () const [inline]
Return the number of entries in this stat.
Returns:
The number of entries.
Definition at line 2755 of file statistics.hh.
template<class Derived, class Stor> bool Stats::SparseHistBase< Derived, Stor >::zero () const [inline]
Return true if no samples have been added.
Returns:
True if there haven't been any samples.
Reimplemented from Stats::InfoAccess.
Definition at line 2760 of file statistics.hh.
Member Data Documentation
template<class Derived, class Stor> char Stats::SparseHistBase< Derived, Stor >::storage[sizeof(Storage)] [protected]
The storage for this stat.
Definition at line 2709 of file statistics.hh.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::data(), and Stats::SparseHistBase< SparseHistogram, SparseHistStor >::doInit().
The documentation for this class was generated from the following file:
base/statistics.hh