gem5: X86ISA::PageFault Class Reference
X86ISA::PageFault Class Reference
#include <faults.hh>
Public Member Functions
PageFault (Addr _addr, uint32_t _errorCode)
PageFault (Addr _addr, bool present, BaseTLB::Mode mode, bool user, bool reserved)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
virtual std::string describe () const
Protected Member Functions
BitUnion32 (PageFaultErrorCode) Bitfield< 0 > present
EndBitUnion (PageFaultErrorCode) Addr addr
Protected Attributes
Bitfield< 1 > write
Bitfield< 2 > user
Bitfield< 3 > reserved
Bitfield< 4 > fetch
Detailed Description
Definition at line 304 of file faults.hh.
Constructor & Destructor Documentation
X86ISA::PageFault::PageFault (Addr _addr, uint32_t _errorCode) [inline]
Definition at line 318 of file faults.hh.
X86ISA::PageFault::PageFault (Addr _addr, bool present, BaseTLB::Mode mode, bool user, bool reserved) [inline]
Definition at line 322 of file faults.hh.
References X86ISA::X86FaultBase::errorCode, BaseTLB::Execute, and BaseTLB::Write.
Member Function Documentation
X86ISA::PageFault::BitUnion32 (PageFaultErrorCode) [protected]
std::string X86ISA::PageFault::describe () const [virtual]
Reimplemented from X86ISA::X86FaultBase.
Definition at line 165 of file faults.cc.
References X86ISA::addr, ccprintf(), X86ISA::X86FaultBase::describe(), and ArmISA::ss.
X86ISA::PageFault::EndBitUnion (PageFaultErrorCode) [protected]
void X86ISA::PageFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from X86ISA::X86FaultBase.
Definition at line 135 of file faults.cc.
References X86ISA::addr, X86ISA::X86FaultBase::errorCode, FullSystem, X86ISA::MISCREG_CR2, X86ISA::MISCREG_M5_REG, panic, ThreadContext::readMiscRegNoEffect(), and ThreadContext::setMiscReg().
Member Data Documentation
Bitfield<4> X86ISA::PageFault::fetch [protected]
Definition at line 312 of file faults.hh.
Bitfield<3> X86ISA::PageFault::reserved [protected]
Definition at line 311 of file faults.hh.
Bitfield<2> X86ISA::PageFault::user [protected]
Definition at line 310 of file faults.hh.
Bitfield<1> X86ISA::PageFault::write [protected]
Definition at line 309 of file faults.hh.
The documentation for this class was generated from the following files:
arch/x86/faults.hh
arch/x86/faults.cc