gem5: ArmISA::FpRegRegOp Class Reference
ArmISA::FpRegRegOp Class Reference
#include <vfp.hh>
Protected Member Functions
FpRegRegOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, VfpMicroMode mode=VfpNotAMicroop)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
IntRegIndex op1
Detailed Description
Definition at line 912 of file vfp.hh.
Constructor & Destructor Documentation
ArmISA::FpRegRegOp::FpRegRegOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, VfpMicroMode mode = VfpNotAMicroop) [inline, protected]
Definition at line 918 of file vfp.hh.
References StaticInst::flags, ArmISA::mode, and ArmISA::setVfpMicroFlags().
Member Function Documentation
std::string FpRegRegOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 80 of file vfp.cc.
References dest, ArmISA::FP_Reg_Base, op1, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex ArmISA::FpRegRegOp::dest [protected]
Definition at line 915 of file vfp.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::FpRegRegOp::op1 [protected]
Definition at line 916 of file vfp.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/vfp.hh
arch/arm/insts/vfp.cc