gem5: Stats::DataWrap< Derived, InfoProxyType > Class Template Reference
Stats::DataWrap< Derived, InfoProxyType > Class Template Reference
#include <statistics.hh>
Public Types
typedef InfoProxyType< Derived > Info
Public Member Functions
const Info * info () const
Grab the information class for this statistic.
DataWrap ()
Derived & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Derived & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Derived & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Derived & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Derived & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
template<class Stat >
Derived & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Protected Member Functions
Derived & self ()
Info * info ()
Grab the information class for this statistic.
DataWrap (const DataWrap &stat)
Copy constructor, copies are not allowed.
void operator= (const DataWrap &)
Can't copy stats.
Detailed Description
template<class Derived, template< class > class InfoProxyType>
class Stats::DataWrap< Derived, InfoProxyType >
Definition at line 205 of file statistics.hh.
Member Typedef Documentation
template<class Derived, template< class > class InfoProxyType> typedef InfoProxyType<Derived> Stats::DataWrap< Derived, InfoProxyType >::Info
Reimplemented in Stats::DataWrapVec< Derived, InfoProxyType >, Stats::DataWrapVec2d< Derived, InfoProxyType >, Stats::Vector2dBase< Derived, Stor >, Stats::DistBase< Derived, Stor >, Stats::VectorDistBase< Derived, Stor >, Stats::SparseHistBase< Derived, Stor >, Stats::DataWrapVec< Derived, VectorInfoProxy >, Stats::DataWrapVec< Vector2d, Vector2dInfoProxy >, Stats::DataWrapVec< AverageVector, VectorInfoProxy >, Stats::DataWrapVec< Derived, VectorDistInfoProxy >, Stats::DataWrapVec< VectorDistribution, VectorDistInfoProxy >, Stats::DataWrapVec< Derived, Vector2dInfoProxy >, Stats::DataWrapVec< VectorAverageDeviation, VectorDistInfoProxy >, Stats::DataWrapVec< Vector, VectorInfoProxy >, Stats::DataWrapVec< Formula, FormulaInfoProxy >, Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >, Stats::DataWrapVec2d< Vector2d, Vector2dInfoProxy >, Stats::DataWrapVec2d< Derived, Vector2dInfoProxy >, Stats::Vector2dBase< Vector2d, StatStor >, Stats::DistBase< Histogram, HistStor >, Stats::DistBase< AverageDeviation, AvgSampleStor >, Stats::DistBase< StandardDeviation, SampleStor >, Stats::DistBase< Distribution, DistStor >, Stats::VectorDistBase< VectorStandardDeviation, SampleStor >, Stats::VectorDistBase< VectorDistribution, DistStor >, Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >, and Stats::SparseHistBase< SparseHistogram, SparseHistStor >.
Definition at line 208 of file statistics.hh.
Constructor & Destructor Documentation
template<class Derived, template< class > class InfoProxyType> Stats::DataWrap< Derived, InfoProxyType >::DataWrap (const DataWrap< Derived, InfoProxyType > & stat) [inline, protected]
Copy constructor, copies are not allowed.
Definition at line 231 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Stats::DataWrap< Derived, InfoProxyType >::DataWrap () [inline]
Definition at line 239 of file statistics.hh.
Member Function Documentation
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::desc (const std::string & _desc) [inline]
Set the description and marks this stat to print at the end of simulation.
Parameters:
desc The new description.
Returns:
A reference to this stat.
Definition at line 283 of file statistics.hh.
Referenced by Stats::Global::Global(), and StatTest::init().
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::flags (Flags _flags) [inline]
Set the flags and marks this stat to print at the end of simulation.
Parameters:
f The new flags.
Returns:
A reference to this stat.
Definition at line 307 of file statistics.hh.
Referenced by StatTest::init().
template<class Derived, template< class > class InfoProxyType> const Info* Stats::DataWrap< Derived, InfoProxyType >::info () const [inline]
Grab the information class for this statistic.
Reimplemented from Stats::InfoAccess.
Definition at line 222 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Info* Stats::DataWrap< Derived, InfoProxyType >::info () [inline, protected]
Grab the information class for this statistic.
Reimplemented from Stats::InfoAccess.
Definition at line 215 of file statistics.hh.
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::desc(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::flags(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::info(), Stats::Vector2dBase< Vector2d, StatStor >::init(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::name(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::precision(), Stats::Vector2dBase< Vector2d, StatStor >::prepare(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::prepare(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::prereq(), Stats::Vector2dBase< Vector2d, StatStor >::reset(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::reset(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::setSeparator(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::subdesc(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::subname(), Stats::DataWrapVec2d< Derived, Vector2dInfoProxy >::ysubname(), and Stats::DataWrapVec2d< Derived, Vector2dInfoProxy >::ysubnames().
template<class Derived, template< class > class InfoProxyType> const std::string& Stats::DataWrap< Derived, InfoProxyType >::name () const [inline]
Definition at line 257 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::name (const std::string & name) [inline]
Set the name and marks this stat to print at the end of simulation.
Parameters:
name The new name.
Returns:
A reference to this stat.
Definition at line 250 of file statistics.hh.
Referenced by Stats::Global::Global(), StatTest::init(), Ticked::regStats(), BaseXBar::Layer< SrcType, DstType >::regStats(), SnoopFilter::regStats(), SnapMemCtrl::regStats(), Sequencer::regStats(), Prefetcher::regStats(), CacheMemory::regStats(), AbstractController::regStats(), Profiler::regStats(), MemCntrlProfiler::regStats(), Switch::regStats(), GarnetNetwork::regStats(), Router_d::regStats(), GarnetNetwork_d::regStats(), BaseGarnetNetwork::regStats(), DRAMCtrl::regStats(), DRAMCtrl::Rank::regStats(), CommMonitor::regStats(), CoherentXBar::regStats(), InsertionProfiler::regStats(), FALRU::regStats(), DIP::regStats(), BIP::regStats(), QueuedPrefetcher::regStats(), Cacti::regStats(), AbstractMemory::regStats(), Sinic::Device::regStats(), IdeDisk::regStats(), EtherDevice::regStats(), UFSHostDevice::regStats(), FlashDevice::regStats(), TrafficGen::regStats(), MemTest::regStats(), BPredUnit::regStats(), ROB< Impl >::regStats(), DefaultRename< Impl >::regStats(), MemDepUnit< MemDepPred, Impl >::regStats(), LSQUnit< Impl >::regStats(), InstructionQueue< Impl >::regStats(), DefaultIEW< Impl >::regStats(), DefaultFetch< Impl >::regStats(), DefaultDecode< Impl >::regStats(), DefaultCommit< Impl >::regStats(), Minor::MinorStats::regStats(), FullO3CPU< Impl >::regStats(), BaseTags::regStats(), BasePrefetcher::regStats(), BaseCache::regStats(), BaseSimpleCPU::regStats(), BaseKvmCPU::regStats(), ArmISA::TableWalker::regStats(), PowerISA::TLB::regStats(), MipsISA::TLB::regStats(), ArmISA::TLB::regStats(), AlphaISA::TLB::regStats(), and Process::regStats().
template<class Derived, template< class > class InfoProxyType> void Stats::DataWrap< Derived, InfoProxyType >::operator= (const DataWrap< Derived, InfoProxyType > &) [inline, protected]
Can't copy stats.
Reimplemented in Stats::DataWrapVec< Derived, InfoProxyType >.
Definition at line 236 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::precision (int _precision) [inline]
Set the precision and marks this stat to print at the end of simulation.
Parameters:
_precision The new precision
Returns:
A reference to this stat.
Definition at line 295 of file statistics.hh.
Referenced by Stats::Global::Global(), and StatTest::init().
template<class Derived, template< class > class InfoProxyType> template<class Stat > Derived& Stats::DataWrap< Derived, InfoProxyType >::prereq (const Stat & prereq) [inline]
Set the prerequisite stat and marks this stat to print at the end of simulation.
Parameters:
prereq The prerequisite stat.
Returns:
A reference to this stat.
Definition at line 321 of file statistics.hh.
Referenced by Stats::Global::Global(), and StatTest::init().
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::self () [inline, protected]
Definition at line 211 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> const std::string& Stats::DataWrap< Derived, InfoProxyType >::setSeparator () const [inline]
Definition at line 271 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::setSeparator (const std::string & _sep) [inline]
Set the character(s) used between the name and vector number on vectors, dist, etc.
Parameters:
_sep The new separator string
Returns:
A reference to this stat.
Definition at line 266 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh