gem5: Globals Class Reference
Globals Class Reference
Container for serializing global variables (not associated with any serialized object).
Public Member Functions
const string name () const
void serialize (ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Detailed Description
Container for serializing global variables (not associated with any serialized object).
Definition at line 423 of file serialize.cc.
Member Function Documentation
const string Globals::name () const [virtual]
Implements Serializable.
Definition at line 435 of file serialize.cc.
Referenced by Serializable::unserializeGlobals().
void Globals::serialize (ostream & os)
Definition at line 441 of file serialize.cc.
References curTick(), ArmISA::i, mainEventQueue, Serializable::nameOut(), numMainEventQueues, and paramOut().
void Globals::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 455 of file serialize.cc.
References ArmISA::i, mainEventQueue, numMainEventQueues, and paramIn().
Referenced by Serializable::unserializeGlobals().
The documentation for this class was generated from the following file:
sim/serialize.cc