gem5: ArmISA::SupervisorCall Class Reference
ArmISA::SupervisorCall Class Reference
#include <faults.hh>
Public Member Functions
SupervisorCall (ExtMachInst _machInst, uint32_t _iss, ExceptionClass _overrideEc=EC_INVALID)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
bool routeToHyp (ThreadContext *tc) const
ExceptionClass ec (ThreadContext *tc) const
uint32_t iss () const
Protected Attributes
ExceptionClass overrideEc
Detailed Description
Definition at line 288 of file faults.hh.
Constructor & Destructor Documentation
ArmISA::SupervisorCall::SupervisorCall (ExtMachInst _machInst, uint32_t _iss, ExceptionClass _overrideEc = EC_INVALID) [inline]
Definition at line 293 of file faults.hh.
Member Function Documentation
ExceptionClass ArmISA::SupervisorCall::ec (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFaultVals< SupervisorCall >.
Definition at line 812 of file faults.cc.
References ArmISA::ArmFault::FaultVals::ec, ArmISA::EC_INVALID, ArmISA::EC_SVC_64, ArmISA::ArmFault::from64, overrideEc, and ArmISA::ArmFaultVals< SupervisorCall >::vals.
void ArmISA::SupervisorCall::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 770 of file faults.cc.
References ArmISA::cpsr, FullSystem, ArmISA::INTREG_R7, ArmISA::INTREG_X8, ArmISA::ArmFault::machInst, ArmISA::MISCREG_CPSR, ArmISA::mode, MipsISA::pc, ThreadContext::pcState(), ThreadContext::readIntReg(), ThreadContext::readMiscReg(), and ThreadContext::syscall().
uint32_t ArmISA::SupervisorCall::iss () const [virtual]
Reimplemented from ArmISA::ArmFaultVals< SupervisorCall >.
Definition at line 819 of file faults.cc.
References ArmISA::ArmFault::issRaw.
bool ArmISA::SupervisorCall::routeToHyp (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 796 of file faults.cc.
References ArmISA::cpsr, ArmISA::inSecureState(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_SCR, ArmISA::MODE_HYP, ArmISA::MODE_USER, ThreadContext::readMiscRegNoEffect(), and ArmISA::scr.
Member Data Documentation
ExceptionClass ArmISA::SupervisorCall::overrideEc [protected]
Definition at line 291 of file faults.hh.
Referenced by ec().
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc