gem5: Stats::VectorStandardDeviation Class Reference
Stats::VectorStandardDeviation Class Reference
["Statistic Types"]
This is a vector of StandardDeviation stats.
#include <statistics.hh>
Public Member Functions
VectorStandardDeviation & init (size_type size)
Initialize storage for this distribution.
Detailed Description
This is a vector of StandardDeviation stats.
See also:
VectorDistBase, SampleStor
Definition at line 2622 of file statistics.hh.
Member Function Documentation
VectorStandardDeviation& Stats::VectorStandardDeviation::init (size_type size) [inline]
Initialize storage for this distribution.
Parameters:
size The size of the vector.
Returns:
A reference to this distribution.
Definition at line 2632 of file statistics.hh.
References Stats::VectorDistBase< VectorStandardDeviation, SampleStor >::doInit(), and Stats::InfoAccess::setParams().
Referenced by StatTest::init().
The documentation for this class was generated from the following file:
base/statistics.hh