gem5: MinorCPU Class Reference
MinorCPU Class Reference
MinorCPU is an in-order CPU model with four fixed pipeline stages:.
#include <cpu.hh>
Classes
class MinorCPUPort
Provide a non-protected base class for Minor's Ports as derived classes are created by Fetch1 and Execute.
Public Member Functions
MinorCPU (MinorCPUParams *params)
~MinorCPU ()
void init ()
Starting, waking and initialisation.
void startup ()
void wakeup ()
Addr dbg_vtophys (Addr addr)
void regStats ()
Stats interface from SimObject (by way of BaseCPU).
Counter totalInsts () const
Simple inst count interface from BaseCPU.
Counter totalOps () const
void serializeThread (std::ostream &os, ThreadID thread_id)
void unserializeThread (Checkpoint *cp, const std::string &section, ThreadID thread_id)
void serialize (std::ostream &os)
Serialize pipeline data.
void unserialize (Checkpoint *cp, const std::string &section)
unsigned int drain (DrainManager *drain_manager)
Drain interface.
void drainResume ()
void signalDrainDone ()
Signal from Pipeline that MinorCPU should signal the DrainManager that a drain is complete and set its drainState.
void memWriteback ()
void switchOut ()
Switching interface from BaseCPU.
void takeOverFrom (BaseCPU *old_cpu)
void activateContext (ThreadID thread_id)
Thread activation interface from BaseCPU.
void suspendContext (ThreadID thread_id)
void wakeupOnEvent (unsigned int stage_id)
Interface for stages to signal that they have become active after a callback or eventq event where the pipeline itself may have already been idled.
Public Attributes
Minor::MinorActivityRecorder * activityRecorder
Activity recording for pipeline.
std::vector< Minor::MinorThread * > threads
These are thread state-representing objects for this CPU.
DrainManager * drainManager
The DrainManager passed into drain that needs be signalled when draining is complete.
Minor::MinorStats stats
Processor-specific statistics.
Protected Member Functions
MasterPort & getDataPort ()
Return a reference to the data port.
MasterPort & getInstPort ()
Return a reference to the instruction port.
Protected Attributes
Minor::Pipeline * pipeline
pipeline is a container for the clockable pipeline stage objects.
Detailed Description
MinorCPU is an in-order CPU model with four fixed pipeline stages:.
Fetch1 - fetches lines from memory Fetch2 - decomposes lines into macro-op instructions Decode - decomposes macro-ops into micro-ops Execute - executes those micro-ops
This pipeline is carried in the MinorCPU::pipeline object. The exec_context interface is not carried by MinorCPU but by Minor::ExecContext objects created by Minor::Execute.
Definition at line 78 of file cpu.hh.
Constructor & Destructor Documentation
MinorCPU::MinorCPU (MinorCPUParams * params)
Definition at line 49 of file cpu.cc.
References activityRecorder, fatal, FullSystem, Minor::Pipeline::getActivityRecorder(), SimpleThread::getTC(), ThreadContext::Halted, init(), pipeline, SimpleThread::setStatus(), ArmISA::tc, and threads.
MinorCPU::~MinorCPU ()
Definition at line 83 of file cpu.cc.
References pipeline, and threads.
Member Function Documentation
void MinorCPU::activateContext (ThreadID thread_id)
Thread activation interface from BaseCPU.
Definition at line 279 of file cpu.cc.
References Minor::Pipeline::CPUStageId, Ticked::cyclesSinceLastStopped(), DPRINTF, pipeline, Minor::MinorStats::quiesceCycles, Ticked::resetLastStopped(), stats, threads, Minor::Pipeline::wakeupFetch(), and wakeupOnEvent().
Referenced by startup().
Addr MinorCPU::dbg_vtophys (Addr addr)
Definition at line 163 of file cpu.cc.
References panic.
unsigned int MinorCPU::drain (DrainManager * drain_manager)
Drain interface.
Definition at line 199 of file cpu.cc.
References DPRINTF, Minor::Pipeline::drain(), drainManager, and pipeline.
void MinorCPU::drainResume ()
Definition at line 227 of file cpu.cc.
References DPRINTF, Drainable::Drained, Minor::Pipeline::drainResume(), fatal, pipeline, Drainable::Running, X86ISA::system, and wakeup().
MasterPort & MinorCPU::getDataPort () [protected]
Return a reference to the data port.
Definition at line 327 of file cpu.cc.
References Minor::Pipeline::getDataPort(), and pipeline.
MasterPort & MinorCPU::getInstPort () [protected]
Return a reference to the instruction port.
Definition at line 322 of file cpu.cc.
References Minor::Pipeline::getInstPort(), and pipeline.
void MinorCPU::init ()
Starting, waking and initialisation.
Definition at line 93 of file cpu.cc.
References fatal, FullSystem, AlphaISA::initCPU(), ThreadContext::initMemProxies(), X86ISA::system, ArmISA::tc, and threads.
Referenced by MinorCPU().
void MinorCPU::memWriteback ()
Definition at line 251 of file cpu.cc.
References DPRINTF.
void MinorCPU::regStats ()
Stats interface from SimObject (by way of BaseCPU).
Definition at line 125 of file cpu.cc.
References name(), pipeline, Ticked::regStats(), Minor::MinorStats::regStats(), and stats.
void MinorCPU::serialize (std::ostream & os)
Serialize pipeline data.
Definition at line 149 of file cpu.cc.
References pipeline, and Ticked::serialize().
void MinorCPU::serializeThread (std::ostream & os, ThreadID thread_id)
Definition at line 133 of file cpu.cc.
References threads.
void MinorCPU::signalDrainDone ()
Signal from Pipeline that MinorCPU should signal the DrainManager that a drain is complete and set its drainState.
Definition at line 218 of file cpu.cc.
References DPRINTF, Drainable::Drained, drainManager, and DrainManager::signalDrainDone().
Referenced by Minor::Pipeline::evaluate().
void MinorCPU::startup ()
Definition at line 185 of file cpu.cc.
References activateContext(), DPRINTF, ArmISA::i, and threads.
void MinorCPU::suspendContext (ThreadID thread_id)
Definition at line 296 of file cpu.cc.
References DPRINTF, and threads.
void MinorCPU::switchOut ()
Switching interface from BaseCPU.
Definition at line 257 of file cpu.cc.
References activityRecorder, DPRINTF, and ActivityRecorder::reset().
void MinorCPU::takeOverFrom (BaseCPU * old_cpu)
Definition at line 269 of file cpu.cc.
References DPRINTF.
Counter MinorCPU::totalInsts () const
Simple inst count interface from BaseCPU.
Definition at line 333 of file cpu.cc.
References ArmISA::i, and threads.
Counter MinorCPU::totalOps () const
Definition at line 344 of file cpu.cc.
References ArmISA::i, and threads.
void MinorCPU::unserialize (Checkpoint * cp, const std::string & section)
Definition at line 156 of file cpu.cc.
References pipeline, and Ticked::unserialize().
void MinorCPU::unserializeThread (Checkpoint * cp, const std::string & section, ThreadID thread_id)
Definition at line 139 of file cpu.cc.
References fatal, and threads.
void MinorCPU::wakeup ()
Reimplemented from BaseCPU.
Definition at line 172 of file cpu.cc.
References DPRINTF, ArmISA::i, ThreadContext::Suspended, and threads.
Referenced by drainResume().
void MinorCPU::wakeupOnEvent (unsigned int stage_id)
Interface for stages to signal that they have become active after a callback or eventq event where the pipeline itself may have already been idled.
The stage argument should be from the enumeration Pipeline::StageId
Definition at line 304 of file cpu.cc.
References ActivityRecorder::activateStage(), activityRecorder, DPRINTF, pipeline, and Ticked::start().
Referenced by activateContext(), Minor::Execute::drain(), Minor::Execute::drainResume(), Minor::Fetch1::evaluate(), Minor::Execute::evaluate(), Minor::LSQ::SplitDataRequest::finish(), Minor::LSQ::SingleDataRequest::finish(), Minor::Fetch1::FetchRequest::finish(), Minor::LSQ::StoreBuffer::insert(), Minor::LSQ::recvTimingResp(), Minor::Fetch1::recvTimingResp(), Minor::Fetch1::tryToSendToTransfers(), and Minor::Execute::wakeupFetch().
Member Data Documentation
Minor::MinorActivityRecorder* MinorCPU::activityRecorder
Activity recording for pipeline.
This belongs to Pipeline but stages will access it through the CPU as the MinorCPU object actually mediates idling behaviour
Definition at line 89 of file cpu.hh.
Referenced by Minor::Fetch2::evaluate(), Minor::Fetch1::evaluate(), Minor::Execute::evaluate(), Minor::Decode::evaluate(), Minor::Execute::issue(), MinorCPU(), switchOut(), and wakeupOnEvent().
DrainManager* MinorCPU::drainManager
The DrainManager passed into drain that needs be signalled when draining is complete.
Definition at line 117 of file cpu.hh.
Referenced by drain(), and signalDrainDone().
Minor::Pipeline* MinorCPU::pipeline [protected]
pipeline is a container for the clockable pipeline stage objects.
Elements of pipeline call TheISA to implement the model.
Definition at line 83 of file cpu.hh.
Referenced by activateContext(), drain(), drainResume(), getDataPort(), getInstPort(), MinorCPU(), regStats(), serialize(), unserialize(), wakeupOnEvent(), and ~MinorCPU().
Minor::MinorStats MinorCPU::stats
Processor-specific statistics.
Definition at line 140 of file cpu.hh.
Referenced by activateContext(), Minor::Execute::commit(), Minor::Execute::commitInst(), Minor::Execute::doInstCommitAccounting(), and regStats().
std::vector<Minor::MinorThread *> MinorCPU::threads
These are thread state-representing objects for this CPU.
If you need a ThreadContext for *any* reason, use threads[threadId]->getTC()
Definition at line 94 of file cpu.hh.
Referenced by activateContext(), Minor::Execute::commitInst(), Minor::Execute::doInstCommitAccounting(), Minor::Execute::executeMemRefInst(), Minor::Fetch1::fetchLine(), Minor::Execute::handleMemResponse(), init(), MinorCPU(), Minor::ExecContext::readRegOtherThread(), serializeThread(), Minor::ExecContext::setRegOtherThread(), startup(), suspendContext(), totalInsts(), totalOps(), Minor::LSQ::tryToSendToTransfers(), unserializeThread(), wakeup(), and ~MinorCPU().
The documentation for this class was generated from the following files:
cpu/minor/cpu.hh
cpu/minor/cpu.cc