gem5: ArmSystem Class Reference
ArmSystem Class Reference
#include <system.hh>
Public Types
typedef ArmSystemParams Params
Public Member Functions
const Params * params () const
ArmSystem (Params *p)
~ArmSystem ()
virtual void initState ()
Initialise the system.
virtual Addr fixFuncEventAddr (Addr addr)
Fix up an address used to match PCs for hooking simulator events on to target function executions.
bool haveSecurity () const
Returns true if this system implements the Security Extensions.
bool haveLPAE () const
Returns true if this system implements the Large Physical Address Extension.
bool haveVirtualization () const
Returns true if this system implements the virtualization Extensions.
void setGenericTimer (GenericTimer *generic_timer)
Sets the pointer to the Generic Timer.
GenericTimer * getGenericTimer () const
Get a pointer to the system's generic timer model.
bool highestELIs64 () const
Returns true if the register width of the highest implemented exception level is 64 bits (ARMv8).
ExceptionLevel highestEL () const
Returns the highest implemented exception level.
Addr resetAddr64 () const
Returns the reset address if the highest implemented exception level is 64 bits (ARMv8).
bool haveLargeAsid64 () const
Returns true if ASID is 16 bits in AArch64 (ARMv8).
uint8_t physAddrRange64 () const
Returns the supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8).
uint8_t physAddrRange () const
Returns the supported physical address range in bits.
Addr physAddrMask () const
Returns the physical address mask.
Static Public Member Functions
static bool haveSecurity (ThreadContext *tc)
Returns true if the system of a specific thread context implements the Security Extensions.
static bool haveVirtualization (ThreadContext *tc)
Returns true if the system of a specific thread context implements the virtualization Extensions.
static bool haveLPAE (ThreadContext *tc)
Returns true if the system of a specific thread context implements the Large Physical Address Extension.
static bool highestELIs64 (ThreadContext *tc)
Returns true if the register width of the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8).
static ExceptionLevel highestEL (ThreadContext *tc)
Returns the highest implemented exception level for the system of a specific thread context.
static Addr resetAddr64 (ThreadContext *tc)
Returns the reset address if the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8).
static uint8_t physAddrRange (ThreadContext *tc)
Returns the supported physical address range in bits for the system of a specific thread context.
static Addr physAddrMask (ThreadContext *tc)
Returns the physical address mask for the system of a specific thread context.
static bool haveLargeAsid64 (ThreadContext *tc)
Returns true if ASID is 16 bits for the system of a specific thread context while in AArch64 (ARMv8).
Public Attributes
bool multiProc
true if this a multiprocessor system
Protected Attributes
Linux::DebugPrintkEvent * debugPrintkEvent
PC based event to skip the dprink() call and emulate its functionality.
ObjectFile * bootldr
Pointer to the bootloader object.
const bool _haveSecurity
True if this system implements the Security Extensions.
const bool _haveLPAE
True if this system implements the Large Physical Address Extension.
const bool _haveVirtualization
True if this system implements the virtualization Extensions.
GenericTimer * _genericTimer
Pointer to the Generic Timer wrapper.
bool _highestELIs64
True if the register width of the highest implemented exception level is 64 bits (ARMv8).
const Addr _resetAddr64
Reset address if the highest implemented exception level is 64 bits (ARMv8).
const uint8_t _physAddrRange64
Supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8).
const bool _haveLargeAsid64
True if ASID is 16 bits in AArch64 (ARMv8).
Detailed Description
Definition at line 58 of file system.hh.
Member Typedef Documentation
typedef ArmSystemParams ArmSystem::Params
Reimplemented from System.
Reimplemented in FreebsdArmSystem, LinuxArmSystem, and GenericArmSystem.
Definition at line 116 of file system.hh.
Constructor & Destructor Documentation
ArmSystem::ArmSystem (Params * p)
Definition at line 56 of file system.cc.
References _highestELIs64, _physAddrRange64, ObjectFile::Arm, ObjectFile::Arm64, bootldr, createObjectFile(), debugPrintkEvent, debugSymbolTable, fatal, ObjectFile::getArch(), ObjectFile::loadGlobalSymbols(), and warn.
ArmSystem::~ArmSystem ()
Definition at line 165 of file system.cc.
References debugPrintkEvent.
Member Function Documentation
virtual Addr ArmSystem::fixFuncEventAddr (Addr addr) [inline, virtual]
Fix up an address used to match PCs for hooking simulator events on to target function executions.
See comment in system.cc for details.
Reimplemented from System.
Definition at line 131 of file system.hh.
GenericTimer* ArmSystem::getGenericTimer () const [inline]
Get a pointer to the system's generic timer model.
Definition at line 162 of file system.hh.
References _genericTimer.
bool ArmSystem::haveLargeAsid64 (ThreadContext * tc) [static]
Returns true if ASID is 16 bits for the system of a specific thread context while in AArch64 (ARMv8).
Definition at line 224 of file system.cc.
References ThreadContext::getSystemPtr(), and haveLargeAsid64().
bool ArmSystem::haveLargeAsid64 () const [inline]
Returns true if ASID is 16 bits in AArch64 (ARMv8).
Definition at line 184 of file system.hh.
References _haveLargeAsid64.
Referenced by haveLargeAsid64(), and ArmISA::TableWalker::TableWalker().
bool ArmSystem::haveLPAE (ThreadContext * tc) [static]
Returns true if the system of a specific thread context implements the Large Physical Address Extension.
Definition at line 172 of file system.cc.
References FullSystem, ThreadContext::getSystemPtr(), and haveLPAE().
bool ArmSystem::haveLPAE () const [inline]
Returns true if this system implements the Large Physical Address Extension.
Definition at line 148 of file system.hh.
References _haveLPAE.
Referenced by haveLPAE(), and ArmISA::TableWalker::TableWalker().
bool ArmSystem::haveSecurity (ThreadContext * tc) [static]
Returns true if the system of a specific thread context implements the Security Extensions.
Definition at line 154 of file system.cc.
References FullSystem, ThreadContext::getSystemPtr(), and haveSecurity().
bool ArmSystem::haveSecurity () const [inline]
Returns true if this system implements the Security Extensions.
Definition at line 144 of file system.hh.
References _haveSecurity.
Referenced by ArmISA::FastInterrupt::abortDisable(), ArmISA::Interrupt::abortDisable(), ArmISA::AbortFault< T >::abortDisable(), ArmISA::ArmStaticInst::cpsrWriteByInstr(), ArmISA::FastInterrupt::fiqDisable(), ArmISA::ArmFault::getVector(), ArmISA::ArmFault::getVector64(), haveSecurity(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), ArmISA::SystemError::routeToMonitor(), ArmISA::FastInterrupt::routeToMonitor(), ArmISA::Interrupt::routeToMonitor(), and ArmISA::TableWalker::TableWalker().
bool ArmSystem::haveVirtualization (ThreadContext * tc) [static]
Returns true if the system of a specific thread context implements the virtualization Extensions.
Definition at line 183 of file system.cc.
References FullSystem, ThreadContext::getSystemPtr(), and haveVirtualization().
bool ArmSystem::haveVirtualization () const [inline]
Returns true if this system implements the virtualization Extensions.
Definition at line 153 of file system.hh.
References _haveVirtualization.
Referenced by ArmISA::ArmStaticInst::cpsrWriteByInstr(), ArmISA::FastInterrupt::fiqDisable(), ArmISA::ArmFault::getVector(), haveVirtualization(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke(), and ArmISA::TableWalker::TableWalker().
ExceptionLevel ArmSystem::highestEL (ThreadContext * tc) [static]
Returns the highest implemented exception level for the system of a specific thread context.
Definition at line 200 of file system.cc.
References ThreadContext::getSystemPtr(), and highestEL().
ExceptionLevel ArmSystem::highestEL () const [inline]
Returns the highest implemented exception level.
Definition at line 169 of file system.hh.
References _haveSecurity, ArmISA::EL1, and ArmISA::EL3.
Referenced by highestEL(), and ArmISA::ArmFault::invoke().
bool ArmSystem::highestELIs64 (ThreadContext * tc) [static]
Returns true if the register width of the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8).
Definition at line 194 of file system.cc.
References ThreadContext::getSystemPtr(), and highestELIs64().
bool ArmSystem::highestELIs64 () const [inline]
Returns true if the register width of the highest implemented exception level is 64 bits (ARMv8).
Definition at line 166 of file system.hh.
References _highestELIs64.
Referenced by highestELIs64(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::setSyndrome(), and ArmISA::Interrupts::takeInt().
void ArmSystem::initState () [virtual]
Initialise the system.
Reimplemented from System.
Reimplemented in FreebsdArmSystem, LinuxArmSystem, and GenericArmSystem.
Definition at line 98 of file system.cc.
References _highestELIs64, bootldr, ObjectFile::entryPoint(), fatal, ArmISA::i, inform, System::kernelEntry, System::loadAddrMask, System::loadAddrOffset, ObjectFile::loadSections(), MipsISA::p, params(), System::physProxy, System::threadContexts, and PortProxy::writeBlob().
const Params* ArmSystem::params () const [inline]
Reimplemented from System.
Reimplemented in FreebsdArmSystem, LinuxArmSystem, and GenericArmSystem.
Definition at line 118 of file system.hh.
References System::_params.
Referenced by initState().
Addr ArmSystem::physAddrMask (ThreadContext * tc) [static]
Returns the physical address mask for the system of a specific thread context.
Definition at line 218 of file system.cc.
References ThreadContext::getSystemPtr(), and physAddrMask().
Addr ArmSystem::physAddrMask () const [inline]
Returns the physical address mask.
Definition at line 201 of file system.hh.
References ArmISA::mask, and physAddrRange().
Referenced by physAddrMask().
uint8_t ArmSystem::physAddrRange (ThreadContext * tc) [static]
Returns the supported physical address range in bits for the system of a specific thread context.
Definition at line 212 of file system.cc.
References ThreadContext::getSystemPtr(), and physAddrRange().
uint8_t ArmSystem::physAddrRange () const [inline]
Returns the supported physical address range in bits.
Definition at line 191 of file system.hh.
References _haveLPAE, _highestELIs64, and _physAddrRange64.
Referenced by physAddrMask(), physAddrRange(), and ArmISA::TableWalker::TableWalker().
uint8_t ArmSystem::physAddrRange64 () const [inline]
Returns the supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8).
Definition at line 188 of file system.hh.
References _physAddrRange64.
Addr ArmSystem::resetAddr64 (ThreadContext * tc) [static]
Returns the reset address if the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8).
Definition at line 206 of file system.cc.
References ThreadContext::getSystemPtr(), and resetAddr64().
Addr ArmSystem::resetAddr64 () const [inline]
Returns the reset address if the highest implemented exception level is 64 bits (ARMv8).
Definition at line 181 of file system.hh.
References _resetAddr64.
Referenced by ArmISA::Reset::invoke(), and resetAddr64().
void ArmSystem::setGenericTimer (GenericTimer * generic_timer) [inline]
Sets the pointer to the Generic Timer.
Definition at line 156 of file system.hh.
References _genericTimer.
Member Data Documentation
GenericTimer* ArmSystem::_genericTimer [protected]
Pointer to the Generic Timer wrapper.
Definition at line 90 of file system.hh.
Referenced by getGenericTimer(), and setGenericTimer().
const bool ArmSystem::_haveLargeAsid64 [protected]
True if ASID is 16 bits in AArch64 (ARMv8).
Definition at line 113 of file system.hh.
Referenced by haveLargeAsid64().
const bool ArmSystem::_haveLPAE [protected]
True if this system implements the Large Physical Address Extension.
Definition at line 80 of file system.hh.
Referenced by haveLPAE(), and physAddrRange().
const bool ArmSystem::_haveSecurity [protected]
True if this system implements the Security Extensions.
Definition at line 75 of file system.hh.
Referenced by haveSecurity(), and highestEL().
const bool ArmSystem::_haveVirtualization [protected]
True if this system implements the virtualization Extensions.
Definition at line 85 of file system.hh.
Referenced by haveVirtualization().
bool ArmSystem::_highestELIs64 [protected]
True if the register width of the highest implemented exception level is 64 bits (ARMv8).
Definition at line 96 of file system.hh.
Referenced by ArmSystem(), highestELIs64(), initState(), and physAddrRange().
const uint8_t ArmSystem::_physAddrRange64 [protected]
Supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8).
Definition at line 108 of file system.hh.
Referenced by ArmSystem(), physAddrRange(), and physAddrRange64().
const Addr ArmSystem::_resetAddr64 [protected]
Reset address if the highest implemented exception level is 64 bits (ARMv8).
Definition at line 102 of file system.hh.
Referenced by resetAddr64().
ObjectFile* ArmSystem::bootldr [protected]
Pointer to the bootloader object.
Definition at line 70 of file system.hh.
Referenced by ArmSystem(), and initState().
Linux::DebugPrintkEvent* ArmSystem::debugPrintkEvent [protected]
PC based event to skip the dprink() call and emulate its functionality.
Definition at line 65 of file system.hh.
Referenced by ArmSystem(), and ~ArmSystem().
bool ArmSystem::multiProc
true if this a multiprocessor system
Definition at line 141 of file system.hh.
The documentation for this class was generated from the following files:
arch/arm/system.hh
arch/arm/system.cc