gem5: Minor::LSQ::StoreBuffer Class Reference
Minor::LSQ::StoreBuffer Class Reference
Store buffer.
#include <lsq.hh>
Public Member Functions
StoreBuffer (std::string name_, LSQ &lsq_, unsigned int store_buffer_size, unsigned int store_limit_per_cycle)
bool canInsert () const
Can a new request be inserted into the queue?
void deleteRequest (LSQRequestPtr request)
Delete the given request and free the slot it occupied.
void insert (LSQRequestPtr request)
Insert a request at the back of the queue.
AddrRangeCoverage canForwardDataToLoad (LSQRequestPtr request, unsigned int &found_slot)
Look for a store which satisfies the given load.
void forwardStoreData (LSQRequestPtr load, unsigned int slot_number)
Fill the given packet with appropriate date from slot slot_number.
unsigned int numUnissuedStores ()
Number of stores in the store buffer which have not been completely issued to the memory system.
void countIssuedStore (LSQRequestPtr request)
Count a store being issued to memory by decrementing numUnissuedAccesses.
bool isDrained () const
Drained if there is absolutely nothing left in the buffer.
void step ()
Try to issue more stores to memory.
void minorTrace () const
Report queue contents for MinorTrace.
Public Attributes
LSQ & lsq
My owner.
const unsigned int numSlots
Number of slots, this is a bound on the size of slots.
const unsigned int storeLimitPerCycle
Maximum number of stores that can be issued per cycle.
std::deque< LSQRequestPtr > slots
Queue of store requests on their way to memory.
unsigned int numUnissuedAccesses
Number of occupied slots which have not yet issued a memory access.
Detailed Description
Store buffer.
This contains stores which have been committed but whose memory transfers have not yet been issued. Load data can be forwarded out of the store buffer
Definition at line 466 of file lsq.hh.
Constructor & Destructor Documentation
Minor::LSQ::StoreBuffer::StoreBuffer (std::string name_, LSQ & lsq_, unsigned int store_buffer_size, unsigned int store_limit_per_cycle)
Definition at line 1533 of file lsq.cc.
Member Function Documentation
LSQ::AddrRangeCoverage Minor::LSQ::StoreBuffer::canForwardDataToLoad (LSQRequestPtr request, unsigned int & found_slot)
Look for a store which satisfies the given load.
Returns an indication whether the forwarding request can be wholly, partly or not all all satisfied. If the request can be wholly satisfied, the store buffer slot number which can be used is returned in found_slot
Definition at line 667 of file lsq.cc.
References Minor::LSQ::LSQRequest::containsAddrRangeOf(), DPRINTF, Request::getPaddr(), Request::getSize(), ArmISA::i, Minor::LSQ::NoAddrRangeCoverage, Minor::LSQ::LSQRequest::packet, Minor::LSQ::LSQRequest::request, and slots.
Referenced by Minor::LSQ::tryToSendToTransfers().
bool Minor::LSQ::StoreBuffer::canInsert () const
Can a new request be inserted into the queue?
Definition at line 624 of file lsq.cc.
References numSlots, and slots.
Referenced by Minor::LSQ::canPushIntoStoreBuffer(), Minor::LSQ::findResponse(), and insert().
void Minor::LSQ::StoreBuffer::countIssuedStore (LSQRequestPtr request)
Count a store being issued to memory by decrementing numUnissuedAccesses.
Does not count barrier requests as they will be handles as barriers are cleared from the buffer
Definition at line 733 of file lsq.cc.
References Minor::LSQ::LSQRequest::isBarrier(), and numUnissuedAccesses.
Referenced by Minor::LSQ::recvReqRetry(), and step().
void Minor::LSQ::StoreBuffer::deleteRequest (LSQRequestPtr request)
Delete the given request and free the slot it occupied.
Definition at line 631 of file lsq.cc.
References DPRINTF, Minor::LSQ::LSQRequest::inst, and slots.
Referenced by Minor::LSQ::recvTimingResp().
void Minor::LSQ::StoreBuffer::forwardStoreData (LSQRequestPtr load, unsigned int slot_number)
Fill the given packet with appropriate date from slot slot_number.
Definition at line 703 of file lsq.cc.
References Minor::LSQ::LSQRequest::containsAddrRangeOf(), DPRINTF, Minor::LSQ::FullAddrRangeCoverage, Request::getPaddr(), Packet::getPtr(), Request::getSize(), Minor::LSQ::LSQRequest::isLoad, Minor::LSQ::LSQRequest::packet, Minor::LSQ::LSQRequest::request, and slots.
Referenced by Minor::LSQ::tryToSendToTransfers().
void Minor::LSQ::StoreBuffer::insert (LSQRequestPtr request)
Insert a request at the back of the queue.
Definition at line 645 of file lsq.cc.
References canInsert(), Minor::LSQ::LSQRequest::Complete, Minor::LSQ::cpu, DPRINTF, Minor::Pipeline::ExecuteStageId, Minor::LSQ::LSQRequest::inst, lsq, Named::name(), numUnissuedAccesses, Minor::LSQ::LSQRequest::setState(), slots, Minor::LSQ::LSQRequest::state, Minor::LSQ::LSQRequest::StoreInStoreBuffer, MinorCPU::wakeupOnEvent(), and warn.
Referenced by Minor::LSQ::completeMemBarrierInst(), and Minor::LSQ::sendStoreToStoreBuffer().
bool Minor::LSQ::StoreBuffer::isDrained () const [inline]
Drained if there is absolutely nothing left in the buffer.
Definition at line 523 of file lsq.hh.
References slots.
Referenced by Minor::LSQ::isDrained().
void Minor::LSQ::StoreBuffer::minorTrace () const
Report queue contents for MinorTrace.
Definition at line 829 of file lsq.cc.
References ArmISA::i, MINORTRACE, numSlots, numUnissuedAccesses, X86ISA::os, Minor::LSQ::LSQRequest::reportData(), and slots.
Referenced by Minor::LSQ::minorTrace().
unsigned int Minor::LSQ::StoreBuffer::numUnissuedStores () [inline]
Number of stores in the store buffer which have not been completely issued to the memory system.
Definition at line 515 of file lsq.hh.
References numUnissuedAccesses.
Referenced by Minor::LSQ::needsToTick().
void Minor::LSQ::StoreBuffer::step ()
Try to issue more stores to memory.
Definition at line 742 of file lsq.cc.
References Minor::LSQ::canSendToMemorySystem(), Minor::LSQ::clearMemBarrier(), countIssuedStore(), DPRINTF, ArmISA::i, Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::isBarrier(), Minor::LSQ::LSQRequest::isComplete(), lsq, Minor::LSQ::MemoryNeedsRetry, Minor::LSQ::MemoryRunning, numUnissuedAccesses, Minor::LSQ::LSQRequest::sentAllPackets(), slots, Minor::LSQ::LSQRequest::state, Minor::LSQ::state, Minor::LSQ::LSQRequest::StoreBufferIssuing, storeLimitPerCycle, and Minor::LSQ::tryToSend().
Referenced by Minor::LSQ::step().
Member Data Documentation
LSQ& Minor::LSQ::StoreBuffer::lsq
My owner.
Definition at line 470 of file lsq.hh.
Referenced by insert(), and step().
const unsigned int Minor::LSQ::StoreBuffer::numSlots
Number of slots, this is a bound on the size of slots.
Definition at line 473 of file lsq.hh.
Referenced by canInsert(), and minorTrace().
unsigned int Minor::LSQ::StoreBuffer::numUnissuedAccesses
Number of occupied slots which have not yet issued a memory access.
Definition at line 484 of file lsq.hh.
Referenced by countIssuedStore(), insert(), minorTrace(), numUnissuedStores(), and step().
std::deque<LSQRequestPtr> Minor::LSQ::StoreBuffer::slots
Queue of store requests on their way to memory.
Definition at line 480 of file lsq.hh.
Referenced by canForwardDataToLoad(), canInsert(), deleteRequest(), forwardStoreData(), insert(), isDrained(), minorTrace(), and step().
const unsigned int Minor::LSQ::StoreBuffer::storeLimitPerCycle
Maximum number of stores that can be issued per cycle.
Definition at line 476 of file lsq.hh.
Referenced by step().
The documentation for this class was generated from the following files:
cpu/minor/lsq.hh
cpu/minor/lsq.cc