gem5: LSB_CountingBloomFilter Class Reference
LSB_CountingBloomFilter Class Reference
#include <LSB_CountingBloomFilter.hh>
Public Member Functions
LSB_CountingBloomFilter (std::string config)
~LSB_CountingBloomFilter ()
void clear ()
void increment (const Address &addr)
void decrement (const Address &addr)
void merge (AbstractBloomFilter *other_filter)
void set (const Address &addr)
void unset (const Address &addr)
bool isSet (const Address &addr)
int getCount (const Address &addr)
int getTotalCount ()
int getIndex (const Address &addr)
int readBit (const int index)
void writeBit (const int index, const int value)
void print (std::ostream &out) const
Private Member Functions
int get_index (const Address &addr)
Private Attributes
std::vector< int > m_filter
int m_filter_size
int m_filter_size_bits
int m_count_bits
int m_count
Detailed Description
Definition at line 39 of file LSB_CountingBloomFilter.hh.
Constructor & Destructor Documentation
LSB_CountingBloomFilter::LSB_CountingBloomFilter (std::string config)
LSB_CountingBloomFilter::~LSB_CountingBloomFilter ()
Definition at line 55 of file LSB_CountingBloomFilter.cc.
Member Function Documentation
void LSB_CountingBloomFilter::clear () [virtual]
Implements AbstractBloomFilter.
Definition at line 60 of file LSB_CountingBloomFilter.cc.
References ArmISA::i, m_filter, and m_filter_size.
void LSB_CountingBloomFilter::decrement (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 77 of file LSB_CountingBloomFilter.cc.
References get_index(), ArmISA::i, and m_filter.
int LSB_CountingBloomFilter::get_index (const Address & addr) [private]
Definition at line 151 of file LSB_CountingBloomFilter.cc.
References Address::bitSelect(), and RubySystem::getBlockSizeBits().
Referenced by decrement(), getCount(), getIndex(), and increment().
int LSB_CountingBloomFilter::getCount (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 110 of file LSB_CountingBloomFilter.cc.
References get_index(), and m_filter.
int LSB_CountingBloomFilter::getIndex (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 127 of file LSB_CountingBloomFilter.cc.
References get_index().
int LSB_CountingBloomFilter::getTotalCount () [virtual]
Implements AbstractBloomFilter.
Definition at line 116 of file LSB_CountingBloomFilter.cc.
References X86ISA::count, ArmISA::i, m_filter, and m_filter_size.
void LSB_CountingBloomFilter::increment (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 68 of file LSB_CountingBloomFilter.cc.
References get_index(), ArmISA::i, m_count, and m_filter.
bool LSB_CountingBloomFilter::isSet (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 103 of file LSB_CountingBloomFilter.cc.
void LSB_CountingBloomFilter::merge (AbstractBloomFilter * other_filter)
Definition at line 85 of file LSB_CountingBloomFilter.cc.
void LSB_CountingBloomFilter::print (std::ostream & out) const [virtual]
Implements AbstractBloomFilter.
int LSB_CountingBloomFilter::readBit (const int index) [virtual]
Implements AbstractBloomFilter.
Definition at line 138 of file LSB_CountingBloomFilter.cc.
void LSB_CountingBloomFilter::set (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 91 of file LSB_CountingBloomFilter.cc.
void LSB_CountingBloomFilter::unset (const Address & addr) [virtual]
Implements AbstractBloomFilter.
Definition at line 97 of file LSB_CountingBloomFilter.cc.
void LSB_CountingBloomFilter::writeBit (const int index, const int value) [virtual]
Implements AbstractBloomFilter.
Definition at line 145 of file LSB_CountingBloomFilter.cc.
Member Data Documentation
int LSB_CountingBloomFilter::m_count [private]
Definition at line 69 of file LSB_CountingBloomFilter.hh.
Referenced by increment().
int LSB_CountingBloomFilter::m_count_bits [private]
Definition at line 68 of file LSB_CountingBloomFilter.hh.
std::vector<int> LSB_CountingBloomFilter::m_filter [private]
Definition at line 64 of file LSB_CountingBloomFilter.hh.
Referenced by clear(), decrement(), getCount(), getTotalCount(), and increment().
int LSB_CountingBloomFilter::m_filter_size [private]
Definition at line 65 of file LSB_CountingBloomFilter.hh.
Referenced by clear(), and getTotalCount().
int LSB_CountingBloomFilter::m_filter_size_bits [private]
Definition at line 66 of file LSB_CountingBloomFilter.hh.
The documentation for this class was generated from the following files:
mem/ruby/filters/LSB_CountingBloomFilter.hh
mem/ruby/filters/LSB_CountingBloomFilter.cc