gem5: Random Class Reference
Random Class Reference
#include <random.hh>
Public Member Functions
Random ()
Random (uint32_t s)
~Random ()
void init (uint32_t s)
template<typename T >
std::enable_if
< std::is_integral< T >::value,
T >::type random ()
Use the SFINAE idiom to choose an implementation based on whether the type is integral or floating point.
template<typename T >
std::enable_if
< std::is_floating_point< T >
::value, T >::type random ()
template<typename T >
std::enable_if
< std::is_integral< T >::value,
T >::type random (T min, T max)
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Attributes
std::mt19937_64 gen
Detailed Description
Definition at line 60 of file random.hh.
Constructor & Destructor Documentation
Random::Random ()
Definition at line 51 of file random.cc.
References init().
Random::Random (uint32_t s)
Definition at line 57 of file random.cc.
References init().
Random::~Random ()
Definition at line 62 of file random.cc.
Member Function Documentation
void Random::init (uint32_t s)
Definition at line 67 of file random.cc.
References gen.
Referenced by Random().
template<typename T > std::enable_if<std::is_integral<T>::value, T>::type Random::random (T min, T max) [inline]
Definition at line 99 of file random.hh.
References Stats::dist, and gen.
template<typename T > std::enable_if<std::is_floating_point<T>::value, T>::type Random::random () [inline]
Definition at line 90 of file random.hh.
References Stats::dist, and gen.
template<typename T > std::enable_if<std::is_integral<T>::value, T>::type Random::random () [inline]
Use the SFINAE idiom to choose an implementation based on whether the type is integral or floating point.
Definition at line 81 of file random.hh.
References Stats::dist, and gen.
Referenced by Check::Check(), RubyMemoryControl::executeCycle(), RandomRepl::findVictim(), NetworkTest::generatePkt(), DramGen::genStartAddr(), SimpleMemory::getLatency(), DramGen::getNextPacket(), RandomGen::getNextPacket(), LinearGen::getNextPacket(), CheckTable::getRandomCheck(), Check::initiate(), SeriesRequestGenerator::initiate(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), RandomGen::nextPacketTick(), LinearGen::nextPacketTick(), PerfectSwitch::operateVnet(), StridePrefetcher::pcTableVictim(), Check::pickInitiatingNode(), Check::pickValue(), RubyMemoryControl::queueReady(), random_time(), NetworkTest::tick(), MemTest::tick(), DefaultFetch< Impl >::tick(), TrafficGen::transition(), and EtherLink::Link::transmit().
void Random::serialize (std::ostream & os)
Definition at line 73 of file random.cc.
References gen, panic, and paramOut().
void Random::unserialize (Checkpoint * cp, const std::string & section)
Definition at line 85 of file random.cc.
References gen, optParamIn(), and panic.
Member Data Documentation
std::mt19937_64 Random::gen [private]
Definition at line 65 of file random.hh.
Referenced by init(), random(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
base/random.hh
base/random.cc