gem5: BaseRemoteGDB::InputEvent Class Reference
BaseRemoteGDB::InputEvent Class Reference
#include <remote_gdb.hh>
Public Member Functions
InputEvent (BaseRemoteGDB *g, int fd, int e)
void process (int revent)
Protected Attributes
BaseRemoteGDB * gdb
Detailed Description
Definition at line 108 of file remote_gdb.hh.
Constructor & Destructor Documentation
BaseRemoteGDB::InputEvent::InputEvent (BaseRemoteGDB * g, int fd, int e)
Definition at line 243 of file remote_gdb.cc.
Member Function Documentation
void BaseRemoteGDB::InputEvent::process (int revent) [virtual]
Implements PollEvent.
Definition at line 248 of file remote_gdb.cc.
References BaseRemoteGDB::descheduleInstCommitEvent(), BaseRemoteGDB::detach(), gdb, BaseRemoteGDB::scheduleInstCommitEvent(), BaseRemoteGDB::trapEvent, and BaseRemoteGDB::TrapEvent::type().
Member Data Documentation
BaseRemoteGDB* BaseRemoteGDB::InputEvent::gdb [protected]
Definition at line 111 of file remote_gdb.hh.
Referenced by process().
The documentation for this class was generated from the following files:
base/remote_gdb.hh
base/remote_gdb.cc