gem5: AddressCounterTable Class Reference
AddressCounterTable Class Reference
#include <stl_tables.hh>
Public Member Functions
AddressCounterTable ()
bool exists (const Addr addr) const
void insert (Addr addr, uint64_t n=0)
void erase (Addr addr)
const uint64_t getCount (Addr addr) const
Detailed Description
Definition at line 24 of file stl_tables.hh.
Constructor & Destructor Documentation
AddressCounterTable::AddressCounterTable () [inline]
Definition at line 27 of file stl_tables.hh.
Member Function Documentation
void AddressCounterTable::erase (Addr addr) [inline]
Reimplemented in AddressMapper.
Definition at line 36 of file stl_tables.hh.
References panic.
Referenced by AddressTracer::victim().
bool AddressCounterTable::exists (const Addr addr) const [inline]
Definition at line 29 of file stl_tables.hh.
Referenced by insert(), and AddressMapper::put_addr().
const uint64_t AddressCounterTable::getCount (Addr addr) const [inline]
Definition at line 41 of file stl_tables.hh.
References panic.
void AddressCounterTable::insert (Addr addr, uint64_t n = 0) [inline]
Definition at line 32 of file stl_tables.hh.
References exists(), ArmISA::n, and panic.
Referenced by AddressMapper::put_addr().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/stl_tables.hh