gem5: X86ISA::Interrupts Class Reference
X86ISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
typedef X86LocalApicParams Params
Public Member Functions
int getInitialApicId ()
void setCPU (BaseCPU *newCPU)
const Params * params () const
void init ()
Tick read (PacketPtr pkt)
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt)
Pure virtual function that the device must implement.
Tick recvMessage (PacketPtr pkt)
Tick recvResponse (PacketPtr pkt)
bool triggerTimerInterrupt ()
AddrRangeList getIntAddrRange () const
BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
uint32_t readReg (ApicRegIndex miscReg)
void setReg (ApicRegIndex reg, uint32_t val)
void setRegNoEffect (ApicRegIndex reg, uint32_t val)
Interrupts (Params *p)
bool checkInterrupts (ThreadContext *tc) const
bool checkInterruptsRaw () const
Check if there are pending interrupts without ignoring the interrupts disabled flag.
bool hasPendingUnmaskable () const
Check if there are pending unmaskable interrupts.
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc)
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
void post (int int_num, int index)
void clear (int int_num, int index)
void clearAll ()
Protected Member Functions
BitUnion32 (LVTEntry) Bitfield<7
EndBitUnion (LVTEntry) class ApicTimerEvent
int findRegArrayMSB (ApicRegIndex base)
void updateIRRV ()
void updateISRV ()
void setRegArrayBit (ApicRegIndex base, uint8_t vector)
void clearRegArrayBit (ApicRegIndex base, uint8_t vector)
bool getRegArrayBit (ApicRegIndex base, uint8_t vector)
void requestInterrupt (uint8_t vector, uint8_t deliveryMode, bool level)
Protected Attributes
uint32_t regs [NUM_APIC_REGS]
vector
Bitfield< 10, 8 > deliveryMode
Bitfield< 12 > status
Bitfield< 13 > polarity
Bitfield< 14 > remoteIRR
Bitfield< 15 > trigger
Bitfield< 16 > masked
Bitfield< 17 > periodic
ApicTimerEvent apicTimerEvent
bool pendingSmi
uint8_t smiVector
bool pendingNmi
uint8_t nmiVector
bool pendingExtInt
uint8_t extIntVector
bool pendingInit
uint8_t initVector
bool pendingStartup
uint8_t startupVector
bool startedUp
bool pendingUnmaskableInt
int pendingIPIs
uint8_t IRRV
uint8_t ISRV
BaseCPU * cpu
int initialApicId
IntSlavePort intSlavePort
Detailed Description
Definition at line 75 of file interrupts.hh.
Member Typedef Documentation
typedef X86LocalApicParams X86ISA::Interrupts::Params
Reimplemented from BasicPioDevice.
Definition at line 202 of file interrupts.hh.
Constructor & Destructor Documentation
X86ISA::Interrupts::Interrupts (Params * p)
Definition at line 612 of file interrupts.cc.
References X86ISA::APIC_DESTINATION_FORMAT, IRRV, ISRV, and regs.
Member Function Documentation
X86ISA::Interrupts::BitUnion32 (LVTEntry) [protected]
bool X86ISA::Interrupts::checkInterrupts (ThreadContext * tc) const
Definition at line 633 of file interrupts.cc.
References X86ISA::APIC_TASK_PRIORITY, bits(), DPRINTF, IRRV, ISRV, X86ISA::MISCREG_RFLAGS, pendingExtInt, pendingUnmaskableInt, ThreadContext::readMiscRegNoEffect(), and regs.
Referenced by getInterrupt(), and updateIntrInfo().
bool X86ISA::Interrupts::checkInterruptsRaw () const
Check if there are pending interrupts without ignoring the interrupts disabled flag.
Returns:
true if there are interrupts pending.
Definition at line 655 of file interrupts.cc.
References X86ISA::APIC_TASK_PRIORITY, bits(), IRRV, ISRV, pendingExtInt, pendingUnmaskableInt, and regs.
void X86ISA::Interrupts::clear (int int_num, int index) [inline]
Definition at line 311 of file interrupts.hh.
References panic.
void X86ISA::Interrupts::clearAll () [inline]
Definition at line 317 of file interrupts.hh.
References panic.
void X86ISA::Interrupts::clearRegArrayBit (ApicRegIndex base, uint8_t vector) [inline, protected]
Definition at line 175 of file interrupts.hh.
References regs.
Referenced by requestInterrupt(), setReg(), and updateIntrInfo().
X86ISA::Interrupts::EndBitUnion (LVTEntry) [inline, protected]
Definition at line 90 of file interrupts.hh.
References X86ISA::APIC_INITIAL_COUNT, readReg(), setReg(), and triggerTimerInterrupt().
int X86ISA::Interrupts::findRegArrayMSB (ApicRegIndex base) [inline, protected]
Definition at line 145 of file interrupts.hh.
References findMsbSet(), X86ISA::offset, and regs.
Referenced by updateIRRV(), and updateISRV().
int X86ISA::Interrupts::getInitialApicId () [inline]
Definition at line 197 of file interrupts.hh.
References initialApicId.
Referenced by X86ISA::I82094AA::signalInterrupt().
AddrRangeList X86ISA::Interrupts::getIntAddrRange () const [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 374 of file interrupts.cc.
References initialApicId, X86ISA::PhysAddrAPICRangeSize, RangeEx(), and X86ISA::x86InterruptAddress().
Fault X86ISA::Interrupts::getInterrupt (ThreadContext * tc)
Definition at line 663 of file interrupts.cc.
References checkInterrupts(), DPRINTF, extIntVector, initVector, IRRV, nmiVector, panic, pendingExtInt, pendingInit, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, and startupVector.
BaseMasterPort& X86ISA::Interrupts::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [inline, virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 236 of file interrupts.hh.
References X86ISA::IntDevice::intMasterPort.
bool X86ISA::Interrupts::getRegArrayBit (ApicRegIndex base, uint8_t vector) [inline, protected]
Definition at line 181 of file interrupts.hh.
References bits(), and regs.
Referenced by requestInterrupt().
BaseSlavePort& X86ISA::Interrupts::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [inline, virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from PioDevice.
Definition at line 245 of file interrupts.hh.
References intSlavePort.
bool X86ISA::Interrupts::hasPendingUnmaskable () const [inline]
Check if there are pending unmaskable interrupts.
Returns:
true there are unmaskable interrupts pending.
Definition at line 289 of file interrupts.hh.
References pendingUnmaskableInt.
void X86ISA::Interrupts::init () [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 313 of file interrupts.cc.
References intSlavePort, and SlavePort::sendRangeChange().
const Params* X86ISA::Interrupts::params () const [inline]
Reimplemented from BasicPioDevice.
Definition at line 207 of file interrupts.hh.
References SimObject::_params.
void X86ISA::Interrupts::post (int int_num, int index) [inline]
Definition at line 305 of file interrupts.hh.
References panic.
Tick X86ISA::Interrupts::read (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 214 of file interrupts.cc.
References X86ISA::decodeAddr(), DPRINTF, Packet::getAddr(), Packet::getSize(), BigEndianGuest::htog(), Packet::makeAtomicResponse(), X86ISA::mask, X86ISA::offset, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, readReg(), X86ISA::reg, Packet::setData(), and X86ISA::val.
uint32_t X86ISA::Interrupts::readReg (ApicRegIndex miscReg)
Definition at line 385 of file interrupts.cc.
References X86ISA::APIC_ARBITRATION_PRIORITY, X86ISA::APIC_CURRENT_COUNT, X86ISA::APIC_DIVIDE_CONFIGURATION, X86ISA::APIC_ERROR_STATUS, X86ISA::APIC_INTERNAL_STATE, X86ISA::APIC_PROCESSOR_PRIORITY, X86ISA::APIC_TRIGGER_MODE(), apicTimerEvent, ClockedObject::clockPeriod(), curTick(), divideFromConf(), panic, regs, ULL, and X86ISA::val.
Referenced by EndBitUnion(), read(), and X86ISA::I82094AA::signalInterrupt().
Tick X86ISA::Interrupts::recvMessage (PacketPtr pkt) [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 330 of file interrupts.cc.
References Packet::cmd, DPRINTF, Packet::get(), Packet::getAddr(), initialApicId, Packet::makeAtomicResponse(), MemCmd::MessageReq, X86ISA::offset, panic, BasicPioDevice::pioDelay, requestInterrupt(), and X86ISA::x86InterruptAddress().
Tick X86ISA::Interrupts::recvResponse (PacketPtr pkt) [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 358 of file interrupts.cc.
References X86ISA::APIC_INTERRUPT_COMMAND_LOW, Packet::cmd, DPRINTF, Packet::isError(), MemCmd::MessageResp, pendingIPIs, and regs.
void X86ISA::Interrupts::requestInterrupt (uint8_t vector, uint8_t deliveryMode, bool level) [protected]
Definition at line 248 of file interrupts.cc.
References X86ISA::APIC_INTERRUPT_REQUEST_BASE, X86ISA::APIC_TRIGGER_MODE_BASE, clearRegArrayBit(), cpu, DPRINTF, extIntVector, FullSystem, getRegArrayBit(), initVector, IRRV, nmiVector, pendingExtInt, pendingInit, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, setRegArrayBit(), smiVector, startedUp, startupVector, and BaseCPU::wakeup().
Referenced by recvMessage(), setReg(), and triggerTimerInterrupt().
void X86ISA::Interrupts::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 732 of file interrupts.cc.
References apicTimerEvent, extIntVector, initVector, IRRV, ISRV, nmiVector, X86ISA::NUM_APIC_REGS, pendingExtInt, pendingInit, pendingIPIs, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, regs, SERIALIZE_ARRAY, SERIALIZE_SCALAR, smiVector, startedUp, and startupVector.
void X86ISA::Interrupts::setCPU (BaseCPU * newCPU)
Definition at line 298 of file interrupts.cc.
References X86ISA::APIC_ID, cpu, initialApicId, panic, BasicPioDevice::pioAddr, regs, and X86ISA::x86LocalAPICAddress().
void X86ISA::Interrupts::setReg (ApicRegIndex reg, uint32_t val)
Definition at line 423 of file interrupts.cc.
References X86ISA::APIC_ARBITRATION_PRIORITY, X86ISA::APIC_CURRENT_COUNT, X86ISA::APIC_DESTINATION_FORMAT, X86ISA::APIC_DIVIDE_CONFIGURATION, X86ISA::APIC_EOI, X86ISA::APIC_ERROR_STATUS, X86ISA::APIC_ID, X86ISA::APIC_IN_SERVICE(), X86ISA::APIC_IN_SERVICE_BASE, X86ISA::APIC_INITIAL_COUNT, X86ISA::APIC_INTERNAL_STATE, X86ISA::APIC_INTERRUPT_COMMAND_HIGH, X86ISA::APIC_INTERRUPT_COMMAND_LOW, X86ISA::APIC_INTERRUPT_REQUEST(), X86ISA::APIC_LOGICAL_DESTINATION, X86ISA::APIC_LVT_ERROR, X86ISA::APIC_LVT_LINT0, X86ISA::APIC_LVT_LINT1, X86ISA::APIC_LVT_PERFORMANCE_MONITORING_COUNTERS, X86ISA::APIC_LVT_THERMAL_SENSOR, X86ISA::APIC_LVT_TIMER, X86ISA::APIC_PROCESSOR_PRIORITY, X86ISA::APIC_SPURIOUS_INTERRUPT_VECTOR, X86ISA::APIC_TASK_PRIORITY, X86ISA::APIC_TRIGGER_MODE(), X86ISA::APIC_VERSION, apicTimerEvent, bits(), clearRegArrayBit(), ClockedObject::clockPeriod(), curTick(), divideFromConf(), hack_once, ArmISA::i, initialApicId, X86ISA::IntDevice::intMasterPort, ISRV, System::isTimingMode(), System::numContexts(), X86ISA::offset, panic, pendingIPIs, regs, requestInterrupt(), EventManager::reschedule(), X86ISA::IntDevice::IntMasterPort::sendMessage(), PioDevice::sys, ULL, updateISRV(), and warn.
Referenced by EndBitUnion(), and write().
void X86ISA::Interrupts::setRegArrayBit (ApicRegIndex base, uint8_t vector) [inline, protected]
Definition at line 169 of file interrupts.hh.
References regs.
Referenced by requestInterrupt(), and updateIntrInfo().
void X86ISA::Interrupts::setRegNoEffect (ApicRegIndex reg, uint32_t val) [inline]
Definition at line 261 of file interrupts.hh.
References regs.
bool X86ISA::Interrupts::triggerTimerInterrupt () [inline]
Definition at line 226 of file interrupts.hh.
References X86ISA::APIC_LVT_TIMER, regs, and requestInterrupt().
Referenced by EndBitUnion().
void X86ISA::Interrupts::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 757 of file interrupts.cc.
References apicTimerEvent, extIntVector, initVector, IRRV, ISRV, nmiVector, X86ISA::NUM_APIC_REGS, pendingExtInt, pendingInit, pendingIPIs, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, regs, EventManager::reschedule(), EventManager::schedule(), smiVector, startedUp, startupVector, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
void X86ISA::Interrupts::updateIntrInfo (ThreadContext * tc)
Definition at line 697 of file interrupts.cc.
References X86ISA::APIC_IN_SERVICE_BASE, X86ISA::APIC_INTERRUPT_REQUEST_BASE, checkInterrupts(), clearRegArrayBit(), DPRINTF, IRRV, ISRV, pendingExtInt, pendingInit, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, setRegArrayBit(), startedUp, and updateIRRV().
void X86ISA::Interrupts::updateIRRV () [inline, protected]
Definition at line 157 of file interrupts.hh.
References X86ISA::APIC_INTERRUPT_REQUEST_BASE, findRegArrayMSB(), and IRRV.
Referenced by updateIntrInfo().
void X86ISA::Interrupts::updateISRV () [inline, protected]
Definition at line 163 of file interrupts.hh.
References X86ISA::APIC_IN_SERVICE_BASE, findRegArrayMSB(), and ISRV.
Referenced by setReg().
Tick X86ISA::Interrupts::write (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 231 of file interrupts.cc.
References X86ISA::decodeAddr(), DPRINTF, Packet::getAddr(), Packet::getSize(), BigEndianGuest::gtoh(), Packet::makeAtomicResponse(), X86ISA::mask, X86ISA::offset, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, X86ISA::reg, regs, setReg(), X86ISA::val, and Packet::writeData().
Member Data Documentation
ApicTimerEvent X86ISA::Interrupts::apicTimerEvent [protected]
Definition at line 112 of file interrupts.hh.
Referenced by readReg(), serialize(), setReg(), and unserialize().
BaseCPU* X86ISA::Interrupts::cpu [protected]
Definition at line 188 of file interrupts.hh.
Referenced by requestInterrupt(), and setCPU().
Bitfield<10, 8> X86ISA::Interrupts::deliveryMode [protected]
Definition at line 83 of file interrupts.hh.
uint8_t X86ISA::Interrupts::extIntVector [protected]
Definition at line 125 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), and unserialize().
int X86ISA::Interrupts::initialApicId [protected]
Definition at line 190 of file interrupts.hh.
Referenced by getInitialApicId(), getIntAddrRange(), recvMessage(), setCPU(), and setReg().
uint8_t X86ISA::Interrupts::initVector [protected]
Definition at line 127 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), and unserialize().
IntSlavePort X86ISA::Interrupts::intSlavePort [protected]
Definition at line 193 of file interrupts.hh.
Referenced by getSlavePort(), and init().
uint8_t X86ISA::Interrupts::IRRV [protected]
Definition at line 141 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), getInterrupt(), Interrupts(), requestInterrupt(), serialize(), unserialize(), updateIntrInfo(), and updateIRRV().
uint8_t X86ISA::Interrupts::ISRV [protected]
Definition at line 142 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), Interrupts(), serialize(), setReg(), unserialize(), updateIntrInfo(), and updateISRV().
Bitfield<16> X86ISA::Interrupts::masked [protected]
Definition at line 88 of file interrupts.hh.
uint8_t X86ISA::Interrupts::nmiVector [protected]
Definition at line 123 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), and unserialize().
bool X86ISA::Interrupts::pendingExtInt [protected]
Definition at line 124 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), getInterrupt(), requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
bool X86ISA::Interrupts::pendingInit [protected]
Definition at line 126 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
int X86ISA::Interrupts::pendingIPIs [protected]
Definition at line 136 of file interrupts.hh.
Referenced by recvResponse(), serialize(), setReg(), and unserialize().
bool X86ISA::Interrupts::pendingNmi [protected]
Definition at line 122 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
bool X86ISA::Interrupts::pendingSmi [protected]
Definition at line 120 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
bool X86ISA::Interrupts::pendingStartup [protected]
Definition at line 128 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
bool X86ISA::Interrupts::pendingUnmaskableInt [protected]
Definition at line 133 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), getInterrupt(), hasPendingUnmaskable(), requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
Bitfield<17> X86ISA::Interrupts::periodic [protected]
Definition at line 89 of file interrupts.hh.
Bitfield<13> X86ISA::Interrupts::polarity [protected]
Definition at line 85 of file interrupts.hh.
uint32_t X86ISA::Interrupts::regs[NUM_APIC_REGS] [protected]
Definition at line 79 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), clearRegArrayBit(), findRegArrayMSB(), getRegArrayBit(), Interrupts(), readReg(), recvResponse(), serialize(), setCPU(), setReg(), setRegArrayBit(), setRegNoEffect(), triggerTimerInterrupt(), unserialize(), and write().
Bitfield<14> X86ISA::Interrupts::remoteIRR [protected]
Definition at line 86 of file interrupts.hh.
uint8_t X86ISA::Interrupts::smiVector [protected]
Definition at line 121 of file interrupts.hh.
Referenced by requestInterrupt(), serialize(), and unserialize().
bool X86ISA::Interrupts::startedUp [protected]
Definition at line 130 of file interrupts.hh.
Referenced by requestInterrupt(), serialize(), unserialize(), and updateIntrInfo().
uint8_t X86ISA::Interrupts::startupVector [protected]
Definition at line 129 of file interrupts.hh.
Referenced by getInterrupt(), requestInterrupt(), serialize(), and unserialize().
Bitfield<12> X86ISA::Interrupts::status [protected]
Definition at line 84 of file interrupts.hh.
Bitfield<15> X86ISA::Interrupts::trigger [protected]
Definition at line 87 of file interrupts.hh.
X86ISA::Interrupts::vector [protected]
Definition at line 82 of file interrupts.hh.
The documentation for this class was generated from the following files:
arch/x86/interrupts.hh
arch/x86/interrupts.cc