gem5: X86ISA::I386LiveProcess Class Reference
X86ISA::I386LiveProcess Class Reference
#include <process.hh>
Classes
class VSyscallPage
Public Member Functions
void argsInit (int intSize, int pageSize)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
void syscall (int64_t callnum, ThreadContext *tc)
X86ISA::IntReg getSyscallArg (ThreadContext *tc, int &i)
X86ISA::IntReg getSyscallArg (ThreadContext *tc, int &i, int width)
void setSyscallArg (ThreadContext *tc, int i, X86ISA::IntReg val)
Protected Member Functions
I386LiveProcess (LiveProcessParams *params, ObjectFile *objFile, SyscallDesc *_syscallDescs, int _numSyscallDescs)
Protected Attributes
VSyscallPage vsyscallPage
Detailed Description
Definition at line 112 of file process.hh.
Constructor & Destructor Documentation
I386LiveProcess::I386LiveProcess (LiveProcessParams * params, ObjectFile * objFile, SyscallDesc * _syscallDescs, int _numSyscallDescs) [protected]
Definition at line 133 of file process.cc.
References X86ISA::X86LiveProcess::_gdtSize, X86ISA::X86LiveProcess::_gdtStart, X86ISA::I386LiveProcess::VSyscallPage::base, Process::mmap_end, Process::mmap_start, Process::next_thread_stack_base, X86ISA::PageBytes, X86ISA::I386LiveProcess::VSyscallPage::size, Process::stack_base, ULL, X86ISA::I386LiveProcess::VSyscallPage::vsyscallOffset, vsyscallPage, and X86ISA::I386LiveProcess::VSyscallPage::vsysexitOffset.
Member Function Documentation
void I386LiveProcess::argsInit (int intSize, int pageSize)
Definition at line 1020 of file process.cc.
References X86ISA::I386LiveProcess::VSyscallPage::base, X86ISA::M5_AT_SYSINFO, X86ISA::M5_AT_SYSINFO_EHDR, X86ISA::I386LiveProcess::VSyscallPage::vsyscallOffset, and vsyscallPage.
Referenced by initState().
X86ISA::IntReg I386LiveProcess::getSyscallArg (ThreadContext * tc, int & i, int width) [virtual]
Reimplemented from LiveProcess.
Definition at line 1059 of file process.cc.
References ArgumentReg, X86ISA::mask, NumArgumentRegs, and ThreadContext::readIntReg().
X86ISA::IntReg I386LiveProcess::getSyscallArg (ThreadContext * tc, int & i) [virtual]
Implements LiveProcess.
Definition at line 1052 of file process.cc.
References ThreadContext::readIntReg().
void I386LiveProcess::initState () [virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from Process.
Definition at line 609 of file process.cc.
References X86ISA::X86LiveProcess::_gdtSize, X86ISA::X86LiveProcess::_gdtStart, Process::allocateMem(), argsInit(), X86ISA::I386LiveProcess::VSyscallPage::base, Process::contextIds, System::getThreadContext(), ArmISA::i, Process::initVirtMem, X86ISA::MISCREG_CR0, X86ISA::MISCREG_CS_ATTR, X86ISA::MISCREG_EFER, X86ISA::MISCREG_MXCSR, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_EFF_BASE(), X86ISA::MISCREG_SEG_LIMIT(), X86ISA::MISCREG_SEG_SEL(), X86ISA::MISCREG_TSG_BASE, X86ISA::MISCREG_TSG_EFF_BASE, X86ISA::MISCREG_TSG_LIMIT, X86ISA::MISCREG_TSL, X86ISA::NUM_SEGMENTREGS, X86ISA::PageBytes, X86ISA::seg, ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), X86ISA::I386LiveProcess::VSyscallPage::size, Process::system, ArmISA::tc, X86ISA::I386LiveProcess::VSyscallPage::vsyscallOffset, vsyscallPage, X86ISA::I386LiveProcess::VSyscallPage::vsysexitOffset, PortProxy::write(), and SETranslatingPortProxy::writeBlob().
void I386LiveProcess::setSyscallArg (ThreadContext * tc, int i, X86ISA::IntReg val)
Definition at line 1070 of file process.cc.
References ArgumentReg, NumArgumentRegs, and ThreadContext::setIntReg().
void I386LiveProcess::syscall (int64_t callnum, ThreadContext * tc) [virtual]
Reimplemented from LiveProcess.
Definition at line 120 of file process.cc.
References X86ISA::I386LiveProcess::VSyscallPage::base, X86ISA::pc, ThreadContext::pcState(), X86ISA::I386LiveProcess::VSyscallPage::size, vsyscallPage, and X86ISA::I386LiveProcess::VSyscallPage::vsysexitOffset.
Member Data Documentation
VSyscallPage X86ISA::I386LiveProcess::vsyscallPage [protected]
Definition at line 126 of file process.hh.
Referenced by argsInit(), I386LiveProcess(), initState(), and syscall().
The documentation for this class was generated from the following files:
arch/x86/process.hh
arch/x86/process.cc