gem5: RegMiscRegImmOp Class Reference
RegMiscRegImmOp Class Reference
#include <misc.hh>
Protected Member Functions
RegMiscRegImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, MiscRegIndex _op1, uint64_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
MiscRegIndex op1
uint64_t imm
Detailed Description
Definition at line 276 of file misc.hh.
Constructor & Destructor Documentation
RegMiscRegImmOp::RegMiscRegImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, MiscRegIndex _op1, uint64_t _imm) [inline, protected]
Definition at line 283 of file misc.hh.
Member Function Documentation
std::string RegMiscRegImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 271 of file misc.cc.
References ccprintf(), dest, imm, op1, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex RegMiscRegImmOp::dest [protected]
Definition at line 279 of file misc.hh.
Referenced by generateDisassembly().
uint64_t RegMiscRegImmOp::imm [protected]
Definition at line 281 of file misc.hh.
Referenced by generateDisassembly().
MiscRegIndex RegMiscRegImmOp::op1 [protected]
Definition at line 280 of file misc.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/misc.hh
arch/arm/insts/misc.cc