gem5: Barrier Class Reference
Barrier Class Reference
#include <barrier.hh>
Public Member Functions
Barrier (unsigned _numWaiting)
bool wait ()
Private Attributes
std::mutex bMutex
Mutex to protect access to numLeft and generation.
std::condition_variable bCond
Condition variable for waiting on barrier.
unsigned numWaiting
Number of threads we should be waiting for before completing the barrier.
unsigned generation
Generation of this barrier.
unsigned numLeft
Number of threads remaining for the current generation.
Detailed Description
Definition at line 45 of file barrier.hh.
Constructor & Destructor Documentation
Barrier::Barrier (unsigned _numWaiting) [inline]
Definition at line 60 of file barrier.hh.
Member Function Documentation
bool Barrier::wait () [inline]
Definition at line 65 of file barrier.hh.
References bCond, bMutex, generation, X86ISA::lock, numLeft, and numWaiting.
Referenced by BaseGlobalEvent::BarrierEvent::globalBarrier(), simulate(), and thread_loop().
Member Data Documentation
std::condition_variable Barrier::bCond [private]
Condition variable for waiting on barrier.
Definition at line 51 of file barrier.hh.
Referenced by wait().
std::mutex Barrier::bMutex [private]
Mutex to protect access to numLeft and generation.
Definition at line 49 of file barrier.hh.
Referenced by wait().
unsigned Barrier::generation [private]
Generation of this barrier.
Definition at line 55 of file barrier.hh.
Referenced by wait().
unsigned Barrier::numLeft [private]
Number of threads remaining for the current generation.
Definition at line 57 of file barrier.hh.
Referenced by wait().
unsigned Barrier::numWaiting [private]
Number of threads we should be waiting for before completing the barrier.
Definition at line 53 of file barrier.hh.
Referenced by wait().
The documentation for this class was generated from the following file:
base/barrier.hh