gem5: IntrControl Class Reference
IntrControl Class Reference
#include <intr_control.hh>
Public Types
typedef IntrControlParams Params
Public Member Functions
IntrControl (const Params *p)
void clear (int cpu_id, int int_num, int index)
void post (int cpu_id, int int_num, int index)
void clear (int int_num, int index=0)
void post (int int_num, int index=0)
Public Attributes
System * sys
Detailed Description
Definition at line 42 of file intr_control.hh.
Member Typedef Documentation
typedef IntrControlParams IntrControl::Params
Reimplemented from SimObject.
Definition at line 46 of file intr_control.hh.
Constructor & Destructor Documentation
IntrControl::IntrControl (const Params * p)
Definition at line 44 of file intr_control.cc.
Member Function Documentation
void IntrControl::clear (int int_num, int index = 0) [inline]
Definition at line 53 of file intr_control.hh.
References clear(), and MipsISA::index.
void IntrControl::clear (int cpu_id, int int_num, int index)
Definition at line 58 of file intr_control.cc.
References DPRINTF, sys, and System::threadContexts.
Referenced by clear(), TsunamiCChip::clearDRIR(), MaltaCChip::clearIntr(), TsunamiCChip::clearIPI(), TsunamiCChip::clearITI(), Pl390::driveLegFIQ(), Pl390::driveLegIRQ(), Pl390::readCpu(), VGic::unPostVInt(), and TsunamiCChip::write().
void IntrControl::post (int int_num, int index = 0) [inline]
Definition at line 59 of file intr_control.hh.
References MipsISA::index, and post().
void IntrControl::post (int cpu_id, int int_num, int index)
Definition at line 49 of file intr_control.cc.
References DPRINTF, sys, and System::threadContexts.
Referenced by Pl390::driveLegFIQ(), Pl390::driveLegIRQ(), Iob::generateIpi(), post(), TsunamiCChip::postDRIR(), MaltaCChip::postIntr(), TsunamiCChip::postRTC(), VGic::PostVIntEvent::process(), Pl390::PostIntEvent::process(), Iob::receiveDeviceInterrupt(), Iob::receiveJBusInterrupt(), TsunamiCChip::reqIPI(), and TsunamiCChip::write().
Member Data Documentation
System* IntrControl::sys
Definition at line 45 of file intr_control.hh.
Referenced by clear(), and post().
The documentation for this class was generated from the following files:
cpu/intr_control.hh
cpu/intr_control.cc
cpu/intr_control_noisa.cc