gem5: LinuxArmSystem Class Reference
LinuxArmSystem Class Reference
#include <system.hh>
Public Types
typedef LinuxArmSystemParams Params
Boilerplate params code.
Public Member Functions
const Params * params () const
LinuxArmSystem (Params *p)
~LinuxArmSystem ()
void initState ()
Initialise the system.
void startup ()
startup() is the final initialization call before simulation.
void mapPid (ThreadContext *tc, uint32_t pid)
This function creates a new task Id for the given pid.
Public Attributes
bool enableContextSwitchStatsDump
When enabled, dump stats/task info on context switches for Streamline and per-thread cache occupancy studies, etc.
std::map< uint32_t, uint32_t > taskMap
This map stores a mapping of OS process IDs to internal Task IDs.
std::ostream * taskFile
This is a file that is placed in the run directory that prints out mappings between taskIds and OS process IDs.
Protected Attributes
DumpStatsPCEvent * dumpStatsPCEvent
Private Attributes
PCEvent * kernelPanicEvent
Event to halt the simulator if the kernel calls panic().
PCEvent * kernelOopsEvent
Event to halt the simulator if the kernel calls oopses.
Linux::UDelayEvent * uDelaySkipEvent
PC based event to skip udelay(<time>) calls and quiesce the processor for the appropriate amount of time.
Linux::UDelayEvent * constUDelaySkipEvent
Another PC based skip event for const_udelay().
Detailed Description
Definition at line 59 of file system.hh.
Member Typedef Documentation
typedef LinuxArmSystemParams LinuxArmSystem::Params
Boilerplate params code.
Reimplemented from GenericArmSystem.
Definition at line 66 of file system.hh.
Constructor & Destructor Documentation
LinuxArmSystem::LinuxArmSystem (Params * p)
Definition at line 63 of file system.cc.
References constUDelaySkipEvent, kernelOopsEvent, kernelPanicEvent, and uDelaySkipEvent.
LinuxArmSystem::~LinuxArmSystem ()
Definition at line 213 of file system.cc.
References constUDelaySkipEvent, dumpStatsPCEvent, and uDelaySkipEvent.
Member Function Documentation
void LinuxArmSystem::initState () [virtual]
Initialise the system.
Reimplemented from GenericArmSystem.
Definition at line 101 of file system.cc.
References X86ISA::ac, DtbObject::addBootCmdLine(), X86ISA::addr, SparcISA::am, AtagCmdline::cmdline(), AtagHeader::copyOut(), createObjectFile(), DDUMP, debugSymbolTable, DPRINTF, fatal, SymbolTable::findAddress(), AtagCore::flags(), PhysicalMemory::getConfAddrRanges(), ArmISA::i, inform, System::kernel, System::kernelSymtab, System::loadAddrMask, System::loadAddrOffset, ObjectFile::loadGlobalSymbols(), ObjectFile::loadSections(), AtagMem::memSize(), AtagMem::memStart(), ArmISA::offset, AtagCore::pagesize(), params(), System::physmem, System::physProxy, AtagCore::rootdev(), ObjectFile::setTextBase(), AtagHeader::size(), System::threadContexts, warn, and PortProxy::writeBlob().
void LinuxArmSystem::mapPid (ThreadContext * tc, uint32_t pid)
This function creates a new task Id for the given pid.
Parameters:
tc thread context that is currentyl executing
Definition at line 253 of file system.cc.
References ContextSwitchTaskId::MaxNormalTaskId, taskMap, ContextSwitchTaskId::Unknown, and warn_once.
Referenced by DumpStatsPCEvent::process(), and startup().
const Params* LinuxArmSystem::params () const [inline]
Reimplemented from GenericArmSystem.
Definition at line 68 of file system.hh.
References System::_params.
Referenced by initState().
void LinuxArmSystem::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 231 of file system.cc.
References System::_numContexts, OutputDirectory::create(), dumpStatsPCEvent, enableContextSwitchStatsDump, ThreadContext::getCpuPtr(), ArmISA::i, Request::invldPid, mapPid(), SimObject::name(), panic, simout, taskFile, taskMap, ArmISA::tc, and System::threadContexts.
Member Data Documentation
Linux::UDelayEvent* LinuxArmSystem::constUDelaySkipEvent [private]
Another PC based skip event for const_udelay().
Similar to the udelay skip, but this function precomputes the first multiply that is done in the generic case since the parameter is known at compile time. Thus we need to do some division to get back to us.
Definition at line 117 of file system.hh.
Referenced by LinuxArmSystem(), and ~LinuxArmSystem().
DumpStatsPCEvent* LinuxArmSystem::dumpStatsPCEvent [protected]
Definition at line 62 of file system.hh.
Referenced by startup(), and ~LinuxArmSystem().
bool LinuxArmSystem::enableContextSwitchStatsDump
When enabled, dump stats/task info on context switches for Streamline and per-thread cache occupancy studies, etc.
Definition at line 75 of file system.hh.
Referenced by startup().
PCEvent* LinuxArmSystem::kernelOopsEvent [private]
Event to halt the simulator if the kernel calls oopses.
Definition at line 103 of file system.hh.
Referenced by LinuxArmSystem().
PCEvent* LinuxArmSystem::kernelPanicEvent [private]
Event to halt the simulator if the kernel calls panic().
Definition at line 100 of file system.hh.
Referenced by LinuxArmSystem().
std::ostream* LinuxArmSystem::taskFile
This is a file that is placed in the run directory that prints out mappings between taskIds and OS process IDs.
Definition at line 85 of file system.hh.
Referenced by DumpStatsPCEvent::process(), and startup().
std::map<uint32_t, uint32_t> LinuxArmSystem::taskMap
This map stores a mapping of OS process IDs to internal Task IDs.
The mapping is done because the stats system doesn't tend to like vectors that are much greater than 1000 items and the entire process space is 65K.
Definition at line 81 of file system.hh.
Referenced by mapPid(), DumpStatsPCEvent::process(), and startup().
Linux::UDelayEvent* LinuxArmSystem::uDelaySkipEvent [private]
PC based event to skip udelay(<time>) calls and quiesce the processor for the appropriate amount of time.
This is not functionally required but does speed up simulation.
Definition at line 110 of file system.hh.
Referenced by LinuxArmSystem(), and ~LinuxArmSystem().
The documentation for this class was generated from the following files:
arch/arm/linux/system.hh
arch/arm/linux/system.cc