gem5: ArmISA::MicroMemPairOp Class Reference
ArmISA::MicroMemPairOp Class Reference
#include <macromem.hh>
Protected Member Functions
MicroMemPairOp (const char *mnem, ExtMachInst machInst, OpClass __opClass, RegIndex _dreg1, RegIndex _dreg2, RegIndex _base, bool _up, uint8_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
RegIndex dest
RegIndex dest2
RegIndex urb
bool up
int32_t imm
unsigned memAccessFlags
Detailed Description
Definition at line 398 of file macromem.hh.
Constructor & Destructor Documentation
ArmISA::MicroMemPairOp::MicroMemPairOp (const char * mnem, ExtMachInst machInst, OpClass __opClass, RegIndex _dreg1, RegIndex _dreg2, RegIndex _base, bool _up, uint8_t _imm) [inline, protected]
Definition at line 406 of file macromem.hh.
Member Function Documentation
std::string ArmISA::MicroMemPairOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 1612 of file macromem.cc.
References ccprintf(), dest, dest2, imm, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), ArmISA::ss, and urb.
Member Data Documentation
RegIndex ArmISA::MicroMemPairOp::dest [protected]
Definition at line 401 of file macromem.hh.
Referenced by generateDisassembly().
RegIndex ArmISA::MicroMemPairOp::dest2 [protected]
Definition at line 401 of file macromem.hh.
Referenced by generateDisassembly().
int32_t ArmISA::MicroMemPairOp::imm [protected]
Definition at line 403 of file macromem.hh.
Referenced by generateDisassembly().
unsigned ArmISA::MicroMemPairOp::memAccessFlags [protected]
Definition at line 404 of file macromem.hh.
bool ArmISA::MicroMemPairOp::up [protected]
Definition at line 402 of file macromem.hh.
RegIndex ArmISA::MicroMemPairOp::urb [protected]
Definition at line 401 of file macromem.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/macromem.hh
arch/arm/insts/macromem.cc