gem5: Minor::LSQ::DcachePort Class Reference
Minor::LSQ::DcachePort Class Reference
Exposable data port.
#include <lsq.hh>
Public Member Functions
DcachePort (std::string name, LSQ &lsq_, MinorCPU &cpu)
Protected Member Functions
bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
void recvTimingSnoopReq (PacketPtr pkt)
Snooping a coherence request, do nothing.
Protected Attributes
LSQ & lsq
My owner.
Detailed Description
Exposable data port.
Definition at line 89 of file lsq.hh.
Constructor & Destructor Documentation
Minor::LSQ::DcachePort::DcachePort (std::string name, LSQ & lsq_, MinorCPU & cpu) [inline]
Definition at line 96 of file lsq.hh.
Member Function Documentation
void Minor::LSQ::DcachePort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 104 of file lsq.hh.
References lsq, and Minor::LSQ::recvReqRetry().
bool Minor::LSQ::DcachePort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 101 of file lsq.hh.
References lsq, and Minor::LSQ::recvTimingResp().
void Minor::LSQ::DcachePort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
Snooping a coherence request, do nothing.
Reimplemented from MinorCPU::MinorCPUPort.
Definition at line 106 of file lsq.hh.
References lsq, and Minor::LSQ::recvTimingSnoopReq().
Member Data Documentation
LSQ& Minor::LSQ::DcachePort::lsq [protected]
My owner.
Definition at line 93 of file lsq.hh.
Referenced by recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
The documentation for this class was generated from the following file:
cpu/minor/lsq.hh