gem5: Ticked Class Reference
Ticked Class Reference
Ticked attaches gem5's event queue/scheduler to evaluate calls and provides a start/stop interface to ticking.
#include <ticked_object.hh>
Classes
class ClockEvent
An event to call process periodically.
Public Member Functions
Ticked (ClockedObject &object_, Stats::Scalar *imported_num_cycles=NULL, Event::Priority priority=Event::CPU_Tick_Pri)
virtual ~Ticked ()
void regStats ()
Register {num,ticks}Cycles if necessary.
void start ()
Start ticking.
Cycles cyclesSinceLastStopped () const
How long have we been stopped for?
void resetLastStopped ()
Reset stopped time to current time.
void stop ()
Cancel the next tick event and issue no more.
void serialize (std::ostream &os)
Checkpoint lastStopped.
void unserialize (Checkpoint *cp, const std::string &section)
virtual void evaluate ()=0
Action to call on the clock tick.
virtual void countCycles (Cycles delta)
Callback to handle cycle statistics and probes.
Protected Attributes
ClockedObject & object
ClockedObject who is responsible for this Ticked's actions/stats.
ClockEvent event
The single instance of ClockEvent used.
bool running
Have I been started? and am not stopped.
Cycles lastStopped
Time of last stop event to calculate run time.
Stats::Scalar & numCycles
Total number of cycles either ticked or spend stopped.
Stats::Scalar tickCycles
Number of cycles ticked.
Stats::Formula idleCycles
Number of cycles stopped.
Private Attributes
Stats::Scalar * numCyclesLocal
Locally allocated stats.
Friends
class ClockEvent
Detailed Description
Ticked attaches gem5's event queue/scheduler to evaluate calls and provides a start/stop interface to ticking.
Ticked is not a ClockedObject but can be attached to one by inheritance and by calling regStats, serialize/unserialize
Definition at line 59 of file ticked_object.hh.
Constructor & Destructor Documentation
Ticked::Ticked (ClockedObject & object_, Stats::Scalar * imported_num_cycles = NULL, Event::Priority priority = Event::CPU_Tick_Pri)
Definition at line 42 of file ticked_object.cc.
virtual Ticked::~Ticked () [inline, virtual]
Definition at line 121 of file ticked_object.hh.
Member Function Documentation
virtual void Ticked::countCycles (Cycles delta) [inline, virtual]
Callback to handle cycle statistics and probes.
This callback is called at the beginning of a new cycle active cycle and when restarting the ticked object. The delta parameter indicates the number of cycles elapsed since the previous call is normally '1' unless the object has been stopped and restarted.
Parameters:
delta Number of cycles since the previous call.
Reimplemented in Minor::Pipeline.
Definition at line 184 of file ticked_object.hh.
Referenced by Ticked::ClockEvent::process(), and start().
Cycles Ticked::cyclesSinceLastStopped () const [inline]
How long have we been stopped for?
Definition at line 142 of file ticked_object.hh.
References lastStopped.
Referenced by MinorCPU::activateContext(), and start().
virtual void Ticked::evaluate () [pure virtual]
Action to call on the clock tick.
Implemented in Minor::Pipeline.
Referenced by Ticked::ClockEvent::process().
void Ticked::regStats ()
Register {num,ticks}Cycles if necessary.
If numCycles is imported, be sure to register it *before* calling this regStats
Reimplemented in TickedObject.
Definition at line 56 of file ticked_object.cc.
References idleCycles, name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numCycles, numCyclesLocal, and tickCycles.
Referenced by MinorCPU::regStats().
void Ticked::resetLastStopped () [inline]
Reset stopped time to current time.
Definition at line 149 of file ticked_object.hh.
References lastStopped.
Referenced by MinorCPU::activateContext(), and stop().
void Ticked::serialize (std::ostream & os)
Checkpoint lastStopped.
Reimplemented in TickedObject.
Definition at line 75 of file ticked_object.cc.
References lastStopped, and paramOut().
Referenced by MinorCPU::serialize().
void Ticked::start () [inline]
Start ticking.
Definition at line 129 of file ticked_object.hh.
References countCycles(), cyclesSinceLastStopped(), event, numCycles, running, and Event::scheduled().
Referenced by MinorCPU::wakeupOnEvent().
void Ticked::stop () [inline]
Cancel the next tick event and issue no more.
Definition at line 156 of file ticked_object.hh.
References event, resetLastStopped(), running, and Event::scheduled().
Referenced by Minor::Pipeline::evaluate().
void Ticked::unserialize (Checkpoint * cp, const std::string & section)
Reimplemented in TickedObject.
Definition at line 83 of file ticked_object.cc.
References lastStopped, and optParamIn().
Referenced by MinorCPU::unserialize().
Friends And Related Function Documentation
friend class ClockEvent [friend]
Definition at line 88 of file ticked_object.hh.
Member Data Documentation
ClockEvent Ticked::event [protected]
The single instance of ClockEvent used.
Definition at line 94 of file ticked_object.hh.
Referenced by start(), and stop().
Stats::Formula Ticked::idleCycles [protected]
Number of cycles stopped.
Definition at line 114 of file ticked_object.hh.
Referenced by regStats().
Cycles Ticked::lastStopped [protected]
Time of last stop event to calculate run time.
Definition at line 100 of file ticked_object.hh.
Referenced by cyclesSinceLastStopped(), resetLastStopped(), serialize(), and unserialize().
Stats::Scalar& Ticked::numCycles [protected]
Total number of cycles either ticked or spend stopped.
Definition at line 108 of file ticked_object.hh.
Referenced by Ticked::ClockEvent::process(), regStats(), and start().
Stats::Scalar* Ticked::numCyclesLocal [private]
Locally allocated stats.
Definition at line 104 of file ticked_object.hh.
Referenced by regStats().
ClockedObject& Ticked::object [protected]
ClockedObject who is responsible for this Ticked's actions/stats.
Definition at line 91 of file ticked_object.hh.
Referenced by Ticked::ClockEvent::process().
bool Ticked::running [protected]
Have I been started? and am not stopped.
Definition at line 97 of file ticked_object.hh.
Referenced by Ticked::ClockEvent::process(), start(), and stop().
Stats::Scalar Ticked::tickCycles [protected]
Number of cycles ticked.
Definition at line 111 of file ticked_object.hh.
Referenced by Ticked::ClockEvent::process(), and regStats().
The documentation for this class was generated from the following files:
sim/ticked_object.hh
sim/ticked_object.cc