gem5: NetworkInterface Class Reference
NetworkInterface Class Reference
#include <NetworkInterface.hh>
Public Types
typedef
GarnetNetworkInterfaceParams Params
Public Member Functions
NetworkInterface (const Params *p)
~NetworkInterface ()
void addInPort (NetworkLink *in_link)
void addOutPort (NetworkLink *out_link)
void addNode (std::vector< MessageBuffer * > &inNode, std::vector< MessageBuffer * > &outNode)
void wakeup ()
void grant_vc (int out_port, int vc, Cycles grant_time)
void release_vc (int out_port, int vc, Cycles release_time)
bool isBufferNotFull (int vc, int inport)
void request_vc (int in_vc, int in_port, NetDest destination, Cycles request_time)
void print (std::ostream &out) const
bool functionalRead (Packet *)
uint32_t functionalWrite (Packet *)
void init_net_ptr (GarnetNetwork *net_ptr)
Private Member Functions
bool flitisizeMessage (MsgPtr msg_ptr, int vnet)
int calculateVC (int vnet)
void scheduleOutputLink ()
void checkReschedule ()
Private Attributes
GarnetNetwork * m_net_ptr
uint32_t m_virtual_networks
uint32_t m_num_vcs
uint32_t m_vc_per_vnet
NodeID m_id
std::vector< OutVcState * > m_out_vc_state
std::vector< int > m_vc_allocator
int m_vc_round_robin
flitBuffer * outSrcQueue
NetworkLink * inNetLink
NetworkLink * outNetLink
std::vector< flitBuffer * > m_ni_buffers
std::vector< MessageBuffer * > inNode_ptr
std::vector< MessageBuffer * > outNode_ptr
Detailed Description
Definition at line 49 of file NetworkInterface.hh.
Member Typedef Documentation
typedef GarnetNetworkInterfaceParams NetworkInterface::Params
Reimplemented from SimObject.
Definition at line 52 of file NetworkInterface.hh.
Constructor & Destructor Documentation
NetworkInterface::NetworkInterface (const Params * p)
Definition at line 45 of file NetworkInterface.cc.
References ArmISA::i, m_id, m_ni_buffers, m_num_vcs, m_out_vc_state, m_vc_allocator, m_vc_per_vnet, m_vc_round_robin, and m_virtual_networks.
NetworkInterface::~NetworkInterface ()
Definition at line 69 of file NetworkInterface.cc.
References m5::stl_helpers::deletePointers(), m_ni_buffers, m_out_vc_state, and outSrcQueue.
Member Function Documentation
void NetworkInterface::addInPort (NetworkLink * in_link)
Definition at line 77 of file NetworkInterface.cc.
References inNetLink, and NetworkLink::setLinkConsumer().
void NetworkInterface::addNode (std::vector< MessageBuffer * > & inNode, std::vector< MessageBuffer * > & outNode)
Definition at line 93 of file NetworkInterface.cc.
References inNode_ptr, and outNode_ptr.
void NetworkInterface::addOutPort (NetworkLink * out_link)
Definition at line 84 of file NetworkInterface.cc.
References outNetLink, outSrcQueue, NetworkLink::setSource(), and NetworkLink::setSourceQueue().
int NetworkInterface::calculateVC (int vnet) [private]
Definition at line 210 of file NetworkInterface.cc.
References ClockedObject::curCycle(), ArmISA::i, IDLE_, BaseGarnetNetwork::isVNetOrdered(), m_net_ptr, m_out_vc_state, m_vc_allocator, and m_vc_per_vnet.
Referenced by flitisizeMessage().
void NetworkInterface::checkReschedule () [private]
Definition at line 331 of file NetworkInterface.cc.
References ClockedObject::curCycle(), inNode_ptr, m_ni_buffers, m_num_vcs, and Consumer::scheduleEvent().
Referenced by wakeup().
bool NetworkInterface::flitisizeMessage (MsgPtr msg_ptr, int vnet) [private]
Definition at line 121 of file NetworkInterface.cc.
References NetDest::add(), calculateVC(), NetDest::clear(), ClockedObject::curCycle(), NetDest::getAllDest(), NetworkMessage::getInternalDestination(), NetworkMessage::getMessageSize(), BaseGarnetNetwork::getNiFlitSize(), ArmISA::i, BaseGarnetNetwork::increment_injected_flits(), ArmISA::m, m_net_ptr, m_ni_buffers, m_out_vc_state, Network::MessageSizeType_to_int(), outNetLink, NetDest::removeNetDest(), NetworkLink::request_vc_link(), safe_cast(), flit::set_delay(), ClockedObject::ticksToCycles(), and VC_AB_.
Referenced by wakeup().
bool NetworkInterface::functionalRead (Packet * pkt)
Definition at line 353 of file NetworkInterface.cc.
References flitBuffer::functionalRead(), ArmISA::i, m_ni_buffers, and outSrcQueue.
uint32_t NetworkInterface::functionalWrite (Packet * pkt)
Definition at line 371 of file NetworkInterface.cc.
References flitBuffer::functionalWrite(), ArmISA::i, m_ni_buffers, and outSrcQueue.
void NetworkInterface::grant_vc (int out_port, int vc, Cycles grant_time) [virtual]
Reimplemented from FlexibleConsumer.
Definition at line 191 of file NetworkInterface.cc.
References m_out_vc_state, Consumer::scheduleEvent(), and VC_AB_.
void NetworkInterface::init_net_ptr (GarnetNetwork * net_ptr) [inline]
Definition at line 75 of file NetworkInterface.hh.
References m_net_ptr.
bool NetworkInterface::isBufferNotFull (int vc, int inport) [inline, virtual]
Reimplemented from FlexibleConsumer.
Definition at line 66 of file NetworkInterface.hh.
void NetworkInterface::print (std::ostream & out) const [virtual]
Implements Consumer.
Definition at line 383 of file NetworkInterface.cc.
void NetworkInterface::release_vc (int out_port, int vc, Cycles release_time) [virtual]
Reimplemented from FlexibleConsumer.
Definition at line 201 of file NetworkInterface.cc.
References ACTIVE_, IDLE_, m_out_vc_state, and Consumer::scheduleEvent().
void NetworkInterface::request_vc (int in_vc, int in_port, NetDest destination, Cycles request_time) [virtual]
Reimplemented from FlexibleConsumer.
Definition at line 114 of file NetworkInterface.cc.
References NetworkLink::grant_vc_link(), and inNetLink.
void NetworkInterface::scheduleOutputLink () [private]
Definition at line 301 of file NetworkInterface.cc.
References ACTIVE_, ClockedObject::clockEdge(), ClockedObject::curCycle(), ArmISA::i, flitBuffer::insert(), NetworkLink::isBufferNotFull_link(), m_ni_buffers, m_num_vcs, m_out_vc_state, m_vc_round_robin, outNetLink, outSrcQueue, Consumer::scheduleEventAbsolute(), and flit::set_time().
Referenced by wakeup().
void NetworkInterface::wakeup () [virtual]
Implements Consumer.
Definition at line 242 of file NetworkInterface.cc.
References ArmISA::b, checkReschedule(), NetworkLink::consumeLink(), ClockedObject::curCycle(), MessageBuffer::dequeue(), DPRINTF, flitisizeMessage(), flit::get_delay(), flit::get_enqueue_time(), flit::get_msg_ptr(), flit::get_type(), flit::get_vc(), flit::get_vnet(), HEAD_TAIL_, BaseGarnetNetwork::increment_network_latency(), BaseGarnetNetwork::increment_queueing_latency(), BaseGarnetNetwork::increment_received_flits(), inNetLink, inNode_ptr, NetworkLink::isReady(), MessageBuffer::isReady(), m_id, m_net_ptr, outNode_ptr, MessageBuffer::peekMsgPtr(), NetworkLink::release_vc_link(), scheduleOutputLink(), and TAIL_.
Member Data Documentation
NetworkLink* NetworkInterface::inNetLink [private]
Definition at line 87 of file NetworkInterface.hh.
Referenced by addInPort(), request_vc(), and wakeup().
std::vector<MessageBuffer *> NetworkInterface::inNode_ptr [private]
Definition at line 96 of file NetworkInterface.hh.
Referenced by addNode(), checkReschedule(), and wakeup().
NodeID NetworkInterface::m_id [private]
Definition at line 80 of file NetworkInterface.hh.
Referenced by NetworkInterface(), and wakeup().
GarnetNetwork* NetworkInterface::m_net_ptr [private]
Definition at line 78 of file NetworkInterface.hh.
Referenced by calculateVC(), flitisizeMessage(), init_net_ptr(), and wakeup().
std::vector<flitBuffer *> NetworkInterface::m_ni_buffers [private]
Definition at line 93 of file NetworkInterface.hh.
Referenced by checkReschedule(), flitisizeMessage(), functionalRead(), functionalWrite(), NetworkInterface(), scheduleOutputLink(), and ~NetworkInterface().
uint32_t NetworkInterface::m_num_vcs [private]
Definition at line 79 of file NetworkInterface.hh.
Referenced by checkReschedule(), NetworkInterface(), and scheduleOutputLink().
std::vector<OutVcState *> NetworkInterface::m_out_vc_state [private]
Definition at line 82 of file NetworkInterface.hh.
Referenced by calculateVC(), flitisizeMessage(), grant_vc(), NetworkInterface(), release_vc(), scheduleOutputLink(), and ~NetworkInterface().
std::vector<int> NetworkInterface::m_vc_allocator [private]
Definition at line 83 of file NetworkInterface.hh.
Referenced by calculateVC(), and NetworkInterface().
uint32_t NetworkInterface::m_vc_per_vnet [private]
Definition at line 79 of file NetworkInterface.hh.
Referenced by calculateVC(), and NetworkInterface().
int NetworkInterface::m_vc_round_robin [private]
Definition at line 84 of file NetworkInterface.hh.
Referenced by NetworkInterface(), and scheduleOutputLink().
uint32_t NetworkInterface::m_virtual_networks [private]
Definition at line 79 of file NetworkInterface.hh.
Referenced by NetworkInterface().
NetworkLink* NetworkInterface::outNetLink [private]
Definition at line 88 of file NetworkInterface.hh.
Referenced by addOutPort(), flitisizeMessage(), and scheduleOutputLink().
std::vector<MessageBuffer *> NetworkInterface::outNode_ptr [private]
Definition at line 99 of file NetworkInterface.hh.
Referenced by addNode(), and wakeup().
flitBuffer* NetworkInterface::outSrcQueue [private]
Definition at line 85 of file NetworkInterface.hh.
Referenced by addOutPort(), functionalRead(), functionalWrite(), scheduleOutputLink(), and ~NetworkInterface().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/flexible-pipeline/NetworkInterface.hh
mem/ruby/network/garnet/flexible-pipeline/NetworkInterface.cc