gem5: StridePrefetcher Class Reference
StridePrefetcher Class Reference
#include <stride.hh>
Classes
class PCTable
struct StrideEntry
Public Member Functions
StridePrefetcher (const StridePrefetcherParams *p)
void calculatePrefetch (const PacketPtr &pkt, std::vector< Addr > &addresses)
Protected Member Functions
bool pcTableHit (Addr pc, bool is_secure, int master_id, StrideEntry *&entry)
StrideEntry * pcTableVictim (Addr pc, int master_id)
Addr pcHash (Addr pc) const
Protected Attributes
const int maxConf
const int threshConf
const int minConf
const int startConf
const int pcTableAssoc
const int pcTableSets
const bool useMasterId
const int degree
PCTable pcTable
Detailed Description
Definition at line 55 of file stride.hh.
Constructor & Destructor Documentation
StridePrefetcher::StridePrefetcher (const StridePrefetcherParams * p)
Definition at line 53 of file stride.cc.
References isPowerOf2(), BasePrefetcher::onInst, and pcTableSets.
Member Function Documentation
void StridePrefetcher::calculatePrefetch (const PacketPtr & pkt, std::vector< Addr > & addresses) [virtual]
Implements QueuedPrefetcher.
Definition at line 100 of file stride.cc.
References BasePrefetcher::blkSize, StridePrefetcher::StrideEntry::confidence, ArmISA::d, degree, DPRINTF, Packet::getAddr(), Request::getPC(), Request::hasPC(), StridePrefetcher::StrideEntry::instAddr, StridePrefetcher::StrideEntry::isSecure, Packet::isSecure(), StridePrefetcher::StrideEntry::lastAddr, Request::masterId(), maxConf, minConf, MipsISA::pc, pcTableHit(), pcTableVictim(), QueuedPrefetcher::pfSpanPage, Packet::req, BasePrefetcher::samePage(), startConf, StridePrefetcher::StrideEntry::stride, threshConf, and useMasterId.
Addr StridePrefetcher::pcHash (Addr pc) const [inline, protected]
Definition at line 179 of file stride.cc.
References floorLog2(), and pcTableSets.
Referenced by pcTableHit(), and pcTableVictim().
bool StridePrefetcher::pcTableHit (Addr pc, bool is_secure, int master_id, StrideEntry *& entry) [inline, protected]
Definition at line 198 of file stride.cc.
References DPRINTF, pcHash(), pcTable, and pcTableAssoc.
Referenced by calculatePrefetch().
StridePrefetcher::StrideEntry * StridePrefetcher::pcTableVictim (Addr pc, int master_id) [inline, protected]
Definition at line 187 of file stride.cc.
References DPRINTF, pcHash(), pcTable, pcTableAssoc, Random::random(), and random_mt.
Referenced by calculatePrefetch().
Member Data Documentation
const int StridePrefetcher::degree [protected]
Definition at line 68 of file stride.hh.
Referenced by calculatePrefetch().
const int StridePrefetcher::maxConf [protected]
Definition at line 58 of file stride.hh.
Referenced by calculatePrefetch().
const int StridePrefetcher::minConf [protected]
Definition at line 60 of file stride.hh.
Referenced by calculatePrefetch().
PCTable StridePrefetcher::pcTable [protected]
Definition at line 106 of file stride.hh.
Referenced by pcTableHit(), and pcTableVictim().
const int StridePrefetcher::pcTableAssoc [protected]
Definition at line 63 of file stride.hh.
Referenced by pcTableHit(), and pcTableVictim().
const int StridePrefetcher::pcTableSets [protected]
Definition at line 64 of file stride.hh.
Referenced by pcHash(), and StridePrefetcher().
const int StridePrefetcher::startConf [protected]
Definition at line 61 of file stride.hh.
Referenced by calculatePrefetch().
const int StridePrefetcher::threshConf [protected]
Definition at line 59 of file stride.hh.
Referenced by calculatePrefetch().
const bool StridePrefetcher::useMasterId [protected]
Definition at line 66 of file stride.hh.
Referenced by calculatePrefetch().
The documentation for this class was generated from the following files:
mem/cache/prefetch/stride.hh
mem/cache/prefetch/stride.cc