gem5: EtherLink::Interface Class Reference
EtherLink::Interface Class Reference
#include <etherlink.hh>
Public Member Functions
Interface (const std::string &name, Link *txlink, Link *rxlink)
bool recvPacket (EthPacketPtr packet)
void sendDone ()
bool isBusy ()
Private Attributes
Link * txlink
Detailed Description
Definition at line 110 of file etherlink.hh.
Constructor & Destructor Documentation
EtherLink::Interface::Interface (const std::string & name, Link * txlink, Link * rxlink)
Member Function Documentation
bool EtherLink::Interface::isBusy () [inline, virtual]
Reimplemented from EtherInt.
Definition at line 119 of file etherlink.hh.
References EtherLink::Link::busy(), and txlink.
bool EtherLink::Interface::recvPacket (EthPacketPtr packet) [inline, virtual]
Implements EtherInt.
Definition at line 117 of file etherlink.hh.
References EtherLink::Link::transmit(), and txlink.
void EtherLink::Interface::sendDone () [inline, virtual]
Implements EtherInt.
Definition at line 118 of file etherlink.hh.
References EtherInt::peer, and EtherInt::sendDone().
Referenced by EtherLink::Link::txDone().
Member Data Documentation
Link* EtherLink::Interface::txlink [private]
Definition at line 113 of file etherlink.hh.
Referenced by isBusy(), and recvPacket().
The documentation for this class was generated from the following file:
dev/etherlink.hh