gem5: BaseTLB::Translation Class Reference
BaseTLB::Translation Class Reference
#include <tlb.hh>
Public Member Functions
virtual ~Translation ()
virtual void markDelayed ()=0
Signal that the translation has been delayed due to a hw page table walk.
virtual void finish (const Fault &fault, RequestPtr req, ThreadContext *tc, Mode mode)=0
virtual bool squashed () const
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
Detailed Description
Definition at line 89 of file tlb.hh.
Constructor & Destructor Documentation
virtual BaseTLB::Translation::~Translation () [inline, virtual]
Definition at line 92 of file tlb.hh.
Member Function Documentation
virtual void BaseTLB::Translation::finish (const Fault & fault, RequestPtr req, ThreadContext * tc, Mode mode) [pure virtual]
Implemented in ArmISA::Stage2LookUp, ArmISA::Stage2MMU::Stage2Translation, Minor::Fetch1::FetchRequest, Minor::LSQ::SpecialDataRequest, Minor::LSQ::SingleDataRequest, Minor::LSQ::SplitDataRequest, DefaultFetch< Impl >::FetchTranslation, TimingSimpleCPU::FetchTranslation, and DataTranslation< ExecContextPtr >.
Referenced by ArmISA::TableWalker::doL1DescriptorWrapper(), ArmISA::TableWalker::doL2DescriptorWrapper(), ArmISA::TableWalker::doLongDescriptorWrapper(), ArmISA::Stage2LookUp::finish(), ArmISA::TableWalker::processWalkWrapper(), X86ISA::Walker::WalkerState::recvPacket(), X86ISA::Walker::startWalkWrapper(), ArmISA::TLB::translateComplete(), X86ISA::TLB::translateTiming(), SparcISA::TLB::translateTiming(), PowerISA::TLB::translateTiming(), MipsISA::TLB::translateTiming(), GenericTLB::translateTiming(), and AlphaISA::TLB::translateTiming().
virtual void BaseTLB::Translation::markDelayed () [pure virtual]
Signal that the translation has been delayed due to a hw page table walk.
Implemented in ArmISA::Stage2LookUp, ArmISA::Stage2MMU::Stage2Translation, Minor::Fetch1::FetchRequest, Minor::LSQ::LSQRequest, DefaultFetch< Impl >::FetchTranslation, TimingSimpleCPU::FetchTranslation, and DataTranslation< ExecContextPtr >.
Referenced by ArmISA::TLB::translateComplete().
virtual bool BaseTLB::Translation::squashed () const [inline, virtual]
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
@ return Is the instruction that requested this translation squashed?
Reimplemented in DataTranslation< ExecContextPtr >.
Definition at line 114 of file tlb.hh.
Referenced by ArmISA::TableWalker::processWalkWrapper(), and X86ISA::Walker::startWalkWrapper().
The documentation for this class was generated from the following file:
arch/generic/tlb.hh