gem5: OutputDirectory Class Reference
OutputDirectory Class Reference
Interface for creating files in a gem5 output directory.
#include <output.hh>
Public Member Functions
OutputDirectory ()
Constructor.
~OutputDirectory ()
Destructor.
std::string resolve (const std::string &name) const
Returns relative file names prepended with name of this directory.
std::ostream * openFile (const std::string &filename, std::ios_base::openmode mode=std::ios::trunc)
Opens a file (optionally compressed).
void setDirectory (const std::string &dir)
Sets name of this directory.
const std::string & directory () const
Gets name of this directory.
std::ostream * create (const std::string &name, bool binary=false)
Creates a file in this directory (optionally compressed).
void close (std::ostream *openStream)
Closes a file stream.
std::ostream * find (const std::string &name) const
Finds stream associated with a file.
bool isFile (const std::string &name) const
Determines whether a file name corresponds to a file in this directory.
std::string createSubdirectory (const std::string &name) const
Creates a subdirectory within this directory.
void remove (const std::string &name, bool recursive=false)
Removes a specified file or subdirectory.
Static Public Member Functions
static bool isFile (const std::ostream *os)
Returns true if stream is open and not standard output or error.
static bool isFile (const std::ostream &os)
Returns true if stream is open and not standard output or error.
Protected Member Functions
std::ostream * checkForStdio (const std::string &name) const
Determines whether given file name corresponds to standard output streams.
Private Types
typedef std::map< std::string,
std::ostream * > map_t
File names and associated stream handles.
Private Attributes
map_t files
Open file streams within this directory.
std::string dir
Name of this directory.
Static Private Attributes
static const char PATH_SEPARATOR = '/'
System-specific path separator character.
Detailed Description
Interface for creating files in a gem5 output directory.
Definition at line 40 of file output.hh.
Member Typedef Documentation
typedef std::map<std::string, std::ostream *> OutputDirectory::map_t [private]
File names and associated stream handles.
Definition at line 44 of file output.hh.
Constructor & Destructor Documentation
OutputDirectory::OutputDirectory ()
Constructor.
Definition at line 55 of file output.cc.
OutputDirectory::~OutputDirectory ()
Destructor.
Definition at line 58 of file output.cc.
References files, and ArmISA::i.
Member Function Documentation
std::ostream* OutputDirectory::checkForStdio (const std::string & name) const [protected]
Determines whether given file name corresponds to standard output streams.
Parameters:
name name of file to check
Returns:
output stream for standard output or error stream if name corresponds to one or the other; NULL otherwise
void OutputDirectory::close (std::ostream * openStream)
Closes a file stream.
Stream must have been opened through this interface, or sim will fail.
Parameters:
openStream open stream to close
Referenced by VncInput::captureFrameBuffer(), AddressTracer::close_stream(), StackDistanceCounter::dump(), PolicySelectorPlotter::resetStats(), and SimPoint::~SimPoint().
std::ostream* OutputDirectory::create (const std::string & name, bool binary = false)
Creates a file in this directory (optionally compressed).
Will open a file as a compressed stream if filename ends in .gz.
Parameters:
name name of file to create (without this directory's name leading it)
binary true to create a binary file; false otherwise
Returns:
stream to the opened file
Referenced by VncInput::captureFrameBuffer(), Pl111::dmaDone(), StackDistanceCounter::dump(), SimpleThread::dumpFuncProfile(), O3ThreadState< Impl >::dumpFuncProfile(), HDLcd::endFrame(), Stats::initText(), AddressTracer::open_stream(), PolicySelectorPlotter::resetStats(), SimPoint::SimPoint(), LinuxArmSystem::startup(), and Terminal::Terminal().
std::string OutputDirectory::createSubdirectory (const std::string & name) const
Creates a subdirectory within this directory.
Parameters:
name name of subdirectory
Returns:
the new subdirectory's name suffixed with a path separator
Referenced by VncInput::VncInput().
const string & OutputDirectory::directory () const
Gets name of this directory.
Returns:
name of this directory
Definition at line 141 of file output.cc.
References dir, and panic.
Referenced by AtomicSimpleCPU::AtomicSimpleCPU().
std::ostream* OutputDirectory::find (const std::string & name) const
Finds stream associated with a file.
Parameters:
name of file
Returns:
stream to specified file or NULL if file does not exist
Referenced by Stats::initText(), and Terminal::Terminal().
static bool OutputDirectory::isFile (const std::ostream & os) [inline, static]
Returns true if stream is open and not standard output or error.
Parameters:
os output stream to evaluate
Returns:
true if os is non-NULL and not cout or cerr
Definition at line 154 of file output.hh.
References isFile().
bool OutputDirectory::isFile (const std::string & name) const
Determines whether a file name corresponds to a file in this directory.
Parameters:
name name of file to evaluate
Returns:
true iff file has been opened in this directory or exists on the file system within this directory
bool OutputDirectory::isFile (const std::ostream * os) [static]
Returns true if stream is open and not standard output or error.
Parameters:
os output stream to evaluate
Returns:
true if os is non-NULL and not cout or cerr
Definition at line 186 of file output.cc.
Referenced by isFile().
std::ostream* OutputDirectory::openFile (const std::string & filename, std::ios_base::openmode mode = std::ios::trunc)
Opens a file (optionally compressed).
Will open a file as a compressed stream if filename ends in .gz.
Parameters:
filename file to open
mode attributes to open file with
Returns:
stream pointer to opened file; will cause sim fail on error
Referenced by AtomicSimpleCPU::AtomicSimpleCPU().
void OutputDirectory::remove (const std::string & name, bool recursive = false)
Removes a specified file or subdirectory.
Will cause sim to fail for most errors. However, it will only warn the user if a directory could not be removed. This is in place to accommodate slow file systems where file deletions within a subdirectory may not be recognized quickly enough thereby causing the subsequent call to remove the directory to fail (seemingly unempty directory).
Parameters:
name name of file or subdirectory to remove; name should not be prepended with the name of this directory object
recursive set to true to attempt to recursively delete a subdirectory and its contents
Referenced by PolicySelectorPlotter::resetStats(), and VncInput::VncInput().
std::string OutputDirectory::resolve (const std::string & name) const
Returns relative file names prepended with name of this directory.
Returns absolute file names unaltered.
Parameters:
name file name to prepend with directory name
Returns:
file name prepended with base directory name or unaltered absolute file name
Referenced by CommMonitor::CommMonitor(), and Trace::InstPBTrace::createTraceFile().
void OutputDirectory::setDirectory (const std::string & dir)
Sets name of this directory.
Parameters:
dir name of this directory
Referenced by setOutputDir().
Member Data Documentation
std::string OutputDirectory::dir [private]
Name of this directory.
Definition at line 50 of file output.hh.
Referenced by directory().
map_t OutputDirectory::files [private]
Open file streams within this directory.
Definition at line 47 of file output.hh.
Referenced by ~OutputDirectory().
const char OutputDirectory::PATH_SEPARATOR = '/' [static, private]
System-specific path separator character.
Definition at line 53 of file output.hh.
The documentation for this class was generated from the following files:
base/output.hh
base/output.cc