gem5: ArmISA::BranchImmImmReg64 Class Reference
ArmISA::BranchImmImmReg64 Class Reference
#include <branch64.hh>
Public Member Functions
BranchImmImmReg64 (const char *mnem, ExtMachInst _machInst, OpClass __opClass, int64_t _imm1, int64_t _imm2, IntRegIndex _op1)
ArmISA::PCState branchTarget (const ArmISA::PCState &branchPC) const
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
int64_t imm1
int64_t imm2
IntRegIndex op1
Detailed Description
Definition at line 141 of file branch64.hh.
Constructor & Destructor Documentation
ArmISA::BranchImmImmReg64::BranchImmImmReg64 (const char * mnem, ExtMachInst _machInst, OpClass __opClass, int64_t _imm1, int64_t _imm2, IntRegIndex _op1) [inline]
Definition at line 149 of file branch64.hh.
Member Function Documentation
ArmISA::PCState ArmISA::BranchImmImmReg64::branchTarget (const ArmISA::PCState & branchPC) const
Definition at line 64 of file branch64.cc.
References imm2.
std::string ArmISA::BranchImmImmReg64::generateDisassembly (Addr pc, const SymbolTable * symtab) const [virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 135 of file branch64.cc.
References ccprintf(), imm1, imm2, op1, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), ArmISA::ArmStaticInst::printTarget(), and ArmISA::ss.
Member Data Documentation
int64_t ArmISA::BranchImmImmReg64::imm1 [protected]
Definition at line 144 of file branch64.hh.
Referenced by generateDisassembly().
int64_t ArmISA::BranchImmImmReg64::imm2 [protected]
Definition at line 145 of file branch64.hh.
Referenced by branchTarget(), and generateDisassembly().
IntRegIndex ArmISA::BranchImmImmReg64::op1 [protected]
Definition at line 146 of file branch64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/branch64.hh
arch/arm/insts/branch64.cc