gem5: ArmISA::RemoteGDB Class Reference
ArmISA::RemoteGDB Class Reference
#include <remote_gdb.hh>
Public Member Functions
RemoteGDB (System *_system, ThreadContext *tc)
Protected Member Functions
bool acc (Addr addr, size_t len)
bool write (Addr addr, size_t size, const char *data)
void getregs ()
void setregs ()
Detailed Description
Definition at line 83 of file remote_gdb.hh.
Constructor & Destructor Documentation
RemoteGDB::RemoteGDB (System * _system, ThreadContext * tc)
Definition at line 164 of file remote_gdb.cc.
Member Function Documentation
bool RemoteGDB::acc (Addr addr, size_t len) [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 173 of file remote_gdb.cc.
References BaseRemoteGDB::context, DPRINTF, FullSystem, ThreadContext::getProcessPtr(), PageTableBase::lookup(), ArmISA::PageBytes, Process::pTable, and ArmISA::virtvalid().
void RemoteGDB::getregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 200 of file remote_gdb.cc.
References BaseRemoteGDB::GdbRegCache::bytes(), BaseRemoteGDB::context, DPRINTF, ArmISA::GDB32_CPSR, ArmISA::GDB32_F0, ArmISA::GDB32_FPSCR, ArmISA::GDB32_R0, ArmISA::GDB64_CPSR, ArmISA::GDB64_PC, ArmISA::GDB64_SPX, ArmISA::GDB64_V0_32, ArmISA::GDB64_X0, BaseRemoteGDB::gdbregs, ArmISA::i, ArmISA::inAArch64(), ArmISA::INTREG_LR, ArmISA::INTREG_R0, ArmISA::INTREG_R1, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R2, ArmISA::INTREG_R3, ArmISA::INTREG_R4, ArmISA::INTREG_R5, ArmISA::INTREG_R6, ArmISA::INTREG_R7, ArmISA::INTREG_R8, ArmISA::INTREG_R9, ArmISA::INTREG_SP, ArmISA::INTREG_SPX, ArmISA::INTREG_X0, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_FPSCR, ArmISA::NumFloatV7ArchRegs, ThreadContext::pcState(), ThreadContext::readFloatRegBits(), ThreadContext::readIntReg(), ThreadContext::readMiscRegNoEffect(), BaseRemoteGDB::GdbRegCache::regs, BaseRemoteGDB::GdbRegCache::regs32, and BaseRemoteGDB::GdbRegCache::regs64.
void RemoteGDB::setregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 261 of file remote_gdb.cc.
References BaseRemoteGDB::context, DPRINTF, ArmISA::GDB32_CPSR, ArmISA::GDB32_F0, ArmISA::GDB32_FPSCR, ArmISA::GDB32_R0, ArmISA::GDB64_CPSR, ArmISA::GDB64_PC, ArmISA::GDB64_SPX, ArmISA::GDB64_V0_32, ArmISA::GDB64_X0, BaseRemoteGDB::gdbregs, ArmISA::i, ArmISA::inAArch64(), ArmISA::INTREG_LR, ArmISA::INTREG_R0, ArmISA::INTREG_R1, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R2, ArmISA::INTREG_R3, ArmISA::INTREG_R4, ArmISA::INTREG_R5, ArmISA::INTREG_R6, ArmISA::INTREG_R7, ArmISA::INTREG_R8, ArmISA::INTREG_R9, ArmISA::INTREG_SP, ArmISA::INTREG_SPX, ArmISA::INTREG_X0, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_FPSCR, ArmISA::NumFloatV7ArchRegs, ThreadContext::pcState(), BaseRemoteGDB::GdbRegCache::regs32, BaseRemoteGDB::GdbRegCache::regs64, ThreadContext::setFloatRegBits(), ThreadContext::setIntReg(), ThreadContext::setMiscReg(), and ThreadContext::setMiscRegNoEffect().
bool RemoteGDB::write (Addr addr, size_t size, const char * data) [protected, virtual]
Reimplemented from BaseRemoteGDB.
Definition at line 320 of file remote_gdb.cc.
The documentation for this class was generated from the following files:
arch/arm/remote_gdb.hh
arch/arm/remote_gdb.cc