gem5: BaseRemoteGDB::HardBreakpoint Class Reference
BaseRemoteGDB::HardBreakpoint Class Reference
#include <remote_gdb.hh>
Public Member Functions
HardBreakpoint (BaseRemoteGDB *_gdb, Addr addr)
const std::string name () const
virtual void process (ThreadContext *tc)
Public Attributes
int refcount
Private Attributes
BaseRemoteGDB * gdb
Detailed Description
Definition at line 243 of file remote_gdb.hh.
Constructor & Destructor Documentation
BaseRemoteGDB::HardBreakpoint::HardBreakpoint (BaseRemoteGDB * _gdb, Addr addr)
Definition at line 582 of file remote_gdb.cc.
References DPRINTF, and PCEvent::evpc.
Member Function Documentation
const std::string BaseRemoteGDB::HardBreakpoint::name () const [inline, virtual]
Reimplemented from PCEvent.
Definition at line 253 of file remote_gdb.hh.
References gdb, and BaseRemoteGDB::name().
void BaseRemoteGDB::HardBreakpoint::process (ThreadContext * tc) [virtual]
Implements PCEvent.
Definition at line 590 of file remote_gdb.cc.
References BaseRemoteGDB::context, DPRINTF, gdb, PCEvent::pc(), and BaseRemoteGDB::trap().
Member Data Documentation
BaseRemoteGDB* BaseRemoteGDB::HardBreakpoint::gdb [private]
Definition at line 246 of file remote_gdb.hh.
Referenced by name(), and process().
int BaseRemoteGDB::HardBreakpoint::refcount
Definition at line 249 of file remote_gdb.hh.
Referenced by BaseRemoteGDB::insertHardBreak(), and BaseRemoteGDB::removeHardBreak().
The documentation for this class was generated from the following files:
base/remote_gdb.hh
base/remote_gdb.cc