gem5: VirtIOBlock Class Reference
VirtIOBlock Class Reference
VirtIO block device.
#include <block.hh>
Classes
struct BlkRequest
VirtIO block device request as sent by guest.
struct Config
Block device configuration structure.
class RequestQueue
Virtqueue for disk requests.
Public Types
typedef VirtIOBlockParams Params
Public Member Functions
VirtIOBlock (Params *params)
virtual ~VirtIOBlock ()
void readConfig (PacketPtr pkt, Addr cfgOffset)
Read from the configuration space of a device.
Protected Member Functions
Status read (const BlkRequest &req, VirtDescriptor *desc_chain, size_t off_data, size_t size)
Device read request.
Status write (const BlkRequest &req, VirtDescriptor *desc_chain, size_t off_data, size_t size)
Device write request.
Protected Attributes
struct VirtIOBlock::Config M5_ATTR_PACKED
Block device configuration structure.
Config config
struct VirtIOBlock::BlkRequest M5_ATTR_PACKED
VirtIO block device request as sent by guest.
RequestQueue qRequests
Device I/O request queue.
DiskImage & image
Image backing this device.
Static Protected Attributes
static const DeviceId ID_BLOCK = 0x02
Feature bits
static const FeatureBits F_SIZE_MAX = (1 << 1)
static const FeatureBits F_SEG_MAX = (1 << 2)
static const FeatureBits F_GEOMETRY = (1 << 4)
static const FeatureBits F_RO = (1 << 5)
static const FeatureBits F_BLK_SIZE = (1 << 6)
static const FeatureBits F_TOPOLOGY = (1 << 10)
VirtIO block requests
typedef uint32_t RequestType
static const RequestType T_IN = 0
Read request.
static const RequestType T_OUT = 1
Write request.
static const RequestType T_FLUSH = 4
Flush device buffers.
VirtIO block request status
typedef uint8_t Status
static const Status S_OK = 0
Request succeeded.
static const Status S_IOERR = 1
Request failed due to a device error.
static const Status S_UNSUPP = 2
Request not supported.
Detailed Description
VirtIO block device.
The block device uses the following queues:
Requests
A guest issues a request by creating a descriptor chain that starts with a BlkRequest. Immediately after the BlkRequest follows the data for the request. The data buffer(s) are either input or output descriptors depending on the request type. The last byte in the descriptor chain should always be writable by the host and contains the request status code (OK/Error).
The protocol supports asynchronous request completion by returning descriptor chains when they have been populated by the backing store. However, there is little point in doing so here.
See also:
https://github.com/rustyrussell/virtio-spec
http://docs.oasis-open.org/virtio/virtio/v1.0/virtio-v1.0.html
Definition at line 69 of file block.hh.
Member Typedef Documentation
typedef VirtIOBlockParams VirtIOBlock::Params
Reimplemented from SimObject.
Definition at line 72 of file block.hh.
typedef uint32_t VirtIOBlock::RequestType [protected]
Definition at line 106 of file block.hh.
typedef uint8_t VirtIOBlock::Status [protected]
Definition at line 118 of file block.hh.
Constructor & Destructor Documentation
VirtIOBlock::VirtIOBlock (Params * params)
Definition at line 45 of file block.cc.
References VirtIOBlock::Config::capacity, config, image, qRequests, VirtIODeviceBase::registerQueue(), and DiskImage::size().
VirtIOBlock::~VirtIOBlock () [virtual]
Definition at line 56 of file block.cc.
Member Function Documentation
VirtIOBlock::Status VirtIOBlock::read (const BlkRequest & req, VirtDescriptor * desc_chain, size_t off_data, size_t size) [protected]
Device read request.
Parameters:
req Disk request from guest.
desc_chain Request descriptor chain (from start of request)
off_data Offset into the descriptor chain where data should be written.
size Request data size.
Definition at line 70 of file block.cc.
References VirtDescriptor::chainWrite(), DPRINTF, image, ArmISA::offset, panic, DiskImage::read(), S_IOERR, S_OK, VirtIOBlock::BlkRequest::sector, SectorSize, and warn.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor().
void VirtIOBlock::readConfig (PacketPtr pkt, Addr cfgOffset) [virtual]
Read from the configuration space of a device.
This method is called by the transport interface to read data from a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning:
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters:
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
Reimplemented from VirtIODeviceBase.
Definition at line 61 of file block.cc.
References VirtIOBlock::Config::capacity, config, htov_legacy(), and VirtIODeviceBase::readConfigBlob().
VirtIOBlock::Status VirtIOBlock::write (const BlkRequest & req, VirtDescriptor * desc_chain, size_t off_data, size_t size) [protected]
Device write request.
Parameters:
req Disk request from guest.
desc_chain Request descriptor chain (from start of request)
off_data Offset into the descriptor chain where data should be read.
size Request data size.
Definition at line 96 of file block.cc.
References VirtDescriptor::chainRead(), DPRINTF, image, ArmISA::offset, panic, S_IOERR, S_OK, VirtIOBlock::BlkRequest::sector, SectorSize, warn, and DiskImage::write().
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor().
Member Data Documentation
Config VirtIOBlock::config [protected]
Definition at line 90 of file block.hh.
Referenced by readConfig(), and VirtIOBlock().
const FeatureBits VirtIOBlock::F_BLK_SIZE = (1 << 6) [static, protected]
Definition at line 99 of file block.hh.
const FeatureBits VirtIOBlock::F_GEOMETRY = (1 << 4) [static, protected]
Definition at line 97 of file block.hh.
const FeatureBits VirtIOBlock::F_RO = (1 << 5) [static, protected]
Definition at line 98 of file block.hh.
const FeatureBits VirtIOBlock::F_SEG_MAX = (1 << 2) [static, protected]
Definition at line 96 of file block.hh.
const FeatureBits VirtIOBlock::F_SIZE_MAX = (1 << 1) [static, protected]
Definition at line 95 of file block.hh.
const FeatureBits VirtIOBlock::F_TOPOLOGY = (1 << 10) [static, protected]
Definition at line 100 of file block.hh.
const DeviceId VirtIOBlock::ID_BLOCK = 0x02 [static, protected]
Definition at line 79 of file block.hh.
DiskImage& VirtIOBlock::image [protected]
Image backing this device.
Definition at line 183 of file block.hh.
Referenced by read(), VirtIOBlock(), and write().
struct VirtIOBlock::BlkRequest VirtIOBlock::M5_ATTR_PACKED [protected]
VirtIO block device request as sent by guest.
struct VirtIOBlock::Config VirtIOBlock::M5_ATTR_PACKED [protected]
Block device configuration structure.
Note:
This needs to be changed if the supported feature set changes!
RequestQueue VirtIOBlock::qRequests [protected]
Device I/O request queue.
Definition at line 180 of file block.hh.
Referenced by VirtIOBlock().
const Status VirtIOBlock::S_IOERR = 1 [static, protected]
Request failed due to a device error.
Definition at line 122 of file block.hh.
Referenced by read(), and write().
const Status VirtIOBlock::S_OK = 0 [static, protected]
Request succeeded.
Definition at line 120 of file block.hh.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor(), read(), and write().
const Status VirtIOBlock::S_UNSUPP = 2 [static, protected]
Request not supported.
Definition at line 124 of file block.hh.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor().
const RequestType VirtIOBlock::T_FLUSH = 4 [static, protected]
Flush device buffers.
Definition at line 112 of file block.hh.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor().
const RequestType VirtIOBlock::T_IN = 0 [static, protected]
Read request.
Definition at line 108 of file block.hh.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor().
const RequestType VirtIOBlock::T_OUT = 1 [static, protected]
Write request.
Definition at line 110 of file block.hh.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor().
The documentation for this class was generated from the following files:
dev/virtio/block.hh
dev/virtio/block.cc