gem5: BaseTags Class Reference
BaseTags Class Reference
A common base class of Cache tagstore objects.
#include <base.hh>
Public Types
typedef BaseTagsParams Params
Public Member Functions
BaseTags (const Params *p)
virtual ~BaseTags ()
Destructor.
void setCache (BaseCache *_cache)
Set the parent cache back pointer.
virtual void regStats ()
Register local statistics.
virtual void cleanupRefs ()
Average in the reference count for valid blocks when the simulation exits.
virtual void computeStats ()
Computes stats just prior to dump event.
virtual void clearLocks ()
iterated through all blocks and clear all locks Needed to clear all lock tracking at once
virtual std::string print () const =0
Print all tags used.
virtual CacheBlk * findBlock (Addr addr, bool is_secure) const =0
Find a block using the memory address.
int extractBlkOffset (Addr addr) const
Calculate the block offset of an address.
virtual void invalidate (CacheBlk *blk)=0
virtual CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)=0
virtual Addr extractTag (Addr addr) const =0
virtual void insertBlock (PacketPtr pkt, CacheBlk *blk)=0
virtual Addr regenerateBlkAddr (Addr tag, unsigned set) const =0
virtual CacheBlk * findVictim (Addr addr)=0
virtual int extractSet (Addr addr) const =0
virtual void forEachBlk (CacheBlkVisitor &visitor)=0
Protected Attributes
const unsigned blkSize
The block size of the cache.
const unsigned size
The size of the cache.
const Cycles accessLatency
The access latency of the cache.
BaseCache * cache
Pointer to the parent cache.
int warmupBound
The number of tags that need to be touched to meet the warmup percentage.
bool warmedUp
Marked true when the cache is warmed up.
unsigned numBlocks
the number of blocks in the cache
Stats::Vector replacements
Number of replacements of valid blocks per thread.
Stats::Average tagsInUse
Per cycle average of the number of tags that hold valid data.
Stats::Scalar totalRefs
The total number of references to a block before it is replaced.
Stats::Scalar sampledRefs
The number of reference counts sampled.
Stats::Formula avgRefs
Average number of references to a block before is was replaced.
Stats::Scalar warmupCycle
The cycle that the warmup percentage was hit.
Stats::AverageVector occupancies
Average occupancy of each requestor using the cache.
Stats::Formula avgOccs
Average occ % of each requestor using the cache.
Stats::Vector occupanciesTaskId
Occupancy of each context/cpu using the cache.
Stats::Vector2d ageTaskId
Occupancy of each context/cpu using the cache.
Stats::Formula percentOccsTaskId
Occ % of each context/cpu using the cache.
Stats::Scalar tagAccesses
Number of tags consulted over all accesses.
Stats::Scalar dataAccesses
Number of data blocks consulted over all accesses.
Detailed Description
A common base class of Cache tagstore objects.
Definition at line 65 of file base.hh.
Member Typedef Documentation
typedef BaseTagsParams BaseTags::Params
Reimplemented from SimObject.
Reimplemented in BaseSetAssoc, BIP, DIP, FALRU, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Definition at line 143 of file base.hh.
Constructor & Destructor Documentation
BaseTags::BaseTags (const Params * p)
Definition at line 56 of file base.cc.
virtual BaseTags::~BaseTags () [inline, virtual]
Destructor.
Definition at line 149 of file base.hh.
Member Function Documentation
virtual CacheBlk* BaseTags::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [pure virtual]
Implemented in BaseSetAssoc, DIP, FALRU, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Referenced by Cache::access().
virtual void BaseTags::cleanupRefs () [inline, virtual]
Average in the reference count for valid blocks when the simulation exits.
Reimplemented in BaseSetAssoc.
Definition at line 166 of file base.hh.
Referenced by BaseTagsCallback::process().
virtual void BaseTags::clearLocks () [inline, virtual]
iterated through all blocks and clear all locks Needed to clear all lock tracking at once
Reimplemented in BaseSetAssoc, and FALRU.
Definition at line 177 of file base.hh.
Referenced by Cache::access().
virtual void BaseTags::computeStats () [inline, virtual]
Computes stats just prior to dump event.
Reimplemented in BaseSetAssoc.
Definition at line 171 of file base.hh.
Referenced by BaseTagsDumpCallback::process().
int BaseTags::extractBlkOffset (Addr addr) const [inline]
Calculate the block offset of an address.
Parameters:
addr the address to get the offset of.
Returns:
the block offset.
Definition at line 194 of file base.hh.
References blkSize.
Referenced by Cache::cmpAndSwap().
virtual int BaseTags::extractSet (Addr addr) const [pure virtual]
Implemented in BaseSetAssoc, and FALRU.
Referenced by Cache::handleFill().
virtual Addr BaseTags::extractTag (Addr addr) const [pure virtual]
Implemented in BaseSetAssoc, and FALRU.
Referenced by Cache::handleFill().
virtual CacheBlk* BaseTags::findBlock (Addr addr, bool is_secure) const [pure virtual]
Find a block using the memory address.
Implemented in BaseSetAssoc, and FALRU.
Referenced by Cache::access(), Cache::findBlock(), Cache::functionalAccess(), Cache::getNextMSHR(), Cache::getTimingPacket(), Cache::inCache(), Cache::recvAtomic(), Cache::recvAtomicSnoop(), Cache::recvTimingResp(), and Cache::recvTimingSnoopReq().
virtual CacheBlk* BaseTags::findVictim (Addr addr) [pure virtual]
Implemented in BaseSetAssoc, FALRU, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Referenced by Cache::allocateBlock().
virtual void BaseTags::forEachBlk (CacheBlkVisitor & visitor) [pure virtual]
Implemented in BaseSetAssoc, and FALRU.
Referenced by Cache::isDirty(), Cache::memInvalidate(), and Cache::memWriteback().
virtual void BaseTags::insertBlock (PacketPtr pkt, CacheBlk * blk) [pure virtual]
Implemented in BaseSetAssoc, BIP, DIP, FALRU, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Referenced by Cache::access(), and Cache::handleFill().
virtual void BaseTags::invalidate (CacheBlk * blk) [pure virtual]
Implemented in BaseSetAssoc, FALRU, FLIP, FLIPProfiler, LRU, LRUProfiler, and RandomRepl.
Referenced by Cache::access(), Cache::handleSnoop(), Cache::invalidateVisitor(), Cache::recvAtomic(), Cache::recvTimingResp(), and Cache::satisfyCpuSideRequest().
virtual std::string BaseTags::print () const [pure virtual]
Print all tags used.
Implemented in BaseSetAssoc, and FALRU.
Referenced by Cache::recvTimingReq().
virtual Addr BaseTags::regenerateBlkAddr (Addr tag, unsigned set) const [pure virtual]
Implemented in BaseSetAssoc, and FALRU.
Referenced by Cache::allocateBlock(), Cache::writebackBlk(), and Cache::writebackVisitor().
void BaseTags::regStats () [virtual]
Register local statistics.
Reimplemented from SimObject.
Reimplemented in BIP, DIP, FALRU, FLIP, FLIPProfiler, and LRUProfiler.
Definition at line 71 of file base.cc.
References ageTaskId, avgOccs, avgRefs, cache, Stats::constant(), dataAccesses, System::getMasterName(), ArmISA::i, Stats::Vector2dBase< Derived, Stor >::init(), Stats::VectorBase< Derived, Stor >::init(), System::maxMasters(), maxThreadsPerCPU, Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), Stats::nonan, Stats::nozero, numBlocks, ContextSwitchTaskId::NumTaskId, occupancies, occupanciesTaskId, percentOccsTaskId, Stats::registerDumpCallback(), registerExitCallback(), replacements, sampledRefs, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), BaseCache::system, tagAccesses, tagsInUse, Stats::total, totalRefs, and warmupCycle.
void BaseTags::setCache (BaseCache * _cache)
Set the parent cache back pointer.
Parameters:
_cache Pointer to parent cache.
Definition at line 64 of file base.cc.
References cache.
Referenced by Cache::Cache().
Member Data Documentation
const Cycles BaseTags::accessLatency [protected]
The access latency of the cache.
Definition at line 73 of file base.hh.
Referenced by FALRU::accessBlock(), and BaseSetAssoc::accessBlock().
const unsigned BaseTags::blkSize [protected]
The block size of the cache.
Definition at line 69 of file base.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), FALRU::blkAlign(), FALRU::check(), extractBlkOffset(), FALRU::FALRU(), FALRU::getBlockSize(), BaseSetAssoc::getBlockSize(), FALRU::getSubBlockSize(), and BaseSetAssoc::getSubBlockSize().
BaseCache* BaseTags::cache [protected]
Pointer to the parent cache.
Definition at line 75 of file base.hh.
Referenced by BaseSetAssoc::accessBlock(), BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), regStats(), and setCache().
unsigned BaseTags::numBlocks [protected]
the number of blocks in the cache
Definition at line 86 of file base.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), FALRU::clearLocks(), BaseSetAssoc::clearLocks(), FALRU::FALRU(), FALRU::forEachBlk(), and regStats().
const unsigned BaseTags::size [protected]
The size of the cache.
Definition at line 71 of file base.hh.
Referenced by FALRU::FALRU().
bool BaseTags::warmedUp [protected]
Marked true when the cache is warmed up.
Definition at line 83 of file base.hh.
Referenced by FALRU::findVictim(), and BaseSetAssoc::insertBlock().
int BaseTags::warmupBound [protected]
The number of tags that need to be touched to meet the warmup percentage.
Definition at line 81 of file base.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), FALRU::FALRU(), FALRU::findVictim(), and BaseSetAssoc::insertBlock().
The documentation for this class was generated from the following files:
mem/cache/tags/base.hh
mem/cache/tags/base.cc