gem5: RegImmImmOp Class Reference
RegImmImmOp Class Reference
#include <misc.hh>
Protected Member Functions
RegImmImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, uint64_t _imm1, uint64_t _imm2)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
uint64_t imm1
uint64_t imm2
Detailed Description
Definition at line 293 of file misc.hh.
Constructor & Destructor Documentation
RegImmImmOp::RegImmImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, uint64_t _imm1, uint64_t _imm2) [inline, protected]
Definition at line 300 of file misc.hh.
Member Function Documentation
std::string RegImmImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 283 of file misc.cc.
References ccprintf(), dest, imm1, imm2, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex RegImmImmOp::dest [protected]
Definition at line 296 of file misc.hh.
Referenced by generateDisassembly().
uint64_t RegImmImmOp::imm1 [protected]
Definition at line 297 of file misc.hh.
Referenced by generateDisassembly().
uint64_t RegImmImmOp::imm2 [protected]
Definition at line 298 of file misc.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/misc.hh
arch/arm/insts/misc.cc