gem5: GenericTLB Class Reference
GenericTLB Class Reference
#include <tlb.hh>
Public Member Functions
void demapPage (Addr vaddr, uint64_t asn)
Fault translateAtomic (RequestPtr req, ThreadContext *tc, Mode mode)
void translateTiming (RequestPtr req, ThreadContext *tc, Translation *translation, Mode mode)
Fault finalizePhysical (RequestPtr req, ThreadContext *tc, Mode mode) const
Do post-translation physical address finalization.
Protected Member Functions
GenericTLB (const Params *p)
Detailed Description
Definition at line 118 of file tlb.hh.
Constructor & Destructor Documentation
GenericTLB::GenericTLB (const Params * p) [inline, protected]
Definition at line 121 of file tlb.hh.
Member Function Documentation
void GenericTLB::demapPage (Addr vaddr, uint64_t asn) [virtual]
Implements BaseTLB.
Definition at line 69 of file tlb.cc.
References warn.
Fault GenericTLB::finalizePhysical (RequestPtr req, ThreadContext * tc, Mode mode) const
Do post-translation physical address finalization.
This method is used by some architectures that need post-translation massaging of physical addresses. For example, X86 uses this to remap physical addresses in the APIC range to a range of physical memory not normally available to real x86 implementations.
Parameters:
req Request to updated in-place.
tc Thread context that created the request.
mode Request type (read/write/execute).
Returns:
A fault on failure, NoFault otherwise.
Definition at line 63 of file tlb.cc.
Fault GenericTLB::translateAtomic (RequestPtr req, ThreadContext * tc, Mode mode)
Definition at line 40 of file tlb.cc.
References FullSystem, ThreadContext::getProcessPtr(), MipsISA::p, panic, Process::pTable, and PageTableBase::translate().
Referenced by translateTiming().
void GenericTLB::translateTiming (RequestPtr req, ThreadContext * tc, Translation * translation, Mode mode)
Definition at line 55 of file tlb.cc.
References BaseTLB::Translation::finish(), and translateAtomic().
The documentation for this class was generated from the following files:
arch/generic/tlb.hh
arch/generic/tlb.cc