gem5: TraceGen::InputStream Class Reference
TraceGen::InputStream Class Reference
The InputStream encapsulates a trace file and the internal buffers and populates TraceElements based on the input.
Public Member Functions
InputStream (const std::string &filename)
Create a trace input stream for a given file name.
void reset ()
Reset the stream such that it can be played once again.
void init ()
Check the trace header to make sure that it is of the right format.
bool read (TraceElement &element)
Attempt to read a trace element from the stream, and also notify the caller if the end of the file was reached.
Private Attributes
ProtoInputStream trace
Input file stream for the protobuf trace.
Detailed Description
The InputStream encapsulates a trace file and the internal buffers and populates TraceElements based on the input.
Definition at line 544 of file generators.hh.
Constructor & Destructor Documentation
TraceGen::InputStream::InputStream (const std::string & filename)
Create a trace input stream for a given file name.
Parameters:
filename Path to the file to read from
Definition at line 410 of file generators.cc.
References init().
Member Function Documentation
void TraceGen::InputStream::init ()
Check the trace header to make sure that it is of the right format.
Definition at line 417 of file generators.cc.
References SimClock::Frequency, panic, ProtoInputStream::read(), and trace.
Referenced by InputStream(), and reset().
bool TraceGen::InputStream::read (TraceElement & element)
Attempt to read a trace element from the stream, and also notify the caller if the end of the file was reached.
Parameters:
element Trace element to populate
Returns:
True if an element could be read successfully
Definition at line 439 of file generators.cc.
References TraceGen::TraceElement::addr, TraceGen::TraceElement::blocksize, MemCmd::cmd, TraceGen::TraceElement::cmd, TraceGen::TraceElement::flags, ProtoInputStream::read(), TraceGen::TraceElement::tick, and trace.
Referenced by TraceGen::enter(), and TraceGen::getNextPacket().
void TraceGen::InputStream::reset ()
Reset the stream such that it can be played once again.
Definition at line 432 of file generators.cc.
References init(), ProtoInputStream::reset(), and trace.
Referenced by TraceGen::exit().
Member Data Documentation
ProtoInputStream TraceGen::InputStream::trace [private]
Input file stream for the protobuf trace.
Definition at line 550 of file generators.hh.
Referenced by init(), read(), and reset().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/generators.hh
cpu/testers/traffic_gen/generators.cc