gem5: VncInput Class Reference
VncInput Class Reference
#include <vncinput.hh>
Classes
struct ClientCutTextMessage
struct FrameBufferUpdateReq
struct KeyEventMessage
struct PixelEncodingsMessage
struct PixelFormat
struct PixelFormatMessage
struct PointerEventMessage
Public Types
enum ClientMessages {
ClientSetPixelFormat = 0, ClientSetEncodings = 2, ClientFrameBufferUpdate = 3, ClientKeyEvent = 4,
ClientPointerEvent = 5, ClientCutText = 6
}
Client -> Server message IDs.
typedef VncInputParams Params
Public Member Functions
VncInput (const Params *p)
virtual void setFrameBuffer (const FrameBuffer *rfb)
Set the address of the frame buffer we are going to show.
void setKeyboard (VncKeyboard *_keyboard)
Set up the device that would like to receive notifications when keys are pressed in the vnc client keyboard.
void setMouse (VncMouse *_mouse)
Setup the device that would like to receive notifications when mouse movements or button presses are received from the vnc client.
uint16_t videoWidth () const
What is the width of the screen we're displaying.
uint16_t videoHeight () const
What is the height of the screen we're displaying.
virtual void setDirty ()
The frame buffer uses this call to notify the vnc server that the frame buffer has been updated and a new image needs to be sent to the client.
Public Attributes
struct VncInput::PixelFormat M5_ATTR_PACKED
struct VncInput::PixelFormatMessage M5_ATTR_PACKED
struct
VncInput::PixelEncodingsMessage M5_ATTR_PACKED
struct
VncInput::FrameBufferUpdateReq M5_ATTR_PACKED
struct VncInput::KeyEventMessage M5_ATTR_PACKED
struct
VncInput::PointerEventMessage M5_ATTR_PACKED
struct
VncInput::ClientCutTextMessage M5_ATTR_PACKED
Protected Member Functions
virtual void frameBufferResized ()
void captureFrameBuffer ()
Captures the current frame buffer to a file.
Protected Attributes
VncKeyboard * keyboard
The device to notify when we get key events.
VncMouse * mouse
The device to notify when we get mouse events.
const FrameBuffer * fb
pointer to the actual data that is stored in the frame buffer device
uint16_t _videoWidth
the width of the frame buffer we are sending to the client
uint16_t _videoHeight
the height of the frame buffer we are sending to the client
bool captureEnabled
Flag indicating whether to capture snapshots of frame buffer or not.
int captureCurrentFrame
Current frame number being captured to a file.
std::string captureOutputDirectory
Directory to store captured frames to.
uint64_t captureLastHash
Computed hash of the last captured frame.
std::unique_ptr< Bitmap > captureBitmap
Cached bitmap object for writing out frame buffers to file.
Detailed Description
Definition at line 86 of file vncinput.hh.
Member Typedef Documentation
typedef VncInputParams VncInput::Params
Reimplemented from SimObject.
Reimplemented in VncServer.
Definition at line 155 of file vncinput.hh.
Member Enumeration Documentation
enum VncInput::ClientMessages
Client -> Server message IDs.
Enumerator:
ClientSetPixelFormat
ClientSetEncodings
ClientFrameBufferUpdate
ClientKeyEvent
ClientPointerEvent
ClientCutText
Definition at line 91 of file vncinput.hh.
Constructor & Destructor Documentation
VncInput::VncInput (const Params * p)
Definition at line 54 of file vncinput.cc.
References captureEnabled, captureOutputDirectory, OutputDirectory::createSubdirectory(), SimObject::name(), OutputDirectory::remove(), and simout.
Member Function Documentation
void VncInput::captureFrameBuffer () [protected]
Captures the current frame buffer to a file.
Definition at line 109 of file vncinput.cc.
References captureBitmap, captureCurrentFrame, captureLastHash, captureOutputDirectory, OutputDirectory::close(), OutputDirectory::create(), curTick(), fb, FrameBuffer::getHash(), and simout.
Referenced by setDirty().
virtual void VncInput::frameBufferResized () [inline, protected, virtual]
Reimplemented in VncServer.
Definition at line 198 of file vncinput.hh.
Referenced by setDirty().
void VncInput::setDirty () [virtual]
The frame buffer uses this call to notify the vnc server that the frame buffer has been updated and a new image needs to be sent to the client.
Reimplemented in VncServer.
Definition at line 89 of file vncinput.cc.
References _videoHeight, _videoWidth, captureEnabled, captureFrameBuffer(), DPRINTF, fb, frameBufferResized(), FrameBuffer::height(), FrameBuffer::width(), and ArmISA::width.
Referenced by Pl111::dmaDone(), HDLcd::endFrame(), setFrameBuffer(), Pl111::unserialize(), and HDLcd::unserialize().
void VncInput::setFrameBuffer (const FrameBuffer * rfb) [virtual]
Set the address of the frame buffer we are going to show.
To avoid copying, just have the display controller tell us where the data is instead of constanly copying it around
Parameters:
rfb frame buffer that we're going to use
Definition at line 72 of file vncinput.cc.
References captureBitmap, captureEnabled, fb, panic, and setDirty().
Referenced by HDLcd::HDLcd(), Pl111::Pl111(), Pl111::updateVideoParams(), and HDLcd::updateVideoParams().
void VncInput::setKeyboard (VncKeyboard * _keyboard) [inline]
Set up the device that would like to receive notifications when keys are pressed in the vnc client keyboard.
Parameters:
_keyboard an object that derrives from VncKeyboard
Definition at line 169 of file vncinput.hh.
References keyboard.
Referenced by Pl050::Pl050().
void VncInput::setMouse (VncMouse * _mouse) [inline]
Setup the device that would like to receive notifications when mouse movements or button presses are received from the vnc client.
Parameters:
_mouse an object that derrives from VncMouse
Definition at line 175 of file vncinput.hh.
References mouse.
Referenced by Pl050::Pl050().
uint16_t VncInput::videoHeight () const [inline]
What is the height of the screen we're displaying.
This is used for pointer/tablet devices that need to know to calculate the correct value to send to the device driver.
Returns:
the height of the simulated screen
Definition at line 189 of file vncinput.hh.
References _videoHeight.
Referenced by Pl050::mouseAt(), VncServer::sendFrameBufferResized(), VncServer::sendFrameBufferUpdate(), and VncServer::sendServerInit().
uint16_t VncInput::videoWidth () const [inline]
What is the width of the screen we're displaying.
This is used for pointer/tablet devices that need to know to calculate the correct value to send to the device driver.
Returns:
the width of the simulated screen
Definition at line 182 of file vncinput.hh.
References _videoWidth.
Referenced by Pl050::mouseAt(), VncServer::sendFrameBufferResized(), VncServer::sendFrameBufferUpdate(), and VncServer::sendServerInit().
Member Data Documentation
uint16_t VncInput::_videoHeight [protected]
the height of the frame buffer we are sending to the client
Definition at line 213 of file vncinput.hh.
Referenced by setDirty(), and videoHeight().
uint16_t VncInput::_videoWidth [protected]
the width of the frame buffer we are sending to the client
Definition at line 210 of file vncinput.hh.
Referenced by setDirty(), and videoWidth().
std::unique_ptr<Bitmap> VncInput::captureBitmap [protected]
Cached bitmap object for writing out frame buffers to file.
Definition at line 228 of file vncinput.hh.
Referenced by captureFrameBuffer(), and setFrameBuffer().
int VncInput::captureCurrentFrame [protected]
Current frame number being captured to a file.
Definition at line 219 of file vncinput.hh.
Referenced by captureFrameBuffer().
bool VncInput::captureEnabled [protected]
Flag indicating whether to capture snapshots of frame buffer or not.
Definition at line 216 of file vncinput.hh.
Referenced by setDirty(), setFrameBuffer(), and VncInput().
uint64_t VncInput::captureLastHash [protected]
Computed hash of the last captured frame.
Definition at line 225 of file vncinput.hh.
Referenced by captureFrameBuffer().
std::string VncInput::captureOutputDirectory [protected]
Directory to store captured frames to.
Definition at line 222 of file vncinput.hh.
Referenced by captureFrameBuffer(), and VncInput().
const FrameBuffer* VncInput::fb [protected]
pointer to the actual data that is stored in the frame buffer device
Definition at line 207 of file vncinput.hh.
Referenced by captureFrameBuffer(), VncServer::sendFrameBufferResized(), VncServer::sendFrameBufferUpdate(), setDirty(), and setFrameBuffer().
VncKeyboard* VncInput::keyboard [protected]
The device to notify when we get key events.
Definition at line 198 of file vncinput.hh.
Referenced by VncServer::recvKeyboardInput(), and setKeyboard().
struct VncInput::ClientCutTextMessage VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
struct VncInput::PointerEventMessage VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
struct VncInput::KeyEventMessage VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
struct VncInput::FrameBufferUpdateReq VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
struct VncInput::PixelEncodingsMessage VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
struct VncInput::PixelFormatMessage VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
struct VncInput::PixelFormat VncInput::M5_ATTR_PACKED
Reimplemented in VncServer, VncServer, VncServer, and VncServer.
VncMouse* VncInput::mouse [protected]
The device to notify when we get mouse events.
Definition at line 204 of file vncinput.hh.
Referenced by VncServer::recvPointerInput(), and setMouse().
The documentation for this class was generated from the following files:
base/vnc/vncinput.hh
base/vnc/vncinput.cc