gem5: GenericBloomFilter Class Reference
GenericBloomFilter Class Reference
#include <GenericBloomFilter.hh>
Public Member Functions
GenericBloomFilter (std::string config)
~GenericBloomFilter ()
void clear ()
void increment (const Address &addr)
void decrement (const Address &addr)
void merge (GenericBloomFilter *other_filter)
void set (const Address &addr)
void unset (const Address &addr)
AbstractBloomFilter * getFilter ()
bool isSet (const Address &addr)
int getCount (const Address &addr)
int getTotalCount ()
int getIndex (const Address &addr)
int readBit (const int index)
void writeBit (const int index, const int value)
void print (std::ostream &out) const
Private Attributes
AbstractBloomFilter * m_filter
Detailed Description
Definition at line 38 of file GenericBloomFilter.hh.
Constructor & Destructor Documentation
GenericBloomFilter::GenericBloomFilter (std::string config)
GenericBloomFilter::~GenericBloomFilter ()
Definition at line 70 of file GenericBloomFilter.cc.
References m_filter.
Member Function Documentation
void GenericBloomFilter::clear ()
Definition at line 76 of file GenericBloomFilter.cc.
References AbstractBloomFilter::clear(), and m_filter.
void GenericBloomFilter::decrement (const Address & addr)
Definition at line 88 of file GenericBloomFilter.cc.
References AbstractBloomFilter::decrement(), and m_filter.
int GenericBloomFilter::getCount (const Address & addr)
Definition at line 118 of file GenericBloomFilter.cc.
References AbstractBloomFilter::getCount(), and m_filter.
AbstractBloomFilter* GenericBloomFilter::getFilter () [inline]
Definition at line 51 of file GenericBloomFilter.hh.
References m_filter.
Referenced by merge().
int GenericBloomFilter::getIndex (const Address & addr)
Definition at line 130 of file GenericBloomFilter.cc.
References AbstractBloomFilter::getIndex(), and m_filter.
int GenericBloomFilter::getTotalCount ()
Definition at line 124 of file GenericBloomFilter.cc.
References AbstractBloomFilter::getTotalCount(), and m_filter.
void GenericBloomFilter::increment (const Address & addr)
Definition at line 82 of file GenericBloomFilter.cc.
References AbstractBloomFilter::increment(), and m_filter.
bool GenericBloomFilter::isSet (const Address & addr)
Definition at line 112 of file GenericBloomFilter.cc.
References AbstractBloomFilter::isSet(), and m_filter.
void GenericBloomFilter::merge (GenericBloomFilter * other_filter)
Definition at line 94 of file GenericBloomFilter.cc.
References getFilter(), m_filter, and AbstractBloomFilter::merge().
void GenericBloomFilter::print (std::ostream & out) const
Referenced by operator<<().
int GenericBloomFilter::readBit (const int index)
Definition at line 136 of file GenericBloomFilter.cc.
References m_filter, and AbstractBloomFilter::readBit().
void GenericBloomFilter::set (const Address & addr)
Definition at line 100 of file GenericBloomFilter.cc.
References m_filter, and AbstractBloomFilter::set().
void GenericBloomFilter::unset (const Address & addr)
Definition at line 106 of file GenericBloomFilter.cc.
References m_filter, and AbstractBloomFilter::unset().
void GenericBloomFilter::writeBit (const int index, const int value)
Definition at line 142 of file GenericBloomFilter.cc.
References m_filter, and AbstractBloomFilter::writeBit().
Member Data Documentation
AbstractBloomFilter* GenericBloomFilter::m_filter [private]
Definition at line 69 of file GenericBloomFilter.hh.
Referenced by clear(), decrement(), getCount(), getFilter(), getIndex(), getTotalCount(), increment(), isSet(), merge(), readBit(), set(), unset(), writeBit(), and ~GenericBloomFilter().
The documentation for this class was generated from the following files:
mem/ruby/filters/GenericBloomFilter.hh
mem/ruby/filters/GenericBloomFilter.cc