gem5: Profiler Class Reference
Profiler Class Reference
#include <Profiler.hh>
Public Member Functions
Profiler (const RubySystemParams *)
~Profiler ()
void wakeup ()
void regStats (const std::string &name)
void collateStats ()
AddressProfiler * getAddressProfiler ()
AddressProfiler * getInstructionProfiler ()
void addAddressTraceSample (const RubyRequest &msg, NodeID id)
bool getHotLines ()
bool getAllInstructions ()
Private Member Functions
Profiler (const Profiler &obj)
Profiler & operator= (const Profiler &obj)
Private Attributes
AddressProfiler * m_address_profiler_ptr
AddressProfiler * m_inst_profiler_ptr
Stats::Histogram delayHistogram
std::vector< Stats::Histogram * > delayVCHistogram
Stats::Histogram m_outstandReqHist
Histogram for number of outstanding requests per cycle.
Stats::Histogram m_latencyHist
Histogram for holding latency profile of all requests.
std::vector< Stats::Histogram * > m_typeLatencyHist
Stats::Histogram m_hitLatencyHist
Histogram for holding latency profile of all requests that hit in the controller connected to this sequencer.
std::vector< Stats::Histogram * > m_hitTypeLatencyHist
std::vector< Stats::Histogram * > m_hitMachLatencyHist
Histograms for profiling the latencies for requests that did not required external messages.
std::vector< std::vector
< Stats::Histogram * > > m_hitTypeMachLatencyHist
Stats::Histogram m_missLatencyHist
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
std::vector< Stats::Histogram * > m_missTypeLatencyHist
std::vector< Stats::Histogram * > m_missMachLatencyHist
Histograms for profiling the latencies for requests that required external messages.
std::vector< std::vector
< Stats::Histogram * > > m_missTypeMachLatencyHist
std::vector< Stats::Histogram * > m_IssueToInitialDelayHist
Histograms for recording the breakdown of miss latency.
std::vector< Stats::Histogram * > m_InitialToForwardDelayHist
std::vector< Stats::Histogram * > m_ForwardToFirstResponseDelayHist
std::vector< Stats::Histogram * > m_FirstResponseToCompletionDelayHist
Stats::Scalar m_IncompleteTimes [MachineType_NUM]
bool m_hot_lines
bool m_all_instructions
Detailed Description
Definition at line 66 of file Profiler.hh.
Constructor & Destructor Documentation
Profiler::Profiler (const RubySystemParams * p)
Definition at line 64 of file Profiler.cc.
References m_address_profiler_ptr, m_all_instructions, m_hot_lines, m_inst_profiler_ptr, AddressProfiler::setAllInstructions(), and AddressProfiler::setHotLines().
Profiler::~Profiler ()
Definition at line 80 of file Profiler.cc.
Profiler::Profiler (const Profiler & obj) [private]
Member Function Documentation
void Profiler::addAddressTraceSample (const RubyRequest & msg, NodeID id)
Definition at line 342 of file Profiler.cc.
References RubyRequest::getAccessMode(), RubyRequest::getLineAddress(), RubyRequest::getProgramCounter(), RubyRequest::getType(), and m_address_profiler_ptr.
void Profiler::collateStats ()
Definition at line 244 of file Profiler.cc.
References Stats::DistBase< Derived, Stor >::add(), AddressProfiler::collateStats(), delayHistogram, delayVCHistogram, g_abs_controls, AbstractController::getDelayHist(), AbstractController::getDelayVCHist(), Sequencer::getHitLatencyHist(), Sequencer::getHitMachLatencyHist(), Sequencer::getHitTypeLatencyHist(), Sequencer::getHitTypeMachLatencyHist(), Sequencer::getIncompleteTimes(), Sequencer::getInitialToForwardDelayHist(), Sequencer::getIssueToInitialDelayHist(), Sequencer::getLatencyHist(), Sequencer::getMissLatencyHist(), Sequencer::getMissMachLatencyHist(), Sequencer::getMissTypeLatencyHist(), Sequencer::getMissTypeMachLatencyHist(), Network::getNumberOfVirtualNetworks(), Sequencer::getOutstandReqHist(), AbstractController::getSequencer(), Sequencer::getTypeLatencyHist(), ArmISA::i, ArmISA::j, MipsISA::k, m_address_profiler_ptr, m_all_instructions, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_hitLatencyHist, m_hitMachLatencyHist, m_hitTypeLatencyHist, m_hitTypeMachLatencyHist, m_IncompleteTimes, m_InitialToForwardDelayHist, m_inst_profiler_ptr, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, m_outstandReqHist, and m_typeLatencyHist.
Referenced by RubySystem::collateStats().
AddressProfiler* Profiler::getAddressProfiler () [inline]
Definition at line 76 of file Profiler.hh.
References m_address_profiler_ptr.
bool Profiler::getAllInstructions () [inline]
Definition at line 83 of file Profiler.hh.
References m_all_instructions.
Referenced by printSorted().
bool Profiler::getHotLines () [inline]
Definition at line 82 of file Profiler.hh.
References m_hot_lines.
AddressProfiler* Profiler::getInstructionProfiler () [inline]
Definition at line 77 of file Profiler.hh.
References m_inst_profiler_ptr.
Profiler& Profiler::operator= (const Profiler & obj) [private]
void Profiler::regStats (const std::string & name)
Definition at line 85 of file Profiler.cc.
References csprintf(), delayHistogram, delayVCHistogram, Network::getNumberOfVirtualNetworks(), ArmISA::i, Stats::Histogram::init(), ArmISA::j, m_address_profiler_ptr, m_all_instructions, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_hitLatencyHist, m_hitMachLatencyHist, m_hitTypeLatencyHist, m_hitTypeMachLatencyHist, m_IncompleteTimes, m_InitialToForwardDelayHist, m_inst_profiler_ptr, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, m_outstandReqHist, m_typeLatencyHist, Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, Stats::oneline, Stats::pdf, and AddressProfiler::regStats().
Referenced by RubySystem::regStats().
void Profiler::wakeup ()
Member Data Documentation
Stats::Histogram Profiler::delayHistogram [private]
Definition at line 93 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::delayVCHistogram [private]
Definition at line 94 of file Profiler.hh.
Referenced by collateStats(), and regStats().
AddressProfiler* Profiler::m_address_profiler_ptr [private]
Definition at line 90 of file Profiler.hh.
Referenced by addAddressTraceSample(), collateStats(), getAddressProfiler(), Profiler(), and regStats().
bool Profiler::m_all_instructions [private]
Definition at line 132 of file Profiler.hh.
Referenced by collateStats(), getAllInstructions(), Profiler(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_FirstResponseToCompletionDelayHist [private]
Definition at line 127 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_ForwardToFirstResponseDelayHist [private]
Definition at line 126 of file Profiler.hh.
Referenced by collateStats(), and regStats().
Stats::Histogram Profiler::m_hitLatencyHist [private]
Histogram for holding latency profile of all requests that hit in the controller connected to this sequencer.
Definition at line 105 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_hitMachLatencyHist [private]
Histograms for profiling the latencies for requests that did not required external messages.
Definition at line 110 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_hitTypeLatencyHist [private]
Definition at line 106 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector< std::vector<Stats::Histogram *> > Profiler::m_hitTypeMachLatencyHist [private]
Definition at line 111 of file Profiler.hh.
Referenced by collateStats(), and regStats().
bool Profiler::m_hot_lines [private]
Definition at line 131 of file Profiler.hh.
Referenced by getHotLines(), and Profiler().
Stats::Scalar Profiler::m_IncompleteTimes[MachineType_NUM] [private]
Definition at line 128 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_InitialToForwardDelayHist [private]
Definition at line 125 of file Profiler.hh.
Referenced by collateStats(), and regStats().
AddressProfiler* Profiler::m_inst_profiler_ptr [private]
Definition at line 91 of file Profiler.hh.
Referenced by collateStats(), getInstructionProfiler(), Profiler(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_IssueToInitialDelayHist [private]
Histograms for recording the breakdown of miss latency.
Definition at line 124 of file Profiler.hh.
Referenced by collateStats(), and regStats().
Stats::Histogram Profiler::m_latencyHist [private]
Histogram for holding latency profile of all requests.
Definition at line 100 of file Profiler.hh.
Referenced by collateStats(), and regStats().
Stats::Histogram Profiler::m_missLatencyHist [private]
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
Definition at line 115 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_missMachLatencyHist [private]
Histograms for profiling the latencies for requests that required external messages.
Definition at line 120 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_missTypeLatencyHist [private]
Definition at line 116 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector< std::vector<Stats::Histogram *> > Profiler::m_missTypeMachLatencyHist [private]
Definition at line 121 of file Profiler.hh.
Referenced by collateStats(), and regStats().
Stats::Histogram Profiler::m_outstandReqHist [private]
Histogram for number of outstanding requests per cycle.
Definition at line 97 of file Profiler.hh.
Referenced by collateStats(), and regStats().
std::vector<Stats::Histogram *> Profiler::m_typeLatencyHist [private]
Definition at line 101 of file Profiler.hh.
Referenced by collateStats(), and regStats().
The documentation for this class was generated from the following files:
mem/ruby/profiler/Profiler.hh
mem/ruby/profiler/Profiler.cc