gem5: X86ISA::IntDevice::IntMasterPort Class Reference
X86ISA::IntDevice::IntMasterPort Class Reference
#include <intdev.hh>
Public Member Functions
IntMasterPort (const std::string &_name, MemObject *_parent, IntDevice *dev, Tick _latency)
Tick recvResponse (PacketPtr pkt)
void sendMessage (ApicList apics, TriggerIntMessage message, bool timing)
Private Attributes
IntDevice * device
Tick latency
Detailed Description
Definition at line 90 of file intdev.hh.
Constructor & Destructor Documentation
X86ISA::IntDevice::IntMasterPort::IntMasterPort (const std::string & _name, MemObject * _parent, IntDevice * dev, Tick _latency) [inline]
Definition at line 95 of file intdev.hh.
Member Function Documentation
Tick X86ISA::IntDevice::IntMasterPort::recvResponse (PacketPtr pkt) [inline, virtual]
Reimplemented from MessageMasterPort.
Definition at line 101 of file intdev.hh.
References device, and X86ISA::IntDevice::recvResponse().
Referenced by sendMessage().
void X86ISA::IntDevice::IntMasterPort::sendMessage (ApicList apics, TriggerIntMessage message, bool timing)
Definition at line 46 of file intdev.cc.
References X86ISA::buildIntRequest(), curTick(), Packet::isResponse(), latency, recvResponse(), Packet::req, QueuedMasterPort::schedTimingReq(), and MasterPort::sendAtomic().
Referenced by X86ISA::Interrupts::setReg(), and X86ISA::I82094AA::signalInterrupt().
Member Data Documentation
IntDevice* X86ISA::IntDevice::IntMasterPort::device [private]
Definition at line 92 of file intdev.hh.
Referenced by recvResponse().
Tick X86ISA::IntDevice::IntMasterPort::latency [private]
Definition at line 93 of file intdev.hh.
Referenced by sendMessage().
The documentation for this class was generated from the following files:
dev/x86/intdev.hh
dev/x86/intdev.cc