gem5: RandomRepl Class Reference
RandomRepl Class Reference
#include <random_repl.hh>
Public Types
typedef RandomReplParams Params
Convenience typedef.
Public Member Functions
RandomRepl (const Params *p)
Construct and initiliaze this tag store.
~RandomRepl ()
Destructor.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
CacheBlk * findVictim (Addr addr)
Find an invalid block to evict for the address provided.
void insertBlock (PacketPtr pkt, BlkType *blk)
Insert the new block into the cache.
void invalidate (CacheBlk *blk)
Invalidate the given block.
Detailed Description
Definition at line 45 of file random_repl.hh.
Member Typedef Documentation
typedef RandomReplParams RandomRepl::Params
Convenience typedef.
Reimplemented from BaseSetAssoc.
Definition at line 49 of file random_repl.hh.
Constructor & Destructor Documentation
RandomRepl::RandomRepl (const Params * p)
Construct and initiliaze this tag store.
Definition at line 41 of file random_repl.cc.
RandomRepl::~RandomRepl () [inline]
Destructor.
Definition at line 59 of file random_repl.hh.
Member Function Documentation
CacheBlk * RandomRepl::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Reimplemented from BaseSetAssoc.
Definition at line 48 of file random_repl.cc.
CacheBlk * RandomRepl::findVictim (Addr addr) [virtual]
Find an invalid block to evict for the address provided.
If there are no invalid blocks, this will return the block in the least-recently-used position.
Parameters:
addr The addr to a find a replacement candidate for.
Returns:
The candidate block.
Reimplemented from BaseSetAssoc.
Definition at line 54 of file random_repl.cc.
References BaseSetAssoc::assoc, CacheSet< Blktype >::blks, DPRINTF, BaseSetAssoc::extractSet(), CacheBlk::isValid(), Random::random(), random_mt, BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, BaseSetAssoc::sets, and CacheBlk::tag.
void RandomRepl::insertBlock (PacketPtr pkt, BlkType * blk) [virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Reimplemented from BaseSetAssoc.
Definition at line 74 of file random_repl.cc.
void RandomRepl::invalidate (CacheBlk * blk) [virtual]
Invalidate the given block.
Parameters:
blk The block to invalidate.
Reimplemented from BaseSetAssoc.
Definition at line 80 of file random_repl.cc.
The documentation for this class was generated from the following files:
mem/cache/tags/random_repl.hh
mem/cache/tags/random_repl.cc