gem5: VirtIOConsole::TermTransQueue Class Reference
VirtIOConsole::TermTransQueue Class Reference
Virtqueue for data going from the guest to the host.
#include <console.hh>
Public Member Functions
TermTransQueue (PortProxy &proxy, uint16_t size, VirtIOConsole &_parent)
virtual ~TermTransQueue ()
void onNotifyDescriptor (VirtDescriptor *desc)
Notify queue of pending incoming descriptor.
std::string name () const
Protected Attributes
VirtIOConsole & parent
Detailed Description
Virtqueue for data going from the guest to the host.
Definition at line 131 of file console.hh.
Constructor & Destructor Documentation
VirtIOConsole::TermTransQueue::TermTransQueue (PortProxy & proxy, uint16_t size, VirtIOConsole & _parent) [inline]
Definition at line 135 of file console.hh.
virtual VirtIOConsole::TermTransQueue::~TermTransQueue () [inline, virtual]
Definition at line 137 of file console.hh.
Member Function Documentation
std::string VirtIOConsole::TermTransQueue::name () const [inline]
Definition at line 141 of file console.hh.
References SimObject::name(), and parent.
void VirtIOConsole::TermTransQueue::onNotifyDescriptor (VirtDescriptor * desc) [virtual]
Notify queue of pending incoming descriptor.
This method is called by the default implementation of onNotify() to notify the device model of pending data in a descriptor chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented from VirtQueue.
Definition at line 100 of file console.cc.
References VirtDescriptor::chainRead(), VirtDescriptor::chainSize(), DPRINTF, ArmISA::i, VirtIODeviceBase::kick(), Terminal::out(), parent, VirtQueue::produceDescriptor(), VirtDescriptor::size(), and VirtIOConsole::term.
Member Data Documentation
VirtIOConsole& VirtIOConsole::TermTransQueue::parent [protected]
Definition at line 144 of file console.hh.
Referenced by name(), and onNotifyDescriptor().
The documentation for this class was generated from the following files:
dev/virtio/console.hh
dev/virtio/console.cc