gem5: NoncoherentXBar Class Reference
NoncoherentXBar Class Reference
A non-coherent crossbar connects a number of non-snooping masters and slaves, and routes the request and response packets based on the address.
#include <noncoherent_xbar.hh>
Classes
class NoncoherentXBarMasterPort
Declaration of the crossbar master port type, one will be instantiated for each of the slave ports connecting to the crossbar.
class NoncoherentXBarSlavePort
Declaration of the non-coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
Public Member Functions
NoncoherentXBar (const NoncoherentXBarParams *p)
virtual ~NoncoherentXBar ()
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
virtual void regStats ()
stats
Public Attributes
Stats::Scalar totPktSize
Protected Member Functions
virtual bool recvTimingReq (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Timing request packet.
virtual bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Function called by the port when the crossbar is recieving a Timing response packet.
void recvReqRetry (PortID master_port_id)
Timing function called by port when it is once again able to process requests.
Tick recvAtomic (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Atomic transaction.
void recvFunctional (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Functional transaction.
Protected Attributes
std::vector< ReqLayer * > reqLayers
Declare the layers of this crossbar, one vector for requests and one for responses.
std::vector< RespLayer * > respLayers
Detailed Description
A non-coherent crossbar connects a number of non-snooping masters and slaves, and routes the request and response packets based on the address.
The request packets issued by the master connected to a non-coherent crossbar could still snoop in caches attached to a coherent crossbar, as is the case with the I/O bus and memory bus in most system configurations. No snoops will, however, reach any master on the non-coherent crossbar itself.
The non-coherent crossbar can be used as a template for modelling PCIe, and non-coherent AMBA and OCP buses, and is typically used for the I/O buses.
Definition at line 70 of file noncoherent_xbar.hh.
Constructor & Destructor Documentation
NoncoherentXBar::NoncoherentXBar (const NoncoherentXBarParams * p)
Definition at line 56 of file noncoherent_xbar.cc.
References BaseXBar::clearPortCache(), csprintf(), BaseXBar::defaultPortID, ArmISA::i, BaseXBar::masterPorts, SimObject::name(), reqLayers, respLayers, and BaseXBar::slavePorts.
NoncoherentXBar::~NoncoherentXBar () [virtual]
Definition at line 94 of file noncoherent_xbar.cc.
References MipsISA::l, reqLayers, and respLayers.
Member Function Documentation
unsigned int NoncoherentXBar::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Implements BaseXBar.
Definition at line 306 of file noncoherent_xbar.cc.
References MipsISA::l, reqLayers, respLayers, and Stats::total.
Tick NoncoherentXBar::recvAtomic (PacketPtr pkt, PortID slave_port_id) [protected]
Function called by the port when the crossbar is recieving a Atomic transaction.
Definition at line 251 of file noncoherent_xbar.cc.
References Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), Packet::getAddr(), Packet::getSize(), Packet::hasData(), Packet::isResponse(), BaseXBar::masterPorts, SimObject::name(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, BaseXBar::slavePorts, and BaseXBar::transDist.
Referenced by NoncoherentXBar::NoncoherentXBarSlavePort::recvAtomic().
void NoncoherentXBar::recvFunctional (PacketPtr pkt, PortID slave_port_id) [protected]
Function called by the port when the crossbar is recieving a Functional transaction.
Definition at line 288 of file noncoherent_xbar.cc.
References Packet::cmdString(), DPRINTF, BaseXBar::findPort(), Packet::getAddr(), Packet::isPrint(), BaseXBar::masterPorts, SimObject::name(), and BaseXBar::slavePorts.
Referenced by NoncoherentXBar::NoncoherentXBarSlavePort::recvFunctional().
void NoncoherentXBar::recvReqRetry (PortID master_port_id) [protected]
Timing function called by port when it is once again able to process requests.
Definition at line 242 of file noncoherent_xbar.cc.
References reqLayers.
Referenced by NoncoherentXBar::NoncoherentXBarMasterPort::recvReqRetry().
bool NoncoherentXBar::recvTimingReq (PacketPtr pkt, PortID slave_port_id) [protected, virtual]
Function called by the port when the crossbar is recieving a Timing request packet.
Definition at line 103 of file noncoherent_xbar.cc.
References BaseXBar::calcPacketTiming(), ClockedObject::clockEdge(), ClockedObject::clockPeriod(), Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), BaseXBar::forwardLatency, BaseXBar::frontendLatency, Packet::getAddr(), Packet::getSize(), Packet::hasData(), Packet::headerDelay, Packet::isExpressSnoop(), BaseXBar::masterPorts, Packet::memInhibitAsserted(), Port::name(), Packet::needsResponse(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::req, reqLayers, BaseXBar::routeTo, BaseXBar::slavePorts, and BaseXBar::transDist.
Referenced by NoncoherentXBar::NoncoherentXBarSlavePort::recvTimingReq().
bool NoncoherentXBar::recvTimingResp (PacketPtr pkt, PortID master_port_id) [protected, virtual]
Function called by the port when the crossbar is recieving a Timing response packet.
Definition at line 184 of file noncoherent_xbar.cc.
References BaseXBar::calcPacketTiming(), ClockedObject::clockEdge(), ClockedObject::clockPeriod(), Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::hasData(), InvalidPortID, ArmISA::M5_VAR_USED, BaseXBar::masterPorts, Port::name(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::req, respLayers, BaseXBar::responseLatency, BaseXBar::routeTo, BaseXBar::slavePorts, and BaseXBar::transDist.
Referenced by NoncoherentXBar::NoncoherentXBarMasterPort::recvTimingResp().
void NoncoherentXBar::regStats () [virtual]
stats
Reimplemented from BaseXBar.
Definition at line 324 of file noncoherent_xbar.cc.
References MipsISA::l, reqLayers, and respLayers.
Member Data Documentation
std::vector<ReqLayer*> NoncoherentXBar::reqLayers [protected]
Declare the layers of this crossbar, one vector for requests and one for responses.
Definition at line 79 of file noncoherent_xbar.hh.
Referenced by drain(), NoncoherentXBar(), recvReqRetry(), recvTimingReq(), regStats(), and ~NoncoherentXBar().
std::vector<RespLayer*> NoncoherentXBar::respLayers [protected]
Definition at line 80 of file noncoherent_xbar.hh.
Referenced by drain(), NoncoherentXBar(), recvTimingResp(), regStats(), and ~NoncoherentXBar().
Stats::Scalar NoncoherentXBar::totPktSize
Definition at line 206 of file noncoherent_xbar.hh.
The documentation for this class was generated from the following files:
mem/noncoherent_xbar.hh
mem/noncoherent_xbar.cc