gem5: Cache::MemSidePort Class Reference
Cache::MemSidePort Class Reference
The memory-side port extends the base cache master port with access functions for functional, atomic and timing snoops.
#include <cache.hh>
Public Member Functions
MemSidePort (const std::string &_name, Cache *_cache, const std::string &_label)
Protected Member Functions
virtual void recvTimingSnoopReq (PacketPtr pkt)
virtual bool recvTimingResp (PacketPtr pkt)
virtual Tick recvAtomicSnoop (PacketPtr pkt)
virtual void recvFunctionalSnoop (PacketPtr pkt)
Private Attributes
CacheReqPacketQueue _reqQueue
The cache-specific queue.
SnoopRespPacketQueue _snoopRespQueue
Cache * cache
Detailed Description
The memory-side port extends the base cache master port with access functions for functional, atomic and timing snoops.
Definition at line 150 of file cache.hh.
Constructor & Destructor Documentation
Cache::MemSidePort::MemSidePort (const std::string & _name, Cache * _cache, const std::string & _label)
Definition at line 2291 of file cache_impl.hh.
Member Function Documentation
Tick Cache::MemSidePort::recvAtomicSnoop (PacketPtr pkt) [protected, virtual]
Definition at line 2194 of file cache_impl.hh.
References cache, and Cache::recvAtomicSnoop().
void Cache::MemSidePort::recvFunctionalSnoop (PacketPtr pkt) [protected, virtual]
Definition at line 2200 of file cache_impl.hh.
References cache, and Cache::functionalAccess().
bool Cache::MemSidePort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Definition at line 2179 of file cache_impl.hh.
References cache, and Cache::recvTimingResp().
void Cache::MemSidePort::recvTimingSnoopReq (PacketPtr pkt) [protected, virtual]
Definition at line 2187 of file cache_impl.hh.
References cache, and Cache::recvTimingSnoopReq().
Member Data Documentation
CacheReqPacketQueue Cache::MemSidePort::_reqQueue [private]
The cache-specific queue.
Definition at line 155 of file cache.hh.
SnoopRespPacketQueue Cache::MemSidePort::_snoopRespQueue [private]
Definition at line 157 of file cache.hh.
Cache* Cache::MemSidePort::cache [private]
Definition at line 160 of file cache.hh.
Referenced by recvAtomicSnoop(), recvFunctionalSnoop(), recvTimingResp(), and recvTimingSnoopReq().
The documentation for this class was generated from the following files:
mem/cache/cache.hh
mem/cache/cache_impl.hh