gem5: ArmISA::FpRegImmOp Class Reference
ArmISA::FpRegImmOp Class Reference
#include <vfp.hh>
Protected Member Functions
FpRegImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, uint64_t _imm, VfpMicroMode mode=VfpNotAMicroop)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
uint64_t imm
Detailed Description
Definition at line 929 of file vfp.hh.
Constructor & Destructor Documentation
ArmISA::FpRegImmOp::FpRegImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, uint64_t _imm, VfpMicroMode mode = VfpNotAMicroop) [inline, protected]
Definition at line 935 of file vfp.hh.
References StaticInst::flags, ArmISA::mode, and ArmISA::setVfpMicroFlags().
Member Function Documentation
std::string FpRegImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 91 of file vfp.cc.
References ccprintf(), dest, ArmISA::FP_Reg_Base, imm, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex ArmISA::FpRegImmOp::dest [protected]
Definition at line 932 of file vfp.hh.
Referenced by generateDisassembly().
uint64_t ArmISA::FpRegImmOp::imm [protected]
Definition at line 933 of file vfp.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/vfp.hh
arch/arm/insts/vfp.cc