gem5: GlobalSyncEvent::BarrierEvent Class Reference
GlobalSyncEvent::BarrierEvent Class Reference
#include <global_event.hh>
Public Member Functions
void process ()
BarrierEvent (Base *global_event, Priority p, Flags f)
Detailed Description
Definition at line 212 of file global_event.hh.
Constructor & Destructor Documentation
GlobalSyncEvent::BarrierEvent::BarrierEvent (Base * global_event, Priority p, Flags f) [inline]
Definition at line 216 of file global_event.hh.
Member Function Documentation
void GlobalSyncEvent::BarrierEvent::process () [virtual]
Implements Event.
Definition at line 141 of file global_event.cc.
References BaseGlobalEvent::BarrierEvent::_globalEvent, curEventQueue(), BaseGlobalEvent::BarrierEvent::globalBarrier(), EventQueue::handleAsyncInsertions(), and BaseGlobalEvent::process().
The documentation for this class was generated from the following files:
sim/global_event.hh
sim/global_event.cc