gem5: PolicySelectorPlotter Class Reference
PolicySelectorPlotter Class Reference
#include <psel.hh>
Public Member Functions
PolicySelectorPlotter (std::string name, unsigned int _nbit)
void sample (unsigned int counter, bool final)
void resetStats ()
Private Attributes
Tick prev_sampled
Tick prev_reset
unsigned int prev_counter
double threshold
unsigned int counter_bit
unsigned int counter_max
unsigned int counter_min
std::string plot_filename
std::ostream * psel_out
std::map< Tick, unsigned int > psel_hist
Averager a
Detailed Description
Definition at line 58 of file psel.hh.
Constructor & Destructor Documentation
PolicySelectorPlotter::PolicySelectorPlotter (std::string name, unsigned int _nbit)
Member Function Documentation
void PolicySelectorPlotter::resetStats ()
Definition at line 40 of file psel.cc.
References a, Averager::clear(), OutputDirectory::close(), OutputDirectory::create(), plot_filename, psel_out, OutputDirectory::remove(), and simout.
void PolicySelectorPlotter::sample (unsigned int counter, bool final = false)
Definition at line 27 of file psel.cc.
References a, Averager::add(), Averager::clear(), Averager::getAverage(), Averager::getStart(), psel_out, and threshold.
Referenced by PolicySelector::decrement(), and PolicySelector::increment().
Member Data Documentation
Averager PolicySelectorPlotter::a [private]
Definition at line 73 of file psel.hh.
Referenced by resetStats(), and sample().
unsigned int PolicySelectorPlotter::counter_bit [private]
Definition at line 65 of file psel.hh.
unsigned int PolicySelectorPlotter::counter_max [private]
Definition at line 66 of file psel.hh.
unsigned int PolicySelectorPlotter::counter_min [private]
Definition at line 67 of file psel.hh.
std::string PolicySelectorPlotter::plot_filename [private]
Definition at line 69 of file psel.hh.
Referenced by resetStats().
unsigned int PolicySelectorPlotter::prev_counter [private]
Definition at line 62 of file psel.hh.
Tick PolicySelectorPlotter::prev_reset [private]
Definition at line 61 of file psel.hh.
Tick PolicySelectorPlotter::prev_sampled [private]
Definition at line 60 of file psel.hh.
std::map<Tick, unsigned int> PolicySelectorPlotter::psel_hist [private]
Definition at line 71 of file psel.hh.
std::ostream* PolicySelectorPlotter::psel_out [private]
Definition at line 70 of file psel.hh.
Referenced by resetStats(), and sample().
double PolicySelectorPlotter::threshold [private]
Definition at line 63 of file psel.hh.
Referenced by sample().
The documentation for this class was generated from the following files:
mem/cache/tags/psel.hh
mem/cache/tags/psel.cc