gem5: Checker< Impl > Class Template Reference
Checker< Impl > Class Template Reference
Templated Checker class.
#include <cpu.hh>
Public Member Functions
Checker (Params *p)
void switchOut ()
void takeOverFrom (BaseCPU *oldCPU)
void advancePC (const Fault &fault)
void verify (DynInstPtr &inst)
void validateInst (DynInstPtr &inst)
void validateExecution (DynInstPtr &inst)
void validateState ()
void copyResult (DynInstPtr &inst, uint64_t mismatch_val, int start_idx)
void handlePendingInt ()
Private Types
typedef Impl::DynInstPtr DynInstPtr
typedef std::list< DynInstPtr >
::iterator InstListIt
Private Member Functions
void handleError (DynInstPtr &inst)
void dumpAndExit (DynInstPtr &inst)
void dumpInsts ()
Private Attributes
bool updateThisCycle
DynInstPtr unverifiedInst
std::list< DynInstPtr > instList
Detailed Description
template<class Impl>
class Checker< Impl >
Templated Checker class.
This Checker class is templated on the DynInstPtr of the instruction type that will be verified. Proper template instantiations of the Checker must be placed at the bottom of checker/cpu.cc.
Definition at line 423 of file cpu.hh.
Member Typedef Documentation
template<class Impl> typedef Impl::DynInstPtr Checker< Impl >::DynInstPtr [private]
Definition at line 426 of file cpu.hh.
template<class Impl> typedef std::list<DynInstPtr>::iterator Checker< Impl >::InstListIt [private]
Definition at line 464 of file cpu.hh.
Constructor & Destructor Documentation
template<class Impl> Checker< Impl >::Checker (Params * p) [inline]
Definition at line 429 of file cpu.hh.
Member Function Documentation
template<class Impl > void Checker< Impl >::advancePC (const Fault & fault) [inline]
Definition at line 72 of file cpu_impl.hh.
References CheckerCPU::curMacroStaticInst, CheckerCPU::curStaticInst, SimpleThread::decoder, DPRINTF, StaticInst::nullStaticInstPtr, SimpleThread::pcState(), CheckerCPU::pcState(), CheckerCPU::tc, and CheckerCPU::thread.
Referenced by Checker< Impl >::validateState(), and Checker< Impl >::verify().
template<class Impl > void Checker< Impl >::copyResult (DynInstPtr & inst, uint64_t mismatch_val, int start_idx) [inline]
Definition at line 593 of file cpu_impl.hh.
References AlphaISA::CC_Reg_Base, CCRegClass, FloatRegClass, AlphaISA::FP_Reg_Base, ArmISA::i, IntRegClass, AlphaISA::Misc_Reg_Base, MiscRegClass, regIdxToClass(), SimpleThread::setCCReg(), SimpleThread::setFloatRegBits(), SimpleThread::setIntReg(), SimpleThread::setMiscReg(), and CheckerCPU::thread.
Referenced by Checker< Impl >::validateExecution().
template<class Impl > void Checker< Impl >::dumpAndExit (DynInstPtr & inst) [inline, private]
Definition at line 642 of file cpu_impl.hh.
References cprintf(), and CheckerCPU::dumpAndExit().
template<class Impl > void Checker< Impl >::dumpInsts () [inline, private]
Definition at line 658 of file cpu_impl.hh.
References cprintf(), and Checker< Impl >::instList.
template<class Impl> void Checker< Impl >::handleError (DynInstPtr & inst) [inline, private]
Definition at line 448 of file cpu.hh.
template<class Impl > void Checker< Impl >::handlePendingInt () [inline]
Definition at line 93 of file cpu_impl.hh.
References CheckerCPU::curMacroStaticInst, CheckerCPU::curStaticInst, curTick(), SimpleThread::decoder, DPRINTF, Checker< Impl >::instList, StaticInst::nullStaticInstPtr, panic, SimpleThread::pcState(), CheckerCPU::thread, and Checker< Impl >::verify().
template<class Impl > void Checker< Impl >::switchOut () [inline]
Definition at line 449 of file cpu_impl.hh.
References Checker< Impl >::instList.
template<class Impl > void Checker< Impl >::takeOverFrom (BaseCPU * oldCPU) [inline]
Definition at line 456 of file cpu_impl.hh.
template<class Impl > void Checker< Impl >::validateExecution (DynInstPtr & inst) [inline]
Definition at line 483 of file cpu_impl.hh.
References Checker< Impl >::copyResult(), curTick(), DPRINTF, CheckerCPU::handleError(), ArmISA::i, CheckerCPU::miscRegIdxs, SimpleThread::nextInstAddr(), SimpleThread::readMiscRegNoEffect(), CheckerCPU::result, CheckerCPU::thread, warn, and CheckerCPU::warnOnlyOnLoadError.
Referenced by Checker< Impl >::verify().
template<class Impl > void Checker< Impl >::validateInst (DynInstPtr & inst) [inline]
Definition at line 462 of file cpu_impl.hh.
References CheckerCPU::changedPC, CheckerCPU::curStaticInst, curTick(), CheckerCPU::handleError(), SimpleThread::instAddr(), SimpleThread::pcState(), CheckerCPU::thread, and warn.
Referenced by Checker< Impl >::verify().
template<class Impl > void Checker< Impl >::validateState () [inline]
Definition at line 568 of file cpu_impl.hh.
References Checker< Impl >::advancePC(), SimpleThread::copyArchRegs(), CheckerCPU::curStaticInst, curTick(), panic, CheckerCPU::thread, Checker< Impl >::unverifiedInst, and Checker< Impl >::updateThisCycle.
Referenced by Checker< Impl >::verify().
template<class Impl > void Checker< Impl >::verify (DynInstPtr & inst) [inline]
Definition at line 127 of file cpu_impl.hh.
References Checker< Impl >::advancePC(), CheckerCPU::changedPC, ThreadState::contextId(), X86ISA::count, CheckerCPU::curMacroStaticInst, CheckerCPU::curStaticInst, curTick(), Packet::dataStatic(), SimpleThread::decoder, DPRINTF, Trace::InstRecord::dump(), BaseTLB::Execute, FullSystem, ThreadState::funcExeInst, BigEndianGuest::gtoh(), CheckerCPU::handleError(), CheckerCPU::icachePort, Request::INST_FETCH, SimpleThread::instAddr(), Checker< Impl >::instList, isRomMicroPC(), CheckerCPU::itb, CheckerCPU::masterId, CheckerCPU::memReq, CheckerCPU::newPCState, StaticInst::nullStaticInstPtr, CheckerCPU::numInst, CheckerCPU::numLoad, panic, CheckerCPU::pcState(), SimpleThread::pcState(), MemCmd::ReadReq, CheckerCPU::result, MasterPort::sendFunctional(), SimpleThread::setFloatReg(), SimpleThread::setIntReg(), Request::setVirt(), X86ISA::system, CheckerCPU::tc, CheckerCPU::thread, Checker< Impl >::unverifiedInst, CheckerCPU::unverifiedMemData, CheckerCPU::unverifiedReq, Checker< Impl >::validateExecution(), Checker< Impl >::validateInst(), Checker< Impl >::validateState(), warn, CheckerCPU::willChangePC, CheckerCPU::youngestSN, and AlphaISA::ZeroReg.
Referenced by Checker< Impl >::handlePendingInt().
Member Data Documentation
template<class Impl> std::list<DynInstPtr> Checker< Impl >::instList [private]
Definition at line 463 of file cpu.hh.
Referenced by Checker< Impl >::dumpInsts(), Checker< Impl >::handlePendingInt(), Checker< Impl >::switchOut(), and Checker< Impl >::verify().
template<class Impl> DynInstPtr Checker< Impl >::unverifiedInst [private]
Definition at line 461 of file cpu.hh.
Referenced by Checker< Impl >::validateState(), and Checker< Impl >::verify().
template<class Impl> bool Checker< Impl >::updateThisCycle [private]
Definition at line 459 of file cpu.hh.
Referenced by Checker< O3CPUImpl >::handleError(), and Checker< Impl >::validateState().
The documentation for this class was generated from the following files:
cpu/checker/cpu.hh
cpu/checker/cpu_impl.hh