gem5: ArmISA::DataXCondCompRegOp Class Reference
ArmISA::DataXCondCompRegOp Class Reference
#include <data64.hh>
Protected Member Functions
DataXCondCompRegOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _op1, IntRegIndex _op2, ConditionCode _condCode, uint8_t _defCc)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex op1
IntRegIndex op2
ConditionCode condCode
uint8_t defCc
Detailed Description
Definition at line 221 of file data64.hh.
Constructor & Destructor Documentation
ArmISA::DataXCondCompRegOp::DataXCondCompRegOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _op1, IntRegIndex _op2, ConditionCode _condCode, uint8_t _defCc) [inline, protected]
Definition at line 228 of file data64.hh.
Member Function Documentation
std::string ArmISA::DataXCondCompRegOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 173 of file data64.cc.
References ccprintf(), condCode, defCc, op1, op2, ArmISA::ArmStaticInst::printCondition(), ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
ConditionCode ArmISA::DataXCondCompRegOp::condCode [protected]
Definition at line 225 of file data64.hh.
Referenced by generateDisassembly().
uint8_t ArmISA::DataXCondCompRegOp::defCc [protected]
Definition at line 226 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataXCondCompRegOp::op1 [protected]
Definition at line 224 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataXCondCompRegOp::op2 [protected]
Definition at line 224 of file data64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/data64.hh
arch/arm/insts/data64.cc