gem5: CoherentXBar::CoherentXBarSlavePort Class Reference
CoherentXBar::CoherentXBarSlavePort Class Reference
Declaration of the coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
#include <coherent_xbar.hh>
Public Member Functions
CoherentXBarSlavePort (const std::string &_name, CoherentXBar &_xbar, PortID _id)
Protected Member Functions
virtual bool recvTimingReq (PacketPtr pkt)
When receiving a timing request, pass it to the crossbar.
virtual bool recvTimingSnoopResp (PacketPtr pkt)
When receiving a timing snoop response, pass it to the crossbar.
virtual Tick recvAtomic (PacketPtr pkt)
When receiving an atomic request, pass it to the crossbar.
virtual void recvFunctional (PacketPtr pkt)
When receiving a functional request, pass it to the crossbar.
virtual void recvRespRetry ()
When receiving a retry, pass it to the crossbar.
virtual AddrRangeList getAddrRanges () const
Return the union of all adress ranges seen by this crossbar.
Private Attributes
CoherentXBar & xbar
A reference to the crossbar to which this port belongs.
Detailed Description
Declaration of the coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
Definition at line 87 of file coherent_xbar.hh.
Constructor & Destructor Documentation
CoherentXBar::CoherentXBarSlavePort::CoherentXBarSlavePort (const std::string & _name, CoherentXBar & _xbar, PortID _id) [inline]
Definition at line 97 of file coherent_xbar.hh.
Member Function Documentation
virtual AddrRangeList CoherentXBar::CoherentXBarSlavePort::getAddrRanges () const [inline, protected, virtual]
Return the union of all adress ranges seen by this crossbar.
Implements SlavePort.
Definition at line 137 of file coherent_xbar.hh.
References BaseXBar::getAddrRanges(), and xbar.
virtual Tick CoherentXBar::CoherentXBarSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
When receiving an atomic request, pass it to the crossbar.
Implements SlavePort.
Definition at line 119 of file coherent_xbar.hh.
References CoherentXBar::recvAtomic(), and xbar.
virtual void CoherentXBar::CoherentXBarSlavePort::recvFunctional (PacketPtr pkt) [inline, protected, virtual]
When receiving a functional request, pass it to the crossbar.
Implements SlavePort.
Definition at line 125 of file coherent_xbar.hh.
References CoherentXBar::recvFunctional(), and xbar.
virtual void CoherentXBar::CoherentXBarSlavePort::recvRespRetry () [inline, protected, virtual]
When receiving a retry, pass it to the crossbar.
Implements SlavePort.
Definition at line 131 of file coherent_xbar.hh.
References panic.
virtual bool CoherentXBar::CoherentXBarSlavePort::recvTimingReq (PacketPtr pkt) [inline, protected, virtual]
When receiving a timing request, pass it to the crossbar.
Implements SlavePort.
Definition at line 107 of file coherent_xbar.hh.
References CoherentXBar::recvTimingReq(), and xbar.
virtual bool CoherentXBar::CoherentXBarSlavePort::recvTimingSnoopResp (PacketPtr pkt) [inline, protected, virtual]
When receiving a timing snoop response, pass it to the crossbar.
Reimplemented from SlavePort.
Definition at line 113 of file coherent_xbar.hh.
References CoherentXBar::recvTimingSnoopResp(), and xbar.
Member Data Documentation
CoherentXBar& CoherentXBar::CoherentXBarSlavePort::xbar [private]
A reference to the crossbar to which this port belongs.
Definition at line 93 of file coherent_xbar.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvTimingReq(), and recvTimingSnoopResp().
The documentation for this class was generated from the following file:
mem/coherent_xbar.hh