gem5: SkipFuncEvent Class Reference
SkipFuncEvent Class Reference
#include <system_events.hh>
Public Member Functions
SkipFuncEvent (PCEventQueue *q, const std::string &desc, Addr addr)
virtual void process (ThreadContext *tc)
Detailed Description
Definition at line 38 of file system_events.hh.
Constructor & Destructor Documentation
SkipFuncEvent::SkipFuncEvent (PCEventQueue * q, const std::string & desc, Addr addr) [inline]
Definition at line 41 of file system_events.hh.
Member Function Documentation
void SkipFuncEvent::process (ThreadContext * tc) [virtual]
Implements PCEvent.
Reimplemented in FreebsdAlphaSystem::SkipCalibrateClocksEvent, LinuxAlphaSystem::SkipDelayLoopEvent, LinuxMipsSystem::SkipDelayLoopEvent, FreeBSD::UDelayEvent, Linux::DebugPrintkEvent, Linux::UDelayEvent, and BadAddrEvent.
Definition at line 43 of file system_events.cc.
References PCEvent::description, DPRINTF, ArmISA::M5_VAR_USED, ThreadContext::pcState(), and AlphaISA::skipFunction().
Referenced by Linux::UDelayEvent::process(), Linux::DebugPrintkEvent::process(), and FreeBSD::UDelayEvent::process().
The documentation for this class was generated from the following files:
kern/system_events.hh
kern/system_events.cc