gem5: ArmISA::MemoryLiteral64 Class Reference
ArmISA::MemoryLiteral64 Class Reference
#include <mem64.hh>
Protected Member Functions
MemoryLiteral64 (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, int64_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
int64_t imm
Detailed Description
Definition at line 239 of file mem64.hh.
Constructor & Destructor Documentation
ArmISA::MemoryLiteral64::MemoryLiteral64 (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, int64_t _imm) [inline, protected]
Definition at line 244 of file mem64.hh.
Member Function Documentation
std::string ArmISA::MemoryLiteral64::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 185 of file mem64.cc.
References ccprintf(), ArmISA::Memory64::dest, imm, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
int64_t ArmISA::MemoryLiteral64::imm [protected]
Definition at line 242 of file mem64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/mem64.hh
arch/arm/insts/mem64.cc