gem5: DerivedClockDomain Class Reference
DerivedClockDomain Class Reference
The derived clock domains provides the notion of a clock domain that is connected to a parent clock domain that can either be a source clock domain or a derived clock domain.
#include <clock_domain.hh>
Public Types
typedef DerivedClockDomainParams Params
Public Member Functions
DerivedClockDomain (const Params *p)
void updateClockPeriod ()
Called by the parent clock domain to propagate changes.
Private Attributes
ClockDomain & parent
Reference to the parent clock domain this clock domain derives its clock period from.
const uint64_t clockDivider
Local clock divider of the domain.
Detailed Description
The derived clock domains provides the notion of a clock domain that is connected to a parent clock domain that can either be a source clock domain or a derived clock domain.
It maintains the clock divider and provides methods for getting the clock.
Definition at line 274 of file clock_domain.hh.
Member Typedef Documentation
typedef DerivedClockDomainParams DerivedClockDomain::Params
Reimplemented from ClockDomain.
Definition at line 279 of file clock_domain.hh.
Constructor & Destructor Documentation
DerivedClockDomain::DerivedClockDomain (const Params * p)
Definition at line 186 of file clock_domain.cc.
References ClockDomain::addDerivedDomain(), clockDivider, fatal, parent, and updateClockPeriod().
Member Function Documentation
void DerivedClockDomain::updateClockPeriod ()
Called by the parent clock domain to propagate changes.
This also involves propagating the change further to any children of the derived domain itself.
Definition at line 206 of file clock_domain.cc.
References ClockDomain::_clockPeriod, ArmISA::c, ClockDomain::children, clockDivider, ClockDomain::clockPeriod(), DPRINTF, ArmISA::m, ClockDomain::members, SimObject::name(), and parent.
Referenced by DerivedClockDomain().
Member Data Documentation
const uint64_t DerivedClockDomain::clockDivider [private]
Local clock divider of the domain.
Definition at line 300 of file clock_domain.hh.
Referenced by DerivedClockDomain(), and updateClockPeriod().
ClockDomain& DerivedClockDomain::parent [private]
Reference to the parent clock domain this clock domain derives its clock period from.
Definition at line 295 of file clock_domain.hh.
Referenced by DerivedClockDomain(), and updateClockPeriod().
The documentation for this class was generated from the following files:
sim/clock_domain.hh
sim/clock_domain.cc