gem5: SyscallDesc Class Reference
SyscallDesc Class Reference
System call descriptor.
#include <syscall_emul.hh>
Public Types
enum Flags { SuppressReturnValue = 1, WarnOnce = 2 }
Flag values for controlling syscall behavior.
typedef SyscallReturn(* FuncPtr)(SyscallDesc *, int num, LiveProcess *, ThreadContext *)
Typedef for target syscall handler functions.
Public Member Functions
SyscallDesc (const char *_name, FuncPtr _funcPtr, int _flags=0)
Constructor.
void doSyscall (int callnum, LiveProcess *proc, ThreadContext *tc)
Emulate the syscall. Public interface for calling through funcPtr.
bool warnOnce () const
Is the WarnOnce flag set?
Public Attributes
const char * name
Syscall name (e.g., "open").
FuncPtr funcPtr
Pointer to emulation function.
int flags
Flags (see Flags enum).
bool warned
Have we warned about unimplemented syscall?
Detailed Description
System call descriptor.
Definition at line 89 of file syscall_emul.hh.
Member Typedef Documentation
typedef SyscallReturn(* SyscallDesc::FuncPtr)(SyscallDesc *, int num, LiveProcess *, ThreadContext *)
Typedef for target syscall handler functions.
Definition at line 94 of file syscall_emul.hh.
Member Enumeration Documentation
enum SyscallDesc::Flags
Flag values for controlling syscall behavior.
Enumerator:
SuppressReturnValue
Don't set return regs according to funcPtr return value.
Used for syscalls with non-standard return conventions that explicitly set the ThreadContext regs (e.g., sigreturn).
WarnOnce
Definition at line 103 of file syscall_emul.hh.
Constructor & Destructor Documentation
SyscallDesc::SyscallDesc (const char * _name, FuncPtr _funcPtr, int _flags = 0) [inline]
Constructor.
Definition at line 113 of file syscall_emul.hh.
Member Function Documentation
void SyscallDesc::doSyscall (int callnum, LiveProcess * proc, ThreadContext * tc)
Emulate the syscall. Public interface for calling through funcPtr.
Definition at line 56 of file syscall_emul.cc.
References curTick(), DPRINTFNR, DPRINTFS, DTRACE, SyscallReturn::encodedValue(), flags, ThreadContext::getCpuPtr(), LiveProcess::getSyscallArg(), ArmISA::i, MipsISA::index, ArmISA::M5_VAR_USED, name, SyscallReturn::needsRetry(), and SuppressReturnValue.
Referenced by Tru64::indirectSyscallFunc(), and LiveProcess::syscall().
bool SyscallDesc::warnOnce () const [inline]
Is the WarnOnce flag set?
Definition at line 122 of file syscall_emul.hh.
References flags, and WarnOnce.
Referenced by ignoreFunc().
Member Data Documentation
int SyscallDesc::flags
Flags (see Flags enum).
Definition at line 99 of file syscall_emul.hh.
Referenced by doSyscall(), and warnOnce().
FuncPtr SyscallDesc::funcPtr
Pointer to emulation function.
Definition at line 98 of file syscall_emul.hh.
const char* SyscallDesc::name
Syscall name (e.g., "open").
Definition at line 97 of file syscall_emul.hh.
Referenced by doSyscall(), ignoreFunc(), setThreadArea32Func(), and unimplementedFunc().
bool SyscallDesc::warned
Have we warned about unimplemented syscall?
Definition at line 100 of file syscall_emul.hh.
Referenced by ignoreFunc().
The documentation for this class was generated from the following files:
sim/syscall_emul.hh
sim/syscall_emul.cc