gem5: ArmISA::Stage2MMU Class Reference
ArmISA::Stage2MMU Class Reference
#include <stage2_mmu.hh>
Classes
class Stage2Translation
This translation class is used to trigger the data fetch once a timing translation returns the translated physical address.
Public Types
typedef ArmStage2MMUParams Params
Public Member Functions
Stage2MMU (const Params *p)
DmaPort & getPort ()
Get the port that ultimately belongs to the stage-two MMU, but is used by the two table walkers, and is exposed externally and connected through the stage-one table walker.
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Fault readDataUntimed (ThreadContext *tc, Addr oVAddr, Addr descAddr, uint8_t *data, int numBytes, Request::Flags flags, bool isFunctional)
Fault readDataTimed (ThreadContext *tc, Addr descAddr, Stage2Translation *translation, int numBytes, Request::Flags flags)
TLB * stage1Tlb () const
TLB * stage2Tlb () const
Protected Attributes
DmaPort port
Port to issue translation requests from.
MasterID masterId
Request id for requests generated by this MMU.
Private Attributes
TLB * _stage1Tlb
TLB * _stage2Tlb
The TLB that will cache the stage 2 look ups.
Detailed Description
Definition at line 52 of file stage2_mmu.hh.
Member Typedef Documentation
typedef ArmStage2MMUParams ArmISA::Stage2MMU::Params
Reimplemented from SimObject.
Definition at line 105 of file stage2_mmu.hh.
Constructor & Destructor Documentation
Stage2MMU::Stage2MMU (const Params * p)
Definition at line 51 of file stage2_mmu.cc.
References masterId, ArmISA::TLB::setMMU(), stage1Tlb(), and stage2Tlb().
Member Function Documentation
unsigned int Stage2MMU::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 145 of file stage2_mmu.cc.
References DmaPort::drain(), and port.
DmaPort& ArmISA::Stage2MMU::getPort () [inline]
Get the port that ultimately belongs to the stage-two MMU, but is used by the two table walkers, and is exposed externally and connected through the stage-one table walker.
Definition at line 113 of file stage2_mmu.hh.
References port.
Referenced by ArmISA::Stage2MMU::Stage2Translation::finish(), ArmISA::TLB::getMasterPort(), and ArmISA::TableWalker::setMMU().
Fault Stage2MMU::readDataTimed (ThreadContext * tc, Addr descAddr, Stage2Translation * translation, int numBytes, Request::Flags flags)
Definition at line 101 of file stage2_mmu.cc.
References masterId, Request::PT_WALK, ArmISA::Stage2MMU::Stage2Translation::setVirt(), and ArmISA::Stage2MMU::Stage2Translation::translateTiming().
Referenced by ArmISA::TableWalker::fetchDescriptor().
Fault Stage2MMU::readDataUntimed (ThreadContext * tc, Addr oVAddr, Addr descAddr, uint8_t * data, int numBytes, Request::Flags flags, bool isFunctional)
Definition at line 64 of file stage2_mmu.cc.
References ArmISA::ArmFault::annotate(), Packet::dataStatic(), Request::getFlags(), Packet::isError(), Flags< T >::isSet(), masterId, Request::NO_ACCESS, ArmISA::ArmFault::OVA, port, Request::PT_WALK, BaseTLB::Read, MemCmd::ReadReq, ArmISA::ArmFault::S1PTW, MasterPort::sendAtomic(), MasterPort::sendFunctional(), Request::setVirt(), stage2Tlb(), ArmISA::TLB::translateAtomic(), and ArmISA::TLB::translateFunctional().
Referenced by ArmISA::TableWalker::fetchDescriptor().
TLB* ArmISA::Stage2MMU::stage1Tlb () const [inline]
Definition at line 123 of file stage2_mmu.hh.
References _stage1Tlb.
Referenced by Stage2MMU().
TLB* ArmISA::Stage2MMU::stage2Tlb () const [inline]
Definition at line 124 of file stage2_mmu.hh.
References _stage2Tlb.
Referenced by ArmISA::TLB::init(), readDataUntimed(), Stage2MMU(), and ArmISA::Stage2MMU::Stage2Translation::translateTiming().
Member Data Documentation
TLB* ArmISA::Stage2MMU::_stage1Tlb [private]
Definition at line 55 of file stage2_mmu.hh.
Referenced by stage1Tlb().
TLB* ArmISA::Stage2MMU::_stage2Tlb [private]
The TLB that will cache the stage 2 look ups.
Definition at line 57 of file stage2_mmu.hh.
Referenced by stage2Tlb().
MasterID ArmISA::Stage2MMU::masterId [protected]
Request id for requests generated by this MMU.
Definition at line 65 of file stage2_mmu.hh.
Referenced by readDataTimed(), readDataUntimed(), and Stage2MMU().
DmaPort ArmISA::Stage2MMU::port [protected]
Port to issue translation requests from.
Definition at line 62 of file stage2_mmu.hh.
Referenced by drain(), getPort(), and readDataUntimed().
The documentation for this class was generated from the following files:
arch/arm/stage2_mmu.hh
arch/arm/stage2_mmu.cc