gem5: Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits > Class Template Reference
Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits > Class Template Reference
Like a Queue but with a restricted interface and a setTail function which, when the queue is empty, just takes a reference to the pushed item as the single element.
#include <buffers.hh>
Public Member Functions
InputBuffer (const std::string &name, const std::string &data_name, unsigned int capacity_)
void setTail (ElemType &new_element)
Set the tail of the queue, this is like push but needs to be followed by pushTail for the new tail to make its way into the queue proper.
bool empty () const
No single element or queue entries.
const ElemType & front () const
Return the element, or the front of the queue.
ElemType & front ()
void pop ()
Pop either the head, or if none, the head of the queue.
void pushTail () const
Push the single element (if any) into the queue proper.
void minorTrace () const
Report elements.
bool canReserve () const
Reservable interface, passed on to queue.
void reserve ()
Reserve a slot in whatever structure this is attached to.
void freeReservation ()
Free a reserved slot.
unsigned int unreservedRemainingSpace ()
Like remainingSpace but does not count reserved spaces.
Protected Attributes
Queue< ElemType, ReportTraits,
BubbleTraits > queue
Underlying queue.
ElemType * elementPtr
Pointer to the single element (if not NULL).
Detailed Description
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>>
class Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >
Like a Queue but with a restricted interface and a setTail function which, when the queue is empty, just takes a reference to the pushed item as the single element.
Calling pushTail will push that element onto the queue.
The purpose of this class is to allow the faster operation of queues of items which usually don't get deeper than one item and for which the copy associated with a push is expensive enough to want to avoid
The intended use case is the input buffer for pipeline stages, hence the class name
Definition at line 562 of file buffers.hh.
Constructor & Destructor Documentation
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::InputBuffer (const std::string & name, const std::string & data_name, unsigned int capacity_) [inline]
Definition at line 572 of file buffers.hh.
Member Function Documentation
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::canReserve () const [inline, virtual]
Reservable interface, passed on to queue.
Implements Minor::Reservable.
Definition at line 638 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty () const [inline]
No single element or queue entries.
Definition at line 595 of file buffers.hh.
Referenced by Minor::Fetch2::dumpAllInput(), Minor::Fetch2::getInput(), Minor::Execute::getInput(), Minor::Decode::getInput(), Minor::Fetch2::isDrained(), Minor::Execute::isDrained(), Minor::Decode::isDrained(), Minor::Fetch2::popInput(), Minor::Execute::popInput(), and Minor::Decode::popInput().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::freeReservation () [inline, virtual]
Free a reserved slot.
Implements Minor::Reservable.
Definition at line 640 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> ElemType& Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::front () [inline]
Definition at line 601 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> const ElemType& Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::front () const [inline]
Return the element, or the front of the queue.
Definition at line 598 of file buffers.hh.
Referenced by Minor::Fetch2::getInput(), Minor::Execute::getInput(), Minor::Decode::getInput(), and Minor::Fetch2::popInput().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::minorTrace () const [inline]
Report elements.
Definition at line 631 of file buffers.hh.
Referenced by Minor::Fetch2::minorTrace(), Minor::Execute::minorTrace(), and Minor::Decode::minorTrace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::pop () [inline]
Pop either the head, or if none, the head of the queue.
Definition at line 606 of file buffers.hh.
Referenced by Minor::Fetch2::popInput(), Minor::Execute::popInput(), and Minor::Decode::popInput().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::pushTail () const [inline]
Push the single element (if any) into the queue proper.
If the element's reference points to a transient object, remember to always do this before the end of that object's life
Definition at line 622 of file buffers.hh.
Referenced by Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), Minor::Decode::evaluate(), Minor::InputBuffer< ForwardInstData >::minorTrace(), and Minor::InputBuffer< ForwardInstData >::unreservedRemainingSpace().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::reserve () [inline, virtual]
Reserve a slot in whatever structure this is attached to.
Implements Minor::Reservable.
Definition at line 639 of file buffers.hh.
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::setTail (ElemType & new_element) [inline]
Set the tail of the queue, this is like push but needs to be followed by pushTail for the new tail to make its way into the queue proper.
Definition at line 583 of file buffers.hh.
Referenced by Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), and Minor::Decode::evaluate().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::unreservedRemainingSpace () [inline]
Like remainingSpace but does not count reserved spaces.
Definition at line 644 of file buffers.hh.
Member Data Documentation
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> ElemType* Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::elementPtr [mutable, protected]
Pointer to the single element (if not NULL).
Definition at line 569 of file buffers.hh.
Referenced by Minor::InputBuffer< ForwardInstData >::empty(), Minor::InputBuffer< ForwardInstData >::front(), Minor::InputBuffer< ForwardInstData >::pop(), Minor::InputBuffer< ForwardInstData >::pushTail(), and Minor::InputBuffer< ForwardInstData >::setTail().
template<typename ElemType, typename ReportTraits = ReportTraitsAdaptor<ElemType>, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> Queue<ElemType, ReportTraits, BubbleTraits> Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::queue [mutable, protected]
Underlying queue.
Definition at line 566 of file buffers.hh.
Referenced by Minor::InputBuffer< ForwardInstData >::canReserve(), Minor::InputBuffer< ForwardInstData >::empty(), Minor::InputBuffer< ForwardInstData >::freeReservation(), Minor::InputBuffer< ForwardInstData >::front(), Minor::InputBuffer< ForwardInstData >::minorTrace(), Minor::InputBuffer< ForwardInstData >::pop(), Minor::InputBuffer< ForwardInstData >::pushTail(), Minor::InputBuffer< ForwardInstData >::reserve(), Minor::InputBuffer< ForwardInstData >::setTail(), and Minor::InputBuffer< ForwardInstData >::unreservedRemainingSpace().
The documentation for this class was generated from the following file:
cpu/minor/buffers.hh