gem5: AlphaSystem Class Reference
AlphaSystem Class Reference
#include <system.hh>
Public Types
typedef AlphaSystemParams Params
Public Member Functions
AlphaSystem (Params *p)
~AlphaSystem ()
virtual void initState ()
Initialise the state of the system.
virtual void serializeSymtab (std::ostream &os)
Serialization stuff.
virtual void unserializeSymtab (Checkpoint *cp, const std::string &section)
If needed, unserialize additional symbol table entries for a specific subclass of this system.
virtual void startup ()
Override startup() to provide a path to call setupFuncEvents().
void setAlphaAccess (Addr access)
Set the m5AlphaAccess pointer in the console.
void setIntrFreq (Tick freq)
Public Attributes
SymbolTable * consoleSymtab
console symbol table
SymbolTable * palSymtab
pal symbol table
ObjectFile * console
Object pointer for the console code.
ObjectFile * pal
Object pointer for the PAL code.
BreakPCEvent * consolePanicEvent
Event to halt the simulator if the console calls panic().
Protected Member Functions
const Params * params () const
virtual void setupFuncEvents ()
Setup all the function events.
template<class T >
T * addPalFuncEvent (const char *lbl)
Add a function-based event to PALcode.
template<class T >
T * addConsoleFuncEvent (const char *lbl)
Add a function-based event to the console code.
virtual Addr fixFuncEventAddr (Addr addr)
This function fixes up addresses that are used to match PCs for hooking simulator events on to target function executions.
Protected Attributes
Tick intrFreq
FSTranslatingPortProxy virtProxy
Proxy used to copy arguments directly into kernel memory.
Detailed Description
Definition at line 46 of file system.hh.
Member Typedef Documentation
typedef AlphaSystemParams AlphaSystem::Params
Reimplemented from System.
Reimplemented in FreebsdAlphaSystem, LinuxAlphaSystem, and Tru64AlphaSystem.
Definition at line 49 of file system.hh.
Constructor & Destructor Documentation
AlphaSystem::AlphaSystem (Params * p)
Load the pal, and console code into memory
Definition at line 47 of file system.cc.
References console, consoleSymtab, createObjectFile(), debugSymbolTable, fatal, ObjectFile::loadGlobalSymbols(), ObjectFile::loadLocalSymbols(), pal, palSymtab, panic, and params().
AlphaSystem::~AlphaSystem ()
Definition at line 89 of file system.cc.
References console, consolePanicEvent, consoleSymtab, and pal.
Member Function Documentation
template<class T > T* AlphaSystem::addConsoleFuncEvent (const char * lbl) [inline, protected]
Add a function-based event to the console code.
Definition at line 119 of file system.hh.
References consoleSymtab.
template<class T > T* AlphaSystem::addPalFuncEvent (const char * lbl) [inline, protected]
Add a function-based event to PALcode.
Definition at line 111 of file system.hh.
References palSymtab.
Addr AlphaSystem::fixFuncEventAddr (Addr addr) [protected, virtual]
This function fixes up addresses that are used to match PCs for hooking simulator events on to target function executions.
Alpha binaries may have multiple global offset table (GOT) sections. A function that uses the GOT starts with a two-instruction prolog which sets the global pointer (gp == r29) to the appropriate GOT section. The proper gp value is calculated based on the function address, which must be passed by the caller in the procedure value register (pv aka t12 == r27). This sequence looks like the following:
opcode Ra Rb offset ldah gp,X(pv) 09 29 27 X lda gp,Y(gp) 08 29 29 Y
for some constant offsets X and Y. The catch is that the linker (or maybe even the compiler, I'm not sure) may recognize that the caller and callee are using the same GOT section, making this prolog redundant, and modify the call target to skip these instructions. If we check for execution of the first instruction of a function (the one the symbol points to) to detect when to skip it, we'll miss all these modified calls. It might work to unconditionally check for the third instruction, but not all functions have this prolog, and there's some chance that those first two instructions could have undesired consequences. So we do the Right Thing and pattern-match the first two instructions of the function to decide where to patch.
Eventually this code should be moved into an ISA-specific file.
Reimplemented from System.
Definition at line 187 of file system.cc.
References DPRINTF, PortProxy::read(), and virtProxy.
void AlphaSystem::initState () [virtual]
Initialise the state of the system.
Copy the osflags (kernel arguments) into the consoles memory. (Presently Linux does not use the console service routine to get these command line arguments, but Tru64 and others do.)
Set the hardware reset parameter block system type and revision information to Tsunami.
Reimplemented from System.
Reimplemented in LinuxAlphaSystem.
Definition at line 100 of file system.cc.
References X86ISA::addr, console, consoleSymtab, SymbolTable::findAddress(), BigEndianGuest::htog(), System::loadAddrMask, ObjectFile::loadSections(), pal, panic, params(), System::physProxy, virtProxy, PortProxy::write(), and FSTranslatingPortProxy::writeBlob().
const Params* AlphaSystem::params () const [inline, protected]
Reimplemented from System.
Reimplemented in LinuxAlphaSystem.
Definition at line 100 of file system.hh.
References System::_params.
Referenced by AlphaSystem(), and initState().
void AlphaSystem::serializeSymtab (std::ostream & os) [virtual]
Serialization stuff.
Reimplemented from System.
Definition at line 221 of file system.cc.
References consoleSymtab, palSymtab, and SymbolTable::serialize().
void AlphaSystem::setAlphaAccess (Addr access)
Set the m5AlphaAccess pointer in the console.
Definition at line 210 of file system.cc.
References X86ISA::addr, consoleSymtab, SymbolTable::findAddress(), BigEndianGuest::htog(), panic, AlphaISA::Phys2K0Seg(), virtProxy, and PortProxy::write().
Referenced by AlphaBackdoor::startup().
void AlphaSystem::setIntrFreq (Tick freq) [inline]
Definition at line 127 of file system.hh.
References intrFreq.
Referenced by Tsunami::init().
void AlphaSystem::setupFuncEvents () [protected, virtual]
Setup all the function events.
Must be done after init() for Alpha since fixFuncEvent() requires a function port
Reimplemented in LinuxAlphaSystem.
Definition at line 148 of file system.cc.
References consolePanicEvent.
Referenced by startup().
void AlphaSystem::startup () [virtual]
Override startup() to provide a path to call setupFuncEvents().
Reimplemented from SimObject.
Definition at line 140 of file system.cc.
References setupFuncEvents().
void AlphaSystem::unserializeSymtab (Checkpoint * cp, const std::string & section) [virtual]
If needed, unserialize additional symbol table entries for a specific subclass of this system.
Parameters:
cp checkpoint to unserialize from
section relevant section in the checkpoint
Reimplemented from System.
Definition at line 228 of file system.cc.
References consoleSymtab, palSymtab, and SymbolTable::unserialize().
Member Data Documentation
ObjectFile* AlphaSystem::console
Object pointer for the console code.
Definition at line 82 of file system.hh.
Referenced by AlphaSystem(), initState(), and ~AlphaSystem().
BreakPCEvent* AlphaSystem::consolePanicEvent
Event to halt the simulator if the console calls panic().
Definition at line 89 of file system.hh.
Referenced by setupFuncEvents(), and ~AlphaSystem().
SymbolTable* AlphaSystem::consoleSymtab
console symbol table
Definition at line 76 of file system.hh.
Referenced by addConsoleFuncEvent(), AlphaSystem(), initState(), serializeSymtab(), setAlphaAccess(), unserializeSymtab(), and ~AlphaSystem().
Tick AlphaSystem::intrFreq [protected]
Definition at line 93 of file system.hh.
Referenced by LinuxAlphaSystem::setDelayLoop(), and setIntrFreq().
ObjectFile* AlphaSystem::pal
Object pointer for the PAL code.
Definition at line 85 of file system.hh.
Referenced by AlphaSystem(), initState(), and ~AlphaSystem().
SymbolTable* AlphaSystem::palSymtab
pal symbol table
Definition at line 79 of file system.hh.
Referenced by addPalFuncEvent(), AlphaSystem(), serializeSymtab(), and unserializeSymtab().
FSTranslatingPortProxy AlphaSystem::virtProxy [protected]
Proxy used to copy arguments directly into kernel memory.
Definition at line 98 of file system.hh.
Referenced by FreebsdAlphaSystem::doCalibrateClocks(), fixFuncEventAddr(), initState(), LinuxAlphaSystem::initState(), setAlphaAccess(), and Tru64AlphaSystem::Tru64AlphaSystem().
The documentation for this class was generated from the following files:
arch/alpha/system.hh
arch/alpha/system.cc