gem5: ArmISA::DataX2RegImmOp Class Reference
ArmISA::DataX2RegImmOp Class Reference
#include <data64.hh>
Protected Member Functions
DataX2RegImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, IntRegIndex _op2, uint64_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
IntRegIndex op1
IntRegIndex op2
uint64_t imm
Detailed Description
Definition at line 172 of file data64.hh.
Constructor & Destructor Documentation
ArmISA::DataX2RegImmOp::DataX2RegImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, IntRegIndex _op2, uint64_t _imm) [inline, protected]
Definition at line 178 of file data64.hh.
Member Function Documentation
std::string ArmISA::DataX2RegImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 131 of file data64.cc.
References ccprintf(), dest, imm, op1, op2, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex ArmISA::DataX2RegImmOp::dest [protected]
Definition at line 175 of file data64.hh.
Referenced by generateDisassembly().
uint64_t ArmISA::DataX2RegImmOp::imm [protected]
Definition at line 176 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataX2RegImmOp::op1 [protected]
Definition at line 175 of file data64.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::DataX2RegImmOp::op2 [protected]
Definition at line 175 of file data64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/data64.hh
arch/arm/insts/data64.cc