gem5: BaseCPU Class Reference
BaseCPU Class Reference
#include <cpu_dummy.hh>
Static Public Member Functions
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup ()
Detailed Description
Definition at line 45 of file cpu_dummy.hh.
Member Function Documentation
static int BaseCPU::numSimulatedInsts () [inline, static]
Definition at line 48 of file cpu_dummy.hh.
Referenced by Stats::Global::Global().
static int BaseCPU::numSimulatedOps () [inline, static]
Definition at line 49 of file cpu_dummy.hh.
Referenced by Stats::Global::Global().
static void BaseCPU::wakeup () [inline, static]
Reimplemented in CheckerCPU, BaseKvmCPU, MinorCPU, FullO3CPU< Impl >, BaseSimpleCPU, and FullO3CPU< O3CPUImpl >.
Definition at line 50 of file cpu_dummy.hh.
Referenced by AbstractMemory::checkLockedAddrList(), and X86ISA::Interrupts::requestInterrupt().
The documentation for this class was generated from the following file:
arch/null/cpu_dummy.hh