gem5: ArmISA::Interrupts Class Reference
ArmISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
enum InterruptMask { INT_MASK_M, INT_MASK_T, INT_MASK_P }
typedef ArmInterruptsParams Params
Public Member Functions
void setCPU (BaseCPU *_cpu)
const Params * params () const
Interrupts (Params *p)
void post (int int_num, int index)
void clear (int int_num, int index)
void clearAll ()
bool takeInt (ThreadContext *tc, InterruptTypes int_type) const
bool checkInterrupts (ThreadContext *tc) const
bool checkWfiWake (HCR hcr, CPSR cpsr, SCR scr) const
This function is used to check if a wfi operation should sleep.
uint32_t getISR (HCR hcr, CPSR cpsr, SCR scr)
bool checkRaw (InterruptTypes interrupt) const
Check the state of a particular interrupt, ignoring CPSR masks.
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc)
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Attributes
BaseCPU * cpu
bool interrupts [NumInterruptTypes]
uint64_t intStatus
Detailed Description
Definition at line 59 of file interrupts.hh.
Member Typedef Documentation
typedef ArmInterruptsParams ArmISA::Interrupts::Params
Reimplemented from SimObject.
Definition at line 75 of file interrupts.hh.
Member Enumeration Documentation
enum ArmISA::Interrupts::InterruptMask
Enumerator:
INT_MASK_M
INT_MASK_T
INT_MASK_P
Definition at line 127 of file interrupts.hh.
Constructor & Destructor Documentation
ArmISA::Interrupts::Interrupts (Params * p) [inline]
Definition at line 83 of file interrupts.hh.
References clearAll().
Member Function Documentation
bool ArmISA::Interrupts::checkInterrupts (ThreadContext * tc) const [inline]
Definition at line 136 of file interrupts.hh.
References ArmISA::cpsr, ArmISA::inSecureState(), ArmISA::INT_ABT, ArmISA::INT_FIQ, ArmISA::INT_IRQ, ArmISA::INT_RST, ArmISA::INT_SEV, ArmISA::INT_VIRT_FIQ, ArmISA::INT_VIRT_IRQ, interrupts, intStatus, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_SCR, ArmISA::MODE_HYP, ThreadContext::readMiscReg(), ArmISA::scr, and takeInt().
bool ArmISA::Interrupts::checkRaw (InterruptTypes interrupt) const [inline]
Check the state of a particular interrupt, ignoring CPSR masks.
This method is primarily used when running the target CPU in a hardware VM (e.g., KVM) to check if interrupts should be delivered upon guest entry.
Parameters:
interrupt Interrupt type to check the state of.
Returns:
true if the interrupt is asserted, false otherwise.
Definition at line 213 of file interrupts.hh.
References interrupts, ArmISA::NumInterruptTypes, and panic.
bool ArmISA::Interrupts::checkWfiWake (HCR hcr, CPSR cpsr, SCR scr) const [inline]
This function is used to check if a wfi operation should sleep.
If there is an interrupt pending, even if it's masked, wfi doesn't sleep.
Returns:
any interrupts pending
Definition at line 173 of file interrupts.hh.
References ArmISA::inSecureState(), ArmISA::INT_VIRT_FIQ, ArmISA::INT_VIRT_IRQ, interrupts, intStatus, and ArmISA::MODE_HYP.
void ArmISA::Interrupts::clear (int int_num, int index) [inline]
Definition at line 105 of file interrupts.hh.
References DPRINTF, interrupts, intStatus, ArmISA::NumInterruptTypes, panic, and ULL.
void ArmISA::Interrupts::clearAll () [inline]
Definition at line 120 of file interrupts.hh.
References DPRINTF, interrupts, and intStatus.
Referenced by Interrupts().
Fault ArmISA::Interrupts::getInterrupt (ThreadContext * tc) [inline]
Definition at line 222 of file interrupts.hh.
References ArmISA::ArmFault::AsynchronousExternalAbort, ArmISA::cpsr, ArmISA::inSecureState(), ArmISA::INT_ABT, ArmISA::INT_FIQ, ArmISA::INT_IRQ, ArmISA::INT_RST, ArmISA::INT_SEV, ArmISA::INT_VIRT_FIQ, ArmISA::INT_VIRT_IRQ, interrupts, intStatus, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_SCR, ArmISA::MODE_HYP, panic, ThreadContext::readMiscReg(), ArmISA::scr, and takeInt().
uint32_t ArmISA::Interrupts::getISR (HCR hcr, CPSR cpsr, SCR scr) [inline]
Definition at line 188 of file interrupts.hh.
References ArmISA::inSecureState(), ArmISA::INT_ABT, ArmISA::INT_FIQ, ArmISA::INT_IRQ, ArmISA::INT_VIRT_FIQ, ArmISA::INT_VIRT_IRQ, interrupts, and ArmISA::MODE_HYP.
const Params* ArmISA::Interrupts::params () const [inline]
Reimplemented from SimObject.
Definition at line 78 of file interrupts.hh.
References SimObject::_params.
void ArmISA::Interrupts::post (int int_num, int index) [inline]
Definition at line 90 of file interrupts.hh.
References DPRINTF, interrupts, intStatus, ArmISA::NumInterruptTypes, panic, and ULL.
void ArmISA::Interrupts::serialize (std::ostream & os) [inline, virtual]
Reimplemented from Serializable.
Definition at line 275 of file interrupts.hh.
References interrupts, intStatus, ArmISA::NumInterruptTypes, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
void ArmISA::Interrupts::setCPU (BaseCPU * _cpu) [inline]
Definition at line 70 of file interrupts.hh.
References cpu.
bool ArmISA::Interrupts::takeInt (ThreadContext * tc, InterruptTypes int_type) const
Definition at line 50 of file interrupts.cc.
References ArmISA::cpsr, ArmISA::el, ArmISA::EL0, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmSystem::highestELIs64(), ArmISA::inSecureState(), ArmISA::INT_ABT, ArmISA::INT_FIQ, ArmISA::INT_IRQ, INT_MASK_M, INT_MASK_P, INT_MASK_T, ArmISA::mask, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_SCR, ArmISA::MISCREG_SCR_EL3, panic, ThreadContext::readMiscReg(), and ArmISA::scr.
Referenced by checkInterrupts(), and getInterrupt().
void ArmISA::Interrupts::unserialize (Checkpoint * cp, const std::string & section) [inline, virtual]
Reimplemented from Serializable.
Definition at line 282 of file interrupts.hh.
References interrupts, intStatus, ArmISA::NumInterruptTypes, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
void ArmISA::Interrupts::updateIntrInfo (ThreadContext * tc) [inline]
Definition at line 269 of file interrupts.hh.
Member Data Documentation
BaseCPU* ArmISA::Interrupts::cpu [private]
Definition at line 62 of file interrupts.hh.
Referenced by setCPU().
bool ArmISA::Interrupts::interrupts[NumInterruptTypes] [private]
Definition at line 64 of file interrupts.hh.
Referenced by checkInterrupts(), checkRaw(), checkWfiWake(), clear(), clearAll(), getInterrupt(), getISR(), post(), serialize(), and unserialize().
uint64_t ArmISA::Interrupts::intStatus [private]
Definition at line 65 of file interrupts.hh.
Referenced by checkInterrupts(), checkWfiWake(), clear(), clearAll(), getInterrupt(), post(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
arch/arm/interrupts.hh
arch/arm/interrupts.cc