gem5: VoltageDomain Class Reference
VoltageDomain Class Reference
A VoltageDomain is used to group clock domains that operate under the same voltage.
#include <voltage_domain.hh>
Public Types
typedef VoltageDomainParams Params
typedef SrcClockDomain::PerfLevel PerfLevel
Public Member Functions
VoltageDomain (const Params *p)
double voltage () const
Get the current voltage.
double voltage (PerfLevel perf_level) const
Get the voltage at specified performance level.
uint32_t numVoltages () const
void perfLevel (PerfLevel perf_level)
Set the voltage point of the domain.
PerfLevel perfLevel () const
Get the voltage point of the domain.
void registerSrcClockDom (SrcClockDomain *src_clock_dom)
Register a SrcClockDomain with this voltage domain.
void startup ()
Startup has all SrcClockDomains registered with this voltage domain, so try to make sure that all perf level requests from them are met.
bool sanitiseVoltages ()
Recomputes the highest (fastest, i.e., numerically lowest) requested performance level of all associated clock domains, and updates the performance level of this voltage domain to match.
void regStats ()
Register statistics for this object.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Types
typedef std::vector< double > Voltages
typedef std::vector
< SrcClockDomain * > SrcClockChildren
List of associated SrcClockDomains that are connected to this voltage domain.
Private Attributes
const Voltages voltageOpPoints
List of possible minimum voltage at each of the frequency operational points, should be in descending order and same size as freqOpPoints.
PerfLevel _perfLevel
Stats::Value currentVoltage
Stat for reporting voltage of the domain.
SrcClockChildren srcClockChildren
Detailed Description
A VoltageDomain is used to group clock domains that operate under the same voltage.
The class provides methods for setting and getting the voltage.
Definition at line 56 of file voltage_domain.hh.
Member Typedef Documentation
typedef VoltageDomainParams VoltageDomain::Params
Reimplemented from SimObject.
Definition at line 60 of file voltage_domain.hh.
typedef SrcClockDomain::PerfLevel VoltageDomain::PerfLevel
Definition at line 63 of file voltage_domain.hh.
typedef std::vector<SrcClockDomain *> VoltageDomain::SrcClockChildren [private]
List of associated SrcClockDomains that are connected to this voltage domain.
Definition at line 154 of file voltage_domain.hh.
typedef std::vector<double> VoltageDomain::Voltages [private]
Definition at line 134 of file voltage_domain.hh.
Constructor & Destructor Documentation
VoltageDomain::VoltageDomain (const Params * p)
Definition at line 49 of file voltage_domain.cc.
References fatal_if, SimObject::name(), and voltageOpPoints.
Member Function Documentation
uint32_t VoltageDomain::numVoltages () const [inline]
Definition at line 87 of file voltage_domain.hh.
References voltageOpPoints.
Referenced by sanitiseVoltages(), SrcClockDomain::SrcClockDomain(), voltage(), and DVFSHandler::voltageAtPerfLevel().
PerfLevel VoltageDomain::perfLevel () const [inline]
Get the voltage point of the domain.
Parameters:
Voltage value to be set
Definition at line 99 of file voltage_domain.hh.
References _perfLevel.
Referenced by sanitiseVoltages(), and unserialize().
void VoltageDomain::perfLevel (PerfLevel perf_level)
Set the voltage point of the domain.
Parameters:
Voltage value to be set
Definition at line 63 of file voltage_domain.cc.
References _perfLevel, chatty_assert, DPRINTF, SimObject::name(), voltage(), and voltageOpPoints.
void VoltageDomain::registerSrcClockDom (SrcClockDomain * src_clock_dom) [inline]
Register a SrcClockDomain with this voltage domain.
Parameters:
src_clock_domain The SrcClockDomain to register.
Definition at line 105 of file voltage_domain.hh.
References srcClockChildren, and ClockDomain::voltageDomain().
Referenced by SrcClockDomain::SrcClockDomain().
void VoltageDomain::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 129 of file voltage_domain.cc.
References currentVoltage, Stats::ValueBase< Derived >::method(), SimObject::name(), SimObject::params(), and voltage().
bool VoltageDomain::sanitiseVoltages ()
Recomputes the highest (fastest, i.e., numerically lowest) requested performance level of all associated clock domains, and updates the performance level of this voltage domain to match.
This means that for two connected clock domains, one fast and one slow, the voltage domain will provide the voltage associated with the fast DVFS operation point. Must be called whenever a clock domain decides to swtich its performance level.
Returns:
True, if the voltage was actually changed.
Definition at line 81 of file voltage_domain.cc.
References chatty_assert, ArmISA::d, SrcClockDomain::domainID(), DPRINTF, SimObject::name(), numVoltages(), perfLevel(), SrcClockDomain::perfLevel(), srcClockChildren, and ClockDomain::voltageDomain().
Referenced by SrcClockDomain::perfLevel(), and startup().
void VoltageDomain::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 145 of file voltage_domain.cc.
References _perfLevel, and SERIALIZE_SCALAR.
void VoltageDomain::startup () [virtual]
Startup has all SrcClockDomains registered with this voltage domain, so try to make sure that all perf level requests from them are met.
Reimplemented from SimObject.
Definition at line 120 of file voltage_domain.cc.
References SimObject::name(), sanitiseVoltages(), and warn.
void VoltageDomain::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 150 of file voltage_domain.cc.
References _perfLevel, perfLevel(), and UNSERIALIZE_SCALAR.
double VoltageDomain::voltage (PerfLevel perf_level) const [inline]
Get the voltage at specified performance level.
Parameters:
perf_level Performance level for which the voltage is requested
Returns:
Voltage of the domain at specified performance level
Definition at line 78 of file voltage_domain.hh.
References chatty_assert, SimObject::name(), numVoltages(), and voltageOpPoints.
double VoltageDomain::voltage () const [inline]
Get the current voltage.
Returns:
Voltage of the domain
Definition at line 70 of file voltage_domain.hh.
References _perfLevel, and voltageOpPoints.
Referenced by perfLevel(), regStats(), ClockDomain::voltage(), and DVFSHandler::voltageAtPerfLevel().
Member Data Documentation
PerfLevel VoltageDomain::_perfLevel [private]
Definition at line 143 of file voltage_domain.hh.
Referenced by perfLevel(), serialize(), unserialize(), and voltage().
Stats::Value VoltageDomain::currentVoltage [private]
Stat for reporting voltage of the domain.
Definition at line 148 of file voltage_domain.hh.
Referenced by regStats().
SrcClockChildren VoltageDomain::srcClockChildren [private]
Definition at line 155 of file voltage_domain.hh.
Referenced by registerSrcClockDom(), and sanitiseVoltages().
const Voltages VoltageDomain::voltageOpPoints [private]
List of possible minimum voltage at each of the frequency operational points, should be in descending order and same size as freqOpPoints.
An empty list corresponds to default voltage specified for the voltage domain its clock domain belongs. The same voltage is applied for each freqOpPoints, overall implying NO DVS
Definition at line 142 of file voltage_domain.hh.
Referenced by numVoltages(), perfLevel(), voltage(), and VoltageDomain().
The documentation for this class was generated from the following files:
sim/voltage_domain.hh
sim/voltage_domain.cc