gem5: PciDevice Class Reference
PciDevice Class Reference
PCI device, base implementation is only config space.
#include <pcidev.hh>
Classes
class PciConfigPort
Public Types
typedef PciDeviceParams Params
Public Member Functions
const Params * params () const
Addr pciToDma (Addr pciAddr) const
void intrPost ()
void intrClear ()
uint8_t interruptLine ()
AddrRangeList getAddrRanges () const
Determine the address ranges that this device responds to.
PciDevice (const Params *params)
Constructor for PCI Dev.
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void serialize (std::ostream &os)
Serialize this object to the given output stream.
virtual void unserialize (Checkpoint *cp, const std::string &section)
Reconstruct the state of this object from a checkpoint.
virtual unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
virtual BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
Protected Member Functions
bool isBAR (Addr addr, int bar) const
Does the given address lie within the space mapped by the given base address register?
int getBAR (Addr addr)
Which base address register (if any) maps the given address?
bool getBAR (Addr addr, int &bar, Addr &offs)
Which base address register (if any) maps the given address?
virtual Tick writeConfig (PacketPtr pkt)
Write to the PCI config space data that is stored locally.
virtual Tick readConfig (PacketPtr pkt)
Read from the PCI config space data that is stored locally.
Protected Attributes
PCIConfig config
The current config space.
std::vector< MSIXTable > msix_table
MSIX Table and PBA Structures.
std::vector< MSIXPbaEntry > msix_pba
uint32_t BARSize [6]
The size of the BARs.
Addr BARAddrs [6]
The current address mapping of the BARs.
bool legacyIO [6]
Whether the BARs are really hardwired legacy IO locations.
Platform * platform
Tick pioDelay
Tick configDelay
PciConfigPort configPort
const int PMCAP_BASE
The capability list structures and base addresses.
const int PMCAP_ID_OFFSET
const int PMCAP_PC_OFFSET
const int PMCAP_PMCS_OFFSET
PMCAP pmcap
const int MSICAP_BASE
MSICAP msicap
const int MSIXCAP_BASE
const int MSIXCAP_ID_OFFSET
const int MSIXCAP_MXC_OFFSET
const int MSIXCAP_MTAB_OFFSET
const int MSIXCAP_MPBA_OFFSET
int MSIX_TABLE_OFFSET
int MSIX_TABLE_END
int MSIX_PBA_OFFSET
int MSIX_PBA_END
MSIXCAP msixcap
const int PXCAP_BASE
PXCAP pxcap
Detailed Description
PCI device, base implementation is only config space.
Definition at line 72 of file pcidev.hh.
Member Typedef Documentation
typedef PciDeviceParams PciDevice::Params
Reimplemented from DmaDevice.
Reimplemented in CopyEngine, EtherDevice, IGbE, IdeController, NSGigE, Sinic::Base, and PciVirtIO.
Definition at line 97 of file pcidev.hh.
Constructor & Destructor Documentation
PciDevice::PciDevice (const Params * params)
Constructor for PCI Dev.
This function copies data from the config file object PCIConfigData and registers the device with a PciConfigAll object.
Definition at line 97 of file pcidev.cc.
References BARAddrs, BARSize, PCIConfig::baseAddr, PCIConfig::bist, PCIConfig::cacheLineSize, PCIConfig::capabilityPtr, PCIConfig::cardbusCIS, PCIConfig::classCode, PCIConfig::command, config, PCIConfig::device, PCIConfig::expansionROM, fatal, PCIConfig::headerType, htole(), ArmISA::i, PCIConfig::interruptLine, PCIConfig::interruptPin, isPowerOf2(), PCIConfig::latencyTimer, legacyIO, letoh(), MSICAP::ma, PCIConfig::maximumLatency, MSICAP::mc, MSICAP::md, MSICAP::mid, PCIConfig::minimumGrant, MSICAP::mmask, MSIXCAP::mpba, MSICAP::mpend, msicap, msix_pba, MSIX_PBA_END, MSIX_PBA_OFFSET, msix_table, MSIX_TABLE_END, MSIX_TABLE_OFFSET, msixcap, MSIXCAP_BASE, MSIXVECS_PER_PBA, MSIXCAP::mtab, MSICAP::mua, MSIXCAP::mxc, MSIXCAP::mxid, PMCAP::pc, PMCAP::pid, platform, pmcap, PMCAP::pmcs, PCIConfig::progIF, PXCAP::pxcap, pxcap, PXCAP::pxdc, PXCAP::pxdc2, PXCAP::pxdcap, PXCAP::pxdcap2, PXCAP::pxds, PXCAP::pxid, PXCAP::pxlc, PXCAP::pxlcap, PXCAP::pxls, Platform::registerPciDevice(), PCIConfig::reserved, PCIConfig::revision, PCIConfig::status, PCIConfig::subClassCode, PCIConfig::subsystemID, PCIConfig::subsystemVendorID, and PCIConfig::vendor.
Member Function Documentation
unsigned int PciDevice::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from DmaDevice.
Reimplemented in CopyEngine, and IGbE.
Definition at line 259 of file pcidev.cc.
References configPort, X86ISA::count, DmaDevice::dmaPort, DmaPort::drain(), QueuedSlavePort::drain(), Drainable::Drained, Drainable::Draining, PioDevice::pioPort, and Drainable::setDrainState().
AddrRangeList PciDevice::getAddrRanges () const [virtual]
Determine the address ranges that this device responds to.
Returns:
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 328 of file pcidev.cc.
References BARAddrs, BARSize, RangeSize(), and X86ISA::x.
bool PciDevice::getBAR (Addr addr, int & bar, Addr & offs) [inline, protected]
Which base address register (if any) maps the given address?
Parameters:
addr The address to check.
Return values:
bar The BAR number (0-5 inclusive), only valid if return value is true.
offs The offset from the base address, only valid if return value is true.
Returns:
True iff address maps to a base address register's region.
Definition at line 182 of file pcidev.hh.
References ArmISA::b, BARAddrs, and getBAR().
int PciDevice::getBAR (Addr addr) [inline, protected]
Which base address register (if any) maps the given address?
Returns:
The BAR number (0-5 inclusive), or -1 if none.
Definition at line 163 of file pcidev.hh.
References ArmISA::i, and isBAR().
Referenced by getBAR(), PciVirtIO::read(), IGbE::read(), CopyEngine::read(), PciVirtIO::write(), IGbE::write(), and CopyEngine::write().
virtual BaseSlavePort& PciDevice::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [inline, virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from PioDevice.
Definition at line 264 of file pcidev.hh.
References configPort.
void PciDevice::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from DmaDevice.
Reimplemented in IGbE.
Definition at line 250 of file pcidev.cc.
References configPort, BaseSlavePort::isConnected(), SimObject::name(), panic, and SlavePort::sendRangeChange().
uint8_t PciDevice::interruptLine () [inline]
Definition at line 229 of file pcidev.hh.
References config, PCIConfig::interruptLine, and letoh().
void PciDevice::intrClear () [inline]
Definition at line 225 of file pcidev.hh.
References Platform::clearPciInt(), config, PCIConfig::interruptLine, letoh(), and platform.
Referenced by IGbE::cpuClearInt(), Sinic::Base::cpuIntrClear(), NSGigE::cpuIntrClear(), IdeDisk::intrClear(), and PciVirtIO::read().
void PciDevice::intrPost () [inline]
Reimplemented in IdeController.
Definition at line 221 of file pcidev.hh.
References config, PCIConfig::interruptLine, letoh(), platform, and Platform::postPciInt().
Referenced by Sinic::Base::cpuInterrupt(), NSGigE::cpuInterrupt(), IGbE::cpuPostInt(), and PciVirtIO::kick().
bool PciDevice::isBAR (Addr addr, int bar) const [inline, protected]
Does the given address lie within the space mapped by the given base address register?
Definition at line 152 of file pcidev.hh.
References BARAddrs, and BARSize.
Referenced by getBAR().
const Params* PciDevice::params () const [inline]
Reimplemented from PioDevice.
Reimplemented in CopyEngine, EtherDevice, EtherDevBase, IGbE, IdeController, NSGigE, and Sinic::Base.
Definition at line 99 of file pcidev.hh.
References SimObject::_params.
Referenced by readConfig(), and writeConfig().
Addr PciDevice::pciToDma (Addr pciAddr) const [inline]
Definition at line 217 of file pcidev.hh.
References Platform::pciToDma(), and platform.
Referenced by IdeDisk::pciToDma().
Tick PciDevice::readConfig (PacketPtr pkt) [protected, virtual]
Read from the PCI config space data that is stored locally.
This may be overridden by the device but at some point it will eventually call this for normal operations that it does not need to override.
Parameters:
pkt packet containing the write the offset into config space
Reimplemented in IdeController.
Definition at line 271 of file pcidev.cc.
References config, configDelay, PCIConfig::data, DPRINTF, Packet::get(), Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), SimObject::name(), ArmISA::offset, panic, params(), PCI_CONFIG_SIZE, PCI_DEVICE_SPECIFIC, Packet::set(), and warn_once.
Referenced by NSGigE::read(), and PciDevice::PciConfigPort::recvAtomic().
void PciDevice::serialize (std::ostream & os) [virtual]
Serialize this object to the given output stream.
Parameters:
os The stream to serialize to.
Reimplemented from Serializable.
Reimplemented in CopyEngine, IGbE, IdeController, NSGigE, Sinic::Base, and Sinic::Device.
Definition at line 476 of file pcidev.cc.
References BARAddrs, BARSize, bits(), config, csprintf(), PCIConfig::data, ArmISA::i, MSICAP::ma, MSICAP::mc, MSICAP::md, MSICAP::mid, MSICAP::mmask, MSIXCAP::mpba, MSICAP::mpend, msicap, msix_pba, msix_table, msixcap, MSIXCAP_BASE, MSIXVECS_PER_PBA, MSIXCAP::mtab, MSICAP::mua, MSIXCAP::mxc, MSIXCAP::mxid, paramOut(), PMCAP::pc, PMCAP::pid, pmcap, PMCAP::pmcs, PXCAP::pxcap, pxcap, PXCAP::pxdc, PXCAP::pxdc2, PXCAP::pxdcap, PXCAP::pxdcap2, PXCAP::pxds, PXCAP::pxid, PXCAP::pxlc, PXCAP::pxlcap, PXCAP::pxls, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
void PciDevice::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reconstruct the state of this object from a checkpoint.
Parameters:
cp The checkpoint use.
section The section name of this object
Reimplemented from Serializable.
Reimplemented in CopyEngine, IGbE, IdeController, NSGigE, Sinic::Base, and Sinic::Device.
Definition at line 541 of file pcidev.cc.
References BARAddrs, BARSize, bits(), config, csprintf(), PCIConfig::data, ArmISA::i, MSICAP::ma, MSICAP::mc, MSICAP::md, MSICAP::mid, MSICAP::mmask, MSIXCAP::mpba, MSICAP::mpend, msicap, msix_pba, msix_table, msixcap, MSIXCAP_BASE, MSIXCAP::mtab, MSICAP::mua, MSIXCAP::mxc, MSIXCAP::mxid, paramIn(), PMCAP::pc, PMCAP::pid, PioDevice::pioPort, pmcap, PMCAP::pmcs, PXCAP::pxcap, pxcap, PXCAP::pxdc, PXCAP::pxdc2, PXCAP::pxdcap, PXCAP::pxdcap2, PXCAP::pxds, PXCAP::pxid, PXCAP::pxlc, PXCAP::pxlcap, PXCAP::pxls, SlavePort::sendRangeChange(), UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Tick PciDevice::writeConfig (PacketPtr pkt) [protected, virtual]
Write to the PCI config space data that is stored locally.
This may be overridden by the device but at some point it will eventually call this for normal operations that it does not need to override.
Parameters:
pkt packet containing the write the offset into config space
Reimplemented in IGbE, IdeController, and NSGigE.
Definition at line 339 of file pcidev.cc.
References BAR_IO_MASK, BAR_IO_SPACE, BAR_MEM_MASK, BAR_NUMBER, BARAddrs, BARSize, PCIConfig::baseAddr, PCIConfig::cacheLineSize, Platform::calcPciIOAddr(), Platform::calcPciMemAddr(), PCIConfig::command, config, configDelay, DPRINTF, PCIConfig::expansionROM, Packet::get(), Packet::getAddr(), Packet::getSize(), htole(), PCIConfig::interruptLine, PCIConfig::latencyTimer, legacyIO, letoh(), Packet::makeAtomicResponse(), SimObject::name(), ArmISA::offset, panic, params(), PCI0_BASE_ADDR0, PCI0_BASE_ADDR1, PCI0_BASE_ADDR2, PCI0_BASE_ADDR3, PCI0_BASE_ADDR4, PCI0_BASE_ADDR5, PCI0_INTERRUPT_LINE, PCI0_INTERRUPT_PIN, PCI0_MAXIMUM_LATENCY, PCI0_MINIMUM_GRANT, PCI0_ROM_BASE_ADDR, PCI_CACHE_LINE_SIZE, PCI_CLASS_CODE, PCI_COMMAND, PCI_CONFIG_SIZE, PCI_DEVICE_SPECIFIC, PCI_LATENCY_TIMER, PCI_REVISION_ID, PCI_STATUS, PioDevice::pioPort, platform, SlavePort::sendRangeChange(), PCIConfig::status, and warn_once.
Referenced by PciDevice::PciConfigPort::recvAtomic().
Member Data Documentation
Addr PciDevice::BARAddrs[6] [protected]
The current address mapping of the BARs.
Definition at line 142 of file pcidev.hh.
Referenced by getAddrRanges(), getBAR(), IdeController::IdeController(), isBAR(), PciDevice(), Sinic::Device::read(), serialize(), unserialize(), Sinic::Device::write(), writeConfig(), and IdeController::writeConfig().
uint32_t PciDevice::BARSize[6] [protected]
The size of the BARs.
Definition at line 139 of file pcidev.hh.
Referenced by getAddrRanges(), IdeController::IdeController(), isBAR(), PciDevice(), PciVirtIO::PciVirtIO(), Sinic::Device::read(), serialize(), unserialize(), Sinic::Device::write(), and writeConfig().
PCIConfig PciDevice::config [protected]
The current config space.
Definition at line 106 of file pcidev.hh.
Referenced by IdeController::IdeController(), interruptLine(), intrClear(), intrPost(), PciDevice(), PciVirtIO::PciVirtIO(), Sinic::Device::read(), readConfig(), serialize(), unserialize(), Sinic::Device::write(), writeConfig(), NSGigE::writeConfig(), and IdeController::writeConfig().
Tick PciDevice::configDelay [protected]
Definition at line 196 of file pcidev.hh.
Referenced by readConfig(), IdeController::readConfig(), writeConfig(), NSGigE::writeConfig(), IdeController::writeConfig(), and IGbE::writeConfig().
PciConfigPort PciDevice::configPort [protected]
Definition at line 197 of file pcidev.hh.
Referenced by drain(), CopyEngine::drain(), getSlavePort(), and init().
bool PciDevice::legacyIO[6] [protected]
Whether the BARs are really hardwired legacy IO locations.
Definition at line 145 of file pcidev.hh.
Referenced by IdeController::IdeController(), PciDevice(), and writeConfig().
MSICAP PciDevice::msicap [protected]
Definition at line 117 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
const int PciDevice::MSICAP_BASE [protected]
Definition at line 116 of file pcidev.hh.
std::vector<MSIXPbaEntry> PciDevice::msix_pba [protected]
Definition at line 136 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
int PciDevice::MSIX_PBA_END [protected]
Definition at line 127 of file pcidev.hh.
Referenced by PciDevice().
int PciDevice::MSIX_PBA_OFFSET [protected]
Definition at line 126 of file pcidev.hh.
Referenced by PciDevice().
std::vector<MSIXTable> PciDevice::msix_table [protected]
MSIX Table and PBA Structures.
Definition at line 135 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
int PciDevice::MSIX_TABLE_END [protected]
Definition at line 125 of file pcidev.hh.
Referenced by PciDevice().
int PciDevice::MSIX_TABLE_OFFSET [protected]
Definition at line 124 of file pcidev.hh.
Referenced by PciDevice().
MSIXCAP PciDevice::msixcap [protected]
Definition at line 128 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
const int PciDevice::MSIXCAP_BASE [protected]
Definition at line 119 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
const int PciDevice::MSIXCAP_ID_OFFSET [protected]
Definition at line 120 of file pcidev.hh.
const int PciDevice::MSIXCAP_MPBA_OFFSET [protected]
Definition at line 123 of file pcidev.hh.
const int PciDevice::MSIXCAP_MTAB_OFFSET [protected]
Definition at line 122 of file pcidev.hh.
const int PciDevice::MSIXCAP_MXC_OFFSET [protected]
Definition at line 121 of file pcidev.hh.
Tick PciDevice::pioDelay [protected]
Definition at line 195 of file pcidev.hh.
Referenced by Sinic::Device::read(), NSGigE::read(), IdeController::read(), IGbE::read(), CopyEngine::read(), Sinic::Device::write(), NSGigE::write(), IdeController::write(), IGbE::write(), and CopyEngine::write().
Platform* PciDevice::platform [protected]
Definition at line 194 of file pcidev.hh.
Referenced by CopyEngine::CopyEngineChannel::fetchDescriptor(), CopyEngine::CopyEngineChannel::fetchNextAddr(), intrClear(), intrPost(), PciDevice(), pciToDma(), IGbE::DescCache< iGbReg::RxDesc >::pciToDma(), CopyEngine::CopyEngineChannel::readCopyBytes(), CopyEngine::CopyEngineChannel::writeCompletionStatus(), writeConfig(), and CopyEngine::CopyEngineChannel::writeCopyBytes().
PMCAP PciDevice::pmcap [protected]
Definition at line 114 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
const int PciDevice::PMCAP_BASE [protected]
The capability list structures and base addresses.
Definition at line 110 of file pcidev.hh.
const int PciDevice::PMCAP_ID_OFFSET [protected]
Definition at line 111 of file pcidev.hh.
const int PciDevice::PMCAP_PC_OFFSET [protected]
Definition at line 112 of file pcidev.hh.
const int PciDevice::PMCAP_PMCS_OFFSET [protected]
Definition at line 113 of file pcidev.hh.
PXCAP PciDevice::pxcap [protected]
Definition at line 131 of file pcidev.hh.
Referenced by PciDevice(), serialize(), and unserialize().
const int PciDevice::PXCAP_BASE [protected]
Definition at line 130 of file pcidev.hh.
The documentation for this class was generated from the following files:
dev/pcidev.hh
dev/pcidev.cc