gem5: Stats::BinaryNode< Op > Class Template Reference
Stats::BinaryNode< Op > Class Template Reference
#include <statistics.hh>
Public Member Functions
BinaryNode (NodePtr &a, NodePtr &b)
const VResult & result () const
Return the result vector of this subtree.
Result total () const
Return the total of the result vector.
size_type size () const
Return the number of nodes in the subtree starting at this node.
std::string str () const
Public Attributes
NodePtr l
NodePtr r
VResult vresult
Detailed Description
template<class Op>
class Stats::BinaryNode< Op >
Definition at line 2295 of file statistics.hh.
Constructor & Destructor Documentation
template<class Op > Stats::BinaryNode< Op >::BinaryNode (NodePtr & a, NodePtr & b) [inline]
Definition at line 2303 of file statistics.hh.
Member Function Documentation
template<class Op > const VResult& Stats::BinaryNode< Op >::result () const [inline, virtual]
Return the result vector of this subtree.
Returns:
The result vector of this subtree.
Implements Stats::Node.
Definition at line 2306 of file statistics.hh.
References ArmISA::i, Stats::BinaryNode< Op >::l, X86ISA::op, Stats::BinaryNode< Op >::r, Stats::BinaryNode< Op >::size(), and Stats::BinaryNode< Op >::vresult.
Referenced by Stats::BinaryNode< Op >::total().
template<class Op > size_type Stats::BinaryNode< Op >::size () const [inline, virtual]
Return the number of nodes in the subtree starting at this node.
Returns:
the number of nodes in this subtree.
Implements Stats::Node.
Definition at line 2370 of file statistics.hh.
References Stats::BinaryNode< Op >::l, Stats::BinaryNode< Op >::r, and ArmISA::rs.
Referenced by Stats::BinaryNode< Op >::result(), and Stats::BinaryNode< Op >::total().
template<class Op > std::string Stats::BinaryNode< Op >::str () const [inline, virtual]
Implements Stats::Node.
Definition at line 2385 of file statistics.hh.
References csprintf(), Stats::BinaryNode< Op >::l, and Stats::BinaryNode< Op >::r.
template<class Op > Result Stats::BinaryNode< Op >::total () const [inline, virtual]
Return the total of the result vector.
Returns:
The total of the result vector.
If vectors are the same divide their sums (x0+x1)/(y0+y1)
Otherwise divide each item by the divisor
Implements Stats::Node.
Definition at line 2338 of file statistics.hh.
References ArmISA::i, Stats::BinaryNode< Op >::l, X86ISA::op, Stats::BinaryNode< Op >::r, Stats::BinaryNode< Op >::result(), and Stats::BinaryNode< Op >::size().
Member Data Documentation
template<class Op > NodePtr Stats::BinaryNode< Op >::l
Definition at line 2298 of file statistics.hh.
Referenced by Stats::BinaryNode< Op >::result(), Stats::BinaryNode< Op >::size(), Stats::BinaryNode< Op >::str(), and Stats::BinaryNode< Op >::total().
template<class Op > NodePtr Stats::BinaryNode< Op >::r
Definition at line 2299 of file statistics.hh.
Referenced by Stats::BinaryNode< Op >::result(), Stats::BinaryNode< Op >::size(), Stats::BinaryNode< Op >::str(), and Stats::BinaryNode< Op >::total().
template<class Op > VResult Stats::BinaryNode< Op >::vresult [mutable]
Definition at line 2300 of file statistics.hh.
Referenced by Stats::BinaryNode< Op >::result().
The documentation for this class was generated from the following file:
base/statistics.hh