gem5: CacheBlk::Lock Class Reference
CacheBlk::Lock Class Reference
Represents that the indicated thread context has a "lock" on the block, in the LL/SC sense.
#include <blk.hh>
Public Member Functions
bool matchesContext (Request *req)
bool overlapping (Request *req)
Lock (Request *req)
Public Attributes
int contextId
Addr lowAddr
Addr highAddr
Detailed Description
Represents that the indicated thread context has a "lock" on the block, in the LL/SC sense.
Definition at line 137 of file blk.hh.
Constructor & Destructor Documentation
CacheBlk::Lock::Lock (Request * req) [inline]
Definition at line 160 of file blk.hh.
Member Function Documentation
bool CacheBlk::Lock::matchesContext (Request * req) [inline]
Definition at line 144 of file blk.hh.
References Request::contextId(), contextId, Request::getPaddr(), Request::getSize(), highAddr, and lowAddr.
bool CacheBlk::Lock::overlapping (Request * req) [inline]
Definition at line 152 of file blk.hh.
References Request::getPaddr(), Request::getSize(), highAddr, and lowAddr.
Member Data Documentation
int CacheBlk::Lock::contextId
Definition at line 139 of file blk.hh.
Referenced by matchesContext().
Addr CacheBlk::Lock::highAddr
Definition at line 141 of file blk.hh.
Referenced by matchesContext(), and overlapping().
Addr CacheBlk::Lock::lowAddr
Definition at line 140 of file blk.hh.
Referenced by matchesContext(), and overlapping().
The documentation for this class was generated from the following file:
mem/cache/blk.hh