gem5: X86ISA::I82094AA Class Reference
X86ISA::I82094AA Class Reference
#include <i82094aa.hh>
Public Types
typedef I82094AAParams Params
Public Member Functions
BitUnion64 (RedirTableEntry) Bitfield< 63
const Params * params () const
I82094AA (Params *p)
void init ()
Tick read (PacketPtr pkt)
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt)
Pure virtual function that the device must implement.
AddrRangeList getIntAddrRange () const
void writeReg (uint8_t offset, uint32_t value)
uint32_t readReg (uint8_t offset)
BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
void signalInterrupt (int line)
void raiseInterruptPin (int number)
void lowerInterruptPin (int number)
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
Public Attributes
topDW
Bitfield< 55, 32 > topReserved
Bitfield< 31, 0 > bottomDW
Bitfield< 31, 17 > bottomReserved
Bitfield< 63, 56 > dest
Bitfield< 16 > mask
Bitfield< 15 > trigger
Bitfield< 14 > remoteIRR
Bitfield< 13 > polarity
Bitfield< 12 > deliveryStatus
Bitfield< 11 > destMode
Bitfield< 10, 8 > deliveryMode
Bitfield< 7, 0 > vector
EndBitUnion(RedirTableEntry)
protected uint8_t regSel
uint8_t initialApicId
uint8_t id
uint8_t arbId
uint64_t lowestPriorityOffset
RedirTableEntry redirTable [TableSize]
bool pinStates [TableSize]
Static Public Attributes
static const uint8_t TableSize = 24
static const uint8_t APICVersion = 0x14
Detailed Description
Definition at line 47 of file i82094aa.hh.
Member Typedef Documentation
typedef I82094AAParams X86ISA::I82094AA::Params
Reimplemented from BasicPioDevice.
Definition at line 85 of file i82094aa.hh.
Constructor & Destructor Documentation
X86ISA::I82094AA::I82094AA (Params * p)
Definition at line 41 of file i82094aa.cc.
References arbId, ArmISA::i, id, initialApicId, pinStates, redirTable, regSel, and TableSize.
Member Function Documentation
X86ISA::I82094AA::BitUnion64 (RedirTableEntry)
AddrRangeList X86ISA::I82094AA::getIntAddrRange () const [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 81 of file i82094aa.cc.
References initialApicId, X86ISA::PhysAddrAPICRangeSize, RangeEx(), and X86ISA::x86InterruptAddress().
BaseMasterPort & X86ISA::I82094AA::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 73 of file i82094aa.cc.
References X86ISA::IntDevice::intMasterPort.
void X86ISA::I82094AA::init () [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 62 of file i82094aa.cc.
void X86ISA::I82094AA::lowerInterruptPin (int number) [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 256 of file i82094aa.cc.
References pinStates, and TableSize.
const Params* X86ISA::I82094AA::params () const [inline]
Reimplemented from BasicPioDevice.
Definition at line 88 of file i82094aa.hh.
References SimObject::_params.
void X86ISA::I82094AA::raiseInterruptPin (int number) [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 247 of file i82094aa.cc.
References pinStates, signalInterrupt(), and TableSize.
Tick X86ISA::I82094AA::read (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 91 of file i82094aa.cc.
References Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), X86ISA::offset, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, readReg(), regSel, and Packet::set().
uint32_t X86ISA::I82094AA::readReg (uint8_t offset)
Definition at line 154 of file i82094aa.cc.
References APICVersion, arbId, DPRINTF, X86ISA::index, redirTable, TableSize, and warn.
Referenced by read().
void X86ISA::I82094AA::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 263 of file i82094aa.cc.
References arbId, initialApicId, lowestPriorityOffset, pinStates, redirTable, regSel, SERIALIZE_ARRAY, SERIALIZE_SCALAR, and TableSize.
void X86ISA::I82094AA::signalInterrupt (int line) [virtual]
Reimplemented from X86ISA::IntDevice.
Definition at line 179 of file i82094aa.cc.
References X86ISA::APIC_LOGICAL_DESTINATION, DPRINTF, X86ISA::Interrupts::getInitialApicId(), System::getThreadContext(), ArmISA::i, X86ISA::IntDevice::intMasterPort, System::isTimingMode(), lowestPriorityOffset, System::numContexts(), panic, X86ISA::Interrupts::readReg(), redirTable, X86ISA::IntDevice::IntMasterPort::sendMessage(), PioDevice::sys, and TableSize.
Referenced by Pc::postConsoleInt(), Pc::postPciInt(), and raiseInterruptPin().
void X86ISA::I82094AA::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 276 of file i82094aa.cc.
References arbId, ArmISA::i, initialApicId, lowestPriorityOffset, pinStates, redirTable, regSel, TableSize, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Tick X86ISA::I82094AA::write (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 110 of file i82094aa.cc.
References Packet::get(), Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), X86ISA::offset, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, regSel, and writeReg().
void X86ISA::I82094AA::writeReg (uint8_t offset, uint32_t value)
Definition at line 129 of file i82094aa.cc.
References arbId, bits(), DPRINTF, X86ISA::index, redirTable, TableSize, and warn.
Referenced by write().
Member Data Documentation
const uint8_t X86ISA::I82094AA::APICVersion = 0x14 [static]
Definition at line 79 of file i82094aa.hh.
Referenced by readReg().
uint8_t X86ISA::I82094AA::arbId
Definition at line 72 of file i82094aa.hh.
Referenced by I82094AA(), readReg(), serialize(), unserialize(), and writeReg().
Bitfield<31, 0> X86ISA::I82094AA::bottomDW
Definition at line 53 of file i82094aa.hh.
Bitfield<31, 17> X86ISA::I82094AA::bottomReserved
Definition at line 54 of file i82094aa.hh.
Bitfield<10, 8> X86ISA::I82094AA::deliveryMode
Definition at line 62 of file i82094aa.hh.
Referenced by Pc::init().
Bitfield<12> X86ISA::I82094AA::deliveryStatus
Definition at line 60 of file i82094aa.hh.
Bitfield<63, 56> X86ISA::I82094AA::dest
Definition at line 55 of file i82094aa.hh.
Bitfield<11> X86ISA::I82094AA::destMode
Definition at line 61 of file i82094aa.hh.
uint8_t X86ISA::I82094AA::id
Definition at line 71 of file i82094aa.hh.
Referenced by I82094AA().
uint8_t X86ISA::I82094AA::initialApicId
Definition at line 70 of file i82094aa.hh.
Referenced by getIntAddrRange(), I82094AA(), serialize(), and unserialize().
uint64_t X86ISA::I82094AA::lowestPriorityOffset
Definition at line 74 of file i82094aa.hh.
Referenced by serialize(), signalInterrupt(), and unserialize().
Bitfield<16> X86ISA::I82094AA::mask
Definition at line 56 of file i82094aa.hh.
bool X86ISA::I82094AA::pinStates[TableSize]
Definition at line 82 of file i82094aa.hh.
Referenced by I82094AA(), lowerInterruptPin(), raiseInterruptPin(), serialize(), and unserialize().
Bitfield<13> X86ISA::I82094AA::polarity
Definition at line 59 of file i82094aa.hh.
RedirTableEntry X86ISA::I82094AA::redirTable[TableSize]
Definition at line 81 of file i82094aa.hh.
Referenced by I82094AA(), readReg(), serialize(), signalInterrupt(), unserialize(), and writeReg().
EndBitUnion (RedirTableEntry) protected uint8_t X86ISA::I82094AA::regSel
Definition at line 64 of file i82094aa.hh.
Referenced by I82094AA(), read(), serialize(), unserialize(), and write().
Bitfield<14> X86ISA::I82094AA::remoteIRR
Definition at line 58 of file i82094aa.hh.
const uint8_t X86ISA::I82094AA::TableSize = 24 [static]
Definition at line 76 of file i82094aa.hh.
Referenced by I82094AA(), lowerInterruptPin(), raiseInterruptPin(), readReg(), serialize(), signalInterrupt(), unserialize(), and writeReg().
X86ISA::I82094AA::topDW
Definition at line 51 of file i82094aa.hh.
Bitfield<55, 32> X86ISA::I82094AA::topReserved
Definition at line 52 of file i82094aa.hh.
Bitfield<15> X86ISA::I82094AA::trigger
Definition at line 57 of file i82094aa.hh.
Bitfield<7, 0> X86ISA::I82094AA::vector
Definition at line 63 of file i82094aa.hh.
The documentation for this class was generated from the following files:
dev/x86/i82094aa.hh
dev/x86/i82094aa.cc