gem5: Minor::ExecContext Class Reference
Minor::ExecContext Class Reference
ExecContext bears the exec_context interface for Minor.
#include <exec_context.hh>
Public Member Functions
ExecContext (MinorCPU &cpu_, SimpleThread &thread_, Execute &execute_, MinorDynInstPtr inst_)
Fault readMem (Addr addr, uint8_t *data, unsigned int size, unsigned int flags)
Fault writeMem (uint8_t *data, unsigned int size, Addr addr, unsigned int flags, uint64_t *res)
IntReg readIntRegOperand (const StaticInst *si, int idx)
Reads an integer register.
TheISA::FloatReg readFloatRegOperand (const StaticInst *si, int idx)
Reads a floating point register of single register width.
TheISA::FloatRegBits readFloatRegOperandBits (const StaticInst *si, int idx)
Reads a floating point register in its binary format, instead of by value.
void setIntRegOperand (const StaticInst *si, int idx, IntReg val)
Sets an integer register to a value.
void setFloatRegOperand (const StaticInst *si, int idx, TheISA::FloatReg val)
Sets a floating point register of single width to a value.
void setFloatRegOperandBits (const StaticInst *si, int idx, TheISA::FloatRegBits val)
Sets the bits of a floating point register of single width to a binary value.
bool readPredicate ()
void setPredicate (bool val)
TheISA::PCState pcState () const
void pcState (const TheISA::PCState &val)
TheISA::MiscReg readMiscRegNoEffect (int misc_reg) const
TheISA::MiscReg readMiscReg (int misc_reg)
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
void setMiscReg (int misc_reg, const TheISA::MiscReg &val)
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
TheISA::MiscReg readMiscRegOperand (const StaticInst *si, int idx)
void setMiscRegOperand (const StaticInst *si, int idx, const TheISA::MiscReg &val)
Fault hwrei ()
Somewhat Alpha-specific function that handles returning from an error or interrupt.
bool simPalCheck (int palFunc)
Check for special simulator handling of specific PAL calls.
void syscall (int64_t callnum)
Executes a syscall specified by the callnum.
ThreadContext * tcBase ()
Returns a pointer to the ThreadContext.
unsigned int readStCondFailures () const
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned int st_cond_failures)
Sets the number of consecutive store conditional failures.
int contextId ()
void demapPage (Addr vaddr, uint64_t asn)
Invalidate a page in the DTLB and ITLB.
TheISA::CCReg readCCRegOperand (const StaticInst *si, int idx)
void setCCRegOperand (const StaticInst *si, int idx, TheISA::CCReg val)
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
void setEA (Addr ea)
Record the effective address of the instruction.
BaseCPU * getCpuPtr ()
Addr getEA () const
Get the effective address of the instruction.
uint64_t readRegOtherThread (int idx, ThreadID tid=InvalidThreadID)
void setRegOtherThread (int idx, const TheISA::MiscReg &val, ThreadID tid=InvalidThreadID)
void armMonitor (Addr address)
bool mwait (PacketPtr pkt)
void mwaitAtomic (ThreadContext *tc)
AddressMonitor * getAddrMonitor ()
Public Attributes
MinorCPU & cpu
SimpleThread & thread
ThreadState object, provides all the architectural state.
Execute & execute
The execute stage so we can peek at its contents.
MinorDynInstPtr inst
Instruction for the benefit of memory operations and for PC.
Detailed Description
ExecContext bears the exec_context interface for Minor.
This nicely separates that interface from other classes such as Pipeline, MinorCPU and DynMinorInst and makes it easier to see what state is accessed by it.
Definition at line 73 of file exec_context.hh.
Constructor & Destructor Documentation
Minor::ExecContext::ExecContext (MinorCPU & cpu_, SimpleThread & thread_, Execute & execute_, MinorDynInstPtr inst_) [inline]
Definition at line 87 of file exec_context.hh.
References DPRINTF, inst, pcState(), SimpleThread::setFloatReg(), SimpleThread::setIntReg(), setPredicate(), thread, and AlphaISA::ZeroReg.
Member Function Documentation
void Minor::ExecContext::armMonitor (Addr address) [inline, virtual]
Implements ExecContext.
Definition at line 346 of file exec_context.hh.
References getCpuPtr().
int Minor::ExecContext::contextId () [inline]
Definition at line 257 of file exec_context.hh.
References ThreadState::contextId(), and thread.
void Minor::ExecContext::demapDataPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 289 of file exec_context.hh.
References SimpleThread::getDTBPtr(), and thread.
void Minor::ExecContext::demapInstPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 283 of file exec_context.hh.
References SimpleThread::getITBPtr(), and thread.
void Minor::ExecContext::demapPage (Addr vaddr, uint64_t asn) [inline, virtual]
Invalidate a page in the DTLB and ITLB.
Implements ExecContext.
Definition at line 262 of file exec_context.hh.
References SimpleThread::getDTBPtr(), SimpleThread::getITBPtr(), and thread.
AddressMonitor* Minor::ExecContext::getAddrMonitor () [inline, virtual]
Implements ExecContext.
Definition at line 350 of file exec_context.hh.
References getCpuPtr().
BaseCPU* Minor::ExecContext::getCpuPtr () [inline]
Definition at line 300 of file exec_context.hh.
References cpu.
Referenced by armMonitor(), getAddrMonitor(), mwait(), and mwaitAtomic().
Addr Minor::ExecContext::getEA () const [inline, virtual]
Get the effective address of the instruction.
Note:
Only valid for memory ops.
Implements ExecContext.
Definition at line 303 of file exec_context.hh.
References inst.
Fault Minor::ExecContext::hwrei () [inline, virtual]
Somewhat Alpha-specific function that handles returning from an error or interrupt.
Implements ExecContext.
Definition at line 223 of file exec_context.hh.
References SimpleThread::hwrei(), and thread.
bool Minor::ExecContext::mwait (PacketPtr pkt) [inline, virtual]
Implements ExecContext.
Definition at line 347 of file exec_context.hh.
References getCpuPtr().
void Minor::ExecContext::mwaitAtomic (ThreadContext * tc) [inline, virtual]
Implements ExecContext.
Definition at line 348 of file exec_context.hh.
References SimpleThread::dtb, getCpuPtr(), and thread.
void Minor::ExecContext::pcState (const TheISA::PCState & val) [inline, virtual]
Implements ExecContext.
Definition at line 184 of file exec_context.hh.
References SimpleThread::pcState(), and thread.
TheISA::PCState Minor::ExecContext::pcState () const [inline, virtual]
Implements ExecContext.
Definition at line 178 of file exec_context.hh.
References SimpleThread::pcState(), and thread.
Referenced by ExecContext().
TheISA::CCReg Minor::ExecContext::readCCRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 269 of file exec_context.hh.
References AlphaISA::CC_Reg_Base, SimpleThread::readCCReg(), StaticInst::srcRegIdx(), and thread.
TheISA::FloatReg Minor::ExecContext::readFloatRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register of single register width.
Implements ExecContext.
Definition at line 130 of file exec_context.hh.
References AlphaISA::FP_Reg_Base, SimpleThread::readFloatReg(), StaticInst::srcRegIdx(), and thread.
TheISA::FloatRegBits Minor::ExecContext::readFloatRegOperandBits (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 137 of file exec_context.hh.
References AlphaISA::FP_Reg_Base, SimpleThread::readFloatRegBits(), StaticInst::srcRegIdx(), and thread.
IntReg Minor::ExecContext::readIntRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads an integer register.
Implements ExecContext.
Definition at line 124 of file exec_context.hh.
References SimpleThread::readIntReg(), StaticInst::srcRegIdx(), and thread.
Fault Minor::ExecContext::readMem (Addr addr, uint8_t * data, unsigned int size, unsigned int flags) [inline, virtual]
Implements ExecContext.
Definition at line 106 of file exec_context.hh.
References execute, Minor::Execute::getLSQ(), inst, and Minor::LSQ::pushRequest().
TheISA::MiscReg Minor::ExecContext::readMiscReg (int misc_reg) [inline, virtual]
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
Implements ExecContext.
Definition at line 196 of file exec_context.hh.
References SimpleThread::readMiscReg(), and thread.
TheISA::MiscReg Minor::ExecContext::readMiscRegNoEffect (int misc_reg) const [inline]
Definition at line 190 of file exec_context.hh.
References SimpleThread::readMiscRegNoEffect(), and thread.
TheISA::MiscReg Minor::ExecContext::readMiscRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 208 of file exec_context.hh.
References AlphaISA::Misc_Reg_Base, SimpleThread::readMiscReg(), StaticInst::srcRegIdx(), and thread.
bool Minor::ExecContext::readPredicate () [inline, virtual]
Implements ExecContext.
Definition at line 166 of file exec_context.hh.
References SimpleThread::readPredicate(), and thread.
Referenced by Minor::Execute::commitInst(), Minor::Execute::executeMemRefInst(), and Minor::Execute::handleMemResponse().
uint64_t Minor::ExecContext::readRegOtherThread (int idx, ThreadID tid = InvalidThreadID) [inline, virtual]
Implements ExecContext.
Definition at line 310 of file exec_context.hh.
References cpu, AlphaISA::FP_Reg_Base, InvalidThreadID, AlphaISA::Misc_Reg_Base, SimpleThread::readFloatRegBits(), SimpleThread::readIntReg(), SimpleThread::readMiscReg(), thread, and MinorCPU::threads.
unsigned int Minor::ExecContext::readStCondFailures () const [inline, virtual]
Returns the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 254 of file exec_context.hh.
void Minor::ExecContext::setCCRegOperand (const StaticInst * si, int idx, TheISA::CCReg val) [inline, virtual]
Implements ExecContext.
Definition at line 276 of file exec_context.hh.
References AlphaISA::CC_Reg_Base, StaticInst::destRegIdx(), SimpleThread::setCCReg(), and thread.
void Minor::ExecContext::setEA (Addr EA) [inline, virtual]
Record the effective address of the instruction.
Note:
Only valid for memory ops.
Implements ExecContext.
Definition at line 295 of file exec_context.hh.
References inst.
void Minor::ExecContext::setFloatRegOperand (const StaticInst * si, int idx, TheISA::FloatReg val) [inline, virtual]
Sets a floating point register of single width to a value.
Implements ExecContext.
Definition at line 150 of file exec_context.hh.
References StaticInst::destRegIdx(), AlphaISA::FP_Reg_Base, SimpleThread::setFloatReg(), and thread.
void Minor::ExecContext::setFloatRegOperandBits (const StaticInst * si, int idx, TheISA::FloatRegBits val) [inline, virtual]
Sets the bits of a floating point register of single width to a binary value.
Implements ExecContext.
Definition at line 158 of file exec_context.hh.
References StaticInst::destRegIdx(), AlphaISA::FP_Reg_Base, SimpleThread::setFloatRegBits(), and thread.
void Minor::ExecContext::setIntRegOperand (const StaticInst * si, int idx, IntReg val) [inline, virtual]
Sets an integer register to a value.
Implements ExecContext.
Definition at line 144 of file exec_context.hh.
References StaticInst::destRegIdx(), SimpleThread::setIntReg(), and thread.
void Minor::ExecContext::setMiscReg (int misc_reg, const TheISA::MiscReg & val) [inline, virtual]
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
Implements ExecContext.
Definition at line 202 of file exec_context.hh.
References SimpleThread::setMiscReg(), and thread.
void Minor::ExecContext::setMiscRegOperand (const StaticInst * si, int idx, const TheISA::MiscReg & val) [inline, virtual]
Implements ExecContext.
Definition at line 215 of file exec_context.hh.
References StaticInst::destRegIdx(), AlphaISA::Misc_Reg_Base, SimpleThread::setMiscReg(), and thread.
void Minor::ExecContext::setPredicate (bool val) [inline, virtual]
Implements ExecContext.
Definition at line 172 of file exec_context.hh.
References SimpleThread::setPredicate(), and thread.
Referenced by ExecContext().
void Minor::ExecContext::setRegOtherThread (int idx, const TheISA::MiscReg & val, ThreadID tid = InvalidThreadID) [inline]
Definition at line 327 of file exec_context.hh.
References cpu, AlphaISA::FP_Reg_Base, InvalidThreadID, AlphaISA::Misc_Reg_Base, SimpleThread::setFloatRegBits(), SimpleThread::setIntReg(), SimpleThread::setMiscReg(), thread, and MinorCPU::threads.
void Minor::ExecContext::setStCondFailures (unsigned int sc_failures) [inline, virtual]
Sets the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 255 of file exec_context.hh.
bool Minor::ExecContext::simPalCheck (int palFunc) [inline, virtual]
Check for special simulator handling of specific PAL calls.
If return value is false, actual PAL call will be suppressed.
Implements ExecContext.
Definition at line 233 of file exec_context.hh.
References SimpleThread::simPalCheck(), and thread.
void Minor::ExecContext::syscall (int64_t callnum) [inline, virtual]
Executes a syscall specified by the callnum.
Implements ExecContext.
Definition at line 243 of file exec_context.hh.
References FullSystem, panic, SimpleThread::syscall(), and thread.
ThreadContext* Minor::ExecContext::tcBase () [inline, virtual]
Returns a pointer to the ThreadContext.
Implements ExecContext.
Definition at line 251 of file exec_context.hh.
References SimpleThread::getTC(), and thread.
Fault Minor::ExecContext::writeMem (uint8_t * data, unsigned int size, Addr addr, unsigned int flags, uint64_t * res) [inline, virtual]
Implements ExecContext.
Definition at line 115 of file exec_context.hh.
References execute, Minor::Execute::getLSQ(), inst, and Minor::LSQ::pushRequest().
Member Data Documentation
MinorCPU& Minor::ExecContext::cpu
Definition at line 76 of file exec_context.hh.
Referenced by getCpuPtr(), readRegOtherThread(), and setRegOtherThread().
Execute& Minor::ExecContext::execute
The execute stage so we can peek at its contents.
Definition at line 82 of file exec_context.hh.
Referenced by readMem(), and writeMem().
MinorDynInstPtr Minor::ExecContext::inst
Instruction for the benefit of memory operations and for PC.
Definition at line 85 of file exec_context.hh.
Referenced by ExecContext(), getEA(), readMem(), setEA(), and writeMem().
SimpleThread& Minor::ExecContext::thread
ThreadState object, provides all the architectural state.
Definition at line 79 of file exec_context.hh.
Referenced by contextId(), demapDataPage(), demapInstPage(), demapPage(), ExecContext(), hwrei(), mwaitAtomic(), pcState(), readCCRegOperand(), readFloatRegOperand(), readFloatRegOperandBits(), readIntRegOperand(), readMiscReg(), readMiscRegNoEffect(), readMiscRegOperand(), readPredicate(), readRegOtherThread(), setCCRegOperand(), setFloatRegOperand(), setFloatRegOperandBits(), setIntRegOperand(), setMiscReg(), setMiscRegOperand(), setPredicate(), setRegOtherThread(), simPalCheck(), syscall(), and tcBase().
The documentation for this class was generated from the following file:
cpu/minor/exec_context.hh