gem5: ThreadContext Class Reference
ThreadContext Class Reference
ThreadContext is the external interface to all thread state for anything outside of the CPU.
#include <thread_context.hh>
Public Types
enum Status { Active, Suspended, Halted }
Public Member Functions
virtual ~ThreadContext ()
virtual BaseCPU * getCpuPtr ()=0
virtual int cpuId () const =0
virtual uint32_t socketId () const =0
virtual int threadId () const =0
virtual void setThreadId (int id)=0
virtual int contextId () const =0
virtual void setContextId (int id)=0
virtual TheISA::TLB * getITBPtr ()=0
virtual TheISA::TLB * getDTBPtr ()=0
virtual CheckerCPU * getCheckerCpuPtr ()=0
virtual TheISA::Decoder * getDecoderPtr ()=0
virtual System * getSystemPtr ()=0
virtual
TheISA::Kernel::Statistics * getKernelStats ()=0
virtual PortProxy & getPhysProxy ()=0
virtual FSTranslatingPortProxy & getVirtProxy ()=0
virtual void initMemProxies (ThreadContext *tc)=0
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
virtual SETranslatingPortProxy & getMemProxy ()=0
virtual Process * getProcessPtr ()=0
virtual Status status () const =0
virtual void setStatus (Status new_status)=0
virtual void activate ()=0
Set the status to Active.
virtual void suspend ()=0
Set the status to Suspended.
virtual void halt ()=0
Set the status to Halted.
virtual void dumpFuncProfile ()=0
virtual void takeOverFrom (ThreadContext *old_context)=0
virtual void regStats (const std::string &name)=0
virtual EndQuiesceEvent * getQuiesceEvent ()=0
virtual Tick readLastActivate ()=0
virtual Tick readLastSuspend ()=0
virtual void profileClear ()=0
virtual void profileSample ()=0
virtual void copyArchRegs (ThreadContext *tc)=0
virtual void clearArchRegs ()=0
virtual uint64_t readIntReg (int reg_idx)=0
virtual FloatReg readFloatReg (int reg_idx)=0
virtual FloatRegBits readFloatRegBits (int reg_idx)=0
virtual CCReg readCCReg (int reg_idx)=0
virtual void setIntReg (int reg_idx, uint64_t val)=0
virtual void setFloatReg (int reg_idx, FloatReg val)=0
virtual void setFloatRegBits (int reg_idx, FloatRegBits val)=0
virtual void setCCReg (int reg_idx, CCReg val)=0
virtual TheISA::PCState pcState ()=0
virtual void pcState (const TheISA::PCState &val)=0
virtual void pcStateNoRecord (const TheISA::PCState &val)=0
virtual Addr instAddr ()=0
virtual Addr nextInstAddr ()=0
virtual MicroPC microPC ()=0
virtual MiscReg readMiscRegNoEffect (int misc_reg) const =0
virtual MiscReg readMiscReg (int misc_reg)=0
virtual void setMiscRegNoEffect (int misc_reg, const MiscReg &val)=0
virtual void setMiscReg (int misc_reg, const MiscReg &val)=0
virtual int flattenIntIndex (int reg)=0
virtual int flattenFloatIndex (int reg)=0
virtual int flattenCCIndex (int reg)=0
virtual int flattenMiscIndex (int reg)=0
virtual uint64_t readRegOtherThread (int misc_reg, ThreadID tid)
virtual void setRegOtherThread (int misc_reg, const MiscReg &val, ThreadID tid)
virtual unsigned readStCondFailures ()=0
virtual void setStCondFailures (unsigned sc_failures)=0
virtual Counter readFuncExeInst ()=0
virtual void syscall (int64_t callnum)=0
virtual int exit ()
virtual uint64_t readIntRegFlat (int idx)=0
Flat register interfaces.
virtual void setIntRegFlat (int idx, uint64_t val)=0
virtual FloatReg readFloatRegFlat (int idx)=0
virtual void setFloatRegFlat (int idx, FloatReg val)=0
virtual FloatRegBits readFloatRegBitsFlat (int idx)=0
virtual void setFloatRegBitsFlat (int idx, FloatRegBits val)=0
virtual CCReg readCCRegFlat (int idx)=0
virtual void setCCRegFlat (int idx, CCReg val)=0
Static Public Member Functions
static void compare (ThreadContext *one, ThreadContext *two)
function to compare two thread contexts (for debugging)
Protected Types
typedef TheISA::MachInst MachInst
typedef TheISA::IntReg IntReg
typedef TheISA::FloatReg FloatReg
typedef TheISA::FloatRegBits FloatRegBits
typedef TheISA::CCReg CCReg
typedef TheISA::MiscReg MiscReg
Detailed Description
ThreadContext is the external interface to all thread state for anything outside of the CPU.
It provides all accessor methods to state that might be needed by external objects, ranging from register values to things such as kernel stats. It is an abstract base class; the CPU can create its own ThreadContext by either deriving from it, or using the templated ProxyThreadContext.
The ThreadContext is slightly different than the ExecContext. The ThreadContext provides access to an individual thread's state; an ExecContext provides ISA access to the CPU (meaning it is implicitly multithreaded on SMT systems). Additionally the ThreadState is an abstract class that exactly defines the interface; the ExecContext is a more implicit interface that must be implemented so that the ISA can access whatever state it needs.
Definition at line 93 of file thread_context.hh.
Member Typedef Documentation
typedef TheISA::CCReg ThreadContext::CCReg [protected]
Definition at line 100 of file thread_context.hh.
typedef TheISA::FloatReg ThreadContext::FloatReg [protected]
Definition at line 98 of file thread_context.hh.
typedef TheISA::FloatRegBits ThreadContext::FloatRegBits [protected]
Definition at line 99 of file thread_context.hh.
typedef TheISA::IntReg ThreadContext::IntReg [protected]
Definition at line 97 of file thread_context.hh.
typedef TheISA::MachInst ThreadContext::MachInst [protected]
Definition at line 96 of file thread_context.hh.
typedef TheISA::MiscReg ThreadContext::MiscReg [protected]
Definition at line 101 of file thread_context.hh.
Member Enumeration Documentation
enum ThreadContext::Status
Enumerator:
Active
Running.
Instructions should be executed only when the context is in this state.
Suspended
Temporarily inactive.
Entered while waiting for synchronization, etc.
Halted
Permanently shut down.
Entered when target executes m5exit pseudo-instruction. When all contexts enter this state, the simulation will terminate.
Definition at line 104 of file thread_context.hh.
Constructor & Destructor Documentation
virtual ThreadContext::~ThreadContext () [inline, virtual]
Definition at line 120 of file thread_context.hh.
Member Function Documentation
virtual void ThreadContext::activate () [pure virtual]
Set the status to Active.
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Tru64::activate_waiting_context(), cloneFunc(), Tru64::init_thread_context(), Process::initState(), EndQuiesceEvent::process(), SparcISA::startupCPU(), PowerISA::startupCPU(), ArmISA::startupCPU(), and AlphaISA::startupCPU().
virtual void ThreadContext::clearArchRegs () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by cloneFunc(), Tru64::init_thread_context(), and ArmISA::Reset::invoke().
void ThreadContext::compare (ThreadContext * one, ThreadContext * two) [static]
function to compare two thread contexts (for debugging)
Definition at line 54 of file thread_context.cc.
References contextId(), cpuId(), DPRINTF, ArmISA::i, AlphaISA::NumCCRegs, AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, AlphaISA::NumMiscRegs, panic, pcState(), readCCReg(), readFloatRegBits(), readIntReg(), readMiscRegNoEffect(), ArmISA::t1, and ArmISA::t2.
virtual int ThreadContext::contextId () const [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by compare(), SimpleThread::copyState(), BaseKvmCPU::doMMIOAccess(), X86ISA::TLB::finalizePhysical(), X86KvmCPU::handleKvmExitIO(), AtomicSimpleCPU::init(), FullO3CPU< Impl >::init(), BaseKvmCPU::init(), SparcISA::ISA::readFSReg(), CheckerCPU::readMem(), takeOverFrom(), and CheckerCPU::writeMem().
virtual void ThreadContext::copyArchRegs (ThreadContext * tc) [pure virtual]
Referenced by takeOverFrom().
virtual int ThreadContext::cpuId () const [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by compare(), DumpStatsPCEvent::process(), and Trace::InstPBTrace::traceInst().
virtual void ThreadContext::dumpFuncProfile () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual int ThreadContext::exit () [inline, virtual]
Definition at line 266 of file thread_context.hh.
virtual int ThreadContext::flattenCCIndex (int reg) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Minor::flattenRegIndex(), DefaultRename< Impl >::renameDestRegs(), and DefaultRename< Impl >::renameSrcRegs().
virtual int ThreadContext::flattenFloatIndex (int reg) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Minor::flattenRegIndex(), DefaultRename< Impl >::renameDestRegs(), and DefaultRename< Impl >::renameSrcRegs().
virtual int ThreadContext::flattenIntIndex (int reg) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Minor::flattenRegIndex(), DefaultRename< Impl >::renameDestRegs(), and DefaultRename< Impl >::renameSrcRegs().
virtual int ThreadContext::flattenMiscIndex (int reg) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual CheckerCPU* ThreadContext::getCheckerCpuPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual BaseCPU* ThreadContext::getCpuPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by AbstractMemory::checkLockedAddrList(), SparcISA::ISA::checkSoftInt(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), SyscallDesc::doSyscall(), ArmISA::TableWalker::fetchDescriptor(), ArmISA::Stage2MMU::Stage2Translation::finish(), BaseRemoteGDB::getComInstEventQueue(), ArmISA::ArmSev::invoke(), ArmISA::SystemError::invoke(), ArmISA::AbortFault< T >::invoke(), ArmISA::Reset::invoke(), Tru64::nxm_blockFunc(), Tru64::nxm_thread_blockFunc(), Tru64::nxm_unblockFunc(), BadAddrEvent::process(), EndQuiesceEvent::process(), PanicPCEvent::process(), BreakPCEvent::process(), DumpStatsPCEvent::process(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), ArmISA::TableWalker::processWalkAArch64(), AlphaISA::ISA::readIpr(), X86ISA::ISA::readMiscReg(), SparcISA::ISA::readMiscReg(), SparcISA::ISA::serialize(), LinuxAlphaSystem::setDelayLoop(), SparcISA::ISA::setFSReg(), X86ISA::ISA::setMiscReg(), SparcISA::ISA::setMiscReg(), MipsISA::ISA::setMiscReg(), LinuxArmSystem::startup(), takeOverFrom(), and Trace::ExeTracerRecord::traceInst().
virtual TheISA::Decoder* ThreadContext::getDecoderPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Minor::Fetch2::evaluate(), SparcISA::ISA::setMiscReg(), X86ISA::ISA::startup(), SimpleThread::takeOverFrom(), O3ThreadContext< Impl >::takeOverFrom(), and X86ISA::ISA::updateHandyM5Reg().
virtual TheISA::TLB* ThreadContext::getDTBPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by X86ISA::RemoteGDB::acc(), BaseKvmCPU::doMMIOAccess(), SparcISA::handleIprRead(), SparcISA::handleIprWrite(), SparcISA::FastDataAccessMMUMiss::invoke(), AlphaISA::NDtbMissFault::invoke(), AlphaISA::ISA::readIpr(), Minor::LSQ::SplitDataRequest::sendNextFragmentToTranslation(), AlphaISA::ISA::setIpr(), X86ISA::ISA::setMiscReg(), Minor::LSQ::SingleDataRequest::startAddrTranslation(), and try_translate().
virtual TheISA::TLB* ThreadContext::getITBPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), SparcISA::TLB::GetTsbPtr(), SparcISA::FastInstructionAccessMMUMiss::invoke(), AlphaISA::ItbPageFault::invoke(), AlphaISA::ISA::setIpr(), X86ISA::ISA::setMiscReg(), and try_translate().
virtual TheISA::Kernel::Statistics* ThreadContext::getKernelStats () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by IdleStartEvent::process(), SparcISA::ISA::setFSReg(), AlphaISA::ISA::setIpr(), SimpleThread::takeOverFrom(), and O3ThreadContext< Impl >::takeOverFrom().
virtual SETranslatingPortProxy& ThreadContext::getMemProxy () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by _llseekFunc(), accessFunc(), archPrctlFunc(), brkFunc(), chmodFunc(), chownFunc(), clock_gettimeFunc(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), fstat64Func(), fstatat64Func(), fstatfsFunc(), fstatFunc(), futexFunc(), getcwdFunc(), Tru64::getdirentriesFunc(), gethostnameFunc(), SparcISA::getresuidFunc(), getrlimitFunc(), getrusageFunc(), getsysinfoFunc(), gettimeofdayFunc(), ArmLinuxProcess32::initState(), lstat64Func(), lstatFunc(), Tru64::m5_cond_waitFunc(), Tru64::m5_lock_mutex(), Tru64::m5_mutex_trylockFunc(), Tru64::m5_unlock_mutex(), mkdirFunc(), Tru64::nxm_task_initFunc(), Tru64::nxm_thread_createFunc(), openFunc(), osf_getsysinfoFunc(), osf_setsysinfoFunc(), BaseRemoteGDB::read(), readFunc(), readlinkFunc(), renameatFunc(), renameFunc(), setThreadArea32Func(), setTLSFunc32(), Tru64::sigreturnFunc(), Tru64::stack_createFunc(), stat64Func(), statfsFunc(), statFunc(), sys_getsysinfoFunc(), sys_setsysinfoFunc(), sysctlFunc(), sysinfoFunc(), tableFunc(), timeFunc(), timesFunc(), truncate64Func(), truncateFunc(), SparcISA::unameFunc(), unameFunc(), unameFunc32(), unameFunc64(), unlinkHelper(), utimesFunc(), BaseRemoteGDB::write(), writeFunc(), and writevFunc().
virtual PortProxy& ThreadContext::getPhysProxy () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by AlphaISA::RemoteGDB::acc(), and Linux::ThreadInfo::curThreadInfo().
virtual Process* ThreadContext::getProcessPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by X86ISA::RemoteGDB::acc(), SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), GenericPageTableFault::invoke(), SparcISA::TrapInstruction::invoke(), SparcISA::FillNNormal::invoke(), SparcISA::SpillNNormal::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), AlphaISA::NDtbMissFault::invoke(), AlphaISA::ItbPageFault::invoke(), takeOverFrom(), X86ISA::TLB::translate(), GenericTLB::translateAtomic(), PowerISA::TLB::translateData(), MipsISA::TLB::translateData(), PowerISA::TLB::translateInst(), MipsISA::TLB::translateInst(), and ArmISA::TLB::translateSe().
virtual EndQuiesceEvent* ThreadContext::getQuiesceEvent () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by takeOverFrom().
virtual System* ThreadContext::getSystemPtr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by SparcISA::TLB::doMmuRegWrite(), futexFunc(), ArmSystem::haveLargeAsid64(), ArmSystem::haveLPAE(), ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), ArmSystem::highestEL(), ArmSystem::highestELIs64(), X86System::initState(), ArmISA::Reset::invoke(), ArmSystem::physAddrMask(), ArmSystem::physAddrRange(), DebugPrintfEvent::process(), PrintfEvent::process(), Linux::DebugPrintkEvent::process(), LinuxMipsSystem::SkipDelayLoopEvent::process(), DumpStatsPCEvent::process(), LinuxAlphaSystem::SkipDelayLoopEvent::process(), FreebsdAlphaSystem::SkipCalibrateClocksEvent::process(), X86ISA::ProcessInfo::ProcessInfo(), ArmISA::ProcessInfo::ProcessInfo(), AlphaISA::ProcessInfo::ProcessInfo(), SparcISA::ISA::readFSReg(), ArmSystem::resetAddr64(), takeOverFrom(), and AlphaISA::StackTrace::trace().
virtual FSTranslatingPortProxy& ThreadContext::getVirtProxy () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by CopyIn(), CopyOut(), CopyStringIn(), CopyStringOut(), X86ISA::ProcessInfo::pid(), MipsISA::ProcessInfo::pid(), ArmISA::ProcessInfo::pid(), AlphaISA::ProcessInfo::pid(), X86ISA::ProcessInfo::ProcessInfo(), ArmISA::ProcessInfo::ProcessInfo(), AlphaISA::ProcessInfo::ProcessInfo(), BaseRemoteGDB::read(), VPtr< T >::refresh(), LinuxAlphaSystem::setDelayLoop(), X86ISA::ProcessInfo::task(), MipsISA::ProcessInfo::task(), ArmISA::ProcessInfo::task(), AlphaISA::ProcessInfo::task(), and BaseRemoteGDB::write().
virtual void ThreadContext::halt () [pure virtual]
Set the status to Halted.
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by exitFunc(), exitGroupFunc(), and Tru64::m5_thread_exitFunc().
virtual void ThreadContext::initMemProxies (ThreadContext * tc) [pure virtual]
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
tc ThreadContext for the virtual-to-physical translation
Referenced by TimingSimpleCPU::init(), AtomicSimpleCPU::init(), MinorCPU::init(), and BaseKvmCPU::init().
virtual Addr ThreadContext::instAddr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by PCEventQueue::doService(), X86ISA::TLB::translate(), Minor::Execute::tryPCEvents(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCore(), and X86KvmCPU::updateKvmStateRegs().
virtual MicroPC ThreadContext::microPC () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual Addr ThreadContext::nextInstAddr () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Trace::ArmNativeTrace::check(), cloneFunc(), DefaultCommit< Impl >::commitHead(), and BaseSimpleCPU::postExecute().
virtual void ThreadContext::pcState (const TheISA::PCState & val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual TheISA::PCState ThreadContext::pcState () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by X86ISA::X86LiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), Trace::SparcNativeTrace::check(), AlphaISA::Interrupts::checkInterrupts(), cloneFunc(), Minor::Execute::commit(), compare(), Minor::Execute::executeMemRefInst(), X86ISA::RemoteGDB::getregs(), SparcISA::RemoteGDB::getregs(), MipsISA::RemoteGDB::getregs(), ArmISA::RemoteGDB::getregs(), AlphaISA::RemoteGDB::getregs(), SparcLiveProcess::handleTrap(), Tru64::init_thread_context(), X86System::initState(), FullO3CPU< Impl >::insertThread(), MipsISA::TlbFault< TlbInvalidFault >::invoke(), ReExec::invoke(), FaultBase::invoke(), X86ISA::StartupInterrupt::invoke(), X86ISA::InitInterrupt::invoke(), X86ISA::X86Trap::invoke(), X86ISA::X86FaultBase::invoke(), SparcISA::TrapInstruction::invoke(), SparcISA::FillNNormal::invoke(), SparcISA::SpillNNormal::invoke(), SparcISA::PowerOnReset::invoke(), SparcISA::SparcFaultBase::invoke(), MipsISA::ResetFault::invoke(), MipsISA::MipsFaultBase::invoke(), ArmISA::FlushPipe::invoke(), ArmISA::SupervisorCall::invoke(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke(), AlphaISA::AlphaFault::invoke(), ArmISA::ArmFault::invoke64(), ioctlFunc(), BaseSimpleCPU::postExecute(), SkipFuncEvent::process(), serialize(), MipsISA::MipsFaultBase::setExceptionState(), X86ISA::RemoteGDB::setregs(), SparcISA::RemoteGDB::setregs(), MipsISA::RemoteGDB::setregs(), ArmISA::RemoteGDB::setregs(), AlphaISA::RemoteGDB::setregs(), Tru64::sigreturnFunc(), X86ISA::I386LiveProcess::syscall(), AlphaISA::StackTrace::trace(), BaseRemoteGDB::trap(), Minor::Execute::tryPCEvents(), Minor::Execute::tryToBranch(), unserialize(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), ArmKvmCPU::updateTCStateCore(), ArmV8KvmCPU::updateThreadContext(), and X86KvmCPU::updateThreadContextRegs().
virtual void ThreadContext::pcStateNoRecord (const TheISA::PCState & val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual void ThreadContext::profileClear () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual void ThreadContext::profileSample () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual CCReg ThreadContext::readCCReg (int reg_idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by compare(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), and Trace::ArmNativeTrace::ThreadState::update().
virtual CCReg ThreadContext::readCCRegFlat (int idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by serialize().
virtual FloatReg ThreadContext::readFloatReg (int reg_idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by updateKvmStateFPUCommon().
virtual FloatRegBits ThreadContext::readFloatRegBits (int reg_idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by compare(), MipsISA::RemoteGDB::getregs(), ArmISA::RemoteGDB::getregs(), AlphaISA::RemoteGDB::getregs(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), ArmV8KvmCPU::updateKvmState(), and updateKvmStateFPUCommon().
virtual FloatRegBits ThreadContext::readFloatRegBitsFlat (int idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by serialize(), and ArmKvmCPU::updateKvmStateVFP().
virtual FloatReg ThreadContext::readFloatRegFlat (int idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual Counter ThreadContext::readFuncExeInst () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by O3ThreadContext< Impl >::copyArchRegs(), SimpleThread::copyState(), SimpleThread::takeOverFrom(), and O3ThreadContext< Impl >::takeOverFrom().
virtual uint64_t ThreadContext::readIntReg (int reg_idx) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by PowerISA::BranchRegCond::branchTarget(), AlphaISA::Kernel::Statistics::callpal(), Trace::SparcNativeTrace::check(), cloneFunc(), compare(), FreebsdAlphaSystem::doCalibrateClocks(), TimingExprReadIntReg::eval(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), X86ISA::RemoteGDB::getregs(), SparcISA::RemoteGDB::getregs(), MipsISA::RemoteGDB::getregs(), ArmISA::RemoteGDB::getregs(), AlphaISA::RemoteGDB::getregs(), X86ISA::I386LiveProcess::getSyscallArg(), X86ISA::X86_64LiveProcess::getSyscallArg(), Sparc64LiveProcess::getSyscallArg(), Sparc32LiveProcess::getSyscallArg(), PowerLiveProcess::getSyscallArg(), PowerLinuxProcess::getSyscallArg(), MipsLiveProcess::getSyscallArg(), ArmLiveProcess64::getSyscallArg(), ArmLiveProcess32::getSyscallArg(), AlphaLiveProcess::getSyscallArg(), SparcISA::Sparc64LinuxProcess::handleTrap(), SparcISA::Sparc32LinuxProcess::handleTrap(), ArmISA::SupervisorCall::invoke(), ArmISA::ArmFault::invoke(), BadAddrEvent::process(), DumpStatsPCEvent::process(), SparcLiveProcess::setSyscallReturn(), PowerLiveProcess::setSyscallReturn(), AlphaISA::StackTrace::trace(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), and ArmV8KvmCPU::updateKvmState().
virtual uint64_t ThreadContext::readIntRegFlat (int idx) [pure virtual]
Flat register interfaces.
Some architectures have different registers visible in different modes. Such architectures "flatten" a register (see flattenIntIndex() and flattenFloatIndex()) to map it into the gem5 register file. This interface provides a flat interface to the underlying register file, which allows for example serialization code to access all registers.
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by ArmKvmCPU::onKvmExitHypercall(), serialize(), and ArmKvmCPU::updateKvmStateCore().
virtual Tick ThreadContext::readLastActivate () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual Tick ThreadContext::readLastSuspend () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual MiscReg ThreadContext::readMiscReg (int misc_reg) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by MipsISA::MipsFaultBase::base(), ArmISA::Interrupts::checkInterrupts(), ArmISA::currEL(), ArmISA::currOpMode(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), ArmKvmCPU::dumpKvmStateCoProc(), ArmISA::DataAbort::ec(), ArmISA::PrefetchAbort::ec(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), ArmISA::getExecutingAsid(), ArmISA::Interrupts::getInterrupt(), SparcISA::RemoteGDB::getregs(), ArmISA::ArmFault::getVector(), ArmISA::ArmFault::getVector64(), X86ISA::handleIprRead(), ArmLiveProcess64::initState(), ArmLiveProcess32::initState(), MipsISA::inUserMode(), MipsISA::CoprocessorUnusableFault::invoke(), X86ISA::StartupInterrupt::invoke(), X86ISA::InitInterrupt::invoke(), ArmISA::AbortFault< T >::invoke(), ArmISA::SupervisorCall::invoke(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), X86KvmCPU::kvmRunWrapper(), ArmISA::TableWalker::memAttrs(), ArmISA::TableWalker::memAttrsAArch64(), ArmISA::TableWalker::memAttrsLPAE(), MipsISA::TlbRefillFault::offset(), ArmISA::ArmFaultVals< T >::offset(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), MipsISA::MipsFaultBase::setExceptionState(), MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState(), ArmISA::Interrupts::takeInt(), Trace::ArmNativeTrace::ThreadState::update(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCore(), updateKvmStateFPUCommon(), X86KvmCPU::updateKvmStateMSRs(), X86KvmCPU::updateKvmStateRegs(), X86KvmCPU::updateKvmStateSRegs(), ArmKvmCPU::updateKvmStateVFP(), ArmISA::TLB::updateMiscReg(), and ArmISA::TableWalker::walk().
virtual MiscReg ThreadContext::readMiscRegNoEffect (int misc_reg) const [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by ArmISA::FastInterrupt::abortDisable(), ArmISA::Interrupt::abortDisable(), ArmISA::AbortFault< T >::abortDisable(), AlphaISA::RemoteGDB::acc(), archPrctlFunc(), X86ISA::Interrupts::checkInterrupts(), compare(), Linux::ThreadInfo::curThreadInfo(), ArmKvmCPU::dumpKvmStateCoProc(), X86ISA::TLB::finalizePhysical(), ArmISA::FastInterrupt::fiqDisable(), MipsISA::getCauseIP(), SparcISA::getExecutingAsid(), AlphaISA::getExecutingAsid(), ArmISA::AbortFault< T >::getFsr(), SparcISA::Interrupts::getInterrupt(), AlphaISA::Interrupts::getInterrupt(), MipsISA::Interrupts::getInterrupt(), X86ISA::RemoteGDB::getregs(), MipsISA::RemoteGDB::getregs(), ArmISA::RemoteGDB::getregs(), ArmISA::ArmFault::getVector(), X86KvmCPU::handleIOMiscReg32(), X86ISA::handleIprWrite(), X86KvmCPU::handleKvmExitIO(), X86System::initState(), MipsISA::Interrupts::interruptsPending(), X86ISA::inUserMode(), SparcISA::inUserMode(), ArmISA::inUserMode(), AlphaISA::inUserMode(), X86ISA::PageFault::invoke(), X86ISA::X86FaultBase::invoke(), SparcISA::PowerOnReset::invoke(), SparcISA::SparcFaultBase::invoke(), MipsISA::ResetFault::invoke(), ArmISA::VirtualDataAbort::invoke(), ArmISA::ArmFault::invoke(), AlphaISA::ItbFault::invoke(), AlphaISA::DtbFault::invoke(), AlphaISA::AlphaFault::invoke(), AlphaISA::StackTrace::isEntry(), AlphaISA::Kernel::Statistics::mode(), Tru64::nxm_task_initFunc(), MipsISA::InterruptFault::offset(), MipsISA::Interrupts::onCpuTimerInterrupt(), X86ISA::Walker::WalkerState::pageFault(), IdleStartEvent::process(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), ArmISA::SystemError::routeToHyp(), ArmISA::FastInterrupt::routeToHyp(), ArmISA::Interrupt::routeToHyp(), ArmISA::DataAbort::routeToHyp(), ArmISA::PrefetchAbort::routeToHyp(), ArmISA::SupervisorCall::routeToHyp(), ArmISA::UndefinedInstruction::routeToHyp(), ArmISA::SystemError::routeToMonitor(), ArmISA::FastInterrupt::routeToMonitor(), ArmISA::Interrupt::routeToMonitor(), ArmISA::DataAbort::routeToMonitor(), ArmISA::PrefetchAbort::routeToMonitor(), MipsISA::setCauseIP(), setKvmDTableReg(), setKvmSegmentReg(), X86ISA::RemoteGDB::setregs(), SparcLiveProcess::setSyscallReturn(), X86ISA::Walker::WalkerState::setupWalk(), AlphaISA::StackTrace::trace(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), AlphaISA::TLB::translateData(), SparcISA::TLB::translateInst(), AlphaISA::TLB::translateInst(), X86ISA::TLB::translateInt(), Trace::ArmNativeTrace::ThreadState::update(), ArmKvmCPU::updateKvmStateCoProc(), updateKvmStateFPUCommon(), X86KvmCPU::updateKvmStateFPULegacy(), X86KvmCPU::updateKvmStateFPUXSave(), ArmKvmCPU::updateTCStateCore(), and ArmV8KvmCPU::updateThreadContext().
virtual uint64_t ThreadContext::readRegOtherThread (int misc_reg, ThreadID tid) [inline, virtual]
Definition at line 242 of file thread_context.hh.
virtual unsigned ThreadContext::readStCondFailures () [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual void ThreadContext::regStats (const std::string & name) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual void ThreadContext::setCCReg (int reg_idx, CCReg val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by ArmLiveProcess64::setSyscallReturn(), and ArmLiveProcess32::setSyscallReturn().
virtual void ThreadContext::setCCRegFlat (int idx, CCReg val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by unserialize().
virtual void ThreadContext::setContextId (int id) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by takeOverFrom().
virtual void ThreadContext::setFloatReg (int reg_idx, FloatReg val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by updateThreadContextFPUCommon().
virtual void ThreadContext::setFloatRegBits (int reg_idx, FloatRegBits val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by MipsISA::RemoteGDB::setregs(), ArmISA::RemoteGDB::setregs(), AlphaISA::RemoteGDB::setregs(), Tru64::sigreturnFunc(), ArmV8KvmCPU::updateThreadContext(), and updateThreadContextFPUCommon().
virtual void ThreadContext::setFloatRegBitsFlat (int idx, FloatRegBits val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by unserialize(), and ArmKvmCPU::updateTCStateVFP().
virtual void ThreadContext::setFloatRegFlat (int idx, FloatReg val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual void ThreadContext::setIntReg (int reg_idx, uint64_t val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), cloneFunc(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), getgidPseudoFunc(), getpidFunc(), getpidPseudoFunc(), getuidPseudoFunc(), Tru64::init_thread_context(), SparcLiveProcess::initState(), AlphaLiveProcess::initState(), X86ISA::InitInterrupt::invoke(), X86ISA::X86FaultBase::invoke(), ArmISA::ArmFault::invoke(), pipePseudoFunc(), BadAddrEvent::process(), X86ISA::RemoteGDB::setregs(), SparcISA::RemoteGDB::setregs(), MipsISA::RemoteGDB::setregs(), ArmISA::RemoteGDB::setregs(), AlphaISA::RemoteGDB::setregs(), X86ISA::I386LiveProcess::setSyscallArg(), X86ISA::X86_64LiveProcess::setSyscallArg(), PowerLiveProcess::setSyscallArg(), PowerLinuxProcess::setSyscallArg(), MipsLiveProcess::setSyscallArg(), ArmLiveProcess64::setSyscallArg(), ArmLiveProcess32::setSyscallArg(), AlphaLiveProcess::setSyscallArg(), X86ISA::X86LiveProcess::setSyscallReturn(), SparcLiveProcess::setSyscallReturn(), PowerLiveProcess::setSyscallReturn(), MipsLiveProcess::setSyscallReturn(), ArmLiveProcess64::setSyscallReturn(), ArmLiveProcess32::setSyscallReturn(), AlphaLiveProcess::setSyscallReturn(), Tru64::sigreturnFunc(), and ArmV8KvmCPU::updateThreadContext().
virtual void ThreadContext::setIntRegFlat (int idx, uint64_t val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by unserialize(), and ArmKvmCPU::updateTCStateCore().
virtual void ThreadContext::setMiscReg (int misc_reg, const MiscReg & val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by cloneFunc(), SparcISA::TLB::doMmuRegWrite(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), X86KvmCPU::handleIOMiscReg32(), X86ISA::handleIprWrite(), X86ISA::I386LiveProcess::initState(), X86ISA::X86_64LiveProcess::initState(), Sparc64LiveProcess::initState(), Sparc32LiveProcess::initState(), SparcLiveProcess::initState(), ArmLiveProcess64::initState(), ArmLiveProcess32::initState(), X86System::initState(), X86ISA::installSegDesc(), X86ISA::StartupInterrupt::invoke(), X86ISA::InitInterrupt::invoke(), X86ISA::PageFault::invoke(), SparcISA::PowerOnReset::invoke(), MipsISA::ResetFault::invoke(), ArmISA::ArmSev::invoke(), ArmISA::PCAlignmentFault::invoke(), ArmISA::AbortFault< T >::invoke(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), X86KvmCPU::kvmRunWrapper(), setContextSegment(), X86ISA::RemoteGDB::setregs(), ArmISA::RemoteGDB::setregs(), ArmISA::ArmFault::setSyndrome(), setTLSFunc32(), setTLSFunc64(), ArmKvmCPU::updateTCStateCore(), ArmKvmCPU::updateTCStateVFP(), X86KvmCPU::updateThreadContext(), and X86KvmCPU::updateThreadContextMSRs().
virtual void ThreadContext::setMiscRegNoEffect (int misc_reg, const MiscReg & val) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by archPrctlFunc(), cloneFunc(), Tru64::init_thread_context(), X86ISA::I386LiveProcess::initState(), X86ISA::X86_64LiveProcess::initState(), SparcLiveProcess::initState(), AlphaLiveProcess::initState(), MipsISA::AddressFault< TlbInvalidFault >::invoke(), MipsISA::CoprocessorUnusableFault::invoke(), SparcISA::PowerOnReset::invoke(), ArmISA::VirtualDataAbort::invoke(), ArmISA::ArmFault::invoke(), AlphaISA::ItbFault::invoke(), AlphaISA::DtbFault::invoke(), AlphaISA::AlphaFault::invoke(), MipsISA::setCauseIP(), MipsISA::MipsFaultBase::setExceptionState(), MipsISA::RemoteGDB::setregs(), ArmISA::RemoteGDB::setregs(), setThreadAreaFunc(), MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState(), AlphaLiveProcess::setupASNReg(), Tru64::sigreturnFunc(), AlphaISA::Interrupts::updateIntrInfo(), ArmKvmCPU::updateTCStateCoProc(), ArmKvmCPU::updateTCStateCore(), ArmV8KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContextFPU(), updateThreadContextFPUCommon(), and X86KvmCPU::updateThreadContextXSave().
virtual void ThreadContext::setRegOtherThread (int misc_reg, const MiscReg & val, ThreadID tid) [inline, virtual]
Definition at line 248 of file thread_context.hh.
virtual void ThreadContext::setStatus (Status new_status) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by FullO3CPU< Impl >::insertThread(), and takeOverFrom().
virtual void ThreadContext::setStCondFailures (unsigned sc_failures) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual void ThreadContext::setThreadId (int id) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by takeOverFrom().
virtual uint32_t ThreadContext::socketId () const [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
virtual Status ThreadContext::status () const [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by Tru64::activate_waiting_context(), Minor::Execute::commitInst(), SimpleThread::copyState(), BaseKvmCPU::drainResume(), Process::findFreeContext(), Tru64::m5_thread_exitFunc(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), takeOverFrom(), and Minor::Execute::tryToBranch().
virtual void ThreadContext::suspend () [pure virtual]
Set the status to Suspended.
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by futexFunc(), Tru64::m5_cond_waitFunc(), Tru64::m5_lock_mutex(), and SparcISA::ISA::setFSReg().
virtual void ThreadContext::syscall (int64_t callnum) [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by SparcISA::Sparc64LinuxProcess::handleTrap(), SparcISA::Sparc32LinuxProcess::handleTrap(), and ArmISA::SupervisorCall::invoke().
virtual void ThreadContext::takeOverFrom (ThreadContext * old_context) [pure virtual]
virtual int ThreadContext::threadId () const [pure virtual]
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, ProxyThreadContext< TC >, and ProxyThreadContext< SimpleThread >.
Referenced by SimpleThread::copyState(), BaseRemoteGDB::getComInstEventQueue(), takeOverFrom(), and Trace::ExeTracerRecord::traceInst().
The documentation for this class was generated from the following files:
cpu/thread_context.hh
cpu/thread_context.cc