gem5: ReusabilityProfiler::BlockSample Class Reference
ReusabilityProfiler::BlockSample Class Reference
Public Member Functions
BlockSample (Addr _addr, ReusabilityProfiler *_bs)
void sample_as_reusable ()
void sample_as_dead ()
void reset ()
void finalize ()
Public Attributes
Addr addr
Tick insert_tick
Tick previous_tick
unsigned reuse_count
ReusabilityProfiler * bs
Detailed Description
Definition at line 56 of file reusability.hh.
Constructor & Destructor Documentation
ReusabilityProfiler::BlockSample::BlockSample (Addr _addr, ReusabilityProfiler * _bs) [inline]
Definition at line 64 of file reusability.hh.
References addr, bs, curTick(), insert_tick, previous_tick, and reuse_count.
Member Function Documentation
void ReusabilityProfiler::BlockSample::finalize () [inline]
Definition at line 88 of file reusability.hh.
References sample_as_dead().
void ReusabilityProfiler::BlockSample::reset () [inline]
Definition at line 84 of file reusability.hh.
References curTick(), and previous_tick.
void ReusabilityProfiler::BlockSample::sample_as_dead () [inline]
Definition at line 77 of file reusability.hh.
References bs, curTick(), ReusabilityProfiler::distAllTick, ReusabilityProfiler::distDeadTick, previous_tick, and reuse_count.
Referenced by finalize().
void ReusabilityProfiler::BlockSample::sample_as_reusable () [inline]
Definition at line 69 of file reusability.hh.
References bs, curTick(), ReusabilityProfiler::distAllTick, ReusabilityProfiler::distReusableTick, previous_tick, and reuse_count.
Member Data Documentation
Addr ReusabilityProfiler::BlockSample::addr
Definition at line 58 of file reusability.hh.
Referenced by BlockSample().
ReusabilityProfiler* ReusabilityProfiler::BlockSample::bs
Definition at line 62 of file reusability.hh.
Referenced by BlockSample(), sample_as_dead(), and sample_as_reusable().
Tick ReusabilityProfiler::BlockSample::insert_tick
Definition at line 59 of file reusability.hh.
Referenced by BlockSample().
Tick ReusabilityProfiler::BlockSample::previous_tick
Definition at line 60 of file reusability.hh.
Referenced by BlockSample(), reset(), sample_as_dead(), and sample_as_reusable().
unsigned ReusabilityProfiler::BlockSample::reuse_count
Definition at line 61 of file reusability.hh.
Referenced by BlockSample(), sample_as_dead(), and sample_as_reusable().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/reusability.hh