gem5: Cacti Class Reference
Cacti Class Reference
#include <cacti.hh>
Public Member Functions
Cacti (const Params *p)
void access (PacketPtr pkt)
void sampleLeak ()
void read ()
void write ()
void fill ()
void regStats (const string name)
Private Types
typedef BaseCacheParams Params
Private Member Functions
void check_consistency (const Params *p)
Private Attributes
CACTI::InputParameter ip
CACTI::uca_org_t uca
Stats::Formula dynamicReadEnergyPerAccess
Stats::Formula dynamicWriteEnergyPerAccess
Stats::Formula leakageBankPower
Stats::Scalar readCount
Stats::Scalar writeCount
Stats::Scalar sampledSeconds
Stats::Scalar totalDynamicEnergy
Stats::Scalar totalLeakageEnergy
Stats::Formula totalEnergy
double dy_read_energy_per_access
double dy_write_energy_per_access
double le_bank_power
double total_energy
Tick previous_sampled_tick
Detailed Description
Definition at line 9 of file cacti.hh.
Member Typedef Documentation
typedef BaseCacheParams Cacti::Params [private]
Definition at line 37 of file cacti.hh.
Constructor & Destructor Documentation
Cacti::Cacti (const Params * p)
Definition at line 11 of file cacti.cc.
References check_consistency(), dy_read_energy_per_access, dy_write_energy_per_access, inform, ip, le_bank_power, previous_sampled_tick, Stats::registerDumpCallback(), Stats::registerResetCallback(), and uca.
Member Function Documentation
void Cacti::access (PacketPtr pkt)
Definition at line 63 of file cacti.cc.
References dy_read_energy_per_access, dy_write_energy_per_access, fatal, Packet::isRead(), Packet::isWrite(), readCount, sampleLeak(), totalDynamicEnergy, and writeCount.
void Cacti::check_consistency (const Params * p) [private]
Definition at line 37 of file cacti.cc.
References fatal, inform, and ip.
Referenced by Cacti().
void Cacti::fill ()
Definition at line 91 of file cacti.cc.
References read(), sampleLeak(), and write().
Referenced by Cache::handleFill().
void Cacti::read ()
Definition at line 77 of file cacti.cc.
References dy_write_energy_per_access, readCount, sampleLeak(), and totalDynamicEnergy.
Referenced by Cache::access(), fill(), and Cache::handleSnoop().
void Cacti::regStats (const string name)
Definition at line 111 of file cacti.cc.
References dy_read_energy_per_access, dy_write_energy_per_access, dynamicReadEnergyPerAccess, dynamicWriteEnergyPerAccess, le_bank_power, leakageBankPower, Stats::DataWrap< Derived, InfoProxyType >::name(), readCount, sampledSeconds, totalDynamicEnergy, totalEnergy, totalLeakageEnergy, and writeCount.
Referenced by Cache::regStats().
void Cacti::sampleLeak ()
Definition at line 98 of file cacti.cc.
References curTick(), le_bank_power, previous_sampled_tick, SimClock::Int::s, sampledSeconds, and totalLeakageEnergy.
Referenced by access(), fill(), read(), and write().
void Cacti::write ()
Definition at line 84 of file cacti.cc.
References dy_read_energy_per_access, sampleLeak(), totalDynamicEnergy, and writeCount.
Referenced by Cache::access(), and fill().
Member Data Documentation
double Cacti::dy_read_energy_per_access [private]
Definition at line 31 of file cacti.hh.
Referenced by access(), Cacti(), regStats(), and write().
double Cacti::dy_write_energy_per_access [private]
Definition at line 32 of file cacti.hh.
Referenced by access(), Cacti(), read(), and regStats().
Stats::Formula Cacti::dynamicReadEnergyPerAccess [private]
Definition at line 18 of file cacti.hh.
Referenced by regStats().
Stats::Formula Cacti::dynamicWriteEnergyPerAccess [private]
Definition at line 19 of file cacti.hh.
Referenced by regStats().
CACTI::InputParameter Cacti::ip [private]
Definition at line 14 of file cacti.hh.
Referenced by Cacti(), and check_consistency().
double Cacti::le_bank_power [private]
Definition at line 33 of file cacti.hh.
Referenced by Cacti(), regStats(), and sampleLeak().
Stats::Formula Cacti::leakageBankPower [private]
Definition at line 20 of file cacti.hh.
Referenced by regStats().
Tick Cacti::previous_sampled_tick [private]
Definition at line 40 of file cacti.hh.
Referenced by Cacti(), and sampleLeak().
Stats::Scalar Cacti::readCount [private]
Definition at line 22 of file cacti.hh.
Referenced by access(), read(), and regStats().
Stats::Scalar Cacti::sampledSeconds [private]
Definition at line 24 of file cacti.hh.
Referenced by regStats(), and sampleLeak().
double Cacti::total_energy [private]
Definition at line 35 of file cacti.hh.
Stats::Scalar Cacti::totalDynamicEnergy [private]
Definition at line 26 of file cacti.hh.
Referenced by access(), read(), regStats(), and write().
Stats::Formula Cacti::totalEnergy [private]
Definition at line 28 of file cacti.hh.
Referenced by regStats().
Stats::Scalar Cacti::totalLeakageEnergy [private]
Definition at line 27 of file cacti.hh.
Referenced by regStats(), and sampleLeak().
CACTI::uca_org_t Cacti::uca [private]
Definition at line 15 of file cacti.hh.
Referenced by Cacti().
Stats::Scalar Cacti::writeCount [private]
Definition at line 23 of file cacti.hh.
Referenced by access(), regStats(), and write().
The documentation for this class was generated from the following files:
mem/cache/cacti.hh
mem/cache/cacti.cc