gem5: ArmISA::FpOp Class Reference
ArmISA::FpOp Class Reference
#include <vfp.hh>
Protected Member Functions
FpOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass)
virtual float doOp (float op1, float op2) const
virtual float doOp (float op1) const
virtual double doOp (double op1, double op2) const
virtual double doOp (double op1) const
double dbl (uint32_t low, uint32_t high) const
uint32_t dblLow (double val) const
uint32_t dblHi (double val) const
template<class fpType >
fpType processNans (FPSCR &fpscr, bool &done, bool defaultNan, fpType op1, fpType op2) const
template<class fpType >
fpType ternaryOp (FPSCR &fpscr, fpType op1, fpType op2, fpType op3, fpType(*func)(fpType, fpType, fpType), bool flush, bool defaultNan, uint32_t rMode) const
template<class fpType >
fpType binaryOp (FPSCR &fpscr, fpType op1, fpType op2, fpType(*func)(fpType, fpType), bool flush, bool defaultNan, uint32_t rMode) const
template<class fpType >
fpType unaryOp (FPSCR &fpscr, fpType op1, fpType(*func)(fpType), bool flush, uint32_t rMode) const
void advancePC (PCState &pcState) const
float fpSqrt (FPSCR fpscr, float x) const
double fpSqrt (FPSCR fpscr, double x) const
Detailed Description
Definition at line 777 of file vfp.hh.
Constructor & Destructor Documentation
ArmISA::FpOp::FpOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass) [inline, protected]
Definition at line 780 of file vfp.hh.
Member Function Documentation
void ArmISA::FpOp::advancePC (PCState & pcState) const [inline, protected]
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 851 of file vfp.hh.
References StaticInst::flags.
template<class fpType > fpType ArmISA::FpOp::binaryOp (FPSCR & fpscr, fpType op1, fpType op2, fpType(*)(fpType, fpType) func, bool flush, bool defaultNan, uint32_t rMode) const [inline, protected]
Definition at line 1003 of file vfp.cc.
References ArmISA::bitsToFp(), ArmISA::FeRoundZero, ArmISA::finishVfp(), ArmISA::flushToZero, ArmISA::fpToBits(), ArmISA::prepFpState(), ULL, and ArmISA::VfpRoundZero.
double ArmISA::FpOp::dbl (uint32_t low, uint32_t high) const [inline, protected]
Definition at line 809 of file vfp.hh.
References ArmISA::bitsToFp().
uint32_t ArmISA::FpOp::dblHi (double val) const [inline, protected]
Definition at line 822 of file vfp.hh.
References ArmISA::fpToBits().
uint32_t ArmISA::FpOp::dblLow (double val) const [inline, protected]
Definition at line 816 of file vfp.hh.
References ArmISA::fpToBits().
virtual double ArmISA::FpOp::doOp (double op1) const [inline, protected, virtual]
Definition at line 803 of file vfp.hh.
References panic.
virtual double ArmISA::FpOp::doOp (double op1, double op2) const [inline, protected, virtual]
Definition at line 797 of file vfp.hh.
References panic.
virtual float ArmISA::FpOp::doOp (float op1) const [inline, protected, virtual]
Definition at line 791 of file vfp.hh.
References panic.
virtual float ArmISA::FpOp::doOp (float op1, float op2) const [inline, protected, virtual]
Definition at line 785 of file vfp.hh.
References panic.
double ArmISA::FpOp::fpSqrt (FPSCR fpscr, double x) const [inline, protected]
Definition at line 871 of file vfp.hh.
References unaryOp().
float ArmISA::FpOp::fpSqrt (FPSCR fpscr, float x) const [inline, protected]
Definition at line 863 of file vfp.hh.
References unaryOp().
template<class fpType > fpType ArmISA::FpOp::processNans (FPSCR & fpscr, bool & done, bool defaultNan, fpType op1, fpType op2) const [inline, protected]
Definition at line 881 of file vfp.cc.
References ArmISA::bitsToFp(), ArmISA::fpToBits(), and ULL.
template<class fpType > fpType ArmISA::FpOp::ternaryOp (FPSCR & fpscr, fpType op1, fpType op2, fpType op3, fpType(*)(fpType, fpType, fpType) func, bool flush, bool defaultNan, uint32_t rMode) const [inline, protected]
Definition at line 925 of file vfp.cc.
References ArmISA::bitsToFp(), ArmISA::FeRoundZero, ArmISA::finishVfp(), ArmISA::flushToZero, ArmISA::fpToBits(), ArmISA::prepFpState(), ULL, and ArmISA::VfpRoundZero.
template<class fpType > fpType ArmISA::FpOp::unaryOp (FPSCR & fpscr, fpType op1, fpType(*)(fpType) func, bool flush, uint32_t rMode) const [inline, protected]
Definition at line 1074 of file vfp.cc.
References ArmISA::bitsToFp(), ArmISA::FeRoundZero, ArmISA::finishVfp(), ArmISA::flushToZero, ArmISA::fpToBits(), ArmISA::prepFpState(), ULL, and ArmISA::VfpRoundZero.
Referenced by fpSqrt().
The documentation for this class was generated from the following files:
arch/arm/insts/vfp.hh
arch/arm/insts/vfp.cc