gem5: VirtIOBlock::RequestQueue Class Reference
VirtIOBlock::RequestQueue Class Reference
Virtqueue for disk requests.
#include <block.hh>
Public Member Functions
RequestQueue (PortProxy &proxy, uint16_t size, VirtIOBlock &_parent)
virtual ~RequestQueue ()
void onNotifyDescriptor (VirtDescriptor *desc)
Notify queue of pending incoming descriptor.
std::string name () const
Protected Attributes
VirtIOBlock & parent
Detailed Description
Virtqueue for disk requests.
Definition at line 163 of file block.hh.
Constructor & Destructor Documentation
VirtIOBlock::RequestQueue::RequestQueue (PortProxy & proxy, uint16_t size, VirtIOBlock & _parent) [inline]
Definition at line 167 of file block.hh.
virtual VirtIOBlock::RequestQueue::~RequestQueue () [inline, virtual]
Definition at line 169 of file block.hh.
Member Function Documentation
std::string VirtIOBlock::RequestQueue::name () const [inline]
Definition at line 173 of file block.hh.
References SimObject::name(), and parent.
void VirtIOBlock::RequestQueue::onNotifyDescriptor (VirtDescriptor * desc) [virtual]
Notify queue of pending incoming descriptor.
This method is called by the default implementation of onNotify() to notify the device model of pending data in a descriptor chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented from VirtQueue.
Definition at line 124 of file block.cc.
References VirtDescriptor::chainRead(), VirtDescriptor::chainSize(), VirtDescriptor::chainWrite(), DPRINTF, htov_legacy(), VirtIODeviceBase::kick(), parent, VirtQueue::produceDescriptor(), VirtIOBlock::read(), VirtIOBlock::S_OK, VirtIOBlock::S_UNSUPP, VirtDescriptor::size(), ArmISA::status, VirtIOBlock::T_FLUSH, VirtIOBlock::T_IN, VirtIOBlock::T_OUT, warn, and VirtIOBlock::write().
Member Data Documentation
VirtIOBlock& VirtIOBlock::RequestQueue::parent [protected]
Definition at line 176 of file block.hh.
Referenced by name(), and onNotifyDescriptor().
The documentation for this class was generated from the following files:
dev/virtio/block.hh
dev/virtio/block.cc