gem5: QueuedSlavePort Class Reference
QueuedSlavePort Class Reference
A queued port is a port that has an infinite queue for outgoing packets and thus decouples the module that wants to send request/responses from the flow control (retry mechanism) of the port.
#include <qport.hh>
Public Member Functions
QueuedSlavePort (const std::string &name, MemObject *owner, RespPacketQueue &resp_queue, PortID id=InvalidPortID)
Create a QueuedPort with a given name, owner, and a supplied implementation of a packet queue.
virtual ~QueuedSlavePort ()
void schedTimingResp (PacketPtr pkt, Tick when)
Schedule the sending of a timing response.
bool checkFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
unsigned int drain (DrainManager *dm)
Protected Member Functions
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Protected Attributes
RespPacketQueue & respQueue
Packet queue used to store outgoing responses.
Detailed Description
A queued port is a port that has an infinite queue for outgoing packets and thus decouples the module that wants to send request/responses from the flow control (retry mechanism) of the port.
A queued port can be used by both a master and a slave. The queue is a parameter to allow tailoring of the queue implementation (used in the cache).
Definition at line 59 of file qport.hh.
Constructor & Destructor Documentation
QueuedSlavePort::QueuedSlavePort (const std::string & name, MemObject * owner, RespPacketQueue & resp_queue, PortID id = InvalidPortID) [inline]
Create a QueuedPort with a given name, owner, and a supplied implementation of a packet queue.
The external definition of the queue enables e.g. the cache to implement a specific queue behaviuor in a subclass, and provide the latter to the QueuePort constructor.
Definition at line 78 of file qport.hh.
virtual QueuedSlavePort::~QueuedSlavePort () [inline, virtual]
Definition at line 83 of file qport.hh.
Member Function Documentation
bool QueuedSlavePort::checkFunctional (PacketPtr pkt) [inline]
Check the list of buffered packets against the supplied functional request.
Definition at line 96 of file qport.hh.
References PacketQueue::checkFunctional(), and respQueue.
Referenced by Cache::functionalAccess().
unsigned int QueuedSlavePort::drain (DrainManager * dm) [inline]
Definition at line 99 of file qport.hh.
References PacketQueue::drain(), and respQueue.
Referenced by DRAMCtrl::drain(), PciDevice::drain(), PioDevice::drain(), IGbE::drain(), DmaDevice::drain(), CopyEngine::drain(), UFSHostDevice::drain(), BaseCache::drain(), and DMASequencer::getChildDrainCount().
void QueuedSlavePort::recvRespRetry () [inline, protected, virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 67 of file qport.hh.
References respQueue, and PacketQueue::retry().
void QueuedSlavePort::schedTimingResp (PacketPtr pkt, Tick when) [inline]
Schedule the sending of a timing response.
Parameters:
pkt Packet to send
when Absolute time (in ticks) to send packet
Definition at line 91 of file qport.hh.
References respQueue, and PacketQueue::schedSendTiming().
Referenced by DRAMCtrl::accessAndRespond(), RubyMemoryControl::enqueueToDirectory(), RubyPort::MemSlavePort::hitCallback(), DMASequencer::MemSlavePort::hitCallback(), SimpleTimingPort::recvTimingReq(), Cache::recvTimingReq(), RubyPort::PioMasterPort::recvTimingResp(), and Cache::recvTimingResp().
Member Data Documentation
RespPacketQueue& QueuedSlavePort::respQueue [protected]
Packet queue used to store outgoing responses.
Definition at line 65 of file qport.hh.
Referenced by checkFunctional(), drain(), SimpleTimingPort::recvFunctional(), recvRespRetry(), and schedTimingResp().
The documentation for this class was generated from the following file:
mem/qport.hh