gem5: AbstractCacheEntry Class Reference
AbstractCacheEntry Class Reference
#include <AbstractCacheEntry.hh>
Public Member Functions
AbstractCacheEntry ()
virtual ~AbstractCacheEntry ()=0
void changePermission (AccessPermission new_perm)
virtual DataBlock & getDataBlk ()
Public Attributes
Address m_Address
int m_locked
Detailed Description
Definition at line 45 of file AbstractCacheEntry.hh.
Constructor & Destructor Documentation
AbstractCacheEntry::AbstractCacheEntry ()
Definition at line 31 of file AbstractCacheEntry.cc.
References m_Address, m_locked, AbstractEntry::m_Permission, and Address::setAddress().
AbstractCacheEntry::~AbstractCacheEntry () [pure virtual]
Definition at line 38 of file AbstractCacheEntry.cc.
Member Function Documentation
void AbstractCacheEntry::changePermission (AccessPermission new_perm)
Reimplemented from AbstractEntry.
Definition at line 43 of file AbstractCacheEntry.cc.
References m_locked.
virtual DataBlock& AbstractCacheEntry::getDataBlk () [inline, virtual]
Definition at line 56 of file AbstractCacheEntry.hh.
References panic.
Referenced by CacheMemory::testCacheAccess(), and CacheMemory::tryCacheAccess().
Member Data Documentation
Address AbstractCacheEntry::m_Address
Definition at line 60 of file AbstractCacheEntry.hh.
Referenced by AbstractCacheEntry(), CacheMemory::allocate(), and CacheMemory::cacheAvail().
int AbstractCacheEntry::m_locked
Definition at line 61 of file AbstractCacheEntry.hh.
Referenced by AbstractCacheEntry(), and changePermission().
The documentation for this class was generated from the following files:
mem/ruby/slicc_interface/AbstractCacheEntry.hh
mem/ruby/slicc_interface/AbstractCacheEntry.cc