gem5: ArmISA::Memory64 Class Reference
ArmISA::Memory64 Class Reference
#include <mem64.hh>
Public Types
enum AddrMode { AddrMd_Offset, AddrMd_PreIndex, AddrMd_PostIndex }
Protected Member Functions
Memory64 (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _base)
virtual ~Memory64 ()
StaticInstPtr fetchMicroop (MicroPC microPC) const
Return the microop that goes with a particular micropc.
void startDisassembly (std::ostream &os) const
void setExcAcRel (bool exclusive, bool acrel)
Protected Attributes
IntRegIndex dest
IntRegIndex base
bool baseIsSP
True if the base register is SP (used for SP alignment checking).
StaticInstPtr * uops
unsigned memAccessFlags
Static Protected Attributes
static const unsigned numMicroops = 3
Detailed Description
Definition at line 82 of file mem64.hh.
Member Enumeration Documentation
enum ArmISA::Memory64::AddrMode
Enumerator:
AddrMd_Offset
AddrMd_PreIndex
AddrMd_PostIndex
Definition at line 85 of file mem64.hh.
Constructor & Destructor Documentation
ArmISA::Memory64::Memory64 (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _base) [inline, protected]
Definition at line 101 of file mem64.hh.
References baseIsSP, and ArmISA::isSP().
virtual ArmISA::Memory64::~Memory64 () [inline, protected, virtual]
Definition at line 110 of file mem64.hh.
References uops.
Member Function Documentation
StaticInstPtr ArmISA::Memory64::fetchMicroop (MicroPC upc) const [inline, protected, virtual]
Return the microop that goes with a particular micropc.
This should only be defined/used in macroops which will contain microops
Reimplemented from StaticInst.
Definition at line 116 of file mem64.hh.
References numMicroops, and uops.
void ArmISA::Memory64::setExcAcRel (bool exclusive, bool acrel) [protected]
Definition at line 73 of file mem64.cc.
References ArmISA::TLB::AllowUnaligned, StaticInst::flags, Request::LLSC, and memAccessFlags.
void ArmISA::Memory64::startDisassembly (std::ostream & os) const [protected]
Definition at line 64 of file mem64.cc.
References base, ccprintf(), dest, ArmISA::ArmStaticInst::printMnemonic(), and ArmISA::ArmStaticInst::printReg().
Referenced by ArmISA::MemoryRaw64::generateDisassembly(), ArmISA::MemoryReg64::generateDisassembly(), ArmISA::MemoryPostIndex64::generateDisassembly(), ArmISA::MemoryPreIndex64::generateDisassembly(), and ArmISA::MemoryImm64::generateDisassembly().
Member Data Documentation
IntRegIndex ArmISA::Memory64::base [protected]
Definition at line 94 of file mem64.hh.
Referenced by ArmISA::MemoryEx64::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), and startDisassembly().
bool ArmISA::Memory64::baseIsSP [protected]
True if the base register is SP (used for SP alignment checking).
Definition at line 96 of file mem64.hh.
Referenced by Memory64().
IntRegIndex ArmISA::Memory64::dest [protected]
Definition at line 93 of file mem64.hh.
Referenced by ArmISA::MemoryLiteral64::generateDisassembly(), ArmISA::MemoryEx64::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), and startDisassembly().
unsigned ArmISA::Memory64::memAccessFlags [protected]
Definition at line 124 of file mem64.hh.
Referenced by setExcAcRel().
const unsigned ArmISA::Memory64::numMicroops = 3 [static, protected]
Definition at line 97 of file mem64.hh.
Referenced by fetchMicroop().
StaticInstPtr* ArmISA::Memory64::uops [protected]
Definition at line 99 of file mem64.hh.
Referenced by fetchMicroop(), and ~Memory64().
The documentation for this class was generated from the following files:
arch/arm/insts/mem64.hh
arch/arm/insts/mem64.cc