gem5: DRAMCtrl::Rank Class Reference
DRAMCtrl::Rank Class Reference
Rank class includes a vector of banks.
Public Member Functions
Rank (DRAMCtrl &_memory, const DRAMCtrlParams *_p)
const std::string name () const
void startup (Tick ref_tick)
Kick off accounting for power and refresh states and schedule initial refresh.
void suspend ()
Stop the refresh events.
bool isAvailable () const
Check if the current rank is available for scheduling.
void checkDrainDone ()
Let the rank check if it was waiting for requests to drain to allow it to transition states.
void regStats ()
void processActivateEvent ()
void processPrechargeEvent ()
void processRefreshEvent ()
void processPowerEvent ()
Public Attributes
uint8_t rank
Current Rank index.
DRAMPower power
One DRAMPower instance per rank.
std::vector< Bank > banks
Vector of Banks.
unsigned int numBanksActive
To track number of banks which are currently active for this rank.
std::deque< Tick > actTicks
List to keep track of activate ticks.
EventWrapper< Rank,&Rank::processActivateEvent > activateEvent
EventWrapper< Rank,&Rank::processPrechargeEvent > prechargeEvent
EventWrapper< Rank,&Rank::processRefreshEvent > refreshEvent
EventWrapper< Rank,&Rank::processPowerEvent > powerEvent
Private Types
enum PowerState {
PWR_IDLE = 0, PWR_REF, PWR_PRE_PDN, PWR_ACT,
PWR_ACT_PDN
}
The power state captures the different operational states of the DRAM and interacts with the bus read/write state machine, and the refresh state machine.
enum RefreshState { REF_IDLE = 0, REF_DRAIN, REF_PRE, REF_RUN }
The refresh state is used to control the progress of the refresh scheduling.
Private Member Functions
void updatePowerStats ()
Function to update Power Stats.
void schedulePowerEvent (PowerState pwr_state, Tick tick)
Schedule a power state transition in the future, and potentially override an already scheduled transition.
Private Attributes
DRAMCtrl & memory
A reference to the parent DRAMCtrl instance.
PowerState pwrStateTrans
Since we are taking decisions out of order, we need to keep track of what power transition is happening at what time, such that we can go back in time and change history.
PowerState pwrState
Current power state.
Tick pwrStateTick
Track when we transitioned to the current power state.
RefreshState refreshState
current refresh state
Tick refreshDueAt
Keep track of when a refresh is due.
Stats::Scalar actEnergy
Stats::Scalar preEnergy
Stats::Scalar readEnergy
Stats::Scalar writeEnergy
Stats::Scalar refreshEnergy
Stats::Scalar actBackEnergy
Stats::Scalar preBackEnergy
Stats::Scalar totalEnergy
Stats::Scalar averagePower
Stats::Vector pwrStateTime
Track time spent in each power state.
Detailed Description
Rank class includes a vector of banks.
Refresh and Power state machines are defined per rank. Events required to change the state of the refresh and power state machine are scheduled per rank. This class allows the implementation of rank-wise refresh and rank-wise power-down.
Definition at line 189 of file dram_ctrl.hh.
Member Enumeration Documentation
enum DRAMCtrl::Rank::PowerState [private]
The power state captures the different operational states of the DRAM and interacts with the bus read/write state machine, and the refresh state machine.
In the idle state all banks are precharged. From there we either go to an auto refresh (as determined by the refresh state machine), or to a precharge power down mode. From idle the memory can also go to the active state (with one or more banks active), and in turn from there to active power down. At the moment we do not capture the deep power down and self-refresh state.
Enumerator:
PWR_IDLE
PWR_REF
PWR_PRE_PDN
PWR_ACT
PWR_ACT_PDN
Definition at line 205 of file dram_ctrl.hh.
enum DRAMCtrl::Rank::RefreshState [private]
The refresh state is used to control the progress of the refresh scheduling.
When normal operation is in progress the refresh state is idle. From there, it progresses to the refresh drain state once tREFI has passed. The refresh drain state captures the DRAM row active state, as it will stay there until all ongoing accesses complete. Thereafter all banks are precharged, and lastly, the DRAM is refreshed.
Enumerator:
REF_IDLE
REF_DRAIN
REF_PRE
REF_RUN
Definition at line 222 of file dram_ctrl.hh.
Constructor & Destructor Documentation
DRAMCtrl::Rank::Rank (DRAMCtrl & _memory, const DRAMCtrlParams * _p)
Definition at line 1553 of file dram_ctrl.cc.
Member Function Documentation
void DRAMCtrl::Rank::checkDrainDone ()
Let the rank check if it was waiting for requests to drain to allow it to transition states.
Definition at line 1581 of file dram_ctrl.cc.
References curTick(), DPRINTF, REF_DRAIN, REF_PRE, refreshEvent, refreshState, and EventManager::schedule().
bool DRAMCtrl::Rank::isAvailable () const [inline]
Check if the current rank is available for scheduling.
Parameters:
Return true if the rank is idle from a refresh point of view
Definition at line 357 of file dram_ctrl.hh.
References REF_IDLE, and refreshState.
Referenced by DRAMCtrl::processNextReqEvent(), and DRAMCtrl::reorderQueue().
const std::string DRAMCtrl::Rank::name () const [inline]
Definition at line 334 of file dram_ctrl.hh.
References csprintf(), memory, SimObject::name(), and rank.
Referenced by regStats().
void DRAMCtrl::Rank::processActivateEvent ()
Definition at line 1596 of file dram_ctrl.cc.
References curTick(), PWR_ACT, pwrState, and schedulePowerEvent().
void DRAMCtrl::Rank::processPowerEvent ()
Definition at line 1792 of file dram_ctrl.cc.
References curTick(), DPRINTF, memory, DRAMCtrl::nextReqEvent, powerEvent, processRefreshEvent(), PWR_ACT, PWR_IDLE, PWR_REF, pwrState, pwrStateTick, pwrStateTime, pwrStateTrans, REF_IDLE, REF_RUN, refreshState, EventManager::schedule(), and Event::scheduled().
void DRAMCtrl::Rank::processPrechargeEvent ()
Definition at line 1606 of file dram_ctrl.cc.
References curTick(), numBanksActive, PWR_IDLE, and schedulePowerEvent().
void DRAMCtrl::Rank::processRefreshEvent ()
Definition at line 1618 of file dram_ctrl.cc.
References DRAMCtrl::activeRank, ArmISA::b, banks, curTick(), divCeil(), DPRINTF, fatal, memory, DRAMCtrl::nextReqEvent, DRAMCtrl::Bank::NO_ROW, numBanksActive, power, powerEvent, DRAMPower::powerlib, DRAMCtrl::prechargeBank(), PWR_IDLE, PWR_REF, pwrState, REF_DRAIN, REF_IDLE, REF_PRE, REF_RUN, refreshDueAt, refreshEvent, refreshState, EventManager::schedule(), Event::scheduled(), schedulePowerEvent(), DRAMCtrl::sortTime(), DRAMCtrl::tCK, DRAMCtrl::timeStampOffset, DRAMCtrl::tREFI, DRAMCtrl::tRFC, DRAMCtrl::tRP, and updatePowerStats().
Referenced by processPowerEvent().
void DRAMCtrl::Rank::regStats ()
Definition at line 1868 of file dram_ctrl.cc.
References actBackEnergy, actEnergy, averagePower, Stats::VectorBase< Derived, Stor >::init(), Stats::DataWrap< Derived, InfoProxyType >::name(), name(), preBackEnergy, preEnergy, pwrStateTime, readEnergy, refreshEnergy, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), totalEnergy, and writeEnergy.
void DRAMCtrl::Rank::schedulePowerEvent (PowerState pwr_state, Tick tick) [private]
Schedule a power state transition in the future, and potentially override an already scheduled transition.
Parameters:
pwr_state Power state to transition to
tick Tick when transition should take place
Definition at line 1771 of file dram_ctrl.cc.
References curTick(), DPRINTF, panic, powerEvent, pwrStateTrans, EventManager::schedule(), Event::scheduled(), and Event::when().
Referenced by processActivateEvent(), processPrechargeEvent(), and processRefreshEvent().
void DRAMCtrl::Rank::startup (Tick ref_tick)
Kick off accounting for power and refresh states and schedule initial refresh.
Parameters:
ref_tick Tick for first refresh
Definition at line 1563 of file dram_ctrl.cc.
References curTick(), pwrStateTick, refreshEvent, and EventManager::schedule().
void DRAMCtrl::Rank::suspend ()
Stop the refresh events.
Definition at line 1575 of file dram_ctrl.cc.
References EventManager::deschedule(), and refreshEvent.
void DRAMCtrl::Rank::updatePowerStats () [private]
Function to update Power Stats.
Definition at line 1848 of file dram_ctrl.cc.
References actBackEnergy, actEnergy, averagePower, DRAMCtrl::devicesPerRank, memory, power, DRAMPower::powerlib, preBackEnergy, preEnergy, readEnergy, refreshEnergy, totalEnergy, and writeEnergy.
Referenced by processRefreshEvent().
Member Data Documentation
Stats::Scalar DRAMCtrl::Rank::actBackEnergy [private]
Definition at line 276 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
Stats::Scalar DRAMCtrl::Rank::actEnergy [private]
Definition at line 267 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
EventWrapper<Rank, &Rank::processActivateEvent> DRAMCtrl::Rank::activateEvent
Definition at line 372 of file dram_ctrl.hh.
Referenced by DRAMCtrl::activateBank().
std::deque<Tick> DRAMCtrl::Rank::actTicks
List to keep track of activate ticks.
Definition at line 330 of file dram_ctrl.hh.
Referenced by DRAMCtrl::activateBank(), and DRAMCtrl::DRAMCtrl().
Stats::Scalar DRAMCtrl::Rank::averagePower [private]
Definition at line 284 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
std::vector<Bank> DRAMCtrl::Rank::banks
Vector of Banks.
Each rank is made of several devices which in term are made from several banks.
Definition at line 321 of file dram_ctrl.hh.
Referenced by DRAMCtrl::activateBank(), DRAMCtrl::DRAMCtrl(), and processRefreshEvent().
DRAMCtrl& DRAMCtrl::Rank::memory [private]
A reference to the parent DRAMCtrl instance.
Definition at line 232 of file dram_ctrl.hh.
Referenced by name(), processPowerEvent(), processRefreshEvent(), and updatePowerStats().
unsigned int DRAMCtrl::Rank::numBanksActive
To track number of banks which are currently active for this rank.
Definition at line 327 of file dram_ctrl.hh.
Referenced by DRAMCtrl::activateBank(), DRAMCtrl::prechargeBank(), processPrechargeEvent(), and processRefreshEvent().
DRAMPower DRAMCtrl::Rank::power
One DRAMPower instance per rank.
Definition at line 315 of file dram_ctrl.hh.
Referenced by DRAMCtrl::activateBank(), DRAMCtrl::doDRAMAccess(), DRAMCtrl::prechargeBank(), processRefreshEvent(), and updatePowerStats().
EventWrapper<Rank, &Rank::processPowerEvent> DRAMCtrl::Rank::powerEvent
Definition at line 384 of file dram_ctrl.hh.
Referenced by processPowerEvent(), processRefreshEvent(), and schedulePowerEvent().
Stats::Scalar DRAMCtrl::Rank::preBackEnergy [private]
Definition at line 281 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
EventWrapper<Rank, &Rank::processPrechargeEvent> DRAMCtrl::Rank::prechargeEvent
Definition at line 376 of file dram_ctrl.hh.
Referenced by DRAMCtrl::prechargeBank().
Stats::Scalar DRAMCtrl::Rank::preEnergy [private]
Definition at line 268 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
PowerState DRAMCtrl::Rank::pwrState [private]
Current power state.
Definition at line 247 of file dram_ctrl.hh.
Referenced by processActivateEvent(), processPowerEvent(), and processRefreshEvent().
Tick DRAMCtrl::Rank::pwrStateTick [private]
Track when we transitioned to the current power state.
Definition at line 252 of file dram_ctrl.hh.
Referenced by processPowerEvent(), and startup().
Stats::Vector DRAMCtrl::Rank::pwrStateTime [private]
Track time spent in each power state.
Definition at line 289 of file dram_ctrl.hh.
Referenced by processPowerEvent(), and regStats().
PowerState DRAMCtrl::Rank::pwrStateTrans [private]
Since we are taking decisions out of order, we need to keep track of what power transition is happening at what time, such that we can go back in time and change history.
For example, if we precharge all banks and schedule going to the idle state, we might at a later point decide to activate a bank before the transition to idle would have taken place.
Definition at line 242 of file dram_ctrl.hh.
Referenced by processPowerEvent(), and schedulePowerEvent().
uint8_t DRAMCtrl::Rank::rank
Current Rank index.
Definition at line 310 of file dram_ctrl.hh.
Referenced by DRAMCtrl::activateBank(), DRAMCtrl::DRAMCtrl(), name(), and DRAMCtrl::prechargeBank().
Stats::Scalar DRAMCtrl::Rank::readEnergy [private]
Definition at line 269 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
Tick DRAMCtrl::Rank::refreshDueAt [private]
Keep track of when a refresh is due.
Definition at line 262 of file dram_ctrl.hh.
Referenced by processRefreshEvent().
Stats::Scalar DRAMCtrl::Rank::refreshEnergy [private]
Definition at line 271 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
EventWrapper<Rank, &Rank::processRefreshEvent> DRAMCtrl::Rank::refreshEvent
Definition at line 380 of file dram_ctrl.hh.
Referenced by checkDrainDone(), processRefreshEvent(), startup(), and suspend().
RefreshState DRAMCtrl::Rank::refreshState [private]
current refresh state
Definition at line 257 of file dram_ctrl.hh.
Referenced by checkDrainDone(), isAvailable(), processPowerEvent(), and processRefreshEvent().
Stats::Scalar DRAMCtrl::Rank::totalEnergy [private]
Definition at line 283 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
Stats::Scalar DRAMCtrl::Rank::writeEnergy [private]
Definition at line 270 of file dram_ctrl.hh.
Referenced by regStats(), and updatePowerStats().
The documentation for this class was generated from the following files:
mem/dram_ctrl.hh
mem/dram_ctrl.cc