gem5: SparcISA::Interrupts Class Reference
SparcISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
typedef SparcInterruptsParams Params
Public Member Functions
void setCPU (BaseCPU *_cpu)
const Params * params () const
Interrupts (Params *p)
int InterruptLevel (uint64_t softint)
void post (int int_num, int index)
void clear (int int_num, int index)
void clearAll ()
bool checkInterrupts (ThreadContext *tc) const
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc)
uint64_t get_vec (int int_num)
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Attributes
BaseCPU * cpu
uint64_t interrupts [NumInterruptTypes]
uint64_t intStatus
Detailed Description
Definition at line 46 of file interrupts.hh.
Member Typedef Documentation
typedef SparcInterruptsParams SparcISA::Interrupts::Params
Reimplemented from SimObject.
Definition at line 62 of file interrupts.hh.
Constructor & Destructor Documentation
SparcISA::Interrupts::Interrupts (Params * p) [inline]
Definition at line 70 of file interrupts.hh.
References clearAll().
Member Function Documentation
bool SparcISA::Interrupts::checkInterrupts (ThreadContext * tc) const [inline]
Definition at line 122 of file interrupts.hh.
References intStatus.
void SparcISA::Interrupts::clear (int int_num, int index) [inline]
Definition at line 101 of file interrupts.hh.
References DPRINTF, interrupts, intStatus, SparcISA::NumInterruptTypes, and ULL.
void SparcISA::Interrupts::clearAll () [inline]
Definition at line 113 of file interrupts.hh.
References ArmISA::i, interrupts, intStatus, and SparcISA::NumInterruptTypes.
Referenced by Interrupts().
uint64_t SparcISA::Interrupts::get_vec (int int_num) [inline]
Definition at line 187 of file interrupts.hh.
References interrupts, and SparcISA::NumInterruptTypes.
Referenced by SparcISA::TLB::doMmuRegRead(), and SparcISA::TLB::doMmuRegWrite().
Fault SparcISA::Interrupts::getInterrupt (ThreadContext * tc) [inline]
Definition at line 128 of file interrupts.hh.
References InterruptLevel(), interrupts, SparcISA::IT_CPU_MONDO, SparcISA::IT_DEV_MONDO, SparcISA::IT_HINTP, SparcISA::IT_INT_VEC, SparcISA::IT_RES_ERROR, SparcISA::IT_SOFT_INT, SparcISA::IT_TRAP_LEVEL_ZERO, X86ISA::level, SparcISA::MISCREG_HPSTATE, SparcISA::MISCREG_PSTATE, and ThreadContext::readMiscRegNoEffect().
int SparcISA::Interrupts::InterruptLevel (uint64_t softint) [inline]
Definition at line 76 of file interrupts.hh.
References X86ISA::level.
Referenced by getInterrupt().
const Params* SparcISA::Interrupts::params () const [inline]
Reimplemented from SimObject.
Definition at line 65 of file interrupts.hh.
References SimObject::_params.
void SparcISA::Interrupts::post (int int_num, int index) [inline]
Definition at line 90 of file interrupts.hh.
References DPRINTF, interrupts, intStatus, SparcISA::NumInterruptTypes, and ULL.
void SparcISA::Interrupts::serialize (std::ostream & os) [inline, virtual]
Reimplemented from Serializable.
Definition at line 194 of file interrupts.hh.
References interrupts, intStatus, SparcISA::NumInterruptTypes, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
void SparcISA::Interrupts::setCPU (BaseCPU * _cpu) [inline]
Definition at line 57 of file interrupts.hh.
References cpu.
void SparcISA::Interrupts::unserialize (Checkpoint * cp, const std::string & section) [inline, virtual]
Reimplemented from Serializable.
Definition at line 201 of file interrupts.hh.
References interrupts, intStatus, SparcISA::NumInterruptTypes, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
void SparcISA::Interrupts::updateIntrInfo (ThreadContext * tc) [inline]
Definition at line 183 of file interrupts.hh.
Member Data Documentation
BaseCPU* SparcISA::Interrupts::cpu [private]
Definition at line 49 of file interrupts.hh.
Referenced by setCPU().
uint64_t SparcISA::Interrupts::interrupts[NumInterruptTypes] [private]
Definition at line 51 of file interrupts.hh.
Referenced by clear(), clearAll(), get_vec(), getInterrupt(), post(), serialize(), and unserialize().
uint64_t SparcISA::Interrupts::intStatus [private]
Definition at line 52 of file interrupts.hh.
Referenced by checkInterrupts(), clear(), clearAll(), post(), serialize(), and unserialize().
The documentation for this class was generated from the following file:
arch/sparc/interrupts.hh