gem5: Stats::SparseHistogram Class Reference
Stats::SparseHistogram Class Reference
["Statistic Types"]
#include <statistics.hh>
Public Member Functions
SparseHistogram & init (size_type size)
Set the parameters of this histogram.
Detailed Description
Definition at line 2854 of file statistics.hh.
Member Function Documentation
SparseHistogram& Stats::SparseHistogram::init (size_type size) [inline]
Set the parameters of this histogram.
See also:
HistStor::Params
Parameters:
size The number of buckets in the histogram
Returns:
A reference to this histogram.
Definition at line 2863 of file statistics.hh.
References Stats::SparseHistBase< SparseHistogram, SparseHistStor >::doInit(), and Stats::InfoAccess::setParams().
Referenced by StatTest::init(), StackDistCalc::regStats(), and CommMonitor::regStats().
The documentation for this class was generated from the following file:
base/statistics.hh