gem5: Minor::QueuedInst Class Reference
Minor::QueuedInst Class Reference
Container class to box instructions in the FUs to make those queues have correct bubble behaviour when stepped.
#include <func_unit.hh>
Public Member Functions
QueuedInst (MinorDynInstPtr inst_=MinorDynInst::bubble())
void reportData (std::ostream &os) const
Report and bubble interfaces.
bool isBubble () const
Static Public Member Functions
static QueuedInst bubble ()
Public Attributes
MinorDynInstPtr inst
Detailed Description
Container class to box instructions in the FUs to make those queues have correct bubble behaviour when stepped.
Definition at line 198 of file func_unit.hh.
Constructor & Destructor Documentation
Minor::QueuedInst::QueuedInst (MinorDynInstPtr inst_ = MinorDynInst::bubble()) [inline]
Definition at line 204 of file func_unit.hh.
Referenced by bubble().
Member Function Documentation
static QueuedInst Minor::QueuedInst::bubble () [inline, static]
Definition at line 213 of file func_unit.hh.
References Minor::MinorDynInst::bubble(), and QueuedInst().
bool Minor::QueuedInst::isBubble () const [inline]
Definition at line 211 of file func_unit.hh.
References inst.
void Minor::QueuedInst::reportData (std::ostream & os) const
Report and bubble interfaces.
Definition at line 107 of file func_unit.cc.
References inst.
Member Data Documentation
MinorDynInstPtr Minor::QueuedInst::inst
Definition at line 201 of file func_unit.hh.
Referenced by Minor::Execute::commit(), Minor::Execute::evaluate(), Minor::Execute::instIsHeadInst(), isBubble(), and reportData().
The documentation for this class was generated from the following files:
cpu/minor/func_unit.hh
cpu/minor/func_unit.cc