gem5: DRAMSim2::MemoryPort Class Reference
DRAMSim2::MemoryPort Class Reference
The memory port has to deal with its own flow control to avoid having unbounded storage that is implicitly created in the port itself.
Public Member Functions
MemoryPort (const std::string &_name, DRAMSim2 &_memory)
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Private Attributes
DRAMSim2 & memory
Detailed Description
The memory port has to deal with its own flow control to avoid having unbounded storage that is implicitly created in the port itself.
Definition at line 64 of file dramsim2.hh.
Constructor & Destructor Documentation
DRAMSim2::MemoryPort::MemoryPort (const std::string & _name, DRAMSim2 & _memory)
Definition at line 377 of file dramsim2.cc.
Member Function Documentation
AddrRangeList DRAMSim2::MemoryPort::getAddrRanges () const [protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 383 of file dramsim2.cc.
References AbstractMemory::getAddrRange(), and memory.
Tick DRAMSim2::MemoryPort::recvAtomic (PacketPtr pkt) [protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 391 of file dramsim2.cc.
References memory, and DRAMSim2::recvAtomic().
void DRAMSim2::MemoryPort::recvFunctional (PacketPtr pkt) [protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 397 of file dramsim2.cc.
References memory, and DRAMSim2::recvFunctional().
void DRAMSim2::MemoryPort::recvRespRetry () [protected, virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 410 of file dramsim2.cc.
References memory, and DRAMSim2::recvRespRetry().
bool DRAMSim2::MemoryPort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 403 of file dramsim2.cc.
References memory, and DRAMSim2::recvTimingReq().
Member Data Documentation
DRAMSim2& DRAMSim2::MemoryPort::memory [private]
Definition at line 69 of file dramsim2.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvRespRetry(), and recvTimingReq().
The documentation for this class was generated from the following files:
mem/dramsim2.hh
mem/dramsim2.cc