gem5: AbstractController Class Reference
AbstractController Class Reference
#include <AbstractController.hh>
Classes
class MemoryPort
Port that forwards requests and receives responses from the memory controller.
struct SenderState
class StatsCallback
Callback class used for collating statistics from all the controller of this type.
Public Types
typedef RubyControllerParams Params
Public Member Functions
AbstractController (const Params *p)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
const Params * params () const
const NodeID getVersion () const
const MachineType getType () const
void initNetworkPtr (Network *net_ptr)
void blockOnQueue (Address, MessageBuffer *)
void unblock (Address)
virtual MessageBuffer * getMandatoryQueue () const =0
virtual AccessPermission getAccessPermission (const Address &addr)=0
virtual void print (std::ostream &out) const =0
virtual void wakeup ()=0
virtual void resetStats ()=0
Reset statistics associated with this object.
virtual void regStats ()
Register statistics for this object.
virtual void recordCacheTrace (int cntrl, CacheRecorder *tr)=0
virtual Sequencer * getSequencer () const =0
virtual void functionalRead (const Address &addr, PacketPtr)=0
These functions are used by ruby system to read/write the data blocks that exist with in the controller.
void functionalMemoryRead (PacketPtr)
virtual int functionalWriteBuffers (PacketPtr &)=0
The return value indicates the number of messages written with the data from the packet.
virtual int functionalWrite (const Address &addr, PacketPtr)=0
int functionalMemoryWrite (PacketPtr)
virtual void enqueuePrefetch (const Address &, const RubyRequestType &)
Function for enqueuing a prefetch request.
virtual void collateStats ()
Function for collating statistics from all the controllers of this particular type.
virtual void setNetQueue (const std::string &name, MessageBuffer *b)=0
Set the message buffer with given name.
BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
A function used to return the port associated with this bus object.
void queueMemoryRead (const MachineID &id, Address addr, Cycles latency)
void queueMemoryWrite (const MachineID &id, Address addr, Cycles latency, const DataBlock &block)
void queueMemoryWritePartial (const MachineID &id, Address addr, Cycles latency, const DataBlock &block, int size)
void recvTimingResp (PacketPtr pkt)
MachineID getMachineID () const
Stats::Histogram & getDelayHist ()
Stats::Histogram & getDelayVCHist (uint32_t index)
Protected Types
typedef std::vector
< MessageBuffer * > MsgVecType
typedef std::map< Address,
MsgVecType * > WaitingBufType
Protected Member Functions
void profileRequest (const std::string &request)
Profiles original cache requests including PUTs.
void profileMsgDelay (uint32_t virtualNetwork, Cycles delay)
Profiles the delay associated with messages.
void stallBuffer (MessageBuffer *buf, Address addr)
void wakeUpBuffers (Address addr)
void wakeUpAllBuffers (Address addr)
void wakeUpAllBuffers ()
Protected Attributes
NodeID m_version
MachineID m_machineID
NodeID m_clusterID
MasterID m_masterId
Network * m_net_ptr
bool m_is_blocking
std::map< Address,
MessageBuffer * > m_block_map
WaitingBufType m_waiting_buffers
unsigned int m_in_ports
unsigned int m_cur_in_port
int m_number_of_TBEs
int m_transitions_per_cycle
unsigned int m_buffer_size
Cycles m_recycle_latency
Stats::Scalar m_fully_busy_cycles
Counter for the number of cycles when the transitions carried out were equal to the maximum allowed.
Stats::Histogram m_delayHistogram
Histogram for profiling delay for the messages this controller cares for.
std::vector< Stats::Histogram * > m_delayVCHistogram
MemoryPort memoryPort
MessageBuffer * m_responseFromMemory_ptr
Detailed Description
Definition at line 52 of file AbstractController.hh.
Member Typedef Documentation
typedef std::vector<MessageBuffer*> AbstractController::MsgVecType [protected]
Definition at line 144 of file AbstractController.hh.
typedef RubyControllerParams AbstractController::Params
Reimplemented from MemObject.
Definition at line 55 of file AbstractController.hh.
typedef std::map< Address, MsgVecType* > AbstractController::WaitingBufType [protected]
Definition at line 145 of file AbstractController.hh.
Constructor & Destructor Documentation
AbstractController::AbstractController (const Params * p)
Definition at line 35 of file AbstractController.cc.
References m_responseFromMemory_ptr, m_version, Stats::registerDumpCallback(), MessageBuffer::setOrdering(), MessageBuffer::setReceiver(), and MessageBuffer::setSender().
Member Function Documentation
void AbstractController::blockOnQueue (Address addr, MessageBuffer * port)
Definition at line 183 of file AbstractController.cc.
References m_block_map, and m_is_blocking.
Referenced by Sequencer::writeCallback().
virtual void AbstractController::collateStats () [inline, virtual]
Function for collating statistics from all the controllers of this particular type.
This function should only be called from the version 0 of this controller type.
Definition at line 97 of file AbstractController.hh.
References fatal.
Referenced by AbstractController::StatsCallback::process().
virtual void AbstractController::enqueuePrefetch (const Address & , const RubyRequestType &) [inline, virtual]
Function for enqueuing a prefetch request.
Definition at line 91 of file AbstractController.hh.
References fatal.
Referenced by Prefetcher::initializeStream(), and Prefetcher::issueNextPrefetch().
void AbstractController::functionalMemoryRead (PacketPtr pkt)
Definition at line 280 of file AbstractController.cc.
References memoryPort, and MasterPort::sendFunctional().
int AbstractController::functionalMemoryWrite (PacketPtr pkt)
Definition at line 286 of file AbstractController.cc.
References QueuedMasterPort::checkFunctional(), MessageBuffer::functionalWrite(), m_responseFromMemory_ptr, memoryPort, and MasterPort::sendFunctional().
virtual void AbstractController::functionalRead (const Address & addr, PacketPtr) [pure virtual]
These functions are used by ruby system to read/write the data blocks that exist with in the controller.
virtual int AbstractController::functionalWrite (const Address & addr, PacketPtr) [pure virtual]
virtual int AbstractController::functionalWriteBuffers (PacketPtr &) [pure virtual]
The return value indicates the number of messages written with the data from the packet.
virtual AccessPermission AbstractController::getAccessPermission (const Address & addr) [pure virtual]
Stats::Histogram& AbstractController::getDelayHist () [inline]
Definition at line 117 of file AbstractController.hh.
References m_delayHistogram.
Referenced by Profiler::collateStats().
Stats::Histogram& AbstractController::getDelayVCHist (uint32_t index) [inline]
Definition at line 118 of file AbstractController.hh.
References m_delayVCHistogram.
Referenced by Profiler::collateStats().
MachineID AbstractController::getMachineID () const [inline]
Definition at line 115 of file AbstractController.hh.
References m_machineID.
Referenced by RubySystem::registerAbstractController().
virtual MessageBuffer* AbstractController::getMandatoryQueue () const [pure virtual]
Referenced by RubyPort::init(), and DMASequencer::init().
BaseMasterPort & AbstractController::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
A function used to return the port associated with this bus object.
Reimplemented from MemObject.
Definition at line 199 of file AbstractController.cc.
References memoryPort.
virtual Sequencer* AbstractController::getSequencer () const [pure virtual]
Referenced by Profiler::collateStats().
const MachineType AbstractController::getType () const [inline]
Definition at line 61 of file AbstractController.hh.
References MachineID::getType(), and m_machineID.
Referenced by Topology::Topology().
const NodeID AbstractController::getVersion () const [inline]
Definition at line 60 of file AbstractController.hh.
References MachineID::getNum(), and m_machineID.
Referenced by Topology::Topology().
void AbstractController::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 60 of file AbstractController.cc.
References Network::getNumberOfVirtualNetworks(), ArmISA::i, Stats::Histogram::init(), m_delayHistogram, m_delayVCHistogram, and params().
void AbstractController::initNetworkPtr (Network * net_ptr) [inline]
Definition at line 63 of file AbstractController.hh.
References m_net_ptr.
Referenced by Network::Network().
const Params* AbstractController::params () const [inline]
Reimplemented from MemObject.
Definition at line 58 of file AbstractController.hh.
References SimObject::_params.
Referenced by init().
virtual void AbstractController::print (std::ostream & out) const [pure virtual]
Implements Consumer.
void AbstractController::profileMsgDelay (uint32_t virtualNetwork, Cycles delay) [protected]
Profiles the delay associated with messages.
Definition at line 91 of file AbstractController.cc.
References m_delayHistogram, m_delayVCHistogram, and Stats::DistBase< Derived, Stor >::sample().
void AbstractController::profileRequest (const std::string & request) [protected]
Profiles original cache requests including PUTs.
void AbstractController::queueMemoryRead (const MachineID & id, Address addr, Cycles latency)
Definition at line 206 of file AbstractController.cc.
References ClockedObject::clockEdge(), Packet::createRead(), Address::getAddress(), RubySystem::getBlockSizeBytes(), RubySystem::getWarmupEnabled(), m_masterId, memoryPort, recvTimingResp(), ArmISA::s, QueuedMasterPort::schedTimingReq(), and MasterPort::sendFunctional().
void AbstractController::queueMemoryWrite (const MachineID & id, Address addr, Cycles latency, const DataBlock & block)
Definition at line 231 of file AbstractController.cc.
References ClockedObject::clockEdge(), Packet::createWrite(), Address::getAddress(), RubySystem::getBlockSizeBytes(), DataBlock::getData(), RubySystem::getWarmupEnabled(), m_masterId, memoryPort, recvTimingResp(), ArmISA::s, QueuedMasterPort::schedTimingReq(), and MasterPort::sendFunctional().
void AbstractController::queueMemoryWritePartial (const MachineID & id, Address addr, Cycles latency, const DataBlock & block, int size)
Definition at line 259 of file AbstractController.cc.
References ClockedObject::clockEdge(), Packet::createWrite(), Address::getAddress(), RubySystem::getBlockSizeBytes(), DataBlock::getData(), Address::getOffset(), m_masterId, memoryPort, ArmISA::s, and QueuedMasterPort::schedTimingReq().
virtual void AbstractController::recordCacheTrace (int cntrl, CacheRecorder * tr) [pure virtual]
void AbstractController::recvTimingResp (PacketPtr pkt)
Definition at line 304 of file AbstractController.cc.
References ClockedObject::clockEdge(), MessageBuffer::enqueue(), Packet::getAddr(), RubySystem::getBlockSizeBytes(), Packet::getPtr(), AbstractController::SenderState::id, Packet::isRead(), Packet::isResponse(), Packet::isWrite(), m_machineID, m_responseFromMemory_ptr, panic, ArmISA::s, and Packet::senderState.
Referenced by queueMemoryRead(), queueMemoryWrite(), and AbstractController::MemoryPort::recvTimingResp().
void AbstractController::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 82 of file AbstractController.cc.
References m_fully_busy_cycles, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::nozero.
void AbstractController::resetStats () [pure virtual]
Reset statistics associated with this object.
Reimplemented from SimObject.
Definition at line 72 of file AbstractController.cc.
References Network::getNumberOfVirtualNetworks(), ArmISA::i, m_delayHistogram, m_delayVCHistogram, and Stats::DistBase< Derived, Stor >::reset().
virtual void AbstractController::setNetQueue (const std::string & name, MessageBuffer * b) [pure virtual]
Set the message buffer with given name.
Referenced by connectPorts().
void AbstractController::stallBuffer (MessageBuffer * buf, Address addr) [protected]
Definition at line 99 of file AbstractController.cc.
References m_cur_in_port, m_in_ports, and m_waiting_buffers.
void AbstractController::unblock (Address addr)
Definition at line 190 of file AbstractController.cc.
References m_block_map, and m_is_blocking.
Referenced by Sequencer::writeCallback().
virtual void AbstractController::wakeup () [pure virtual]
Implements Consumer.
void AbstractController::wakeUpAllBuffers () [protected]
Definition at line 150 of file AbstractController.cc.
References m_waiting_buffers.
void AbstractController::wakeUpAllBuffers (Address addr) [protected]
Definition at line 130 of file AbstractController.cc.
References m_in_ports, and m_waiting_buffers.
void AbstractController::wakeUpBuffers (Address addr) [protected]
Definition at line 110 of file AbstractController.cc.
References m_cur_in_port, and m_waiting_buffers.
Member Data Documentation
std::map<Address, MessageBuffer*> AbstractController::m_block_map [protected]
Definition at line 142 of file AbstractController.hh.
Referenced by blockOnQueue(), and unblock().
unsigned int AbstractController::m_buffer_size [protected]
Definition at line 152 of file AbstractController.hh.
NodeID AbstractController::m_clusterID [protected]
Definition at line 135 of file AbstractController.hh.
unsigned int AbstractController::m_cur_in_port [protected]
Definition at line 149 of file AbstractController.hh.
Referenced by stallBuffer(), and wakeUpBuffers().
Stats::Histogram AbstractController::m_delayHistogram [protected]
Histogram for profiling delay for the messages this controller cares for.
Definition at line 161 of file AbstractController.hh.
Referenced by getDelayHist(), init(), profileMsgDelay(), and resetStats().
std::vector<Stats::Histogram *> AbstractController::m_delayVCHistogram [protected]
Definition at line 162 of file AbstractController.hh.
Referenced by getDelayVCHist(), init(), profileMsgDelay(), and resetStats().
Stats::Scalar AbstractController::m_fully_busy_cycles [protected]
Counter for the number of cycles when the transitions carried out were equal to the maximum allowed.
Definition at line 157 of file AbstractController.hh.
Referenced by regStats().
unsigned int AbstractController::m_in_ports [protected]
Definition at line 148 of file AbstractController.hh.
Referenced by stallBuffer(), and wakeUpAllBuffers().
bool AbstractController::m_is_blocking [protected]
Definition at line 141 of file AbstractController.hh.
Referenced by blockOnQueue(), and unblock().
MachineID AbstractController::m_machineID [protected]
Definition at line 134 of file AbstractController.hh.
Referenced by getMachineID(), getType(), getVersion(), and recvTimingResp().
MasterID AbstractController::m_masterId [protected]
Definition at line 138 of file AbstractController.hh.
Referenced by queueMemoryRead(), queueMemoryWrite(), and queueMemoryWritePartial().
Network* AbstractController::m_net_ptr [protected]
Definition at line 140 of file AbstractController.hh.
Referenced by initNetworkPtr().
int AbstractController::m_number_of_TBEs [protected]
Definition at line 150 of file AbstractController.hh.
Cycles AbstractController::m_recycle_latency [protected]
Definition at line 153 of file AbstractController.hh.
MessageBuffer* AbstractController::m_responseFromMemory_ptr [protected]
Definition at line 206 of file AbstractController.hh.
Referenced by AbstractController(), functionalMemoryWrite(), and recvTimingResp().
int AbstractController::m_transitions_per_cycle [protected]
Definition at line 151 of file AbstractController.hh.
NodeID AbstractController::m_version [protected]
Definition at line 133 of file AbstractController.hh.
Referenced by AbstractController().
WaitingBufType AbstractController::m_waiting_buffers [protected]
Definition at line 146 of file AbstractController.hh.
Referenced by stallBuffer(), wakeUpAllBuffers(), and wakeUpBuffers().
MemoryPort AbstractController::memoryPort [protected]
Definition at line 202 of file AbstractController.hh.
Referenced by functionalMemoryRead(), functionalMemoryWrite(), getMasterPort(), queueMemoryRead(), queueMemoryWrite(), and queueMemoryWritePartial().
The documentation for this class was generated from the following files:
mem/ruby/slicc_interface/AbstractController.hh
mem/ruby/slicc_interface/AbstractController.cc