gem5: SparcISA::FillNNormal Class Reference
SparcISA::FillNNormal Class Reference
#include <faults.hh>
Public Member Functions
FillNNormal (uint32_t n)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Detailed Description
Definition at line 252 of file faults.hh.
Constructor & Destructor Documentation
SparcISA::FillNNormal::FillNNormal (uint32_t n) [inline]
Definition at line 255 of file faults.hh.
Member Function Documentation
void SparcISA::FillNNormal::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from SparcISA::SparcFaultBase.
Definition at line 682 of file faults.cc.
References SparcISA::doNormalFault(), FullSystem, ThreadContext::getProcessPtr(), MipsISA::p, ThreadContext::pcState(), SparcLiveProcess::readFillStart(), and SparcISA::EnumeratedFault< FillNNormal >::trapType().
The documentation for this class was generated from the following files:
arch/sparc/faults.hh
arch/sparc/faults.cc