gem5: AddressTracer Class Reference
AddressTracer Class Reference
#include <addr_tracer.hh>
Public Member Functions
AddressTracer (std::string _name, bool _set_sample=true, unsigned int _nsets=128, Addr _bsize=64, std::string _order_by="spacefill")
std::string name ()
virtual void regStats ()
virtual void insert (Addr addr)
virtual void access (Addr addr)
virtual void victim (Addr addr)
virtual void sampling ()
virtual void dump ()
virtual void reset ()
bool is_samplesets (Addr addr)
void open_stream ()
void close_stream ()
void finalize ()
Private Attributes
SampledSetIdentifier ssid
AddressMapper addr_map
AddressCounterTable reusehist
ReuseDistanceAnalyzer rdanalyze
std::ostream * insert_ostream
std::ostream * access_ostream
std::ostream * reused_ostream
DistanceAddressStream insert_stream
DistanceAddressStream access_stream
Tick usage_distance
Addr bsize
bool set_sample
std::string order_by
Detailed Description
Definition at line 23 of file addr_tracer.hh.
Constructor & Destructor Documentation
AddressTracer::AddressTracer (std::string _name, bool _set_sample = true, unsigned int _nsets = 128, Addr _bsize = 64, std::string _order_by = "spacefill")
Member Function Documentation
void AddressTracer::access (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 51 of file addr_tracer.cc.
References ReuseDistanceAnalyzer::access(), access_stream, addr_map, is_samplesets(), DistanceAddressStream::push_back(), AddressMapper::put_addr(), rdanalyze, reusehist, set_sample, and usage_distance.
void AddressTracer::close_stream ()
Definition at line 31 of file addr_tracer.cc.
References access_ostream, OutputDirectory::close(), insert_ostream, reused_ostream, and simout.
Referenced by dump().
void AddressTracer::dump () [virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 87 of file addr_tracer.cc.
References access_ostream, access_stream, addr_map, close_stream(), insert_ostream, insert_stream, open_stream(), order_by, AddressMapper::order_by_firsttouch(), AddressMapper::order_by_spacefill(), ReuseDistanceAnalyzer::output(), rdanalyze, and reused_ostream.
Referenced by finalize().
void AddressTracer::finalize () [inline]
Definition at line 70 of file addr_tracer.hh.
References dump().
void AddressTracer::insert (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 39 of file addr_tracer.cc.
References addr_map, ReuseDistanceAnalyzer::insert(), insert_stream, is_samplesets(), DistanceAddressStream::push_back(), AddressMapper::put_addr(), rdanalyze, reusehist, set_sample, and usage_distance.
bool AddressTracer::is_samplesets (Addr addr)
Definition at line 71 of file addr_tracer.cc.
References SampledSetIdentifier::isSampledAddr(), set_sample, and ssid.
Referenced by access(), insert(), and victim().
std::string AddressTracer::name () [inline]
Reimplemented from BaseTagsProfiler.
Definition at line 53 of file addr_tracer.hh.
Referenced by open_stream().
void AddressTracer::open_stream ()
Definition at line 24 of file addr_tracer.cc.
References access_ostream, OutputDirectory::create(), insert_ostream, name(), reused_ostream, and simout.
Referenced by dump().
virtual void AddressTracer::regStats () [inline, virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 55 of file addr_tracer.hh.
void AddressTracer::reset () [virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 114 of file addr_tracer.cc.
References access_stream, addr_map, AddressMapper::clear(), insert_stream, rdanalyze, ReuseDistanceAnalyzer::reset(), and usage_distance.
virtual void AddressTracer::sampling () [inline, virtual]
Implements BaseTagsProfiler.
Definition at line 61 of file addr_tracer.hh.
void AddressTracer::victim (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 63 of file addr_tracer.cc.
References AddressCounterTable::erase(), is_samplesets(), rdanalyze, reusehist, set_sample, and ReuseDistanceAnalyzer::victim().
Member Data Documentation
std::ostream* AddressTracer::access_ostream [private]
Definition at line 34 of file addr_tracer.hh.
Referenced by close_stream(), dump(), and open_stream().
DistanceAddressStream AddressTracer::access_stream [private]
Definition at line 38 of file addr_tracer.hh.
Referenced by access(), dump(), and reset().
AddressMapper AddressTracer::addr_map [private]
Definition at line 27 of file addr_tracer.hh.
Referenced by access(), dump(), insert(), and reset().
Addr AddressTracer::bsize [private]
Definition at line 42 of file addr_tracer.hh.
std::ostream* AddressTracer::insert_ostream [private]
Definition at line 33 of file addr_tracer.hh.
Referenced by close_stream(), dump(), and open_stream().
DistanceAddressStream AddressTracer::insert_stream [private]
Definition at line 37 of file addr_tracer.hh.
Referenced by dump(), insert(), and reset().
std::string AddressTracer::order_by [private]
Definition at line 44 of file addr_tracer.hh.
Referenced by dump().
ReuseDistanceAnalyzer AddressTracer::rdanalyze [private]
Definition at line 31 of file addr_tracer.hh.
Referenced by access(), dump(), insert(), reset(), and victim().
std::ostream* AddressTracer::reused_ostream [private]
Definition at line 35 of file addr_tracer.hh.
Referenced by close_stream(), dump(), and open_stream().
AddressCounterTable AddressTracer::reusehist [private]
Definition at line 29 of file addr_tracer.hh.
Referenced by access(), insert(), and victim().
bool AddressTracer::set_sample [private]
Definition at line 43 of file addr_tracer.hh.
Referenced by access(), insert(), is_samplesets(), and victim().
SampledSetIdentifier AddressTracer::ssid [private]
Definition at line 25 of file addr_tracer.hh.
Referenced by is_samplesets().
Tick AddressTracer::usage_distance [private]
Definition at line 40 of file addr_tracer.hh.
Referenced by access(), insert(), and reset().
The documentation for this class was generated from the following files:
mem/cache/tags/prof/addr_tracer.hh
mem/cache/tags/prof/addr_tracer.cc