gem5: NetworkLink_d Class Reference
NetworkLink_d Class Reference
#include <NetworkLink_d.hh>
Public Types
typedef NetworkLink_dParams Params
Public Member Functions
NetworkLink_d (const Params *p)
~NetworkLink_d ()
void setLinkConsumer (Consumer *consumer)
void setSourceQueue (flitBuffer_d *srcQueue)
void print (std::ostream &out) const
int get_id ()
void wakeup ()
unsigned int getLinkUtilization () const
const std::vector< unsigned int > & getVcLoad () const
bool isReady (Cycles curTime)
flit_d * peekLink ()
flit_d * consumeLink ()
uint32_t functionalWrite (Packet *)
Private Attributes
int m_id
Cycles m_latency
int channel_width
flitBuffer_d * linkBuffer
Consumer * link_consumer
flitBuffer_d * link_srcQueue
unsigned int m_link_utilized
std::vector< unsigned int > m_vc_load
Detailed Description
Definition at line 45 of file NetworkLink_d.hh.
Member Typedef Documentation
typedef NetworkLink_dParams NetworkLink_d::Params
Reimplemented from SimObject.
Reimplemented in CreditLink_d.
Definition at line 48 of file NetworkLink_d.hh.
Constructor & Destructor Documentation
NetworkLink_d::NetworkLink_d (const Params * p)
Definition at line 34 of file NetworkLink_d.cc.
References channel_width, ArmISA::i, linkBuffer, m_id, m_latency, m_link_utilized, and m_vc_load.
NetworkLink_d::~NetworkLink_d ()
Definition at line 49 of file NetworkLink_d.cc.
References linkBuffer.
Member Function Documentation
flit_d* NetworkLink_d::consumeLink () [inline]
Definition at line 65 of file NetworkLink_d.hh.
References flitBuffer_d::getTopFlit(), and linkBuffer.
Referenced by OutputUnit_d::wakeup(), NetworkInterface_d::wakeup(), and InputUnit_d::wakeup().
uint32_t NetworkLink_d::functionalWrite (Packet * pkt)
Definition at line 92 of file NetworkLink_d.cc.
References flitBuffer_d::functionalWrite(), and linkBuffer.
int NetworkLink_d::get_id () [inline]
Definition at line 55 of file NetworkLink_d.hh.
References m_id.
Referenced by InputUnit_d::get_inlink_id(), and OutputUnit_d::get_outlink_id().
unsigned int NetworkLink_d::getLinkUtilization () const [inline]
Definition at line 58 of file NetworkLink_d.hh.
References m_link_utilized.
const std::vector<unsigned int>& NetworkLink_d::getVcLoad () const [inline]
Definition at line 59 of file NetworkLink_d.hh.
References m_vc_load.
bool NetworkLink_d::isReady (Cycles curTime) [inline]
Definition at line 61 of file NetworkLink_d.hh.
References flitBuffer_d::isReady(), and linkBuffer.
Referenced by OutputUnit_d::wakeup(), NetworkInterface_d::wakeup(), and InputUnit_d::wakeup().
flit_d* NetworkLink_d::peekLink () [inline]
Definition at line 64 of file NetworkLink_d.hh.
References linkBuffer, and flitBuffer_d::peekTopFlit().
void NetworkLink_d::print (std::ostream & out) const [inline, virtual]
Implements Consumer.
Definition at line 54 of file NetworkLink_d.hh.
void NetworkLink_d::setLinkConsumer (Consumer * consumer)
Definition at line 55 of file NetworkLink_d.cc.
References link_consumer.
Referenced by Router_d::addInPort(), NetworkInterface_d::addInPort(), Router_d::addOutPort(), and NetworkInterface_d::addOutPort().
void NetworkLink_d::setSourceQueue (flitBuffer_d * srcQueue)
Definition at line 61 of file NetworkLink_d.cc.
References link_srcQueue.
Referenced by Router_d::addInPort(), NetworkInterface_d::addInPort(), Router_d::addOutPort(), and NetworkInterface_d::addOutPort().
void NetworkLink_d::wakeup () [virtual]
Implements Consumer.
Definition at line 67 of file NetworkLink_d.cc.
References ClockedObject::clockEdge(), ClockedObject::curCycle(), flit_d::get_vc(), flitBuffer_d::getTopFlit(), flitBuffer_d::insert(), flitBuffer_d::isReady(), link_consumer, link_srcQueue, linkBuffer, m_latency, m_link_utilized, m_vc_load, Consumer::scheduleEventAbsolute(), and flit_d::set_time().
Member Data Documentation
int NetworkLink_d::channel_width [private]
Definition at line 72 of file NetworkLink_d.hh.
Referenced by NetworkLink_d().
Consumer* NetworkLink_d::link_consumer [private]
Definition at line 75 of file NetworkLink_d.hh.
Referenced by setLinkConsumer(), and wakeup().
flitBuffer_d* NetworkLink_d::link_srcQueue [private]
Definition at line 76 of file NetworkLink_d.hh.
Referenced by setSourceQueue(), and wakeup().
flitBuffer_d* NetworkLink_d::linkBuffer [private]
Definition at line 74 of file NetworkLink_d.hh.
Referenced by consumeLink(), functionalWrite(), isReady(), NetworkLink_d(), peekLink(), wakeup(), and ~NetworkLink_d().
int NetworkLink_d::m_id [private]
Definition at line 70 of file NetworkLink_d.hh.
Referenced by get_id(), and NetworkLink_d().
Cycles NetworkLink_d::m_latency [private]
Definition at line 71 of file NetworkLink_d.hh.
Referenced by NetworkLink_d(), and wakeup().
unsigned int NetworkLink_d::m_link_utilized [private]
Definition at line 79 of file NetworkLink_d.hh.
Referenced by getLinkUtilization(), NetworkLink_d(), and wakeup().
std::vector<unsigned int> NetworkLink_d::m_vc_load [private]
Definition at line 80 of file NetworkLink_d.hh.
Referenced by getVcLoad(), NetworkLink_d(), and wakeup().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/NetworkLink_d.hh
mem/ruby/network/garnet/fixed-pipeline/NetworkLink_d.cc