gem5: DecoderFaultInst Class Reference
DecoderFaultInst Class Reference
#include <pseudo.hh>
Public Member Functions
DecoderFaultInst (ExtMachInst _machInst)
Fault execute (ExecContext *xc, Trace::InstRecord *traceData) const
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Member Functions
const char * faultName () const
Protected Attributes
DecoderFault faultId
Detailed Description
Definition at line 49 of file pseudo.hh.
Constructor & Destructor Documentation
DecoderFaultInst::DecoderFaultInst (ExtMachInst _machInst)
Definition at line 47 of file pseudo.cc.
References faultId, StaticInst::flags, and ArmISA::PANIC.
Member Function Documentation
Fault DecoderFaultInst::execute (ExecContext * xc, Trace::InstRecord * traceData) const [virtual]
Implements StaticInst.
Definition at line 58 of file pseudo.cc.
References faultId, StaticInst::machInst, ArmISA::OK, panic, ArmISA::PANIC, MipsISA::pc, ExecContext::pcState(), and ArmISA::UNALIGNED.
const char * DecoderFaultInst::faultName () const [protected]
Definition at line 85 of file pseudo.cc.
References faultId, ArmISA::OK, panic, ArmISA::PANIC, and ArmISA::UNALIGNED.
Referenced by generateDisassembly().
std::string DecoderFaultInst::generateDisassembly (Addr pc, const SymbolTable * symtab) const [virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 102 of file pseudo.cc.
References csprintf(), and faultName().
Member Data Documentation
DecoderFault DecoderFaultInst::faultId [protected]
Definition at line 52 of file pseudo.hh.
Referenced by DecoderFaultInst(), execute(), and faultName().
The documentation for this class was generated from the following files:
arch/arm/insts/pseudo.hh
arch/arm/insts/pseudo.cc