gem5: Topology Class Reference
Topology Class Reference
#include <Topology.hh>
Public Member Functions
Topology (uint32_t num_routers, std::vector< BasicExtLink * > ext_links, std::vector< BasicIntLink * > int_links)
uint32_t numSwitches () const
void createLinks (Network *net)
void print (std::ostream &out) const
Protected Member Functions
void addLink (SwitchID src, SwitchID dest, BasicLink *link, LinkDirection dir)
void makeLink (Network *net, SwitchID src, SwitchID dest, const NetDest &routing_table_entry)
Protected Attributes
NodeID m_nodes
uint32_t m_number_of_switches
std::vector< BasicExtLink * > m_ext_link_vector
std::vector< BasicIntLink * > m_int_link_vector
Matrix m_component_latencies
Matrix m_component_inter_switches
LinkMap m_link_map
Detailed Description
Definition at line 64 of file Topology.hh.
Constructor & Destructor Documentation
Topology::Topology (uint32_t num_routers, std::vector< BasicExtLink * > ext_links, std::vector< BasicIntLink * > int_links)
Definition at line 59 of file Topology.cc.
References ArmISA::a, addLink(), ArmISA::b, fatal, AbstractController::getType(), AbstractController::getVersion(), ArmISA::i, m_component_inter_switches, m_component_latencies, m_ext_link_vector, m_int_link_vector, m_nodes, BasicIntLink::params(), BasicRouter::params(), and BasicExtLink::params().
Member Function Documentation
void Topology::addLink (SwitchID src, SwitchID dest, BasicLink * link, LinkDirection dir) [protected]
Definition at line 191 of file Topology.cc.
References LinkEntry::direction, LinkEntry::link, m_link_map, m_nodes, and m_number_of_switches.
Referenced by Topology().
void Topology::createLinks (Network * net)
Definition at line 124 of file Topology.cc.
References Stats::dist, ArmISA::i, INFINITE_LATENCY, ArmISA::j, m_component_inter_switches, m_component_latencies, BasicLink::m_latency, m_link_map, BasicLink::m_weight, makeLink(), shortest_path(), and shortest_path_to_node().
Referenced by SimpleNetwork::init(), GarnetNetwork::init(), and GarnetNetwork_d::init().
void Topology::makeLink (Network * net, SwitchID src, SwitchID dest, const NetDest & routing_table_entry) [protected]
Definition at line 208 of file Topology.cc.
References LinkEntry::direction, LinkEntry::link, m_link_map, m_nodes, Network::makeInLink(), Network::makeInternalLink(), and Network::makeOutLink().
Referenced by createLinks().
uint32_t Topology::numSwitches () const [inline]
Definition at line 70 of file Topology.hh.
References m_number_of_switches.
void Topology::print (std::ostream & out) const [inline]
Definition at line 72 of file Topology.hh.
Referenced by operator<<().
Member Data Documentation
Matrix Topology::m_component_inter_switches [protected]
Definition at line 87 of file Topology.hh.
Referenced by createLinks(), and Topology().
Matrix Topology::m_component_latencies [protected]
Definition at line 86 of file Topology.hh.
Referenced by createLinks(), and Topology().
std::vector<BasicExtLink*> Topology::m_ext_link_vector [protected]
Definition at line 83 of file Topology.hh.
Referenced by Topology().
std::vector<BasicIntLink*> Topology::m_int_link_vector [protected]
Definition at line 84 of file Topology.hh.
Referenced by Topology().
LinkMap Topology::m_link_map [protected]
Definition at line 89 of file Topology.hh.
Referenced by addLink(), createLinks(), and makeLink().
NodeID Topology::m_nodes [protected]
Definition at line 80 of file Topology.hh.
Referenced by addLink(), makeLink(), and Topology().
uint32_t Topology::m_number_of_switches [protected]
Definition at line 81 of file Topology.hh.
Referenced by addLink(), and numSwitches().
The documentation for this class was generated from the following files:
mem/ruby/network/Topology.hh
mem/ruby/network/Topology.cc