gem5: X86ISA::IntDevice Class Reference
X86ISA::IntDevice Class Reference
#include <intdev.hh>
Classes
class IntMasterPort
class IntSlavePort
Public Member Functions
IntDevice (MemObject *parent, Tick latency=0)
virtual ~IntDevice ()
virtual void init ()
virtual void signalInterrupt (int line)
virtual void raiseInterruptPin (int number)
virtual void lowerInterruptPin (int number)
virtual Tick recvMessage (PacketPtr pkt)
virtual Tick recvResponse (PacketPtr pkt)
virtual AddrRangeList getIntAddrRange () const
Protected Attributes
IntMasterPort intMasterPort
Detailed Description
Definition at line 63 of file intdev.hh.
Constructor & Destructor Documentation
X86ISA::IntDevice::IntDevice (MemObject * parent, Tick latency = 0) [inline]
Definition at line 115 of file intdev.hh.
virtual X86ISA::IntDevice::~IntDevice () [inline, virtual]
Definition at line 120 of file intdev.hh.
Member Function Documentation
virtual AddrRangeList X86ISA::IntDevice::getIntAddrRange () const [inline, virtual]
Reimplemented in X86ISA::Interrupts, and X86ISA::I82094AA.
Definition at line 157 of file intdev.hh.
References panic.
Referenced by X86ISA::IntDevice::IntSlavePort::getAddrRanges().
void X86ISA::IntDevice::init () [virtual]
Reimplemented in X86ISA::Interrupts, and X86ISA::I82094AA.
Definition at line 69 of file intdev.cc.
References intMasterPort, BaseMasterPort::isConnected(), and panic.
virtual void X86ISA::IntDevice::lowerInterruptPin (int number) [inline, virtual]
Reimplemented in X86ISA::I82094AA, and X86ISA::I8259.
Definition at line 138 of file intdev.hh.
References panic.
Referenced by X86ISA::IntSourcePin::lower().
virtual void X86ISA::IntDevice::raiseInterruptPin (int number) [inline, virtual]
Reimplemented in X86ISA::I82094AA, and X86ISA::I8259.
Definition at line 132 of file intdev.hh.
References panic.
Referenced by X86ISA::IntSourcePin::raise().
virtual Tick X86ISA::IntDevice::recvMessage (PacketPtr pkt) [inline, virtual]
Reimplemented in X86ISA::Interrupts.
Definition at line 144 of file intdev.hh.
References panic.
Referenced by X86ISA::IntDevice::IntSlavePort::recvMessage().
virtual Tick X86ISA::IntDevice::recvResponse (PacketPtr pkt) [inline, virtual]
Reimplemented in X86ISA::Interrupts.
Definition at line 151 of file intdev.hh.
Referenced by X86ISA::IntDevice::IntMasterPort::recvResponse().
virtual void X86ISA::IntDevice::signalInterrupt (int line) [inline, virtual]
Reimplemented in X86ISA::I82094AA, and X86ISA::I8259.
Definition at line 126 of file intdev.hh.
References panic.
Member Data Documentation
IntMasterPort X86ISA::IntDevice::intMasterPort [protected]
Definition at line 112 of file intdev.hh.
Referenced by X86ISA::I82094AA::getMasterPort(), X86ISA::Interrupts::getMasterPort(), init(), X86ISA::Interrupts::setReg(), and X86ISA::I82094AA::signalInterrupt().
The documentation for this class was generated from the following files:
dev/x86/intdev.hh
dev/x86/intdev.cc