gem5: TimingExpr Class Reference
TimingExpr Class Reference
#include <timing_expr.hh>
Public Member Functions
TimingExpr (const TimingExprParams *params)
virtual uint64_t eval (TimingExprEvalContext &context)=0
Detailed Description
Definition at line 90 of file timing_expr.hh.
Constructor & Destructor Documentation
TimingExpr::TimingExpr (const TimingExprParams * params) [inline]
Definition at line 93 of file timing_expr.hh.
Member Function Documentation
virtual uint64_t TimingExpr::eval (TimingExprEvalContext & context) [pure virtual]
Implemented in TimingExprLiteral, TimingExprSrcReg, TimingExprReadIntReg, TimingExprLet, TimingExprRef, TimingExprUn, TimingExprBin, and TimingExprIf.
Referenced by TimingExprIf::eval(), TimingExprBin::eval(), TimingExprUn::eval(), TimingExprLet::eval(), and TimingExprReadIntReg::eval().
The documentation for this class was generated from the following file:
cpu/timing_expr.hh