gem5: BaseArmKvmCPU Class Reference
BaseArmKvmCPU Class Reference
#include <base_cpu.hh>
Public Member Functions
BaseArmKvmCPU (BaseArmKvmCPUParams *params)
virtual ~BaseArmKvmCPU ()
void startup () M5_ATTR_OVERRIDE
Protected Types
typedef std::vector< uint64_t > RegIndexVector
Protected Member Functions
Tick kvmRun (Tick ticks) M5_ATTR_OVERRIDE
Request KVM to run the guest for a given number of ticks.
const RegIndexVector & getRegList () const
Get a list of registers supported by getOneReg() and setOneReg().
void kvmArmVCpuInit (const struct kvm_vcpu_init &init)
Tell the kernel to initialize this CPU.
Protected Attributes
bool irqAsserted
Cached state of the IRQ line.
bool fiqAsserted
Cached state of the FIQ line.
Private Member Functions
std::unique_ptr< struct
kvm_reg_list > tryGetRegList (uint64_t nelem) const
bool getRegList (struct kvm_reg_list &regs) const
Get a list of registers supported by getOneReg() and setOneReg().
Private Attributes
RegIndexVector _regIndexList
Cached copy of the list of registers supported by KVM.
Detailed Description
Definition at line 49 of file base_cpu.hh.
Member Typedef Documentation
typedef std::vector<uint64_t> BaseArmKvmCPU::RegIndexVector [protected]
Definition at line 67 of file base_cpu.hh.
Constructor & Destructor Documentation
BaseArmKvmCPU::BaseArmKvmCPU (BaseArmKvmCPUParams * params)
Definition at line 60 of file base_cpu.cc.
BaseArmKvmCPU::~BaseArmKvmCPU () [virtual]
Definition at line 66 of file base_cpu.cc.
Member Function Documentation
bool BaseArmKvmCPU::getRegList (struct kvm_reg_list & regs) const [private]
Get a list of registers supported by getOneReg() and setOneReg().
Returns:
False if the number of elements allocated in the list is too small to hold the complete register list (the required size is written to regs.n in this case). True on success.
Definition at line 142 of file base_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
const BaseArmKvmCPU::RegIndexVector & BaseArmKvmCPU::getRegList () const [protected]
Get a list of registers supported by getOneReg() and setOneReg().
This method returns a list of all registers supported by kvm. The actual list is only requested the first time this method is called. Subsequent calls return a cached copy of the register list.
Returns:
Vector of register indexes.
Definition at line 107 of file base_cpu.cc.
References _regIndexList, and panic.
Referenced by ArmV8KvmCPU::dump(), and ArmV8KvmCPU::getSysRegMap().
void BaseArmKvmCPU::kvmArmVCpuInit (const struct kvm_vcpu_init & init) [protected]
Tell the kernel to initialize this CPU.
The kernel needs to know what type of the CPU that we want to emulate. The specified CPU type has to be compatible with the host CPU. In practice, we usually call KvmVM::kvmArmPreferredTarget() to discover the host CPU.
Parameters:
target CPU type to emulate
Definition at line 135 of file base_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by startup().
Tick BaseArmKvmCPU::kvmRun (Tick ticks) [protected, virtual]
Request KVM to run the guest for a given number of ticks.
The method returns the approximate number of ticks executed.
Note:
The returned number of ticks can be both larger or smaller than the requested number of ticks. A smaller number can, for example, occur when the guest executes MMIO. A larger number is typically due to performance counter inaccuracies.
This method is virtual in order to allow implementations to check for architecture specific events (e.g., interrupts) before entering the VM.
It is the response of the caller (normally tick()) to make sure that the KVM state is synchronized and that the TC is invalidated after entering KVM.
This method does not normally cause any state transitions. However, if it may suspend the CPU by suspending the thread, which leads to a transition to the Idle state. In such a case, kvm must not be entered.
Parameters:
ticks Number of ticks to execute, set to 0 to exit immediately after finishing pending operations.
Returns:
Number of ticks executed (see note)
Reimplemented from BaseKvmCPU.
Definition at line 87 of file base_cpu.cc.
References DPRINTF, fiqAsserted, ArmISA::INT_FIQ, ArmISA::INT_IRQ, INTERRUPT_VCPU_FIQ, INTERRUPT_VCPU_IRQ, irqAsserted, KvmVM::setIRQLine(), BaseKvmCPU::vcpuID, and BaseKvmCPU::vm.
void BaseArmKvmCPU::startup ()
Reimplemented from BaseKvmCPU.
Definition at line 71 of file base_cpu.cc.
References kvmArmVCpuInit(), and BaseKvmCPU::vm.
std::unique_ptr<struct kvm_reg_list> BaseArmKvmCPU::tryGetRegList (uint64_t nelem) const [private]
Member Data Documentation
RegIndexVector BaseArmKvmCPU::_regIndexList [mutable, private]
Cached copy of the list of registers supported by KVM.
Definition at line 108 of file base_cpu.hh.
Referenced by getRegList().
bool BaseArmKvmCPU::fiqAsserted [protected]
Cached state of the FIQ line.
Definition at line 64 of file base_cpu.hh.
Referenced by kvmRun().
bool BaseArmKvmCPU::irqAsserted [protected]
Cached state of the IRQ line.
Definition at line 62 of file base_cpu.hh.
Referenced by kvmRun().
The documentation for this class was generated from the following files:
arch/arm/kvm/base_cpu.hh
arch/arm/kvm/base_cpu.cc