gem5: Sp804 Class Reference
Sp804 Class Reference
#include <timer_sp804.hh>
Classes
class Timer
Public Types
typedef Sp804Params Params
Public Member Functions
const Params * params () const
Sp804 (Params *p)
The constructor for RealView just registers itself with the MMU.
virtual Tick read (PacketPtr pkt)
Handle a read to the device.
virtual Tick write (PacketPtr pkt)
All writes are simply ignored.
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
Protected Attributes
BaseGic * gic
Pointer to the GIC for causing an interrupt.
Timer timer0
Timers that do the actual work.
Timer timer1
Detailed Description
Definition at line 52 of file timer_sp804.hh.
Member Typedef Documentation
typedef Sp804Params Sp804::Params
Reimplemented from AmbaPioDevice.
Definition at line 137 of file timer_sp804.hh.
Constructor & Destructor Documentation
Sp804::Sp804 (Params * p)
The constructor for RealView just registers itself with the MMU.
Parameters:
p params structure
Definition at line 49 of file timer_sp804.cc.
Member Function Documentation
const Params* Sp804::params () const [inline]
Reimplemented from BasicPioDevice.
Definition at line 139 of file timer_sp804.hh.
References SimObject::_params.
Tick Sp804::read (PacketPtr pkt) [virtual]
Handle a read to the device.
Parameters:
pkt The memory request.
data Where to put the data.
Implements PioDevice.
Definition at line 64 of file timer_sp804.cc.
References AmbaPioDevice::ambaId, DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, Sp804::Timer::read(), AmbaDevice::readId(), Sp804::Timer::Size, timer0, and timer1.
void Sp804::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 267 of file timer_sp804.cc.
References csprintf(), SimObject::name(), Serializable::nameOut(), Sp804::Timer::serialize(), timer0, and timer1.
void Sp804::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 276 of file timer_sp804.cc.
References csprintf(), timer0, timer1, and Sp804::Timer::unserialize().
Tick Sp804::write (PacketPtr pkt) [virtual]
All writes are simply ignored.
Parameters:
pkt The memory request.
data the data
Implements PioDevice.
Definition at line 118 of file timer_sp804.cc.
References AmbaPioDevice::ambaId, DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, AmbaDevice::readId(), Sp804::Timer::Size, timer0, timer1, and Sp804::Timer::write().
Member Data Documentation
BaseGic* Sp804::gic [protected]
Pointer to the GIC for causing an interrupt.
Definition at line 130 of file timer_sp804.hh.
Referenced by Sp804::Timer::counterAtZero(), and Sp804::Timer::write().
Timer Sp804::timer0 [protected]
Timers that do the actual work.
Definition at line 133 of file timer_sp804.hh.
Referenced by read(), serialize(), unserialize(), and write().
Timer Sp804::timer1 [protected]
Definition at line 134 of file timer_sp804.hh.
Referenced by read(), serialize(), unserialize(), and write().
The documentation for this class was generated from the following files:
dev/arm/timer_sp804.hh
dev/arm/timer_sp804.cc