gem5: Address Class Reference
Address Class Reference
#include <Address.hh>
Public Member Functions
Address ()
Address (physical_address_t address)
Address (const Address &obj)
Address & operator= (const Address &obj)
void setAddress (physical_address_t address)
physical_address_t getAddress () const
physical_address_t bitSelect (unsigned int small, unsigned int big) const
physical_address_t bitRemove (unsigned int small, unsigned int big) const
physical_address_t maskLowOrderBits (unsigned int number) const
physical_address_t maskHighOrderBits (unsigned int number) const
physical_address_t shiftLowOrderBits (unsigned int number) const
physical_address_t getLineAddress () const
physical_address_t getOffset () const
void makeLineAddress ()
void makeNextStrideAddress (int stride)
int64 memoryModuleIndex () const
void print (std::ostream &out) const
void output (std::ostream &out) const
void input (std::istream &in)
void setOffset (int offset)
Private Attributes
physical_address_t m_address
Detailed Description
Definition at line 45 of file Address.hh.
Constructor & Destructor Documentation
Address::Address () [inline]
Definition at line 48 of file Address.hh.
Address::Address (physical_address_t address) [inline, explicit]
Definition at line 53 of file Address.hh.
Address::Address (const Address & obj)
Definition at line 121 of file Address.cc.
References m_address.
Member Function Documentation
physical_address_t Address::bitRemove (unsigned int small, unsigned int big) const [inline]
Definition at line 145 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
Referenced by DirectoryMemory::mapAddressToLocalIdx().
physical_address_t Address::bitSelect (unsigned int small, unsigned int big) const [inline]
Definition at line 128 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
Referenced by CheckTable::addCheck(), CacheMemory::addressToCacheSet(), MultiGrainBloomFilter::get_block_index(), NonCountingBloomFilter::get_index(), LSB_CountingBloomFilter::get_index(), BulkBloomFilter::get_index(), BlockBloomFilter::get_index(), MultiGrainBloomFilter::get_page_index(), getLineAddress(), getOffset(), BulkBloomFilter::isSet(), DirectoryMemory::mapAddressToDirectoryVersion(), mapAddressToRange(), memoryModuleIndex(), BulkBloomFilter::permute(), and BulkBloomFilter::set().
physical_address_t Address::getAddress () const [inline]
Definition at line 61 of file Address.hh.
References m_address.
Referenced by Prefetcher::accessNonunitFilter(), CheckTable::addCheck(), Check::debugPrint(), RubyRequest::functionalWrite(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), DirectoryMemory::mapAddressToLocalIdx(), operator!=(), hash< Address >::operator()(), operator<(), operator==(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), AbstractController::queueMemoryWritePartial(), RubyPort::MemSlavePort::recvFunctional(), RubyPort::ruby_eviction_callback(), testAndRead(), and testAndWrite().
physical_address_t Address::getLineAddress () const
Definition at line 33 of file Address.cc.
References ADDRESS_WIDTH, bitSelect(), and RubySystem::getBlockSizeBits().
Referenced by MultiBitSelBloomFilter::get_index(), H3BloomFilter::get_index(), and Check::performCallback().
physical_address_t Address::getOffset () const
Definition at line 39 of file Address.cc.
References bitSelect(), and RubySystem::getBlockSizeBits().
Referenced by addressOffset(), SubBlock::internalMergeFrom(), SubBlock::internalMergeTo(), AbstractController::queueMemoryWritePartial(), and MessageBuffer::stallMessage().
void Address::input (std::istream & in)
Definition at line 112 of file Address.cc.
References m_address.
void Address::makeLineAddress ()
Definition at line 45 of file Address.cc.
References RubySystem::getBlockSizeBits(), m_address, and maskLowOrderBits().
Referenced by AddressProfiler::addTraceSample(), PerfectCacheMemory< ENTRY >::changePermission(), line_address(), makeLineAddress(), RubyRequest::RubyRequest(), setOffset(), testAndRead(), and testAndWrite().
void Address::makeNextStrideAddress (int stride)
Definition at line 52 of file Address.cc.
References RubySystem::getBlockSizeBits(), RubySystem::getBlockSizeBytes(), m_address, and maskLowOrderBits().
Referenced by next_stride_address().
physical_address_t Address::maskHighOrderBits (unsigned int number) const [inline]
Definition at line 184 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
physical_address_t Address::maskLowOrderBits (unsigned int number) const [inline]
Definition at line 171 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
Referenced by AddressProfiler::addTraceSample(), makeLineAddress(), makeNextStrideAddress(), Prefetcher::pageAddress(), and print().
int64 Address::memoryModuleIndex () const
Definition at line 59 of file Address.cc.
References ADDRESS_WIDTH, bitSelect(), RubySystem::getBlockSizeBits(), RubySystem::getMemorySizeBits(), and MipsISA::index.
Address & Address::operator= (const Address & obj)
Definition at line 127 of file Address.cc.
References m_address.
void Address::output (std::ostream & out) const
Definition at line 102 of file Address.cc.
References m_address.
void Address::print (std::ostream & out) const
Definition at line 93 of file Address.cc.
References RubySystem::getBlockSizeBits(), m_address, and maskLowOrderBits().
Referenced by operator<<().
void Address::setAddress (physical_address_t address) [inline]
Definition at line 60 of file Address.hh.
References m_address.
Referenced by AbstractCacheEntry::AbstractCacheEntry(), and CheckTable::CheckTable().
void Address::setOffset (int offset) [inline]
Definition at line 81 of file Address.hh.
References m_address, and makeLineAddress().
Referenced by setOffset().
physical_address_t Address::shiftLowOrderBits (unsigned int number) const [inline]
Definition at line 197 of file Address.hh.
References m_address.
Member Data Documentation
physical_address_t Address::m_address [private]
Definition at line 89 of file Address.hh.
Referenced by Address(), bitRemove(), bitSelect(), getAddress(), input(), makeLineAddress(), makeNextStrideAddress(), maskHighOrderBits(), maskLowOrderBits(), operator=(), output(), print(), setAddress(), setOffset(), and shiftLowOrderBits().
The documentation for this class was generated from the following files:
mem/ruby/common/Address.hh
mem/ruby/common/Address.cc