gem5: ProbeManager Class Reference
ProbeManager Class Reference
ProbeManager is a conduit class that lives on each SimObject, and is used to match up probe listeners with probe points.
#include <probe.hh>
Public Member Functions
ProbeManager (SimObject *obj)
virtual ~ProbeManager ()
bool addListener (std::string pointName, ProbeListener &listener)
Add a ProbeListener to the ProbePoint named by pointName.
bool removeListener (std::string pointName, ProbeListener &listener)
Remove a ProbeListener from the ProbePoint named by pointName.
void addPoint (ProbePoint &point)
Add a ProbePoint to this SimObject ProbeManager.
Private Attributes
const M5_CLASS_VAR_USED SimObject * object
Required for sensible debug messages.
std::vector< ProbePoint * > points
Vector for name look-up.
Detailed Description
ProbeManager is a conduit class that lives on each SimObject, and is used to match up probe listeners with probe points.
Definition at line 151 of file probe.hh.
Constructor & Destructor Documentation
ProbeManager::ProbeManager (SimObject * obj) [inline]
Definition at line 160 of file probe.hh.
virtual ProbeManager::~ProbeManager () [inline, virtual]
Definition at line 163 of file probe.hh.
Member Function Documentation
bool ProbeManager::addListener (std::string pointName, ProbeListener & listener)
Add a ProbeListener to the ProbePoint named by pointName.
If the name doesn't resolve a ProbePoint return false.
Parameters:
pointName the name of the ProbePoint to add the ProbeListener to.
listener the ProbeListener to add.
Returns:
true if added, false otherwise.
Definition at line 83 of file probe.cc.
References DPRINTFR, SimObject::name(), object, MipsISA::p, and points.
Referenced by ProbeListener::ProbeListener().
void ProbeManager::addPoint (ProbePoint & point)
Add a ProbePoint to this SimObject ProbeManager.
Parameters:
point the ProbePoint to add.
Definition at line 117 of file probe.cc.
References DPRINTFR, ProbePoint::getName(), MipsISA::p, and points.
Referenced by ProbePoint::ProbePoint().
bool ProbeManager::removeListener (std::string pointName, ProbeListener & listener)
Remove a ProbeListener from the ProbePoint named by pointName.
If the name doesn't resolve a ProbePoint return false.
Parameters:
pointName the name of the ProbePoint to remove the ProbeListener from.
listener the ProbeListener to remove.
Returns:
true if removed, false otherwise.
Definition at line 100 of file probe.cc.
References DPRINTFR, SimObject::name(), object, MipsISA::p, and points.
Referenced by ProbeListener::~ProbeListener().
Member Data Documentation
const M5_CLASS_VAR_USED SimObject* ProbeManager::object [private]
Required for sensible debug messages.
Definition at line 155 of file probe.hh.
Referenced by addListener(), and removeListener().
std::vector<ProbePoint *> ProbeManager::points [private]
Vector for name look-up.
Definition at line 157 of file probe.hh.
Referenced by addListener(), addPoint(), and removeListener().
The documentation for this class was generated from the following files:
sim/probe/probe.hh
sim/probe/probe.cc