gem5: SrcClockDomain Class Reference
SrcClockDomain Class Reference
The source clock domains provides the notion of a clock domain that is connected to a tunable clock source.
#include <clock_domain.hh>
Public Types
typedef SrcClockDomainParams Params
typedef int32_t DomainID
typedef uint32_t PerfLevel
Public Member Functions
SrcClockDomain (const Params *p)
void clockPeriod (Tick clock_period)
Set new clock value.
uint32_t domainID () const
bool validPerfLevel (PerfLevel perf_level) const
Checks whether the performance level requested exists in the current domain configuration.
void perfLevel (PerfLevel perf_level)
Sets the current performance level of the domain.
PerfLevel perfLevel () const
PerfLevel numPerfLevels () const
Get the number of available performance levels for this clock domain.
Tick clkPeriodAtPerfLevel () const
Tick clkPeriodAtPerfLevel (PerfLevel perf_level) const
void startup ()
startup() is the final initialization call before simulation.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Static Public Attributes
static const DomainID emptyDomainID = -1
Private Attributes
const std::vector< Tick > freqOpPoints
List of possible frequency operational points, should be in descending order An empty list corresponds to default frequency specified for its clock domain, overall implying NO DVFS.
const uint32_t _domainID
Software recognizable id number for the domain, should be unique for each domain.
PerfLevel _perfLevel
Current performance level the domain is set to.
Detailed Description
The source clock domains provides the notion of a clock domain that is connected to a tunable clock source.
It maintains the clock period and provides methods for setting/getting the clock and configuration parameters for clock domain that handler is going to manage. This includes frequency values at various performance levels, domain id, and current performance level. Note that a performance level as requested by the software corresponds to one of the frequency operational points the domain can operate at.
Definition at line 171 of file clock_domain.hh.
Member Typedef Documentation
typedef int32_t SrcClockDomain::DomainID
Definition at line 188 of file clock_domain.hh.
typedef SrcClockDomainParams SrcClockDomain::Params
Reimplemented from ClockDomain.
Definition at line 176 of file clock_domain.hh.
typedef uint32_t SrcClockDomain::PerfLevel
Definition at line 196 of file clock_domain.hh.
Constructor & Destructor Documentation
SrcClockDomain::SrcClockDomain (const Params * p)
Definition at line 76 of file clock_domain.cc.
References _domainID, _perfLevel, ClockDomain::clockPeriod(), fatal_if, freqOpPoints, SimObject::name(), VoltageDomain::numVoltages(), and VoltageDomain::registerSrcClockDom().
Member Function Documentation
Tick SrcClockDomain::clkPeriodAtPerfLevel (PerfLevel perf_level) const [inline]
Definition at line 234 of file clock_domain.hh.
References freqOpPoints, and validPerfLevel().
Tick SrcClockDomain::clkPeriodAtPerfLevel () const [inline]
Returns:
the clock period (expressed in ticks) for the current performance level
Definition at line 232 of file clock_domain.hh.
References freqOpPoints, and perfLevel().
Referenced by DVFSHandler::clkPeriodAtPerfLevel(), and perfLevel().
void SrcClockDomain::clockPeriod (Tick clock_period)
Set new clock value.
Parameters:
clock The new clock period in ticks
Definition at line 111 of file clock_domain.cc.
References ClockDomain::_clockPeriod, ArmISA::c, ClockDomain::children, DPRINTF, fatal, ArmISA::m, ClockDomain::members, and SimObject::name().
uint32_t SrcClockDomain::domainID () const [inline]
Returns:
the domainID of the domain
Definition at line 194 of file clock_domain.hh.
References _domainID.
Referenced by DVFSHandler::DVFSHandler(), perfLevel(), and VoltageDomain::sanitiseVoltages().
PerfLevel SrcClockDomain::numPerfLevels () const [inline]
Get the number of available performance levels for this clock domain.
Returns:
Number of perf levels configured for this domain.
Definition at line 226 of file clock_domain.hh.
References freqOpPoints.
Referenced by DVFSHandler::clkPeriodAtPerfLevel(), DVFSHandler::numPerfLevels(), and validPerfLevel().
PerfLevel SrcClockDomain::perfLevel () const [inline]
Returns:
the current performance level of the domain
Definition at line 219 of file clock_domain.hh.
References _perfLevel.
Referenced by clkPeriodAtPerfLevel(), and startup().
void SrcClockDomain::perfLevel (PerfLevel perf_level)
Sets the current performance level of the domain.
Parameters:
perf_level the target performance level
Definition at line 135 of file clock_domain.cc.
References _perfLevel, clkPeriodAtPerfLevel(), ClockDomain::clockPeriod(), domainID(), DPRINTF, SimObject::name(), VoltageDomain::sanitiseVoltages(), validPerfLevel(), and ClockDomain::voltageDomain().
Referenced by DVFSHandler::perfLevel(), and VoltageDomain::sanitiseVoltages().
void SrcClockDomain::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 159 of file clock_domain.cc.
References _perfLevel, and SERIALIZE_SCALAR.
void SrcClockDomain::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 173 of file clock_domain.cc.
References _perfLevel, and perfLevel().
void SrcClockDomain::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 166 of file clock_domain.cc.
References _perfLevel, and UNSERIALIZE_SCALAR.
bool SrcClockDomain::validPerfLevel (PerfLevel perf_level) const [inline]
Checks whether the performance level requested exists in the current domain configuration.
Parameters:
the target performance level of the domain
Returns:
validity status of the given performance level
Definition at line 205 of file clock_domain.hh.
References numPerfLevels().
Referenced by clkPeriodAtPerfLevel(), and perfLevel().
Member Data Documentation
const uint32_t SrcClockDomain::_domainID [private]
Software recognizable id number for the domain, should be unique for each domain.
Definition at line 257 of file clock_domain.hh.
Referenced by domainID(), and SrcClockDomain().
PerfLevel SrcClockDomain::_perfLevel [private]
Current performance level the domain is set to.
The performance level corresponds to one selected frequency (and related voltage) from the supplied list of frequencies, with perfLevel = 0 being the fastest performance state.
Definition at line 265 of file clock_domain.hh.
Referenced by perfLevel(), serialize(), SrcClockDomain(), startup(), and unserialize().
const DomainID SrcClockDomain::emptyDomainID = -1 [static]
Definition at line 189 of file clock_domain.hh.
Referenced by DVFSHandler::DVFSHandler().
const std::vector<Tick> SrcClockDomain::freqOpPoints [private]
List of possible frequency operational points, should be in descending order An empty list corresponds to default frequency specified for its clock domain, overall implying NO DVFS.
Definition at line 251 of file clock_domain.hh.
Referenced by clkPeriodAtPerfLevel(), numPerfLevels(), and SrcClockDomain().
The documentation for this class was generated from the following files:
sim/clock_domain.hh
sim/clock_domain.cc