gem5: AtomicSimpleCPU Class Reference
AtomicSimpleCPU Class Reference
#include <atomic.hh>
Classes
class AtomicCPUDPort
class AtomicCPUPort
An AtomicCPUPort overrides the default behaviour of the recvAtomicSnoop and ignores the packet instead of panicking.
struct TickEvent
Public Member Functions
AtomicSimpleCPU (AtomicSimpleCPUParams *params)
virtual ~AtomicSimpleCPU ()
virtual void init ()
unsigned int drain (DrainManager *drain_manager)
void drainResume ()
void switchOut ()
void takeOverFrom (BaseCPU *oldCPU)
void verifyMemoryMode () const
virtual void activateContext (ThreadID thread_num)
virtual void suspendContext (ThreadID thread_num)
Fault readMem (Addr addr, uint8_t *data, unsigned size, unsigned flags)
Fault writeMem (uint8_t *data, unsigned size, Addr addr, unsigned flags, uint64_t *res)
virtual void regProbePoints ()
void printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
Public Attributes
std::ostream * fraccpu
Protected Member Functions
virtual MasterPort & getDataPort ()
Return a reference to the data port.
virtual MasterPort & getInstPort ()
Return a reference to the instruction port.
Private Member Functions
void tick ()
bool isDrained ()
Check if a system is in a drained state.
bool tryCompleteDrain ()
Try to complete a drain request.
Private Attributes
TickEvent tickEvent
const int width
bool locked
const bool simulate_data_stalls
const bool simulate_inst_stalls
DrainManager * drain_manager
Drain manager to use when signaling drain completion.
AtomicCPUPort icachePort
AtomicCPUDPort dcachePort
bool fastmem
Request ifetch_req
Request data_read_req
Request data_write_req
bool dcache_access
Tick dcache_latency
ProbePointArg< std::pair
< SimpleThread *, const
StaticInstPtr > > * ppCommit
Probe Points.
Detailed Description
Definition at line 51 of file atomic.hh.
Constructor & Destructor Documentation
AtomicSimpleCPU::AtomicSimpleCPU (AtomicSimpleCPUParams * params)
Definition at line 107 of file atomic.cc.
References BaseSimpleCPU::_status, OutputDirectory::directory(), fraccpu, BaseSimpleCPU::Idle, name(), OutputDirectory::openFile(), and simout.
AtomicSimpleCPU::~AtomicSimpleCPU () [virtual]
Definition at line 125 of file atomic.cc.
References Event::scheduled(), and tickEvent.
Member Function Documentation
void AtomicSimpleCPU::activateContext (ThreadID thread_num) [virtual]
Definition at line 229 of file atomic.cc.
References BaseSimpleCPU::_status, DPRINTF, BaseSimpleCPU::Idle, ThreadState::lastActivate, ThreadState::lastSuspend, BaseSimpleCPU::notIdleFraction, BaseSimpleCPU::Running, Event::scheduled(), BaseSimpleCPU::thread, and tickEvent.
unsigned int AtomicSimpleCPU::drain (DrainManager * drain_manager)
Definition at line 133 of file atomic.cc.
References DPRINTF, drain_manager, isDrained(), BaseSimpleCPU::pcState(), Event::scheduled(), and tickEvent.
void AtomicSimpleCPU::drainResume ()
Definition at line 153 of file atomic.cc.
References BaseSimpleCPU::_status, ThreadContext::Active, DPRINTF, drain_manager, fatal, BaseSimpleCPU::Idle, BaseSimpleCPU::notIdleFraction, BaseSimpleCPU::Running, Event::scheduled(), SimpleThread::status(), BaseSimpleCPU::thread, tickEvent, and verifyMemoryMode().
virtual MasterPort& AtomicSimpleCPU::getDataPort () [inline, protected, virtual]
Return a reference to the data port.
Definition at line 191 of file atomic.hh.
References dcachePort.
virtual MasterPort& AtomicSimpleCPU::getInstPort () [inline, protected, virtual]
Return a reference to the instruction port.
Definition at line 194 of file atomic.hh.
References icachePort.
void AtomicSimpleCPU::init () [virtual]
Definition at line 85 of file atomic.cc.
References ThreadContext::contextId(), data_read_req, data_write_req, FullSystem, ArmISA::i, ifetch_req, AlphaISA::initCPU(), ThreadContext::initMemProxies(), Request::setThreadContext(), BaseSimpleCPU::tc, and BaseSimpleCPU::tcBase().
bool AtomicSimpleCPU::isDrained () [inline, private]
Check if a system is in a drained state.
We need to drain if:
We are in the middle of a microcode sequence as some CPUs (e.g., HW accelerated CPUs) can't be started in the middle of a gem5 microcode sequence.
The CPU is in a LLSC region. This shouldn't normally happen as these are executed atomically within a single tick() call. The only way this can happen at the moment is if there is an event in the PC event queue that affects the CPU state while it is in an LLSC region.
Stay at PC is true.
Definition at line 108 of file atomic.hh.
References locked, BaseSimpleCPU::microPC(), and BaseSimpleCPU::stayAtPC.
Referenced by drain(), switchOut(), and tryCompleteDrain().
void AtomicSimpleCPU::printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
Definition at line 648 of file atomic.cc.
References dcachePort, and MasterPort::printAddr().
Fault AtomicSimpleCPU::readMem (Addr addr, uint8_t * data, unsigned size, unsigned flags)
Definition at line 316 of file atomic.cc.
References curTick(), data_read_req, Packet::dataStatic(), dcache_access, dcache_latency, dcachePort, SimpleThread::dtb, fastmem, fraccpu, Packet::getAddr(), Request::getFlags(), SimpleThread::getTC(), GenericISA::handleIprRead(), AlphaISA::handleLockedRead(), Packet::isError(), Request::isLLSC(), Request::isLockedRMW(), Request::isMmappedIpr(), Request::isPrefetch(), Flags< T >::isSet(), locked, Packet::makeReadCmd(), Request::NO_ACCESS, SimpleThread::pcState(), BaseTLB::Read, roundDown(), MasterPort::sendAtomic(), Trace::InstRecord::setMem(), Request::setVirt(), X86ISA::system, Request::taskId(), BaseSimpleCPU::tc, BaseSimpleCPU::thread, and BaseSimpleCPU::traceData.
void AtomicSimpleCPU::regProbePoints () [virtual]
Definition at line 639 of file atomic.cc.
References ppCommit.
void AtomicSimpleCPU::suspendContext (ThreadID thread_num) [virtual]
Definition at line 251 of file atomic.cc.
References BaseSimpleCPU::_status, DPRINTF, BaseSimpleCPU::Idle, BaseSimpleCPU::notIdleFraction, BaseSimpleCPU::Running, Event::scheduled(), BaseSimpleCPU::thread, and tickEvent.
void AtomicSimpleCPU::switchOut ()
Definition at line 196 of file atomic.cc.
References BaseSimpleCPU::_status, BaseSimpleCPU::Idle, isDrained(), BaseSimpleCPU::Running, Event::scheduled(), and tickEvent.
void AtomicSimpleCPU::takeOverFrom (BaseCPU * oldCPU)
Definition at line 207 of file atomic.cc.
References data_read_req, data_write_req, ifetch_req, Event::scheduled(), Request::setThreadContext(), and tickEvent.
void AtomicSimpleCPU::tick () [private]
Definition at line 521 of file atomic.cc.
References BaseSimpleCPU::_status, BaseSimpleCPU::advancePC(), BaseSimpleCPU::checkForInterrupts(), BaseSimpleCPU::checkPcEventQueue(), BaseSimpleCPU::countInst(), BaseSimpleCPU::curMacroStaticInst, BaseSimpleCPU::curStaticInst, curTick(), Packet::dataStatic(), dcache_access, dcache_latency, divCeil(), DPRINTF, DTRACE, BaseTLB::Execute, fastmem, Packet::getAddr(), ArmISA::i, icachePort, BaseSimpleCPU::Idle, ifetch_req, BaseSimpleCPU::inst, Packet::isError(), isRomMicroPC(), SimpleThread::itb, locked, ProbePointArg< Arg >::notify(), SimpleThread::pcState(), BaseSimpleCPU::pcState(), BaseSimpleCPU::postExecute(), ppCommit, BaseSimpleCPU::preExecute(), MemCmd::ReadReq, MasterPort::sendAtomic(), BaseSimpleCPU::setupFetchRequest(), simulate_data_stalls, simulate_inst_stalls, BaseSimpleCPU::stayAtPC, X86ISA::system, Request::taskId(), BaseSimpleCPU::tc, BaseSimpleCPU::thread, tickEvent, BaseSimpleCPU::traceData, tryCompleteDrain(), and width.
Referenced by AtomicSimpleCPU::TickEvent::process().
bool AtomicSimpleCPU::tryCompleteDrain () [private]
Try to complete a drain request.
Returns:
true if the CPU is drained, false otherwise.
Definition at line 178 of file atomic.cc.
References DPRINTF, drain_manager, isDrained(), BaseSimpleCPU::pcState(), and DrainManager::signalDrainDone().
Referenced by tick().
void AtomicSimpleCPU::verifyMemoryMode () const
Definition at line 220 of file atomic.cc.
References fatal, and X86ISA::system.
Referenced by drainResume().
Fault AtomicSimpleCPU::writeMem (uint8_t * data, unsigned size, Addr addr, unsigned flags, uint64_t * res)
Definition at line 405 of file atomic.cc.
References Request::CACHE_BLOCK_ZERO, AtomicSimpleCPU::AtomicCPUDPort::cacheBlockMask, curTick(), data_write_req, Packet::dataStatic(), dcache_access, dcache_latency, dcachePort, SimpleThread::dtb, fastmem, fraccpu, Packet::getAddr(), Packet::getConstPtr(), Request::getExtraData(), Request::getFlags(), SimpleThread::getTC(), GenericISA::handleIprWrite(), AlphaISA::handleLockedWrite(), Request::isCondSwap(), Packet::isError(), Request::isLLSC(), Request::isLockedRMW(), Request::isMmappedIpr(), Request::isPrefetch(), Flags< T >::isSet(), Request::isSwap(), locked, Request::NO_ACCESS, SimpleThread::pcState(), roundDown(), MasterPort::sendAtomic(), Request::setExtraData(), Trace::InstRecord::setMem(), Request::setVirt(), MemCmd::StoreCondReq, MemCmd::SwapReq, X86ISA::system, Request::taskId(), BaseSimpleCPU::tc, BaseSimpleCPU::thread, BaseSimpleCPU::traceData, BaseTLB::Write, and MemCmd::WriteReq.
Member Data Documentation
Request AtomicSimpleCPU::data_read_req [private]
Definition at line 179 of file atomic.hh.
Referenced by init(), readMem(), and takeOverFrom().
Request AtomicSimpleCPU::data_write_req [private]
Definition at line 180 of file atomic.hh.
Referenced by init(), takeOverFrom(), and writeMem().
bool AtomicSimpleCPU::dcache_access [private]
Definition at line 182 of file atomic.hh.
Referenced by readMem(), tick(), and writeMem().
Tick AtomicSimpleCPU::dcache_latency [private]
Definition at line 183 of file atomic.hh.
Referenced by readMem(), tick(), and writeMem().
AtomicCPUDPort AtomicSimpleCPU::dcachePort [private]
Definition at line 175 of file atomic.hh.
Referenced by getDataPort(), printAddr(), readMem(), and writeMem().
DrainManager* AtomicSimpleCPU::drain_manager [private]
Drain manager to use when signaling drain completion.
This pointer is non-NULL when draining and NULL otherwise.
Definition at line 85 of file atomic.hh.
Referenced by drain(), drainResume(), and tryCompleteDrain().
bool AtomicSimpleCPU::fastmem [private]
Definition at line 177 of file atomic.hh.
Referenced by readMem(), tick(), and writeMem().
std::ostream* AtomicSimpleCPU::fraccpu
Definition at line 55 of file atomic.hh.
Referenced by AtomicSimpleCPU(), readMem(), and writeMem().
AtomicCPUPort AtomicSimpleCPU::icachePort [private]
Definition at line 174 of file atomic.hh.
Referenced by getInstPort(), and tick().
Request AtomicSimpleCPU::ifetch_req [private]
Definition at line 178 of file atomic.hh.
Referenced by init(), takeOverFrom(), and tick().
bool AtomicSimpleCPU::locked [private]
Definition at line 76 of file atomic.hh.
Referenced by isDrained(), readMem(), tick(), and writeMem().
ProbePointArg<std::pair<SimpleThread*, const StaticInstPtr> >* AtomicSimpleCPU::ppCommit [private]
Probe Points.
Definition at line 186 of file atomic.hh.
Referenced by regProbePoints(), and tick().
const bool AtomicSimpleCPU::simulate_data_stalls [private]
Definition at line 77 of file atomic.hh.
Referenced by tick().
const bool AtomicSimpleCPU::simulate_inst_stalls [private]
Definition at line 78 of file atomic.hh.
Referenced by tick().
TickEvent AtomicSimpleCPU::tickEvent [private]
Definition at line 73 of file atomic.hh.
Referenced by activateContext(), drain(), drainResume(), suspendContext(), switchOut(), takeOverFrom(), tick(), and ~AtomicSimpleCPU().
const int AtomicSimpleCPU::width [private]
Definition at line 75 of file atomic.hh.
Referenced by tick().
The documentation for this class was generated from the following files:
cpu/simple/atomic.hh
cpu/simple/atomic.cc