gem5: Intel8254Timer::Counter::CounterEvent Class Reference
Intel8254Timer::Counter::CounterEvent Class Reference
Event for counter interrupt.
Public Member Functions
CounterEvent (Counter *)
void process ()
Event process.
virtual const char * description () const
Event description.
void setTo (int clocks)
int clocksLeft ()
Tick getInterval ()
Private Attributes
Counter * counter
Pointer back to Counter.
Tick interval
Friends
class Counter
All counters are of 64-bit values.
Detailed Description
Event for counter interrupt.
Definition at line 84 of file intel_8254_timer.hh.
Constructor & Destructor Documentation
Intel8254Timer::Counter::CounterEvent::CounterEvent (Counter * c_ptr)
Definition at line 278 of file intel_8254_timer.cc.
References Intel8254Timer::counter, CounterEvent(), interval, and SimClock::Float::s.
Referenced by CounterEvent().
Member Function Documentation
int Intel8254Timer::Counter::CounterEvent::clocksLeft ()
Definition at line 312 of file intel_8254_timer.cc.
References clocksLeft(), curTick(), interval, Event::scheduled(), and Event::when().
Referenced by clocksLeft().
const char * Intel8254Timer::Counter::CounterEvent::description () const [virtual]
Event description.
Reimplemented from Event.
Definition at line 320 of file intel_8254_timer.cc.
Tick Intel8254Timer::Counter::CounterEvent::getInterval ()
Definition at line 326 of file intel_8254_timer.cc.
References getInterval(), and interval.
Referenced by getInterval().
void Intel8254Timer::Counter::CounterEvent::process () [virtual]
Event process.
Implements Event.
Definition at line 285 of file intel_8254_timer.cc.
References Intel8254Timer::counter, Intel8254Timer::counterInterrupt(), Intel8254Timer::InitTc, Intel8254Timer::Counter::mode, Intel8254Timer::Counter::num, Intel8254Timer::Counter::output_high, panic, Intel8254Timer::Counter::parent, Intel8254Timer::Counter::period, Intel8254Timer::RateGen, setTo(), and Intel8254Timer::SquareWave.
void Intel8254Timer::Counter::CounterEvent::setTo (int clocks)
Definition at line 302 of file intel_8254_timer.cc.
References Intel8254Timer::counter, curTick(), DPRINTF, interval, panic, Intel8254Timer::Counter::parent, EventManager::schedule(), and setTo().
Referenced by process(), and setTo().
Friends And Related Function Documentation
friend class Counter [friend]
All counters are of 64-bit values.
Not much excuse for not using a 64-bit integer here, but if you're desperate and only run short simulations you could make this 32 bits.
Definition at line 100 of file intel_8254_timer.hh.
Member Data Documentation
Counter* Intel8254Timer::Counter::CounterEvent::counter [private]
Pointer back to Counter.
Definition at line 88 of file intel_8254_timer.hh.
Tick Intel8254Timer::Counter::CounterEvent::interval [private]
Definition at line 89 of file intel_8254_timer.hh.
Referenced by clocksLeft(), CounterEvent(), getInterval(), and setTo().
The documentation for this class was generated from the following files:
dev/intel_8254_timer.hh
dev/intel_8254_timer.cc