gem5: Stats::VectorProxy< Stat > Class Template Reference
Stats::VectorProxy< Stat > Class Template Reference
#include <statistics.hh>
Public Member Functions
const VResult & result () const
Result total () const
VectorProxy (Stat &s, off_type o, size_type l)
VectorProxy (const VectorProxy &sp)
const VectorProxy & operator= (const VectorProxy &sp)
ScalarProxy< Stat > operator[] (off_type index)
size_type size () const
Private Member Functions
Stat::Storage * data (off_type index)
const Stat::Storage * data (off_type index) const
Private Attributes
Stat & stat
off_type offset
size_type len
VResult vec
Detailed Description
template<class Stat>
class Stats::VectorProxy< Stat >
Definition at line 1135 of file statistics.hh.
Constructor & Destructor Documentation
template<class Stat > Stats::VectorProxy< Stat >::VectorProxy (Stat & s, off_type o, size_type l) [inline]
Definition at line 1181 of file statistics.hh.
template<class Stat > Stats::VectorProxy< Stat >::VectorProxy (const VectorProxy< Stat > & sp) [inline]
Definition at line 1186 of file statistics.hh.
Member Function Documentation
template<class Stat > const Stat::Storage* Stats::VectorProxy< Stat >::data (off_type index) const [inline, private]
Definition at line 1153 of file statistics.hh.
References Stats::VectorProxy< Stat >::len, Stats::VectorProxy< Stat >::offset, and Stats::VectorProxy< Stat >::stat.
template<class Stat > Stat::Storage* Stats::VectorProxy< Stat >::data (off_type index) [inline, private]
Definition at line 1146 of file statistics.hh.
References Stats::VectorProxy< Stat >::len, Stats::VectorProxy< Stat >::offset, and Stats::VectorProxy< Stat >::stat.
Referenced by Stats::VectorProxy< Stat >::result(), and Stats::VectorProxy< Stat >::total().
template<class Stat > const VectorProxy& Stats::VectorProxy< Stat >::operator= (const VectorProxy< Stat > & sp) [inline]
Definition at line 1192 of file statistics.hh.
References Stats::VectorProxy< Stat >::len, Stats::VectorProxy< Stat >::offset, and Stats::VectorProxy< Stat >::stat.
template<class Stat > ScalarProxy<Stat> Stats::VectorProxy< Stat >::operator[] (off_type index) [inline]
Definition at line 1201 of file statistics.hh.
References Stats::VectorProxy< Stat >::offset, Stats::VectorProxy< Stat >::size(), and Stats::VectorProxy< Stat >::stat.
template<class Stat > const VResult& Stats::VectorProxy< Stat >::result () const [inline]
Definition at line 1161 of file statistics.hh.
References Stats::VectorProxy< Stat >::data(), ArmISA::i, Stats::VectorProxy< Stat >::size(), and Stats::VectorProxy< Stat >::vec.
template<class Stat > size_type Stats::VectorProxy< Stat >::size () const [inline]
Definition at line 1207 of file statistics.hh.
References Stats::VectorProxy< Stat >::len.
Referenced by Stats::VectorProxy< Stat >::operator[](), Stats::VectorProxy< Stat >::result(), and Stats::VectorProxy< Stat >::total().
template<class Stat > Result Stats::VectorProxy< Stat >::total () const [inline]
Definition at line 1172 of file statistics.hh.
References Stats::VectorProxy< Stat >::data(), ArmISA::i, and Stats::VectorProxy< Stat >::size().
Member Data Documentation
template<class Stat > size_type Stats::VectorProxy< Stat >::len [private]
Definition at line 1140 of file statistics.hh.
Referenced by Stats::VectorProxy< Stat >::data(), Stats::VectorProxy< Stat >::operator=(), and Stats::VectorProxy< Stat >::size().
template<class Stat > off_type Stats::VectorProxy< Stat >::offset [private]
Definition at line 1139 of file statistics.hh.
Referenced by Stats::VectorProxy< Stat >::data(), Stats::VectorProxy< Stat >::operator=(), and Stats::VectorProxy< Stat >::operator[]().
template<class Stat > Stat& Stats::VectorProxy< Stat >::stat [private]
Definition at line 1138 of file statistics.hh.
Referenced by Stats::VectorProxy< Stat >::data(), Stats::VectorProxy< Stat >::operator=(), and Stats::VectorProxy< Stat >::operator[]().
template<class Stat > VResult Stats::VectorProxy< Stat >::vec [mutable, private]
Definition at line 1143 of file statistics.hh.
Referenced by Stats::VectorProxy< Stat >::result().
The documentation for this class was generated from the following file:
base/statistics.hh