gem5: MipsISA::ISA::CP0Event Class Reference
MipsISA::ISA::CP0Event Class Reference
#include <isa.hh>
Public Member Functions
CP0Event (CP0 *_cp0, BaseCPU *_cpu, CP0EventType e_type)
Constructs a CP0 event.
virtual void process ()
Process this event.
const char * description () const
Returns the description of this event.
void scheduleEvent (Cycles delay)
Schedule This Event.
void unscheduleEvent ()
Unschedule This Event.
Protected Attributes
ISA::CP0 * cp0
BaseCPU * cpu
CP0EventType cp0EventType
Fault fault
Detailed Description
Definition at line 121 of file isa.hh.
Constructor & Destructor Documentation
MipsISA::ISA::CP0Event::CP0Event (CP0 * _cp0, BaseCPU * _cpu, CP0EventType e_type)
Constructs a CP0 event.
Definition at line 559 of file isa.cc.
Member Function Documentation
const char * MipsISA::ISA::CP0Event::description () const [virtual]
Returns the description of this event.
Reimplemented from Event.
Definition at line 575 of file isa.cc.
void MipsISA::ISA::CP0Event::process () [virtual]
Process this event.
Implements Event.
Definition at line 564 of file isa.cc.
References cp0, cp0EventType, cpu, MipsISA::ISA::UpdateCP0, and MipsISA::ISA::updateCPU().
void MipsISA::ISA::CP0Event::scheduleEvent (Cycles delay)
Schedule This Event.
Definition at line 581 of file isa.cc.
References cpu.
void MipsISA::ISA::CP0Event::unscheduleEvent ()
Unschedule This Event.
Definition at line 587 of file isa.cc.
References Event::scheduled(), and Event::squash().
Member Data Documentation
ISA::CP0* MipsISA::ISA::CP0Event::cp0 [protected]
Definition at line 124 of file isa.hh.
Referenced by process().
CP0EventType MipsISA::ISA::CP0Event::cp0EventType [protected]
Definition at line 126 of file isa.hh.
Referenced by process().
BaseCPU* MipsISA::ISA::CP0Event::cpu [protected]
Definition at line 125 of file isa.hh.
Referenced by process(), and scheduleEvent().
Fault MipsISA::ISA::CP0Event::fault [protected]
Definition at line 127 of file isa.hh.
The documentation for this class was generated from the following files:
arch/mips/isa.hh
arch/mips/isa.cc