gem5: Minor::Decode Class Reference
Minor::Decode Class Reference
#include <decode.hh>
Public Member Functions
Decode (const std::string &name, MinorCPU &cpu_, MinorCPUParams &params, Latch< ForwardInstData >::Output inp_, Latch< ForwardInstData >::Input out_, Reservable &next_stage_input_buffer)
void evaluate ()
Pass on input/buffer data to the output if you can.
void minorTrace () const
bool isDrained ()
Is this stage drained? For Decoed, draining is initiated by Execute halting Fetch1 causing Fetch2 to naturally drain into Decode and on to Execute which is responsible for actually killing instructions.
Public Attributes
InputBuffer< ForwardInstData > inputBuffer
Protected Member Functions
const ForwardInstData * getInput ()
Get a piece of data to work on, or 0 if there is no data.
void popInput ()
Pop an element off the input buffer, if there are any.
Protected Attributes
MinorCPU & cpu
Pointer back to the containing CPU.
Latch< ForwardInstData >::Output inp
Input port carrying macro instructions from Fetch2.
Latch< ForwardInstData >::Input out
Output port carrying micro-op decomposed instructions to Execute.
Reservable & nextStageReserve
Interface to reserve space in the next stage.
unsigned int outputWidth
Width of output of this stage/input of next in instructions.
bool processMoreThanOneInput
If true, more than one input word can be processed each cycle if there is room in the output to contain its processed data.
unsigned int inputIndex
Data members after this line are cycle-to-cycle state.
bool inMacroop
True when we're in the process of decomposing a micro-op and microopPC will be valid.
TheISA::PCState microopPC
InstSeqNum execSeqNum
Source of execSeqNums to number instructions.
bool blocked
Blocked indication for report.
Detailed Description
Definition at line 62 of file decode.hh.
Constructor & Destructor Documentation
Minor::Decode::Decode (const std::string & name, MinorCPU & cpu_, MinorCPUParams & params, Latch< ForwardInstData >::Output inp_, Latch< ForwardInstData >::Input out_, Reservable & next_stage_input_buffer)
Definition at line 47 of file decode.cc.
References fatal, and outputWidth.
Member Function Documentation
void Minor::Decode::evaluate ()
Pass on input/buffer data to the output if you can.
Definition at line 118 of file decode.cc.
References ActivityRecorder::activateStage(), ActivityRecorder::activity(), MinorCPU::activityRecorder, blocked, Minor::Reservable::canReserve(), Minor::Pipeline::DecodeStageId, DPRINTF, execSeqNum, getInput(), inMacroop, inp, inputBuffer, inputIndex, Minor::ForwardInstData::insts, Minor::ForwardInstData::isBubble(), microopPC, nextStageReserve, out, outputWidth, popInput(), processMoreThanOneInput, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::pushTail(), Minor::Reservable::reserve(), Minor::ForwardInstData::resize(), Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::setTail(), Minor::ForwardInstData::width(), and ArmISA::width.
Referenced by Minor::Pipeline::evaluate().
const ForwardInstData * Minor::Decode::getInput () [protected]
Get a piece of data to work on, or 0 if there is no data.
Definition at line 76 of file decode.cc.
References Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::front(), inputBuffer, and Minor::ForwardInstData::isBubble().
Referenced by evaluate().
bool Minor::Decode::isDrained ()
Is this stage drained? For Decoed, draining is initiated by Execute halting Fetch1 causing Fetch2 to naturally drain into Decode and on to Execute which is responsible for actually killing instructions.
Definition at line 277 of file decode.cc.
References Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), inp, and inputBuffer.
Referenced by Minor::Pipeline::isDrained().
void Minor::Decode::minorTrace () const
Definition at line 283 of file decode.cc.
References blocked, inputBuffer, Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::minorTrace(), MINORTRACE, and out.
Referenced by Minor::Pipeline::minorTrace().
void Minor::Decode::popInput () [protected]
Pop an element off the input buffer, if there are any.
Definition at line 89 of file decode.cc.
References Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::empty(), inMacroop, inputBuffer, inputIndex, and Minor::InputBuffer< ElemType, ReportTraits, BubbleTraits >::pop().
Referenced by evaluate().
Member Data Documentation
bool Minor::Decode::blocked [protected]
Blocked indication for report.
Definition at line 106 of file decode.hh.
Referenced by evaluate(), and minorTrace().
MinorCPU& Minor::Decode::cpu [protected]
Pointer back to the containing CPU.
Definition at line 66 of file decode.hh.
InstSeqNum Minor::Decode::execSeqNum [protected]
Source of execSeqNums to number instructions.
Definition at line 103 of file decode.hh.
Referenced by evaluate().
bool Minor::Decode::inMacroop [protected]
True when we're in the process of decomposing a micro-op and microopPC will be valid.
This is only the case when there isn't sufficient space in Executes input buffer to take the whole of a decomposed instruction and some of that instructions micro-ops must be generated in a later cycle
Definition at line 99 of file decode.hh.
Referenced by evaluate(), and popInput().
Latch<ForwardInstData>::Output Minor::Decode::inp [protected]
Input port carrying macro instructions from Fetch2.
Definition at line 69 of file decode.hh.
Referenced by evaluate(), and isDrained().
InputBuffer<ForwardInstData> Minor::Decode::inputBuffer
Definition at line 85 of file decode.hh.
Referenced by evaluate(), getInput(), isDrained(), minorTrace(), and popInput().
unsigned int Minor::Decode::inputIndex [protected]
Data members after this line are cycle-to-cycle state.
Index into the inputBuffer's head marking the start of unhandled instructions
Definition at line 92 of file decode.hh.
Referenced by evaluate(), and popInput().
TheISA::PCState Minor::Decode::microopPC [protected]
Definition at line 100 of file decode.hh.
Referenced by evaluate().
Reservable& Minor::Decode::nextStageReserve [protected]
Interface to reserve space in the next stage.
Definition at line 74 of file decode.hh.
Referenced by evaluate().
Latch<ForwardInstData>::Input Minor::Decode::out [protected]
Output port carrying micro-op decomposed instructions to Execute.
Definition at line 71 of file decode.hh.
Referenced by evaluate(), and minorTrace().
unsigned int Minor::Decode::outputWidth [protected]
Width of output of this stage/input of next in instructions.
Definition at line 77 of file decode.hh.
Referenced by Decode(), and evaluate().
bool Minor::Decode::processMoreThanOneInput [protected]
If true, more than one input word can be processed each cycle if there is room in the output to contain its processed data.
Definition at line 81 of file decode.hh.
Referenced by evaluate().
The documentation for this class was generated from the following files:
cpu/minor/decode.hh
cpu/minor/decode.cc