gem5: Pl011 Class Reference
Pl011 Class Reference
#include <pl011.hh>
Public Member Functions
Pl011 (const Pl011Params *p)
void serialize (std::ostream &os) M5_ATTR_OVERRIDE
void unserialize (Checkpoint *cp, const std::string &sec) M5_ATTR_OVERRIDE
Tick read (PacketPtr pkt) M5_ATTR_OVERRIDE
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) M5_ATTR_OVERRIDE
Pure virtual function that the device must implement.
void dataAvailable () M5_ATTR_OVERRIDE
Inform the uart that there is data available.
Protected Member Functions
void generateInterrupt ()
Function to generate interrupt.
void setInterrupts (uint16_t ints, uint16_t mask)
Assign new interrupt values and update interrupt signals.
void setInterruptMask (uint16_t mask)
Convenience function to update the interrupt mask.
void raiseInterrupts (uint16_t ints)
Convenience function to raise a new interrupt.
void clearInterrupts (uint16_t ints)
Convenience function to clear interrupts.
const uint16_t maskInt () const
Masked interrupt status register.
Protected Attributes
EventWrapper< Pl011,&Pl011::generateInterrupt > intEvent
Wrapper to create an event out of the thing.
uint16_t control
uint16_t fbrd
fractional baud rate divisor.
uint16_t ibrd
integer baud rate divisor.
uint16_t lcrh
Line control register.
uint16_t ifls
interrupt fifo level register.
uint16_t imsc
interrupt mask register.
uint16_t rawInt
raw interrupt status register
BaseGic *const gic
Gic to use for interrupting.
const bool endOnEOT
Should the simulation end on an EOT.
const int intNum
Interrupt number to generate.
const Tick intDelay
Delay before interrupting.
Static Protected Attributes
static const uint64_t AMBA_ID = ULL(0xb105f00d00341011)
static const int UART_DR = 0x000
static const int UART_FR = 0x018
static const int UART_FR_CTS = 0x001
static const int UART_FR_TXFE = 0x080
static const int UART_FR_RXFE = 0x010
static const int UART_IBRD = 0x024
static const int UART_FBRD = 0x028
static const int UART_LCRH = 0x02C
static const int UART_CR = 0x030
static const int UART_IFLS = 0x034
static const int UART_IMSC = 0x038
static const int UART_RIS = 0x03C
static const int UART_MIS = 0x040
static const int UART_ICR = 0x044
static const uint16_t UART_RIINTR = 1 << 0
static const uint16_t UART_CTSINTR = 1 << 1
static const uint16_t UART_CDCINTR = 1 << 2
static const uint16_t UART_DSRINTR = 1 << 3
static const uint16_t UART_RXINTR = 1 << 4
static const uint16_t UART_TXINTR = 1 << 5
static const uint16_t UART_RTINTR = 1 << 6
static const uint16_t UART_FEINTR = 1 << 7
static const uint16_t UART_PEINTR = 1 << 8
static const uint16_t UART_BEINTR = 1 << 9
static const uint16_t UART_OEINTR = 1 << 10
Detailed Description
Definition at line 58 of file pl011.hh.
Constructor & Destructor Documentation
Pl011::Pl011 (const Pl011Params * p)
Definition at line 57 of file pl011.cc.
Member Function Documentation
void Pl011::clearInterrupts (uint16_t ints) [inline, protected]
Convenience function to clear interrupts.
See also:
setInterrupts
Parameters:
ints Set of interrupts to clear
Definition at line 110 of file pl011.hh.
References imsc, rawInt, and setInterrupts().
Referenced by read(), and write().
void Pl011::dataAvailable () [virtual]
Inform the uart that there is data available.
Implements Uart.
Definition at line 236 of file pl011.cc.
References DPRINTF, raiseInterrupts(), UART_RTINTR, and UART_RXINTR.
void Pl011::generateInterrupt () [protected]
Function to generate interrupt.
Definition at line 245 of file pl011.cc.
References DPRINTF, gic, imsc, intNum, maskInt(), rawInt, and BaseGic::sendInt().
const uint16_t Pl011::maskInt () const [inline, protected]
Masked interrupt status register.
Definition at line 113 of file pl011.hh.
References imsc, and rawInt.
Referenced by generateInterrupt(), read(), and setInterrupts().
void Pl011::raiseInterrupts (uint16_t ints) [inline, protected]
Convenience function to raise a new interrupt.
See also:
setInterrupts
Parameters:
ints Set of interrupts to raise
Definition at line 103 of file pl011.hh.
References imsc, rawInt, and setInterrupts().
Referenced by dataAvailable(), and write().
Tick Pl011::read (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 68 of file pl011.cc.
References AMBA_ID, clearInterrupts(), control, Terminal::dataAvailable(), DPRINTF, fbrd, Packet::get(), Packet::getAddr(), Packet::getSize(), ibrd, ifls, imsc, Terminal::in(), lcrh, Packet::makeAtomicResponse(), maskInt(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, rawInt, AmbaDevice::readId(), Packet::set(), Uart::term, UART_CR, UART_DR, UART_FBRD, UART_FR, UART_FR_CTS, UART_FR_RXFE, UART_FR_TXFE, UART_IBRD, UART_IFLS, UART_IMSC, UART_LCRH, UART_MIS, UART_RIS, UART_RTINTR, and UART_RXINTR.
void Pl011::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 275 of file pl011.cc.
References control, DPRINTF, fbrd, ibrd, ifls, imsc, lcrh, paramOut(), rawInt, and SERIALIZE_SCALAR.
void Pl011::setInterruptMask (uint16_t mask) [inline, protected]
Convenience function to update the interrupt mask.
See also:
setInterrupts
Parameters:
mask New interrupt mask
Definition at line 96 of file pl011.hh.
References rawInt, and setInterrupts().
Referenced by write().
void Pl011::setInterrupts (uint16_t ints, uint16_t mask) [protected]
Assign new interrupt values and update interrupt signals.
A new interrupt is scheduled signalled if the set of unmasked interrupts goes empty to non-empty. Conversely, if the set of unmasked interrupts goes from non-empty to empty, the interrupt signal is cleared.
Parameters:
ints New raw interrupt status
mask New interrupt mask
Definition at line 257 of file pl011.cc.
References BaseGic::clearInt(), curTick(), gic, imsc, intDelay, intEvent, intNum, maskInt(), rawInt, EventManager::schedule(), and Event::scheduled().
Referenced by clearInterrupts(), raiseInterrupts(), and setInterruptMask().
void Pl011::unserialize (Checkpoint * cp, const std::string & sec) [virtual]
Reimplemented from Serializable.
Definition at line 290 of file pl011.cc.
References control, DPRINTF, fbrd, ibrd, ifls, imsc, lcrh, paramIn(), rawInt, and UNSERIALIZE_SCALAR.
Tick Pl011::write (PacketPtr pkt) [virtual]
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 160 of file pl011.cc.
References clearInterrupts(), control, DPRINTF, endOnEOT, exitSimLoop(), fbrd, Packet::get(), Packet::getAddr(), Packet::getSize(), ibrd, ifls, lcrh, Packet::makeAtomicResponse(), Terminal::out(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, raiseInterrupts(), setInterruptMask(), Uart::term, UART_CR, UART_DR, UART_FBRD, UART_IBRD, UART_ICR, UART_IFLS, UART_IMSC, UART_LCRH, and UART_TXINTR.
Member Data Documentation
const uint64_t Pl011::AMBA_ID = ULL(0xb105f00d00341011) [static, protected]
Definition at line 119 of file pl011.hh.
Referenced by read().
uint16_t Pl011::control [protected]
Definition at line 147 of file pl011.hh.
Referenced by read(), serialize(), unserialize(), and write().
const bool Pl011::endOnEOT [protected]
Should the simulation end on an EOT.
Definition at line 176 of file pl011.hh.
Referenced by write().
uint16_t Pl011::fbrd [protected]
fractional baud rate divisor.
Not used for anything but reporting written value
Definition at line 151 of file pl011.hh.
Referenced by read(), serialize(), unserialize(), and write().
BaseGic* const Pl011::gic [protected]
Gic to use for interrupting.
Definition at line 173 of file pl011.hh.
Referenced by generateInterrupt(), and setInterrupts().
uint16_t Pl011::ibrd [protected]
integer baud rate divisor.
Not used for anything but reporting written value
Definition at line 155 of file pl011.hh.
Referenced by read(), serialize(), unserialize(), and write().
uint16_t Pl011::ifls [protected]
interrupt fifo level register.
Not used for anything but reporting written value
Definition at line 163 of file pl011.hh.
Referenced by read(), serialize(), unserialize(), and write().
uint16_t Pl011::imsc [protected]
interrupt mask register.
Definition at line 166 of file pl011.hh.
Referenced by clearInterrupts(), generateInterrupt(), maskInt(), raiseInterrupts(), read(), serialize(), setInterrupts(), and unserialize().
const Tick Pl011::intDelay [protected]
Delay before interrupting.
Definition at line 182 of file pl011.hh.
Referenced by setInterrupts().
EventWrapper<Pl011, &Pl011::generateInterrupt> Pl011::intEvent [protected]
Wrapper to create an event out of the thing.
Definition at line 116 of file pl011.hh.
Referenced by setInterrupts().
const int Pl011::intNum [protected]
Interrupt number to generate.
Definition at line 179 of file pl011.hh.
Referenced by generateInterrupt(), and setInterrupts().
uint16_t Pl011::lcrh [protected]
Line control register.
Not used for anything but reporting written value
Definition at line 159 of file pl011.hh.
Referenced by read(), serialize(), unserialize(), and write().
uint16_t Pl011::rawInt [protected]
raw interrupt status register
Definition at line 169 of file pl011.hh.
Referenced by clearInterrupts(), generateInterrupt(), maskInt(), raiseInterrupts(), read(), serialize(), setInterruptMask(), setInterrupts(), and unserialize().
const uint16_t Pl011::UART_BEINTR = 1 << 9 [static, protected]
Definition at line 144 of file pl011.hh.
const uint16_t Pl011::UART_CDCINTR = 1 << 2 [static, protected]
Definition at line 137 of file pl011.hh.
const int Pl011::UART_CR = 0x030 [static, protected]
Definition at line 128 of file pl011.hh.
Referenced by read(), and write().
const uint16_t Pl011::UART_CTSINTR = 1 << 1 [static, protected]
Definition at line 136 of file pl011.hh.
const int Pl011::UART_DR = 0x000 [static, protected]
Definition at line 120 of file pl011.hh.
Referenced by read(), and write().
const uint16_t Pl011::UART_DSRINTR = 1 << 3 [static, protected]
Definition at line 138 of file pl011.hh.
const int Pl011::UART_FBRD = 0x028 [static, protected]
Definition at line 126 of file pl011.hh.
Referenced by read(), and write().
const uint16_t Pl011::UART_FEINTR = 1 << 7 [static, protected]
Definition at line 142 of file pl011.hh.
const int Pl011::UART_FR = 0x018 [static, protected]
Definition at line 121 of file pl011.hh.
Referenced by read().
const int Pl011::UART_FR_CTS = 0x001 [static, protected]
Definition at line 122 of file pl011.hh.
Referenced by read().
const int Pl011::UART_FR_RXFE = 0x010 [static, protected]
Definition at line 124 of file pl011.hh.
Referenced by read().
const int Pl011::UART_FR_TXFE = 0x080 [static, protected]
Definition at line 123 of file pl011.hh.
Referenced by read().
const int Pl011::UART_IBRD = 0x024 [static, protected]
Definition at line 125 of file pl011.hh.
Referenced by read(), and write().
const int Pl011::UART_ICR = 0x044 [static, protected]
Definition at line 133 of file pl011.hh.
Referenced by write().
const int Pl011::UART_IFLS = 0x034 [static, protected]
Definition at line 129 of file pl011.hh.
Referenced by read(), and write().
const int Pl011::UART_IMSC = 0x038 [static, protected]
Definition at line 130 of file pl011.hh.
Referenced by read(), and write().
const int Pl011::UART_LCRH = 0x02C [static, protected]
Definition at line 127 of file pl011.hh.
Referenced by read(), and write().
const int Pl011::UART_MIS = 0x040 [static, protected]
Definition at line 132 of file pl011.hh.
Referenced by read().
const uint16_t Pl011::UART_OEINTR = 1 << 10 [static, protected]
Definition at line 145 of file pl011.hh.
const uint16_t Pl011::UART_PEINTR = 1 << 8 [static, protected]
Definition at line 143 of file pl011.hh.
const uint16_t Pl011::UART_RIINTR = 1 << 0 [static, protected]
Definition at line 135 of file pl011.hh.
const int Pl011::UART_RIS = 0x03C [static, protected]
Definition at line 131 of file pl011.hh.
Referenced by read().
const uint16_t Pl011::UART_RTINTR = 1 << 6 [static, protected]
Definition at line 141 of file pl011.hh.
Referenced by dataAvailable(), and read().
const uint16_t Pl011::UART_RXINTR = 1 << 4 [static, protected]
Definition at line 139 of file pl011.hh.
Referenced by dataAvailable(), and read().
const uint16_t Pl011::UART_TXINTR = 1 << 5 [static, protected]
Definition at line 140 of file pl011.hh.
Referenced by write().
The documentation for this class was generated from the following files:
dev/arm/pl011.hh
dev/arm/pl011.cc