gem5: MipsISA::Interrupts Class Reference
MipsISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
typedef MipsInterruptsParams Params
Public Member Functions
const Params * params () const
Interrupts (Params *p)
void setCPU (BaseCPU *_cpu)
void post (int int_num, ThreadContext *tc)
void post (int int_num, int index)
void clear (int int_num, ThreadContext *tc)
void clear (int int_num, int index)
void clearAll (ThreadContext *tc)
void clearAll ()
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc) const
bool interruptsPending (ThreadContext *tc) const
bool onCpuTimerInterrupt (ThreadContext *tc) const
bool checkInterrupts (ThreadContext *tc) const
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Detailed Description
Definition at line 49 of file interrupts.hh.
Member Typedef Documentation
typedef MipsInterruptsParams MipsISA::Interrupts::Params
Reimplemented from SimObject.
Definition at line 52 of file interrupts.hh.
Constructor & Destructor Documentation
MipsISA::Interrupts::Interrupts (Params * p) [inline]
Definition at line 60 of file interrupts.hh.
Member Function Documentation
bool MipsISA::Interrupts::checkInterrupts (ThreadContext * tc) const [inline]
Definition at line 112 of file interrupts.hh.
References interruptsPending().
void MipsISA::Interrupts::clear (int int_num, int index)
Definition at line 88 of file interrupts.cc.
References fatal.
void MipsISA::Interrupts::clear (int int_num, ThreadContext * tc)
Definition at line 76 of file interrupts.cc.
References DPRINTF, MipsISA::getCauseIP(), MipsISA::NumInterruptLevels, panic, and MipsISA::setCauseIP().
void MipsISA::Interrupts::clearAll ()
Definition at line 102 of file interrupts.cc.
References fatal.
void MipsISA::Interrupts::clearAll (ThreadContext * tc)
Definition at line 94 of file interrupts.cc.
References DPRINTF, and MipsISA::setCauseIP().
Fault MipsISA::Interrupts::getInterrupt (ThreadContext * tc)
Definition at line 110 of file interrupts.cc.
References DPRINTF, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_STATUS, ThreadContext::readMiscRegNoEffect(), and ArmISA::status.
bool MipsISA::Interrupts::interruptsPending (ThreadContext * tc) const
Definition at line 150 of file interrupts.cc.
References DPRINTF, MipsISA::getCauseIP(), MipsISA::MISCREG_INTCTL, onCpuTimerInterrupt(), ThreadContext::readMiscRegNoEffect(), and MipsISA::setCauseIP().
Referenced by checkInterrupts().
bool MipsISA::Interrupts::onCpuTimerInterrupt (ThreadContext * tc) const
Definition at line 134 of file interrupts.cc.
References X86ISA::count, MipsISA::MISCREG_COMPARE, MipsISA::MISCREG_COUNT, and ThreadContext::readMiscRegNoEffect().
Referenced by interruptsPending().
const Params* MipsISA::Interrupts::params () const [inline]
Reimplemented from SimObject.
Definition at line 55 of file interrupts.hh.
References SimObject::_params.
void MipsISA::Interrupts::post (int int_num, int index)
Definition at line 70 of file interrupts.cc.
References fatal.
void MipsISA::Interrupts::post (int int_num, ThreadContext * tc)
Definition at line 58 of file interrupts.cc.
References DPRINTF, MipsISA::getCauseIP(), MipsISA::NumInterruptLevels, panic, and MipsISA::setCauseIP().
void MipsISA::Interrupts::serialize (std::ostream & os) [inline, virtual]
Reimplemented from Serializable.
Definition at line 119 of file interrupts.hh.
References fatal.
void MipsISA::Interrupts::setCPU (BaseCPU * _cpu) [inline]
Definition at line 65 of file interrupts.hh.
void MipsISA::Interrupts::unserialize (Checkpoint * cp, const std::string & section) [inline, virtual]
Reimplemented from Serializable.
Definition at line 125 of file interrupts.hh.
References fatal.
void MipsISA::Interrupts::updateIntrInfo (ThreadContext * tc) const
Definition at line 144 of file interrupts.cc.
The documentation for this class was generated from the following files:
arch/mips/interrupts.hh
arch/mips/interrupts.cc