gem5: VirtIO9PBase Class Reference
VirtIO9PBase Class Reference
This class implements a VirtIO transport layer for the 9p network file system.
#include <fs9p.hh>
Classes
struct Config
VirtIO 9p configuration structure.
class FSQueue
Virtqueue for 9p requests.
Public Types
typedef VirtIO9PBaseParams Params
Public Member Functions
VirtIO9PBase (Params *params)
virtual ~VirtIO9PBase ()
void readConfig (PacketPtr pkt, Addr cfgOffset)
Read from the configuration space of a device.
Protected Member Functions
virtual void recvTMsg (const P9MsgHeader &header, const uint8_t *data, size_t size)=0
Handle incoming 9p RPC message.
void sendRMsg (const P9MsgHeader &header, const uint8_t *data, size_t size)
Send a 9p RPC message reply.
void dumpMsg (const P9MsgHeader &header, const uint8_t *data, size_t size)
Dump a 9p RPC message on the debug output.
Protected Attributes
struct VirtIO9PBase::Config M5_ATTR_PACKED
VirtIO 9p configuration structure.
std::unique_ptr< Config > config
Currently active configuration (host byte order).
FSQueue queue
Static Protected Attributes
static const DeviceId ID_9P = 0x09
VirtIO device ID.
Feature bits
static const FeatureBits F_MOUNT_TAG = 0x01
Device provides a name of the resource in its configuration.
Private Attributes
std::map< P9Tag, VirtDescriptor * > pendingTransactions
Map between 9p transaction tags and descriptors where they appeared.
Detailed Description
This class implements a VirtIO transport layer for the 9p network file system.
The 9p VirtIO transport uses the following queues:
9p requests and replies
Each 9p request and response is sent in its own descriptor chain. The guest initiates a transaction by packing a T message (see the 9p spec) into the first part of a descriptor chain. After the T message, the guest reserves space for the reply (R message) by including one or more writable descriptors. The server replies by writing an R message into the writable descriptors and putting the chain in the used ring (VirtQueue::produceDescriptor()).
See also:
https://github.com/rustyrussell/virtio-spec
https://github.com/ericvh/9p-rfc
https://code.google.com/p/diod/wiki/protocol
Definition at line 109 of file fs9p.hh.
Member Typedef Documentation
typedef VirtIO9PBaseParams VirtIO9PBase::Params
Reimplemented from SimObject.
Reimplemented in VirtIO9PProxy, VirtIO9PDiod, and VirtIO9PSocket.
Definition at line 112 of file fs9p.hh.
Constructor & Destructor Documentation
VirtIO9PBase::VirtIO9PBase (Params * params)
Definition at line 109 of file fs9p.cc.
References config, VirtIODeviceBase::configSize, htov_legacy(), queue, and VirtIODeviceBase::registerQueue().
VirtIO9PBase::~VirtIO9PBase () [virtual]
Definition at line 124 of file fs9p.cc.
Member Function Documentation
void VirtIO9PBase::dumpMsg (const P9MsgHeader & header, const uint8_t * data, size_t size) [protected]
Dump a 9p RPC message on the debug output.
Parameters:
header 9p message header.
data Pointer to data in message.
size Size of data (excluding header)
Definition at line 186 of file fs9p.cc.
References DDUMP, DPRINTF, DTRACE, P9MsgHeader::len, P9MsgInfo::name, P9MsgHeader::tag, and P9MsgHeader::type.
Referenced by VirtIO9PBase::FSQueue::onNotifyDescriptor(), and sendRMsg().
void VirtIO9PBase::readConfig (PacketPtr pkt, Addr cfgOffset) [virtual]
Read from the configuration space of a device.
This method is called by the transport interface to read data from a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning:
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters:
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
Reimplemented from VirtIODeviceBase.
Definition at line 129 of file fs9p.cc.
References config, and VirtIODeviceBase::readConfigBlob().
virtual void VirtIO9PBase::recvTMsg (const P9MsgHeader & header, const uint8_t * data, size_t size) [protected, pure virtual]
Handle incoming 9p RPC message.
Parameters:
header 9p message header.
data Pointer to data in message.
size Size of data (excluding header)
Implemented in VirtIO9PProxy.
Referenced by VirtIO9PBase::FSQueue::onNotifyDescriptor().
void VirtIO9PBase::sendRMsg (const P9MsgHeader & header, const uint8_t * data, size_t size) [protected]
Send a 9p RPC message reply.
Parameters:
header 9p message header.
data Pointer to data in message.
size Size of data (excluding header)
Definition at line 158 of file fs9p.cc.
References VirtDescriptor::chainWrite(), DPRINTF, dumpMsg(), htop9(), VirtDescriptor::isOutgoing(), VirtIODeviceBase::kick(), P9MsgHeader::len, VirtDescriptor::next(), panic, pendingTransactions, VirtQueue::produceDescriptor(), queue, and P9MsgHeader::tag.
Referenced by VirtIO9PProxy::serverDataReady().
Member Data Documentation
std::unique_ptr<Config> VirtIO9PBase::config [protected]
Currently active configuration (host byte order).
Definition at line 131 of file fs9p.hh.
Referenced by readConfig(), and VirtIO9PBase().
const FeatureBits VirtIO9PBase::F_MOUNT_TAG = 0x01 [static, protected]
Device provides a name of the resource in its configuration.
Definition at line 140 of file fs9p.hh.
const DeviceId VirtIO9PBase::ID_9P = 0x09 [static, protected]
VirtIO device ID.
Definition at line 134 of file fs9p.hh.
struct VirtIO9PBase::Config VirtIO9PBase::M5_ATTR_PACKED [protected]
VirtIO 9p configuration structure.
Note:
The fields in this structure depend on the features exposed to the guest.
std::map<P9Tag, VirtDescriptor *> VirtIO9PBase::pendingTransactions [private]
Map between 9p transaction tags and descriptors where they appeared.
When handling asynchronous requests, we need to ensure that replies are posted in the same descriptor as queries. The 9p RPC protocol uses the tag field in the header to match requests and replies, which we use here to find the relevant descriptor.
Definition at line 201 of file fs9p.hh.
Referenced by VirtIO9PBase::FSQueue::onNotifyDescriptor(), and sendRMsg().
FSQueue VirtIO9PBase::queue [protected]
Definition at line 162 of file fs9p.hh.
Referenced by sendRMsg(), and VirtIO9PBase().
The documentation for this class was generated from the following files:
dev/virtio/fs9p.hh
dev/virtio/fs9p.cc