gem5: MipsISA::TlbFault< T > Class Template Reference
MipsISA::TlbFault< T > Class Template Reference
#include <faults.hh>
Protected Member Functions
TlbFault (Addr _asid, Addr _vaddr, Addr _vpn, bool _store)
void setTlbExceptionState (ThreadContext *tc, uint8_t excCode)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
ExcCode code () const
Protected Attributes
Addr asid
Addr vpn
Detailed Description
template<typename T>
class MipsISA::TlbFault< T >
Definition at line 225 of file faults.hh.
Constructor & Destructor Documentation
template<typename T> MipsISA::TlbFault< T >::TlbFault (Addr _asid, Addr _vaddr, Addr _vpn, bool _store) [inline, protected]
Definition at line 231 of file faults.hh.
Member Function Documentation
template<typename T> ExcCode MipsISA::TlbFault< T >::code () const [inline, protected, virtual]
Reimplemented from MipsISA::MipsFault< T >.
Reimplemented in MipsISA::TlbModifiedFault.
Definition at line 267 of file faults.hh.
Referenced by MipsISA::TlbFault< TlbInvalidFault >::invoke().
template<typename T> void MipsISA::TlbFault< T >::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [inline, protected, virtual]
Reimplemented from MipsISA::AddressFault< T >.
Definition at line 253 of file faults.hh.
Referenced by MipsISA::TlbFault< TlbInvalidFault >::invoke().
template<typename T> void MipsISA::TlbFault< T >::setTlbExceptionState (ThreadContext * tc, uint8_t excCode) [inline, protected]
Definition at line 236 of file faults.hh.
Referenced by MipsISA::TlbFault< TlbInvalidFault >::invoke().
Member Data Documentation
template<typename T> Addr MipsISA::TlbFault< T >::asid [protected]
Definition at line 228 of file faults.hh.
Referenced by MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState().
template<typename T> Addr MipsISA::TlbFault< T >::vpn [protected]
Definition at line 229 of file faults.hh.
Referenced by MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState().
The documentation for this class was generated from the following file:
arch/mips/faults.hh