gem5: ArmISA::MacroMemOp Class Reference
ArmISA::MacroMemOp Class Reference
Base class for microcoded integer memory instructions.
#include <macromem.hh>
Protected Member Functions
MacroMemOp (const char *mnem, ExtMachInst machInst, OpClass __opClass, IntRegIndex rn, bool index, bool up, bool user, bool writeback, bool load, uint32_t reglist)
Detailed Description
Base class for microcoded integer memory instructions.
Definition at line 421 of file macromem.hh.
Constructor & Destructor Documentation
ArmISA::MacroMemOp::MacroMemOp (const char * mnem, ExtMachInst machInst, OpClass __opClass, IntRegIndex rn, bool index, bool up, bool user, bool writeback, bool load, uint32_t reglist) [protected]
Definition at line 56 of file macromem.cc.
References X86ISA::addr, bits(), ArmISA::COND_AL, ArmISA::COND_UC, ArmISA::PredOp::condCode, ArmISA::INTREG_PC, ArmISA::INTREG_SP, ArmISA::INTREG_UREG0, ArmISA::INTREG_UREG1, ArmISA::intRegInMode(), ArmISA::PredMacroOp::microOps, ArmISA::MODE_USER, ArmISA::number_of_ones(), ArmISA::PredMacroOp::numMicroops, X86ISA::reg, replaceBits(), and StaticInst::setFlag().
The documentation for this class was generated from the following files:
arch/arm/insts/macromem.hh
arch/arm/insts/macromem.cc