gem5: ArmISA::ArmFaultVals< T > Class Template Reference
ArmISA::ArmFaultVals< T > Class Template Reference
#include <faults.hh>
Public Member Functions
ArmFaultVals (ExtMachInst _machInst=0, uint32_t _iss=0)
FaultName name () const
FaultStat & countStat ()
FaultOffset offset (ThreadContext *tc)
FaultOffset offset64 ()
OperatingMode nextMode ()
virtual bool routeToMonitor (ThreadContext *tc) const
uint8_t armPcOffset (bool isHyp)
uint8_t thumbPcOffset (bool isHyp)
uint8_t armPcElrOffset ()
uint8_t thumbPcElrOffset ()
virtual bool abortDisable (ThreadContext *tc)
virtual bool fiqDisable (ThreadContext *tc)
virtual ExceptionClass ec (ThreadContext *tc) const
virtual uint32_t iss () const
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
template<>
ArmFault::FaultVals vals
Static Protected Attributes
static FaultVals vals
Detailed Description
template<typename T>
class ArmISA::ArmFaultVals< T >
Definition at line 210 of file faults.hh.
Constructor & Destructor Documentation
template<typename T> ArmISA::ArmFaultVals< T >::ArmFaultVals (ExtMachInst _machInst = 0, uint32_t _iss = 0) [inline]
Member Function Documentation
template<typename T> virtual bool ArmISA::ArmFaultVals< T >::abortDisable (ThreadContext * tc) [inline, virtual]
Implements ArmISA::ArmFault.
Reimplemented in ArmISA::AbortFault< T >, ArmISA::Interrupt, ArmISA::FastInterrupt, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 244 of file faults.hh.
template<typename T> uint8_t ArmISA::ArmFaultVals< T >::armPcElrOffset () [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 242 of file faults.hh.
template<typename T> uint8_t ArmISA::ArmFaultVals< T >::armPcOffset (bool isHyp) [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 238 of file faults.hh.
template<typename T> FaultStat& ArmISA::ArmFaultVals< T >::countStat () [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 219 of file faults.hh.
template<typename T> virtual ExceptionClass ArmISA::ArmFaultVals< T >::ec (ThreadContext * tc) const [inline, virtual]
Implements ArmISA::ArmFault.
Reimplemented in ArmISA::UndefinedInstruction, ArmISA::SupervisorCall, ArmISA::SecureMonitorCall, ArmISA::SupervisorTrap, ArmISA::SecureMonitorTrap, ArmISA::HypervisorTrap, ArmISA::PrefetchAbort, and ArmISA::DataAbort.
Definition at line 246 of file faults.hh.
template<typename T> virtual bool ArmISA::ArmFaultVals< T >::fiqDisable (ThreadContext * tc) [inline, virtual]
Implements ArmISA::ArmFault.
Reimplemented in ArmISA::FastInterrupt.
Definition at line 245 of file faults.hh.
template<typename T> virtual uint32_t ArmISA::ArmFaultVals< T >::iss () const [inline, virtual]
Implements ArmISA::ArmFault.
Reimplemented in ArmISA::UndefinedInstruction, ArmISA::SupervisorCall, ArmISA::SecureMonitorCall, ArmISA::AbortFault< T >, ArmISA::DataAbort, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 247 of file faults.hh.
template<typename T> FaultName ArmISA::ArmFaultVals< T >::name () const [inline, virtual]
Implements FaultBase.
Definition at line 218 of file faults.hh.
template<typename T> OperatingMode ArmISA::ArmFaultVals< T >::nextMode () [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 236 of file faults.hh.
template<class T > FaultOffset ArmISA::ArmFaultVals< T >::offset (ThreadContext * tc) [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 853 of file faults.cc.
References ArmISA::cpsr, ArmISA::ArmFault::FaultVals::hypTrappable, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_SPSR_HYP, ArmISA::MODE_HYP, ArmISA::ArmFault::FaultVals::offset, ThreadContext::readMiscReg(), and ArmISA::ArmFaultVals< T >::vals().
template<typename T> FaultOffset ArmISA::ArmFaultVals< T >::offset64 () [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 223 of file faults.hh.
template<typename T> virtual bool ArmISA::ArmFaultVals< T >::routeToMonitor (ThreadContext * tc) const [inline, virtual]
Implements ArmISA::ArmFault.
Reimplemented in ArmISA::PrefetchAbort, ArmISA::DataAbort, ArmISA::Interrupt, ArmISA::FastInterrupt, and ArmISA::SystemError.
Definition at line 237 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::invoke().
template<typename T> uint8_t ArmISA::ArmFaultVals< T >::thumbPcElrOffset () [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 243 of file faults.hh.
template<typename T> uint8_t ArmISA::ArmFaultVals< T >::thumbPcOffset (bool isHyp) [inline, virtual]
Implements ArmISA::ArmFault.
Definition at line 240 of file faults.hh.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< IllegalInstSetStateFault >::vals () [inline]
Definition at line 290 of file faults.cc.
References ArmISA::EC_ILLEGAL_INST, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< ArmSev >::vals () [inline]
Definition at line 285 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< FlushPipe >::vals () [inline]
Definition at line 280 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< SystemError >::vals () [inline]
Definition at line 275 of file faults.cc.
References ArmISA::EC_SERROR, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< SPAlignmentFault >::vals () [inline]
Definition at line 270 of file faults.cc.
References ArmISA::EC_STACK_PTR_ALIGNMENT, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< PCAlignmentFault >::vals () [inline]
Definition at line 265 of file faults.cc.
References ArmISA::EC_PC_ALIGNMENT, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< SecureMonitorTrap >::vals () [inline]
Definition at line 260 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_MON.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< SupervisorTrap >::vals () [inline]
Definition at line 255 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< VirtualFastInterrupt >::vals () [inline]
Definition at line 251 of file faults.cc.
References ArmISA::EC_INVALID, and ArmISA::MODE_FIQ.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< FastInterrupt >::vals () [inline]
Definition at line 247 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_FIQ.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< VirtualInterrupt >::vals () [inline]
Definition at line 243 of file faults.cc.
References ArmISA::EC_INVALID, and ArmISA::MODE_IRQ.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< Interrupt >::vals () [inline]
Definition at line 239 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_IRQ.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< HypervisorTrap >::vals () [inline]
Definition at line 234 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_HYP.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< VirtualDataAbort >::vals () [inline]
Definition at line 230 of file faults.cc.
References ArmISA::EC_INVALID, and ArmISA::MODE_ABORT.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< DataAbort >::vals () [inline]
Definition at line 226 of file faults.cc.
References ArmISA::EC_DATA_ABORT_TO_HYP, and ArmISA::MODE_ABORT.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< PrefetchAbort >::vals () [inline]
Definition at line 222 of file faults.cc.
References ArmISA::EC_PREFETCH_ABORT_TO_HYP, and ArmISA::MODE_ABORT.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< HypervisorCall >::vals () [inline]
Definition at line 218 of file faults.cc.
References ArmISA::EC_HVC, and ArmISA::MODE_HYP.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< SecureMonitorCall >::vals () [inline]
Definition at line 214 of file faults.cc.
References ArmISA::EC_SMC_TO_HYP, and ArmISA::MODE_MON.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< SupervisorCall >::vals () [inline]
Definition at line 210 of file faults.cc.
References ArmISA::EC_SVC_TO_HYP, and ArmISA::MODE_SVC.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< UndefinedInstruction >::vals () [inline]
Definition at line 206 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_UNDEFINED.
template<> ArmFault::FaultVals ArmISA::ArmFaultVals< Reset >::vals () [inline]
Definition at line 200 of file faults.cc.
References ArmISA::EC_UNKNOWN, and ArmISA::MODE_SVC.
Referenced by ArmISA::ArmFaultVals< FastInterrupt >::abortDisable(), ArmISA::ArmFaultVals< FastInterrupt >::armPcElrOffset(), ArmISA::ArmFaultVals< FastInterrupt >::armPcOffset(), ArmISA::ArmFaultVals< FastInterrupt >::countStat(), ArmISA::ArmFaultVals< FastInterrupt >::ec(), ArmISA::ArmFaultVals< FastInterrupt >::fiqDisable(), ArmISA::ArmFaultVals< FastInterrupt >::name(), ArmISA::ArmFaultVals< FastInterrupt >::nextMode(), ArmISA::ArmFaultVals< T >::offset(), ArmISA::ArmFaultVals< FastInterrupt >::offset64(), ArmISA::ArmFaultVals< FastInterrupt >::thumbPcElrOffset(), and ArmISA::ArmFaultVals< FastInterrupt >::thumbPcOffset().
Member Data Documentation
template<typename T> FaultVals ArmISA::ArmFaultVals< T >::vals [static, protected]
Definition at line 213 of file faults.hh.
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc