gem5: SETranslatingPortProxy Class Reference
SETranslatingPortProxy Class Reference
#include <se_translating_port_proxy.hh>
Public Types
enum AllocType { Always, Never, NextPage }
Public Member Functions
SETranslatingPortProxy (MasterPort &port, Process *p, AllocType alloc)
virtual ~SETranslatingPortProxy ()
bool tryReadBlob (Addr addr, uint8_t *p, int size) const
bool tryWriteBlob (Addr addr, const uint8_t *p, int size) const
bool tryMemsetBlob (Addr addr, uint8_t val, int size) const
bool tryWriteString (Addr addr, const char *str) const
bool tryReadString (std::string &str, Addr addr) const
virtual void readBlob (Addr addr, uint8_t *p, int size) const
Read size bytes memory at address and store in p.
virtual void writeBlob (Addr addr, const uint8_t *p, int size) const
Write size bytes from p to address.
virtual void memsetBlob (Addr addr, uint8_t val, int size) const
Fill size bytes starting at addr with byte value val.
void writeString (Addr addr, const char *str) const
void readString (std::string &str, Addr addr) const
Private Attributes
PageTableBase * pTable
Process * process
AllocType allocating
Detailed Description
Definition at line 67 of file se_translating_port_proxy.hh.
Member Enumeration Documentation
enum SETranslatingPortProxy::AllocType
Enumerator:
Always
Never
NextPage
Definition at line 71 of file se_translating_port_proxy.hh.
Constructor & Destructor Documentation
SETranslatingPortProxy::SETranslatingPortProxy (MasterPort & port, Process * p, AllocType alloc)
Definition at line 57 of file se_translating_port_proxy.cc.
SETranslatingPortProxy::~SETranslatingPortProxy () [virtual]
Definition at line 63 of file se_translating_port_proxy.cc.
Member Function Documentation
void SETranslatingPortProxy::memsetBlob (Addr addr, uint8_t v, int size) const [virtual]
Fill size bytes starting at addr with byte value val.
Reimplemented from PortProxy.
Definition at line 154 of file se_translating_port_proxy.cc.
References fatal, and tryMemsetBlob().
Referenced by brkFunc(), and tryMemsetBlob().
void SETranslatingPortProxy::readBlob (Addr addr, uint8_t * p, int size) const [virtual]
Read size bytes memory at address and store in p.
Reimplemented from PortProxy.
Definition at line 85 of file se_translating_port_proxy.cc.
References fatal, and tryReadBlob().
Referenced by BaseBufferArg::copyIn(), futexFunc(), BaseRemoteGDB::read(), tryReadBlob(), tryReadString(), and writevFunc().
void SETranslatingPortProxy::readString (std::string & str, Addr addr) const
Definition at line 212 of file se_translating_port_proxy.cc.
References fatal, and tryReadString().
bool SETranslatingPortProxy::tryMemsetBlob (Addr addr, uint8_t val, int size) const
Definition at line 132 of file se_translating_port_proxy.cc.
References Process::allocateMem(), allocating, Always, memsetBlob(), AlphaISA::PageBytes, process, pTable, roundDown(), and PageTableBase::translate().
Referenced by memsetBlob().
bool SETranslatingPortProxy::tryReadBlob (Addr addr, uint8_t * p, int size) const
Definition at line 67 of file se_translating_port_proxy.cc.
References AlphaISA::PageBytes, pTable, readBlob(), and PageTableBase::translate().
Referenced by readBlob().
bool SETranslatingPortProxy::tryReadString (std::string & str, Addr addr) const
Definition at line 189 of file se_translating_port_proxy.cc.
References ArmISA::c, pTable, readBlob(), PageTableBase::translate(), and MipsISA::vaddr.
Referenced by accessFunc(), chmodFunc(), chownFunc(), fstatat64Func(), lstat64Func(), lstatFunc(), mkdirFunc(), openFunc(), readlinkFunc(), readString(), renameatFunc(), renameFunc(), stat64Func(), statfsFunc(), statFunc(), truncate64Func(), truncateFunc(), unlinkHelper(), and utimesFunc().
bool SETranslatingPortProxy::tryWriteBlob (Addr addr, const uint8_t * p, int size) const
Definition at line 93 of file se_translating_port_proxy.cc.
References Process::allocateMem(), allocating, Always, Process::fixupStackFault(), NextPage, AlphaISA::PageBytes, panic, process, pTable, roundDown(), PageTableBase::translate(), and writeBlob().
Referenced by Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), and writeBlob().
bool SETranslatingPortProxy::tryWriteString (Addr addr, const char * str) const
Definition at line 162 of file se_translating_port_proxy.cc.
References ArmISA::c, pTable, PageTableBase::translate(), MipsISA::vaddr, and writeBlob().
Referenced by writeString().
void SETranslatingPortProxy::writeBlob (Addr addr, const uint8_t * p, int size) const [virtual]
Write size bytes from p to address.
Reimplemented from PortProxy.
Definition at line 125 of file se_translating_port_proxy.cc.
References fatal, and tryWriteBlob().
Referenced by X86ISA::X86LiveProcess::argsInit(), Sparc32LiveProcess::argsInit(), Sparc64LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), BaseBufferArg::copyOut(), copyStringArray(), X86ISA::I386LiveProcess::initState(), X86ISA::X86_64LiveProcess::initState(), ArmLinuxProcess32::initState(), setTLSFunc32(), timeFunc(), tryWriteBlob(), tryWriteString(), and BaseRemoteGDB::write().
void SETranslatingPortProxy::writeString (Addr addr, const char * str) const
Definition at line 182 of file se_translating_port_proxy.cc.
References fatal, and tryWriteString().
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), ArmLiveProcess::argsInit(), and copyStringArray().
Member Data Documentation
AllocType SETranslatingPortProxy::allocating [private]
Definition at line 80 of file se_translating_port_proxy.hh.
Referenced by tryMemsetBlob(), and tryWriteBlob().
Process* SETranslatingPortProxy::process [private]
Definition at line 79 of file se_translating_port_proxy.hh.
Referenced by tryMemsetBlob(), and tryWriteBlob().
PageTableBase* SETranslatingPortProxy::pTable [private]
Definition at line 78 of file se_translating_port_proxy.hh.
Referenced by tryMemsetBlob(), tryReadBlob(), tryReadString(), tryWriteBlob(), and tryWriteString().
The documentation for this class was generated from the following files:
mem/se_translating_port_proxy.hh
mem/se_translating_port_proxy.cc