gem5: Trace::InstPBTrace Class Reference
Trace::InstPBTrace Class Reference
#include <inst_pb_trace.hh>
Public Member Functions
InstPBTrace (const InstPBTraceParams *p)
virtual ~InstPBTrace ()
InstPBTraceRecord * getInstRecord (Tick when, ThreadContext *tc, const StaticInstPtr si, TheISA::PCState pc, const StaticInstPtr mi=NULL) M5_ATTR_OVERRIDE
Protected Member Functions
void createTraceFile (std::string filename)
Create the output file and write the header into it.
void closeStreams ()
If there is a pending message still write it out and then close the file.
void traceInst (ThreadContext *tc, StaticInstPtr si, TheISA::PCState pc)
Write an instruction to the trace file.
void traceMem (StaticInstPtr si, Addr a, Addr s, unsigned f)
Write a memory request to the trace file as part of the cur instruction.
Protected Attributes
ProtoMessage::Inst * curMsg
This is the message were working on writing.
Static Protected Attributes
static ProtoOutputStream * traceStream
One output stream for the entire simulation.
Friends
class InstPBTraceRecord
Detailed Description
Definition at line 85 of file inst_pb_trace.hh.
Constructor & Destructor Documentation
Trace::InstPBTrace::InstPBTrace (const InstPBTraceParams * p)
Definition at line 71 of file inst_pb_trace.cc.
References createTraceFile().
Trace::InstPBTrace::~InstPBTrace () [virtual]
Definition at line 117 of file inst_pb_trace.cc.
References closeStreams().
Member Function Documentation
void Trace::InstPBTrace::closeStreams () [protected]
If there is a pending message still write it out and then close the file.
Definition at line 102 of file inst_pb_trace.cc.
References curMsg, traceStream, and ProtoOutputStream::write().
Referenced by createTraceFile(), and ~InstPBTrace().
void Trace::InstPBTrace::createTraceFile (std::string filename) [protected]
Create the output file and write the header into it.
Parameters:
filename the file to create (if ends with .gz it will be compressed)
Definition at line 79 of file inst_pb_trace.cc.
References closeStreams(), SimClock::Frequency, registerExitCallback(), OutputDirectory::resolve(), simout, traceStream, and ProtoOutputStream::write().
Referenced by InstPBTrace().
InstPBTraceRecord * Trace::InstPBTrace::getInstRecord (Tick when, ThreadContext * tc, const StaticInstPtr si, TheISA::PCState pc, const StaticInstPtr mi = NULL) [virtual]
Implements Trace::InstTracer.
Definition at line 123 of file inst_pb_trace.cc.
References Trace::enabled, and InstPBTraceRecord.
void Trace::InstPBTrace::traceInst (ThreadContext * tc, StaticInstPtr si, TheISA::PCState pc) [protected]
Write an instruction to the trace file.
Parameters:
tc thread context for the cpu ID
si for the machInst and opClass
pc for the PC Addr
Todo:
if we are running multi-threaded I assume we'd need a lock here
Definition at line 135 of file inst_pb_trace.cc.
References bits(), ThreadContext::cpuId(), curMsg, curTick(), traceStream, and ProtoOutputStream::write().
Referenced by Trace::InstPBTraceRecord::dump().
void Trace::InstPBTrace::traceMem (StaticInstPtr si, Addr a, Addr s, unsigned f) [protected]
Write a memory request to the trace file as part of the cur instruction.
Parameters:
si for the machInst and opClass
a address of the request
s size of the request
f flags for the request
Definition at line 156 of file inst_pb_trace.cc.
References curMsg, and panic_if.
Referenced by Trace::InstPBTraceRecord::dump().
Friends And Related Function Documentation
friend class InstPBTraceRecord [friend]
Definition at line 132 of file inst_pb_trace.hh.
Referenced by getInstRecord().
Member Data Documentation
ProtoMessage::Inst* Trace::InstPBTrace::curMsg [protected]
This is the message were working on writing.
The majority of the message exists however the memory accesses will be delayed.
Definition at line 105 of file inst_pb_trace.hh.
Referenced by closeStreams(), traceInst(), and traceMem().
ProtoOutputStream * Trace::InstPBTrace::traceStream [static, protected]
One output stream for the entire simulation.
We encode the CPU & system ID so all we need is a single file
Definition at line 99 of file inst_pb_trace.hh.
Referenced by closeStreams(), createTraceFile(), and traceInst().
The documentation for this class was generated from the following files:
cpu/inst_pb_trace.hh
cpu/inst_pb_trace.cc