gem5: Checkpoint Class Reference
Checkpoint Class Reference
#include <serialize.hh>
Public Member Functions
Checkpoint (const std::string &cpt_dir, SimObjectResolver &resolver)
~Checkpoint ()
bool find (const std::string &section, const std::string &entry, std::string &value)
bool findObj (const std::string &section, const std::string &entry, SimObject *&value)
bool sectionExists (const std::string &section)
Static Public Member Functions
static std::string setDir (const std::string &base_name)
static std::string dir ()
Public Attributes
const std::string cptDir
Static Public Attributes
static const char * baseFilename = "m5.cpt"
Private Attributes
IniFile * db
SimObjectResolver & objNameResolver
Static Private Attributes
static std::string currentDirectory
Detailed Description
Definition at line 294 of file serialize.hh.
Constructor & Destructor Documentation
Checkpoint::Checkpoint (const std::string & cpt_dir, SimObjectResolver & resolver)
Checkpoint::~Checkpoint ()
Definition at line 610 of file serialize.cc.
References db.
Member Function Documentation
string Checkpoint::dir () [static]
Definition at line 595 of file serialize.cc.
References currentDirectory.
bool Checkpoint::find (const std::string & section, const std::string & entry, std::string & value)
Referenced by arrayParamIn(), optParamIn(), and paramIn().
bool Checkpoint::findObj (const std::string & section, const std::string & entry, SimObject *& value)
Referenced by objParamIn().
bool Checkpoint::sectionExists (const std::string & section)
Referenced by SimObject::loadState().
static std::string Checkpoint::setDir (const std::string & base_name) [static]
Member Data Documentation
const char * Checkpoint::baseFilename = "m5.cpt" [static]
Definition at line 340 of file serialize.hh.
const std::string Checkpoint::cptDir
Definition at line 306 of file serialize.hh.
string Checkpoint::currentDirectory [static, private]
Definition at line 325 of file serialize.hh.
Referenced by dir().
IniFile* Checkpoint::db [private]
Definition at line 298 of file serialize.hh.
Referenced by ~Checkpoint().
SimObjectResolver& Checkpoint::objNameResolver [private]
Definition at line 300 of file serialize.hh.
The documentation for this class was generated from the following files:
sim/serialize.hh
sim/serialize.cc