gem5: BasePrefetcher Class Reference
BasePrefetcher Class Reference
#include <base.hh>
Public Member Functions
BasePrefetcher (const BasePrefetcherParams *p)
virtual ~BasePrefetcher ()
void setCache (BaseCache *_cache)
virtual Tick notify (const PacketPtr &pkt)=0
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.
virtual PacketPtr getPacket ()=0
virtual Tick nextPrefetchReadyTime () const =0
virtual void regStats ()
Register statistics for this object.
Protected Member Functions
bool observeAccess (const PacketPtr &pkt) const
Determine if this access should be observed.
bool inCache (Addr addr, bool is_secure) const
Determine if address is in cache.
bool inMissQueue (Addr addr, bool is_secure) const
Determine if address is in cache miss queue.
bool samePage (Addr a, Addr b) const
Determine if addresses are on the same page.
Protected Attributes
BaseCache * cache
Pointr to the parent cache.
unsigned blkSize
The block size of the parent cache.
System * system
System we belong to.
bool onMiss
Only consult prefetcher on cache misses?
bool onRead
Consult prefetcher on reads?
bool onWrite
Consult prefetcher on reads?
bool onData
Consult prefetcher on data accesses?
bool onInst
Consult prefetcher on instruction accesses?
MasterID masterId
Request id for prefetches.
const Addr pageBytes
Stats::Scalar pfIssued
Detailed Description
Definition at line 59 of file base.hh.
Constructor & Destructor Documentation
BasePrefetcher::BasePrefetcher (const BasePrefetcherParams * p)
Definition at line 55 of file base.cc.
virtual BasePrefetcher::~BasePrefetcher () [inline, virtual]
Definition at line 112 of file base.hh.
Member Function Documentation
virtual PacketPtr BasePrefetcher::getPacket () [pure virtual]
Implemented in QueuedPrefetcher.
Referenced by Cache::getNextMSHR().
bool BasePrefetcher::inCache (Addr addr, bool is_secure) const [protected]
Determine if address is in cache.
Definition at line 106 of file base.cc.
References cache, and BaseCache::inCache().
Referenced by QueuedPrefetcher::notify(), and observeAccess().
bool BasePrefetcher::inMissQueue (Addr addr, bool is_secure) const [protected]
Determine if address is in cache miss queue.
Definition at line 115 of file base.cc.
References cache, and BaseCache::inMissQueue().
Referenced by QueuedPrefetcher::notify(), and observeAccess().
virtual Tick BasePrefetcher::nextPrefetchReadyTime () const [pure virtual]
Implemented in QueuedPrefetcher.
Referenced by Cache::nextMSHRReadyTime(), and Cache::recvTimingResp().
virtual Tick BasePrefetcher::notify (const PacketPtr & pkt) [pure virtual]
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.
)
Return values:
Time of next prefetch availability, or MaxTick if none.
Implemented in QueuedPrefetcher.
Referenced by Cache::recvTimingReq().
bool BasePrefetcher::observeAccess (const PacketPtr & pkt) const [protected]
Determine if this access should be observed.
Definition at line 82 of file base.cc.
References X86ISA::addr, Packet::getAddr(), inCache(), inMissQueue(), X86ISA::inv, Request::isInstFetch(), Packet::isInvalidate(), Packet::isRead(), Packet::isSecure(), Request::isUncacheable(), onData, onInst, onMiss, onRead, onWrite, and Packet::req.
Referenced by QueuedPrefetcher::notify().
void BasePrefetcher::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Reimplemented in QueuedPrefetcher.
Definition at line 73 of file base.cc.
References SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and pfIssued.
bool BasePrefetcher::samePage (Addr a, Addr b) const [protected]
Determine if addresses are on the same page.
Definition at line 124 of file base.cc.
References pageBytes, and roundDown().
Referenced by TaggedPrefetcher::calculatePrefetch(), and StridePrefetcher::calculatePrefetch().
void BasePrefetcher::setCache (BaseCache * _cache)
Definition at line 65 of file base.cc.
References blkSize, cache, and BaseCache::getBlockSize().
Referenced by Cache::Cache().
Member Data Documentation
unsigned BasePrefetcher::blkSize [protected]
The block size of the parent cache.
Definition at line 69 of file base.hh.
Referenced by TaggedPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), QueuedPrefetcher::notify(), and setCache().
BaseCache* BasePrefetcher::cache [protected]
Pointr to the parent cache.
Definition at line 66 of file base.hh.
Referenced by inCache(), inMissQueue(), QueuedPrefetcher::notify(), and setCache().
MasterID BasePrefetcher::masterId [protected]
Request id for prefetches.
Definition at line 90 of file base.hh.
Referenced by QueuedPrefetcher::notify().
bool BasePrefetcher::onData [protected]
Consult prefetcher on data accesses?
Definition at line 84 of file base.hh.
Referenced by observeAccess().
bool BasePrefetcher::onInst [protected]
Consult prefetcher on instruction accesses?
Definition at line 87 of file base.hh.
Referenced by observeAccess(), and StridePrefetcher::StridePrefetcher().
bool BasePrefetcher::onMiss [protected]
Only consult prefetcher on cache misses?
Definition at line 75 of file base.hh.
Referenced by observeAccess().
bool BasePrefetcher::onRead [protected]
Consult prefetcher on reads?
Definition at line 78 of file base.hh.
Referenced by observeAccess().
bool BasePrefetcher::onWrite [protected]
Consult prefetcher on reads?
Definition at line 81 of file base.hh.
Referenced by observeAccess().
const Addr BasePrefetcher::pageBytes [protected]
Definition at line 92 of file base.hh.
Referenced by samePage().
Stats::Scalar BasePrefetcher::pfIssued [protected]
Definition at line 106 of file base.hh.
Referenced by QueuedPrefetcher::getPacket(), and regStats().
System* BasePrefetcher::system [protected]
System we belong to.
Definition at line 72 of file base.hh.
The documentation for this class was generated from the following files:
mem/cache/prefetch/base.hh
mem/cache/prefetch/base.cc