gem5: ReusabilityProfiler Class Reference
ReusabilityProfiler Class Reference
#include <reusability.hh>
Classes
class BlockSample
Public Member Functions
ReusabilityProfiler (std::string name)
std::string name ()
virtual void access (Addr addr)
virtual void victim (Addr addr)
virtual void insert (Addr addr)
virtual void sampling ()
virtual void regStats ()
virtual void reset ()
virtual void dump ()
void finalize ()
void tick_to_block (OverflowVector< Tick > *tickDist, Stats::Distribution *blockDist)
Private Attributes
Tick previous_reset_tick
Tick previous_finalize_tick
std::unordered_map< Addr,
BlockSample * > blocks
std::unordered_map< Addr,
BlockSample * >::iterator it
OverflowVector< Tick > distReusableTick
OverflowVector< Tick > distDeadTick
OverflowVector< Tick > distAllTick
Stats::Distribution distReusableBlocks
Stats::Distribution distDeadBlocks
Stats::Distribution distAllBlocks
unsigned dist_size
Detailed Description
Definition at line 53 of file reusability.hh.
Constructor & Destructor Documentation
ReusabilityProfiler::ReusabilityProfiler (std::string name)
Definition at line 4 of file reusability.cc.
References dist_size, distAllTick, distDeadTick, distReusableTick, inform, name(), previous_finalize_tick, previous_reset_tick, and OverflowVector< T >::resize().
Member Function Documentation
void ReusabilityProfiler::access (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 41 of file reusability.cc.
References blocks.
void ReusabilityProfiler::dump () [virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 88 of file reusability.cc.
References finalize().
void ReusabilityProfiler::finalize ()
Definition at line 76 of file reusability.cc.
References blocks, distAllBlocks, distAllTick, distDeadBlocks, distDeadTick, distReusableBlocks, distReusableTick, inform, name(), and tick_to_block().
Referenced by dump().
void ReusabilityProfiler::insert (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 57 of file reusability.cc.
References blocks.
std::string ReusabilityProfiler::name () [inline]
Reimplemented from BaseTagsProfiler.
Definition at line 112 of file reusability.hh.
Referenced by finalize(), regStats(), reset(), and ReusabilityProfiler().
void ReusabilityProfiler::regStats () [virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 19 of file reusability.cc.
References dist_size, distAllBlocks, distDeadBlocks, distReusableBlocks, Stats::Distribution::init(), name(), and Stats::total.
void ReusabilityProfiler::reset () [virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 64 of file reusability.cc.
References blocks, curTick(), distAllTick, distDeadTick, distReusableTick, inform, name(), previous_reset_tick, and OverflowVector< T >::reset().
virtual void ReusabilityProfiler::sampling () [inline, virtual]
Implements BaseTagsProfiler.
Definition at line 118 of file reusability.hh.
void ReusabilityProfiler::tick_to_block (OverflowVector< Tick > * tickDist, Stats::Distribution * blockDist)
Definition at line 94 of file reusability.cc.
References curTick(), dist_size, OverflowVector< T >::get_maxid(), OverflowVector< T >::get_minid(), OverflowVector< T >::get_overflow_value(), OverflowVector< T >::get_underflow_value(), ArmISA::i, previous_reset_tick, and Stats::DistBase< Derived, Stor >::sample().
Referenced by finalize().
void ReusabilityProfiler::victim (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 48 of file reusability.cc.
References blocks.
Member Data Documentation
std::unordered_map<Addr, BlockSample*> ReusabilityProfiler::blocks [private]
Definition at line 96 of file reusability.hh.
Referenced by access(), finalize(), insert(), reset(), and victim().
unsigned ReusabilityProfiler::dist_size [private]
Definition at line 107 of file reusability.hh.
Referenced by regStats(), ReusabilityProfiler(), and tick_to_block().
Stats::Distribution ReusabilityProfiler::distAllBlocks [private]
Definition at line 105 of file reusability.hh.
Referenced by finalize(), and regStats().
OverflowVector<Tick> ReusabilityProfiler::distAllTick [private]
Definition at line 101 of file reusability.hh.
Referenced by finalize(), reset(), ReusabilityProfiler(), ReusabilityProfiler::BlockSample::sample_as_dead(), and ReusabilityProfiler::BlockSample::sample_as_reusable().
Stats::Distribution ReusabilityProfiler::distDeadBlocks [private]
Definition at line 104 of file reusability.hh.
Referenced by finalize(), and regStats().
OverflowVector<Tick> ReusabilityProfiler::distDeadTick [private]
Definition at line 100 of file reusability.hh.
Referenced by finalize(), reset(), ReusabilityProfiler(), and ReusabilityProfiler::BlockSample::sample_as_dead().
Stats::Distribution ReusabilityProfiler::distReusableBlocks [private]
Definition at line 103 of file reusability.hh.
Referenced by finalize(), and regStats().
OverflowVector<Tick> ReusabilityProfiler::distReusableTick [private]
Definition at line 99 of file reusability.hh.
Referenced by finalize(), reset(), ReusabilityProfiler(), and ReusabilityProfiler::BlockSample::sample_as_reusable().
std::unordered_map<Addr, BlockSample*>::iterator ReusabilityProfiler::it [private]
Definition at line 97 of file reusability.hh.
Tick ReusabilityProfiler::previous_finalize_tick [private]
Definition at line 94 of file reusability.hh.
Referenced by ReusabilityProfiler().
Tick ReusabilityProfiler::previous_reset_tick [private]
Definition at line 93 of file reusability.hh.
Referenced by reset(), ReusabilityProfiler(), and tick_to_block().
The documentation for this class was generated from the following files:
mem/cache/tags/prof/reusability.hh
mem/cache/tags/prof/reusability.cc