gem5: LinuxMipsSystem Class Reference
LinuxMipsSystem Class Reference
This class contains linux specific system code (Loading, Events).
#include <system.hh>
Classes
class PrintThreadInfo
class SkipDelayLoopEvent
Public Types
typedef LinuxMipsSystemParams Params
Public Member Functions
Addr InitStack () const
Addr EmptyPGT () const
Addr EmptyPGE () const
Addr ZeroPGE () const
Addr StartAddr () const
Addr Param () const
Addr CommandLine () const
Addr InitrdStart () const
Addr InitrdSize () const
LinuxMipsSystem (Params *p)
~LinuxMipsSystem ()
void setDelayLoop (ThreadContext *tc)
Static Public Attributes
static const int CommandLineSize = 256
Private Attributes
Addr KernelStart
Addresses defining where the kernel bootloader places various elements.
Detailed Description
This class contains linux specific system code (Loading, Events).
It points to objects that are the system binaries to load and patches them appropriately to work in simulator.
Definition at line 51 of file system.hh.
Member Typedef Documentation
typedef LinuxMipsSystemParams LinuxMipsSystem::Params
Reimplemented from MipsSystem.
Definition at line 91 of file system.hh.
Constructor & Destructor Documentation
LinuxMipsSystem::LinuxMipsSystem (Params * p)
Definition at line 63 of file system.cc.
LinuxMipsSystem::~LinuxMipsSystem ()
Definition at line 68 of file system.cc.
Member Function Documentation
Addr LinuxMipsSystem::CommandLine () const [inline]
Definition at line 85 of file system.hh.
References Param().
Addr LinuxMipsSystem::EmptyPGE () const [inline]
Definition at line 80 of file system.hh.
References KernelStart.
Addr LinuxMipsSystem::EmptyPGT () const [inline]
Definition at line 79 of file system.hh.
References KernelStart.
Addr LinuxMipsSystem::InitrdSize () const [inline]
Definition at line 87 of file system.hh.
References Param().
Addr LinuxMipsSystem::InitrdStart () const [inline]
Definition at line 86 of file system.hh.
References Param().
Addr LinuxMipsSystem::InitStack () const [inline]
Definition at line 78 of file system.hh.
References KernelStart.
Addr LinuxMipsSystem::Param () const [inline]
Definition at line 84 of file system.hh.
References ZeroPGE().
Referenced by CommandLine(), InitrdSize(), and InitrdStart().
void LinuxMipsSystem::setDelayLoop (ThreadContext * tc)
Definition at line 74 of file system.cc.
References panic.
Referenced by LinuxMipsSystem::SkipDelayLoopEvent::process().
Addr LinuxMipsSystem::StartAddr () const [inline]
Definition at line 82 of file system.hh.
References KernelStart.
Addr LinuxMipsSystem::ZeroPGE () const [inline]
Definition at line 81 of file system.hh.
References KernelStart.
Referenced by Param().
Member Data Documentation
const int LinuxMipsSystem::CommandLineSize = 256 [static]
Definition at line 88 of file system.hh.
Addr LinuxMipsSystem::KernelStart [private]
Addresses defining where the kernel bootloader places various elements.
Details found in include/asm-mips/system.h
Definition at line 75 of file system.hh.
Referenced by EmptyPGE(), EmptyPGT(), InitStack(), StartAddr(), and ZeroPGE().
The documentation for this class was generated from the following files:
arch/mips/linux/system.hh
arch/mips/linux/system.cc