gem5: Consumer Class Reference
Consumer Class Reference
#include <Consumer.hh>
Classes
class ConsumerEvent
Public Member Functions
Consumer (ClockedObject *_em)
virtual ~Consumer ()
virtual void wakeup ()=0
virtual void print (std::ostream &out) const =0
virtual void storeEventInfo (int info)
bool alreadyScheduled (Tick time)
void insertScheduledWakeupTime (Tick time)
void scheduleEventAbsolute (Tick timeAbs)
Protected Member Functions
void scheduleEvent (Cycles timeDelta)
Private Attributes
std::set< Tick > m_scheduled_wakeups
ClockedObject * em
Detailed Description
Definition at line 43 of file Consumer.hh.
Constructor & Destructor Documentation
Consumer::Consumer (ClockedObject * _em) [inline]
Definition at line 46 of file Consumer.hh.
virtual Consumer::~Consumer () [inline, virtual]
Definition at line 52 of file Consumer.hh.
Member Function Documentation
bool Consumer::alreadyScheduled (Tick time) [inline]
Definition at line 60 of file Consumer.hh.
References m_scheduled_wakeups.
Referenced by scheduleEventAbsolute().
void Consumer::insertScheduledWakeupTime (Tick time) [inline]
Definition at line 66 of file Consumer.hh.
References m_scheduled_wakeups.
Referenced by scheduleEventAbsolute().
virtual void Consumer::print (std::ostream & out) const [pure virtual]
Implemented in InputUnit_d, NetworkInterface_d, NetworkLink_d, OutputUnit_d, SWallocator_d, Switch_d, VCallocator_d, NetworkInterface, NetworkLink, Router, VCarbiter, PerfectSwitch, Throttle, AbstractController, and RubyMemoryControl.
Referenced by operator<<().
void Consumer::scheduleEvent (Cycles timeDelta) [protected]
Definition at line 34 of file Consumer.cc.
References ClockedObject::clockEdge(), em, and scheduleEventAbsolute().
Referenced by VCallocator_d::check_for_wakeup(), Switch_d::check_for_wakeup(), SWallocator_d::check_for_wakeup(), Router::checkReschedule(), NetworkInterface::checkReschedule(), NetworkInterface_d::checkReschedule(), Router::grant_vc(), NetworkInterface::grant_vc(), PerfectSwitch::operateVnet(), Router::release_vc(), NetworkInterface::release_vc(), Router::routeCompute(), and Throttle::wakeup().
void Consumer::scheduleEventAbsolute (Tick timeAbs)
Definition at line 40 of file Consumer.cc.
References alreadyScheduled(), ClockedObject::clockEdge(), em, insertScheduledWakeupTime(), m_scheduled_wakeups, EventManager::schedule(), and ArmISA::t.
Referenced by Router::check_arbiter_reschedule(), MessageBuffer::enqueue(), InputUnit_d::increment_credit(), OutputUnit_d::insert_flit(), MessageBuffer::reanalyzeList(), Router::request_vc(), scheduleEvent(), NetworkInterface::scheduleOutputLink(), NetworkInterface_d::scheduleOutputLink(), Router::scheduleOutputLinks(), Router_d::swarb_req(), Router_d::update_sw_winner(), Router_d::vcarb_req(), NetworkLink::wakeup(), NetworkLink_d::wakeup(), and NetworkInterface_d::wakeup().
virtual void Consumer::storeEventInfo (int info) [inline, virtual]
Reimplemented in PerfectSwitch.
Definition at line 57 of file Consumer.hh.
Referenced by MessageBuffer::enqueue().
virtual void Consumer::wakeup () [pure virtual]
Implemented in InputUnit_d, NetworkInterface_d, NetworkLink_d, OutputUnit_d, SWallocator_d, Switch_d, VCallocator_d, NetworkInterface, NetworkLink, Router, VCarbiter, PerfectSwitch, Throttle, AbstractController, and RubyMemoryControl.
Referenced by Consumer::ConsumerEvent::process().
Member Data Documentation
ClockedObject* Consumer::em [private]
Definition at line 78 of file Consumer.hh.
Referenced by scheduleEvent(), and scheduleEventAbsolute().
std::set<Tick> Consumer::m_scheduled_wakeups [private]
Definition at line 77 of file Consumer.hh.
Referenced by alreadyScheduled(), insertScheduledWakeupTime(), and scheduleEventAbsolute().
The documentation for this class was generated from the following files:
mem/ruby/common/Consumer.hh
mem/ruby/common/Consumer.cc