gem5: BaseO3DynInst< Impl > Class Template Reference
BaseO3DynInst< Impl > Class Template Reference
#include <dyn_inst.hh>
Public Types
enum { MaxInstSrcRegs = TheISA::MaxInstSrcRegs, MaxInstDestRegs = TheISA::MaxInstDestRegs }
typedef Impl::O3CPU O3CPU
Typedef for the CPU.
typedef TheISA::MachInst MachInst
Binary machine instruction type.
typedef TheISA::ExtMachInst ExtMachInst
Extended machine instruction type.
typedef TheISA::RegIndex RegIndex
Logical register index type.
typedef TheISA::IntReg IntReg
Integer register index type.
typedef TheISA::FloatReg FloatReg
typedef TheISA::FloatRegBits FloatRegBits
typedef TheISA::CCReg CCReg
typedef TheISA::MiscReg MiscReg
Misc register index type.
Public Member Functions
BaseO3DynInst (const StaticInstPtr &staticInst, const StaticInstPtr &macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, O3CPU *cpu)
BaseDynInst constructor given a binary instruction.
BaseO3DynInst (const StaticInstPtr &_staticInst, const StaticInstPtr &_macroop)
BaseDynInst constructor given a static inst pointer.
~BaseO3DynInst ()
Fault execute ()
Executes the instruction.
Fault initiateAcc ()
Initiates the access.
Fault completeAcc (PacketPtr pkt)
Completes the access.
MiscReg readMiscReg (int misc_reg)
Reads a misc.
void setMiscReg (int misc_reg, const MiscReg &val)
Sets a misc.
TheISA::MiscReg readMiscRegOperand (const StaticInst *si, int idx)
Reads a misc.
void setMiscRegOperand (const StaticInst *si, int idx, const MiscReg &val)
Sets a misc.
void updateMiscRegs ()
Called at the commit stage to update the misc.
void forwardOldRegs ()
Fault hwrei ()
Calls hardware return from error interrupt.
void trap (const Fault &fault)
Traps to handle specified fault.
bool simPalCheck (int palFunc)
Check for special simulator handling of specific PAL calls.
void syscall (int64_t callnum)
Emulates a syscall.
IntReg readIntRegOperand (const StaticInst *si, int idx)
Reads an integer register.
FloatReg readFloatRegOperand (const StaticInst *si, int idx)
Reads a floating point register of single register width.
FloatRegBits readFloatRegOperandBits (const StaticInst *si, int idx)
Reads a floating point register in its binary format, instead of by value.
CCReg readCCRegOperand (const StaticInst *si, int idx)
void setIntRegOperand (const StaticInst *si, int idx, IntReg val)
void setFloatRegOperand (const StaticInst *si, int idx, FloatReg val)
Records an fp register being set to a value.
void setFloatRegOperandBits (const StaticInst *si, int idx, FloatRegBits val)
Records an fp register being set to an integer value.
void setCCRegOperand (const StaticInst *si, int idx, CCReg val)
Records a CC register being set to a value.
MiscReg readRegOtherThread (int misc_reg, ThreadID tid)
void setRegOtherThread (int misc_reg, MiscReg val, ThreadID tid)
Fault calcEA ()
Calculates EA part of a memory instruction.
Fault memAccess ()
Does the memory access part of a memory instruction.
Protected Attributes
std::array< MiscReg,
TheISA::MaxMiscDestRegs > _destMiscRegVal
Values to be written to the destination misc.
std::array< short,
TheISA::MaxMiscDestRegs > _destMiscRegIdx
Indexes of the destination misc.
uint8_t _numDestMiscRegs
Number of destination misc.
Private Member Functions
void initVars ()
Initializes variables.
Detailed Description
template<class Impl>
class BaseO3DynInst< Impl >
Definition at line 60 of file dyn_inst.hh.
Member Typedef Documentation
template<class Impl > typedef TheISA::CCReg BaseO3DynInst< Impl >::CCReg
Reimplemented from ExecContext.
Definition at line 76 of file dyn_inst.hh.
template<class Impl > typedef TheISA::ExtMachInst BaseO3DynInst< Impl >::ExtMachInst
Extended machine instruction type.
Definition at line 69 of file dyn_inst.hh.
template<class Impl > typedef TheISA::FloatReg BaseO3DynInst< Impl >::FloatReg
Reimplemented from ExecContext.
Definition at line 74 of file dyn_inst.hh.
template<class Impl > typedef TheISA::FloatRegBits BaseO3DynInst< Impl >::FloatRegBits
Reimplemented from ExecContext.
Definition at line 75 of file dyn_inst.hh.
template<class Impl > typedef TheISA::IntReg BaseO3DynInst< Impl >::IntReg
Integer register index type.
Reimplemented from ExecContext.
Definition at line 73 of file dyn_inst.hh.
template<class Impl > typedef TheISA::MachInst BaseO3DynInst< Impl >::MachInst
Binary machine instruction type.
Definition at line 67 of file dyn_inst.hh.
template<class Impl > typedef TheISA::MiscReg BaseO3DynInst< Impl >::MiscReg
Misc register index type.
Reimplemented from ExecContext.
Definition at line 79 of file dyn_inst.hh.
template<class Impl > typedef Impl::O3CPU BaseO3DynInst< Impl >::O3CPU
Typedef for the CPU.
Definition at line 64 of file dyn_inst.hh.
template<class Impl > typedef TheISA::RegIndex BaseO3DynInst< Impl >::RegIndex
Logical register index type.
Reimplemented from BaseDynInst< Impl >.
Definition at line 71 of file dyn_inst.hh.
Member Enumeration Documentation
template<class Impl > anonymous enum
Enumerator:
MaxInstSrcRegs
MaxInstDestRegs
Max source regs.
Definition at line 81 of file dyn_inst.hh.
Constructor & Destructor Documentation
template<class Impl > BaseO3DynInst< Impl >::BaseO3DynInst (const StaticInstPtr & staticInst, const StaticInstPtr & macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, O3CPU * cpu) [inline]
BaseDynInst constructor given a binary instruction.
Definition at line 52 of file dyn_inst_impl.hh.
References BaseO3DynInst< Impl >::initVars().
template<class Impl > BaseO3DynInst< Impl >::BaseO3DynInst (const StaticInstPtr & _staticInst, const StaticInstPtr & _macroop) [inline]
BaseDynInst constructor given a static inst pointer.
Definition at line 62 of file dyn_inst_impl.hh.
References BaseO3DynInst< Impl >::initVars().
template<class Impl > BaseO3DynInst< Impl >::~BaseO3DynInst () [inline]
Definition at line 69 of file dyn_inst_impl.hh.
References DPRINTFR, DTRACE, BaseDynInst< Impl >::instAddr(), BaseDynInst< Impl >::microPC(), BaseDynInst< Impl >::seqNum, BaseDynInst< Impl >::staticInst, and X86ISA::val.
Member Function Documentation
template<class Impl > Fault BaseO3DynInst< Impl >::calcEA () [inline]
Calculates EA part of a memory instruction.
Currently unused, though it may be useful in the future if we want to split memory operations into EA calculation and memory access parts.
Definition at line 321 of file dyn_inst.hh.
References BaseDynInst< Impl >::staticInst, and BaseDynInst< Impl >::traceData.
template<class Impl > Fault BaseO3DynInst< Impl >::completeAcc (PacketPtr pkt) [inline]
Completes the access.
Only valid for memory operations.
Definition at line 176 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::cpu, BaseDynInst< Impl >::fault, Request::getExtraData(), BaseDynInst< Impl >::isStoreConditional(), Packet::req, BaseDynInst< Impl >::reqToVerify, Request::setExtraData(), BaseDynInst< Impl >::staticInst, BaseDynInst< Impl >::thread, and BaseDynInst< Impl >::traceData.
template<class Impl > Fault BaseO3DynInst< Impl >::execute () [inline]
Executes the instruction.
Definition at line 140 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::fault, BaseDynInst< Impl >::staticInst, BaseDynInst< Impl >::thread, and BaseDynInst< Impl >::traceData.
template<class Impl > void BaseO3DynInst< Impl >::forwardOldRegs () [inline]
Definition at line 207 of file dyn_inst.hh.
References CCRegClass, BaseDynInst< Impl >::cpu, FloatRegClass, RefCountingPtr< T >::get(), IntRegClass, MiscRegClass, BaseDynInst< Impl >::numDestRegs(), BaseDynInst< Impl >::prevDestRegIdx(), regIdxToClass(), BaseO3DynInst< Impl >::setCCRegOperand(), BaseO3DynInst< Impl >::setFloatRegOperandBits(), BaseO3DynInst< Impl >::setIntRegOperand(), and BaseDynInst< Impl >::staticInst.
template<class Impl > Fault BaseO3DynInst< Impl >::hwrei () [inline, virtual]
Calls hardware return from error interrupt.
Implements ExecContext.
Definition at line 200 of file dyn_inst_impl.hh.
References CPA::available(), CPA::cpa(), BaseDynInst< Impl >::cpu, BaseDynInst< Impl >::instAddr(), AlphaISA::IPR_EXC_ADDR, BaseDynInst< Impl >::nextInstAddr(), BaseDynInst< Impl >::pc, BaseDynInst< Impl >::pcState(), CPA::swAutoBegin(), ArmISA::tc, and BaseDynInst< Impl >::threadNumber.
template<class Impl > Fault BaseO3DynInst< Impl >::initiateAcc () [inline]
Initiates the access.
Only valid for memory operations.
Definition at line 158 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::fault, BaseDynInst< Impl >::staticInst, BaseDynInst< Impl >::thread, and BaseDynInst< Impl >::traceData.
template<class Impl > void BaseO3DynInst< Impl >::initVars () [inline, private]
Initializes variables.
Reimplemented from BaseDynInst< Impl >.
Definition at line 107 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseO3DynInst< Impl >::_numDestMiscRegs, BaseDynInst< Impl >::_readySrcRegIdx, BaseDynInst< Impl >::_srcRegIdx, ArmISA::i, and BaseDynInst< Impl >::staticInst.
Referenced by BaseO3DynInst< Impl >::BaseO3DynInst().
template<class Impl > Fault BaseO3DynInst< Impl >::memAccess () [inline]
Does the memory access part of a memory instruction.
Currently unused, though it may be useful in the future if we want to split memory operations into EA calculation and memory access parts.
Definition at line 330 of file dyn_inst.hh.
References BaseDynInst< Impl >::staticInst, and BaseDynInst< Impl >::traceData.
template<class Impl > CCReg BaseO3DynInst< Impl >::readCCRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 270 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
template<class Impl > FloatReg BaseO3DynInst< Impl >::readFloatRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register of single register width.
Implements ExecContext.
Definition at line 260 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
template<class Impl > FloatRegBits BaseO3DynInst< Impl >::readFloatRegOperandBits (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 265 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
template<class Impl > IntReg BaseO3DynInst< Impl >::readIntRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads an integer register.
Implements ExecContext.
Definition at line 255 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
template<class Impl > MiscReg BaseO3DynInst< Impl >::readMiscReg (int misc_reg) [inline, virtual]
Reads a misc.
register, including any side-effects the read might have as defined by the architecture.
Implements ExecContext.
Definition at line 141 of file dyn_inst.hh.
References BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::threadNumber.
template<class Impl > TheISA::MiscReg BaseO3DynInst< Impl >::readMiscRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads a misc.
register, including any side-effects the read might have as defined by the architecture.
Implements ExecContext.
Definition at line 173 of file dyn_inst.hh.
References BaseDynInst< Impl >::cpu, AlphaISA::Misc_Reg_Base, StaticInst::srcRegIdx(), and BaseDynInst< Impl >::threadNumber.
template<class Impl > MiscReg BaseO3DynInst< Impl >::readRegOtherThread (int misc_reg, ThreadID tid) [inline, virtual]
Implements ExecContext.
Definition at line 304 of file dyn_inst.hh.
References panic.
template<class Impl > void BaseO3DynInst< Impl >::setCCRegOperand (const StaticInst * si, int idx, CCReg val) [inline, virtual]
Records a CC register being set to a value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 297 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
template<class Impl > void BaseO3DynInst< Impl >::setFloatRegOperand (const StaticInst * si, int idx, FloatReg val) [inline, virtual]
Records an fp register being set to a value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 284 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
template<class Impl > void BaseO3DynInst< Impl >::setFloatRegOperandBits (const StaticInst * si, int idx, FloatRegBits val) [inline, virtual]
Records an fp register being set to an integer value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 290 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
template<class Impl > void BaseO3DynInst< Impl >::setIntRegOperand (const StaticInst * si, int idx, IntReg val) [inline, virtual]
Todo:
: Make results into arrays so they can handle multiple dest registers.
Reimplemented from BaseDynInst< Impl >.
Definition at line 278 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
template<class Impl > void BaseO3DynInst< Impl >::setMiscReg (int misc_reg, const MiscReg & val) [inline, virtual]
Sets a misc.
register, including any side-effects the write might have as defined by the architecture.
Writes to misc. registers are recorded and deferred until the commit stage, when updateMiscRegs() is called. First, check if the misc reg has been written before and update its value to be committed instead of making a new entry. If not, make a new entry and record the write.
Implements ExecContext.
Definition at line 149 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::_destMiscRegIdx, BaseO3DynInst< Impl >::_destMiscRegVal, BaseO3DynInst< Impl >::_numDestMiscRegs, and AlphaISA::MaxMiscDestRegs.
Referenced by BaseO3DynInst< Impl >::setMiscRegOperand().
template<class Impl > void BaseO3DynInst< Impl >::setMiscRegOperand (const StaticInst * si, int idx, const MiscReg & val) [inline, virtual]
Sets a misc.
register, including any side-effects the write might have as defined by the architecture.
Implements ExecContext.
Definition at line 183 of file dyn_inst.hh.
References StaticInst::destRegIdx(), AlphaISA::Misc_Reg_Base, and BaseO3DynInst< Impl >::setMiscReg().
template<class Impl > void BaseO3DynInst< Impl >::setRegOtherThread (int misc_reg, MiscReg val, ThreadID tid) [inline, virtual]
Implements ExecContext.
Definition at line 310 of file dyn_inst.hh.
References panic.
template<class Impl > bool BaseO3DynInst< Impl >::simPalCheck (int palFunc) [inline, virtual]
Check for special simulator handling of specific PAL calls.
If return value is false, actual PAL call will be suppressed.
Implements ExecContext.
Definition at line 235 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::cpu, panic, and BaseDynInst< Impl >::threadNumber.
template<class Impl > void BaseO3DynInst< Impl >::syscall (int64_t callnum) [inline, virtual]
Emulates a syscall.
Implements ExecContext.
Definition at line 245 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::cpu, FullSystem, panic, BaseDynInst< Impl >::pcState(), and BaseDynInst< Impl >::threadNumber.
template<class Impl > void BaseO3DynInst< Impl >::trap (const Fault & fault) [inline]
Traps to handle specified fault.
Definition at line 228 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::cpu, BaseDynInst< Impl >::staticInst, and BaseDynInst< Impl >::threadNumber.
template<class Impl > void BaseO3DynInst< Impl >::updateMiscRegs () [inline]
Called at the commit stage to update the misc.
registers.
Definition at line 191 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::_destMiscRegIdx, BaseO3DynInst< Impl >::_destMiscRegVal, BaseO3DynInst< Impl >::_numDestMiscRegs, BaseDynInst< Impl >::cpu, ArmISA::i, and BaseDynInst< Impl >::thread.
Member Data Documentation
template<class Impl > std::array<short, TheISA::MaxMiscDestRegs> BaseO3DynInst< Impl >::_destMiscRegIdx [protected]
Indexes of the destination misc.
registers. They are needed to defer the write accesses to the misc. registers until the commit stage, when the instruction is out of its speculative state.
Definition at line 119 of file dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::setMiscReg(), and BaseO3DynInst< Impl >::updateMiscRegs().
template<class Impl > std::array<MiscReg, TheISA::MaxMiscDestRegs> BaseO3DynInst< Impl >::_destMiscRegVal [protected]
Values to be written to the destination misc.
registers.
Definition at line 113 of file dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::setMiscReg(), and BaseO3DynInst< Impl >::updateMiscRegs().
template<class Impl > uint8_t BaseO3DynInst< Impl >::_numDestMiscRegs [protected]
Number of destination misc.
registers.
Definition at line 122 of file dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::initVars(), BaseO3DynInst< Impl >::setMiscReg(), and BaseO3DynInst< Impl >::updateMiscRegs().
The documentation for this class was generated from the following files:
cpu/o3/dyn_inst.hh
cpu/o3/dyn_inst_impl.hh