gem5: Drainable Class Reference
Drainable Class Reference
Interface for objects that might require draining before checkpointing.
#include <drain.hh>
Public Types
enum State { Running, Draining, Drained }
Object drain/handover states.
Public Member Functions
Drainable ()
virtual ~Drainable ()
virtual unsigned int drain (DrainManager *drainManager)=0
Determine if an object needs draining and register a DrainManager.
virtual void drainResume ()
Resume execution after a successful drain.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
State getDrainState () const
Protected Member Functions
void setDrainState (State new_state)
Private Attributes
State _drainState
Detailed Description
Interface for objects that might require draining before checkpointing.
An object's internal state needs to be drained when creating a checkpoint, switching between CPU models, or switching between timing models. Once the internal state has been drained from all objects in the system, the objects are serialized to disc or the configuration change takes place. The process works as follows (see simulate.py for details):
An instance of a DrainManager is created to keep track of how many objects need to be drained. The object maintains an internal counter that is decreased every time its CountedDrainEvent::signalDrainDone() method is called. When the counter reaches zero, the simulation is stopped.
Call Drainable::drain() for every object in the system. Draining has completed if all of them return zero. Otherwise, the sum of the return values is loaded into the counter of the DrainManager. A pointer to the drain manager is passed as an argument to the drain() method.
Continue simulation. When an object has finished draining its internal state, it calls CountedDrainEvent::signalDrainDone() on the manager. When the counter in the manager reaches zero, the simulation stops.
Check if any object still needs draining, if so repeat the process above.
Serialize objects, switch CPU model, or change timing model.
Call Drainable::drainResume() and continue the simulation.
Definition at line 141 of file drain.hh.
Member Enumeration Documentation
enum Drainable::State
Object drain/handover states.
An object starts out in the Running state. When the simulator prepares to take a snapshot or prepares a CPU for handover, it calls the drain() method to transfer the object into the Draining or Drained state. If any object enters the Draining state (drain() returning >0), simulation continues until it all objects have entered the Drained state.
Before resuming simulation, the simulator calls resume() to transfer the object to the Running state.
Note:
Even though the state of an object (visible to the rest of the world through getState()) could be used to determine if all objects have entered the Drained state, the protocol is actually a bit more elaborate. See drain() for details.
Enumerator:
Running
Draining
Running normally.
Drained
Draining buffers pending serialization/handover.
Buffers drained, ready for serialization/handover
Reimplemented in BaseXBar::Layer< SrcType, DstType >, VGic, BaseXBar::Layer< SlavePort, MasterPort >, and BaseXBar::Layer< MasterPort, SlavePort >.
Definition at line 162 of file drain.hh.
Constructor & Destructor Documentation
Drainable::Drainable ()
Definition at line 60 of file drain.cc.
Drainable::~Drainable () [virtual]
Definition at line 65 of file drain.cc.
Member Function Documentation
virtual unsigned int Drainable::drain (DrainManager * drainManager) [pure virtual]
Determine if an object needs draining and register a DrainManager.
When draining the state of an object, the simulator calls drain with a pointer to a drain manager. If the object does not need further simulation to drain internal buffers, it switched to the Drained state and returns 0, otherwise it switches to the Draining state and returns the number of times that it will call Event::process() on the drain event. Most objects are expected to return either 0 or 1.
Note:
An object that has entered the Drained state can be disturbed by other objects in the system and consequently be forced to enter the Draining state again. The simulator therefore repeats the draining process until all objects return 0 on the first call to drain().
Parameters:
drainManager DrainManager to use to inform the simulator when draining has completed.
Returns:
0 if the object is ready for serialization now, >0 if it needs further simulation.
Implemented in ArmISA::Stage2MMU, ArmISA::TableWalker, TrafficGen, FlashDevice, UFSHostDevice, CopyEngine::CopyEngineChannel, CopyEngine, DmaDevice, IGbE, PioDevice, PciDevice, BaseCache, MSHRQueue, CoherentXBar, DRAMCtrl, DRAMSim2, NoncoherentXBar, PacketQueue, RubyMemoryControl, DMASequencer, RubyPort, SimpleMemory, BaseXBar::Layer< SrcType, DstType >, BaseXBar, SimObject, System, BaseXBar::Layer< SlavePort, MasterPort >, and BaseXBar::Layer< MasterPort, SlavePort >.
void Drainable::drainResume () [virtual]
Resume execution after a successful drain.
Note:
This method is normally only called from the simulation scripts.
Reimplemented in KvmGic, ArmISA::PMU, ArmISA::TableWalker, ArmISA::TLB, CopyEngine::CopyEngineChannel, CopyEngine, IGbE, NSGigE, Sinic::Device, DRAMCtrl, and System.
Definition at line 70 of file drain.cc.
References _drainState, and Running.
Referenced by CxxConfigManager::drainResume().
State Drainable::getDrainState () const [inline]
Definition at line 228 of file drain.hh.
References _drainState.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaTransfer(), IdeDisk::doDmaWrite(), NSGigE::doRxDmaRead(), NSGigE::doRxDmaWrite(), NSGigE::doTxDmaRead(), NSGigE::doTxDmaWrite(), CopyEngine::CopyEngineChannel::drain(), IGbE::TxDescCache::fetchAfterWb(), IGbE::RxDescCache::fetchAfterWb(), IGbE::DescCache< T >::fetchDescriptors1(), CopyEngine::CopyEngineChannel::inDrain(), Sequencer::insertRequest(), CopyEngine::CopyEngineChannel::recvCommand(), IGbE::restartClock(), Sinic::Device::rxKick(), System::setMemoryMode(), Sinic::Device::txKick(), Sequencer::wakeup(), IGbE::write(), and IGbE::DescCache< T >::writeback1().
virtual void Drainable::memInvalidate () [inline, virtual]
Invalidate the contents of memory buffers.
When the switching to hardware virtualized CPU models, we need to make sure that we don't have any cached state in the system that might become stale when we return. This method is used to flush all such state back to main memory.
This does not cause any dirty state to be written back to memory.
Reimplemented in BaseTLB, BaseCache, and Cache.
Definition at line 226 of file drain.hh.
virtual void Drainable::memWriteback () [inline, virtual]
Write back dirty buffers to memory using functional writes.
After returning, an object implementing this method should have written all its dirty data back to memory. This method is typically used to prepare a system with caches for checkpointing.
Reimplemented in BaseCache, and Cache.
Definition at line 213 of file drain.hh.
void Drainable::setDrainState (State new_state) [inline, protected]
Definition at line 231 of file drain.hh.
References _drainState.
Referenced by ArmISA::TableWalker::completeDrain(), MSHRQueue::deallocateOne(), SimObject::drain(), SimpleMemory::drain(), RubyPort::drain(), DMASequencer::drain(), DRAMSim2::drain(), DRAMCtrl::drain(), MSHRQueue::drain(), PciDevice::drain(), PioDevice::drain(), IGbE::drain(), DmaDevice::drain(), CopyEngine::drain(), UFSHostDevice::drain(), FlashDevice::drain(), BaseCache::drain(), ArmISA::TableWalker::drain(), and System::drain().
Member Data Documentation
State Drainable::_drainState [private]
Definition at line 235 of file drain.hh.
Referenced by drainResume(), getDrainState(), and setDrainState().
The documentation for this class was generated from the following files:
sim/drain.hh
sim/drain.cc