gem5: DirectoryMemory Class Reference
DirectoryMemory Class Reference
#include <DirectoryMemory.hh>
Public Types
typedef RubyDirectoryMemoryParams Params
Public Member Functions
DirectoryMemory (const Params *p)
~DirectoryMemory ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
uint64 mapAddressToLocalIdx (PhysAddress address)
uint64 getSize ()
bool isPresent (PhysAddress address)
AbstractEntry * lookup (PhysAddress address)
AbstractEntry * allocate (const PhysAddress &address, AbstractEntry *new_entry)
void print (std::ostream &out) const
void recordRequestType (DirectoryRequestType requestType)
Static Public Member Functions
static uint64 mapAddressToDirectoryVersion (PhysAddress address)
Private Member Functions
DirectoryMemory (const DirectoryMemory &obj)
DirectoryMemory & operator= (const DirectoryMemory &obj)
Private Attributes
const std::string m_name
AbstractEntry ** m_entries
uint64 m_size_bytes
uint64 m_size_bits
uint64 m_num_entries
int m_version
Static Private Attributes
static int m_num_directories = 0
static int m_num_directories_bits = 0
static uint64_t m_total_size_bytes = 0
static int m_numa_high_bit = 0
Detailed Description
Definition at line 41 of file DirectoryMemory.hh.
Member Typedef Documentation
typedef RubyDirectoryMemoryParams DirectoryMemory::Params
Reimplemented from SimObject.
Definition at line 44 of file DirectoryMemory.hh.
Constructor & Destructor Documentation
DirectoryMemory::DirectoryMemory (const Params * p)
Definition at line 43 of file DirectoryMemory.cc.
References floorLog2(), m_num_entries, m_numa_high_bit, m_size_bits, m_size_bytes, and m_version.
DirectoryMemory::~DirectoryMemory ()
Definition at line 71 of file DirectoryMemory.cc.
References ArmISA::i, m_entries, and m_num_entries.
DirectoryMemory::DirectoryMemory (const DirectoryMemory & obj) [private]
Member Function Documentation
AbstractEntry * DirectoryMemory::allocate (const PhysAddress & address, AbstractEntry * new_entry)
Definition at line 126 of file DirectoryMemory.cc.
References AbstractEntry::changePermission(), DPRINTF, isPresent(), m_entries, m_num_entries, and mapAddressToLocalIdx().
uint64 DirectoryMemory::getSize () [inline]
Definition at line 53 of file DirectoryMemory.hh.
References m_size_bytes.
void DirectoryMemory::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 54 of file DirectoryMemory.cc.
References ceilLog2(), RubySystem::getBlockSizeBytes(), RubySystem::getMemorySizeBits(), ArmISA::i, m_entries, m_num_directories, m_num_directories_bits, m_num_entries, m_numa_high_bit, m_size_bytes, and m_total_size_bytes.
bool DirectoryMemory::isPresent (PhysAddress address)
Definition at line 94 of file DirectoryMemory.cc.
References m_version, and mapAddressToDirectoryVersion().
Referenced by allocate(), and lookup().
AbstractEntry * DirectoryMemory::lookup (PhysAddress address)
Definition at line 115 of file DirectoryMemory.cc.
References DPRINTF, isPresent(), m_entries, m_num_entries, and mapAddressToLocalIdx().
uint64 DirectoryMemory::mapAddressToDirectoryVersion (PhysAddress address) [static]
Definition at line 83 of file DirectoryMemory.cc.
References Address::bitSelect(), m_num_directories_bits, and m_numa_high_bit.
Referenced by isPresent(), and map_Address_to_DirectoryNode().
uint64 DirectoryMemory::mapAddressToLocalIdx (PhysAddress address)
Definition at line 101 of file DirectoryMemory.cc.
References Address::bitRemove(), Address::getAddress(), RubySystem::getBlockSizeBits(), m_num_directories_bits, and m_numa_high_bit.
Referenced by allocate(), and lookup().
DirectoryMemory& DirectoryMemory::operator= (const DirectoryMemory & obj) [private]
void DirectoryMemory::print (std::ostream & out) const
Referenced by operator<<().
void DirectoryMemory::recordRequestType (DirectoryRequestType requestType)
Definition at line 146 of file DirectoryMemory.cc.
References DPRINTF.
Member Data Documentation
AbstractEntry** DirectoryMemory::m_entries [private]
Definition at line 70 of file DirectoryMemory.hh.
Referenced by allocate(), init(), lookup(), and ~DirectoryMemory().
const std::string DirectoryMemory::m_name [private]
Definition at line 69 of file DirectoryMemory.hh.
int DirectoryMemory::m_num_directories = 0 [static, private]
Definition at line 78 of file DirectoryMemory.hh.
Referenced by init().
int DirectoryMemory::m_num_directories_bits = 0 [static, private]
Definition at line 79 of file DirectoryMemory.hh.
Referenced by init(), mapAddressToDirectoryVersion(), and mapAddressToLocalIdx().
uint64 DirectoryMemory::m_num_entries [private]
Definition at line 75 of file DirectoryMemory.hh.
Referenced by allocate(), DirectoryMemory(), init(), lookup(), and ~DirectoryMemory().
int DirectoryMemory::m_numa_high_bit = 0 [static, private]
Definition at line 81 of file DirectoryMemory.hh.
Referenced by DirectoryMemory(), init(), mapAddressToDirectoryVersion(), and mapAddressToLocalIdx().
uint64 DirectoryMemory::m_size_bits [private]
Definition at line 74 of file DirectoryMemory.hh.
Referenced by DirectoryMemory().
uint64 DirectoryMemory::m_size_bytes [private]
Definition at line 73 of file DirectoryMemory.hh.
Referenced by DirectoryMemory(), getSize(), and init().
uint64_t DirectoryMemory::m_total_size_bytes = 0 [static, private]
Definition at line 80 of file DirectoryMemory.hh.
Referenced by init().
int DirectoryMemory::m_version [private]
Definition at line 76 of file DirectoryMemory.hh.
Referenced by DirectoryMemory(), and isPresent().
The documentation for this class was generated from the following files:
mem/ruby/structures/DirectoryMemory.hh
mem/ruby/structures/DirectoryMemory.cc