gem5: BaseTagsProfiler Class Reference
BaseTagsProfiler Class Reference
#include <base.hh>
Public Member Functions
BaseTagsProfiler (std::string parent)
virtual ~BaseTagsProfiler ()
std::string name ()
virtual void regStats ()
virtual void insert (Addr addr)=0
virtual void access (Addr addr)=0
virtual void victim (Addr addr)=0
virtual void sampling ()=0
virtual void dump ()
virtual void reset ()
virtual void add (BaseTagsProfiler *prof)
Private Attributes
std::string parent_name
Detailed Description
Definition at line 13 of file base.hh.
Constructor & Destructor Documentation
BaseTagsProfiler::BaseTagsProfiler (std::string parent) [inline]
Definition at line 19 of file base.hh.
References parent_name.
virtual BaseTagsProfiler::~BaseTagsProfiler () [inline, virtual]
Definition at line 20 of file base.hh.
Member Function Documentation
virtual void BaseTagsProfiler::access (Addr addr) [pure virtual]
Implemented in AddressTracer, ProfilerComposite, InsertionProfiler, and ReusabilityProfiler.
Referenced by LRUProfiler::accessBlock(), and FLIPProfiler::accessBlock().
virtual void BaseTagsProfiler::add (BaseTagsProfiler * prof) [inline, virtual]
Definition at line 35 of file base.hh.
References fatal.
Referenced by FLIPProfiler::FLIPProfiler(), and LRUProfiler::LRUProfiler().
virtual void BaseTagsProfiler::dump () [inline, virtual]
Reimplemented in AddressTracer, ProfilerComposite, and ReusabilityProfiler.
Definition at line 32 of file base.hh.
virtual void BaseTagsProfiler::insert (Addr addr) [pure virtual]
Implemented in AddressTracer, ProfilerComposite, InsertionProfiler, and ReusabilityProfiler.
Referenced by LRUProfiler::insertBlock(), and FLIPProfiler::insertBlock().
std::string BaseTagsProfiler::name () [inline]
Reimplemented in AddressTracer, ProfilerComposite, InsertionProfiler, and ReusabilityProfiler.
Definition at line 22 of file base.hh.
References parent_name.
virtual void BaseTagsProfiler::regStats () [inline, virtual]
Reimplemented in AddressTracer, ProfilerComposite, InsertionProfiler, and ReusabilityProfiler.
Definition at line 24 of file base.hh.
Referenced by LRUProfiler::regStats(), and FLIPProfiler::regStats().
virtual void BaseTagsProfiler::reset () [inline, virtual]
Reimplemented in AddressTracer, ProfilerComposite, and ReusabilityProfiler.
Definition at line 33 of file base.hh.
virtual void BaseTagsProfiler::sampling () [pure virtual]
Implemented in AddressTracer, ProfilerComposite, InsertionProfiler, and ReusabilityProfiler.
Referenced by LRUProfiler::sampling(), and FLIPProfiler::sampling().
virtual void BaseTagsProfiler::victim (Addr addr) [pure virtual]
Implemented in AddressTracer, ProfilerComposite, InsertionProfiler, and ReusabilityProfiler.
Referenced by LRUProfiler::findVictim(), FLIPProfiler::findVictim(), LRUProfiler::invalidate(), and FLIPProfiler::invalidate().
Member Data Documentation
std::string BaseTagsProfiler::parent_name [private]
Definition at line 16 of file base.hh.
Referenced by BaseTagsProfiler(), and name().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/base.hh