gem5: ArmISA::AbortFault< T > Class Template Reference
ArmISA::AbortFault< T > Class Template Reference
#include <faults.hh>
Public Member Functions
AbortFault (Addr _faultAddr, bool _write, TlbEntry::DomainType _domain, uint8_t _source, bool _stage2, ArmFault::TranMethod _tranMethod=ArmFault::UnknownTran)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
FSR getFsr (ThreadContext *tc)
bool abortDisable (ThreadContext *tc)
uint32_t iss () const
bool isStage2 () const
void annotate (ArmFault::AnnotationIDs id, uint64_t val)
bool isMMUFault () const
Protected Attributes
Addr faultAddr
The virtual address the fault occured at.
Addr OVAddr
Original virtual address.
bool write
TlbEntry::DomainType domain
uint8_t source
uint8_t srcEncoded
bool stage2
bool s1ptw
ArmFault::TranMethod tranMethod
Detailed Description
template<class T>
class ArmISA::AbortFault< T >
Definition at line 374 of file faults.hh.
Constructor & Destructor Documentation
template<class T> ArmISA::AbortFault< T >::AbortFault (Addr _faultAddr, bool _write, TlbEntry::DomainType _domain, uint8_t _source, bool _stage2, ArmFault::TranMethod _tranMethod = ArmFault::UnknownTran) [inline]
Definition at line 399 of file faults.hh.
Member Function Documentation
template<class T > bool ArmISA::AbortFault< T >::abortDisable (ThreadContext * tc) [inline, virtual]
Reimplemented from ArmISA::ArmFaultVals< T >.
Definition at line 1003 of file faults.cc.
References ArmSystem::haveSecurity(), ArmISA::MISCREG_SCR, ThreadContext::readMiscRegNoEffect(), and ArmISA::scr.
template<class T > void ArmISA::AbortFault< T >::annotate (ArmFault::AnnotationIDs id, uint64_t val) [inline, virtual]
Reimplemented from ArmISA::ArmFault.
Reimplemented in ArmISA::DataAbort.
Definition at line 1014 of file faults.cc.
References ArmISA::ArmFault::OVA, ArmISA::AbortFault< T >::OVAddr, ArmISA::AbortFault< T >::s1ptw, and ArmISA::ArmFault::S1PTW.
template<class T > FSR ArmISA::AbortFault< T >::getFsr (ThreadContext * tc) [inline, virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 972 of file faults.cc.
References ArmISA::ArmFault::aarch64FaultSources, bits(), ArmISA::AbortFault< T >::domain, ArmISA::ArmFault::FaultSourceInvalid, ArmISA::ArmFault::longDescFaultSources, ArmISA::ArmFault::LpaeTran, ArmISA::MISCREG_CPSR, panic, ThreadContext::readMiscRegNoEffect(), ArmISA::ArmFault::shortDescFaultSources, ArmISA::AbortFault< T >::source, ArmISA::AbortFault< T >::srcEncoded, ArmISA::AbortFault< T >::tranMethod, ArmISA::ArmFault::UnknownTran, ArmISA::width, and ArmISA::AbortFault< T >::write.
Referenced by ArmISA::AbortFault< T >::invoke().
template<class T > void ArmISA::AbortFault< T >::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [inline, virtual]
Reimplemented from ArmISA::ArmFault.
Reimplemented in ArmISA::VirtualDataAbort.
Definition at line 916 of file faults.cc.
References ArmISA::ArmFault::AsynchronousExternalAbort, ArmISA::cpsr, DPRINTF, ArmISA::AbortFault< T >::faultAddr, ThreadContext::getCpuPtr(), ArmISA::AbortFault< T >::getFsr(), ArmISA::INT_ABT, ArmISA::longDescFormatInUse(), ArmISA::ArmFault::LpaeTran, ArmISA::M5_VAR_USED, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HPFAR, ArmISA::MISCREG_TTBCR_NS, ArmISA::MISCREG_TTBCR_S, ArmISA::MODE_HYP, ArmISA::AbortFault< T >::OVAddr, ThreadContext::readMiscReg(), ArmISA::ArmFaultVals< T >::routeToMonitor(), ThreadContext::setMiscReg(), ArmISA::AbortFault< T >::source, ArmISA::AbortFault< T >::stage2, ArmISA::AbortFault< T >::tranMethod, ArmISA::ArmFault::UnknownTran, and ArmISA::ArmFault::VmsaTran.
template<class T > bool ArmISA::AbortFault< T >::isMMUFault () const [inline]
Definition at line 1045 of file faults.cc.
References ArmISA::ArmFault::AccessFlagLL, ArmISA::ArmFault::AlignmentFault, ArmISA::ArmFault::DomainLL, ArmISA::ArmFault::PermissionLL, ArmISA::AbortFault< T >::source, and ArmISA::ArmFault::TranslationLL.
template<class T > uint32_t ArmISA::AbortFault< T >::iss () const [inline, virtual]
Reimplemented from ArmISA::ArmFaultVals< T >.
Reimplemented in ArmISA::DataAbort.
Definition at line 1033 of file faults.cc.
References ArmISA::AbortFault< T >::s1ptw, ArmISA::AbortFault< T >::srcEncoded, X86ISA::val, and ArmISA::AbortFault< T >::write.
template<class T> bool ArmISA::AbortFault< T >::isStage2 () const [inline, virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 413 of file faults.hh.
Member Data Documentation
template<class T> TlbEntry::DomainType ArmISA::AbortFault< T >::domain [protected]
Definition at line 391 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::getFsr().
template<class T> Addr ArmISA::AbortFault< T >::faultAddr [protected]
The virtual address the fault occured at.
If 2 stages of translation are being used then this is the intermediate physical address that is the starting point for the second stage of translation.
Definition at line 383 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::invoke().
template<class T> Addr ArmISA::AbortFault< T >::OVAddr [protected]
Original virtual address.
If the fault was generated on the second stage of translation then this variable stores the virtual address used in the original stage 1 translation.
Definition at line 389 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::annotate(), and ArmISA::AbortFault< T >::invoke().
template<class T> bool ArmISA::AbortFault< T >::s1ptw [protected]
Definition at line 395 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::annotate(), and ArmISA::AbortFault< T >::iss().
template<class T> uint8_t ArmISA::AbortFault< T >::source [protected]
Definition at line 392 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::getFsr(), ArmISA::AbortFault< T >::invoke(), and ArmISA::AbortFault< T >::isMMUFault().
template<class T> uint8_t ArmISA::AbortFault< T >::srcEncoded [protected]
Definition at line 393 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::getFsr(), and ArmISA::AbortFault< T >::iss().
template<class T> bool ArmISA::AbortFault< T >::stage2 [protected]
Definition at line 394 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::invoke(), and ArmISA::AbortFault< DataAbort >::isStage2().
template<class T> ArmFault::TranMethod ArmISA::AbortFault< T >::tranMethod [protected]
Definition at line 396 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::getFsr(), and ArmISA::AbortFault< T >::invoke().
template<class T> bool ArmISA::AbortFault< T >::write [protected]
Definition at line 390 of file faults.hh.
Referenced by ArmISA::AbortFault< T >::getFsr(), and ArmISA::AbortFault< T >::iss().
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc