gem5: BaseGlobalEvent Class Reference
BaseGlobalEvent Class Reference
Common base class for GlobalEvent and GlobalSyncEvent.
#include <global_event.hh>
Classes
class BarrierEvent
The base class for the local events that will synchronize threads to perform the global event.
Public Member Functions
BaseGlobalEvent (Priority p, Flags f)
virtual ~BaseGlobalEvent ()
virtual void process ()=0
virtual const char * description () const =0
void schedule (Tick when)
bool scheduled () const
Tick when () const
void deschedule ()
void reschedule (Tick when)
Protected Attributes
Barrier barrier
The barrier that all threads wait on before performing the global event.
std::vector< BarrierEvent * > barrierEvent
The individual local event instances (one per thread/event queue).
Static Private Attributes
static std::mutex globalQMutex
Mutex variable for providing exculsive right to schedule global events.
Detailed Description
Common base class for GlobalEvent and GlobalSyncEvent.
Definition at line 62 of file global_event.hh.
Constructor & Destructor Documentation
BaseGlobalEvent::BaseGlobalEvent (Priority p, Flags f)
Definition at line 36 of file global_event.cc.
BaseGlobalEvent::~BaseGlobalEvent () [virtual]
Definition at line 43 of file global_event.cc.
References barrierEvent, ArmISA::i, and numMainEventQueues.
Member Function Documentation
void BaseGlobalEvent::deschedule ()
Definition at line 84 of file global_event.cc.
References barrierEvent, curEventQueue(), ArmISA::i, mainEventQueue, numMainEventQueues, ArmISA::q, and scheduled().
Referenced by simulate().
virtual const char* BaseGlobalEvent::description () const [pure virtual]
Implemented in DebugBreakEvent, GlobalSyncEvent, GlobalSimLoopExitEvent, and Stats::StatEvent.
virtual void BaseGlobalEvent::process () [pure virtual]
Implemented in DebugBreakEvent, GlobalEvent, GlobalSyncEvent, GlobalSimLoopExitEvent, and Stats::StatEvent.
Referenced by GlobalSyncEvent::BarrierEvent::process(), and GlobalEvent::BarrierEvent::process().
void BaseGlobalEvent::reschedule (Tick when)
Definition at line 97 of file global_event.cc.
References barrierEvent, globalQMutex, ArmISA::i, mainEventQueue, numMainEventQueues, and scheduled().
Referenced by simulate().
void BaseGlobalEvent::schedule (Tick when)
Definition at line 53 of file global_event.cc.
References barrierEvent, globalQMutex, ArmISA::i, mainEventQueue, and numMainEventQueues.
Referenced by GlobalEvent::GlobalEvent(), GlobalSyncEvent::GlobalSyncEvent(), GlobalSimLoopExitEvent::process(), and GlobalSyncEvent::process().
bool BaseGlobalEvent::scheduled () const [inline]
Definition at line 128 of file global_event.hh.
References barrierEvent, ArmISA::i, and numMainEventQueues.
Referenced by deschedule(), and reschedule().
Tick BaseGlobalEvent::when () const [inline]
Definition at line 138 of file global_event.hh.
References barrierEvent, and numMainEventQueues.
Member Data Documentation
Barrier BaseGlobalEvent::barrier [protected]
The barrier that all threads wait on before performing the global event.
Definition at line 112 of file global_event.hh.
Referenced by BaseGlobalEvent::BarrierEvent::globalBarrier().
std::vector<BarrierEvent *> BaseGlobalEvent::barrierEvent [protected]
The individual local event instances (one per thread/event queue).
Definition at line 115 of file global_event.hh.
Referenced by BaseGlobalEventTemplate< GlobalSyncEvent >::BaseGlobalEventTemplate(), deschedule(), reschedule(), schedule(), scheduled(), when(), BaseGlobalEvent::BarrierEvent::~BarrierEvent(), and ~BaseGlobalEvent().
std::mutex BaseGlobalEvent::globalQMutex [static, private]
Mutex variable for providing exculsive right to schedule global events.
This is necessary so that a total order can be maintained amongst the global events. Without ensuring the total order, it is possible that threads execute global events in different orders, which can result in a deadlock.
Definition at line 70 of file global_event.hh.
Referenced by reschedule(), and schedule().
The documentation for this class was generated from the following files:
sim/global_event.hh
sim/global_event.cc