gem5: Request Class Reference
Request Class Reference
#include <request.hh>
Public Types
typedef uint32_t FlagsType
typedef uint8_t ArchFlagsType
typedef ::Flags< FlagsType > Flags
Public Member Functions
Request ()
Minimal constructor.
Request (Addr paddr, unsigned size, Flags flags, MasterID mid)
Constructor for physical (e.g.
Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time)
Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time, Addr pc)
Request (int asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, int cid, ThreadID tid)
~Request ()
void setThreadContext (int context_id, ThreadID tid)
Set up CPU and thread numbers.
void setVirt (int asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc)
Set up a virtual (e.g., CPU) request in a previously allocated Request object.
void setPaddr (Addr paddr)
Set just the physical address.
void splitOnVaddr (Addr split_addr, RequestPtr &req1, RequestPtr &req2)
Generate two requests as if this request had been split into two pieces.
bool hasPaddr () const
Accessor for paddr.
Addr getPaddr () const
bool hasSize () const
Accessor for size.
unsigned getSize () const
Tick time () const
Accessor for time.
Flags getFlags ()
Accessor for flags.
void setFlags (Flags flags)
Note that unlike other accessors, this function sets *specific flags* (ORs them in); it does not assign its argument to the _flags field.
bool hasVaddr () const
Accessor function for vaddr.
Addr getVaddr () const
MasterID masterId () const
Accesssor for the requestor id.
uint32_t taskId () const
void taskId (uint32_t id)
int getAsid () const
Accessor function for asid.
void setAsid (int asid)
Accessor function for asid.
ArchFlagsType getArchFlags () const
Accessor function for architecture-specific flags.
bool extraDataValid () const
Accessor function to check if sc result is valid.
uint64_t getExtraData () const
Accessor function for store conditional return value.
void setExtraData (uint64_t extraData)
Accessor function for store conditional return value.
bool hasContextId () const
int contextId () const
Accessor function for context ID.
ThreadID threadId () const
Accessor function for thread ID.
void setPC (Addr pc)
bool hasPC () const
Addr getPC () const
Accessor function for pc.
void incAccessDepth () const
Increment/Get the depth at which this request is responded to.
int getAccessDepth () const
void setTranslateLatency ()
Set/Get the time taken for this request to be successfully translated.
Tick getTranslateLatency () const
void setAccessLatency ()
Set/Get the time taken to complete this request's access, not including the time to successfully translate the request.
Tick getAccessLatency () const
bool isUncacheable () const
Accessor functions for flags.
bool isStrictlyOrdered () const
bool isInstFetch () const
bool isPrefetch () const
bool isLLSC () const
bool isPriv () const
bool isLockedRMW () const
bool isSwap () const
bool isCondSwap () const
bool isMmappedIpr () const
bool isClearLL () const
bool isSecure () const
bool isPTWalk () const
Public Attributes
Tick translateDelta
Time for the TLB/table walker to successfully translate this request.
Tick accessDelta
Access latency to complete this memory transaction not including translation time.
int depth
Level of the cache hierachy where this request was responded to (e.g.
Static Public Attributes
static const FlagsType ARCH_BITS = 0x000000FF
Architecture specific flags.
static const FlagsType INST_FETCH = 0x00000100
The request was an instruction fetch.
static const FlagsType PHYSICAL = 0x00000200
The virtual address is also the physical address.
static const FlagsType UNCACHEABLE = 0x00000400
The request is to an uncacheable address.
static const FlagsType STRICT_ORDER = 0x00000800
The request is required to be strictly ordered by CPU models and is non-speculative.
static const FlagsType MMAPPED_IPR = 0x00002000
This request is to a memory mapped register.
static const FlagsType CLEAR_LL = 0x00004000
This request is a clear exclusive.
static const FlagsType PRIVILEGED = 0x00008000
This request is made in privileged mode.
static const FlagsType CACHE_BLOCK_ZERO = 0x00010000
This is a write that is targeted and zeroing an entire cache block.
static const FlagsType NO_ACCESS = 0x00080000
The request should not cause a memory access.
static const FlagsType LOCKED_RMW = 0x00100000
This request will lock or unlock the accessed memory.
static const FlagsType LLSC = 0x00200000
The request is a Load locked/store conditional.
static const FlagsType MEM_SWAP = 0x00400000
This request is for a memory swap.
static const FlagsType MEM_SWAP_COND = 0x00800000
static const FlagsType PREFETCH = 0x01000000
The request is a prefetch.
static const FlagsType PF_EXCLUSIVE = 0x02000000
The request should be prefetched into the exclusive state.
static const FlagsType EVICT_NEXT = 0x04000000
The request should be marked as LRU.
static const FlagsType GENERIC_IPR = 0x08000000
The request should be handled by the generic IPR code (only valid together with MMAPPED_IPR).
static const FlagsType SECURE = 0x10000000
The request targets the secure memory space.
static const FlagsType PT_WALK = 0x20000000
The request is a page table walk.
static const FlagsType STICKY_FLAGS = INST_FETCH
These flags are *not* cleared when a Request object is reused (assigned a new address).
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const MasterID wbMasterId = 0
Request Ids that are statically allocated.
static const MasterID funcMasterId = 1
This request id is used for functional requests that don't come from a particular device.
static const MasterID intMasterId = 2
This request id is used for message signaled interrupts.
static const MasterID invldMasterId = std::numeric_limits<MasterID>::max()
Invalid request id for assertion checking only.
Private Types
typedef uint8_t PrivateFlagsType
typedef ::Flags< PrivateFlagsType > PrivateFlags
Private Member Functions
void setPhys (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time)
Set up a physical (e.g.
Private Attributes
Addr _paddr
The physical address of the request.
unsigned _size
The size of the request.
MasterID _masterId
The requestor ID which is unique in the system for all ports that are capable of issuing a transaction.
Flags _flags
Flag structure for the request.
PrivateFlags privateFlags
Private flags for field validity checking.
Tick _time
The time this request was started.
uint32_t _taskId
The task id associated with this request.
int _asid
The address space ID.
Addr _vaddr
The virtual address of the request.
uint64_t _extraData
Extra data for the request, such as the return value of store conditional or the compare value for a CAS.
int _contextId
The context ID (for statistics, typically).
ThreadID _threadId
The thread ID (id within this CPU).
Addr _pc
program counter of initiating access; for tracing/debugging
Static Private Attributes
static const PrivateFlagsType VALID_SIZE = 0x00000001
Whether or not the size is valid.
static const PrivateFlagsType VALID_PADDR = 0x00000002
Whether or not paddr is valid (has been written yet).
static const PrivateFlagsType VALID_VADDR = 0x00000004
Whether or not the vaddr & asid are valid.
static const PrivateFlagsType VALID_PC = 0x00000010
Whether or not the pc is valid.
static const PrivateFlagsType VALID_CONTEXT_ID = 0x00000020
Whether or not the context ID is valid.
static const PrivateFlagsType VALID_THREAD_ID = 0x00000040
static const PrivateFlagsType VALID_EXTRA_DATA = 0x00000080
Whether or not the sc result is valid.
static const PrivateFlagsType STICKY_PRIVATE_FLAGS
These flags are *not* cleared when a Request object is reused (assigned a new address).
Detailed Description
Definition at line 85 of file request.hh.
Member Typedef Documentation
typedef uint8_t Request::ArchFlagsType
Definition at line 89 of file request.hh.
typedef ::Flags<FlagsType> Request::Flags
Definition at line 90 of file request.hh.
typedef uint32_t Request::FlagsType
Definition at line 88 of file request.hh.
typedef ::Flags<PrivateFlagsType> Request::PrivateFlags [private]
Definition at line 191 of file request.hh.
typedef uint8_t Request::PrivateFlagsType [private]
Definition at line 190 of file request.hh.
Constructor & Destructor Documentation
Request::Request () [inline]
Minimal constructor.
No fields are initialized. (Note that _flags and privateFlags are cleared by Flags default constructor.)
Definition at line 297 of file request.hh.
Referenced by splitOnVaddr().
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid) [inline]
Constructor for physical (e.g.
device) requests. Initializes just physical address, size, flags, and timestamp (to curTick()). These fields are adequate to perform a request.
Definition at line 309 of file request.hh.
References curTick(), and setPhys().
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time) [inline]
Definition at line 318 of file request.hh.
References setPhys().
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time, Addr pc) [inline]
Definition at line 327 of file request.hh.
References _pc, privateFlags, Flags< T >::set(), setPhys(), and VALID_PC.
Request::Request (int asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, int cid, ThreadID tid) [inline]
Definition at line 339 of file request.hh.
References setThreadContext(), and setVirt().
Request::~Request () [inline]
Definition at line 350 of file request.hh.
Member Function Documentation
int Request::contextId () const [inline]
Accessor function for context ID.
Definition at line 579 of file request.hh.
References _contextId, Flags< T >::isSet(), privateFlags, and VALID_CONTEXT_ID.
Referenced by Cache::access(), AbstractMemory::checkLockedAddrList(), Sequencer::issueRequest(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), CacheBlk::Lock::matchesContext(), LockedAddr::matchesContext(), QueuedPrefetcher::notify(), Sinic::Device::read(), CpuLocalTimer::read(), TsunamiCChip::read(), Pl390::readCpu(), VGic::readCtrl(), Pl390::readDistributor(), Iob::readJBus(), VGic::readVCpu(), AbstractMemory::trackLoadLocked(), Sinic::Device::write(), CpuLocalTimer::write(), Pl390::writeCpu(), VGic::writeCtrl(), Pl390::writeDistributor(), Iob::writeJBus(), and VGic::writeVCpu().
bool Request::extraDataValid () const [inline]
Accessor function to check if sc result is valid.
Definition at line 550 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_EXTRA_DATA.
Referenced by CheckerCPU::writeMem().
int Request::getAccessDepth () const [inline]
Definition at line 619 of file request.hh.
References depth.
Tick Request::getAccessLatency () const [inline]
Definition at line 632 of file request.hh.
References accessDelta.
ArchFlagsType Request::getArchFlags () const [inline]
Accessor function for architecture-specific flags.
Definition at line 542 of file request.hh.
References _flags, ARCH_BITS, Flags< T >::isSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Referenced by SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), SparcISA::TLB::translateData(), and SparcISA::TLB::translateInst().
int Request::getAsid () const [inline]
Accessor function for asid.
Definition at line 527 of file request.hh.
References _asid, Flags< T >::isSet(), privateFlags, and VALID_VADDR.
uint64_t Request::getExtraData () const [inline]
Accessor function for store conditional return value.
Definition at line 557 of file request.hh.
References _extraData, Flags< T >::isSet(), privateFlags, and VALID_EXTRA_DATA.
Referenced by AbstractMemory::access(), Cache::cmpAndSwap(), BaseO3DynInst< Impl >::completeAcc(), RubyPort::MemSlavePort::hitCallback(), MemCheckerMonitor::recvTimingResp(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
Flags Request::getFlags () [inline]
Accessor for flags.
Definition at line 476 of file request.hh.
References _flags, Flags< T >::isSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Referenced by TimingSimpleCPU::buildSplitPacket(), CheckerCPU::checkFlags(), ArmISA::TLB::checkPermissions(), ArmISA::TLB::checkPermissions64(), TimingSimpleCPU::completeDataAccess(), WholeTranslationState::finish(), ArmISA::Stage2MMU::Stage2Translation::finish(), WholeTranslationState::getFlags(), GenericISA::isGenericIprAccess(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), Sequencer::makeRequest(), ArmISA::Stage2MMU::readDataUntimed(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), CommMonitor::recvAtomic(), CommMonitor::recvTimingReq(), Cache::recvTimingReq(), TimingSimpleCPU::sendData(), TimingSimpleCPU::sendSplitData(), ArmISA::Stage2LookUp::Stage2LookUp(), X86ISA::Walker::WalkerState::stepWalk(), X86ISA::TLB::translate(), AlphaISA::TLB::translateData(), ArmISA::TLB::translateFs(), AlphaISA::TLB::translateInst(), ArmISA::TLB::translateSe(), LSQUnit< Impl >::write(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
Addr Request::getPaddr () const [inline]
Definition at line 427 of file request.hh.
References _paddr, Flags< T >::isSet(), privateFlags, and VALID_PADDR.
Referenced by Minor::LSQ::StoreBuffer::canForwardDataToLoad(), AlphaISA::TLB::checkCacheability(), CheckerCPU::checkFlags(), AbstractMemory::checkLockedAddrList(), NetworkTest::completeRequest(), MemTest::completeRequest(), X86ISA::TLB::finalizePhysical(), WholeTranslationState::finish(), ArmISA::Stage2MMU::Stage2Translation::finish(), DefaultFetch< Impl >::finishTranslation(), Minor::LSQ::StoreBuffer::forwardStoreData(), NetworkTest::generatePkt(), WholeTranslationState::getPaddr(), ArmISA::TLB::getResultTe(), MipsISA::handleLockedRead(), ArmISA::handleLockedRead(), AlphaISA::handleLockedRead(), MipsISA::handleLockedWrite(), ArmISA::handleLockedWrite(), AlphaISA::handleLockedWrite(), Minor::Fetch1::handleTLBResponse(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), CacheBlk::Lock::matchesContext(), CacheBlk::Lock::overlapping(), Packet::Packet(), LSQUnit< Impl >::read(), CheckerCPU::readMem(), Cache::recvTimingReq(), DmaPort::sendDma(), TimingSimpleCPU::sendFetch(), MemTest::tick(), AbstractMemory::trackLoadLocked(), SparcISA::TLB::translateData(), AlphaISA::TLB::translateData(), SparcISA::TLB::translateInst(), AlphaISA::TLB::translateInst(), try_translate(), LSQUnit< Impl >::write(), LSQUnit< Impl >::writebackStores(), and CheckerCPU::writeMem().
Addr Request::getPC () const [inline]
Accessor function for pc.
Definition at line 608 of file request.hh.
References _pc, Flags< T >::isSet(), privateFlags, and VALID_PC.
Referenced by StridePrefetcher::calculatePrefetch(), ArmISA::TLB::checkPermissions64(), Sequencer::issueRequest(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), QueuedPrefetcher::notify(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
unsigned Request::getSize () const [inline]
Definition at line 460 of file request.hh.
References _size, Flags< T >::isSet(), privateFlags, and VALID_SIZE.
Referenced by Minor::ForwardLineData::adoptPacketData(), TimingSimpleCPU::buildSplitPacket(), Minor::LSQ::StoreBuffer::canForwardDataToLoad(), MemTest::completeRequest(), Minor::LSQ::StoreBuffer::forwardStoreData(), NetworkTest::generatePkt(), BaseGen::getPacket(), DmaPort::handleResp(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), CacheBlk::Lock::matchesContext(), CacheBlk::Lock::overlapping(), Packet::Packet(), LSQUnit< Impl >::read(), Cache::recvTimingReq(), Minor::LSQ::SplitDataRequest::retireResponse(), DmaPort::sendDma(), BaseDynInst< Impl >::splitRequest(), ArmISA::Stage2LookUp::Stage2LookUp(), PageTableBase::translate(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), AlphaISA::TLB::translateData(), SparcISA::TLB::translateInst(), PowerISA::TLB::translateInst(), X86ISA::TLB::translateInt(), LSQUnit< Impl >::write(), and LSQUnit< Impl >::writebackStores().
Tick Request::getTranslateLatency () const [inline]
Definition at line 625 of file request.hh.
References translateDelta.
Addr Request::getVaddr () const [inline]
Definition at line 501 of file request.hh.
References _vaddr, Flags< T >::isSet(), privateFlags, and VALID_VADDR.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), CheckerCPU::checkFlags(), ArmISA::TLB::checkPermissions(), ArmISA::TLB::checkPermissions64(), TimingSimpleCPU::fetch(), DefaultFetch< Impl >::finishTranslation(), ArmISA::TLB::getResultTe(), ArmISA::TLB::getTE(), Minor::Fetch1::handleTLBResponse(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), ArmISA::Stage2LookUp::mergeTe(), Minor::Fetch1::processResponse(), LSQUnit< Impl >::read(), CheckerCPU::readMem(), BaseDynInst< Impl >::readMem(), Minor::LSQ::SplitDataRequest::retireResponse(), TimingSimpleCPU::sendFetch(), BaseDynInst< Impl >::splitRequest(), ArmISA::Stage2LookUp::Stage2LookUp(), X86ISA::Walker::WalkerState::startWalk(), X86ISA::Walker::startWalkWrapper(), PageTableBase::translate(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), AlphaISA::TLB::translateData(), ArmISA::TLB::translateFs(), SparcISA::TLB::translateInst(), PowerISA::TLB::translateInst(), AlphaISA::TLB::translateInst(), X86ISA::TLB::translateInt(), ArmISA::TLB::translateSe(), Minor::LSQ::tryToSend(), ArmISA::TableWalker::walk(), CheckerCPU::writeMem(), and BaseDynInst< Impl >::writeMem().
bool Request::hasContextId () const [inline]
Definition at line 572 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_CONTEXT_ID.
Referenced by Cache::access(), Sequencer::issueRequest(), QueuedPrefetcher::notify(), Pl390::readCpu(), Pl390::writeCpu(), and Pl390::writeDistributor().
bool Request::hasPaddr () const [inline]
Accessor for paddr.
Definition at line 421 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_PADDR.
Referenced by ArmISA::TLB::getResultTe(), Minor::Fetch1::handleTLBResponse(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), Packet::Packet(), Cache::recvTimingReq(), and ArmISA::TLB::translateComplete().
bool Request::hasPC () const [inline]
Definition at line 601 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_PC.
Referenced by StridePrefetcher::calculatePrefetch(), Sequencer::issueRequest(), and QueuedPrefetcher::notify().
bool Request::hasSize () const [inline]
Accessor for size.
Definition at line 454 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_SIZE.
Referenced by Packet::Packet().
bool Request::hasVaddr () const [inline]
Accessor function for vaddr.
Definition at line 495 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_VADDR.
void Request::incAccessDepth () const [inline]
Increment/Get the depth at which this request is responded to.
This currently happens when the request misses in any cache level.
Definition at line 618 of file request.hh.
References depth.
Referenced by BaseCache::incMissCount().
bool Request::isClearLL () const [inline]
Definition at line 646 of file request.hh.
References _flags, CLEAR_LL, and Flags< T >::isSet().
Referenced by Cache::access().
bool Request::isCondSwap () const [inline]
Definition at line 644 of file request.hh.
References _flags, Flags< T >::isSet(), and MEM_SWAP_COND.
Referenced by AbstractMemory::access(), Cache::cmpAndSwap(), BaseDynInst< Impl >::finishTranslation(), TimingSimpleCPU::sendData(), and AtomicSimpleCPU::writeMem().
bool Request::isInstFetch () const [inline]
Definition at line 638 of file request.hh.
References _flags, INST_FETCH, and Flags< T >::isSet().
Referenced by Cache::access(), AbstractMemory::access(), Sequencer::makeRequest(), BasePrefetcher::observeAccess(), Cache::satisfyCpuSideRequest(), and ArmISA::TLB::translateFs().
bool Request::isLLSC () const [inline]
Definition at line 640 of file request.hh.
References _flags, Flags< T >::isSet(), and LLSC.
Referenced by TimingSimpleCPU::handleReadPacket(), Packet::makeReadCmd(), Packet::makeWriteCmd(), LSQUnit< Impl >::read(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), TimingSimpleCPU::sendData(), Minor::LSQ::tryToSendToTransfers(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
bool Request::isLockedRMW () const [inline]
Definition at line 642 of file request.hh.
References _flags, Flags< T >::isSet(), and LOCKED_RMW.
Referenced by Sequencer::makeRequest(), AtomicSimpleCPU::readMem(), and AtomicSimpleCPU::writeMem().
bool Request::isMmappedIpr () const [inline]
Definition at line 645 of file request.hh.
References _flags, Flags< T >::isSet(), and MMAPPED_IPR.
Referenced by TimingSimpleCPU::buildSplitPacket(), BaseKvmCPU::doMMIOAccess(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), LSQUnit< Impl >::read(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), Minor::LSQ::tryToSend(), Minor::LSQ::tryToSendToTransfers(), LSQUnit< Impl >::writebackStores(), and AtomicSimpleCPU::writeMem().
bool Request::isPrefetch () const [inline]
Definition at line 639 of file request.hh.
References _flags, Flags< T >::isSet(), and PREFETCH.
Referenced by ArmISA::TLB::checkPermissions(), ArmISA::TLB::checkPermissions64(), ArmISA::TLB::getTE(), WholeTranslationState::isPrefetch(), Packet::makeReadCmd(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), MemCheckerMonitor::recvTimingReq(), MemCheckerMonitor::recvTimingResp(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
bool Request::isPriv () const [inline]
Definition at line 641 of file request.hh.
References _flags, Flags< T >::isSet(), and PRIVILEGED.
bool Request::isPTWalk () const [inline]
Definition at line 648 of file request.hh.
References _flags, Flags< T >::isSet(), and PT_WALK.
Referenced by ArmISA::TLB::checkPermissions(), and ArmISA::TLB::checkPermissions64().
bool Request::isSecure () const [inline]
Definition at line 647 of file request.hh.
References _flags, Flags< T >::isSet(), and SECURE.
Referenced by Packet::Packet().
bool Request::isStrictlyOrdered () const [inline]
Definition at line 637 of file request.hh.
References _flags, Flags< T >::isSet(), and STRICT_ORDER.
Referenced by WholeTranslationState::isStrictlyOrdered(), LSQUnit< Impl >::read(), and Minor::LSQ::tryToSendToTransfers().
bool Request::isSwap () const [inline]
Definition at line 643 of file request.hh.
References _flags, Flags< T >::isSet(), MEM_SWAP, and MEM_SWAP_COND.
Referenced by ArmISA::handleLockedWrite(), Packet::makeWriteCmd(), TimingSimpleCPU::readMem(), Minor::LSQ::tryToSendToTransfers(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
bool Request::isUncacheable () const [inline]
Accessor functions for flags.
Note that these are for testing only; setting flags should be done via setFlags().
Definition at line 636 of file request.hh.
References _flags, Flags< T >::isSet(), and UNCACHEABLE.
Referenced by Cache::access(), MSHR::allocate(), AlphaISA::TLB::checkCacheability(), Cache::doTimingSupplyResponse(), Cache::getBusPacket(), MipsISA::handleLockedWrite(), AlphaISA::handleLockedWrite(), MSHR::handleSnoop(), Cache::handleSnoop(), SnoopFilter::lookupRequest(), BasePrefetcher::observeAccess(), CheckerCPU::readMem(), Cache::recvTimingReq(), Cache::recvTimingResp(), DmaPort::recvTimingResp(), FullO3CPU< Impl >::IcachePort::recvTimingResp(), SnoopFilter::updateRequest(), SnoopFilter::updateResponse(), and SnoopFilter::updateSnoopResponse().
MasterID Request::masterId () const [inline]
Accesssor for the requestor id.
Definition at line 509 of file request.hh.
References _masterId.
Referenced by AbstractMemory::access(), StridePrefetcher::calculatePrefetch(), Cache::getNextMSHR(), BaseCache::incHitCount(), BaseCache::incMissCount(), BaseSetAssoc::insertBlock(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), Cache::recvTimingReq(), Cache::recvTimingResp(), and ArmISA::Stage2LookUp::Stage2LookUp().
void Request::setAccessLatency () [inline]
Set/Get the time taken to complete this request's access, not including the time to successfully translate the request.
Definition at line 631 of file request.hh.
References _time, accessDelta, curTick(), and translateDelta.
Referenced by TimingSimpleCPU::completeDataAccess(), LSQUnit< Impl >::completeDataAccess(), TimingSimpleCPU::completeIfetch(), and DefaultFetch< Impl >::processCacheCompletion().
void Request::setAsid (int asid) [inline]
Accessor function for asid.
Definition at line 535 of file request.hh.
References _asid.
Referenced by ArmISA::TLB::translateFs().
void Request::setExtraData (uint64_t extraData) [inline]
Accessor function for store conditional return value.
Definition at line 565 of file request.hh.
References _extraData, privateFlags, Flags< T >::set(), and VALID_EXTRA_DATA.
Referenced by Cache::access(), AbstractMemory::checkLockedAddrList(), CacheBlk::checkWrite(), BaseO3DynInst< Impl >::completeAcc(), BaseDynInst< Impl >::finishTranslation(), Sequencer::handleLlsc(), MipsISA::handleLockedWrite(), ArmISA::handleLockedWrite(), AlphaISA::handleLockedWrite(), Cache::recvTimingResp(), TimingSimpleCPU::sendData(), AtomicSimpleCPU::writeMem(), and AbstractMemory::writeOK().
void Request::setFlags (Flags flags) [inline]
Note that unlike other accessors, this function sets *specific flags* (ORs them in); it does not assign its argument to the _flags field.
Thus this method should rightly be called setFlags() and not just flags().
Definition at line 487 of file request.hh.
References _flags, Flags< T >::isSet(), privateFlags, Flags< T >::set(), VALID_PADDR, and VALID_VADDR.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), AlphaISA::TLB::checkCacheability(), X86ISA::TLB::finalizePhysical(), WholeTranslationState::finish(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), QueuedPrefetcher::notify(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), ArmISA::TLB::translateFs(), AlphaISA::TLB::translateInst(), X86ISA::TLB::translateInt(), and Cache::writebackBlk().
void Request::setPaddr (Addr paddr) [inline]
Set just the physical address.
This usually used to record the result of a translation. However, when using virtualized CPUs setPhys() is sometimes called to finalize a physical address without a virtual address, so we can't check if the virtual address is valid.
Definition at line 395 of file request.hh.
References _paddr, privateFlags, Flags< T >::set(), and VALID_PADDR.
Referenced by AlphaISA::TLB::checkCacheability(), X86ISA::TLB::finalizePhysical(), WholeTranslationState::finish(), NetworkTest::generatePkt(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), PageTableBase::translate(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), AlphaISA::TLB::translateData(), ArmISA::TLB::translateFs(), SparcISA::TLB::translateInst(), AlphaISA::TLB::translateInst(), X86ISA::TLB::translateInt(), and ArmISA::TLB::translateSe().
void Request::setPC (Addr pc) [inline]
Definition at line 594 of file request.hh.
References _pc, privateFlags, Flags< T >::set(), and VALID_PC.
Referenced by BaseGen::getPacket(), and QueuedPrefetcher::notify().
void Request::setPhys (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time) [inline, private]
Set up a physical (e.g.
device) request in a previously allocated Request object.
Definition at line 219 of file request.hh.
References _flags, _masterId, _paddr, _size, _time, accessDelta, Flags< T >::clear(), depth, privateFlags, Flags< T >::set(), STICKY_FLAGS, STICKY_PRIVATE_FLAGS, VALID_PADDR, and VALID_SIZE.
Referenced by Request().
void Request::setThreadContext (int context_id, ThreadID tid) [inline]
Set up CPU and thread numbers.
Definition at line 356 of file request.hh.
References _contextId, _threadId, privateFlags, Flags< T >::set(), VALID_CONTEXT_ID, and VALID_THREAD_ID.
Referenced by BaseKvmCPU::doMMIOAccess(), TimingSimpleCPU::fetch(), Minor::Fetch1::fetchLine(), NetworkTest::generatePkt(), X86KvmCPU::handleKvmExitIO(), AtomicSimpleCPU::init(), Check::initiateCheck(), Check::initiatePrefetch(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), QueuedPrefetcher::notify(), Minor::LSQ::pushRequest(), Request(), AtomicSimpleCPU::takeOverFrom(), and MemTest::tick().
void Request::setTranslateLatency () [inline]
Set/Get the time taken for this request to be successfully translated.
Definition at line 624 of file request.hh.
References _time, curTick(), and translateDelta.
Referenced by DataTranslation< ExecContextPtr >::finish().
void Request::setVirt (int asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc) [inline]
Set up a virtual (e.g., CPU) request in a previously allocated Request object.
Definition at line 368 of file request.hh.
References _asid, _flags, _masterId, _pc, _size, _time, _vaddr, accessDelta, Flags< T >::clear(), curTick(), depth, privateFlags, Flags< T >::set(), STICKY_FLAGS, STICKY_PRIVATE_FLAGS, translateDelta, VALID_PC, VALID_SIZE, and VALID_VADDR.
Referenced by Minor::Fetch1::fetchLine(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), Minor::LSQ::pushRequest(), ArmISA::Stage2MMU::readDataUntimed(), AtomicSimpleCPU::readMem(), Request(), BaseSimpleCPU::setupFetchRequest(), ArmISA::Stage2MMU::Stage2Translation::setVirt(), ArmISA::Stage2LookUp::Stage2LookUp(), Checker< Impl >::verify(), and AtomicSimpleCPU::writeMem().
void Request::splitOnVaddr (Addr split_addr, RequestPtr & req1, RequestPtr & req2) [inline]
Generate two requests as if this request had been split into two pieces.
The original request can't have been translated already.
Definition at line 405 of file request.hh.
References _size, _vaddr, Flags< T >::isSet(), Flags< T >::noneSet(), privateFlags, Request(), VALID_PADDR, and VALID_VADDR.
Referenced by TimingSimpleCPU::readMem(), BaseDynInst< Impl >::splitRequest(), and TimingSimpleCPU::writeMem().
void Request::taskId (uint32_t id) [inline]
Definition at line 521 of file request.hh.
References _taskId.
uint32_t Request::taskId () const [inline]
Definition at line 515 of file request.hh.
References _taskId.
Referenced by DmaPort::dmaAction(), TimingSimpleCPU::fetch(), DefaultFetch< Impl >::fetchCacheLine(), ArmISA::TableWalker::fetchDescriptor(), BaseSetAssoc::insertBlock(), QueuedPrefetcher::notify(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), BaseDynInst< Impl >::readMem(), AtomicSimpleCPU::tick(), Cache::writebackBlk(), TimingSimpleCPU::writeMem(), AtomicSimpleCPU::writeMem(), and BaseDynInst< Impl >::writeMem().
ThreadID Request::threadId () const [inline]
Accessor function for thread ID.
Definition at line 587 of file request.hh.
References _threadId, Flags< T >::isSet(), privateFlags, and VALID_THREAD_ID.
Referenced by DefaultFetch< Impl >::finishTranslation(), MipsISA::handleLockedRead(), MipsISA::handleLockedWrite(), QueuedPrefetcher::notify(), DefaultFetch< Impl >::processCacheCompletion(), LSQ< Impl >::read(), LSQ< Impl >::recvTimingResp(), Minor::LSQ::tryToSend(), and LSQ< Impl >::write().
Tick Request::time () const [inline]
Accessor for time.
Definition at line 468 of file request.hh.
References _time, Flags< T >::isSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Member Data Documentation
int Request::_asid [private]
The address space ID.
Definition at line 272 of file request.hh.
Referenced by getAsid(), setAsid(), and setVirt().
int Request::_contextId [private]
The context ID (for statistics, typically).
Definition at line 283 of file request.hh.
Referenced by contextId(), and setThreadContext().
uint64_t Request::_extraData [private]
Extra data for the request, such as the return value of store conditional or the compare value for a CAS.
Definition at line 280 of file request.hh.
Referenced by getExtraData(), and setExtraData().
Flags Request::_flags [private]
Flag structure for the request.
Definition at line 254 of file request.hh.
Referenced by getArchFlags(), getFlags(), isClearLL(), isCondSwap(), isInstFetch(), isLLSC(), isLockedRMW(), isMmappedIpr(), isPrefetch(), isPriv(), isPTWalk(), isSecure(), isStrictlyOrdered(), isSwap(), isUncacheable(), setFlags(), setPhys(), and setVirt().
MasterID Request::_masterId [private]
The requestor ID which is unique in the system for all ports that are capable of issuing a transaction.
Definition at line 251 of file request.hh.
Referenced by masterId(), setPhys(), and setVirt().
Addr Request::_paddr [private]
The physical address of the request.
Valid only if validPaddr is set.
Definition at line 239 of file request.hh.
Referenced by getPaddr(), setPaddr(), and setPhys().
Addr Request::_pc [private]
program counter of initiating access; for tracing/debugging
Definition at line 288 of file request.hh.
Referenced by getPC(), Request(), setPC(), and setVirt().
unsigned Request::_size [private]
The size of the request.
This field must be set when vaddr or paddr is written via setVirt() or setPhys(), so it is always valid as long as one of the address fields is valid.
Definition at line 246 of file request.hh.
Referenced by getSize(), setPhys(), setVirt(), and splitOnVaddr().
uint32_t Request::_taskId [private]
The task id associated with this request.
Definition at line 269 of file request.hh.
Referenced by taskId().
ThreadID Request::_threadId [private]
The thread ID (id within this CPU).
Definition at line 285 of file request.hh.
Referenced by setThreadContext(), and threadId().
Tick Request::_time [private]
The time this request was started.
Used to calculate latencies. This field is set to curTick() any time paddr or vaddr is written.
Definition at line 264 of file request.hh.
Referenced by setAccessLatency(), setPhys(), setTranslateLatency(), setVirt(), and time().
Addr Request::_vaddr [private]
The virtual address of the request.
Definition at line 275 of file request.hh.
Referenced by getVaddr(), setVirt(), and splitOnVaddr().
Tick Request::accessDelta
Access latency to complete this memory transaction not including translation time.
Definition at line 442 of file request.hh.
Referenced by getAccessLatency(), setAccessLatency(), setPhys(), and setVirt().
const FlagsType Request::ARCH_BITS = 0x000000FF [static]
Architecture specific flags.
These bits int the flag field are reserved for architecture-specific code. For example, SPARC uses them to represent ASIs.
Definition at line 99 of file request.hh.
Referenced by getArchFlags().
const FlagsType Request::CACHE_BLOCK_ZERO = 0x00010000 [static]
This is a write that is targeted and zeroing an entire cache block.
There is no need for a read/modify/write
Definition at line 132 of file request.hh.
Referenced by Minor::LSQ::pushRequest(), LSQUnit< Impl >::write(), TimingSimpleCPU::writeMem(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
const FlagsType Request::CLEAR_LL = 0x00004000 [static]
This request is a clear exclusive.
Definition at line 125 of file request.hh.
Referenced by isClearLL(), and ArmISA::TLB::translateFs().
int Request::depth [mutable]
Level of the cache hierachy where this request was responded to (e.g.
0 = L1; 1 = L2).
Definition at line 448 of file request.hh.
Referenced by getAccessDepth(), incAccessDepth(), setPhys(), and setVirt().
const FlagsType Request::EVICT_NEXT = 0x04000000 [static]
The request should be marked as LRU.
Definition at line 154 of file request.hh.
const MasterID Request::funcMasterId = 1 [static]
This request id is used for functional requests that don't come from a particular device.
Definition at line 176 of file request.hh.
Referenced by CacheRecorder::enqueueNextFetchRequest(), CacheRecorder::enqueueNextFlushRequest(), MasterPort::printAddr(), PortProxy::readBlob(), RubyPort::ruby_eviction_callback(), System::System(), Cache::writebackVisitor(), and PortProxy::writeBlob().
const FlagsType Request::GENERIC_IPR = 0x08000000 [static]
The request should be handled by the generic IPR code (only valid together with MMAPPED_IPR).
Definition at line 158 of file request.hh.
Referenced by X86ISA::TLB::finalizePhysical(), and GenericISA::isGenericIprAccess().
const FlagsType Request::INST_FETCH = 0x00000100 [static]
The request was an instruction fetch.
Definition at line 101 of file request.hh.
Referenced by CacheRecorder::enqueueNextFetchRequest(), DefaultFetch< Impl >::fetchCacheLine(), Minor::Fetch1::fetchLine(), NetworkTest::generatePkt(), Check::initiateCheck(), Check::initiatePrefetch(), isInstFetch(), BaseSimpleCPU::setupFetchRequest(), and Checker< Impl >::verify().
const MasterID Request::intMasterId = 2 [static]
This request id is used for message signaled interrupts.
Definition at line 178 of file request.hh.
Referenced by X86ISA::prepIntRequest(), and System::System().
const MasterID Request::invldMasterId = std::numeric_limits<MasterID>::max() [static]
Invalid request id for assertion checking only.
It is invalid behavior to ever send this id as part of a request.
Todo:
C++1x replace with numeric_limits when constexpr is added
Definition at line 182 of file request.hh.
Referenced by BaseSetAssoc::invalidate().
const uint32_t Request::invldPid = std::numeric_limits<uint32_t>::max() [static]
Invalid or unknown Pid.
Possible when operating system is not present or has not assigned a pid yet
Definition at line 187 of file request.hh.
Referenced by LinuxArmSystem::startup().
const FlagsType Request::LLSC = 0x00200000 [static]
The request is a Load locked/store conditional.
Definition at line 144 of file request.hh.
Referenced by LSQUnit< Impl >::checkSnoop(), isLLSC(), and ArmISA::Memory64::setExcAcRel().
const FlagsType Request::LOCKED_RMW = 0x00100000 [static]
This request will lock or unlock the accessed memory.
When used with a load, the access locks the particular chunk of memory. When used with a store, it unlocks. The rule is that locked accesses have to be made up of a locked load, some operation on the data, and then a locked store.
Definition at line 142 of file request.hh.
Referenced by isLockedRMW().
const FlagsType Request::MEM_SWAP = 0x00400000 [static]
This request is for a memory swap.
Definition at line 146 of file request.hh.
Referenced by isSwap(), and writeMemAtomic().
const FlagsType Request::MEM_SWAP_COND = 0x00800000 [static]
Definition at line 147 of file request.hh.
Referenced by isCondSwap(), isSwap(), and writeMemAtomic().
const FlagsType Request::MMAPPED_IPR = 0x00002000 [static]
This request is to a memory mapped register.
Definition at line 123 of file request.hh.
Referenced by X86ISA::TLB::finalizePhysical(), GenericISA::isGenericIprAccess(), isMmappedIpr(), SparcISA::TLB::translateData(), and X86ISA::TLB::translateInt().
const FlagsType Request::NO_ACCESS = 0x00080000 [static]
The request should not cause a memory access.
Definition at line 135 of file request.hh.
Referenced by TimingSimpleCPU::buildSplitPacket(), TimingSimpleCPU::completeDataAccess(), ArmISA::Stage2MMU::Stage2Translation::finish(), ArmISA::Stage2MMU::readDataUntimed(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), TimingSimpleCPU::sendData(), TimingSimpleCPU::sendSplitData(), and AtomicSimpleCPU::writeMem().
const FlagsType Request::PF_EXCLUSIVE = 0x02000000 [static]
The request should be prefetched into the exclusive state.
Definition at line 152 of file request.hh.
Referenced by Check::initiatePrefetch().
const FlagsType Request::PHYSICAL = 0x00000200 [static]
The virtual address is also the physical address.
Definition at line 103 of file request.hh.
Referenced by X86ISA::Walker::WalkerState::setupWalk(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
const FlagsType Request::PREFETCH = 0x01000000 [static]
The request is a prefetch.
Definition at line 150 of file request.hh.
Referenced by Check::initiatePrefetch(), AlphaISA::DtbFault::invoke(), and isPrefetch().
PrivateFlags Request::privateFlags [private]
Private flags for field validity checking.
Definition at line 257 of file request.hh.
Referenced by contextId(), extraDataValid(), getArchFlags(), getAsid(), getExtraData(), getFlags(), getPaddr(), getPC(), getSize(), getVaddr(), hasContextId(), hasPaddr(), hasPC(), hasSize(), hasVaddr(), Request(), setExtraData(), setFlags(), setPaddr(), setPC(), setPhys(), setThreadContext(), setVirt(), splitOnVaddr(), threadId(), and time().
const FlagsType Request::PRIVILEGED = 0x00008000 [static]
This request is made in privileged mode.
Definition at line 127 of file request.hh.
Referenced by isPriv().
const FlagsType Request::PT_WALK = 0x20000000 [static]
The request is a page table walk.
Definition at line 163 of file request.hh.
Referenced by ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doLongDescriptor(), isPTWalk(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::Stage2MMU::readDataTimed(), and ArmISA::Stage2MMU::readDataUntimed().
const FlagsType Request::SECURE = 0x10000000 [static]
The request targets the secure memory space.
Definition at line 161 of file request.hh.
Referenced by ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doLongDescriptor(), isSecure(), QueuedPrefetcher::notify(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TLB::translateFs(), and Cache::writebackBlk().
const FlagsType Request::STICKY_FLAGS = INST_FETCH [static]
These flags are *not* cleared when a Request object is reused (assigned a new address).
Definition at line 167 of file request.hh.
Referenced by setPhys(), and setVirt().
const PrivateFlagsType Request::STICKY_PRIVATE_FLAGS [static, private]
Initial value:
        VALID_CONTEXT_ID | VALID_THREAD_ID
These flags are *not* cleared when a Request object is reused (assigned a new address).
Definition at line 209 of file request.hh.
Referenced by setPhys(), and setVirt().
const FlagsType Request::STRICT_ORDER = 0x00000800 [static]
The request is required to be strictly ordered by CPU models and is non-speculative.
A strictly ordered request is guaranteed to never be re-ordered or executed speculatively by a CPU model. The memory system may still reorder requests in caches unless the UNCACHEABLE flag is set as well.
Definition at line 121 of file request.hh.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), AlphaISA::TLB::checkCacheability(), X86ISA::TLB::finalizePhysical(), isStrictlyOrdered(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), ArmISA::TLB::translateFs(), and X86ISA::TLB::translateInt().
Tick Request::translateDelta
Time for the TLB/table walker to successfully translate this request.
Definition at line 436 of file request.hh.
Referenced by getTranslateLatency(), setAccessLatency(), setTranslateLatency(), and setVirt().
const FlagsType Request::UNCACHEABLE = 0x00000400 [static]
The request is to an uncacheable address.
Note:
Uncacheable accesses may be reordered by CPU models. The STRICT_ORDER flag should be set if such reordering is undesirable.
Definition at line 111 of file request.hh.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), AlphaISA::TLB::checkCacheability(), BaseKvmCPU::doMMIOAccess(), Pl111::fillFifo(), HDLcd::fillPixelBuffer(), X86ISA::TLB::finalizePhysical(), X86KvmCPU::handleKvmExitIO(), isUncacheable(), X86ISA::prepIntRequest(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), X86ISA::Walker::WalkerState::setupWalk(), X86ISA::Walker::WalkerState::stepWalk(), MemTest::tick(), X86ISA::TLB::translate(), SparcISA::TLB::translateData(), ArmISA::TLB::translateFs(), and X86ISA::TLB::translateInt().
const PrivateFlagsType Request::VALID_CONTEXT_ID = 0x00000020 [static, private]
Whether or not the context ID is valid.
Definition at line 202 of file request.hh.
Referenced by contextId(), hasContextId(), and setThreadContext().
const PrivateFlagsType Request::VALID_EXTRA_DATA = 0x00000080 [static, private]
Whether or not the sc result is valid.
Definition at line 205 of file request.hh.
Referenced by extraDataValid(), getExtraData(), and setExtraData().
const PrivateFlagsType Request::VALID_PADDR = 0x00000002 [static, private]
Whether or not paddr is valid (has been written yet).
Definition at line 196 of file request.hh.
Referenced by getArchFlags(), getFlags(), getPaddr(), hasPaddr(), setFlags(), setPaddr(), setPhys(), splitOnVaddr(), and time().
const PrivateFlagsType Request::VALID_PC = 0x00000010 [static, private]
Whether or not the pc is valid.
Definition at line 200 of file request.hh.
Referenced by getPC(), hasPC(), Request(), setPC(), and setVirt().
const PrivateFlagsType Request::VALID_SIZE = 0x00000001 [static, private]
Whether or not the size is valid.
Definition at line 194 of file request.hh.
Referenced by getSize(), hasSize(), setPhys(), and setVirt().
const PrivateFlagsType Request::VALID_THREAD_ID = 0x00000040 [static, private]
Definition at line 203 of file request.hh.
Referenced by setThreadContext(), and threadId().
const PrivateFlagsType Request::VALID_VADDR = 0x00000004 [static, private]
Whether or not the vaddr & asid are valid.
Definition at line 198 of file request.hh.
Referenced by getArchFlags(), getAsid(), getFlags(), getVaddr(), hasVaddr(), setFlags(), setVirt(), splitOnVaddr(), and time().
const MasterID Request::wbMasterId = 0 [static]
Request Ids that are statically allocated.
This request id is used for writeback requests by the caches
Definition at line 172 of file request.hh.
Referenced by System::System(), and Cache::writebackBlk().
The documentation for this class was generated from the following file:
mem/request.hh