gem5: LocalBP Class Reference
LocalBP Class Reference
Implements a local predictor that uses the PC to index into a table of counters.
#include <2bit_local.hh>
Public Member Functions
LocalBP (const LocalBPParams *params)
Default branch predictor constructor.
virtual void uncondBranch (Addr pc, void *&bp_history)
bool lookup (Addr branch_addr, void *&bp_history)
Looks up the given address in the branch predictor and returns a true/false value as to whether it is taken.
void btbUpdate (Addr branch_addr, void *&bp_history)
Updates the branch predictor to Not Taken if a BTB entry is invalid or not found.
void update (Addr branch_addr, bool taken, void *bp_history, bool squashed)
Updates the branch predictor with the actual result of a branch.
void retireSquashed (void *bp_history)
Deletes the associated history with a branch, performs no predictor updates.
void squash (void *bp_history)
void reset ()
Private Member Functions
bool getPrediction (uint8_t &count)
Returns the taken/not taken prediction given the value of the counter.
unsigned getLocalIndex (Addr &PC)
Calculates the local index based on the PC.
Private Attributes
std::vector< SatCounter > localCtrs
Array of counters that make up the local predictor.
unsigned localPredictorSize
Size of the local predictor.
unsigned localPredictorSets
Number of sets.
unsigned localCtrBits
Number of bits of the local predictor's counters.
unsigned indexMask
Mask to get index bits.
Detailed Description
Implements a local predictor that uses the PC to index into a table of counters.
Note that any time a pointer to the bp_history is given, it should be NULL using this predictor because it does not have any branch predictor state that needs to be recorded or updated; the update can be determined solely by the branch being taken or not taken.
Definition at line 61 of file 2bit_local.hh.
Constructor & Destructor Documentation
LocalBP::LocalBP (const LocalBPParams * params)
Default branch predictor constructor.
Definition at line 37 of file 2bit_local.cc.
References DPRINTF, fatal, ArmISA::i, indexMask, BPredUnit::instShiftAmt, isPowerOf2(), localCtrBits, localCtrs, localPredictorSets, and localPredictorSize.
Member Function Documentation
void LocalBP::btbUpdate (Addr branch_addr, void *& bp_history) [virtual]
Updates the branch predictor to Not Taken if a BTB entry is invalid or not found.
Parameters:
branch_addr The address of the branch to look up.
bp_history Pointer to any bp history state.
Returns:
Whether or not the branch is taken.
Implements BPredUnit.
Definition at line 81 of file 2bit_local.cc.
unsigned LocalBP::getLocalIndex (Addr & PC) [inline, private]
Calculates the local index based on the PC.
Definition at line 149 of file 2bit_local.cc.
References indexMask, and BPredUnit::instShiftAmt.
Referenced by lookup(), and update().
bool LocalBP::getPrediction (uint8_t & count) [inline, private]
Returns the taken/not taken prediction given the value of the counter.
Parameters:
count The value of the counter.
Returns:
The prediction based on the counter value.
Definition at line 141 of file 2bit_local.cc.
References localCtrBits.
Referenced by lookup().
bool LocalBP::lookup (Addr branch_addr, void *& bp_history) [virtual]
Looks up the given address in the branch predictor and returns a true/false value as to whether it is taken.
Parameters:
branch_addr The address of the branch to look up.
bp_history Pointer to any bp history state.
Returns:
Whether or not the branch is taken.
Implements BPredUnit.
Definition at line 89 of file 2bit_local.cc.
References DPRINTF, getLocalIndex(), getPrediction(), and localCtrs.
void LocalBP::reset ()
Definition at line 73 of file 2bit_local.cc.
References ArmISA::i, localCtrs, and localPredictorSets.
void LocalBP::retireSquashed (void * bp_history) [inline, virtual]
Deletes the associated history with a branch, performs no predictor updates.
Used for branches that mispredict and update tables but are still speculative and later retire.
Parameters:
bp_history History to delete associated with this predictor
Implements BPredUnit.
Definition at line 96 of file 2bit_local.hh.
void LocalBP::squash (void * bp_history) [inline, virtual]
Parameters:
bp_history Pointer to the history object. The predictor will need to update any state and delete the object.
Implements BPredUnit.
Definition at line 99 of file 2bit_local.hh.
void LocalBP::uncondBranch (Addr pc, void *& bp_history) [virtual]
Implements BPredUnit.
Definition at line 155 of file 2bit_local.cc.
void LocalBP::update (Addr branch_addr, bool taken, void * bp_history, bool squashed) [virtual]
Updates the branch predictor with the actual result of a branch.
Parameters:
branch_addr The address of the branch to update.
taken Whether or not the branch was taken.
Implements BPredUnit.
Definition at line 120 of file 2bit_local.cc.
References DPRINTF, getLocalIndex(), and localCtrs.
Member Data Documentation
unsigned LocalBP::indexMask [private]
Mask to get index bits.
Definition at line 129 of file 2bit_local.hh.
Referenced by getLocalIndex(), and LocalBP().
unsigned LocalBP::localCtrBits [private]
Number of bits of the local predictor's counters.
Definition at line 126 of file 2bit_local.hh.
Referenced by getPrediction(), and LocalBP().
std::vector<SatCounter> LocalBP::localCtrs [private]
Array of counters that make up the local predictor.
Definition at line 117 of file 2bit_local.hh.
Referenced by LocalBP(), lookup(), reset(), and update().
unsigned LocalBP::localPredictorSets [private]
Number of sets.
Definition at line 123 of file 2bit_local.hh.
Referenced by LocalBP(), and reset().
unsigned LocalBP::localPredictorSize [private]
Size of the local predictor.
Definition at line 120 of file 2bit_local.hh.
Referenced by LocalBP().
The documentation for this class was generated from the following files:
cpu/pred/2bit_local.hh
cpu/pred/2bit_local.cc