gem5: ArmLiveProcess Class Reference
ArmLiveProcess Class Reference
#include <process.hh>
Protected Member Functions
ArmLiveProcess (LiveProcessParams *params, ObjectFile *objFile, ObjectFile::Arch _arch)
template<class IntType >
void argsInit (int pageSize, ArmISA::IntRegIndex spIndex)
Protected Attributes
ObjectFile::Arch arch
Detailed Description
Definition at line 57 of file process.hh.
Constructor & Destructor Documentation
ArmLiveProcess::ArmLiveProcess (LiveProcessParams * params, ObjectFile * objFile, ObjectFile::Arch _arch) [protected]
Definition at line 60 of file process.cc.
Member Function Documentation
template<class IntType > void ArmLiveProcess::argsInit (int pageSize, ArmISA::IntRegIndex spIndex) [inline, protected]
Definition at line 143 of file process.cc.
References Process::allocateMem(), arch, ArmISA::ArgumentReg0, ArmISA::ArgumentReg1, ArmISA::ArgumentReg2, LiveProcess::argv, ObjectFile::Arm64, Process::contextIds, copyStringArray(), DPRINTF, LiveProcess::egid(), ObjectFile::entryPoint(), LiveProcess::envp, LiveProcess::euid(), ObjectFile::getOpSys(), System::getThreadContext(), LiveProcess::gid(), BigEndianGuest::htog(), ArmISA::i, Process::initVirtMem, ObjectFile::Linux, ObjectFile::loadSections(), LiveProcess::M5_AT_BASE, LiveProcess::M5_AT_CLKTCK, LiveProcess::M5_AT_EGID, LiveProcess::M5_AT_ENTRY, LiveProcess::M5_AT_EUID, LiveProcess::M5_AT_EXECFN, LiveProcess::M5_AT_FLAGS, LiveProcess::M5_AT_GID, LiveProcess::M5_AT_HWCAP, LiveProcess::M5_AT_PAGESZ, LiveProcess::M5_AT_PHDR, LiveProcess::M5_AT_PHENT, LiveProcess::M5_AT_PHNUM, LiveProcess::M5_AT_PLATFORM, LiveProcess::M5_AT_RANDOM, LiveProcess::M5_AT_SECURE, LiveProcess::M5_AT_UID, ArmISA::mask, LiveProcess::objFile, ArmISA::PageBytes, MipsISA::pc, ThreadContext::pcState(), ElfObject::programHeaderCount(), ElfObject::programHeaderSize(), ElfObject::programHeaderTable(), roundDown(), roundUp(), ThreadContext::setIntReg(), Process::stack_base, Process::stack_min, Process::stack_size, Process::system, ArmISA::tc, ObjectFile::Thumb, LiveProcess::uid(), SETranslatingPortProxy::writeBlob(), SETranslatingPortProxy::writeString(), and X86ISA::x.
Member Data Documentation
ObjectFile::Arch ArmLiveProcess::arch [protected]
Definition at line 60 of file process.hh.
Referenced by argsInit().
The documentation for this class was generated from the following files:
arch/arm/process.hh
arch/arm/process.cc