gem5: BaseGic Class Reference
BaseGic Class Reference
#include <base_gic.hh>
Public Types
typedef struct BaseGicParams Params
Public Member Functions
BaseGic (const Params *p)
virtual ~BaseGic ()
const Params * params () const
virtual void sendInt (uint32_t num)=0
Post an interrupt from a device that is connected to the GIC.
virtual void sendPPInt (uint32_t num, uint32_t cpu)=0
Interface call for private peripheral interrupts.
virtual void clearPPInt (uint32_t num, uint32_t cpu)=0
virtual void clearInt (uint32_t num)=0
Clear an interrupt from a device that is connected to the GIC.
Protected Attributes
Platform * platform
Platform this GIC belongs to.
Detailed Description
Definition at line 51 of file base_gic.hh.
Member Typedef Documentation
typedef struct BaseGicParams BaseGic::Params [read]
Reimplemented from PioDevice.
Reimplemented in Pl390.
Definition at line 54 of file base_gic.hh.
Constructor & Destructor Documentation
BaseGic::BaseGic (const Params * p)
Definition at line 45 of file base_gic.cc.
References fatal_if, and RealView::setGic().
BaseGic::~BaseGic () [virtual]
Definition at line 59 of file base_gic.cc.
Member Function Documentation
virtual void BaseGic::clearInt (uint32_t num) [pure virtual]
Clear an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC may de-assert it's CPU line.
Parameters:
num number of interrupt to send
Implemented in KvmGic, and Pl390.
Referenced by ArchTimer::Interrupt::clear(), UFSHostDevice::clearInterrupt(), RealView::clearPciInt(), Pl011::setInterrupts(), Sp804::Timer::write(), and Pl111::write().
virtual void BaseGic::clearPPInt (uint32_t num, uint32_t cpu) [pure virtual]
Implemented in KvmGic, and Pl390.
Referenced by ArchTimer::Interrupt::clear(), and VGic::unPostMaintInt().
const BaseGic::Params * BaseGic::params () const
Reimplemented from PioDevice.
Reimplemented in Pl390.
Definition at line 64 of file base_gic.cc.
References SimObject::_params.
virtual void BaseGic::sendInt (uint32_t num) [pure virtual]
Post an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC will pass this interrupt on through to a CPU.
Parameters:
num number of interrupt to send
Implemented in KvmGic, and Pl390.
Referenced by Sp804::Timer::counterAtZero(), PL031::counterMatch(), UFSHostDevice::generateInterrupt(), Pl111::generateInterrupt(), Pl011::generateInterrupt(), Pl050::generateInterrupt(), HDLcd::generateInterrupt(), RealView::postPciInt(), ArmISA::PMU::raiseInterrupt(), ArchTimer::Interrupt::send(), and Gicv2m::write().
virtual void BaseGic::sendPPInt (uint32_t num, uint32_t cpu) [pure virtual]
Interface call for private peripheral interrupts.
Parameters:
num number of interrupt to send
cpu CPU to forward interrupt to
Implemented in KvmGic, and Pl390.
Referenced by VGic::postMaintInt(), ArchTimer::Interrupt::send(), CpuLocalTimer::Timer::timerAtZero(), and CpuLocalTimer::Timer::watchdogAtZero().
Member Data Documentation
Platform* BaseGic::platform [protected]
Platform this GIC belongs to.
Definition at line 92 of file base_gic.hh.
Referenced by Pl390::driveLegFIQ(), Pl390::driveLegIRQ(), and Pl390::readCpu().
The documentation for this class was generated from the following files:
dev/arm/base_gic.hh
dev/arm/base_gic.cc