gem5: ArchTimer::Interrupt Class Reference
ArchTimer::Interrupt Class Reference
#include <generic_timer.hh>
Public Member Functions
Interrupt (BaseGic &gic, unsigned irq)
Interrupt (BaseGic &gic, unsigned irq, unsigned cpu)
void send ()
void clear ()
Private Attributes
BaseGic & _gic
const bool _ppi
const unsigned _irq
const unsigned _cpu
Detailed Description
Definition at line 108 of file generic_timer.hh.
Constructor & Destructor Documentation
ArchTimer::Interrupt::Interrupt (BaseGic & gic, unsigned irq) [inline]
Definition at line 111 of file generic_timer.hh.
ArchTimer::Interrupt::Interrupt (BaseGic & gic, unsigned irq, unsigned cpu) [inline]
Definition at line 114 of file generic_timer.hh.
Member Function Documentation
void ArchTimer::Interrupt::clear ()
Definition at line 223 of file generic_timer.cc.
References _cpu, _gic, _irq, _ppi, BaseGic::clearInt(), and BaseGic::clearPPInt().
void ArchTimer::Interrupt::send ()
Definition at line 212 of file generic_timer.cc.
References _cpu, _gic, _irq, _ppi, BaseGic::sendInt(), and BaseGic::sendPPInt().
Referenced by ArchTimer::counterLimitReached().
Member Data Documentation
const unsigned ArchTimer::Interrupt::_cpu [private]
Definition at line 124 of file generic_timer.hh.
Referenced by clear(), and send().
BaseGic& ArchTimer::Interrupt::_gic [private]
Definition at line 121 of file generic_timer.hh.
Referenced by clear(), and send().
const unsigned ArchTimer::Interrupt::_irq [private]
Definition at line 123 of file generic_timer.hh.
Referenced by clear(), and send().
const bool ArchTimer::Interrupt::_ppi [private]
Definition at line 122 of file generic_timer.hh.
Referenced by clear(), and send().
The documentation for this class was generated from the following files:
dev/arm/generic_timer.hh
dev/arm/generic_timer.cc