gem5: SimpleThread Class Reference
SimpleThread Class Reference
The SimpleThread object provides a combination of the ThreadState object and the ThreadContext interface.
#include <simple_thread.hh>
Public Types
typedef ThreadContext::Status Status
Public Member Functions
std::string name () const
SimpleThread (BaseCPU *_cpu, int _thread_num, System *_system, TheISA::TLB *_itb, TheISA::TLB *_dtb, TheISA::ISA *_isa, bool use_kernel_stats=true)
SimpleThread (BaseCPU *_cpu, int _thread_num, System *_system, Process *_process, TheISA::TLB *_itb, TheISA::TLB *_dtb, TheISA::ISA *_isa)
virtual ~SimpleThread ()
virtual void takeOverFrom (ThreadContext *oldContext)
void regStats (const std::string &name)
void copyState (ThreadContext *oldContext)
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
void startup ()
ThreadContext * getTC ()
Returns the pointer to this SimpleThread's ThreadContext.
void demapPage (Addr vaddr, uint64_t asn)
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
void dumpFuncProfile ()
Fault hwrei ()
bool simPalCheck (int palFunc)
Check for special simulator handling of specific PAL calls.
BaseCPU * getCpuPtr ()
TheISA::TLB * getITBPtr ()
TheISA::TLB * getDTBPtr ()
CheckerCPU * getCheckerCpuPtr ()
TheISA::Decoder * getDecoderPtr ()
System * getSystemPtr ()
Status status () const
Returns the status of this thread.
void setStatus (Status newStatus)
Sets the status of this thread.
void activate ()
Set the status to Active.
void suspend ()
Set the status to Suspended.
void halt ()
Set the status to Halted.
void copyArchRegs (ThreadContext *tc)
void clearArchRegs ()
uint64_t readIntReg (int reg_idx)
FloatReg readFloatReg (int reg_idx)
FloatRegBits readFloatRegBits (int reg_idx)
CCReg readCCReg (int reg_idx)
void setIntReg (int reg_idx, uint64_t val)
void setFloatReg (int reg_idx, FloatReg val)
void setFloatRegBits (int reg_idx, FloatRegBits val)
void setCCReg (int reg_idx, CCReg val)
TheISA::PCState pcState ()
void pcState (const TheISA::PCState &val)
void pcStateNoRecord (const TheISA::PCState &val)
Addr instAddr ()
Addr nextInstAddr ()
MicroPC microPC ()
bool readPredicate ()
void setPredicate (bool val)
MiscReg readMiscRegNoEffect (int misc_reg, ThreadID tid=0) const
MiscReg readMiscReg (int misc_reg, ThreadID tid=0)
void setMiscRegNoEffect (int misc_reg, const MiscReg &val, ThreadID tid=0)
void setMiscReg (int misc_reg, const MiscReg &val, ThreadID tid=0)
int flattenIntIndex (int reg)
int flattenFloatIndex (int reg)
int flattenCCIndex (int reg)
int flattenMiscIndex (int reg)
unsigned readStCondFailures ()
void setStCondFailures (unsigned sc_failures)
void syscall (int64_t callnum)
uint64_t readIntRegFlat (int idx)
void setIntRegFlat (int idx, uint64_t val)
FloatReg readFloatRegFlat (int idx)
void setFloatRegFlat (int idx, FloatReg val)
FloatRegBits readFloatRegBitsFlat (int idx)
void setFloatRegBitsFlat (int idx, FloatRegBits val)
CCReg readCCRegFlat (int idx)
void setCCRegFlat (int idx, CCReg val)
Public Attributes
ProxyThreadContext
< SimpleThread > * tc
System * system
TheISA::TLB * itb
TheISA::TLB * dtb
TheISA::Decoder decoder
FloatReg f [TheISA::NumFloatRegs]
FloatRegBits i [TheISA::NumFloatRegs]
Protected Types
typedef TheISA::MachInst MachInst
typedef TheISA::MiscReg MiscReg
typedef TheISA::FloatReg FloatReg
typedef TheISA::FloatRegBits FloatRegBits
typedef TheISA::CCReg CCReg
Protected Attributes
union {
FloatReg f [TheISA::NumFloatRegs]
FloatRegBits i [TheISA::NumFloatRegs]
} floatRegs
TheISA::IntReg intRegs [TheISA::NumIntRegs]
TheISA::CCReg ccRegs [TheISA::NumCCRegs]
TheISA::ISA *const isa
TheISA::PCState _pcState
bool predicate
Did this instruction execute or is it predicated false.
Detailed Description
The SimpleThread object provides a combination of the ThreadState object and the ThreadContext interface.
It implements the ThreadContext interface so that a ProxyThreadContext class can be made using SimpleThread as the template parameter (see thread_context.hh). It adds to the ThreadState object by adding all the objects needed for simple functional execution, including a simple architectural register file, and pointers to the ITB and DTB in full system mode. For CPU models that do not need more advanced ways to hold state (i.e. a separate physical register file, or separate fetch and commit PC's), this SimpleThread class provides all the necessary state for full architecture-level functional simulation. See the AtomicSimpleCPU or TimingSimpleCPU for examples.
Definition at line 97 of file simple_thread.hh.
Member Typedef Documentation
typedef TheISA::CCReg SimpleThread::CCReg [protected]
Definition at line 104 of file simple_thread.hh.
typedef TheISA::FloatReg SimpleThread::FloatReg [protected]
Definition at line 102 of file simple_thread.hh.
typedef TheISA::FloatRegBits SimpleThread::FloatRegBits [protected]
Definition at line 103 of file simple_thread.hh.
typedef TheISA::MachInst SimpleThread::MachInst [protected]
Definition at line 100 of file simple_thread.hh.
typedef TheISA::MiscReg SimpleThread::MiscReg [protected]
Definition at line 101 of file simple_thread.hh.
typedef ThreadContext::Status SimpleThread::Status
Reimplemented from ThreadState.
Definition at line 106 of file simple_thread.hh.
Constructor & Destructor Documentation
SimpleThread::SimpleThread (BaseCPU * _cpu, int _thread_num, System * _system, TheISA::TLB * _itb, TheISA::TLB * _dtb, TheISA::ISA * _isa, bool use_kernel_stats = true)
Definition at line 74 of file simple_thread.cc.
References ThreadState::baseCpu, clearArchRegs(), dumpFuncProfile(), ThreadState::kernelStats, System::kernelSymtab, ThreadState::profile, ThreadState::profileNode, ThreadState::profilePC, ThreadState::quiesceEvent, registerExitCallback(), system, and tc.
SimpleThread::SimpleThread (BaseCPU * _cpu, int _thread_num, System * _system, Process * _process, TheISA::TLB * _itb, TheISA::TLB * _dtb, TheISA::ISA * _isa)
Definition at line 63 of file simple_thread.cc.
References clearArchRegs(), and tc.
SimpleThread::~SimpleThread () [virtual]
Definition at line 104 of file simple_thread.cc.
References tc.
Member Function Documentation
void SimpleThread::activate ()
Set the status to Active.
Definition at line 163 of file simple_thread.cc.
References ThreadState::_status, ThreadState::_threadId, ThreadContext::Active, ThreadState::baseCpu, curTick(), ThreadState::lastActivate, and status().
Referenced by BaseSimpleCPU::wakeup(), and BaseKvmCPU::wakeup().
void SimpleThread::clearArchRegs () [inline]
Definition at line 225 of file simple_thread.hh.
References _pcState, ccRegs, floatRegs, intRegs, and isa.
Referenced by CheckerThreadContext< TC >::clearArchRegs(), and SimpleThread().
void SimpleThread::copyArchRegs (ThreadContext * tc)
Definition at line 205 of file simple_thread.cc.
References AlphaISA::copyRegs(), and tc.
Referenced by CheckerThreadContext< TC >::copyArchRegs(), copyState(), and Checker< Impl >::validateState().
void SimpleThread::copyState (ThreadContext * oldContext)
Definition at line 121 of file simple_thread.cc.
References ThreadState::_contextId, ThreadState::_status, ThreadState::_threadId, ThreadContext::contextId(), copyArchRegs(), FullSystem, ThreadState::funcExeInst, ThreadContext::readFuncExeInst(), ThreadContext::status(), and ThreadContext::threadId().
Referenced by CheckerThreadContext< TC >::takeOverFrom().
void SimpleThread::demapDataPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 183 of file simple_thread.hh.
References dtb.
Referenced by BaseSimpleCPU::demapDataPage().
void SimpleThread::demapInstPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 178 of file simple_thread.hh.
References itb.
Referenced by BaseSimpleCPU::demapInstPage().
void SimpleThread::demapPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 172 of file simple_thread.hh.
References dtb, and itb.
Referenced by BaseSimpleCPU::demapPage().
void SimpleThread::dumpFuncProfile ()
Reimplemented from ThreadState.
Definition at line 155 of file simple_thread.cc.
References ThreadState::baseCpu, OutputDirectory::create(), csprintf(), FunctionProfile::dump(), X86ISA::os, ThreadState::profile, simout, and tc.
Referenced by SimpleThread().
int SimpleThread::flattenCCIndex (int reg) [inline]
Definition at line 411 of file simple_thread.hh.
References isa.
int SimpleThread::flattenFloatIndex (int reg) [inline]
Definition at line 405 of file simple_thread.hh.
References isa.
int SimpleThread::flattenIntIndex (int reg) [inline]
Definition at line 399 of file simple_thread.hh.
References isa.
int SimpleThread::flattenMiscIndex (int reg) [inline]
Definition at line 417 of file simple_thread.hh.
References isa.
CheckerCPU* SimpleThread::getCheckerCpuPtr () [inline]
Definition at line 204 of file simple_thread.hh.
BaseCPU* SimpleThread::getCpuPtr () [inline]
Definition at line 198 of file simple_thread.hh.
References ThreadState::baseCpu.
TheISA::Decoder* SimpleThread::getDecoderPtr () [inline]
Definition at line 206 of file simple_thread.hh.
References decoder.
TheISA::TLB* SimpleThread::getDTBPtr () [inline]
Definition at line 202 of file simple_thread.hh.
References dtb.
Referenced by Minor::ExecContext::demapDataPage(), and Minor::ExecContext::demapPage().
TheISA::TLB* SimpleThread::getITBPtr () [inline]
Definition at line 200 of file simple_thread.hh.
References itb.
Referenced by Minor::ExecContext::demapInstPage(), and Minor::ExecContext::demapPage().
System* SimpleThread::getSystemPtr () [inline]
Definition at line 208 of file simple_thread.hh.
References system.
ThreadContext* SimpleThread::getTC () [inline]
Returns the pointer to this SimpleThread's ThreadContext.
Used when a ThreadContext must be passed to objects outside of the CPU.
Definition at line 170 of file simple_thread.hh.
References tc.
Referenced by BaseKvmCPU::BaseKvmCPU(), BaseSimpleCPU::BaseSimpleCPU(), BaseKvmCPU::doMMIOAccess(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), MinorCPU::MinorCPU(), AtomicSimpleCPU::readMem(), CheckerCPU::setSystem(), Minor::ExecContext::tcBase(), and AtomicSimpleCPU::writeMem().
void SimpleThread::halt ()
Set the status to Halted.
Definition at line 187 of file simple_thread.cc.
References ThreadState::_status, ThreadState::_threadId, ThreadState::baseCpu, ThreadContext::Halted, and status().
Referenced by simPalCheck().
Fault SimpleThread::hwrei ()
Definition at line 472 of file ev5.cc.
References CPA::cpa(), AlphaISA::IPR_EXC_ADDR, ThreadState::kernelStats, GenericISA::SimplePCState< MachInst >::npc(), GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, pcState(), readMiscRegNoEffect(), and CPA::swAutoBegin().
Referenced by Minor::ExecContext::hwrei(), CheckerCPU::hwrei(), and BaseSimpleCPU::hwrei().
Addr SimpleThread::instAddr () [inline]
Definition at line 347 of file simple_thread.hh.
References _pcState.
Referenced by BaseSimpleCPU::checkPcEventQueue(), CheckerCPU::instAddr(), BaseSimpleCPU::instAddr(), TimingSimpleCPU::readMem(), BaseSimpleCPU::setupFetchRequest(), Checker< Impl >::validateInst(), Checker< Impl >::verify(), and TimingSimpleCPU::writeMem().
MicroPC SimpleThread::microPC () [inline]
Definition at line 359 of file simple_thread.hh.
References _pcState.
Referenced by CheckerCPU::microPC(), and BaseSimpleCPU::microPC().
std::string SimpleThread::name () const [inline]
Definition at line 125 of file simple_thread.hh.
References ThreadState::baseCpu, csprintf(), tc, and ProxyThreadContext< TC >::threadId().
Addr SimpleThread::nextInstAddr () [inline]
Definition at line 353 of file simple_thread.hh.
References _pcState.
Referenced by CheckerCPU::nextInstAddr(), BaseSimpleCPU::nextInstAddr(), and Checker< Impl >::validateExecution().
void SimpleThread::pcState (const TheISA::PCState & val) [inline]
Definition at line 335 of file simple_thread.hh.
References _pcState.
TheISA::PCState SimpleThread::pcState () [inline]
Definition at line 329 of file simple_thread.hh.
References _pcState.
Referenced by Checker< Impl >::advancePC(), BaseSimpleCPU::advancePC(), CheckerCPU::dumpAndExit(), TimingSimpleCPU::fetch(), Checker< Impl >::handlePendingInt(), hwrei(), Minor::ExecContext::pcState(), CheckerThreadContext< TC >::pcState(), CheckerCPU::pcState(), BaseSimpleCPU::pcState(), BaseSimpleCPU::preExecute(), SimPoint::profile(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), AtomicSimpleCPU::tick(), Minor::LSQ::tryToSendToTransfers(), Checker< Impl >::validateInst(), Checker< Impl >::verify(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
void SimpleThread::pcStateNoRecord (const TheISA::PCState & val) [inline]
Definition at line 341 of file simple_thread.hh.
References _pcState.
CCReg SimpleThread::readCCReg (int reg_idx) [inline]
Definition at line 269 of file simple_thread.hh.
References DPRINTF, isa, AlphaISA::NumCCRegs, panic, and readCCRegFlat().
Referenced by Minor::ExecContext::readCCRegOperand(), CheckerCPU::readCCRegOperand(), and BaseSimpleCPU::readCCRegOperand().
CCReg SimpleThread::readCCRegFlat (int idx) [inline]
Definition at line 444 of file simple_thread.hh.
References ccRegs.
Referenced by readCCReg().
FloatReg SimpleThread::readFloatReg (int reg_idx) [inline]
Definition at line 249 of file simple_thread.hh.
References DPRINTF, floatRegs, isa, AlphaISA::NumFloatRegs, and readFloatRegFlat().
Referenced by Minor::ExecContext::readFloatRegOperand(), CheckerCPU::readFloatRegOperand(), and BaseSimpleCPU::readFloatRegOperand().
FloatRegBits SimpleThread::readFloatRegBits (int reg_idx) [inline]
Definition at line 259 of file simple_thread.hh.
References DPRINTF, floatRegs, isa, AlphaISA::NumFloatRegs, and readFloatRegBitsFlat().
Referenced by Minor::ExecContext::readFloatRegOperandBits(), CheckerCPU::readFloatRegOperandBits(), BaseSimpleCPU::readFloatRegOperandBits(), and Minor::ExecContext::readRegOtherThread().
FloatRegBits SimpleThread::readFloatRegBitsFlat (int idx) [inline]
Definition at line 438 of file simple_thread.hh.
References floatRegs.
Referenced by readFloatRegBits().
FloatReg SimpleThread::readFloatRegFlat (int idx) [inline]
Definition at line 435 of file simple_thread.hh.
References floatRegs.
Referenced by readFloatReg().
uint64_t SimpleThread::readIntReg (int reg_idx) [inline]
Definition at line 239 of file simple_thread.hh.
References DPRINTF, isa, AlphaISA::NumIntRegs, and readIntRegFlat().
Referenced by Minor::ExecContext::readIntRegOperand(), CheckerCPU::readIntRegOperand(), BaseSimpleCPU::readIntRegOperand(), and Minor::ExecContext::readRegOtherThread().
uint64_t SimpleThread::readIntRegFlat (int idx) [inline]
Definition at line 432 of file simple_thread.hh.
References intRegs.
Referenced by readIntReg().
MiscReg SimpleThread::readMiscReg (int misc_reg, ThreadID tid = 0) [inline]
Definition at line 381 of file simple_thread.hh.
References isa, and tc.
Referenced by Minor::ExecContext::readMiscReg(), CheckerCPU::readMiscReg(), BaseSimpleCPU::readMiscReg(), Minor::ExecContext::readMiscRegOperand(), CheckerCPU::readMiscRegOperand(), BaseSimpleCPU::readMiscRegOperand(), and Minor::ExecContext::readRegOtherThread().
MiscReg SimpleThread::readMiscRegNoEffect (int misc_reg, ThreadID tid = 0) const [inline]
Definition at line 375 of file simple_thread.hh.
References isa.
Referenced by hwrei(), Minor::ExecContext::readMiscRegNoEffect(), CheckerCPU::readMiscRegNoEffect(), BaseSimpleCPU::readMiscRegNoEffect(), and Checker< Impl >::validateExecution().
bool SimpleThread::readPredicate () [inline]
Definition at line 364 of file simple_thread.hh.
References predicate.
Referenced by Minor::ExecContext::readPredicate(), CheckerCPU::readPredicate(), and BaseSimpleCPU::readPredicate().
unsigned SimpleThread::readStCondFailures () [inline]
Definition at line 422 of file simple_thread.hh.
References ThreadState::storeCondFailures.
Referenced by CheckerCPU::readStCondFailures(), and BaseSimpleCPU::readStCondFailures().
void SimpleThread::regStats (const std::string & name)
Referenced by CheckerThreadContext< TC >::regStats().
void SimpleThread::serialize (std::ostream & os)
Reimplemented from ThreadState.
Referenced by BaseKvmCPU::serializeThread().
void SimpleThread::setCCReg (int reg_idx, CCReg val) [inline]
Definition at line 315 of file simple_thread.hh.
References DPRINTF, isa, AlphaISA::NumCCRegs, panic, and setCCRegFlat().
Referenced by Checker< Impl >::copyResult(), CheckerThreadContext< TC >::setCCReg(), Minor::ExecContext::setCCRegOperand(), CheckerCPU::setCCRegOperand(), and BaseSimpleCPU::setCCRegOperand().
void SimpleThread::setCCRegFlat (int idx, CCReg val) [inline]
Definition at line 445 of file simple_thread.hh.
References ccRegs.
Referenced by setCCReg().
void SimpleThread::setFloatReg (int reg_idx, FloatReg val) [inline]
Definition at line 294 of file simple_thread.hh.
References DPRINTF, floatRegs, isa, AlphaISA::NumFloatRegs, and setFloatRegFlat().
Referenced by Minor::ExecContext::ExecContext(), BaseSimpleCPU::preExecute(), CheckerThreadContext< TC >::setFloatReg(), Minor::ExecContext::setFloatRegOperand(), CheckerCPU::setFloatRegOperand(), BaseSimpleCPU::setFloatRegOperand(), and Checker< Impl >::verify().
void SimpleThread::setFloatRegBits (int reg_idx, FloatRegBits val) [inline]
Definition at line 303 of file simple_thread.hh.
References DPRINTF, floatRegs, isa, AlphaISA::NumFloatRegs, and setFloatRegBitsFlat().
Referenced by Checker< Impl >::copyResult(), CheckerThreadContext< TC >::setFloatRegBits(), Minor::ExecContext::setFloatRegOperandBits(), CheckerCPU::setFloatRegOperandBits(), BaseSimpleCPU::setFloatRegOperandBits(), and Minor::ExecContext::setRegOtherThread().
void SimpleThread::setFloatRegBitsFlat (int idx, FloatRegBits val) [inline]
Definition at line 439 of file simple_thread.hh.
References floatRegs.
Referenced by setFloatRegBits().
void SimpleThread::setFloatRegFlat (int idx, FloatReg val) [inline]
Definition at line 436 of file simple_thread.hh.
References floatRegs.
Referenced by setFloatReg().
void SimpleThread::setIntReg (int reg_idx, uint64_t val) [inline]
Definition at line 285 of file simple_thread.hh.
References DPRINTF, isa, AlphaISA::NumIntRegs, and setIntRegFlat().
Referenced by Checker< Impl >::copyResult(), Minor::ExecContext::ExecContext(), BaseSimpleCPU::preExecute(), CheckerThreadContext< TC >::setIntReg(), Minor::ExecContext::setIntRegOperand(), CheckerCPU::setIntRegOperand(), BaseSimpleCPU::setIntRegOperand(), Minor::ExecContext::setRegOtherThread(), and Checker< Impl >::verify().
void SimpleThread::setIntRegFlat (int idx, uint64_t val) [inline]
Definition at line 433 of file simple_thread.hh.
References intRegs.
Referenced by setIntReg().
void SimpleThread::setMiscReg (int misc_reg, const MiscReg & val, ThreadID tid = 0) [inline]
Definition at line 393 of file simple_thread.hh.
References isa, and tc.
Referenced by Checker< Impl >::copyResult(), Minor::ExecContext::setMiscReg(), CheckerThreadContext< TC >::setMiscReg(), CheckerCPU::setMiscReg(), BaseSimpleCPU::setMiscReg(), Minor::ExecContext::setMiscRegOperand(), BaseSimpleCPU::setMiscRegOperand(), and Minor::ExecContext::setRegOtherThread().
void SimpleThread::setMiscRegNoEffect (int misc_reg, const MiscReg & val, ThreadID tid = 0) [inline]
Definition at line 387 of file simple_thread.hh.
References isa.
Referenced by CheckerThreadContext< TC >::setMiscRegNoEffect(), and CheckerCPU::setMiscRegNoEffect().
void SimpleThread::setPredicate (bool val) [inline]
Definition at line 369 of file simple_thread.hh.
References predicate.
Referenced by Minor::ExecContext::setPredicate(), CheckerCPU::setPredicate(), and BaseSimpleCPU::setPredicate().
void SimpleThread::setStatus (Status new_status) [inline]
Sets the status of this thread.
Reimplemented from ThreadState.
Definition at line 212 of file simple_thread.hh.
References ThreadState::_status.
Referenced by BaseKvmCPU::BaseKvmCPU(), BaseSimpleCPU::BaseSimpleCPU(), MinorCPU::MinorCPU(), and CheckerThreadContext< TC >::setStatus().
void SimpleThread::setStCondFailures (unsigned sc_failures) [inline]
Definition at line 424 of file simple_thread.hh.
References ThreadState::storeCondFailures.
Referenced by BaseSimpleCPU::setStCondFailures().
bool SimpleThread::simPalCheck (int palFunc)
Check for special simulator handling of specific PAL calls.
If return value is false, actual PAL call will be suppressed.
Definition at line 495 of file ev5.cc.
References PAL::bpt, System::breakpoint(), PAL::bugchk, exitSimLoop(), halt(), PAL::halt, ThreadState::kernelStats, System::numSystemsRunning, and system.
Referenced by Minor::ExecContext::simPalCheck(), CheckerCPU::simPalCheck(), and BaseSimpleCPU::simPalCheck().
void SimpleThread::startup ()
Definition at line 149 of file simple_thread.cc.
References isa, and tc.
Referenced by BaseSimpleCPU::startup(), and BaseKvmCPU::startup().
Status SimpleThread::status () const [inline]
Returns the status of this thread.
Reimplemented from ThreadState.
Definition at line 210 of file simple_thread.hh.
References ThreadState::_status.
Referenced by activate(), TimingSimpleCPU::drainResume(), AtomicSimpleCPU::drainResume(), halt(), suspend(), BaseSimpleCPU::wakeup(), and BaseKvmCPU::wakeup().
void SimpleThread::suspend ()
Set the status to Suspended.
Definition at line 174 of file simple_thread.cc.
References ThreadState::_status, ThreadState::_threadId, ThreadState::baseCpu, curTick(), ThreadState::lastActivate, ThreadState::lastSuspend, status(), and ThreadContext::Suspended.
Referenced by X86KvmCPU::deliverInterrupts(), and BaseKvmCPU::handleKvmExit().
void SimpleThread::syscall (int64_t callnum) [inline]
Definition at line 427 of file simple_thread.hh.
References ThreadState::process, Process::syscall(), and tc.
Referenced by Minor::ExecContext::syscall(), and BaseSimpleCPU::syscall().
void SimpleThread::takeOverFrom (ThreadContext * oldContext) [virtual]
Definition at line 110 of file simple_thread.cc.
References decoder, ThreadState::funcExeInst, ThreadContext::getDecoderPtr(), ThreadContext::getKernelStats(), ThreadState::kernelStats, ThreadContext::readFuncExeInst(), ThreadState::storeCondFailures, and tc.
void SimpleThread::unserialize (Checkpoint * cp, const std::string & section)
Reimplemented from ThreadState.
Definition at line 142 of file simple_thread.cc.
References tc.
Referenced by BaseKvmCPU::unserializeThread().
Member Data Documentation
TheISA::PCState SimpleThread::_pcState [protected]
Definition at line 119 of file simple_thread.hh.
Referenced by clearArchRegs(), instAddr(), microPC(), nextInstAddr(), pcState(), and pcStateNoRecord().
TheISA::CCReg SimpleThread::ccRegs[TheISA::NumCCRegs] [protected]
Definition at line 115 of file simple_thread.hh.
Referenced by clearArchRegs(), readCCRegFlat(), and setCCRegFlat().
TheISA::Decoder SimpleThread::decoder
Definition at line 137 of file simple_thread.hh.
Referenced by Checker< Impl >::advancePC(), BaseSimpleCPU::advancePC(), BaseSimpleCPU::checkForInterrupts(), getDecoderPtr(), Checker< Impl >::handlePendingInt(), BaseSimpleCPU::preExecute(), takeOverFrom(), and Checker< Impl >::verify().
TheISA::TLB* SimpleThread::dtb
Definition at line 135 of file simple_thread.hh.
Referenced by demapDataPage(), demapPage(), getDTBPtr(), Minor::ExecContext::mwaitAtomic(), CheckerCPU::mwaitAtomic(), BaseSimpleCPU::mwaitAtomic(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
FloatReg SimpleThread::f[TheISA::NumFloatRegs]
Definition at line 110 of file simple_thread.hh.
union { ... } SimpleThread::floatRegs [protected]
Referenced by clearArchRegs(), readFloatReg(), readFloatRegBits(), readFloatRegBitsFlat(), readFloatRegFlat(), setFloatReg(), setFloatRegBits(), setFloatRegBitsFlat(), and setFloatRegFlat().
FloatRegBits SimpleThread::i[TheISA::NumFloatRegs]
Definition at line 111 of file simple_thread.hh.
TheISA::IntReg SimpleThread::intRegs[TheISA::NumIntRegs] [protected]
Definition at line 113 of file simple_thread.hh.
Referenced by clearArchRegs(), readIntRegFlat(), and setIntRegFlat().
TheISA::ISA* const SimpleThread::isa [protected]
Definition at line 117 of file simple_thread.hh.
Referenced by clearArchRegs(), flattenCCIndex(), flattenFloatIndex(), flattenIntIndex(), flattenMiscIndex(), readCCReg(), readFloatReg(), readFloatRegBits(), readIntReg(), readMiscReg(), readMiscRegNoEffect(), setCCReg(), setFloatReg(), setFloatRegBits(), setIntReg(), setMiscReg(), setMiscRegNoEffect(), and startup().
TheISA::TLB* SimpleThread::itb
Definition at line 134 of file simple_thread.hh.
Referenced by demapInstPage(), demapPage(), TimingSimpleCPU::fetch(), getITBPtr(), and AtomicSimpleCPU::tick().
bool SimpleThread::predicate [protected]
Did this instruction execute or is it predicated false.
Definition at line 122 of file simple_thread.hh.
Referenced by readPredicate(), and setPredicate().
System* SimpleThread::system
Definition at line 132 of file simple_thread.hh.
Referenced by getSystemPtr(), simPalCheck(), and SimpleThread().
ProxyThreadContext<SimpleThread>* SimpleThread::tc
Definition at line 130 of file simple_thread.hh.
Referenced by copyArchRegs(), dumpFuncProfile(), getTC(), name(), readMiscReg(), setMiscReg(), SimpleThread(), startup(), syscall(), takeOverFrom(), unserialize(), and ~SimpleThread().
The documentation for this class was generated from the following files:
cpu/simple_thread.hh
arch/alpha/ev5.cc
cpu/simple_thread.cc