gem5: ArmISA::ArmStaticInst Class Reference
ArmISA::ArmStaticInst Class Reference
#include <static_inst.hh>
Public Member Functions
virtual void annotateFault (ArmFault *fault)
Protected Member Functions
int32_t shift_rm_imm (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const
int32_t shift_rm_rs (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const
bool shift_carry_imm (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const
bool shift_carry_rs (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const
int64_t shiftReg64 (uint64_t base, uint64_t shiftAmt, ArmShiftType type, uint8_t width) const
int64_t extendReg64 (uint64_t base, ArmExtendType type, uint64_t shiftAmt, uint8_t width) const
ArmStaticInst (const char *mnem, ExtMachInst _machInst, OpClass __opClass)
void printReg (std::ostream &os, int reg) const
Print a register name for disassembly given the unique dependence tag number (FP or int).
void printMnemonic (std::ostream &os, const std::string &suffix="", bool withPred=true, bool withCond64=false, ConditionCode cond64=COND_UC) const
void printTarget (std::ostream &os, Addr target, const SymbolTable *symtab) const
void printCondition (std::ostream &os, unsigned code, bool noImplicit=false) const
void printMemSymbol (std::ostream &os, const SymbolTable *symtab, const std::string &prefix, const Addr addr, const std::string &suffix) const
void printShiftOperand (std::ostream &os, IntRegIndex rm, bool immShift, uint32_t shiftAmt, IntRegIndex rs, ArmShiftType type) const
void printExtendOperand (bool firstOperand, std::ostream &os, IntRegIndex rm, ArmExtendType type, int64_t shiftAmt) const
void printDataInst (std::ostream &os, bool withImm) const
void printDataInst (std::ostream &os, bool withImm, bool immShift, bool s, IntRegIndex rd, IntRegIndex rn, IntRegIndex rm, IntRegIndex rs, uint32_t shiftAmt, ArmShiftType type, uint32_t imm) const
void advancePC (PCState &pcState) const
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Fault disabledFault () const
Static Protected Member Functions
template<int width>
static bool saturateOp (int32_t &res, int64_t op1, int64_t op2, bool sub=false)
static bool satInt (int32_t &res, int64_t op, int width)
template<int width>
static bool uSaturateOp (uint32_t &res, int64_t op1, int64_t op2, bool sub=false)
static bool uSatInt (int32_t &res, int64_t op, int width)
static uint32_t cpsrWriteByInstr (CPSR cpsr, uint32_t val, SCR scr, NSACR nsacr, uint8_t byteMask, bool affectState, bool nmfi, ThreadContext *tc)
static uint32_t spsrWriteByInstr (uint32_t spsr, uint32_t val, uint8_t byteMask, bool affectState)
template<class XC >
static Addr readPC (XC *xc)
template<class XC >
static void setNextPC (XC *xc, Addr val)
template<class T >
static T cSwap (T val, bool big)
template<class T , class E >
static T cSwap (T val, bool big)
template<class XC >
static void setIWNextPC (XC *xc, Addr val)
template<class XC >
static void setAIWNextPC (XC *xc, Addr val)
Protected Attributes
bool aarch64
uint8_t intWidth
Detailed Description
Definition at line 58 of file static_inst.hh.
Constructor & Destructor Documentation
ArmISA::ArmStaticInst::ArmStaticInst (const char * mnem, ExtMachInst _machInst, OpClass __opClass) [inline, protected]
Definition at line 145 of file static_inst.hh.
References aarch64, bits(), intWidth, and StaticInst::machInst.
Member Function Documentation
void ArmISA::ArmStaticInst::advancePC (PCState & pcState) const [inline, protected]
Reimplemented in ArmISA::MicroOp, ArmISA::MicroOpX, ArmISA::MightBeMicro, ArmISA::MightBeMicro64, ArmISA::PredMicroop, and ArmISA::FpOp.
Definition at line 186 of file static_inst.hh.
virtual void ArmISA::ArmStaticInst::annotateFault (ArmFault * fault) [inline, virtual]
Definition at line 368 of file static_inst.hh.
Referenced by ArmISA::ArmFault::invoke().
static uint32_t ArmISA::ArmStaticInst::cpsrWriteByInstr (CPSR cpsr, uint32_t val, SCR scr, NSACR nsacr, uint8_t byteMask, bool affectState, bool nmfi, ThreadContext * tc) [inline, static, protected]
Definition at line 194 of file static_inst.hh.
References ArmISA::badMode(), bits(), ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), ArmISA::inSecureState(), ArmISA::mask, ArmISA::MODE_FIQ, ArmISA::MODE_HYP, ArmISA::MODE_MON, ArmISA::MODE_USER, and warn_once.
template<class T , class E > static T ArmISA::ArmStaticInst::cSwap (T val, bool big) [inline, static, protected]
Definition at line 318 of file static_inst.hh.
References RefCounted::count, X86ISA::E, BigEndianGuest::gtobe(), BigEndianGuest::gtoh(), BigEndianGuest::gtole(), BigEndianGuest::htog(), and ArmISA::i.
template<class T > static T ArmISA::ArmStaticInst::cSwap (T val, bool big) [inline, static, protected]
Definition at line 307 of file static_inst.hh.
References BigEndianGuest::gtobe(), and BigEndianGuest::gtole().
Fault ArmISA::ArmStaticInst::disabledFault () const [inline, protected]
Definition at line 360 of file static_inst.hh.
References StaticInst::machInst, and StaticInst::mnemonic.
int64_t ArmISA::ArmStaticInst::extendReg64 (uint64_t base, ArmExtendType type, uint64_t shiftAmt, uint8_t width) const [protected]
Definition at line 129 of file static_inst.cc.
References bits(), ArmISA::len, ArmISA::mask, ArmISA::SXTB, ArmISA::SXTH, ArmISA::SXTW, ArmISA::SXTX, ArmISA::UXTB, ArmISA::UXTH, ArmISA::UXTW, and ArmISA::UXTX.
std::string ArmISA::ArmStaticInst::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Implements StaticInst.
Reimplemented in ArmISA::BranchImm64, ArmISA::BranchImmCond64, ArmISA::BranchReg64, ArmISA::BranchRet64, ArmISA::BranchEret64, ArmISA::BranchImmReg64, ArmISA::BranchImmImmReg64, ArmISA::DataXImmOp, ArmISA::DataXImmOnlyOp, ArmISA::DataXSRegOp, ArmISA::DataXERegOp, ArmISA::DataX1RegOp, ArmISA::DataX1RegImmOp, ArmISA::DataX1Reg2ImmOp, ArmISA::DataX2RegOp, ArmISA::DataX2RegImmOp, ArmISA::DataX3RegOp, ArmISA::DataXCondCompImmOp, ArmISA::DataXCondCompRegOp, ArmISA::DataXCondSelOp, ArmISA::MicroSetPCCPSR, ArmISA::MicroIntMov, ArmISA::MicroIntImmOp, ArmISA::MicroIntImmXOp, ArmISA::MicroIntOp, ArmISA::MicroIntRegXOp, ArmISA::MicroMemOp, ArmISA::MicroMemPairOp, ArmISA::Swap, ArmISA::RfeOp, ArmISA::SrsOp, ArmISA::SysDC64, ArmISA::MemoryImm64, ArmISA::MemoryDImm64, ArmISA::MemoryDImmEx64, ArmISA::MemoryPreIndex64, ArmISA::MemoryPostIndex64, ArmISA::MemoryReg64, ArmISA::MemoryRaw64, ArmISA::MemoryEx64, ArmISA::MemoryLiteral64, MrsOp, MsrImmOp, MsrRegOp, MrrcOp, McrrOp, ImmOp, RegImmOp, RegRegOp, RegImmRegOp, RegRegRegImmOp, RegRegRegRegOp, RegRegRegOp, RegRegImmOp, MiscRegRegImmOp, RegMiscRegImmOp, RegImmImmOp, RegRegImmImmOp, RegImmRegShiftOp, UnknownOp, RegRegImmImmOp64, RegRegRegImmOp64, UnknownOp64, ArmISA::PredImmOp, ArmISA::PredIntOp, ArmISA::DataImmOp, ArmISA::DataRegOp, ArmISA::DataRegRegOp, ArmISA::PredMacroOp, DecoderFaultInst, FailUnimplemented, WarnUnimplemented, FlushPipeInst, ArmISA::FpCondCompRegOp, ArmISA::FpCondSelOp, ArmISA::FpRegRegOp, ArmISA::FpRegImmOp, ArmISA::FpRegRegImmOp, ArmISA::FpRegRegRegOp, ArmISA::FpRegRegRegRegOp, and ArmISA::FpRegRegRegImmOp.
Definition at line 591 of file static_inst.cc.
References printMnemonic(), and ArmISA::ss.
void ArmISA::ArmStaticInst::printCondition (std::ostream & os, unsigned code, bool noImplicit = false) const [protected]
Definition at line 383 of file static_inst.cc.
References ArmISA::COND_AL, ArmISA::COND_CC, ArmISA::COND_CS, ArmISA::COND_EQ, ArmISA::COND_GE, ArmISA::COND_GT, ArmISA::COND_HI, ArmISA::COND_LE, ArmISA::COND_LS, ArmISA::COND_LT, ArmISA::COND_MI, ArmISA::COND_NE, ArmISA::COND_PL, ArmISA::COND_UC, ArmISA::COND_VC, ArmISA::COND_VS, and panic.
Referenced by ArmISA::FpCondSelOp::generateDisassembly(), ArmISA::FpCondCompRegOp::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), and printMnemonic().
void ArmISA::ArmStaticInst::printDataInst (std::ostream & os, bool withImm, bool immShift, bool s, IntRegIndex rd, IntRegIndex rn, IntRegIndex rm, IntRegIndex rs, uint32_t shiftAmt, ArmShiftType type, uint32_t imm) const [protected]
Definition at line 559 of file static_inst.cc.
References ccprintf(), ArmISA::INTREG_ZERO, printMnemonic(), printReg(), and printShiftOperand().
void ArmISA::ArmStaticInst::printDataInst (std::ostream & os, bool withImm) const [protected]
Referenced by ArmISA::DataRegRegOp::generateDisassembly(), ArmISA::DataRegOp::generateDisassembly(), ArmISA::DataImmOp::generateDisassembly(), ArmISA::PredImmOp::generateDisassembly(), ArmISA::PredIntOp::generateDisassembly(), ArmISA::DataXERegOp::generateDisassembly(), ArmISA::DataXSRegOp::generateDisassembly(), and ArmISA::DataXImmOp::generateDisassembly().
void ArmISA::ArmStaticInst::printExtendOperand (bool firstOperand, std::ostream & os, IntRegIndex rm, ArmExtendType type, int64_t shiftAmt) const [protected]
Definition at line 527 of file static_inst.cc.
References ccprintf(), printReg(), ArmISA::SXTB, ArmISA::SXTH, ArmISA::SXTW, ArmISA::SXTX, ArmISA::UXTB, ArmISA::UXTH, ArmISA::UXTW, and ArmISA::UXTX.
Referenced by ArmISA::MemoryReg64::generateDisassembly(), and ArmISA::MicroIntRegXOp::generateDisassembly().
void ArmISA::ArmStaticInst::printMemSymbol (std::ostream & os, const SymbolTable * symtab, const std::string & prefix, const Addr addr, const std::string & suffix) const [protected]
Definition at line 446 of file static_inst.cc.
References ccprintf(), and SymbolTable::findNearestSymbol().
void ArmISA::ArmStaticInst::printMnemonic (std::ostream & os, const std::string & suffix = "", bool withPred = true, bool withCond64 = false, ConditionCode cond64 = COND_UC) const [protected]
Definition at line 344 of file static_inst.cc.
References aarch64, StaticInst::machInst, StaticInst::mnemonic, and printCondition().
Referenced by ArmISA::FpRegRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegRegRegOp::generateDisassembly(), ArmISA::FpRegRegRegOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), ArmISA::FpRegRegOp::generateDisassembly(), ArmISA::FpCondSelOp::generateDisassembly(), ArmISA::FpCondCompRegOp::generateDisassembly(), generateDisassembly(), RegRegRegImmOp64::generateDisassembly(), RegRegImmImmOp64::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), RegImmRegOp::generateDisassembly(), RegRegImmImmOp::generateDisassembly(), RegImmImmOp::generateDisassembly(), RegMiscRegImmOp::generateDisassembly(), MiscRegRegImmOp::generateDisassembly(), RegRegImmOp::generateDisassembly(), RegRegRegOp::generateDisassembly(), RegRegRegRegOp::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), RegRegOp::generateDisassembly(), RegImmOp::generateDisassembly(), ImmOp::generateDisassembly(), McrrOp::generateDisassembly(), MrrcOp::generateDisassembly(), MrsOp::generateDisassembly(), ArmISA::MemoryLiteral64::generateDisassembly(), ArmISA::MemoryEx64::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), ArmISA::SysDC64::generateDisassembly(), ArmISA::SrsOp::generateDisassembly(), ArmISA::RfeOp::generateDisassembly(), ArmISA::Swap::generateDisassembly(), ArmISA::MicroMemPairOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::MicroIntOp::generateDisassembly(), ArmISA::MicroIntMov::generateDisassembly(), ArmISA::MicroIntRegXOp::generateDisassembly(), ArmISA::MicroSetPCCPSR::generateDisassembly(), ArmISA::MicroIntImmXOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), ArmISA::DataX3RegOp::generateDisassembly(), ArmISA::DataX2RegImmOp::generateDisassembly(), ArmISA::DataX2RegOp::generateDisassembly(), ArmISA::DataX1Reg2ImmOp::generateDisassembly(), ArmISA::DataX1RegImmOp::generateDisassembly(), ArmISA::DataX1RegOp::generateDisassembly(), ArmISA::DataXImmOnlyOp::generateDisassembly(), ArmISA::BranchImmImmReg64::generateDisassembly(), ArmISA::BranchImmReg64::generateDisassembly(), ArmISA::BranchEret64::generateDisassembly(), ArmISA::BranchRet64::generateDisassembly(), ArmISA::BranchReg64::generateDisassembly(), ArmISA::BranchImm64::generateDisassembly(), ArmISA::BranchImmCond64::generateDisassembly(), printDataInst(), ArmISA::Memory::printInst(), MsrBase::printMsrBase(), and ArmISA::Memory64::startDisassembly().
void ArmISA::ArmStaticInst::printReg (std::ostream & os, int reg) const [protected]
Print a register name for disassembly given the unique dependence tag number (FP or int).
Definition at line 295 of file static_inst.cc.
References aarch64, ccprintf(), CCRegClass, ArmISA::ccRegName, FloatRegClass, ArmISA::FramePointerReg, ArmISA::INTREG_SPX, ArmISA::INTREG_UREG0, ArmISA::INTREG_X31, IntRegClass, intWidth, MiscRegClass, ArmISA::miscRegName, ArmISA::NUM_MISCREGS, ArmISA::PCReg, regIdxToClass(), ArmISA::ReturnAddressReg, and ArmISA::StackPointerReg.
Referenced by ArmISA::FpRegRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegRegRegOp::generateDisassembly(), ArmISA::FpRegRegRegOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), ArmISA::FpRegRegOp::generateDisassembly(), ArmISA::FpCondSelOp::generateDisassembly(), ArmISA::FpCondCompRegOp::generateDisassembly(), RegRegRegImmOp64::generateDisassembly(), RegRegImmImmOp64::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), RegImmRegOp::generateDisassembly(), RegRegImmImmOp::generateDisassembly(), RegImmImmOp::generateDisassembly(), RegMiscRegImmOp::generateDisassembly(), MiscRegRegImmOp::generateDisassembly(), RegRegImmOp::generateDisassembly(), RegRegRegOp::generateDisassembly(), RegRegRegRegOp::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), RegRegOp::generateDisassembly(), RegImmOp::generateDisassembly(), McrrOp::generateDisassembly(), MrrcOp::generateDisassembly(), MsrRegOp::generateDisassembly(), MrsOp::generateDisassembly(), ArmISA::MemoryLiteral64::generateDisassembly(), ArmISA::MemoryEx64::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), ArmISA::SysDC64::generateDisassembly(), ArmISA::SrsOp::generateDisassembly(), ArmISA::RfeOp::generateDisassembly(), ArmISA::Swap::generateDisassembly(), ArmISA::MicroMemPairOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::MicroIntOp::generateDisassembly(), ArmISA::MicroIntMov::generateDisassembly(), ArmISA::MicroIntRegXOp::generateDisassembly(), ArmISA::MicroIntImmXOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), ArmISA::DataX3RegOp::generateDisassembly(), ArmISA::DataX2RegImmOp::generateDisassembly(), ArmISA::DataX2RegOp::generateDisassembly(), ArmISA::DataX1Reg2ImmOp::generateDisassembly(), ArmISA::DataX1RegImmOp::generateDisassembly(), ArmISA::DataX1RegOp::generateDisassembly(), ArmISA::DataXImmOnlyOp::generateDisassembly(), ArmISA::BranchImmImmReg64::generateDisassembly(), ArmISA::BranchImmReg64::generateDisassembly(), ArmISA::BranchRet64::generateDisassembly(), ArmISA::BranchReg64::generateDisassembly(), printDataInst(), ArmISA::MemoryDReg::printDest(), ArmISA::MemoryExDImm::printDest(), ArmISA::MemoryDImm::printDest(), ArmISA::MemoryExImm::printDest(), ArmISA::Memory::printDest(), printExtendOperand(), ArmISA::Memory::printInst(), ArmISA::MemoryReg::printOffset(), printShiftOperand(), and ArmISA::Memory64::startDisassembly().
void ArmISA::ArmStaticInst::printShiftOperand (std::ostream & os, IntRegIndex rm, bool immShift, uint32_t shiftAmt, IntRegIndex rs, ArmShiftType type) const [protected]
Definition at line 463 of file static_inst.cc.
References ArmISA::ASR, ArmISA::INTREG_ZERO, ArmISA::LSL, ArmISA::LSR, panic, printReg(), and ArmISA::ROR.
Referenced by RegImmRegShiftOp::generateDisassembly(), and printDataInst().
void ArmISA::ArmStaticInst::printTarget (std::ostream & os, Addr target, const SymbolTable * symtab) const [protected]
Definition at line 365 of file static_inst.cc.
References ccprintf(), and SymbolTable::findNearestSymbol().
Referenced by ArmISA::BranchImmImmReg64::generateDisassembly(), ArmISA::BranchImmReg64::generateDisassembly(), ArmISA::BranchImm64::generateDisassembly(), and ArmISA::BranchImmCond64::generateDisassembly().
template<class XC > static Addr ArmISA::ArmStaticInst::readPC (XC * xc) [inline, static, protected]
Definition at line 291 of file static_inst.hh.
static bool ArmISA::ArmStaticInst::satInt (int32_t & res, int64_t op, int width) [inline, static, protected]
Definition at line 97 of file static_inst.hh.
References LL.
template<int width> static bool ArmISA::ArmStaticInst::saturateOp (int32_t & res, int64_t op1, int64_t op2, bool sub = false) [inline, static, protected]
Definition at line 81 of file static_inst.hh.
References bits(), LL, and ArmISA::width.
template<class XC > static void ArmISA::ArmStaticInst::setAIWNextPC (XC * xc, Addr val) [inline, static, protected]
Definition at line 352 of file static_inst.hh.
References MipsISA::pc.
template<class XC > static void ArmISA::ArmStaticInst::setIWNextPC (XC * xc, Addr val) [inline, static, protected]
Definition at line 341 of file static_inst.hh.
References MipsISA::pc.
template<class XC > static void ArmISA::ArmStaticInst::setNextPC (XC * xc, Addr val) [inline, static, protected]
Definition at line 298 of file static_inst.hh.
References MipsISA::pc.
bool ArmISA::ArmStaticInst::shift_carry_imm (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const [protected]
Definition at line 215 of file static_inst.cc.
References ArmISA::ASR, ccprintf(), X86ISA::exit, ArmISA::LSL, ArmISA::LSR, and ArmISA::ROR.
bool ArmISA::ArmStaticInst::shift_carry_rs (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const [protected]
Definition at line 255 of file static_inst.cc.
References ArmISA::ASR, ccprintf(), X86ISA::exit, ArmISA::LSL, ArmISA::LSR, and ArmISA::ROR.
int32_t ArmISA::ArmStaticInst::shift_rm_imm (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const [protected]
Definition at line 55 of file static_inst.cc.
References ArmISA::ASR, ccprintf(), X86ISA::exit, ArmISA::LSL, ArmISA::LSR, and ArmISA::ROR.
int32_t ArmISA::ArmStaticInst::shift_rm_rs (uint32_t base, uint32_t shamt, uint32_t type, uint32_t cfval) const [protected]
Definition at line 175 of file static_inst.cc.
References ArmISA::ASR, ccprintf(), X86ISA::exit, ArmISA::LSL, ArmISA::LSR, and ArmISA::ROR.
int64_t ArmISA::ArmStaticInst::shiftReg64 (uint64_t base, uint64_t shiftAmt, ArmShiftType type, uint8_t width) const [protected]
Definition at line 90 of file static_inst.cc.
References ArmISA::ASR, bits(), ccprintf(), X86ISA::exit, intWidth, ArmISA::LSL, ArmISA::LSR, ArmISA::mask, and ArmISA::ROR.
static uint32_t ArmISA::ArmStaticInst::spsrWriteByInstr (uint32_t spsr, uint32_t val, uint8_t byteMask, bool affectState) [inline, static, protected]
Definition at line 272 of file static_inst.hh.
References bits(), and ArmISA::mask.
static bool ArmISA::ArmStaticInst::uSatInt (int32_t & res, int64_t op, int width) [inline, static, protected]
Definition at line 130 of file static_inst.hh.
References LL.
template<int width> static bool ArmISA::ArmStaticInst::uSaturateOp (uint32_t & res, int64_t op1, int64_t op2, bool sub = false) [inline, static, protected]
Definition at line 114 of file static_inst.hh.
References LL, and ArmISA::width.
Member Data Documentation
bool ArmISA::ArmStaticInst::aarch64 [protected]
Definition at line 61 of file static_inst.hh.
Referenced by ArmStaticInst(), printMnemonic(), and printReg().
uint8_t ArmISA::ArmStaticInst::intWidth [protected]
Definition at line 62 of file static_inst.hh.
Referenced by ArmStaticInst(), printReg(), and shiftReg64().
The documentation for this class was generated from the following files:
arch/arm/insts/static_inst.hh
arch/arm/insts/static_inst.cc