gem5: RegRegRegImmOp Class Reference
RegRegRegImmOp Class Reference
#include <misc.hh>
Protected Member Functions
RegRegRegImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, IntRegIndex _op2, uint64_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
IntRegIndex op1
IntRegIndex op2
uint64_t imm
Detailed Description
Definition at line 190 of file misc.hh.
Constructor & Destructor Documentation
RegRegRegImmOp::RegRegRegImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, IntRegIndex _op1, IntRegIndex _op2, uint64_t _imm) [inline, protected]
Definition at line 198 of file misc.hh.
Member Function Documentation
std::string RegRegRegImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 205 of file misc.cc.
References ccprintf(), dest, imm, op1, op2, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex RegRegRegImmOp::dest [protected]
Definition at line 193 of file misc.hh.
Referenced by generateDisassembly().
uint64_t RegRegRegImmOp::imm [protected]
Definition at line 196 of file misc.hh.
Referenced by generateDisassembly().
IntRegIndex RegRegRegImmOp::op1 [protected]
Definition at line 194 of file misc.hh.
Referenced by generateDisassembly().
IntRegIndex RegRegRegImmOp::op2 [protected]
Definition at line 195 of file misc.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/misc.hh
arch/arm/insts/misc.cc