gem5: CommMonitor::MonitorMasterPort Class Reference
CommMonitor::MonitorMasterPort Class Reference
This is the master port of the communication monitor.
Public Member Functions
MonitorMasterPort (const std::string &_name, CommMonitor &_mon)
Protected Member Functions
void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from the slave port.
bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the slave port.
void recvRangeChange ()
Called to receive an address range change from the peer slave port.
bool isSnooping () const
Determine if this master port is snooping or not.
void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Private Attributes
CommMonitor & mon
Detailed Description
This is the master port of the communication monitor.
All recv functions call a function in CommMonitor, where the send function of the slave port is called. Besides this, these functions can also perform actions for capturing statistics.
Definition at line 135 of file comm_monitor.hh.
Constructor & Destructor Documentation
CommMonitor::MonitorMasterPort::MonitorMasterPort (const std::string & _name, CommMonitor & _mon) [inline]
Definition at line 140 of file comm_monitor.hh.
Member Function Documentation
bool CommMonitor::MonitorMasterPort::isSnooping () const [inline, protected, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented from MasterPort.
Definition at line 171 of file comm_monitor.hh.
References CommMonitor::isSnooping(), and mon.
Tick CommMonitor::MonitorMasterPort::recvAtomicSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 151 of file comm_monitor.hh.
References mon, and CommMonitor::recvAtomicSnoop().
void CommMonitor::MonitorMasterPort::recvFunctionalSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 146 of file comm_monitor.hh.
References mon, and CommMonitor::recvFunctionalSnoop().
void CommMonitor::MonitorMasterPort::recvRangeChange () [inline, protected, virtual]
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 166 of file comm_monitor.hh.
References mon, and CommMonitor::recvRangeChange().
void CommMonitor::MonitorMasterPort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 176 of file comm_monitor.hh.
References mon, and CommMonitor::recvReqRetry().
bool CommMonitor::MonitorMasterPort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 156 of file comm_monitor.hh.
References mon, and CommMonitor::recvTimingResp().
void CommMonitor::MonitorMasterPort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop request from the slave port.
Reimplemented from MasterPort.
Definition at line 161 of file comm_monitor.hh.
References mon, and CommMonitor::recvTimingSnoopReq().
Member Data Documentation
CommMonitor& CommMonitor::MonitorMasterPort::mon [private]
Definition at line 183 of file comm_monitor.hh.
Referenced by isSnooping(), recvAtomicSnoop(), recvFunctionalSnoop(), recvRangeChange(), recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
The documentation for this class was generated from the following file:
mem/comm_monitor.hh