gem5: ArmLinuxProcess32 Class Reference
ArmLinuxProcess32 Class Reference
A process with emulated Arm/Linux syscalls.
#include <process.hh>
Public Member Functions
ArmLinuxProcess32 (LiveProcessParams *params, ObjectFile *objFile, ObjectFile::Arch _arch)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
SyscallDesc * getDesc (int callnum)
Static Public Attributes
static const Addr commPage = 0xffff0000
A page to hold "kernel" provided functions. The name might be wrong.
Detailed Description
A process with emulated Arm/Linux syscalls.
Definition at line 68 of file process.hh.
Constructor & Destructor Documentation
ArmLinuxProcess32::ArmLinuxProcess32 (LiveProcessParams * params, ObjectFile * objFile, ObjectFile::Arch _arch)
Definition at line 1590 of file process.cc.
References ArmLinuxProcessBits::SyscallTable::base, ArmLinuxProcessBits::SyscallTable::descs, ArmLinuxProcessBits::SyscallTable::size, and ArmLinuxProcessBits::syscallTables.
Member Function Documentation
SyscallDesc * ArmLinuxProcess32::getDesc (int callnum) [virtual]
Implements LiveProcess.
Definition at line 1654 of file process.cc.
References ArmLinuxProcessBits::getLinuxDesc().
void ArmLinuxProcess32::initState () [virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from ArmLiveProcess32.
Definition at line 1666 of file process.cc.
References X86ISA::addr, Process::allocateMem(), commPage, Process::contextIds, ThreadContext::getMemProxy(), System::getThreadContext(), AlphaISA::PageBytes, Process::system, ArmISA::tc, and SETranslatingPortProxy::writeBlob().
Member Data Documentation
const Addr ArmLinuxProcess32::commPage = 0xffff0000 [static]
A page to hold "kernel" provided functions. The name might be wrong.
Definition at line 80 of file process.hh.
Referenced by initState(), and setTLSFunc32().
The documentation for this class was generated from the following files:
arch/arm/linux/process.hh
arch/arm/linux/process.cc