gem5: DrainManager Class Reference
DrainManager Class Reference
This class coordinates draining of a System.
#include <drain.hh>
Public Member Functions
DrainManager ()
virtual ~DrainManager ()
unsigned int getCount () const
Get the number of objects registered with this DrainManager that are currently draining their state.
void setCount (int count)
void signalDrainDone ()
Notify the DrainManager that a Drainable object has finished draining.
Protected Member Functions
virtual void drainCycleDone ()
Callback when all registered Drainable objects have completed a drain cycle.
Protected Attributes
unsigned int _count
Number of objects still draining.
Detailed Description
This class coordinates draining of a System.
When draining a System, we need to make sure that all SimObjects in that system have drained their state before declaring the operation to be successful. This class keeps track of how many objects are still in the process of draining their state. Once it determines that all objects have drained their state, it exits the simulation loop.
Note:
A System might not be completely drained even though the DrainManager has caused the simulation loop to exit. Draining needs to be restarted until all Drainable objects declare that they don't need further simulation to be completely drained. See Drainable for more information.
Definition at line 66 of file drain.hh.
Constructor & Destructor Documentation
DrainManager::DrainManager ()
Definition at line 43 of file drain.cc.
DrainManager::~DrainManager () [virtual]
Definition at line 48 of file drain.cc.
Member Function Documentation
void DrainManager::drainCycleDone () [protected, virtual]
Callback when all registered Drainable objects have completed a drain cycle.
Definition at line 53 of file drain.cc.
References exitSimLoop().
Referenced by signalDrainDone().
unsigned int DrainManager::getCount () const [inline]
Get the number of objects registered with this DrainManager that are currently draining their state.
Returns:
Number of objects currently draining.
Definition at line 78 of file drain.hh.
References _count.
void DrainManager::setCount (int count) [inline]
Definition at line 80 of file drain.hh.
References _count.
void DrainManager::signalDrainDone () [inline]
Notify the DrainManager that a Drainable object has finished draining.
Definition at line 86 of file drain.hh.
References _count, and drainCycleDone().
Referenced by IGbE::checkDrain(), UFSHostDevice::checkDrain(), FlashDevice::checkDrain(), ArmISA::TableWalker::completeDrain(), MSHRQueue::deallocateOne(), SimpleMemory::dequeue(), DmaPort::handleResp(), CopyEngine::CopyEngineChannel::inDrain(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::processRespondEvent(), TrafficGen::recvReqRetry(), BaseXBar::Layer< SrcType, DstType >::releaseLayer(), PacketQueue::schedSendEvent(), DRAMSim2::sendResponse(), MinorCPU::signalDrainDone(), RubyPort::testDrainComplete(), DMASequencer::testDrainComplete(), TimingSimpleCPU::tryCompleteDrain(), AtomicSimpleCPU::tryCompleteDrain(), FullO3CPU< Impl >::tryDrain(), BaseKvmCPU::tryDrain(), and DRAMSim2::writeComplete().
Member Data Documentation
unsigned int DrainManager::_count [protected]
Number of objects still draining.
Definition at line 100 of file drain.hh.
Referenced by getCount(), setCount(), and signalDrainDone().
The documentation for this class was generated from the following files:
sim/drain.hh
sim/drain.cc