gem5: Cache::CpuSidePort Class Reference
Cache::CpuSidePort Class Reference
The CPU-side port extends the base cache slave port with access functions for functional, atomic and timing requests.
#include <cache.hh>
Public Member Functions
CpuSidePort (const std::string &_name, Cache *_cache, const std::string &_label)
Protected Member Functions
virtual bool recvTimingSnoopResp (PacketPtr pkt)
virtual bool recvTimingReq (PacketPtr pkt)
virtual Tick recvAtomic (PacketPtr pkt)
virtual void recvFunctional (PacketPtr pkt)
virtual AddrRangeList getAddrRanges () const
Private Attributes
Cache * cache
Detailed Description
The CPU-side port extends the base cache slave port with access functions for functional, atomic and timing requests.
Definition at line 89 of file cache.hh.
Constructor & Destructor Documentation
Cache::CpuSidePort::CpuSidePort (const std::string & _name, Cache * _cache, const std::string & _label)
Definition at line 2166 of file cache_impl.hh.
Member Function Documentation
AddrRangeList Cache::CpuSidePort::getAddrRanges () const [protected, virtual]
Definition at line 2118 of file cache_impl.hh.
References cache, and BaseCache::getAddrRanges().
Tick Cache::CpuSidePort::recvAtomic (PacketPtr pkt) [protected, virtual]
Definition at line 2153 of file cache_impl.hh.
References cache, and Cache::recvAtomic().
void Cache::CpuSidePort::recvFunctional (PacketPtr pkt) [protected, virtual]
Definition at line 2159 of file cache_impl.hh.
References cache, and Cache::functionalAccess().
bool Cache::CpuSidePort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Definition at line 2124 of file cache_impl.hh.
References BaseCache::blocked, System::bypassCaches(), cache, ArmISA::M5_VAR_USED, Packet::memInhibitAsserted(), Cache::recvTimingReq(), and BaseCache::system.
bool Cache::CpuSidePort::recvTimingSnoopResp (PacketPtr pkt) [protected, virtual]
Definition at line 1862 of file cache_impl.hh.
References cache, and Cache::recvTimingSnoopResp().
Member Data Documentation
Cache* Cache::CpuSidePort::cache [private]
Definition at line 94 of file cache.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvTimingReq(), and recvTimingSnoopResp().
The documentation for this class was generated from the following files:
mem/cache/cache.hh
mem/cache/cache_impl.hh