gem5: Stats::DataWrapVec< Derived, InfoProxyType > Class Template Reference
Stats::DataWrapVec< Derived, InfoProxyType > Class Template Reference
#include <statistics.hh>
Public Types
typedef InfoProxyType< Derived > Info
Public Member Functions
DataWrapVec ()
DataWrapVec (const DataWrapVec &ref)
void operator= (const DataWrapVec &)
Can't copy stats.
Derived & subname (off_type index, const std::string &name)
Set the subfield name for the given index, and marks this stat to print at the end of simulation.
Derived & subdesc (off_type index, const std::string &desc)
Set the subfield description for the given index and marks this stat to print at the end of simulation.
void prepare ()
void reset ()
Reset the stat to the default state.
Detailed Description
template<class Derived, template< class > class InfoProxyType>
class Stats::DataWrapVec< Derived, InfoProxyType >
Definition at line 329 of file statistics.hh.
Member Typedef Documentation
template<class Derived, template< class > class InfoProxyType> typedef InfoProxyType<Derived> Stats::DataWrapVec< Derived, InfoProxyType >::Info
Reimplemented from Stats::DataWrap< Derived, InfoProxyType >.
Reimplemented in Stats::DataWrapVec2d< Derived, InfoProxyType >, Stats::Vector2dBase< Derived, Stor >, Stats::VectorDistBase< Derived, Stor >, Stats::DataWrapVec2d< Vector2d, Vector2dInfoProxy >, Stats::DataWrapVec2d< Derived, Vector2dInfoProxy >, Stats::Vector2dBase< Vector2d, StatStor >, Stats::VectorDistBase< VectorStandardDeviation, SampleStor >, Stats::VectorDistBase< VectorDistribution, DistStor >, and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >.
Definition at line 332 of file statistics.hh.
Constructor & Destructor Documentation
template<class Derived, template< class > class InfoProxyType> Stats::DataWrapVec< Derived, InfoProxyType >::DataWrapVec () [inline]
Definition at line 334 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Stats::DataWrapVec< Derived, InfoProxyType >::DataWrapVec (const DataWrapVec< Derived, InfoProxyType > & ref) [inline]
Definition at line 337 of file statistics.hh.
Member Function Documentation
template<class Derived, template< class > class InfoProxyType> void Stats::DataWrapVec< Derived, InfoProxyType >::operator= (const DataWrapVec< Derived, InfoProxyType > &) [inline]
Can't copy stats.
Reimplemented from Stats::DataWrap< Derived, InfoProxyType >.
Definition at line 340 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> void Stats::DataWrapVec< Derived, InfoProxyType >::prepare () [inline]
Reimplemented in Stats::Vector2dBase< Derived, Stor >, Stats::VectorDistBase< Derived, Stor >, Stats::Formula, Stats::Vector2dBase< Vector2d, StatStor >, Stats::VectorDistBase< VectorStandardDeviation, SampleStor >, Stats::VectorDistBase< VectorDistribution, DistStor >, and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >.
Definition at line 391 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> void Stats::DataWrapVec< Derived, InfoProxyType >::reset () [inline]
Reset the stat to the default state.
Reimplemented from Stats::InfoAccess.
Reimplemented in Stats::Vector2dBase< Derived, Stor >, Stats::Formula, and Stats::Vector2dBase< Vector2d, StatStor >.
Definition at line 402 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrapVec< Derived, InfoProxyType >::subdesc (off_type index, const std::string & desc) [inline]
Set the subfield description for the given index and marks this stat to print at the end of simulation.
Parameters:
index The subfield index.
desc The new description of the subfield
Returns:
A reference to this stat.
Definition at line 378 of file statistics.hh.
Referenced by FALRU::regStats().
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrapVec< Derived, InfoProxyType >::subname (off_type index, const std::string & name) [inline]
Set the subfield name for the given index, and marks this stat to print at the end of simulation.
Parameters:
index The subfield index.
name The new name of the subfield.
Returns:
A reference to this stat.
Definition at line 354 of file statistics.hh.
Referenced by StatTest::init(), BaseXBar::regStats(), CacheMemory::regStats(), MemCntrlProfiler::regStats(), GarnetNetwork::regStats(), BaseGarnetNetwork::regStats(), DRAMCtrl::Rank::regStats(), FALRU::regStats(), AbstractMemory::regStats(), InstructionQueue< Impl >::regStats(), BaseTags::regStats(), BaseCache::regStats(), BaseSimpleCPU::regStats(), and ArmISA::TableWalker::regStats().
The documentation for this class was generated from the following file:
base/statistics.hh