gem5: ArmISA::FpCondCompRegOp Class Reference
ArmISA::FpCondCompRegOp Class Reference
#include <vfp.hh>
Protected Member Functions
FpCondCompRegOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _op1, IntRegIndex _op2, ConditionCode _condCode, uint8_t _defCc)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex op1
IntRegIndex op2
ConditionCode condCode
uint8_t defCc
Detailed Description
Definition at line 879 of file vfp.hh.
Constructor & Destructor Documentation
ArmISA::FpCondCompRegOp::FpCondCompRegOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _op1, IntRegIndex _op2, ConditionCode _condCode, uint8_t _defCc) [inline, protected]
Definition at line 886 of file vfp.hh.
Member Function Documentation
std::string FpCondCompRegOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 49 of file vfp.cc.
References ccprintf(), condCode, defCc, op1, op2, ArmISA::ArmStaticInst::printCondition(), ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
ConditionCode ArmISA::FpCondCompRegOp::condCode [protected]
Reimplemented from ArmISA::PredOp.
Definition at line 883 of file vfp.hh.
Referenced by generateDisassembly().
uint8_t ArmISA::FpCondCompRegOp::defCc [protected]
Definition at line 884 of file vfp.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::FpCondCompRegOp::op1 [protected]
Definition at line 882 of file vfp.hh.
Referenced by generateDisassembly().
IntRegIndex ArmISA::FpCondCompRegOp::op2 [protected]
Definition at line 882 of file vfp.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/vfp.hh
arch/arm/insts/vfp.cc