gem5: CacheSet< Blktype > Class Template Reference
CacheSet< Blktype > Class Template Reference
An associative set of cache blocks.
#include <cacheset.hh>
Public Member Functions
Blktype * findBlk (Addr tag, bool is_secure, int &way_id) const
Find a block matching the tag in this set.
Blktype * findBlk (Addr tag, bool is_secure) const
void moveToHead (Blktype *blk)
Move the given block to the head of the list.
void moveToTail (Blktype *blk)
Move the given block to the tail of the list.
void moveTo (Blktype *blk, unsigned int lrustate)
unsigned int getLRUState (Blktype *blk)
Public Attributes
int assoc
The associativity of this set.
Blktype ** blks
Cache blocks in this set, maintained in LRU order 0 = MRU.
Detailed Description
template<class Blktype>
class CacheSet< Blktype >
An associative set of cache blocks.
Definition at line 59 of file cacheset.hh.
Member Function Documentation
template<class Blktype > Blktype * CacheSet< Blktype >::findBlk (Addr tag, bool is_secure) const [inline]
Definition at line 116 of file cacheset.hh.
References CacheSet< Blktype >::findBlk().
template<class Blktype > Blktype * CacheSet< Blktype >::findBlk (Addr tag, bool is_secure, int & way_id) const [inline]
Find a block matching the tag in this set.
Parameters:
way_id The id of the way that matches the tag.
tag The Tag to find.
is_secure True if the target memory space is secure.
Returns:
Pointer to the block if found. Set way_id to assoc if none found
Way_id returns the id of the way that matches the block If no block is found way_id is set to assoc.
Definition at line 97 of file cacheset.hh.
References CacheSet< Blktype >::assoc, CacheSet< Blktype >::blks, and ArmISA::i.
Referenced by BaseSetAssoc::accessBlock(), CacheSet< Blktype >::findBlk(), and BaseSetAssoc::findBlock().
template<class Blktype > unsigned int CacheSet< Blktype >::getLRUState (Blktype * blk) [inline]
Definition at line 199 of file cacheset.hh.
References CacheSet< Blktype >::assoc, CacheSet< Blktype >::blks, and fatal.
Referenced by FLIP::accessBlock(), and CacheSet< Blktype >::moveTo().
template<class Blktype > void CacheSet< Blktype >::moveTo (Blktype * blk, unsigned int lrustate) [inline]
Definition at line 174 of file cacheset.hh.
References CacheSet< Blktype >::blks, CacheSet< Blktype >::getLRUState(), ArmISA::i, and CacheSet< Blktype >::moveToHead().
Referenced by FLIP::accessBlock(), and FLIP::insertBlock().
template<class Blktype > void CacheSet< Blktype >::moveToHead (Blktype * blk) [inline]
Move the given block to the head of the list.
Parameters:
blk The block to move.
Definition at line 124 of file cacheset.hh.
References CacheSet< Blktype >::assoc, CacheSet< Blktype >::blks, and ArmISA::i.
Referenced by LRU::accessBlock(), FLIP::accessBlock(), DIP::accessBlock(), LRU::insertBlock(), BIP::insertBlock(), DIP::insertBlock_bip(), DIP::insertBlock_lru(), and CacheSet< Blktype >::moveTo().
template<class Blktype > void CacheSet< Blktype >::moveToTail (Blktype * blk) [inline]
Move the given block to the tail of the list.
Parameters:
blk The block to move
Definition at line 149 of file cacheset.hh.
References CacheSet< Blktype >::assoc, CacheSet< Blktype >::blks, and ArmISA::i.
Referenced by LRU::invalidate(), and FLIP::invalidate().
Member Data Documentation
template<class Blktype > int CacheSet< Blktype >::assoc
The associativity of this set.
Definition at line 63 of file cacheset.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), CacheSet< Blktype >::findBlk(), CacheSet< Blktype >::getLRUState(), CacheSet< Blktype >::moveToHead(), and CacheSet< Blktype >::moveToTail().
template<class Blktype > Blktype** CacheSet< Blktype >::blks
Cache blocks in this set, maintained in LRU order 0 = MRU.
Definition at line 66 of file cacheset.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), CacheSet< Blktype >::findBlk(), RandomRepl::findVictim(), LRU::findVictim(), FLIP::findVictim(), BaseSetAssoc::findVictim(), CacheSet< Blktype >::getLRUState(), CacheSet< Blktype >::moveTo(), CacheSet< Blktype >::moveToHead(), CacheSet< Blktype >::moveToTail(), and BaseSetAssoc::print().
The documentation for this class was generated from the following file:
mem/cache/tags/cacheset.hh