gem5: RubyPort::MemSlavePort Class Reference
RubyPort::MemSlavePort Class Reference
#include <RubyPort.hh>
Public Member Functions
MemSlavePort (const std::string &_name, RubyPort *_port, RubySystem *_system, bool _access_backing_store, PortID id)
void hitCallback (PacketPtr pkt)
void evictionCallback (const Address &address)
Protected Member Functions
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Private Member Functions
bool isPhysMemAddress (Addr addr) const
Private Attributes
RespPacketQueue queue
RubySystem * ruby_system
bool access_backing_store
Detailed Description
Definition at line 74 of file RubyPort.hh.
Constructor & Destructor Documentation
RubyPort::MemSlavePort::MemSlavePort (const std::string & _name, RubyPort * _port, RubySystem * _system, bool _access_backing_store, PortID id)
Definition at line 160 of file RubyPort.cc.
References DPRINTF.
Member Function Documentation
void RubyPort::MemSlavePort::evictionCallback (const Address & address)
AddrRangeList RubyPort::MemSlavePort::getAddrRanges () const [inline, protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 95 of file RubyPort.hh.
void RubyPort::MemSlavePort::hitCallback (PacketPtr pkt)
Definition at line 462 of file RubyPort.cc.
References AbstractMemory::access(), access_backing_store, ClockedObject::clockPeriod(), Packet::convertLlToRead(), Packet::convertScToWrite(), curTick(), DPRINTF, g_system_ptr, Request::getExtraData(), RubySystem::getPhysMem(), Packet::isFlush(), Packet::isLLSC(), Packet::isWrite(), Packet::makeResponse(), Packet::needsResponse(), Packet::req, ruby_system, and QueuedSlavePort::schedTimingResp().
bool RubyPort::MemSlavePort::isPhysMemAddress (Addr addr) const [private]
Definition at line 535 of file RubyPort.cc.
References System::isMemAddr(), Port::owner, and RubyPort::system.
Referenced by recvFunctional(), and recvTimingReq().
Tick RubyPort::MemSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 90 of file RubyPort.hh.
References panic.
void RubyPort::MemSlavePort::recvFunctional (PacketPtr pkt) [protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 286 of file RubyPort.cc.
References access_backing_store, Packet::cmdString(), DPRINTF, fatal, AbstractMemory::functionalAccess(), RubySystem::functionalRead(), RubySystem::functionalWrite(), Packet::getAddr(), Address::getAddress(), RubySystem::getBlockSizeBytes(), RubySystem::getPhysMem(), Packet::getSize(), isPhysMemAddress(), Packet::isRead(), Packet::isWrite(), line_address(), ArmISA::M5_VAR_USED, Packet::needsResponse(), Port::owner, panic, ruby_system, Packet::setFunctionalResponseStatus(), and Packet::suppressFuncError().
bool RubyPort::MemSlavePort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 226 of file RubyPort.cc.
References ClockedObject::clockPeriod(), Packet::cmdString(), curTick(), DPRINTF, g_system_ptr, Packet::getAddr(), RubySystem::getBlockSizeBytes(), Packet::getSize(), Port::id, isPhysMemAddress(), Packet::memInhibitAsserted(), Port::owner, panic, and Packet::pushSenderState().
Member Data Documentation
bool RubyPort::MemSlavePort::access_backing_store [private]
Definition at line 79 of file RubyPort.hh.
Referenced by hitCallback(), and recvFunctional().
RespPacketQueue RubyPort::MemSlavePort::queue [private]
Definition at line 77 of file RubyPort.hh.
RubySystem* RubyPort::MemSlavePort::ruby_system [private]
Definition at line 78 of file RubyPort.hh.
Referenced by hitCallback(), and recvFunctional().
The documentation for this class was generated from the following files:
mem/ruby/system/RubyPort.hh
mem/ruby/system/RubyPort.cc