gem5: X86KvmCPU Class Reference
X86KvmCPU Class Reference
x86 implementation of a KVM-based hardware virtualized CPU.
#include <x86_cpu.hh>
Public Member Functions
X86KvmCPU (X86KvmCPUParams *params)
virtual ~X86KvmCPU ()
void startup ()
Protected Types
typedef std::vector< struct
kvm_msr_entry > KvmMSRVector
Protected Member Functions
Tick kvmRun (Tick ticks)
Request KVM to run the guest for a given number of ticks.
Tick kvmRunDrain ()
Run the virtual CPU until draining completes.
Tick kvmRunWrapper (Tick ticks)
Wrapper that synchronizes state in kvm_run.
uint64_t getHostCycles () const
Get the value of the hardware cycle counter in the guest.
const Kvm::MSRIndexVector & getMsrIntersection () const
Get a list of MSRs supported by both gem5 and KVM.
void updateKvmState ()
Update the KVM state from the current thread context.
void updateThreadContext ()
Update the current thread context with the KVM state.
void deliverInterrupts ()
Inject pending interrupts from gem5 into the virtual CPU.
Tick handleKvmExitIO ()
Handle x86 legacy IO (in/out).
Tick handleKvmExitIRQWindowOpen ()
The guest exited because an interrupt window was requested.
bool archIsDrained () const
Check if there are pending events in the vCPU that prevents it from being drained.
Private Member Functions
void updateCPUID ()
Transfer gem5's CPUID values into the virtual CPU.
void handleIOMiscReg32 (int miscreg)
Handle a 32-bit IO access that should be mapped to a MiscReg.
Private Attributes
Kvm::MSRIndexVector cachedMsrIntersection
Cached intersection of supported MSRs.
bool haveDebugRegs
Kvm::capDebugRegs() available?
bool haveXSave
Kvm::capXSave() available?
bool useXSave
Should the XSave interface be used to sync the FPU and SIMD registers?
bool haveXCRs
Kvm::capXCRs() available?
void dump ()
void dumpFpuRegs () const
void dumpIntRegs () const
void dumpSpecRegs () const
void dumpDebugRegs () const
void dumpXCRs () const
void dumpXSave () const
void dumpVCpuEvents () const
void dumpMSRs () const
void setCPUID (const struct kvm_cpuid2 &cpuid)
Methods to access CPUID information using the extended API.
void setCPUID (const Kvm::CPUIDVector &cpuid)
void setMSRs (const struct kvm_msrs &msrs)
Methods to access MSRs in the guest.
void setMSRs (const KvmMSRVector &msrs)
void getMSRs (struct kvm_msrs &msrs) const
void setMSR (uint32_t index, uint64_t value)
uint64_t getMSR (uint32_t index) const
void getDebugRegisters (struct kvm_debugregs &regs) const
Wrappers around KVM's state transfer methods.
void setDebugRegisters (const struct kvm_debugregs &regs)
void getXCRs (struct kvm_xcrs &regs) const
void setXCRs (const struct kvm_xcrs &regs)
void getXSave (struct kvm_xsave &xsave) const
void setXSave (const struct kvm_xsave &xsave)
void getVCpuEvents (struct kvm_vcpu_events &events) const
void setVCpuEvents (const struct kvm_vcpu_events &events)
void updateKvmStateRegs ()
Support routines to update the state of the KVM CPU from gem5's state representation.
void updateKvmStateSRegs ()
Update control registers (CRx, segments, etc.
void updateKvmStateFPU ()
Update FPU and SIMD registers.
void updateKvmStateFPULegacy ()
Update FPU and SIMD registers using the legacy API.
void updateKvmStateFPUXSave ()
Update FPU and SIMD registers using the XSave API.
void updateKvmStateMSRs ()
Update MSR registers.
void updateThreadContextRegs (const struct kvm_regs &regs, const struct kvm_sregs &sregs)
Support routines to update the state of gem5's thread context from KVM's state representation.
void updateThreadContextSRegs (const struct kvm_sregs &sregs)
Update control registers (CRx, segments, etc.
void updateThreadContextFPU (const struct kvm_fpu &fpu)
Update FPU and SIMD registers using the legacy API.
void updateThreadContextXSave (const struct kvm_xsave &kxsave)
Update FPU and SIMD registers using the XSave API.
void updateThreadContextMSRs ()
Update MSR registers.
Detailed Description
x86 implementation of a KVM-based hardware virtualized CPU.
Definition at line 41 of file x86_cpu.hh.
Member Typedef Documentation
typedef std::vector<struct kvm_msr_entry> X86KvmCPU::KvmMSRVector [protected]
Definition at line 62 of file x86_cpu.hh.
Constructor & Destructor Documentation
X86KvmCPU::X86KvmCPU (X86KvmCPUParams * params)
Definition at line 518 of file x86_cpu.cc.
References Kvm::capDebugRegs(), Kvm::capExtendedCPUID(), Kvm::capSetTSSAddress(), Kvm::capUserNMI(), Kvm::capVCPUEvents(), Kvm::capXCRs(), Kvm::capXSave(), haveDebugRegs, haveXCRs, haveXSave, KvmVM::kvm, panic, useXSave, BaseKvmCPU::vm, and warn.
X86KvmCPU::~X86KvmCPU () [virtual]
Definition at line 546 of file x86_cpu.cc.
Member Function Documentation
bool X86KvmCPU::archIsDrained () const [protected, virtual]
Check if there are pending events in the vCPU that prevents it from being drained.
There are cases after interrupt injection where the interrupt is still pending in the guest. This method detects such cases and requests additional draining.
Returns:
False if there are pending events in the guest, True otherwise.
Reimplemented from BaseKvmCPU.
Definition at line 1378 of file x86_cpu.cc.
References DPRINTF, and getVCpuEvents().
Referenced by kvmRunDrain().
void X86KvmCPU::deliverInterrupts () [protected]
Inject pending interrupts from gem5 into the virtual CPU.
Definition at line 1133 of file x86_cpu.cc.
References DPRINTF, X86ISA::X86FaultBase::getVector(), BaseKvmCPU::kvmInterrupt(), BaseKvmCPU::kvmNonMaskableInterrupt(), panic, SimpleThread::suspend(), BaseKvmCPU::syncThreadContext(), BaseKvmCPU::tc, BaseKvmCPU::thread, BaseKvmCPU::threadContextDirty, and updateKvmState().
Referenced by kvmRun().
void X86KvmCPU::dump () [virtual]
Reimplemented from BaseKvmCPU.
Definition at line 565 of file x86_cpu.cc.
References dumpDebugRegs(), dumpFpuRegs(), dumpIntRegs(), dumpMSRs(), dumpSpecRegs(), dumpVCpuEvents(), dumpXCRs(), dumpXSave(), and useXSave.
Referenced by updateKvmState(), and updateThreadContext().
void X86KvmCPU::dumpDebugRegs () const
Definition at line 604 of file x86_cpu.cc.
References dumpKvm(), getDebugRegisters(), haveDebugRegs, and inform.
Referenced by dump().
void X86KvmCPU::dumpFpuRegs () const
Definition at line 580 of file x86_cpu.cc.
References dumpKvm(), and BaseKvmCPU::getFPUState().
Referenced by dump().
void X86KvmCPU::dumpIntRegs () const
Definition at line 588 of file x86_cpu.cc.
References dumpKvm(), and BaseKvmCPU::getRegisters().
Referenced by dump().
void X86KvmCPU::dumpMSRs () const
Definition at line 650 of file x86_cpu.cc.
References dumpKvm(), ArmISA::e, getMSRs(), ArmISA::i, KvmVM::kvm, and BaseKvmCPU::vm.
Referenced by dump().
void X86KvmCPU::dumpSpecRegs () const
Definition at line 596 of file x86_cpu.cc.
References dumpKvm(), and BaseKvmCPU::getSpecialRegisters().
Referenced by dump().
void X86KvmCPU::dumpVCpuEvents () const
Definition at line 642 of file x86_cpu.cc.
References dumpKvm(), and getVCpuEvents().
Referenced by dump().
void X86KvmCPU::dumpXCRs () const
Definition at line 618 of file x86_cpu.cc.
References dumpKvm(), getXCRs(), haveXCRs, and inform.
Referenced by dump().
void X86KvmCPU::dumpXSave () const
Definition at line 630 of file x86_cpu.cc.
References dumpKvm(), getXSave(), haveXSave, and inform.
Referenced by dump().
void X86KvmCPU::getDebugRegisters (struct kvm_debugregs & regs) const [protected]
Wrappers around KVM's state transfer methods.
Definition at line 1560 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by dumpDebugRegs().
uint64_t X86KvmCPU::getHostCycles () const [protected, virtual]
Get the value of the hardware cycle counter in the guest.
This method is supposed to return the total number of cycles executed in hardware mode relative to some arbitrary point in the past. It's mainly used when estimating the number of cycles actually executed by the CPU in kvmRun(). The default behavior of this method is to use the cycles performance counter, but some architectures may want to use internal registers instead.
Returns:
Number of host cycles executed relative to an undefined point in the past.
Reimplemented from BaseKvmCPU.
Definition at line 1276 of file x86_cpu.cc.
References getMSR(), and MSR_TSC.
uint64_t X86KvmCPU::getMSR (uint32_t index) const [protected]
Definition at line 1523 of file x86_cpu.cc.
References getMSRs().
Referenced by getHostCycles().
const Kvm::MSRIndexVector & X86KvmCPU::getMsrIntersection () const [protected]
Get a list of MSRs supported by both gem5 and KVM.
Note:
This method uses an internal cache and only generates the MSR list once.
Returns:
reference to a list of msr indices
Definition at line 1539 of file x86_cpu.cc.
References cachedMsrIntersection, DPRINTF, KvmVM::kvm, X86ISA::msrMap, BaseKvmCPU::vm, and warn.
Referenced by updateKvmStateMSRs(), and updateThreadContextMSRs().
void X86KvmCPU::getMSRs (struct kvm_msrs & msrs) const [protected]
Definition at line 1499 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by dumpMSRs(), getMSR(), and updateThreadContextMSRs().
void X86KvmCPU::getVCpuEvents (struct kvm_vcpu_events & events) const [protected]
Definition at line 1611 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by archIsDrained(), and dumpVCpuEvents().
void X86KvmCPU::getXCRs (struct kvm_xcrs & regs) const [protected]
Definition at line 1582 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by dumpXCRs().
void X86KvmCPU::getXSave (struct kvm_xsave & xsave) const [protected]
Definition at line 1596 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by dumpXSave(), and updateThreadContext().
void X86KvmCPU::handleIOMiscReg32 (int miscreg) [private]
Handle a 32-bit IO access that should be mapped to a MiscReg.
Note:
This method can only be called on when handling IO after a KVM_EXIT_IO.
Parameters:
miscreg Register to map the current IO access to.
Definition at line 1282 of file x86_cpu.cc.
References BaseKvmCPU::getGuestData(), BaseKvmCPU::getKvmRunState(), panic, ThreadContext::readMiscRegNoEffect(), ThreadContext::setMiscReg(), and BaseKvmCPU::tc.
Referenced by handleKvmExitIO().
Tick X86KvmCPU::handleKvmExitIO () [protected, virtual]
Handle x86 legacy IO (in/out).
Reimplemented from BaseKvmCPU.
Definition at line 1307 of file x86_cpu.cc.
References ThreadContext::contextId(), X86ISA::count, BaseKvmCPU::dataPort, Packet::dataStatic(), DPRINTF, EventManager::eventQueue(), BaseKvmCPU::getGuestData(), BaseKvmCPU::getKvmRunState(), handleIOMiscReg32(), ArmISA::i, IO_PCI_CONF_ADDR, IO_PCI_CONF_DATA_BASE, X86ISA::MISCREG_PCI_CONFIG_ADDRESS, ThreadContext::readMiscRegNoEffect(), MemCmd::ReadReq, MasterPort::sendAtomic(), Request::setThreadContext(), BaseKvmCPU::tc, Request::UNCACHEABLE, BaseKvmCPU::vm, MemCmd::WriteReq, X86ISA::x86IOAddress(), and X86ISA::x86PciConfigAddress().
Tick X86KvmCPU::handleKvmExitIRQWindowOpen () [protected, virtual]
The guest exited because an interrupt window was requested.
The guest exited because an interrupt window was requested (request_interrupt_window in the kvm_run structure was set to 1 before calling kvmRun) and it is now ready to receive
Returns:
Number of ticks spent servicing the IRQ
Reimplemented from BaseKvmCPU.
Definition at line 1369 of file x86_cpu.cc.
Tick X86KvmCPU::kvmRun (Tick ticks) [protected, virtual]
Request KVM to run the guest for a given number of ticks.
The method returns the approximate number of ticks executed.
Note:
The returned number of ticks can be both larger or smaller than the requested number of ticks. A smaller number can, for example, occur when the guest executes MMIO. A larger number is typically due to performance counter inaccuracies.
This method is virtual in order to allow implementations to check for architecture specific events (e.g., interrupts) before entering the VM.
It is the response of the caller (normally tick()) to make sure that the KVM state is synchronized and that the TC is invalidated after entering KVM.
This method does not normally cause any state transitions. However, if it may suspend the CPU by suspending the thread, which leads to a transition to the Idle state. In such a case, kvm must not be entered.
Parameters:
ticks Number of ticks to execute, set to 0 to exit immediately after finishing pending operations.
Returns:
Number of ticks executed (see note)
Reimplemented from BaseKvmCPU.
Definition at line 1186 of file x86_cpu.cc.
References BaseKvmCPU::_status, deliverInterrupts(), DPRINTF, BaseKvmCPU::getKvmRunState(), BaseKvmCPU::Idle, kvmRunWrapper(), BaseKvmCPU::syncThreadContext(), and BaseKvmCPU::tc.
Tick X86KvmCPU::kvmRunDrain () [protected, virtual]
Run the virtual CPU until draining completes.
In addition to the base functionality provided by BaseKvmCPU::kvmRunDrain(), this method handles x86-specific cases where there are pending interrupt events in the virtual CPU. These are handled by requesting an interrupt window if interrupts are pending (causing the vCPU to execute until interrupts can be delivered again).
See also:
BaseKvmCPU::kvmRunDrain()
archIsDrained()
Returns:
Number of ticks executed
Reimplemented from BaseKvmCPU.
Definition at line 1232 of file x86_cpu.cc.
References archIsDrained(), DPRINTF, BaseKvmCPU::getKvmRunState(), kvmRunWrapper(), and SimClock::Float::ms.
Tick X86KvmCPU::kvmRunWrapper (Tick ticks) [protected]
Wrapper that synchronizes state in kvm_run.
Definition at line 1257 of file x86_cpu.cc.
References BaseKvmCPU::getKvmRunState(), BaseKvmCPU::kvmRun(), X86ISA::MISCREG_APIC_BASE, X86ISA::MISCREG_CR8, ThreadContext::readMiscReg(), ThreadContext::setMiscReg(), and BaseKvmCPU::tc.
Referenced by kvmRun(), and kvmRunDrain().
void X86KvmCPU::setCPUID (const Kvm::CPUIDVector & cpuid) [protected]
Definition at line 1467 of file x86_cpu.cc.
References setCPUID().
void X86KvmCPU::setCPUID (const struct kvm_cpuid2 & cpuid) [protected]
Methods to access CPUID information using the extended API.
Only available if Kvm::capExtendedCPUID() is true.
Definition at line 1459 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by setCPUID(), and updateCPUID().
void X86KvmCPU::setDebugRegisters (const struct kvm_debugregs & regs) [protected]
Definition at line 1571 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
void X86KvmCPU::setMSR (uint32_t index, uint64_t value) [protected]
Definition at line 1508 of file x86_cpu.cc.
References setMSRs().
void X86KvmCPU::setMSRs (const KvmMSRVector & msrs) [protected]
Definition at line 1487 of file x86_cpu.cc.
References setMSRs().
void X86KvmCPU::setMSRs (const struct kvm_msrs & msrs) [protected]
Methods to access MSRs in the guest.
Definition at line 1479 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by setMSR(), setMSRs(), and updateKvmStateMSRs().
void X86KvmCPU::setVCpuEvents (const struct kvm_vcpu_events & events) [protected]
Definition at line 1618 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
void X86KvmCPU::setXCRs (const struct kvm_xcrs & regs) [protected]
Definition at line 1589 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
void X86KvmCPU::setXSave (const struct kvm_xsave & xsave) [protected]
Definition at line 1603 of file x86_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
Referenced by updateKvmStateFPUXSave().
void X86KvmCPU::startup ()
Reimplemented from BaseKvmCPU.
Definition at line 551 of file x86_cpu.cc.
References updateCPUID().
void X86KvmCPU::updateCPUID () [private]
Transfer gem5's CPUID values into the virtual CPU.
Definition at line 1423 of file x86_cpu.cc.
References MipsISA::cpuid, X86ISA::doCpuid(), makeKvmCpuid(), X86ISA::CpuidResult::rax, setCPUID(), and BaseKvmCPU::tc.
Referenced by startup().
void X86KvmCPU::updateKvmState () [protected, virtual]
Update the KVM state from the current thread context.
The base CPU calls this method before starting the guest CPU when the contextDirty flag is set. The architecture dependent CPU implementation is expected to update all guest state (registers, special registers, and FPU state).
Implements BaseKvmCPU.
Definition at line 670 of file x86_cpu.cc.
References DPRINTF, DTRACE, dump(), updateKvmStateFPU(), updateKvmStateMSRs(), updateKvmStateRegs(), and updateKvmStateSRegs().
Referenced by deliverInterrupts().
void X86KvmCPU::updateKvmStateFPU () [private]
Update FPU and SIMD registers.
This method uses the appropriate (depending on availability and user configuration) kernel API by calling updateKvmStateFPULegacy() or updateKvmStateFPUXSave().
See also:
updateKvmStateFPULegacy()
updateKvmStateFPUXSave()
Definition at line 904 of file x86_cpu.cc.
References updateKvmStateFPULegacy(), updateKvmStateFPUXSave(), and useXSave.
Referenced by updateKvmState().
void X86KvmCPU::updateKvmStateFPULegacy () [private]
Update FPU and SIMD registers using the legacy API.
Note:
This method should normally only be called by updateKvmStateFPU() which automatically chooses between available APIs.
Definition at line 855 of file x86_cpu.cc.
References X86ISA::MISCREG_FIOFF, X86ISA::MISCREG_FISEG, X86ISA::MISCREG_FOOFF, X86ISA::MISCREG_FOSEG, ThreadContext::readMiscRegNoEffect(), BaseKvmCPU::setFPUState(), BaseKvmCPU::tc, updateKvmStateFPUCommon(), and warn_once.
Referenced by updateKvmStateFPU().
void X86KvmCPU::updateKvmStateFPUXSave () [private]
Update FPU and SIMD registers using the XSave API.
Note:
This method should normally only be called by updateKvmStateFPU() which automatically chooses between available APIs.
Definition at line 879 of file x86_cpu.cc.
References X86ISA::MISCREG_FIOFF, X86ISA::MISCREG_FISEG, X86ISA::MISCREG_FOOFF, X86ISA::MISCREG_FOSEG, ThreadContext::readMiscRegNoEffect(), setXSave(), BaseKvmCPU::tc, updateKvmStateFPUCommon(), and warn_once.
Referenced by updateKvmStateFPU().
void X86KvmCPU::updateKvmStateMSRs () [private]
Update MSR registers.
Definition at line 913 of file x86_cpu.cc.
References DPRINTF, getMsrIntersection(), X86ISA::msrMap, ThreadContext::readMiscReg(), setMSRs(), and BaseKvmCPU::tc.
Referenced by updateKvmState().
void X86KvmCPU::updateKvmStateRegs () [private]
Support routines to update the state of the KVM CPU from gem5's state representation.
Update integer registers
Definition at line 683 of file x86_cpu.cc.
References FOREACH_IREG, X86ISA::getRFlags(), ThreadContext::instAddr(), X86ISA::MISCREG_CS_BASE, ThreadContext::readMiscReg(), BaseKvmCPU::setRegisters(), and BaseKvmCPU::tc.
Referenced by updateKvmState().
void X86KvmCPU::updateKvmStateSRegs () [private]
Update control registers (CRx, segments, etc.
)
Definition at line 750 of file x86_cpu.cc.
References forceSegAccessed(), FOREACH_DTABLE, FOREACH_SEGMENT, FOREACH_SREG, hack, X86ISA::MISCREG_RFLAGS, ThreadContext::readMiscReg(), SEG_CS_TYPE_ACCESSED, SEG_CS_TYPE_READ_ACCESSED, SEG_SYS_TYPE_TSS_AVAILABLE, SEG_SYS_TYPE_TSS_BUSY, BaseKvmCPU::setSpecialRegisters(), and BaseKvmCPU::tc.
Referenced by updateKvmState().
void X86KvmCPU::updateThreadContext () [protected, virtual]
Update the current thread context with the KVM state.
The base CPU after the guest updates any of the KVM state. In practice, this happens after kvmRun is called. The architecture dependent code is expected to read the state of the guest CPU and update gem5's thread state.
Implements BaseKvmCPU.
Definition at line 935 of file x86_cpu.cc.
References DPRINTF, DTRACE, dump(), BaseKvmCPU::getFPUState(), BaseKvmCPU::getRegisters(), BaseKvmCPU::getSpecialRegisters(), getXSave(), X86ISA::MISCREG_M5_REG, ThreadContext::setMiscReg(), BaseKvmCPU::tc, updateThreadContextFPU(), updateThreadContextMSRs(), updateThreadContextRegs(), updateThreadContextSRegs(), updateThreadContextXSave(), and useXSave.
void X86KvmCPU::updateThreadContextFPU (const struct kvm_fpu & fpu) [private]
Update FPU and SIMD registers using the legacy API.
Definition at line 1079 of file x86_cpu.cc.
References X86ISA::MISCREG_FIOFF, X86ISA::MISCREG_FISEG, X86ISA::MISCREG_FOOFF, X86ISA::MISCREG_FOSEG, ThreadContext::setMiscRegNoEffect(), BaseKvmCPU::tc, and updateThreadContextFPUCommon().
Referenced by updateThreadContext().
void X86KvmCPU::updateThreadContextMSRs () [private]
Update MSR registers.
Definition at line 1103 of file x86_cpu.cc.
References MipsISA::at, DPRINTF, getMsrIntersection(), getMSRs(), ArmISA::i, X86ISA::msrMap, ThreadContext::setMiscReg(), and BaseKvmCPU::tc.
Referenced by updateThreadContext().
void X86KvmCPU::updateThreadContextRegs (const struct kvm_regs & regs, const struct kvm_sregs & sregs) [private]
Support routines to update the state of gem5's thread context from KVM's state representation.
Update integer registers
Definition at line 969 of file x86_cpu.cc.
References FOREACH_IREG, ThreadContext::pcState(), X86ISA::setRFlags(), and BaseKvmCPU::tc.
Referenced by updateThreadContext().
void X86KvmCPU::updateThreadContextSRegs (const struct kvm_sregs & sregs) [private]
Update control registers (CRx, segments, etc.
)
Definition at line 1023 of file x86_cpu.cc.
References FOREACH_DTABLE, FOREACH_SEGMENT, FOREACH_SREG, and BaseKvmCPU::getKvmRunState().
Referenced by updateThreadContext().
void X86KvmCPU::updateThreadContextXSave (const struct kvm_xsave & kxsave) [private]
Update FPU and SIMD registers using the XSave API.
Definition at line 1090 of file x86_cpu.cc.
References FXSave::ctrl64, X86ISA::MISCREG_FIOFF, X86ISA::MISCREG_FISEG, X86ISA::MISCREG_FOOFF, X86ISA::MISCREG_FOSEG, ThreadContext::setMiscRegNoEffect(), BaseKvmCPU::tc, and updateThreadContextFPUCommon().
Referenced by updateThreadContext().
Member Data Documentation
Kvm::MSRIndexVector X86KvmCPU::cachedMsrIntersection [mutable, private]
Cached intersection of supported MSRs.
Definition at line 238 of file x86_cpu.hh.
Referenced by getMsrIntersection().
bool X86KvmCPU::haveDebugRegs [private]
Kvm::capDebugRegs() available?
Definition at line 242 of file x86_cpu.hh.
Referenced by dumpDebugRegs(), and X86KvmCPU().
bool X86KvmCPU::haveXCRs [private]
Kvm::capXCRs() available?
Definition at line 251 of file x86_cpu.hh.
Referenced by dumpXCRs(), and X86KvmCPU().
bool X86KvmCPU::haveXSave [private]
Kvm::capXSave() available?
Definition at line 244 of file x86_cpu.hh.
Referenced by dumpXSave(), and X86KvmCPU().
bool X86KvmCPU::useXSave [private]
Should the XSave interface be used to sync the FPU and SIMD registers?
Definition at line 249 of file x86_cpu.hh.
Referenced by dump(), updateKvmStateFPU(), updateThreadContext(), and X86KvmCPU().
The documentation for this class was generated from the following files:
cpu/kvm/x86_cpu.hh
cpu/kvm/x86_cpu.cc