gem5: X86ISA::RemoteGDB Class Reference
X86ISA::RemoteGDB Class Reference
#include <remote_gdb.hh>
Public Types
enum {
GDB32_EAX, GDB32_ECX, GDB32_EDX, GDB32_EBX,
GDB32_ESP, GDB32_EBP, GDB32_ESI, GDB32_EDI,
GDB32_EIP, GDB32_EFLAGS, GDB32_CS, GDB32_SS,
GDB32_DS, GDB32_ES, GDB32_FS, GDB32_GS,
GDB32_NUMREGS
}
enum {
GDB64_RAX, GDB64_RBX, GDB64_RCX, GDB64_RDX,
GDB64_RSI, GDB64_RDI, GDB64_RBP, GDB64_RSP,
GDB64_R8, GDB64_R9, GDB64_R10, GDB64_R11,
GDB64_R12, GDB64_R13, GDB64_R14, GDB64_R15,
GDB64_RIP, GDB64_RFLAGS_32 = (GDB64_RIP + 1) * 2, GDB64_CS_32, GDB64_SS_32,
GDB64_DS_32, GDB64_ES_32, GDB64_FS_32, GDB64_GS_32,
GDB64_NUMREGS = (GDB64_GS_32 + 1) / 2 + 1
}
Public Member Functions
RemoteGDB (System *system, ThreadContext *context)
bool acc (Addr addr, size_t len)
Protected Member Functions
void getregs ()
void setregs ()
bool checkBpLen (size_t len)
Detailed Description
Definition at line 54 of file remote_gdb.hh.
Member Enumeration Documentation
anonymous enum
Enumerator:
GDB32_EAX
GDB32_ECX
GDB32_EDX
GDB32_EBX
GDB32_ESP
GDB32_EBP
GDB32_ESI
GDB32_EDI
GDB32_EIP
GDB32_EFLAGS
GDB32_CS
GDB32_SS
GDB32_DS
GDB32_ES
GDB32_FS
GDB32_GS
GDB32_NUMREGS
Definition at line 57 of file remote_gdb.hh.
anonymous enum
Enumerator:
GDB64_RAX
GDB64_RBX
GDB64_RCX
GDB64_RDX
GDB64_RSI
GDB64_RDI
GDB64_RBP
GDB64_RSP
GDB64_R8
GDB64_R9
GDB64_R10
GDB64_R11
GDB64_R12
GDB64_R13
GDB64_R14
GDB64_R15
GDB64_RIP
GDB64_RFLAGS_32
GDB64_CS_32
GDB64_SS_32
GDB64_DS_32
GDB64_ES_32
GDB64_FS_32
GDB64_GS_32
GDB64_NUMREGS
Definition at line 79 of file remote_gdb.hh.
Constructor & Destructor Documentation
RemoteGDB::RemoteGDB (System * system, ThreadContext * context)
Definition at line 63 of file remote_gdb.cc.
Member Function Documentation
bool RemoteGDB::acc (Addr addr, size_t len) [virtual]
Implements BaseRemoteGDB.
Definition at line 68 of file remote_gdb.cc.
References BaseRemoteGDB::context, FullSystem, ThreadContext::getDTBPtr(), ThreadContext::getProcessPtr(), PageTableBase::lookup(), X86ISA::mask, Process::pTable, BaseTLB::Read, and X86ISA::Walker::startFunctional().
bool X86ISA::RemoteGDB::checkBpLen (size_t len) [inline, protected, virtual]
Reimplemented from BaseRemoteGDB.
Definition at line 122 of file remote_gdb.hh.
void RemoteGDB::getregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 92 of file remote_gdb.cc.
References BaseRemoteGDB::context, GDB32_CS, GDB32_EAX, GDB32_EBP, GDB32_EBX, GDB32_ECX, GDB32_EDI, GDB32_EDX, GDB32_EFLAGS, GDB32_EIP, GDB32_ESI, GDB32_ESP, GDB64_CS_32, GDB64_DS_32, GDB64_ES_32, GDB64_FS_32, GDB64_GS_32, GDB64_R10, GDB64_R11, GDB64_R12, GDB64_R13, GDB64_R14, GDB64_R15, GDB64_R8, GDB64_R9, GDB64_RAX, GDB64_RBP, GDB64_RBX, GDB64_RCX, GDB64_RDI, GDB64_RDX, GDB64_RFLAGS_32, GDB64_RIP, GDB64_RSI, GDB64_RSP, GDB64_SS_32, BaseRemoteGDB::gdbregs, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R13, ArmISA::INTREG_R14, ArmISA::INTREG_R15, ArmISA::INTREG_R8, ArmISA::INTREG_R9, X86ISA::MISCREG_CS, X86ISA::MISCREG_DS, X86ISA::MISCREG_ES, X86ISA::MISCREG_FS, X86ISA::MISCREG_GS, X86ISA::MISCREG_M5_REG, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SS, ThreadContext::pcState(), ThreadContext::readIntReg(), ThreadContext::readMiscRegNoEffect(), BaseRemoteGDB::GdbRegCache::regs32, BaseRemoteGDB::GdbRegCache::regs64, and X86ISA::SixtyFourBitMode.
void RemoteGDB::setregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 143 of file remote_gdb.cc.
References BaseRemoteGDB::context, GDB32_DS, GDB32_EAX, GDB32_EBP, GDB32_EBX, GDB32_ECX, GDB32_EDI, GDB32_EDX, GDB32_EFLAGS, GDB32_EIP, GDB32_ES, GDB32_ESI, GDB32_ESP, GDB32_FS, GDB32_GS, GDB32_SS, GDB64_CS_32, GDB64_DS_32, GDB64_ES_32, GDB64_FS_32, GDB64_GS_32, GDB64_R10, GDB64_R11, GDB64_R12, GDB64_R13, GDB64_R14, GDB64_R15, GDB64_R8, GDB64_R9, GDB64_RAX, GDB64_RBP, GDB64_RBX, GDB64_RCX, GDB64_RDI, GDB64_RDX, GDB64_RFLAGS_32, GDB64_RIP, GDB64_RSI, GDB64_RSP, GDB64_SS_32, BaseRemoteGDB::gdbregs, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R13, ArmISA::INTREG_R14, ArmISA::INTREG_R15, ArmISA::INTREG_R8, ArmISA::INTREG_R9, X86ISA::MISCREG_CS, X86ISA::MISCREG_DS, X86ISA::MISCREG_ES, X86ISA::MISCREG_FS, X86ISA::MISCREG_GS, X86ISA::MISCREG_M5_REG, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SS, ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), BaseRemoteGDB::GdbRegCache::regs32, BaseRemoteGDB::GdbRegCache::regs64, ThreadContext::setIntReg(), ThreadContext::setMiscReg(), X86ISA::SixtyFourBitMode, and warn.
The documentation for this class was generated from the following files:
arch/x86/remote_gdb.hh
arch/x86/remote_gdb.cc