gem5: SampledSetIdentifier Class Reference
SampledSetIdentifier Class Reference
#include <set_sample.hh>
Public Member Functions
SampledSetIdentifier (unsigned int _nsets, unsigned int _bsize)
unsigned int getSet (Addr addr)
unsigned int getConstituencyID (unsigned int set)
unsigned int getConstituencyOffset (unsigned int set)
bool isSampledSet (unsigned int set, unsigned int tid=0)
bool isSampledSetInverted (unsigned int set, unsigned int tid=0)
bool isSampledAddr (Addr addr, unsigned int tid=0)
bool isSampledAddrInverted (Addr addr, unsigned int tid=0)
Private Attributes
unsigned int nsets
unsigned int numSetsInConstituency
unsigned int bsize
Detailed Description
Definition at line 6 of file set_sample.hh.
Constructor & Destructor Documentation
SampledSetIdentifier::SampledSetIdentifier (unsigned int _nsets, unsigned int _bsize) [inline]
Definition at line 13 of file set_sample.hh.
References bsize, nsets, and numSetsInConstituency.
Member Function Documentation
unsigned int SampledSetIdentifier::getConstituencyID (unsigned int set) [inline]
Definition at line 20 of file set_sample.hh.
References numSetsInConstituency.
Referenced by isSampledSet(), and isSampledSetInverted().
unsigned int SampledSetIdentifier::getConstituencyOffset (unsigned int set) [inline]
Definition at line 21 of file set_sample.hh.
References numSetsInConstituency.
Referenced by isSampledSet(), and isSampledSetInverted().
unsigned int SampledSetIdentifier::getSet (Addr addr) [inline]
Definition at line 19 of file set_sample.hh.
References bsize, and nsets.
Referenced by isSampledAddr(), and isSampledAddrInverted().
bool SampledSetIdentifier::isSampledAddr (Addr addr, unsigned int tid = 0) [inline]
Definition at line 43 of file set_sample.hh.
References getSet(), and isSampledSet().
Referenced by AddressTracer::is_samplesets().
bool SampledSetIdentifier::isSampledAddrInverted (Addr addr, unsigned int tid = 0) [inline]
Definition at line 44 of file set_sample.hh.
References getSet(), and isSampledSetInverted().
bool SampledSetIdentifier::isSampledSet (unsigned int set, unsigned int tid = 0) [inline]
Definition at line 24 of file set_sample.hh.
References getConstituencyID(), getConstituencyOffset(), numSetsInConstituency, and ArmISA::offset.
Referenced by isSampledAddr().
bool SampledSetIdentifier::isSampledSetInverted (unsigned int set, unsigned int tid = 0) [inline]
Definition at line 33 of file set_sample.hh.
References getConstituencyID(), getConstituencyOffset(), numSetsInConstituency, and ArmISA::offset.
Referenced by isSampledAddrInverted().
Member Data Documentation
unsigned int SampledSetIdentifier::bsize [private]
Definition at line 10 of file set_sample.hh.
Referenced by getSet(), and SampledSetIdentifier().
unsigned int SampledSetIdentifier::nsets [private]
Definition at line 8 of file set_sample.hh.
Referenced by getSet(), and SampledSetIdentifier().
unsigned int SampledSetIdentifier::numSetsInConstituency [private]
Definition at line 9 of file set_sample.hh.
Referenced by getConstituencyID(), getConstituencyOffset(), isSampledSet(), isSampledSetInverted(), and SampledSetIdentifier().
The documentation for this class was generated from the following file:
mem/cache/tags/set_sample.hh