gem5: SimpleFreeList Class Reference
SimpleFreeList Class Reference
Free list for a single class of registers (e.g., integer or floating point).
#include <free_list.hh>
Public Member Functions
SimpleFreeList ()
void addReg (PhysRegIndex reg)
Add a physical register to the free list.
PhysRegIndex getReg ()
Get the next available register from the free list.
unsigned numFreeRegs () const
Return the number of free registers on the list.
bool hasFreeRegs () const
True iff there are free registers on the list.
Private Attributes
std::queue< PhysRegIndex > freeRegs
The actual free list.
Detailed Description
Free list for a single class of registers (e.g., integer or floating point).
Because the register class is implicitly determined by the rename map instance being accessed, all architectural register index parameters and values in this class are relative (e.g., fp2 is just index 2).
Definition at line 51 of file free_list.hh.
Constructor & Destructor Documentation
SimpleFreeList::SimpleFreeList () [inline]
Definition at line 60 of file free_list.hh.
Member Function Documentation
void SimpleFreeList::addReg (PhysRegIndex reg) [inline]
Add a physical register to the free list.
Definition at line 63 of file free_list.hh.
References freeRegs.
Referenced by UnifiedFreeList::addCCReg(), UnifiedFreeList::addFloatReg(), UnifiedFreeList::addIntReg(), and UnifiedFreeList::addReg().
PhysRegIndex SimpleFreeList::getReg () [inline]
Get the next available register from the free list.
Definition at line 66 of file free_list.hh.
References freeRegs.
Referenced by UnifiedFreeList::getCCReg(), UnifiedFreeList::getFloatReg(), UnifiedFreeList::getIntReg(), and SimpleRenameMap::rename().
bool SimpleFreeList::hasFreeRegs () const [inline]
True iff there are free registers on the list.
Definition at line 78 of file free_list.hh.
References freeRegs.
Referenced by UnifiedFreeList::hasFreeCCRegs(), UnifiedFreeList::hasFreeFloatRegs(), and UnifiedFreeList::hasFreeIntRegs().
unsigned SimpleFreeList::numFreeRegs () const [inline]
Return the number of free registers on the list.
Definition at line 75 of file free_list.hh.
References freeRegs.
Referenced by UnifiedFreeList::numFreeCCRegs(), SimpleRenameMap::numFreeEntries(), UnifiedFreeList::numFreeFloatRegs(), and UnifiedFreeList::numFreeIntRegs().
Member Data Documentation
std::queue<PhysRegIndex> SimpleFreeList::freeRegs [private]
The actual free list.
Definition at line 56 of file free_list.hh.
Referenced by addReg(), getReg(), hasFreeRegs(), and numFreeRegs().
The documentation for this class was generated from the following file:
cpu/o3/free_list.hh