gem5: ArmLiveProcess32 Class Reference
ArmLiveProcess32 Class Reference
#include <process.hh>
Public Member Functions
ArmISA::IntReg getSyscallArg (ThreadContext *tc, int &i, int width)
ArmISA::IntReg getSyscallArg (ThreadContext *tc, int &i)
void setSyscallArg (ThreadContext *tc, int i, ArmISA::IntReg val)
void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)
Protected Member Functions
ArmLiveProcess32 (LiveProcessParams *params, ObjectFile *objFile, ObjectFile::Arch _arch)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
Detailed Description
Definition at line 67 of file process.hh.
Constructor & Destructor Documentation
ArmLiveProcess32::ArmLiveProcess32 (LiveProcessParams * params, ObjectFile * objFile, ObjectFile::Arch _arch) [protected]
Definition at line 66 of file process.cc.
References Process::brk_point, ObjectFile::bssSize(), ObjectFile::dataBase(), ObjectFile::dataSize(), X86ISA::L, Process::mmap_end, Process::mmap_start, Process::next_thread_stack_base, AlphaISA::PageBytes, roundUp(), and Process::stack_base.
Member Function Documentation
ArmISA::IntReg ArmLiveProcess32::getSyscallArg (ThreadContext * tc, int & i) [virtual]
Implements LiveProcess.
Definition at line 403 of file process.cc.
References ArmISA::ArgumentReg0, and ThreadContext::readIntReg().
ArmISA::IntReg ArmLiveProcess32::getSyscallArg (ThreadContext * tc, int & i, int width) [virtual]
Reimplemented from LiveProcess.
Definition at line 417 of file process.cc.
References ArmISA::ArgumentReg0, ThreadContext::readIntReg(), and X86ISA::val.
void ArmLiveProcess32::initState () [protected, virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from Process.
Reimplemented in ArmFreebsdProcess32, and ArmLinuxProcess32.
Definition at line 101 of file process.cc.
References Process::contextIds, System::getThreadContext(), ArmISA::i, ArmISA::INTREG_SP, ArmISA::MISCREG_CPACR, ArmISA::MISCREG_FPEXC, AlphaISA::PageBytes, ThreadContext::readMiscReg(), ThreadContext::setMiscReg(), Process::system, and ArmISA::tc.
void ArmLiveProcess32::setSyscallArg (ThreadContext * tc, int i, ArmISA::IntReg val)
Definition at line 443 of file process.cc.
References ArmISA::ArgumentReg0, and ThreadContext::setIntReg().
void ArmLiveProcess32::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) [virtual]
Implements LiveProcess.
Definition at line 458 of file process.cc.
References ArmISA::CCREG_C, SyscallReturn::encodedValue(), ObjectFile::FreeBSD, ObjectFile::getOpSys(), LiveProcess::objFile, AlphaISA::ReturnValueReg, ThreadContext::setCCReg(), and ThreadContext::setIntReg().
The documentation for this class was generated from the following files:
arch/arm/process.hh
arch/arm/process.cc