gem5: StubSlavePort::ResponseEvent Class Reference
StubSlavePort::ResponseEvent Class Reference
Public Member Functions
ResponseEvent (StubSlavePort &owner_)
void process ()
Public Attributes
StubSlavePort & owner
Detailed Description
Definition at line 53 of file external_slave.cc.
Constructor & Destructor Documentation
StubSlavePort::ResponseEvent::ResponseEvent (StubSlavePort & owner_) [inline]
Definition at line 58 of file external_slave.cc.
Member Function Documentation
void StubSlavePort::ResponseEvent::process () [virtual]
Implements Event.
Definition at line 124 of file external_slave.cc.
References Packet::headerDelay, Packet::makeResponse(), StubSlavePort::mustRetry, owner, Packet::payloadDelay, StubSlavePort::responsePacket, SlavePort::sendRetryReq(), and SlavePort::sendTimingResp().
Referenced by StubSlavePort::recvRespRetry().
Member Data Documentation
StubSlavePort& StubSlavePort::ResponseEvent::owner
Definition at line 56 of file external_slave.cc.
Referenced by process().
The documentation for this class was generated from the following file:
mem/external_slave.cc