gem5: ClockDomain Class Reference
ClockDomain Class Reference
The ClockDomain provides clock to group of clocked objects bundled under the same clock domain.
#include <clock_domain.hh>
Public Types
typedef ClockDomainParams Params
Public Member Functions
ClockDomain (const Params *p, VoltageDomain *voltage_domain)
void regStats ()
Register statistics for this object.
Tick clockPeriod () const
Get the clock period.
void registerWithClockDomain (ClockedObject *c)
Register a ClockedObject to this ClockDomain.
VoltageDomain * voltageDomain () const
Get the voltage domain.
double voltage () const
Get the current voltage this clock domain operates at.
void addDerivedDomain (DerivedClockDomain *clock_domain)
Add a derived domain.
Protected Attributes
Tick _clockPeriod
Pre-computed clock period in ticks.
VoltageDomain * _voltageDomain
Voltage domain this clock domain belongs to.
std::vector< DerivedClockDomain * > children
Pointers to potential derived clock domains so we can propagate changes.
std::vector< ClockedObject * > members
Pointers to members of this clock domain, so that when the clock period changes, we can update each member's tick.
Private Attributes
Stats::Value currentClock
Stat to report clock period of clock domain.
Detailed Description
The ClockDomain provides clock to group of clocked objects bundled under the same clock domain.
The clock domains, in turn, are grouped into voltage domains. The clock domains provide support for a hierarchial structure with source and derived domains.
Definition at line 73 of file clock_domain.hh.
Member Typedef Documentation
typedef ClockDomainParams ClockDomain::Params
Reimplemented from SimObject.
Reimplemented in SrcClockDomain, and DerivedClockDomain.
Definition at line 110 of file clock_domain.hh.
Constructor & Destructor Documentation
ClockDomain::ClockDomain (const Params * p, VoltageDomain * voltage_domain) [inline]
Definition at line 111 of file clock_domain.hh.
Member Function Documentation
void ClockDomain::addDerivedDomain (DerivedClockDomain * clock_domain) [inline]
Add a derived domain.
Parameters:
Derived domain to add as a child
Definition at line 157 of file clock_domain.hh.
References children.
Referenced by DerivedClockDomain::DerivedClockDomain().
Tick ClockDomain::clockPeriod () const [inline]
Get the clock period.
Returns:
Clock period in ticks
Definition at line 123 of file clock_domain.hh.
References _clockPeriod.
Referenced by ClockedObject::clockPeriod(), SrcClockDomain::perfLevel(), SrcClockDomain::SrcClockDomain(), and DerivedClockDomain::updateClockPeriod().
void ClockDomain::registerWithClockDomain (ClockedObject * c) [inline]
Register a ClockedObject to this ClockDomain.
Parameters:
ClockedObject to add as a member
Definition at line 130 of file clock_domain.hh.
References members.
Referenced by ClockedObject::ClockedObject().
void ClockDomain::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 57 of file clock_domain.cc.
References _clockPeriod, currentClock, SimObject::name(), SimObject::params(), and Stats::ValueBase< Derived >::scalar().
double ClockDomain::voltage () const
Get the current voltage this clock domain operates at.
Returns:
Voltage applied to the clock domain
Definition at line 71 of file clock_domain.cc.
References _voltageDomain, and VoltageDomain::voltage().
VoltageDomain* ClockDomain::voltageDomain () const [inline]
Get the voltage domain.
Returns:
Voltage domain this clock domain belongs to
Definition at line 142 of file clock_domain.hh.
References _voltageDomain.
Referenced by SrcClockDomain::perfLevel(), VoltageDomain::registerSrcClockDom(), VoltageDomain::sanitiseVoltages(), and DVFSHandler::voltageAtPerfLevel().
Member Data Documentation
Tick ClockDomain::_clockPeriod [protected]
Pre-computed clock period in ticks.
This is populated by the inheriting classes based on how their period is determined.
Definition at line 89 of file clock_domain.hh.
Referenced by clockPeriod(), SrcClockDomain::clockPeriod(), regStats(), and DerivedClockDomain::updateClockPeriod().
VoltageDomain* ClockDomain::_voltageDomain [protected]
Voltage domain this clock domain belongs to.
Definition at line 94 of file clock_domain.hh.
Referenced by voltage(), and voltageDomain().
std::vector<DerivedClockDomain*> ClockDomain::children [protected]
Pointers to potential derived clock domains so we can propagate changes.
Definition at line 100 of file clock_domain.hh.
Referenced by addDerivedDomain(), SrcClockDomain::clockPeriod(), and DerivedClockDomain::updateClockPeriod().
Stats::Value ClockDomain::currentClock [private]
Stat to report clock period of clock domain.
Definition at line 81 of file clock_domain.hh.
Referenced by regStats().
std::vector<ClockedObject*> ClockDomain::members [protected]
Pointers to members of this clock domain, so that when the clock period changes, we can update each member's tick.
Definition at line 106 of file clock_domain.hh.
Referenced by SrcClockDomain::clockPeriod(), registerWithClockDomain(), and DerivedClockDomain::updateClockPeriod().
The documentation for this class was generated from the following files:
sim/clock_domain.hh
sim/clock_domain.cc