gem5: Minor::BranchData Class Reference
Minor::BranchData Class Reference
Forward data betwen Execute and Fetch1 carrying change-of-address/stream information.
#include <pipe_data.hh>
Public Types
enum Reason {
NoBranch, CorrectlyPredictedBranch, UnpredictedBranch, BranchPrediction,
BadlyPredictedBranchTarget, BadlyPredictedBranch, SuspendThread, WakeupFetch,
Interrupt, HaltFetch
}
Public Member Functions
BranchData ()
BranchData (Reason reason_, InstSeqNum new_stream_seq_num, InstSeqNum new_prediction_seq_num, TheISA::PCState target, MinorDynInstPtr inst_)
bool isBubble () const
bool isStreamChange () const
As static isStreamChange but on this branch data.
bool isBranch () const
As static isBranch but on this branch data.
void reportData (std::ostream &os) const
ReportIF interface.
Static Public Member Functions
static bool isStreamChange (const BranchData::Reason reason)
Is a request with this reason actually a request to change the PC rather than a bubble or branch prediction information.
static bool isBranch (const BranchData::Reason reason)
Is a request with this reason actually a 'real' branch, that is, a stream change that's not just an instruction to Fetch1 to halt or wake up.
static BranchData bubble ()
BubbleIF interface.
Public Attributes
Reason reason
Explanation for this branch.
InstSeqNum newStreamSeqNum
Sequence number of new stream/prediction to be adopted.
InstSeqNum newPredictionSeqNum
TheISA::PCState target
Starting PC of that stream.
MinorDynInstPtr inst
Instruction which caused this branch.
Detailed Description
Forward data betwen Execute and Fetch1 carrying change-of-address/stream information.
Definition at line 64 of file pipe_data.hh.
Member Enumeration Documentation
enum Minor::BranchData::Reason
Enumerator:
NoBranch
CorrectlyPredictedBranch
UnpredictedBranch
BranchPrediction
BadlyPredictedBranchTarget
BadlyPredictedBranch
SuspendThread
WakeupFetch
Interrupt
HaltFetch
Definition at line 67 of file pipe_data.hh.
Constructor & Destructor Documentation
Minor::BranchData::BranchData () [inline]
Definition at line 126 of file pipe_data.hh.
Referenced by bubble().
Minor::BranchData::BranchData (Reason reason_, InstSeqNum new_stream_seq_num, InstSeqNum new_prediction_seq_num, TheISA::PCState target, MinorDynInstPtr inst_) [inline]
Definition at line 132 of file pipe_data.hh.
Member Function Documentation
static BranchData Minor::BranchData::bubble () [inline, static]
BubbleIF interface.
Definition at line 146 of file pipe_data.hh.
References BranchData().
Referenced by Minor::Execute::evaluate().
bool Minor::BranchData::isBranch () const [inline]
As static isBranch but on this branch data.
Definition at line 153 of file pipe_data.hh.
References isBranch(), and reason.
Referenced by isBranch().
bool Minor::BranchData::isBranch (const BranchData::Reason reason) [static]
Is a request with this reason actually a 'real' branch, that is, a stream change that's not just an instruction to Fetch1 to halt or wake up.
Definition at line 115 of file pipe_data.cc.
References BadlyPredictedBranch, BadlyPredictedBranchTarget, BranchPrediction, CorrectlyPredictedBranch, HaltFetch, Interrupt, NoBranch, SuspendThread, UnpredictedBranch, and WakeupFetch.
bool Minor::BranchData::isBubble () const [inline]
Definition at line 147 of file pipe_data.hh.
References NoBranch, and reason.
Referenced by Minor::Execute::commitInst(), Minor::Fetch2::evaluate(), Minor::Fetch1::evaluate(), Minor::Execute::evaluate(), reportData(), and Minor::Execute::wakeupFetch().
bool Minor::BranchData::isStreamChange () const [inline]
As static isStreamChange but on this branch data.
Definition at line 150 of file pipe_data.hh.
References isStreamChange(), and reason.
Referenced by isStreamChange(), and Minor::Execute::updateBranchData().
bool Minor::BranchData::isStreamChange (const BranchData::Reason reason) [static]
Is a request with this reason actually a request to change the PC rather than a bubble or branch prediction information.
Definition at line 86 of file pipe_data.cc.
References BadlyPredictedBranch, BadlyPredictedBranchTarget, BranchPrediction, CorrectlyPredictedBranch, HaltFetch, Interrupt, NoBranch, SuspendThread, UnpredictedBranch, and WakeupFetch.
Referenced by Minor::Execute::commit(), Minor::Fetch2::evaluate(), Minor::Fetch1::evaluate(), and Minor::Execute::wakeupFetch().
void Minor::BranchData::reportData (std::ostream & os) const
ReportIF interface.
Definition at line 144 of file pipe_data.cc.
References inst, isBubble(), newPredictionSeqNum, newStreamSeqNum, and target.
Member Data Documentation
MinorDynInstPtr Minor::BranchData::inst
Instruction which caused this branch.
Definition at line 123 of file pipe_data.hh.
Referenced by reportData(), and Minor::Fetch2::updateBranchPrediction().
InstSeqNum Minor::BranchData::newPredictionSeqNum
Definition at line 117 of file pipe_data.hh.
Referenced by reportData(), and Minor::Fetch1::updateExpectedSeqNums().
InstSeqNum Minor::BranchData::newStreamSeqNum
Sequence number of new stream/prediction to be adopted.
Definition at line 116 of file pipe_data.hh.
Referenced by Minor::Fetch1::evaluate(), reportData(), and Minor::Fetch1::updateExpectedSeqNums().
Reason Minor::BranchData::reason
Explanation for this branch.
Definition at line 113 of file pipe_data.hh.
Referenced by Minor::Fetch1::changeStream(), Minor::Fetch1::evaluate(), isBranch(), isBubble(), isStreamChange(), and Minor::Fetch2::updateBranchPrediction().
TheISA::PCState Minor::BranchData::target
Starting PC of that stream.
Definition at line 120 of file pipe_data.hh.
Referenced by Minor::Fetch1::changeStream(), Minor::Fetch2::predictBranch(), reportData(), and Minor::Fetch2::updateBranchPrediction().
The documentation for this class was generated from the following files:
cpu/minor/pipe_data.hh
cpu/minor/pipe_data.cc