gem5: VirtQueue Class Reference
VirtQueue Class Reference
Base wrapper around a virtqueue.
#include <base.hh>
Classes
class VirtRing
VirtIO ring buffer wrapper.
Public Member Functions
virtual ~VirtQueue ()
Checkpointing Interface
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
Low-level Device Interface
void setAddress (Addr address)
Set the base address of this queue.
Addr getAddress () const
Get the guest physical address of this queue.
uint16_t getSize () const
Get the number of descriptors available in this queue.
VirtDescriptor * getDescriptor (VirtDescriptor::Index index)
Get a pointer to a specific descriptor in the queue.
Device Model Interfaces
VirtDescriptor * consumeDescriptor ()
Get an incoming descriptor chain from the queue.
void produceDescriptor (VirtDescriptor *desc, uint32_t len)
Send a descriptor chain to the guest.
Device Model Callbacks
virtual void onNotify ()
Notify queue of pending events.
virtual void onNotifyDescriptor (VirtDescriptor *desc)
Notify queue of pending incoming descriptor.
Debug interfaces
void dump () const
Dump the contents of a queue.
Static Public Attributes
static const unsigned ALIGN_BITS = 12
Page size used by VirtIO. It's hard-coded to 4096 bytes in the spec for historical reasons.
static const unsigned ALIGN_SIZE = 1 << ALIGN_BITS
Protected Member Functions
VirtQueue (PortProxy &proxy, uint16_t size)
Instantiate a new virtqueue.
Private Member Functions
VirtQueue ()
Private Attributes
const uint16_t _size
Queue size in terms of number of descriptors.
Addr _address
Base address of the queue.
PortProxy & memProxy
Guest physical memory proxy.
VirtRing< VirtDescriptor::Index > avail
Ring of available (incoming) descriptors.
VirtRing< struct vring_used_elem > used
Ring of used (outgoing) descriptors.
uint16_t _last_avail
Offset of last consumed descriptor in the VirtQueue::avail ring.
std::vector< VirtDescriptor > descriptors
Vector of pre-created descriptors indexed by their index into the queue.
Detailed Description
Base wrapper around a virtqueue.
VirtIO device models typically need to extend this class to implement their own device queues.
Note:
Queues must be registered with VirtIODeviceBase::registerQueue() to be active.
Definition at line 315 of file base.hh.
Constructor & Destructor Documentation
virtual VirtQueue::~VirtQueue () [inline, virtual]
Definition at line 317 of file base.hh.
VirtQueue::VirtQueue (PortProxy & proxy, uint16_t size) [protected]
Instantiate a new virtqueue.
Instantiate a virtqueue with a fixed size. The size is specified in descriptors which are defined as 4096 bytes each.
Parameters:
proxy Proxy to the guest physical memory.
size Size in descriptors/pages.
VirtQueue::VirtQueue () [private]
Member Function Documentation
VirtDescriptor * VirtQueue::consumeDescriptor ()
Get an incoming descriptor chain from the queue.
Returns:
Pointer to descriptor on success, NULL if no pending descriptors are available.
Definition at line 269 of file base.cc.
References _last_avail, avail, ArmISA::d, descriptors, DPRINTF, VirtQueue::VirtRing< T >::header, MipsISA::index, VirtQueue::VirtRing< T >::read(), VirtQueue::VirtRing< T >::ring, VirtDescriptor::updateChain(), and used.
Referenced by onNotify(), and VirtIOConsole::TermRecvQueue::trySend().
void VirtQueue::dump () const
Dump the contents of a queue.
Definition at line 302 of file base.cc.
References ArmISA::d, descriptors, and DTRACE.
Addr VirtQueue::getAddress () const [inline]
Get the guest physical address of this queue.
Returns:
Physical address in guest where this queue resides.
Definition at line 340 of file base.hh.
References _address.
VirtDescriptor* VirtQueue::getDescriptor (VirtDescriptor::Index index) [inline]
Get a pointer to a specific descriptor in the queue.
Note:
This interfaces is normally only used by VirtDescriptor to follow descriptor chains. Device models typically don't need to use it.
Returns:
Pointer to a VirtDescriptor.
Definition at line 358 of file base.hh.
References descriptors.
uint16_t VirtQueue::getSize () const [inline]
Get the number of descriptors available in this queue.
Returns:
Size of queue in descriptors.
Definition at line 347 of file base.hh.
References _size.
Referenced by VirtIODeviceBase::getQueueSize().
void VirtQueue::onNotify () [virtual]
Notify queue of pending events.
This method is called by VirtIODeviceBase::onNotify() to notify the device model of pending data in a virtqueue. The default implementation of this method iterates over the available descriptor chains and calls onNotifyDescriptor() for every new incoming chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented in VirtIOConsole::TermRecvQueue.
Definition at line 312 of file base.cc.
References consumeDescriptor(), ArmISA::d, DPRINTF, and onNotifyDescriptor().
virtual void VirtQueue::onNotifyDescriptor (VirtDescriptor * desc) [inline, virtual]
Notify queue of pending incoming descriptor.
This method is called by the default implementation of onNotify() to notify the device model of pending data in a descriptor chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented in VirtIOBlock::RequestQueue, VirtIOConsole::TermTransQueue, and VirtIO9PBase::FSQueue.
Definition at line 420 of file base.hh.
Referenced by onNotify().
void VirtQueue::produceDescriptor (VirtDescriptor * desc, uint32_t len)
Send a descriptor chain to the guest.
This method posts a descriptor chain to the guest after a device model has finished processing it. The device model typically needs to call VirtIODeviceBase::kick() to deliver notify tell the guest that the queue has been updated.
Note:
The desc parameter must refer to the first descriptor in a chain that has been retrieved using consumeDescriptor().
The len parameter specified the amount of data produced by the device model. It seems to be ignored by Linux and it is not well defined.
Parameters:
desc Start of descriptor chain.
len Length of the produced data.
Definition at line 288 of file base.cc.
References DPRINTF, ArmISA::e, VirtQueue::VirtRing< T >::header, VirtDescriptor::index(), VirtQueue::VirtRing< T >::readHeader(), VirtQueue::VirtRing< T >::ring, used, and VirtQueue::VirtRing< T >::write().
Referenced by VirtIOConsole::TermTransQueue::onNotifyDescriptor(), VirtIOBlock::RequestQueue::onNotifyDescriptor(), VirtIO9PBase::sendRMsg(), and VirtIOConsole::TermRecvQueue::trySend().
void VirtQueue::serialize (std::ostream & os) [virtual]
Definition at line 236 of file base.cc.
References _address, _last_avail, and SERIALIZE_SCALAR.
void VirtQueue::setAddress (Addr address)
Set the base address of this queue.
Parameters:
address Guest physical base address of the queue.
Definition at line 256 of file base.cc.
References _address, _size, ALIGN_SIZE, avail, VirtQueue::VirtRing< T >::setAddress(), and used.
Referenced by VirtIODeviceBase::setQueueAddress(), and unserialize().
void VirtQueue::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Definition at line 243 of file base.cc.
References _last_avail, paramIn(), setAddress(), and UNSERIALIZE_SCALAR.
Member Data Documentation
Addr VirtQueue::_address [private]
Base address of the queue.
Definition at line 457 of file base.hh.
Referenced by getAddress(), serialize(), and setAddress().
uint16_t VirtQueue::_last_avail [private]
Offset of last consumed descriptor in the VirtQueue::avail ring.
Definition at line 552 of file base.hh.
Referenced by consumeDescriptor(), serialize(), and unserialize().
const uint16_t VirtQueue::_size [private]
Queue size in terms of number of descriptors.
Definition at line 455 of file base.hh.
Referenced by getSize(), and setAddress().
const unsigned VirtQueue::ALIGN_BITS = 12 [static]
Page size used by VirtIO. It's hard-coded to 4096 bytes in the spec for historical reasons.
Definition at line 435 of file base.hh.
Referenced by VirtIODeviceBase::getQueueAddress().
const unsigned VirtQueue::ALIGN_SIZE = 1 << ALIGN_BITS [static]
Definition at line 436 of file base.hh.
Referenced by setAddress(), and VirtIODeviceBase::setQueueAddress().
VirtRing<VirtDescriptor::Index> VirtQueue::avail [private]
Ring of available (incoming) descriptors.
Definition at line 546 of file base.hh.
Referenced by consumeDescriptor(), and setAddress().
std::vector<VirtDescriptor> VirtQueue::descriptors [private]
Vector of pre-created descriptors indexed by their index into the queue.
Definition at line 556 of file base.hh.
Referenced by consumeDescriptor(), dump(), and getDescriptor().
PortProxy& VirtQueue::memProxy [private]
Guest physical memory proxy.
Definition at line 459 of file base.hh.
VirtRing<struct vring_used_elem> VirtQueue::used [private]
Ring of used (outgoing) descriptors.
Definition at line 548 of file base.hh.
Referenced by consumeDescriptor(), produceDescriptor(), and setAddress().
The documentation for this class was generated from the following files:
dev/virtio/base.hh
dev/virtio/base.cc