gem5: StackDistanceCounter Class Reference
StackDistanceCounter Class Reference
#include <sdp_counter.hh>
Public Member Functions
StackDistanceCounter (std::string _name, unsigned int _assoc, bool autoreset=true, bool autodump=true)
void sample (unsigned int lrustate)
uint64_t get (unsigned int lrustate)
void reset ()
void dump ()
Private Attributes
std::vector< uint64_t > counter
bool enable_reset
bool enable_dump
unsigned int assoc
std::string file_prefix
std::ostream * fout
Detailed Description
Definition at line 10 of file sdp_counter.hh.
Constructor & Destructor Documentation
StackDistanceCounter::StackDistanceCounter (std::string _name, unsigned int _assoc, bool autoreset = true, bool autodump = true) [inline]
Definition at line 21 of file sdp_counter.hh.
References assoc, enable_dump, enable_reset, file_prefix, Stats::registerDumpCallback(), and Stats::registerResetCallback().
Member Function Documentation
void StackDistanceCounter::dump () [inline]
Definition at line 57 of file sdp_counter.hh.
References assoc, OutputDirectory::close(), counter, OutputDirectory::create(), enable_dump, file_prefix, fout, ArmISA::i, and simout.
Referenced by reset(), and FLIP::updatePriorityPointer().
uint64_t StackDistanceCounter::get (unsigned int lrustate) [inline]
Definition at line 47 of file sdp_counter.hh.
References assoc, and counter.
void StackDistanceCounter::reset () [inline]
Definition at line 52 of file sdp_counter.hh.
References assoc, counter, dump(), and ArmISA::i.
void StackDistanceCounter::sample (unsigned int lrustate) [inline]
Definition at line 42 of file sdp_counter.hh.
References assoc, and counter.
Referenced by FLIP::accessBlock().
Member Data Documentation
unsigned int StackDistanceCounter::assoc [private]
Definition at line 16 of file sdp_counter.hh.
Referenced by dump(), get(), reset(), sample(), and StackDistanceCounter().
std::vector<uint64_t> StackDistanceCounter::counter [private]
Definition at line 12 of file sdp_counter.hh.
Referenced by dump(), get(), reset(), and sample().
bool StackDistanceCounter::enable_dump [private]
Definition at line 14 of file sdp_counter.hh.
Referenced by dump(), and StackDistanceCounter().
bool StackDistanceCounter::enable_reset [private]
Definition at line 13 of file sdp_counter.hh.
Referenced by StackDistanceCounter().
std::string StackDistanceCounter::file_prefix [private]
Definition at line 17 of file sdp_counter.hh.
Referenced by dump(), and StackDistanceCounter().
std::ostream* StackDistanceCounter::fout [private]
Definition at line 18 of file sdp_counter.hh.
Referenced by dump().
The documentation for this class was generated from the following file:
mem/cache/tags/sdp_counter.hh