gem5: BaseXBar::Layer< SrcType, DstType > Class Template Reference
BaseXBar::Layer< SrcType, DstType > Class Template Reference
A layer is an internal crossbar arbitration point with its own flow control.
#include <xbar.hh>
Public Member Functions
Layer (DstType &_port, BaseXBar &_xbar, const std::string &_name)
Create a layer and give it a name.
unsigned int drain (DrainManager *dm)
Drain according to the normal semantics, so that the crossbar can tell the layer to drain, and pass an event to signal back when drained.
const std::string name () const
Get the crossbar layer's name.
bool tryTiming (SrcType *src_port)
Determine if the layer accepts a packet from a specific port.
void succeededTiming (Tick busy_time)
Deal with a destination port accepting a packet by potentially removing the source port from the retry list (if retrying) and occupying the layer accordingly.
void failedTiming (SrcType *src_port, Tick busy_time)
Deal with a destination port not accepting a packet by potentially adding the source port to the retry list (if not already at the front) and occupying the layer accordingly.
void occupyLayer (Tick until)
Occupy the layer until until.
void retryWaiting ()
Send a retry to the port at the head of waitingForLayer.
void recvRetry ()
Handle a retry from a neighbouring module.
void regStats ()
Register stats for the layer.
Protected Member Functions
virtual void sendRetry (SrcType *retry_port)=0
Sending the actual retry, in a manner specific to the individual layers.
Private Types
enum State { IDLE, BUSY, RETRY }
We declare an enum to track the state of the layer.
Private Member Functions
void releaseLayer ()
Release the layer after being occupied and return to an idle state where we proceed to send a retry to any potential waiting port, or drain if asked to do so.
Private Attributes
DstType & port
The destination port this layer converges at.
BaseXBar & xbar
The crossbar this layer is a part of.
std::string _name
A name for this layer.
State state
track the state of the layer
DrainManager * drainManager
manager to signal when drained
std::deque< SrcType * > waitingForLayer
A deque of ports that retry should be called on because the original send was delayed due to a busy layer.
SrcType * waitingForPeer
Track who is waiting for the retry when receiving it from a peer.
EventWrapper< Layer,&Layer::releaseLayer > releaseEvent
event used to schedule a release of the layer
Stats::Scalar occupancy
Stats for occupancy and utilization.
Stats::Formula utilization
Detailed Description
template<typename SrcType, typename DstType>
class BaseXBar::Layer< SrcType, DstType >
A layer is an internal crossbar arbitration point with its own flow control.
Each layer is a converging multiplexer tree. By instantiating one layer per destination port (and per packet type, i.e. request, response, snoop request and snoop response), we model full crossbar structures like AXI, ACE, PCIe, etc.
The template parameter, PortClass, indicates the destination port type for the layer. The retry list holds either master ports or slave ports, depending on the direction of the layer. Thus, a request layer has a retry list containing slave ports, whereas a response layer holds master ports.
Definition at line 92 of file xbar.hh.
Member Enumeration Documentation
template<typename SrcType, typename DstType> enum BaseXBar::Layer::State [private]
We declare an enum to track the state of the layer.
The starting point is an idle state where the layer is waiting for a packet to arrive. Upon arrival, the layer transitions to the busy state, where it remains either until the packet transfer is done, or the header time is spent. Once the layer leaves the busy state, it can either go back to idle, if no packets have arrived while it was busy, or the layer goes on to retry the first port in waitingForLayer. A similar transition takes place from idle to retry if the layer receives a retry from one of its connected ports. The retry state lasts until the port in questions calls sendTiming and returns control to the layer, or goes to a busy state if the port does not immediately react to the retry by calling sendTiming.
Enumerator:
IDLE
BUSY
RETRY
Reimplemented from Drainable.
Definition at line 214 of file xbar.hh.
Constructor & Destructor Documentation
template<typename SrcType , typename DstType> BaseXBar::Layer< SrcType, DstType >::Layer (DstType & _port, BaseXBar & _xbar, const std::string & _name) [inline]
Create a layer and give it a name.
The layer uses the crossbar an event manager.
Parameters:
_port destination port the layer converges at
_xbar the crossbar this layer belongs to
_name the layer's name
Definition at line 146 of file xbar.cc.
Member Function Documentation
template<typename SrcType , typename DstType > unsigned int BaseXBar::Layer< SrcType, DstType >::drain (DrainManager * dm) [inline, virtual]
Drain according to the normal semantics, so that the crossbar can tell the layer to drain, and pass an event to signal back when drained.
Parameters:
de drain event to call once drained
Returns:
1 if busy or waiting to retry, or 0 if idle
Implements Drainable.
Definition at line 591 of file xbar.cc.
References DPRINTF, BaseXBar::Layer< SrcType, DstType >::drainManager, BaseXBar::Layer< SrcType, DstType >::IDLE, and BaseXBar::Layer< SrcType, DstType >::state.
template<typename SrcType, typename DstType > void BaseXBar::Layer< SrcType, DstType >::failedTiming (SrcType * src_port, Tick busy_time) [inline]
Deal with a destination port not accepting a packet by potentially adding the source port to the retry list (if not already at the front) and occupying the layer accordingly.
Parameters:
src_port Source port
busy_time Time to spend as a result of a failed send
Definition at line 218 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, BaseXBar::Layer< SrcType, DstType >::occupyLayer(), BaseXBar::Layer< SrcType, DstType >::state, and BaseXBar::Layer< SrcType, DstType >::waitingForPeer.
template<typename SrcType, typename DstType> const std::string BaseXBar::Layer< SrcType, DstType >::name () const [inline]
Get the crossbar layer's name.
Definition at line 121 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::regStats().
template<typename SrcType , typename DstType > void BaseXBar::Layer< SrcType, DstType >::occupyLayer (Tick until) [inline]
Occupy the layer until until.
Definition at line 154 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, curTick(), DPRINTF, BaseXBar::Layer< SrcType, DstType >::occupancy, BaseXBar::Layer< SrcType, DstType >::releaseEvent, EventManager::schedule(), BaseXBar::Layer< SrcType, DstType >::state, and BaseXBar::Layer< SrcType, DstType >::xbar.
Referenced by BaseXBar::Layer< SrcType, DstType >::failedTiming(), BaseXBar::Layer< SrcType, DstType >::retryWaiting(), and BaseXBar::Layer< SrcType, DstType >::succeededTiming().
template<typename SrcType , typename DstType > void BaseXBar::Layer< SrcType, DstType >::recvRetry () [inline]
Handle a retry from a neighbouring module.
This wraps retryWaiting by verifying that there are ports waiting before calling retryWaiting.
Definition at line 301 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, BaseXBar::Layer< SrcType, DstType >::IDLE, BaseXBar::Layer< SrcType, DstType >::retryWaiting(), BaseXBar::Layer< SrcType, DstType >::state, BaseXBar::Layer< SrcType, DstType >::waitingForLayer, and BaseXBar::Layer< SrcType, DstType >::waitingForPeer.
template<typename SrcType , typename DstType > void BaseXBar::Layer< SrcType, DstType >::regStats () [inline]
Register stats for the layer.
Definition at line 606 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, BaseXBar::Layer< SrcType, DstType >::occupancy, simTicks, and BaseXBar::Layer< SrcType, DstType >::utilization.
template<typename SrcType , typename DstType > void BaseXBar::Layer< SrcType, DstType >::releaseLayer () [inline, private]
Release the layer after being occupied and return to an idle state where we proceed to send a retry to any potential waiting port, or drain if asked to do so.
Definition at line 240 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, DPRINTF, BaseXBar::Layer< SrcType, DstType >::drainManager, BaseXBar::Layer< SrcType, DstType >::IDLE, BaseXBar::Layer< SrcType, DstType >::releaseEvent, BaseXBar::Layer< SrcType, DstType >::retryWaiting(), Event::scheduled(), DrainManager::signalDrainDone(), BaseXBar::Layer< SrcType, DstType >::state, BaseXBar::Layer< SrcType, DstType >::waitingForLayer, and BaseXBar::Layer< SrcType, DstType >::waitingForPeer.
template<typename SrcType , typename DstType > void BaseXBar::Layer< SrcType, DstType >::retryWaiting () [inline]
Send a retry to the port at the head of waitingForLayer.
The caller must ensure that the list is not empty.
Definition at line 266 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, ClockedObject::clockEdge(), BaseXBar::Layer< SrcType, DstType >::IDLE, BaseXBar::Layer< SrcType, DstType >::occupyLayer(), BaseXBar::Layer< SrcType, DstType >::RETRY, BaseXBar::Layer< SrcType, DstType >::sendRetry(), BaseXBar::Layer< SrcType, DstType >::state, BaseXBar::Layer< SrcType, DstType >::waitingForLayer, and BaseXBar::Layer< SrcType, DstType >::xbar.
Referenced by BaseXBar::Layer< SrcType, DstType >::recvRetry(), and BaseXBar::Layer< SrcType, DstType >::releaseLayer().
template<typename SrcType, typename DstType> virtual void BaseXBar::Layer< SrcType, DstType >::sendRetry (SrcType * retry_port) [protected, pure virtual]
Sending the actual retry, in a manner specific to the individual layers.
Note that for a MasterPort, there is both a RequestLayer and a SnoopResponseLayer using the same port, but using different functions for the flow control.
Implemented in BaseXBar::ReqLayer, BaseXBar::RespLayer, and BaseXBar::SnoopRespLayer.
Referenced by BaseXBar::Layer< SrcType, DstType >::retryWaiting().
template<typename SrcType , typename DstType > void BaseXBar::Layer< SrcType, DstType >::succeededTiming (Tick busy_time) [inline]
Deal with a destination port accepting a packet by potentially removing the source port from the retry list (if retrying) and occupying the layer accordingly.
Parameters:
busy_time Time to spend as a result of a successful send
Definition at line 206 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, BaseXBar::Layer< SrcType, DstType >::occupyLayer(), and BaseXBar::Layer< SrcType, DstType >::state.
template<typename SrcType, typename DstType > bool BaseXBar::Layer< SrcType, DstType >::tryTiming (SrcType * src_port) [inline]
Determine if the layer accepts a packet from a specific port.
If not, the port in question is also added to the retry list. In either case the state of the layer is updated accordingly.
Parameters:
port Source port presenting the packet
Returns:
True if the layer accepts the packet
Definition at line 175 of file xbar.cc.
References BaseXBar::Layer< SrcType, DstType >::BUSY, BaseXBar::Layer< SrcType, DstType >::state, BaseXBar::Layer< SrcType, DstType >::waitingForLayer, and BaseXBar::Layer< SrcType, DstType >::waitingForPeer.
Member Data Documentation
template<typename SrcType, typename DstType> std::string BaseXBar::Layer< SrcType, DstType >::_name [private]
A name for this layer.
Definition at line 196 of file xbar.hh.
template<typename SrcType, typename DstType> DrainManager* BaseXBar::Layer< SrcType, DstType >::drainManager [private]
manager to signal when drained
Definition at line 220 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::drain(), and BaseXBar::Layer< SrcType, DstType >::releaseLayer().
template<typename SrcType, typename DstType> Stats::Scalar BaseXBar::Layer< SrcType, DstType >::occupancy [private]
Stats for occupancy and utilization.
These stats capture the time the layer spends in the busy state and are thus only relevant when the memory system is in timing mode.
Definition at line 249 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::occupyLayer(), and BaseXBar::Layer< SrcType, DstType >::regStats().
template<typename SrcType, typename DstType> DstType& BaseXBar::Layer< SrcType, DstType >::port [private]
The destination port this layer converges at.
Definition at line 190 of file xbar.hh.
template<typename SrcType, typename DstType> EventWrapper<Layer, &Layer::releaseLayer> BaseXBar::Layer< SrcType, DstType >::releaseEvent [private]
event used to schedule a release of the layer
Definition at line 242 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::occupyLayer(), and BaseXBar::Layer< SrcType, DstType >::releaseLayer().
template<typename SrcType, typename DstType> State BaseXBar::Layer< SrcType, DstType >::state [private]
track the state of the layer
Definition at line 217 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::drain(), BaseXBar::Layer< SrcType, DstType >::failedTiming(), BaseXBar::Layer< SrcType, DstType >::occupyLayer(), BaseXBar::Layer< SrcType, DstType >::recvRetry(), BaseXBar::Layer< SrcType, DstType >::releaseLayer(), BaseXBar::Layer< SrcType, DstType >::retryWaiting(), BaseXBar::Layer< SrcType, DstType >::succeededTiming(), and BaseXBar::Layer< SrcType, DstType >::tryTiming().
template<typename SrcType, typename DstType> Stats::Formula BaseXBar::Layer< SrcType, DstType >::utilization [private]
Definition at line 250 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::regStats().
template<typename SrcType, typename DstType> std::deque<SrcType*> BaseXBar::Layer< SrcType, DstType >::waitingForLayer [private]
A deque of ports that retry should be called on because the original send was delayed due to a busy layer.
Definition at line 226 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::recvRetry(), BaseXBar::Layer< SrcType, DstType >::releaseLayer(), BaseXBar::Layer< SrcType, DstType >::retryWaiting(), and BaseXBar::Layer< SrcType, DstType >::tryTiming().
template<typename SrcType, typename DstType> SrcType* BaseXBar::Layer< SrcType, DstType >::waitingForPeer [private]
Track who is waiting for the retry when receiving it from a peer.
If no port is waiting NULL is stored.
Definition at line 232 of file xbar.hh.
Referenced by BaseXBar::Layer< SrcType, DstType >::failedTiming(), BaseXBar::Layer< SrcType, DstType >::recvRetry(), BaseXBar::Layer< SrcType, DstType >::releaseLayer(), and BaseXBar::Layer< SrcType, DstType >::tryTiming().
template<typename SrcType, typename DstType> BaseXBar& BaseXBar::Layer< SrcType, DstType >::xbar [private]
The crossbar this layer is a part of.
Definition at line 193 of file xbar.hh.
Referenced by BaseXBar::Layer< MasterPort, SlavePort >::name(), BaseXBar::Layer< SrcType, DstType >::occupyLayer(), and BaseXBar::Layer< SrcType, DstType >::retryWaiting().
The documentation for this class was generated from the following files:
mem/xbar.hh
mem/xbar.cc