gem5: NetworkInterface_d Class Reference
NetworkInterface_d Class Reference
#include <NetworkInterface_d.hh>
Public Types
typedef
GarnetNetworkInterface_dParams Params
Public Member Functions
NetworkInterface_d (const Params *p)
~NetworkInterface_d ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void addInPort (NetworkLink_d *in_link, CreditLink_d *credit_link)
void addOutPort (NetworkLink_d *out_link, CreditLink_d *credit_link)
void wakeup ()
void addNode (std::vector< MessageBuffer * > &inNode, std::vector< MessageBuffer * > &outNode)
void print (std::ostream &out) const
int get_vnet (int vc)
void init_net_ptr (GarnetNetwork_d *net_ptr)
uint32_t functionalWrite (Packet *)
Private Member Functions
bool flitisizeMessage (MsgPtr msg_ptr, int vnet)
int calculateVC (int vnet)
void scheduleOutputLink ()
This function looks at the NI buffers if some buffer has flits which are ready to traverse the link in the next cycle, and the downstream output vc associated with this flit has buffers left, the link is scheduled for the next cycle.
void checkReschedule ()
Private Attributes
GarnetNetwork_d * m_net_ptr
int m_virtual_networks
int m_num_vcs
int m_vc_per_vnet
NodeID m_id
std::vector< OutVcState_d * > m_out_vc_state
std::vector< int > m_vc_allocator
int m_vc_round_robin
flitBuffer_d * outSrcQueue
flitBuffer_d * creditQueue
NetworkLink_d * inNetLink
NetworkLink_d * outNetLink
CreditLink_d * m_credit_link
CreditLink_d * m_ni_credit_link
std::vector< flitBuffer_d * > m_ni_buffers
std::vector< Cycles > m_ni_enqueue_time
std::vector< MessageBuffer * > inNode_ptr
std::vector< MessageBuffer * > outNode_ptr
Detailed Description
Definition at line 50 of file NetworkInterface_d.hh.
Member Typedef Documentation
typedef GarnetNetworkInterface_dParams NetworkInterface_d::Params
Reimplemented from SimObject.
Definition at line 53 of file NetworkInterface_d.hh.
Constructor & Destructor Documentation
NetworkInterface_d::NetworkInterface_d (const Params * p)
Definition at line 45 of file NetworkInterface_d.cc.
References creditQueue, ArmISA::i, INFINITE_, m_id, m_ni_buffers, m_ni_enqueue_time, m_num_vcs, m_vc_allocator, m_vc_per_vnet, m_vc_round_robin, and m_virtual_networks.
NetworkInterface_d::~NetworkInterface_d ()
Definition at line 78 of file NetworkInterface_d.cc.
References creditQueue, m5::stl_helpers::deletePointers(), m_ni_buffers, m_out_vc_state, and outSrcQueue.
Member Function Documentation
void NetworkInterface_d::addInPort (NetworkLink_d * in_link, CreditLink_d * credit_link)
Definition at line 87 of file NetworkInterface_d.cc.
References creditQueue, inNetLink, m_ni_credit_link, NetworkLink_d::setLinkConsumer(), and NetworkLink_d::setSourceQueue().
void NetworkInterface_d::addNode (std::vector< MessageBuffer * > & inNode, std::vector< MessageBuffer * > & outNode)
Definition at line 109 of file NetworkInterface_d.cc.
References inNode_ptr, and outNode_ptr.
void NetworkInterface_d::addOutPort (NetworkLink_d * out_link, CreditLink_d * credit_link)
Definition at line 97 of file NetworkInterface_d.cc.
References m_credit_link, outNetLink, outSrcQueue, NetworkLink_d::setLinkConsumer(), and NetworkLink_d::setSourceQueue().
int NetworkInterface_d::calculateVC (int vnet) [private]
Definition at line 194 of file NetworkInterface_d.cc.
References ClockedObject::curCycle(), ArmISA::i, IDLE_, m_out_vc_state, m_vc_allocator, and m_vc_per_vnet.
Referenced by flitisizeMessage().
void NetworkInterface_d::checkReschedule () [private]
Definition at line 360 of file NetworkInterface_d.cc.
References ClockedObject::curCycle(), inNode_ptr, m_ni_buffers, m_num_vcs, and Consumer::scheduleEvent().
Referenced by wakeup().
bool NetworkInterface_d::flitisizeMessage (MsgPtr msg_ptr, int vnet) [private]
Definition at line 130 of file NetworkInterface_d.cc.
References ACTIVE_, NetDest::add(), calculateVC(), NetDest::clear(), ClockedObject::curCycle(), NetDest::getAllDest(), NetworkMessage::getInternalDestination(), NetworkMessage::getMessageSize(), BaseGarnetNetwork::getNiFlitSize(), ArmISA::i, BaseGarnetNetwork::increment_injected_flits(), ArmISA::m, m_net_ptr, m_ni_buffers, m_ni_enqueue_time, m_out_vc_state, Network::MessageSizeType_to_int(), NetDest::removeNetDest(), safe_cast(), flit_d::set_delay(), and ClockedObject::ticksToCycles().
Referenced by wakeup().
uint32_t NetworkInterface_d::functionalWrite (Packet * pkt)
Definition at line 388 of file NetworkInterface_d.cc.
References flitBuffer_d::functionalWrite(), ArmISA::i, m_ni_buffers, m_num_vcs, and outSrcQueue.
int NetworkInterface_d::get_vnet (int vc)
Definition at line 349 of file NetworkInterface_d.cc.
References fatal, ArmISA::i, m_vc_per_vnet, and m_virtual_networks.
Referenced by scheduleOutputLink().
void NetworkInterface_d::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 71 of file NetworkInterface_d.cc.
References ArmISA::i, m_net_ptr, m_num_vcs, and m_out_vc_state.
void NetworkInterface_d::init_net_ptr (GarnetNetwork_d * net_ptr) [inline]
Definition at line 68 of file NetworkInterface_d.hh.
References m_net_ptr.
Referenced by GarnetNetwork_d::GarnetNetwork_d().
void NetworkInterface_d::print (std::ostream & out) const [virtual]
Implements Consumer.
Definition at line 382 of file NetworkInterface_d.cc.
void NetworkInterface_d::scheduleOutputLink () [private]
This function looks at the NI buffers if some buffer has flits which are ready to traverse the link in the next cycle, and the downstream output vc associated with this flit has buffers left, the link is scheduled for the next cycle.
Definition at line 296 of file NetworkInterface_d.cc.
References ClockedObject::clockEdge(), ClockedObject::curCycle(), flit_d::get_type(), get_vnet(), HEAD_TAIL_, ArmISA::i, INFINITE_, flitBuffer_d::insert(), BaseGarnetNetwork::isVNetOrdered(), m_net_ptr, m_ni_buffers, m_ni_enqueue_time, m_num_vcs, m_out_vc_state, m_vc_per_vnet, m_vc_round_robin, outNetLink, outSrcQueue, Consumer::scheduleEventAbsolute(), flit_d::set_time(), and TAIL_.
Referenced by wakeup().
void NetworkInterface_d::wakeup () [virtual]
Implements Consumer.
Definition at line 221 of file NetworkInterface_d.cc.
References ArmISA::b, checkReschedule(), ClockedObject::clockEdge(), NetworkLink_d::consumeLink(), creditQueue, ClockedObject::curCycle(), MessageBuffer::dequeue(), DPRINTF, flitisizeMessage(), flit_d::get_delay(), flit_d::get_enqueue_time(), flit_d::get_msg_ptr(), flit_d::get_type(), flit_d::get_vc(), flit_d::get_vnet(), HEAD_TAIL_, IDLE_, BaseGarnetNetwork::increment_network_latency(), BaseGarnetNetwork::increment_queueing_latency(), BaseGarnetNetwork::increment_received_flits(), inNetLink, inNode_ptr, flitBuffer_d::insert(), flit_d::is_free_signal(), NetworkLink_d::isReady(), MessageBuffer::isReady(), m_credit_link, m_id, m_net_ptr, m_ni_credit_link, m_out_vc_state, outNode_ptr, MessageBuffer::peekMsgPtr(), Consumer::scheduleEventAbsolute(), scheduleOutputLink(), and TAIL_.
Member Data Documentation
flitBuffer_d* NetworkInterface_d::creditQueue [private]
Definition at line 80 of file NetworkInterface_d.hh.
Referenced by addInPort(), NetworkInterface_d(), wakeup(), and ~NetworkInterface_d().
NetworkLink_d* NetworkInterface_d::inNetLink [private]
Definition at line 82 of file NetworkInterface_d.hh.
Referenced by addInPort(), and wakeup().
std::vector<MessageBuffer *> NetworkInterface_d::inNode_ptr [private]
Definition at line 93 of file NetworkInterface_d.hh.
Referenced by addNode(), checkReschedule(), and wakeup().
CreditLink_d* NetworkInterface_d::m_credit_link [private]
Definition at line 84 of file NetworkInterface_d.hh.
Referenced by addOutPort(), and wakeup().
NodeID NetworkInterface_d::m_id [private]
Definition at line 75 of file NetworkInterface_d.hh.
Referenced by NetworkInterface_d(), and wakeup().
GarnetNetwork_d* NetworkInterface_d::m_net_ptr [private]
Definition at line 73 of file NetworkInterface_d.hh.
Referenced by flitisizeMessage(), init(), init_net_ptr(), scheduleOutputLink(), and wakeup().
std::vector<flitBuffer_d *> NetworkInterface_d::m_ni_buffers [private]
Definition at line 89 of file NetworkInterface_d.hh.
Referenced by checkReschedule(), flitisizeMessage(), functionalWrite(), NetworkInterface_d(), scheduleOutputLink(), and ~NetworkInterface_d().
CreditLink_d* NetworkInterface_d::m_ni_credit_link [private]
Definition at line 85 of file NetworkInterface_d.hh.
Referenced by addInPort(), and wakeup().
std::vector<Cycles> NetworkInterface_d::m_ni_enqueue_time [private]
Definition at line 90 of file NetworkInterface_d.hh.
Referenced by flitisizeMessage(), NetworkInterface_d(), and scheduleOutputLink().
int NetworkInterface_d::m_num_vcs [private]
Definition at line 74 of file NetworkInterface_d.hh.
Referenced by checkReschedule(), functionalWrite(), init(), NetworkInterface_d(), and scheduleOutputLink().
std::vector<OutVcState_d *> NetworkInterface_d::m_out_vc_state [private]
Definition at line 76 of file NetworkInterface_d.hh.
Referenced by calculateVC(), flitisizeMessage(), init(), scheduleOutputLink(), wakeup(), and ~NetworkInterface_d().
std::vector<int> NetworkInterface_d::m_vc_allocator [private]
Definition at line 77 of file NetworkInterface_d.hh.
Referenced by calculateVC(), and NetworkInterface_d().
int NetworkInterface_d::m_vc_per_vnet [private]
Definition at line 74 of file NetworkInterface_d.hh.
Referenced by calculateVC(), get_vnet(), NetworkInterface_d(), and scheduleOutputLink().
int NetworkInterface_d::m_vc_round_robin [private]
Definition at line 78 of file NetworkInterface_d.hh.
Referenced by NetworkInterface_d(), and scheduleOutputLink().
int NetworkInterface_d::m_virtual_networks [private]
Definition at line 74 of file NetworkInterface_d.hh.
Referenced by get_vnet(), and NetworkInterface_d().
NetworkLink_d* NetworkInterface_d::outNetLink [private]
Definition at line 83 of file NetworkInterface_d.hh.
Referenced by addOutPort(), and scheduleOutputLink().
std::vector<MessageBuffer *> NetworkInterface_d::outNode_ptr [private]
Definition at line 95 of file NetworkInterface_d.hh.
Referenced by addNode(), and wakeup().
flitBuffer_d* NetworkInterface_d::outSrcQueue [private]
Definition at line 79 of file NetworkInterface_d.hh.
Referenced by addOutPort(), functionalWrite(), scheduleOutputLink(), and ~NetworkInterface_d().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/NetworkInterface_d.hh
mem/ruby/network/garnet/fixed-pipeline/NetworkInterface_d.cc