gem5: ArmISA::MicroIntRegXOp Class Reference
ArmISA::MicroIntRegXOp Class Reference
#include <macromem.hh>
Protected Member Functions
MicroIntRegXOp (const char *mnem, ExtMachInst machInst, OpClass __opClass, RegIndex _ura, RegIndex _urb, RegIndex _urc, ArmExtendType _type, uint32_t _shiftAmt)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
RegIndex ura
RegIndex urb
RegIndex urc
ArmExtendType type
uint32_t shiftAmt
Detailed Description
Definition at line 340 of file macromem.hh.
Constructor & Destructor Documentation
ArmISA::MicroIntRegXOp::MicroIntRegXOp (const char * mnem, ExtMachInst machInst, OpClass __opClass, RegIndex _ura, RegIndex _urb, RegIndex _urc, ArmExtendType _type, uint32_t _shiftAmt) [inline, protected]
Definition at line 347 of file macromem.hh.
Member Function Documentation
std::string ArmISA::MicroIntRegXOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 1559 of file macromem.cc.
References ccprintf(), ArmISA::ArmStaticInst::printExtendOperand(), ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), shiftAmt, ArmISA::ss, type, ura, urb, and urc.
Member Data Documentation
uint32_t ArmISA::MicroIntRegXOp::shiftAmt [protected]
Definition at line 345 of file macromem.hh.
Referenced by generateDisassembly().
ArmExtendType ArmISA::MicroIntRegXOp::type [protected]
Definition at line 344 of file macromem.hh.
Referenced by generateDisassembly().
RegIndex ArmISA::MicroIntRegXOp::ura [protected]
Definition at line 343 of file macromem.hh.
Referenced by generateDisassembly().
RegIndex ArmISA::MicroIntRegXOp::urb [protected]
Definition at line 343 of file macromem.hh.
Referenced by generateDisassembly().
RegIndex ArmISA::MicroIntRegXOp::urc [protected]
Definition at line 343 of file macromem.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/macromem.hh
arch/arm/insts/macromem.cc