gem5: PerfectSwitch Class Reference
PerfectSwitch Class Reference
#include <PerfectSwitch.hh>
Public Member Functions
PerfectSwitch (SwitchID sid, Switch *, uint32_t)
~PerfectSwitch ()
std::string name ()
void init (SimpleNetwork *)
void addInPort (const std::vector< MessageBuffer * > &in)
void addOutPort (const std::vector< MessageBuffer * > &out, const NetDest &routing_table_entry)
int getInLinks () const
int getOutLinks () const
void wakeup ()
void storeEventInfo (int info)
void clearStats ()
void collateStats ()
void print (std::ostream &out) const
Private Member Functions
PerfectSwitch (const PerfectSwitch &obj)
PerfectSwitch & operator= (const PerfectSwitch &obj)
void operateVnet (int vnet)
Private Attributes
SwitchID m_switch_id
std::vector< std::vector
< MessageBuffer * > > m_in
std::vector< std::vector
< MessageBuffer * > > m_out
std::vector< NetDest > m_routing_table
std::vector< LinkOrder > m_link_order
uint32_t m_virtual_networks
int m_round_robin_start
int m_wakeups_wo_switch
SimpleNetwork * m_network_ptr
std::vector< int > m_pending_message_count
Detailed Description
Definition at line 58 of file PerfectSwitch.hh.
Constructor & Destructor Documentation
PerfectSwitch::PerfectSwitch (SwitchID sid, Switch * sw, uint32_t virt_nets)
Definition at line 51 of file PerfectSwitch.cc.
References m_round_robin_start, m_switch_id, m_virtual_networks, and m_wakeups_wo_switch.
PerfectSwitch::~PerfectSwitch ()
Definition at line 107 of file PerfectSwitch.cc.
PerfectSwitch::PerfectSwitch (const PerfectSwitch & obj) [private]
Member Function Documentation
void PerfectSwitch::addInPort (const std::vector< MessageBuffer * > & in)
Definition at line 71 of file PerfectSwitch.cc.
References csprintf(), ArmISA::i, m_in, and m_switch_id.
Referenced by Switch::addInPort().
void PerfectSwitch::addOutPort (const std::vector< MessageBuffer * > & out, const NetDest & routing_table_entry)
Definition at line 93 of file PerfectSwitch.cc.
References MipsISA::l, LinkOrder::m_link, m_link_order, m_out, m_routing_table, and LinkOrder::m_value.
Referenced by Switch::addOutPort().
void PerfectSwitch::clearStats ()
Definition at line 315 of file PerfectSwitch.cc.
Referenced by Switch::resetStats().
void PerfectSwitch::collateStats ()
Definition at line 319 of file PerfectSwitch.cc.
Referenced by Switch::collateStats().
int PerfectSwitch::getInLinks () const [inline]
Definition at line 72 of file PerfectSwitch.hh.
References m_in.
int PerfectSwitch::getOutLinks () const [inline]
Definition at line 73 of file PerfectSwitch.hh.
References m_out.
void PerfectSwitch::init (SimpleNetwork * network_ptr)
Definition at line 61 of file PerfectSwitch.cc.
References ArmISA::i, m_network_ptr, m_pending_message_count, and m_virtual_networks.
Referenced by Switch::init().
std::string PerfectSwitch::name () [inline]
Definition at line 64 of file PerfectSwitch.hh.
References csprintf(), and m_switch_id.
void PerfectSwitch::operateVnet (int vnet) [private]
Definition at line 112 of file PerfectSwitch.cc.
References NetDest::AND(), NetDest::count(), MessageBuffer::dequeue(), DPRINTF, SimpleNetwork::getAdaptiveRouting(), NetworkMessage::getInternalDestination(), ArmISA::i, NetDest::intersectionIsNotEmpty(), MessageBuffer::isReady(), SimpleNetwork::isVNetOrdered(), m_in, m_link_order, m_network_ptr, m_out, m_pending_message_count, m_round_robin_start, m_routing_table, m_virtual_networks, MessageBuffer::peekMsgPtr(), Random::random(), random_mt, NetDest::removeNetDest(), safe_cast(), Consumer::scheduleEvent(), and ArmISA::v.
Referenced by wakeup().
PerfectSwitch& PerfectSwitch::operator= (const PerfectSwitch & obj) [private]
void PerfectSwitch::print (std::ostream & out) const [virtual]
Implements Consumer.
Definition at line 325 of file PerfectSwitch.cc.
References m_switch_id.
Referenced by operator<<().
void PerfectSwitch::storeEventInfo (int info) [virtual]
Reimplemented from Consumer.
Definition at line 309 of file PerfectSwitch.cc.
References m_pending_message_count.
void PerfectSwitch::wakeup () [virtual]
Implements Consumer.
Definition at line 284 of file PerfectSwitch.cc.
References m_virtual_networks, m_wakeups_wo_switch, operateVnet(), and PRIORITY_SWITCH_LIMIT.
Member Data Documentation
std::vector<std::vector<MessageBuffer*> > PerfectSwitch::m_in [private]
Definition at line 92 of file PerfectSwitch.hh.
Referenced by addInPort(), getInLinks(), and operateVnet().
std::vector<LinkOrder> PerfectSwitch::m_link_order [private]
Definition at line 96 of file PerfectSwitch.hh.
Referenced by addOutPort(), and operateVnet().
SimpleNetwork* PerfectSwitch::m_network_ptr [private]
Definition at line 102 of file PerfectSwitch.hh.
Referenced by init(), and operateVnet().
std::vector<std::vector<MessageBuffer*> > PerfectSwitch::m_out [private]
Definition at line 93 of file PerfectSwitch.hh.
Referenced by addOutPort(), getOutLinks(), and operateVnet().
std::vector<int> PerfectSwitch::m_pending_message_count [private]
Definition at line 103 of file PerfectSwitch.hh.
Referenced by init(), operateVnet(), and storeEventInfo().
int PerfectSwitch::m_round_robin_start [private]
Definition at line 99 of file PerfectSwitch.hh.
Referenced by operateVnet(), and PerfectSwitch().
std::vector<NetDest> PerfectSwitch::m_routing_table [private]
Definition at line 95 of file PerfectSwitch.hh.
Referenced by addOutPort(), and operateVnet().
SwitchID PerfectSwitch::m_switch_id [private]
Definition at line 89 of file PerfectSwitch.hh.
Referenced by addInPort(), name(), PerfectSwitch(), and print().
uint32_t PerfectSwitch::m_virtual_networks [private]
Definition at line 98 of file PerfectSwitch.hh.
Referenced by init(), operateVnet(), PerfectSwitch(), and wakeup().
int PerfectSwitch::m_wakeups_wo_switch [private]
Definition at line 100 of file PerfectSwitch.hh.
Referenced by PerfectSwitch(), and wakeup().
The documentation for this class was generated from the following files:
mem/ruby/network/simple/PerfectSwitch.hh
mem/ruby/network/simple/PerfectSwitch.cc