gem5: CoherentXBar Class Reference
CoherentXBar Class Reference
A coherent crossbar connects a number of (potentially) snooping masters and slaves, and routes the request and response packets based on the address, and also forwards all requests to the snoopers and deals with the snoop responses.
#include <coherent_xbar.hh>
Classes
class CoherentXBarMasterPort
Declaration of the coherent crossbar master port type, one will be instantiated for each of the slave interfaces connecting to the crossbar.
class CoherentXBarSlavePort
Declaration of the coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
class SnoopRespPort
Internal class to bridge between an incoming snoop response from a slave port and forwarding it through an outgoing slave port.
Public Member Functions
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
CoherentXBar (const CoherentXBarParams *p)
virtual ~CoherentXBar ()
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
virtual void regStats ()
Register statistics for this object.
Protected Member Functions
bool recvTimingReq (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Timing request packet.
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Function called by the port when the crossbar is recieving a Timing response packet.
void recvTimingSnoopReq (PacketPtr pkt, PortID master_port_id)
Function called by the port when the crossbar is recieving a timing snoop request.
bool recvTimingSnoopResp (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a timing snoop response.
void recvReqRetry (PortID master_port_id)
Timing function called by port when it is once again able to process requests.
void forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id)
Forward a timing packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
void forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id, const std::vector< SlavePort * > &dests)
Forward a timing packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Tick recvAtomic (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Atomic transaction.
Tick recvAtomicSnoop (PacketPtr pkt, PortID master_port_id)
Function called by the port when the crossbar is recieving an atomic snoop transaction.
std::pair< MemCmd, Tick > forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id)
Forward an atomic packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
std::pair< MemCmd, Tick > forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id, PortID source_master_port_id, const std::vector< SlavePort * > &dests)
Forward an atomic packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
void recvFunctional (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Functional transaction.
void recvFunctionalSnoop (PacketPtr pkt, PortID master_port_id)
Function called by the port when the crossbar is recieving a functional snoop transaction.
void forwardFunctional (PacketPtr pkt, PortID exclude_slave_port_id)
Forward a functional packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Protected Attributes
std::vector< ReqLayer * > reqLayers
Declare the layers of this crossbar, one vector for requests, one for responses, and one for snoop responses.
std::vector< RespLayer * > respLayers
std::vector< SnoopRespLayer * > snoopLayers
std::vector< SnoopRespPort * > snoopRespPorts
std::vector< SlavePort * > snoopPorts
m5::hash_set< RequestPtr > outstandingSnoop
Store the outstanding requests that we are expecting snoop responses from so we can determine which snoop responses we generated and which ones were merely forwarded.
System * system
Keep a pointer to the system to be allow to querying memory system properties.
SnoopFilter * snoopFilter
A snoop filter that tracks cache line residency and can restrict the broadcast needed for probes.
const Cycles snoopResponseLatency
Cycles of snoop response latency.
Stats::Scalar snoops
Stats::Distribution snoopFanout
Detailed Description
A coherent crossbar connects a number of (potentially) snooping masters and slaves, and routes the request and response packets based on the address, and also forwards all requests to the snoopers and deals with the snoop responses.
The coherent crossbar can be used as a template for modelling QPI, HyperTransport, ACE and coherent OCP buses, and is typically used for the L1-to-L2 buses and as the main system interconnect.
See also:
gem5 Memory System
Definition at line 69 of file coherent_xbar.hh.
Constructor & Destructor Documentation
CoherentXBar::CoherentXBar (const CoherentXBarParams * p)
Definition at line 57 of file coherent_xbar.cc.
References BaseXBar::clearPortCache(), csprintf(), BaseXBar::defaultPortID, ArmISA::i, BaseXBar::masterPorts, SimObject::name(), reqLayers, respLayers, SnoopFilter::setSlavePorts(), BaseXBar::slavePorts, snoopFilter, snoopLayers, and snoopRespPorts.
CoherentXBar::~CoherentXBar () [virtual]
Definition at line 105 of file coherent_xbar.cc.
References MipsISA::l, MipsISA::p, reqLayers, respLayers, snoopLayers, and snoopRespPorts.
Member Function Documentation
unsigned int CoherentXBar::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Implements BaseXBar.
Definition at line 815 of file coherent_xbar.cc.
References MipsISA::l, reqLayers, respLayers, snoopLayers, and Stats::total.
std::pair< MemCmd, Tick > CoherentXBar::forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id, PortID source_master_port_id, const std::vector< SlavePort * > & dests) [protected]
Forward an atomic packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters:
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
source_master_port_id Id of the master port for snoops from below
dests Vector of destination ports for the forwarded pkt
Returns:
a pair containing the snoop response and snoop latency
Definition at line 682 of file coherent_xbar.cc.
References System::bypassCaches(), Packet::cmd, MemCmd::InvalidCmd, InvalidPortID, Packet::isResponse(), BaseXBar::masterPorts, Packet::memInhibitAsserted(), MipsISA::p, Stats::DistBase< Derived, Stor >::sample(), BaseXBar::slavePorts, snoopFanout, snoopFilter, system, SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
std::pair<MemCmd, Tick> CoherentXBar::forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id) [inline, protected]
Forward an atomic packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters:
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
Returns:
a pair containing the snoop response and snoop latency
Definition at line 340 of file coherent_xbar.hh.
References InvalidPortID, and snoopPorts.
Referenced by recvAtomic(), and recvAtomicSnoop().
void CoherentXBar::forwardFunctional (PacketPtr pkt, PortID exclude_slave_port_id) [protected]
Forward a functional packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters:
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
Definition at line 793 of file coherent_xbar.cc.
References System::bypassCaches(), InvalidPortID, Packet::isResponse(), MipsISA::p, snoopPorts, and system.
Referenced by recvFunctional(), and recvFunctionalSnoop().
void CoherentXBar::forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id, const std::vector< SlavePort * > & dests) [protected]
Forward a timing packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters:
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
dests Vector of destination ports for the forwarded pkt
Definition at line 529 of file coherent_xbar.cc.
References System::bypassCaches(), Packet::cmdString(), DPRINTF, Packet::getAddr(), Packet::getSize(), InvalidPortID, MipsISA::p, Stats::DistBase< Derived, Stor >::sample(), snoopFanout, and system.
void CoherentXBar::forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id) [inline, protected]
Forward a timing packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters:
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
Definition at line 306 of file coherent_xbar.hh.
References snoopPorts.
Referenced by recvTimingReq(), and recvTimingSnoopReq().
void CoherentXBar::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BaseXBar.
Definition at line 118 of file coherent_xbar.cc.
References DPRINTF, SimObject::name(), MipsISA::p, BaseXBar::slavePorts, snoopPorts, and warn.
Tick CoherentXBar::recvAtomic (PacketPtr pkt, PortID slave_port_id) [protected]
Function called by the port when the crossbar is recieving a Atomic transaction.
Definition at line 567 of file coherent_xbar.cc.
References System::bypassCaches(), ClockedObject::clockPeriod(), Packet::cmd, Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), forwardAtomic(), Packet::getAddr(), Packet::getSize(), Packet::hasData(), MemCmd::InvalidCmd, InvalidPortID, Packet::isResponse(), SnoopFilter::lookupRequest(), BaseXBar::masterPorts, SimObject::name(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, BaseXBar::slavePorts, snoopFilter, system, BaseXBar::transDist, and SnoopFilter::updateResponse().
Referenced by CoherentXBar::CoherentXBarSlavePort::recvAtomic().
Tick CoherentXBar::recvAtomicSnoop (PacketPtr pkt, PortID master_port_id) [protected]
Function called by the port when the crossbar is recieving an atomic snoop transaction.
Definition at line 642 of file coherent_xbar.cc.
References ClockedObject::clockPeriod(), Packet::cmd, Packet::cmdString(), DPRINTF, forwardAtomic(), Packet::getAddr(), MemCmd::InvalidCmd, InvalidPortID, Packet::isResponse(), SnoopFilter::lookupSnoop(), BaseXBar::masterPorts, SimObject::name(), Packet::payloadDelay, snoopFilter, and snoops.
Referenced by CoherentXBar::CoherentXBarMasterPort::recvAtomicSnoop().
void CoherentXBar::recvFunctional (PacketPtr pkt, PortID slave_port_id) [protected]
Function called by the port when the crossbar is recieving a Functional transaction.
Definition at line 753 of file coherent_xbar.cc.
References System::bypassCaches(), Packet::cmdString(), DPRINTF, BaseXBar::findPort(), forwardFunctional(), Packet::getAddr(), Packet::isPrint(), Packet::isResponse(), BaseXBar::masterPorts, SimObject::name(), BaseXBar::slavePorts, and system.
Referenced by CoherentXBar::CoherentXBarSlavePort::recvFunctional().
void CoherentXBar::recvFunctionalSnoop (PacketPtr pkt, PortID master_port_id) [protected]
Function called by the port when the crossbar is recieving a functional snoop transaction.
Definition at line 778 of file coherent_xbar.cc.
References Packet::cmdString(), DPRINTF, forwardFunctional(), Packet::getAddr(), InvalidPortID, Packet::isPrint(), BaseXBar::masterPorts, and SimObject::name().
Referenced by CoherentXBar::CoherentXBarMasterPort::recvFunctionalSnoop().
void CoherentXBar::recvReqRetry (PortID master_port_id) [protected]
Timing function called by port when it is once again able to process requests.
Definition at line 558 of file coherent_xbar.cc.
References reqLayers.
Referenced by CoherentXBar::CoherentXBarMasterPort::recvReqRetry().
bool CoherentXBar::recvTimingReq (PacketPtr pkt, PortID slave_port_id) [protected]
Function called by the port when the crossbar is recieving a Timing request packet.
Definition at line 139 of file coherent_xbar.cc.
References System::bypassCaches(), BaseXBar::calcPacketTiming(), ClockedObject::clockEdge(), ClockedObject::clockPeriod(), Packet::cmd, Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), BaseXBar::forwardLatency, forwardTiming(), BaseXBar::frontendLatency, Packet::getAddr(), Packet::getSize(), Packet::hasData(), Packet::headerDelay, Packet::isExpressSnoop(), SnoopFilter::lookupRequest(), BaseXBar::masterPorts, Packet::memInhibitAsserted(), Port::name(), Packet::needsResponse(), outstandingSnoop, panic_if, Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::req, reqLayers, BaseXBar::routeTo, BaseXBar::slavePorts, snoopFilter, snoops, system, BaseXBar::transDist, and SnoopFilter::updateRequest().
Referenced by CoherentXBar::CoherentXBarSlavePort::recvTimingReq().
bool CoherentXBar::recvTimingResp (PacketPtr pkt, PortID master_port_id) [protected]
Function called by the port when the crossbar is recieving a Timing response packet.
Definition at line 287 of file coherent_xbar.cc.
References System::bypassCaches(), BaseXBar::calcPacketTiming(), ClockedObject::clockEdge(), ClockedObject::clockPeriod(), Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::hasData(), InvalidPortID, ArmISA::M5_VAR_USED, BaseXBar::masterPorts, Port::name(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::req, respLayers, BaseXBar::responseLatency, BaseXBar::routeTo, BaseXBar::slavePorts, snoopFilter, system, BaseXBar::transDist, and SnoopFilter::updateResponse().
Referenced by CoherentXBar::CoherentXBarMasterPort::recvTimingResp().
void CoherentXBar::recvTimingSnoopReq (PacketPtr pkt, PortID master_port_id) [protected]
Function called by the port when the crossbar is recieving a timing snoop request.
Definition at line 350 of file coherent_xbar.cc.
References Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), forwardTiming(), Packet::getAddr(), InvalidPortID, Packet::isExpressSnoop(), SnoopFilter::lookupSnoop(), BaseXBar::masterPorts, Packet::memInhibitAsserted(), SimObject::name(), Packet::req, BaseXBar::routeTo, snoopFilter, snoops, and BaseXBar::transDist.
Referenced by CoherentXBar::CoherentXBarMasterPort::recvTimingSnoopReq().
bool CoherentXBar::recvTimingSnoopResp (PacketPtr pkt, PortID slave_port_id) [protected]
Function called by the port when the crossbar is recieving a timing snoop response.
Definition at line 396 of file coherent_xbar.cc.
References BaseXBar::calcPacketTiming(), ClockedObject::clockEdge(), ClockedObject::clockPeriod(), Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::hasData(), InvalidPortID, Packet::isExpressSnoop(), ArmISA::M5_VAR_USED, BaseXBar::masterPorts, Port::name(), outstandingSnoop, Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::req, respLayers, BaseXBar::responseLatency, BaseXBar::routeTo, BaseXBar::slavePorts, snoopFilter, snoopLayers, snoopResponseLatency, snoopRespPorts, snoops, BaseXBar::transDist, SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
Referenced by CoherentXBar::CoherentXBarSlavePort::recvTimingSnoopResp().
void CoherentXBar::regStats () [virtual]
Register statistics for this object.
Reimplemented from BaseXBar.
Definition at line 829 of file coherent_xbar.cc.
References Stats::Distribution::init(), MipsISA::l, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), reqLayers, respLayers, snoopFanout, snoopLayers, snoopPorts, and snoops.
Member Data Documentation
m5::hash_set<RequestPtr> CoherentXBar::outstandingSnoop [protected]
Store the outstanding requests that we are expecting snoop responses from so we can determine which snoop responses we generated and which ones were merely forwarded.
Definition at line 263 of file coherent_xbar.hh.
Referenced by recvTimingReq(), and recvTimingSnoopResp().
std::vector<ReqLayer*> CoherentXBar::reqLayers [protected]
Declare the layers of this crossbar, one vector for requests, one for responses, and one for snoop responses.
Definition at line 78 of file coherent_xbar.hh.
Referenced by CoherentXBar(), drain(), recvReqRetry(), recvTimingReq(), regStats(), and ~CoherentXBar().
std::vector<RespLayer*> CoherentXBar::respLayers [protected]
Definition at line 79 of file coherent_xbar.hh.
Referenced by CoherentXBar(), drain(), recvTimingResp(), recvTimingSnoopResp(), regStats(), and ~CoherentXBar().
Stats::Distribution CoherentXBar::snoopFanout [protected]
Definition at line 382 of file coherent_xbar.hh.
Referenced by forwardAtomic(), forwardTiming(), and regStats().
SnoopFilter* CoherentXBar::snoopFilter [protected]
A snoop filter that tracks cache line residency and can restrict the broadcast needed for probes.
NULL denotes an absent filter.
Definition at line 273 of file coherent_xbar.hh.
Referenced by CoherentXBar(), forwardAtomic(), recvAtomic(), recvAtomicSnoop(), recvTimingReq(), recvTimingResp(), recvTimingSnoopReq(), and recvTimingSnoopResp().
std::vector<SnoopRespLayer*> CoherentXBar::snoopLayers [protected]
Definition at line 80 of file coherent_xbar.hh.
Referenced by CoherentXBar(), drain(), recvTimingSnoopResp(), regStats(), and ~CoherentXBar().
std::vector<SlavePort*> CoherentXBar::snoopPorts [protected]
Definition at line 256 of file coherent_xbar.hh.
Referenced by forwardAtomic(), forwardFunctional(), forwardTiming(), init(), and regStats().
const Cycles CoherentXBar::snoopResponseLatency [protected]
Cycles of snoop response latency.
Definition at line 276 of file coherent_xbar.hh.
Referenced by recvTimingSnoopResp().
std::vector<SnoopRespPort*> CoherentXBar::snoopRespPorts [protected]
Definition at line 254 of file coherent_xbar.hh.
Referenced by CoherentXBar(), recvTimingSnoopResp(), and ~CoherentXBar().
Stats::Scalar CoherentXBar::snoops [protected]
Definition at line 381 of file coherent_xbar.hh.
Referenced by recvAtomicSnoop(), recvTimingReq(), recvTimingSnoopReq(), recvTimingSnoopResp(), and regStats().
System* CoherentXBar::system [protected]
Keep a pointer to the system to be allow to querying memory system properties.
Definition at line 269 of file coherent_xbar.hh.
Referenced by forwardAtomic(), forwardFunctional(), forwardTiming(), recvAtomic(), recvFunctional(), recvTimingReq(), and recvTimingResp().
The documentation for this class was generated from the following files:
mem/coherent_xbar.hh
mem/coherent_xbar.cc