gem5: PolicySelector Class Reference
PolicySelector Class Reference
#include <psel.hh>
Public Member Functions
PolicySelector (std::string name, unsigned int _nbit)
void increment ()
void decrement ()
bool isOver ()
bool isUnder ()
void sampleCounter ()
void regStats (std::string name)
void resetStats ()
void dumpStats ()
Public Attributes
Stats::Distribution valueDist
Private Attributes
unsigned int counter
unsigned int max
unsigned int nbit
PolicySelectorPlotter plotter
Tick sampled
Detailed Description
Definition at line 84 of file psel.hh.
Constructor & Destructor Documentation
PolicySelector::PolicySelector (std::string name, unsigned int _nbit)
Member Function Documentation
void PolicySelector::decrement ()
Definition at line 79 of file psel.cc.
References counter, plotter, PolicySelectorPlotter::sample(), and sampleCounter().
Referenced by DIP::setSampling().
void PolicySelector::dumpStats () [inline]
Definition at line 108 of file psel.hh.
void PolicySelector::increment ()
Definition at line 71 of file psel.cc.
References counter, max, plotter, PolicySelectorPlotter::sample(), and sampleCounter().
Referenced by DIP::setSampling().
bool PolicySelector::isOver () [inline]
Definition at line 101 of file psel.hh.
References counter, and max.
Referenced by DIP::insertBlock(), and isUnder().
bool PolicySelector::isUnder () [inline]
Definition at line 102 of file psel.hh.
References isOver().
void PolicySelector::regStats (std::string name)
Definition at line 60 of file psel.cc.
References Stats::Distribution::init(), nbit, Stats::pdf, and valueDist.
Referenced by DIP::regStats().
void PolicySelector::resetStats () [inline]
Definition at line 107 of file psel.hh.
void PolicySelector::sampleCounter ()
Definition at line 87 of file psel.cc.
References counter, curTick(), Stats::DistBase< Derived, Stor >::sample(), sampled, and valueDist.
Referenced by decrement(), and increment().
Member Data Documentation
unsigned int PolicySelector::counter [private]
Definition at line 86 of file psel.hh.
Referenced by decrement(), increment(), isOver(), and sampleCounter().
unsigned int PolicySelector::max [private]
Definition at line 87 of file psel.hh.
Referenced by increment(), and isOver().
unsigned int PolicySelector::nbit [private]
Definition at line 88 of file psel.hh.
Referenced by regStats().
PolicySelectorPlotter PolicySelector::plotter [private]
Definition at line 90 of file psel.hh.
Referenced by decrement(), and increment().
Tick PolicySelector::sampled [private]
Definition at line 92 of file psel.hh.
Referenced by sampleCounter().
Stats::Distribution PolicySelector::valueDist
Definition at line 108 of file psel.hh.
Referenced by regStats(), and sampleCounter().
The documentation for this class was generated from the following files:
mem/cache/tags/psel.hh
mem/cache/tags/psel.cc