gem5: SnoopFilter Class Reference
SnoopFilter Class Reference
This snoop filter keeps track of which connected port has a particular line of data.
#include <snoop_filter.hh>
Classes
struct SnoopItem
Per cache line item tracking a bitmask of SlavePorts who have an outstanding request to this line (requested) or already share a cache line with this address (holder).
Public Types
typedef std::vector< SlavePort * > SnoopList
Public Member Functions
SnoopFilter (const SnoopFilterParams *p)
void setSlavePorts (const std::vector< SlavePort * > &bus_slave_ports)
Init a new snoop filter and tell it about all the slave ports of the enclosing bus.
std::pair< SnoopList, Cycles > lookupRequest (const Packet *cpkt, const SlavePort &slave_port)
Lookup a request (from a slave port) in the snoop filter and return a list of other slave ports that need forwarding of the resulting snoops.
void updateRequest (const Packet *cpkt, const SlavePort &slave_port, bool will_retry)
For a successful request, update all data structures in the snoop filter reflecting the changes caused by that request.
std::pair< SnoopList, Cycles > lookupSnoop (const Packet *cpkt)
Handle an incoming snoop from below (the master port).
void updateSnoopResponse (const Packet *cpkt, const SlavePort &rsp_port, const SlavePort &req_port)
Let the snoop filter see any snoop responses that turn into request responses and indicate cache to cache transfers.
void updateSnoopForward (const Packet *cpkt, const SlavePort &rsp_port, const MasterPort &req_port)
Pass snoop responses that travel downward through the snoop filter and let them update the snoop filter state.
void updateResponse (const Packet *cpkt, const SlavePort &slave_port)
Update the snoop filter with a response from below (outer / other cache, or memory) and update the tracking information in the snoop filter.
std::pair< SnoopList, Cycles > snoopAll (Cycles latency) const
Simple factory methods for standard return values for lookupRequest.
std::pair< SnoopList, Cycles > snoopSelected (const SnoopList &slave_ports, Cycles latency) const
std::pair< SnoopList, Cycles > snoopDown (Cycles latency) const
virtual void regStats ()
Register statistics for this object.
Protected Types
typedef uint64_t SnoopMask
Protected Member Functions
SnoopMask portToMask (const SlavePort &port) const
Convert a single port to a corresponding, one-hot bitmask.
SnoopMask portListToMask (const SnoopList &ports) const
Convert multiple ports to a corresponding bitmask.
SnoopList maskToPortList (SnoopMask ports) const
Converts a bitmask of ports into the corresponing list of ports.
Private Attributes
m5::hash_map< Addr, SnoopItem > cachedLocations
Simple hash set of cached addresses.
SnoopList slavePorts
List of all attached slave ports.
const unsigned linesize
Cache line size.
const Cycles lookupLatency
Latency for doing a lookup in the filter.
Stats::Scalar totRequests
Statistics.
Stats::Scalar hitSingleRequests
Stats::Scalar hitMultiRequests
Stats::Scalar totSnoops
Stats::Scalar hitSingleSnoops
Stats::Scalar hitMultiSnoops
Detailed Description
This snoop filter keeps track of which connected port has a particular line of data.
It can be queried (through lookup*) on memory requests from above (reads / writes / ...); and also from below (snoops). The snoop filter precisely knows about the location of lines "above" it through a map from cache line address to sharers/ports. The snoop filter ties into the flows of requests (when they succeed at the lower interface), regular responses from below and also responses from sideway's caches (in update*). This allows the snoop filter to model cache-line residency by snooping the messages.
The tracking happens in two fields to be able to distinguish between in-flight requests (in requested) and already pulled in lines (in holder). This distinction is used for producing tighter assertions and tracking request completion. For safety, (requested | holder) should be notified and the requesting MSHRs will take care of ordering.
Overall, some trickery is required because: (1) snoops are not followed by an ACK, but only evoke a response if they need to (hit dirty) (2) side-channel information is funnelled through direct modifications of pkt, instead of proper messages through the bus (3) there are no clean evict messages telling the snoop filter that a local, upper cache dropped a line, making the snoop filter pessimistic for now (4) ordering: there is no single point of order in the system. Instead, requesting MSHRs track order between local requests and remote snoops
Definition at line 86 of file snoop_filter.hh.
Member Typedef Documentation
typedef std::vector<SlavePort*> SnoopFilter::SnoopList
Definition at line 88 of file snoop_filter.hh.
typedef uint64_t SnoopFilter::SnoopMask [protected]
Definition at line 194 of file snoop_filter.hh.
Constructor & Destructor Documentation
SnoopFilter::SnoopFilter (const SnoopFilterParams * p) [inline]
Definition at line 90 of file snoop_filter.hh.
Member Function Documentation
std::pair< SnoopFilter::SnoopList, Cycles > SnoopFilter::lookupRequest (const Packet * cpkt, const SlavePort & slave_port)
Lookup a request (from a slave port) in the snoop filter and return a list of other slave ports that need forwarding of the resulting snoops.
Additionally, update the tracking structures with new request information.
Parameters:
cpkt Pointer to the request packet. Not changed.
slave_port Slave port where the request came from.
Returns:
Pair of a vector of snoop target ports and lookup latency.
Definition at line 52 of file snoop_filter.cc.
References cachedLocations, Packet::cmdString(), DPRINTF, Packet::getAddr(), hitMultiRequests, hitSingleRequests, SnoopFilter::SnoopItem::holder, isPow2(), Request::isUncacheable(), linesize, lookupLatency, maskToPortList(), Packet::memInhibitAsserted(), Port::name(), Packet::needsResponse(), panic_if, portToMask(), Packet::req, SnoopFilter::SnoopItem::requested, snoopSelected(), and totRequests.
Referenced by CoherentXBar::recvAtomic(), and CoherentXBar::recvTimingReq().
std::pair< SnoopFilter::SnoopList, Cycles > SnoopFilter::lookupSnoop (const Packet * cpkt)
Handle an incoming snoop from below (the master port).
These can upgrade the tracking logic and may also benefit from additional steering thanks to the snoop filter.
Parameters:
cpkt Pointer to const Packet containing the snoop.
Returns:
Pair with a vector of SlavePorts that need snooping and a lookup latency.
Definition at line 145 of file snoop_filter.cc.
References cachedLocations, Packet::cmdString(), DPRINTF, Packet::getAddr(), hitMultiSnoops, hitSingleSnoops, SnoopFilter::SnoopItem::holder, Packet::isInvalidate(), isPow2(), Packet::isRequest(), linesize, lookupLatency, maskToPortList(), Packet::needsExclusive(), SnoopFilter::SnoopItem::requested, snoopAll(), snoopSelected(), and totSnoops.
Referenced by CoherentXBar::recvAtomicSnoop(), and CoherentXBar::recvTimingSnoopReq().
SnoopFilter::SnoopList SnoopFilter::maskToPortList (SnoopMask ports) const [inline, protected]
Converts a bitmask of ports into the corresponing list of ports.
Parameters:
ports SnoopMask of the requested ports
Returns:
SnoopList containing all the requested SlavePorts
Definition at line 263 of file snoop_filter.hh.
References portToMask(), and slavePorts.
Referenced by lookupRequest(), and lookupSnoop().
SnoopFilter::SnoopMask SnoopFilter::portListToMask (const SnoopList & ports) const [inline, protected]
Convert multiple ports to a corresponding bitmask.
Parameters:
ports SnoopList that should be converted.
Returns:
Bitmask corresponding to the ports in the list.
Definition at line 254 of file snoop_filter.hh.
References ArmISA::m, and portToMask().
SnoopFilter::SnoopMask SnoopFilter::portToMask (const SlavePort & port) const [inline, protected]
Convert a single port to a corresponding, one-hot bitmask.
Parameters:
port SlavePort that should be converted.
Returns:
One-hot bitmask corresponding to the port.
Definition at line 244 of file snoop_filter.hh.
References Port::getId(), and InvalidPortID.
Referenced by lookupRequest(), maskToPortList(), portListToMask(), updateRequest(), updateResponse(), updateSnoopForward(), and updateSnoopResponse().
void SnoopFilter::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 305 of file snoop_filter.cc.
References hitMultiRequests, hitMultiSnoops, hitSingleRequests, hitSingleSnoops, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), totRequests, and totSnoops.
void SnoopFilter::setSlavePorts (const std::vector< SlavePort * > & bus_slave_ports) [inline]
Init a new snoop filter and tell it about all the slave ports of the enclosing bus.
Parameters:
bus_slave_ports Vector of slave ports that the bus is attached to.
Definition at line 101 of file snoop_filter.hh.
References slavePorts.
Referenced by CoherentXBar::CoherentXBar().
std::pair<SnoopList, Cycles> SnoopFilter::snoopAll (Cycles latency) const [inline]
Simple factory methods for standard return values for lookupRequest.
Definition at line 176 of file snoop_filter.hh.
References slavePorts.
Referenced by lookupSnoop().
std::pair<SnoopList, Cycles> SnoopFilter::snoopDown (Cycles latency) const [inline]
Definition at line 185 of file snoop_filter.hh.
std::pair<SnoopList, Cycles> SnoopFilter::snoopSelected (const SnoopList & slave_ports, Cycles latency) const [inline]
Definition at line 180 of file snoop_filter.hh.
Referenced by lookupRequest(), and lookupSnoop().
void SnoopFilter::updateRequest (const Packet * cpkt, const SlavePort & slave_port, bool will_retry)
For a successful request, update all data structures in the snoop filter reflecting the changes caused by that request.
Parameters:
cpkt Pointer to the request packet. Not changed.
slave_port Slave port where the request came from.
will_retry This request will retry on this bus / snoop filter
Definition at line 101 of file snoop_filter.cc.
References cachedLocations, Packet::cmd, Packet::cmdString(), DPRINTF, Packet::getAddr(), SnoopFilter::SnoopItem::holder, Request::isUncacheable(), linesize, Port::name(), Packet::needsResponse(), panic_if, portToMask(), Packet::req, SnoopFilter::SnoopItem::requested, and MemCmd::Writeback.
Referenced by CoherentXBar::recvTimingReq().
void SnoopFilter::updateResponse (const Packet * cpkt, const SlavePort & slave_port)
Update the snoop filter with a response from below (outer / other cache, or memory) and update the tracking information in the snoop filter.
Parameters:
cpkt Pointer to const Packet holding the snoop response.
slave_port SlavePort that made the original request and is the target of this response.
Definition at line 274 of file snoop_filter.cc.
References cachedLocations, Packet::cmdString(), DPRINTF, Packet::getAddr(), SnoopFilter::SnoopItem::holder, Packet::isResponse(), Request::isUncacheable(), linesize, Port::name(), Packet::needsExclusive(), panic_if, portToMask(), Packet::req, SnoopFilter::SnoopItem::requested, and Packet::sharedAsserted().
Referenced by CoherentXBar::recvAtomic(), and CoherentXBar::recvTimingResp().
void SnoopFilter::updateSnoopForward (const Packet * cpkt, const SlavePort & rsp_port, const MasterPort & req_port)
Pass snoop responses that travel downward through the snoop filter and let them update the snoop filter state.
No additional routing happens.
Parameters:
cpkt Pointer to const Packet holding the snoop response.
rsp_port SlavePort that sends the response.
req_port MasterPort through which the response leaves this cluster.
Definition at line 244 of file snoop_filter.cc.
References cachedLocations, Packet::cmdString(), DPRINTF, Packet::getAddr(), SnoopFilter::SnoopItem::holder, Packet::isResponse(), linesize, ArmISA::M5_VAR_USED, Packet::memInhibitAsserted(), Port::name(), Packet::needsExclusive(), portToMask(), and SnoopFilter::SnoopItem::requested.
Referenced by CoherentXBar::forwardAtomic(), and CoherentXBar::recvTimingSnoopResp().
void SnoopFilter::updateSnoopResponse (const Packet * cpkt, const SlavePort & rsp_port, const SlavePort & req_port)
Let the snoop filter see any snoop responses that turn into request responses and indicate cache to cache transfers.
These will update the corresponding state in the filter.
Parameters:
cpkt Pointer to const Packet holding the snoop response.
rsp_port SlavePort that sends the response.
req_port SlavePort that made the original request and is the destination of the snoop response.
Definition at line 193 of file snoop_filter.cc.
References cachedLocations, Packet::cmd, Packet::cmdString(), DPRINTF, Packet::getAddr(), SnoopFilter::SnoopItem::holder, Packet::isResponse(), Request::isUncacheable(), linesize, Packet::memInhibitAsserted(), Port::name(), Packet::needsExclusive(), panic_if, portToMask(), Packet::req, SnoopFilter::SnoopItem::requested, Packet::sharedAsserted(), and MemCmd::Writeback.
Referenced by CoherentXBar::forwardAtomic(), and CoherentXBar::recvTimingSnoopResp().
Member Data Documentation
m5::hash_map<Addr, SnoopItem> SnoopFilter::cachedLocations [private]
Simple hash set of cached addresses.
Definition at line 225 of file snoop_filter.hh.
Referenced by lookupRequest(), lookupSnoop(), updateRequest(), updateResponse(), updateSnoopForward(), and updateSnoopResponse().
Stats::Scalar SnoopFilter::hitMultiRequests [private]
Definition at line 236 of file snoop_filter.hh.
Referenced by lookupRequest(), and regStats().
Stats::Scalar SnoopFilter::hitMultiSnoops [private]
Definition at line 240 of file snoop_filter.hh.
Referenced by lookupSnoop(), and regStats().
Stats::Scalar SnoopFilter::hitSingleRequests [private]
Definition at line 235 of file snoop_filter.hh.
Referenced by lookupRequest(), and regStats().
Stats::Scalar SnoopFilter::hitSingleSnoops [private]
Definition at line 239 of file snoop_filter.hh.
Referenced by lookupSnoop(), and regStats().
const unsigned SnoopFilter::linesize [private]
Cache line size.
Definition at line 229 of file snoop_filter.hh.
Referenced by lookupRequest(), lookupSnoop(), updateRequest(), updateResponse(), updateSnoopForward(), and updateSnoopResponse().
const Cycles SnoopFilter::lookupLatency [private]
Latency for doing a lookup in the filter.
Definition at line 231 of file snoop_filter.hh.
Referenced by lookupRequest(), and lookupSnoop().
SnoopList SnoopFilter::slavePorts [private]
List of all attached slave ports.
Definition at line 227 of file snoop_filter.hh.
Referenced by maskToPortList(), setSlavePorts(), and snoopAll().
Stats::Scalar SnoopFilter::totRequests [private]
Statistics.
Definition at line 234 of file snoop_filter.hh.
Referenced by lookupRequest(), and regStats().
Stats::Scalar SnoopFilter::totSnoops [private]
Definition at line 238 of file snoop_filter.hh.
Referenced by lookupSnoop(), and regStats().
The documentation for this class was generated from the following files:
mem/snoop_filter.hh
mem/snoop_filter.cc