gem5: FreebsdArmSystem Class Reference
FreebsdArmSystem Class Reference
#include <system.hh>
Public Types
typedef FreebsdArmSystemParams Params
Boilerplate params code.
Public Member Functions
const Params * params () const
FreebsdArmSystem (Params *p)
~FreebsdArmSystem ()
void initState ()
Initialise the system.
void startup ()
startup() is the final initialization call before simulation.
void mapPid (ThreadContext *tc, uint32_t pid)
This function creates a new task Id for the given pid.
Public Attributes
bool enableContextSwitchStatsDump
When enabled, dump stats/task info on context switches for Streamline and per-thread cache occupancy studies, etc.
std::map< uint32_t, uint32_t > taskMap
This map stores a mapping of OS process IDs to internal Task IDs.
std::ostream * taskFile
This is a file that is placed in the run directory that prints out mappings between taskIds and OS process IDs.
Protected Attributes
DumpStatsPCEventF * dumpStatsPCEventF
Private Attributes
PCEvent * kernelPanicEvent
Event to halt the simulator if the kernel calls panic().
PCEvent * kernelOopsEvent
Event to halt the simulator if the kernel calls oopses.
FreeBSD::UDelayEvent * uDelaySkipEvent
PC based event to skip udelay(<time>) calls and quiesce the processor for the appropriate amount of time.
FreeBSD::UDelayEvent * constUDelaySkipEvent
Another PC based skip event for const_udelay().
Addr secDataPtrAddr
These variables store addresses of important data structures that are normaly kept coherent at boot with cache mainetence operations.
Addr secDataAddr
Addr penReleaseAddr
Addr pen64ReleaseAddr
Addr bootReleaseAddr
Detailed Description
Definition at line 49 of file system.hh.
Member Typedef Documentation
typedef FreebsdArmSystemParams FreebsdArmSystem::Params
Boilerplate params code.
Reimplemented from GenericArmSystem.
Definition at line 56 of file system.hh.
Constructor & Destructor Documentation
FreebsdArmSystem::FreebsdArmSystem (Params * p)
Definition at line 53 of file system.cc.
References kernelOopsEvent, kernelPanicEvent, and uDelaySkipEvent.
FreebsdArmSystem::~FreebsdArmSystem ()
Definition at line 147 of file system.cc.
References constUDelaySkipEvent, dumpStatsPCEventF, and uDelaySkipEvent.
Member Function Documentation
void FreebsdArmSystem::initState () [virtual]
Initialise the system.
Reimplemented from GenericArmSystem.
Definition at line 77 of file system.cc.
References DtbObject::addBootCmdLine(), X86ISA::addr, bootReleaseAddr, createObjectFile(), debugSymbolTable, fatal, SymbolTable::findAddress(), DtbObject::findReleaseAddr(), ArmISA::i, inform, System::kernel, System::kernelSymtab, System::loadAddrMask, System::loadAddrOffset, ObjectFile::loadGlobalSymbols(), ObjectFile::loadSections(), params(), System::physProxy, PowerISA::ra, ObjectFile::setTextBase(), System::threadContexts, ULL, and warn.
void FreebsdArmSystem::mapPid (ThreadContext * tc, uint32_t pid)
This function creates a new task Id for the given pid.
Parameters:
tc thread context that is currentyl executing
const Params* FreebsdArmSystem::params () const [inline]
Reimplemented from GenericArmSystem.
Definition at line 58 of file system.hh.
References System::_params.
Referenced by initState().
void FreebsdArmSystem::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 165 of file system.cc.
Member Data Documentation
Addr FreebsdArmSystem::bootReleaseAddr [private]
Definition at line 118 of file system.hh.
Referenced by initState().
FreeBSD::UDelayEvent* FreebsdArmSystem::constUDelaySkipEvent [private]
Another PC based skip event for const_udelay().
Similar to the udelay skip, but this function precomputes the first multiply that is done in the generic case since the parameter is known at compile time. Thus we need to do some division to get back to us.
Definition at line 107 of file system.hh.
Referenced by ~FreebsdArmSystem().
DumpStatsPCEventF* FreebsdArmSystem::dumpStatsPCEventF [protected]
Definition at line 52 of file system.hh.
Referenced by ~FreebsdArmSystem().
bool FreebsdArmSystem::enableContextSwitchStatsDump
When enabled, dump stats/task info on context switches for Streamline and per-thread cache occupancy studies, etc.
Definition at line 65 of file system.hh.
PCEvent* FreebsdArmSystem::kernelOopsEvent [private]
Event to halt the simulator if the kernel calls oopses.
Definition at line 93 of file system.hh.
Referenced by FreebsdArmSystem().
PCEvent* FreebsdArmSystem::kernelPanicEvent [private]
Event to halt the simulator if the kernel calls panic().
Definition at line 90 of file system.hh.
Referenced by FreebsdArmSystem().
Addr FreebsdArmSystem::pen64ReleaseAddr [private]
Definition at line 117 of file system.hh.
Addr FreebsdArmSystem::penReleaseAddr [private]
Definition at line 116 of file system.hh.
Addr FreebsdArmSystem::secDataAddr [private]
Definition at line 115 of file system.hh.
Addr FreebsdArmSystem::secDataPtrAddr [private]
These variables store addresses of important data structures that are normaly kept coherent at boot with cache mainetence operations.
Since these operations aren't supported in gem5, we keep them coherent by making them uncacheable until all processors in the system boot.
Definition at line 114 of file system.hh.
std::ostream* FreebsdArmSystem::taskFile
This is a file that is placed in the run directory that prints out mappings between taskIds and OS process IDs.
Definition at line 75 of file system.hh.
std::map<uint32_t, uint32_t> FreebsdArmSystem::taskMap
This map stores a mapping of OS process IDs to internal Task IDs.
The mapping is done because the stats system doesn't tend to like vectors that are much greater than 1000 items and the entire process space is 65K.
Definition at line 71 of file system.hh.
FreeBSD::UDelayEvent* FreebsdArmSystem::uDelaySkipEvent [private]
PC based event to skip udelay(<time>) calls and quiesce the processor for the appropriate amount of time.
This is not functionally required but does speed up simulation.
Definition at line 100 of file system.hh.
Referenced by FreebsdArmSystem(), and ~FreebsdArmSystem().
The documentation for this class was generated from the following files:
arch/arm/freebsd/system.hh
arch/arm/freebsd/system.cc