gem5: BaseKvmCPU Class Reference
BaseKvmCPU Class Reference
Base class for KVM based CPU models.
#include <base.hh>
Classes
class KVMCpuPort
KVM memory port.
struct TickEvent
Public Member Functions
BaseKvmCPU (BaseKvmCPUParams *params)
virtual ~BaseKvmCPU ()
void init ()
void startup ()
void regStats ()
void serializeThread (std::ostream &os, ThreadID tid)
void unserializeThread (Checkpoint *cp, const std::string &section, ThreadID tid)
unsigned int drain (DrainManager *dm)
void drainResume ()
void switchOut ()
void takeOverFrom (BaseCPU *cpu)
void verifyMemoryMode () const
MasterPort & getDataPort ()
MasterPort & getInstPort ()
void wakeup ()
void activateContext (ThreadID thread_num)
void suspendContext (ThreadID thread_num)
void deallocateContext (ThreadID thread_num)
void haltContext (ThreadID thread_num)
ThreadContext * getContext (int tn)
Counter totalInsts () const
Counter totalOps () const
virtual void dump ()
Dump the internal state to the terminal.
void kick () const
Force an exit from KVM.
Public Attributes
SimpleThread * thread
A cached copy of a thread's state in the form of a SimpleThread object.
ThreadContext * tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
KvmVM & vm
Counter ctrInsts
Number of instructions executed by the CPU.
Protected Types
enum Status { Idle, Running, RunningService, RunningServiceCompletion }
Protected Member Functions
void tick ()
Execute the CPU until the next event in the main event queue or until the guest needs service from gem5.
virtual uint64_t getHostCycles () const
Get the value of the hardware cycle counter in the guest.
virtual Tick kvmRun (Tick ticks)
Request KVM to run the guest for a given number of ticks.
virtual Tick kvmRunDrain ()
Request the CPU to run until draining completes.
struct kvm_run * getKvmRunState ()
Get a pointer to the kvm_run structure containing all the input and output parameters from kvmRun().
uint8_t * getGuestData (uint64_t offset) const
Retrieve a pointer to guest data stored at the end of the kvm_run structure.
void kvmNonMaskableInterrupt ()
Send a non-maskable interrupt to the guest.
void kvmInterrupt (const struct kvm_interrupt &interrupt)
Send a normal interrupt to the guest.
std::string getAndFormatOneReg (uint64_t id) const
Get and format one register for printout.
virtual bool archIsDrained () const
Is the architecture specific code in a state that prevents draining?
Tick doMMIOAccess (Addr paddr, void *data, int size, bool write)
Inject a memory mapped IO request into gem5.
int ioctl (int request, long p1) const
vCPU ioctl interface.
int ioctl (int request, void *p1) const
int ioctl (int request) const
Protected Attributes
Status _status
CPU run state.
KVMCpuPort dataPort
Port for data requests.
KVMCpuPort instPort
Unused dummy port for the instruction interface.
bool threadContextDirty
Is the gem5 context dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
bool kvmStateDirty
Is the KVM state dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
const long vcpuID
KVM internal ID of the vCPU.
pthread_t vcpuThread
ID of the vCPU thread.
Private Member Functions
Tick flushCoalescedMMIO ()
Service MMIO requests in the mmioRing.
void setupSignalHandler ()
Setup a signal handler to catch the timer signal used to switch back to the monitor.
bool discardPendingSignal (int signum) const
Discard a (potentially) pending signal.
void startupThread ()
Thread-specific initialization.
bool tryDrain ()
Try to drain the CPU if a drain is pending.
void ioctlRun ()
Execute the KVM_RUN ioctl.
void setupInstStop ()
Setup an instruction break if there is one pending.
Private Attributes
int vcpuFD
KVM vCPU file descriptor.
int vcpuMMapSize
Size of MMAPed kvm_run area.
struct kvm_run * _kvmRun
Pointer to the kvm_run structure used to communicate parameters with KVM.
struct kvm_coalesced_mmio_ring * mmioRing
Coalesced MMIO ring buffer.
const long pageSize
Cached page size of the host.
TickEvent tickEvent
std::unique_ptr< BaseKvmTimer > runTimer
Timer used to force execution into the monitor after a specified number of simulation tick equivalents have executed in the guest.
float hostFactor
Host factor as specified in the configuration.
DrainManager * drainManager
Drain manager to use when signaling drain completion.
Stats::Scalar numInsts
Stats::Scalar numVMExits
Stats::Scalar numVMHalfEntries
Stats::Scalar numExitSignal
Stats::Scalar numMMIO
Stats::Scalar numCoalescedMMIO
Stats::Scalar numIO
Stats::Scalar numHalt
Stats::Scalar numInterrupts
Stats::Scalar numHypercalls
uint64_t activeInstPeriod
Currently active instruction count breakpoint.
PerfKvmCounter hwCycles
Guest cycle counter.
PerfKvmCounter hwInstructions
Guest instruction counter.
bool perfControlledByTimer
Does the runTimer control the performance counters?
void getRegisters (struct kvm_regs &regs) const
Get/Set the register state of the guest vCPU.
void setRegisters (const struct kvm_regs &regs)
void getSpecialRegisters (struct kvm_sregs &regs) const
void setSpecialRegisters (const struct kvm_sregs &regs)
void getFPUState (struct kvm_fpu &state) const
Get/Set the guest FPU/vector state.
void setFPUState (const struct kvm_fpu &state)
void setOneReg (uint64_t id, const void *addr)
Get/Set single register using the KVM_(SET|GET)_ONE_REG API.
void setOneReg (uint64_t id, uint64_t value)
void setOneReg (uint64_t id, uint32_t value)
void getOneReg (uint64_t id, void *addr) const
uint64_t getOneRegU64 (uint64_t id) const
uint32_t getOneRegU32 (uint64_t id) const
virtual void updateKvmState ()=0
Update the KVM state from the current thread context.
virtual void updateThreadContext ()=0
Update the current thread context with the KVM state.
void syncThreadContext ()
Update a thread context if the KVM state is dirty with respect to the cached thread context.
void syncKvmState ()
Update the KVM if the thread context is dirty.
virtual Tick handleKvmExit ()
Main kvmRun exit handler, calls the relevant handleKvmExit* depending on exit type.
virtual Tick handleKvmExitIO ()
The guest performed a legacy IO request (out/inp on x86).
virtual Tick handleKvmExitHypercall ()
The guest requested a monitor service using a hypercall.
virtual Tick handleKvmExitIRQWindowOpen ()
The guest exited because an interrupt window was requested.
virtual Tick handleKvmExitUnknown ()
An unknown architecture dependent error occurred when starting the vCPU.
virtual Tick handleKvmExitException ()
An unhandled virtualization exception occured.
virtual Tick handleKvmExitFailEntry ()
KVM failed to start the virtualized CPU.
void setSignalMask (const sigset_t *mask)
Set the signal mask used in kvmRun().
void setupCounters ()
Setup hardware performance counters.
void setupInstCounter (uint64_t period=0)
Setup the guest instruction counter.
Detailed Description
Base class for KVM based CPU models.
All architecture specific KVM implementation should inherit from this class. The most basic CPU models only need to override the updateKvmState() and updateThreadContext() methods to implement state synchronization between gem5 and KVM.
The architecture specific implementation is also responsible for delivering interrupts into the VM. This is typically done by overriding tick() and checking the thread context before entering into the VM. In order to deliver an interrupt, the implementation then calls KvmVM::setIRQLine() or BaseKvmCPU::kvmInterrupt() depending on the specifics of the underlying hardware/drivers.
Definition at line 77 of file base.hh.
Member Enumeration Documentation
enum BaseKvmCPU::Status [protected]
Enumerator:
Idle
Context not scheduled in KVM.
The CPU generally enters this state when the guest execute an instruction that halts the CPU (e.g., WFI on ARM or HLT on X86) if KVM traps this instruction. Ticks are not scheduled in this state.
See also:
suspendContext()
Running
Running normally.
This is the normal run state of the CPU. KVM will be entered next time tick() is called.
RunningService
Requiring service at the beginning of the next cycle.
The virtual machine has exited and requires service, tick() will call handleKvmExit() on the next cycle. The next state after running service is determined in handleKvmExit() and depends on what kind of service the guest requested:
IO/MMIO: RunningServiceCompletion
Halt: Idle
Others: Running
RunningServiceCompletion
Service completion in progress.
The VM has requested service that requires KVM to be entered once in order to get to a consistent state. This happens in handleKvmExit() or one of its friends after IO exits. After executing tick(), the CPU will transition into the Running or RunningService state.
Definition at line 169 of file base.hh.
Constructor & Destructor Documentation
BaseKvmCPU::BaseKvmCPU (BaseKvmCPUParams * params)
Definition at line 66 of file base.cc.
References FullSystem, SimpleThread::getTC(), ThreadContext::Halted, pageSize, panic, SimpleThread::setStatus(), tc, and thread.
BaseKvmCPU::~BaseKvmCPU () [virtual]
Definition at line 101 of file base.cc.
References _kvmRun, vcpuFD, and vcpuMMapSize.
Member Function Documentation
void BaseKvmCPU::activateContext (ThreadID thread_num)
Definition at line 437 of file base.cc.
References _status, DPRINTF, Idle, ThreadState::lastActivate, ThreadState::lastSuspend, Running, Event::scheduled(), thread, and tickEvent.
virtual bool BaseKvmCPU::archIsDrained () const [inline, protected, virtual]
Is the architecture specific code in a state that prevents draining?
This method should return false if there are any pending events in the guest vCPU that won't be carried over to the gem5 state and thus will prevent correct checkpointing or CPU handover. It might, for example, check for pending interrupts that have been passed to the vCPU but not acknowledged by the OS. Architecures implementing this method must override kvmRunDrain().
See also:
BaseKvmCPU::kvmRunDrain()
Returns:
true if the vCPU is drained, false otherwise.
Reimplemented in X86KvmCPU.
Definition at line 493 of file base.hh.
Referenced by drain(), and tryDrain().
void BaseKvmCPU::deallocateContext (ThreadID thread_num)
Definition at line 478 of file base.cc.
References suspendContext().
bool BaseKvmCPU::discardPendingSignal (int signum) const [private]
Discard a (potentially) pending signal.
Parameters:
signum Signal to discard
Returns:
true if the signal was pending, false otherwise.
Definition at line 1141 of file base.cc.
References panic.
Referenced by kvmRun().
Tick BaseKvmCPU::doMMIOAccess (Addr paddr, void * data, int size, bool write) [protected]
Inject a memory mapped IO request into gem5.
Parameters:
paddr Physical address
data Pointer to the source/destination buffer
size Memory access size
write True if write, False if read
Returns:
Number of ticks spent servicing the memory access
Definition at line 999 of file base.cc.
References ThreadContext::contextId(), dataPort, Packet::dataStatic(), EventManager::eventQueue(), ThreadContext::getDTBPtr(), SimpleThread::getTC(), GenericISA::handleIprRead(), GenericISA::handleIprWrite(), Request::isMmappedIpr(), BaseTLB::Read, MemCmd::ReadReq, MasterPort::sendAtomic(), Request::setThreadContext(), syncThreadContext(), tc, thread, threadContextDirty, Request::UNCACHEABLE, vm, warn, BaseTLB::Write, and MemCmd::WriteReq.
Referenced by flushCoalescedMMIO(), and handleKvmExit().
unsigned int BaseKvmCPU::drain (DrainManager * dm)
FALLTHROUGH
Definition at line 287 of file base.cc.
References _status, archIsDrained(), DPRINTF, drainManager, Idle, panic, Running, RunningService, RunningServiceCompletion, Event::scheduled(), syncThreadContext(), and tickEvent.
void BaseKvmCPU::drainResume ()
Definition at line 351 of file base.cc.
References _status, ThreadContext::Active, DPRINTF, Idle, Running, Event::scheduled(), ThreadContext::status(), tc, tickEvent, and verifyMemoryMode().
void BaseKvmCPU::dump () [virtual]
Dump the internal state to the terminal.
Reimplemented in ArmKvmCPU, ArmV8KvmCPU, and X86KvmCPU.
Definition at line 514 of file base.cc.
References inform.
Referenced by handleKvmExit(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitUnknown(), and serializeThread().
Tick BaseKvmCPU::flushCoalescedMMIO () [private]
Service MMIO requests in the mmioRing.
Returns:
Number of ticks spent servicing the MMIO requests in the MMIO ring buffer
Definition at line 1070 of file base.cc.
References doMMIOAccess(), DPRINTF, mmioRing, and numCoalescedMMIO.
Referenced by kvmRun().
std::string BaseKvmCPU::getAndFormatOneReg (uint64_t id) const [protected]
Get and format one register for printout.
This function call getOneReg() to retrieve the contents of one register and automatically formats it for printing.
Note:
The presence of this call depends on Kvm::capOneReg().
Definition at line 813 of file base.cc.
References panic, and ArmISA::ss.
Referenced by ArmV8KvmCPU::dump(), ArmKvmCPU::dumpKvmStateCoProc(), ArmKvmCPU::dumpKvmStateMisc(), ArmKvmCPU::dumpKvmStateVFP(), ArmV8KvmCPU::updateKvmState(), and ArmV8KvmCPU::updateThreadContext().
ThreadContext * BaseKvmCPU::getContext (int tn)
Definition at line 492 of file base.cc.
References syncThreadContext(), and tc.
Referenced by ArmKvmCPU::onKvmExitHypercall().
MasterPort& BaseKvmCPU::getDataPort () [inline]
Definition at line 99 of file base.hh.
References dataPort.
void BaseKvmCPU::getFPUState (struct kvm_fpu & state) const [protected]
Get/Set the guest FPU/vector state.
Definition at line 764 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::dumpFpuRegs(), and X86KvmCPU::updateThreadContext().
uint8_t* BaseKvmCPU::getGuestData (uint64_t offset) const [inline, protected]
Retrieve a pointer to guest data stored at the end of the kvm_run structure.
This is mainly used for PIO operations (KVM_EXIT_IO).
Parameters:
offset Offset as specified by the kvm_run structure
Returns:
Pointer to guest data
Definition at line 289 of file base.hh.
References _kvmRun.
Referenced by X86KvmCPU::handleIOMiscReg32(), and X86KvmCPU::handleKvmExitIO().
uint64_t BaseKvmCPU::getHostCycles () const [protected, virtual]
Get the value of the hardware cycle counter in the guest.
This method is supposed to return the total number of cycles executed in hardware mode relative to some arbitrary point in the past. It's mainly used when estimating the number of cycles actually executed by the CPU in kvmRun(). The default behavior of this method is to use the cycles performance counter, but some architectures may want to use internal registers instead.
Returns:
Number of host cycles executed relative to an undefined point in the past.
Reimplemented in X86KvmCPU.
Definition at line 619 of file base.cc.
References hwCycles, and PerfKvmCounter::read().
Referenced by kvmRun().
MasterPort& BaseKvmCPU::getInstPort () [inline]
Definition at line 100 of file base.hh.
References instPort.
struct kvm_run* BaseKvmCPU::getKvmRunState () [inline, read, protected]
Get a pointer to the kvm_run structure containing all the input and output parameters from kvmRun().
Definition at line 279 of file base.hh.
References _kvmRun.
Referenced by X86KvmCPU::handleIOMiscReg32(), X86KvmCPU::handleKvmExitIO(), X86KvmCPU::kvmRun(), X86KvmCPU::kvmRunDrain(), X86KvmCPU::kvmRunWrapper(), and X86KvmCPU::updateThreadContextSRegs().
void BaseKvmCPU::getOneReg (uint64_t id, void * addr) const [protected]
Definition at line 796 of file base.cc.
References ioctl(), and panic.
Referenced by getOneRegU32(), getOneRegU64(), and ArmV8KvmCPU::updateThreadContext().
uint32_t BaseKvmCPU::getOneRegU32 (uint64_t id) const [inline, protected]
Definition at line 357 of file base.hh.
References getOneReg().
Referenced by ArmKvmCPU::dumpKvmStateCoProc(), ArmKvmCPU::dumpKvmStateCore(), ArmKvmCPU::updateTCStateCoProc(), and ArmKvmCPU::updateTCStateCore().
uint64_t BaseKvmCPU::getOneRegU64 (uint64_t id) const [inline, protected]
Definition at line 352 of file base.hh.
References getOneReg().
Referenced by ArmKvmCPU::updateTCStateCoProc(), ArmKvmCPU::updateTCStateVFP(), and ArmV8KvmCPU::updateThreadContext().
void BaseKvmCPU::getRegisters (struct kvm_regs & regs) const [protected]
Get/Set the register state of the guest vCPU.
KVM has two different interfaces for accessing the state of the guest CPU. One interface updates 'normal' registers and one updates 'special' registers. The distinction between special and normal registers isn't very clear and is architecture dependent.
Definition at line 736 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::dumpIntRegs(), and X86KvmCPU::updateThreadContext().
void BaseKvmCPU::getSpecialRegisters (struct kvm_sregs & regs) const [protected]
Definition at line 750 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::dumpSpecRegs(), and X86KvmCPU::updateThreadContext().
void BaseKvmCPU::haltContext (ThreadID thread_num)
Definition at line 485 of file base.cc.
References suspendContext().
Tick BaseKvmCPU::handleKvmExit () [protected, virtual]
Main kvmRun exit handler, calls the relevant handleKvmExit* depending on exit type.
Returns:
Number of ticks spent servicing the exit request
Definition at line 884 of file base.cc.
References _kvmRun, _status, doMMIOAccess(), DPRINTF, dump(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitHypercall(), handleKvmExitIO(), handleKvmExitIRQWindowOpen(), handleKvmExitUnknown(), numHalt, numHypercalls, numIO, numMMIO, panic, Running, RunningService, RunningServiceCompletion, SimpleThread::suspend(), and thread.
Referenced by tick().
Tick BaseKvmCPU::handleKvmExitException () [protected, virtual]
An unhandled virtualization exception occured.
Some KVM virtualization drivers return unhandled exceptions to the user-space monitor. This interface is currently only used by the Intel VMX KVM driver.
Returns:
Number of ticks delay the next CPU tick
Definition at line 982 of file base.cc.
References _kvmRun, dump(), and panic.
Referenced by handleKvmExit().
Tick BaseKvmCPU::handleKvmExitFailEntry () [protected, virtual]
KVM failed to start the virtualized CPU.
The kvm_run data structure contains the hardware-specific error code.
Returns:
Number of ticks delay the next CPU tick
Definition at line 991 of file base.cc.
References _kvmRun, dump(), and panic.
Referenced by handleKvmExit().
Tick BaseKvmCPU::handleKvmExitHypercall () [protected, virtual]
The guest requested a monitor service using a hypercall.
Returns:
Number of ticks spent servicing the hypercall
Definition at line 960 of file base.cc.
References panic.
Referenced by handleKvmExit().
Tick BaseKvmCPU::handleKvmExitIO () [protected, virtual]
The guest performed a legacy IO request (out/inp on x86).
Returns:
Number of ticks spent servicing the IO request
Reimplemented in X86KvmCPU.
Definition at line 952 of file base.cc.
References _kvmRun, and panic.
Referenced by handleKvmExit().
Tick BaseKvmCPU::handleKvmExitIRQWindowOpen () [protected, virtual]
The guest exited because an interrupt window was requested.
The guest exited because an interrupt window was requested (request_interrupt_window in the kvm_run structure was set to 1 before calling kvmRun) and it is now ready to receive
Returns:
Number of ticks spent servicing the IRQ
Reimplemented in X86KvmCPU.
Definition at line 966 of file base.cc.
References warn.
Referenced by handleKvmExit().
Tick BaseKvmCPU::handleKvmExitUnknown () [protected, virtual]
An unknown architecture dependent error occurred when starting the vCPU.
The kvm_run data structure contains the hardware error code. The defaults behavior of this method just prints the HW error code and panics. Architecture dependent implementations may want to override this method to provide better, hardware-aware, error messages.
Returns:
Number of ticks delay the next CPU tick
Definition at line 974 of file base.cc.
References _kvmRun, dump(), and panic.
Referenced by handleKvmExit().
void BaseKvmCPU::init ()
Definition at line 109 of file base.cc.
References ThreadContext::contextId(), fatal, FullSystem, AlphaISA::initCPU(), ThreadContext::initMemProxies(), and tc.
void BaseKvmCPU::ioctlRun () [private]
Execute the KVM_RUN ioctl.
Definition at line 1223 of file base.cc.
References ioctl(), and panic.
Referenced by kvmRun().
void BaseKvmCPU::kick () const [inline]
Force an exit from KVM.
Send a signal to the thread owning this vCPU to get it to exit from KVM. Ignored if the vCPU is not executing.
Definition at line 122 of file base.hh.
References KVM_KICK_SIGNAL, and vcpuThread.
Referenced by kvmRun(), and wakeup().
Tick BaseKvmCPU::kvmRun (Tick ticks) [protected, virtual]
Request KVM to run the guest for a given number of ticks.
The method returns the approximate number of ticks executed.
Note:
The returned number of ticks can be both larger or smaller than the requested number of ticks. A smaller number can, for example, occur when the guest executes MMIO. A larger number is typically due to performance counter inaccuracies.
This method is virtual in order to allow implementations to check for architecture specific events (e.g., interrupts) before entering the VM.
It is the response of the caller (normally tick()) to make sure that the KVM state is synchronized and that the TC is invalidated after entering KVM.
This method does not normally cause any state transitions. However, if it may suspend the CPU by suspending the thread, which leads to a transition to the Idle state. In such a case, kvm must not be entered.
Parameters:
ticks Number of ticks to execute, set to 0 to exit immediately after finishing pending operations.
Returns:
Number of ticks executed (see note)
Reimplemented in ArmKvmCPU, BaseArmKvmCPU, and X86KvmCPU.
Definition at line 625 of file base.cc.
References ctrInsts, curEventQueue(), discardPendingSignal(), DPRINTF, flushCoalescedMMIO(), getHostCycles(), hostFactor, hwCycles, hwInstructions, ioctlRun(), kick(), KVM_KICK_SIGNAL, numInsts, numVMExits, numVMHalfEntries, perfControlledByTimer, PerfKvmCounter::read(), runTimer, PerfKvmCounter::start(), PerfKvmCounter::stop(), and X86ISA::system.
Referenced by kvmRunDrain(), X86KvmCPU::kvmRunWrapper(), and tick().
Tick BaseKvmCPU::kvmRunDrain () [protected, virtual]
Request the CPU to run until draining completes.
This function normally calls kvmRun(0) to make KVM finish pending MMIO operations. Architecures implementing archIsDrained() must override this method.
See also:
BaseKvmCPU::archIsDrained()
Returns:
Number of ticks executed
Reimplemented in X86KvmCPU.
Definition at line 606 of file base.cc.
References _status, kvmRun(), and RunningServiceCompletion.
Referenced by tick().
void BaseKvmCPU::regStats ()
Definition at line 204 of file base.cc.
References name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numCoalescedMMIO, numExitSignal, numHalt, numHypercalls, numInsts, numInterrupts, numIO, numMMIO, numVMExits, and numVMHalfEntries.
void BaseKvmCPU::serializeThread (std::ostream & os, ThreadID tid)
Definition at line 262 of file base.cc.
References _status, DPRINTF, DTRACE, dump(), Idle, SimpleThread::serialize(), and thread.
void BaseKvmCPU::setFPUState (const struct kvm_fpu & state) [protected]
Definition at line 771 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::updateKvmStateFPULegacy().
void BaseKvmCPU::setOneReg (uint64_t id, uint32_t value) [inline, protected]
Definition at line 350 of file base.hh.
References setOneReg().
Referenced by setOneReg().
void BaseKvmCPU::setOneReg (uint64_t id, uint64_t value) [inline, protected]
Definition at line 349 of file base.hh.
References setOneReg().
Referenced by setOneReg().
void BaseKvmCPU::setOneReg (uint64_t id, const void * addr) [protected]
Get/Set single register using the KVM_(SET|GET)_ONE_REG API.
Note:
The presence of this call depends on Kvm::capOneReg().
Definition at line 779 of file base.cc.
References ioctl(), and panic.
Referenced by ArmKvmCPU::onKvmExitHypercall(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCoProc(), ArmKvmCPU::updateKvmStateCore(), and ArmKvmCPU::updateKvmStateVFP().
void BaseKvmCPU::setRegisters (const struct kvm_regs & regs) [protected]
Definition at line 743 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::updateKvmStateRegs().
void BaseKvmCPU::setSignalMask (const sigset_t * mask) [protected]
Set the signal mask used in kvmRun().
This method allows the signal mask of the thread executing kvmRun() to be overridden inside the actual system call. This allows us to mask timer signals used to force KVM exits while in gem5.
The signal mask can be disabled by setting it to NULL.
Parameters:
mask Signals to mask
Definition at line 1040 of file base.cc.
References ioctl(), and panic.
Referenced by setupSignalHandler().
void BaseKvmCPU::setSpecialRegisters (const struct kvm_sregs & regs) [protected]
Definition at line 757 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::updateKvmStateSRegs().
void BaseKvmCPU::setupCounters () [private]
Setup hardware performance counters.
Definition at line 1169 of file base.cc.
References PerfKvmCounter::attach(), PerfKvmCounterConfig::disabled(), DPRINTF, PerfKvmCounterConfig::exclude_host(), PerfKvmCounterConfig::exclude_hv(), hwCycles, perfControlledByTimer, PerfKvmCounterConfig::pinned(), PerfKvmCounterConfig::samplePeriod(), setupInstCounter(), and PerfKvmCounterConfig::wakeupEvents().
Referenced by startupThread().
void BaseKvmCPU::setupInstCounter (uint64_t period = 0) [private]
Setup the guest instruction counter.
Setup the guest instruction counter and optionally request a signal every N instructions executed by the guest. This method will re-attach the counter if the counter has already been attached and its sampling settings have changed.
Parameters:
period Signal period, set to 0 to disable signaling.
Definition at line 1246 of file base.cc.
References activeInstPeriod, PerfKvmCounter::attach(), PerfKvmCounter::attached(), PerfKvmCounter::detach(), PerfKvmCounter::enableSignals(), PerfKvmCounterConfig::exclude_host(), PerfKvmCounterConfig::exclude_hv(), hwCycles, hwInstructions, KVM_KICK_SIGNAL, PerfKvmCounterConfig::samplePeriod(), and PerfKvmCounterConfig::wakeupEvents().
Referenced by setupCounters(), and setupInstStop().
void BaseKvmCPU::setupInstStop () [private]
Setup an instruction break if there is one pending.
Check if there are pending instruction breaks in the CPU's instruction event queue and schedule an instruction break using PerfEvent.
Note:
This method doesn't currently handle the main system instruction event queue.
Definition at line 1233 of file base.cc.
References ctrInsts, and setupInstCounter().
Referenced by tick().
void BaseKvmCPU::setupSignalHandler () [private]
Setup a signal handler to catch the timer signal used to switch back to the monitor.
Definition at line 1112 of file base.cc.
References KVM_KICK_SIGNAL, onKickSignal(), panic, and setSignalMask().
Referenced by startupThread().
void BaseKvmCPU::startup ()
Reimplemented in ArmKvmCPU, BaseArmKvmCPU, and X86KvmCPU.
Definition at line 124 of file base.cc.
References _kvmRun, Kvm::capCoalescedMMIO(), KvmVM::cpuStartup(), KvmVM::createVCPU(), curTick(), Kvm::getVCPUMMapSize(), inform, KvmVM::kvm, mmioRing, MipsISA::p, pageSize, panic, SimpleThread::startup(), startupThread(), thread, vcpuFD, vcpuID, vcpuMMapSize, and vm.
void BaseKvmCPU::startupThread () [private]
Thread-specific initialization.
Some KVM-related initialization requires us to know the TID of the thread that is going to execute our event queue. For example, when setting up timers, we need to know the TID of the thread executing in KVM in order to deliver the timer signal to that thread. This method is called as the first event in this SimObject's event queue.
See also:
startup
Definition at line 174 of file base.cc.
References hwCycles, KVM_KICK_SIGNAL, MipsISA::p, runTimer, setupCounters(), setupSignalHandler(), and vcpuThread.
Referenced by startup().
void BaseKvmCPU::suspendContext (ThreadID thread_num)
Definition at line 455 of file base.cc.
References _status, DPRINTF, Idle, Running, RunningServiceCompletion, Event::scheduled(), thread, and tickEvent.
Referenced by deallocateContext(), and haltContext().
void BaseKvmCPU::switchOut ()
Definition at line 374 of file base.cc.
References _status, DPRINTF, Idle, Event::scheduled(), and tickEvent.
void BaseKvmCPU::syncKvmState () [protected]
Update the KVM if the thread context is dirty.
Definition at line 872 of file base.cc.
References kvmStateDirty, threadContextDirty, and updateKvmState().
Referenced by tick().
void BaseKvmCPU::syncThreadContext () [protected]
Update a thread context if the KVM state is dirty with respect to the cached thread context.
Definition at line 860 of file base.cc.
References kvmStateDirty, threadContextDirty, and updateThreadContext().
Referenced by X86KvmCPU::deliverInterrupts(), doMMIOAccess(), drain(), getContext(), and X86KvmCPU::kvmRun().
void BaseKvmCPU::takeOverFrom (BaseCPU * cpu)
Definition at line 388 of file base.cc.
References _status, DPRINTF, Idle, Event::scheduled(), threadContextDirty, tickEvent, and updateKvmState().
void BaseKvmCPU::tick () [protected]
Execute the CPU until the next event in the main event queue or until the guest needs service from gem5.
Definition at line 520 of file base.cc.
References _kvmRun, _status, ctrInsts, curEventQueue(), curTick(), DPRINTF, drainManager, handleKvmExit(), Idle, kvmRun(), kvmRunDrain(), kvmStateDirty, numExitSignal, panic, Running, RunningService, RunningServiceCompletion, setupInstStop(), syncKvmState(), X86ISA::system, tickEvent, and tryDrain().
Counter BaseKvmCPU::totalInsts () const
Definition at line 501 of file base.cc.
References ctrInsts.
Counter BaseKvmCPU::totalOps () const
Definition at line 507 of file base.cc.
References ctrInsts, and hack_once.
bool BaseKvmCPU::tryDrain () [private]
Try to drain the CPU if a drain is pending.
Definition at line 1200 of file base.cc.
References _status, archIsDrained(), DPRINTF, drainManager, Idle, Running, and DrainManager::signalDrainDone().
Referenced by tick().
void BaseKvmCPU::unserializeThread (Checkpoint * cp, const std::string & section, ThreadID tid)
Definition at line 275 of file base.cc.
References _status, DPRINTF, Idle, thread, threadContextDirty, and SimpleThread::unserialize().
virtual void BaseKvmCPU::updateKvmState () [protected, pure virtual]
Update the KVM state from the current thread context.
The base CPU calls this method before starting the guest CPU when the contextDirty flag is set. The architecture dependent CPU implementation is expected to update all guest state (registers, special registers, and FPU state).
Implemented in ArmKvmCPU, ArmV8KvmCPU, and X86KvmCPU.
Referenced by syncKvmState(), and takeOverFrom().
virtual void BaseKvmCPU::updateThreadContext () [protected, pure virtual]
Update the current thread context with the KVM state.
The base CPU after the guest updates any of the KVM state. In practice, this happens after kvmRun is called. The architecture dependent code is expected to read the state of the guest CPU and update gem5's thread state.
Implemented in ArmKvmCPU, ArmV8KvmCPU, and X86KvmCPU.
Referenced by syncThreadContext().
void BaseKvmCPU::verifyMemoryMode () const
Definition at line 410 of file base.cc.
References fatal, and X86ISA::system.
Referenced by drainResume().
void BaseKvmCPU::wakeup ()
Reimplemented from BaseCPU.
Definition at line 419 of file base.cc.
References SimpleThread::activate(), DPRINTF, kick(), SimpleThread::status(), ThreadContext::Suspended, and thread.
Member Data Documentation
struct kvm_run* BaseKvmCPU::_kvmRun [read, private]
Pointer to the kvm_run structure used to communicate parameters with KVM.
Note:
This is the base pointer of the MMAPed KVM region. The first page contains the kvm_run structure. Subsequent pages may contain other data such as the MMIO ring buffer.
Definition at line 665 of file base.hh.
Referenced by getGuestData(), getKvmRunState(), handleKvmExit(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitIO(), handleKvmExitUnknown(), startup(), tick(), and ~BaseKvmCPU().
Status BaseKvmCPU::_status [protected]
CPU run state.
Definition at line 211 of file base.hh.
Referenced by activateContext(), drain(), drainResume(), handleKvmExit(), X86KvmCPU::kvmRun(), kvmRunDrain(), serializeThread(), suspendContext(), switchOut(), takeOverFrom(), tick(), tryDrain(), and unserializeThread().
uint64_t BaseKvmCPU::activeInstPeriod [private]
Currently active instruction count breakpoint.
Definition at line 705 of file base.hh.
Referenced by setupInstCounter().
Counter BaseKvmCPU::ctrInsts
Number of instructions executed by the CPU.
Definition at line 773 of file base.hh.
Referenced by kvmRun(), setupInstStop(), tick(), totalInsts(), and totalOps().
KVMCpuPort BaseKvmCPU::dataPort [protected]
Port for data requests.
Definition at line 572 of file base.hh.
Referenced by doMMIOAccess(), getDataPort(), and X86KvmCPU::handleKvmExitIO().
DrainManager* BaseKvmCPU::drainManager [private]
Drain manager to use when signaling drain completion.
This pointer is non-NULL when draining and NULL otherwise.
Definition at line 756 of file base.hh.
Referenced by drain(), tick(), and tryDrain().
float BaseKvmCPU::hostFactor [private]
Host factor as specified in the configuration.
Definition at line 749 of file base.hh.
Referenced by kvmRun().
PerfKvmCounter BaseKvmCPU::hwCycles [private]
Guest cycle counter.
This is the group leader of all performance counters measuring the guest system. It can be used in conjunction with the PerfKvmTimer (see perfControlledByTimer) to trigger exits from KVM.
Definition at line 715 of file base.hh.
Referenced by getHostCycles(), kvmRun(), setupCounters(), setupInstCounter(), and startupThread().
PerfKvmCounter BaseKvmCPU::hwInstructions [private]
Guest instruction counter.
This counter is typically only used to measure the number of instructions executed by the guest. However, it can also be used to trigger exits from KVM if the configuration script requests an exit after a certain number of instructions.
See also:
setupInstBreak
scheduleInstStop
Definition at line 728 of file base.hh.
Referenced by kvmRun(), and setupInstCounter().
KVMCpuPort BaseKvmCPU::instPort [protected]
Unused dummy port for the instruction interface.
Definition at line 575 of file base.hh.
Referenced by getInstPort().
bool BaseKvmCPU::kvmStateDirty [protected]
Is the KVM state dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
Definition at line 587 of file base.hh.
Referenced by syncKvmState(), syncThreadContext(), and tick().
struct kvm_coalesced_mmio_ring* BaseKvmCPU::mmioRing [read, private]
Coalesced MMIO ring buffer.
NULL if coalesced MMIO is not supported.
Definition at line 670 of file base.hh.
Referenced by flushCoalescedMMIO(), and startup().
Stats::Scalar BaseKvmCPU::numCoalescedMMIO
Definition at line 765 of file base.hh.
Referenced by flushCoalescedMMIO(), and regStats().
Stats::Scalar BaseKvmCPU::numExitSignal
Definition at line 763 of file base.hh.
Referenced by regStats(), and tick().
Stats::Scalar BaseKvmCPU::numHalt
Definition at line 767 of file base.hh.
Referenced by handleKvmExit(), and regStats().
Stats::Scalar BaseKvmCPU::numHypercalls
Definition at line 769 of file base.hh.
Referenced by handleKvmExit(), and regStats().
Stats::Scalar BaseKvmCPU::numInsts
Definition at line 760 of file base.hh.
Referenced by kvmRun(), and regStats().
Stats::Scalar BaseKvmCPU::numInterrupts
Definition at line 768 of file base.hh.
Referenced by kvmInterrupt(), kvmNonMaskableInterrupt(), and regStats().
Stats::Scalar BaseKvmCPU::numIO
Definition at line 766 of file base.hh.
Referenced by handleKvmExit(), and regStats().
Stats::Scalar BaseKvmCPU::numMMIO
Definition at line 764 of file base.hh.
Referenced by handleKvmExit(), and regStats().
Stats::Scalar BaseKvmCPU::numVMExits
Definition at line 761 of file base.hh.
Referenced by kvmRun(), and regStats().
Stats::Scalar BaseKvmCPU::numVMHalfEntries
Definition at line 762 of file base.hh.
Referenced by kvmRun(), and regStats().
const long BaseKvmCPU::pageSize [private]
Cached page size of the host.
Definition at line 672 of file base.hh.
Referenced by BaseKvmCPU(), and startup().
bool BaseKvmCPU::perfControlledByTimer [private]
Does the runTimer control the performance counters?
The run timer will automatically enable and disable performance counters if a PerfEvent-based timer is used to control KVM exits.
Definition at line 737 of file base.hh.
Referenced by kvmRun(), and setupCounters().
std::unique_ptr<BaseKvmTimer> BaseKvmCPU::runTimer [private]
Timer used to force execution into the monitor after a specified number of simulation tick equivalents have executed in the guest.
This counter generates the signal specified by KVM_TIMER_SIGNAL.
Definition at line 746 of file base.hh.
Referenced by kvmRun(), and startupThread().
ThreadContext* BaseKvmCPU::tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
Definition at line 142 of file base.hh.
Referenced by BaseKvmCPU(), X86KvmCPU::deliverInterrupts(), doMMIOAccess(), drainResume(), ArmKvmCPU::dumpKvmStateCoProc(), getContext(), X86KvmCPU::handleIOMiscReg32(), X86KvmCPU::handleKvmExitIO(), init(), X86KvmCPU::kvmRun(), X86KvmCPU::kvmRunWrapper(), ArmKvmCPU::onKvmExitHypercall(), X86KvmCPU::updateCPUID(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCoProc(), ArmKvmCPU::updateKvmStateCore(), X86KvmCPU::updateKvmStateFPULegacy(), X86KvmCPU::updateKvmStateFPUXSave(), X86KvmCPU::updateKvmStateMSRs(), X86KvmCPU::updateKvmStateRegs(), X86KvmCPU::updateKvmStateSRegs(), ArmKvmCPU::updateKvmStateVFP(), ArmKvmCPU::updateTCStateCoProc(), ArmKvmCPU::updateTCStateCore(), ArmKvmCPU::updateTCStateVFP(), X86KvmCPU::updateThreadContext(), ArmV8KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContextFPU(), X86KvmCPU::updateThreadContextMSRs(), X86KvmCPU::updateThreadContextRegs(), and X86KvmCPU::updateThreadContextXSave().
SimpleThread* BaseKvmCPU::thread
A cached copy of a thread's state in the form of a SimpleThread object.
Normally the actual thread state is stored in the KVM vCPU. If KVM has been running this copy is will be out of date. If we recently handled some events within gem5 that required state to be updated this could be the most up-to-date copy. When getContext() or updateThreadContext() is called this copy gets updated. The method syncThreadContext can be used within a KVM CPU to update the thread context if the KVM state is dirty (i.e., the vCPU has been run since the last update).
Definition at line 137 of file base.hh.
Referenced by activateContext(), BaseKvmCPU(), X86KvmCPU::deliverInterrupts(), doMMIOAccess(), handleKvmExit(), serializeThread(), startup(), suspendContext(), unserializeThread(), and wakeup().
bool BaseKvmCPU::threadContextDirty [protected]
Is the gem5 context dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
Definition at line 581 of file base.hh.
Referenced by X86KvmCPU::deliverInterrupts(), doMMIOAccess(), syncKvmState(), syncThreadContext(), takeOverFrom(), and unserializeThread().
TickEvent BaseKvmCPU::tickEvent [private]
Definition at line 674 of file base.hh.
Referenced by activateContext(), drain(), drainResume(), suspendContext(), switchOut(), takeOverFrom(), and tick().
int BaseKvmCPU::vcpuFD [private]
KVM vCPU file descriptor.
Definition at line 654 of file base.hh.
Referenced by ioctl(), startup(), and ~BaseKvmCPU().
const long BaseKvmCPU::vcpuID [protected]
KVM internal ID of the vCPU.
Definition at line 590 of file base.hh.
Referenced by BaseArmKvmCPU::kvmRun(), ArmKvmCPU::kvmRun(), and startup().
int BaseKvmCPU::vcpuMMapSize [private]
Size of MMAPed kvm_run area.
Definition at line 656 of file base.hh.
Referenced by startup(), and ~BaseKvmCPU().
pthread_t BaseKvmCPU::vcpuThread [protected]
ID of the vCPU thread.
Definition at line 593 of file base.hh.
Referenced by kick(), and startupThread().
KvmVM& BaseKvmCPU::vm
Definition at line 144 of file base.hh.
Referenced by doMMIOAccess(), X86KvmCPU::dumpMSRs(), X86KvmCPU::getMsrIntersection(), X86KvmCPU::handleKvmExitIO(), BaseArmKvmCPU::kvmRun(), ArmKvmCPU::kvmRun(), startup(), BaseArmKvmCPU::startup(), and X86KvmCPU::X86KvmCPU().
The documentation for this class was generated from the following files:
cpu/kvm/base.hh
cpu/kvm/base.cc