gem5: Ticked::ClockEvent Class Reference
Ticked::ClockEvent Class Reference
An event to call process periodically.
#include <ticked_object.hh>
Public Member Functions
ClockEvent (Ticked &owner_, Priority priority)
void process ()
Evaluate and reschedule.
Public Attributes
Ticked & owner
Detailed Description
An event to call process periodically.
Definition at line 63 of file ticked_object.hh.
Constructor & Destructor Documentation
Ticked::ClockEvent::ClockEvent (Ticked & owner_, Priority priority) [inline]
Definition at line 68 of file ticked_object.hh.
Member Function Documentation
void Ticked::ClockEvent::process () [inline, virtual]
Evaluate and reschedule.
Implements Event.
Definition at line 75 of file ticked_object.hh.
References ClockedObject::clockEdge(), Ticked::countCycles(), Ticked::evaluate(), Ticked::numCycles, Ticked::object, owner, Ticked::running, EventManager::schedule(), and Ticked::tickCycles.
Member Data Documentation
Ticked& Ticked::ClockEvent::owner
Definition at line 66 of file ticked_object.hh.
Referenced by process().
The documentation for this class was generated from the following file:
sim/ticked_object.hh