gem5: WireBuffer Class Reference
WireBuffer Class Reference
#include <WireBuffer.hh>
Public Types
typedef RubyWireBufferParams Params
Public Member Functions
WireBuffer (const Params *p)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
~WireBuffer ()
void wakeup ()
void setConsumer (Consumer *consumer_ptr)
Consumer * getConsumer ()
void setDescription (const std::string &name)
std::string getDescription ()
void enqueue (MsgPtr message, Cycles latency)
void dequeue ()
const Message * peek ()
MessageBufferNode peekNode ()
void recycle ()
bool isReady ()
bool areNSlotsAvailable (int n)
void print (std::ostream &out) const
Public Attributes
uint64_t m_msg_counter
Private Member Functions
WireBuffer (const WireBuffer &obj)
WireBuffer & operator= (const WireBuffer &obj)
Private Attributes
Consumer * m_consumer_ptr
std::string m_description
std::vector< MessageBufferNode > m_message_queue
Detailed Description
Definition at line 56 of file WireBuffer.hh.
Member Typedef Documentation
typedef RubyWireBufferParams WireBuffer::Params
Reimplemented from SimObject.
Definition at line 59 of file WireBuffer.hh.
Constructor & Destructor Documentation
WireBuffer::WireBuffer (const Params * p)
Definition at line 57 of file WireBuffer.cc.
References m_msg_counter.
WireBuffer::~WireBuffer ()
Definition at line 68 of file WireBuffer.cc.
WireBuffer::WireBuffer (const WireBuffer & obj) [private]
Member Function Documentation
bool WireBuffer::areNSlotsAvailable (int n) [inline]
Definition at line 81 of file WireBuffer.hh.
void WireBuffer::dequeue ()
Definition at line 91 of file WireBuffer.cc.
References isReady(), and m_message_queue.
void WireBuffer::enqueue (MsgPtr message, Cycles latency)
Definition at line 73 of file WireBuffer.cc.
References ClockedObject::clockPeriod(), ClockedObject::curCycle(), g_system_ptr, m_consumer_ptr, m_message_queue, m_msg_counter, and panic.
Consumer* WireBuffer::getConsumer () [inline]
Definition at line 71 of file WireBuffer.hh.
References m_consumer_ptr.
std::string WireBuffer::getDescription () [inline]
Definition at line 73 of file WireBuffer.hh.
References m_description.
void WireBuffer::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 64 of file WireBuffer.cc.
bool WireBuffer::isReady ()
Definition at line 137 of file WireBuffer.cc.
References ClockedObject::curCycle(), g_system_ptr, and m_message_queue.
Referenced by dequeue(), peekNode(), and recycle().
WireBuffer& WireBuffer::operator= (const WireBuffer & obj) [private]
const Message * WireBuffer::peek ()
Definition at line 100 of file WireBuffer.cc.
References MessageBufferNode::m_msgptr, and peekNode().
MessageBufferNode WireBuffer::peekNode ()
Definition at line 109 of file WireBuffer.cc.
References isReady(), and m_message_queue.
Referenced by peek().
void WireBuffer::print (std::ostream & out) const
Referenced by operator<<().
void WireBuffer::recycle ()
Definition at line 117 of file WireBuffer.cc.
References ClockedObject::clockPeriod(), ClockedObject::curCycle(), g_system_ptr, isReady(), m_consumer_ptr, m_message_queue, and MessageBufferNode::m_time.
void WireBuffer::setConsumer (Consumer * consumer_ptr) [inline]
Definition at line 67 of file WireBuffer.hh.
References m_consumer_ptr.
void WireBuffer::setDescription (const std::string & name) [inline]
Definition at line 72 of file WireBuffer.hh.
References m_description.
void WireBuffer::wakeup ()
Definition at line 149 of file WireBuffer.cc.
Member Data Documentation
Consumer* WireBuffer::m_consumer_ptr [private]
Definition at line 92 of file WireBuffer.hh.
Referenced by enqueue(), getConsumer(), recycle(), and setConsumer().
std::string WireBuffer::m_description [private]
Definition at line 93 of file WireBuffer.hh.
Referenced by getDescription(), and setDescription().
std::vector<MessageBufferNode> WireBuffer::m_message_queue [private]
Definition at line 96 of file WireBuffer.hh.
Referenced by dequeue(), enqueue(), isReady(), peekNode(), and recycle().
uint64_t WireBuffer::m_msg_counter
Definition at line 84 of file WireBuffer.hh.
Referenced by enqueue(), and WireBuffer().
The documentation for this class was generated from the following files:
mem/ruby/structures/WireBuffer.hh
mem/ruby/structures/WireBuffer.cc