gem5: X86ISA::X86LiveProcess Class Reference
X86ISA::X86LiveProcess Class Reference
#include <process.hh>
Public Member Functions
Addr gdtStart ()
Addr gdtSize ()
SyscallDesc * getDesc (int callnum)
void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)
Protected Member Functions
X86LiveProcess (LiveProcessParams *params, ObjectFile *objFile, SyscallDesc *_syscallDescs, int _numSyscallDescs)
template<class IntType >
void argsInit (int pageSize, std::vector< AuxVector< IntType > > extraAuxvs)
Protected Attributes
Addr _gdtStart
Addr _gdtSize
SyscallDesc * syscallDescs
const int numSyscallDescs
Detailed Description
Definition at line 58 of file process.hh.
Constructor & Destructor Documentation
X86LiveProcess::X86LiveProcess (LiveProcessParams * params, ObjectFile * objFile, SyscallDesc * _syscallDescs, int _numSyscallDescs) [protected]
Definition at line 86 of file process.cc.
References Process::brk_point, ObjectFile::bssSize(), ObjectFile::dataBase(), ObjectFile::dataSize(), X86ISA::PageBytes, and roundUp().
Member Function Documentation
template<class IntType > void X86LiveProcess::argsInit (int pageSize, std::vector< AuxVector< IntType > > extraAuxvs) [inline, protected]
Definition at line 729 of file process.cc.
References Process::allocateMem(), LiveProcess::argv, Process::contextIds, copyStringArray(), DPRINTF, LiveProcess::egid(), ObjectFile::entryPoint(), LiveProcess::envp, LiveProcess::euid(), System::getThreadContext(), LiveProcess::gid(), BigEndianGuest::htog(), ArmISA::i, Process::initVirtMem, ObjectFile::loadSections(), LiveProcess::M5_AT_BASE, LiveProcess::M5_AT_CLKTCK, LiveProcess::M5_AT_EGID, LiveProcess::M5_AT_ENTRY, LiveProcess::M5_AT_EUID, LiveProcess::M5_AT_EXECFN, LiveProcess::M5_AT_FLAGS, LiveProcess::M5_AT_GID, LiveProcess::M5_AT_HWCAP, LiveProcess::M5_AT_PAGESZ, LiveProcess::M5_AT_PHDR, LiveProcess::M5_AT_PHENT, LiveProcess::M5_AT_PHNUM, LiveProcess::M5_AT_PLATFORM, LiveProcess::M5_AT_RANDOM, LiveProcess::M5_AT_SECURE, LiveProcess::M5_AT_UID, LiveProcess::objFile, X86ISA::PageBytes, ThreadContext::pcState(), ElfObject::programHeaderCount(), ElfObject::programHeaderSize(), ElfObject::programHeaderTable(), roundDown(), roundUp(), ThreadContext::setIntReg(), Process::stack_base, Process::stack_min, Process::stack_size, X86ISA::StackPointerReg, Process::system, ArmISA::tc, LiveProcess::uid(), SETranslatingPortProxy::writeBlob(), SETranslatingPortProxy::writeString(), and X86ISA::x.
Addr X86ISA::X86LiveProcess::gdtSize () [inline]
Definition at line 78 of file process.hh.
References _gdtSize.
Referenced by setThreadArea32Func().
Addr X86ISA::X86LiveProcess::gdtStart () [inline]
Definition at line 75 of file process.hh.
References _gdtStart.
Referenced by setThreadArea32Func().
SyscallDesc * X86LiveProcess::getDesc (int callnum) [virtual]
Implements LiveProcess.
Definition at line 157 of file process.cc.
References numSyscallDescs, and syscallDescs.
void X86LiveProcess::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) [virtual]
Implements LiveProcess.
Definition at line 1032 of file process.cc.
References SyscallReturn::encodedValue(), and ThreadContext::setIntReg().
Member Data Documentation
Addr X86ISA::X86LiveProcess::_gdtSize [protected]
Definition at line 62 of file process.hh.
Referenced by gdtSize(), X86ISA::I386LiveProcess::I386LiveProcess(), and X86ISA::I386LiveProcess::initState().
Addr X86ISA::X86LiveProcess::_gdtStart [protected]
Definition at line 61 of file process.hh.
Referenced by gdtStart(), X86ISA::I386LiveProcess::I386LiveProcess(), and X86ISA::I386LiveProcess::initState().
const int X86ISA::X86LiveProcess::numSyscallDescs [protected]
Definition at line 65 of file process.hh.
Referenced by getDesc().
SyscallDesc* X86ISA::X86LiveProcess::syscallDescs [protected]
Definition at line 64 of file process.hh.
Referenced by getDesc().
The documentation for this class was generated from the following files:
arch/x86/process.hh
arch/x86/process.cc