gem5: AddressMapper Class Reference
AddressMapper Class Reference
#include <addr_mapper.hh>
Public Member Functions
AddressMapper ()
void put_addr (Addr addr)
void order_by_firsttouch ()
void order_by_spacefill ()
void erase (Addr addr)
void clear ()
Private Attributes
AddressSet addr_set
int ordered_addr_max
Detailed Description
Definition at line 6 of file addr_mapper.hh.
Constructor & Destructor Documentation
AddressMapper::AddressMapper () [inline]
Definition at line 13 of file addr_mapper.hh.
References addr_set, clear(), and ordered_addr_max.
Member Function Documentation
void AddressMapper::clear () [inline]
Definition at line 40 of file addr_mapper.hh.
References addr_set, and ordered_addr_max.
Referenced by AddressMapper(), ReuseDistanceAnalyzer::reset(), and AddressTracer::reset().
void AddressMapper::erase (Addr addr) [inline]
Reimplemented from AddressCounterTable.
Definition at line 35 of file addr_mapper.hh.
References addr_set, and AddressSet::erase().
void AddressMapper::order_by_firsttouch () [inline]
Definition at line 26 of file addr_mapper.hh.
Referenced by AddressTracer::dump().
void AddressMapper::order_by_spacefill () [inline]
Definition at line 28 of file addr_mapper.hh.
References addr_set.
Referenced by AddressTracer::dump(), and ReuseDistanceAnalyzer::output().
void AddressMapper::put_addr (Addr addr) [inline]
Definition at line 19 of file addr_mapper.hh.
References addr_set, AddressCounterTable::exists(), AddressCounterTable::insert(), and ordered_addr_max.
Referenced by ReuseDistanceAnalyzer::access(), AddressTracer::access(), and AddressTracer::insert().
Member Data Documentation
AddressSet AddressMapper::addr_set [private]
Definition at line 8 of file addr_mapper.hh.
Referenced by AddressMapper(), clear(), erase(), order_by_spacefill(), and put_addr().
int AddressMapper::ordered_addr_max [private]
Definition at line 9 of file addr_mapper.hh.
Referenced by AddressMapper(), clear(), and put_addr().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/addr_mapper.hh