gem5: VirtIO9PDiod Class Reference
VirtIO9PDiod Class Reference
VirtIO 9p proxy that communicates with the diod 9p server using pipes.
#include <fs9p.hh>
Classes
class DiodDataEvent
Public Types
typedef VirtIO9PDiodParams Params
Public Member Functions
VirtIO9PDiod (Params *params)
virtual ~VirtIO9PDiod ()
void startup ()
startup() is the final initialization call before simulation.
Protected Member Functions
void startDiod ()
Start diod and setup the communication pipes.
ssize_t read (uint8_t *data, size_t len)
Read data from the server behind the proxy.
ssize_t write (const uint8_t *data, size_t len)
Write data to the server behind the proxy.
Private Attributes
int fd_to_diod
fd for data pipe going to diod (write end)
int fd_from_diod
fd for data pipe coming from diod (read end)
std::unique_ptr< DiodDataEvent > dataEvent
int diod_pid
PID of diod process.
Detailed Description
VirtIO 9p proxy that communicates with the diod 9p server using pipes.
Definition at line 279 of file fs9p.hh.
Member Typedef Documentation
typedef VirtIO9PDiodParams VirtIO9PDiod::Params
Reimplemented from VirtIO9PProxy.
Definition at line 282 of file fs9p.hh.
Constructor & Destructor Documentation
VirtIO9PDiod::VirtIO9PDiod (Params * params)
Definition at line 292 of file fs9p.cc.
VirtIO9PDiod::~VirtIO9PDiod () [virtual]
Definition at line 298 of file fs9p.cc.
Member Function Documentation
ssize_t VirtIO9PDiod::read (uint8_t * data, size_t len) [protected, virtual]
Read data from the server behind the proxy.
Note:
This method may return read fewer than len bytes.
Parameters:
data Memory location to store results in.
len Maximum length to read.
Returns:
Number of bytes read, -errno on failure.
Implements VirtIO9PProxy.
Definition at line 359 of file fs9p.cc.
References fd_from_diod.
void VirtIO9PDiod::startDiod () [protected]
Start diod and setup the communication pipes.
Definition at line 311 of file fs9p.cc.
References diod_pid, fd_from_diod, fd_to_diod, MipsISA::p, panic, and SimObject::params().
Referenced by startup().
void VirtIO9PDiod::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 303 of file fs9p.cc.
References dataEvent, fd_from_diod, pollQueue, PollQueue::schedule(), and startDiod().
ssize_t VirtIO9PDiod::write (const uint8_t * data, size_t len) [protected, virtual]
Write data to the server behind the proxy.
Note:
This method may return write fewer than len bytes.
Parameters:
data Pointer to data to write.
len Maximum length to write.
Returns:
Number of bytes written, -errno on failure.
Implements VirtIO9PProxy.
Definition at line 367 of file fs9p.cc.
References fd_to_diod.
Member Data Documentation
std::unique_ptr<DiodDataEvent> VirtIO9PDiod::dataEvent [private]
Definition at line 317 of file fs9p.hh.
Referenced by startup().
int VirtIO9PDiod::diod_pid [private]
PID of diod process.
Definition at line 320 of file fs9p.hh.
Referenced by startDiod().
int VirtIO9PDiod::fd_from_diod [private]
fd for data pipe coming from diod (read end)
Definition at line 315 of file fs9p.hh.
Referenced by read(), startDiod(), and startup().
int VirtIO9PDiod::fd_to_diod [private]
fd for data pipe going to diod (write end)
Definition at line 313 of file fs9p.hh.
Referenced by startDiod(), and write().
The documentation for this class was generated from the following files:
dev/virtio/fs9p.hh
dev/virtio/fs9p.cc