gem5: AtomicSimpleCPU::AtomicCPUDPort Class Reference
AtomicSimpleCPU::AtomicCPUDPort Class Reference
Public Member Functions
AtomicCPUDPort (const std::string &_name, BaseSimpleCPU *_cpu)
bool isSnooping () const
Determine if this master port is snooping or not.
Public Attributes
Addr cacheBlockMask
Protected Member Functions
virtual Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from the slave port.
virtual void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
Protected Attributes
BaseSimpleCPU * cpu
Detailed Description
Definition at line 152 of file atomic.hh.
Constructor & Destructor Documentation
AtomicSimpleCPU::AtomicCPUDPort::AtomicCPUDPort (const std::string & _name, BaseSimpleCPU * _cpu) [inline]
Definition at line 157 of file atomic.hh.
References cacheBlockMask, and cpu.
Member Function Documentation
bool AtomicSimpleCPU::AtomicCPUDPort::isSnooping () const [inline, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented from MasterPort.
Definition at line 163 of file atomic.hh.
Tick AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop (PacketPtr pkt) [protected, virtual]
Receive an atomic snoop request packet from the slave port.
Reimplemented from AtomicSimpleCPU::AtomicCPUPort.
Definition at line 274 of file atomic.cc.
References cacheBlockMask, Packet::cmdString(), cpu, DPRINTF, Packet::getAddr(), AlphaISA::handleLockedSnoop(), Packet::isInvalidate(), Port::owner, and BaseSimpleCPU::wakeup().
void AtomicSimpleCPU::AtomicCPUDPort::recvFunctionalSnoop (PacketPtr pkt) [protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 296 of file atomic.cc.
References cacheBlockMask, Packet::cmdString(), cpu, DPRINTF, Packet::getAddr(), AlphaISA::handleLockedSnoop(), Packet::isInvalidate(), Port::owner, and BaseSimpleCPU::wakeup().
Member Data Documentation
Addr AtomicSimpleCPU::AtomicCPUDPort::cacheBlockMask
Definition at line 165 of file atomic.hh.
Referenced by AtomicCPUDPort(), recvAtomicSnoop(), recvFunctionalSnoop(), and AtomicSimpleCPU::writeMem().
BaseSimpleCPU* AtomicSimpleCPU::AtomicCPUDPort::cpu [protected]
Definition at line 167 of file atomic.hh.
Referenced by AtomicCPUDPort(), recvAtomicSnoop(), and recvFunctionalSnoop().
The documentation for this class was generated from the following files:
cpu/simple/atomic.hh
cpu/simple/atomic.cc