gem5: SimpleTrace Class Reference
SimpleTrace Class Reference
#include <simple_trace.hh>
Public Member Functions
SimpleTrace (const SimpleTraceParams *params)
void regProbeListeners ()
Register the probe listeners.
const std::string name () const
Returns the name of the trace.
Private Member Functions
void traceFetch (const O3CPUImpl::DynInstPtr &dynInst)
void traceCommit (const O3CPUImpl::DynInstPtr &dynInst)
Detailed Description
Definition at line 54 of file simple_trace.hh.
Constructor & Destructor Documentation
SimpleTrace::SimpleTrace (const SimpleTraceParams * params) [inline]
Definition at line 57 of file simple_trace.hh.
Member Function Documentation
const std::string SimpleTrace::name () const [inline, virtual]
Returns the name of the trace.
Reimplemented from SimObject.
Definition at line 66 of file simple_trace.hh.
Referenced by traceCommit(), and traceFetch().
void SimpleTrace::regProbeListeners () [virtual]
Register the probe listeners.
Reimplemented from SimObject.
Definition at line 58 of file simple_trace.cc.
References ProbeListenerObject::listeners, traceCommit(), and traceFetch().
void SimpleTrace::traceCommit (const O3CPUImpl::DynInstPtr & dynInst) [private]
Definition at line 44 of file simple_trace.cc.
References DPRINTFR, and name().
Referenced by regProbeListeners().
void SimpleTrace::traceFetch (const O3CPUImpl::DynInstPtr & dynInst) [private]
Definition at line 51 of file simple_trace.cc.
References DPRINTFR, and name().
Referenced by regProbeListeners().
The documentation for this class was generated from the following files:
cpu/o3/probe/simple_trace.hh
cpu/o3/probe/simple_trace.cc