gem5: X86ISA::X86_64LiveProcess Class Reference
X86ISA::X86_64LiveProcess Class Reference
#include <process.hh>
Classes
class VSyscallPage
Public Member Functions
void argsInit (int intSize, int pageSize)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
X86ISA::IntReg getSyscallArg (ThreadContext *tc, int &i)
void setSyscallArg (ThreadContext *tc, int i, X86ISA::IntReg val)
Protected Member Functions
X86_64LiveProcess (LiveProcessParams *params, ObjectFile *objFile, SyscallDesc *_syscallDescs, int _numSyscallDescs)
Protected Attributes
VSyscallPage vsyscallPage
Detailed Description
Definition at line 86 of file process.hh.
Constructor & Destructor Documentation
X86_64LiveProcess::X86_64LiveProcess (LiveProcessParams * params, ObjectFile * objFile, SyscallDesc * _syscallDescs, int _numSyscallDescs) [protected]
Definition at line 95 of file process.cc.
References X86ISA::X86_64LiveProcess::VSyscallPage::base, Process::mmap_end, Process::mmap_start, Process::next_thread_stack_base, X86ISA::PageBytes, X86ISA::X86_64LiveProcess::VSyscallPage::size, Process::stack_base, ULL, X86ISA::X86_64LiveProcess::VSyscallPage::vgettimeofdayOffset, vsyscallPage, and X86ISA::X86_64LiveProcess::VSyscallPage::vtimeOffset.
Member Function Documentation
void X86_64LiveProcess::argsInit (int intSize, int pageSize)
Definition at line 1011 of file process.cc.
References X86ISA::X86_64LiveProcess::VSyscallPage::base, X86ISA::M5_AT_SYSINFO_EHDR, and vsyscallPage.
Referenced by initState().
X86ISA::IntReg X86_64LiveProcess::getSyscallArg (ThreadContext * tc, int & i) [virtual]
Implements LiveProcess.
Definition at line 1038 of file process.cc.
References ArgumentReg, NumArgumentRegs, and ThreadContext::readIntReg().
void X86_64LiveProcess::initState () [virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
setting Interrupt Stack Table
Page fault handler
Reimplemented from Process.
Definition at line 165 of file process.cc.
References Process::allocateMem(), argsInit(), X86ISA::X86_64LiveProcess::VSyscallPage::base, bits(), Process::contextIds, MipsISA::ds, X86ISA::GDTPhysAddr, X86ISA::GDTVirtAddr, System::getThreadContext(), ArmISA::i, X86ISA::IDTPhysAddr, X86ISA::IDTVirtAddr, Process::initVirtMem, X86ISA::installSegDesc(), X86ISA::ISTPhysAddr, X86ISA::ISTVirtAddr, Process::kvmInSE, MultiLevelPageTable< ISAOps >::map(), X86ISA::MISCREG_APIC_BASE, X86ISA::MISCREG_CR0, X86ISA::MISCREG_CR2, X86ISA::MISCREG_CR3, X86ISA::MISCREG_CR4, X86ISA::MISCREG_CR8, X86ISA::MISCREG_CS, X86ISA::MISCREG_CS_ATTR, X86ISA::MISCREG_DS, X86ISA::MISCREG_EFER, X86ISA::MISCREG_ES, X86ISA::MISCREG_FS, X86ISA::MISCREG_GS, X86ISA::MISCREG_IDTR_BASE, X86ISA::MISCREG_IDTR_LIMIT, X86ISA::MISCREG_LSTAR, X86ISA::MISCREG_MXCSR, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_EFF_BASE(), X86ISA::MISCREG_SF_MASK, X86ISA::MISCREG_SS, X86ISA::MISCREG_STAR, X86ISA::MISCREG_TR, X86ISA::MISCREG_TR_ATTR, X86ISA::MISCREG_TR_BASE, X86ISA::MISCREG_TR_EFF_BASE, X86ISA::MISCREG_TR_LIMIT, X86ISA::MISCREG_TSG_BASE, X86ISA::MISCREG_TSG_LIMIT, X86ISA::MISCREG_TSL, X86ISA::MISCREG_TSL_ATTR, X86ISA::MMIORegionPhysAddr, X86ISA::MMIORegionVirtAddr, X86ISA::NUM_SEGMENTREGS, X86ISA::PageBytes, X86ISA::pageTablePhysAddr, X86ISA::PFHandlerPhysAddr, X86ISA::PFHandlerVirtAddr, System::physProxy, Process::pTable, X86ISA::seg, X86ISA::SEGMENT_REG_CS, X86ISA::SEGMENT_REG_DS, X86ISA::SEGMENT_REG_ES, X86ISA::SEGMENT_REG_FS, X86ISA::SEGMENT_REG_GS, X86ISA::SEGMENT_REG_SS, ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), X86ISA::X86_64LiveProcess::VSyscallPage::size, X86ISA::syscallCodePhysAddr, X86ISA::syscallCodeVirtAddr, Process::system, ArmISA::tc, X86ISA::TSSPhysAddr, X86ISA::TSSVirtAddr, X86ISA::X86_64LiveProcess::VSyscallPage::vgettimeofdayOffset, vsyscallPage, X86ISA::X86_64LiveProcess::VSyscallPage::vtimeOffset, PortProxy::writeBlob(), and SETranslatingPortProxy::writeBlob().
void X86_64LiveProcess::setSyscallArg (ThreadContext * tc, int i, X86ISA::IntReg val)
Definition at line 1045 of file process.cc.
References ArgumentReg, NumArgumentRegs, and ThreadContext::setIntReg().
Member Data Documentation
VSyscallPage X86ISA::X86_64LiveProcess::vsyscallPage [protected]
Definition at line 100 of file process.hh.
Referenced by argsInit(), initState(), and X86_64LiveProcess().
The documentation for this class was generated from the following files:
arch/x86/process.hh
arch/x86/process.cc