gem5: MipsISA::ISA Class Reference
MipsISA::ISA Class Reference
#include <isa.hh>
Classes
class CP0Event
Public Types
enum CP0EventType { UpdateCP0 }
typedef ISA CP0
typedef MipsISAParams Params
Public Member Functions
void clear ()
void configCP ()
unsigned getVPENum (ThreadID tid) const
void updateCP0ReadView (int misc_reg, ThreadID tid)
MiscReg readMiscRegNoEffect (int misc_reg, ThreadID tid=0) const
MiscReg readMiscReg (int misc_reg, ThreadContext *tc, ThreadID tid=0)
MiscReg filterCP0Write (int misc_reg, int reg_sel, const MiscReg &val)
This method doesn't need to adjust the Control Register Offset since it has already been done in the calling method (setRegWithEffect).
void setRegMask (int misc_reg, const MiscReg &val, ThreadID tid=0)
void setMiscRegNoEffect (int misc_reg, const MiscReg &val, ThreadID tid=0)
void setMiscReg (int misc_reg, const MiscReg &val, ThreadContext *tc, ThreadID tid=0)
void scheduleCP0Update (BaseCPU *cpu, Cycles delay=Cycles(0))
void updateCPU (BaseCPU *cpu)
void startup (ThreadContext *tc)
const Params * params () const
ISA (Params *p)
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
Public Attributes
bool cp0Updated
std::queue< CP0Event * > cp0EventRemoveList
Static Public Attributes
static std::string miscRegNames [NumMiscRegs]
Protected Types
enum BankType { perProcessor, perThreadContext, perVirtProcessor }
Protected Attributes
uint8_t numThreads
uint8_t numVpes
std::vector< std::vector
< MiscReg > > miscRegFile
std::vector< std::vector
< MiscReg > > miscRegFile_WriteMask
std::vector< BankType > bankType
Detailed Description
Definition at line 51 of file isa.hh.
Member Typedef Documentation
typedef ISA MipsISA::ISA::CP0
Definition at line 55 of file isa.hh.
typedef MipsISAParams MipsISA::ISA::Params
Reimplemented from SimObject.
Definition at line 57 of file isa.hh.
Member Enumeration Documentation
enum MipsISA::ISA::BankType [protected]
Enumerator:
perProcessor
perThreadContext
perVirtProcessor
Definition at line 64 of file isa.hh.
enum MipsISA::ISA::CP0EventType
Enumerator:
UpdateCP0
Definition at line 116 of file isa.hh.
Constructor & Destructor Documentation
MipsISA::ISA::ISA (Params * p)
Definition at line 91 of file isa.cc.
References bankType, clear(), MipsISA::i, MipsISA::MISCREG_DEBUG, MipsISA::MISCREG_EBASE, MipsISA::MISCREG_LLADDR, MipsISA::MISCREG_SRS_CONF0, MipsISA::MISCREG_SRS_CONF1, MipsISA::MISCREG_SRS_CONF2, MipsISA::MISCREG_SRS_CONF3, MipsISA::MISCREG_SRS_CONF4, MipsISA::MISCREG_STATUS, MipsISA::MISCREG_TC_BIND, MipsISA::MISCREG_TC_CONTEXT, MipsISA::MISCREG_TC_HALT, MipsISA::MISCREG_TC_RESTART, MipsISA::MISCREG_TC_SCHEDULE, MipsISA::MISCREG_TC_SCHEFBACK, MipsISA::MISCREG_TC_STATUS, MipsISA::MISCREG_VPE_CONF0, MipsISA::MISCREG_VPE_CONF1, MipsISA::MISCREG_VPE_CONTROL, MipsISA::MISCREG_VPE_OPT, MipsISA::MISCREG_VPE_SCHEDULE, MipsISA::MISCREG_VPE_SCHEFBACK, MipsISA::MISCREG_YQMASK, miscRegFile, miscRegFile_WriteMask, MipsISA::NumMiscRegs, numThreads, numVpes, perProcessor, perThreadContext, and perVirtProcessor.
Member Function Documentation
void MipsISA::ISA::clear ()
Definition at line 151 of file isa.cc.
References MipsISA::i, ArmISA::j, MipsISA::k, miscRegFile, miscRegFile_WriteMask, and MipsISA::NumMiscRegs.
Referenced by ISA().
void MipsISA::ISA::configCP ()
Definition at line 164 of file isa.cc.
References MipsISA::CoreSpecific::CP0_Config1_C2, MipsISA::CoreSpecific::CP0_Config1_DA, MipsISA::CoreSpecific::CP0_Config1_DL, MipsISA::CoreSpecific::CP0_Config1_DS, MipsISA::CoreSpecific::CP0_Config1_EP, MipsISA::CoreSpecific::CP0_Config1_FP, MipsISA::CoreSpecific::CP0_Config1_IA, MipsISA::CoreSpecific::CP0_Config1_IL, MipsISA::CoreSpecific::CP0_Config1_IS, MipsISA::CoreSpecific::CP0_Config1_M, MipsISA::CoreSpecific::CP0_Config1_MD, MipsISA::CoreSpecific::CP0_Config1_MMU, MipsISA::CoreSpecific::CP0_Config1_PC, MipsISA::CoreSpecific::CP0_Config1_WR, MipsISA::CoreSpecific::CP0_Config2_M, MipsISA::CoreSpecific::CP0_Config2_SA, MipsISA::CoreSpecific::CP0_Config2_SL, MipsISA::CoreSpecific::CP0_Config2_SS, MipsISA::CoreSpecific::CP0_Config2_SU, MipsISA::CoreSpecific::CP0_Config2_TA, MipsISA::CoreSpecific::CP0_Config2_TL, MipsISA::CoreSpecific::CP0_Config2_TS, MipsISA::CoreSpecific::CP0_Config2_TU, MipsISA::CoreSpecific::CP0_Config3_DSPP, MipsISA::CoreSpecific::CP0_Config3_LPA, MipsISA::CoreSpecific::CP0_Config3_MT, MipsISA::CoreSpecific::CP0_Config3_SM, MipsISA::CoreSpecific::CP0_Config3_SP, MipsISA::CoreSpecific::CP0_Config3_TL, MipsISA::CoreSpecific::CP0_Config3_VEIC, MipsISA::CoreSpecific::CP0_Config3_VInt, MipsISA::CoreSpecific::CP0_Config_AR, MipsISA::CoreSpecific::CP0_Config_AT, MipsISA::CoreSpecific::CP0_Config_BE, MipsISA::CoreSpecific::CP0_Config_MT, MipsISA::CoreSpecific::CP0_Config_VI, MipsISA::CoreSpecific::CP0_EBase_CPUNum, MipsISA::CoreSpecific::CP0_IntCtl_IPPCI, MipsISA::CoreSpecific::CP0_IntCtl_IPTI, MipsISA::CoreSpecific::CP0_PerfCtr_M, MipsISA::CoreSpecific::CP0_PerfCtr_W, MipsISA::CoreSpecific::CP0_PRId_CompanyID, MipsISA::CoreSpecific::CP0_PRId_CompanyOptions, MipsISA::CoreSpecific::CP0_PRId_ProcessorID, MipsISA::CoreSpecific::CP0_PRId_Revision, MipsISA::CoreSpecific::CP0_SrsCtl_HSS, MipsISA::CoreSpecific::CP0_WatchHi_M, DPRINTF, MipsISA::mask, MipsISA::MISCREG_BADVADDR, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_CONFIG, MipsISA::MISCREG_CONFIG1, MipsISA::MISCREG_CONFIG2, MipsISA::MISCREG_CONFIG3, MipsISA::MISCREG_CONTEXT, MipsISA::MISCREG_CP0_RANDOM, MipsISA::MISCREG_EBASE, MipsISA::MISCREG_ENTRYLO0, MipsISA::MISCREG_ENTRYLO1, MipsISA::MISCREG_INDEX, MipsISA::MISCREG_INTCTL, MipsISA::MISCREG_LLADDR, MipsISA::MISCREG_MVP_CONF0, MipsISA::MISCREG_PAGEGRAIN, MipsISA::MISCREG_PAGEMASK, MipsISA::MISCREG_PERFCNT0, MipsISA::MISCREG_PRID, MipsISA::MISCREG_SRSCTL, MipsISA::MISCREG_STATUS, MipsISA::MISCREG_TC_BIND, MipsISA::MISCREG_TC_HALT, MipsISA::MISCREG_TC_STATUS, MipsISA::MISCREG_VPE_CONF0, MipsISA::MISCREG_WATCHHI0, numThreads, numVpes, panic, MipsISA::procId, readMiscRegNoEffect(), replaceBits(), setMiscRegNoEffect(), setRegMask(), and ArmISA::status.
MiscReg MipsISA::ISA::filterCP0Write (int misc_reg, int reg_sel, const MiscReg & val)
This method doesn't need to adjust the Control Register Offset since it has already been done in the calling method (setRegWithEffect).
Definition at line 499 of file isa.cc.
References DPRINTF, miscRegFile, and miscRegFile_WriteMask.
Referenced by setMiscReg().
int MipsISA::ISA::flattenCCIndex (int reg) const [inline]
Definition at line 182 of file isa.hh.
int MipsISA::ISA::flattenFloatIndex (int reg) const [inline]
Definition at line 175 of file isa.hh.
int MipsISA::ISA::flattenIntIndex (int reg) const [inline]
Definition at line 169 of file isa.hh.
int MipsISA::ISA::flattenMiscIndex (int reg) const [inline]
Definition at line 188 of file isa.hh.
unsigned MipsISA::ISA::getVPENum (ThreadID tid) const [inline]
Definition at line 413 of file isa.cc.
References MipsISA::MISCREG_TC_BIND, and miscRegFile.
Referenced by readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), and setRegMask().
const MipsISAParams * MipsISA::ISA::params () const
Reimplemented from SimObject.
Definition at line 145 of file isa.cc.
References SimObject::_params.
MiscReg MipsISA::ISA::readMiscReg (int misc_reg, ThreadContext * tc, ThreadID tid = 0)
Definition at line 434 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile, miscRegNames, and perThreadContext.
MiscReg MipsISA::ISA::readMiscRegNoEffect (int misc_reg, ThreadID tid = 0) const
Definition at line 420 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile, miscRegNames, and perThreadContext.
Referenced by configCP(), and updateCPU().
void MipsISA::ISA::scheduleCP0Update (BaseCPU * cpu, Cycles delay = Cycles(0))
Definition at line 519 of file isa.cc.
References cp0Updated, and UpdateCP0.
Referenced by setMiscReg().
void MipsISA::ISA::setMiscReg (int misc_reg, const MiscReg & val, ThreadContext * tc, ThreadID tid = 0)
Definition at line 475 of file isa.cc.
References bankType, DPRINTF, filterCP0Write(), ThreadContext::getCpuPtr(), getVPENum(), miscRegFile, miscRegNames, perThreadContext, and scheduleCP0Update().
void MipsISA::ISA::setMiscRegNoEffect (int misc_reg, const MiscReg & val, ThreadID tid = 0)
Definition at line 447 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile, miscRegNames, and perThreadContext.
Referenced by configCP().
void MipsISA::ISA::setRegMask (int misc_reg, const MiscReg & val, ThreadID tid = 0)
Definition at line 460 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile_WriteMask, miscRegNames, and perThreadContext.
Referenced by configCP().
void MipsISA::ISA::startup (ThreadContext * tc) [inline]
Definition at line 159 of file isa.hh.
void MipsISA::ISA::updateCP0ReadView (int misc_reg, ThreadID tid) [inline]
Definition at line 89 of file isa.hh.
void MipsISA::ISA::updateCPU (BaseCPU * cpu)
Definition at line 531 of file isa.cc.
References cp0Updated, MipsISA::haltThread(), MipsISA::MISCREG_MVP_CONF0, MipsISA::MISCREG_TC_HALT, MipsISA::MISCREG_TC_STATUS, readMiscRegNoEffect(), and MipsISA::restoreThread().
Referenced by MipsISA::ISA::CP0Event::process().
Member Data Documentation
std::vector<BankType> MipsISA::ISA::bankType [protected]
Definition at line 72 of file isa.hh.
Referenced by ISA(), readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), and setRegMask().
std::queue<CP0Event*> MipsISA::ISA::cp0EventRemoveList
Definition at line 154 of file isa.hh.
bool MipsISA::ISA::cp0Updated
Definition at line 113 of file isa.hh.
Referenced by scheduleCP0Update(), and updateCPU().
std::vector<std::vector<MiscReg> > MipsISA::ISA::miscRegFile [protected]
Definition at line 70 of file isa.hh.
Referenced by clear(), filterCP0Write(), getVPENum(), ISA(), readMiscReg(), readMiscRegNoEffect(), setMiscReg(), and setMiscRegNoEffect().
std::vector<std::vector<MiscReg> > MipsISA::ISA::miscRegFile_WriteMask [protected]
Definition at line 71 of file isa.hh.
Referenced by clear(), filterCP0Write(), ISA(), and setRegMask().
std::string MipsISA::ISA::miscRegNames [static]
Definition at line 156 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), and setRegMask().
uint8_t MipsISA::ISA::numThreads [protected]
Definition at line 61 of file isa.hh.
Referenced by configCP(), and ISA().
uint8_t MipsISA::ISA::numVpes [protected]
Definition at line 62 of file isa.hh.
Referenced by configCP(), and ISA().
The documentation for this class was generated from the following files:
arch/mips/isa.hh
arch/mips/isa.cc