gem5: SlavePort Class Reference
SlavePort Class Reference
A SlavePort is a specialisation of a port.
#include <port.hh>
Public Member Functions
SlavePort (const std::string &name, MemObject *owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt)
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
virtual AddrRangeList getAddrRanges () const =0
Get a list of the non-overlapping address ranges the owner is responsible for.
Protected Member Functions
void unbind ()
Called by the master port to unbind.
void bind (MasterPort &master_port)
Called by the master port to bind.
virtual Tick recvAtomic (PacketPtr pkt)=0
Receive an atomic request packet from the master port.
virtual void recvFunctional (PacketPtr pkt)=0
Receive a functional request packet from the master port.
virtual bool recvTimingReq (PacketPtr pkt)=0
Receive a timing request from the master port.
virtual bool recvTimingSnoopResp (PacketPtr pkt)
Receive a timing snoop response from the master port.
virtual void recvRespRetry ()=0
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Private Attributes
MasterPort * _masterPort
Friends
class MasterPort
Detailed Description
A SlavePort is a specialisation of a port.
In addition to the basic functionality of sending packets to its master peer, it also has functions specific to a slave, e.g. to send range changes and get the address ranges that the port responds to.
Definition at line 331 of file port.hh.
Constructor & Destructor Documentation
SlavePort::SlavePort (const std::string & name, MemObject * owner, PortID id = InvalidPortID)
Slave port.
Definition at line 212 of file port.cc.
SlavePort::~SlavePort () [virtual]
Definition at line 217 of file port.cc.
Member Function Documentation
void SlavePort::bind (MasterPort & master_port) [protected]
Called by the master port to bind.
Should never be called directly.
Definition at line 229 of file port.cc.
References BaseSlavePort::_baseMasterPort, and _masterPort.
Referenced by MasterPort::bind().
virtual AddrRangeList SlavePort::getAddrRanges () const [pure virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implemented in PioPort, PciDevice::PciConfigPort, X86ISA::IntDevice::IntSlavePort, AddrMapper::MapperSlavePort, Bridge::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, CommMonitor::MonitorSlavePort, DRAMCtrl::MemoryPort, DRAMSim2::MemoryPort, ExternalSlave::Port, MemCheckerMonitor::MonitorSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, RubyMemoryControl::MemoryPort, DMASequencer::MemSlavePort, RubyPort::MemSlavePort, RubyPort::PioSlavePort, SimpleMemory::MemoryPort, and SnapMemCtrl::SnapMemCtrlSlavePort.
Referenced by MasterPort::getAddrRanges().
bool SlavePort::isSnooping () const [inline]
Find out if the peer master port is snooping or not.
Returns:
true if the peer master port is snooping
Reimplemented in SnapMemCtrl::SnapMemCtrlSlavePort.
Definition at line 405 of file port.hh.
References _masterPort, and MasterPort::isSnooping().
Referenced by Cache::functionalAccess(), MemCheckerMonitor::isSnooping(), CommMonitor::isSnooping(), and AddrMapper::isSnooping().
virtual Tick SlavePort::recvAtomic (PacketPtr pkt) [protected, pure virtual]
Receive an atomic request packet from the master port.
Implemented in PioPort, PciDevice::PciConfigPort, AddrMapper::MapperSlavePort, Bridge::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, CommMonitor::MonitorSlavePort, DRAMCtrl::MemoryPort, DRAMSim2::MemoryPort, StubSlavePort, MemCheckerMonitor::MonitorSlavePort, MessageSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, RubyMemoryControl::MemoryPort, DMASequencer::MemSlavePort, RubyPort::MemSlavePort, RubyPort::PioSlavePort, SimpleMemory::MemoryPort, SnapMemCtrl::SnapMemCtrlSlavePort, and SimpleTimingPort.
Referenced by MasterPort::sendAtomic().
virtual void SlavePort::recvFunctional (PacketPtr pkt) [protected, pure virtual]
Receive a functional request packet from the master port.
Implemented in AddrMapper::MapperSlavePort, Bridge::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, CommMonitor::MonitorSlavePort, DRAMCtrl::MemoryPort, DRAMSim2::MemoryPort, StubSlavePort, MemCheckerMonitor::MonitorSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, RubyMemoryControl::MemoryPort, DMASequencer::MemSlavePort, RubyPort::MemSlavePort, RubyPort::PioSlavePort, SimpleMemory::MemoryPort, SnapMemCtrl::SnapMemCtrlSlavePort, and SimpleTimingPort.
Referenced by MasterPort::sendFunctional().
virtual void SlavePort::recvRespRetry () [protected, pure virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implemented in AddrMapper::MapperSlavePort, Bridge::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, CommMonitor::MonitorSlavePort, DRAMSim2::MemoryPort, StubSlavePort, MemCheckerMonitor::MonitorSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, QueuedSlavePort, and SimpleMemory::MemoryPort.
Referenced by MasterPort::sendRetryResp().
virtual bool SlavePort::recvTimingReq (PacketPtr pkt) [protected, pure virtual]
Receive a timing request from the master port.
Implemented in AddrMapper::MapperSlavePort, Bridge::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, CommMonitor::MonitorSlavePort, DRAMCtrl::MemoryPort, DRAMSim2::MemoryPort, StubSlavePort, MemCheckerMonitor::MonitorSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, RubyMemoryControl::MemoryPort, DMASequencer::MemSlavePort, RubyPort::MemSlavePort, RubyPort::PioSlavePort, SimpleMemory::MemoryPort, SnapMemCtrl::SnapMemCtrlSlavePort, and SimpleTimingPort.
Referenced by MasterPort::sendTimingReq().
virtual bool SlavePort::recvTimingSnoopResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop response from the master port.
Reimplemented in AddrMapper::MapperSlavePort, CoherentXBar::CoherentXBarSlavePort, CommMonitor::MonitorSlavePort, StubSlavePort, and MemCheckerMonitor::MonitorSlavePort.
Definition at line 457 of file port.hh.
References Port::name(), and panic.
Referenced by MasterPort::sendTimingSnoopResp().
Tick SlavePort::sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Parameters:
pkt Snoop packet to send.
Returns:
Estimated latency of access.
Definition at line 236 of file port.cc.
References _masterPort, Packet::isRequest(), and MasterPort::recvAtomicSnoop().
Referenced by Cache::handleSnoop(), MemCheckerMonitor::recvAtomicSnoop(), CommMonitor::recvAtomicSnoop(), and AddrMapper::recvAtomicSnoop().
void SlavePort::sendFunctionalSnoop (PacketPtr pkt)
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Parameters:
pkt Snoop packet to send.
Definition at line 243 of file port.cc.
References _masterPort, Packet::isRequest(), and MasterPort::recvFunctionalSnoop().
Referenced by Cache::functionalAccess(), MemCheckerMonitor::recvFunctionalSnoop(), CommMonitor::recvFunctionalSnoop(), and AddrMapper::recvFunctionalSnoop().
void SlavePort::sendRangeChange () const [inline]
Called by the owner to send a range change.
Definition at line 410 of file port.hh.
References _masterPort, fatal, Port::name(), and MasterPort::recvRangeChange().
Referenced by SimpleMemory::init(), DMASequencer::init(), ExternalSlave::init(), DRAMSim2::init(), DRAMCtrl::init(), Bridge::init(), PciDevice::init(), PioDevice::init(), BaseCache::init(), X86ISA::Interrupts::init(), RubyPort::PioMasterPort::recvRangeChange(), MemCheckerMonitor::recvRangeChange(), CommMonitor::recvRangeChange(), AddrMapper::recvRangeChange(), Sinic::Device::unserialize(), PciDevice::unserialize(), and PciDevice::writeConfig().
void SlavePort::sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
Definition at line 264 of file port.cc.
References _masterPort, and MasterPort::recvReqRetry().
Referenced by StubSlavePort::ResponseEvent::process(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::processRespondEvent(), BaseCache::CacheSlavePort::processSendRetry(), MemCheckerMonitor::recvReqRetry(), CommMonitor::recvReqRetry(), AddrMapper::recvReqRetry(), SimpleMemory::release(), Bridge::BridgeSlavePort::retryStalledReq(), DMASequencer::ruby_hit_callback(), BaseXBar::ReqLayer::sendRetry(), DRAMSim2::tick(), and Bridge::BridgeSlavePort::trySendTiming().
void SlavePort::sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Definition at line 270 of file port.cc.
References _masterPort, and MasterPort::recvRetrySnoopResp().
Referenced by BaseXBar::SnoopRespLayer::sendRetry(), and CoherentXBar::SnoopRespPort::sendRetryResp().
bool SlavePort::sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvRespRetry at which point it can re-issue a sendTimingResp.
Parameters:
pkt Packet to send.
Returns:
If the send was succesful or not.
Definition at line 250 of file port.cc.
References _masterPort, Packet::isResponse(), and MasterPort::recvTimingResp().
Referenced by SimpleMemory::dequeue(), StubSlavePort::ResponseEvent::process(), MemCheckerMonitor::recvTimingResp(), CommMonitor::recvTimingResp(), AddrMapper::recvTimingResp(), DRAMSim2::sendResponse(), RespPacketQueue::sendTiming(), and Bridge::BridgeSlavePort::trySendTiming().
void SlavePort::sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
Snoop requests always succeed and hence no return value is needed.
Parameters:
pkt Packet to send.
Definition at line 257 of file port.cc.
References _masterPort, Packet::isRequest(), and MasterPort::recvTimingSnoopReq().
Referenced by Cache::getTimingPacket(), Cache::handleSnoop(), MemCheckerMonitor::recvTimingSnoopReq(), CommMonitor::recvTimingSnoopReq(), and AddrMapper::recvTimingSnoopReq().
void SlavePort::unbind () [protected]
Called by the master port to unbind.
Should never be called directly.
Definition at line 222 of file port.cc.
References BaseSlavePort::_baseMasterPort, and _masterPort.
Referenced by MasterPort::unbind().
Friends And Related Function Documentation
friend class MasterPort [friend]
Definition at line 334 of file port.hh.
Member Data Documentation
MasterPort* SlavePort::_masterPort [private]
Definition at line 338 of file port.hh.
Referenced by bind(), isSnooping(), sendAtomicSnoop(), sendFunctionalSnoop(), sendRangeChange(), sendRetryReq(), sendRetrySnoopResp(), sendTimingResp(), sendTimingSnoopReq(), and unbind().
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc