gem5: Debug::CompoundFlag Class Reference
Debug::CompoundFlag Class Reference
#include <debug.hh>
Public Member Functions
CompoundFlag (const char *name, const char *desc, Flag *f00=nullptr, Flag *f01=nullptr, Flag *f02=nullptr, Flag *f03=nullptr, Flag *f04=nullptr, Flag *f05=nullptr, Flag *f06=nullptr, Flag *f07=nullptr, Flag *f08=nullptr, Flag *f09=nullptr, Flag *f10=nullptr, Flag *f11=nullptr, Flag *f12=nullptr, Flag *f13=nullptr, Flag *f14=nullptr, Flag *f15=nullptr, Flag *f16=nullptr, Flag *f17=nullptr, Flag *f18=nullptr, Flag *f19=nullptr)
void enable ()
void disable ()
Protected Member Functions
void addFlag (Flag *f)
Detailed Description
Definition at line 80 of file debug.hh.
Constructor & Destructor Documentation
Debug::CompoundFlag::CompoundFlag (const char * name, const char * desc, Flag * f00 = nullptr, Flag * f01 = nullptr, Flag * f02 = nullptr, Flag * f03 = nullptr, Flag * f04 = nullptr, Flag * f05 = nullptr, Flag * f06 = nullptr, Flag * f07 = nullptr, Flag * f08 = nullptr, Flag * f09 = nullptr, Flag * f10 = nullptr, Flag * f11 = nullptr, Flag * f12 = nullptr, Flag * f13 = nullptr, Flag * f14 = nullptr, Flag * f15 = nullptr, Flag * f16 = nullptr, Flag * f17 = nullptr, Flag * f18 = nullptr, Flag * f19 = nullptr) [inline]
Definition at line 91 of file debug.hh.
References addFlag().
Member Function Documentation
void Debug::CompoundFlag::addFlag (Flag * f) [inline, protected]
Definition at line 84 of file debug.hh.
References Debug::Flag::_kids.
Referenced by CompoundFlag().
void Debug::CompoundFlag::disable () [virtual]
Reimplemented from Debug::SimpleFlag.
Definition at line 105 of file debug.cc.
References Debug::Flag::_kids, and Debug::Flag::disable().
void Debug::CompoundFlag::enable () [virtual]
Reimplemented from Debug::SimpleFlag.
Definition at line 98 of file debug.cc.
References Debug::Flag::_kids, and Debug::Flag::enable().
The documentation for this class was generated from the following files:
base/debug.hh
base/debug.cc