gem5: BaseMasterPort Class Reference
BaseMasterPort Class Reference
A BaseMasterPort is a protocol-agnostic master port, responsible only for the structural connection to a slave port.
#include <port.hh>
Public Member Functions
virtual void bind (BaseSlavePort &slave_port)=0
virtual void unbind ()=0
BaseSlavePort & getSlavePort () const
bool isConnected () const
Protected Member Functions
BaseMasterPort (const std::string &name, MemObject *owner, PortID id=InvalidPortID)
virtual ~BaseMasterPort ()
Protected Attributes
BaseSlavePort * _baseSlavePort
Detailed Description
A BaseMasterPort is a protocol-agnostic master port, responsible only for the structural connection to a slave port.
The final master port that inherits from the base class must override the bind member function for the specific slave port class.
Definition at line 115 of file port.hh.
Constructor & Destructor Documentation
BaseMasterPort::BaseMasterPort (const std::string & name, MemObject * owner, PortID id = InvalidPortID) [protected]
Definition at line 62 of file port.cc.
BaseMasterPort::~BaseMasterPort () [protected, virtual]
Definition at line 68 of file port.cc.
Member Function Documentation
virtual void BaseMasterPort::bind (BaseSlavePort & slave_port) [pure virtual]
Implemented in MasterPort.
Referenced by CxxConfigManager::bindPort(), and connectPorts().
BaseSlavePort & BaseMasterPort::getSlavePort () const
Definition at line 73 of file port.cc.
References _baseSlavePort, Port::name(), and panic.
bool BaseMasterPort::isConnected () const
Definition at line 83 of file port.cc.
References _baseSlavePort.
Referenced by CxxConfigManager::bindPort(), RubyPort::getChildDrainCount(), MemCheckerMonitor::init(), ExternalMaster::init(), CommMonitor::init(), Bridge::init(), AddrMapper::init(), X86ISA::IntDevice::init(), DmaDevice::init(), TrafficGen::init(), BaseCache::init(), and System::init().
virtual void BaseMasterPort::unbind () [pure virtual]
Implemented in MasterPort.
Member Data Documentation
BaseSlavePort* BaseMasterPort::_baseSlavePort [protected]
Definition at line 120 of file port.hh.
Referenced by MasterPort::bind(), getSlavePort(), isConnected(), and MasterPort::unbind().
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc