gem5: MemChecker Class Reference
MemChecker Class Reference
MemChecker.
#include <mem_checker.hh>
Classes
class ByteTracker
The ByteTracker keeps track of transactions for the *same byte* -- all outstanding reads, the completed reads (and what they observed) and write clusters (see WriteCluster).
class Transaction
The Transaction class captures the lifetimes of read and write operations, and the values they consumed or produced respectively.
class WriteCluster
The WriteCluster class captures sets of writes where all writes are overlapping with at least one other write.
Public Types
typedef uint64_t Serial
The Serial type is used to be able to uniquely identify a transaction as it passes through the system.
typedef std::list< Transaction > TransactionList
typedef std::list< WriteCluster > WriteClusterList
Public Member Functions
MemChecker (const MemCheckerParams *p)
virtual ~MemChecker ()
Serial startRead (Tick start, Addr addr, size_t size)
Starts a read transaction.
Serial startWrite (Tick start, Addr addr, size_t size, const uint8_t *data)
Starts a write transaction.
bool completeRead (Serial serial, Tick complete, Addr addr, size_t size, uint8_t *data)
Completes a previously started read transaction.
void completeWrite (Serial serial, Tick complete, Addr addr, size_t size)
Completes a previously started write transaction.
void abortWrite (Serial serial, Addr addr, size_t size)
Aborts a previously started write transaction.
void reset ()
Resets the entire checker.
void reset (Addr addr, size_t size)
Resets an address-range.
const std::string & getErrorMessage () const
In completeRead, if an error is encountered, this does not print nor cause an error, but instead should be handled by the caller.
Static Public Attributes
static const Serial SERIAL_INITIAL = 0
Initial serial.
static const Tick TICK_INITIAL = 0
The initial tick the system starts with.
static const Tick TICK_FUTURE = MaxTick
The maximum value that curTick() could ever return.
static const uint8_t DATA_INITIAL = 0x00
Initial data value.
Private Member Functions
ByteTracker * getByteTracker (Addr addr)
Returns the instance of ByteTracker for the requested location.
Private Attributes
std::string errorMessage
Detailed error message of the last violation in completeRead.
Serial nextSerial
Next distinct serial to be assigned to the next transaction to be started.
m5::hash_map< Addr, ByteTracker > byte_trackers
Maintain a map of address --> byte-tracker.
Detailed Description
MemChecker.
Verifies that reads observe the values from permissible writes. As memory operations have a start and completion time, we consider them as transactions which have a start and end time. Because of this, the lifetimes of transactions of memory operations may be overlapping -- we assume that if there is overlap between writes, they could be reordered by the memory subsystem, and a read could any of these. For more detail, see comments of inExpectedData().
For simplicity, the permissible values a read can observe are only dependent on the particular location, and we do not consider the effect of multi-byte reads or writes. This precludes us from discovering single-copy atomicity violations.
Definition at line 71 of file mem_checker.hh.
Member Typedef Documentation
typedef uint64_t MemChecker::Serial
The Serial type is used to be able to uniquely identify a transaction as it passes through the system.
It's value is independent of any other system counters.
Definition at line 79 of file mem_checker.hh.
typedef std::list<Transaction> MemChecker::TransactionList
Definition at line 194 of file mem_checker.hh.
typedef std::list<WriteCluster> MemChecker::WriteClusterList
Definition at line 195 of file mem_checker.hh.
Constructor & Destructor Documentation
MemChecker::MemChecker (const MemCheckerParams * p) [inline]
Definition at line 374 of file mem_checker.hh.
virtual MemChecker::~MemChecker () [inline, virtual]
Definition at line 379 of file mem_checker.hh.
Member Function Documentation
void MemChecker::abortWrite (MemChecker::Serial serial, Addr addr, size_t size) [inline]
Aborts a previously started write transaction.
Parameters:
serial A serial of a write that was previously started and matches the address of the previously started write.
addr Address for write.
size The size of the data written.
Definition at line 557 of file mem_checker.hh.
References MemChecker::ByteTracker::abortWrite(), DPRINTF, getByteTracker(), and ArmISA::i.
Referenced by MemCheckerMonitor::recvTimingResp().
bool MemChecker::completeRead (MemChecker::Serial serial, Tick complete, Addr addr, size_t size, uint8_t * data)
Completes a previously started read transaction.
Parameters:
serial A serial of a read that was previously started and matches the address of the previously started read.
complete Tick we received the response from the memory subsystem.
addr Address for read.
size Size of data received.
data Pointer to size bytes, containing data received.
Returns:
True if the data we received is in the expected set, false otherwise.
Definition at line 298 of file mem_checker.cc.
References MemChecker::ByteTracker::completeRead(), csprintf(), DPRINTF, errorMessage, getByteTracker(), ArmISA::i, ArmISA::j, and MemChecker::ByteTracker::lastExpectedData().
Referenced by MemCheckerMonitor::recvTimingResp().
void MemChecker::completeWrite (MemChecker::Serial serial, Tick complete, Addr addr, size_t size) [inline]
Completes a previously started write transaction.
Parameters:
serial A serial of a write that was previously started and matches the address of the previously started write.
complete Tick we received acknowledgment of completion from the memory subsystem.
addr Address for write.
size The size of the data written.
Definition at line 544 of file mem_checker.hh.
References MemChecker::ByteTracker::completeWrite(), DPRINTF, getByteTracker(), and ArmISA::i.
Referenced by MemCheckerMonitor::recvTimingResp().
ByteTracker* MemChecker::getByteTracker (Addr addr) [inline, private]
Returns the instance of ByteTracker for the requested location.
Definition at line 479 of file mem_checker.hh.
References byte_trackers.
Referenced by abortWrite(), completeRead(), completeWrite(), startRead(), and startWrite().
const std::string& MemChecker::getErrorMessage () const [inline]
In completeRead, if an error is encountered, this does not print nor cause an error, but instead should be handled by the caller.
However, to record information about the cause of an error, completeRead creates an errorMessage. This function returns the last error that was detected in completeRead.
Returns:
Reference to string of error message.
Definition at line 473 of file mem_checker.hh.
References errorMessage.
Referenced by MemCheckerMonitor::recvTimingResp().
void MemChecker::reset (Addr addr, size_t size)
Resets an address-range.
This may be useful in case other unmonitored parts of the system caused modification to this memory, but we cannot track their written values.
Parameters:
addr Address base.
size Size of range to be invalidated.
Definition at line 343 of file mem_checker.cc.
References byte_trackers, and ArmISA::i.
void MemChecker::reset () [inline]
Resets the entire checker.
Note that if there are transactions in-flight, this will cause a warning to be issued if these are completed after the reset. This does not reset nextSerial to avoid such a race condition: where a transaction started before a reset with serial S, then reset() was called, followed by a start of a transaction with the same serial S and then receive a completion of the transaction before the reset with serial S.
Definition at line 451 of file mem_checker.hh.
References byte_trackers.
Referenced by MemCheckerMonitor::recvFunctional(), and MemCheckerMonitor::recvFunctionalSnoop().
MemChecker::Serial MemChecker::startRead (Tick start, Addr addr, size_t size) [inline]
Starts a read transaction.
Parameters:
start Tick this read was sent to the memory subsystem.
addr Address for read.
size Size of data expected.
Returns:
Serial representing the unique identifier for this transaction.
Definition at line 516 of file mem_checker.hh.
References DPRINTF, getByteTracker(), ArmISA::i, nextSerial, and MemChecker::ByteTracker::startRead().
Referenced by MemCheckerMonitor::recvTimingReq().
MemChecker::Serial MemChecker::startWrite (Tick start, Addr addr, size_t size, const uint8_t * data) [inline]
Starts a write transaction.
Parameters:
start Tick when this write was sent to the memory subsystem.
addr Address for write.
size Size of data to be written.
data Pointer to size bytes, containing data to be written.
Returns:
Serial representing the unique identifier for this transaction.
Definition at line 530 of file mem_checker.hh.
References DPRINTF, getByteTracker(), ArmISA::i, nextSerial, and MemChecker::ByteTracker::startWrite().
Referenced by MemCheckerMonitor::recvTimingReq().
Member Data Documentation
m5::hash_map<Addr, ByteTracker> MemChecker::byte_trackers [private]
Maintain a map of address --> byte-tracker.
Per-byte entries are initialized as needed.
The required space for this obviously grows with the number of distinct addresses used for a particular workload. The used size is independent on the number of nodes in the system, those may affect the size of per-byte tracking information.
Access via getByteTracker()!
Definition at line 512 of file mem_checker.hh.
Referenced by getByteTracker(), and reset().
const uint8_t MemChecker::DATA_INITIAL = 0x00 [static]
Initial data value.
No requirements.
Definition at line 98 of file mem_checker.hh.
Referenced by MemChecker::ByteTracker::ByteTracker().
std::string MemChecker::errorMessage [private]
Detailed error message of the last violation in completeRead.
Definition at line 487 of file mem_checker.hh.
Referenced by completeRead(), and getErrorMessage().
Serial MemChecker::nextSerial [private]
Next distinct serial to be assigned to the next transaction to be started.
Definition at line 499 of file mem_checker.hh.
Referenced by startRead(), and startWrite().
const Serial MemChecker::SERIAL_INITIAL = 0 [static]
Initial serial.
Definition at line 81 of file mem_checker.hh.
Referenced by MemChecker::ByteTracker::ByteTracker().
const Tick MemChecker::TICK_FUTURE = MaxTick [static]
The maximum value that curTick() could ever return.
Definition at line 93 of file mem_checker.hh.
Referenced by MemChecker::WriteCluster::completeWrite(), MemChecker::WriteCluster::isComplete(), MemChecker::ByteTracker::startRead(), and MemChecker::WriteCluster::startWrite().
const Tick MemChecker::TICK_INITIAL = 0 [static]
The initial tick the system starts with.
Must not be larger than the minimum value that curTick() could return at any time in the system's execution.
Definition at line 88 of file mem_checker.hh.
Referenced by MemChecker::ByteTracker::ByteTracker(), and MemChecker::ByteTracker::inExpectedData().
The documentation for this class was generated from the following files:
mem/mem_checker.hh
mem/mem_checker.cc