gem5: Stats::DistBase< Derived, Stor > Class Template Reference
Stats::DistBase< Derived, Stor > Class Template Reference
Implementation of a distribution stat.
#include <statistics.hh>
Public Types
typedef DistInfoProxy< Derived > Info
typedef Stor Storage
typedef Stor::Params Params
Public Member Functions
DistBase ()
template<typename U >
void sample (const U &v, int n=1)
Add a value to the distribtion n times.
size_type size () const
Return the number of entries in this stat.
bool zero () const
Return true if no samples have been added.
void prepare ()
void reset ()
Reset stat value to default.
void add (DistBase &d)
Add the argument distribution to the this distibution.
Protected Member Functions
char storage[sizeof(Storage)] __attribute__ ((aligned(8)))
The storage for this stat.
Storage * data ()
Retrieve the storage.
const Storage * data () const
Retrieve a const pointer to the storage.
void doInit ()
Detailed Description
template<class Derived, class Stor>
class Stats::DistBase< Derived, Stor >
Implementation of a distribution stat.
The type of distribution is determined by the Storage template.
See also:
ScalarBase
Definition at line 1803 of file statistics.hh.
Member Typedef Documentation
template<class Derived, class Stor> typedef DistInfoProxy<Derived> Stats::DistBase< Derived, Stor >::Info
Reimplemented from Stats::DataWrap< Derived, DistInfoProxy >.
Definition at line 1806 of file statistics.hh.
template<class Derived, class Stor> typedef Stor::Params Stats::DistBase< Derived, Stor >::Params
Definition at line 1808 of file statistics.hh.
template<class Derived, class Stor> typedef Stor Stats::DistBase< Derived, Stor >::Storage
Definition at line 1807 of file statistics.hh.
Constructor & Destructor Documentation
template<class Derived, class Stor> Stats::DistBase< Derived, Stor >::DistBase () [inline]
Definition at line 1843 of file statistics.hh.
Member Function Documentation
template<class Derived, class Stor> char storage [sizeof(Storage)] Stats::DistBase< Derived, Stor >::__attribute__ ((aligned(8))) [protected]
The storage for this stat.
template<class Derived, class Stor> void Stats::DistBase< Derived, Stor >::add (DistBase< Derived, Stor > & d) [inline]
Add the argument distribution to the this distibution.
Definition at line 1884 of file statistics.hh.
Referenced by Profiler::collateStats().
template<class Derived, class Stor> const Storage* Stats::DistBase< Derived, Stor >::data () const [inline, protected]
Retrieve a const pointer to the storage.
Returns:
A const pointer to the storage object for this stat.
Definition at line 1830 of file statistics.hh.
template<class Derived, class Stor> Storage* Stats::DistBase< Derived, Stor >::data () [inline, protected]
Retrieve the storage.
Returns:
The storage object for this stat.
Definition at line 1820 of file statistics.hh.
Referenced by Stats::DistBase< Distribution, DistStor >::add(), Stats::DistBase< Distribution, DistStor >::prepare(), Stats::DistBase< Distribution, DistStor >::reset(), Stats::DistBase< Distribution, DistStor >::sample(), Stats::DistBase< Distribution, DistStor >::size(), and Stats::DistBase< Distribution, DistStor >::zero().
template<class Derived, class Stor> void Stats::DistBase< Derived, Stor >::doInit () [inline, protected]
Definition at line 1836 of file statistics.hh.
template<class Derived, class Stor> void Stats::DistBase< Derived, Stor >::prepare () [inline]
Definition at line 1866 of file statistics.hh.
template<class Derived, class Stor> void Stats::DistBase< Derived, Stor >::reset () [inline]
Reset stat value to default.
Reimplemented from Stats::InfoAccess.
Definition at line 1876 of file statistics.hh.
Referenced by Sequencer::resetStats(), and AbstractController::resetStats().
template<class Derived, class Stor> template<typename U > void Stats::DistBase< Derived, Stor >::sample (const U & v, int n = 1) [inline]
Add a value to the distribtion n times.
Calls sample on the storage class.
Parameters:
v The value to add.
n The number of times to add it, defaults to 1.
Definition at line 1852 of file statistics.hh.
Referenced by FlashDevice::accessDevice(), DefaultCommit< Impl >::commitInsts(), ArmISA::TableWalker::doL1DescriptorWrapper(), ArmISA::TableWalker::doL2DescriptorWrapper(), ArmISA::TableWalker::doLongDescriptorWrapper(), UFSHostDevice::finalUTP(), CoherentXBar::forwardAtomic(), CoherentXBar::forwardTiming(), Sequencer::insertRequest(), ArmISA::TableWalker::pendingChange(), DRAMCtrl::prechargeBank(), DRAMCtrl::processNextReqEvent(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TableWalker::processWalkWrapper(), AbstractController::profileMsgDelay(), Sequencer::recordMissLatency(), CommMonitor::recvTimingReq(), CommMonitor::recvTimingResp(), StatTest::run(), PolicySelector::sampleCounter(), CommMonitor::samplePeriodic(), InstructionQueue< Impl >::scheduleReadyInsts(), DefaultFetch< Impl >::tick(), ReusabilityProfiler::tick_to_block(), StackDistCalc::update(), and UFSHostDevice::write().
template<class Derived, class Stor> size_type Stats::DistBase< Derived, Stor >::size () const [inline]
Return the number of entries in this stat.
Returns:
The number of entries.
Definition at line 1858 of file statistics.hh.
template<class Derived, class Stor> bool Stats::DistBase< Derived, Stor >::zero () const [inline]
Return true if no samples have been added.
Returns:
True if there haven't been any samples.
Reimplemented from Stats::InfoAccess.
Definition at line 1863 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh