gem5: LRUCacheSetTracer Class Reference
LRUCacheSetTracer Class Reference
#include <reuse_dist.hh>
Public Member Functions
LRUCacheSetTracer ()
void insert (Addr addr)
bool exists (Addr addr)
void victim (Addr addr)
void access (Addr addr)
unsigned int lrustate (Addr addr)
Detailed Description
Definition at line 10 of file reuse_dist.hh.
Constructor & Destructor Documentation
LRUCacheSetTracer::LRUCacheSetTracer () [inline]
Definition at line 12 of file reuse_dist.hh.
Member Function Documentation
void LRUCacheSetTracer::access (Addr addr) [inline]
Definition at line 16 of file reuse_dist.hh.
References insert(), and victim().
bool LRUCacheSetTracer::exists (Addr addr) [inline]
Definition at line 14 of file reuse_dist.hh.
void LRUCacheSetTracer::insert (Addr addr) [inline]
Definition at line 13 of file reuse_dist.hh.
Referenced by access().
unsigned int LRUCacheSetTracer::lrustate (Addr addr) [inline]
Definition at line 17 of file reuse_dist.hh.
void LRUCacheSetTracer::victim (Addr addr) [inline]
Definition at line 15 of file reuse_dist.hh.
Referenced by access().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/reuse_dist.hh