gem5: CommMonitor Class Reference
CommMonitor Class Reference
The communication monitor is a MemObject which can monitor statistics of the communication happening between two ports in the memory system.
#include <comm_monitor.hh>
Classes
class CommMonitorSenderState
Sender state class for the monitor so that we can annotate packets with a transmit time and receive time.
class MonitorMasterPort
This is the master port of the communication monitor.
class MonitorSlavePort
This is the slave port of the communication monitor.
struct MonitorStats
Stats declarations, all in a struct for convenience.
Public Types
typedef CommMonitorParams Params
Parameters of communication monitor.
Public Member Functions
const Params * params () const
CommMonitor (Params *params)
Constructor based on the Python params.
~CommMonitor ()
Destructor.
void closeStreams ()
Callback to flush and close all open output streams on exit.
virtual BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
virtual BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void regStats ()
Register statistics.
Private Member Functions
void recvFunctional (PacketPtr pkt)
void recvFunctionalSnoop (PacketPtr pkt)
Tick recvAtomic (PacketPtr pkt)
Tick recvAtomicSnoop (PacketPtr pkt)
bool recvTimingReq (PacketPtr pkt)
bool recvTimingResp (PacketPtr pkt)
void recvTimingSnoopReq (PacketPtr pkt)
bool recvTimingSnoopResp (PacketPtr pkt)
AddrRangeList getAddrRanges () const
bool isSnooping () const
void recvReqRetry ()
void recvRespRetry ()
void recvRangeChange ()
void samplePeriodic ()
This function is called periodically at the end of each time bin.
void startup ()
Schedule the first periodic event.
Private Attributes
MonitorMasterPort masterPort
Instance of master port, facing the memory side.
MonitorSlavePort slavePort
Instance of slave port, i.e.
EventWrapper< CommMonitor,&CommMonitor::samplePeriodic > samplePeriodicEvent
Periodic event called at the end of each simulation time bin.
Tick samplePeriodTicks
Length of simulation time bin.
Time samplePeriod
Addr readAddrMask
Address mask for sources of read accesses to be captured.
Addr writeAddrMask
Address mask for sources of write accesses to be captured.
MonitorStats stats
Instantiate stats.
StackDistCalc * stackDistCalc
Optional stack distance calculator.
ProtoOutputStream * traceStream
Output stream for a potential trace.
System * system
The system in which the monitor lives.
Detailed Description
The communication monitor is a MemObject which can monitor statistics of the communication happening between two ports in the memory system.
Currently the following stats are implemented: Histograms of read/write transactions, read/write burst lengths, read/write bandwidth, outstanding read/write requests, read latency and inter transaction time (read-read, write-write, read/write-read/write). Furthermore it allows to capture the number of accesses to an address over time ("heat map"). All stats can be disabled from Python.
Definition at line 63 of file comm_monitor.hh.
Member Typedef Documentation
typedef CommMonitorParams CommMonitor::Params
Parameters of communication monitor.
Reimplemented from MemObject.
Definition at line 69 of file comm_monitor.hh.
Constructor & Destructor Documentation
CommMonitor::CommMonitor (Params * params)
Constructor based on the Python params.
Parameters:
params Python parameters
Definition at line 49 of file comm_monitor.cc.
References closeStreams(), DPRINTF, SimClock::Frequency, Time::msec(), SimObject::name(), registerExitCallback(), OutputDirectory::resolve(), samplePeriod, samplePeriodTicks, Time::setTick(), simout, traceStream, and ProtoOutputStream::write().
CommMonitor::~CommMonitor ()
Destructor.
Definition at line 109 of file comm_monitor.cc.
References closeStreams().
Member Function Documentation
void CommMonitor::closeStreams ()
Callback to flush and close all open output streams on exit.
If we were calling the destructor it could be done there.
Definition at line 116 of file comm_monitor.cc.
References traceStream.
Referenced by CommMonitor(), and ~CommMonitor().
AddrRangeList CommMonitor::getAddrRanges () const [private]
Definition at line 438 of file comm_monitor.cc.
References MasterPort::getAddrRanges(), and masterPort.
Referenced by CommMonitor::MonitorSlavePort::getAddrRanges().
BaseMasterPort & CommMonitor::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 145 of file comm_monitor.cc.
References masterPort.
BaseSlavePort & CommMonitor::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 155 of file comm_monitor.cc.
References slavePort.
void CommMonitor::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 129 of file comm_monitor.cc.
References fatal, BaseMasterPort::isConnected(), BaseSlavePort::isConnected(), System::isTimingMode(), masterPort, SimObject::name(), slavePort, system, traceStream, and warn.
bool CommMonitor::isSnooping () const [private]
Definition at line 431 of file comm_monitor.cc.
References SlavePort::isSnooping(), and slavePort.
Referenced by CommMonitor::MonitorMasterPort::isSnooping().
const Params* CommMonitor::params () const [inline]
Reimplemented from MemObject.
Definition at line 70 of file comm_monitor.hh.
References SimObject::_params.
Referenced by regStats().
Tick CommMonitor::recvAtomic (PacketPtr pkt) [private]
Definition at line 177 of file comm_monitor.cc.
References Packet::cmd, Packet::cmdToIndex(), curTick(), Packet::getAddr(), Request::getFlags(), Packet::getSize(), masterPort, Packet::req, MasterPort::sendAtomic(), stackDistCalc, traceStream, StackDistCalc::update(), and ProtoOutputStream::write().
Referenced by CommMonitor::MonitorSlavePort::recvAtomic().
Tick CommMonitor::recvAtomicSnoop (PacketPtr pkt) [private]
Definition at line 200 of file comm_monitor.cc.
References SlavePort::sendAtomicSnoop(), and slavePort.
Referenced by CommMonitor::MonitorMasterPort::recvAtomicSnoop().
void CommMonitor::recvFunctional (PacketPtr pkt) [private]
Definition at line 165 of file comm_monitor.cc.
References masterPort, and MasterPort::sendFunctional().
Referenced by CommMonitor::MonitorSlavePort::recvFunctional().
void CommMonitor::recvFunctionalSnoop (PacketPtr pkt) [private]
Definition at line 171 of file comm_monitor.cc.
References SlavePort::sendFunctionalSnoop(), and slavePort.
Referenced by CommMonitor::MonitorMasterPort::recvFunctionalSnoop().
void CommMonitor::recvRangeChange () [private]
Definition at line 457 of file comm_monitor.cc.
References SlavePort::sendRangeChange(), and slavePort.
Referenced by CommMonitor::MonitorMasterPort::recvRangeChange().
void CommMonitor::recvReqRetry () [private]
Definition at line 445 of file comm_monitor.cc.
References SlavePort::sendRetryReq(), and slavePort.
Referenced by CommMonitor::MonitorMasterPort::recvReqRetry().
void CommMonitor::recvRespRetry () [private]
Definition at line 451 of file comm_monitor.cc.
References masterPort, and MasterPort::sendRetryResp().
Referenced by CommMonitor::MonitorSlavePort::recvRespRetry().
bool CommMonitor::recvTimingReq (PacketPtr pkt) [private]
Definition at line 206 of file comm_monitor.cc.
References X86ISA::addr, Packet::cmd, Packet::cmdToIndex(), curTick(), CommMonitor::MonitorStats::disableAddrDists, CommMonitor::MonitorStats::disableBandwidthHists, CommMonitor::MonitorStats::disableBurstLengthHists, CommMonitor::MonitorStats::disableITTDists, CommMonitor::MonitorStats::disableLatencyHists, CommMonitor::MonitorStats::disableOutstandingHists, CommMonitor::MonitorStats::disableTransactionHists, DPRINTF, Packet::getAddr(), Request::getFlags(), Packet::getSize(), Packet::isRead(), Packet::isRequest(), Packet::isWrite(), CommMonitor::MonitorStats::ittReadRead, CommMonitor::MonitorStats::ittReqReq, CommMonitor::MonitorStats::ittWriteWrite, masterPort, Packet::memInhibitAsserted(), Packet::needsResponse(), CommMonitor::MonitorStats::outstandingReadReqs, CommMonitor::MonitorStats::outstandingWriteReqs, Packet::popSenderState(), Packet::pushSenderState(), CommMonitor::MonitorStats::readAddrDist, readAddrMask, CommMonitor::MonitorStats::readBurstLengthHist, CommMonitor::MonitorStats::readTrans, Packet::req, Stats::SparseHistBase< Derived, Stor >::sample(), Stats::DistBase< Derived, Stor >::sample(), MasterPort::sendTimingReq(), stackDistCalc, stats, CommMonitor::MonitorStats::timeOfLastRead, CommMonitor::MonitorStats::timeOfLastReq, CommMonitor::MonitorStats::timeOfLastWrite, CommMonitor::MonitorStats::totalWrittenBytes, traceStream, StackDistCalc::update(), ProtoOutputStream::write(), CommMonitor::MonitorStats::writeAddrDist, writeAddrMask, CommMonitor::MonitorStats::writeBurstLengthHist, CommMonitor::MonitorStats::writeTrans, and CommMonitor::MonitorStats::writtenBytes.
Referenced by CommMonitor::MonitorSlavePort::recvTimingReq().
bool CommMonitor::recvTimingResp (PacketPtr pkt) [private]
Definition at line 343 of file comm_monitor.cc.
References curTick(), CommMonitor::MonitorStats::disableBandwidthHists, CommMonitor::MonitorStats::disableLatencyHists, CommMonitor::MonitorStats::disableOutstandingHists, DPRINTF, Packet::getSize(), Packet::isRead(), Packet::isResponse(), Packet::isWrite(), CommMonitor::MonitorStats::outstandingReadReqs, CommMonitor::MonitorStats::outstandingWriteReqs, panic, Packet::SenderState::predecessor, CommMonitor::MonitorStats::readBytes, CommMonitor::MonitorStats::readLatencyHist, Stats::DistBase< Derived, Stor >::sample(), Packet::senderState, SlavePort::sendTimingResp(), slavePort, stats, CommMonitor::MonitorStats::totalReadBytes, CommMonitor::CommMonitorSenderState::transmitTime, and CommMonitor::MonitorStats::writeLatencyHist.
Referenced by CommMonitor::MonitorMasterPort::recvTimingResp().
void CommMonitor::recvTimingSnoopReq (PacketPtr pkt) [private]
Definition at line 419 of file comm_monitor.cc.
References SlavePort::sendTimingSnoopReq(), and slavePort.
Referenced by CommMonitor::MonitorMasterPort::recvTimingSnoopReq().
bool CommMonitor::recvTimingSnoopResp (PacketPtr pkt) [private]
Definition at line 425 of file comm_monitor.cc.
References masterPort, and MasterPort::sendTimingSnoopResp().
Referenced by CommMonitor::MonitorSlavePort::recvTimingSnoopResp().
void CommMonitor::regStats () [virtual]
Register statistics.
Reimplemented from SimObject.
Definition at line 463 of file comm_monitor.cc.
References CommMonitor::MonitorStats::averageReadBW, CommMonitor::MonitorStats::averageWriteBW, CommMonitor::MonitorStats::disableAddrDists, CommMonitor::MonitorStats::disableBandwidthHists, CommMonitor::MonitorStats::disableBurstLengthHists, CommMonitor::MonitorStats::disableITTDists, CommMonitor::MonitorStats::disableLatencyHists, CommMonitor::MonitorStats::disableOutstandingHists, CommMonitor::MonitorStats::disableTransactionHists, Stats::SparseHistogram::init(), Stats::Distribution::init(), Stats::Histogram::init(), CommMonitor::MonitorStats::ittReadRead, CommMonitor::MonitorStats::ittReqReq, CommMonitor::MonitorStats::ittWriteWrite, Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), Stats::nozero, CommMonitor::MonitorStats::outstandingReadsHist, CommMonitor::MonitorStats::outstandingWritesHist, params(), Stats::pdf, CommMonitor::MonitorStats::readAddrDist, CommMonitor::MonitorStats::readBandwidthHist, CommMonitor::MonitorStats::readBurstLengthHist, CommMonitor::MonitorStats::readLatencyHist, CommMonitor::MonitorStats::readTransHist, simSeconds, stats, CommMonitor::MonitorStats::totalReadBytes, CommMonitor::MonitorStats::totalWrittenBytes, CommMonitor::MonitorStats::writeAddrDist, CommMonitor::MonitorStats::writeBandwidthHist, CommMonitor::MonitorStats::writeBurstLengthHist, CommMonitor::MonitorStats::writeLatencyHist, and CommMonitor::MonitorStats::writeTransHist.
void CommMonitor::samplePeriodic () [private]
This function is called periodically at the end of each time bin.
Definition at line 589 of file comm_monitor.cc.
References curTick(), CommMonitor::MonitorStats::disableBandwidthHists, CommMonitor::MonitorStats::disableOutstandingHists, CommMonitor::MonitorStats::disableTransactionHists, CommMonitor::MonitorStats::outstandingReadReqs, CommMonitor::MonitorStats::outstandingReadsHist, CommMonitor::MonitorStats::outstandingWriteReqs, CommMonitor::MonitorStats::outstandingWritesHist, CommMonitor::MonitorStats::readBandwidthHist, CommMonitor::MonitorStats::readBytes, CommMonitor::MonitorStats::readTrans, CommMonitor::MonitorStats::readTransHist, Stats::DistBase< Derived, Stor >::sample(), samplePeriod, samplePeriodicEvent, samplePeriodTicks, EventManager::schedule(), simTicks, stats, Stats::ValueBase< Derived >::value(), CommMonitor::MonitorStats::writeBandwidthHist, CommMonitor::MonitorStats::writeTrans, CommMonitor::MonitorStats::writeTransHist, and CommMonitor::MonitorStats::writtenBytes.
void CommMonitor::startup () [private, virtual]
Schedule the first periodic event.
Reimplemented from SimObject.
Definition at line 627 of file comm_monitor.cc.
References curTick(), samplePeriodicEvent, samplePeriodTicks, and EventManager::schedule().
Member Data Documentation
MonitorMasterPort CommMonitor::masterPort [private]
Instance of master port, facing the memory side.
Definition at line 188 of file comm_monitor.hh.
Referenced by getAddrRanges(), getMasterPort(), init(), recvAtomic(), recvFunctional(), recvRespRetry(), recvTimingReq(), and recvTimingSnoopResp().
Addr CommMonitor::readAddrMask [private]
Address mask for sources of read accesses to be captured.
Definition at line 411 of file comm_monitor.hh.
Referenced by recvTimingReq().
Time CommMonitor::samplePeriod [private]
Definition at line 408 of file comm_monitor.hh.
Referenced by CommMonitor(), and samplePeriodic().
EventWrapper<CommMonitor, &CommMonitor::samplePeriodic> CommMonitor::samplePeriodicEvent [private]
Periodic event called at the end of each simulation time bin.
Definition at line 404 of file comm_monitor.hh.
Referenced by samplePeriodic(), and startup().
Tick CommMonitor::samplePeriodTicks [private]
Length of simulation time bin.
Definition at line 407 of file comm_monitor.hh.
Referenced by CommMonitor(), samplePeriodic(), and startup().
MonitorSlavePort CommMonitor::slavePort [private]
Instance of slave port, i.e.
on the CPU side
Definition at line 244 of file comm_monitor.hh.
Referenced by getSlavePort(), init(), isSnooping(), recvAtomicSnoop(), recvFunctionalSnoop(), recvRangeChange(), recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
StackDistCalc* CommMonitor::stackDistCalc [private]
Optional stack distance calculator.
Definition at line 420 of file comm_monitor.hh.
Referenced by recvAtomic(), and recvTimingReq().
MonitorStats CommMonitor::stats [private]
Instantiate stats.
Definition at line 417 of file comm_monitor.hh.
Referenced by recvTimingReq(), recvTimingResp(), regStats(), and samplePeriodic().
System* CommMonitor::system [private]
The system in which the monitor lives.
Definition at line 426 of file comm_monitor.hh.
Referenced by init().
ProtoOutputStream* CommMonitor::traceStream [private]
Output stream for a potential trace.
Definition at line 423 of file comm_monitor.hh.
Referenced by closeStreams(), CommMonitor(), init(), recvAtomic(), and recvTimingReq().
Addr CommMonitor::writeAddrMask [private]
Address mask for sources of write accesses to be captured.
Definition at line 414 of file comm_monitor.hh.
Referenced by recvTimingReq().
The documentation for this class was generated from the following files:
mem/comm_monitor.hh
mem/comm_monitor.cc