gem5: MSHRQueue Class Reference
MSHRQueue Class Reference
A Class for maintaining a list of pending and allocated memory requests.
#include <mshr_queue.hh>
Public Member Functions
MSHRQueue (const std::string &_label, int num_entries, int reserve, int demand_reserve, int index)
Create a queue with a given number of entries.
MSHR * findMatch (Addr blk_addr, bool is_secure) const
Find the first MSHR that matches the provided address.
bool findMatches (Addr blk_addr, bool is_secure, std::vector< MSHR * > &matches) const
Find and return all the matching entries in the provided vector.
MSHR * findPending (Addr blk_addr, bool is_secure) const
Find any pending requests that overlap the given request.
bool checkFunctional (PacketPtr pkt, Addr blk_addr)
MSHR * allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter order)
Allocates a new MSHR for the request and size.
void deallocate (MSHR *mshr)
Removes the given MSHR from the queue.
MSHR::Iterator deallocateOne (MSHR *mshr)
Remove a MSHR from the queue.
void moveToFront (MSHR *mshr)
Moves the MSHR to the front of the pending list if it is not in service.
void markInService (MSHR *mshr, bool pending_dirty_resp)
Mark the given MSHR as in service.
void markPending (MSHR *mshr)
Mark an in service entry as pending, used to resend a request.
void squash (int threadNum)
Squash outstanding requests with the given thread number.
bool forceDeallocateTarget (MSHR *mshr)
Deallocate top target, possibly freeing the MSHR.
bool havePending () const
Returns true if the pending list is not empty.
bool isFull () const
Returns true if there are no free entries.
bool canPrefetch () const
Returns true if sufficient mshrs for prefetch.
MSHR * getNextMSHR () const
Returns the MSHR at the head of the readyList.
Tick nextMSHRReadyTime () const
unsigned int drain (DrainManager *dm)
Determine if an object needs draining and register a DrainManager.
Public Attributes
int allocated
The number of allocated entries.
int inServiceEntries
The number of entries that have been forwarded to the bus.
const int index
The index of this queue within the cache (MSHR queue vs.
Private Member Functions
MSHR::Iterator addToReadyList (MSHR *mshr)
Private Attributes
const std::string label
Local label (for functional print requests).
const int numEntries
The total number of entries in this queue.
const int numReserve
The number of entries to hold in reserve.
const int demandReserve
The number of entries to reserve for future demand accesses.
std::vector< MSHR > registers
MSHR storage.
MSHR::List allocatedList
Holds pointers to all allocated entries.
MSHR::List readyList
Holds pointers to entries that haven't been sent to the bus.
MSHR::List freeList
Holds non allocated entries.
DrainManager * drainManager
Drain manager to inform of a completed drain.
Detailed Description
A Class for maintaining a list of pending and allocated memory requests.
Definition at line 60 of file mshr_queue.hh.
Constructor & Destructor Documentation
MSHRQueue::MSHRQueue (const std::string & _label, int num_entries, int reserve, int demand_reserve, int index)
Create a queue with a given number of entries.
Parameters:
num_entrys The number of entries in this queue.
reserve The minimum number of entries needed to satisfy any access.
demand_reserve The minimum number of entries needed to satisfy demand accesses.
Definition at line 54 of file mshr_queue.cc.
References freeList, ArmISA::i, numEntries, and registers.
Member Function Documentation
MSHR::Iterator MSHRQueue::addToReadyList (MSHR * mshr) [private]
Definition at line 131 of file mshr_queue.cc.
References ArmISA::i, readyList, and MSHR::readyTime.
Referenced by allocate(), and markPending().
MSHR * MSHRQueue::allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter order)
Allocates a new MSHR for the request and size.
This places the request as the first target in the MSHR.
Parameters:
blk_addr The address of the block.
blk_size The number of bytes to request.
pkt The original miss.
when_ready When should the MSHR be ready to act upon.
order The logical order of this MSHR
Returns:
The a pointer to the MSHR allocated.
Precondition:
There are free entries.
Definition at line 148 of file mshr_queue.cc.
References addToReadyList(), allocated, allocatedList, and freeList.
Referenced by BaseCache::allocateBufferInternal().
bool MSHRQueue::canPrefetch () const [inline]
Returns true if sufficient mshrs for prefetch.
Returns:
True if sufficient mshrs for prefetch.
Definition at line 239 of file mshr_queue.hh.
References allocated, demandReserve, numEntries, and numReserve.
Referenced by Cache::getNextMSHR(), Cache::nextMSHRReadyTime(), and Cache::recvTimingResp().
bool MSHRQueue::checkFunctional (PacketPtr pkt, Addr blk_addr)
Definition at line 104 of file mshr_queue.cc.
References allocatedList, label, Packet::popLabel(), and Packet::pushLabel().
Referenced by Cache::functionalAccess().
void MSHRQueue::deallocate (MSHR * mshr)
Removes the given MSHR from the queue.
This places the MSHR on the free list.
Parameters:
mshr
Definition at line 166 of file mshr_queue.cc.
References deallocateOne().
Referenced by markInService().
MSHR::Iterator MSHRQueue::deallocateOne (MSHR * mshr)
Remove a MSHR from the queue.
Returns an iterator into the allocatedList for faster squash implementation.
Parameters:
mshr The MSHR to remove.
Returns:
An iterator to the next entry in the allocatedList.
Definition at line 172 of file mshr_queue.cc.
References allocated, allocatedList, MSHR::allocIter, MSHR::deallocate(), DPRINTF, Drainable::Drained, drainManager, freeList, MSHR::inService, inServiceEntries, MSHR::readyIter, readyList, Drainable::setDrainState(), and DrainManager::signalDrainDone().
Referenced by deallocate(), forceDeallocateTarget(), and squash().
unsigned int MSHRQueue::drain (DrainManager * drainManager) [virtual]
Determine if an object needs draining and register a DrainManager.
When draining the state of an object, the simulator calls drain with a pointer to a drain manager. If the object does not need further simulation to drain internal buffers, it switched to the Drained state and returns 0, otherwise it switches to the Draining state and returns the number of times that it will call Event::process() on the drain event. Most objects are expected to return either 0 or 1.
Note:
An object that has entered the Drained state can be disturbed by other objects in the system and consequently be forced to enter the Draining state again. The simulator therefore repeats the draining process until all objects return 0 on the first call to drain().
Parameters:
drainManager DrainManager to use to inform the simulator when draining has completed.
Returns:
0 if the object is ready for serialization now, >0 if it needs further simulation.
Implements Drainable.
Definition at line 269 of file mshr_queue.cc.
References allocated, Drainable::Drained, Drainable::Draining, drainManager, and Drainable::setDrainState().
Referenced by BaseCache::drain().
MSHR * MSHRQueue::findMatch (Addr blk_addr, bool is_secure) const
Find the first MSHR that matches the provided address.
Parameters:
blk_addr The block address to find.
is_secure True if the target memory space is secure.
Returns:
Pointer to the matching MSHR, null if not found.
Definition at line 69 of file mshr_queue.cc.
References allocatedList.
Referenced by Cache::allocateBlock(), Cache::functionalAccess(), Cache::getNextMSHR(), Cache::inMissQueue(), Cache::recvTimingReq(), and Cache::recvTimingSnoopReq().
bool MSHRQueue::findMatches (Addr blk_addr, bool is_secure, std::vector< MSHR * > & matches) const
Find and return all the matching entries in the provided vector.
Parameters:
blk_addr The block address to find.
is_secure True if the target memory space is secure.
matches The vector to return pointers to the matching entries.
Returns:
True if any matches are found, false otherwise.
Definition at line 86 of file mshr_queue.cc.
References allocatedList.
Referenced by Cache::recvTimingSnoopReq().
MSHR * MSHRQueue::findPending (Addr blk_addr, bool is_secure) const
Find any pending requests that overlap the given request.
Parameters:
blk_addr Block address.
is_secure True if the target memory space is secure.
Returns:
A pointer to the earliest matching MSHR.
Definition at line 119 of file mshr_queue.cc.
References readyList.
Referenced by Cache::getNextMSHR().
bool MSHRQueue::forceDeallocateTarget (MSHR * mshr)
Deallocate top target, possibly freeing the MSHR.
Returns:
if MSHR queue is no longer full
Definition at line 229 of file mshr_queue.cc.
References deallocateOne(), MSHR::hasTargets(), isFull(), MSHR::popTarget(), and MSHR::promoteDeferredTargets().
Referenced by Cache::getTimingPacket().
MSHR* MSHRQueue::getNextMSHR () const [inline]
Returns the MSHR at the head of the readyList.
Returns:
The next request to service.
Definition at line 248 of file mshr_queue.hh.
References curTick(), and readyList.
Referenced by Cache::getNextMSHR().
bool MSHRQueue::havePending () const [inline]
Returns true if the pending list is not empty.
Returns:
True if there are outstanding requests.
Definition at line 221 of file mshr_queue.hh.
References readyList.
bool MSHRQueue::isFull () const [inline]
Returns true if there are no free entries.
Returns:
True if this queue is full.
Definition at line 230 of file mshr_queue.hh.
References allocated, numEntries, and numReserve.
Referenced by BaseCache::allocateBufferInternal(), forceDeallocateTarget(), Cache::getNextMSHR(), BaseCache::markInServiceInternal(), and Cache::squash().
void MSHRQueue::markInService (MSHR * mshr, bool pending_dirty_resp)
Mark the given MSHR as in service.
This removes the MSHR from the readyList or deallocates the MSHR if it does not expect a response.
Parameters:
mshr The MSHR to mark in service.
pending_dirty_resp Whether we expect a dirty response from another cache
Definition at line 205 of file mshr_queue.cc.
References deallocate(), inServiceEntries, MSHR::markInService(), MSHR::readyIter, and readyList.
Referenced by BaseCache::markInServiceInternal().
void MSHRQueue::markPending (MSHR * mshr)
Mark an in service entry as pending, used to resend a request.
Parameters:
mshr The MSHR to resend.
@ todo might want to add rerequests to front of pending list for performance.
Definition at line 216 of file mshr_queue.cc.
References addToReadyList(), MSHR::inService, inServiceEntries, and MSHR::readyIter.
void MSHRQueue::moveToFront (MSHR * mshr)
Moves the MSHR to the front of the pending list if it is not in service.
Parameters:
mshr The entry to move.
Definition at line 195 of file mshr_queue.cc.
References MSHR::inService, MSHR::readyIter, and readyList.
Tick MSHRQueue::nextMSHRReadyTime () const [inline]
Definition at line 256 of file mshr_queue.hh.
References MaxTick, and readyList.
Referenced by Cache::nextMSHRReadyTime().
void MSHRQueue::squash (int threadNum)
Squash outstanding requests with the given thread number.
If a request is in service, just squashes the targets.
Parameters:
threadNum The thread to squash.
Definition at line 245 of file mshr_queue.cc.
References allocatedList, deallocateOne(), MSHR::getNumTargets(), MSHR::hasTargets(), ArmISA::i, MSHR::inService, MSHR::popTarget(), and MSHR::threadNum.
Referenced by Cache::squash().
Member Data Documentation
int MSHRQueue::allocated
The number of allocated entries.
Definition at line 103 of file mshr_queue.hh.
Referenced by allocate(), canPrefetch(), deallocateOne(), drain(), isFull(), and Cache::outstandingMisses().
MSHR::List MSHRQueue::allocatedList [private]
Holds pointers to all allocated entries.
Definition at line 89 of file mshr_queue.hh.
Referenced by allocate(), checkFunctional(), deallocateOne(), findMatch(), findMatches(), and squash().
const int MSHRQueue::demandReserve [private]
The number of entries to reserve for future demand accesses.
Prevent prefetcher from taking all mshr entries
Definition at line 84 of file mshr_queue.hh.
Referenced by canPrefetch().
DrainManager* MSHRQueue::drainManager [private]
Drain manager to inform of a completed drain.
Definition at line 96 of file mshr_queue.hh.
Referenced by deallocateOne(), and drain().
MSHR::List MSHRQueue::freeList [private]
Holds non allocated entries.
Definition at line 93 of file mshr_queue.hh.
Referenced by allocate(), deallocateOne(), and MSHRQueue().
const int MSHRQueue::index
The index of this queue within the cache (MSHR queue vs.
write buffer).
Definition at line 108 of file mshr_queue.hh.
Referenced by BaseCache::allocateBufferInternal(), Cache::getTimingPacket(), and BaseCache::markInServiceInternal().
int MSHRQueue::inServiceEntries
The number of entries that have been forwarded to the bus.
Definition at line 105 of file mshr_queue.hh.
Referenced by deallocateOne(), Cache::getNextMSHR(), markInService(), and markPending().
const std::string MSHRQueue::label [private]
Local label (for functional print requests).
Definition at line 64 of file mshr_queue.hh.
Referenced by checkFunctional().
const int MSHRQueue::numEntries [private]
The total number of entries in this queue.
This number is set as the number of entries requested plus (numReserve - 1). This allows for the same number of effective entries while still maintaining the reserve.
Definition at line 72 of file mshr_queue.hh.
Referenced by canPrefetch(), isFull(), and MSHRQueue().
const int MSHRQueue::numReserve [private]
The number of entries to hold in reserve.
This is needed because copy operations can allocate upto 4 entries at one time.
Definition at line 78 of file mshr_queue.hh.
Referenced by canPrefetch(), and isFull().
MSHR::List MSHRQueue::readyList [private]
Holds pointers to entries that haven't been sent to the bus.
Definition at line 91 of file mshr_queue.hh.
Referenced by addToReadyList(), deallocateOne(), findPending(), getNextMSHR(), havePending(), markInService(), moveToFront(), and nextMSHRReadyTime().
std::vector<MSHR> MSHRQueue::registers [private]
MSHR storage.
Definition at line 87 of file mshr_queue.hh.
Referenced by MSHRQueue().
The documentation for this class was generated from the following files:
mem/cache/mshr_queue.hh
mem/cache/mshr_queue.cc