gem5: QueuedPrefetcher Class Reference
QueuedPrefetcher Class Reference
#include <queued.hh>
Classes
struct DeferredPacket
Public Member Functions
QueuedPrefetcher (const QueuedPrefetcherParams *p)
virtual ~QueuedPrefetcher ()
Tick notify (const PacketPtr &pkt)
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.
virtual void calculatePrefetch (const PacketPtr &pkt, std::vector< Addr > &addresses)=0
PacketPtr getPacket ()
Tick nextPrefetchReadyTime () const
void regStats ()
Register statistics for this object.
Protected Member Functions
bool inPrefetch (Addr address, bool is_secure) const
Protected Attributes
std::list< DeferredPacket > pfq
const unsigned queueSize
Maximum size of the prefetch queue.
const Cycles latency
Cycles after generation when a prefetch can first be issued.
const bool queueSquash
Squash queued prefetch if demand access observed.
const bool queueFilter
Filter prefetches if already queued.
const bool cacheSnoop
Snoop the cache before generating prefetch (cheating basically).
const bool tagPrefetch
Tag prefetch with PC of generating access?
Stats::Scalar pfIdentified
Stats::Scalar pfBufferHit
Stats::Scalar pfInCache
Stats::Scalar pfRemovedFull
Stats::Scalar pfSpanPage
Detailed Description
Definition at line 48 of file queued.hh.
Constructor & Destructor Documentation
QueuedPrefetcher::QueuedPrefetcher (const QueuedPrefetcherParams * p)
Definition at line 44 of file queued.cc.
QueuedPrefetcher::~QueuedPrefetcher () [virtual]
Definition at line 52 of file queued.cc.
References MipsISA::p, and pfq.
Member Function Documentation
virtual void QueuedPrefetcher::calculatePrefetch (const PacketPtr & pkt, std::vector< Addr > & addresses) [pure virtual]
Implemented in StridePrefetcher, and TaggedPrefetcher.
Referenced by notify().
PacketPtr QueuedPrefetcher::getPacket () [virtual]
Implements BasePrefetcher.
Definition at line 160 of file queued.cc.
References DPRINTF, Packet::getAddr(), BasePrefetcher::pfIssued, and pfq.
bool QueuedPrefetcher::inPrefetch (Addr address, bool is_secure) const [protected]
Definition at line 179 of file queued.cc.
References pfq.
Referenced by notify().
Tick QueuedPrefetcher::nextPrefetchReadyTime () const [inline, virtual]
Implements BasePrefetcher.
Definition at line 99 of file queued.hh.
References MaxTick, and pfq.
Tick QueuedPrefetcher::notify (const PacketPtr & pkt) [virtual]
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.
)
Return values:
Time of next prefetch availability, or MaxTick if none.
Implements BasePrefetcher.
Definition at line 62 of file queued.cc.
References Packet::allocate(), BasePrefetcher::blkSize, BasePrefetcher::cache, cacheSnoop, calculatePrefetch(), ClockedObject::clockPeriod(), Request::contextId(), curTick(), BaseCache::deassertMemSideBusRequest(), DPRINTF, Packet::getAddr(), Request::getPC(), MemCmd::HardPFReq, Request::hasContextId(), Request::hasPC(), BasePrefetcher::inCache(), BasePrefetcher::inMissQueue(), inPrefetch(), Packet::isSecure(), latency, BasePrefetcher::masterId, MaxTick, BasePrefetcher::observeAccess(), pfBufferHit, pfIdentified, pfInCache, pfq, pfRemovedFull, ContextSwitchTaskId::Prefetcher, queueFilter, queueSize, queueSquash, Packet::req, BaseCache::Request_PF, Request::SECURE, Request::setFlags(), Request::setPC(), Request::setThreadContext(), tagPrefetch, Request::taskId(), and Request::threadId().
void QueuedPrefetcher::regStats () [virtual]
Register statistics for this object.
Reimplemented from BasePrefetcher.
Definition at line 190 of file queued.cc.
References SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), pfBufferHit, pfIdentified, pfInCache, pfRemovedFull, and pfSpanPage.
Member Data Documentation
const bool QueuedPrefetcher::cacheSnoop [protected]
Snoop the cache before generating prefetch (cheating basically).
Definition at line 74 of file queued.hh.
Referenced by notify().
const Cycles QueuedPrefetcher::latency [protected]
Cycles after generation when a prefetch can first be issued.
Definition at line 65 of file queued.hh.
Referenced by notify().
Stats::Scalar QueuedPrefetcher::pfBufferHit [protected]
Definition at line 83 of file queued.hh.
Referenced by notify(), and regStats().
Stats::Scalar QueuedPrefetcher::pfIdentified [protected]
Definition at line 82 of file queued.hh.
Referenced by notify(), and regStats().
Stats::Scalar QueuedPrefetcher::pfInCache [protected]
Definition at line 84 of file queued.hh.
Referenced by notify(), and regStats().
std::list<DeferredPacket> QueuedPrefetcher::pfq [protected]
Definition at line 57 of file queued.hh.
Referenced by getPacket(), inPrefetch(), nextPrefetchReadyTime(), notify(), and ~QueuedPrefetcher().
Stats::Scalar QueuedPrefetcher::pfRemovedFull [protected]
Definition at line 85 of file queued.hh.
Referenced by notify(), and regStats().
Stats::Scalar QueuedPrefetcher::pfSpanPage [protected]
Definition at line 86 of file queued.hh.
Referenced by TaggedPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), and regStats().
const bool QueuedPrefetcher::queueFilter [protected]
Filter prefetches if already queued.
Definition at line 71 of file queued.hh.
Referenced by notify().
const unsigned QueuedPrefetcher::queueSize [protected]
Maximum size of the prefetch queue.
Definition at line 62 of file queued.hh.
Referenced by notify().
const bool QueuedPrefetcher::queueSquash [protected]
Squash queued prefetch if demand access observed.
Definition at line 68 of file queued.hh.
Referenced by notify().
const bool QueuedPrefetcher::tagPrefetch [protected]
Tag prefetch with PC of generating access?
Definition at line 77 of file queued.hh.
Referenced by notify().
The documentation for this class was generated from the following files:
mem/cache/prefetch/queued.hh
mem/cache/prefetch/queued.cc