gem5: CacheBlk Class Reference
CacheBlk Class Reference
A Basic Cache block.
#include <blk.hh>
Classes
class Lock
Represents that the indicated thread context has a "lock" on the block, in the LL/SC sense.
Public Types
typedef unsigned State
block state: OR of CacheBlkStatusBit
Public Member Functions
CacheBlk ()
const CacheBlk & operator= (const CacheBlk &rhs)
Copy the state of the given block into this one.
bool isWritable () const
Checks the write permissions of this block.
bool isReadable () const
Checks the read permissions of this block.
bool isValid () const
Checks that a block is valid.
void invalidate ()
Invalidate the block and clear all state.
bool isDirty () const
Check to see if a block has been written.
bool isReferenced () const
Check if this block has been referenced.
bool wasPrefetched () const
Check if this block was the result of a hardware prefetch, yet to be touched.
bool isSecure () const
Check if this block holds data from the secure memory space.
void trackLoadLocked (PacketPtr pkt)
Track the fact that a local locked was issued to the block.
void clearLoadLocks (Request *req=NULL)
Clear the list of valid load locks.
std::string print () const
Pretty-print a tag, and interpret state bits to readable form including mapping to a MOESI stat.
bool checkWrite (PacketPtr pkt)
Handle interaction of load-locked operations and stores.
Public Attributes
uint32_t task_id
Task Id associated with this block.
int asid
The address space ID of this block.
Addr tag
Data block tag value.
uint8_t * data
Contains a copy of the data in this block for easy access.
int size
the number of bytes stored in this block.
State status
The current status of this block.
Tick whenReady
Which curTick() will this block be accessable.
int set
The set this block belongs to.
bool isTouched
whether this block has been touched
int refCount
Number of references to this block since it was brought in.
int srcMasterId
holds the source requestor ID for this block.
Tick tickInserted
unsigned int tag_refcount
Number of references to this block since it was brought in.
Protected Attributes
std::list< Lock > lockList
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Detailed Description
A Basic Cache block.
Contains the tag, status, and a pointer to data.
Definition at line 82 of file blk.hh.
Member Typedef Documentation
typedef unsigned CacheBlk::State
block state: OR of CacheBlkStatusBit
Definition at line 104 of file blk.hh.
Constructor & Destructor Documentation
CacheBlk::CacheBlk () [inline]
Definition at line 174 of file blk.hh.
Member Function Documentation
bool CacheBlk::checkWrite (PacketPtr pkt) [inline]
Handle interaction of load-locked operations and stores.
Returns:
True if write should proceed, false otherwise. Returns false only in the case of a failed store conditional.
Definition at line 354 of file blk.hh.
References clearLoadLocks(), ArmISA::i, Packet::isLLSC(), lockList, Packet::req, and Request::setExtraData().
Referenced by Cache::satisfyCpuSideRequest().
void CacheBlk::clearLoadLocks (Request * req = NULL) [inline]
Clear the list of valid load locks.
Should be called whenever block is written to or invalidated.
Definition at line 295 of file blk.hh.
References lockList.
Referenced by checkWrite(), FALRU::clearLocks(), BaseSetAssoc::clearLocks(), and invalidate().
void CacheBlk::invalidate () [inline]
Invalidate the block and clear all state.
Definition at line 235 of file blk.hh.
References clearLoadLocks(), isTouched, and status.
Referenced by Cache::access(), BaseSetAssoc::BaseSetAssoc(), Cache::handleSnoop(), BaseSetAssoc::insertBlock(), Cache::invalidateVisitor(), Cache::recvAtomic(), Cache::recvTimingResp(), and Cache::satisfyCpuSideRequest().
bool CacheBlk::isDirty () const [inline]
Check to see if a block has been written.
Returns:
True if the block is dirty.
Definition at line 246 of file blk.hh.
References BlkDirty, and status.
Referenced by Cache::access(), Cache::allocateBlock(), Cache::functionalAccess(), Cache::handleSnoop(), Cache::invalidateVisitor(), print(), CacheBlkPrintWrapper::print(), Cache::recvTimingResp(), Cache::satisfyCpuSideRequest(), Cache::writebackBlk(), and Cache::writebackVisitor().
bool CacheBlk::isReadable () const [inline]
Checks the read permissions of this block.
Note that a block can be valid but not readable if there is an outstanding write upgrade miss.
Returns:
True if the block is readable.
Definition at line 217 of file blk.hh.
References BlkReadable, BlkValid, and status.
Referenced by Cache::access(), and print().
bool CacheBlk::isReferenced () const [inline]
Check if this block has been referenced.
Returns:
True if the block has been referenced.
Definition at line 255 of file blk.hh.
References BlkReferenced, and status.
bool CacheBlk::isSecure () const [inline]
Check if this block holds data from the secure memory space.
Returns:
True if the block holds data from the secure memory space.
Definition at line 274 of file blk.hh.
References BlkSecure, and status.
Referenced by Cache::allocateBlock(), CacheBlkPrintWrapper::print(), and Cache::writebackBlk().
bool CacheBlk::isValid () const [inline]
Checks that a block is valid.
Returns:
True if the block is valid.
Definition at line 227 of file blk.hh.
References BlkValid, and status.
Referenced by Cache::access(), FALRU::accessBlock(), Cache::allocateBlock(), FALRU::findBlock(), RandomRepl::findVictim(), LRU::findVictim(), FLIP::findVictim(), FALRU::findVictim(), BaseSetAssoc::findVictim(), Cache::functionalAccess(), Cache::getBusPacket(), Cache::handleFill(), Cache::handleSnoop(), BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), Cache::invalidateVisitor(), BaseSetAssoc::print(), print(), CacheBlkPrintWrapper::print(), Cache::recvAtomic(), Cache::recvTimingReq(), Cache::recvTimingResp(), Cache::satisfyCpuSideRequest(), LRUProfiler::should_be_profiled(), FLIPProfiler::should_be_profiled(), Cache::writebackBlk(), and Cache::writebackVisitor().
bool CacheBlk::isWritable () const [inline]
Checks the write permissions of this block.
Returns:
True if the block is writable.
Definition at line 205 of file blk.hh.
References BlkValid, BlkWritable, and status.
Referenced by Cache::access(), Cache::allocateBlock(), Cache::getBusPacket(), Cache::handleSnoop(), print(), CacheBlkPrintWrapper::print(), Cache::recvTimingReq(), Cache::satisfyCpuSideRequest(), and Cache::writebackBlk().
const CacheBlk& CacheBlk::operator= (const CacheBlk & rhs) [inline]
Copy the state of the given block into this one.
Parameters:
rhs The block to copy.
Returns:
a const reference to this block.
Definition at line 187 of file blk.hh.
References asid, data, refCount, set, size, status, tag, task_id, and whenReady.
std::string CacheBlk::print () const [inline]
Pretty-print a tag, and interpret state bits to readable form including mapping to a MOESI stat.
Returns:
string with basic state information
state M O E S I writable 1 0 1 0 0 dirty 1 1 0 0 0 valid 1 1 1 1 0
state writable dirty valid M 1 1 1 O 0 1 1 E 1 0 1 S 0 0 1 I 0 0 0
Definition at line 319 of file blk.hh.
References csprintf(), isDirty(), isReadable(), isValid(), isWritable(), ArmISA::s, status, and tag.
Referenced by Cache::access(), Cache::handleFill(), Cache::handleSnoop(), and BaseSetAssoc::print().
void CacheBlk::trackLoadLocked (PacketPtr pkt) [inline]
Track the fact that a local locked was issued to the block.
If multiple LLs get issued from the same context we could have redundant records on the list, but that's OK, as they'll all get blown away at the next store.
Definition at line 285 of file blk.hh.
References Packet::isLLSC(), X86ISA::Lock, lockList, and Packet::req.
Referenced by Cache::satisfyCpuSideRequest().
bool CacheBlk::wasPrefetched () const [inline]
Check if this block was the result of a hardware prefetch, yet to be touched.
Returns:
True if the block was a hardware prefetch, unaccesed.
Definition at line 265 of file blk.hh.
References BlkHWPrefetched, and status.
Referenced by Cache::recvTimingReq().
Member Data Documentation
int CacheBlk::asid
The address space ID of this block.
Definition at line 89 of file blk.hh.
Referenced by operator=().
uint8_t* CacheBlk::data
Contains a copy of the data in this block for easy access.
This is used for efficient execution when the data could be actually stored in another format (COW, compressed, sub-blocked, etc). In all cases the data stored here should be kept consistant with the actual data referenced by this block.
Definition at line 99 of file blk.hh.
Referenced by Cache::access(), BaseSetAssoc::BaseSetAssoc(), Cache::Cache(), Cache::cmpAndSwap(), Cache::functionalAccess(), Cache::handleFill(), Cache::handleSnoop(), operator=(), Cache::satisfyCpuSideRequest(), Cache::writebackBlk(), Cache::writebackVisitor(), and Cache::~Cache().
bool CacheBlk::isTouched
whether this block has been touched
Reimplemented in FALRUBlk.
Definition at line 119 of file blk.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), BaseSetAssoc::insertBlock(), and invalidate().
std::list<Lock> CacheBlk::lockList [protected]
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Definition at line 170 of file blk.hh.
Referenced by checkWrite(), clearLoadLocks(), and trackLoadLocked().
int CacheBlk::refCount
Number of references to this block since it was brought in.
Definition at line 122 of file blk.hh.
Referenced by BaseSetAssoc::accessBlock(), BaseSetAssoc::cleanupRefs(), BaseSetAssoc::insertBlock(), and operator=().
int CacheBlk::set
The set this block belongs to.
Todo:
Move this into subclasses when we fix CacheTags to use them.
Definition at line 116 of file blk.hh.
Referenced by LRUProfiler::accessBlock(), LRU::accessBlock(), FLIPProfiler::accessBlock(), FLIP::accessBlock(), DIP::accessBlock(), Cache::allocateBlock(), BaseSetAssoc::BaseSetAssoc(), RandomRepl::findVictim(), LRUProfiler::findVictim(), FLIPProfiler::findVictim(), Cache::handleFill(), LRUProfiler::insertBlock(), FLIPProfiler::insertBlock(), LRUProfiler::invalidate(), LRU::invalidate(), FLIPProfiler::invalidate(), FLIP::invalidate(), operator=(), Cache::writebackBlk(), and Cache::writebackVisitor().
int CacheBlk::size
the number of bytes stored in this block.
Definition at line 101 of file blk.hh.
Referenced by BaseSetAssoc::BaseSetAssoc(), and operator=().
int CacheBlk::srcMasterId
holds the source requestor ID for this block.
Definition at line 125 of file blk.hh.
Referenced by BaseSetAssoc::insertBlock(), and BaseSetAssoc::invalidate().
State CacheBlk::status
The current status of this block.
See also:
CacheBlockStatusBits
Definition at line 107 of file blk.hh.
Referenced by Cache::access(), Cache::cmpAndSwap(), Cache::handleFill(), Cache::handleSnoop(), invalidate(), isDirty(), isReadable(), isReferenced(), isSecure(), isValid(), isWritable(), operator=(), print(), Cache::recvAtomic(), Cache::recvTimingReq(), Cache::recvTimingResp(), Cache::satisfyCpuSideRequest(), wasPrefetched(), Cache::writebackBlk(), and Cache::writebackVisitor().
Addr CacheBlk::tag
Data block tag value.
Definition at line 91 of file blk.hh.
Referenced by LRUProfiler::accessBlock(), LRU::accessBlock(), FLIPProfiler::accessBlock(), FALRU::accessBlock(), DIP::accessBlock(), Cache::allocateBlock(), BaseSetAssoc::BaseSetAssoc(), FALRU::findBlock(), RandomRepl::findVictim(), LRUProfiler::findVictim(), LRU::findVictim(), FLIPProfiler::findVictim(), FLIP::findVictim(), FALRU::findVictim(), Cache::handleFill(), LRUProfiler::insertBlock(), FLIPProfiler::insertBlock(), BaseSetAssoc::insertBlock(), LRUProfiler::invalidate(), FLIPProfiler::invalidate(), operator=(), print(), Cache::writebackBlk(), and Cache::writebackVisitor().
unsigned int CacheBlk::tag_refcount
Number of references to this block since it was brought in.
(for tags-in-use)
Definition at line 130 of file blk.hh.
Referenced by FLIP::accessBlock(), and FLIP::insertBlock().
uint32_t CacheBlk::task_id
Task Id associated with this block.
Definition at line 86 of file blk.hh.
Referenced by BaseSetAssoc::computeStats(), BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), operator=(), Cache::writebackBlk(), and Cache::writebackVisitor().
Tick CacheBlk::tickInserted
Definition at line 127 of file blk.hh.
Referenced by BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), and Cache::writebackBlk().
Tick CacheBlk::whenReady
Which curTick() will this block be accessable.
Definition at line 110 of file blk.hh.
Referenced by BaseSetAssoc::accessBlock(), BaseSetAssoc::BaseSetAssoc(), Cache::handleFill(), and operator=().
The documentation for this class was generated from the following file:
mem/cache/blk.hh