gem5: ArmISA::BranchImmReg64 Class Reference
ArmISA::BranchImmReg64 Class Reference
#include <branch64.hh>
Public Member Functions
BranchImmReg64 (const char *mnem, ExtMachInst _machInst, OpClass __opClass, int64_t _imm, IntRegIndex _op1)
ArmISA::PCState branchTarget (const ArmISA::PCState &branchPC) const
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
int64_t imm
IntRegIndex op1
Detailed Description
Definition at line 120 of file branch64.hh.
Constructor & Destructor Documentation
ArmISA::BranchImmReg64::BranchImmReg64 (const char * mnem, ExtMachInst _machInst, OpClass __opClass, int64_t _imm, IntRegIndex _op1) [inline]
Definition at line 127 of file branch64.hh.
Member Function Documentation
ArmISA::PCState ArmISA::BranchImmReg64::branchTarget (const ArmISA::PCState & branchPC) const
Definition at line 55 of file branch64.cc.
References imm.
std::string ArmISA::BranchImmReg64::generateDisassembly (Addr pc, const SymbolTable * symtab) const [virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 123 of file branch64.cc.
References ccprintf(), imm, op1, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), ArmISA::ArmStaticInst::printTarget(), and ArmISA::ss.
Member Data Documentation
int64_t ArmISA::BranchImmReg64::imm [protected]
Definition at line 123 of file branch64.hh.
Referenced by branchTarget(), and generateDisassembly().
IntRegIndex ArmISA::BranchImmReg64::op1 [protected]
Definition at line 124 of file branch64.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/branch64.hh
arch/arm/insts/branch64.cc