gem5: MSHR Class Reference
MSHR Class Reference
Miss Status and handling Register.
#include <mshr.hh>
Classes
class Target
class TargetList
Public Types
typedef std::list< MSHR * > List
A list of MSHRs.
typedef List::iterator Iterator
MSHR list iterator.
typedef List::const_iterator ConstIterator
MSHR list const_iterator.
Public Member Functions
bool needsExclusive () const
The pending* and post* flags are only valid if inService is true.
bool isPendingDirty () const
bool hasPostInvalidate () const
bool hasPostDowngrade () const
bool isUncacheable () const
void allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter _order)
Allocate a miss to this MSHR.
bool markInService (bool pending_dirty_resp)
void clearDownstreamPending ()
void deallocate ()
Mark this MSHR as free.
void allocateTarget (PacketPtr target, Tick when, Counter order)
Add a request to the list of targets.
bool handleSnoop (PacketPtr target, Counter order)
MSHR ()
A simple constructor.
int getNumTargets () const
Returns the current number of allocated targets.
bool hasTargets () const
Returns true if there are targets left.
Target * getTarget ()
Returns a reference to the first target.
void popTarget ()
Pop first target.
bool isForwardNoResponse () const
bool promoteDeferredTargets ()
void handleFill (PacketPtr pkt, CacheBlk *blk)
bool checkFunctional (PacketPtr pkt)
void print (std::ostream &os, int verbosity=0, const std::string &prefix="") const
Prints the contents of this MSHR for debugging.
std::string print () const
A no-args wrapper of print(std::ostream.
Public Attributes
MSHRQueue * queue
Pointer to queue containing this MSHR.
Counter order
Order number assigned by the miss queue.
Addr blkAddr
Block aligned address of the MSHR.
unsigned blkSize
Block size of the cache.
bool isSecure
True if the request targets the secure memory space.
bool inService
True if the request has been sent to the bus.
bool isForward
True if the request is just a simple forward from an upper level.
ThreadID threadNum
Thread number of the miss.
Private Attributes
Tick readyTime
Cycle when ready to issue.
bool _isUncacheable
True if the request is uncacheable.
bool downstreamPending
Flag set by downstream caches.
bool pendingDirty
Will we have a dirty copy after this request?
bool postInvalidate
Did we snoop an invalidate while waiting for data?
bool postDowngrade
Did we snoop a read while waiting for data?
uint8_t * data
Data buffer (if needed).
Iterator readyIter
Pointer to this MSHR on the ready list.
Iterator allocIter
Pointer to this MSHR on the allocated list.
TargetList targets
List of all requests that match the address.
TargetList deferredTargets
Friends
class MSHRQueue
Consider the MSHRQueue a friend to avoid making everything public.
Detailed Description
Miss Status and handling Register.
This class keeps all the information needed to handle a cache miss including a list of target requests.
See also:
gem5 Memory System
Definition at line 64 of file mshr.hh.
Member Typedef Documentation
typedef List::const_iterator MSHR::ConstIterator
MSHR list const_iterator.
Definition at line 141 of file mshr.hh.
typedef List::iterator MSHR::Iterator
MSHR list iterator.
Definition at line 139 of file mshr.hh.
typedef std::list<MSHR *> MSHR::List
A list of MSHRs.
Definition at line 137 of file mshr.hh.
Constructor & Destructor Documentation
MSHR::MSHR ()
A simple constructor.
Definition at line 64 of file mshr.cc.
Member Function Documentation
void MSHR::allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter _order)
Allocate a miss to this MSHR.
Parameters:
blk_addr The address of the block.
blk_size The number of bytes to request.
pkt The original miss.
when_ready When should the MSHR be ready to act upon.
_order The logical order of this MSHR
Definition at line 201 of file mshr.cc.
References _isUncacheable, MSHR::TargetList::add(), blkAddr, blkSize, Packet::cmd, data, deferredTargets, downstreamPending, MSHR::Target::FromCPU, MSHR::Target::FromPrefetcher, MemCmd::HardPFReq, inService, isForward, MSHR::TargetList::isReset(), Packet::isSecure(), isSecure, Request::isUncacheable(), order, readyTime, Packet::req, targets, and threadNum.
void MSHR::allocateTarget (PacketPtr target, Tick when, Counter order)
Add a request to the list of targets.
Parameters:
target The target.
Definition at line 274 of file mshr.cc.
References _isUncacheable, MSHR::TargetList::add(), Packet::cmd, deferredTargets, MSHR::Target::FromCPU, MemCmd::HardPFReq, hasPostDowngrade(), hasPostInvalidate(), inService, isForward, isPendingDirty(), Packet::needsExclusive(), replaceUpgrade(), and targets.
bool MSHR::checkFunctional (PacketPtr pkt)
Definition at line 457 of file mshr.cc.
References blkAddr, blkSize, MSHR::TargetList::checkFunctional(), Packet::checkFunctional(), deferredTargets, Packet::isPrint(), isSecure, and targets.
void MSHR::clearDownstreamPending ()
Definition at line 227 of file mshr.cc.
References MSHR::TargetList::clearDownstreamPending(), downstreamPending, and targets.
Referenced by MSHR::TargetList::clearDownstreamPending().
void MSHR::deallocate ()
Mark this MSHR as free.
Definition at line 262 of file mshr.cc.
References deferredTargets, inService, MSHR::TargetList::isReset(), MSHR::TargetList::resetFlags(), and targets.
Referenced by MSHRQueue::deallocateOne().
int MSHR::getNumTargets () const [inline]
Returns the current number of allocated targets.
Returns:
The current number of allocated targets.
Definition at line 248 of file mshr.hh.
References deferredTargets, and targets.
Referenced by isForwardNoResponse(), markInService(), and MSHRQueue::squash().
Target* MSHR::getTarget () [inline]
Returns a reference to the first target.
Returns:
A pointer to the first target.
Definition at line 261 of file mshr.hh.
References hasTargets(), and targets.
Referenced by Cache::getTimingPacket(), and Cache::recvTimingResp().
void MSHR::handleFill (PacketPtr pkt, CacheBlk * blk)
Definition at line 430 of file mshr.cc.
References MSHR::TargetList::clearDownstreamPending(), deferredTargets, downstreamPending, hasPostDowngrade(), hasPostInvalidate(), MSHR::TargetList::needsExclusive, MSHR::TargetList::resetFlags(), Packet::sharedAsserted(), and targets.
bool MSHR::handleSnoop (PacketPtr target, Counter order)
Definition at line 313 of file mshr.cc.
References MSHR::TargetList::add(), Packet::assertMemInhibit(), Packet::assertShared(), Packet::cmd, Packet::cmdString(), curTick(), deferredTargets, downstreamPending, DPRINTF, MSHR::Target::FromSnoop, Packet::getAddr(), Packet::getSize(), hasPostInvalidate(), inService, Packet::isExpressSnoop(), Packet::isInvalidate(), isPendingDirty(), Request::isUncacheable(), MSHR::TargetList::needsExclusive, Packet::needsExclusive(), postDowngrade, postInvalidate, MSHR::TargetList::replaceUpgrades(), Packet::req, Packet::setSupplyExclusive(), and targets.
bool MSHR::hasPostDowngrade () const [inline]
Definition at line 180 of file mshr.hh.
References inService, and postDowngrade.
Referenced by allocateTarget(), handleFill(), and print().
bool MSHR::hasPostInvalidate () const [inline]
Definition at line 176 of file mshr.hh.
References inService, and postInvalidate.
Referenced by allocateTarget(), handleFill(), handleSnoop(), and print().
bool MSHR::hasTargets () const [inline]
Returns true if there are targets left.
Returns:
true if there are targets
Definition at line 255 of file mshr.hh.
References targets.
Referenced by MSHRQueue::forceDeallocateTarget(), getTarget(), and MSHRQueue::squash().
bool MSHR::isForwardNoResponse () const [inline]
Definition at line 275 of file mshr.hh.
References MSHR::Target::FromCPU, getNumTargets(), Packet::needsResponse(), MSHR::Target::pkt, MSHR::Target::source, and targets.
Referenced by Cache::getTimingPacket(), markInService(), print(), and Cache::CacheReqPacketQueue::sendDeferredPacket().
bool MSHR::isPendingDirty () const [inline]
Definition at line 172 of file mshr.hh.
References inService, and pendingDirty.
Referenced by allocateTarget(), Cache::functionalAccess(), and handleSnoop().
bool MSHR::isUncacheable () const [inline]
Definition at line 212 of file mshr.hh.
References _isUncacheable.
bool MSHR::markInService (bool pending_dirty_resp)
Definition at line 237 of file mshr.cc.
References MSHR::TargetList::clearDownstreamPending(), downstreamPending, getNumTargets(), inService, isForwardNoResponse(), MSHR::TargetList::needsExclusive, pendingDirty, popTarget(), postDowngrade, postInvalidate, and targets.
Referenced by MSHRQueue::markInService().
bool MSHR::needsExclusive () const [inline]
The pending* and post* flags are only valid if inService is true.
Using the accessor functions lets us detect if these flags are accessed improperly. True if we need to get an exclusive copy of the block.
Definition at line 170 of file mshr.hh.
References MSHR::TargetList::needsExclusive, and targets.
Referenced by Cache::allocateBlock(), Cache::getTimingPacket(), and print().
void MSHR::popTarget () [inline]
Pop first target.
Definition at line 270 of file mshr.hh.
References targets.
Referenced by MSHRQueue::forceDeallocateTarget(), markInService(), and MSHRQueue::squash().
std::string MSHR::print () const
A no-args wrapper of print(std::ostream.
..) meant to be invoked from DPRINTFs avoiding string overheads in fast mode
Returns:
string with mshr fields + [deferred]targets
Definition at line 496 of file mshr.cc.
void MSHR::print (std::ostream & os, int verbosity = 0, const std::string & prefix = "") const [virtual]
Prints the contents of this MSHR for debugging.
Implements Printable.
Definition at line 473 of file mshr.cc.
References _isUncacheable, blkAddr, blkSize, ccprintf(), deferredTargets, downstreamPending, hasPostDowngrade(), hasPostInvalidate(), inService, isForward, isForwardNoResponse(), isSecure, needsExclusive(), MSHR::TargetList::print(), and targets.
bool MSHR::promoteDeferredTargets ()
Definition at line 409 of file mshr.cc.
References curTick(), deferredTargets, order, readyTime, MSHR::TargetList::resetFlags(), and targets.
Referenced by MSHRQueue::forceDeallocateTarget().
Friends And Related Function Documentation
friend class MSHRQueue [friend]
Consider the MSHRQueue a friend to avoid making everything public.
Definition at line 70 of file mshr.hh.
Member Data Documentation
bool MSHR::_isUncacheable [private]
True if the request is uncacheable.
Definition at line 78 of file mshr.hh.
Referenced by allocate(), allocateTarget(), isUncacheable(), and print().
Iterator MSHR::allocIter [private]
Pointer to this MSHR on the allocated list.
See also:
MissQueue, MSHRQueue::allocatedList
Definition at line 203 of file mshr.hh.
Referenced by MSHRQueue::deallocateOne().
Addr MSHR::blkAddr
Block aligned address of the MSHR.
Definition at line 150 of file mshr.hh.
Referenced by allocate(), checkFunctional(), Cache::getNextMSHR(), Cache::getTimingPacket(), and print().
unsigned MSHR::blkSize
Block size of the cache.
Definition at line 153 of file mshr.hh.
Referenced by allocate(), checkFunctional(), and print().
uint8_t* MSHR::data [private]
Data buffer (if needed).
Currently used only for pending upgrade handling.
Definition at line 191 of file mshr.hh.
Referenced by allocate().
TargetList MSHR::deferredTargets [private]
Definition at line 208 of file mshr.hh.
Referenced by allocate(), allocateTarget(), checkFunctional(), deallocate(), getNumTargets(), handleFill(), handleSnoop(), print(), and promoteDeferredTargets().
bool MSHR::downstreamPending [private]
Flag set by downstream caches.
Definition at line 81 of file mshr.hh.
Referenced by MSHR::TargetList::add(), allocate(), clearDownstreamPending(), handleFill(), handleSnoop(), markInService(), and print().
bool MSHR::inService
True if the request has been sent to the bus.
Definition at line 159 of file mshr.hh.
Referenced by allocate(), allocateTarget(), deallocate(), MSHRQueue::deallocateOne(), Cache::functionalAccess(), handleSnoop(), hasPostDowngrade(), hasPostInvalidate(), isPendingDirty(), markInService(), MSHRQueue::markPending(), MSHRQueue::moveToFront(), print(), and MSHRQueue::squash().
bool MSHR::isForward
True if the request is just a simple forward from an upper level.
Definition at line 162 of file mshr.hh.
Referenced by allocate(), allocateTarget(), Cache::getTimingPacket(), and print().
bool MSHR::isSecure
True if the request targets the secure memory space.
Definition at line 156 of file mshr.hh.
Referenced by allocate(), checkFunctional(), Cache::getNextMSHR(), Cache::getTimingPacket(), and print().
Counter MSHR::order
Order number assigned by the miss queue.
Definition at line 147 of file mshr.hh.
Referenced by allocate(), Cache::getNextMSHR(), and promoteDeferredTargets().
bool MSHR::pendingDirty [private]
Will we have a dirty copy after this request?
Definition at line 84 of file mshr.hh.
Referenced by isPendingDirty(), and markInService().
bool MSHR::postDowngrade [private]
Did we snoop a read while waiting for data?
Definition at line 90 of file mshr.hh.
Referenced by handleSnoop(), hasPostDowngrade(), and markInService().
bool MSHR::postInvalidate [private]
Did we snoop an invalidate while waiting for data?
Definition at line 87 of file mshr.hh.
Referenced by handleSnoop(), hasPostInvalidate(), and markInService().
MSHRQueue* MSHR::queue
Pointer to queue containing this MSHR.
Definition at line 144 of file mshr.hh.
Referenced by Cache::getTimingPacket(), and BaseCache::markInServiceInternal().
Iterator MSHR::readyIter [private]
Pointer to this MSHR on the ready list.
See also:
MissQueue, MSHRQueue::readyList
Definition at line 197 of file mshr.hh.
Referenced by MSHRQueue::deallocateOne(), MSHRQueue::markInService(), MSHRQueue::markPending(), and MSHRQueue::moveToFront().
Tick MSHR::readyTime [private]
Cycle when ready to issue.
Definition at line 75 of file mshr.hh.
Referenced by MSHRQueue::addToReadyList(), allocate(), and promoteDeferredTargets().
TargetList MSHR::targets [private]
List of all requests that match the address.
Definition at line 206 of file mshr.hh.
Referenced by allocate(), allocateTarget(), checkFunctional(), clearDownstreamPending(), deallocate(), getNumTargets(), getTarget(), handleFill(), handleSnoop(), hasTargets(), isForwardNoResponse(), markInService(), needsExclusive(), popTarget(), print(), and promoteDeferredTargets().
ThreadID MSHR::threadNum
Thread number of the miss.
Definition at line 185 of file mshr.hh.
Referenced by allocate(), MSHRQueue::squash(), and Cache::squash().
The documentation for this class was generated from the following files:
mem/cache/mshr.hh
mem/cache/mshr.cc