gem5: SparcISA::TLB Class Reference
SparcISA::TLB Class Reference
#include <tlb.hh>
Public Types
typedef SparcTLBParams Params
Public Member Functions
TlbEntry * lookup (Addr va, int partition_id, bool real, int context_id=0, bool update_used=true)
lookup an entry in the TLB based on the partition id, and real bit if real is true or the partition id, and context id if real is false.
void flushAll ()
Remove all entries from the TLB.
TLB (const Params *p)
void takeOverFrom (BaseTLB *otlb)
void demapPage (Addr vaddr, uint64_t asn)
void dumpAll ()
Fault translateAtomic (RequestPtr req, ThreadContext *tc, Mode mode)
void translateTiming (RequestPtr req, ThreadContext *tc, Translation *translation, Mode mode)
Fault translateFunctional (RequestPtr req, ThreadContext *tc, Mode mode)
Stub function for compilation support with CheckerCPU.
Fault finalizePhysical (RequestPtr req, ThreadContext *tc, Mode mode) const
Cycles doMmuRegRead (ThreadContext *tc, Packet *pkt)
Cycles doMmuRegWrite (ThreadContext *tc, Packet *pkt)
void GetTsbPtr (ThreadContext *tc, Addr addr, int ctx, Addr *ptrs)
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
uint64_t TteRead (int entry)
Give an entry id, read that tlb entries' tte.
Protected Types
enum FaultTypes {
OtherFault = 0, PrivViolation = 0x1, SideEffect = 0x2, AtomicToIo = 0x4,
IllegalAsi = 0x8, LoadFromNfo = 0x10, VaOutOfRange = 0x20, VaOutOfRangeJmp = 0x40
}
enum ContextType { Primary = 0, Secondary = 1, Nucleus = 2 }
enum TsbPageSize { Ps0, Ps1 }
typedef TlbMap::iterator MapIter
Protected Member Functions
void insert (Addr vpn, int partition_id, int context_id, bool real, const PageTableEntry &PTE, int entry=-1)
Insert a PTE into the TLB.
uint64_t TagRead (int entry)
Given an entry id, read that tlb entries' tag.
void demapAll (int partition_id)
Remove all non-locked entries from the tlb that match partition id.
void demapContext (int partition_id, int context_id)
Remove all entries that match a given context/partition id.
void demapPage (Addr va, int partition_id, bool real, int context_id)
Remve all entries that match a certain partition id, (contextid), and va).
bool validVirtualAddress (Addr va, bool am)
Checks if the virtual address provided is a valid one.
void writeSfsr (bool write, ContextType ct, bool se, FaultTypes ft, int asi)
void clearUsedBits ()
void writeTagAccess (Addr va, int context)
Fault translateInst (RequestPtr req, ThreadContext *tc)
Fault translateData (RequestPtr req, ThreadContext *tc, bool write)
Protected Attributes
uint64_t sfar
uint64_t c0_tsb_ps0
uint64_t c0_tsb_ps1
uint64_t c0_config
uint64_t cx_tsb_ps0
uint64_t cx_tsb_ps1
uint64_t cx_config
uint64_t sfsr
uint64_t tag_access
TlbMap lookupTable
TlbEntry * tlb
int size
int usedEntries
int lastReplaced
uint64_t cacheState
bool cacheValid
std::list< TlbEntry * > freeList
Private Member Functions
void writeSfsr (Addr a, bool write, ContextType ct, bool se, FaultTypes ft, int asi)
uint64_t MakeTsbPtr (TsbPageSize ps, uint64_t tag_access, uint64_t c0_tsb, uint64_t c0_config, uint64_t cX_tsb, uint64_t cX_config)
Private Attributes
TlbEntry * cacheEntry [2]
ASI cacheAsi [2]
Friends
class FastInstructionAccessMMUMiss
class FastDataAccessMMUMiss
Detailed Description
Definition at line 47 of file tlb.hh.
Member Typedef Documentation
typedef TlbMap::iterator SparcISA::TLB::MapIter [protected]
Definition at line 67 of file tlb.hh.
typedef SparcTLBParams SparcISA::TLB::Params
Reimplemented from SimObject.
Definition at line 153 of file tlb.hh.
Member Enumeration Documentation
enum SparcISA::TLB::ContextType [protected]
Enumerator:
Primary
Secondary
Nucleus
Definition at line 92 of file tlb.hh.
enum SparcISA::TLB::FaultTypes [protected]
Enumerator:
OtherFault
PrivViolation
SideEffect
AtomicToIo
IllegalAsi
LoadFromNfo
VaOutOfRange
VaOutOfRangeJmp
Definition at line 81 of file tlb.hh.
enum SparcISA::TLB::TsbPageSize [protected]
Enumerator:
Ps0
Ps1
Definition at line 98 of file tlb.hh.
Constructor & Destructor Documentation
SparcISA::TLB::TLB (const Params * p)
Definition at line 52 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, cacheEntry, cx_config, cx_tsb_ps0, cx_tsb_ps1, fatal, freeList, sfar, sfsr, size, tag_access, tlb, and X86ISA::x.
Member Function Documentation
void SparcISA::TLB::clearUsedBits () [protected]
Definition at line 80 of file tlb.cc.
References SparcISA::TlbMap::begin(), SparcISA::TlbMap::end(), ArmISA::i, SparcISA::PageTableEntry::locked(), lookupTable, SparcISA::TlbEntry::pte, ArmISA::t, SparcISA::TlbEntry::used, and usedEntries.
Referenced by insert(), and lookup().
void SparcISA::TLB::demapAll (int partition_id) [protected]
Remove all non-locked entries from the tlb that match partition id.
Definition at line 307 of file tlb.cc.
References cacheValid, DPRINTF, SparcISA::TlbMap::erase(), freeList, lookupTable, SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::range, size, tlb, SparcISA::TlbEntry::used, used(), usedEntries, SparcISA::TlbEntry::valid, and X86ISA::x.
Referenced by doMmuRegWrite().
void SparcISA::TLB::demapContext (int partition_id, int context_id) [protected]
Remove all entries that match a given context/partition id.
Definition at line 285 of file tlb.cc.
References cacheValid, DPRINTF, SparcISA::TlbMap::erase(), freeList, lookupTable, SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::range, size, tlb, SparcISA::TlbEntry::used, used(), usedEntries, SparcISA::TlbEntry::valid, and X86ISA::x.
Referenced by doMmuRegWrite().
void SparcISA::TLB::demapPage (Addr vaddr, uint64_t asn) [inline, virtual]
Implements BaseTLB.
Definition at line 159 of file tlb.hh.
References panic.
void SparcISA::TLB::demapPage (Addr va, int partition_id, bool real, int context_id) [protected]
Remve all entries that match a certain partition id, (contextid), and va).
Definition at line 253 of file tlb.cc.
References cacheValid, SparcISA::TlbRange::contextId, DPRINTF, SparcISA::TlbMap::end(), SparcISA::TlbMap::erase(), SparcISA::TlbMap::find(), freeList, ArmISA::i, lookupTable, SparcISA::TlbRange::partitionId, SparcISA::TlbRange::real, SparcISA::TlbRange::size, usedEntries, and SparcISA::TlbRange::va.
Referenced by doMmuRegWrite().
Cycles SparcISA::TLB::doMmuRegRead (ThreadContext * tc, Packet * pkt)
Definition at line 864 of file tlb.cc.
References SparcISA::ASI_DMMU, SparcISA::ASI_DMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_TSB_PS0_PTR_REG, SparcISA::ASI_DMMU_TSB_PS1_PTR_REG, SparcISA::ASI_HYP_SCRATCHPAD, SparcISA::ASI_IMMU, SparcISA::ASI_IMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_TSB_PS0_PTR_REG, SparcISA::ASI_IMMU_TSB_PS1_PTR_REG, SparcISA::ASI_LSU_CONTROL_REG, SparcISA::ASI_MMU, SparcISA::ASI_QUEUE, SparcISA::ASI_SCRATCHPAD, SparcISA::ASI_SPARC_ERROR_STATUS_REG, SparcISA::ASI_SWVR_INTR_RECEIVE, SparcISA::ASI_SWVR_UDB_INTR_R, bits(), c0_config, c0_tsb_ps0, c0_tsb_ps1, cx_config, cx_tsb_ps0, cx_tsb_ps1, DPRINTF, findMsbSet(), SparcISA::Interrupts::get_vec(), Packet::getAddr(), Request::getArchFlags(), ThreadContext::getCpuPtr(), ThreadContext::getITBPtr(), SparcISA::IT_INT_VEC, Packet::makeAtomicResponse(), MakeTsbPtr(), SparcISA::MISCREG_MMU_LSU_CTRL, SparcISA::MISCREG_MMU_P_CONTEXT, SparcISA::MISCREG_MMU_PART_ID, SparcISA::MISCREG_MMU_S_CONTEXT, SparcISA::MISCREG_QUEUE_CPU_MONDO_HEAD, SparcISA::MISCREG_SCRATCHPAD_R0, panic, Ps0, Ps1, ThreadContext::readMiscReg(), Packet::req, Packet::set(), sfar, sfsr, tag_access, and ArmISA::va.
Cycles SparcISA::TLB::doMmuRegWrite (ThreadContext * tc, Packet * pkt)
Definition at line 1049 of file tlb.cc.
References SparcISA::ASI_DMMU, SparcISA::ASI_DMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_DEMAP, SparcISA::ASI_DTLB_DATA_ACCESS_REG, SparcISA::ASI_DTLB_DATA_IN_REG, SparcISA::ASI_HYP_SCRATCHPAD, SparcISA::ASI_IMMU, SparcISA::ASI_IMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_DEMAP, SparcISA::ASI_ITLB_DATA_ACCESS_REG, SparcISA::ASI_ITLB_DATA_IN_REG, SparcISA::ASI_LSU_CONTROL_REG, SparcISA::ASI_MMU, SparcISA::ASI_QUEUE, SparcISA::ASI_SCRATCHPAD, SparcISA::ASI_SPARC_ERROR_EN_REG, SparcISA::ASI_SPARC_ERROR_STATUS_REG, SparcISA::ASI_SWVR_INTR_RECEIVE, SparcISA::ASI_SWVR_UDB_INTR_W, bits(), c0_config, c0_tsb_ps0, c0_tsb_ps1, cx_config, cx_tsb_ps0, cx_tsb_ps1, demapAll(), demapContext(), demapPage(), DPRINTF, findMsbSet(), Packet::get(), SparcISA::Interrupts::get_vec(), Packet::getAddr(), Request::getArchFlags(), ThreadContext::getCpuPtr(), ThreadContext::getITBPtr(), ThreadContext::getSystemPtr(), Trace::ignore, inform, insert(), SparcISA::IT_INT_VEC, Packet::makeAtomicResponse(), mbits(), SparcISA::MISCREG_MMU_LSU_CTRL, SparcISA::MISCREG_MMU_P_CONTEXT, SparcISA::MISCREG_MMU_PART_ID, SparcISA::MISCREG_MMU_S_CONTEXT, SparcISA::MISCREG_QUEUE_CPU_MONDO_HEAD, SparcISA::MISCREG_SCRATCHPAD_R0, panic, SparcISA::PageTableEntry::populate(), ThreadContext::readMiscReg(), Packet::req, ThreadContext::setMiscReg(), sfsr, SparcISA::PageTableEntry::sun4u, SparcISA::PageTableEntry::sun4v, tag_access, System::threadContexts, and ArmISA::va.
void SparcISA::TLB::dumpAll ()
Definition at line 239 of file tlb.cc.
References SparcISA::TlbRange::contextId, DPRINTFN, ArmISA::i, SparcISA::PageTableEntry::paddr(), SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, SparcISA::TlbRange::real, SparcISA::TlbRange::size, size, tlb, SparcISA::TlbRange::va, and X86ISA::x.
Fault SparcISA::TLB::finalizePhysical (RequestPtr req, ThreadContext * tc, Mode mode) const
Definition at line 858 of file tlb.cc.
void SparcISA::TLB::flushAll () [virtual]
Remove all entries from the TLB.
Implements BaseTLB.
Definition at line 326 of file tlb.cc.
References cacheValid, SparcISA::TlbMap::clear(), freeList, lookupTable, size, tlb, SparcISA::TlbEntry::used, usedEntries, SparcISA::TlbEntry::valid, and X86ISA::x.
void SparcISA::TLB::GetTsbPtr (ThreadContext * tc, Addr addr, int ctx, Addr * ptrs)
Definition at line 1302 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, cx_config, cx_tsb_ps0, cx_tsb_ps1, ThreadContext::getITBPtr(), MakeTsbPtr(), mbits(), Ps0, Ps1, and tag_access.
void SparcISA::TLB::insert (Addr vpn, int partition_id, int context_id, bool real, const PageTableEntry & PTE, int entry = -1) [protected]
Insert a PTE into the TLB.
Definition at line 94 of file tlb.cc.
References cacheValid, clearUsedBits(), SparcISA::TlbRange::contextId, DPRINTF, SparcISA::TlbMap::end(), SparcISA::TlbMap::erase(), freeList, ArmISA::i, SparcISA::TlbMap::insert(), lastReplaced, lookupTable, SparcISA::PageTableEntry::paddr(), SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, SparcISA::TlbRange::real, SparcISA::TlbRange::size, size, SparcISA::PageTableEntry::size(), tlb, SparcISA::TlbEntry::used, used(), usedEntries, SparcISA::TlbRange::va, SparcISA::PageTableEntry::valid(), SparcISA::TlbEntry::valid, and X86ISA::x.
Referenced by doMmuRegWrite().
TlbEntry * SparcISA::TLB::lookup (Addr va, int partition_id, bool real, int context_id = 0, bool update_used = true)
lookup an entry in the TLB based on the partition id, and real bit if real is true or the partition id, and context id if real is false.
Parameters:
va the virtual address not shifted (e.g. bottom 13 bits are 0)
paritition_id partition this entry is for
real is this a real->phys or virt->phys translation
context_id if this is virt->phys what context
update_used should ew update the used bits in the entries on not useful if we are trying to do a va->pa without mucking with any state for a debug read for example.
Returns:
A pointer to a tlb entry
Definition at line 195 of file tlb.cc.
References clearUsedBits(), SparcISA::TlbRange::contextId, DPRINTF, SparcISA::TlbMap::end(), SparcISA::TlbMap::find(), ArmISA::i, lookupTable, SparcISA::PageTableEntry::paddr(), SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::pte, SparcISA::TlbRange::real, size, SparcISA::PageTableEntry::size(), SparcISA::TlbRange::size, ArmISA::t, SparcISA::TlbEntry::used, usedEntries, and SparcISA::TlbRange::va.
Referenced by translateData(), and translateInst().
uint64_t SparcISA::TLB::MakeTsbPtr (TsbPageSize ps, uint64_t tag_access, uint64_t c0_tsb, uint64_t c0_config, uint64_t cX_tsb, uint64_t cX_config) [private]
Definition at line 1329 of file tlb.cc.
References bits(), ArmISA::mask, mbits(), Ps0, Ps1, and ULL.
Referenced by doMmuRegRead(), and GetTsbPtr().
void SparcISA::TLB::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 1356 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, csprintf(), cx_config, cx_tsb_ps0, cx_tsb_ps1, freeList, ArmISA::i, lastReplaced, SimObject::name(), Serializable::nameOut(), SparcISA::TlbEntry::serialize(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, sfar, sfsr, size, tag_access, tlb, usedEntries, and X86ISA::x.
uint64_t SparcISA::TLB::TagRead (int entry) [protected]
Given an entry id, read that tlb entries' tag.
Definition at line 354 of file tlb.cc.
References SparcISA::TlbRange::contextId, SparcISA::TlbEntry::range, SparcISA::TlbRange::real, size, tlb, ULL, and SparcISA::TlbRange::va.
void SparcISA::TLB::takeOverFrom (BaseTLB * otlb) [inline]
Definition at line 156 of file tlb.hh.
Fault SparcISA::TLB::translateAtomic (RequestPtr req, ThreadContext * tc, Mode mode)
Definition at line 834 of file tlb.cc.
References BaseTLB::Execute, translateData(), translateInst(), and BaseTLB::Write.
Referenced by translateTiming().
Fault SparcISA::TLB::translateData (RequestPtr req, ThreadContext * tc, bool write) [protected]
Normal flow ends here.
Definition at line 530 of file tlb.cc.
References SparcISA::ASI_IMPLICIT, SparcISA::ASI_N, SparcISA::ASI_P, SparcISA::ASI_S, SparcISA::ASI_SWVR_UDB_INTR_R, SparcISA::ASI_SWVR_UDB_INTR_W, SparcISA::asiIsAsIfUser(), SparcISA::asiIsBlock(), SparcISA::asiIsCmt(), SparcISA::asiIsHPriv(), SparcISA::asiIsInterrupt(), SparcISA::asiIsLittle(), SparcISA::asiIsMmu(), SparcISA::asiIsNoFault(), SparcISA::asiIsNucleus(), SparcISA::asiIsPartialStore(), SparcISA::asiIsPrimary(), SparcISA::asiIsQueue(), SparcISA::asiIsReal(), SparcISA::asiIsScratchPad(), SparcISA::asiIsSecondary(), SparcISA::asiIsSparcError(), SparcISA::asiIsTwin(), SparcISA::asiIsUnPriv(), bits(), cacheAsi, cacheEntry, cacheState, cacheValid, MipsISA::ce, DPRINTF, ArmISA::e, freeList, FullSystem, Request::getArchFlags(), Request::getPaddr(), Request::getSize(), Request::getVaddr(), SparcISA::hpriv, IllegalAsi, LoadFromNfo, lookup(), lookupTable, SparcISA::MISCREG_TLB_DATA, Request::MMAPPED_IPR, SparcISA::PageTableEntry::nofault(), Nucleus, OtherFault, SparcISA::PageTableEntry::paddr(), SparcISA::PAddrImplMask, panic, Primary, SparcISA::PageTableEntry::priv(), SparcISA::priv, PrivViolation, SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, ThreadContext::readMiscRegNoEffect(), SparcISA::red, Secondary, Request::setFlags(), Request::setPaddr(), SideEffect, SparcISA::PageTableEntry::sideffect(), SparcISA::TlbMap::size(), size, Request::STRICT_ORDER, MipsISA::tl, SparcISA::PageTableEntry::translate(), Request::UNCACHEABLE, SparcISA::TlbRange::va, MipsISA::vaddr, SparcISA::VAddrAMask, SparcISA::TlbEntry::valid, validVirtualAddress(), VaOutOfRange, SparcISA::PageTableEntry::writable(), writeSfsr(), and writeTagAccess().
Referenced by translateAtomic().
Fault SparcISA::TLB::translateFunctional (RequestPtr req, ThreadContext * tc, Mode mode)
Stub function for compilation support with CheckerCPU.
SPARC ISA does not support the Checker model at the moment
Definition at line 851 of file tlb.cc.
References panic.
Fault SparcISA::TLB::translateInst (RequestPtr req, ThreadContext * tc) [protected]
Definition at line 416 of file tlb.cc.
References SparcISA::ASI_IMPLICIT, SparcISA::ASI_N, SparcISA::ASI_P, bits(), cacheEntry, cacheState, cacheValid, DPRINTF, ArmISA::e, FullSystem, Request::getArchFlags(), Request::getPaddr(), Request::getSize(), Request::getVaddr(), SparcISA::hpriv, lookup(), SparcISA::MISCREG_TLB_DATA, Nucleus, OtherFault, SparcISA::PAddrImplMask, Primary, SparcISA::PageTableEntry::priv(), SparcISA::priv, PrivViolation, SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, ThreadContext::readMiscRegNoEffect(), SparcISA::red, Request::setPaddr(), SparcISA::TlbRange::size, MipsISA::tl, SparcISA::PageTableEntry::translate(), SparcISA::TlbRange::va, MipsISA::vaddr, SparcISA::VAddrAMask, SparcISA::TlbEntry::valid, validVirtualAddress(), VaOutOfRange, writeSfsr(), and writeTagAccess().
Referenced by translateAtomic().
void SparcISA::TLB::translateTiming (RequestPtr req, ThreadContext * tc, Translation * translation, Mode mode)
Definition at line 843 of file tlb.cc.
References BaseTLB::Translation::finish(), and translateAtomic().
uint64_t SparcISA::TLB::TteRead (int entry)
Give an entry id, read that tlb entries' tte.
Definition at line 341 of file tlb.cc.
References panic, SparcISA::TlbEntry::pte, size, and tlb.
void SparcISA::TLB::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 1391 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, SparcISA::TlbMap::clear(), csprintf(), cx_config, cx_tsb_ps0, cx_tsb_ps1, freeList, SparcISA::TlbMap::insert(), lastReplaced, lookupTable, panic, paramIn(), sfar, sfsr, size, tag_access, tlb, SparcISA::TlbEntry::unserialize(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, usedEntries, and X86ISA::x.
bool SparcISA::TLB::validVirtualAddress (Addr va, bool am) [protected]
Checks if the virtual address provided is a valid one.
Definition at line 370 of file tlb.cc.
References SparcISA::EndVAddrHole, and SparcISA::StartVAddrHole.
Referenced by translateData(), and translateInst().
void SparcISA::TLB::writeSfsr (Addr a, bool write, ContextType ct, bool se, FaultTypes ft, int asi) [private]
Definition at line 406 of file tlb.cc.
References DPRINTF, sfar, and writeSfsr().
void SparcISA::TLB::writeSfsr (bool write, ContextType ct, bool se, FaultTypes ft, int asi) [protected]
Definition at line 380 of file tlb.cc.
References sfsr.
Referenced by translateData(), translateInst(), and writeSfsr().
void SparcISA::TLB::writeTagAccess (Addr va, int context) [protected]
Definition at line 397 of file tlb.cc.
References DPRINTF, mbits(), and tag_access.
Referenced by translateData(), and translateInst().
Friends And Related Function Documentation
friend class FastDataAccessMMUMiss [friend]
Definition at line 51 of file tlb.hh.
friend class FastInstructionAccessMMUMiss [friend]
Definition at line 50 of file tlb.hh.
Member Data Documentation
uint64_t SparcISA::TLB::c0_config [protected]
Definition at line 59 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
uint64_t SparcISA::TLB::c0_tsb_ps0 [protected]
Definition at line 57 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
uint64_t SparcISA::TLB::c0_tsb_ps1 [protected]
Definition at line 58 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
ASI SparcISA::TLB::cacheAsi[2] [private]
Definition at line 194 of file tlb.hh.
Referenced by translateData().
TlbEntry* SparcISA::TLB::cacheEntry[2] [private]
Definition at line 193 of file tlb.hh.
Referenced by TLB(), translateData(), and translateInst().
uint64_t SparcISA::TLB::cacheState [protected]
Definition at line 76 of file tlb.hh.
Referenced by translateData(), and translateInst().
bool SparcISA::TLB::cacheValid [protected]
Definition at line 77 of file tlb.hh.
Referenced by demapAll(), demapContext(), demapPage(), flushAll(), insert(), translateData(), and translateInst().
uint64_t SparcISA::TLB::cx_config [protected]
Definition at line 62 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
uint64_t SparcISA::TLB::cx_tsb_ps0 [protected]
Definition at line 60 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
uint64_t SparcISA::TLB::cx_tsb_ps1 [protected]
Definition at line 61 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
std::list<TlbEntry*> SparcISA::TLB::freeList [protected]
Definition at line 79 of file tlb.hh.
Referenced by demapAll(), demapContext(), demapPage(), flushAll(), insert(), serialize(), TLB(), translateData(), and unserialize().
int SparcISA::TLB::lastReplaced [protected]
Definition at line 74 of file tlb.hh.
Referenced by insert(), serialize(), and unserialize().
TlbMap SparcISA::TLB::lookupTable [protected]
Definition at line 67 of file tlb.hh.
Referenced by clearUsedBits(), demapAll(), demapContext(), demapPage(), flushAll(), insert(), lookup(), translateData(), and unserialize().
uint64_t SparcISA::TLB::sfar [protected]
Definition at line 56 of file tlb.hh.
Referenced by doMmuRegRead(), serialize(), TLB(), unserialize(), and writeSfsr().
uint64_t SparcISA::TLB::sfsr [protected]
Definition at line 63 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), serialize(), TLB(), unserialize(), and writeSfsr().
int SparcISA::TLB::size [protected]
Definition at line 72 of file tlb.hh.
Referenced by demapAll(), demapContext(), dumpAll(), flushAll(), insert(), lookup(), serialize(), TagRead(), TLB(), translateData(), TteRead(), and unserialize().
uint64_t SparcISA::TLB::tag_access [protected]
Definition at line 64 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), unserialize(), and writeTagAccess().
TlbEntry* SparcISA::TLB::tlb [protected]
Definition at line 70 of file tlb.hh.
Referenced by demapAll(), demapContext(), dumpAll(), flushAll(), insert(), serialize(), TagRead(), TLB(), TteRead(), and unserialize().
int SparcISA::TLB::usedEntries [protected]
Definition at line 73 of file tlb.hh.
Referenced by clearUsedBits(), demapAll(), demapContext(), demapPage(), flushAll(), insert(), lookup(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
arch/sparc/tlb.hh
arch/sparc/tlb.cc