gem5: Minor::ForwardLineData Class Reference
Minor::ForwardLineData Class Reference
Line fetch data in the forward direction.
#include <pipe_data.hh>
Public Member Functions
ForwardLineData ()
~ForwardLineData ()
bool isFault () const
This is a fault, not a line.
void setFault (Fault fault_)
Set fault and possible clear the bubble flag.
void allocateLine (unsigned int width_)
In-place initialise a ForwardLineData, freeing and overridding the line.
void adoptPacketData (Packet *packet)
Use the data from a packet as line instead of allocating new space.
void freeLine ()
Free this ForwardLineData line.
bool isBubble () const
void reportData (std::ostream &os) const
ReportIF interface.
Static Public Member Functions
static ForwardLineData bubble ()
BubbleIF interface.
Public Attributes
Addr lineBaseAddr
First byte address in the line.
TheISA::PCState pc
PC of the first requested inst within this line.
unsigned int lineWidth
Explicit line width, don't rely on data.size.
Fault fault
This line has a fault.
InstId id
Thread, stream, prediction .
uint8_t * line
Line data.
Packet * packet
Packet from which the line is taken.
Private Attributes
bool bubbleFlag
This line is a bubble.
Detailed Description
Line fetch data in the forward direction.
Contains a single cache line (or fragment of a line), its address, a sequence number assigned when that line was fetched and a bubbleFlag that can allow ForwardLineData to be used to represent the absence of line data in a pipeline.
Definition at line 170 of file pipe_data.hh.
Constructor & Destructor Documentation
Minor::ForwardLineData::ForwardLineData () [inline]
Definition at line 204 of file pipe_data.hh.
Referenced by bubble().
Minor::ForwardLineData::~ForwardLineData () [inline]
Definition at line 215 of file pipe_data.hh.
References line.
Member Function Documentation
void Minor::ForwardLineData::adoptPacketData (Packet * packet)
Use the data from a packet as line instead of allocating new space.
On destruction of this object, the packet will be destroyed
Definition at line 190 of file pipe_data.cc.
References bubbleFlag, Packet::getPtr(), Request::getSize(), isFault(), line, lineWidth, and Packet::req.
Referenced by Minor::Fetch1::processResponse().
void Minor::ForwardLineData::allocateLine (unsigned int width_)
In-place initialise a ForwardLineData, freeing and overridding the line.
Definition at line 178 of file pipe_data.cc.
References bubbleFlag, isFault(), line, and lineWidth.
static ForwardLineData Minor::ForwardLineData::bubble () [inline, static]
BubbleIF interface.
Definition at line 239 of file pipe_data.hh.
References ForwardLineData().
void Minor::ForwardLineData::freeLine ()
Free this ForwardLineData line.
Note that these are shared between line objects and so you must be careful when deallocating them. Copying of ForwardLineData can, therefore, be done by default copy constructors/assignment
Definition at line 203 of file pipe_data.cc.
References bubbleFlag, isBubble(), isFault(), line, and packet.
Referenced by Minor::Fetch2::popInput().
bool Minor::ForwardLineData::isBubble () const [inline]
Definition at line 240 of file pipe_data.hh.
References bubbleFlag.
Referenced by Minor::Fetch1::evaluate(), freeLine(), and reportData().
bool Minor::ForwardLineData::isFault () const [inline]
This is a fault, not a line.
Definition at line 219 of file pipe_data.hh.
References fault.
Referenced by adoptPacketData(), allocateLine(), Minor::Fetch2::evaluate(), freeLine(), and setFault().
void Minor::ForwardLineData::reportData (std::ostream & os) const
ReportIF interface.
Definition at line 221 of file pipe_data.cc.
References fault, id, and isBubble().
void Minor::ForwardLineData::setFault (Fault fault_)
Set fault and possible clear the bubble flag.
Definition at line 170 of file pipe_data.cc.
References bubbleFlag, fault, and isFault().
Referenced by Minor::Fetch1::processResponse().
Member Data Documentation
bool Minor::ForwardLineData::bubbleFlag [private]
This line is a bubble.
No other data member is required to be valid if this is true
Definition at line 175 of file pipe_data.hh.
Referenced by adoptPacketData(), allocateLine(), freeLine(), isBubble(), and setFault().
Fault Minor::ForwardLineData::fault
This line has a fault.
The bubble flag will be false and seqNums will be valid but no data will
Definition at line 191 of file pipe_data.hh.
Referenced by Minor::Fetch2::evaluate(), isFault(), reportData(), and setFault().
InstId Minor::ForwardLineData::id
Thread, stream, prediction .
.. id of this line
Definition at line 194 of file pipe_data.hh.
Referenced by Minor::Fetch2::evaluate(), Minor::Fetch1::processResponse(), and reportData().
uint8_t* Minor::ForwardLineData::line
Line data.
line[0] is the byte at address pc.instAddr(). Data is only valid upto lineWidth - 1.
Definition at line 198 of file pipe_data.hh.
Referenced by adoptPacketData(), allocateLine(), Minor::Fetch2::evaluate(), freeLine(), and ~ForwardLineData().
Addr Minor::ForwardLineData::lineBaseAddr
First byte address in the line.
This is allowed to be <= pc.instAddr()
Definition at line 180 of file pipe_data.hh.
Referenced by Minor::Fetch2::evaluate(), and Minor::Fetch1::processResponse().
unsigned int Minor::ForwardLineData::lineWidth
Explicit line width, don't rely on data.size.
Definition at line 186 of file pipe_data.hh.
Referenced by adoptPacketData(), allocateLine(), and Minor::Fetch2::evaluate().
Packet* Minor::ForwardLineData::packet
Packet from which the line is taken.
Definition at line 201 of file pipe_data.hh.
Referenced by freeLine().
TheISA::PCState Minor::ForwardLineData::pc
PC of the first requested inst within this line.
Definition at line 183 of file pipe_data.hh.
Referenced by Minor::Fetch2::evaluate(), and Minor::Fetch1::processResponse().
The documentation for this class was generated from the following files:
cpu/minor/pipe_data.hh
cpu/minor/pipe_data.cc