gem5: GenericTimer Class Reference
GenericTimer Class Reference
#include <generic_timer.hh>
Classes
struct CoreTimers
Public Member Functions
GenericTimer (GenericTimerParams *p)
void serialize (std::ostream &os) M5_ATTR_OVERRIDE
void unserialize (Checkpoint *cp, const std::string &sec) M5_ATTR_OVERRIDE
void setMiscReg (int misc_reg, unsigned cpu, ArmISA::MiscReg val)
ArmISA::MiscReg readMiscReg (int misc_reg, unsigned cpu)
Protected Member Functions
CoreTimers & getTimers (int cpu_id)
void createTimers (unsigned cpus)
Protected Attributes
SystemCounter systemCounter
System counter.
std::vector< std::unique_ptr
< CoreTimers > > timers
Per-CPU physical architected timers.
BaseGic *const gic
Pointer to the GIC, needed to trigger timer interrupts.
const unsigned irqPhys
Physical timer interrupt.
const unsigned irqVirt
Virtual timer interrupt.
Detailed Description
Definition at line 200 of file generic_timer.hh.
Constructor & Destructor Documentation
GenericTimer::GenericTimer (GenericTimerParams * p)
Definition at line 233 of file generic_timer.cc.
Member Function Documentation
void GenericTimer::createTimers (unsigned cpus) [protected]
Definition at line 297 of file generic_timer.cc.
References ArmISA::i, irqPhys, irqVirt, and timers.
Referenced by getTimers().
GenericTimer::CoreTimers & GenericTimer::getTimers (int cpu_id) [protected]
Definition at line 288 of file generic_timer.cc.
References createTimers(), and timers.
Referenced by readMiscReg(), serialize(), and unserialize().
MiscReg GenericTimer::readMiscReg (int misc_reg, unsigned cpu)
Definition at line 403 of file generic_timer.cc.
References ArchTimer::compareValue(), ArchTimer::control(), SystemCounter::freq(), SystemCounter::getKernelControl(), getTimers(), ArmISA::MISCREG_CNTFRQ, ArmISA::MISCREG_CNTFRQ_EL0, ArmISA::MISCREG_CNTHCTL, ArmISA::MISCREG_CNTHCTL_EL2, ArmISA::MISCREG_CNTHP_CTL, ArmISA::MISCREG_CNTHP_CTL_EL2, ArmISA::MISCREG_CNTHP_CVAL, ArmISA::MISCREG_CNTHP_CVAL_EL2, ArmISA::MISCREG_CNTHP_TVAL, ArmISA::MISCREG_CNTHP_TVAL_EL2, ArmISA::MISCREG_CNTKCTL, ArmISA::MISCREG_CNTKCTL_EL1, ArmISA::MISCREG_CNTP_CTL, ArmISA::MISCREG_CNTP_CTL_EL0, ArmISA::MISCREG_CNTP_CTL_NS, ArmISA::MISCREG_CNTP_CTL_S, ArmISA::MISCREG_CNTP_CVAL, ArmISA::MISCREG_CNTP_CVAL_EL0, ArmISA::MISCREG_CNTP_TVAL, ArmISA::MISCREG_CNTP_TVAL_EL0, ArmISA::MISCREG_CNTPCT, ArmISA::MISCREG_CNTPCT_EL0, ArmISA::MISCREG_CNTPS_CTL_EL1, ArmISA::MISCREG_CNTPS_CVAL_EL1, ArmISA::MISCREG_CNTPS_TVAL_EL1, ArmISA::MISCREG_CNTV_CTL, ArmISA::MISCREG_CNTV_CTL_EL0, ArmISA::MISCREG_CNTV_CVAL, ArmISA::MISCREG_CNTV_CVAL_EL0, ArmISA::MISCREG_CNTV_TVAL, ArmISA::MISCREG_CNTV_TVAL_EL0, ArmISA::MISCREG_CNTVCT, ArmISA::MISCREG_CNTVCT_EL0, ArmISA::MISCREG_CNTVOFF, ArmISA::MISCREG_CNTVOFF_EL2, ArmISA::miscRegName, ArchTimer::offset(), GenericTimer::CoreTimers::phys, systemCounter, ArchTimer::timerValue(), ArchTimer::value(), GenericTimer::CoreTimers::virt, and warn.
Referenced by GenericTimerISA::readMiscReg().
void GenericTimer::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 243 of file generic_timer.cc.
References csprintf(), getTimers(), ArmISA::i, ArchTimer::name(), SimObject::name(), Serializable::nameOut(), paramOut(), GenericTimer::CoreTimers::phys, ArchTimer::serialize(), SystemCounter::serialize(), systemCounter, timers, and GenericTimer::CoreTimers::virt.
void GenericTimer::setMiscReg (int misc_reg, unsigned cpu, ArmISA::MiscReg val)
Referenced by GenericTimerISA::setMiscReg().
void GenericTimer::unserialize (Checkpoint * cp, const std::string & sec) [virtual]
Reimplemented from Serializable.
Definition at line 262 of file generic_timer.cc.
References csprintf(), getTimers(), ArmISA::i, GenericTimer::CoreTimers::phys, systemCounter, ArchTimer::unserialize(), SystemCounter::unserialize(), UNSERIALIZE_OPT_SCALAR, GenericTimer::CoreTimers::virt, and warn.
Member Data Documentation
BaseGic* const GenericTimer::gic [protected]
Pointer to the GIC, needed to trigger timer interrupts.
Definition at line 250 of file generic_timer.hh.
const unsigned GenericTimer::irqPhys [protected]
Physical timer interrupt.
Definition at line 253 of file generic_timer.hh.
Referenced by createTimers().
const unsigned GenericTimer::irqVirt [protected]
Virtual timer interrupt.
Definition at line 256 of file generic_timer.hh.
Referenced by createTimers().
SystemCounter GenericTimer::systemCounter [protected]
System counter.
Definition at line 243 of file generic_timer.hh.
Referenced by readMiscReg(), serialize(), and unserialize().
std::vector<std::unique_ptr<CoreTimers> > GenericTimer::timers [protected]
Per-CPU physical architected timers.
Definition at line 246 of file generic_timer.hh.
Referenced by createTimers(), getTimers(), and serialize().
The documentation for this class was generated from the following files:
dev/arm/generic_timer.hh
dev/arm/generic_timer.cc