gem5: BaseGarnetNetwork Class Reference
BaseGarnetNetwork Class Reference
#include <BaseGarnetNetwork.hh>
Public Types
typedef BaseGarnetNetworkParams Params
Public Member Functions
BaseGarnetNetwork (const Params *p)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
int getNiFlitSize ()
int getVCsPerVnet ()
bool isFaultModelEnabled ()
void increment_injected_flits (int vnet)
void increment_received_flits (int vnet)
void increment_network_latency (Cycles latency, int vnet)
void increment_queueing_latency (Cycles latency, int vnet)
void setToNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer *b)
void setFromNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer *b)
bool isVNetOrdered (int vnet)
bool validVirtualNetwork (int vnet)
virtual void checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type)=0
virtual void regStats ()
Register statistics for this object.
virtual void collateStats ()
Public Attributes
FaultModel * fault_model
Protected Attributes
int m_ni_flit_size
int m_vcs_per_vnet
bool m_enable_fault_model
Stats::Vector m_flits_received
Stats::Vector m_flits_injected
Stats::Vector m_network_latency
Stats::Vector m_queueing_latency
Stats::Formula m_avg_vnet_latency
Stats::Formula m_avg_vqueue_latency
Stats::Formula m_avg_network_latency
Stats::Formula m_avg_queueing_latency
Stats::Formula m_avg_latency
Detailed Description
Definition at line 44 of file BaseGarnetNetwork.hh.
Member Typedef Documentation
typedef BaseGarnetNetworkParams BaseGarnetNetwork::Params
Reimplemented from Network.
Reimplemented in GarnetNetwork_d, and GarnetNetwork.
Definition at line 47 of file BaseGarnetNetwork.hh.
Constructor & Destructor Documentation
BaseGarnetNetwork::BaseGarnetNetwork (const Params * p)
Definition at line 36 of file BaseGarnetNetwork.cc.
References fatal, fault_model, ArmISA::i, m_enable_fault_model, m_ni_flit_size, m_vcs_per_vnet, BasicIntLink::params(), and BasicExtLink::params().
Member Function Documentation
virtual void BaseGarnetNetwork::checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type) [pure virtual]
Implemented in GarnetNetwork_d, and GarnetNetwork.
virtual void BaseGarnetNetwork::collateStats () [inline, virtual]
Implements Network.
Reimplemented in GarnetNetwork_d, and GarnetNetwork.
Definition at line 83 of file BaseGarnetNetwork.hh.
int BaseGarnetNetwork::getNiFlitSize () [inline]
Definition at line 51 of file BaseGarnetNetwork.hh.
References m_ni_flit_size.
Referenced by NetworkInterface::flitisizeMessage(), and NetworkInterface_d::flitisizeMessage().
int BaseGarnetNetwork::getVCsPerVnet () [inline]
Definition at line 52 of file BaseGarnetNetwork.hh.
References m_vcs_per_vnet.
Referenced by GarnetNetwork_d::get_vnet_type().
void BaseGarnetNetwork::increment_injected_flits (int vnet) [inline]
Definition at line 56 of file BaseGarnetNetwork.hh.
References m_flits_injected.
Referenced by NetworkInterface::flitisizeMessage(), and NetworkInterface_d::flitisizeMessage().
void BaseGarnetNetwork::increment_network_latency (Cycles latency, int vnet) [inline]
Definition at line 60 of file BaseGarnetNetwork.hh.
References m_network_latency.
Referenced by NetworkInterface::wakeup(), and NetworkInterface_d::wakeup().
void BaseGarnetNetwork::increment_queueing_latency (Cycles latency, int vnet) [inline]
Definition at line 66 of file BaseGarnetNetwork.hh.
References m_queueing_latency.
Referenced by NetworkInterface::wakeup(), and NetworkInterface_d::wakeup().
void BaseGarnetNetwork::increment_received_flits (int vnet) [inline]
Definition at line 57 of file BaseGarnetNetwork.hh.
References m_flits_received.
Referenced by NetworkInterface::wakeup(), and NetworkInterface_d::wakeup().
void BaseGarnetNetwork::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from Network.
Reimplemented in GarnetNetwork_d, and GarnetNetwork.
Definition at line 64 of file BaseGarnetNetwork.cc.
bool BaseGarnetNetwork::isFaultModelEnabled () [inline]
Definition at line 53 of file BaseGarnetNetwork.hh.
References m_enable_fault_model.
Referenced by GarnetNetwork_d::init().
bool BaseGarnetNetwork::isVNetOrdered (int vnet) [inline]
Definition at line 77 of file BaseGarnetNetwork.hh.
References Network::m_ordered.
Referenced by NetworkInterface::calculateVC(), Router::get_valid_vcs(), and NetworkInterface_d::scheduleOutputLink().
void BaseGarnetNetwork::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Reimplemented in GarnetNetwork_d, and GarnetNetwork.
Definition at line 92 of file BaseGarnetNetwork.cc.
References csprintf(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), m_avg_latency, m_avg_network_latency, m_avg_queueing_latency, m_avg_vnet_latency, m_avg_vqueue_latency, m_flits_injected, m_flits_received, m_network_latency, m_queueing_latency, Network::m_virtual_networks, Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), Stats::nozero, Stats::oneline, Stats::pdf, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), Stats::sum(), and Stats::total.
void BaseGarnetNetwork::setFromNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer * b) [virtual]
Implements Network.
void BaseGarnetNetwork::setToNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer * b) [virtual]
Implements Network.
bool BaseGarnetNetwork::validVirtualNetwork (int vnet) [inline]
Definition at line 78 of file BaseGarnetNetwork.hh.
References Network::m_in_use.
Referenced by Router::scheduleOutputLinks(), and Router::vc_arbitrate().
Member Data Documentation
FaultModel* BaseGarnetNetwork::fault_model
Definition at line 54 of file BaseGarnetNetwork.hh.
Referenced by BaseGarnetNetwork(), Router_d::get_aggregate_fault_probability(), Router_d::get_fault_vector(), and GarnetNetwork_d::init().
Stats::Formula BaseGarnetNetwork::m_avg_latency [protected]
Definition at line 100 of file BaseGarnetNetwork.hh.
Referenced by regStats().
Stats::Formula BaseGarnetNetwork::m_avg_network_latency [protected]
Definition at line 98 of file BaseGarnetNetwork.hh.
Referenced by regStats().
Stats::Formula BaseGarnetNetwork::m_avg_queueing_latency [protected]
Definition at line 99 of file BaseGarnetNetwork.hh.
Referenced by regStats().
Stats::Formula BaseGarnetNetwork::m_avg_vnet_latency [protected]
Definition at line 96 of file BaseGarnetNetwork.hh.
Referenced by regStats().
Stats::Formula BaseGarnetNetwork::m_avg_vqueue_latency [protected]
Definition at line 97 of file BaseGarnetNetwork.hh.
Referenced by regStats().
bool BaseGarnetNetwork::m_enable_fault_model [protected]
Definition at line 88 of file BaseGarnetNetwork.hh.
Referenced by BaseGarnetNetwork(), and isFaultModelEnabled().
Stats::Vector BaseGarnetNetwork::m_flits_injected [protected]
Definition at line 92 of file BaseGarnetNetwork.hh.
Referenced by increment_injected_flits(), and regStats().
Stats::Vector BaseGarnetNetwork::m_flits_received [protected]
Definition at line 91 of file BaseGarnetNetwork.hh.
Referenced by increment_received_flits(), and regStats().
Stats::Vector BaseGarnetNetwork::m_network_latency [protected]
Definition at line 93 of file BaseGarnetNetwork.hh.
Referenced by increment_network_latency(), and regStats().
int BaseGarnetNetwork::m_ni_flit_size [protected]
Definition at line 86 of file BaseGarnetNetwork.hh.
Referenced by BaseGarnetNetwork(), and getNiFlitSize().
Stats::Vector BaseGarnetNetwork::m_queueing_latency [protected]
Definition at line 94 of file BaseGarnetNetwork.hh.
Referenced by increment_queueing_latency(), and regStats().
int BaseGarnetNetwork::m_vcs_per_vnet [protected]
Definition at line 87 of file BaseGarnetNetwork.hh.
Referenced by BaseGarnetNetwork(), getVCsPerVnet(), GarnetNetwork::regStats(), and GarnetNetwork_d::regStats().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/BaseGarnetNetwork.hh
mem/ruby/network/garnet/BaseGarnetNetwork.cc