gem5: ArmISA::StackTrace Class Reference
ArmISA::StackTrace Class Reference
#include <stacktrace.hh>
Public Member Functions
StackTrace ()
StackTrace (ThreadContext *tc, const StaticInstPtr &inst)
~StackTrace ()
void clear ()
bool valid () const
bool trace (ThreadContext *tc, const StaticInstPtr &inst)
const std::vector< Addr > & getstack () const
void dprintf ()
Protected Types
typedef ArmISA::MachInst MachInst
Private Member Functions
bool isEntry (Addr addr)
bool decodePrologue (Addr sp, Addr callpc, Addr func, int &size, Addr &ra)
bool decodeSave (MachInst inst, int &reg, int &disp)
bool decodeStack (MachInst inst, int &disp)
void trace (ThreadContext *tc, bool is_call)
Private Attributes
ThreadContext * tc
std::vector< Addr > stack
Detailed Description
Definition at line 63 of file stacktrace.hh.
Member Typedef Documentation
typedef ArmISA::MachInst ArmISA::StackTrace::MachInst [protected]
Definition at line 66 of file stacktrace.hh.
Constructor & Destructor Documentation
ArmISA::StackTrace::StackTrace ()
Definition at line 119 of file stacktrace.cc.
ArmISA::StackTrace::StackTrace (ThreadContext * tc, const StaticInstPtr & inst)
Definition at line 124 of file stacktrace.cc.
References trace().
ArmISA::StackTrace::~StackTrace ()
Definition at line 130 of file stacktrace.cc.
Member Function Documentation
void ArmISA::StackTrace::clear () [inline]
Definition at line 84 of file stacktrace.hh.
References stack, and tc.
Referenced by trace().
bool ArmISA::StackTrace::decodePrologue (Addr sp, Addr callpc, Addr func, int & size, Addr & ra) [private]
Definition at line 162 of file stacktrace.cc.
bool ArmISA::StackTrace::decodeSave (MachInst inst, int & reg, int & disp) [private]
Definition at line 152 of file stacktrace.cc.
bool ArmISA::StackTrace::decodeStack (MachInst inst, int & disp) [private]
Definition at line 146 of file stacktrace.cc.
void ArmISA::StackTrace::dprintf () [inline]
Definition at line 104 of file stacktrace.hh.
const std::vector<Addr>& ArmISA::StackTrace::getstack () const [inline]
Definition at line 94 of file stacktrace.hh.
References stack.
bool ArmISA::StackTrace::isEntry (Addr addr) [private]
Definition at line 140 of file stacktrace.cc.
bool ArmISA::StackTrace::trace (ThreadContext * tc, const StaticInstPtr & inst) [inline]
Definition at line 109 of file stacktrace.hh.
References clear(), trace(), and valid().
void ArmISA::StackTrace::trace (ThreadContext * tc, bool is_call) [private]
Definition at line 135 of file stacktrace.cc.
Referenced by StackTrace(), and trace().
bool ArmISA::StackTrace::valid () const [inline]
Definition at line 90 of file stacktrace.hh.
References tc.
Referenced by trace().
Member Data Documentation
std::vector<Addr> ArmISA::StackTrace::stack [private]
Definition at line 69 of file stacktrace.hh.
Referenced by clear(), and getstack().
ThreadContext* ArmISA::StackTrace::tc [private]
Definition at line 68 of file stacktrace.hh.
Referenced by clear(), and valid().
The documentation for this class was generated from the following files:
arch/arm/stacktrace.hh
arch/arm/stacktrace.cc