gem5: ClockedObject Class Reference
ClockedObject Class Reference
The ClockedObject class extends the SimObject with a clock and accessor functions to relate ticks to the cycles of the object.
#include <clocked_object.hh>
Public Member Functions
void updateClockPeriod () const
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
Cycles ticksToCycles (Tick t) const
Protected Member Functions
ClockedObject (const ClockedObjectParams *p)
Create a clocked object and set the clock domain based on the parameters.
virtual ~ClockedObject ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
Private Member Functions
ClockedObject (ClockedObject &)
Prevent inadvertent use of the copy constructor and assignment operator by making them private.
ClockedObject & operator= (ClockedObject &)
void update () const
Align cycle and tick to the next clock edge if not already done.
Private Attributes
Tick tick
Cycles cycle
ClockDomain & clockDomain
The clock domain this clocked object belongs to.
Detailed Description
The ClockedObject class extends the SimObject with a clock and accessor functions to relate ticks to the cycles of the object.
Definition at line 61 of file clocked_object.hh.
Constructor & Destructor Documentation
ClockedObject::ClockedObject (ClockedObject &) [private]
Prevent inadvertent use of the copy constructor and assignment operator by making them private.
ClockedObject::ClockedObject (const ClockedObjectParams * p) [inline, protected]
Create a clocked object and set the clock domain based on the parameters.
Definition at line 121 of file clocked_object.hh.
References clockDomain, and ClockDomain::registerWithClockDomain().
virtual ClockedObject::~ClockedObject () [inline, protected, virtual]
Virtual destructor due to inheritance.
Definition at line 132 of file clocked_object.hh.
Member Function Documentation
Tick ClockedObject::clockEdge (Cycles cycles = Cycles(0)) const [inline]
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
When curTick() is on a clock edge, the number of cycles in the parameter is added to curTick() to be returned. When curTick() is not aligned to a clock edge, the number of cycles in the parameter is added to the next clock edge.
Parameters:
cycles The number of cycles into the future
Returns:
The start tick when the requested clock edge occurs. Precisely, this tick can be curTick() + [0, clockPeriod()) + clockPeriod() * cycles
Definition at line 171 of file clocked_object.hh.
References clockPeriod(), tick, and update().
Referenced by BaseXBar::calcPacketTiming(), Router::check_arbiter_reschedule(), MemTest::completeRequest(), MessageBuffer::dequeue(), Pl111::dmaDone(), HDLcd::dmaDone(), Cache::doTimingSupplyResponse(), MessageBuffer::enqueue(), RubyMemoryControl::enqueueMemRef(), RubyMemoryControl::enqueueToDirectory(), FLIPProfiler::FLIPProfiler(), Cache::handleFill(), InputUnit_d::increment_credit(), OutputUnit_d::insert_flit(), Sequencer::insertRequest(), MessageBuffer::isReady(), DMASequencer::issueNext(), Sequencer::issueRequest(), LRUProfiler::LRUProfiler(), DMASequencer::makeRequest(), MemTest::MemTest(), nextCycle(), ArmISA::TableWalker::nextWalk(), Ticked::ClockEvent::process(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), AbstractController::queueMemoryWritePartial(), Pl111::readFramebuffer(), MessageBuffer::reanalyzeAllMessages(), MessageBuffer::reanalyzeMessages(), MemTest::recvRetry(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), Cache::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), AbstractController::recvTimingResp(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), Cache::recvTimingResp(), Bridge::BridgeMasterPort::recvTimingResp(), X86ISA::Walker::recvTimingResp(), CoherentXBar::recvTimingSnoopResp(), Cache::recvTimingSnoopResp(), MessageBuffer::recycle(), HDLcd::renderPixel(), IGbE::restartClock(), BaseXBar::Layer< SrcType, DstType >::retryWaiting(), NSGigE::rxKick(), Consumer::scheduleEvent(), Consumer::scheduleEventAbsolute(), NetworkInterface::scheduleOutputLink(), NetworkInterface_d::scheduleOutputLink(), Router::scheduleOutputLinks(), FLIP::scheduleUpdatePriorityEvent(), SnapMemCtrl::sendReadPacketToNormalMemory(), DRAMSim2::startup(), Router_d::swarb_req(), NetworkTest::tick(), MemTest::tick(), Sinic::Device::transferDone(), NSGigE::transferDone(), Bridge::BridgeSlavePort::trySendTiming(), Bridge::BridgeMasterPort::trySendTiming(), DmaPort::trySendTimingReq(), NSGigE::txKick(), Router_d::update_sw_winner(), Router_d::vcarb_req(), Sequencer::wakeup(), RubyMemoryControl::wakeup(), NetworkLink::wakeup(), NetworkLink_d::wakeup(), NetworkInterface_d::wakeup(), and HDLcd::write().
Tick ClockedObject::clockPeriod () const [inline]
Definition at line 214 of file clocked_object.hh.
References clockDomain, and ClockDomain::clockPeriod().
Referenced by BaseXBar::calcPacketTiming(), clockEdge(), WireBuffer::enqueue(), MessageBuffer::enqueue(), RubyMemoryControl::enqueueMemRef(), frequency(), Cache::handleFill(), RubyPort::MemSlavePort::hitCallback(), DMASequencer::MemSlavePort::hitCallback(), QueuedPrefetcher::notify(), CpuLocalTimer::Timer::read(), X86ISA::Interrupts::readReg(), CoherentXBar::recvAtomic(), Cache::recvAtomic(), Bridge::BridgeSlavePort::recvAtomic(), CoherentXBar::recvAtomicSnoop(), Cache::recvAtomicSnoop(), RubyPort::MemSlavePort::recvTimingReq(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), RubyPort::PioMasterPort::recvTimingResp(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopResp(), WireBuffer::recycle(), SnapMemCtrl::regStats(), Router::request_vc(), resetClock(), CpuLocalTimer::Timer::restartTimerCounter(), CpuLocalTimer::Timer::restartWatchdogCounter(), TimerTable::set(), X86ISA::Interrupts::setReg(), IGbE::tick(), ticksToCycles(), BankedArray::tryAccess(), update(), and Sequencer::wakeup().
Cycles ClockedObject::curCycle () const [inline]
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Returns:
When curTick() is on a clock edge, return the Cycle corresponding to that clock edge. When curTick() is not on a clock edge, return the Cycle corresponding to the next clock edge.
Definition at line 188 of file clocked_object.hh.
References cycle, and update().
Referenced by Router::addInPort(), Router::addOutPort(), Minor::FUPipeline::advance(), SWallocator_d::arbitrate_inports(), VCallocator_d::arbitrate_invcs(), SWallocator_d::arbitrate_outports(), VCallocator_d::arbitrate_outvcs(), NetworkInterface::calculateVC(), NetworkInterface_d::calculateVC(), Minor::FUPipeline::canInsert(), Router::check_arbiter_reschedule(), VCallocator_d::check_for_wakeup(), Switch_d::check_for_wakeup(), SWallocator_d::check_for_wakeup(), RubyTester::checkForDeadlock(), Router::checkReschedule(), NetworkInterface::checkReschedule(), NetworkInterface_d::checkReschedule(), BaseCache::clearBlocked(), Throttle::collateStats(), GarnetNetwork::collateStats(), GarnetNetwork_d::collateStats(), Minor::FUPipeline::cyclesBeforeInsert(), WireBuffer::enqueue(), MessageBuffer::enqueue(), NetworkInterface::flitisizeMessage(), NetworkInterface_d::flitisizeMessage(), MessageBuffer::getSize(), Sequencer::hitCallback(), RubyTester::hitCallback(), Prefetcher::initializeStream(), Sequencer::insertRequest(), SWallocator_d::is_candidate_inport(), VCallocator_d::is_invc_candidate(), WireBuffer::isReady(), TimerTable::isReady(), NetworkLink::isReady(), Prefetcher::issueNextPrefetch(), Throttle::operateVnet(), RoutingUnit_d::RC_stage(), RubyMemoryControl::recvTimingReq(), WireBuffer::recycle(), Router::request_vc(), RubySystem::resetStats(), Router::routeCompute(), NetworkInterface::scheduleOutputLink(), NetworkInterface_d::scheduleOutputLink(), Router::scheduleOutputLinks(), VCallocator_d::select_outvc(), TimerTable::set(), BaseCache::setBlocked(), OutputUnit_d::update_vc(), Router::vc_arbitrate(), Sequencer::wakeup(), Router::wakeup(), NetworkLink::wakeup(), NetworkInterface::wakeup(), Switch_d::wakeup(), OutputUnit_d::wakeup(), NetworkLink_d::wakeup(), NetworkInterface_d::wakeup(), and InputUnit_d::wakeup().
uint64_t ClockedObject::frequency () const [inline]
Reimplemented in TsunamiIO, and MaltaIO.
Definition at line 209 of file clocked_object.hh.
References clockPeriod(), and SimClock::Frequency.
Tick ClockedObject::nextCycle () const [inline]
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
When curTick() is at the current cycle edge, this returns the next clock edge. When calling this during the middle of a cycle, this returns 2 clock edges in the future.
Returns:
The start tick of the first cycle that is at least one cycle in the future. Precisely, the returned tick can be in the range curTick() + [clockPeriod(), 2 * clockPeriod())
Definition at line 206 of file clocked_object.hh.
References clockEdge().
Referenced by SnapMemCtrl::catchSnapReadResponsePacket(), SnapMemCtrl::snapshot(), and SnapMemCtrl::snapshotCycle().
ClockedObject& ClockedObject::operator= (ClockedObject &) [private]
void ClockedObject::resetClock () const [inline, protected]
Reset the object's clock using the current global tick value.
Likely to be used only when the global clock is reset. Currently, this done only when Ruby is done warming up the memory system.
Definition at line 139 of file clocked_object.hh.
References clockPeriod(), curTick(), cycle, divCeil(), and tick.
Referenced by RubySystem::startup().
Cycles ClockedObject::ticksToCycles (Tick t) const [inline]
Definition at line 219 of file clocked_object.hh.
References clockPeriod(), and divCeil().
Referenced by BaseSetAssoc::accessBlock(), MessageBuffer::dequeue(), Pl111::dmaDone(), NetworkInterface::flitisizeMessage(), NetworkInterface_d::flitisizeMessage(), and Cache::recvAtomic().
void ClockedObject::update () const [inline, private]
Align cycle and tick to the next clock edge if not already done.
When complete, tick must be at least curTick().
Definition at line 85 of file clocked_object.hh.
References clockPeriod(), curTick(), cycle, divCeil(), and tick.
Referenced by clockEdge(), curCycle(), and updateClockPeriod().
void ClockedObject::updateClockPeriod () const [inline]
Update the tick to the current tick.
Definition at line 152 of file clocked_object.hh.
References update().
Member Data Documentation
ClockDomain& ClockedObject::clockDomain [private]
The clock domain this clocked object belongs to.
Definition at line 113 of file clocked_object.hh.
Referenced by ClockedObject(), and clockPeriod().
Cycles ClockedObject::cycle [mutable, private]
Definition at line 72 of file clocked_object.hh.
Referenced by curCycle(), resetClock(), and update().
Tick ClockedObject::tick [mutable, private]
Definition at line 68 of file clocked_object.hh.
Referenced by clockEdge(), resetClock(), and update().
The documentation for this class was generated from the following file:
sim/clocked_object.hh