gem5: MipsISA::RemoteGDB Class Reference
MipsISA::RemoteGDB Class Reference
#include <remote_gdb.hh>
Public Member Functions
RemoteGDB (System *_system, ThreadContext *tc)
Protected Member Functions
bool acc (Addr addr, size_t len)
void getregs ()
void setregs ()
Detailed Description
Definition at line 55 of file remote_gdb.hh.
Constructor & Destructor Documentation
RemoteGDB::RemoteGDB (System * _system, ThreadContext * tc)
Definition at line 151 of file remote_gdb.cc.
Member Function Documentation
bool RemoteGDB::acc (Addr addr, size_t len) [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 160 of file remote_gdb.cc.
References BaseRemoteGDB::context, FullSystem, ThreadContext::getProcessPtr(), PageTableBase::lookup(), panic, and Process::pTable.
void RemoteGDB::getregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 176 of file remote_gdb.cc.
References BaseRemoteGDB::GdbRegCache::bytes(), BaseRemoteGDB::context, DPRINTF, MipsISA::FLOATREG_FCCR, MipsISA::FLOATREG_FIR, MipsISA::GdbFloatArchRegs, MipsISA::GdbIntArchRegs, MipsISA::GdbIntRegs, BaseRemoteGDB::gdbregs, MipsISA::i, MipsISA::INTREG_HI, MipsISA::INTREG_LO, MipsISA::MISCREG_BADVADDR, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_STATUS, ThreadContext::pcState(), ThreadContext::readFloatRegBits(), ThreadContext::readIntReg(), ThreadContext::readMiscRegNoEffect(), BaseRemoteGDB::GdbRegCache::regs, and BaseRemoteGDB::GdbRegCache::regs32.
void RemoteGDB::setregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 212 of file remote_gdb.cc.
References BaseRemoteGDB::context, DPRINTF, MipsISA::FLOATREG_FCCR, MipsISA::FLOATREG_FIR, MipsISA::GdbFloatArchRegs, MipsISA::GdbIntArchRegs, MipsISA::GdbIntRegs, BaseRemoteGDB::gdbregs, MipsISA::i, MipsISA::INTREG_HI, MipsISA::INTREG_LO, MipsISA::MISCREG_BADVADDR, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_STATUS, ThreadContext::pcState(), BaseRemoteGDB::GdbRegCache::regs32, ThreadContext::setFloatRegBits(), ThreadContext::setIntReg(), and ThreadContext::setMiscRegNoEffect().
The documentation for this class was generated from the following files:
arch/mips/remote_gdb.hh
arch/mips/remote_gdb.cc