gem5: RubyTester::CpuPort Class Reference
RubyTester::CpuPort Class Reference
#include <RubyTester.hh>
Public Member Functions
CpuPort (const std::string &_name, RubyTester *_tester, PortID _id)
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
virtual void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Private Attributes
RubyTester * tester
Detailed Description
Definition at line 60 of file RubyTester.hh.
Constructor & Destructor Documentation
RubyTester::CpuPort::CpuPort (const std::string & _name, RubyTester * _tester, PortID _id) [inline]
Definition at line 72 of file RubyTester.hh.
Member Function Documentation
virtual void RubyTester::CpuPort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 78 of file RubyTester.hh.
References Port::name(), and panic.
bool RubyTester::CpuPort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 150 of file RubyTester.cc.
References RubyTester::hitCallback(), Packet::req, safe_cast(), Packet::senderState, RubyTester::SenderState::subBlock, and tester.
Member Data Documentation
RubyTester* RubyTester::CpuPort::tester [private]
Definition at line 63 of file RubyTester.hh.
Referenced by recvTimingResp().
The documentation for this class was generated from the following files:
cpu/testers/rubytest/RubyTester.hh
cpu/testers/rubytest/RubyTester.cc