gem5: AddressTable Class Reference
AddressTable Class Reference
#include <addr_tables.hh>
Public Member Functions
AddressTable ()
void insert (Addr addr)
void erase (Addr addr)
bool exists (Addr addr)
uint64_t size ()
Private Attributes
std::set< Addr > entries
Detailed Description
Definition at line 12 of file addr_tables.hh.
Constructor & Destructor Documentation
AddressTable::AddressTable () [inline]
Definition at line 18 of file addr_tables.hh.
References entries.
Member Function Documentation
void AddressTable::erase (Addr addr) [inline]
Definition at line 21 of file addr_tables.hh.
References entries, exists(), and panic.
Referenced by InsertionProfiler::access(), and InsertionProfiler::victim().
bool AddressTable::exists (Addr addr) [inline]
Definition at line 27 of file addr_tables.hh.
References entries.
Referenced by InsertionProfiler::access(), erase(), InsertionProfiler::insert(), and InsertionProfiler::victim().
void AddressTable::insert (Addr addr) [inline]
Definition at line 20 of file addr_tables.hh.
References entries.
Referenced by InsertionProfiler::insert().
uint64_t AddressTable::size () [inline]
Definition at line 28 of file addr_tables.hh.
References entries.
Referenced by InsertionProfiler::finalize().
Member Data Documentation
std::set<Addr> AddressTable::entries [private]
Definition at line 15 of file addr_tables.hh.
Referenced by AddressTable(), erase(), exists(), insert(), and size().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/addr_tables.hh