gem5: SparcISA::RemoteGDB Class Reference
SparcISA::RemoteGDB Class Reference
#include <remote_gdb.hh>
Public Member Functions
RemoteGDB (System *system, ThreadContext *context)
bool acc (Addr addr, size_t len)
Protected Types
enum RegisterConstants {
RegG0 = 0, RegO0 = 8, RegL0 = 16, RegI0 = 24,
RegF0 = 32, RegPc = 64, RegNpc, RegState,
RegFsr, RegFprs, RegY, Reg32Y = 64,
Reg32Psr = 65, Reg32Tbr = 66, Reg32Pc = 67, Reg32Npc = 68,
Reg32Fsr = 69, Reg32Csr = 70, NumGDBRegs
}
Protected Member Functions
void getregs ()
void setregs ()
Detailed Description
Definition at line 47 of file remote_gdb.hh.
Member Enumeration Documentation
enum SparcISA::RemoteGDB::RegisterConstants [protected]
Enumerator:
RegG0
RegO0
RegL0
RegI0
RegF0
RegPc
RegNpc
RegState
RegFsr
RegFprs
RegY
Reg32Y
Reg32Psr
Reg32Tbr
Reg32Pc
Reg32Npc
Reg32Fsr
Reg32Csr
NumGDBRegs
Definition at line 50 of file remote_gdb.hh.
Constructor & Destructor Documentation
RemoteGDB::RemoteGDB (System * system, ThreadContext * context)
Definition at line 146 of file remote_gdb.cc.
Member Function Documentation
bool RemoteGDB::acc (Addr addr, size_t len) [virtual]
Implements BaseRemoteGDB.
Definition at line 156 of file remote_gdb.cc.
References BaseRemoteGDB::context, FullSystem, ThreadContext::getProcessPtr(), PageTableBase::lookup(), and Process::pTable.
void RemoteGDB::getregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 181 of file remote_gdb.cc.
References BaseRemoteGDB::context, DPRINTF, BaseRemoteGDB::gdbregs, htobe(), SparcISA::MISCREG_ASI, SparcISA::MISCREG_CWP, SparcISA::MISCREG_FPRS, SparcISA::MISCREG_FSR, SparcISA::MISCREG_PSTATE, GenericISA::SimplePCState< MachInst >::npc(), SparcISA::NumIntArchRegs, GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), ThreadContext::readIntReg(), ThreadContext::readMiscReg(), Reg32Csr, Reg32Fsr, Reg32Npc, Reg32Pc, Reg32Psr, Reg32Y, RegFprs, RegFsr, RegG0, RegI0, RegNpc, RegPc, BaseRemoteGDB::GdbRegCache::regs, BaseRemoteGDB::GdbRegCache::regs32, BaseRemoteGDB::GdbRegCache::regs64, RegState, RegY, BaseRemoteGDB::GdbRegCache::size, and X86ISA::x.
void RemoteGDB::setregs () [protected, virtual]
Implements BaseRemoteGDB.
Definition at line 231 of file remote_gdb.cc.
References BaseRemoteGDB::context, BaseRemoteGDB::gdbregs, GenericISA::DelaySlotPCState< MachInst >::nnpc(), GenericISA::SimplePCState< MachInst >::npc(), GenericISA::DelaySlotUPCState< MachInst >::nupc(), GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), RegG0, RegI0, RegNpc, RegPc, BaseRemoteGDB::GdbRegCache::regs64, ThreadContext::setIntReg(), GenericISA::DelaySlotUPCState< MachInst >::upc(), and X86ISA::x.
The documentation for this class was generated from the following files:
arch/sparc/remote_gdb.hh
arch/sparc/remote_gdb.cc