gem5: ReuseDistanceAnalyzer Class Reference
ReuseDistanceAnalyzer Class Reference
#include <reuse_dist.hh>
Public Member Functions
ReuseDistanceAnalyzer (unsigned int _nsets, unsigned int _bsize)
bool exists (const Addr addr) const
unsigned int setid (Addr addr)
LRUCacheSetTracer & set (Addr addr)
void insert (Addr addr)
void victim (Addr addr)
void access (Addr addr)
void output (std::ostream *stream)
void reset ()
Private Attributes
unsigned int nsets
unsigned int bsize
unsigned int max_distance
AddressMapper addr_map
bool only_cache_range
std::unordered_map< unsigned
int, LRUCacheSetTracer > sets
Detailed Description
Definition at line 22 of file reuse_dist.hh.
Constructor & Destructor Documentation
ReuseDistanceAnalyzer::ReuseDistanceAnalyzer (unsigned int _nsets, unsigned int _bsize) [inline]
Definition at line 32 of file reuse_dist.hh.
References bsize, max_distance, and nsets.
Member Function Documentation
void ReuseDistanceAnalyzer::access (Addr addr) [inline]
Definition at line 53 of file reuse_dist.hh.
References addr_map, exists(), max_distance, and AddressMapper::put_addr().
Referenced by AddressTracer::access(), and insert().
bool ReuseDistanceAnalyzer::exists (const Addr addr) const [inline]
Definition at line 35 of file reuse_dist.hh.
Referenced by access(), and insert().
void ReuseDistanceAnalyzer::insert (Addr addr) [inline]
Definition at line 44 of file reuse_dist.hh.
References access(), and exists().
Referenced by AddressTracer::insert().
void ReuseDistanceAnalyzer::output (std::ostream * stream) [inline]
Definition at line 64 of file reuse_dist.hh.
References addr_map, and AddressMapper::order_by_spacefill().
Referenced by AddressTracer::dump().
void ReuseDistanceAnalyzer::reset () [inline]
Definition at line 76 of file reuse_dist.hh.
References addr_map, and AddressMapper::clear().
Referenced by AddressTracer::reset().
LRUCacheSetTracer& ReuseDistanceAnalyzer::set (Addr addr) [inline]
Definition at line 39 of file reuse_dist.hh.
References X86ISA::addr, setid(), and sets.
unsigned int ReuseDistanceAnalyzer::setid (Addr addr) [inline]
Definition at line 38 of file reuse_dist.hh.
References bsize, and nsets.
Referenced by set().
void ReuseDistanceAnalyzer::victim (Addr addr) [inline]
Definition at line 50 of file reuse_dist.hh.
Referenced by AddressTracer::victim().
Member Data Documentation
AddressMapper ReuseDistanceAnalyzer::addr_map [private]
Definition at line 27 of file reuse_dist.hh.
Referenced by access(), output(), and reset().
unsigned int ReuseDistanceAnalyzer::bsize [private]
Definition at line 25 of file reuse_dist.hh.
Referenced by ReuseDistanceAnalyzer(), and setid().
unsigned int ReuseDistanceAnalyzer::max_distance [private]
Definition at line 26 of file reuse_dist.hh.
Referenced by access(), and ReuseDistanceAnalyzer().
unsigned int ReuseDistanceAnalyzer::nsets [private]
Definition at line 24 of file reuse_dist.hh.
Referenced by ReuseDistanceAnalyzer(), and setid().
bool ReuseDistanceAnalyzer::only_cache_range [private]
Definition at line 28 of file reuse_dist.hh.
std::unordered_map<unsigned int, LRUCacheSetTracer> ReuseDistanceAnalyzer::sets [private]
Definition at line 29 of file reuse_dist.hh.
Referenced by set().
The documentation for this class was generated from the following file:
mem/cache/tags/prof/reuse_dist.hh