gem5: CacheMemory Class Reference
CacheMemory Class Reference
#include <CacheMemory.hh>
Public Types
typedef RubyCacheParams Params
Public Member Functions
CacheMemory (const Params *p)
~CacheMemory ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
bool tryCacheAccess (const Address &address, RubyRequestType type, DataBlock *&data_ptr)
bool testCacheAccess (const Address &address, RubyRequestType type, DataBlock *&data_ptr)
bool isTagPresent (const Address &address) const
bool cacheAvail (const Address &address) const
AbstractCacheEntry * allocate (const Address &address, AbstractCacheEntry *new_entry)
void allocateVoid (const Address &address, AbstractCacheEntry *new_entry)
void deallocate (const Address &address)
Address cacheProbe (const Address &address) const
AbstractCacheEntry * lookup (const Address &address)
const AbstractCacheEntry * lookup (const Address &address) const
Cycles getLatency () const
void recordCacheContents (int cntrl, CacheRecorder *tr) const
void setMRU (const Address &address)
void setLocked (const Address &addr, int context)
void clearLocked (const Address &addr)
bool isLocked (const Address &addr, int context)
void print (std::ostream &out) const
void printData (std::ostream &out) const
void regStats ()
Register statistics for this object.
bool checkResourceAvailable (CacheResourceType res, Address addr)
void recordRequestType (CacheRequestType requestType)
Public Attributes
Stats::Scalar m_demand_hits
Stats::Scalar m_demand_misses
Stats::Formula m_demand_accesses
Stats::Scalar m_sw_prefetches
Stats::Scalar m_hw_prefetches
Stats::Formula m_prefetches
Stats::Vector m_accessModeType
Stats::Scalar numDataArrayReads
Stats::Scalar numDataArrayWrites
Stats::Scalar numTagArrayReads
Stats::Scalar numTagArrayWrites
Stats::Scalar numTagArrayStalls
Stats::Scalar numDataArrayStalls
Private Member Functions
int64 addressToCacheSet (const Address &address) const
int findTagInSet (int64 line, const Address &tag) const
int findTagInSetIgnorePermissions (int64 cacheSet, const Address &tag) const
CacheMemory (const CacheMemory &obj)
CacheMemory & operator= (const CacheMemory &obj)
Private Attributes
Cycles m_latency
bool m_is_instruction_only_cache
m5::hash_map< Address, int > m_tag_index
std::vector< std::vector
< AbstractCacheEntry * > > m_cache
AbstractReplacementPolicy * m_replacementPolicy_ptr
BankedArray dataArray
BankedArray tagArray
int m_cache_size
std::string m_policy
int m_cache_num_sets
int m_cache_num_set_bits
int m_cache_assoc
int m_start_index_bit
bool m_resource_stalls
Detailed Description
Definition at line 50 of file CacheMemory.hh.
Member Typedef Documentation
typedef RubyCacheParams CacheMemory::Params
Reimplemented from SimObject.
Definition at line 53 of file CacheMemory.hh.
Constructor & Destructor Documentation
CacheMemory::CacheMemory (const Params * p)
Definition at line 54 of file CacheMemory.cc.
References m_cache_assoc, m_cache_size, m_is_instruction_only_cache, m_latency, m_policy, m_resource_stalls, and m_start_index_bit.
CacheMemory::~CacheMemory ()
Definition at line 95 of file CacheMemory.cc.
References ArmISA::i, ArmISA::j, m_cache, m_cache_assoc, m_cache_num_sets, and m_replacementPolicy_ptr.
CacheMemory::CacheMemory (const CacheMemory & obj) [private]
Member Function Documentation
int64 CacheMemory::addressToCacheSet (const Address & address) const [private]
Definition at line 108 of file CacheMemory.cc.
References Address::bitSelect(), line_address(), m_cache_num_set_bits, and m_start_index_bit.
Referenced by allocate(), cacheAvail(), cacheProbe(), checkResourceAvailable(), clearLocked(), deallocate(), isLocked(), isTagPresent(), lookup(), setLocked(), setMRU(), testCacheAccess(), and tryCacheAccess().
AbstractCacheEntry * CacheMemory::allocate (const Address & address, AbstractCacheEntry * new_entry)
Definition at line 237 of file CacheMemory.cc.
References addressToCacheSet(), cacheAvail(), curTick(), DPRINTF, ArmISA::i, isTagPresent(), line_address(), AbstractCacheEntry::m_Address, m_cache, m_cache_assoc, m_replacementPolicy_ptr, m_tag_index, panic, and AbstractReplacementPolicy::touch().
Referenced by allocateVoid().
void CacheMemory::allocateVoid (const Address & address, AbstractCacheEntry * new_entry) [inline]
Definition at line 78 of file CacheMemory.hh.
References allocate().
bool CacheMemory::cacheAvail (const Address & address) const
Definition at line 215 of file CacheMemory.cc.
References addressToCacheSet(), ArmISA::i, line_address(), AbstractCacheEntry::m_Address, m_cache, m_cache_assoc, and AbstractEntry::m_Permission.
Referenced by allocate(), and cacheProbe().
Address CacheMemory::cacheProbe (const Address & address) const
Definition at line 282 of file CacheMemory.cc.
References addressToCacheSet(), cacheAvail(), AbstractReplacementPolicy::getVictim(), line_address(), m_cache, and m_replacementPolicy_ptr.
bool CacheMemory::checkResourceAvailable (CacheResourceType res, Address addr)
Definition at line 537 of file CacheMemory.cc.
References addressToCacheSet(), dataArray, DPRINTF, m_resource_stalls, numDataArrayStalls, numTagArrayStalls, tagArray, and BankedArray::tryAccess().
void CacheMemory::clearLocked (const Address & addr)
Definition at line 401 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), line_address(), and m_cache.
Referenced by Sequencer::handleLlsc(), and Sequencer::invalidateSC().
void CacheMemory::deallocate (const Address & address)
Definition at line 266 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), isTagPresent(), line_address(), m_cache, and m_tag_index.
int CacheMemory::findTagInSet (int64 line, const Address & tag) const [private]
Definition at line 118 of file CacheMemory.cc.
References line_address(), m_cache, and m_tag_index.
Referenced by clearLocked(), deallocate(), isLocked(), isTagPresent(), lookup(), setLocked(), setMRU(), testCacheAccess(), and tryCacheAccess().
int CacheMemory::findTagInSetIgnorePermissions (int64 cacheSet, const Address & tag) const [private]
Definition at line 133 of file CacheMemory.cc.
References line_address(), and m_tag_index.
Cycles CacheMemory::getLatency () const [inline]
Definition at line 93 of file CacheMemory.hh.
References m_latency.
Referenced by Sequencer::issueRequest().
void CacheMemory::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 69 of file CacheMemory.cc.
References floorLog2(), RubySystem::getBlockSizeBytes(), ArmISA::i, ArmISA::j, m_cache, m_cache_assoc, m_cache_num_set_bits, m_cache_num_sets, m_cache_size, m_policy, and m_replacementPolicy_ptr.
bool CacheMemory::isLocked (const Address & addr, int context)
Definition at line 412 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), line_address(), and m_cache.
Referenced by Sequencer::handleLlsc().
bool CacheMemory::isTagPresent (const Address & address) const
Definition at line 196 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), and line_address().
Referenced by allocate(), deallocate(), and Sequencer::handleLlsc().
const AbstractCacheEntry * CacheMemory::lookup (const Address & address) const
Definition at line 305 of file CacheMemory.cc.
References addressToCacheSet(), findTagInSet(), line_address(), and m_cache.
AbstractCacheEntry * CacheMemory::lookup (const Address & address)
Definition at line 294 of file CacheMemory.cc.
References addressToCacheSet(), findTagInSet(), line_address(), and m_cache.
CacheMemory& CacheMemory::operator= (const CacheMemory & obj) [private]
void CacheMemory::print (std::ostream & out) const
Referenced by operator<<().
void CacheMemory::printData (std::ostream & out) const
void CacheMemory::recordCacheContents (int cntrl, CacheRecorder * tr) const
Definition at line 326 of file CacheMemory.cc.
References CacheRecorder::addRecord(), DPRINTF, AbstractReplacementPolicy::getLastAccess(), ArmISA::i, ArmISA::j, ArmISA::M5_VAR_USED, m_cache, m_cache_assoc, m_cache_num_sets, m_is_instruction_only_cache, m_replacementPolicy_ptr, and SimObject::name().
void CacheMemory::recordRequestType (CacheRequestType requestType)
Definition at line 513 of file CacheMemory.cc.
References DPRINTF, numDataArrayReads, numDataArrayWrites, numTagArrayReads, numTagArrayWrites, and warn.
void CacheMemory::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 424 of file CacheMemory.cc.
References ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), m_accessModeType, m_demand_accesses, m_demand_hits, m_demand_misses, m_hw_prefetches, m_prefetches, m_sw_prefetches, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, numDataArrayReads, numDataArrayStalls, numDataArrayWrites, numTagArrayReads, numTagArrayStalls, numTagArrayWrites, Stats::pdf, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), and Stats::total.
void CacheMemory::setLocked (const Address & addr, int context)
Definition at line 390 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), line_address(), and m_cache.
Referenced by Sequencer::handleLlsc().
void CacheMemory::setMRU (const Address & address)
Definition at line 316 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), findTagInSet(), m_replacementPolicy_ptr, and AbstractReplacementPolicy::touch().
Referenced by Sequencer::hitCallback().
bool CacheMemory::testCacheAccess (const Address & address, RubyRequestType type, DataBlock *& data_ptr)
Definition at line 172 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), DPRINTF, findTagInSet(), AbstractCacheEntry::getDataBlk(), line_address(), m_cache, m_replacementPolicy_ptr, and AbstractReplacementPolicy::touch().
bool CacheMemory::tryCacheAccess (const Address & address, RubyRequestType type, DataBlock *& data_ptr)
Definition at line 145 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), DPRINTF, findTagInSet(), AbstractCacheEntry::getDataBlk(), line_address(), m_cache, AbstractEntry::m_Permission, m_replacementPolicy_ptr, and AbstractReplacementPolicy::touch().
Member Data Documentation
BankedArray CacheMemory::dataArray [private]
Definition at line 159 of file CacheMemory.hh.
Referenced by checkResourceAvailable().
Stats::Vector CacheMemory::m_accessModeType
Definition at line 122 of file CacheMemory.hh.
Referenced by regStats().
std::vector<std::vector<AbstractCacheEntry*> > CacheMemory::m_cache [private]
Definition at line 155 of file CacheMemory.hh.
Referenced by allocate(), cacheAvail(), cacheProbe(), clearLocked(), deallocate(), findTagInSet(), init(), isLocked(), lookup(), recordCacheContents(), setLocked(), testCacheAccess(), tryCacheAccess(), and ~CacheMemory().
int CacheMemory::m_cache_assoc [private]
Definition at line 166 of file CacheMemory.hh.
Referenced by allocate(), cacheAvail(), CacheMemory(), init(), recordCacheContents(), and ~CacheMemory().
int CacheMemory::m_cache_num_set_bits [private]
Definition at line 165 of file CacheMemory.hh.
Referenced by addressToCacheSet(), and init().
int CacheMemory::m_cache_num_sets [private]
Definition at line 164 of file CacheMemory.hh.
Referenced by init(), recordCacheContents(), and ~CacheMemory().
int CacheMemory::m_cache_size [private]
Definition at line 162 of file CacheMemory.hh.
Referenced by CacheMemory(), and init().
Stats::Formula CacheMemory::m_demand_accesses
Definition at line 116 of file CacheMemory.hh.
Referenced by regStats().
Stats::Scalar CacheMemory::m_demand_hits
Definition at line 114 of file CacheMemory.hh.
Referenced by regStats().
Stats::Scalar CacheMemory::m_demand_misses
Definition at line 115 of file CacheMemory.hh.
Referenced by regStats().
Stats::Scalar CacheMemory::m_hw_prefetches
Definition at line 119 of file CacheMemory.hh.
Referenced by regStats().
bool CacheMemory::m_is_instruction_only_cache [private]
Definition at line 150 of file CacheMemory.hh.
Referenced by CacheMemory(), and recordCacheContents().
Cycles CacheMemory::m_latency [private]
Definition at line 147 of file CacheMemory.hh.
Referenced by CacheMemory(), and getLatency().
std::string CacheMemory::m_policy [private]
Definition at line 163 of file CacheMemory.hh.
Referenced by CacheMemory(), and init().
Stats::Formula CacheMemory::m_prefetches
Definition at line 120 of file CacheMemory.hh.
Referenced by regStats().
AbstractReplacementPolicy* CacheMemory::m_replacementPolicy_ptr [private]
Definition at line 157 of file CacheMemory.hh.
Referenced by allocate(), cacheProbe(), init(), recordCacheContents(), setMRU(), testCacheAccess(), tryCacheAccess(), and ~CacheMemory().
bool CacheMemory::m_resource_stalls [private]
Definition at line 168 of file CacheMemory.hh.
Referenced by CacheMemory(), and checkResourceAvailable().
int CacheMemory::m_start_index_bit [private]
Definition at line 167 of file CacheMemory.hh.
Referenced by addressToCacheSet(), and CacheMemory().
Stats::Scalar CacheMemory::m_sw_prefetches
Definition at line 118 of file CacheMemory.hh.
Referenced by regStats().
m5::hash_map<Address, int> CacheMemory::m_tag_index [private]
Definition at line 154 of file CacheMemory.hh.
Referenced by allocate(), deallocate(), findTagInSet(), and findTagInSetIgnorePermissions().
Stats::Scalar CacheMemory::numDataArrayReads
Definition at line 124 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
Stats::Scalar CacheMemory::numDataArrayStalls
Definition at line 130 of file CacheMemory.hh.
Referenced by checkResourceAvailable(), and regStats().
Stats::Scalar CacheMemory::numDataArrayWrites
Definition at line 125 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
Stats::Scalar CacheMemory::numTagArrayReads
Definition at line 126 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
Stats::Scalar CacheMemory::numTagArrayStalls
Definition at line 129 of file CacheMemory.hh.
Referenced by checkResourceAvailable(), and regStats().
Stats::Scalar CacheMemory::numTagArrayWrites
Definition at line 127 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
BankedArray CacheMemory::tagArray [private]
Definition at line 160 of file CacheMemory.hh.
Referenced by checkResourceAvailable().
The documentation for this class was generated from the following files:
mem/ruby/structures/CacheMemory.hh
mem/ruby/structures/CacheMemory.cc