gem5: Trace::InstPBTraceRecord Class Reference
Trace::InstPBTraceRecord Class Reference
This in an instruction tracer that records the flow of instructions through multiple cpus and systems to a protobuf file specified by proto/inst.proto for further analysis.
#include <inst_pb_trace.hh>
Public Member Functions
InstPBTraceRecord (InstPBTrace &_tracer, Tick when, ThreadContext *tc, const StaticInstPtr si, TheISA::PCState pc, const StaticInstPtr mi=NULL)
void dump () M5_ATTR_OVERRIDE
called by the cpu when the instruction commits.
Protected Attributes
InstPBTrace & tracer
Detailed Description
This in an instruction tracer that records the flow of instructions through multiple cpus and systems to a protobuf file specified by proto/inst.proto for further analysis.
Definition at line 65 of file inst_pb_trace.hh.
Constructor & Destructor Documentation
Trace::InstPBTraceRecord::InstPBTraceRecord (InstPBTrace & _tracer, Tick when, ThreadContext * tc, const StaticInstPtr si, TheISA::PCState pc, const StaticInstPtr mi = NULL) [inline]
Definition at line 68 of file inst_pb_trace.hh.
Member Function Documentation
void Trace::InstPBTraceRecord::dump () [virtual]
called by the cpu when the instruction commits.
This implementation of dump calls InstPBTrace to output the contents to a protobuf file
Implements Trace::InstRecord.
Definition at line 57 of file inst_pb_trace.cc.
References Trace::InstRecord::getAddr(), Trace::InstRecord::getFlags(), Trace::InstRecord::getMemValid(), Trace::InstRecord::getSize(), Trace::InstRecord::macroStaticInst, Trace::InstRecord::pc, Trace::InstRecord::staticInst, Trace::InstRecord::thread, Trace::InstPBTrace::traceInst(), Trace::InstPBTrace::traceMem(), and tracer.
Member Data Documentation
InstPBTrace& Trace::InstPBTraceRecord::tracer [protected]
Definition at line 81 of file inst_pb_trace.hh.
Referenced by dump().
The documentation for this class was generated from the following files:
cpu/inst_pb_trace.hh
cpu/inst_pb_trace.cc