gem5: MipsLiveProcess Class Reference
MipsLiveProcess Class Reference
#include <process.hh>
Public Member Functions
MipsISA::IntReg getSyscallArg (ThreadContext *tc, int &i)
void setSyscallArg (ThreadContext *tc, int i, MipsISA::IntReg val)
void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)
Protected Member Functions
MipsLiveProcess (LiveProcessParams *params, ObjectFile *objFile)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
template<class IntType >
void argsInit (int pageSize)
Detailed Description
Definition at line 44 of file process.hh.
Constructor & Destructor Documentation
MipsLiveProcess::MipsLiveProcess (LiveProcessParams * params, ObjectFile * objFile) [protected]
Definition at line 48 of file process.cc.
References Process::brk_point, ObjectFile::bssSize(), ObjectFile::dataBase(), ObjectFile::dataSize(), X86ISA::L, Process::mmap_end, Process::mmap_start, Process::next_thread_stack_base, AlphaISA::PageBytes, roundUp(), and Process::stack_base.
Member Function Documentation
template<class IntType > void MipsLiveProcess::argsInit (int pageSize) [inline, protected]
Definition at line 77 of file process.cc.
References X86ISA::addr, Process::allocateMem(), LiveProcess::argv, Process::contextIds, copyStringArray(), DPRINTF, LiveProcess::egid(), ObjectFile::entryPoint(), LiveProcess::envp, LiveProcess::euid(), System::getThreadContext(), LiveProcess::gid(), BigEndianGuest::htog(), ArmISA::i, Process::initVirtMem, ObjectFile::loadSections(), LiveProcess::M5_AT_CLKTCK, LiveProcess::M5_AT_EGID, LiveProcess::M5_AT_ENTRY, LiveProcess::M5_AT_EUID, LiveProcess::M5_AT_GID, LiveProcess::M5_AT_PAGESZ, LiveProcess::M5_AT_PHDR, LiveProcess::M5_AT_PHENT, LiveProcess::M5_AT_PHNUM, LiveProcess::M5_AT_UID, LiveProcess::objFile, MipsISA::PageBytes, ThreadContext::pcState(), ElfObject::programHeaderCount(), ElfObject::programHeaderSize(), ElfObject::programHeaderTable(), roundDown(), roundUp(), ThreadContext::setIntReg(), setSyscallArg(), Process::stack_base, Process::stack_min, Process::stack_size, AlphaISA::StackPointerReg, Process::system, ArmISA::tc, LiveProcess::uid(), SETranslatingPortProxy::writeBlob(), and X86ISA::x.
MipsISA::IntReg MipsLiveProcess::getSyscallArg (ThreadContext * tc, int & i) [virtual]
Implements LiveProcess.
Definition at line 185 of file process.cc.
References FirstArgumentReg, and ThreadContext::readIntReg().
void MipsLiveProcess::initState () [protected, virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from Process.
Definition at line 68 of file process.cc.
References AlphaISA::PageBytes.
void MipsLiveProcess::setSyscallArg (ThreadContext * tc, int i, MipsISA::IntReg val)
Definition at line 192 of file process.cc.
References FirstArgumentReg, and ThreadContext::setIntReg().
Referenced by argsInit().
void MipsLiveProcess::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) [virtual]
Implements LiveProcess.
Definition at line 200 of file process.cc.
References SyscallReturn::errnoValue(), SyscallReturn::returnValue(), AlphaISA::ReturnValueReg, ThreadContext::setIntReg(), SyscallReturn::successful(), and AlphaISA::SyscallSuccessReg.
The documentation for this class was generated from the following files:
arch/mips/process.hh
arch/mips/process.cc