gem5: ArmISA::PredImmOp Class Reference
ArmISA::PredImmOp Class Reference
Base class for predicated immediate operations.
#include <pred_inst.hh>
Protected Member Functions
PredImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass)
Constructor.
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
uint32_t imm
uint32_t rotated_imm
uint32_t rotated_carry
uint32_t rotate
Detailed Description
Base class for predicated immediate operations.
Definition at line 206 of file pred_inst.hh.
Constructor & Destructor Documentation
ArmISA::PredImmOp::PredImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass) [inline, protected]
Constructor.
Definition at line 216 of file pred_inst.hh.
References bits(), imm, rotate, ArmISA::rotate_imm(), rotated_carry, and rotated_imm.
Member Function Documentation
std::string ArmISA::PredImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 65 of file pred_inst.cc.
References imm, StaticInst::machInst, ArmISA::ArmStaticInst::printDataInst(), and ArmISA::ss.
Member Data Documentation
uint32_t ArmISA::PredImmOp::imm [protected]
Definition at line 210 of file pred_inst.hh.
Referenced by generateDisassembly(), and PredImmOp().
uint32_t ArmISA::PredImmOp::rotate [protected]
Definition at line 213 of file pred_inst.hh.
Referenced by PredImmOp().
uint32_t ArmISA::PredImmOp::rotated_carry [protected]
Definition at line 212 of file pred_inst.hh.
Referenced by PredImmOp().
uint32_t ArmISA::PredImmOp::rotated_imm [protected]
Definition at line 211 of file pred_inst.hh.
Referenced by PredImmOp().
The documentation for this class was generated from the following files:
arch/arm/insts/pred_inst.hh
arch/arm/insts/pred_inst.cc