gem5: SimpleMemory Class Reference
SimpleMemory Class Reference
The simple memory is a basic single-ported memory controller with a configurable throughput and latency.
#include <simple_mem.hh>
Classes
class DeferredPacket
A deferred packet stores a packet along with its scheduled transmission time.
class MemoryPort
Public Member Functions
SimpleMemory (const SimpleMemoryParams *p)
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
void init ()
Initialise this memory.
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
void recvFunctional (PacketPtr pkt)
bool recvTimingReq (PacketPtr pkt)
void recvRespRetry ()
Private Member Functions
void release ()
Release the memory after being busy and send a retry if a request was rejected in the meanwhile.
void dequeue ()
Dequeue a packet from our internal packet queue and move it to the port where it will be sent as soon as possible.
Tick getLatency () const
Detemine the latency.
Private Attributes
MemoryPort port
const Tick latency
Latency from that a request is accepted until the response is ready to be sent.
const Tick latency_var
Fudge factor added to the latency.
std::deque< DeferredPacket > packetQueue
Internal (unbounded) storage to mimic the delay caused by the actual memory access.
const double bandwidth
Bandwidth in ticks per byte.
bool isBusy
Track the state of the memory as either idle or busy, no need for an enum with only two states.
bool retryReq
Remember if we have to retry an outstanding request that arrived while we were busy.
bool retryResp
Remember if we failed to send a response and are awaiting a retry.
EventWrapper< SimpleMemory,&SimpleMemory::release > releaseEvent
EventWrapper< SimpleMemory,&SimpleMemory::dequeue > dequeueEvent
std::vector< PacketPtr > pendingDelete
DrainManager * drainManager
If we need to drain, keep the drain manager around until we're done here.
Detailed Description
The simple memory is a basic single-ported memory controller with a configurable throughput and latency.
See also:
gem5 Memory System
Definition at line 64 of file simple_mem.hh.
Constructor & Destructor Documentation
SimpleMemory::SimpleMemory (const SimpleMemoryParams * p)
Definition at line 51 of file simple_mem.cc.
Member Function Documentation
void SimpleMemory::dequeue () [private]
Dequeue a packet from our internal packet queue and move it to the port where it will be sent as soon as possible.
Definition at line 186 of file simple_mem.cc.
References curTick(), dequeueEvent, DPRINTF, drainManager, packetQueue, port, EventManager::reschedule(), retryResp, SlavePort::sendTimingResp(), and DrainManager::signalDrainDone().
Referenced by recvRespRetry().
unsigned int SimpleMemory::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 237 of file simple_mem.cc.
References X86ISA::count, DPRINTF, Drainable::Drained, Drainable::Draining, drainManager, packetQueue, and Drainable::setDrainState().
Tick SimpleMemory::getLatency () const [private]
Detemine the latency.
Returns:
the latency seen by the current packet
Definition at line 212 of file simple_mem.cc.
References latency, latency_var, Random::random(), and random_mt.
Referenced by recvAtomic(), and recvTimingReq().
BaseSlavePort & SimpleMemory::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 227 of file simple_mem.cc.
References port.
void SimpleMemory::init () [virtual]
Initialise this memory.
Reimplemented from AbstractMemory.
Definition at line 61 of file simple_mem.cc.
References BaseSlavePort::isConnected(), port, and SlavePort::sendRangeChange().
Tick SimpleMemory::recvAtomic (PacketPtr pkt) [protected]
Definition at line 73 of file simple_mem.cc.
References AbstractMemory::access(), getLatency(), and Packet::memInhibitAsserted().
Referenced by SimpleMemory::MemoryPort::recvAtomic(), and recvTimingReq().
void SimpleMemory::recvFunctional (PacketPtr pkt) [protected]
Definition at line 80 of file simple_mem.cc.
References Packet::checkFunctional(), AbstractMemory::functionalAccess(), SimObject::name(), MipsISA::p, packetQueue, Packet::popLabel(), and Packet::pushLabel().
Referenced by SimpleMemory::MemoryPort::recvFunctional().
void SimpleMemory::recvRespRetry () [protected]
Definition at line 219 of file simple_mem.cc.
References dequeue(), and retryResp.
Referenced by SimpleMemory::MemoryPort::recvRespRetry().
bool SimpleMemory::recvTimingReq (PacketPtr pkt) [protected]
Todo:
temporary hack to deal with memory corruption issues until 4-phase transactions are complete
Definition at line 98 of file simple_mem.cc.
References bandwidth, curTick(), dequeueEvent, getLatency(), Packet::getSize(), Packet::headerDelay, isBusy, Packet::isRead(), Packet::isResponse(), Packet::isWrite(), Packet::memInhibitAsserted(), Packet::needsResponse(), packetQueue, Packet::payloadDelay, pendingDelete, recvAtomic(), releaseEvent, retryReq, retryResp, EventManager::schedule(), Event::scheduled(), and X86ISA::x.
Referenced by SimpleMemory::MemoryPort::recvTimingReq().
void SimpleMemory::release () [private]
Release the memory after being busy and send a retry if a request was rejected in the meanwhile.
Definition at line 175 of file simple_mem.cc.
References isBusy, port, retryReq, and SlavePort::sendRetryReq().
Member Data Documentation
const double SimpleMemory::bandwidth [private]
Bandwidth in ticks per byte.
The regulation affects the acceptance rate of requests and the queueing takes place after the regulation.
Definition at line 135 of file simple_mem.hh.
Referenced by recvTimingReq().
EventWrapper<SimpleMemory, &SimpleMemory::dequeue> SimpleMemory::dequeueEvent [private]
Definition at line 169 of file simple_mem.hh.
Referenced by dequeue(), and recvTimingReq().
DrainManager* SimpleMemory::drainManager [private]
If we need to drain, keep the drain manager around until we're done here.
Definition at line 188 of file simple_mem.hh.
Referenced by dequeue(), and drain().
bool SimpleMemory::isBusy [private]
Track the state of the memory as either idle or busy, no need for an enum with only two states.
Definition at line 141 of file simple_mem.hh.
Referenced by recvTimingReq(), and release().
const Tick SimpleMemory::latency [private]
Latency from that a request is accepted until the response is ready to be sent.
Definition at line 116 of file simple_mem.hh.
Referenced by getLatency().
const Tick SimpleMemory::latency_var [private]
Fudge factor added to the latency.
Definition at line 121 of file simple_mem.hh.
Referenced by getLatency().
std::deque<DeferredPacket> SimpleMemory::packetQueue [private]
Internal (unbounded) storage to mimic the delay caused by the actual memory access.
Note that this is where the packet spends the memory latency.
Definition at line 128 of file simple_mem.hh.
Referenced by dequeue(), drain(), recvFunctional(), and recvTimingReq().
std::vector<PacketPtr> SimpleMemory::pendingDelete [private]
Todo:
this is a temporary workaround until the 4-phase code is committed. upstream caches needs this packet until true is returned, so hold onto it for deletion until a subsequent call
Definition at line 182 of file simple_mem.hh.
Referenced by recvTimingReq().
MemoryPort SimpleMemory::port [private]
Definition at line 110 of file simple_mem.hh.
Referenced by dequeue(), getSlavePort(), init(), and release().
EventWrapper<SimpleMemory, &SimpleMemory::release> SimpleMemory::releaseEvent [private]
Definition at line 161 of file simple_mem.hh.
Referenced by recvTimingReq().
bool SimpleMemory::retryReq [private]
Remember if we have to retry an outstanding request that arrived while we were busy.
Definition at line 147 of file simple_mem.hh.
Referenced by recvTimingReq(), and release().
bool SimpleMemory::retryResp [private]
Remember if we failed to send a response and are awaiting a retry.
This is only used as a check.
Definition at line 153 of file simple_mem.hh.
Referenced by dequeue(), recvRespRetry(), and recvTimingReq().
The documentation for this class was generated from the following files:
mem/simple_mem.hh
mem/simple_mem.cc