gem5: FALRU Class Reference
FALRU Class Reference
A fully associative LRU cache.
#include <fa_lru.hh>
Public Types
typedef FALRUBlk BlkType
Typedef the block type used in this class.
typedef std::list< FALRUBlk * > BlkList
Typedef a list of pointers to the local block type.
typedef FALRUParams Params
Public Member Functions
FALRU (const Params *p)
Construct and initialize this cache tagstore.
~FALRU ()
void regStats ()
Register the stats for this object.
void invalidate (CacheBlk *blk)
Invalidate a cache block.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src, int *inCache)
Access block and update replacement data.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Just a wrapper of above function to conform with the base interface.
CacheBlk * findBlock (Addr addr, bool is_secure) const
Find the block in the cache, do not update the replacement data.
CacheBlk * findVictim (Addr addr)
Find a replacement block for the address provided.
void insertBlock (PacketPtr pkt, CacheBlk *blk)
unsigned getBlockSize () const
Return the block size of this cache.
unsigned getSubBlockSize () const
Return the subblock size of this cache, always the block size.
Addr blkAlign (Addr addr) const
Align an address to the block size.
Addr extractTag (Addr addr) const
Generate the tag from the addres.
int extractSet (Addr addr) const
Return the set of an address.
Addr regenerateBlkAddr (Addr tag, unsigned set) const
Regenerate the block address from the tag and the set.
virtual void clearLocks ()
iterated through all blocks and clear all locks Needed to clear all lock tracking at once
virtual std::string print () const
void forEachBlk (CacheBlkVisitor &visitor) M5_ATTR_OVERRIDE
Visit each block in the tag store and apply a visitor to the block.
Protected Types
typedef m5::hash_map< Addr,
FALRUBlk *, m5::hash< Addr > > hash_t
Hash table type mapping addresses to cache block pointers.
typedef hash_t::const_iterator tagIterator
Iterator into the address hash table.
Protected Member Functions
FALRUBlk * hashLookup (Addr addr) const
Find the cache block for the given address.
void moveToHead (FALRUBlk *blk)
Move a cache block to the MRU position.
bool check ()
Check to make sure all the cache boundaries are still where they should be.
Protected Attributes
FALRUBlk ** cacheBoundaries
Array of pointers to blocks at the cache size boundaries.
int cacheMask
A mask for the FALRUBlk::inCache bits.
unsigned numCaches
The number of different size caches being tracked.
FALRUBlk * blks
The cache blocks.
FALRUBlk * head
The MRU block.
FALRUBlk * tail
The LRU block.
hash_t tagHash
The address hash table.
Stats::Vector hits
Hits in each cache size >= 128K.
Stats::Vector misses
Misses in each cache size >= 128K.
Stats::Scalar accesses
Total number of accesses.
Detailed Description
A fully associative LRU cache.
Keeps statistics for accesses to a number of cache sizes at once.
Definition at line 87 of file fa_lru.hh.
Member Typedef Documentation
typedef std::list<FALRUBlk*> FALRU::BlkList
Typedef a list of pointers to the local block type.
Definition at line 93 of file fa_lru.hh.
typedef FALRUBlk FALRU::BlkType
Typedef the block type used in this class.
Definition at line 91 of file fa_lru.hh.
typedef m5::hash_map<Addr, FALRUBlk *, m5::hash<Addr> > FALRU::hash_t [protected]
Hash table type mapping addresses to cache block pointers.
Definition at line 112 of file fa_lru.hh.
typedef FALRUParams FALRU::Params
Reimplemented from BaseTags.
Definition at line 159 of file fa_lru.hh.
typedef hash_t::const_iterator FALRU::tagIterator [protected]
Iterator into the address hash table.
Definition at line 114 of file fa_lru.hh.
Constructor & Destructor Documentation
FALRU::FALRU (const Params * p)
Construct and initialize this cache tagstore.
Definition at line 57 of file fa_lru.cc.
References blks, BaseTags::blkSize, cacheBoundaries, cacheMask, fatal, floorLog2(), head, ArmISA::i, FALRUBlk::inCache, MipsISA::index, isPowerOf2(), FALRUBlk::isTouched, ArmISA::j, FALRUBlk::next, BaseTags::numBlocks, numCaches, FALRUBlk::prev, BaseTags::size, tail, and BaseTags::warmupBound.
FALRU::~FALRU ()
Definition at line 110 of file fa_lru.cc.
References blks, cacheBoundaries, and numCaches.
Member Function Documentation
CacheBlk * FALRU::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Just a wrapper of above function to conform with the base interface.
Implements BaseTags.
Definition at line 171 of file fa_lru.cc.
References accessBlock().
CacheBlk * FALRU::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src, int * inCache)
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency and inCache flags as a side effect.
Parameters:
addr The address to look for.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The latency of the access.
inCache The FALRUBlk::inCache flags.
Returns:
Pointer to the cache block.
Definition at line 177 of file fa_lru.cc.
References accesses, BaseTags::accessLatency, blkAlign(), hashLookup(), head, hits, ArmISA::i, FALRUBlk::inCache, CacheBlk::isValid(), misses, moveToHead(), numCaches, and CacheBlk::tag.
Referenced by accessBlock().
Addr FALRU::blkAlign (Addr addr) const [inline]
Align an address to the block size.
Parameters:
addr the address to align.
Returns:
The aligned address.
Definition at line 243 of file fa_lru.hh.
References BaseTags::blkSize.
Referenced by accessBlock(), extractTag(), findBlock(), and findVictim().
bool FALRU::check () [protected]
Check to make sure all the cache boundaries are still where they should be.
Used for debugging.
Returns:
True if everything is correct.
Definition at line 286 of file fa_lru.cc.
References BaseTags::blkSize, cacheBoundaries, cacheMask, head, FALRUBlk::inCache, ArmISA::j, FALRUBlk::next, and tail.
void FALRU::clearLocks () [virtual]
iterated through all blocks and clear all locks Needed to clear all lock tracking at once
Reimplemented from BaseTags.
Definition at line 312 of file fa_lru.cc.
References blks, CacheBlk::clearLoadLocks(), ArmISA::i, and BaseTags::numBlocks.
int FALRU::extractSet (Addr addr) const [inline, virtual]
Return the set of an address.
Only one set in a fully associative cache.
Parameters:
addr The address to get the set from.
Returns:
0.
Implements BaseTags.
Definition at line 264 of file fa_lru.hh.
Addr FALRU::extractTag (Addr addr) const [inline, virtual]
Generate the tag from the addres.
For fully associative this is just the block address.
Parameters:
addr The address to get the tag from.
Returns:
The tag.
Implements BaseTags.
Definition at line 254 of file fa_lru.hh.
References blkAlign().
CacheBlk * FALRU::findBlock (Addr addr, bool is_secure) const [virtual]
Find the block in the cache, do not update the replacement data.
Parameters:
addr The address to look for.
is_secure True if the target memory space is secure.
asid The address space ID.
Returns:
Pointer to the cache block.
Implements BaseTags.
Definition at line 216 of file fa_lru.cc.
References blkAlign(), hashLookup(), CacheBlk::isValid(), and CacheBlk::tag.
CacheBlk * FALRU::findVictim (Addr addr) [virtual]
Find a replacement block for the address provided.
Parameters:
pkt The request to a find a replacement candidate for.
Returns:
The block to place the replacement in.
Implements BaseTags.
Definition at line 230 of file fa_lru.cc.
References blkAlign(), curTick(), FALRUBlk::inCache, FALRUBlk::isTouched, CacheBlk::isValid(), moveToHead(), BaseTags::replacements, CacheBlk::tag, tagHash, BaseTags::tagsInUse, tail, Stats::ScalarBase< Derived, Stor >::value(), BaseTags::warmedUp, BaseTags::warmupBound, and BaseTags::warmupCycle.
void FALRU::forEachBlk (CacheBlkVisitor & visitor) [inline, virtual]
Visit each block in the tag store and apply a visitor to the block.
The visitor should be a function (or object that behaves like a function) that takes a cache block reference as its parameter and returns a bool. A visitor can request the traversal to be stopped by returning false, returning true causes it to be called for the next block in the tag store.
Parameters:
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 303 of file fa_lru.hh.
References blks, ArmISA::i, and BaseTags::numBlocks.
unsigned FALRU::getBlockSize () const [inline]
Return the block size of this cache.
Returns:
The block size.
Definition at line 223 of file fa_lru.hh.
References BaseTags::blkSize.
unsigned FALRU::getSubBlockSize () const [inline]
Return the subblock size of this cache, always the block size.
Returns:
The block size.
Definition at line 233 of file fa_lru.hh.
References BaseTags::blkSize.
FALRUBlk * FALRU::hashLookup (Addr addr) const [protected]
Find the cache block for the given address.
Parameters:
addr The address to find.
Returns:
The cache block of the address, if any.
Definition at line 154 of file fa_lru.cc.
References tagHash.
Referenced by accessBlock(), and findBlock().
void FALRU::insertBlock (PacketPtr pkt, CacheBlk * blk) [virtual]
Implements BaseTags.
Definition at line 252 of file fa_lru.cc.
void FALRU::invalidate (CacheBlk * blk) [virtual]
Invalidate a cache block.
Parameters:
blk The block to invalidate.
Implements BaseTags.
Definition at line 164 of file fa_lru.cc.
References BaseTags::tagsInUse.
void FALRU::moveToHead (FALRUBlk * blk) [protected]
Move a cache block to the MRU position.
Parameters:
blk The block to promote.
Definition at line 257 of file fa_lru.cc.
References cacheBoundaries, cacheMask, head, ArmISA::i, FALRUBlk::inCache, FALRUBlk::next, numCaches, FALRUBlk::prev, and tail.
Referenced by accessBlock(), and findVictim().
virtual std::string FALRU::print () const [inline, virtual]
Todo:
Implement as in lru. Currently not used
Implements BaseTags.
Definition at line 289 of file fa_lru.hh.
Addr FALRU::regenerateBlkAddr (Addr tag, unsigned set) const [inline, virtual]
Regenerate the block address from the tag and the set.
Parameters:
tag The tag of the block.
set The set the block belongs to.
Returns:
the block address.
Implements BaseTags.
Definition at line 275 of file fa_lru.hh.
void FALRU::regStats () [virtual]
Register the stats for this object.
Parameters:
name The name to prepend to the stats name.
Reimplemented from BaseTags.
Definition at line 119 of file fa_lru.cc.
References accesses, hits, ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), misses, Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), numCaches, Stats::DataWrapVec< Derived, InfoProxyType >::subdesc(), and Stats::DataWrapVec< Derived, InfoProxyType >::subname().
Member Data Documentation
FALRUBlk* FALRU::blks [protected]
The cache blocks.
Definition at line 104 of file fa_lru.hh.
Referenced by clearLocks(), FALRU(), forEachBlk(), and ~FALRU().
FALRUBlk** FALRU::cacheBoundaries [protected]
Array of pointers to blocks at the cache size boundaries.
Definition at line 97 of file fa_lru.hh.
Referenced by check(), FALRU(), moveToHead(), and ~FALRU().
int FALRU::cacheMask [protected]
A mask for the FALRUBlk::inCache bits.
Definition at line 99 of file fa_lru.hh.
Referenced by check(), FALRU(), and moveToHead().
FALRUBlk* FALRU::head [protected]
The MRU block.
Definition at line 107 of file fa_lru.hh.
Referenced by accessBlock(), check(), FALRU(), and moveToHead().
unsigned FALRU::numCaches [protected]
The number of different size caches being tracked.
Definition at line 101 of file fa_lru.hh.
Referenced by accessBlock(), FALRU(), moveToHead(), regStats(), and ~FALRU().
hash_t FALRU::tagHash [protected]
The address hash table.
Definition at line 117 of file fa_lru.hh.
Referenced by findVictim(), and hashLookup().
FALRUBlk* FALRU::tail [protected]
The LRU block.
Definition at line 109 of file fa_lru.hh.
Referenced by check(), FALRU(), findVictim(), and moveToHead().
The documentation for this class was generated from the following files:
mem/cache/tags/fa_lru.hh
mem/cache/tags/fa_lru.cc