gem5: TimingSimpleCPU Class Reference
TimingSimpleCPU Class Reference
#include <timing.hh>
Classes
class DcachePort
class FetchTranslation
class IcachePort
struct IprEvent
class SplitFragmentSenderState
class SplitMainSenderState
class TimingCPUPort
A TimingCPUPort overrides the default behaviour of the recvTiming and recvRetry and implements events for the scheduling of handling of incoming packets in the following cycle.
Public Member Functions
TimingSimpleCPU (TimingSimpleCPUParams *params)
virtual ~TimingSimpleCPU ()
virtual void init ()
unsigned int drain (DrainManager *drain_manager)
void drainResume ()
void switchOut ()
void takeOverFrom (BaseCPU *oldCPU)
void verifyMemoryMode () const
virtual void activateContext (ThreadID thread_num)
virtual void suspendContext (ThreadID thread_num)
Fault readMem (Addr addr, uint8_t *data, unsigned size, unsigned flags)
Fault writeMem (uint8_t *data, unsigned size, Addr addr, unsigned flags, uint64_t *res)
void fetch ()
void sendFetch (const Fault &fault, RequestPtr req, ThreadContext *tc)
void completeIfetch (PacketPtr)
void completeDataAccess (PacketPtr pkt)
void advanceInst (const Fault &fault)
bool isSquashed () const
This function is used by the page table walker to determine if it could translate the a pending request or if the underlying request has been squashed.
void printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
void finishTranslation (WholeTranslationState *state)
Finish a DTB translation.
Protected Member Functions
virtual MasterPort & getDataPort ()
Return a reference to the data port.
virtual MasterPort & getInstPort ()
Return a reference to the instruction port.
Private Types
typedef EventWrapper
< TimingSimpleCPU,&TimingSimpleCPU::fetch > FetchEvent
Private Member Functions
void sendData (RequestPtr req, uint8_t *data, uint64_t *res, bool read)
void sendSplitData (RequestPtr req1, RequestPtr req2, RequestPtr req, uint8_t *data, bool read)
void translationFault (const Fault &fault)
PacketPtr buildPacket (RequestPtr req, bool read)
void buildSplitPacket (PacketPtr &pkt1, PacketPtr &pkt2, RequestPtr req1, RequestPtr req2, RequestPtr req, uint8_t *data, bool read)
bool handleReadPacket (PacketPtr pkt)
bool handleWritePacket ()
void updateCycleCounts ()
bool isDrained ()
Check if a system is in a drained state.
bool tryCompleteDrain ()
Try to complete a drain request.
Private Attributes
FetchTranslation fetchTranslation
IcachePort icachePort
DcachePort dcachePort
PacketPtr ifetch_pkt
PacketPtr dcache_pkt
Cycles previousCycle
FetchEvent fetchEvent
DrainManager * drainManager
Drain manager to use when signaling drain completion.
Detailed Description
Definition at line 50 of file timing.hh.
Member Typedef Documentation
typedef EventWrapper<TimingSimpleCPU, &TimingSimpleCPU::fetch> TimingSimpleCPU::FetchEvent [private]
Definition at line 317 of file timing.hh.
Constructor & Destructor Documentation
TimingSimpleCPU::TimingSimpleCPU (TimingSimpleCPUParams * params)
Definition at line 91 of file timing.cc.
References BaseSimpleCPU::_status, and BaseSimpleCPU::Idle.
TimingSimpleCPU::~TimingSimpleCPU () [virtual]
Definition at line 101 of file timing.cc.
Member Function Documentation
void TimingSimpleCPU::activateContext (ThreadID thread_num) [virtual]
Definition at line 204 of file timing.cc.
References BaseSimpleCPU::_status, DPRINTF, fetchEvent, BaseSimpleCPU::Idle, BaseSimpleCPU::notIdleFraction, BaseSimpleCPU::Running, and BaseSimpleCPU::thread.
void TimingSimpleCPU::advanceInst (const Fault & fault)
Definition at line 612 of file timing.cc.
References BaseSimpleCPU::_status, BaseSimpleCPU::advancePC(), DPRINTF, BaseSimpleCPU::Faulting, fetch(), fetchEvent, BaseSimpleCPU::Running, BaseSimpleCPU::stayAtPC, and tryCompleteDrain().
Referenced by completeDataAccess(), completeIfetch(), sendFetch(), and translationFault().
PacketPtr TimingSimpleCPU::buildPacket (RequestPtr req, bool read) [private]
Definition at line 355 of file timing.cc.
References Packet::createRead(), and Packet::createWrite().
Referenced by buildSplitPacket(), and sendData().
void TimingSimpleCPU::buildSplitPacket (PacketPtr & pkt1, PacketPtr & pkt2, RequestPtr req1, RequestPtr req2, RequestPtr req, uint8_t * data, bool read) [private]
Definition at line 361 of file timing.cc.
References buildPacket(), Packet::cmd, Packet::dataDynamic(), Packet::dataStatic(), Request::getFlags(), Request::getSize(), Request::isMmappedIpr(), Flags< T >::isSet(), Request::NO_ACCESS, MemCmd::responseCommand(), and Packet::senderState.
Referenced by sendSplitData().
void TimingSimpleCPU::completeDataAccess (PacketPtr pkt)
Definition at line 744 of file timing.cc.
References BaseSimpleCPU::_status, advanceInst(), TimingSimpleCPU::SplitFragmentSenderState::bigPkt, BaseSimpleCPU::countInst(), BaseSimpleCPU::curStaticInst, BaseSimpleCPU::DcacheWaitResponse, BaseSimpleCPU::DTBWaitResponse, Request::getFlags(), Packet::isError(), Flags< T >::isSet(), Request::NO_ACCESS, TimingSimpleCPU::SplitMainSenderState::outstanding, BaseSimpleCPU::postExecute(), Packet::req, BaseSimpleCPU::Running, Packet::senderState, Request::setAccessLatency(), BaseSimpleCPU::traceData, and updateCycleCounts().
Referenced by TimingSimpleCPU::IprEvent::process(), TimingSimpleCPU::DcachePort::DTickEvent::process(), sendData(), and sendSplitData().
void TimingSimpleCPU::completeIfetch (PacketPtr pkt)
Definition at line 642 of file timing.cc.
References BaseSimpleCPU::_status, advanceInst(), BaseSimpleCPU::countInst(), BaseSimpleCPU::curStaticInst, DPRINTF, DTRACE, Packet::getAddr(), BaseSimpleCPU::IcacheWaitResponse, Packet::isError(), BaseSimpleCPU::postExecute(), BaseSimpleCPU::preExecute(), Packet::req, BaseSimpleCPU::Running, Request::setAccessLatency(), BaseSimpleCPU::traceData, and updateCycleCounts().
Referenced by fetch(), and TimingSimpleCPU::IcachePort::ITickEvent::process().
unsigned int TimingSimpleCPU::drain (DrainManager * drain_manager)
Definition at line 106 of file timing.cc.
References BaseSimpleCPU::_status, DPRINTF, drainManager, fetchEvent, BaseSimpleCPU::Idle, isDrained(), BaseSimpleCPU::pcState(), BaseSimpleCPU::Running, and Event::scheduled().
void TimingSimpleCPU::drainResume ()
Definition at line 131 of file timing.cc.
References BaseSimpleCPU::_status, ThreadContext::Active, DPRINTF, drainManager, fatal, fetchEvent, BaseSimpleCPU::Idle, BaseSimpleCPU::notIdleFraction, BaseSimpleCPU::Running, Event::scheduled(), SimpleThread::status(), BaseSimpleCPU::thread, and verifyMemoryMode().
void TimingSimpleCPU::fetch ()
Definition at line 545 of file timing.cc.
References BaseSimpleCPU::_status, BaseSimpleCPU::checkForInterrupts(), BaseSimpleCPU::checkPcEventQueue(), completeIfetch(), BaseSimpleCPU::curMacroStaticInst, BaseSimpleCPU::curStaticInst, DPRINTF, BaseTLB::Execute, fetchTranslation, Request::getVaddr(), BaseSimpleCPU::IcacheWaitResponse, BaseSimpleCPU::Idle, isRomMicroPC(), SimpleThread::itb, SimpleThread::pcState(), BaseSimpleCPU::pcState(), BaseSimpleCPU::Running, Request::setThreadContext(), BaseSimpleCPU::setupFetchRequest(), Request::taskId(), BaseSimpleCPU::tc, BaseSimpleCPU::thread, and updateCycleCounts().
Referenced by advanceInst().
void TimingSimpleCPU::finishTranslation (WholeTranslationState * state)
Finish a DTB translation.
Parameters:
state The DTB translation state.
Definition at line 519 of file timing.cc.
References BaseSimpleCPU::_status, WholeTranslationState::data, WholeTranslationState::deleteReqs(), WholeTranslationState::getFault(), WholeTranslationState::isPrefetch(), WholeTranslationState::isSplit, WholeTranslationState::mainReq, WholeTranslationState::mode, BaseTLB::Read, WholeTranslationState::res, BaseSimpleCPU::Running, sendData(), sendSplitData(), WholeTranslationState::setNoFault(), WholeTranslationState::sreqHigh, WholeTranslationState::sreqLow, and translationFault().
virtual MasterPort& TimingSimpleCPU::getDataPort () [inline, protected, virtual]
Return a reference to the data port.
Definition at line 266 of file timing.hh.
References dcachePort.
virtual MasterPort& TimingSimpleCPU::getInstPort () [inline, protected, virtual]
Return a reference to the instruction port.
Definition at line 269 of file timing.hh.
References icachePort.
bool TimingSimpleCPU::handleReadPacket (PacketPtr pkt) [private]
Definition at line 242 of file timing.cc.
References BaseSimpleCPU::_status, dcache_pkt, dcachePort, BaseSimpleCPU::DcacheRetry, BaseSimpleCPU::DcacheWaitResponse, SimpleThread::getTC(), GenericISA::handleIprRead(), AlphaISA::handleLockedRead(), Request::isLLSC(), Request::isMmappedIpr(), Packet::isRead(), Packet::req, MasterPort::sendTimingReq(), and BaseSimpleCPU::thread.
Referenced by TimingSimpleCPU::DcachePort::recvReqRetry(), sendData(), and sendSplitData().
bool TimingSimpleCPU::handleWritePacket () [private]
Definition at line 442 of file timing.cc.
References BaseSimpleCPU::_status, dcache_pkt, dcachePort, BaseSimpleCPU::DcacheRetry, BaseSimpleCPU::DcacheWaitResponse, SimpleThread::getTC(), GenericISA::handleIprWrite(), Request::isMmappedIpr(), Packet::req, MasterPort::sendTimingReq(), and BaseSimpleCPU::thread.
Referenced by TimingSimpleCPU::DcachePort::recvReqRetry(), sendData(), and sendSplitData().
void TimingSimpleCPU::init () [virtual]
Definition at line 68 of file timing.cc.
References FullSystem, ArmISA::i, AlphaISA::initCPU(), ThreadContext::initMemProxies(), BaseSimpleCPU::tc, and BaseSimpleCPU::tcBase().
bool TimingSimpleCPU::isDrained () [inline, private]
Check if a system is in a drained state.
We need to drain if:
We are in the middle of a microcode sequence as some CPUs (e.g., HW accelerated CPUs) can't be started in the middle of a gem5 microcode sequence.
Stay at PC is true.
A fetch event is scheduled. Normally this would never be the case with microPC() == 0, but right after a context is activated it can happen.
Definition at line 344 of file timing.hh.
References fetchEvent, BaseSimpleCPU::microPC(), Event::scheduled(), and BaseSimpleCPU::stayAtPC.
Referenced by drain(), and tryCompleteDrain().
bool TimingSimpleCPU::isSquashed () const [inline]
This function is used by the page table walker to determine if it could translate the a pending request or if the underlying request has been squashed.
This always returns false for the simple timing CPU as it never executes any instructions speculatively. @ return Is the current instruction squashed?
Definition at line 301 of file timing.hh.
void TimingSimpleCPU::printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
Definition at line 924 of file timing.cc.
References dcachePort, and MasterPort::printAddr().
Fault TimingSimpleCPU::readMem (Addr addr, uint8_t * data, unsigned size, unsigned flags)
Definition at line 393 of file timing.cc.
References BaseSimpleCPU::_status, ArmISA::asid, SimpleThread::dtb, BaseSimpleCPU::DTBWaitResponse, SimpleThread::instAddr(), Request::isLLSC(), Request::isSwap(), ArmISA::mode, MipsISA::pc, BaseTLB::Read, roundDown(), Trace::InstRecord::setMem(), Request::splitOnVaddr(), Request::taskId(), BaseSimpleCPU::tc, BaseSimpleCPU::thread, and BaseSimpleCPU::traceData.
void TimingSimpleCPU::sendData (RequestPtr req, uint8_t * data, uint64_t * res, bool read) [private]
Definition at line 268 of file timing.cc.
References BaseSimpleCPU::_status, buildPacket(), TimingSimpleCPU::DcachePort::cacheBlockMask, completeDataAccess(), Packet::dataDynamic(), dcache_pkt, dcachePort, BaseSimpleCPU::DcacheWaitResponse, Request::getFlags(), AlphaISA::handleLockedWrite(), handleReadPacket(), handleWritePacket(), Request::isCondSwap(), Request::isLLSC(), Flags< T >::isSet(), Packet::makeResponse(), Request::NO_ACCESS, Request::setExtraData(), and BaseSimpleCPU::thread.
Referenced by finishTranslation().
void TimingSimpleCPU::sendFetch (const Fault & fault, RequestPtr req, ThreadContext * tc)
Definition at line 580 of file timing.cc.
References BaseSimpleCPU::_status, advanceInst(), DPRINTF, Request::getPaddr(), Request::getVaddr(), icachePort, BaseSimpleCPU::IcacheRetry, BaseSimpleCPU::IcacheWaitResponse, ifetch_pkt, BaseSimpleCPU::inst, MemCmd::ReadReq, BaseSimpleCPU::Running, MasterPort::sendTimingReq(), and updateCycleCounts().
Referenced by TimingSimpleCPU::FetchTranslation::finish().
void TimingSimpleCPU::sendSplitData (RequestPtr req1, RequestPtr req2, RequestPtr req, uint8_t * data, bool read) [private]
Definition at line 300 of file timing.cc.
References buildSplitPacket(), TimingSimpleCPU::SplitFragmentSenderState::clearFromParent(), completeDataAccess(), dcache_pkt, Request::getFlags(), handleReadPacket(), handleWritePacket(), Flags< T >::isSet(), Packet::makeResponse(), Request::NO_ACCESS, and Packet::senderState.
Referenced by finishTranslation().
void TimingSimpleCPU::suspendContext (ThreadID thread_num) [virtual]
Definition at line 222 of file timing.cc.
References BaseSimpleCPU::_status, DPRINTF, BaseSimpleCPU::Idle, BaseSimpleCPU::notIdleFraction, BaseSimpleCPU::Running, and BaseSimpleCPU::thread.
void TimingSimpleCPU::switchOut ()
Definition at line 173 of file timing.cc.
References BaseSimpleCPU::_status, fetchEvent, BaseSimpleCPU::Idle, BaseSimpleCPU::microPC(), BaseSimpleCPU::Running, Event::scheduled(), BaseSimpleCPU::stayAtPC, and updateCycleCounts().
void TimingSimpleCPU::takeOverFrom (BaseCPU * oldCPU)
Definition at line 187 of file timing.cc.
References previousCycle.
void TimingSimpleCPU::translationFault (const Fault & fault) [private]
Definition at line 337 of file timing.cc.
References advanceInst(), BaseSimpleCPU::postExecute(), BaseSimpleCPU::traceData, and updateCycleCounts().
Referenced by finishTranslation().
bool TimingSimpleCPU::tryCompleteDrain () [private]
Try to complete a drain request.
Returns:
true if the CPU is drained, false otherwise.
Definition at line 156 of file timing.cc.
References DPRINTF, drainManager, isDrained(), BaseSimpleCPU::pcState(), and DrainManager::signalDrainDone().
Referenced by advanceInst().
void TimingSimpleCPU::updateCycleCounts () [private]
Definition at line 803 of file timing.cc.
References previousCycle.
Referenced by completeDataAccess(), completeIfetch(), fetch(), sendFetch(), switchOut(), and translationFault().
void TimingSimpleCPU::verifyMemoryMode () const
Definition at line 195 of file timing.cc.
References fatal, and X86ISA::system.
Referenced by drainResume().
Fault TimingSimpleCPU::writeMem (uint8_t * data, unsigned size, Addr addr, unsigned flags, uint64_t * res)
Definition at line 461 of file timing.cc.
References BaseSimpleCPU::_status, ArmISA::asid, Request::CACHE_BLOCK_ZERO, SimpleThread::dtb, BaseSimpleCPU::DTBWaitResponse, SimpleThread::instAddr(), Request::isLLSC(), Request::isSwap(), ArmISA::mode, MipsISA::pc, roundDown(), Trace::InstRecord::setMem(), Request::splitOnVaddr(), Request::taskId(), BaseSimpleCPU::tc, BaseSimpleCPU::thread, BaseSimpleCPU::traceData, and BaseTLB::Write.
Member Data Documentation
PacketPtr TimingSimpleCPU::dcache_pkt [private]
Definition at line 259 of file timing.hh.
Referenced by handleReadPacket(), handleWritePacket(), TimingSimpleCPU::DcachePort::recvReqRetry(), sendData(), and sendSplitData().
DcachePort TimingSimpleCPU::dcachePort [private]
Definition at line 256 of file timing.hh.
Referenced by getDataPort(), handleReadPacket(), handleWritePacket(), printAddr(), and sendData().
DrainManager* TimingSimpleCPU::drainManager [private]
Drain manager to use when signaling drain completion.
This pointer is non-NULL when draining and NULL otherwise.
Definition at line 360 of file timing.hh.
Referenced by drain(), drainResume(), and tryCompleteDrain().
FetchEvent TimingSimpleCPU::fetchEvent [private]
Definition at line 318 of file timing.hh.
Referenced by activateContext(), advanceInst(), drain(), drainResume(), isDrained(), and switchOut().
FetchTranslation TimingSimpleCPU::fetchTranslation [private]
Definition at line 132 of file timing.hh.
Referenced by fetch().
IcachePort TimingSimpleCPU::icachePort [private]
Definition at line 255 of file timing.hh.
Referenced by getInstPort(), and sendFetch().
PacketPtr TimingSimpleCPU::ifetch_pkt [private]
Definition at line 258 of file timing.hh.
Referenced by TimingSimpleCPU::IcachePort::recvReqRetry(), and sendFetch().
Cycles TimingSimpleCPU::previousCycle [private]
Definition at line 261 of file timing.hh.
Referenced by takeOverFrom(), and updateCycleCounts().
The documentation for this class was generated from the following files:
cpu/simple/timing.hh
cpu/simple/timing.cc