gem5: Minor::Latch< Data > Class Template Reference
Minor::Latch< Data > Class Template Reference
Wraps a MinorBuffer with Input/Output interfaces to ensure that units within the model can only see the right end of buffers between them.
#include <buffers.hh>
Classes
class Input
Encapsulate wires on either input or output of the latch.
class Output
Public Types
typedef MinorBuffer< Data > Buffer
Public Member Functions
Latch (const std::string &name, const std::string &data_name, Cycles delay_=Cycles(1), bool report_backwards=false)
forward/backwardDelay specify the delay from input to output in each direction.
bool empty () const
Input input ()
An interface to just the input of the buffer.
Output output ()
An interface to just the output of the buffer.
void minorTrace () const
void evaluate ()
Protected Attributes
Cycles delay
Delays, in cycles, writing data into the latch and seeing it on the latched wires.
Buffer buffer
Detailed Description
template<typename Data>
class Minor::Latch< Data >
Wraps a MinorBuffer with Input/Output interfaces to ensure that units within the model can only see the right end of buffers between them.
Definition at line 212 of file buffers.hh.
Member Typedef Documentation
template<typename Data> typedef MinorBuffer<Data> Minor::Latch< Data >::Buffer
Definition at line 215 of file buffers.hh.
Constructor & Destructor Documentation
template<typename Data> Minor::Latch< Data >::Latch (const std::string & name, const std::string & data_name, Cycles delay_ = Cycles(1), bool report_backwards = false) [inline]
forward/backwardDelay specify the delay from input to output in each direction.
These arguments *must* be >= 1
Definition at line 227 of file buffers.hh.
Member Function Documentation
template<typename Data> bool Minor::Latch< Data >::empty () const [inline]
Definition at line 264 of file buffers.hh.
Referenced by Minor::Pipeline::isDrained().
template<typename Data> void Minor::Latch< Data >::evaluate () [inline]
Definition at line 274 of file buffers.hh.
Referenced by Minor::Pipeline::evaluate().
template<typename Data> Input Minor::Latch< Data >::input () [inline]
An interface to just the input of the buffer.
Definition at line 267 of file buffers.hh.
template<typename Data> void Minor::Latch< Data >::minorTrace () const [inline]
Definition at line 272 of file buffers.hh.
Referenced by Minor::Pipeline::minorTrace().
template<typename Data> Output Minor::Latch< Data >::output () [inline]
An interface to just the output of the buffer.
Definition at line 270 of file buffers.hh.
Member Data Documentation
template<typename Data> Buffer Minor::Latch< Data >::buffer [protected]
Definition at line 222 of file buffers.hh.
Referenced by Minor::Latch< ForwardInstData >::empty(), Minor::Latch< ForwardInstData >::evaluate(), Minor::Latch< ForwardInstData >::input(), Minor::Latch< ForwardInstData >::minorTrace(), and Minor::Latch< ForwardInstData >::output().
template<typename Data> Cycles Minor::Latch< Data >::delay [protected]
Delays, in cycles, writing data into the latch and seeing it on the latched wires.
Definition at line 220 of file buffers.hh.
Referenced by Minor::Latch< ForwardInstData >::output().
The documentation for this class was generated from the following file:
cpu/minor/buffers.hh