gem5: CoherentXBar::CoherentXBarMasterPort Class Reference
CoherentXBar::CoherentXBarMasterPort Class Reference
Declaration of the coherent crossbar master port type, one will be instantiated for each of the slave interfaces connecting to the crossbar.
#include <coherent_xbar.hh>
Public Member Functions
CoherentXBarMasterPort (const std::string &_name, CoherentXBar &_xbar, PortID _id)
Protected Member Functions
virtual bool isSnooping () const
Determine if this port should be considered a snooper.
virtual bool recvTimingResp (PacketPtr pkt)
When receiving a timing response, pass it to the crossbar.
virtual void recvTimingSnoopReq (PacketPtr pkt)
When receiving a timing snoop request, pass it to the crossbar.
virtual Tick recvAtomicSnoop (PacketPtr pkt)
When receiving an atomic snoop request, pass it to the crossbar.
virtual void recvFunctionalSnoop (PacketPtr pkt)
When receiving a functional snoop request, pass it to the crossbar.
virtual void recvRangeChange ()
When reciving a range change from the peer port (at id), pass it to the crossbar.
virtual void recvReqRetry ()
When reciving a retry from the peer port (at id), pass it to the crossbar.
Private Attributes
CoherentXBar & xbar
A reference to the crossbar to which this port belongs.
Detailed Description
Declaration of the coherent crossbar master port type, one will be instantiated for each of the slave interfaces connecting to the crossbar.
Definition at line 147 of file coherent_xbar.hh.
Constructor & Destructor Documentation
CoherentXBar::CoherentXBarMasterPort::CoherentXBarMasterPort (const std::string & _name, CoherentXBar & _xbar, PortID _id) [inline]
Definition at line 155 of file coherent_xbar.hh.
Member Function Documentation
virtual bool CoherentXBar::CoherentXBarMasterPort::isSnooping () const [inline, protected, virtual]
Determine if this port should be considered a snooper.
For a coherent crossbar master port this is always true.
Returns:
a boolean that is true if this port is snooping
Reimplemented from MasterPort.
Definition at line 168 of file coherent_xbar.hh.
virtual Tick CoherentXBar::CoherentXBarMasterPort::recvAtomicSnoop (PacketPtr pkt) [inline, protected, virtual]
When receiving an atomic snoop request, pass it to the crossbar.
Reimplemented from MasterPort.
Definition at line 186 of file coherent_xbar.hh.
References CoherentXBar::recvAtomicSnoop(), and xbar.
virtual void CoherentXBar::CoherentXBarMasterPort::recvFunctionalSnoop (PacketPtr pkt) [inline, protected, virtual]
When receiving a functional snoop request, pass it to the crossbar.
Reimplemented from MasterPort.
Definition at line 192 of file coherent_xbar.hh.
References CoherentXBar::recvFunctionalSnoop(), and xbar.
virtual void CoherentXBar::CoherentXBarMasterPort::recvRangeChange () [inline, protected, virtual]
When reciving a range change from the peer port (at id), pass it to the crossbar.
Reimplemented from MasterPort.
Definition at line 197 of file coherent_xbar.hh.
References BaseXBar::recvRangeChange(), and xbar.
virtual void CoherentXBar::CoherentXBarMasterPort::recvReqRetry () [inline, protected, virtual]
When reciving a retry from the peer port (at id), pass it to the crossbar.
Implements MasterPort.
Definition at line 202 of file coherent_xbar.hh.
References CoherentXBar::recvReqRetry(), and xbar.
virtual bool CoherentXBar::CoherentXBarMasterPort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
When receiving a timing response, pass it to the crossbar.
Implements MasterPort.
Definition at line 174 of file coherent_xbar.hh.
References CoherentXBar::recvTimingResp(), and xbar.
virtual void CoherentXBar::CoherentXBarMasterPort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
When receiving a timing snoop request, pass it to the crossbar.
Reimplemented from MasterPort.
Definition at line 180 of file coherent_xbar.hh.
References CoherentXBar::recvTimingSnoopReq(), and xbar.
Member Data Documentation
CoherentXBar& CoherentXBar::CoherentXBarMasterPort::xbar [private]
A reference to the crossbar to which this port belongs.
Definition at line 151 of file coherent_xbar.hh.
Referenced by recvAtomicSnoop(), recvFunctionalSnoop(), recvRangeChange(), recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
The documentation for this class was generated from the following file:
mem/coherent_xbar.hh