gem5: PowerISA::FloatOp Class Reference
PowerISA::FloatOp Class Reference
Base class for floating point operations.
#include <floating.hh>
Protected Member Functions
FloatOp (const char *mnem, MachInst _machInst, OpClass __opClass)
Constructor.
bool isNan (uint32_t val_bits) const
bool isNan (uint64_t val_bits) const
bool isNan (float val) const
bool isNan (double val) const
bool isSnan (uint32_t val_bits) const
bool isQnan (uint32_t val_bits) const
bool isInfinity (uint32_t val_bits) const
bool isNormalized (uint32_t val_bits) const
bool isDenormalized (uint32_t val_bits) const
bool isZero (uint32_t val_bits) const
bool isNegative (uint32_t val_bits) const
uint32_t makeCRField (double a, double b) const
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
bool rcSet
Detailed Description
Base class for floating point operations.
Definition at line 45 of file floating.hh.
Constructor & Destructor Documentation
PowerISA::FloatOp::FloatOp (const char * mnem, MachInst _machInst, OpClass __opClass) [inline, protected]
Constructor.
Definition at line 52 of file floating.hh.
Member Function Documentation
std::string FloatOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from PowerISA::PowerStaticInst.
Definition at line 36 of file floating.cc.
References StaticInst::_destRegIdx, StaticInst::_numDestRegs, StaticInst::_numSrcRegs, StaticInst::_srcRegIdx, ccprintf(), StaticInst::mnemonic, PowerISA::PowerStaticInst::printReg(), and ArmISA::ss.
bool PowerISA::FloatOp::isDenormalized (uint32_t val_bits) const [inline, protected]
Definition at line 117 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isInfinity (uint32_t val_bits) const [inline, protected]
Definition at line 102 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isNan (double val) const [inline, protected]
Definition at line 79 of file floating.hh.
References isNan().
bool PowerISA::FloatOp::isNan (float val) const [inline, protected]
Definition at line 71 of file floating.hh.
References isNan().
bool PowerISA::FloatOp::isNan (uint64_t val_bits) const [inline, protected]
Definition at line 65 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isNan (uint32_t val_bits) const [inline, protected]
Definition at line 59 of file floating.hh.
References bits().
Referenced by isNan(), and makeCRField().
bool PowerISA::FloatOp::isNegative (uint32_t val_bits) const [inline, protected]
Definition at line 131 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isNormalized (uint32_t val_bits) const [inline, protected]
Definition at line 109 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isQnan (uint32_t val_bits) const [inline, protected]
Definition at line 95 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isSnan (uint32_t val_bits) const [inline, protected]
Definition at line 88 of file floating.hh.
References bits().
bool PowerISA::FloatOp::isZero (uint32_t val_bits) const [inline, protected]
Definition at line 124 of file floating.hh.
References bits().
uint32_t PowerISA::FloatOp::makeCRField (double a, double b) const [inline, protected]
Definition at line 138 of file floating.hh.
References ArmISA::c, and isNan().
Member Data Documentation
bool PowerISA::FloatOp::rcSet [protected]
Definition at line 49 of file floating.hh.
The documentation for this class was generated from the following files:
arch/power/insts/floating.hh
arch/power/insts/floating.cc