gem5: SnapMemCtrl::SnapMemCtrlSlavePort Class Reference
SnapMemCtrl::SnapMemCtrlSlavePort Class Reference
#include <snap_mem_ctrl.hh>
Public Member Functions
SnapMemCtrlSlavePort (const std::string &_name, SnapMemCtrl *ctrl)
virtual bool isSnooping () const
Find out if the peer master port is snooping or not.
Protected Member Functions
virtual AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
virtual bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
virtual Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
virtual void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
Private Attributes
SlavePacketQueue queue
SnapMemCtrl * ctrl
Detailed Description
Definition at line 62 of file snap_mem_ctrl.hh.
Constructor & Destructor Documentation
SnapMemCtrl::SnapMemCtrlSlavePort::SnapMemCtrlSlavePort (const std::string & _name, SnapMemCtrl * ctrl)
Definition at line 45 of file snap_mem_ctrl.cc.
Member Function Documentation
AddrRangeList SnapMemCtrl::SnapMemCtrlSlavePort::getAddrRanges () const [protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 51 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::getAddrRanges().
virtual bool SnapMemCtrl::SnapMemCtrlSlavePort::isSnooping () const [inline, virtual]
Find out if the peer master port is snooping or not.
Returns:
true if the peer master port is snooping
Reimplemented from SlavePort.
Definition at line 72 of file snap_mem_ctrl.hh.
Tick SnapMemCtrl::SnapMemCtrlSlavePort::recvAtomic (PacketPtr pkt) [protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 61 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvAtomic().
void SnapMemCtrl::SnapMemCtrlSlavePort::recvFunctional (PacketPtr pkt) [protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 66 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvFunctional().
bool SnapMemCtrl::SnapMemCtrlSlavePort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 56 of file snap_mem_ctrl.cc.
References ctrl, and SnapMemCtrl::recvTimingReq().
Member Data Documentation
SnapMemCtrl* SnapMemCtrl::SnapMemCtrlSlavePort::ctrl [private]
Definition at line 64 of file snap_mem_ctrl.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), and recvTimingReq().
SlavePacketQueue SnapMemCtrl::SnapMemCtrlSlavePort::queue [private]
Definition at line 63 of file snap_mem_ctrl.hh.
The documentation for this class was generated from the following files:
mem/snapmem/snap_mem_ctrl.hh
mem/snapmem/snap_mem_ctrl.cc