gem5: SparcISA::FastDataAccessMMUMiss Class Reference
SparcISA::FastDataAccessMMUMiss Class Reference
#include <faults.hh>
Public Member Functions
FastDataAccessMMUMiss (Addr addr)
FastDataAccessMMUMiss ()
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Protected Attributes
Addr vaddr
Detailed Description
Definition at line 213 of file faults.hh.
Constructor & Destructor Documentation
SparcISA::FastDataAccessMMUMiss::FastDataAccessMMUMiss (Addr addr) [inline]
Definition at line 218 of file faults.hh.
SparcISA::FastDataAccessMMUMiss::FastDataAccessMMUMiss () [inline]
Definition at line 220 of file faults.hh.
Member Function Documentation
void SparcISA::FastDataAccessMMUMiss::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from SparcISA::SparcFaultBase.
Definition at line 638 of file faults.cc.
References Process::fixupStackFault(), FullSystem, ThreadContext::getDTBPtr(), ThreadContext::getProcessPtr(), PageTableBase::lookup(), Process::M5_pid, MipsISA::p, PageTableBase::pageAlign(), panic, Process::pTable, SparcISA::TlbEntry::pte, and vaddr.
Member Data Documentation
Addr SparcISA::FastDataAccessMMUMiss::vaddr [protected]
Definition at line 216 of file faults.hh.
Referenced by invoke().
The documentation for this class was generated from the following files:
arch/sparc/faults.hh
arch/sparc/faults.cc