gem5: HexFile Class Reference
HexFile Class Reference
#include <hex_file.hh>
Public Member Functions
HexFile (const std::string _filename)
virtual ~HexFile ()
void close ()
bool loadSections (PortProxy &memProxy)
Protected Member Functions
void parseLine (char *, Addr *, uint32_t *)
Protected Attributes
const std::string filename
FILE * fp
Detailed Description
Definition at line 42 of file hex_file.hh.
Constructor & Destructor Documentation
HexFile::HexFile (const std::string _filename)
HexFile::~HexFile () [virtual]
Definition at line 57 of file hex_file.cc.
References fp.
Member Function Documentation
void HexFile::close ()
Definition at line 137 of file hex_file.cc.
References fp.
bool HexFile::loadSections (PortProxy & memProxy)
Definition at line 64 of file hex_file.cc.
References fp, panic, parseLine(), and PortProxy::writeBlob().
void HexFile::parseLine (char * Str, Addr * A, uint32_t * D) [protected]
Definition at line 83 of file hex_file.cc.
References ArmISA::i.
Referenced by loadSections().
Member Data Documentation
const std::string HexFile::filename [protected]
Definition at line 45 of file hex_file.hh.
FILE* HexFile::fp [protected]
Definition at line 46 of file hex_file.hh.
Referenced by close(), loadSections(), and ~HexFile().
The documentation for this class was generated from the following files:
base/loader/hex_file.hh
base/loader/hex_file.cc