gem5: Trace::SparcNativeTrace Class Reference
Trace::SparcNativeTrace Class Reference
#include <nativetrace.hh>
Public Member Functions
SparcNativeTrace (const Params *p)
void check (NativeTraceRecord *record)
Detailed Description
Definition at line 41 of file nativetrace.hh.
Constructor & Destructor Documentation
Trace::SparcNativeTrace::SparcNativeTrace (const Params * p) [inline]
Definition at line 44 of file nativetrace.hh.
Member Function Documentation
void Trace::SparcNativeTrace::check (NativeTraceRecord * record) [virtual]
Implements Trace::NativeTrace.
Definition at line 52 of file nativetrace.cc.
References Trace::NativeTrace::checkReg(), Trace::InstRecord::getThread(), BigEndianGuest::gtoh(), ArmISA::i, Trace::intRegNames, GenericISA::DelaySlotPCState< MachInst >::nnpc(), GenericISA::SimplePCState< MachInst >::npc(), SparcISA::NumIntArchRegs, MipsISA::pc, ThreadContext::pcState(), Trace::NativeTrace::read(), ThreadContext::readIntReg(), and ArmISA::tc.
The documentation for this class was generated from the following files:
arch/sparc/nativetrace.hh
arch/sparc/nativetrace.cc