gem5: AddrMapper::MapperMasterPort Class Reference
AddrMapper::MapperMasterPort Class Reference
#include <addr_mapper.hh>
Public Member Functions
MapperMasterPort (const std::string &_name, AddrMapper &_mapper)
Protected Member Functions
void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from the slave port.
bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the slave port.
void recvRangeChange ()
Called to receive an address range change from the peer slave port.
bool isSnooping () const
Determine if this master port is snooping or not.
void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Private Attributes
AddrMapper & mapper
Detailed Description
Definition at line 105 of file addr_mapper.hh.
Constructor & Destructor Documentation
AddrMapper::MapperMasterPort::MapperMasterPort (const std::string & _name, AddrMapper & _mapper) [inline]
Definition at line 110 of file addr_mapper.hh.
Member Function Documentation
bool AddrMapper::MapperMasterPort::isSnooping () const [inline, protected, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented from MasterPort.
Definition at line 141 of file addr_mapper.hh.
References AddrMapper::isSnooping(), and mapper.
Tick AddrMapper::MapperMasterPort::recvAtomicSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 121 of file addr_mapper.hh.
References mapper, and AddrMapper::recvAtomicSnoop().
void AddrMapper::MapperMasterPort::recvFunctionalSnoop (PacketPtr pkt) [inline, protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 116 of file addr_mapper.hh.
References mapper, and AddrMapper::recvFunctionalSnoop().
void AddrMapper::MapperMasterPort::recvRangeChange () [inline, protected, virtual]
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 136 of file addr_mapper.hh.
References mapper, and AddrMapper::recvRangeChange().
void AddrMapper::MapperMasterPort::recvReqRetry () [inline, protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 146 of file addr_mapper.hh.
References mapper, and AddrMapper::recvReqRetry().
bool AddrMapper::MapperMasterPort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 126 of file addr_mapper.hh.
References mapper, and AddrMapper::recvTimingResp().
void AddrMapper::MapperMasterPort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop request from the slave port.
Reimplemented from MasterPort.
Definition at line 131 of file addr_mapper.hh.
References mapper, and AddrMapper::recvTimingSnoopReq().
Member Data Documentation
AddrMapper& AddrMapper::MapperMasterPort::mapper [private]
Definition at line 153 of file addr_mapper.hh.
Referenced by isSnooping(), recvAtomicSnoop(), recvFunctionalSnoop(), recvRangeChange(), recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
The documentation for this class was generated from the following file:
mem/addr_mapper.hh