gem5: BaseSimpleCPU Class Reference
BaseSimpleCPU Class Reference
#include <base.hh>
Public Member Functions
void wakeup ()
void zero_fill_64 (Addr addr)
BaseSimpleCPU (BaseSimpleCPUParams *params)
virtual ~BaseSimpleCPU ()
Addr dbg_vtophys (Addr addr)
void checkForInterrupts ()
void setupFetchRequest (Request *req)
void preExecute ()
void postExecute ()
void advancePC (const Fault &fault)
virtual void haltContext (ThreadID thread_num)
virtual void regStats ()
virtual void resetStats ()
virtual void startup ()
void countInst ()
virtual Counter totalInsts () const
virtual Counter totalOps () const
void serializeThread (std::ostream &os, ThreadID tid)
void unserializeThread (Checkpoint *cp, const std::string &section, ThreadID tid)
void setEA (Addr EA)
Record the effective address of the instruction.
Addr getEA () const
Get the effective address of the instruction.
IntReg readIntRegOperand (const StaticInst *si, int idx)
Reads an integer register.
FloatReg readFloatRegOperand (const StaticInst *si, int idx)
Reads a floating point register of single register width.
FloatRegBits readFloatRegOperandBits (const StaticInst *si, int idx)
Reads a floating point register in its binary format, instead of by value.
CCReg readCCRegOperand (const StaticInst *si, int idx)
void setIntRegOperand (const StaticInst *si, int idx, IntReg val)
Sets an integer register to a value.
void setFloatRegOperand (const StaticInst *si, int idx, FloatReg val)
Sets a floating point register of single width to a value.
void setFloatRegOperandBits (const StaticInst *si, int idx, FloatRegBits val)
Sets the bits of a floating point register of single width to a binary value.
void setCCRegOperand (const StaticInst *si, int idx, CCReg val)
bool readPredicate ()
void setPredicate (bool val)
TheISA::PCState pcState () const
void pcState (const TheISA::PCState &val)
Addr instAddr ()
Addr nextInstAddr ()
MicroPC microPC ()
MiscReg readMiscRegNoEffect (int misc_reg) const
MiscReg readMiscReg (int misc_reg)
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
void setMiscReg (int misc_reg, const MiscReg &val)
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
MiscReg readMiscRegOperand (const StaticInst *si, int idx)
void setMiscRegOperand (const StaticInst *si, int idx, const MiscReg &val)
void demapPage (Addr vaddr, uint64_t asn)
Invalidate a page in the DTLB and ITLB.
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
unsigned int readStCondFailures () const
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned int sc_failures)
Sets the number of consecutive store conditional failures.
MiscReg readRegOtherThread (int regIdx, ThreadID tid=InvalidThreadID)
void setRegOtherThread (int regIdx, MiscReg val, ThreadID tid=InvalidThreadID)
Fault hwrei ()
Somewhat Alpha-specific function that handles returning from an error or interrupt.
bool simPalCheck (int palFunc)
Check for special simulator handling of specific PAL calls.
void syscall (int64_t callnum)
Executes a syscall specified by the callnum.
ThreadContext * tcBase ()
Returns a pointer to the ThreadContext.
void armMonitor (Addr address)
bool mwait (PacketPtr pkt)
void mwaitAtomic (ThreadContext *tc)
AddressMonitor * getAddrMonitor ()
Public Attributes
SimpleThread * thread
SimpleThread object, provides all the architectural state.
ThreadContext * tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
CheckerCPU * checker
bool interval_stats
TheISA::MachInst inst
StaticInstPtr curStaticInst
StaticInstPtr curMacroStaticInst
Addr fetchOffset
bool stayAtPC
Counter numInst
Counter startNumInst
Stats::Scalar numInsts
Counter numOp
Counter startNumOp
Stats::Scalar numOps
Stats::Scalar numIntAluAccesses
Stats::Scalar numFpAluAccesses
Stats::Scalar numCallsReturns
Stats::Scalar numCondCtrlInsts
Stats::Scalar numIntInsts
Stats::Scalar numFpInsts
Stats::Scalar numIntRegReads
Stats::Scalar numIntRegWrites
Stats::Scalar numFpRegReads
Stats::Scalar numFpRegWrites
Stats::Scalar numCCRegReads
Stats::Scalar numCCRegWrites
Stats::Scalar numMemRefs
Stats::Scalar numLoadInsts
Stats::Scalar numStoreInsts
Stats::Formula numIdleCycles
Stats::Formula numBusyCycles
Counter numLoad
Counter startNumLoad
Stats::Average notIdleFraction
Stats::Formula idleFraction
Stats::Scalar icacheStallCycles
Counter lastIcacheStall
Stats::Scalar dcacheStallCycles
Counter lastDcacheStall
Stats::Vector statExecutedInstType
Stats::Scalar numBranches
Stats::Scalar numPredictedBranches
Number of branches predicted as taken.
Stats::Scalar numBranchMispred
Number of misprediced branches.
Protected Types
enum Status {
Idle, Running, Faulting, ITBWaitResponse,
IcacheRetry, IcacheWaitResponse, IcacheWaitSwitch, DTBWaitResponse,
DcacheRetry, DcacheWaitResponse, DcacheWaitSwitch
}
typedef TheISA::MiscReg MiscReg
typedef TheISA::FloatReg FloatReg
typedef TheISA::FloatRegBits FloatRegBits
typedef TheISA::CCReg CCReg
Protected Member Functions
void checkPcEventQueue ()
Protected Attributes
BPredUnit * branchPred
Trace::InstRecord * traceData
Status _status
Private Attributes
TheISA::PCState pred_pc
Detailed Description
Definition at line 83 of file base.hh.
Member Typedef Documentation
typedef TheISA::CCReg BaseSimpleCPU::CCReg [protected]
Reimplemented from ExecContext.
Definition at line 89 of file base.hh.
typedef TheISA::FloatReg BaseSimpleCPU::FloatReg [protected]
Reimplemented from ExecContext.
Definition at line 87 of file base.hh.
typedef TheISA::FloatRegBits BaseSimpleCPU::FloatRegBits [protected]
Reimplemented from ExecContext.
Definition at line 88 of file base.hh.
typedef TheISA::MiscReg BaseSimpleCPU::MiscReg [protected]
Reimplemented from ExecContext.
Definition at line 86 of file base.hh.
Member Enumeration Documentation
enum BaseSimpleCPU::Status [protected]
Enumerator:
Idle
Running
Faulting
ITBWaitResponse
IcacheRetry
IcacheWaitResponse
IcacheWaitSwitch
DTBWaitResponse
DcacheRetry
DcacheWaitResponse
DcacheWaitSwitch
Definition at line 133 of file base.hh.
Constructor & Destructor Documentation
BaseSimpleCPU::BaseSimpleCPU (BaseSimpleCPUParams * params)
Definition at line 88 of file base.cc.
References checker, fetchOffset, FullSystem, SimpleThread::getTC(), ThreadContext::Halted, lastDcacheStall, lastIcacheStall, numInst, numLoad, numOp, SimpleThread::setStatus(), CheckerCPU::setSystem(), startNumInst, startNumLoad, startNumOp, stayAtPC, tc, and thread.
BaseSimpleCPU::~BaseSimpleCPU () [virtual]
Definition at line 132 of file base.cc.
Member Function Documentation
void BaseSimpleCPU::advancePC (const Fault & fault)
Definition at line 544 of file base.cc.
References branchPred, curMacroStaticInst, curStaticInst, SimpleThread::decoder, fetchOffset, StaticInst::nullStaticInstPtr, numBranchMispred, pcState(), SimpleThread::pcState(), pred_pc, BPredUnit::squash(), tc, thread, and BPredUnit::update().
Referenced by TimingSimpleCPU::advanceInst(), and AtomicSimpleCPU::tick().
void BaseSimpleCPU::armMonitor (Addr address) [inline, virtual]
Implements ExecContext.
Definition at line 459 of file base.hh.
void BaseSimpleCPU::checkForInterrupts ()
Definition at line 349 of file base.cc.
References SimpleThread::decoder, fetchOffset, tc, and thread.
Referenced by TimingSimpleCPU::fetch(), and AtomicSimpleCPU::tick().
void BaseSimpleCPU::checkPcEventQueue () [inline, protected]
Definition at line 96 of file base.hh.
References SimpleThread::instAddr(), MipsISA::pc, X86ISA::system, tc, and thread.
Referenced by TimingSimpleCPU::fetch(), and AtomicSimpleCPU::tick().
void BaseSimpleCPU::countInst () [inline]
Definition at line 189 of file base.hh.
References curStaticInst, ThreadState::funcExeInst, numInst, numInsts, numOp, numOps, X86ISA::system, and thread.
Referenced by TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), and AtomicSimpleCPU::tick().
Addr BaseSimpleCPU::dbg_vtophys (Addr addr)
Definition at line 331 of file base.cc.
References tc, and AlphaISA::vtophys().
void BaseSimpleCPU::demapDataPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 412 of file base.hh.
References SimpleThread::demapDataPage(), and thread.
void BaseSimpleCPU::demapInstPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 407 of file base.hh.
References SimpleThread::demapInstPage(), and thread.
void BaseSimpleCPU::demapPage (Addr vaddr, uint64_t asn) [inline, virtual]
Invalidate a page in the DTLB and ITLB.
Implements ExecContext.
Definition at line 402 of file base.hh.
References SimpleThread::demapPage(), and thread.
AddressMonitor* BaseSimpleCPU::getAddrMonitor () [inline, virtual]
Implements ExecContext.
Definition at line 463 of file base.hh.
Referenced by TimingSimpleCPU::DcachePort::recvFunctionalSnoop(), TimingSimpleCPU::DcachePort::recvTimingSnoopReq(), and wakeup().
Addr BaseSimpleCPU::getEA () const [inline, virtual]
Get the effective address of the instruction.
Note:
Only valid for memory ops.
Implements ExecContext.
Definition at line 288 of file base.hh.
References panic.
void BaseSimpleCPU::haltContext (ThreadID thread_num) [virtual]
Definition at line 137 of file base.cc.
Fault BaseSimpleCPU::hwrei () [inline, virtual]
Somewhat Alpha-specific function that handles returning from an error or interrupt.
Implements ExecContext.
Definition at line 440 of file base.hh.
References SimpleThread::hwrei(), and thread.
Addr BaseSimpleCPU::instAddr () [inline]
Definition at line 366 of file base.hh.
References SimpleThread::instAddr(), and thread.
Referenced by postExecute(), and setupFetchRequest().
MicroPC BaseSimpleCPU::microPC () [inline]
Definition at line 368 of file base.hh.
References SimpleThread::microPC(), and thread.
Referenced by TimingSimpleCPU::isDrained(), AtomicSimpleCPU::isDrained(), and TimingSimpleCPU::switchOut().
bool BaseSimpleCPU::mwait (PacketPtr pkt) [inline, virtual]
Implements ExecContext.
Definition at line 460 of file base.hh.
void BaseSimpleCPU::mwaitAtomic (ThreadContext * tc) [inline, virtual]
Implements ExecContext.
Definition at line 461 of file base.hh.
References SimpleThread::dtb, and thread.
Addr BaseSimpleCPU::nextInstAddr () [inline]
Definition at line 367 of file base.hh.
References SimpleThread::nextInstAddr(), and thread.
void BaseSimpleCPU::pcState (const TheISA::PCState & val) [inline, virtual]
Implements ExecContext.
Definition at line 365 of file base.hh.
References SimpleThread::pcState(), and thread.
TheISA::PCState BaseSimpleCPU::pcState () const [inline, virtual]
Implements ExecContext.
Definition at line 364 of file base.hh.
References SimpleThread::pcState(), and thread.
Referenced by advancePC(), TimingSimpleCPU::drain(), AtomicSimpleCPU::drain(), TimingSimpleCPU::fetch(), preExecute(), AtomicSimpleCPU::tick(), TimingSimpleCPU::tryCompleteDrain(), and AtomicSimpleCPU::tryCompleteDrain().
void BaseSimpleCPU::postExecute ()
Definition at line 464 of file base.cc.
References CPA::available(), FunctionProfile::consume(), CPA::cpa(), curStaticInst, Trace::InstRecord::dump(), FullSystem, instAddr(), AlphaISA::inUserMode(), ThreadContext::nextInstAddr(), numBranches, numCallsReturns, numCondCtrlInsts, numFpAluAccesses, numFpInsts, numIntAluAccesses, numIntInsts, numLoad, numLoadInsts, numMemRefs, numStoreInsts, MipsISA::pc, ThreadContext::pcState(), ThreadState::profile, ThreadState::profileNode, ThreadState::profilePC, statExecutedInstType, CPA::swAutoBegin(), tc, thread, and traceData.
Referenced by TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), AtomicSimpleCPU::tick(), and TimingSimpleCPU::translationFault().
void BaseSimpleCPU::preExecute ()
Definition at line 379 of file base.cc.
References branchPred, curMacroStaticInst, curStaticInst, curTick(), SimpleThread::decoder, DPRINTF, fetchOffset, BigEndianGuest::gtoh(), inst, isRomMicroPC(), numInst, numPredictedBranches, SimpleThread::pcState(), pcState(), pred_pc, BPredUnit::predict(), SimpleThread::setFloatReg(), SimpleThread::setIntReg(), stayAtPC, X86ISA::system, tc, thread, traceData, and AlphaISA::ZeroReg.
Referenced by TimingSimpleCPU::completeIfetch(), and AtomicSimpleCPU::tick().
CCReg BaseSimpleCPU::readCCRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 321 of file base.hh.
References AlphaISA::CC_Reg_Base, numCCRegReads, SimpleThread::readCCReg(), StaticInst::srcRegIdx(), and thread.
FloatReg BaseSimpleCPU::readFloatRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register of single register width.
Implements ExecContext.
Definition at line 307 of file base.hh.
References AlphaISA::FP_Reg_Base, numFpRegReads, SimpleThread::readFloatReg(), StaticInst::srcRegIdx(), and thread.
FloatRegBits BaseSimpleCPU::readFloatRegOperandBits (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 314 of file base.hh.
References AlphaISA::FP_Reg_Base, numFpRegReads, SimpleThread::readFloatRegBits(), StaticInst::srcRegIdx(), and thread.
IntReg BaseSimpleCPU::readIntRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads an integer register.
Implements ExecContext.
Definition at line 301 of file base.hh.
References numIntRegReads, SimpleThread::readIntReg(), StaticInst::srcRegIdx(), and thread.
MiscReg BaseSimpleCPU::readMiscReg (int misc_reg) [inline, virtual]
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
Implements ExecContext.
Definition at line 375 of file base.hh.
References numIntRegReads, SimpleThread::readMiscReg(), and thread.
MiscReg BaseSimpleCPU::readMiscRegNoEffect (int misc_reg) const [inline]
Definition at line 370 of file base.hh.
References SimpleThread::readMiscRegNoEffect(), and thread.
MiscReg BaseSimpleCPU::readMiscRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 387 of file base.hh.
References AlphaISA::Misc_Reg_Base, numIntRegReads, SimpleThread::readMiscReg(), StaticInst::srcRegIdx(), and thread.
bool BaseSimpleCPU::readPredicate () [inline, virtual]
Implements ExecContext.
Definition at line 356 of file base.hh.
References SimpleThread::readPredicate(), and thread.
MiscReg BaseSimpleCPU::readRegOtherThread (int regIdx, ThreadID tid = InvalidThreadID) [inline, virtual]
Implements ExecContext.
Definition at line 425 of file base.hh.
References panic.
unsigned int BaseSimpleCPU::readStCondFailures () const [inline, virtual]
Returns the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 417 of file base.hh.
References SimpleThread::readStCondFailures(), and thread.
void BaseSimpleCPU::regStats () [virtual]
Definition at line 145 of file base.cc.
References Stats::constant(), dcacheStallCycles, Stats::dist, ArmISA::i, icacheStallCycles, idleFraction, Stats::VectorBase< Derived, Stor >::init(), name(), Stats::DataWrap< Derived, InfoProxyType >::name(), notIdleFraction, Stats::nozero, Num_OpClasses, numBranches, numBranchMispred, numBusyCycles, numCallsReturns, numCCRegReads, numCCRegWrites, numCondCtrlInsts, numFpAluAccesses, numFpInsts, numFpRegReads, numFpRegWrites, numIdleCycles, numInsts, numIntAluAccesses, numIntInsts, numIntRegReads, numIntRegWrites, numLoadInsts, numMemRefs, numOps, numPredictedBranches, numStoreInsts, Stats::pdf, statExecutedInstType, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), and Stats::total.
void BaseSimpleCPU::resetStats () [virtual]
Definition at line 301 of file base.cc.
References _status, Idle, and notIdleFraction.
void BaseSimpleCPU::serializeThread (std::ostream & os, ThreadID tid)
void BaseSimpleCPU::setCCRegOperand (const StaticInst * si, int idx, CCReg val) [inline, virtual]
Implements ExecContext.
Definition at line 349 of file base.hh.
References AlphaISA::CC_Reg_Base, StaticInst::destRegIdx(), numCCRegWrites, SimpleThread::setCCReg(), and thread.
void BaseSimpleCPU::setEA (Addr EA) [inline, virtual]
Record the effective address of the instruction.
Note:
Only valid for memory ops.
Implements ExecContext.
Definition at line 287 of file base.hh.
References panic.
void BaseSimpleCPU::setFloatRegOperand (const StaticInst * si, int idx, FloatReg val) [inline, virtual]
Sets a floating point register of single width to a value.
Implements ExecContext.
Definition at line 334 of file base.hh.
References StaticInst::destRegIdx(), AlphaISA::FP_Reg_Base, numFpRegWrites, SimpleThread::setFloatReg(), and thread.
void BaseSimpleCPU::setFloatRegOperandBits (const StaticInst * si, int idx, FloatRegBits val) [inline, virtual]
Sets the bits of a floating point register of single width to a binary value.
Implements ExecContext.
Definition at line 341 of file base.hh.
References StaticInst::destRegIdx(), AlphaISA::FP_Reg_Base, numFpRegWrites, SimpleThread::setFloatRegBits(), and thread.
void BaseSimpleCPU::setIntRegOperand (const StaticInst * si, int idx, IntReg val) [inline, virtual]
Sets an integer register to a value.
Implements ExecContext.
Definition at line 328 of file base.hh.
References StaticInst::destRegIdx(), numIntRegWrites, SimpleThread::setIntReg(), and thread.
void BaseSimpleCPU::setMiscReg (int misc_reg, const MiscReg & val) [inline, virtual]
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
Implements ExecContext.
Definition at line 381 of file base.hh.
References numIntRegWrites, SimpleThread::setMiscReg(), and thread.
void BaseSimpleCPU::setMiscRegOperand (const StaticInst * si, int idx, const MiscReg & val) [inline, virtual]
Implements ExecContext.
Definition at line 394 of file base.hh.
References StaticInst::destRegIdx(), AlphaISA::Misc_Reg_Base, numIntRegWrites, SimpleThread::setMiscReg(), and thread.
void BaseSimpleCPU::setPredicate (bool val) [inline, virtual]
Implements ExecContext.
Definition at line 357 of file base.hh.
References Trace::InstRecord::setPredicate(), SimpleThread::setPredicate(), thread, and traceData.
void BaseSimpleCPU::setRegOtherThread (int regIdx, MiscReg val, ThreadID tid = InvalidThreadID) [inline, virtual]
Implements ExecContext.
Definition at line 431 of file base.hh.
References panic.
void BaseSimpleCPU::setStCondFailures (unsigned int sc_failures) [inline, virtual]
Sets the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 421 of file base.hh.
References SimpleThread::setStCondFailures(), and thread.
void BaseSimpleCPU::setupFetchRequest (Request * req)
Definition at line 365 of file base.cc.
References DPRINTF, fetchOffset, Request::INST_FETCH, SimpleThread::instAddr(), instAddr(), Request::setVirt(), and thread.
Referenced by TimingSimpleCPU::fetch(), and AtomicSimpleCPU::tick().
bool BaseSimpleCPU::simPalCheck (int palFunc) [inline, virtual]
Check for special simulator handling of specific PAL calls.
If return value is false, actual PAL call will be suppressed.
Implements ExecContext.
Definition at line 441 of file base.hh.
References SimpleThread::simPalCheck(), and thread.
void BaseSimpleCPU::startup () [virtual]
Definition at line 583 of file base.cc.
References SimpleThread::startup(), and thread.
void BaseSimpleCPU::syscall (int64_t callnum) [inline, virtual]
Executes a syscall specified by the callnum.
Implements ExecContext.
Definition at line 444 of file base.hh.
References FullSystem, panic, SimpleThread::syscall(), and thread.
ThreadContext* BaseSimpleCPU::tcBase () [inline, virtual]
Returns a pointer to the ThreadContext.
Implements ExecContext.
Definition at line 452 of file base.hh.
References tc.
Referenced by TimingSimpleCPU::init(), and AtomicSimpleCPU::init().
virtual Counter BaseSimpleCPU::totalInsts () const [inline, virtual]
Definition at line 202 of file base.hh.
References numInst, and startNumInst.
virtual Counter BaseSimpleCPU::totalOps () const [inline, virtual]
Definition at line 207 of file base.hh.
References numOp, and startNumOp.
void BaseSimpleCPU::unserializeThread (Checkpoint * cp, const std::string & section, ThreadID tid)
void BaseSimpleCPU::wakeup ()
Reimplemented from BaseCPU.
Definition at line 337 of file base.cc.
References SimpleThread::activate(), DPRINTF, getAddrMonitor(), SimpleThread::status(), ThreadContext::Suspended, and thread.
Referenced by AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop(), TimingSimpleCPU::DcachePort::recvFunctionalSnoop(), AtomicSimpleCPU::AtomicCPUDPort::recvFunctionalSnoop(), and TimingSimpleCPU::DcachePort::recvTimingSnoopReq().
void BaseSimpleCPU::zero_fill_64 (Addr addr) [inline]
Definition at line 108 of file base.hh.
References warn.
Member Data Documentation
Status BaseSimpleCPU::_status [protected]
Definition at line 147 of file base.hh.
Referenced by TimingSimpleCPU::activateContext(), AtomicSimpleCPU::activateContext(), TimingSimpleCPU::advanceInst(), AtomicSimpleCPU::AtomicSimpleCPU(), TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), TimingSimpleCPU::drain(), TimingSimpleCPU::drainResume(), AtomicSimpleCPU::drainResume(), TimingSimpleCPU::fetch(), TimingSimpleCPU::finishTranslation(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), TimingSimpleCPU::FetchTranslation::markDelayed(), TimingSimpleCPU::readMem(), TimingSimpleCPU::DcachePort::recvReqRetry(), TimingSimpleCPU::IcachePort::recvReqRetry(), resetStats(), TimingSimpleCPU::sendData(), TimingSimpleCPU::sendFetch(), TimingSimpleCPU::suspendContext(), AtomicSimpleCPU::suspendContext(), TimingSimpleCPU::switchOut(), AtomicSimpleCPU::switchOut(), AtomicSimpleCPU::tick(), TimingSimpleCPU::TimingSimpleCPU(), and TimingSimpleCPU::writeMem().
BPredUnit* BaseSimpleCPU::branchPred [protected]
Definition at line 91 of file base.hh.
Referenced by advancePC(), and preExecute().
CheckerCPU* BaseSimpleCPU::checker
Definition at line 129 of file base.hh.
Referenced by BaseSimpleCPU().
StaticInstPtr BaseSimpleCPU::curMacroStaticInst
Definition at line 159 of file base.hh.
Referenced by advancePC(), TimingSimpleCPU::fetch(), preExecute(), and AtomicSimpleCPU::tick().
StaticInstPtr BaseSimpleCPU::curStaticInst
Definition at line 158 of file base.hh.
Referenced by advancePC(), TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), countInst(), TimingSimpleCPU::fetch(), postExecute(), preExecute(), and AtomicSimpleCPU::tick().
Stats::Scalar BaseSimpleCPU::dcacheStallCycles
Definition at line 266 of file base.hh.
Referenced by regStats().
Addr BaseSimpleCPU::fetchOffset
Definition at line 162 of file base.hh.
Referenced by advancePC(), BaseSimpleCPU(), checkForInterrupts(), preExecute(), and setupFetchRequest().
Stats::Scalar BaseSimpleCPU::icacheStallCycles
Definition at line 262 of file base.hh.
Referenced by regStats().
Stats::Formula BaseSimpleCPU::idleFraction
Definition at line 259 of file base.hh.
Referenced by regStats().
TheISA::MachInst BaseSimpleCPU::inst
Definition at line 156 of file base.hh.
Referenced by preExecute(), TimingSimpleCPU::sendFetch(), and AtomicSimpleCPU::tick().
bool BaseSimpleCPU::interval_stats
Definition at line 153 of file base.hh.
Counter BaseSimpleCPU::lastDcacheStall
Definition at line 267 of file base.hh.
Referenced by BaseSimpleCPU().
Counter BaseSimpleCPU::lastIcacheStall
Definition at line 263 of file base.hh.
Referenced by BaseSimpleCPU().
Stats::Average BaseSimpleCPU::notIdleFraction
Definition at line 258 of file base.hh.
Referenced by TimingSimpleCPU::activateContext(), AtomicSimpleCPU::activateContext(), TimingSimpleCPU::drainResume(), AtomicSimpleCPU::drainResume(), regStats(), resetStats(), TimingSimpleCPU::suspendContext(), and AtomicSimpleCPU::suspendContext().
Stats::Scalar BaseSimpleCPU::numBranches
Total number of branches fetched
Definition at line 271 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numBranchMispred
Number of misprediced branches.
Definition at line 275 of file base.hh.
Referenced by advancePC(), and regStats().
Stats::Formula BaseSimpleCPU::numBusyCycles
Definition at line 251 of file base.hh.
Referenced by regStats().
Stats::Scalar BaseSimpleCPU::numCallsReturns
Definition at line 219 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numCCRegReads
Definition at line 239 of file base.hh.
Referenced by readCCRegOperand(), and regStats().
Stats::Scalar BaseSimpleCPU::numCCRegWrites
Definition at line 240 of file base.hh.
Referenced by regStats(), and setCCRegOperand().
Stats::Scalar BaseSimpleCPU::numCondCtrlInsts
Definition at line 222 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numFpAluAccesses
Definition at line 216 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numFpInsts
Definition at line 228 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numFpRegReads
Definition at line 235 of file base.hh.
Referenced by readFloatRegOperand(), readFloatRegOperandBits(), and regStats().
Stats::Scalar BaseSimpleCPU::numFpRegWrites
Definition at line 236 of file base.hh.
Referenced by regStats(), setFloatRegOperand(), and setFloatRegOperandBits().
Stats::Formula BaseSimpleCPU::numIdleCycles
Definition at line 248 of file base.hh.
Referenced by regStats().
Counter BaseSimpleCPU::numInst
Definition at line 182 of file base.hh.
Referenced by BaseSimpleCPU(), countInst(), preExecute(), and totalInsts().
Stats::Scalar BaseSimpleCPU::numInsts
Definition at line 184 of file base.hh.
Referenced by countInst(), and regStats().
Stats::Scalar BaseSimpleCPU::numIntAluAccesses
Definition at line 213 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numIntInsts
Definition at line 225 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numIntRegReads
Definition at line 231 of file base.hh.
Referenced by readIntRegOperand(), readMiscReg(), readMiscRegOperand(), and regStats().
Stats::Scalar BaseSimpleCPU::numIntRegWrites
Definition at line 232 of file base.hh.
Referenced by regStats(), setIntRegOperand(), setMiscReg(), and setMiscRegOperand().
Counter BaseSimpleCPU::numLoad
Definition at line 254 of file base.hh.
Referenced by BaseSimpleCPU(), and postExecute().
Stats::Scalar BaseSimpleCPU::numLoadInsts
Definition at line 244 of file base.hh.
Referenced by postExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numMemRefs
Definition at line 243 of file base.hh.
Referenced by postExecute(), and regStats().
Counter BaseSimpleCPU::numOp
Definition at line 185 of file base.hh.
Referenced by BaseSimpleCPU(), countInst(), and totalOps().
Stats::Scalar BaseSimpleCPU::numOps
Definition at line 187 of file base.hh.
Referenced by countInst(), and regStats().
Stats::Scalar BaseSimpleCPU::numPredictedBranches
Number of branches predicted as taken.
Definition at line 273 of file base.hh.
Referenced by preExecute(), and regStats().
Stats::Scalar BaseSimpleCPU::numStoreInsts
Definition at line 245 of file base.hh.
Referenced by postExecute(), and regStats().
TheISA::PCState BaseSimpleCPU::pred_pc [private]
Definition at line 455 of file base.hh.
Referenced by advancePC(), and preExecute().
Counter BaseSimpleCPU::startNumInst
Definition at line 183 of file base.hh.
Referenced by BaseSimpleCPU(), and totalInsts().
Counter BaseSimpleCPU::startNumLoad
Definition at line 255 of file base.hh.
Referenced by BaseSimpleCPU().
Counter BaseSimpleCPU::startNumOp
Definition at line 186 of file base.hh.
Referenced by BaseSimpleCPU(), and totalOps().
Stats::Vector BaseSimpleCPU::statExecutedInstType
Definition at line 279 of file base.hh.
Referenced by postExecute(), and regStats().
bool BaseSimpleCPU::stayAtPC
Definition at line 165 of file base.hh.
Referenced by TimingSimpleCPU::advanceInst(), BaseSimpleCPU(), TimingSimpleCPU::isDrained(), AtomicSimpleCPU::isDrained(), preExecute(), TimingSimpleCPU::switchOut(), and AtomicSimpleCPU::tick().
ThreadContext* BaseSimpleCPU::tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
Definition at line 127 of file base.hh.
Referenced by advancePC(), BaseSimpleCPU(), checkForInterrupts(), checkPcEventQueue(), dbg_vtophys(), TimingSimpleCPU::fetch(), TimingSimpleCPU::init(), AtomicSimpleCPU::init(), postExecute(), preExecute(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), tcBase(), AtomicSimpleCPU::tick(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
SimpleThread* BaseSimpleCPU::thread
SimpleThread object, provides all the architectural state.
Definition at line 122 of file base.hh.
Referenced by TimingSimpleCPU::activateContext(), AtomicSimpleCPU::activateContext(), advancePC(), BaseSimpleCPU(), checkForInterrupts(), checkPcEventQueue(), countInst(), demapDataPage(), demapInstPage(), demapPage(), TimingSimpleCPU::drainResume(), AtomicSimpleCPU::drainResume(), TimingSimpleCPU::fetch(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), hwrei(), instAddr(), microPC(), mwaitAtomic(), nextInstAddr(), pcState(), postExecute(), preExecute(), readCCRegOperand(), readFloatRegOperand(), readFloatRegOperandBits(), readIntRegOperand(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), readMiscReg(), readMiscRegNoEffect(), readMiscRegOperand(), readPredicate(), readStCondFailures(), TimingSimpleCPU::DcachePort::recvTimingSnoopReq(), TimingSimpleCPU::sendData(), setCCRegOperand(), setFloatRegOperand(), setFloatRegOperandBits(), setIntRegOperand(), setMiscReg(), setMiscRegOperand(), setPredicate(), setStCondFailures(), setupFetchRequest(), simPalCheck(), startup(), TimingSimpleCPU::suspendContext(), AtomicSimpleCPU::suspendContext(), syscall(), AtomicSimpleCPU::tick(), wakeup(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
Trace::InstRecord* BaseSimpleCPU::traceData [protected]
Definition at line 94 of file base.hh.
Referenced by TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), postExecute(), preExecute(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), setPredicate(), AtomicSimpleCPU::tick(), TimingSimpleCPU::translationFault(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
The documentation for this class was generated from the following files:
cpu/simple/base.hh
cpu/simple/base.cc