gem5: GlobalSyncEvent Class Reference
GlobalSyncEvent Class Reference
A special global event that synchronizes all threads and forces them to process asynchronously enqueued events.
#include <global_event.hh>
Classes
class BarrierEvent
Public Types
typedef
BaseGlobalEventTemplate
< GlobalSyncEvent > Base
Public Member Functions
GlobalSyncEvent (Priority p, Flags f)
GlobalSyncEvent (Tick when, Tick _repeat, Priority p, Flags f)
void process ()
const char * description () const
Public Attributes
Tick repeat
Detailed Description
A special global event that synchronizes all threads and forces them to process asynchronously enqueued events.
Useful for separating quanta in a quantum-based parallel simulation.
Definition at line 207 of file global_event.hh.
Member Typedef Documentation
typedef BaseGlobalEventTemplate<GlobalSyncEvent> GlobalSyncEvent::Base
Definition at line 210 of file global_event.hh.
Constructor & Destructor Documentation
GlobalSyncEvent::GlobalSyncEvent (Priority p, Flags f) [inline]
Definition at line 221 of file global_event.hh.
GlobalSyncEvent::GlobalSyncEvent (Tick when, Tick _repeat, Priority p, Flags f) [inline]
Definition at line 225 of file global_event.hh.
References BaseGlobalEvent::schedule().
Member Function Documentation
const char * GlobalSyncEvent::description () const [virtual]
Implements BaseGlobalEvent.
Definition at line 163 of file global_event.cc.
void GlobalSyncEvent::process () [virtual]
Implements BaseGlobalEvent.
Definition at line 155 of file global_event.cc.
References curTick(), repeat, and BaseGlobalEvent::schedule().
Member Data Documentation
Tick GlobalSyncEvent::repeat
Definition at line 235 of file global_event.hh.
Referenced by process().
The documentation for this class was generated from the following files:
sim/global_event.hh
sim/global_event.cc