gem5: RubyMemoryControl::MemoryPort Class Reference
RubyMemoryControl::MemoryPort Class Reference
Public Member Functions
MemoryPort (const std::string &name, RubyMemoryControl &_memory)
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
bool recvTimingReq (PacketPtr)
Receive a timing request from the master port.
virtual AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Private Attributes
RespPacketQueue queue
RubyMemoryControl & memory
Detailed Description
Definition at line 110 of file RubyMemoryControl.hh.
Constructor & Destructor Documentation
RubyMemoryControl::MemoryPort::MemoryPort (const std::string & name, RubyMemoryControl & _memory)
Definition at line 767 of file RubyMemoryControl.cc.
Member Function Documentation
AddrRangeList RubyMemoryControl::MemoryPort::getAddrRanges () const [protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 774 of file RubyMemoryControl.cc.
References AbstractMemory::getAddrRange(), and memory.
Tick RubyMemoryControl::MemoryPort::recvAtomic (PacketPtr pkt) [protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 797 of file RubyMemoryControl.cc.
References panic.
void RubyMemoryControl::MemoryPort::recvFunctional (PacketPtr pkt) [protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 782 of file RubyMemoryControl.cc.
References PacketQueue::checkFunctional(), RubyMemoryControl::functionalWrite(), memory, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), and queue.
bool RubyMemoryControl::MemoryPort::recvTimingReq (PacketPtr pkt) [protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 803 of file RubyMemoryControl.cc.
References memory, and RubyMemoryControl::recvTimingReq().
Member Data Documentation
RubyMemoryControl& RubyMemoryControl::MemoryPort::memory [private]
Definition at line 113 of file RubyMemoryControl.hh.
Referenced by getAddrRanges(), recvFunctional(), and recvTimingReq().
RespPacketQueue RubyMemoryControl::MemoryPort::queue [private]
Definition at line 112 of file RubyMemoryControl.hh.
Referenced by recvFunctional().
The documentation for this class was generated from the following files:
mem/ruby/structures/RubyMemoryControl.hh
mem/ruby/structures/RubyMemoryControl.cc