gem5: DRAMSim2Wrapper Class Reference
DRAMSim2Wrapper Class Reference
Wrapper class to avoid having DRAMSim2 names like ClockDomain etc clashing with the normal gem5 world.
#include <dramsim2_wrapper.hh>
Public Member Functions
DRAMSim2Wrapper (const std::string &config_file, const std::string &system_file, const std::string &working_dir, const std::string &trace_file, unsigned int memory_size_mb, bool enable_debug, const std::string &name)
Create an instance of the DRAMSim2 multi-channel memory controller using a specific config and system description.
~DRAMSim2Wrapper ()
void printStats ()
Print the stats gathered in DRAMsim2.
void setCallbacks (DRAMSim::TransactionCompleteCB *read_callback, DRAMSim::TransactionCompleteCB *write_callback)
Set the callbacks to use for read and write completion.
bool canAccept () const
Determine if the controller can accept a new packet or not.
void enqueue (bool is_write, uint64_t addr)
Enqueue a packet.
double clockPeriod () const
Get the internal clock period used by DRAMSim2, specified in ns.
unsigned int queueSize () const
Get the transaction queue size used by DRAMSim2.
unsigned int burstSize () const
Get the burst size in bytes used by DRAMSim2.
void tick ()
Progress the memory controller one cycle.
void resetStats ()
Private Member Functions
template<typename T >
T extractConfig (const std::string &field_name, const std::string &file_name) const
Private Attributes
std::string _name
DRAMSim::MultiChannelMemorySystem * dramsim
double _clockPeriod
unsigned int _queueSize
unsigned int _burstSize
Detailed Description
Wrapper class to avoid having DRAMSim2 names like ClockDomain etc clashing with the normal gem5 world.
Many of the DRAMSim2 headers do not make use of namespaces, and quite a few also open up std. The only thing that needs to be exposed externally are the callbacks. This wrapper effectively avoids clashes by not including any of the conventional gem5 headers (e.g. Packet or SimObject).
Definition at line 69 of file dramsim2_wrapper.hh.
Constructor & Destructor Documentation
DRAMSim2Wrapper::DRAMSim2Wrapper (const std::string & config_file, const std::string & system_file, const std::string & working_dir, const std::string & trace_file, unsigned int memory_size_mb, bool enable_debug, const std::string & name)
Create an instance of the DRAMSim2 multi-channel memory controller using a specific config and system description.
Parameters:
config_file Memory config file
system_file Controller config file
working_dir Path pre-pended to config files
trace_file Output trace file
memory_size_mb Total memory size in MByte
enable_debug Enable debug output
Definition at line 65 of file dramsim2_wrapper.cc.
References _burstSize, _clockPeriod, _name, _queueSize, dramsim, fatal, and SHOW_SIM_OUTPUT.
DRAMSim2Wrapper::~DRAMSim2Wrapper ()
Definition at line 117 of file dramsim2_wrapper.cc.
References dramsim.
Member Function Documentation
unsigned int DRAMSim2Wrapper::burstSize () const
Get the burst size in bytes used by DRAMSim2.
Returns:
The burst size in bytes (data width * burst length)
Definition at line 202 of file dramsim2_wrapper.cc.
References _burstSize.
Referenced by DRAMSim2::init().
bool DRAMSim2Wrapper::canAccept () const
Determine if the controller can accept a new packet or not.
Returns:
true if the controller can accept transactions
Definition at line 177 of file dramsim2_wrapper.cc.
References dramsim.
Referenced by DRAMSim2::recvTimingReq().
double DRAMSim2Wrapper::clockPeriod () const
Get the internal clock period used by DRAMSim2, specified in ns.
Returns:
The clock period of the DRAM interface in ns
Definition at line 190 of file dramsim2_wrapper.cc.
References _clockPeriod.
Referenced by DRAMSim2::DRAMSim2(), DRAMSim2::readComplete(), DRAMSim2::tick(), and DRAMSim2::writeComplete().
void DRAMSim2Wrapper::enqueue (bool is_write, uint64_t addr)
Enqueue a packet.
This assumes that canAccept has returned true.
Parameters:
pkt Packet to turn into a DRAMSim2 transaction
Definition at line 183 of file dramsim2_wrapper.cc.
References dramsim, and ArmISA::M5_VAR_USED.
Referenced by DRAMSim2::recvTimingReq().
template<typename T > T DRAMSim2Wrapper::extractConfig (const std::string & field_name, const std::string & file_name) const [inline, private]
Definition at line 124 of file dramsim2_wrapper.cc.
References fatal.
void DRAMSim2Wrapper::printStats ()
Print the stats gathered in DRAMsim2.
Definition at line 154 of file dramsim2_wrapper.cc.
References _name, dramsim, and inform.
Referenced by DRAMSim2::DRAMSim2().
unsigned int DRAMSim2Wrapper::queueSize () const
Get the transaction queue size used by DRAMSim2.
Returns:
The queue size counted in number of transactions
Definition at line 196 of file dramsim2_wrapper.cc.
References _queueSize.
Referenced by DRAMSim2::DRAMSim2(), DRAMSim2::recvTimingReq(), and DRAMSim2::tick().
void DRAMSim2Wrapper::resetStats ()
Definition at line 162 of file dramsim2_wrapper.cc.
References dramsim, and inform.
Referenced by DRAMSim2::DRAMSim2().
void DRAMSim2Wrapper::setCallbacks (DRAMSim::TransactionCompleteCB * read_callback, DRAMSim::TransactionCompleteCB * write_callback)
Set the callbacks to use for read and write completion.
Parameters:
read_callback Callback used for read completions
write_callback Callback used for write completions
Definition at line 169 of file dramsim2_wrapper.cc.
References dramsim.
Referenced by DRAMSim2::DRAMSim2().
void DRAMSim2Wrapper::tick ()
Progress the memory controller one cycle.
Definition at line 208 of file dramsim2_wrapper.cc.
References dramsim.
Referenced by DRAMSim2::tick().
Member Data Documentation
unsigned int DRAMSim2Wrapper::_burstSize [private]
Definition at line 82 of file dramsim2_wrapper.hh.
Referenced by burstSize(), and DRAMSim2Wrapper().
double DRAMSim2Wrapper::_clockPeriod [private]
Definition at line 78 of file dramsim2_wrapper.hh.
Referenced by clockPeriod(), and DRAMSim2Wrapper().
std::string DRAMSim2Wrapper::_name [private]
Definition at line 74 of file dramsim2_wrapper.hh.
Referenced by DRAMSim2Wrapper(), and printStats().
unsigned int DRAMSim2Wrapper::_queueSize [private]
Definition at line 80 of file dramsim2_wrapper.hh.
Referenced by DRAMSim2Wrapper(), and queueSize().
DRAMSim::MultiChannelMemorySystem* DRAMSim2Wrapper::dramsim [private]
Definition at line 76 of file dramsim2_wrapper.hh.
Referenced by canAccept(), DRAMSim2Wrapper(), enqueue(), printStats(), resetStats(), setCallbacks(), tick(), and ~DRAMSim2Wrapper().
The documentation for this class was generated from the following files:
mem/dramsim2_wrapper.hh
mem/dramsim2_wrapper.cc