gem5: ArmISA::TLB Class Reference
ArmISA::TLB Class Reference
#include <tlb.hh>
Public Types
enum ArmFlags {
AlignmentMask = 0x7, AlignByte = 0x0, AlignHalfWord = 0x1, AlignWord = 0x2,
AlignDoubleWord = 0x3, AlignQuadWord = 0x4, AlignOctWord = 0x5, AllowUnaligned = 0x8,
UserMode = 0x10, MustBeOne = 0x40
}
enum ArmTranslationType { NormalTran = 0, S1CTran = 0x1, HypMode = 0x2, S1S2NsTran = 0x4 }
Public Member Functions
TLB (const ArmTLBParams *p)
TLB (const Params *p, int _size, TableWalker *_walker)
TlbEntry * lookup (Addr vpn, uint16_t asn, uint8_t vmid, bool hyp, bool secure, bool functional, bool ignore_asn, uint8_t target_el)
Lookup an entry in the TLB.
virtual ~TLB ()
void takeOverFrom (BaseTLB *otlb)
virtual void init ()
setup all the back pointers
TableWalker * getTableWalker ()
void setMMU (Stage2MMU *m, MasterID master_id)
int getsize () const
void insert (Addr vaddr, TlbEntry &pte)
Fault getTE (TlbEntry **te, RequestPtr req, ThreadContext *tc, Mode mode, Translation *translation, bool timing, bool functional, bool is_secure, ArmTranslationType tranType)
Fault getResultTe (TlbEntry **te, RequestPtr req, ThreadContext *tc, Mode mode, Translation *translation, bool timing, bool functional, TlbEntry *mergeTe)
Fault checkPermissions (TlbEntry *te, RequestPtr req, Mode mode)
Fault checkPermissions64 (TlbEntry *te, RequestPtr req, Mode mode, ThreadContext *tc)
void flushAllSecurity (bool secure_lookup, uint8_t target_el, bool ignore_el=false)
Reset the entire TLB.
void flushAllNs (bool hyp, uint8_t target_el, bool ignore_el=false)
Remove all entries in the non secure world, depending on whether they were allocated in hyp mode or not.
void flushAll ()
Reset the entire TLB.
void flushMvaAsid (Addr mva, uint64_t asn, bool secure_lookup, uint8_t target_el)
Remove any entries that match both a va and asn.
void flushAsid (uint64_t asn, bool secure_lookup, uint8_t target_el)
Remove any entries that match the asn.
void flushMva (Addr mva, bool secure_lookup, bool hyp, uint8_t target_el)
Remove all entries that match the va regardless of asn.
Fault trickBoxCheck (RequestPtr req, Mode mode, TlbEntry::DomainType domain)
Fault walkTrickBoxCheck (Addr pa, bool is_secure, Addr va, Addr sz, bool is_exec, bool is_write, TlbEntry::DomainType domain, LookupLevel lookup_level)
void printTlb () const
void demapPage (Addr vaddr, uint64_t asn)
bool translateFunctional (ThreadContext *tc, Addr vaddr, Addr &paddr)
Do a functional lookup on the TLB (for debugging) and don't modify any internal state.
Fault translateFunctional (RequestPtr req, ThreadContext *tc, Mode mode, ArmTranslationType tranType=NormalTran)
Do a functional lookup on the TLB (for checker cpu) that behaves like a normal lookup without modifying any page table state.
void setAttr (uint64_t attr)
Accessor functions for memory attributes for last accessed TLB entry.
uint64_t getAttr () const
Fault translateFs (RequestPtr req, ThreadContext *tc, Mode mode, Translation *translation, bool &delay, bool timing, ArmTranslationType tranType, bool functional=false)
Fault translateSe (RequestPtr req, ThreadContext *tc, Mode mode, Translation *translation, bool &delay, bool timing)
Fault translateAtomic (RequestPtr req, ThreadContext *tc, Mode mode, ArmTranslationType tranType=NormalTran)
Fault translateTiming (RequestPtr req, ThreadContext *tc, Translation *translation, Mode mode, ArmTranslationType tranType=NormalTran)
Fault translateComplete (RequestPtr req, ThreadContext *tc, Translation *translation, Mode mode, ArmTranslationType tranType, bool callFromS2)
Fault finalizePhysical (RequestPtr req, ThreadContext *tc, Mode mode) const
void drainResume ()
Resume execution after a successful drain.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
void regStats ()
Register statistics for this object.
void regProbePoints () M5_ATTR_OVERRIDE
Register probe points for this object.
virtual BaseMasterPort * getMasterPort ()
Get the table walker master port.
const Params * params () const
void invalidateMiscReg ()
Static Public Member Functions
static bool validVirtualAddress (Addr vaddr)
Protected Member Functions
void updateMiscReg (ThreadContext *tc, ArmTranslationType tranType=NormalTran)
Protected Attributes
TlbEntry * table
int size
bool isStage2
bool stage2Req
uint64_t _attr
bool directToStage2
TableWalker * tableWalker
TLB * stage2Tlb
Stage2MMU * stage2Mmu
Stats::Scalar instHits
Stats::Scalar instMisses
Stats::Scalar readHits
Stats::Scalar readMisses
Stats::Scalar writeHits
Stats::Scalar writeMisses
Stats::Scalar inserts
Stats::Scalar flushTlb
Stats::Scalar flushTlbMva
Stats::Scalar flushTlbMvaAsid
Stats::Scalar flushTlbAsid
Stats::Scalar flushedEntries
Stats::Scalar alignFaults
Stats::Scalar prefetchFaults
Stats::Scalar domainFaults
Stats::Scalar permsFaults
Stats::Formula readAccesses
Stats::Formula writeAccesses
Stats::Formula instAccesses
Stats::Formula hits
Stats::Formula misses
Stats::Formula accesses
ProbePoints::PMUUPtr ppRefills
PMU probe for TLB refills.
int rangeMRU
CPSR cpsr
bool aarch64
ExceptionLevel aarch64EL
SCTLR sctlr
SCR scr
bool isPriv
bool isSecure
bool isHyp
TTBCR ttbcr
uint16_t asid
uint8_t vmid
PRRR prrr
NMRR nmrr
HCR hcr
uint32_t dacr
bool miscRegValid
ArmTranslationType curTranType
bool haveLPAE
bool haveVirtualization
bool haveLargeAsid64
Private Member Functions
void _flushMva (Addr mva, uint64_t asn, bool secure_lookup, bool hyp, bool ignore_asn, uint8_t target_el)
Remove any entries that match both a va and asn.
bool checkELMatch (uint8_t target_el, uint8_t tentry_el, bool ignore_el)
Detailed Description
Definition at line 65 of file tlb.hh.
Member Enumeration Documentation
enum ArmISA::TLB::ArmFlags
Enumerator:
AlignmentMask
AlignByte
AlignHalfWord
AlignWord
AlignDoubleWord
AlignQuadWord
AlignOctWord
AllowUnaligned
UserMode
MustBeOne
Definition at line 68 of file tlb.hh.
enum ArmISA::TLB::ArmTranslationType
Enumerator:
NormalTran
S1CTran
HypMode
S1S2NsTran
Definition at line 87 of file tlb.hh.
Constructor & Destructor Documentation
TLB::TLB (const ArmTLBParams * p)
Definition at line 74 of file tlb.cc.
References ArmISA::TableWalker::haveLargeAsid64(), haveLargeAsid64, ArmISA::TableWalker::haveLPAE(), haveLPAE, ArmISA::TableWalker::haveVirtualization(), haveVirtualization, ArmISA::TableWalker::setTlb(), and tableWalker.
ArmISA::TLB::TLB (const Params * p, int _size, TableWalker * _walker)
TLB::~TLB () [virtual]
Definition at line 91 of file tlb.cc.
References table.
Member Function Documentation
void TLB::_flushMva (Addr mva, uint64_t asn, bool secure_lookup, bool hyp, bool ignore_asn, uint8_t target_el) [private]
Remove any entries that match both a va and asn.
Parameters:
mva virtual address to flush
asn contextid/asn to flush on match
secure_lookup if the operation affects the secure world
hyp if the operation affects hyp mode
ignore_asn if the flush should ignore the asn
Definition at line 321 of file tlb.cc.
References DPRINTF, flushedEntries, lookup(), MipsISA::te, and vmid.
Referenced by flushMva(), and flushMvaAsid().
bool TLB::checkELMatch (uint8_t target_el, uint8_t tentry_el, bool ignore_el) [private]
Definition at line 341 of file tlb.cc.
Referenced by flushAllNs(), flushAllSecurity(), and flushAsid().
Fault TLB::checkPermissions (TlbEntry * te, RequestPtr req, Mode mode)
Definition at line 596 of file tlb.cc.
References alignFaults, ArmISA::ArmFault::AlignmentFault, AlignmentMask, ArmISA::TlbEntry::ap, dacr, ArmISA::TlbEntry::domain, domainFaults, ArmISA::ArmFault::DomainLL, DPRINTF, BaseTLB::Execute, Request::getFlags(), Request::getVaddr(), ArmISA::TlbEntry::hap, hcr, Request::isPrefetch(), isPriv, Request::isPTWalk(), isSecure, isStage2, ArmISA::TlbEntry::longDescFormat, ArmISA::TlbEntry::lookupLevel, ArmISA::ArmFault::LpaeTran, ArmISA::mask, ArmISA::TlbEntry::mtype, ArmISA::TlbEntry::nonCacheable, ArmISA::TlbEntry::ns, panic, ArmISA::ArmFault::PermissionLL, permsFaults, ArmISA::ArmFault::PrefetchUncacheable, ArmISA::TlbEntry::pxn, scr, sctlr, UserMode, MipsISA::vaddr, ArmISA::ArmFault::VmsaTran, BaseTLB::Write, and ArmISA::TlbEntry::xn.
Referenced by getResultTe(), and ArmISA::Stage2LookUp::mergeTe().
Fault TLB::checkPermissions64 (TlbEntry * te, RequestPtr req, Mode mode, ThreadContext * tc)
Definition at line 763 of file tlb.cc.
References aarch64, aarch64EL, alignFaults, ArmISA::ArmFault::AlignmentFault, AlignmentMask, ArmISA::TlbEntry::ap, curTranType, ArmISA::TlbEntry::domain, DPRINTF, ArmISA::EL0, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, BaseTLB::Execute, Request::getFlags(), Request::getPC(), Request::getVaddr(), hcr, Request::isPrefetch(), isPriv, Request::isPTWalk(), isStage2, ArmISA::TlbEntry::lookupLevel, ArmISA::ArmFault::LpaeTran, ArmISA::M5_VAR_USED, ArmISA::mask, ArmISA::TlbEntry::mtype, ArmISA::TlbEntry::nonCacheable, ArmISA::TlbEntry::ns, panic, ArmISA::ArmFault::PermissionLL, permsFaults, ArmISA::ArmFault::PrefetchUncacheable, ArmISA::purifyTaggedAddr(), ArmISA::TlbEntry::pxn, MipsISA::r, scr, sctlr, ttbcr, updateMiscReg(), UserMode, MipsISA::vaddr, MipsISA::w, BaseTLB::Write, X86ISA::x, and ArmISA::TlbEntry::xn.
Referenced by getResultTe().
void ArmISA::TLB::demapPage (Addr vaddr, uint64_t asn) [inline, virtual]
Implements BaseTLB.
Definition at line 233 of file tlb.hh.
References panic.
void TLB::drainResume () [virtual]
Resume execution after a successful drain.
Note:
This method is normally only called from the simulation scripts.
Reimplemented from Drainable.
Definition at line 355 of file tlb.cc.
References miscRegValid.
Fault TLB::finalizePhysical (RequestPtr req, ThreadContext * tc, Mode mode) const
Definition at line 129 of file tlb.cc.
void ArmISA::TLB::flushAll () [inline, virtual]
Reset the entire TLB.
Used for CPU switching to prevent stale translations after multiple switches
Implements BaseTLB.
Definition at line 200 of file tlb.hh.
References flushAllSecurity().
void TLB::flushAllNs (bool hyp, uint8_t target_el, bool ignore_el = false)
Remove all entries in the non secure world, depending on whether they were allocated in hyp mode or not.
Parameters:
hyp if the opperation affects hyp mode
Definition at line 251 of file tlb.cc.
References checkELMatch(), DPRINTF, ArmISA::TlbEntry::el, flushAllNs(), flushedEntries, flushTlb, ArmISA::TlbEntry::isHyp, isStage2, ArmISA::TlbEntry::nstid, ArmISA::TlbEntry::print(), size, stage2Tlb, table, MipsISA::te, ArmISA::TlbEntry::valid, and X86ISA::x.
Referenced by flushAllNs().
void TLB::flushAllSecurity (bool secure_lookup, uint8_t target_el, bool ignore_el = false)
Reset the entire TLB.
Parameters:
secure_lookup if the operation affects the secure world
Definition at line 222 of file tlb.cc.
References checkELMatch(), DPRINTF, ArmISA::TlbEntry::el, flushAllSecurity(), flushedEntries, flushTlb, isHyp, isStage2, ArmISA::TlbEntry::nstid, ArmISA::TlbEntry::print(), size, stage2Tlb, table, MipsISA::te, ArmISA::TlbEntry::valid, vmid, ArmISA::TlbEntry::vmid, and X86ISA::x.
Referenced by flushAll(), and flushAllSecurity().
void TLB::flushAsid (uint64_t asn, bool secure_lookup, uint8_t target_el)
Remove any entries that match the asn.
Parameters:
asn contextid/asn to flush on match
secure_lookup if the operation affects the secure world
Definition at line 288 of file tlb.cc.
References ArmISA::TlbEntry::asid, checkELMatch(), DPRINTF, ArmISA::TlbEntry::el, flushedEntries, flushTlbAsid, ArmISA::TlbEntry::nstid, ArmISA::TlbEntry::print(), size, table, MipsISA::te, ArmISA::TlbEntry::valid, vmid, ArmISA::TlbEntry::vmid, and X86ISA::x.
void TLB::flushMva (Addr mva, bool secure_lookup, bool hyp, uint8_t target_el)
Remove all entries that match the va regardless of asn.
Parameters:
mva address to flush from cache
secure_lookup if the operation affects the secure world
hyp if the operation affects hyp mode
Definition at line 312 of file tlb.cc.
References _flushMva(), DPRINTF, and flushTlbMva.
void TLB::flushMvaAsid (Addr mva, uint64_t asn, bool secure_lookup, uint8_t target_el)
Remove any entries that match both a va and asn.
Parameters:
mva virtual address to flush
asn contextid/asn to flush on match
secure_lookup if the operation affects the secure world
Definition at line 278 of file tlb.cc.
References _flushMva(), DPRINTF, and flushTlbMvaAsid.
uint64_t ArmISA::TLB::getAttr () const [inline]
Definition at line 267 of file tlb.hh.
References _attr.
BaseMasterPort * TLB::getMasterPort () [virtual]
Get the table walker master port.
This is used for migrating port connections during a CPU takeOverFrom() call. For architectures that do not have a table walker, NULL is returned, hence the use of a pointer rather than a reference. For ARM this method will always return a valid port pointer.
Returns:
A pointer to the walker master port
Reimplemented from BaseTLB.
Definition at line 1209 of file tlb.cc.
References ArmISA::Stage2MMU::getPort(), and stage2Mmu.
Fault TLB::getResultTe (TlbEntry ** te, RequestPtr req, ThreadContext * tc, Mode mode, Translation * translation, bool timing, bool functional, TlbEntry * mergeTe)
Definition at line 1382 of file tlb.cc.
References aarch64, ArmISA::ArmFault::annotate(), checkPermissions(), checkPermissions64(), curTranType, DPRINTF, Request::getPaddr(), ArmISA::Stage2LookUp::getTe(), getTE(), Request::getVaddr(), Request::hasPaddr(), ArmISA::Stage2LookUp::isComplete(), isSecure, isStage2, ArmISA::ArmFault::OVA, ArmISA::ArmFault::S1PTW, ArmISA::Stage2LookUp::setSelfDelete(), stage2Req, and stage2Tlb.
Referenced by translateFs().
int ArmISA::TLB::getsize () const [inline]
Definition at line 167 of file tlb.hh.
References size.
TableWalker* ArmISA::TLB::getTableWalker () [inline]
Definition at line 163 of file tlb.hh.
References tableWalker.
Fault TLB::getTE (TlbEntry ** te, RequestPtr req, ThreadContext * tc, Mode mode, Translation * translation, bool timing, bool functional, bool is_secure, TLB::ArmTranslationType tranType)
Definition at line 1320 of file tlb.cc.
References aarch64, aarch64EL, asid, DPRINTF, ArmISA::EL1, BaseTLB::Execute, Request::getVaddr(), instHits, instMisses, isHyp, Request::isPrefetch(), isStage2, lookup(), prefetchFaults, ArmISA::ArmFault::PrefetchTLBMiss, printTlb(), ArmISA::purifyTaggedAddr(), readHits, readMisses, tableWalker, ttbcr, MipsISA::vaddr, vmid, ArmISA::TableWalker::walk(), BaseTLB::Write, writeHits, and writeMisses.
Referenced by ArmISA::Stage2LookUp::finish(), getResultTe(), and ArmISA::Stage2LookUp::getTe().
void TLB::init () [virtual]
setup all the back pointers
Reimplemented from SimObject.
Definition at line 97 of file tlb.cc.
References isStage2, stage2Mmu, ArmISA::Stage2MMU::stage2Tlb(), and stage2Tlb.
void TLB::insert (Addr vaddr, TlbEntry & pte)
Definition at line 178 of file tlb.cc.
References ArmISA::TlbEntry::ap, asid, ArmISA::TlbEntry::asid, ArmISA::TlbEntry::domain, DPRINTF, ArmISA::el, ArmISA::TlbEntry::global, ArmISA::i, inserts, isHyp, ArmISA::TlbEntry::isHyp, ArmISA::TlbEntry::N, ArmISA::TlbEntry::nonCacheable, ArmISA::ns, ArmISA::TlbEntry::ns, ArmISA::TlbEntry::nstid, MipsISA::pfn, ArmISA::TlbEntry::pfn, ppRefills, size, ArmISA::TlbEntry::size, table, ArmISA::TlbEntry::valid, vmid, ArmISA::TlbEntry::vmid, ArmISA::TlbEntry::vpn, and ArmISA::TlbEntry::xn.
Referenced by ArmISA::TableWalker::insertTableEntry().
void ArmISA::TLB::invalidateMiscReg () [inline]
Definition at line 346 of file tlb.hh.
References miscRegValid.
TlbEntry * TLB::lookup (Addr vpn, uint16_t asn, uint8_t vmid, bool hyp, bool secure, bool functional, bool ignore_asn, uint8_t target_el)
Lookup an entry in the TLB.
Parameters:
vpn virtual address
asn context id/address space id to use
vmid The virtual machine ID used for stage 2 translation
secure if the lookup is secure
hyp if the lookup is done from hyp mode
functional if the lookup should modify state
ignore_asn if on lookup asn should be ignored
Returns:
pointer to TLB entry if it exists
Definition at line 135 of file tlb.cc.
References ArmISA::TlbEntry::ap, ArmISA::TlbEntry::asid, DPRINTF, ArmISA::TlbEntry::el, ArmISA::TlbEntry::global, ArmISA::i, ArmISA::TlbEntry::ns, ArmISA::TlbEntry::nstid, ArmISA::TlbEntry::pAddr(), ArmISA::TlbEntry::pfn, rangeMRU, ArmISA::TlbEntry::size, size, table, and X86ISA::x.
Referenced by _flushMva(), getTE(), ArmISA::TableWalker::processWalkWrapper(), and translateFunctional().
const Params* ArmISA::TLB::params () const [inline]
Reimplemented from SimObject.
Definition at line 342 of file tlb.hh.
References SimObject::_params.
void TLB::printTlb () const
Definition at line 208 of file tlb.cc.
References DPRINTF, ArmISA::TlbEntry::print(), size, table, MipsISA::te, ArmISA::TlbEntry::valid, and X86ISA::x.
Referenced by getTE().
void TLB::regProbePoints () [virtual]
Register probe points for this object.
No probe points by default, so do nothing in base.
Reimplemented from SimObject.
Definition at line 537 of file tlb.cc.
References SimObject::getProbeManager(), and ppRefills.
void TLB::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 421 of file tlb.cc.
References accesses, alignFaults, domainFaults, flushedEntries, flushTlb, flushTlbAsid, flushTlbMva, flushTlbMvaAsid, hits, instAccesses, instHits, instMisses, misses, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), permsFaults, prefetchFaults, readAccesses, readHits, readMisses, writeAccesses, writeHits, and writeMisses.
void ArmISA::TLB::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
void ArmISA::TLB::setAttr (uint64_t attr) [inline]
Accessor functions for memory attributes for last accessed TLB entry.
Definition at line 261 of file tlb.hh.
References _attr.
Referenced by translateFs().
void TLB::setMMU (Stage2MMU * m, MasterID master_id)
Definition at line 104 of file tlb.cc.
References ArmISA::TableWalker::setMMU(), stage2Mmu, and tableWalker.
Referenced by ArmISA::Stage2MMU::Stage2MMU().
void TLB::takeOverFrom (BaseTLB * otlb)
Definition at line 363 of file tlb.cc.
References _attr, directToStage2, haveLPAE, isStage2, panic, stage2Req, stage2Tlb, and takeOverFrom().
Referenced by takeOverFrom().
Fault TLB::translateAtomic (RequestPtr req, ThreadContext * tc, Mode mode, TLB::ArmTranslationType tranType = NormalTran)
Definition at line 1123 of file tlb.cc.
References directToStage2, FullSystem, stage2Tlb, translateAtomic(), translateFs(), translateSe(), and updateMiscReg().
Referenced by ArmISA::Stage2MMU::readDataUntimed(), and translateAtomic().
Fault TLB::translateComplete (RequestPtr req, ThreadContext * tc, Translation * translation, Mode mode, TLB::ArmTranslationType tranType, bool callFromS2)
Definition at line 1181 of file tlb.cc.
References DPRINTF, BaseTLB::Translation::finish(), FullSystem, Request::hasPaddr(), BaseTLB::Translation::markDelayed(), stage2Req, translateFs(), and translateSe().
Referenced by ArmISA::Stage2LookUp::finish(), and translateTiming().
Fault TLB::translateFs (RequestPtr req, ThreadContext * tc, Mode mode, Translation * translation, bool & delay, bool timing, TLB::ArmTranslationType tranType, bool functional = false)
Definition at line 951 of file tlb.cc.
References aarch64, aarch64EL, alignFaults, ArmISA::ArmFault::AlignmentFault, AlignmentMask, AllowUnaligned, asid, ArmISA::TlbEntry::attributes, Request::CLEAR_LL, cpsr, ArmISA::TlbEntry::domain, DPRINTF, BaseTLB::Execute, Request::getFlags(), getResultTe(), Request::getVaddr(), haveLPAE, hcr, ArmISA::TlbEntry::innerAttrs, isHyp, Request::isInstFetch(), isPriv, isSecure, isStage2, ArmISA::ArmFault::LpaeTran, ArmISA::mask, ArmISA::TlbEntry::mtype, MustBeOne, nmrr, ArmISA::TlbEntry::nonCacheable, ArmISA::TlbEntry::ns, ArmISA::TlbEntry::outerAttrs, ArmISA::TlbEntry::outerShareable, ArmISA::pa, ArmISA::TlbEntry::pAddr(), prrr, ArmISA::purifyTaggedAddr(), S1CTran, S1S2NsTran, scr, sctlr, Request::SECURE, Request::setAsid(), setAttr(), ArmISA::TlbEntry::setAttributes(), Request::setFlags(), Request::setPaddr(), ArmISA::TlbEntry::shareable, Request::STRICT_ORDER, MipsISA::te, trickBoxCheck(), ttbcr, Request::UNCACHEABLE, updateMiscReg(), UserMode, MipsISA::vaddr, ArmISA::ArmFault::VmsaTran, and BaseTLB::Write.
Referenced by translateAtomic(), translateComplete(), and translateFunctional().
Fault TLB::translateFunctional (RequestPtr req, ThreadContext * tc, Mode mode, TLB::ArmTranslationType tranType = NormalTran)
Do a functional lookup on the TLB (for checker cpu) that behaves like a normal lookup without modifying any page table state.
Definition at line 1144 of file tlb.cc.
References directToStage2, FullSystem, stage2Tlb, translateFs(), translateFunctional(), translateSe(), and updateMiscReg().
bool TLB::translateFunctional (ThreadContext * tc, Addr vaddr, Addr & paddr)
Do a functional lookup on the TLB (for debugging) and don't modify any internal state.
Parameters:
tc thread context to get the context id from
vaddr virtual address to translate
pa returned physical address
Returns:
if the translation was successful
Definition at line 111 of file tlb.cc.
References aarch64, aarch64EL, asid, directToStage2, ArmISA::e, ArmISA::EL1, isHyp, isSecure, lookup(), ArmISA::TlbEntry::pAddr(), stage2Tlb, translateFunctional(), updateMiscReg(), and vmid.
Referenced by ArmISA::Stage2MMU::readDataUntimed(), translateFunctional(), and try_translate().
Fault TLB::translateSe (RequestPtr req, ThreadContext * tc, Mode mode, Translation * translation, bool & delay, bool timing)
Definition at line 543 of file tlb.cc.
References aarch64, aarch64EL, ArmISA::ArmFault::AlignmentFault, AlignmentMask, AllowUnaligned, BaseTLB::Execute, Request::getFlags(), ThreadContext::getProcessPtr(), Request::getVaddr(), isStage2, ArmISA::mask, MustBeOne, MipsISA::p, Process::pTable, ArmISA::purifyTaggedAddr(), sctlr, Request::setPaddr(), PageTableBase::translate(), ttbcr, updateMiscReg(), MipsISA::vaddr, ArmISA::ArmFault::VmsaTran, and BaseTLB::Write.
Referenced by translateAtomic(), translateComplete(), and translateFunctional().
Fault TLB::translateTiming (RequestPtr req, ThreadContext * tc, Translation * translation, Mode mode, TLB::ArmTranslationType tranType = NormalTran)
Definition at line 1165 of file tlb.cc.
References directToStage2, isStage2, stage2Tlb, translateComplete(), translateTiming(), and updateMiscReg().
Referenced by ArmISA::TableWalker::doL1DescriptorWrapper(), ArmISA::TableWalker::doL2DescriptorWrapper(), ArmISA::TableWalker::doLongDescriptorWrapper(), ArmISA::TableWalker::processWalkWrapper(), ArmISA::Stage2MMU::Stage2Translation::translateTiming(), and translateTiming().
Fault TLB::trickBoxCheck (RequestPtr req, Mode mode, TlbEntry::DomainType domain)
Definition at line 583 of file tlb.cc.
Referenced by translateFs().
void ArmISA::TLB::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
void TLB::updateMiscReg (ThreadContext * tc, ArmTranslationType tranType = NormalTran) [protected]
Definition at line 1215 of file tlb.cc.
References aarch64, aarch64EL, asid, bits(), cpsr, curTranType, dacr, directToStage2, DPRINTF, ArmISA::EL0, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmISA::flattenMiscRegNsBanked(), haveLargeAsid64, haveLPAE, haveVirtualization, hcr, HypMode, ArmISA::inSecureState(), isHyp, isPriv, isSecure, isStage2, ArmISA::MISCREG_CONTEXTIDR, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_DACR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_HSCTLR, ArmISA::MISCREG_NMRR, ArmISA::MISCREG_PRRR, ArmISA::MISCREG_SCR, ArmISA::MISCREG_SCR_EL3, ArmISA::MISCREG_SCTLR, ArmISA::MISCREG_SCTLR_EL1, ArmISA::MISCREG_SCTLR_EL2, ArmISA::MISCREG_SCTLR_EL3, ArmISA::MISCREG_TCR_EL1, ArmISA::MISCREG_TCR_EL2, ArmISA::MISCREG_TCR_EL3, ArmISA::MISCREG_TTBCR, ArmISA::MISCREG_TTBR0, ArmISA::MISCREG_TTBR0_EL1, ArmISA::MISCREG_TTBR1, ArmISA::MISCREG_TTBR1_EL1, ArmISA::MISCREG_VTTBR, miscRegValid, ArmISA::MODE_HYP, ArmISA::MODE_USER, nmrr, prrr, ThreadContext::readMiscReg(), S1CTran, S1S2NsTran, scr, sctlr, stage2Req, ttbcr, and vmid.
Referenced by checkPermissions64(), translateAtomic(), translateFs(), translateFunctional(), translateSe(), and translateTiming().
static bool ArmISA::TLB::validVirtualAddress (Addr vaddr) [static]
Fault TLB::walkTrickBoxCheck (Addr pa, bool is_secure, Addr va, Addr sz, bool is_exec, bool is_write, TlbEntry::DomainType domain, LookupLevel lookup_level)
Definition at line 589 of file tlb.cc.
Referenced by ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doLongDescriptor(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), and ArmISA::TableWalker::processWalkLPAE().
Member Data Documentation
uint64_t ArmISA::TLB::_attr [protected]
Definition at line 100 of file tlb.hh.
Referenced by getAttr(), setAttr(), and takeOverFrom().
bool ArmISA::TLB::aarch64 [protected]
Definition at line 315 of file tlb.hh.
Referenced by checkPermissions64(), getResultTe(), getTE(), translateFs(), translateFunctional(), translateSe(), and updateMiscReg().
ExceptionLevel ArmISA::TLB::aarch64EL [protected]
Definition at line 316 of file tlb.hh.
Referenced by checkPermissions64(), getTE(), translateFs(), translateFunctional(), translateSe(), and updateMiscReg().
Stats::Formula ArmISA::TLB::accesses [protected]
Definition at line 131 of file tlb.hh.
Referenced by regStats().
Stats::Scalar ArmISA::TLB::alignFaults [mutable, protected]
Definition at line 121 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), regStats(), and translateFs().
uint16_t ArmISA::TLB::asid [protected]
Definition at line 323 of file tlb.hh.
Referenced by getTE(), insert(), translateFs(), translateFunctional(), and updateMiscReg().
CPSR ArmISA::TLB::cpsr [protected]
Definition at line 314 of file tlb.hh.
Referenced by translateFs(), and updateMiscReg().
ArmTranslationType ArmISA::TLB::curTranType [protected]
Definition at line 330 of file tlb.hh.
Referenced by checkPermissions64(), getResultTe(), and updateMiscReg().
uint32_t ArmISA::TLB::dacr [protected]
Definition at line 328 of file tlb.hh.
Referenced by checkPermissions(), and updateMiscReg().
bool ArmISA::TLB::directToStage2 [protected]
Definition at line 101 of file tlb.hh.
Referenced by takeOverFrom(), translateAtomic(), translateFunctional(), translateTiming(), and updateMiscReg().
Stats::Scalar ArmISA::TLB::domainFaults [mutable, protected]
Definition at line 123 of file tlb.hh.
Referenced by checkPermissions(), and regStats().
Stats::Scalar ArmISA::TLB::flushedEntries [mutable, protected]
Definition at line 120 of file tlb.hh.
Referenced by _flushMva(), flushAllNs(), flushAllSecurity(), flushAsid(), and regStats().
Stats::Scalar ArmISA::TLB::flushTlb [mutable, protected]
Definition at line 116 of file tlb.hh.
Referenced by flushAllNs(), flushAllSecurity(), and regStats().
Stats::Scalar ArmISA::TLB::flushTlbAsid [mutable, protected]
Definition at line 119 of file tlb.hh.
Referenced by flushAsid(), and regStats().
Stats::Scalar ArmISA::TLB::flushTlbMva [mutable, protected]
Definition at line 117 of file tlb.hh.
Referenced by flushMva(), and regStats().
Stats::Scalar ArmISA::TLB::flushTlbMvaAsid [mutable, protected]
Definition at line 118 of file tlb.hh.
Referenced by flushMvaAsid(), and regStats().
bool ArmISA::TLB::haveLargeAsid64 [protected]
Definition at line 335 of file tlb.hh.
Referenced by TLB(), and updateMiscReg().
bool ArmISA::TLB::haveLPAE [protected]
Definition at line 333 of file tlb.hh.
Referenced by takeOverFrom(), TLB(), translateFs(), and updateMiscReg().
bool ArmISA::TLB::haveVirtualization [protected]
Definition at line 334 of file tlb.hh.
Referenced by TLB(), and updateMiscReg().
HCR ArmISA::TLB::hcr [protected]
Definition at line 327 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), translateFs(), and updateMiscReg().
Stats::Formula ArmISA::TLB::hits [protected]
Definition at line 129 of file tlb.hh.
Referenced by regStats().
Stats::Scalar ArmISA::TLB::inserts [mutable, protected]
Definition at line 115 of file tlb.hh.
Referenced by insert().
Stats::Formula ArmISA::TLB::instAccesses [protected]
Definition at line 128 of file tlb.hh.
Referenced by regStats().
Stats::Scalar ArmISA::TLB::instHits [mutable, protected]
Definition at line 109 of file tlb.hh.
Referenced by getTE(), and regStats().
Stats::Scalar ArmISA::TLB::instMisses [mutable, protected]
Definition at line 110 of file tlb.hh.
Referenced by getTE(), and regStats().
bool ArmISA::TLB::isHyp [protected]
Definition at line 321 of file tlb.hh.
Referenced by flushAllSecurity(), getTE(), insert(), translateFs(), translateFunctional(), and updateMiscReg().
bool ArmISA::TLB::isPriv [protected]
Definition at line 319 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), translateFs(), and updateMiscReg().
bool ArmISA::TLB::isSecure [protected]
Definition at line 320 of file tlb.hh.
Referenced by checkPermissions(), getResultTe(), translateFs(), translateFunctional(), and updateMiscReg().
bool ArmISA::TLB::isStage2 [protected]
Definition at line 98 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), flushAllNs(), flushAllSecurity(), getResultTe(), getTE(), init(), takeOverFrom(), translateFs(), translateSe(), translateTiming(), and updateMiscReg().
bool ArmISA::TLB::miscRegValid [protected]
Definition at line 329 of file tlb.hh.
Referenced by drainResume(), invalidateMiscReg(), and updateMiscReg().
Stats::Formula ArmISA::TLB::misses [protected]
Definition at line 130 of file tlb.hh.
Referenced by regStats().
NMRR ArmISA::TLB::nmrr [protected]
Definition at line 326 of file tlb.hh.
Referenced by translateFs(), and updateMiscReg().
Stats::Scalar ArmISA::TLB::permsFaults [mutable, protected]
Definition at line 124 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), and regStats().
ProbePoints::PMUUPtr ArmISA::TLB::ppRefills [protected]
PMU probe for TLB refills.
Definition at line 134 of file tlb.hh.
Referenced by insert(), and regProbePoints().
Stats::Scalar ArmISA::TLB::prefetchFaults [mutable, protected]
Definition at line 122 of file tlb.hh.
Referenced by getTE(), and regStats().
PRRR ArmISA::TLB::prrr [protected]
Definition at line 325 of file tlb.hh.
Referenced by translateFs(), and updateMiscReg().
int ArmISA::TLB::rangeMRU [protected]
Definition at line 136 of file tlb.hh.
Referenced by lookup().
Stats::Formula ArmISA::TLB::readAccesses [protected]
Definition at line 126 of file tlb.hh.
Referenced by regStats().
Stats::Scalar ArmISA::TLB::readHits [mutable, protected]
Definition at line 111 of file tlb.hh.
Referenced by getTE(), and regStats().
Stats::Scalar ArmISA::TLB::readMisses [mutable, protected]
Definition at line 112 of file tlb.hh.
Referenced by getTE(), and regStats().
SCR ArmISA::TLB::scr [protected]
Definition at line 318 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), translateFs(), and updateMiscReg().
SCTLR ArmISA::TLB::sctlr [protected]
Definition at line 317 of file tlb.hh.
Referenced by checkPermissions(), checkPermissions64(), translateFs(), translateSe(), and updateMiscReg().
int ArmISA::TLB::size [protected]
Definition at line 97 of file tlb.hh.
Referenced by flushAllNs(), flushAllSecurity(), flushAsid(), getsize(), insert(), lookup(), and printTlb().
Stage2MMU* ArmISA::TLB::stage2Mmu [protected]
Definition at line 106 of file tlb.hh.
Referenced by getMasterPort(), init(), and setMMU().
bool ArmISA::TLB::stage2Req [protected]
Definition at line 99 of file tlb.hh.
Referenced by getResultTe(), takeOverFrom(), translateComplete(), and updateMiscReg().
TLB* ArmISA::TLB::stage2Tlb [protected]
Definition at line 105 of file tlb.hh.
Referenced by flushAllNs(), flushAllSecurity(), getResultTe(), init(), takeOverFrom(), translateAtomic(), translateFunctional(), and translateTiming().
TlbEntry* ArmISA::TLB::table [protected]
Definition at line 96 of file tlb.hh.
Referenced by flushAllNs(), flushAllSecurity(), flushAsid(), insert(), lookup(), printTlb(), and ~TLB().
TableWalker* ArmISA::TLB::tableWalker [protected]
Definition at line 104 of file tlb.hh.
Referenced by getTableWalker(), getTE(), setMMU(), and TLB().
TTBCR ArmISA::TLB::ttbcr [protected]
Definition at line 322 of file tlb.hh.
Referenced by checkPermissions64(), getTE(), translateFs(), translateSe(), and updateMiscReg().
uint8_t ArmISA::TLB::vmid [protected]
Definition at line 324 of file tlb.hh.
Referenced by _flushMva(), flushAllSecurity(), flushAsid(), getTE(), insert(), translateFunctional(), and updateMiscReg().
Stats::Formula ArmISA::TLB::writeAccesses [protected]
Definition at line 127 of file tlb.hh.
Referenced by regStats().
Stats::Scalar ArmISA::TLB::writeHits [mutable, protected]
Definition at line 113 of file tlb.hh.
Referenced by getTE(), and regStats().
Stats::Scalar ArmISA::TLB::writeMisses [mutable, protected]
Definition at line 114 of file tlb.hh.
Referenced by getTE(), and regStats().
The documentation for this class was generated from the following files:
arch/arm/tlb.hh
arch/arm/tlb.cc