gem5: RubyPort::PioMasterPort Class Reference
RubyPort::PioMasterPort Class Reference
#include <RubyPort.hh>
Public Member Functions
PioMasterPort (const std::string &_name, RubyPort *_port)
Protected Member Functions
bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Private Attributes
ReqPacketQueue reqQueue
Packet queue used to store outgoing requests.
SnoopRespPacketQueue snoopRespQueue
Packet queue used to store outgoing snoop responses.
Detailed Description
Definition at line 102 of file RubyPort.hh.
Constructor & Destructor Documentation
RubyPort::PioMasterPort::PioMasterPort (const std::string & _name, RubyPort * _port)
Definition at line 137 of file RubyPort.cc.
References DPRINTF.
Member Function Documentation
void RubyPort::PioMasterPort::recvRangeChange () [protected, virtual]
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 563 of file RubyPort.cc.
References FullSystem, RubyPort::gotAddrRanges, Port::owner, RubyPort::pioSlavePort, MipsISA::r, and SlavePort::sendRangeChange().
bool RubyPort::PioMasterPort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 170 of file RubyPort.cc.
References ClockedObject::clockPeriod(), curTick(), DPRINTF, g_system_ptr, Packet::getAddr(), Port::owner, RubyPort::pioSlavePort, and QueuedSlavePort::schedTimingResp().
Member Data Documentation
ReqPacketQueue RubyPort::PioMasterPort::reqQueue [private]
Packet queue used to store outgoing requests.
Reimplemented from QueuedMasterPort.
Definition at line 105 of file RubyPort.hh.
SnoopRespPacketQueue RubyPort::PioMasterPort::snoopRespQueue [private]
Packet queue used to store outgoing snoop responses.
Reimplemented from QueuedMasterPort.
Definition at line 106 of file RubyPort.hh.
The documentation for this class was generated from the following files:
mem/ruby/system/RubyPort.hh
mem/ruby/system/RubyPort.cc