gem5: X86ISA::InitInterrupt Class Reference
X86ISA::InitInterrupt Class Reference
#include <faults.hh>
Public Member Functions
InitInterrupt (uint8_t _vector)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Detailed Description
Definition at line 397 of file faults.hh.
Constructor & Destructor Documentation
X86ISA::InitInterrupt::InitInterrupt (uint8_t _vector) [inline]
Definition at line 400 of file faults.hh.
Member Function Documentation
void X86ISA::InitInterrupt::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from X86ISA::X86FaultBase.
Definition at line 173 of file faults.cc.
References DPRINTF, X86ISA::index, X86ISA::MISCREG_CR0, X86ISA::MISCREG_CR2, X86ISA::MISCREG_CR3, X86ISA::MISCREG_CR4, X86ISA::MISCREG_CS, X86ISA::MISCREG_CS_ATTR, X86ISA::MISCREG_CS_BASE, X86ISA::MISCREG_CS_EFF_BASE, X86ISA::MISCREG_CS_LIMIT, X86ISA::MISCREG_DR0, X86ISA::MISCREG_DR1, X86ISA::MISCREG_DR2, X86ISA::MISCREG_DR3, X86ISA::MISCREG_DR6, X86ISA::MISCREG_DR7, X86ISA::MISCREG_EFER, X86ISA::MISCREG_FTW, X86ISA::MISCREG_IDTR_BASE, X86ISA::MISCREG_IDTR_LIMIT, X86ISA::MISCREG_M5_REG, X86ISA::MISCREG_MXCSR, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_EFF_BASE(), X86ISA::MISCREG_SEG_LIMIT(), X86ISA::MISCREG_SEG_SEL(), X86ISA::MISCREG_TR, X86ISA::MISCREG_TR_ATTR, X86ISA::MISCREG_TR_BASE, X86ISA::MISCREG_TR_LIMIT, X86ISA::MISCREG_TSG_BASE, X86ISA::MISCREG_TSG_LIMIT, X86ISA::MISCREG_TSL, X86ISA::MISCREG_TSL_ATTR, X86ISA::MISCREG_TSL_BASE, X86ISA::MISCREG_TSL_LIMIT, ArmISA::NUM_INTREGS, X86ISA::NUM_SEGMENTREGS, X86ISA::pc, ThreadContext::pcState(), ThreadContext::readMiscReg(), romMicroPC(), X86ISA::seg, ThreadContext::setIntReg(), and ThreadContext::setMiscReg().
The documentation for this class was generated from the following files:
arch/x86/faults.hh
arch/x86/faults.cc