gem5: ArmISA::MicroMemOp Class Reference
ArmISA::MicroMemOp Class Reference
Memory microops which use IntReg + Imm addressing.
#include <macromem.hh>
Protected Member Functions
MicroMemOp (const char *mnem, ExtMachInst machInst, OpClass __opClass, RegIndex _ura, RegIndex _urb, bool _up, uint8_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
bool up
unsigned memAccessFlags
Detailed Description
Memory microops which use IntReg + Imm addressing.
Definition at line 382 of file macromem.hh.
Constructor & Destructor Documentation
ArmISA::MicroMemOp::MicroMemOp (const char * mnem, ExtMachInst machInst, OpClass __opClass, RegIndex _ura, RegIndex _urb, bool _up, uint8_t _imm) [inline, protected]
Definition at line 388 of file macromem.hh.
Member Function Documentation
std::string ArmISA::MicroMemOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::MicroIntImmOp.
Definition at line 1595 of file macromem.cc.
References ccprintf(), ArmISA::FP_Reg_Base, ArmISA::MicroIntImmOp::imm, StaticInst::isFloating(), ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), ArmISA::ss, ArmISA::MicroIntImmOp::ura, and ArmISA::MicroIntImmOp::urb.
Member Data Documentation
unsigned ArmISA::MicroMemOp::memAccessFlags [protected]
Definition at line 386 of file macromem.hh.
bool ArmISA::MicroMemOp::up [protected]
Definition at line 385 of file macromem.hh.
The documentation for this class was generated from the following files:
arch/arm/insts/macromem.hh
arch/arm/insts/macromem.cc