gem5: TrafficGen Class Reference
TrafficGen Class Reference
The traffic generator is a master module that generates stimuli for the memory system, based on a collection of simple generator behaviours that are either probabilistic or based on traces.
#include <traffic_gen.hh>
Classes
class TrafficGenPort
Master port specialisation for the traffic generator.
struct Transition
Struct to represent a probabilistic transition during parsing.
Public Member Functions
TrafficGen (const TrafficGenParams *p)
~TrafficGen ()
virtual BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a master port with a given name and index.
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
void regStats ()
Register statistics.
Private Member Functions
void transition ()
Determine next state and perform the transition.
void enterState (uint32_t newState)
Enter a new state.
void parseConfig ()
Parse the config file and build the state map and transition matrix.
void update ()
Schedules event for next update and executes an update on the state graph, either performing a state transition or executing the current state, depending on the current time.
void recvReqRetry ()
Receive a retry from the neighbouring port and attempt to resend the waiting packet.
Private Attributes
System * system
The system used to determine which mode we are currently operating in.
MasterID masterID
MasterID used in generated requests.
const std::string configFile
The config file to parse.
const bool elasticReq
Determine whether to add elasticity in the request injection, thus responding to backpressure by slowing things down.
Tick nextTransitionTick
Time of next transition.
Tick nextPacketTick
Time of the next packet.
std::vector< std::vector
< double > > transitionMatrix
State transition matrix.
uint32_t currState
Index of the current state.
m5::hash_map< uint32_t, BaseGen * > states
Map of generator states.
TrafficGenPort port
The instance of master port used by the traffic generator.
PacketPtr retryPkt
Packet waiting to be sent.
Tick retryPktTick
Tick when the stalled packet was meant to be sent.
EventWrapper< TrafficGen,&TrafficGen::update > updateEvent
Event for scheduling updates.
DrainManager * drainManager
Manager to signal when drained.
Stats::Scalar numPackets
Count the number of generated packets.
Stats::Scalar numRetries
Count the number of retries.
Stats::Scalar retryTicks
Count the time incurred from back-pressure.
Detailed Description
The traffic generator is a master module that generates stimuli for the memory system, based on a collection of simple generator behaviours that are either probabilistic or based on traces.
It can be used stand alone for creating test cases for interconnect and memory controllers, or function as a black box replacement for system components that are not yet modelled in detail, e.g. a video engine or baseband subsystem.
Definition at line 60 of file traffic_gen.hh.
Constructor & Destructor Documentation
TrafficGen::TrafficGen (const TrafficGenParams * p)
Definition at line 54 of file traffic_gen.cc.
TrafficGen::~TrafficGen () [inline]
Definition at line 195 of file traffic_gen.hh.
Member Function Documentation
unsigned int TrafficGen::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 122 of file traffic_gen.cc.
References EventManager::deschedule(), drainManager, MaxTick, nextPacketTick, nextTransitionTick, retryPkt, Event::scheduled(), and updateEvent.
void TrafficGen::enterState (uint32_t newState) [private]
Enter a new state.
Parameters:
newState identifier of state to enter
Definition at line 461 of file traffic_gen.cc.
References currState, curTick(), DPRINTF, nextTransitionTick, and states.
Referenced by init(), and transition().
virtual BaseMasterPort& TrafficGen::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a master port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
void TrafficGen::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 88 of file traffic_gen.cc.
References currState, DPRINTF, enterState(), fatal, BaseMasterPort::isConnected(), System::isTimingMode(), SimObject::name(), parseConfig(), port, and system.
void TrafficGen::initState () [virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from SimObject.
Definition at line 108 of file traffic_gen.cc.
References currState, DPRINTF, elasticReq, System::isTimingMode(), nextPacketTick, nextTransitionTick, EventManager::schedule(), states, system, and updateEvent.
void TrafficGen::parseConfig () [private]
Parse the config file and build the state map and transition matrix.
Definition at line 220 of file traffic_gen.cc.
References System::cacheLineSize(), configFile, currState, divCeil(), DPRINTF, fatal, TrafficGen::Transition::from, ArmISA::i, SparcISA::id, MipsISA::is, ArmISA::j, masterID, ArmISA::mode, SimObject::name(), TrafficGen::Transition::p, states, Stats::sum(), system, ArmISA::t, TrafficGen::Transition::to, transition(), transitionMatrix, and warn.
Referenced by init().
void TrafficGen::recvReqRetry () [private]
Receive a retry from the neighbouring port and attempt to resend the waiting packet.
Definition at line 474 of file traffic_gen.cc.
References currState, curTick(), DPRINTF, drainManager, elasticReq, MaxTick, nextPacketTick, nextTransitionTick, numRetries, port, retryPkt, retryPktTick, retryTicks, EventManager::schedule(), MasterPort::sendTimingReq(), DrainManager::signalDrainDone(), states, and updateEvent.
Referenced by TrafficGen::TrafficGenPort::recvReqRetry().
void TrafficGen::regStats () [virtual]
Register statistics.
Reimplemented from SimObject.
Definition at line 509 of file traffic_gen.cc.
References SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numPackets, numRetries, and retryTicks.
void TrafficGen::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
void TrafficGen::transition () [private]
Determine next state and perform the transition.
Definition at line 442 of file traffic_gen.cc.
References currState, enterState(), ArmISA::i, MipsISA::p, Random::random(), random_mt, states, and transitionMatrix.
Referenced by parseConfig(), and update().
void TrafficGen::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
void TrafficGen::update () [private]
Schedules event for next update and executes an update on the state graph, either performing a state transition or executing the current state, depending on the current time.
Definition at line 181 of file traffic_gen.cc.
References Packet::cmdString(), currState, curTick(), DPRINTF, elasticReq, Packet::getAddr(), System::isMemAddr(), nextPacketTick, nextTransitionTick, numPackets, port, retryPkt, retryPktTick, EventManager::schedule(), MasterPort::sendTimingReq(), states, system, transition(), and updateEvent.
Member Data Documentation
const std::string TrafficGen::configFile [private]
The config file to parse.
Definition at line 117 of file traffic_gen.hh.
Referenced by parseConfig().
uint32_t TrafficGen::currState [private]
Index of the current state.
Definition at line 135 of file traffic_gen.hh.
Referenced by enterState(), init(), initState(), parseConfig(), recvReqRetry(), transition(), and update().
DrainManager* TrafficGen::drainManager [private]
Manager to signal when drained.
Definition at line 180 of file traffic_gen.hh.
Referenced by drain(), and recvReqRetry().
const bool TrafficGen::elasticReq [private]
Determine whether to add elasticity in the request injection, thus responding to backpressure by slowing things down.
Definition at line 123 of file traffic_gen.hh.
Referenced by initState(), recvReqRetry(), and update().
MasterID TrafficGen::masterID [private]
MasterID used in generated requests.
Definition at line 112 of file traffic_gen.hh.
Referenced by parseConfig().
Tick TrafficGen::nextPacketTick [private]
Time of the next packet.
Definition at line 129 of file traffic_gen.hh.
Referenced by drain(), initState(), recvReqRetry(), and update().
Tick TrafficGen::nextTransitionTick [private]
Time of next transition.
Definition at line 126 of file traffic_gen.hh.
Referenced by drain(), enterState(), initState(), recvReqRetry(), and update().
Stats::Scalar TrafficGen::numPackets [private]
Count the number of generated packets.
Definition at line 183 of file traffic_gen.hh.
Referenced by regStats(), and update().
Stats::Scalar TrafficGen::numRetries [private]
Count the number of retries.
Definition at line 186 of file traffic_gen.hh.
Referenced by recvReqRetry(), and regStats().
TrafficGenPort TrafficGen::port [private]
The instance of master port used by the traffic generator.
Definition at line 168 of file traffic_gen.hh.
Referenced by init(), recvReqRetry(), and update().
PacketPtr TrafficGen::retryPkt [private]
Packet waiting to be sent.
Definition at line 171 of file traffic_gen.hh.
Referenced by drain(), recvReqRetry(), and update().
Tick TrafficGen::retryPktTick [private]
Tick when the stalled packet was meant to be sent.
Definition at line 174 of file traffic_gen.hh.
Referenced by recvReqRetry(), and update().
Stats::Scalar TrafficGen::retryTicks [private]
Count the time incurred from back-pressure.
Definition at line 189 of file traffic_gen.hh.
Referenced by recvReqRetry(), and regStats().
m5::hash_map<uint32_t, BaseGen*> TrafficGen::states [private]
Map of generator states.
Definition at line 138 of file traffic_gen.hh.
Referenced by enterState(), initState(), parseConfig(), recvReqRetry(), transition(), and update().
System* TrafficGen::system [private]
The system used to determine which mode we are currently operating in.
Definition at line 107 of file traffic_gen.hh.
Referenced by init(), initState(), parseConfig(), and update().
std::vector<std::vector<double> > TrafficGen::transitionMatrix [private]
State transition matrix.
Definition at line 132 of file traffic_gen.hh.
Referenced by parseConfig(), and transition().
EventWrapper<TrafficGen, &TrafficGen::update> TrafficGen::updateEvent [private]
Event for scheduling updates.
Definition at line 177 of file traffic_gen.hh.
Referenced by drain(), initState(), recvReqRetry(), and update().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/traffic_gen.hh
cpu/testers/traffic_gen/traffic_gen.cc