gem5: Stats::DataWrapVec2d< Derived, InfoProxyType > Class Template Reference
Stats::DataWrapVec2d< Derived, InfoProxyType > Class Template Reference
#include <statistics.hh>
Public Types
typedef InfoProxyType< Derived > Info
Public Member Functions
Derived & ysubnames (const char **names)
Derived & ysubname (off_type index, const std::string &subname)
std::string ysubname (off_type i) const
Detailed Description
template<class Derived, template< class > class InfoProxyType>
class Stats::DataWrapVec2d< Derived, InfoProxyType >
Definition at line 414 of file statistics.hh.
Member Typedef Documentation
template<class Derived, template< class > class InfoProxyType> typedef InfoProxyType<Derived> Stats::DataWrapVec2d< Derived, InfoProxyType >::Info
Reimplemented from Stats::DataWrapVec< Derived, InfoProxyType >.
Reimplemented in Stats::Vector2dBase< Derived, Stor >, and Stats::Vector2dBase< Vector2d, StatStor >.
Definition at line 417 of file statistics.hh.
Member Function Documentation
template<class Derived, template< class > class InfoProxyType> std::string Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubname (off_type i) const [inline]
Definition at line 448 of file statistics.hh.
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubname (off_type index, const std::string & subname) [inline]
Definition at line 436 of file statistics.hh.
Referenced by StatTest::init(), BaseXBar::regStats(), and ArmISA::TableWalker::regStats().
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubnames (const char ** names) [inline]
Warning:
This makes the assumption that if you're gonna subnames a 2d vector, you're subnaming across all y
Definition at line 424 of file statistics.hh.
Referenced by InstructionQueue< Impl >::regStats(), and DefaultCommit< Impl >::regStats().
The documentation for this class was generated from the following file:
base/statistics.hh