gem5: X86ISA::RegOp Class Reference
X86ISA::RegOp Class Reference
#include <microregop.hh>
Protected Member Functions
RegOp (ExtMachInst _machInst, const char *mnem, const char *_instMnem, uint64_t setFlags, InstRegIndex _src1, InstRegIndex _src2, InstRegIndex _dest, uint8_t _dataSize, uint16_t _ext, OpClass __opClass)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
const RegIndex src2
Detailed Description
Definition at line 79 of file microregop.hh.
Constructor & Destructor Documentation
X86ISA::RegOp::RegOp (ExtMachInst _machInst, const char * mnem, const char * _instMnem, uint64_t setFlags, InstRegIndex _src1, InstRegIndex _src2, InstRegIndex _dest, uint8_t _dataSize, uint16_t _ext, OpClass __opClass) [inline, protected]
Definition at line 85 of file microregop.hh.
Member Function Documentation
std::string X86ISA::RegOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from X86ISA::X86MicroopBase.
Definition at line 80 of file microregop.cc.
References X86ISA::RegOpBase::dataSize, X86ISA::X86MicroopBase::instMnem, StaticInst::mnemonic, X86ISA::X86StaticInst::printDestReg(), X86ISA::X86StaticInst::printMnemonic(), and X86ISA::X86StaticInst::printSrcReg().
Member Data Documentation
const RegIndex X86ISA::RegOp::src2 [protected]
Definition at line 82 of file microregop.hh.
The documentation for this class was generated from the following files:
arch/x86/insts/microregop.hh
arch/x86/insts/microregop.cc