gem5: ArmLiveProcess64 Class Reference
ArmLiveProcess64 Class Reference
#include <process.hh>
Public Member Functions
ArmISA::IntReg getSyscallArg (ThreadContext *tc, int &i, int width)
ArmISA::IntReg getSyscallArg (ThreadContext *tc, int &i)
void setSyscallArg (ThreadContext *tc, int i, ArmISA::IntReg val)
void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)
Protected Member Functions
ArmLiveProcess64 (LiveProcessParams *params, ObjectFile *objFile, ObjectFile::Arch _arch)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
Detailed Description
Definition at line 83 of file process.hh.
Constructor & Destructor Documentation
ArmLiveProcess64::ArmLiveProcess64 (LiveProcessParams * params, ObjectFile * objFile, ObjectFile::Arch _arch) [protected]
Definition at line 83 of file process.cc.
References Process::brk_point, ObjectFile::bssSize(), ObjectFile::dataBase(), ObjectFile::dataSize(), X86ISA::L, Process::mmap_end, Process::mmap_start, Process::next_thread_stack_base, AlphaISA::PageBytes, roundUp(), and Process::stack_base.
Member Function Documentation
ArmISA::IntReg ArmLiveProcess64::getSyscallArg (ThreadContext * tc, int & i) [virtual]
Implements LiveProcess.
Definition at line 410 of file process.cc.
References ArmISA::ArgumentReg0, and ThreadContext::readIntReg().
ArmISA::IntReg ArmLiveProcess64::getSyscallArg (ThreadContext * tc, int & i, int width) [virtual]
Reimplemented from LiveProcess.
Definition at line 436 of file process.cc.
void ArmLiveProcess64::initState () [protected, virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from Process.
Reimplemented in ArmFreebsdProcess64, and ArmLinuxProcess64.
Definition at line 120 of file process.cc.
References Process::contextIds, ArmISA::cpsr, System::getThreadContext(), ArmISA::i, ArmISA::INTREG_SP0, ArmISA::MISCREG_CPACR_EL1, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_FPEXC, ArmISA::MODE_EL0T, AlphaISA::PageBytes, ThreadContext::readMiscReg(), ThreadContext::setMiscReg(), Process::system, and ArmISA::tc.
void ArmLiveProcess64::setSyscallArg (ThreadContext * tc, int i, ArmISA::IntReg val)
Definition at line 450 of file process.cc.
References ArmISA::ArgumentReg0, and ThreadContext::setIntReg().
void ArmLiveProcess64::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) [virtual]
Implements LiveProcess.
Definition at line 475 of file process.cc.
References ArmISA::CCREG_C, SyscallReturn::encodedValue(), ObjectFile::FreeBSD, ObjectFile::getOpSys(), LiveProcess::objFile, AlphaISA::ReturnValueReg, ThreadContext::setCCReg(), and ThreadContext::setIntReg().
The documentation for this class was generated from the following files:
arch/arm/process.hh
arch/arm/process.cc