gem5: ArmV8KvmCPU Class Reference
ArmV8KvmCPU Class Reference
This is an implementation of a KVM-based ARMv8-compatible CPU.
#include <armv8_cpu.hh>
Classes
struct IntRegInfo
Mapping between integer registers in gem5 and KVM.
struct MiscRegInfo
Mapping between misc registers in gem5 and registers in KVM.
Public Member Functions
ArmV8KvmCPU (ArmV8KvmCPUParams *params)
virtual ~ArmV8KvmCPU ()
void dump () M5_ATTR_OVERRIDE
Dump the internal state to the terminal.
Protected Member Functions
void updateKvmState () M5_ATTR_OVERRIDE
Update the KVM state from the current thread context.
void updateThreadContext () M5_ATTR_OVERRIDE
Update the current thread context with the KVM state.
const std::vector
< ArmV8KvmCPU::MiscRegInfo > & getSysRegMap () const
Get a map between system registers in kvm and gem5 registers.
Protected Attributes
std::vector
< ArmV8KvmCPU::MiscRegInfo > sysRegMap
Cached mapping between system registers in kvm and misc regs in gem5.
Static Protected Attributes
static const std::vector
< ArmV8KvmCPU::IntRegInfo > intRegMap
Mapping between gem5 integer registers and integer registers in kvm.
static const std::vector
< ArmV8KvmCPU::MiscRegInfo > miscRegMap
Mapping between gem5 misc registers registers and registers in kvm.
Detailed Description
This is an implementation of a KVM-based ARMv8-compatible CPU.
Known limitations:
The system-register-based generic timer can only be simulated by the host kernel. Workaround: Use a memory mapped timer instead to simulate the timer in gem5.
Simulating devices (e.g., the generic timer) in the host kernel requires that the host kernel also simulates the GIC.
ID registers in the host and in gem5 must match for switching between simulated CPUs and KVM. This is particularly important for ID registers describing memory system capabilities (e.g., ASID size, physical address size).
Switching between a virtualized CPU and a simulated CPU is currently not supported if in-kernel device emulation is used. This could be worked around by adding support for switching to the gem5 (e.g., the KvmGic) side of the device models. A simpler workaround is to avoid in-kernel device models altogether.
Definition at line 80 of file armv8_cpu.hh.
Constructor & Destructor Documentation
ArmV8KvmCPU::ArmV8KvmCPU (ArmV8KvmCPUParams * params)
Definition at line 116 of file armv8_cpu.cc.
ArmV8KvmCPU::~ArmV8KvmCPU () [virtual]
Definition at line 121 of file armv8_cpu.cc.
Member Function Documentation
void ArmV8KvmCPU::dump () [virtual]
Dump the internal state to the terminal.
Reimplemented from BaseKvmCPU.
Definition at line 126 of file armv8_cpu.cc.
References ArmISA::decodeAArch64SysReg(), EXTRACT_FIELD, BaseKvmCPU::getAndFormatOneReg(), BaseArmKvmCPU::getRegList(), ArmISA::i, SparcISA::id, inform, INT_REG, intRegMap, kvmFPReg(), kvmXReg(), miscRegMap, ArmISA::miscRegName, NUM_QREGS, NUM_XREGS, X86ISA::reg, X86ISA::type, and X86ISA::val.
const std::vector< ArmV8KvmCPU::MiscRegInfo > & ArmV8KvmCPU::getSysRegMap () const [protected]
Get a map between system registers in kvm and gem5 registers.
This method returns a mapping between system registers in kvm and misc regs in gem5. The actual mapping is only created the first time the method is called and stored in a cache (ArmV8KvmCPU::sysRegMap).
Returns:
Vector of kvm<->misc reg mappings.
Definition at line 283 of file armv8_cpu.cc.
References ArmISA::decodeAArch64SysReg(), EXTRACT_FIELD, BaseArmKvmCPU::getRegList(), ArmISA::MISCREG_HYP_WR, ArmISA::MISCREG_IMPLEMENTED, ArmISA::MISCREG_MON_NS0_WR, ArmISA::MISCREG_MON_NS1_WR, ArmISA::MISCREG_PRI_NS_WR, ArmISA::MISCREG_PRI_S_WR, ArmISA::MISCREG_USR_NS_WR, ArmISA::MISCREG_USR_S_WR, ArmISA::MISCREG_WARN_NOT_FAIL, ArmISA::miscRegInfo, ArmISA::miscRegName, X86ISA::reg, sysRegMap, and X86ISA::type.
Referenced by updateKvmState(), and updateThreadContext().
void ArmV8KvmCPU::updateKvmState () [protected, virtual]
Update the KVM state from the current thread context.
The base CPU calls this method before starting the guest CPU when the contextDirty flag is set. The architecture dependent CPU implementation is expected to update all guest state (registers, special registers, and FPU state).
Implements BaseKvmCPU.
Definition at line 188 of file armv8_cpu.cc.
References KvmFPReg::data, DPRINTF, FP_REGS_PER_VFP_REG, BaseKvmCPU::getAndFormatOneReg(), getSysRegMap(), KvmFPReg::i, ArmISA::i, ThreadContext::instAddr(), INT_REG, ArmISA::INTREG_X0, intRegMap, ArmISA::j, kvmFPReg(), kvmXReg(), miscRegMap, NUM_QREGS, NUM_XREGS, ThreadContext::readFloatRegBits(), ThreadContext::readIntReg(), ThreadContext::readMiscReg(), X86ISA::reg, KvmFPReg::s, BaseKvmCPU::setOneReg(), and BaseKvmCPU::tc.
void ArmV8KvmCPU::updateThreadContext () [protected, virtual]
Update the current thread context with the KVM state.
The base CPU after the guest updates any of the KVM state. In practice, this happens after kvmRun is called. The architecture dependent code is expected to read the state of the guest CPU and update gem5's thread state.
Implements BaseKvmCPU.
Definition at line 230 of file armv8_cpu.cc.
References ArmISA::cpsr, KvmFPReg::data, DPRINTF, FP_REGS_PER_VFP_REG, BaseKvmCPU::getAndFormatOneReg(), BaseKvmCPU::getOneReg(), BaseKvmCPU::getOneRegU64(), getSysRegMap(), KvmFPReg::i, ArmISA::i, ArmISA::inAArch64(), INT_REG, ArmISA::INTREG_X0, intRegMap, ArmISA::j, kvmFPReg(), kvmXReg(), ArmISA::MISCREG_CPSR, miscRegMap, NUM_QREGS, NUM_XREGS, MipsISA::pc, ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), X86ISA::reg, KvmFPReg::s, ThreadContext::setFloatRegBits(), ThreadContext::setIntReg(), ThreadContext::setMiscRegNoEffect(), and BaseKvmCPU::tc.
Member Data Documentation
const std::vector< ArmV8KvmCPU::IntRegInfo > ArmV8KvmCPU::intRegMap [static, protected]
Initial value:
 {
    { INT_REG(regs.sp), INTREG_SP0, "SP(EL0)" },
    { INT_REG(sp_el1), INTREG_SP1, "SP(EL1)" },
}
Mapping between gem5 integer registers and integer registers in kvm.
Definition at line 132 of file armv8_cpu.hh.
Referenced by dump(), updateKvmState(), and updateThreadContext().
const std::vector< ArmV8KvmCPU::MiscRegInfo > ArmV8KvmCPU::miscRegMap [static, protected]
Initial value:
 {
    MiscRegInfo(INT_REG(regs.pstate), MISCREG_CPSR, "PSTATE"),
    MiscRegInfo(INT_REG(elr_el1), MISCREG_ELR_EL1, "ELR(EL1)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_EL1]), MISCREG_SPSR_EL1, "SPSR(EL1)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_ABT]), MISCREG_SPSR_ABT, "SPSR(ABT)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_UND]), MISCREG_SPSR_UND, "SPSR(UND)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_IRQ]), MISCREG_SPSR_IRQ, "SPSR(IRQ)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_FIQ]), MISCREG_SPSR_FIQ, "SPSR(FIQ)"),
    MiscRegInfo(INT_REG(fp_regs.fpsr), MISCREG_FPSR, "FPSR"),
    MiscRegInfo(INT_REG(fp_regs.fpcr), MISCREG_FPCR, "FPCR"),
}
Mapping between gem5 misc registers registers and registers in kvm.
Definition at line 134 of file armv8_cpu.hh.
Referenced by dump(), updateKvmState(), and updateThreadContext().
std::vector<ArmV8KvmCPU::MiscRegInfo> ArmV8KvmCPU::sysRegMap [mutable, protected]
Cached mapping between system registers in kvm and misc regs in gem5.
Definition at line 137 of file armv8_cpu.hh.
Referenced by getSysRegMap().
The documentation for this class was generated from the following files:
arch/arm/kvm/armv8_cpu.hh
arch/arm/kvm/armv8_cpu.cc