gem5: FullO3CPU< Impl >::IcachePort Class Reference
FullO3CPU< Impl >::IcachePort Class Reference
IcachePort class for instruction fetch.
Public Member Functions
IcachePort (DefaultFetch< Impl > *_fetch, FullO3CPU< Impl > *_cpu)
Default constructor.
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
Timing version of receive.
virtual void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the slave port.
virtual void recvReqRetry ()
Handles doing a retry of a failed fetch.
Protected Attributes
DefaultFetch< Impl > * fetch
Pointer to fetch.
Detailed Description
template<class Impl>
class FullO3CPU< Impl >::IcachePort
IcachePort class for instruction fetch.
Definition at line 133 of file cpu.hh.
Constructor & Destructor Documentation
template<class Impl> FullO3CPU< Impl >::IcachePort::IcachePort (DefaultFetch< Impl > * _fetch, FullO3CPU< Impl > * _cpu) [inline]
Default constructor.
Definition at line 141 of file cpu.hh.
Member Function Documentation
template<class Impl > void FullO3CPU< Impl >::IcachePort::recvReqRetry () [inline, protected, virtual]
Handles doing a retry of a failed fetch.
Implements MasterPort.
Definition at line 105 of file cpu.cc.
References FullO3CPU< Impl >::IcachePort::fetch.
template<class Impl > bool FullO3CPU< Impl >::IcachePort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
Timing version of receive.
Handles setting fetch to the proper status to start fetching.
Implements MasterPort.
Definition at line 92 of file cpu.cc.
References DPRINTF, FullO3CPU< Impl >::IcachePort::fetch, Request::isUncacheable(), Packet::memInhibitAsserted(), Packet::req, and Packet::sharedAsserted().
template<class Impl> virtual void FullO3CPU< Impl >::IcachePort::recvTimingSnoopReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop request from the slave port.
Reimplemented from MasterPort.
Definition at line 150 of file cpu.hh.
Member Data Documentation
template<class Impl> DefaultFetch<Impl>* FullO3CPU< Impl >::IcachePort::fetch [protected]
Pointer to fetch.
Definition at line 137 of file cpu.hh.
Referenced by FullO3CPU< Impl >::IcachePort::recvReqRetry(), and FullO3CPU< Impl >::IcachePort::recvTimingResp().
The documentation for this class was generated from the following files:
cpu/o3/cpu.hh
cpu/o3/cpu.cc