gem5: Stats::DistProxy< Stat > Class Template Reference
Stats::DistProxy< Stat > Class Template Reference
#include <statistics.hh>
Public Member Functions
DistProxy (Stat &s, off_type i)
DistProxy (const DistProxy &sp)
const DistProxy & operator= (const DistProxy &sp)
template<typename U >
void sample (const U &v, int n=1)
size_type size () const
bool zero () const
void reset ()
Proxy has no state.
Protected Member Functions
Stat::Storage * data ()
const Stat::Storage * data () const
Private Attributes
Stat & stat
off_type index
Detailed Description
template<class Stat>
class Stats::DistProxy< Stat >
Definition at line 1990 of file statistics.hh.
Constructor & Destructor Documentation
template<class Stat > Stats::DistProxy< Stat >::DistProxy (Stat & s, off_type i) [inline]
Definition at line 2001 of file statistics.hh.
template<class Stat > Stats::DistProxy< Stat >::DistProxy (const DistProxy< Stat > & sp) [inline]
Definition at line 2005 of file statistics.hh.
Member Function Documentation
template<class Stat > const Stat::Storage* Stats::DistProxy< Stat >::data () const [inline, protected]
Definition at line 1998 of file statistics.hh.
References Stats::DistProxy< Stat >::index, and Stats::DistProxy< Stat >::stat.
template<class Stat > Stat::Storage* Stats::DistProxy< Stat >::data () [inline, protected]
Definition at line 1997 of file statistics.hh.
References Stats::DistProxy< Stat >::index, and Stats::DistProxy< Stat >::stat.
Referenced by Stats::DistProxy< Stat >::sample(), and Stats::DistProxy< Stat >::zero().
template<class Stat > const DistProxy& Stats::DistProxy< Stat >::operator= (const DistProxy< Stat > & sp) [inline]
Definition at line 2010 of file statistics.hh.
References Stats::DistProxy< Stat >::index, and Stats::DistProxy< Stat >::stat.
template<class Stat > void Stats::DistProxy< Stat >::reset () [inline]
Proxy has no state.
Nothing to reset.
Definition at line 2040 of file statistics.hh.
template<class Stat > template<typename U > void Stats::DistProxy< Stat >::sample (const U & v, int n = 1) [inline]
Definition at line 2020 of file statistics.hh.
References Stats::DistProxy< Stat >::data(), and ArmISA::n.
template<class Stat > size_type Stats::DistProxy< Stat >::size () const [inline]
Definition at line 2026 of file statistics.hh.
template<class Stat > bool Stats::DistProxy< Stat >::zero () const [inline]
Definition at line 2032 of file statistics.hh.
References Stats::DistProxy< Stat >::data().
Member Data Documentation
template<class Stat > off_type Stats::DistProxy< Stat >::index [private]
Definition at line 1994 of file statistics.hh.
Referenced by Stats::DistProxy< Stat >::data(), and Stats::DistProxy< Stat >::operator=().
template<class Stat > Stat& Stats::DistProxy< Stat >::stat [private]
Definition at line 1993 of file statistics.hh.
Referenced by Stats::DistProxy< Stat >::data(), and Stats::DistProxy< Stat >::operator=().
The documentation for this class was generated from the following file:
base/statistics.hh