gem5: LiveProcess Class Reference
LiveProcess Class Reference
#include <process.hh>
Public Types
enum AuxiliaryVectorType {
M5_AT_NULL = 0, M5_AT_IGNORE = 1, M5_AT_EXECFD = 2, M5_AT_PHDR = 3,
M5_AT_PHENT = 4, M5_AT_PHNUM = 5, M5_AT_PAGESZ = 6, M5_AT_BASE = 7,
M5_AT_FLAGS = 8, M5_AT_ENTRY = 9, M5_AT_NOTELF = 10, M5_AT_UID = 11,
M5_AT_EUID = 12, M5_AT_GID = 13, M5_AT_EGID = 14, M5_AT_PLATFORM = 15,
M5_AT_HWCAP = 16, M5_AT_CLKTCK = 17, M5_AT_SECURE = 23, M5_BASE_PLATFORM = 24,
M5_AT_RANDOM = 25, M5_AT_EXECFN = 31, M5_AT_VECTOR_SIZE = 44
}
Public Member Functions
uint64_t uid ()
uint64_t euid ()
uint64_t gid ()
uint64_t egid ()
uint64_t pid ()
uint64_t ppid ()
virtual const char * progName () const
std::string fullPath (const std::string &filename)
std::string getcwd () const
virtual void syscall (int64_t callnum, ThreadContext *tc)
virtual TheISA::IntReg getSyscallArg (ThreadContext *tc, int &i)=0
virtual TheISA::IntReg getSyscallArg (ThreadContext *tc, int &i, int width)
virtual void setSyscallArg (ThreadContext *tc, int i, TheISA::IntReg val)=0
virtual void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)=0
virtual SyscallDesc * getDesc (int callnum)=0
EmulatedDriver * findDriver (std::string filename)
Find an emulated device driver.
Static Public Member Functions
static LiveProcess * create (LiveProcessParams *params)
Protected Member Functions
LiveProcess (LiveProcessParams *params, ObjectFile *objFile)
Protected Attributes
ObjectFile * objFile
std::vector< std::string > argv
std::vector< std::string > envp
std::string cwd
uint64_t __uid
uint64_t __euid
uint64_t __gid
uint64_t __egid
uint64_t __pid
uint64_t __ppid
std::vector< EmulatedDriver * > drivers
Detailed Description
Definition at line 244 of file process.hh.
Member Enumeration Documentation
enum LiveProcess::AuxiliaryVectorType
Enumerator:
M5_AT_NULL
M5_AT_IGNORE
M5_AT_EXECFD
M5_AT_PHDR
M5_AT_PHENT
M5_AT_PHNUM
M5_AT_PAGESZ
M5_AT_BASE
M5_AT_FLAGS
M5_AT_ENTRY
M5_AT_NOTELF
M5_AT_UID
M5_AT_EUID
M5_AT_GID
M5_AT_EGID
M5_AT_PLATFORM
M5_AT_HWCAP
M5_AT_CLKTCK
M5_AT_SECURE
M5_BASE_PLATFORM
M5_AT_RANDOM
M5_AT_EXECFN
M5_AT_VECTOR_SIZE
Definition at line 269 of file process.hh.
Constructor & Destructor Documentation
LiveProcess::LiveProcess (LiveProcessParams * params, ObjectFile * objFile) [protected]
Definition at line 575 of file process.cc.
References debugSymbolTable, ObjectFile::loadGlobalSymbols(), ObjectFile::loadLocalSymbols(), ObjectFile::loadWeakSymbols(), and objFile.
Member Function Documentation
LiveProcess * LiveProcess::create (LiveProcessParams * params) [static]
Definition at line 630 of file process.cc.
References ObjectFile::Alpha, ObjectFile::Arm, ObjectFile::Arm64, createObjectFile(), fatal, ObjectFile::FreeBSD, ObjectFile::getArch(), ObjectFile::getOpSys(), ObjectFile::I386, ObjectFile::isDynamic(), ObjectFile::Linux, ObjectFile::LinuxArmOABI, ObjectFile::Mips, objFile, ObjectFile::Power, ObjectFile::Solaris, ObjectFile::SPARC32, ObjectFile::SPARC64, ObjectFile::Thumb, ObjectFile::Tru64, ObjectFile::UnknownOpSys, warn, and ObjectFile::X86_64.
uint64_t LiveProcess::egid () [inline]
Definition at line 302 of file process.hh.
References __egid.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), getegidFunc(), and getgidPseudoFunc().
uint64_t LiveProcess::euid () [inline]
Definition at line 300 of file process.hh.
References __euid.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), geteuidFunc(), and getuidPseudoFunc().
EmulatedDriver * LiveProcess::findDriver (std::string filename)
Find an emulated device driver.
Parameters:
filename Name of the device (under /dev)
Returns:
Pointer to driver object if found, else NULL
Definition at line 618 of file process.cc.
References ArmISA::d, and drivers.
Referenced by openFunc().
std::string LiveProcess::fullPath (const std::string & filename) [inline]
Definition at line 310 of file process.hh.
References cwd.
Referenced by accessFunc(), chmodFunc(), chownFunc(), fstatat64Func(), lstat64Func(), lstatFunc(), mkdirFunc(), openFunc(), readlinkFunc(), renameatFunc(), renameFunc(), stat64Func(), statfsFunc(), statFunc(), truncate64Func(), truncateFunc(), unlinkHelper(), and utimesFunc().
std::string LiveProcess::getcwd () const [inline]
Definition at line 323 of file process.hh.
References cwd.
Referenced by getcwdFunc().
virtual SyscallDesc* LiveProcess::getDesc (int callnum) [pure virtual]
Implemented in AlphaISA::AlphaLinuxProcess, AlphaISA::AlphaTru64Process, ArmFreebsdProcess32, ArmFreebsdProcess64, ArmLinuxProcess32, ArmLinuxProcess64, MipsLinuxProcess, PowerLinuxProcess, SparcISA::Sparc32LinuxProcess, SparcISA::Sparc64LinuxProcess, SparcISA::SparcSolarisProcess, and X86ISA::X86LiveProcess.
Referenced by Tru64::indirectSyscallFunc(), and syscall().
IntReg LiveProcess::getSyscallArg (ThreadContext * tc, int & i, int width) [virtual]
Reimplemented in ArmLiveProcess32, ArmLiveProcess64, and X86ISA::I386LiveProcess.
Definition at line 611 of file process.cc.
References getSyscallArg().
virtual TheISA::IntReg LiveProcess::getSyscallArg (ThreadContext * tc, int & i) [pure virtual]
Implemented in AlphaLiveProcess, ArmLiveProcess32, ArmLiveProcess64, MipsLiveProcess, PowerLinuxProcess, PowerLiveProcess, Sparc32LiveProcess, Sparc64LiveProcess, X86ISA::X86_64LiveProcess, and X86ISA::I386LiveProcess.
Referenced by _llseekFunc(), accessFunc(), archPrctlFunc(), brkFunc(), chmodFunc(), chownFunc(), clock_gettimeFunc(), cloneFunc(), closeFunc(), SyscallDesc::doSyscall(), dupFunc(), exitFunc(), exitGroupFunc(), faccessatFunc(), fchmodFunc(), fchownFunc(), fcntl64Func(), fcntlFunc(), fstat64Func(), fstatat64Func(), fstatfsFunc(), fstatFunc(), ftruncate64Func(), ftruncateFunc(), futexFunc(), getcwdFunc(), Tru64::getdirentriesFunc(), gethostnameFunc(), SparcISA::getresuidFunc(), getrlimitFunc(), getrusageFunc(), getSyscallArg(), getsysinfoFunc(), gettimeofdayFunc(), ignoreFunc(), Tru64::indirectSyscallFunc(), ioctlFunc(), lseekFunc(), lstat64Func(), lstatFunc(), Tru64::m5_cond_broadcastFunc(), Tru64::m5_cond_signalFunc(), Tru64::m5_cond_waitFunc(), Tru64::m5_mutex_lockFunc(), Tru64::m5_mutex_trylockFunc(), Tru64::m5_mutex_unlockFunc(), mkdirFunc(), mmapFunc(), mremapFunc(), Tru64::nxm_blockFunc(), Tru64::nxm_task_initFunc(), Tru64::nxm_thread_blockFunc(), Tru64::nxm_thread_createFunc(), Tru64::nxm_unblockFunc(), openatFunc(), openFunc(), osf_getsysinfoFunc(), osf_setsysinfoFunc(), readFunc(), readlinkatFunc(), readlinkFunc(), renameatFunc(), renameFunc(), setsysinfoFunc(), setThreadArea32Func(), setThreadAreaFunc(), setTLSFunc32(), setTLSFunc64(), setuidFunc(), Tru64::sigreturnFunc(), Tru64::stack_createFunc(), stat64Func(), statfsFunc(), statFunc(), sys_getsysinfoFunc(), sys_setsysinfoFunc(), sysctlFunc(), sysinfoFunc(), tableFunc(), timeFunc(), timesFunc(), truncate64Func(), truncateFunc(), SparcISA::unameFunc(), unameFunc(), unameFunc32(), unameFunc64(), unlinkatFunc(), unlinkHelper(), utimesFunc(), writeFunc(), and writevFunc().
uint64_t LiveProcess::gid () [inline]
Definition at line 301 of file process.hh.
References __gid.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), getgidFunc(), and getgidPseudoFunc().
uint64_t LiveProcess::pid () [inline]
Definition at line 303 of file process.hh.
References __pid.
Referenced by getpidFunc(), and getpidPseudoFunc().
uint64_t LiveProcess::ppid () [inline]
Definition at line 304 of file process.hh.
References __ppid.
Referenced by getpidFunc(), getpidPseudoFunc(), and getppidFunc().
virtual const char* LiveProcess::progName () const [inline, virtual]
Reimplemented from Process.
Definition at line 307 of file process.hh.
References argv.
virtual void LiveProcess::setSyscallArg (ThreadContext * tc, int i, TheISA::IntReg val) [pure virtual]
Referenced by Tru64::indirectSyscallFunc(), and Tru64::init_thread_context().
virtual void LiveProcess::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) [pure virtual]
Implemented in AlphaLiveProcess, ArmLiveProcess32, ArmLiveProcess64, MipsLiveProcess, PowerLiveProcess, SparcLiveProcess, and X86ISA::X86LiveProcess.
void LiveProcess::syscall (int64_t callnum, ThreadContext * tc) [virtual]
Implements Process.
Reimplemented in X86ISA::I386LiveProcess.
Definition at line 599 of file process.cc.
References SyscallDesc::doSyscall(), fatal, getDesc(), and Process::num_syscalls.
uint64_t LiveProcess::uid () [inline]
Definition at line 299 of file process.hh.
References __uid.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), getuidFunc(), and getuidPseudoFunc().
Member Data Documentation
uint64_t LiveProcess::__egid [protected]
Definition at line 258 of file process.hh.
Referenced by egid().
uint64_t LiveProcess::__euid [protected]
Definition at line 256 of file process.hh.
Referenced by euid().
uint64_t LiveProcess::__gid [protected]
Definition at line 257 of file process.hh.
Referenced by gid().
uint64_t LiveProcess::__pid [protected]
Definition at line 261 of file process.hh.
Referenced by pid().
uint64_t LiveProcess::__ppid [protected]
Definition at line 262 of file process.hh.
Referenced by ppid().
uint64_t LiveProcess::__uid [protected]
Definition at line 255 of file process.hh.
Referenced by uid().
std::vector<std::string> LiveProcess::argv [protected]
Definition at line 248 of file process.hh.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), and progName().
std::string LiveProcess::cwd [protected]
Definition at line 250 of file process.hh.
Referenced by fullPath(), and getcwd().
std::vector<EmulatedDriver *> LiveProcess::drivers [protected]
Definition at line 265 of file process.hh.
Referenced by findDriver().
std::vector<std::string> LiveProcess::envp [protected]
Definition at line 249 of file process.hh.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), and AlphaLiveProcess::argsInit().
ObjectFile* LiveProcess::objFile [protected]
Definition at line 247 of file process.hh.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), create(), AlphaLiveProcess::initState(), LiveProcess(), ArmLiveProcess64::setSyscallReturn(), and ArmLiveProcess32::setSyscallReturn().
The documentation for this class was generated from the following files:
sim/process.hh
sim/process.cc