gem5: BaseXBar Class Reference
BaseXBar Class Reference
The base crossbar contains the common elements of the non-coherent and coherent crossbar.
#include <xbar.hh>
Classes
class Layer
A layer is an internal crossbar arbitration point with its own flow control.
struct PortCache
class ReqLayer
class RespLayer
class SnoopRespLayer
Public Member Functions
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
BaseMasterPort & getMasterPort (const std::string &if_name, PortID idx=InvalidPortID)
A function used to return the port associated with this object.
BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
virtual unsigned int drain (DrainManager *dm)=0
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
virtual void regStats ()
Register statistics for this object.
Protected Member Functions
void recvRangeChange (PortID master_port_id)
Function called by the port when the crossbar is recieving a range change.
PortID findPort (Addr addr)
Find which port connected to this crossbar (if any) should be given a packet with this address.
PortID checkPortCache (Addr addr) const
void updatePortCache (short id, const AddrRange &range)
void clearPortCache ()
AddrRangeList getAddrRanges () const
Return the address ranges the crossbar is responsible for.
void calcPacketTiming (PacketPtr pkt, Tick header_delay)
Calculate the timing parameters for the packet.
BaseXBar (const BaseXBarParams *p)
virtual ~BaseXBar ()
Protected Attributes
const Cycles frontendLatency
Cycles of front-end pipeline including the delay to accept the request and to decode the address.
const Cycles forwardLatency
Cycles of forward latency.
const Cycles responseLatency
Cycles of response latency.
const uint32_t width
the width of the xbar in bytes
AddrRangeMap< PortID > portMap
m5::unordered_map< RequestPtr,
PortID > routeTo
Remember where request packets came from so that we can route responses to the appropriate port.
AddrRangeList xbarRanges
all contigous ranges seen by this crossbar
AddrRange defaultRange
PortCache portCache [3]
std::vector< bool > gotAddrRanges
Remember for each of the master ports of the crossbar if we got an address range from the connected slave.
bool gotAllAddrRanges
std::vector< SlavePort * > slavePorts
The master and slave ports of the crossbar.
std::vector< MasterPort * > masterPorts
PortID defaultPortID
Port that handles requests that don't match any of the interfaces.
const bool useDefaultRange
If true, use address range provided by default device.
Stats::Vector transDist
Stats for transaction distribution and data passing through the crossbar.
Stats::Vector2d pktCount
Stats::Vector2d pktSize
Detailed Description
The base crossbar contains the common elements of the non-coherent and coherent crossbar.
It is an abstract class that does not have any of the functionality relating to the actual reception and transmission of packets, as this is left for the subclasses.
The BaseXBar is responsible for the basic flow control (busy or not), the administration of retries, and the address decoding.
Definition at line 72 of file xbar.hh.
Constructor & Destructor Documentation
BaseXBar::BaseXBar (const BaseXBarParams * p) [protected]
Definition at line 57 of file xbar.cc.
BaseXBar::~BaseXBar () [protected, virtual]
Definition at line 69 of file xbar.cc.
References ArmISA::m, masterPorts, ArmISA::s, and slavePorts.
Member Function Documentation
void BaseXBar::calcPacketTiming (PacketPtr pkt, Tick header_delay) [protected]
Calculate the timing parameters for the packet.
Updates the headerDelay and payloadDelay fields of the packet object with the relative number of ticks required to transmit the header and the payload, respectively.
Parameters:
pkt Packet to populate with timings
header_delay Header delay to be added
Definition at line 108 of file xbar.cc.
References ClockedObject::clockEdge(), ClockedObject::clockPeriod(), curTick(), divCeil(), Packet::getSize(), Packet::hasData(), Packet::headerDelay, ArmISA::offset, panic_if, Packet::payloadDelay, SimClock::Int::us, and width.
Referenced by NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), and CoherentXBar::recvTimingSnoopResp().
PortID BaseXBar::checkPortCache (Addr addr) const [inline, protected]
Definition at line 366 of file xbar.hh.
References BaseXBar::PortCache::id, InvalidPortID, and portCache.
Referenced by findPort().
void BaseXBar::clearPortCache () [inline, protected]
Definition at line 396 of file xbar.hh.
References portCache, and BaseXBar::PortCache::valid.
Referenced by CoherentXBar::CoherentXBar(), NoncoherentXBar::NoncoherentXBar(), and recvRangeChange().
virtual unsigned int BaseXBar::drain (DrainManager * drainManger) [pure virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Implemented in CoherentXBar, and NoncoherentXBar.
PortID BaseXBar::findPort (Addr addr) [protected]
Find which port connected to this crossbar (if any) should be given a packet with this address.
Parameters:
addr Address to find port for.
Returns:
id of port that the packet should be sent out of.
Definition at line 325 of file xbar.cc.
References checkPortCache(), AddrRange::contains(), defaultPortID, defaultRange, DPRINTF, AddrRangeMap< V >::end(), fatal, AddrRangeMap< V >::find(), gotAllAddrRanges, ArmISA::i, InvalidPortID, SimObject::name(), portMap, updatePortCache(), and useDefaultRange.
Referenced by NoncoherentXBar::recvAtomic(), CoherentXBar::recvAtomic(), NoncoherentXBar::recvFunctional(), CoherentXBar::recvFunctional(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), and CoherentXBar::recvTimingSnoopReq().
AddrRangeList BaseXBar::getAddrRanges () const [protected]
Return the address ranges the crossbar is responsible for.
Returns:
a list of non-overlapping address ranges
Definition at line 526 of file xbar.cc.
References DPRINTF, gotAllAddrRanges, and xbarRanges.
Referenced by NoncoherentXBar::NoncoherentXBarSlavePort::getAddrRanges(), and CoherentXBar::CoherentXBarSlavePort::getAddrRanges().
BaseMasterPort & BaseXBar::getMasterPort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
A function used to return the port associated with this object.
Reimplemented from MemObject.
Definition at line 84 of file xbar.cc.
References defaultPortID, and masterPorts.
Referenced by regStats().
BaseSlavePort & BaseXBar::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 97 of file xbar.cc.
References slavePorts.
Referenced by recvRangeChange(), and regStats().
void BaseXBar::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in CoherentXBar.
Definition at line 79 of file xbar.cc.
void BaseXBar::recvRangeChange (PortID master_port_id) [protected]
Function called by the port when the crossbar is recieving a range change.
Function called by the port when the crossbar is receiving a range change.
Parameters:
master_port_id id of the port that received the change
Definition at line 365 of file xbar.cc.
References AddrRangeMap< V >::begin(), clearPortCache(), defaultPortID, defaultRange, DPRINTF, AddrRangeMap< V >::end(), AddrRangeMap< V >::erase(), fatal, AddrRangeMap< V >::find(), getSlavePort(), gotAddrRanges, gotAllAddrRanges, AddrRangeMap< V >::insert(), masterPorts, SimObject::name(), MipsISA::p, portMap, MipsISA::r, ArmISA::s, slavePorts, AddrRange::to_string(), useDefaultRange, and xbarRanges.
Referenced by NoncoherentXBar::NoncoherentXBarMasterPort::recvRangeChange(), and CoherentXBar::CoherentXBarMasterPort::recvRangeChange().
void BaseXBar::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Reimplemented in CoherentXBar, and NoncoherentXBar.
Definition at line 544 of file xbar.cc.
References getMasterPort(), getSlavePort(), ArmISA::i, Stats::Vector2dBase< Derived, Stor >::init(), Stats::VectorBase< Derived, Stor >::init(), ArmISA::j, masterPorts, SimObject::name(), Stats::nonan, Stats::nozero, MemCmd::NUM_MEM_CMDS, pktCount, pktSize, slavePorts, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), MemCmd::toString(), Stats::total, transDist, and Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubname().
void BaseXBar::updatePortCache (short id, const AddrRange & range) [inline, protected]
Definition at line 381 of file xbar.hh.
References BaseXBar::PortCache::id, portCache, BaseXBar::PortCache::range, and BaseXBar::PortCache::valid.
Referenced by findPort().
Member Data Documentation
PortID BaseXBar::defaultPortID [protected]
Port that handles requests that don't match any of the interfaces.
Definition at line 434 of file xbar.hh.
Referenced by CoherentXBar::CoherentXBar(), findPort(), getMasterPort(), NoncoherentXBar::NoncoherentXBar(), and recvRangeChange().
AddrRange BaseXBar::defaultRange [protected]
Definition at line 337 of file xbar.hh.
Referenced by findPort(), and recvRangeChange().
const Cycles BaseXBar::forwardLatency [protected]
Cycles of forward latency.
Definition at line 318 of file xbar.hh.
Referenced by NoncoherentXBar::recvTimingReq(), and CoherentXBar::recvTimingReq().
const Cycles BaseXBar::frontendLatency [protected]
Cycles of front-end pipeline including the delay to accept the request and to decode the address.
Definition at line 316 of file xbar.hh.
Referenced by NoncoherentXBar::recvTimingReq(), and CoherentXBar::recvTimingReq().
std::vector<bool> BaseXBar::gotAddrRanges [protected]
Remember for each of the master ports of the crossbar if we got an address range from the connected slave.
For convenience, also keep track of if we got ranges from all the slave modules or not.
Definition at line 426 of file xbar.hh.
Referenced by recvRangeChange().
bool BaseXBar::gotAllAddrRanges [protected]
Definition at line 427 of file xbar.hh.
Referenced by findPort(), getAddrRanges(), and recvRangeChange().
std::vector<MasterPort*> BaseXBar::masterPorts [protected]
Definition at line 431 of file xbar.hh.
Referenced by CoherentXBar::CoherentXBar(), CoherentXBar::forwardAtomic(), getMasterPort(), NoncoherentXBar::NoncoherentXBar(), NoncoherentXBar::recvAtomic(), CoherentXBar::recvAtomic(), CoherentXBar::recvAtomicSnoop(), NoncoherentXBar::recvFunctional(), CoherentXBar::recvFunctional(), CoherentXBar::recvFunctionalSnoop(), recvRangeChange(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopResp(), regStats(), and ~BaseXBar().
Stats::Vector2d BaseXBar::pktCount [protected]
Definition at line 456 of file xbar.hh.
Referenced by NoncoherentXBar::recvAtomic(), CoherentXBar::recvAtomic(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopResp(), and regStats().
Stats::Vector2d BaseXBar::pktSize [protected]
Definition at line 457 of file xbar.hh.
Referenced by NoncoherentXBar::recvAtomic(), CoherentXBar::recvAtomic(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopResp(), and regStats().
PortCache BaseXBar::portCache[3] [protected]
Definition at line 362 of file xbar.hh.
Referenced by checkPortCache(), clearPortCache(), and updatePortCache().
AddrRangeMap<PortID> BaseXBar::portMap [protected]
Definition at line 324 of file xbar.hh.
Referenced by findPort(), and recvRangeChange().
const Cycles BaseXBar::responseLatency [protected]
Cycles of response latency.
Definition at line 320 of file xbar.hh.
Referenced by NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), and CoherentXBar::recvTimingSnoopResp().
m5::unordered_map<RequestPtr, PortID> BaseXBar::routeTo [protected]
Remember where request packets came from so that we can route responses to the appropriate port.
This relies on the fact that the underlying Request pointer inside the Packet stays constant.
Definition at line 332 of file xbar.hh.
Referenced by NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), and CoherentXBar::recvTimingSnoopResp().
std::vector<SlavePort*> BaseXBar::slavePorts [protected]
The master and slave ports of the crossbar.
Definition at line 430 of file xbar.hh.
Referenced by CoherentXBar::CoherentXBar(), CoherentXBar::forwardAtomic(), getSlavePort(), CoherentXBar::init(), NoncoherentXBar::NoncoherentXBar(), NoncoherentXBar::recvAtomic(), CoherentXBar::recvAtomic(), NoncoherentXBar::recvFunctional(), CoherentXBar::recvFunctional(), recvRangeChange(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopResp(), regStats(), and ~BaseXBar().
Stats::Vector BaseXBar::transDist [protected]
Stats for transaction distribution and data passing through the crossbar.
The transaction distribution is globally counting different types of commands. The packet count and total packet size are two-dimensional vectors that are indexed by the slave port and master port id (thus the neighbouring master and neighbouring slave), summing up both directions (request and response).
Definition at line 455 of file xbar.hh.
Referenced by NoncoherentXBar::recvAtomic(), CoherentXBar::recvAtomic(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopResp(), and regStats().
const bool BaseXBar::useDefaultRange [protected]
If true, use address range provided by default device.
Any address not handled by another port and not in default device's range will cause a fatal error. If false, just send all addresses not handled by another port to default device.
Definition at line 440 of file xbar.hh.
Referenced by findPort(), and recvRangeChange().
const uint32_t BaseXBar::width [protected]
the width of the xbar in bytes
Definition at line 322 of file xbar.hh.
Referenced by calcPacketTiming().
AddrRangeList BaseXBar::xbarRanges [protected]
all contigous ranges seen by this crossbar
Definition at line 335 of file xbar.hh.
Referenced by getAddrRanges(), and recvRangeChange().
The documentation for this class was generated from the following files:
mem/xbar.hh
mem/xbar.cc