gem5: NoncoherentXBar::NoncoherentXBarMasterPort Class Reference
NoncoherentXBar::NoncoherentXBarMasterPort Class Reference
Declaration of the crossbar master port type, one will be instantiated for each of the slave ports connecting to the crossbar.
#include <noncoherent_xbar.hh>
Public Member Functions
NoncoherentXBarMasterPort (const std::string &_name, NoncoherentXBar &_xbar, PortID _id)
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
When receiving a timing response, pass it to the crossbar.
virtual void recvRangeChange ()
When reciving a range change from the peer port (at id), pass it to the crossbar.
virtual void recvReqRetry ()
When reciving a retry from the peer port (at id), pass it to the crossbar.
Private Attributes
NoncoherentXBar & xbar
A reference to the crossbar to which this port belongs.
Detailed Description
Declaration of the crossbar master port type, one will be instantiated for each of the slave ports connecting to the crossbar.
Definition at line 140 of file noncoherent_xbar.hh.
Constructor & Destructor Documentation
NoncoherentXBar::NoncoherentXBarMasterPort::NoncoherentXBarMasterPort (const std::string & _name, NoncoherentXBar & _xbar, PortID _id) [inline]
Definition at line 149 of file noncoherent_xbar.hh.
Member Function Documentation
virtual void NoncoherentXBar::NoncoherentXBarMasterPort::recvRangeChange () [inline, protected, virtual]
When reciving a range change from the peer port (at id), pass it to the crossbar.
Reimplemented from MasterPort.
Definition at line 164 of file noncoherent_xbar.hh.
References BaseXBar::recvRangeChange(), and xbar.
virtual void NoncoherentXBar::NoncoherentXBarMasterPort::recvReqRetry () [inline, protected, virtual]
When reciving a retry from the peer port (at id), pass it to the crossbar.
Implements MasterPort.
Definition at line 169 of file noncoherent_xbar.hh.
References NoncoherentXBar::recvReqRetry(), and xbar.
virtual bool NoncoherentXBar::NoncoherentXBarMasterPort::recvTimingResp (PacketPtr pkt) [inline, protected, virtual]
When receiving a timing response, pass it to the crossbar.
Implements MasterPort.
Definition at line 159 of file noncoherent_xbar.hh.
References NoncoherentXBar::recvTimingResp(), and xbar.
Member Data Documentation
NoncoherentXBar& NoncoherentXBar::NoncoherentXBarMasterPort::xbar [private]
A reference to the crossbar to which this port belongs.
Definition at line 145 of file noncoherent_xbar.hh.
Referenced by recvRangeChange(), recvReqRetry(), and recvTimingResp().
The documentation for this class was generated from the following file:
mem/noncoherent_xbar.hh