gem5: AtagCore Class Reference
AtagCore Class Reference
#include <atag.hh>
Public Member Functions
uint32_t tag ()
Tag (normally starts with 'T''A' and 16 bits of number.
void flags (uint32_t i)
void pagesize (uint32_t i)
void rootdev (uint32_t i)
AtagCore ()
Static Public Attributes
static const uint32_t Size = 5
Detailed Description
Definition at line 91 of file atag.hh.
Constructor & Destructor Documentation
AtagCore::AtagCore () [inline]
Definition at line 100 of file atag.hh.
Member Function Documentation
void AtagCore::flags (uint32_t i) [inline]
Definition at line 97 of file atag.hh.
References AtagHeader::storage.
Referenced by LinuxArmSystem::initState().
void AtagCore::pagesize (uint32_t i) [inline]
Definition at line 98 of file atag.hh.
References AtagHeader::storage.
Referenced by LinuxArmSystem::initState().
void AtagCore::rootdev (uint32_t i) [inline]
Definition at line 99 of file atag.hh.
References AtagHeader::storage.
Referenced by LinuxArmSystem::initState().
uint32_t AtagCore::tag () [inline, virtual]
Tag (normally starts with 'T''A' and 16 bits of number.
Implements AtagHeader.
Definition at line 95 of file atag.hh.
References CoreTag.
Member Data Documentation
const uint32_t AtagCore::Size = 5 [static]
Definition at line 94 of file atag.hh.
The documentation for this class was generated from the following file:
arch/arm/linux/atag.hh