gem5: SimpleNetwork Class Reference
SimpleNetwork Class Reference
#include <SimpleNetwork.hh>
Public Types
typedef SimpleNetworkParams Params
Public Member Functions
SimpleNetwork (const Params *p)
~SimpleNetwork ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
int getBufferSize ()
int getEndpointBandwidth ()
bool getAdaptiveRouting ()
void collateStats ()
void regStats ()
Register statistics for this object.
void setToNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer *b)
void setFromNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer *b)
bool isVNetOrdered (int vnet)
bool validVirtualNetwork (int vnet)
void makeOutLink (SwitchID src, NodeID dest, BasicLink *link, LinkDirection direction, const NetDest &routing_table_entry)
void makeInLink (NodeID src, SwitchID dest, BasicLink *link, LinkDirection direction, const NetDest &routing_table_entry)
void makeInternalLink (SwitchID src, SwitchID dest, BasicLink *link, LinkDirection direction, const NetDest &routing_table_entry)
void print (std::ostream &out) const
bool functionalRead (Packet *pkt)
uint32_t functionalWrite (Packet *pkt)
Private Member Functions
void checkNetworkAllocation (NodeID id, bool ordered, int network_num)
void addLink (SwitchID src, SwitchID dest, int link_latency)
void makeLink (SwitchID src, SwitchID dest, const NetDest &routing_table_entry, int link_latency)
void makeTopology ()
SimpleNetwork (const SimpleNetwork &obj)
SimpleNetwork & operator= (const SimpleNetwork &obj)
Private Attributes
std::vector< Switch * > m_switches
std::vector< MessageBuffer * > m_buffers_to_free
std::vector< Switch * > m_endpoint_switches
int m_buffer_size
int m_endpoint_bandwidth
bool m_adaptive_routing
Stats::Formula m_msg_counts [MessageSizeType_NUM]
Stats::Formula m_msg_bytes [MessageSizeType_NUM]
Detailed Description
Definition at line 43 of file SimpleNetwork.hh.
Member Typedef Documentation
typedef SimpleNetworkParams SimpleNetwork::Params
Reimplemented from Network.
Definition at line 46 of file SimpleNetwork.hh.
Constructor & Destructor Documentation
SimpleNetwork::SimpleNetwork (const Params * p)
Definition at line 46 of file SimpleNetwork.cc.
References ArmISA::i, Switch::init_net_ptr(), m_adaptive_routing, m_buffer_size, m_endpoint_bandwidth, m_endpoint_switches, Network::m_nodes, m_switches, ArmISA::s, and safe_cast().
SimpleNetwork::~SimpleNetwork ()
Definition at line 78 of file SimpleNetwork.cc.
References m5::stl_helpers::deletePointers(), m_buffers_to_free, and m_switches.
SimpleNetwork::SimpleNetwork (const SimpleNetwork & obj) [private]
Member Function Documentation
void SimpleNetwork::addLink (SwitchID src, SwitchID dest, int link_latency) [private]
void SimpleNetwork::checkNetworkAllocation (NodeID id, bool ordered, int network_num) [private]
Definition at line 146 of file SimpleNetwork.cc.
References Network::m_in_use, Network::m_nodes, Network::m_ordered, and Network::m_virtual_networks.
Referenced by setFromNetQueue(), and setToNetQueue().
void SimpleNetwork::collateStats () [virtual]
Implements Network.
Definition at line 206 of file SimpleNetwork.cc.
References ArmISA::i, and m_switches.
bool SimpleNetwork::functionalRead (Packet * pkt) [virtual]
Reimplemented from Network.
Definition at line 231 of file SimpleNetwork.cc.
References ArmISA::i, m_buffers_to_free, and m_switches.
uint32_t SimpleNetwork::functionalWrite (Packet * pkt) [virtual]
Reimplemented from Network.
Definition at line 249 of file SimpleNetwork.cc.
References ArmISA::i, m_buffers_to_free, and m_switches.
bool SimpleNetwork::getAdaptiveRouting () [inline]
Definition at line 54 of file SimpleNetwork.hh.
References m_adaptive_routing.
Referenced by PerfectSwitch::operateVnet().
int SimpleNetwork::getBufferSize () [inline]
Definition at line 52 of file SimpleNetwork.hh.
References m_buffer_size.
Referenced by Switch::addOutPort().
int SimpleNetwork::getEndpointBandwidth () [inline]
Definition at line 53 of file SimpleNetwork.hh.
References m_endpoint_bandwidth.
Referenced by Switch::addOutPort().
void SimpleNetwork::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from Network.
Definition at line 68 of file SimpleNetwork.cc.
References Topology::createLinks(), and Network::m_topology_ptr.
bool SimpleNetwork::isVNetOrdered (int vnet) [inline]
Definition at line 65 of file SimpleNetwork.hh.
References Network::m_ordered.
Referenced by PerfectSwitch::operateVnet().
void SimpleNetwork::makeInLink (NodeID src, SwitchID dest, BasicLink * link, LinkDirection direction, const NetDest & routing_table_entry) [virtual]
Implements Network.
Definition at line 105 of file SimpleNetwork.cc.
References Network::m_nodes, m_switches, and Network::m_toNetQueues.
void SimpleNetwork::makeInternalLink (SwitchID src, SwitchID dest, BasicLink * link, LinkDirection direction, const NetDest & routing_table_entry) [virtual]
Implements Network.
Definition at line 115 of file SimpleNetwork.cc.
References ArmISA::i, m_buffer_size, m_buffers_to_free, SimpleIntLink::m_bw_multiplier, BasicLink::m_latency, m_switches, Network::m_virtual_networks, MessageBuffer::resize(), safe_cast(), and MessageBuffer::setOrdering().
void SimpleNetwork::makeLink (SwitchID src, SwitchID dest, const NetDest & routing_table_entry, int link_latency) [private]
void SimpleNetwork::makeOutLink (SwitchID src, NodeID dest, BasicLink * link, LinkDirection direction, const NetDest & routing_table_entry) [virtual]
Implements Network.
Definition at line 86 of file SimpleNetwork.cc.
References SimpleExtLink::m_bw_multiplier, m_endpoint_switches, Network::m_fromNetQueues, BasicLink::m_latency, Network::m_nodes, m_switches, and safe_cast().
void SimpleNetwork::makeTopology () [private]
SimpleNetwork& SimpleNetwork::operator= (const SimpleNetwork & obj) [private]
Reimplemented from Network.
void SimpleNetwork::print (std::ostream & out) const [virtual]
Implements Network.
Referenced by operator<<().
void SimpleNetwork::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 180 of file SimpleNetwork.cc.
References Stats::constant(), ArmISA::i, m_msg_bytes, m_msg_counts, m_switches, Network::MessageSizeType_to_int(), SimObject::name(), Stats::nozero, Stats::sum(), and X86ISA::type.
void SimpleNetwork::setFromNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer * b) [virtual]
Implements Network.
Definition at line 169 of file SimpleNetwork.cc.
References checkNetworkAllocation(), and Network::m_fromNetQueues.
void SimpleNetwork::setToNetQueue (NodeID id, bool ordered, int network_num, std::string vnet_type, MessageBuffer * b) [virtual]
Implements Network.
Definition at line 158 of file SimpleNetwork.cc.
References checkNetworkAllocation(), and Network::m_toNetQueues.
bool SimpleNetwork::validVirtualNetwork (int vnet) [inline]
Definition at line 66 of file SimpleNetwork.hh.
References Network::m_in_use.
Member Data Documentation
bool SimpleNetwork::m_adaptive_routing [private]
Definition at line 101 of file SimpleNetwork.hh.
Referenced by getAdaptiveRouting(), and SimpleNetwork().
int SimpleNetwork::m_buffer_size [private]
Definition at line 99 of file SimpleNetwork.hh.
Referenced by getBufferSize(), makeInternalLink(), and SimpleNetwork().
std::vector<MessageBuffer*> SimpleNetwork::m_buffers_to_free [private]
Definition at line 96 of file SimpleNetwork.hh.
Referenced by functionalRead(), functionalWrite(), makeInternalLink(), and ~SimpleNetwork().
int SimpleNetwork::m_endpoint_bandwidth [private]
Definition at line 100 of file SimpleNetwork.hh.
Referenced by getEndpointBandwidth(), and SimpleNetwork().
std::vector<Switch*> SimpleNetwork::m_endpoint_switches [private]
Definition at line 97 of file SimpleNetwork.hh.
Referenced by makeOutLink(), and SimpleNetwork().
Stats::Formula SimpleNetwork::m_msg_bytes[MessageSizeType_NUM] [private]
Definition at line 105 of file SimpleNetwork.hh.
Referenced by regStats().
Stats::Formula SimpleNetwork::m_msg_counts[MessageSizeType_NUM] [private]
Definition at line 104 of file SimpleNetwork.hh.
Referenced by regStats().
std::vector<Switch*> SimpleNetwork::m_switches [private]
Definition at line 95 of file SimpleNetwork.hh.
Referenced by collateStats(), functionalRead(), functionalWrite(), makeInLink(), makeInternalLink(), makeOutLink(), regStats(), SimpleNetwork(), and ~SimpleNetwork().
The documentation for this class was generated from the following files:
mem/ruby/network/simple/SimpleNetwork.hh
mem/ruby/network/simple/SimpleNetwork.cc