gem5: Check Class Reference
Check Class Reference
#include <Check.hh>
Public Member Functions
Check (const Address &address, const Address &pc, int _num_writers, int _num_readers, RubyTester *_tester)
void initiate ()
void performCallback (NodeID proc, SubBlock *data, Cycles curTime)
const Address & getAddress ()
void changeAddress (const Address &address)
void print (std::ostream &out) const
Private Member Functions
void initiateFlush ()
void initiatePrefetch ()
void initiateAction ()
void initiateCheck ()
void pickValue ()
void pickInitiatingNode ()
void debugPrint ()
Private Attributes
TesterStatus m_status
uint8_t m_value
int m_store_count
NodeID m_initiatingNode
Address m_address
Address m_pc
RubyAccessMode m_access_mode
int m_num_writers
int m_num_readers
RubyTester * m_tester_ptr
Detailed Description
Definition at line 46 of file Check.hh.
Constructor & Destructor Documentation
Check::Check (const Address & address, const Address & pc, int _num_writers, int _num_readers, RubyTester * _tester)
Definition at line 39 of file Check.cc.
References changeAddress(), m_access_mode, m_pc, m_status, m_store_count, pickInitiatingNode(), pickValue(), Random::random(), and random_mt.
Member Function Documentation
void Check::changeAddress (const Address & address)
Definition at line 336 of file Check.cc.
References m_address, m_status, and m_store_count.
Referenced by Check().
void Check::debugPrint () [private]
Definition at line 376 of file Check.cc.
References DPRINTF, Address::getAddress(), m_address, m_initiatingNode, m_status, m_store_count, and m_value.
Referenced by initiate(), and performCallback().
const Address& Check::getAddress () [inline]
Definition at line 54 of file Check.hh.
References m_address.
Referenced by performCallback().
void Check::initiate ()
Definition at line 56 of file Check.cc.
References debugPrint(), DPRINTF, RubyTester::getCheckFlush(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), m_status, m_tester_ptr, Random::random(), and random_mt.
Referenced by RubyTester::wakeup().
void Check::initiateAction () [private]
Definition at line 166 of file Check.cc.
References curTick(), Packet::dataDynamic(), DPRINTF, Address::getAddress(), Packet::getConstPtr(), RubyTester::getWritableCpuPort(), MipsISA::index, m_address, m_num_writers, m_pc, m_status, m_store_count, m_tester_ptr, m_value, RubyTester::masterId(), Random::random(), random_mt, Packet::req, Packet::senderState, MasterPort::sendTimingReq(), and MemCmd::WriteReq.
Referenced by initiate().
void Check::initiateCheck () [private]
Definition at line 227 of file Check.cc.
References CHECK_SIZE, curTick(), Packet::dataDynamic(), DPRINTF, Address::getAddress(), RubyTester::getReadableCpuPort(), Request::getSize(), MipsISA::index, Request::INST_FETCH, RubyTester::isInstReadableCpuPort(), m_address, m_num_readers, m_pc, m_status, m_tester_ptr, RubyTester::masterId(), Random::random(), random_mt, MemCmd::ReadReq, Packet::req, Packet::senderState, MasterPort::sendTimingReq(), Flags< T >::set(), and Request::setThreadContext().
Referenced by initiate().
void Check::initiateFlush () [private]
Definition at line 137 of file Check.cc.
References CHECK_SIZE, curTick(), DPRINTF, MemCmd::FlushReq, Address::getAddress(), Request::getSize(), RubyTester::getWritableCpuPort(), MipsISA::index, m_address, m_num_writers, m_pc, m_tester_ptr, RubyTester::masterId(), Random::random(), random_mt, Packet::senderState, and MasterPort::sendTimingReq().
Referenced by initiate().
void Check::initiatePrefetch () [private]
Definition at line 82 of file Check.cc.
References curTick(), Packet::dataDynamic(), DPRINTF, Address::getAddress(), RubyTester::getReadableCpuPort(), Request::getSize(), MipsISA::index, Request::INST_FETCH, RubyTester::isInstReadableCpuPort(), m_address, m_num_readers, m_pc, m_tester_ptr, RubyTester::masterId(), Request::PF_EXCLUSIVE, Request::PREFETCH, Random::random(), random_mt, MemCmd::ReadReq, Packet::req, Packet::senderState, MasterPort::sendTimingReq(), Flags< T >::set(), Request::setThreadContext(), and MemCmd::WriteReq.
Referenced by initiate().
void Check::performCallback (NodeID proc, SubBlock * data, Cycles curTime)
Definition at line 276 of file Check.cc.
References CHECK_SIZE, debugPrint(), DPRINTF, getAddress(), SubBlock::getAddress(), SubBlock::getByte(), Address::getLineAddress(), RubyTester::incrementCheckCompletions(), m_status, m_store_count, m_tester_ptr, m_value, panic, pickValue(), and SubBlock::setByte().
Referenced by RubyTester::hitCallback().
void Check::pickInitiatingNode () [private]
Definition at line 354 of file Check.cc.
References DPRINTF, m_initiatingNode, m_num_writers, m_status, m_store_count, Random::random(), and random_mt.
Referenced by Check().
void Check::pickValue () [private]
Definition at line 345 of file Check.cc.
References m_status, m_store_count, m_value, Random::random(), and random_mt.
Referenced by Check(), and performCallback().
void Check::print (std::ostream & out) const
Definition at line 364 of file Check.cc.
References m_address, m_initiatingNode, m_status, m_store_count, and m_value.
Referenced by operator<<().
Member Data Documentation
RubyAccessMode Check::m_access_mode [private]
Definition at line 76 of file Check.hh.
Referenced by Check().
Address Check::m_address [private]
Definition at line 74 of file Check.hh.
Referenced by changeAddress(), debugPrint(), getAddress(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), and print().
NodeID Check::m_initiatingNode [private]
Definition at line 73 of file Check.hh.
Referenced by debugPrint(), pickInitiatingNode(), and print().
int Check::m_num_readers [private]
Definition at line 78 of file Check.hh.
Referenced by initiateCheck(), and initiatePrefetch().
int Check::m_num_writers [private]
Definition at line 77 of file Check.hh.
Referenced by initiateAction(), initiateFlush(), and pickInitiatingNode().
Address Check::m_pc [private]
Definition at line 75 of file Check.hh.
Referenced by Check(), initiateAction(), initiateCheck(), initiateFlush(), and initiatePrefetch().
TesterStatus Check::m_status [private]
Definition at line 70 of file Check.hh.
Referenced by changeAddress(), Check(), debugPrint(), initiate(), initiateAction(), initiateCheck(), performCallback(), pickInitiatingNode(), pickValue(), and print().
int Check::m_store_count [private]
Definition at line 72 of file Check.hh.
Referenced by changeAddress(), Check(), debugPrint(), initiateAction(), performCallback(), pickInitiatingNode(), pickValue(), and print().
RubyTester* Check::m_tester_ptr [private]
Definition at line 79 of file Check.hh.
Referenced by initiate(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), and performCallback().
uint8_t Check::m_value [private]
Definition at line 71 of file Check.hh.
Referenced by debugPrint(), initiateAction(), performCallback(), pickValue(), and print().
The documentation for this class was generated from the following files:
cpu/testers/rubytest/Check.hh
cpu/testers/rubytest/Check.cc