gem5: Averager Class Reference
Averager Class Reference
#include <psel.hh>
Public Member Functions
Averager ()
Tick getStart ()
double getAverage ()
void add (Tick _start, Tick _end, unsigned int _counter)
void add (double _counter)
void clear ()
Private Attributes
Tick start
Tick end
Tick duration
double average
bool first_add
Detailed Description
Definition at line 11 of file psel.hh.
Constructor & Destructor Documentation
Averager::Averager () [inline]
Definition at line 21 of file psel.hh.
References clear(), and first_add.
Member Function Documentation
void Averager::add (double _counter) [inline]
Definition at line 50 of file psel.hh.
References add(), curTick(), and end.
void Averager::add (Tick _start, Tick _end, unsigned int _counter) [inline]
Definition at line 27 of file psel.hh.
References average, curTick(), duration, end, first_add, and start.
Referenced by add(), and PolicySelectorPlotter::sample().
void Averager::clear () [inline]
Definition at line 54 of file psel.hh.
References curTick(), duration, end, and start.
Referenced by Averager(), PolicySelectorPlotter::resetStats(), and PolicySelectorPlotter::sample().
double Averager::getAverage () [inline]
Definition at line 25 of file psel.hh.
References average.
Referenced by PolicySelectorPlotter::sample().
Tick Averager::getStart () [inline]
Definition at line 23 of file psel.hh.
References start.
Referenced by PolicySelectorPlotter::sample().
Member Data Documentation
double Averager::average [private]
Definition at line 15 of file psel.hh.
Referenced by add(), and getAverage().
Tick Averager::duration [private]
Definition at line 14 of file psel.hh.
Referenced by add(), and clear().
Tick Averager::end [private]
Definition at line 13 of file psel.hh.
Referenced by add(), and clear().
bool Averager::first_add [private]
Definition at line 17 of file psel.hh.
Referenced by add(), and Averager().
Tick Averager::start [private]
Definition at line 12 of file psel.hh.
Referenced by add(), clear(), and getStart().
The documentation for this class was generated from the following file:
mem/cache/tags/psel.hh