gem5: TimingSimpleCPU::DcachePort Class Reference
TimingSimpleCPU::DcachePort Class Reference
Classes
struct DTickEvent
Public Member Functions
DcachePort (TimingSimpleCPU *_cpu)
Public Attributes
Addr cacheBlockMask
Protected Member Functions
virtual void recvTimingSnoopReq (PacketPtr pkt)
Snoop a coherence request, we need to check if this causes a wakeup event on a cpu that is monitoring an address.
virtual void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the slave port.
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
virtual void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
Protected Attributes
DTickEvent tickEvent
Detailed Description
Definition at line 213 of file timing.hh.
Constructor & Destructor Documentation
TimingSimpleCPU::DcachePort::DcachePort (TimingSimpleCPU * _cpu) [inline]
Definition at line 217 of file timing.hh.
References cacheBlockMask, and TimingSimpleCPU::TimingCPUPort::cpu.
Member Function Documentation
virtual bool TimingSimpleCPU::DcachePort::isSnooping () const [inline, protected, virtual]
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns:
true if the port should be considered a snooper
Reimplemented from MasterPort.
Definition at line 237 of file timing.hh.
void TimingSimpleCPU::DcachePort::recvFunctionalSnoop (PacketPtr pkt) [protected, virtual]
Receive a functional snoop request packet from the slave port.
Reimplemented from MasterPort.
Definition at line 824 of file timing.cc.
References TimingSimpleCPU::TimingCPUPort::cpu, BaseSimpleCPU::getAddrMonitor(), and BaseSimpleCPU::wakeup().
void TimingSimpleCPU::DcachePort::recvReqRetry () [protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 860 of file timing.cc.
References BaseSimpleCPU::_status, TimingSimpleCPU::SplitFragmentSenderState::bigPkt, TimingSimpleCPU::SplitFragmentSenderState::clearFromParent(), TimingSimpleCPU::TimingCPUPort::cpu, TimingSimpleCPU::dcache_pkt, BaseSimpleCPU::DcacheRetry, BaseSimpleCPU::DcacheWaitResponse, TimingSimpleCPU::SplitMainSenderState::fragments, TimingSimpleCPU::SplitMainSenderState::getPendingFragment(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), Packet::isRead(), Packet::isWrite(), Packet::senderState, and MasterPort::sendTimingReq().
bool TimingSimpleCPU::DcachePort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 833 of file timing.cc.
References TimingSimpleCPU::TimingCPUPort::cpu, DPRINTF, Packet::getAddr(), TimingSimpleCPU::TimingCPUPort::retryRespEvent, Event::scheduled(), and tickEvent.
void TimingSimpleCPU::DcachePort::recvTimingSnoopReq (PacketPtr pkt) [protected, virtual]
Snoop a coherence request, we need to check if this causes a wakeup event on a cpu that is monitoring an address.
Reimplemented from TimingSimpleCPU::TimingCPUPort.
Definition at line 814 of file timing.cc.
References cacheBlockMask, TimingSimpleCPU::TimingCPUPort::cpu, BaseSimpleCPU::getAddrMonitor(), AlphaISA::handleLockedSnoop(), BaseSimpleCPU::thread, and BaseSimpleCPU::wakeup().
Member Data Documentation
Addr TimingSimpleCPU::DcachePort::cacheBlockMask
Definition at line 224 of file timing.hh.
Referenced by DcachePort(), recvTimingSnoopReq(), and TimingSimpleCPU::sendData().
DTickEvent TimingSimpleCPU::DcachePort::tickEvent [protected]
Definition at line 249 of file timing.hh.
Referenced by recvTimingResp().
The documentation for this class was generated from the following files:
cpu/simple/timing.hh
cpu/simple/timing.cc