gem5: PageTableBase Class Reference
PageTableBase Class Reference
Declaration of base class for page table.
#include <page_table.hh>
Classes
struct cacheElement
Public Types
enum MappingFlags { Clobber = 1, NotPresent = 2, Uncacheable = 4, ReadOnly = 8 }
Public Member Functions
PageTableBase (const std::string &__name, uint64_t _pid, Addr _pageSize=TheISA::PageBytes)
virtual ~PageTableBase ()
virtual void initState (ThreadContext *tc)=0
const std::string name () const
Addr pageAlign (Addr a)
Addr pageOffset (Addr a)
virtual void map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags=0)=0
Maps a virtual memory region to a physical memory region.
virtual void remap (Addr vaddr, int64_t size, Addr new_vaddr)=0
virtual void unmap (Addr vaddr, int64_t size)=0
virtual bool isUnmapped (Addr vaddr, int64_t size)=0
Check if any pages in a region are already allocated.
virtual bool lookup (Addr vaddr, TheISA::TlbEntry &entry)=0
Lookup function.
bool translate (Addr vaddr, Addr &paddr)
Translate function.
bool translate (Addr vaddr)
Simplified translate function (just check for translation).
Fault translate (RequestPtr req)
Perform a translation on the memory request, fills in paddr field of req.
void updateCache (Addr vaddr, TheISA::TlbEntry entry)
Update the page table cache.
void eraseCacheEntry (Addr vaddr)
Erase an entry from the page table cache.
virtual void serialize (std::ostream &os)=0
virtual void unserialize (Checkpoint *cp, const std::string &section)=0
Protected Attributes
struct cacheElement pTableCache [3]
const Addr pageSize
const Addr offsetMask
const uint64_t pid
const std::string _name
Detailed Description
Declaration of base class for page table.
Definition at line 56 of file page_table.hh.
Member Enumeration Documentation
enum PageTableBase::MappingFlags
Enumerator:
Clobber
NotPresent
Uncacheable
ReadOnly
Definition at line 95 of file page_table.hh.
Constructor & Destructor Documentation
PageTableBase::PageTableBase (const std::string & __name, uint64_t _pid, Addr _pageSize = TheISA::PageBytes) [inline]
Definition at line 75 of file page_table.hh.
References isPowerOf2(), pageSize, pTableCache, and PageTableBase::cacheElement::valid.
virtual PageTableBase::~PageTableBase () [inline, virtual]
Definition at line 86 of file page_table.hh.
Member Function Documentation
void PageTableBase::eraseCacheEntry (Addr vaddr) [inline]
Erase an entry from the page table cache.
Parameters:
vaddr virtual address (page aligned) to check
Definition at line 184 of file page_table.hh.
References pTableCache, and PageTableBase::cacheElement::valid.
Referenced by FuncPageTable::map(), MultiLevelPageTable< ISAOps >::map(), FuncPageTable::remap(), MultiLevelPageTable< ISAOps >::remap(), FuncPageTable::unmap(), and MultiLevelPageTable< ISAOps >::unmap().
virtual void PageTableBase::initState (ThreadContext * tc) [pure virtual]
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by Process::initState().
virtual bool PageTableBase::isUnmapped (Addr vaddr, int64_t size) [pure virtual]
Check if any pages in a region are already allocated.
Parameters:
vaddr The starting virtual address of the region.
size The length of the region.
Returns:
True if no pages in the region are mapped.
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by mmapFunc().
virtual bool PageTableBase::lookup (Addr vaddr, TheISA::TlbEntry & entry) [pure virtual]
Lookup function.
Parameters:
vaddr The virtual address.
Returns:
entry The page table entry corresponding to vaddr.
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by X86ISA::RemoteGDB::acc(), SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), SparcISA::FastDataAccessMMUMiss::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), AlphaISA::NDtbMissFault::invoke(), AlphaISA::ItbPageFault::invoke(), translate(), and X86ISA::TLB::translate().
virtual void PageTableBase::map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags = 0) [pure virtual]
Maps a virtual memory region to a physical memory region.
Parameters:
vaddr The starting virtual address of the region.
paddr The starting physical address where the region is mapped.
size The length of the region.
flags Generic mapping flags that can be set by or-ing values from MappingFlags enum.
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by Process::allocateMem(), and Process::map().
const std::string PageTableBase::name () const [inline]
Definition at line 105 of file page_table.hh.
References _name.
Referenced by FuncPageTable::serialize(), and FuncPageTable::unserialize().
Addr PageTableBase::pageAlign (Addr a) [inline]
Definition at line 107 of file page_table.hh.
References offsetMask.
Referenced by SparcISA::FastDataAccessMMUMiss::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), FuncPageTable::lookup(), and translate().
Addr PageTableBase::pageOffset (Addr a) [inline]
Definition at line 108 of file page_table.hh.
References offsetMask.
Referenced by FuncPageTable::isUnmapped(), MultiLevelPageTable< ISAOps >::isUnmapped(), FuncPageTable::map(), MultiLevelPageTable< ISAOps >::map(), FuncPageTable::remap(), MultiLevelPageTable< ISAOps >::remap(), translate(), FuncPageTable::unmap(), and MultiLevelPageTable< ISAOps >::unmap().
virtual void PageTableBase::remap (Addr vaddr, int64_t size, Addr new_vaddr) [pure virtual]
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by mremapFunc().
virtual void PageTableBase::serialize (std::ostream & os) [pure virtual]
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by Process::serialize().
Fault PageTableBase::translate (RequestPtr req)
Perform a translation on the memory request, fills in paddr field of req.
Parameters:
req The memory request.
Definition at line 182 of file page_table.cc.
References Request::getSize(), Request::getVaddr(), pageAlign(), pageSize, panic, Request::setPaddr(), and translate().
bool PageTableBase::translate (Addr vaddr) [inline]
Simplified translate function (just check for translation).
Parameters:
vaddr The virtual address.
Returns:
True if translation exists
Definition at line 151 of file page_table.hh.
References translate().
Referenced by translate().
bool PageTableBase::translate (Addr vaddr, Addr & paddr)
Translate function.
Parameters:
vaddr The virtual address.
paddr Physical address from translation.
Returns:
True if translation exists
Definition at line 169 of file page_table.cc.
References DPRINTF, lookup(), and pageOffset().
Referenced by brkFunc(), translate(), GenericTLB::translateAtomic(), PowerISA::TLB::translateData(), MipsISA::TLB::translateData(), PowerISA::TLB::translateInst(), MipsISA::TLB::translateInst(), ArmISA::TLB::translateSe(), SETranslatingPortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryReadBlob(), SETranslatingPortProxy::tryReadString(), SETranslatingPortProxy::tryWriteBlob(), and SETranslatingPortProxy::tryWriteString().
virtual void PageTableBase::unmap (Addr vaddr, int64_t size) [pure virtual]
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by mremapFunc().
virtual void PageTableBase::unserialize (Checkpoint * cp, const std::string & section) [pure virtual]
Implemented in MultiLevelPageTable< ISAOps >, and FuncPageTable.
Referenced by Process::unserialize().
void PageTableBase::updateCache (Addr vaddr, TheISA::TlbEntry entry) [inline]
Update the page table cache.
Parameters:
vaddr virtual address (page aligned) to check
pte page table entry to return
Definition at line 165 of file page_table.hh.
References PageTableBase::cacheElement::entry, pTableCache, PageTableBase::cacheElement::vaddr, and PageTableBase::cacheElement::valid.
Referenced by FuncPageTable::lookup(), FuncPageTable::map(), MultiLevelPageTable< ISAOps >::map(), FuncPageTable::remap(), and MultiLevelPageTable< ISAOps >::remap().
Member Data Documentation
const std::string PageTableBase::_name [protected]
Definition at line 71 of file page_table.hh.
Referenced by name().
const Addr PageTableBase::offsetMask [protected]
Definition at line 68 of file page_table.hh.
Referenced by pageAlign(), and pageOffset().
const Addr PageTableBase::pageSize [protected]
Definition at line 67 of file page_table.hh.
Referenced by FuncPageTable::isUnmapped(), MultiLevelPageTable< ISAOps >::isUnmapped(), FuncPageTable::map(), MultiLevelPageTable< ISAOps >::map(), PageTableBase(), FuncPageTable::remap(), MultiLevelPageTable< ISAOps >::remap(), translate(), FuncPageTable::unmap(), and MultiLevelPageTable< ISAOps >::unmap().
const uint64_t PageTableBase::pid [protected]
Definition at line 70 of file page_table.hh.
Referenced by FuncPageTable::map(), MultiLevelPageTable< ISAOps >::map(), and MultiLevelPageTable< ISAOps >::remap().
struct cacheElement PageTableBase::pTableCache[3] [read, protected]
Definition at line 65 of file page_table.hh.
Referenced by eraseCacheEntry(), FuncPageTable::lookup(), PageTableBase(), and updateCache().
The documentation for this class was generated from the following files:
mem/page_table.hh
mem/page_table.cc