gem5: SparcLiveProcess Class Reference
SparcLiveProcess Class Reference
#include <process.hh>
Public Member Functions
virtual void handleTrap (int trapNum, ThreadContext *tc)
Addr readFillStart ()
Addr readSpillStart ()
virtual void flushWindows (ThreadContext *tc)=0
void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)
Protected Member Functions
SparcLiveProcess (LiveProcessParams *params, ObjectFile *objFile, Addr _StackBias)
void initState ()
initState() is called on each SimObject when *not* restoring from a checkpoint.
template<class IntType >
void argsInit (int pageSize)
Protected Attributes
const Addr StackBias
Addr fillStart
Addr spillStart
Detailed Description
Definition at line 44 of file process.hh.
Constructor & Destructor Documentation
SparcLiveProcess::SparcLiveProcess (LiveProcessParams * params, ObjectFile * objFile, Addr _StackBias) [protected]
Definition at line 53 of file process.cc.
References Process::brk_point, ObjectFile::bssSize(), ObjectFile::dataBase(), ObjectFile::dataSize(), fillStart, Process::next_thread_stack_base, AlphaISA::PageBytes, roundUp(), spillStart, and Process::stack_base.
Member Function Documentation
template<class IntType > void SparcLiveProcess::argsInit (int pageSize) [inline, protected]
Definition at line 188 of file process.cc.
References Process::allocateMem(), LiveProcess::argv, Process::contextIds, copyStringArray(), DPRINTF, LiveProcess::egid(), ObjectFile::entryPoint(), LiveProcess::envp, LiveProcess::euid(), fillStart, System::getThreadContext(), LiveProcess::gid(), BigEndianGuest::htog(), ArmISA::i, Process::initVirtMem, ObjectFile::loadSections(), LiveProcess::M5_AT_BASE, LiveProcess::M5_AT_CLKTCK, LiveProcess::M5_AT_EGID, LiveProcess::M5_AT_ENTRY, LiveProcess::M5_AT_EUID, LiveProcess::M5_AT_FLAGS, LiveProcess::M5_AT_GID, LiveProcess::M5_AT_HWCAP, LiveProcess::M5_AT_PAGESZ, LiveProcess::M5_AT_PHDR, LiveProcess::M5_AT_PHENT, LiveProcess::M5_AT_PHNUM, LiveProcess::M5_AT_SECURE, LiveProcess::M5_AT_UID, SparcISA::numFillInsts, LiveProcess::objFile, SparcISA::PageBytes, ElfObject::programHeaderCount(), ElfObject::programHeaderSize(), ElfObject::programHeaderTable(), roundDown(), roundUp(), ThreadContext::setIntReg(), spillStart, Process::stack_base, Process::stack_min, Process::stack_size, StackBias, AlphaISA::StackPointerReg, Process::system, ArmISA::tc, LiveProcess::uid(), SETranslatingPortProxy::writeBlob(), SETranslatingPortProxy::writeString(), and X86ISA::x.
virtual void SparcLiveProcess::flushWindows (ThreadContext * tc) [pure virtual]
Implemented in Sparc32LiveProcess, and Sparc64LiveProcess.
Referenced by handleTrap().
void SparcLiveProcess::handleTrap (int trapNum, ThreadContext * tc) [virtual]
Reimplemented in SparcISA::Sparc32LinuxProcess, and SparcISA::Sparc64LinuxProcess.
Definition at line 71 of file process.cc.
References flushWindows(), panic, GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), and warn.
Referenced by SparcISA::TrapInstruction::invoke().
void SparcLiveProcess::initState () [protected, virtual]
initState() is called on each SimObject when *not* restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from Process.
Reimplemented in Sparc32LiveProcess, and Sparc64LiveProcess.
Definition at line 112 of file process.cc.
References SparcISA::ASI_PRIMARY, Process::contextIds, System::getThreadContext(), SparcISA::MISCREG_ASI, SparcISA::MISCREG_CWP, SparcISA::MISCREG_FSR, SparcISA::MISCREG_MMU_LSU_CTRL, SparcISA::MISCREG_TICK, SparcISA::MISCREG_TL, AlphaISA::NumIntArchRegs, SparcISA::NWindows, ThreadContext::setIntReg(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), Process::system, and ArmISA::tc.
Addr SparcLiveProcess::readFillStart () [inline]
Definition at line 66 of file process.hh.
References fillStart.
Referenced by SparcISA::FillNNormal::invoke().
Addr SparcLiveProcess::readSpillStart () [inline]
Definition at line 67 of file process.hh.
References spillStart.
Referenced by SparcISA::SpillNNormal::invoke().
void SparcLiveProcess::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) [virtual]
Implements LiveProcess.
Definition at line 535 of file process.cc.
References bits(), SyscallReturn::errnoValue(), SparcISA::MISCREG_PSTATE, AlphaISA::NumIntArchRegs, ThreadContext::readIntReg(), ThreadContext::readMiscRegNoEffect(), SyscallReturn::returnValue(), AlphaISA::ReturnValueReg, ThreadContext::setIntReg(), and SyscallReturn::successful().
Member Data Documentation
Addr SparcLiveProcess::fillStart [protected]
Definition at line 51 of file process.hh.
Referenced by Sparc32LiveProcess::argsInit(), Sparc64LiveProcess::argsInit(), argsInit(), readFillStart(), and SparcLiveProcess().
Addr SparcLiveProcess::spillStart [protected]
Definition at line 51 of file process.hh.
Referenced by Sparc32LiveProcess::argsInit(), Sparc64LiveProcess::argsInit(), argsInit(), readSpillStart(), and SparcLiveProcess().
const Addr SparcLiveProcess::StackBias [protected]
Definition at line 48 of file process.hh.
Referenced by argsInit().
The documentation for this class was generated from the following files:
arch/sparc/process.hh
arch/sparc/process.cc