gem5: FLIP Class Reference
FLIP Class Reference
#include <flip.hh>
Classes
class UpdatePriorityEvent
Public Types
typedef FLIPParams Params
Convenience typedef.
Public Member Functions
FLIP (const Params *p)
Construct and initialize this tag store.
~FLIP ()
Destructor.
virtual void startup ()
startup() is the final initialization call before simulation.
virtual BlkType * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
virtual BlkType * findVictim (Addr addr)
Find an invalid block to evict for the address provided.
virtual void insertBlock (PacketPtr pkt, BlkType *blk)
Insert the new block into the cache.
virtual void invalidate (BlkType *blk)
Invalidate the given block.
virtual void updatePriorityPointer ()
void samplePriorityPointer ()
virtual void regStats ()
Register local statistics.
Public Attributes
std::vector
< Stats::Distribution * > posDistDuration
std::vector
< Stats::Distribution * > posDistBlock
Private Member Functions
void scheduleUpdatePriorityEvent (Cycles delay)
Private Attributes
StackDistanceCounter sdp
StackDistanceCounterArray sdparr
std::vector
< ConservativeSaturatingCounter > pos
std::vector< uint64_t > frc
unsigned int blk_max_count
unsigned int detect_th
Cycles update_interval
UpdatePriorityEvent updateEvent
Detailed Description
Definition at line 14 of file flip.hh.
Member Typedef Documentation
typedef FLIPParams FLIP::Params
Convenience typedef.
Reimplemented from LRU.
Reimplemented in FLIPProfiler.
Definition at line 51 of file flip.hh.
Constructor & Destructor Documentation
FLIP::FLIP (const Params * p)
Construct and initialize this tag store.
Definition at line 28 of file flip.cc.
FLIP::~FLIP () [inline]
Destructor.
Definition at line 61 of file flip.hh.
Member Function Documentation
BaseSetAssoc::BlkType * FLIP::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Reimplemented from LRU.
Reimplemented in FLIPProfiler.
Definition at line 72 of file flip.cc.
References BaseSetAssoc::assoc, blk_max_count, fatal, frc, CacheSet< Blktype >::getLRUState(), CacheSet< Blktype >::moveTo(), CacheSet< Blktype >::moveToHead(), pos, posDistBlock, StackDistanceCounterArray::sample(), StackDistanceCounter::sample(), sdp, sdparr, CacheBlk::set, BaseSetAssoc::sets, and CacheBlk::tag_refcount.
BaseSetAssoc::BlkType * FLIP::findVictim (Addr addr) [virtual]
Find an invalid block to evict for the address provided.
If there are no invalid blocks, this will return the block in the least-recently-used position.
Parameters:
addr The addr to a find a replacement candidate for.
Returns:
The candidate block.
Reimplemented from LRU.
Reimplemented in FLIPProfiler.
Definition at line 106 of file flip.cc.
References BaseSetAssoc::assoc, CacheSet< Blktype >::blks, DPRINTF, BaseSetAssoc::extractSet(), CacheBlk::isValid(), BaseSetAssoc::regenerateBlkAddr(), BaseSetAssoc::sets, and CacheBlk::tag.
void FLIP::insertBlock (PacketPtr pkt, BlkType * blk) [virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Reimplemented from LRU.
Reimplemented in FLIPProfiler.
Definition at line 121 of file flip.cc.
References BaseSetAssoc::extractSet(), Packet::getAddr(), CacheSet< Blktype >::moveTo(), pos, posDistBlock, BaseSetAssoc::sets, and CacheBlk::tag_refcount.
void FLIP::invalidate (BlkType * blk) [virtual]
Invalidate the given block.
Parameters:
blk The block to invalidate.
Reimplemented from LRU.
Reimplemented in FLIPProfiler.
Definition at line 134 of file flip.cc.
References CacheSet< Blktype >::moveToTail(), CacheBlk::set, and BaseSetAssoc::sets.
void FLIP::regStats () [virtual]
Register local statistics.
Reimplemented from BaseTags.
Reimplemented in FLIPProfiler.
Definition at line 39 of file flip.cc.
References BaseSetAssoc::assoc, blk_max_count, Stats::dist, ArmISA::i, SimObject::name(), posDistBlock, and posDistDuration.
void FLIP::samplePriorityPointer ()
Definition at line 167 of file flip.cc.
References blk_max_count, curTick(), ArmISA::i, pos, and posDistDuration.
Referenced by updatePriorityPointer().
void FLIP::scheduleUpdatePriorityEvent (Cycles delay) [inline, private]
Definition at line 41 of file flip.hh.
References ClockedObject::clockEdge(), EventManager::reschedule(), EventManager::schedule(), Event::scheduled(), Event::squashed(), and updateEvent.
Referenced by startup(), and updatePriorityPointer().
void FLIP::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Reimplemented in FLIPProfiler.
Definition at line 62 of file flip.cc.
References blk_max_count, detect_th, inform, scheduleUpdatePriorityEvent(), and update_interval.
void FLIP::updatePriorityPointer () [virtual]
Definition at line 144 of file flip.cc.
References blk_max_count, curTick(), detect_th, StackDistanceCounterArray::dump(), StackDistanceCounter::dump(), frc, ArmISA::i, inform, SimObject::name(), pos, samplePriorityPointer(), scheduleUpdatePriorityEvent(), sdp, sdparr, and update_interval.
Referenced by FLIP::UpdatePriorityEvent::process().
Member Data Documentation
unsigned int FLIP::blk_max_count [private]
Definition at line 24 of file flip.hh.
Referenced by accessBlock(), regStats(), samplePriorityPointer(), startup(), and updatePriorityPointer().
unsigned int FLIP::detect_th [private]
Definition at line 25 of file flip.hh.
Referenced by startup(), and updatePriorityPointer().
std::vector<uint64_t> FLIP::frc [private]
Definition at line 22 of file flip.hh.
Referenced by accessBlock(), and updatePriorityPointer().
std::vector<ConservativeSaturatingCounter> FLIP::pos [private]
Definition at line 20 of file flip.hh.
Referenced by accessBlock(), insertBlock(), samplePriorityPointer(), and updatePriorityPointer().
std::vector<Stats::Distribution*> FLIP::posDistBlock
Definition at line 77 of file flip.hh.
Referenced by accessBlock(), insertBlock(), and regStats().
std::vector<Stats::Distribution*> FLIP::posDistDuration
Definition at line 76 of file flip.hh.
Referenced by regStats(), and samplePriorityPointer().
StackDistanceCounter FLIP::sdp [private]
Definition at line 16 of file flip.hh.
Referenced by accessBlock(), and updatePriorityPointer().
StackDistanceCounterArray FLIP::sdparr [private]
Definition at line 17 of file flip.hh.
Referenced by accessBlock(), and updatePriorityPointer().
Cycles FLIP::update_interval [private]
Definition at line 27 of file flip.hh.
Referenced by startup(), and updatePriorityPointer().
UpdatePriorityEvent FLIP::updateEvent [private]
Definition at line 39 of file flip.hh.
Referenced by scheduleUpdatePriorityEvent().
The documentation for this class was generated from the following files:
mem/cache/tags/flip.hh
mem/cache/tags/flip.cc