gem5: Switch Class Reference
Switch Class Reference
#include <Switch.hh>
Public Types
typedef SwitchParams Params
Public Member Functions
Switch (const Params *p)
~Switch ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void addInPort (const std::vector< MessageBuffer * > &in)
void addOutPort (const std::vector< MessageBuffer * > &out, const NetDest &routing_table_entry, Cycles link_latency, int bw_multiplier)
const Throttle * getThrottle (LinkID link_number) const
void resetStats ()
Reset statistics associated with this object.
void collateStats ()
void regStats ()
Register statistics for this object.
const Stats::Formula & getMsgCount (unsigned int type) const
void print (std::ostream &out) const
void init_net_ptr (SimpleNetwork *net_ptr)
bool functionalRead (Packet *)
uint32_t functionalWrite (Packet *)
Private Member Functions
Switch (const Switch &obj)
Switch & operator= (const Switch &obj)
Private Attributes
PerfectSwitch * m_perfect_switch
SimpleNetwork * m_network_ptr
std::vector< Throttle * > m_throttles
std::vector< MessageBuffer * > m_buffers_to_free
Stats::Formula m_avg_utilization
Stats::Formula m_msg_counts [MessageSizeType_NUM]
Stats::Formula m_msg_bytes [MessageSizeType_NUM]
Detailed Description
Definition at line 57 of file Switch.hh.
Member Typedef Documentation
typedef SwitchParams Switch::Params
Reimplemented from BasicRouter.
Definition at line 60 of file Switch.hh.
Constructor & Destructor Documentation
Switch::Switch (const Params * p)
Definition at line 43 of file Switch.cc.
References BasicRouter::m_id, and m_perfect_switch.
Switch::~Switch ()
Definition at line 48 of file Switch.cc.
References m5::stl_helpers::deletePointers(), m_buffers_to_free, m_perfect_switch, and m_throttles.
Switch::Switch (const Switch & obj) [private]
Member Function Documentation
void Switch::addInPort (const std::vector< MessageBuffer * > & in)
Definition at line 67 of file Switch.cc.
References PerfectSwitch::addInPort(), and m_perfect_switch.
void Switch::addOutPort (const std::vector< MessageBuffer * > & out, const NetDest & routing_table_entry, Cycles link_latency, int bw_multiplier)
Definition at line 79 of file Switch.cc.
References Throttle::addLinks(), PerfectSwitch::addOutPort(), SimpleNetwork::getBufferSize(), SimpleNetwork::getEndpointBandwidth(), ArmISA::i, m_buffers_to_free, BasicRouter::m_id, m_network_ptr, m_perfect_switch, m_throttles, MessageBuffer::resize(), MessageBuffer::setOrdering(), MessageBuffer::setReceiver(), and MessageBuffer::setSender().
void Switch::collateStats ()
Definition at line 171 of file Switch.cc.
References PerfectSwitch::collateStats(), ArmISA::i, m_perfect_switch, and m_throttles.
bool Switch::functionalRead (Packet * pkt)
Definition at line 187 of file Switch.cc.
References ArmISA::i, and m_buffers_to_free.
uint32_t Switch::functionalWrite (Packet * pkt)
Definition at line 199 of file Switch.cc.
References ArmISA::i, and m_buffers_to_free.
const Stats::Formula& Switch::getMsgCount (unsigned int type) const [inline]
Definition at line 75 of file Switch.hh.
References m_msg_counts.
const Throttle * Switch::getThrottle (LinkID link_number) const
Definition at line 121 of file Switch.cc.
References m_throttles.
void Switch::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BasicRouter.
Definition at line 60 of file Switch.cc.
References PerfectSwitch::init(), m_network_ptr, and m_perfect_switch.
void Switch::init_net_ptr (SimpleNetwork * net_ptr) [inline]
Definition at line 79 of file Switch.hh.
References m_network_ptr.
Referenced by SimpleNetwork::SimpleNetwork().
Switch& Switch::operator= (const Switch & obj) [private]
void Switch::print (std::ostream & out) const
Reimplemented from BasicRouter.
Definition at line 180 of file Switch.cc.
Referenced by operator<<().
void Switch::regStats () [virtual]
Register statistics for this object.
Reimplemented from SimObject.
Definition at line 128 of file Switch.cc.
References Stats::constant(), ArmISA::i, m_avg_utilization, m_msg_bytes, m_msg_counts, m_throttles, Network::MessageSizeType_to_int(), Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), Stats::nozero, and X86ISA::type.
void Switch::resetStats () [virtual]
Reset statistics associated with this object.
Reimplemented from SimObject.
Definition at line 162 of file Switch.cc.
References PerfectSwitch::clearStats(), ArmISA::i, m_perfect_switch, and m_throttles.
Member Data Documentation
Stats::Formula Switch::m_avg_utilization [private]
Definition at line 95 of file Switch.hh.
Referenced by regStats().
std::vector<MessageBuffer*> Switch::m_buffers_to_free [private]
Definition at line 92 of file Switch.hh.
Referenced by addOutPort(), functionalRead(), functionalWrite(), and ~Switch().
Stats::Formula Switch::m_msg_bytes[MessageSizeType_NUM] [private]
Definition at line 97 of file Switch.hh.
Referenced by regStats().
Stats::Formula Switch::m_msg_counts[MessageSizeType_NUM] [private]
Definition at line 96 of file Switch.hh.
Referenced by getMsgCount(), and regStats().
SimpleNetwork* Switch::m_network_ptr [private]
Definition at line 90 of file Switch.hh.
Referenced by addOutPort(), init(), and init_net_ptr().
PerfectSwitch* Switch::m_perfect_switch [private]
Definition at line 89 of file Switch.hh.
Referenced by addInPort(), addOutPort(), collateStats(), init(), resetStats(), Switch(), and ~Switch().
std::vector<Throttle*> Switch::m_throttles [private]
Definition at line 91 of file Switch.hh.
Referenced by addOutPort(), collateStats(), getThrottle(), regStats(), resetStats(), and ~Switch().
The documentation for this class was generated from the following files:
mem/ruby/network/simple/Switch.hh
mem/ruby/network/simple/Switch.cc