gem5: SimPoint Class Reference
SimPoint Class Reference
#include <simpoint.hh>
Classes
struct BBInfo
Basic Block information.
Public Member Functions
SimPoint (const SimPointParams *params)
virtual ~SimPoint ()
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void regProbeListeners ()
Register probe listeners for this object.
void profile (const std::pair< SimpleThread *, StaticInstPtr > &)
Profile basic blocks for SimPoints.
Private Attributes
const uint64_t intervalSize
SimPoint profiling interval size in instructions.
uint64_t intervalCount
Inst count in current basic block.
uint64_t intervalDrift
Excess inst count from previous interval.
std::ostream * simpointStream
Pointer to SimPoint BBV output stream.
m5::hash_map< BasicBlockRange,
BBInfo > bbMap
Hash table containing all previously seen basic blocks.
BasicBlockRange currentBBV
Currently executing basic block.
uint64_t currentBBVInstCount
inst count in current basic block
Detailed Description
Definition at line 73 of file simpoint.hh.
Constructor & Destructor Documentation
SimPoint::SimPoint (const SimPointParams * params)
Definition at line 44 of file simpoint.cc.
References OutputDirectory::create(), fatal, simout, and simpointStream.
SimPoint::~SimPoint () [virtual]
Definition at line 58 of file simpoint.cc.
References OutputDirectory::close(), simout, and simpointStream.
Member Function Documentation
void SimPoint::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 64 of file simpoint.cc.
void SimPoint::profile (const std::pair< SimpleThread *, StaticInstPtr > & p)
Profile basic blocks for SimPoints.
Called at every macro inst to increment basic block inst counts and to profile block if end of block.
Definition at line 77 of file simpoint.cc.
References bbMap, SimPoint::BBInfo::count, currentBBV, currentBBVInstCount, SimPoint::BBInfo::id, SimPoint::BBInfo::insts, intervalCount, intervalDrift, intervalSize, SimpleThread::pcState(), and simpointStream.
Referenced by regProbeListeners().
void SimPoint::regProbeListeners () [virtual]
Register probe listeners for this object.
No probe listeners by default, so do nothing in base.
Reimplemented from SimObject.
Definition at line 68 of file simpoint.cc.
References ProbeListenerObject::listeners, and profile().
Member Data Documentation
m5::hash_map<BasicBlockRange, BBInfo> SimPoint::bbMap [private]
Hash table containing all previously seen basic blocks.
Definition at line 112 of file simpoint.hh.
Referenced by profile().
BasicBlockRange SimPoint::currentBBV [private]
Currently executing basic block.
Definition at line 114 of file simpoint.hh.
Referenced by profile().
uint64_t SimPoint::currentBBVInstCount [private]
inst count in current basic block
Definition at line 116 of file simpoint.hh.
Referenced by profile().
uint64_t SimPoint::intervalCount [private]
Inst count in current basic block.
Definition at line 95 of file simpoint.hh.
Referenced by profile().
uint64_t SimPoint::intervalDrift [private]
Excess inst count from previous interval.
Definition at line 97 of file simpoint.hh.
Referenced by profile().
const uint64_t SimPoint::intervalSize [private]
SimPoint profiling interval size in instructions.
Definition at line 92 of file simpoint.hh.
Referenced by profile().
std::ostream* SimPoint::simpointStream [private]
Pointer to SimPoint BBV output stream.
Definition at line 99 of file simpoint.hh.
Referenced by profile(), SimPoint(), and ~SimPoint().
The documentation for this class was generated from the following files:
cpu/simple/probes/simpoint.hh
cpu/simple/probes/simpoint.cc