gem5: MemChecker::ByteTracker Class Reference
MemChecker::ByteTracker Class Reference
The ByteTracker keeps track of transactions for the *same byte* -- all outstanding reads, the completed reads (and what they observed) and write clusters (see WriteCluster).
#include <mem_checker.hh>
Public Member Functions
ByteTracker (Addr addr=0, const MemChecker *parent=NULL)
void startRead (Serial serial, Tick start)
Starts a read transaction.
bool inExpectedData (Tick start, Tick complete, uint8_t data)
Given a start and end time (of any read transaction), this function iterates through all data that such a read is expected to see.
bool completeRead (Serial serial, Tick complete, uint8_t data)
Completes a read transaction that is still outstanding.
void startWrite (Serial serial, Tick start, uint8_t data)
Starts a write transaction.
void completeWrite (Serial serial, Tick complete)
Completes a write transaction.
void abortWrite (Serial serial)
Aborts a write transaction.
const std::vector< uint8_t > & lastExpectedData () const
This function returns the expected data that inExpectedData iterated through in the last call.
Private Member Functions
WriteCluster * getIncompleteWriteCluster ()
Convenience function to return the most recent incomplete write cluster.
template<class TList >
TList::iterator lastCompletedTransaction (TList *l, Tick before)
Helper function to return an iterator to the entry of a container of Transaction compatible classes, before a certain tick.
void pruneTransactions ()
Prunes no longer needed transactions.
Private Attributes
std::map< Serial, Transaction > outstandingReads
Maintains a map of Serial -> Transaction for all outstanding reads.
TransactionList readObservations
List of completed reads, i.e.
WriteClusterList writeClusters
List of write clusters for this address.
std::vector< uint8_t > _lastExpectedData
See lastExpectedData().
Detailed Description
The ByteTracker keeps track of transactions for the *same byte* -- all outstanding reads, the completed reads (and what they observed) and write clusters (see WriteCluster).
Definition at line 202 of file mem_checker.hh.
Constructor & Destructor Documentation
MemChecker::ByteTracker::ByteTracker (Addr addr = 0, const MemChecker * parent = NULL) [inline]
Definition at line 206 of file mem_checker.hh.
References MemChecker::DATA_INITIAL, readObservations, MemChecker::SERIAL_INITIAL, and MemChecker::TICK_INITIAL.
Member Function Documentation
void MemChecker::ByteTracker::abortWrite (MemChecker::Serial serial)
Aborts a write transaction.
Wrapper to abortWrite of WriteCluster instance.
Parameters:
serial Unique identifier of a write *previously started*.
Definition at line 272 of file mem_checker.cc.
References MemChecker::WriteCluster::abortWrite(), and getIncompleteWriteCluster().
Referenced by MemChecker::abortWrite().
bool MemChecker::ByteTracker::completeRead (MemChecker::Serial serial, Tick complete, uint8_t data)
Completes a read transaction that is still outstanding.
Parameters:
serial Unique identifier of a read *previously started*.
complete When the read got a response.
data The data returned by the memory subsystem.
Definition at line 223 of file mem_checker.cc.
References inExpectedData(), outstandingReads, pruneTransactions(), readObservations, and warn.
Referenced by MemChecker::completeRead().
void MemChecker::ByteTracker::completeWrite (MemChecker::Serial serial, Tick complete)
Completes a write transaction.
Wrapper to startWrite of WriteCluster instance.
Parameters:
serial Unique identifier of a write *previously started*.
complete When the write was sent off to the memory subsystem.
Definition at line 265 of file mem_checker.cc.
References MemChecker::WriteCluster::completeWrite(), getIncompleteWriteCluster(), and pruneTransactions().
Referenced by MemChecker::completeWrite().
MemChecker::WriteCluster * MemChecker::ByteTracker::getIncompleteWriteCluster () [private]
Convenience function to return the most recent incomplete write cluster.
Instantiates new write cluster if the most recent one has been completed.
Returns:
The most recent incomplete write cluster.
Definition at line 248 of file mem_checker.cc.
References writeClusters.
Referenced by abortWrite(), completeWrite(), and startWrite().
bool MemChecker::ByteTracker::inExpectedData (Tick start, Tick complete, uint8_t data)
Given a start and end time (of any read transaction), this function iterates through all data that such a read is expected to see.
The data parameter is the actual value that we observed, and the function immediately returns true when a match is found, false otherwise.
The set of expected data are:
1. The last value observed by a read with a completion time before this start time (if any).
2. The data produced by write transactions with a completion after the last observed read start time. Only data produced in the closest overlapping / earlier write cluster relative to this check request is considered, as writes in separate clusters are not reordered.
Parameters:
start Start time of transaction to validate.
complete End time of transaction to validate.
data The value that we have actually seen.
Returns:
True if a match is found, false otherwise.
Definition at line 130 of file mem_checker.cc.
References _lastExpectedData, MemChecker::Transaction::complete, MemChecker::Transaction::data, DPRINTF, lastCompletedTransaction(), readObservations, MemChecker::Transaction::start, MemChecker::TICK_INITIAL, and writeClusters.
Referenced by completeRead().
template<class TList > TList::iterator MemChecker::ByteTracker::lastCompletedTransaction (TList * l, Tick before) [inline, private]
Helper function to return an iterator to the entry of a container of Transaction compatible classes, before a certain tick.
Parameters:
before Tick value which should be greater than the completion tick of the returned element.
Returns:
Iterator into container.
Definition at line 322 of file mem_checker.hh.
Referenced by inExpectedData(), and pruneTransactions().
const std::vector<uint8_t>& MemChecker::ByteTracker::lastExpectedData () const [inline]
This function returns the expected data that inExpectedData iterated through in the last call.
If inExpectedData last returned true, the set may be incomplete; if inExpectedData last returned false, the vector will contain the full set.
Returns:
Reference to internally maintained vector maintaining last expected data that inExpectedData iterated through.
Definition at line 298 of file mem_checker.hh.
References _lastExpectedData.
Referenced by MemChecker::completeRead().
void MemChecker::ByteTracker::pruneTransactions () [private]
Prunes no longer needed transactions.
We only keep up to the last / most recent of each, readObservations and writeClusters, before the first outstanding read.
It depends on the contention / overlap between memory operations to the same location of a particular workload how large each of them would grow.
Definition at line 278 of file mem_checker.cc.
References curTick(), lastCompletedTransaction(), outstandingReads, readObservations, and writeClusters.
Referenced by completeRead(), and completeWrite().
void MemChecker::ByteTracker::startRead (MemChecker::Serial serial, Tick start)
Starts a read transaction.
Parameters:
serial Unique identifier for the read.
start When the read was sent off to the memory subsystem.
Definition at line 123 of file mem_checker.cc.
References outstandingReads, and MemChecker::TICK_FUTURE.
Referenced by MemChecker::startRead().
void MemChecker::ByteTracker::startWrite (MemChecker::Serial serial, Tick start, uint8_t data)
Starts a write transaction.
Wrapper to startWrite of WriteCluster instance.
Parameters:
serial Unique identifier of the write.
start When the write was sent off to the memory subsystem.
data The data that this write passed to the memory subsystem.
Definition at line 258 of file mem_checker.cc.
References getIncompleteWriteCluster(), and MemChecker::WriteCluster::startWrite().
Referenced by MemChecker::startWrite().
Member Data Documentation
std::vector<uint8_t> MemChecker::ByteTracker::_lastExpectedData [private]
See lastExpectedData().
Definition at line 369 of file mem_checker.hh.
Referenced by inExpectedData(), and lastExpectedData().
std::map<Serial, Transaction> MemChecker::ByteTracker::outstandingReads [private]
Maintains a map of Serial -> Transaction for all outstanding reads.
Use an ordered map here, as this makes pruneTransactions() more efficient (find first outstanding read).
Definition at line 354 of file mem_checker.hh.
Referenced by completeRead(), pruneTransactions(), and startRead().
TransactionList MemChecker::ByteTracker::readObservations [private]
List of completed reads, i.e.
observations of reads.
Definition at line 359 of file mem_checker.hh.
Referenced by ByteTracker(), completeRead(), inExpectedData(), and pruneTransactions().
WriteClusterList MemChecker::ByteTracker::writeClusters [private]
List of write clusters for this address.
Definition at line 364 of file mem_checker.hh.
Referenced by getIncompleteWriteCluster(), inExpectedData(), and pruneTransactions().
The documentation for this class was generated from the following files:
mem/mem_checker.hh
mem/mem_checker.cc