gem5: AddrMapper::MapperSlavePort Class Reference
AddrMapper::MapperSlavePort Class Reference
#include <addr_mapper.hh>
Public Member Functions
MapperSlavePort (const std::string &_name, AddrMapper &_mapper)
Protected Member Functions
void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the master port.
Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the master port.
bool recvTimingSnoopResp (PacketPtr pkt)
Receive a timing snoop response from the master port.
AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Private Attributes
AddrMapper & mapper
Detailed Description
Definition at line 160 of file addr_mapper.hh.
Constructor & Destructor Documentation
AddrMapper::MapperSlavePort::MapperSlavePort (const std::string & _name, AddrMapper & _mapper) [inline]
Definition at line 165 of file addr_mapper.hh.
Member Function Documentation
AddrRangeList AddrMapper::MapperSlavePort::getAddrRanges () const [inline, protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 191 of file addr_mapper.hh.
References AddrMapper::getAddrRanges(), and mapper.
Tick AddrMapper::MapperSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 176 of file addr_mapper.hh.
References mapper, and AddrMapper::recvAtomic().
void AddrMapper::MapperSlavePort::recvFunctional (PacketPtr pkt) [inline, protected, virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 171 of file addr_mapper.hh.
References mapper, and AddrMapper::recvFunctional().
void AddrMapper::MapperSlavePort::recvRespRetry () [inline, protected, virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 196 of file addr_mapper.hh.
References mapper, and AddrMapper::recvRespRetry().
bool AddrMapper::MapperSlavePort::recvTimingReq (PacketPtr pkt) [inline, protected, virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 181 of file addr_mapper.hh.
References mapper, and AddrMapper::recvTimingReq().
bool AddrMapper::MapperSlavePort::recvTimingSnoopResp (PacketPtr pkt) [inline, protected, virtual]
Receive a timing snoop response from the master port.
Reimplemented from SlavePort.
Definition at line 186 of file addr_mapper.hh.
References mapper, and AddrMapper::recvTimingSnoopResp().
Member Data Documentation
AddrMapper& AddrMapper::MapperSlavePort::mapper [private]
Definition at line 203 of file addr_mapper.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), recvRespRetry(), recvTimingReq(), and recvTimingSnoopResp().
The documentation for this class was generated from the following file:
mem/addr_mapper.hh