gem5: PortProxy Class Reference
PortProxy Class Reference
This object is a proxy for a structural port, to be used for debug accesses.
#include <port_proxy.hh>
Public Member Functions
PortProxy (MasterPort &port, unsigned int cacheLineSize)
virtual ~PortProxy ()
virtual void readBlob (Addr addr, uint8_t *p, int size) const
Read size bytes memory at address and store in p.
virtual void writeBlob (Addr addr, const uint8_t *p, int size) const
Write size bytes from p to address.
virtual void memsetBlob (Addr addr, uint8_t v, int size) const
Fill size bytes starting at addr with byte value val.
template<typename T >
T read (Addr address) const
Read sizeof(T) bytes from address and return as object T.
template<typename T >
void write (Addr address, T data) const
Write object T to address.
Private Attributes
MasterPort & _port
The actual physical port used by this proxy.
const unsigned int _cacheLineSize
Granularity of any transactions issued through this proxy.
Detailed Description
This object is a proxy for a structural port, to be used for debug accesses.
This proxy object is used when non structural entities (e.g. thread contexts, object file loaders) need access to the memory system. It calls the corresponding functions on the underlying structural port, and provides templatized convenience access functions.
The addresses are interpreted as physical addresses.
See also:
SETranslatingProxy
FSTranslatingProxy
Definition at line 84 of file port_proxy.hh.
Constructor & Destructor Documentation
PortProxy::PortProxy (MasterPort & port, unsigned int cacheLineSize) [inline]
Definition at line 95 of file port_proxy.hh.
virtual PortProxy::~PortProxy () [inline, virtual]
Definition at line 97 of file port_proxy.hh.
Member Function Documentation
void PortProxy::memsetBlob (Addr addr, uint8_t v, int size) const [virtual]
Fill size bytes starting at addr with byte value val.
Reimplemented in FSTranslatingPortProxy, and SETranslatingPortProxy.
Definition at line 70 of file port_proxy.cc.
References writeBlob().
Referenced by MultiLevelPageTable< ISAOps >::initState(), and MultiLevelPageTable< ISAOps >::walk().
template<typename T > T PortProxy::read (Addr address) const [inline]
Read sizeof(T) bytes from address and return as object T.
Definition at line 146 of file port_proxy.hh.
References readBlob().
Referenced by AlphaSystem::fixFuncEventAddr(), MultiLevelPageTable< ISAOps >::isUnmapped(), MultiLevelPageTable< ISAOps >::map(), MultiLevelPageTable< ISAOps >::remap(), MultiLevelPageTable< ISAOps >::unmap(), and MultiLevelPageTable< ISAOps >::walk().
void PortProxy::readBlob (Addr addr, uint8_t * p, int size) const [virtual]
Read size bytes memory at address and store in p.
Reimplemented in FSTranslatingPortProxy, and SETranslatingPortProxy.
Definition at line 44 of file port_proxy.cc.
References _cacheLineSize, _port, Request::funcMasterId, MemCmd::ReadReq, and MasterPort::sendFunctional().
Referenced by Linux::ThreadInfo::curThreadInfo(), read(), VirtQueue::VirtRing< struct vring_used_elem >::read(), VirtQueue::VirtRing< struct vring_used_elem >::readHeader(), MaltaPChip::translatePciToDma(), and TsunamiPChip::translatePciToDma().
template<typename T > void PortProxy::write (Addr address, T data) const [inline]
Write object T to address.
Writes sizeof(T) bytes.
Definition at line 155 of file port_proxy.hh.
References writeBlob().
Referenced by archPrctlFunc(), FreebsdAlphaSystem::doCalibrateClocks(), X86ISA::I386LiveProcess::initState(), AlphaSystem::initState(), LinuxAlphaSystem::initState(), MultiLevelPageTable< ISAOps >::map(), MultiLevelPageTable< ISAOps >::remap(), AlphaSystem::setAlphaAccess(), Tru64AlphaSystem::Tru64AlphaSystem(), MultiLevelPageTable< ISAOps >::unmap(), and MultiLevelPageTable< ISAOps >::walk().
void PortProxy::writeBlob (Addr addr, const uint8_t * p, int size) const [virtual]
Write size bytes from p to address.
Reimplemented in FSTranslatingPortProxy, and SETranslatingPortProxy.
Definition at line 57 of file port_proxy.cc.
References _cacheLineSize, _port, Request::funcMasterId, MasterPort::sendFunctional(), and MemCmd::WriteReq.
Referenced by X86ISA::X86_64LiveProcess::initState(), X86System::initState(), LinuxX86System::initState(), ArmSystem::initState(), LinuxArmSystem::initState(), HexFile::loadSections(), memsetBlob(), SimpleDisk::read(), write(), VirtQueue::VirtRing< struct vring_used_elem >::write(), VirtQueue::VirtRing< struct vring_used_elem >::writeHeader(), X86ISA::SMBios::SMBiosTable::writeOut(), X86ISA::SMBios::BiosInformation::writeOut(), X86ISA::SMBios::SMBiosStructure::writeOut(), X86ISA::IntelMP::BusHierarchy::writeOut(), X86ISA::IntelMP::Processor::writeOut(), X86ISA::IntelMP::ConfigTable::writeOut(), X86ISA::IntelMP::ExtConfigEntry::writeOut(), X86ISA::IntelMP::BaseConfigEntry::writeOut(), X86ISA::IntelMP::FloatingPointer::writeOut(), writeOutField(), writeOutString(), X86ISA::SMBios::SMBiosStructure::writeOutStrings(), X86ISA::E820Table::writeTo(), and writeVal().
Member Data Documentation
const unsigned int PortProxy::_cacheLineSize [private]
Granularity of any transactions issued through this proxy.
Definition at line 92 of file port_proxy.hh.
Referenced by readBlob(), and writeBlob().
MasterPort& PortProxy::_port [private]
The actual physical port used by this proxy.
Definition at line 89 of file port_proxy.hh.
Referenced by readBlob(), and writeBlob().
The documentation for this class was generated from the following files:
mem/port_proxy.hh
mem/port_proxy.cc