gem5: CheckerCPU Class Reference
CheckerCPU Class Reference
CheckerCPU class.
#include <cpu.hh>
Classes
union Result
Public Types
typedef CheckerCPUParams Params
Public Member Functions
virtual void init ()
CheckerCPU (Params *p)
virtual ~CheckerCPU ()
void setSystem (System *system)
void setIcachePort (MasterPort *icache_port)
void setDcachePort (MasterPort *dcache_port)
MasterPort & getDataPort ()
MasterPort & getInstPort ()
TheISA::TLB * getITBPtr ()
TheISA::TLB * getDTBPtr ()
virtual Counter totalInsts () const
virtual Counter totalOps () const
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
void setEA (Addr EA)
Record the effective address of the instruction.
Addr getEA () const
Get the effective address of the instruction.
IntReg readIntRegOperand (const StaticInst *si, int idx)
Reads an integer register.
FloatReg readFloatRegOperand (const StaticInst *si, int idx)
Reads a floating point register of single register width.
FloatRegBits readFloatRegOperandBits (const StaticInst *si, int idx)
Reads a floating point register in its binary format, instead of by value.
CCReg readCCRegOperand (const StaticInst *si, int idx)
template<class T >
void setResult (T t)
void setIntRegOperand (const StaticInst *si, int idx, IntReg val)
Sets an integer register to a value.
void setFloatRegOperand (const StaticInst *si, int idx, FloatReg val)
Sets a floating point register of single width to a value.
void setFloatRegOperandBits (const StaticInst *si, int idx, FloatRegBits val)
Sets the bits of a floating point register of single width to a binary value.
void setCCRegOperand (const StaticInst *si, int idx, CCReg val)
bool readPredicate ()
void setPredicate (bool val)
TheISA::PCState pcState () const
void pcState (const TheISA::PCState &val)
Addr instAddr ()
Addr nextInstAddr ()
MicroPC microPC ()
MiscReg readMiscRegNoEffect (int misc_reg) const
MiscReg readMiscReg (int misc_reg)
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
void setMiscRegNoEffect (int misc_reg, const MiscReg &val)
void setMiscReg (int misc_reg, const MiscReg &val)
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
MiscReg readMiscRegOperand (const StaticInst *si, int idx)
void setMiscRegOperand (const StaticInst *si, int idx, const MiscReg &val)
MiscReg readRegOtherThread (int misc_reg, ThreadID tid)
void setRegOtherThread (int misc_reg, MiscReg val, ThreadID tid)
void recordPCChange (const TheISA::PCState &val)
void demapPage (Addr vaddr, uint64_t asn)
Invalidate a page in the DTLB and ITLB.
virtual void armMonitor (Addr address)
bool mwait (PacketPtr pkt)
void mwaitAtomic (ThreadContext *tc)
AddressMonitor * getAddrMonitor ()
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
Fault readMem (Addr addr, uint8_t *data, unsigned size, unsigned flags)
Fault writeMem (uint8_t *data, unsigned size, Addr addr, unsigned flags, uint64_t *res)
unsigned int readStCondFailures () const
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned int sc_failures)
Sets the number of consecutive store conditional failures.
Fault hwrei ()
Somewhat Alpha-specific function that handles returning from an error or interrupt.
bool simPalCheck (int palFunc)
Check for special simulator handling of specific PAL calls.
void wakeup ()
void syscall (int64_t callnum)
Executes a syscall specified by the callnum.
void handleError ()
bool checkFlags (Request *unverified_req, Addr vAddr, Addr pAddr, int flags)
Checks if the flags set by the Checker and Checkee match.
void dumpAndExit ()
ThreadContext * tcBase ()
Returns a pointer to the ThreadContext.
SimpleThread * threadBase ()
Public Attributes
SimpleThread * thread
Counter numLoad
Counter startNumLoad
Result unverifiedResult
Request * unverifiedReq
uint8_t * unverifiedMemData
bool changedPC
bool willChangePC
TheISA::PCState newPCState
bool exitOnError
bool updateOnError
bool warnOnlyOnLoadError
InstSeqNum youngestSN
Protected Types
typedef TheISA::MachInst MachInst
typedef TheISA::FloatReg FloatReg
typedef TheISA::FloatRegBits FloatRegBits
typedef TheISA::MiscReg MiscReg
Protected Member Functions
Addr dbg_vtophys (Addr addr)
Protected Attributes
MasterID masterId
id attached to all issued requests
std::vector< Process * > workload
System * systemPtr
MasterPort * icachePort
MasterPort * dcachePort
ThreadContext * tc
TheISA::TLB * itb
TheISA::TLB * dtb
std::queue< Result > result
RequestPtr memReq
StaticInstPtr curStaticInst
StaticInstPtr curMacroStaticInst
Counter numInst
Counter startNumInst
std::queue< int > miscRegIdxs
Detailed Description
CheckerCPU class.
Dynamically verifies instructions as they are completed by making sure that the instruction and its results match the independent execution of the benchmark inside the checker. The checker verifies instructions in order, regardless of the order in which instructions complete. There are certain results that can not be verified, specifically the result of a store conditional or the values of uncached accesses. In these cases, and with instructions marked as "IsUnverifiable", the checker assumes that the value from the main CPU's execution is correct and simply copies that value. It provides a CheckerThreadContext (see checker/thread_context.hh) that provides hooks for updating the Checker's state through any ThreadContext accesses. This allows the checker to be able to correctly verify instructions, even with external accesses to the ThreadContext that change state.
Definition at line 90 of file cpu.hh.
Member Typedef Documentation
typedef TheISA::FloatReg CheckerCPU::FloatReg [protected]
Reimplemented from ExecContext.
Definition at line 94 of file cpu.hh.
typedef TheISA::FloatRegBits CheckerCPU::FloatRegBits [protected]
Reimplemented from ExecContext.
Definition at line 95 of file cpu.hh.
typedef TheISA::MachInst CheckerCPU::MachInst [protected]
Definition at line 93 of file cpu.hh.
typedef TheISA::MiscReg CheckerCPU::MiscReg [protected]
Reimplemented from ExecContext.
Definition at line 96 of file cpu.hh.
typedef CheckerCPUParams CheckerCPU::Params
Definition at line 103 of file cpu.hh.
Constructor & Destructor Documentation
CheckerCPU::CheckerCPU (Params * p)
Definition at line 67 of file cpu.cc.
References changedPC, curMacroStaticInst, curStaticInst, dtb, exitOnError, itb, memReq, numInst, numLoad, startNumInst, startNumLoad, updateOnError, warnOnlyOnLoadError, willChangePC, workload, and youngestSN.
CheckerCPU::~CheckerCPU () [virtual]
Definition at line 92 of file cpu.cc.
Member Function Documentation
virtual void CheckerCPU::armMonitor (Addr address) [inline, virtual]
Implements ExecContext.
Definition at line 353 of file cpu.hh.
bool CheckerCPU::checkFlags (Request * unverified_req, Addr vAddr, Addr pAddr, int flags)
Checks if the flags set by the Checker and Checkee match.
Definition at line 338 of file cpu.cc.
References Request::getFlags(), Request::getPaddr(), and Request::getVaddr().
Referenced by readMem(), and writeMem().
Addr CheckerCPU::dbg_vtophys (Addr addr) [protected]
Definition at line 329 of file cpu.cc.
References tc, and AlphaISA::vtophys().
void CheckerCPU::demapDataPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 364 of file cpu.hh.
References dtb.
void CheckerCPU::demapInstPage (Addr vaddr, uint64_t asn) [inline]
Definition at line 359 of file cpu.hh.
References itb.
void CheckerCPU::demapPage (Addr vaddr, uint64_t asn) [inline, virtual]
Invalidate a page in the DTLB and ITLB.
Implements ExecContext.
Definition at line 346 of file cpu.hh.
References dtb, and itb.
void CheckerCPU::dumpAndExit ()
Definition at line 355 of file cpu.cc.
References curTick(), panic, SimpleThread::pcState(), thread, and warn.
Referenced by Checker< Impl >::dumpAndExit(), Checker< O3CPUImpl >::handleError(), and handleError().
AddressMonitor* CheckerCPU::getAddrMonitor () [inline, virtual]
Implements ExecContext.
Definition at line 357 of file cpu.hh.
MasterPort& CheckerCPU::getDataPort () [inline]
Definition at line 113 of file cpu.hh.
References dcachePort.
TheISA::TLB* CheckerCPU::getDTBPtr () [inline]
Definition at line 176 of file cpu.hh.
References dtb.
Addr CheckerCPU::getEA () const [inline, virtual]
Get the effective address of the instruction.
Note:
Only valid for memory ops.
Implements ExecContext.
Definition at line 198 of file cpu.hh.
References panic.
MasterPort& CheckerCPU::getInstPort () [inline]
Definition at line 121 of file cpu.hh.
References icachePort.
TheISA::TLB* CheckerCPU::getITBPtr () [inline]
Definition at line 175 of file cpu.hh.
References itb.
void CheckerCPU::handleError () [inline]
Definition at line 388 of file cpu.hh.
References dumpAndExit(), and exitOnError.
Referenced by readMem(), Checker< Impl >::validateExecution(), Checker< Impl >::validateInst(), Checker< Impl >::verify(), and writeMem().
Fault CheckerCPU::hwrei () [inline, virtual]
Somewhat Alpha-specific function that handles returning from an error or interrupt.
Implements ExecContext.
Definition at line 381 of file cpu.hh.
References SimpleThread::hwrei(), and thread.
void CheckerCPU::init () [virtual]
Definition at line 62 of file cpu.cc.
References System::getMasterId(), masterId, name(), and systemPtr.
Addr CheckerCPU::instAddr () [inline]
Definition at line 283 of file cpu.hh.
References SimpleThread::instAddr(), and thread.
MicroPC CheckerCPU::microPC () [inline]
Definition at line 285 of file cpu.hh.
References SimpleThread::microPC(), and thread.
bool CheckerCPU::mwait (PacketPtr pkt) [inline, virtual]
Implements ExecContext.
Definition at line 354 of file cpu.hh.
void CheckerCPU::mwaitAtomic (ThreadContext * tc) [inline, virtual]
Implements ExecContext.
Definition at line 355 of file cpu.hh.
References SimpleThread::dtb, and thread.
Addr CheckerCPU::nextInstAddr () [inline]
Definition at line 284 of file cpu.hh.
References SimpleThread::nextInstAddr(), and thread.
void CheckerCPU::pcState (const TheISA::PCState & val) [inline, virtual]
Implements ExecContext.
Definition at line 277 of file cpu.hh.
References DPRINTF, SimpleThread::pcState(), and thread.
TheISA::PCState CheckerCPU::pcState () const [inline, virtual]
Implements ExecContext.
Definition at line 276 of file cpu.hh.
References SimpleThread::pcState(), and thread.
Referenced by Checker< Impl >::advancePC(), and Checker< Impl >::verify().
CCReg CheckerCPU::readCCRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 228 of file cpu.hh.
References AlphaISA::CC_Reg_Base, SimpleThread::readCCReg(), StaticInst::srcRegIdx(), and thread.
FloatReg CheckerCPU::readFloatRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register of single register width.
Implements ExecContext.
Definition at line 216 of file cpu.hh.
References AlphaISA::FP_Reg_Base, SimpleThread::readFloatReg(), StaticInst::srcRegIdx(), and thread.
FloatRegBits CheckerCPU::readFloatRegOperandBits (const StaticInst * si, int idx) [inline, virtual]
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 222 of file cpu.hh.
References AlphaISA::FP_Reg_Base, SimpleThread::readFloatRegBits(), StaticInst::srcRegIdx(), and thread.
IntReg CheckerCPU::readIntRegOperand (const StaticInst * si, int idx) [inline, virtual]
Reads an integer register.
Implements ExecContext.
Definition at line 211 of file cpu.hh.
References SimpleThread::readIntReg(), StaticInst::srcRegIdx(), and thread.
Fault CheckerCPU::readMem (Addr addr, uint8_t * data, unsigned size, unsigned flags)
Definition at line 142 of file cpu.cc.
References checkFlags(), ThreadContext::contextId(), Packet::createRead(), curTick(), Packet::dataStatic(), dcachePort, dtb, Request::getFlags(), Request::getPaddr(), Request::getVaddr(), handleError(), Request::isMmappedIpr(), Request::isPrefetch(), Flags< T >::isSet(), Request::isUncacheable(), masterId, memReq, Request::NO_ACCESS, SimpleThread::pcState(), BaseTLB::Read, roundDown(), MasterPort::sendFunctional(), tc, thread, unverifiedMemData, unverifiedReq, and warn.
MiscReg CheckerCPU::readMiscReg (int misc_reg) [inline, virtual]
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
Implements ExecContext.
Definition at line 293 of file cpu.hh.
References SimpleThread::readMiscReg(), and thread.
MiscReg CheckerCPU::readMiscRegNoEffect (int misc_reg) const [inline]
Definition at line 288 of file cpu.hh.
References SimpleThread::readMiscRegNoEffect(), and thread.
MiscReg CheckerCPU::readMiscRegOperand (const StaticInst * si, int idx) [inline, virtual]
Implements ExecContext.
Definition at line 312 of file cpu.hh.
References AlphaISA::Misc_Reg_Base, SimpleThread::readMiscReg(), StaticInst::srcRegIdx(), and thread.
bool CheckerCPU::readPredicate () [inline, virtual]
Implements ExecContext.
Definition at line 270 of file cpu.hh.
References SimpleThread::readPredicate(), and thread.
MiscReg CheckerCPU::readRegOtherThread (int misc_reg, ThreadID tid) [inline, virtual]
Implements ExecContext.
Definition at line 326 of file cpu.hh.
References panic.
unsigned int CheckerCPU::readStCondFailures () const [inline, virtual]
Returns the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 373 of file cpu.hh.
References SimpleThread::readStCondFailures(), and thread.
void CheckerCPU::recordPCChange (const TheISA::PCState & val) [inline]
Definition at line 340 of file cpu.hh.
References changedPC, and newPCState.
Referenced by CheckerThreadContext< TC >::pcState().
virtual void CheckerCPU::serialize (std::ostream & os) [virtual]
void CheckerCPU::setCCRegOperand (const StaticInst * si, int idx, CCReg val) [inline, virtual]
Implements ExecContext.
Definition at line 263 of file cpu.hh.
References AlphaISA::CC_Reg_Base, StaticInst::destRegIdx(), SimpleThread::setCCReg(), and thread.
void CheckerCPU::setDcachePort (MasterPort * dcache_port)
Definition at line 126 of file cpu.cc.
References dcachePort.
void CheckerCPU::setEA (Addr EA) [inline, virtual]
Record the effective address of the instruction.
Note:
Only valid for memory ops.
Implements ExecContext.
Definition at line 197 of file cpu.hh.
References panic.
void CheckerCPU::setFloatRegOperand (const StaticInst * si, int idx, FloatReg val) [inline, virtual]
Sets a floating point register of single width to a value.
Implements ExecContext.
Definition at line 248 of file cpu.hh.
References StaticInst::destRegIdx(), AlphaISA::FP_Reg_Base, SimpleThread::setFloatReg(), and thread.
void CheckerCPU::setFloatRegOperandBits (const StaticInst * si, int idx, FloatRegBits val) [inline, virtual]
Sets the bits of a floating point register of single width to a binary value.
Implements ExecContext.
Definition at line 255 of file cpu.hh.
References StaticInst::destRegIdx(), AlphaISA::FP_Reg_Base, SimpleThread::setFloatRegBits(), and thread.
void CheckerCPU::setIcachePort (MasterPort * icache_port)
Definition at line 120 of file cpu.cc.
References icachePort.
void CheckerCPU::setIntRegOperand (const StaticInst * si, int idx, IntReg val) [inline, virtual]
Sets an integer register to a value.
Implements ExecContext.
Definition at line 242 of file cpu.hh.
References StaticInst::destRegIdx(), SimpleThread::setIntReg(), and thread.
void CheckerCPU::setMiscReg (int misc_reg, const MiscReg & val) [inline, virtual]
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
Implements ExecContext.
Definition at line 305 of file cpu.hh.
References DPRINTF, miscRegIdxs, SimpleThread::setMiscReg(), and thread.
Referenced by setMiscRegOperand().
void CheckerCPU::setMiscRegNoEffect (int misc_reg, const MiscReg & val) [inline]
Definition at line 298 of file cpu.hh.
References DPRINTF, miscRegIdxs, SimpleThread::setMiscRegNoEffect(), and thread.
void CheckerCPU::setMiscRegOperand (const StaticInst * si, int idx, const MiscReg & val) [inline, virtual]
Implements ExecContext.
Definition at line 318 of file cpu.hh.
References StaticInst::destRegIdx(), AlphaISA::Misc_Reg_Base, and setMiscReg().
void CheckerCPU::setPredicate (bool val) [inline, virtual]
Implements ExecContext.
Definition at line 271 of file cpu.hh.
References SimpleThread::setPredicate(), and thread.
void CheckerCPU::setRegOtherThread (int misc_reg, MiscReg val, ThreadID tid) [inline, virtual]
Implements ExecContext.
Definition at line 332 of file cpu.hh.
References panic.
template<class T > void CheckerCPU::setResult (T t) [inline]
Definition at line 235 of file cpu.hh.
References result, and CheckerCPU::Result::set().
void CheckerCPU::setStCondFailures (unsigned int sc_failures) [inline, virtual]
Sets the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 377 of file cpu.hh.
void CheckerCPU::setSystem (System * system)
Definition at line 97 of file cpu.cc.
References dtb, FullSystem, SimpleThread::getTC(), itb, ThreadState::kernelStats, MipsISA::p, systemPtr, tc, thread, and workload.
Referenced by BaseSimpleCPU::BaseSimpleCPU().
bool CheckerCPU::simPalCheck (int palFunc) [inline, virtual]
Check for special simulator handling of specific PAL calls.
If return value is false, actual PAL call will be suppressed.
Implements ExecContext.
Definition at line 382 of file cpu.hh.
References SimpleThread::simPalCheck(), and thread.
void CheckerCPU::syscall (int64_t callnum) [inline, virtual]
Executes a syscall specified by the callnum.
Implements ExecContext.
Definition at line 386 of file cpu.hh.
ThreadContext* CheckerCPU::tcBase () [inline, virtual]
Returns a pointer to the ThreadContext.
Implements ExecContext.
Definition at line 399 of file cpu.hh.
References tc.
SimpleThread* CheckerCPU::threadBase () [inline]
Definition at line 400 of file cpu.hh.
References thread.
virtual Counter CheckerCPU::totalInsts () const [inline, virtual]
Definition at line 178 of file cpu.hh.
virtual Counter CheckerCPU::totalOps () const [inline, virtual]
Definition at line 183 of file cpu.hh.
virtual void CheckerCPU::unserialize (Checkpoint * cp, const std::string & section) [virtual]
void CheckerCPU::wakeup () [inline]
Reimplemented from BaseCPU.
Definition at line 383 of file cpu.hh.
Fault CheckerCPU::writeMem (uint8_t * data, unsigned size, Addr addr, unsigned flags, uint64_t * res)
Definition at line 227 of file cpu.cc.
References Request::CACHE_BLOCK_ZERO, checkFlags(), ThreadContext::contextId(), curTick(), dtb, Request::extraDataValid(), Request::getExtraData(), Request::getFlags(), Request::getPaddr(), Request::getVaddr(), handleError(), Request::isPrefetch(), masterId, memReq, SimpleThread::pcState(), roundDown(), tc, thread, unverifiedMemData, unverifiedReq, warn, and BaseTLB::Write.
Member Data Documentation
bool CheckerCPU::changedPC
Definition at line 406 of file cpu.hh.
Referenced by CheckerCPU(), recordPCChange(), Checker< Impl >::validateInst(), and Checker< Impl >::verify().
StaticInstPtr CheckerCPU::curMacroStaticInst [protected]
Definition at line 162 of file cpu.hh.
Referenced by Checker< Impl >::advancePC(), CheckerCPU(), Checker< Impl >::handlePendingInt(), and Checker< Impl >::verify().
StaticInstPtr CheckerCPU::curStaticInst [protected]
Definition at line 161 of file cpu.hh.
Referenced by Checker< Impl >::advancePC(), CheckerCPU(), Checker< Impl >::handlePendingInt(), Checker< Impl >::validateInst(), Checker< Impl >::validateState(), and Checker< Impl >::verify().
MasterPort* CheckerCPU::dcachePort [protected]
Definition at line 136 of file cpu.hh.
Referenced by getDataPort(), readMem(), and setDcachePort().
TheISA::TLB* CheckerCPU::dtb [protected]
Definition at line 141 of file cpu.hh.
Referenced by CheckerCPU(), demapDataPage(), demapPage(), getDTBPtr(), readMem(), setSystem(), and writeMem().
bool CheckerCPU::exitOnError
Definition at line 409 of file cpu.hh.
Referenced by CheckerCPU(), Checker< O3CPUImpl >::handleError(), and handleError().
MasterPort* CheckerCPU::icachePort [protected]
Definition at line 135 of file cpu.hh.
Referenced by getInstPort(), setIcachePort(), and Checker< Impl >::verify().
TheISA::TLB* CheckerCPU::itb [protected]
Definition at line 140 of file cpu.hh.
Referenced by CheckerCPU(), demapInstPage(), demapPage(), getITBPtr(), setSystem(), and Checker< Impl >::verify().
MasterID CheckerCPU::masterId [protected]
id attached to all issued requests
Definition at line 99 of file cpu.hh.
Referenced by init(), readMem(), Checker< Impl >::verify(), and writeMem().
RequestPtr CheckerCPU::memReq [protected]
Definition at line 159 of file cpu.hh.
Referenced by CheckerCPU(), readMem(), Checker< Impl >::verify(), and writeMem().
std::queue<int> CheckerCPU::miscRegIdxs [protected]
Definition at line 168 of file cpu.hh.
Referenced by setMiscReg(), setMiscRegNoEffect(), and Checker< Impl >::validateExecution().
TheISA::PCState CheckerCPU::newPCState
Definition at line 408 of file cpu.hh.
Referenced by recordPCChange(), and Checker< Impl >::verify().
Counter CheckerCPU::numInst [protected]
Definition at line 165 of file cpu.hh.
Referenced by CheckerCPU(), and Checker< Impl >::verify().
Counter CheckerCPU::numLoad
Definition at line 189 of file cpu.hh.
Referenced by CheckerCPU(), and Checker< Impl >::verify().
std::queue<Result> CheckerCPU::result [protected]
Definition at line 156 of file cpu.hh.
Referenced by setResult(), Checker< Impl >::validateExecution(), and Checker< Impl >::verify().
Counter CheckerCPU::startNumInst [protected]
Definition at line 166 of file cpu.hh.
Referenced by CheckerCPU().
Counter CheckerCPU::startNumLoad
Definition at line 190 of file cpu.hh.
Referenced by CheckerCPU().
System* CheckerCPU::systemPtr [protected]
Definition at line 133 of file cpu.hh.
Referenced by init(), and setSystem().
ThreadContext* CheckerCPU::tc [protected]
Definition at line 138 of file cpu.hh.
Referenced by Checker< Impl >::advancePC(), dbg_vtophys(), readMem(), setSystem(), tcBase(), Checker< Impl >::verify(), and writeMem().
SimpleThread* CheckerCPU::thread
Definition at line 173 of file cpu.hh.
Referenced by Checker< Impl >::advancePC(), Checker< Impl >::copyResult(), dumpAndExit(), Checker< Impl >::handlePendingInt(), hwrei(), instAddr(), microPC(), mwaitAtomic(), nextInstAddr(), pcState(), readCCRegOperand(), readFloatRegOperand(), readFloatRegOperandBits(), readIntRegOperand(), readMem(), readMiscReg(), readMiscRegNoEffect(), readMiscRegOperand(), readPredicate(), readStCondFailures(), setCCRegOperand(), setFloatRegOperand(), setFloatRegOperandBits(), setIntRegOperand(), setMiscReg(), setMiscRegNoEffect(), setPredicate(), setSystem(), simPalCheck(), threadBase(), Checker< Impl >::validateExecution(), Checker< Impl >::validateInst(), Checker< Impl >::validateState(), Checker< Impl >::verify(), and writeMem().
uint8_t* CheckerCPU::unverifiedMemData
Definition at line 404 of file cpu.hh.
Referenced by readMem(), Checker< Impl >::verify(), and writeMem().
Request* CheckerCPU::unverifiedReq
Definition at line 403 of file cpu.hh.
Referenced by readMem(), Checker< Impl >::verify(), and writeMem().
Result CheckerCPU::unverifiedResult
Definition at line 402 of file cpu.hh.
bool CheckerCPU::updateOnError
Definition at line 410 of file cpu.hh.
Referenced by CheckerCPU(), and Checker< O3CPUImpl >::handleError().
bool CheckerCPU::warnOnlyOnLoadError
Definition at line 411 of file cpu.hh.
Referenced by CheckerCPU(), and Checker< Impl >::validateExecution().
bool CheckerCPU::willChangePC
Definition at line 407 of file cpu.hh.
Referenced by CheckerCPU(), and Checker< Impl >::verify().
std::vector<Process*> CheckerCPU::workload [protected]
Definition at line 131 of file cpu.hh.
Referenced by CheckerCPU(), and setSystem().
InstSeqNum CheckerCPU::youngestSN
Definition at line 413 of file cpu.hh.
Referenced by CheckerCPU(), and Checker< Impl >::verify().
The documentation for this class was generated from the following files:
cpu/checker/cpu.hh
cpu/checker/cpu.cc