gem5: InsertionProfiler Class Reference
InsertionProfiler Class Reference
#include <insertion.hh>
Public Member Functions
InsertionProfiler (std::string name)
std::string name ()
virtual void regStats ()
virtual void insert (Addr addr)
virtual void access (Addr addr)
virtual void victim (Addr addr)
virtual void sampling ()
void finalize ()
Private Attributes
AddressTable ins_table
Stats::Scalar insertionDeadVerified
Stats::Scalar insertionDeadLeft
Stats::Scalar insertionReusable
Stats::Formula insertionDead
Detailed Description
Definition at line 16 of file insertion.hh.
Constructor & Destructor Documentation
InsertionProfiler::InsertionProfiler (std::string name)
Definition at line 6 of file insertion.cc.
References inform, name(), and registerExitCallback().
Member Function Documentation
void InsertionProfiler::access (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 46 of file insertion.cc.
References AddressTable::erase(), AddressTable::exists(), ins_table, and insertionReusable.
void InsertionProfiler::finalize ()
Definition at line 62 of file insertion.cc.
References ins_table, insertionDeadLeft, and AddressTable::size().
void InsertionProfiler::insert (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 40 of file insertion.cc.
References AddressTable::exists(), ins_table, and AddressTable::insert().
std::string InsertionProfiler::name () [inline]
Reimplemented from BaseTagsProfiler.
Definition at line 29 of file insertion.hh.
Referenced by InsertionProfiler(), and regStats().
void InsertionProfiler::regStats () [virtual]
Reimplemented from BaseTagsProfiler.
Definition at line 14 of file insertion.cc.
References insertionDead, insertionDeadLeft, insertionDeadVerified, insertionReusable, name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::total.
virtual void InsertionProfiler::sampling () [inline, virtual]
Implements BaseTagsProfiler.
Definition at line 37 of file insertion.hh.
void InsertionProfiler::victim (Addr addr) [virtual]
Implements BaseTagsProfiler.
Definition at line 54 of file insertion.cc.
References AddressTable::erase(), AddressTable::exists(), ins_table, and insertionDeadVerified.
Member Data Documentation
AddressTable InsertionProfiler::ins_table [private]
Definition at line 19 of file insertion.hh.
Referenced by access(), finalize(), insert(), and victim().
Stats::Formula InsertionProfiler::insertionDead [private]
Definition at line 24 of file insertion.hh.
Referenced by regStats().
Stats::Scalar InsertionProfiler::insertionDeadLeft [private]
Definition at line 22 of file insertion.hh.
Referenced by finalize(), and regStats().
Stats::Scalar InsertionProfiler::insertionDeadVerified [private]
Definition at line 21 of file insertion.hh.
Referenced by regStats(), and victim().
Stats::Scalar InsertionProfiler::insertionReusable [private]
Definition at line 23 of file insertion.hh.
Referenced by access(), and regStats().
The documentation for this class was generated from the following files:
mem/cache/tags/prof/insertion.hh
mem/cache/tags/prof/insertion.cc