gem5: ArmISA::SystemError Class Reference
ArmISA::SystemError Class Reference
System error (AArch64 only).
#include <faults.hh>
Public Member Functions
SystemError ()
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
bool routeToMonitor (ThreadContext *tc) const
bool routeToHyp (ThreadContext *tc) const
Detailed Description
System error (AArch64 only).
Definition at line 532 of file faults.hh.
Constructor & Destructor Documentation
ArmISA::SystemError::SystemError ()
Definition at line 1350 of file faults.cc.
Member Function Documentation
void ArmISA::SystemError::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 1354 of file faults.cc.
References ThreadContext::getCpuPtr(), and ArmISA::INT_ABT.
bool ArmISA::SystemError::routeToHyp (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFault.
Definition at line 1370 of file faults.cc.
References ArmISA::cpsr, ArmISA::ArmFault::from64, ArmISA::inSecureState(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR, ArmISA::MISCREG_SCR_EL3, ThreadContext::readMiscRegNoEffect(), and ArmISA::scr.
bool ArmISA::SystemError::routeToMonitor (ThreadContext * tc) const [virtual]
Reimplemented from ArmISA::ArmFaultVals< SystemError >.
Definition at line 1361 of file faults.cc.
References ArmISA::ArmFault::from64, ArmSystem::haveSecurity(), ArmISA::MISCREG_SCR_EL3, ThreadContext::readMiscRegNoEffect(), and ArmISA::scr.
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc