gem5: Stats::SparseHistStor Class Reference
Stats::SparseHistStor Class Reference
["Statistic Types"]
Templatized storage and interface for a sparse histogram stat.
#include <statistics.hh>
Classes
struct Params
The parameters for a sparse histogram stat.
Public Member Functions
SparseHistStor (Info *info)
void sample (Counter val, int number)
Add a value to the distribution for the given number of times.
size_type size () const
Return the number of buckets in this distribution.
bool zero () const
Returns true if any calls to sample have been made.
void prepare (Info *info, SparseHistData &data)
void reset (Info *info)
Reset stat value to default.
Private Attributes
Counter samples
Counter for number of samples.
MCounter cmap
Counter for each bucket.
Detailed Description
Templatized storage and interface for a sparse histogram stat.
Definition at line 2782 of file statistics.hh.
Constructor & Destructor Documentation
Stats::SparseHistStor::SparseHistStor (Info * info) [inline]
Definition at line 2798 of file statistics.hh.
References reset().
Member Function Documentation
void Stats::SparseHistStor::prepare (Info * info, SparseHistData & data) [inline]
Definition at line 2832 of file statistics.hh.
References cmap, Stats::SparseHistData::cmap, samples, and Stats::SparseHistData::samples.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::prepare().
void Stats::SparseHistStor::reset (Info * info) [inline]
Reset stat value to default.
Definition at line 2847 of file statistics.hh.
References cmap, and samples.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::reset(), and SparseHistStor().
void Stats::SparseHistStor::sample (Counter val, int number) [inline]
Add a value to the distribution for the given number of times.
Parameters:
val The value to add.
number The number of times to add the value.
Definition at line 2809 of file statistics.hh.
References cmap, and samples.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::sample().
size_type Stats::SparseHistStor::size () const [inline]
Return the number of buckets in this distribution.
Returns:
the number of buckets.
Definition at line 2819 of file statistics.hh.
References cmap.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::size().
bool Stats::SparseHistStor::zero () const [inline]
Returns true if any calls to sample have been made.
Returns:
True if any values have been sampled.
Definition at line 2826 of file statistics.hh.
References samples.
Referenced by Stats::SparseHistBase< SparseHistogram, SparseHistStor >::zero().
Member Data Documentation
MCounter Stats::SparseHistStor::cmap [private]
Counter for each bucket.
Definition at line 2795 of file statistics.hh.
Referenced by prepare(), reset(), sample(), and size().
Counter Stats::SparseHistStor::samples [private]
Counter for number of samples.
Definition at line 2793 of file statistics.hh.
Referenced by prepare(), reset(), sample(), and zero().
The documentation for this class was generated from the following file:
base/statistics.hh