gem5: VirtIOConsole::TermRecvQueue Class Reference
VirtIOConsole::TermRecvQueue Class Reference
Virtqueue for data going from the host to the guest.
#include <console.hh>
Public Member Functions
TermRecvQueue (PortProxy &proxy, uint16_t size, VirtIOConsole &_parent)
virtual ~TermRecvQueue ()
void onNotify ()
Notify queue of pending events.
void trySend ()
Try to send data pending data from the terminal.
std::string name () const
Protected Attributes
VirtIOConsole & parent
Detailed Description
Virtqueue for data going from the host to the guest.
Definition at line 107 of file console.hh.
Constructor & Destructor Documentation
VirtIOConsole::TermRecvQueue::TermRecvQueue (PortProxy & proxy, uint16_t size, VirtIOConsole & _parent) [inline]
Definition at line 111 of file console.hh.
virtual VirtIOConsole::TermRecvQueue::~TermRecvQueue () [inline, virtual]
Definition at line 113 of file console.hh.
Member Function Documentation
std::string VirtIOConsole::TermRecvQueue::name () const [inline]
Definition at line 120 of file console.hh.
References SimObject::name(), and parent.
void VirtIOConsole::TermRecvQueue::onNotify () [inline, virtual]
Notify queue of pending events.
This method is called by VirtIODeviceBase::onNotify() to notify the device model of pending data in a virtqueue. The default implementation of this method iterates over the available descriptor chains and calls onNotifyDescriptor() for every new incoming chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented from VirtQueue.
Definition at line 115 of file console.hh.
References trySend().
void VirtIOConsole::TermRecvQueue::trySend ()
Try to send data pending data from the terminal.
Definition at line 76 of file console.cc.
References VirtDescriptor::chainWrite(), VirtQueue::consumeDescriptor(), ArmISA::d, Terminal::dataAvailable(), DPRINTF, Terminal::in(), VirtIODeviceBase::kick(), ArmISA::len, parent, VirtQueue::produceDescriptor(), VirtDescriptor::size(), and VirtIOConsole::term.
Referenced by onNotify().
Member Data Documentation
VirtIOConsole& VirtIOConsole::TermRecvQueue::parent [protected]
Definition at line 123 of file console.hh.
Referenced by name(), and trySend().
The documentation for this class was generated from the following files:
dev/virtio/console.hh
dev/virtio/console.cc