gem5: EnergyCtrl Class Reference
EnergyCtrl Class Reference
#include <energy_ctrl.hh>
Public Types
enum Registers {
DVFS_HANDLER_STATUS = 0, DVFS_NUM_DOMAINS, DVFS_DOMAINID_AT_INDEX, DVFS_HANDLER_TRANS_LATENCY,
DOMAIN_ID, PERF_LEVEL, PERF_LEVEL_ACK, NUM_OF_PERF_LEVELS,
PERF_LEVEL_TO_READ, FREQ_AT_PERF_LEVEL, VOLT_AT_PERF_LEVEL, PIO_NUM_FIELDS
}
Discovery flows: ---------------- * get basic DVFS handler information read(DVFS_HANDLER_STATUS) read(DVFS_HANDLER_TRANS_LATENCY).
typedef EnergyCtrlParams Params
Public Member Functions
EnergyCtrl (const Params *p)
virtual Tick read (PacketPtr pkt)
Read command sent to the device.
virtual Tick write (PacketPtr pkt)
Write command sent to the device.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
void startup ()
startup() is the final initialization call before simulation.
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
Private Member Functions
void updatePLAck ()
Update the acknowledgment that is read back by the software to confirm newly requested performance level has been set.
Static Private Member Functions
static uint32_t ticksTokHz (Tick period)
static uint32_t toMicroVolt (double voltage)
Private Attributes
DVFSHandler * dvfsHandler
uint32_t domainID
Cluster ID (DOMAIN_ID) R/W register, programmed to ID of the domain for which the set/get performance level command can be issued.
uint32_t domainIDIndexToRead
Index for getting the domain ID from the domain ID list available with the DVFS handler.
uint32_t perfLevelAck
Acknowledgment (PERF_LEVEL_ACK) RO register, software polls this register to read back the status of the last programmed change in the domain ID and/or the performance level.
uint32_t perfLevelToRead
EventWrapper< EnergyCtrl,&EnergyCtrl::updatePLAck > updateAckEvent
Detailed Description
Definition at line 65 of file energy_ctrl.hh.
Member Typedef Documentation
typedef EnergyCtrlParams EnergyCtrl::Params
Reimplemented from BasicPioDevice.
Definition at line 119 of file energy_ctrl.hh.
Member Enumeration Documentation
enum EnergyCtrl::Registers
Discovery flows: ---------------- * get basic DVFS handler information read(DVFS_HANDLER_STATUS) read(DVFS_HANDLER_TRANS_LATENCY).
* get the number of domain IDs read(DVFS_NUM_DOMAINS) -> domains
* query the driver to get the IDs for all i in domains write(DVFS_DOMAINID_AT_INDEX <- i) read(DOMAIN_ID) -> domainID_i
* for each domainID i get voltage / frequency pairs write(DOMAIN_ID <- domainID_i) read(NUM_OF_PERF_LEVELS) -> levels_i * for each l in levels_i write(PERF_LEVEL_TO_READ <- l) read(FREQ_AT_PERF_LEVEL) -> freq_l_i read(VOLT_AT_PERF_LEVEL) -> volt_l_i
Setting a specific performance level (V/F combination) ------------------------------------------------------ * get performance for domain_ID i write(DOMAIN_ID <- i) read(PERF_LEVEL) -> perf_level_i
* set performance for domain_ID i write(DOMAIN_ID <- i) write(PERF_LEVEL <- perf_level_i) * wait for DVFS transition completion while (!read(PERF_LEVEL_ACK));
Enumerator:
DVFS_HANDLER_STATUS
DVFS_NUM_DOMAINS
DVFS_DOMAINID_AT_INDEX
DVFS_HANDLER_TRANS_LATENCY
DOMAIN_ID
PERF_LEVEL
PERF_LEVEL_ACK
NUM_OF_PERF_LEVELS
PERF_LEVEL_TO_READ
FREQ_AT_PERF_LEVEL
VOLT_AT_PERF_LEVEL
PIO_NUM_FIELDS
Definition at line 104 of file energy_ctrl.hh.
Constructor & Destructor Documentation
EnergyCtrl::EnergyCtrl (const Params * p)
Definition at line 49 of file energy_ctrl.cc.
References fatal_if.
Member Function Documentation
void EnergyCtrl::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from PioDevice.
Definition at line 260 of file energy_ctrl.cc.
Tick EnergyCtrl::read (PacketPtr pkt) [virtual]
Read command sent to the device.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 63 of file energy_ctrl.cc.
References DVFSHandler::clkPeriodAtPerfLevel(), DOMAIN_ID, domainID, DVFSHandler::domainID(), domainIDIndexToRead, DPRINTF, DVFS_DOMAINID_AT_INDEX, DVFS_HANDLER_STATUS, DVFS_HANDLER_TRANS_LATENCY, DVFS_NUM_DOMAINS, dvfsHandler, FREQ_AT_PERF_LEVEL, Packet::getAddr(), Packet::getSize(), DVFSHandler::isEnabled(), Packet::makeAtomicResponse(), SimClock::Int::ns, NUM_OF_PERF_LEVELS, DVFSHandler::numDomains(), DVFSHandler::numPerfLevels(), panic, PERF_LEVEL, PERF_LEVEL_ACK, DVFSHandler::perfLevel(), perfLevelAck, perfLevelToRead, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, X86ISA::reg, Packet::set(), ticksTokHz(), toMicroVolt(), DVFSHandler::transLatency(), VOLT_AT_PERF_LEVEL, DVFSHandler::voltageAtPerfLevel(), and warn_once.
void EnergyCtrl::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 219 of file energy_ctrl.cc.
References domainID, domainIDIndexToRead, perfLevelAck, perfLevelToRead, Event::scheduled(), SERIALIZE_SCALAR, updateAckEvent, and Event::when().
void EnergyCtrl::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 252 of file energy_ctrl.cc.
References dvfsHandler, DVFSHandler::isEnabled(), and warn.
static uint32_t EnergyCtrl::ticksTokHz (Tick period) [inline, static, private]
Definition at line 169 of file energy_ctrl.hh.
References SimClock::Int::ms.
Referenced by read().
static uint32_t EnergyCtrl::toMicroVolt (double voltage) [inline, static, private]
Definition at line 173 of file energy_ctrl.hh.
Referenced by read().
void EnergyCtrl::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 231 of file energy_ctrl.cc.
References domainID, domainIDIndexToRead, perfLevelAck, perfLevelToRead, EventManager::schedule(), UNSERIALIZE_SCALAR, and updateAckEvent.
void EnergyCtrl::updatePLAck () [inline, private]
Update the acknowledgment that is read back by the software to confirm newly requested performance level has been set.
Definition at line 181 of file energy_ctrl.hh.
References perfLevelAck.
Tick EnergyCtrl::write (PacketPtr pkt) [virtual]
Write command sent to the device.
Parameters:
pkt Packet describing this request
Returns:
number of ticks it took to complete
Implements PioDevice.
Definition at line 149 of file energy_ctrl.cc.
References curTick(), EventManager::deschedule(), DOMAIN_ID, domainID, domainIDIndexToRead, DPRINTF, DVFS_DOMAINID_AT_INDEX, dvfsHandler, Packet::get(), Packet::getAddr(), Packet::getSize(), DVFSHandler::isEnabled(), Packet::makeAtomicResponse(), panic, PERF_LEVEL, PERF_LEVEL_TO_READ, DVFSHandler::perfLevel(), perfLevelToRead, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, X86ISA::reg, EventManager::schedule(), Event::scheduled(), DVFSHandler::transLatency(), updateAckEvent, DVFSHandler::validDomainID(), and warn_once.
Member Data Documentation
uint32_t EnergyCtrl::domainID [private]
Cluster ID (DOMAIN_ID) R/W register, programmed to ID of the domain for which the set/get performance level command can be issued.
Definition at line 148 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
uint32_t EnergyCtrl::domainIDIndexToRead [private]
Index for getting the domain ID from the domain ID list available with the DVFS handler.
Definition at line 154 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
DVFSHandler* EnergyCtrl::dvfsHandler [private]
Definition at line 142 of file energy_ctrl.hh.
Referenced by read(), startup(), and write().
uint32_t EnergyCtrl::perfLevelAck [private]
Acknowledgment (PERF_LEVEL_ACK) RO register, software polls this register to read back the status of the last programmed change in the domain ID and/or the performance level.
Valid values are: '0' - Ack is not OK yet '1' - Ack is OK It is a read destructive register with a read of '1' resets the ack to '0'.
Definition at line 165 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and updatePLAck().
uint32_t EnergyCtrl::perfLevelToRead [private]
Definition at line 167 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
EventWrapper<EnergyCtrl, &EnergyCtrl::updatePLAck> EnergyCtrl::updateAckEvent [private]
Definition at line 185 of file energy_ctrl.hh.
Referenced by serialize(), unserialize(), and write().
The documentation for this class was generated from the following files:
dev/arm/energy_ctrl.hh
dev/arm/energy_ctrl.cc