gem5: Cache Class Reference
Cache Class Reference
A template-policy based cache.
#include <cache.hh>
Classes
class CacheReqPacketQueue
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
class CpuSidePort
The CPU-side port extends the base cache slave port with access functions for functional, atomic and timing requests.
class MemSidePort
The memory-side port extends the base cache master port with access functions for functional, atomic and timing snoops.
Public Types
typedef std::list< CacheBlk * > BlkList
A typedef for a list of CacheBlk pointers.
Public Member Functions
Cache (const Params *p)
Instantiates a basic cache object.
virtual ~Cache ()
Non-default destructor is needed to deallocate memory.
void regStats ()
Register stats for this object.
virtual void serialize (std::ostream &os)
serialize the state of the caches We currently don't support checkpointing cache state, so this panics.
void unserialize (Checkpoint *cp, const std::string &section)
Public Attributes
Cacti * cacti
Protected Member Functions
void promoteWholeLineWrites (PacketPtr pkt)
Turn line-sized writes into WriteInvalidate transactions.
bool access (PacketPtr pkt, CacheBlk *&blk, Cycles &lat, PacketList &writebacks)
Does all the processing necessary to perform the provided request.
void cmpAndSwap (CacheBlk *blk, PacketPtr pkt)
Handle doing the Compare and Swap function for SPARC.
CacheBlk * allocateBlock (Addr addr, bool is_secure, PacketList &writebacks)
Find a block frame for new block at address addr targeting the given security space, assuming that the block is not currently in the cache.
CacheBlk * handleFill (PacketPtr pkt, CacheBlk *blk, PacketList &writebacks)
Populates a cache block and handles all outstanding requests for the satisfied fill request.
bool recvTimingReq (PacketPtr pkt)
Performs the access specified by the request.
void recvTimingResp (PacketPtr pkt)
Handles a response (cache line fill/write ack) from the bus.
void recvTimingSnoopReq (PacketPtr pkt)
Snoops bus transactions to maintain coherence.
void recvTimingSnoopResp (PacketPtr pkt)
Handle a snoop response.
Tick recvAtomic (PacketPtr pkt)
Performs the access specified by the request.
Tick recvAtomicSnoop (PacketPtr pkt)
Snoop for the provided request in the cache and return the estimated time taken.
void functionalAccess (PacketPtr pkt, bool fromCpuSide)
Performs the access specified by the request.
void satisfyCpuSideRequest (PacketPtr pkt, CacheBlk *blk, bool deferred_response=false, bool pending_downgrade=false)
bool satisfyMSHR (MSHR *mshr, PacketPtr pkt, CacheBlk *blk)
void doTimingSupplyResponse (PacketPtr req_pkt, const uint8_t *blk_data, bool already_copied, bool pending_inval)
void handleSnoop (PacketPtr ptk, CacheBlk *blk, bool is_timing, bool is_deferred, bool pending_inval)
Sets the blk to the new state.
PacketPtr writebackBlk (CacheBlk *blk)
Create a writeback request for the given block.
void memWriteback ()
Write back dirty blocks in the cache using functional accesses.
void memInvalidate ()
Invalidates all blocks in the cache.
bool isDirty () const
Determine if there are any dirty blocks in the cache.
bool writebackVisitor (CacheBlk &blk)
Cache block visitor that writes back dirty cache blocks using functional writes.
bool invalidateVisitor (CacheBlk &blk)
Cache block visitor that invalidates all blocks in the cache.
void squash (int threadNum)
Squash all requests associated with specified thread.
PacketPtr getBusPacket (PacketPtr cpu_pkt, CacheBlk *blk, bool needsExclusive) const
Generate an appropriate downstream bus request packet for the given parameters.
MSHR * getNextMSHR ()
Return the next MSHR to service, either a pending miss from the mshrQueue, a buffered write from the write buffer, or something from the prefetcher.
PacketPtr getTimingPacket ()
Selects an outstanding request to service.
void markInService (MSHR *mshr, bool pending_dirty_resp)
Marks a request as in service (sent on the bus).
bool outstandingMisses () const
Return whether there are any outstanding misses.
CacheBlk * findBlock (Addr addr, bool is_secure) const
bool inCache (Addr addr, bool is_secure) const
bool inMissQueue (Addr addr, bool is_secure) const
Tick nextMSHRReadyTime () const
Find next request ready time from among possible sources.
Protected Attributes
BaseTags * tags
Tag and data Storage.
BasePrefetcher * prefetcher
Prefetcher.
CacheBlk * tempBlock
Temporary cache block for occasional transitory use.
const bool doFastWrites
This cache should allocate a block on a line-sized write miss.
const bool prefetchOnAccess
Notify the prefetcher on every access, not just misses.
std::vector< PacketPtr > pendingDelete
Detailed Description
A template-policy based cache.
The behavior of the cache can be altered by supplying different template policies. TagStore handles all tag and data storage
See also:
TagStore, gem5 Memory System
Definition at line 74 of file cache.hh.
Member Typedef Documentation
typedef std::list<CacheBlk*> Cache::BlkList
A typedef for a list of CacheBlk pointers.
Definition at line 79 of file cache.hh.
Constructor & Destructor Documentation
Cache::Cache (const Params * p)
Instantiates a basic cache object.
Definition at line 71 of file cache_impl.hh.
References BaseCache::blkSize, cacti, BaseCache::cpuSidePort, CacheBlk::data, BaseCache::memSidePort, prefetcher, BasePrefetcher::setCache(), BaseTags::setCache(), tags, and tempBlock.
Cache::~Cache () [virtual]
Non-default destructor is needed to deallocate memory.
Definition at line 100 of file cache_impl.hh.
References BaseCache::cpuSidePort, CacheBlk::data, BaseCache::memSidePort, and tempBlock.
Member Function Documentation
bool Cache::access (PacketPtr pkt, CacheBlk *& blk, Cycles & lat, PacketList & writebacks) [protected]
Does all the processing necessary to perform the provided request.
Parameters:
pkt The memory request to perform.
blk The cache block to be updated.
lat The latency of the access.
writebacks List for any writebacks that need to be performed.
Returns:
Boolean indicating whether the request was satisfied.
Definition at line 311 of file cache_impl.hh.
References BaseTags::accessBlock(), allocateBlock(), BlkDirty, BlkReadable, BlkSecure, BaseCache::blkSize, BlkValid, BlkWritable, cacti, BaseTags::clearLocks(), Packet::cmd, Packet::cmdString(), Request::contextId(), CacheBlk::data, DPRINTF, BaseTags::findBlock(), Packet::getAddr(), Packet::getConstPtr(), Packet::getSize(), Request::hasContextId(), BaseCache::incHitCount(), BaseCache::incMissCount(), BaseTags::insertBlock(), CacheBlk::invalidate(), BaseTags::invalidate(), Request::isClearLL(), CacheBlk::isDirty(), Request::isInstFetch(), Packet::isLLSC(), CacheBlk::isReadable(), Packet::isRequest(), Packet::isSecure(), Packet::isSupplyExclusive(), Request::isUncacheable(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWrite(), BaseCache::lookupLatency, Packet::needsExclusive(), Packet::needsResponse(), CacheBlk::print(), Cacti::read(), Packet::req, satisfyCpuSideRequest(), Request::setExtraData(), CacheBlk::status, tags, Cacti::write(), MemCmd::Writeback, and writebackBlk().
Referenced by recvAtomic(), and recvTimingReq().
CacheBlk * Cache::allocateBlock (Addr addr, bool is_secure, PacketList & writebacks) [protected]
Find a block frame for new block at address addr targeting the given security space, assuming that the block is not currently in the cache.
Append writebacks if any to provided packet list. Return free block frame. May return NULL if there are no replaceable blocks at the moment.
Definition at line 1438 of file cache_impl.hh.
References DPRINTF, MSHRQueue::findMatch(), BaseTags::findVictim(), CacheBlk::isDirty(), CacheBlk::isSecure(), CacheBlk::isValid(), CacheBlk::isWritable(), BaseCache::mshrQueue, MSHR::needsExclusive(), BaseTags::regenerateBlkAddr(), CacheBlk::set, CacheBlk::tag, tags, and writebackBlk().
Referenced by access(), and handleFill().
void Cache::cmpAndSwap (CacheBlk * blk, PacketPtr pkt) [protected]
Handle doing the Compare and Swap function for SPARC.
Definition at line 119 of file cache_impl.hh.
References BlkDirty, CacheBlk::data, BaseTags::extractBlkOffset(), Packet::getAddr(), Request::getExtraData(), Packet::getSize(), Request::isCondSwap(), Packet::isRequest(), ArmISA::offset, panic, Packet::req, Packet::setData(), CacheBlk::status, tags, and Packet::writeData().
Referenced by satisfyCpuSideRequest().
void Cache::doTimingSupplyResponse (PacketPtr req_pkt, const uint8_t * blk_data, bool already_copied, bool pending_inval) [protected]
Definition at line 1568 of file cache_impl.hh.
References BaseCache::blkSize, ClockedObject::clockEdge(), Packet::cmdString(), DPRINTF, BaseCache::forwardLatency, Packet::getAddr(), Packet::getSize(), Packet::isInvalidate(), Packet::isRead(), Packet::isRequest(), Request::isUncacheable(), Packet::makeTimingResponse(), BaseCache::memSidePort, Packet::needsResponse(), MemCmd::ReadResp, MemCmd::ReadRespWithInvalidate, Packet::req, and QueuedMasterPort::schedTimingSnoopResp().
Referenced by handleSnoop(), and recvTimingSnoopReq().
CacheBlk* Cache::findBlock (Addr addr, bool is_secure) const [inline, protected]
Definition at line 391 of file cache.hh.
References BaseTags::findBlock(), and tags.
void Cache::functionalAccess (PacketPtr pkt, bool fromCpuSide) [protected]
Performs the access specified by the request.
Parameters:
pkt The request to perform.
fromCpuSide from the CPU side port or the memory side port
Definition at line 1014 of file cache_impl.hh.
References BaseCache::blkSize, BaseCache::blockAlign(), System::bypassCaches(), QueuedMasterPort::checkFunctional(), MSHRQueue::checkFunctional(), QueuedSlavePort::checkFunctional(), Packet::checkFunctional(), Packet::cmdString(), BaseCache::cpuSidePort, CacheBlk::data, DPRINTF, BaseTags::findBlock(), MSHRQueue::findMatch(), BaseCache::forwardSnoops, Packet::getAddr(), MSHR::inService, CacheBlk::isDirty(), MSHR::isPendingDirty(), Packet::isSecure(), SlavePort::isSnooping(), CacheBlk::isValid(), Packet::makeResponse(), BaseCache::memSidePort, BaseCache::mshrQueue, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), MasterPort::sendFunctional(), SlavePort::sendFunctionalSnoop(), BaseCache::system, tags, and BaseCache::writeBuffer.
Referenced by Cache::CpuSidePort::recvFunctional(), and Cache::MemSidePort::recvFunctionalSnoop().
PacketPtr Cache::getBusPacket (PacketPtr cpu_pkt, CacheBlk * blk, bool needsExclusive) const [protected]
Generate an appropriate downstream bus request packet for the given parameters.
Parameters:
cpu_pkt The upstream request that needs to be satisfied.
blk The block currently in the cache corresponding to cpu_pkt (NULL if none).
needsExclusive Indicates that an exclusive copy is required even if the request in cpu_pkt doesn't indicate that.
Returns:
A new Packet containing the request, or NULL if the current request in cpu_pkt should just be forwarded on.
Definition at line 789 of file cache_impl.hh.
References Packet::allocate(), Packet::assertShared(), BaseCache::blkSize, BaseCache::blockAlign(), Packet::cmd, Packet::cmdString(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::isLLSC(), Request::isUncacheable(), Packet::isUpgrade(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWriteInvalidate(), Packet::needsResponse(), MemCmd::ReadExReq, MemCmd::ReadReq, Packet::req, MemCmd::SCUpgradeFailReq, MemCmd::SCUpgradeReq, Packet::sharedAsserted(), MemCmd::StoreCondFailReq, MemCmd::UpgradeReq, and MemCmd::Writeback.
Referenced by getTimingPacket(), and recvAtomic().
MSHR * Cache::getNextMSHR () [protected]
Return the next MSHR to service, either a pending miss from the mshrQueue, a buffered write from the write buffer, or something from the prefetcher.
This function is responsible for prioritizing among those sources on the fly.
Definition at line 1888 of file cache_impl.hh.
References BaseCache::allocateMissBuffer(), MSHR::blkAddr, BaseCache::blockAlign(), MSHRQueue::canPrefetch(), Packet::cmdToIndex(), curTick(), BaseTags::findBlock(), MSHRQueue::findMatch(), MSHRQueue::findPending(), Packet::getAddr(), MSHRQueue::getNextMSHR(), BasePrefetcher::getPacket(), MSHRQueue::inServiceEntries, MSHRQueue::isFull(), Packet::isSecure(), MSHR::isSecure, Request::masterId(), System::maxMasters(), BaseCache::mshr_misses, BaseCache::mshrQueue, MSHR::order, prefetcher, Packet::req, BaseCache::system, tags, and BaseCache::writeBuffer.
Referenced by getTimingPacket().
PacketPtr Cache::getTimingPacket () [protected]
Selects an outstanding request to service.
Called when the cache gets granted the downstream bus in timing mode.
Returns:
The request to service, NULL if none found.
Definition at line 1971 of file cache_impl.hh.
References MSHR::blkAddr, BaseCache::clearBlocked(), Packet::cmd, Packet::cmdString(), BaseCache::cpuSidePort, DPRINTF, BaseTags::findBlock(), MSHRQueue::forceDeallocateTarget(), BaseCache::forwardSnoops, Packet::getAddr(), getBusPacket(), Packet::getConstPtr(), getNextMSHR(), Packet::getSize(), MSHR::getTarget(), MemCmd::HardPFReq, MSHRQueue::index, Packet::isBlockCached(), MSHR::isForward, MSHR::isForwardNoResponse(), Packet::isSecure(), MSHR::isSecure, Packet::isWrite(), markInService(), Packet::memInhibitAsserted(), MSHR::needsExclusive(), MSHR::queue, Packet::senderState, SlavePort::sendTimingSnoopReq(), Packet::setData(), Packet::setExpressSnoop(), Packet::sharedAsserted(), and tags.
Referenced by Cache::CacheReqPacketQueue::sendDeferredPacket().
CacheBlk * Cache::handleFill (PacketPtr pkt, CacheBlk * blk, PacketList & writebacks) [protected]
Populates a cache block and handles all outstanding requests for the satisfied fill request.
This version takes two memory requests. One contains the fill data, the other is an optional target to satisfy.
Parameters:
pkt The memory request with the fill data.
blk The cache block if it already exists.
writebacks List for any writebacks that need to be performed.
Returns:
Pointer to the new cache block.
Definition at line 1476 of file cache_impl.hh.
References X86ISA::addr, allocateBlock(), BlkDirty, BlkReadable, BlkSecure, BaseCache::blkSize, BlkValid, BlkWritable, cacti, ClockedObject::clockEdge(), ClockedObject::clockPeriod(), CacheBlk::data, DPRINTF, BaseTags::extractSet(), BaseTags::extractTag(), Cacti::fill(), BaseCache::fillLatency, Packet::getAddr(), Packet::getConstPtr(), Packet::getSize(), Packet::hasData(), BaseTags::insertBlock(), Packet::isRead(), Packet::isResponse(), Packet::isSecure(), CacheBlk::isValid(), Packet::isWriteInvalidate(), Packet::memInhibitAsserted(), Packet::payloadDelay, CacheBlk::print(), CacheBlk::set, Packet::sharedAsserted(), CacheBlk::status, CacheBlk::tag, tags, tempBlock, and CacheBlk::whenReady.
Referenced by recvAtomic(), and recvTimingResp().
void Cache::handleSnoop (PacketPtr ptk, CacheBlk * blk, bool is_timing, bool is_deferred, bool pending_inval) [protected]
Sets the blk to the new state.
Parameters:
blk The cache block being snooped.
new_state The new coherence state for the block.
Definition at line 1615 of file cache_impl.hh.
References Packet::assertMemInhibit(), Packet::assertShared(), BlkDirty, BaseCache::blkSize, BlkWritable, cacti, Packet::cmd, Packet::cmdString(), BaseCache::cpuSidePort, CacheBlk::data, doTimingSupplyResponse(), DPRINTF, BaseCache::forwardSnoops, Packet::getAddr(), Packet::getSize(), MemCmd::HardPFReq, Packet::headerDelay, CacheBlk::invalidate(), BaseTags::invalidate(), Packet::isBlockCached(), CacheBlk::isDirty(), Packet::isInvalidate(), Packet::isRead(), Packet::isRequest(), Packet::isResponse(), Request::isUncacheable(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWriteInvalidate(), ArmISA::M5_VAR_USED, Packet::makeAtomicResponse(), Packet::memInhibitAsserted(), Packet::needsExclusive(), Packet::needsResponse(), Packet::payloadDelay, Packet::popSenderState(), CacheBlk::print(), Packet::pushSenderState(), Cacti::read(), Packet::req, SlavePort::sendAtomicSnoop(), SlavePort::sendTimingSnoopReq(), Packet::setBlockCached(), Packet::setDataFromBlock(), Packet::setExpressSnoop(), Packet::setSupplyExclusive(), Packet::sharedAsserted(), CacheBlk::status, tags, and tempBlock.
Referenced by recvAtomicSnoop(), recvTimingResp(), and recvTimingSnoopReq().
bool Cache::inCache (Addr addr, bool is_secure) const [inline, protected, virtual]
Implements BaseCache.
Definition at line 395 of file cache.hh.
References BaseTags::findBlock(), and tags.
bool Cache::inMissQueue (Addr addr, bool is_secure) const [inline, protected, virtual]
Implements BaseCache.
Definition at line 399 of file cache.hh.
References MSHRQueue::findMatch(), and BaseCache::mshrQueue.
bool Cache::invalidateVisitor (CacheBlk & blk) [protected]
Cache block visitor that invalidates all blocks in the cache.
Dirty cache lines will not be written back to memory.
Returns:
Always returns true.
Definition at line 1422 of file cache_impl.hh.
References CacheBlk::invalidate(), BaseTags::invalidate(), CacheBlk::isDirty(), CacheBlk::isValid(), tags, and warn_once.
Referenced by memInvalidate().
bool Cache::isDirty () const [protected, virtual]
Determine if there are any dirty blocks in the cache.
Returns:
true if at least one block is dirty, false otherwise.
Implements BaseCache.
Definition at line 1392 of file cache_impl.hh.
References BaseTags::forEachBlk(), CacheBlkIsDirtyVisitor::isDirty(), and tags.
Referenced by serialize().
void Cache::markInService (MSHR * mshr, bool pending_dirty_resp) [protected]
Marks a request as in service (sent on the bus).
This can have side effect since storage for no response commands is deallocated once they are successfully sent. Also remember if we are expecting a dirty response from another cache, effectively making this MSHR the ordering point.
Definition at line 267 of file cache_impl.hh.
References BaseCache::deassertMemSideBusRequest(), DPRINTF, MemCmd::HardPFReq, BaseCache::markInServiceInternal(), prefetcher, and BaseCache::Request_PF.
Referenced by getTimingPacket(), recvTimingSnoopReq(), and Cache::CacheReqPacketQueue::sendDeferredPacket().
void Cache::memInvalidate () [protected, virtual]
Invalidates all blocks in the cache.
Dirty cache lines will not be written back to memory. Make sure to call functionalWriteback() first if you want the to write them to memory.
Implements BaseCache.
Definition at line 1385 of file cache_impl.hh.
References BaseTags::forEachBlk(), invalidateVisitor(), and tags.
void Cache::memWriteback () [protected, virtual]
Write back dirty blocks in the cache using functional accesses.
Implements BaseCache.
Definition at line 1378 of file cache_impl.hh.
References BaseTags::forEachBlk(), tags, and writebackVisitor().
Tick Cache::nextMSHRReadyTime () const [protected]
Find next request ready time from among possible sources.
Definition at line 2064 of file cache_impl.hh.
References MSHRQueue::canPrefetch(), BaseCache::mshrQueue, MSHRQueue::nextMSHRReadyTime(), BasePrefetcher::nextPrefetchReadyTime(), prefetcher, and BaseCache::writeBuffer.
Referenced by Cache::CacheReqPacketQueue::sendDeferredPacket().
bool Cache::outstandingMisses () const [inline, protected]
Return whether there are any outstanding misses.
Definition at line 386 of file cache.hh.
References MSHRQueue::allocated, and BaseCache::mshrQueue.
void Cache::promoteWholeLineWrites (PacketPtr pkt) [protected]
Turn line-sized writes into WriteInvalidate transactions.
Definition at line 455 of file cache_impl.hh.
References BaseCache::blkSize, Packet::cmd, doFastWrites, DPRINTF, Packet::getOffset(), Packet::getSize(), BaseCache::isTopLevel, MemCmd::WriteInvalidateReq, and MemCmd::WriteReq.
Referenced by recvAtomic(), and recvTimingReq().
Tick Cache::recvAtomic (PacketPtr pkt) [protected]
Performs the access specified by the request.
Parameters:
pkt The request to perform.
Returns:
The number of ticks required for the access.
Definition at line 863 of file cache_impl.hh.
References access(), System::bypassCaches(), ClockedObject::clockPeriod(), Packet::cmd, Packet::cmdString(), Packet::copyError(), DPRINTF, BaseTags::findBlock(), Packet::getAddr(), getBusPacket(), handleFill(), CacheBlk::invalidate(), BaseTags::invalidate(), Packet::isError(), Packet::isInvalidate(), Packet::isRead(), Packet::isResponse(), Packet::isSecure(), BaseCache::isTopLevel, CacheBlk::isValid(), Packet::isWriteInvalidate(), BaseCache::lookupLatency, Packet::makeAtomicResponse(), Packet::memInhibitAsserted(), BaseCache::memSidePort, Packet::needsExclusive(), Packet::needsResponse(), promoteWholeLineWrites(), satisfyCpuSideRequest(), MasterPort::sendAtomic(), CacheBlk::status, BaseCache::system, tags, ClockedObject::ticksToCycles(), MemCmd::UpgradeResp, and BaseCache::writebacks.
Referenced by Cache::CpuSidePort::recvAtomic().
Tick Cache::recvAtomicSnoop (PacketPtr pkt) [protected]
Snoop for the provided request in the cache and return the estimated time taken.
Parameters:
pkt The memory request to snoop
Returns:
The number of ticks required for the snoop.
Definition at line 1870 of file cache_impl.hh.
References System::bypassCaches(), ClockedObject::clockPeriod(), Packet::cmd, BaseTags::findBlock(), BaseCache::forwardLatency, Packet::getAddr(), handleSnoop(), BaseCache::inRange(), Packet::isSecure(), BaseCache::system, tags, and MemCmd::Writeback.
Referenced by Cache::MemSidePort::recvAtomicSnoop().
bool Cache::recvTimingReq (PacketPtr pkt) [protected]
Performs the access specified by the request.
Parameters:
pkt The request to perform.
Returns:
The result of the access.
Todo:
temporary hack to deal with memory corruption issue until 4-phase transactions are complete
Todo:
nominally we should just delete the packet here, however, until 4-phase stuff we can't because sending cache is still relying on it
Todo:
nominally we should just delete the packet here, however, until 4-phase stuff we can't because sending cache is still relying on it
MSHR hit
Note:
writebacks will be checked in getNextMSHR() for any conflicting requests to the same block
Definition at line 467 of file cache_impl.hh.
References access(), BaseCache::allocateMissBuffer(), BaseCache::allocateWriteBuffer(), Packet::assertMemInhibit(), BlkHWPrefetched, BlkReadable, BaseCache::blockAlign(), BaseCache::Blocked_NoTargets, System::bypassCaches(), ClockedObject::clockEdge(), Packet::cmd, Packet::cmdString(), Packet::cmdToIndex(), BaseCache::cpuSidePort, DPRINTF, MSHRQueue::findMatch(), BaseCache::forwardLatency, Packet::getAddr(), Request::getFlags(), Request::getPaddr(), Packet::getPtr(), Packet::getSize(), Request::getSize(), Request::hasPaddr(), Packet::headerDelay, Packet::isRequest(), Packet::isSecure(), Packet::isSupplyExclusive(), MemCmd::isSWPrefetch(), BaseCache::isTopLevel, Request::isUncacheable(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWrite(), BaseCache::lookupLatency, ArmISA::M5_VAR_USED, Packet::makeTimingResponse(), Request::masterId(), System::maxMasters(), MaxTick, Packet::memInhibitAsserted(), BaseCache::memSidePort, BaseCache::mshr_hits, BaseCache::mshr_misses, BaseCache::mshr_uncacheable, BaseCache::mshrQueue, Packet::needsExclusive(), Packet::needsResponse(), BaseCache::noTargetMSHR, BasePrefetcher::notify(), BaseCache::numTarget, BaseCache::order, Packet::payloadDelay, pendingDelete, X86ISA::pf, prefetcher, prefetchOnAccess, BaseTags::print(), promoteWholeLineWrites(), Packet::req, BaseCache::Request_PF, BaseCache::requestMemSideBus(), QueuedSlavePort::schedTimingResp(), MasterPort::sendTimingReq(), BaseCache::setBlocked(), Packet::setExpressSnoop(), CacheBlk::status, BaseCache::system, tags, CacheBlk::wasPrefetched(), MemCmd::Writeback, BaseCache::writebacks, and X86ISA::x.
Referenced by Cache::CpuSidePort::recvTimingReq().
void Cache::recvTimingResp (PacketPtr pkt) [protected]
Handles a response (cache line fill/write ack) from the bus.
Parameters:
pkt The response packet
Definition at line 1090 of file cache_impl.hh.
References BaseCache::allocateWriteBuffer(), BlkHWPrefetched, BlkReadable, BaseCache::blkSize, BlkWritable, BaseCache::Blocked_NoTargets, MSHRQueue::canPrefetch(), BaseCache::clearBlocked(), ClockedObject::clockEdge(), Packet::cmd, Packet::cmdString(), Packet::cmdToIndex(), Packet::copyError(), BaseCache::cpuSidePort, curTick(), DPRINTF, BaseTags::findBlock(), BaseCache::forwardLatency, MSHR::Target::FromCPU, MSHR::Target::FromPrefetcher, MSHR::Target::FromSnoop, Packet::getAddr(), Packet::getConstPtr(), Packet::getOffset(), Packet::getSize(), MSHR::getTarget(), handleFill(), handleSnoop(), MemCmd::HardPFReq, Packet::headerDelay, CacheBlk::invalidate(), BaseTags::invalidate(), CacheBlk::isDirty(), Packet::isError(), Packet::isInvalidate(), Packet::isRead(), Packet::isResponse(), Packet::isSecure(), MemCmd::isSWPrefetch(), BaseCache::isTopLevel, Request::isUncacheable(), CacheBlk::isValid(), Packet::isWriteInvalidate(), Packet::makeTimingResponse(), Request::masterId(), System::maxMasters(), MaxTick, BaseCache::missLatency, BaseCache::mshr_miss_latency, BaseCache::mshr_uncacheable_lat, BaseCache::mshrQueue, BasePrefetcher::nextPrefetchReadyTime(), BaseCache::noTargetMSHR, panic, Packet::payloadDelay, MSHR::Target::pkt, prefetcher, MemCmd::ReadResp, MemCmd::ReadRespWithInvalidate, MSHR::Target::recvTime, Packet::req, BaseCache::Request_PF, BaseCache::requestMemSideBus(), BaseCache::responseLatency, satisfyCpuSideRequest(), QueuedSlavePort::schedTimingResp(), MemCmd::SCUpgradeFailReq, Packet::senderState, Packet::setData(), Request::setExtraData(), MSHR::Target::source, CacheBlk::status, MemCmd::StoreCondFailReq, MemCmd::StoreCondReq, BaseCache::system, tags, tempBlock, MemCmd::UpgradeFailResp, MemCmd::UpgradeResp, writebackBlk(), and BaseCache::writebacks.
Referenced by Cache::MemSidePort::recvTimingResp(), and recvTimingSnoopResp().
void Cache::recvTimingSnoopReq (PacketPtr pkt) [protected]
Snoops bus transactions to maintain coherence.
Parameters:
pkt The current bus transaction.
Definition at line 1776 of file cache_impl.hh.
References Packet::assertMemInhibit(), Packet::assertShared(), BaseCache::blockAlign(), System::bypassCaches(), Packet::cmd, Packet::cmdString(), doTimingSupplyResponse(), DPRINTF, BaseTags::findBlock(), MSHRQueue::findMatch(), MSHRQueue::findMatches(), Packet::getAddr(), Packet::getConstPtr(), Packet::getSize(), handleSnoop(), MemCmd::HardPFReq, BaseCache::inRange(), Packet::isInvalidate(), Packet::isSecure(), markInService(), Packet::memInhibitAsserted(), BaseCache::mshrQueue, Packet::needsExclusive(), BaseCache::numTarget, BaseCache::order, Packet::setBlockCached(), BaseCache::system, tags, warn, MemCmd::Writeback, BaseCache::writebacks, and BaseCache::writeBuffer.
Referenced by Cache::MemSidePort::recvTimingSnoopReq().
void Cache::recvTimingSnoopResp (PacketPtr pkt) [protected]
Handle a snoop response.
Parameters:
pkt Snoop response packet
Definition at line 417 of file cache_impl.hh.
References System::bypassCaches(), ClockedObject::clockEdge(), Packet::cmd, Packet::cmdString(), DPRINTF, BaseCache::forwardLatency, Packet::getAddr(), Packet::getSize(), MemCmd::HardPFResp, Packet::headerDelay, Packet::isResponse(), Packet::isSecure(), BaseCache::memSidePort, Packet::payloadDelay, Packet::popSenderState(), recvTimingResp(), QueuedMasterPort::schedTimingSnoopResp(), Packet::senderState, and BaseCache::system.
Referenced by Cache::CpuSidePort::recvTimingSnoopResp().
void Cache::regStats () [virtual]
Register stats for this object.
Reimplemented from BaseCache.
Definition at line 110 of file cache_impl.hh.
References cacti, SimObject::name(), and Cacti::regStats().
void Cache::satisfyCpuSideRequest (PacketPtr pkt, CacheBlk * blk, bool deferred_response = false, bool pending_downgrade = false) [protected]
Definition at line 160 of file cache_impl.hh.
References Packet::assertMemInhibit(), Packet::assertShared(), BlkDirty, BaseCache::blkSize, CacheBlk::checkWrite(), Packet::cmd, Packet::cmdString(), cmpAndSwap(), CacheBlk::data, DPRINTF, Packet::getAddr(), Packet::getOffset(), Packet::getSize(), CacheBlk::invalidate(), BaseTags::invalidate(), CacheBlk::isDirty(), Request::isInstFetch(), Packet::isLLSC(), Packet::isRead(), Packet::isRequest(), BaseCache::isTopLevel, Packet::isUpgrade(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWrite(), Packet::isWriteInvalidate(), Packet::needsExclusive(), Packet::req, Packet::setDataFromBlock(), Packet::sharedAsserted(), CacheBlk::status, MemCmd::SwapReq, tags, tempBlock, CacheBlk::trackLoadLocked(), and Packet::writeDataToBlock().
Referenced by access(), recvAtomic(), and recvTimingResp().
bool Cache::satisfyMSHR (MSHR * mshr, PacketPtr pkt, CacheBlk * blk) [protected]
void Cache::serialize (std::ostream & os) [virtual]
serialize the state of the caches We currently don't support checkpointing cache state, so this panics.
Reimplemented from Serializable.
Definition at line 2080 of file cache_impl.hh.
References isDirty(), SERIALIZE_SCALAR, and warn.
void Cache::squash (int threadNum) [protected]
Squash all requests associated with specified thread.
intended for use by I-cache.
Parameters:
threadNum The thread to squash.
Definition at line 284 of file cache_impl.hh.
References BaseCache::Blocked_NoMSHRs, BaseCache::Blocked_NoTargets, BaseCache::clearBlocked(), MSHRQueue::isFull(), BaseCache::mshrQueue, BaseCache::noTargetMSHR, BaseCache::NUM_BLOCKED_CAUSES, MSHRQueue::squash(), and MSHR::threadNum.
void Cache::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 2100 of file cache_impl.hh.
References fatal, and UNSERIALIZE_SCALAR.
PacketPtr Cache::writebackBlk (CacheBlk * blk) [protected]
Create a writeback request for the given block.
Parameters:
blk The block to writeback.
Returns:
The writeback request for the block.
Definition at line 1350 of file cache_impl.hh.
References Packet::allocate(), BlkDirty, BaseCache::blkSize, curTick(), CacheBlk::data, Packet::getPtr(), CacheBlk::isDirty(), CacheBlk::isSecure(), CacheBlk::isValid(), CacheBlk::isWritable(), BaseTags::regenerateBlkAddr(), Request::SECURE, CacheBlk::set, Request::setFlags(), Packet::setSupplyExclusive(), CacheBlk::status, CacheBlk::tag, tags, CacheBlk::task_id, Request::taskId(), CacheBlk::tickInserted, ContextSwitchTaskId::Unknown, Request::wbMasterId, MemCmd::Writeback, ArmISA::writeback, and BaseCache::writebacks.
Referenced by access(), allocateBlock(), and recvTimingResp().
bool Cache::writebackVisitor (CacheBlk & blk) [protected]
Cache block visitor that writes back dirty cache blocks using functional writes.
Returns:
Always returns true.
Definition at line 1401 of file cache_impl.hh.
References BlkDirty, BaseCache::blkSize, CacheBlk::data, Packet::dataStatic(), Request::funcMasterId, CacheBlk::isDirty(), CacheBlk::isValid(), BaseCache::memSidePort, BaseTags::regenerateBlkAddr(), MasterPort::sendFunctional(), CacheBlk::set, CacheBlk::status, CacheBlk::tag, tags, CacheBlk::task_id, and MemCmd::WriteReq.
Referenced by memWriteback().
Member Data Documentation
Cacti* Cache::cacti
Definition at line 423 of file cache.hh.
Referenced by access(), Cache(), handleFill(), handleSnoop(), and regStats().
const bool Cache::doFastWrites [protected]
This cache should allocate a block on a line-sized write miss.
Definition at line 190 of file cache.hh.
Referenced by promoteWholeLineWrites().
std::vector<PacketPtr> Cache::pendingDelete [protected]
Todo:
this is a temporary workaround until the 4-phase code is committed. upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call
Definition at line 207 of file cache.hh.
Referenced by recvTimingReq().
BasePrefetcher* Cache::prefetcher [protected]
Prefetcher.
Definition at line 182 of file cache.hh.
Referenced by Cache(), getNextMSHR(), markInService(), nextMSHRReadyTime(), recvTimingReq(), and recvTimingResp().
const bool Cache::prefetchOnAccess [protected]
Notify the prefetcher on every access, not just misses.
Definition at line 200 of file cache.hh.
Referenced by recvTimingReq().
BaseTags* Cache::tags [protected]
Tag and data Storage.
Definition at line 179 of file cache.hh.
Referenced by access(), allocateBlock(), Cache(), cmpAndSwap(), findBlock(), functionalAccess(), getNextMSHR(), getTimingPacket(), handleFill(), handleSnoop(), inCache(), invalidateVisitor(), isDirty(), memInvalidate(), memWriteback(), recvAtomic(), recvAtomicSnoop(), recvTimingReq(), recvTimingResp(), recvTimingSnoopReq(), satisfyCpuSideRequest(), writebackBlk(), and writebackVisitor().
CacheBlk* Cache::tempBlock [protected]
Temporary cache block for occasional transitory use.
Definition at line 185 of file cache.hh.
Referenced by Cache(), handleFill(), handleSnoop(), recvTimingResp(), satisfyCpuSideRequest(), and ~Cache().
The documentation for this class was generated from the following files:
mem/cache/cache.hh
mem/cache/cache_impl.hh