gem5: NetworkLink Class Reference
NetworkLink Class Reference
#include <NetworkLink.hh>
Public Types
typedef NetworkLinkParams Params
Public Member Functions
NetworkLink (const Params *p)
~NetworkLink ()
void setLinkConsumer (FlexibleConsumer *consumer)
void setSourceQueue (flitBuffer *srcQueue)
flit * peekLink ()
flit * consumeLink ()
void print (std::ostream &out) const
bool is_vc_ready (flit *t_flit)
int get_id () const
void setInPort (int port)
void setOutPort (int port)
void wakeup ()
bool isReady ()
void grant_vc_link (int vc, Cycles grant_time)
void release_vc_link (int vc, Cycles release_time)
void request_vc_link (int vc, NetDest destination, Cycles request_time)
bool isBufferNotFull_link (int vc)
void setSource (FlexibleConsumer *source)
void init_net_ptr (GarnetNetwork *net_ptr)
unsigned int getLinkUtilization () const
const std::vector< unsigned int > & getVcLoad () const
bool functionalRead (Packet *)
uint32_t functionalWrite (Packet *)
Private Attributes
int m_id
Cycles m_latency
int m_in_port
int m_out_port
GarnetNetwork * m_net_ptr
flitBuffer * linkBuffer
FlexibleConsumer * link_consumer
FlexibleConsumer * link_source
flitBuffer * link_srcQueue
unsigned int m_link_utilized
std::vector< unsigned int > m_vc_load
Detailed Description
Definition at line 46 of file NetworkLink.hh.
Member Typedef Documentation
typedef NetworkLinkParams NetworkLink::Params
Reimplemented from SimObject.
Definition at line 49 of file NetworkLink.hh.
Constructor & Destructor Documentation
NetworkLink::NetworkLink (const Params * p)
Definition at line 34 of file NetworkLink.cc.
References ArmISA::i, linkBuffer, m_id, m_in_port, m_latency, m_link_utilized, m_out_port, and m_vc_load.
NetworkLink::~NetworkLink ()
Definition at line 52 of file NetworkLink.cc.
References linkBuffer.
Member Function Documentation
flit * NetworkLink::consumeLink ()
Definition at line 139 of file NetworkLink.cc.
References flitBuffer::getTopFlit(), and linkBuffer.
Referenced by NetworkInterface::wakeup().
bool NetworkLink::functionalRead (Packet * pkt)
Definition at line 145 of file NetworkLink.cc.
References flitBuffer::functionalRead(), and linkBuffer.
uint32_t NetworkLink::functionalWrite (Packet * pkt)
Definition at line 151 of file NetworkLink.cc.
References flitBuffer::functionalWrite(), and linkBuffer.
int NetworkLink::get_id () const [inline]
Definition at line 62 of file NetworkLink.hh.
References m_id.
unsigned int NetworkLink::getLinkUtilization () const [inline]
Definition at line 74 of file NetworkLink.hh.
References m_link_utilized.
const std::vector<unsigned int>& NetworkLink::getVcLoad () const [inline]
Definition at line 75 of file NetworkLink.hh.
References m_vc_load.
void NetworkLink::grant_vc_link (int vc, Cycles grant_time)
Definition at line 88 of file NetworkLink.cc.
References FlexibleConsumer::grant_vc(), link_source, and m_out_port.
Referenced by NetworkInterface::request_vc().
void NetworkLink::init_net_ptr (GarnetNetwork * net_ptr) [inline]
Definition at line 72 of file NetworkLink.hh.
References m_net_ptr.
Referenced by GarnetNetwork::makeInLink(), GarnetNetwork::makeInternalLink(), and GarnetNetwork::makeOutLink().
bool NetworkLink::is_vc_ready (flit * t_flit)
bool NetworkLink::isBufferNotFull_link (int vc)
Definition at line 82 of file NetworkLink.cc.
References FlexibleConsumer::isBufferNotFull(), link_consumer, and m_in_port.
Referenced by NetworkInterface::scheduleOutputLink().
bool NetworkLink::isReady ()
Definition at line 100 of file NetworkLink.cc.
References ClockedObject::curCycle(), flitBuffer::isReady(), and linkBuffer.
Referenced by NetworkInterface::wakeup().
flit * NetworkLink::peekLink ()
Definition at line 133 of file NetworkLink.cc.
References linkBuffer, and flitBuffer::peekTopFlit().
void NetworkLink::print (std::ostream & out) const [inline, virtual]
Implements Consumer.
Definition at line 58 of file NetworkLink.hh.
void NetworkLink::release_vc_link (int vc, Cycles release_time)
Definition at line 94 of file NetworkLink.cc.
References link_source, m_out_port, and FlexibleConsumer::release_vc().
Referenced by NetworkInterface::wakeup().
void NetworkLink::request_vc_link (int vc, NetDest destination, Cycles request_time)
Definition at line 76 of file NetworkLink.cc.
References link_consumer, m_in_port, and FlexibleConsumer::request_vc().
Referenced by NetworkInterface::flitisizeMessage().
void NetworkLink::setInPort (int port)
Definition at line 106 of file NetworkLink.cc.
References m_in_port.
Referenced by Router::addInPort().
void NetworkLink::setLinkConsumer (FlexibleConsumer * consumer)
Definition at line 58 of file NetworkLink.cc.
References link_consumer.
Referenced by Router::addInPort(), and NetworkInterface::addInPort().
void NetworkLink::setOutPort (int port)
Definition at line 112 of file NetworkLink.cc.
References m_out_port.
Referenced by Router::addOutPort().
void NetworkLink::setSource (FlexibleConsumer * source)
Definition at line 70 of file NetworkLink.cc.
References link_source.
Referenced by Router::addOutPort(), and NetworkInterface::addOutPort().
void NetworkLink::setSourceQueue (flitBuffer * srcQueue)
Definition at line 64 of file NetworkLink.cc.
References link_srcQueue.
Referenced by Router::addOutPort(), and NetworkInterface::addOutPort().
void NetworkLink::wakeup () [virtual]
Implements Consumer.
Definition at line 118 of file NetworkLink.cc.
References ClockedObject::clockEdge(), ClockedObject::curCycle(), flit::get_vc(), flitBuffer::getTopFlit(), flitBuffer::insert(), flitBuffer::isReady(), link_consumer, link_srcQueue, linkBuffer, m_latency, m_link_utilized, m_vc_load, Consumer::scheduleEventAbsolute(), and flit::set_time().
Member Data Documentation
FlexibleConsumer* NetworkLink::link_consumer [private]
Definition at line 87 of file NetworkLink.hh.
Referenced by isBufferNotFull_link(), request_vc_link(), setLinkConsumer(), and wakeup().
FlexibleConsumer* NetworkLink::link_source [private]
Definition at line 88 of file NetworkLink.hh.
Referenced by grant_vc_link(), release_vc_link(), and setSource().
flitBuffer* NetworkLink::link_srcQueue [private]
Definition at line 89 of file NetworkLink.hh.
Referenced by setSourceQueue(), and wakeup().
flitBuffer* NetworkLink::linkBuffer [private]
Definition at line 86 of file NetworkLink.hh.
Referenced by consumeLink(), functionalRead(), functionalWrite(), isReady(), NetworkLink(), peekLink(), wakeup(), and ~NetworkLink().
int NetworkLink::m_id [private]
Definition at line 81 of file NetworkLink.hh.
Referenced by get_id(), and NetworkLink().
int NetworkLink::m_in_port [private]
Definition at line 83 of file NetworkLink.hh.
Referenced by isBufferNotFull_link(), NetworkLink(), request_vc_link(), and setInPort().
Cycles NetworkLink::m_latency [private]
Definition at line 82 of file NetworkLink.hh.
Referenced by NetworkLink(), and wakeup().
unsigned int NetworkLink::m_link_utilized [private]
Definition at line 92 of file NetworkLink.hh.
Referenced by getLinkUtilization(), NetworkLink(), and wakeup().
GarnetNetwork* NetworkLink::m_net_ptr [private]
Definition at line 84 of file NetworkLink.hh.
Referenced by init_net_ptr().
int NetworkLink::m_out_port [private]
Definition at line 83 of file NetworkLink.hh.
Referenced by grant_vc_link(), NetworkLink(), release_vc_link(), and setOutPort().
std::vector<unsigned int> NetworkLink::m_vc_load [private]
Definition at line 93 of file NetworkLink.hh.
Referenced by getVcLoad(), NetworkLink(), and wakeup().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/flexible-pipeline/NetworkLink.hh
mem/ruby/network/garnet/flexible-pipeline/NetworkLink.cc