gem5: TimingSimpleCPU::IcachePort Class Reference
TimingSimpleCPU::IcachePort Class Reference
Classes
struct ITickEvent
Public Member Functions
IcachePort (TimingSimpleCPU *_cpu)
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the slave port.
virtual void recvReqRetry ()
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Protected Attributes
ITickEvent tickEvent
Detailed Description
Definition at line 185 of file timing.hh.
Constructor & Destructor Documentation
TimingSimpleCPU::IcachePort::IcachePort (TimingSimpleCPU * _cpu) [inline]
Definition at line 189 of file timing.hh.
Member Function Documentation
void TimingSimpleCPU::IcachePort::recvReqRetry () [protected, virtual]
Called by the slave port if sendTimingReq was called on this master port (causing recvTimingReq to be called on the slave port) and was unsuccesful.
Implements MasterPort.
Definition at line 730 of file timing.cc.
References BaseSimpleCPU::_status, TimingSimpleCPU::TimingCPUPort::cpu, BaseSimpleCPU::IcacheRetry, BaseSimpleCPU::IcacheWaitResponse, TimingSimpleCPU::ifetch_pkt, and MasterPort::sendTimingReq().
bool TimingSimpleCPU::IcachePort::recvTimingResp (PacketPtr pkt) [protected, virtual]
Receive a timing response from the slave port.
Implements MasterPort.
Definition at line 717 of file timing.cc.
References TimingSimpleCPU::TimingCPUPort::cpu, DPRINTF, Packet::getAddr(), TimingSimpleCPU::TimingCPUPort::TickEvent::schedule(), Event::scheduled(), and tickEvent.
Member Data Documentation
ITickEvent TimingSimpleCPU::IcachePort::tickEvent [protected]
Definition at line 209 of file timing.hh.
Referenced by recvTimingResp().
The documentation for this class was generated from the following files:
cpu/simple/timing.hh
cpu/simple/timing.cc