gem5: ConservativeSaturatingCounter Class Reference
ConservativeSaturatingCounter Class Reference
#include <sat_counter.hh>
Public Member Functions
ConservativeSaturatingCounter (unsigned int _max, unsigned int _state_max, unsigned int _start=0, unsigned int _state_start=0)
virtual void increment (unsigned int n=1)
virtual void decrement (unsigned int n=1)
Private Attributes
ConservativeStateMachine sm
Detailed Description
Definition at line 62 of file sat_counter.hh.
Constructor & Destructor Documentation
ConservativeSaturatingCounter::ConservativeSaturatingCounter (unsigned int _max, unsigned int _state_max, unsigned int _start = 0, unsigned int _state_start = 0) [inline]
Definition at line 68 of file sat_counter.hh.
Member Function Documentation
virtual void ConservativeSaturatingCounter::decrement (unsigned int n = 1) [inline, virtual]
Reimplemented from SaturatingCounter.
Definition at line 81 of file sat_counter.hh.
References SaturatingCounter::decrement(), SaturatingCounter::isMin(), ArmISA::n, and sm.
virtual void ConservativeSaturatingCounter::increment (unsigned int n = 1) [inline, virtual]
Reimplemented from SaturatingCounter.
Definition at line 76 of file sat_counter.hh.
References SaturatingCounter::increment(), SaturatingCounter::isMax(), ArmISA::n, and sm.
Member Data Documentation
ConservativeStateMachine ConservativeSaturatingCounter::sm [private]
Definition at line 64 of file sat_counter.hh.
Referenced by decrement(), and increment().
The documentation for this class was generated from the following file:
mem/cache/tags/sat_counter.hh