gem5: FuncPageTable Class Reference
FuncPageTable Class Reference
Declaration of functional page table.
#include <page_table.hh>
Public Member Functions
FuncPageTable (const std::string &__name, uint64_t _pid, Addr _pageSize=TheISA::PageBytes)
~FuncPageTable ()
void initState (ThreadContext *tc)
void map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags=0)
Maps a virtual memory region to a physical memory region.
void remap (Addr vaddr, int64_t size, Addr new_vaddr)
void unmap (Addr vaddr, int64_t size)
bool isUnmapped (Addr vaddr, int64_t size)
Check if any pages in a region are already allocated.
bool lookup (Addr vaddr, TheISA::TlbEntry &entry)
Lookup function.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Types
typedef m5::hash_map< Addr,
TheISA::TlbEntry > PTable
typedef PTable::iterator PTableItr
Private Attributes
PTable pTable
Detailed Description
Declaration of functional page table.
Definition at line 204 of file page_table.hh.
Member Typedef Documentation
typedef m5::hash_map<Addr, TheISA::TlbEntry> FuncPageTable::PTable [private]
Definition at line 207 of file page_table.hh.
typedef PTable::iterator FuncPageTable::PTableItr [private]
Definition at line 208 of file page_table.hh.
Constructor & Destructor Documentation
FuncPageTable::FuncPageTable (const std::string & __name, uint64_t _pid, Addr _pageSize = TheISA::PageBytes)
Definition at line 54 of file page_table.cc.
FuncPageTable::~FuncPageTable ()
Definition at line 60 of file page_table.cc.
Member Function Documentation
void FuncPageTable::initState (ThreadContext * tc) [inline, virtual]
Implements PageTableBase.
Definition at line 218 of file page_table.hh.
bool FuncPageTable::isUnmapped (Addr vaddr, int64_t size) [virtual]
Check if any pages in a region are already allocated.
Parameters:
vaddr The starting virtual address of the region.
size The length of the region.
Returns:
True if no pages in the region are mapped.
Implements PageTableBase.
Definition at line 125 of file page_table.cc.
References PageTableBase::pageOffset(), PageTableBase::pageSize, and pTable.
bool FuncPageTable::lookup (Addr vaddr, TheISA::TlbEntry & entry) [virtual]
Lookup function.
Parameters:
vaddr The virtual address.
Returns:
entry The page table entry corresponding to vaddr.
Implements PageTableBase.
Definition at line 140 of file page_table.cc.
References PageTableBase::cacheElement::entry, PageTableBase::pageAlign(), pTable, PageTableBase::pTableCache, and PageTableBase::updateCache().
void FuncPageTable::map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags = 0) [virtual]
Maps a virtual memory region to a physical memory region.
Parameters:
vaddr The starting virtual address of the region.
paddr The starting physical address where the region is mapped.
size The length of the region.
flags Generic mapping flags that can be set by or-ing values from MappingFlags enum.
Implements PageTableBase.
Definition at line 65 of file page_table.cc.
References PageTableBase::Clobber, DPRINTF, PageTableBase::eraseCacheEntry(), fatal, PageTableBase::pageOffset(), PageTableBase::pageSize, PageTableBase::pid, pTable, PageTableBase::ReadOnly, PageTableBase::Uncacheable, and PageTableBase::updateCache().
void FuncPageTable::remap (Addr vaddr, int64_t size, Addr new_vaddr) [virtual]
Implements PageTableBase.
Definition at line 88 of file page_table.cc.
References DPRINTF, PageTableBase::eraseCacheEntry(), PageTableBase::pageOffset(), PageTableBase::pageSize, pTable, and PageTableBase::updateCache().
void FuncPageTable::serialize (std::ostream & os) [virtual]
Implements PageTableBase.
Definition at line 199 of file page_table.cc.
References X86ISA::count, csprintf(), PageTableBase::name(), paramOut(), and pTable.
void FuncPageTable::unmap (Addr vaddr, int64_t size) [virtual]
Implements PageTableBase.
Definition at line 110 of file page_table.cc.
References DPRINTF, PageTableBase::eraseCacheEntry(), PageTableBase::pageOffset(), PageTableBase::pageSize, and pTable.
void FuncPageTable::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Implements PageTableBase.
Definition at line 220 of file page_table.cc.
References X86ISA::count, csprintf(), ArmISA::i, PageTableBase::name(), paramIn(), pTable, and MipsISA::vaddr.
Member Data Documentation
PTable FuncPageTable::pTable [private]
Definition at line 209 of file page_table.hh.
Referenced by isUnmapped(), lookup(), map(), remap(), serialize(), unmap(), and unserialize().
The documentation for this class was generated from the following files:
mem/page_table.hh
mem/page_table.cc