gem5: PciDevice::PciConfigPort Class Reference
PciDevice::PciConfigPort Class Reference
Public Member Functions
PciConfigPort (PciDevice *dev, int busid, int devid, int funcid, Platform *p)
Protected Member Functions
virtual Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the master port.
virtual AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Protected Attributes
PciDevice * device
Platform * platform
int busId
int deviceId
int functionId
Addr configAddr
Detailed Description
Definition at line 74 of file pcidev.hh.
Constructor & Destructor Documentation
PciDevice::PciConfigPort::PciConfigPort (PciDevice * dev, int busid, int devid, int funcid, Platform * p)
Definition at line 68 of file pcidev.cc.
References busId, Platform::calcPciConfigAddr(), configAddr, deviceId, functionId, and platform.
Member Function Documentation
AddrRangeList PciDevice::PciConfigPort::getAddrRanges () const [protected, virtual]
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns:
a list of ranges responded to
Implements SlavePort.
Definition at line 88 of file pcidev.cc.
References configAddr, PCI_CONFIG_SIZE, RangeSize(), and ULL.
Tick PciDevice::PciConfigPort::recvAtomic (PacketPtr pkt) [protected, virtual]
Receive an atomic request packet from the master port.
Implements SimpleTimingPort.
Definition at line 78 of file pcidev.cc.
References configAddr, device, Packet::getAddr(), Packet::headerDelay, Packet::isRead(), Packet::payloadDelay, PCI_CONFIG_SIZE, PciDevice::readConfig(), and PciDevice::writeConfig().
Member Data Documentation
int PciDevice::PciConfigPort::busId [protected]
Definition at line 85 of file pcidev.hh.
Referenced by PciConfigPort().
Addr PciDevice::PciConfigPort::configAddr [protected]
Definition at line 89 of file pcidev.hh.
Referenced by getAddrRanges(), PciConfigPort(), and recvAtomic().
PciDevice* PciDevice::PciConfigPort::device [protected]
Definition at line 77 of file pcidev.hh.
Referenced by recvAtomic().
int PciDevice::PciConfigPort::deviceId [protected]
Definition at line 86 of file pcidev.hh.
Referenced by PciConfigPort().
int PciDevice::PciConfigPort::functionId [protected]
Definition at line 87 of file pcidev.hh.
Referenced by PciConfigPort().
Platform* PciDevice::PciConfigPort::platform [protected]
Definition at line 83 of file pcidev.hh.
Referenced by PciConfigPort().
The documentation for this class was generated from the following files:
dev/pcidev.hh
dev/pcidev.cc