gem5: LRU Class Reference
LRU Class Reference
#include <lru.hh>
Public Types
typedef LRUParams Params
Convenience typedef.
Public Member Functions
LRU (const Params *p)
Construct and initialize this tag store.
~LRU ()
Destructor.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, int context_src)
Access block and update replacement data.
virtual CacheBlk * findVictim (Addr addr)
Find an invalid block to evict for the address provided.
void insertBlock (PacketPtr pkt, BlkType *blk)
Insert the new block into the cache.
void invalidate (CacheBlk *blk)
Invalidate the given block.
Detailed Description
Definition at line 58 of file lru.hh.
Member Typedef Documentation
typedef LRUParams LRU::Params
Convenience typedef.
Reimplemented from BaseSetAssoc.
Reimplemented in BIP, DIP, FLIP, FLIPProfiler, and LRUProfiler.
Definition at line 62 of file lru.hh.
Constructor & Destructor Documentation
LRU::LRU (const Params * p)
Construct and initialize this tag store.
Definition at line 55 of file lru.cc.
LRU::~LRU () [inline]
Destructor.
Definition at line 77 of file lru.hh.
Member Function Documentation
CacheBlk * LRU::accessBlock (Addr addr, bool is_secure, Cycles & lat, int context_src) [virtual]
Access block and update replacement data.
May not succeed, in which case NULL pointer is returned. This has all the implications of a cache access and should only be used as such. Returns the access latency as a side effect.
Parameters:
addr The address to find.
is_secure True if the target memory space is secure.
asid The address space ID.
lat The access latency.
Returns:
Pointer to the cache block if found.
Reimplemented from BaseSetAssoc.
Reimplemented in DIP, FLIP, FLIPProfiler, and LRUProfiler.
Definition at line 64 of file lru.cc.
References DPRINTF, CacheSet< Blktype >::moveToHead(), BaseSetAssoc::regenerateBlkAddr(), CacheBlk::set, BaseSetAssoc::sets, and CacheBlk::tag.
CacheBlk * LRU::findVictim (Addr addr) [virtual]
Find an invalid block to evict for the address provided.
If there are no invalid blocks, this will return the block in the least-recently-used position.
Parameters:
addr The addr to a find a replacement candidate for.
Returns:
The candidate block.
Reimplemented from BaseSetAssoc.
Reimplemented in FLIP, FLIPProfiler, and LRUProfiler.
Definition at line 83 of file lru.cc.
References BaseSetAssoc::assoc, CacheSet< Blktype >::blks, DPRINTF, BaseSetAssoc::extractSet(), CacheBlk::isValid(), BaseSetAssoc::regenerateBlkAddr(), BaseSetAssoc::sets, and CacheBlk::tag.
void LRU::insertBlock (PacketPtr pkt, BlkType * blk) [virtual]
Insert the new block into the cache.
Parameters:
pkt Packet holding the address to update
blk The block to update.
Reimplemented from BaseSetAssoc.
Reimplemented in BIP, DIP, FLIP, FLIPProfiler, and LRUProfiler.
Definition at line 98 of file lru.cc.
References BaseSetAssoc::extractSet(), Packet::getAddr(), CacheSet< Blktype >::moveToHead(), and BaseSetAssoc::sets.
void LRU::invalidate (CacheBlk * blk) [virtual]
Invalidate the given block.
Parameters:
blk The block to invalidate.
Reimplemented from BaseSetAssoc.
Reimplemented in FLIP, FLIPProfiler, and LRUProfiler.
Definition at line 107 of file lru.cc.
References CacheSet< Blktype >::moveToTail(), CacheBlk::set, and BaseSetAssoc::sets.
The documentation for this class was generated from the following files:
mem/cache/tags/lru.hh
mem/cache/tags/lru.cc