gem5: NoncoherentXBar::NoncoherentXBarSlavePort Class Reference
NoncoherentXBar::NoncoherentXBarSlavePort Class Reference
Declaration of the non-coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
#include <noncoherent_xbar.hh>
Public Member Functions
NoncoherentXBarSlavePort (const std::string &_name, NoncoherentXBar &_xbar, PortID _id)
Protected Member Functions
virtual bool recvTimingReq (PacketPtr pkt)
When receiving a timing request, pass it to the crossbar.
virtual Tick recvAtomic (PacketPtr pkt)
When receiving an atomic request, pass it to the crossbar.
virtual void recvFunctional (PacketPtr pkt)
When receiving a functional request, pass it to the crossbar.
virtual void recvRespRetry ()
When receiving a retry, pass it to the crossbar.
virtual AddrRangeList getAddrRanges () const
Return the union of all adress ranges seen by this crossbar.
Private Attributes
NoncoherentXBar & xbar
A reference to the crossbar to which this port belongs.
Detailed Description
Declaration of the non-coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
Definition at line 87 of file noncoherent_xbar.hh.
Constructor & Destructor Documentation
NoncoherentXBar::NoncoherentXBarSlavePort::NoncoherentXBarSlavePort (const std::string & _name, NoncoherentXBar & _xbar, PortID _id) [inline]
Definition at line 96 of file noncoherent_xbar.hh.
Member Function Documentation
virtual AddrRangeList NoncoherentXBar::NoncoherentXBarSlavePort::getAddrRanges () const [inline, protected, virtual]
Return the union of all adress ranges seen by this crossbar.
Implements SlavePort.
Definition at line 130 of file noncoherent_xbar.hh.
References BaseXBar::getAddrRanges(), and xbar.
virtual Tick NoncoherentXBar::NoncoherentXBarSlavePort::recvAtomic (PacketPtr pkt) [inline, protected, virtual]
When receiving an atomic request, pass it to the crossbar.
Implements SlavePort.
Definition at line 112 of file noncoherent_xbar.hh.
References NoncoherentXBar::recvAtomic(), and xbar.
virtual void NoncoherentXBar::NoncoherentXBarSlavePort::recvFunctional (PacketPtr pkt) [inline, protected, virtual]
When receiving a functional request, pass it to the crossbar.
Implements SlavePort.
Definition at line 118 of file noncoherent_xbar.hh.
References NoncoherentXBar::recvFunctional(), and xbar.
virtual void NoncoherentXBar::NoncoherentXBarSlavePort::recvRespRetry () [inline, protected, virtual]
When receiving a retry, pass it to the crossbar.
Implements SlavePort.
Definition at line 124 of file noncoherent_xbar.hh.
References panic.
virtual bool NoncoherentXBar::NoncoherentXBarSlavePort::recvTimingReq (PacketPtr pkt) [inline, protected, virtual]
When receiving a timing request, pass it to the crossbar.
Implements SlavePort.
Definition at line 106 of file noncoherent_xbar.hh.
References NoncoherentXBar::recvTimingReq(), and xbar.
Member Data Documentation
NoncoherentXBar& NoncoherentXBar::NoncoherentXBarSlavePort::xbar [private]
A reference to the crossbar to which this port belongs.
Definition at line 92 of file noncoherent_xbar.hh.
Referenced by getAddrRanges(), recvAtomic(), recvFunctional(), and recvTimingReq().
The documentation for this class was generated from the following file:
mem/noncoherent_xbar.hh