gem5: MemCntrlProfiler Class Reference
MemCntrlProfiler Class Reference
#include <MemCntrlProfiler.hh>
Public Member Functions
MemCntrlProfiler (const std::string &description, int banks_per_rank, int ranks_per_dimm, int dimms_per_channel)
~MemCntrlProfiler ()
void regStats ()
void profileMemReq (int bank)
void profileMemBankBusy ()
void profileMemBusBusy ()
void profileMemTfawBusy ()
void profileMemReadWriteBusy ()
void profileMemDataBusBusy ()
void profileMemRefresh ()
void profileMemRead ()
void profileMemWrite ()
void profileMemWaitCycles (int cycles)
void profileMemInputQ (int cycles)
void profileMemBankQ (int cycles)
void profileMemArbWait (int cycles)
void profileMemRandBusy ()
void profileMemNotOld ()
void print (std::ostream &out) const
Private Member Functions
MemCntrlProfiler (const MemCntrlProfiler &obj)
MemCntrlProfiler & operator= (const MemCntrlProfiler &obj)
Private Attributes
std::string m_description
Stats::Scalar m_memReq
Stats::Scalar m_memRead
Stats::Scalar m_memWrite
Stats::Scalar m_memRefresh
Stats::Scalar m_memWaitCycles
Stats::Scalar m_memInputQ
Stats::Scalar m_memBankQ
Stats::Formula m_totalStalls
Stats::Formula m_stallsPerReq
Stats::Scalar m_memBankBusy
Stats::Scalar m_memBusBusy
Stats::Scalar m_memTfawBusy
Stats::Scalar m_memReadWriteBusy
Stats::Scalar m_memDataBusBusy
Stats::Scalar m_memArbWait
Stats::Scalar m_memRandBusy
Stats::Scalar m_memNotOld
Stats::Vector m_memBankCount
int m_banks_per_rank
int m_ranks_per_dimm
int m_dimms_per_channel
Detailed Description
Definition at line 39 of file MemCntrlProfiler.hh.
Constructor & Destructor Documentation
MemCntrlProfiler::MemCntrlProfiler (const std::string & description, int banks_per_rank, int ranks_per_dimm, int dimms_per_channel)
MemCntrlProfiler::~MemCntrlProfiler ()
Definition at line 42 of file MemCntrlProfiler.cc.
MemCntrlProfiler::MemCntrlProfiler (const MemCntrlProfiler & obj) [private]
Member Function Documentation
MemCntrlProfiler& MemCntrlProfiler::operator= (const MemCntrlProfiler & obj) [private]
void MemCntrlProfiler::print (std::ostream & out) const
Referenced by operator<<().
void MemCntrlProfiler::profileMemArbWait (int cycles)
Definition at line 120 of file MemCntrlProfiler.cc.
References m_memArbWait.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemBankBusy ()
Definition at line 54 of file MemCntrlProfiler.cc.
References m_memBankBusy.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemBankQ (int cycles)
Definition at line 114 of file MemCntrlProfiler.cc.
References m_memBankQ.
Referenced by RubyMemoryControl::executeCycle().
void MemCntrlProfiler::profileMemBusBusy ()
Definition at line 60 of file MemCntrlProfiler.cc.
References m_memBusBusy.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemDataBusBusy ()
Definition at line 72 of file MemCntrlProfiler.cc.
References m_memDataBusBusy.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemInputQ (int cycles)
Definition at line 108 of file MemCntrlProfiler.cc.
References m_memInputQ.
Referenced by RubyMemoryControl::executeCycle().
void MemCntrlProfiler::profileMemNotOld ()
Definition at line 132 of file MemCntrlProfiler.cc.
References m_memNotOld.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemRandBusy ()
Definition at line 126 of file MemCntrlProfiler.cc.
References m_memRandBusy.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemRead ()
Definition at line 90 of file MemCntrlProfiler.cc.
References m_memRead.
Referenced by RubyMemoryControl::issueRequest().
void MemCntrlProfiler::profileMemReadWriteBusy ()
Definition at line 66 of file MemCntrlProfiler.cc.
References m_memReadWriteBusy.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemRefresh ()
Definition at line 84 of file MemCntrlProfiler.cc.
References m_memRefresh.
Referenced by RubyMemoryControl::issueRefresh().
void MemCntrlProfiler::profileMemReq (int bank)
Definition at line 47 of file MemCntrlProfiler.cc.
References m_memBankCount, and m_memReq.
Referenced by RubyMemoryControl::enqueueMemRef().
void MemCntrlProfiler::profileMemTfawBusy ()
Definition at line 78 of file MemCntrlProfiler.cc.
References m_memTfawBusy.
Referenced by RubyMemoryControl::queueReady().
void MemCntrlProfiler::profileMemWaitCycles (int cycles)
Definition at line 102 of file MemCntrlProfiler.cc.
References m_memWaitCycles.
Referenced by RubyMemoryControl::executeCycle().
void MemCntrlProfiler::profileMemWrite ()
Definition at line 96 of file MemCntrlProfiler.cc.
References m_memWrite.
Referenced by RubyMemoryControl::issueRequest().
void MemCntrlProfiler::regStats ()
Definition at line 138 of file MemCntrlProfiler.cc.
References ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), m_banks_per_rank, m_description, m_dimms_per_channel, m_memArbWait, m_memBankBusy, m_memBankCount, m_memBankQ, m_memBusBusy, m_memDataBusBusy, m_memInputQ, m_memNotOld, m_memRandBusy, m_memRead, m_memReadWriteBusy, m_memRefresh, m_memReq, m_memTfawBusy, m_memWaitCycles, m_memWrite, m_ranks_per_dimm, m_stallsPerReq, m_totalStalls, Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, Stats::oneline, Stats::pdf, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), and Stats::total.
Referenced by RubyMemoryControl::regStats().
Member Data Documentation
int MemCntrlProfiler::m_banks_per_rank [private]
Definition at line 93 of file MemCntrlProfiler.hh.
Referenced by regStats().
std::string MemCntrlProfiler::m_description [private]
Definition at line 71 of file MemCntrlProfiler.hh.
Referenced by regStats().
int MemCntrlProfiler::m_dimms_per_channel [private]
Definition at line 95 of file MemCntrlProfiler.hh.
Referenced by regStats().
Stats::Scalar MemCntrlProfiler::m_memArbWait [private]
Definition at line 88 of file MemCntrlProfiler.hh.
Referenced by profileMemArbWait(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memBankBusy [private]
Definition at line 83 of file MemCntrlProfiler.hh.
Referenced by profileMemBankBusy(), and regStats().
Stats::Vector MemCntrlProfiler::m_memBankCount [private]
Definition at line 91 of file MemCntrlProfiler.hh.
Referenced by profileMemReq(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memBankQ [private]
Definition at line 79 of file MemCntrlProfiler.hh.
Referenced by profileMemBankQ(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memBusBusy [private]
Definition at line 84 of file MemCntrlProfiler.hh.
Referenced by profileMemBusBusy(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memDataBusBusy [private]
Definition at line 87 of file MemCntrlProfiler.hh.
Referenced by profileMemDataBusBusy(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memInputQ [private]
Definition at line 78 of file MemCntrlProfiler.hh.
Referenced by profileMemInputQ(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memNotOld [private]
Definition at line 90 of file MemCntrlProfiler.hh.
Referenced by profileMemNotOld(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memRandBusy [private]
Definition at line 89 of file MemCntrlProfiler.hh.
Referenced by profileMemRandBusy(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memRead [private]
Definition at line 73 of file MemCntrlProfiler.hh.
Referenced by profileMemRead(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memReadWriteBusy [private]
Definition at line 86 of file MemCntrlProfiler.hh.
Referenced by profileMemReadWriteBusy(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memRefresh [private]
Definition at line 75 of file MemCntrlProfiler.hh.
Referenced by profileMemRefresh(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memReq [private]
Definition at line 72 of file MemCntrlProfiler.hh.
Referenced by profileMemReq(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memTfawBusy [private]
Definition at line 85 of file MemCntrlProfiler.hh.
Referenced by profileMemTfawBusy(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memWaitCycles [private]
Definition at line 77 of file MemCntrlProfiler.hh.
Referenced by profileMemWaitCycles(), and regStats().
Stats::Scalar MemCntrlProfiler::m_memWrite [private]
Definition at line 74 of file MemCntrlProfiler.hh.
Referenced by profileMemWrite(), and regStats().
int MemCntrlProfiler::m_ranks_per_dimm [private]
Definition at line 94 of file MemCntrlProfiler.hh.
Referenced by regStats().
Stats::Formula MemCntrlProfiler::m_stallsPerReq [private]
Definition at line 81 of file MemCntrlProfiler.hh.
Referenced by regStats().
Stats::Formula MemCntrlProfiler::m_totalStalls [private]
Definition at line 80 of file MemCntrlProfiler.hh.
Referenced by regStats().
The documentation for this class was generated from the following files:
mem/ruby/profiler/MemCntrlProfiler.hh
mem/ruby/profiler/MemCntrlProfiler.cc