gem5: PciConfigAll Class Reference
PciConfigAll Class Reference
PCI Config Space All of PCI config space needs to return -1 on Tsunami, except the devices that exist.
#include <pciconfigall.hh>
Public Types
typedef PciConfigAllParams Params
Public Member Functions
const Params * params () const
PciConfigAll (const Params *p)
Constructor for PCIConfigAll.
virtual Tick read (PacketPtr pkt)
Read something in PCI config space.
virtual Tick write (PacketPtr pkt)
Write to PCI config spcae.
Detailed Description
PCI Config Space All of PCI config space needs to return -1 on Tsunami, except the devices that exist.
This device maps the entire bus config space and passes the requests on to TsunamiPCIDevice devices as appropriate.
Definition at line 51 of file pciconfigall.hh.
Member Typedef Documentation
typedef PciConfigAllParams PciConfigAll::Params
Reimplemented from BasicPioDevice.
Definition at line 54 of file pciconfigall.hh.
Constructor & Destructor Documentation
PciConfigAll::PciConfigAll (const Params * p)
Constructor for PCIConfigAll.
Parameters:
p parameters structure
Definition at line 46 of file pciconfigall.cc.
References params(), and BasicPioDevice::pioAddr.
Member Function Documentation
const Params* PciConfigAll::params () const [inline]
Reimplemented from BasicPioDevice.
Definition at line 55 of file pciconfigall.hh.
References SimObject::_params.
Referenced by PciConfigAll().
Tick PciConfigAll::read (PacketPtr pkt) [virtual]
Read something in PCI config space.
If the device does not exist -1 is returned, if the device does exist its PciDevice::ReadConfig (or the virtual function that overrides) it is called.
Parameters:
pkt Contains information about the read operation
Returns:
Amount of time to do the read
Implements PioDevice.
Definition at line 56 of file pciconfigall.cc.
References DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic, BasicPioDevice::pioDelay, and Packet::set().
Tick PciConfigAll::write (PacketPtr pkt) [virtual]
Write to PCI config spcae.
If the device does not exit the simulator panics. If it does it is passed on the PciDevice::WriteConfig (or the virtual function that overrides it).
Parameters:
pkt Contains information about the write operation
Returns:
Amount of time to do the read
Implements PioDevice.
Definition at line 79 of file pciconfigall.cc.
References panic.
The documentation for this class was generated from the following files:
dev/pciconfigall.hh
dev/pciconfigall.cc