gem5: RegImmOp Class Reference
RegImmOp Class Reference
#include <misc.hh>
Protected Member Functions
RegImmOp (const char *mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, uint64_t _imm)
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const
Internal function to generate disassembly string.
Protected Attributes
IntRegIndex dest
uint64_t imm
Detailed Description
Definition at line 146 of file misc.hh.
Constructor & Destructor Documentation
RegImmOp::RegImmOp (const char * mnem, ExtMachInst _machInst, OpClass __opClass, IntRegIndex _dest, uint64_t _imm) [inline, protected]
Definition at line 152 of file misc.hh.
Member Function Documentation
std::string RegImmOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const [protected, virtual]
Internal function to generate disassembly string.
Reimplemented from ArmISA::ArmStaticInst.
Definition at line 184 of file misc.cc.
References ccprintf(), dest, imm, ArmISA::ArmStaticInst::printMnemonic(), ArmISA::ArmStaticInst::printReg(), and ArmISA::ss.
Member Data Documentation
IntRegIndex RegImmOp::dest [protected]
Definition at line 149 of file misc.hh.
Referenced by generateDisassembly().
uint64_t RegImmOp::imm [protected]
Definition at line 150 of file misc.hh.
Referenced by generateDisassembly().
The documentation for this class was generated from the following files:
arch/arm/insts/misc.hh
arch/arm/insts/misc.cc