gem5: VirtIO9PSocket Class Reference
VirtIO9PSocket Class Reference
VirtIO 9p proxy that communicates with a 9p server over tcp sockets.
#include <fs9p.hh>
Classes
class SocketDataEvent
Public Types
typedef VirtIO9PSocketParams Params
Public Member Functions
VirtIO9PSocket (Params *params)
virtual ~VirtIO9PSocket ()
void startup ()
startup() is the final initialization call before simulation.
Protected Member Functions
void connectSocket ()
Try to resolve the server name and connect to the 9p server.
void socketDisconnect ()
9p server disconnect notification
ssize_t read (uint8_t *data, size_t len)
Read data from the server behind the proxy.
ssize_t write (const uint8_t *data, size_t len)
Write data to the server behind the proxy.
Private Attributes
int fdSocket
Socket connected to the 9p server.
std::unique_ptr< SocketDataEvent > dataEvent
Detailed Description
VirtIO 9p proxy that communicates with a 9p server over tcp sockets.
Definition at line 329 of file fs9p.hh.
Member Typedef Documentation
typedef VirtIO9PSocketParams VirtIO9PSocket::Params
Reimplemented from VirtIO9PProxy.
Definition at line 332 of file fs9p.hh.
Constructor & Destructor Documentation
VirtIO9PSocket::VirtIO9PSocket (Params * params)
Definition at line 389 of file fs9p.cc.
VirtIO9PSocket::~VirtIO9PSocket () [virtual]
Definition at line 394 of file fs9p.cc.
Member Function Documentation
void VirtIO9PSocket::connectSocket () [protected]
Try to resolve the server name and connect to the 9p server.
Definition at line 407 of file fs9p.cc.
References DPRINTF, fdSocket, MipsISA::p, panic, and SimObject::params().
Referenced by startup().
ssize_t VirtIO9PSocket::read (uint8_t * data, size_t len) [protected, virtual]
Read data from the server behind the proxy.
Note:
This method may return read fewer than len bytes.
Parameters:
data Memory location to store results in.
len Maximum length to read.
Returns:
Number of bytes read, -errno on failure.
Implements VirtIO9PProxy.
Definition at line 450 of file fs9p.cc.
References fdSocket, and socketDisconnect().
void VirtIO9PSocket::socketDisconnect () [protected]
9p server disconnect notification
Definition at line 444 of file fs9p.cc.
References panic.
Referenced by read().
void VirtIO9PSocket::startup () [virtual]
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 399 of file fs9p.cc.
References connectSocket(), dataEvent, fdSocket, pollQueue, and PollQueue::schedule().
ssize_t VirtIO9PSocket::write (const uint8_t * data, size_t len) [protected, virtual]
Write data to the server behind the proxy.
Note:
This method may return write fewer than len bytes.
Parameters:
data Pointer to data to write.
len Maximum length to write.
Returns:
Number of bytes written, -errno on failure.
Implements VirtIO9PProxy.
Definition at line 463 of file fs9p.cc.
References fdSocket.
Member Data Documentation
std::unique_ptr<SocketDataEvent> VirtIO9PSocket::dataEvent [private]
Definition at line 368 of file fs9p.hh.
Referenced by startup().
int VirtIO9PSocket::fdSocket [private]
Socket connected to the 9p server.
Definition at line 366 of file fs9p.hh.
Referenced by connectSocket(), read(), startup(), and write().
The documentation for this class was generated from the following files:
dev/virtio/fs9p.hh
dev/virtio/fs9p.cc