gem5: FlashDevice Class Reference
FlashDevice Class Reference
Flash Device model The Flash Device model is a timing model for a NAND flash device.
#include <flash_device.hh>
Classes
struct CallBackEntry
struct FlashDeviceStats
struct PageMapEntry
Every logical address maps to a physical block and a physical page.
Public Member Functions
FlashDevice (const FlashDeviceParams *)
Initialize functions.
~FlashDevice ()
unsigned int drain (DrainManager *dm)
Checkpoint functions.
void checkDrain ()
Checkdrain; needed to enable checkpoints.
void serialize (std::ostream &os)
Serialize; needed to create checkpoints.
void unserialize (Checkpoint *cp, const std::string &section)
Unserialize; needed to restore from checkpoints.
Private Types
enum Actions { ActionRead, ActionWrite, ActionErase, ActionCopy }
Defines the possible actions to the flash.
Private Member Functions
virtual void initializeMemory (uint64_t disk_size, uint32_t sector_size)
Device access functions Inherrited from AbstractNVM.
virtual void readMemory (uint64_t address, uint32_t amount, Callback *event)
Access functions Access function to simulate a read/write access to the memory.
virtual void writeMemory (uint64_t address, uint32_t amount, Callback *event)
void initializeFlash (uint64_t disk_size, uint32_t sector_size)
Initialization function; called when all disk specifics are known.
void accessDevice (uint64_t address, uint32_t amount, Callback *event, Actions action)
Flash action function.
void actionComplete ()
Event rescheduler.
Tick remap (uint64_t logic_page_addr)
FTL functionality.
Tick accessTimes (uint64_t address, Actions accesstype)
Access time calculator.
void clearUnknownPages (uint32_t index)
Function to indicate that a page is known.
bool getUnknownPages (uint32_t index)
Function to test if a page is known.
void regStats ()
Stats register function.
Private Attributes
uint64_t diskSize
Disk sizes in bytes.
const uint32_t blockSize
const uint32_t pageSize
const uint32_t GCActivePercentage
Garbage collection algorithm emulator.
const Tick readLatency
Access latencies.
const Tick writeLatency
const Tick eraseLatency
const Enums::DataDistribution dataDistribution
Flash organization.
const uint32_t numPlanes
struct FlashDeviceStats stats
RequestHandler stats.
uint32_t pagesPerBlock
Disk dimensions in pages and blocks.
uint32_t pagesPerDisk
uint32_t blocksPerDisk
uint32_t planeMask
DrainManager * drainManager
drain manager Needed to be able to implement checkpoint functionality
std::vector< uint32_t > unknownPages
when the disk is first started we are unsure of the number of used pages, this variable will help determining what we do know.
std::vector< struct PageMapEntry > locationTable
address to logic place has a block and a page field
std::vector< uint32_t > blockValidEntries
number of valid entries per block
std::vector< uint32_t > blockEmptyEntries
number of empty entries
std::vector< std::deque
< struct CallBackEntry > > planeEventQueue
This vector of queues keeps track of all the callbacks per plane.
EventWrapper< FlashDevice,&FlashDevice::actionComplete > planeEvent
Completion event.
Detailed Description
Flash Device model The Flash Device model is a timing model for a NAND flash device.
It doesn't tranfer any data
Definition at line 56 of file flash_device.hh.
Member Enumeration Documentation
enum FlashDevice::Actions [private]
Defines the possible actions to the flash.
Enumerator:
ActionRead
ActionWrite
ActionErase
ActionCopy
A copy involves taking all the used pages from a block and store it in another.
Definition at line 72 of file flash_device.hh.
Constructor & Destructor Documentation
FlashDevice::FlashDevice (const FlashDeviceParams * p)
Initialize functions.
Flash Device constructor and destructor.
Definition at line 74 of file flash_device.cc.
References fatal, numPlanes, and planeMask.
FlashDevice::~FlashDevice ()
Definition at line 154 of file flash_device.cc.
References DPRINTF.
Member Function Documentation
void FlashDevice::accessDevice (uint64_t address, uint32_t amount, Callback * event, Actions action) [private]
Flash action function.
Handles the accesses to the device.
The function determines when certain actions are scheduled and schedules an event that uses the callback function on completion of the action.
The access will be broken up in a number of page accesses. The number of page accesses depends on the amount that needs to be transfered. The assumption here is that the interface is completely ignorant of the page size and that this model has to figure out all of the transaction characteristics.
Check if the page is known and used. unknownPages is a bitmap of all the pages. It tracks wether we can be sure that the information of this page is taken into acount in the model (is it considered in blockValidEntries and blockEmptyEntries?). If it has been used in the past, then it is known.
previous part of the function found the times spend in different planes, now lets find the maximum to know when to callback the disk
If there are no events for this plane, then add the current time to the occupation time; otherwise, plan it after the last event. If by chance that event is handled in this tick, then we would still end up with the same result.
Definition at line 165 of file flash_device.cc.
References accessTimes(), ActionRead, ActionWrite, blockEmptyEntries, blockValidEntries, clearUnknownPages(), X86ISA::count, curTick(), DPRINTF, FlashDevice::FlashDeviceStats::fileSystemAccess, FlashDevice::CallBackEntry::function, getUnknownPages(), MipsISA::index, locationTable, numPlanes, pageSize, pagesPerBlock, planeEvent, planeEventQueue, planeMask, FlashDevice::FlashDeviceStats::readAccess, FlashDevice::FlashDeviceStats::readLatency, remap(), EventManager::reschedule(), Stats::DistBase< Derived, Stor >::sample(), EventManager::schedule(), Event::scheduled(), stats, FlashDevice::CallBackEntry::time, Event::when(), FlashDevice::FlashDeviceStats::writeAccess, and FlashDevice::FlashDeviceStats::writeLatency.
Referenced by readMemory(), and writeMemory().
Tick FlashDevice::accessTimes (uint64_t address, Actions accesstype) [private]
Access time calculator.
Calculates the accesstime per operation needed.
Just read the page
Write the page, and read the result
Erase and check wether it was successfull
Copy every valid page
Definition at line 406 of file flash_device.cc.
References ActionCopy, ActionErase, ActionRead, ActionWrite, blockValidEntries, DPRINTF, eraseLatency, readLatency, and writeLatency.
Referenced by accessDevice(), and remap().
void FlashDevice::actionComplete () [private]
Event rescheduler.
When a plane completes its action, this event is triggered.
When a callback function was associated with that event, it will be called.
Search for a callback that is supposed to happen in this Tick
Invariant: All queued events are scheduled in the present or future.
To ensure that the follow-up action is executed correctly, the callback entry first need to be cleared before it can be called.
Found a callback, lets make it happen
Find when to schedule the planeEvent next
Schedule the next plane that will be ready (if any)
Definition at line 291 of file flash_device.cc.
References checkDrain(), curTick(), DPRINTF, numPlanes, planeEvent, planeEventQueue, Callback::process(), EventManager::reschedule(), and Event::when().
void FlashDevice::checkDrain ()
Checkdrain; needed to enable checkpoints.
Definition at line 617 of file flash_device.cc.
References curTick(), DPRINTF, drainManager, planeEvent, DrainManager::signalDrainDone(), and Event::when().
Referenced by actionComplete().
void FlashDevice::clearUnknownPages (uint32_t index) [inline, private]
Function to indicate that a page is known.
clearUnknownPages.
defines that a page is known and used unknownPages is a bitmap of all the pages. It tracks wether we can be sure that the information of this page is taken into acount in the model (is it considered in blockValidEntries and blockEmptyEntries?). If it has been used in the past, then it is known. But it needs to be tracked to make decisions about write accesses, and indirectly about copy actions. one unknownPage entry is a 32 bit integer. So if we have a page index, then that means that we need entry floor(index/32) (index >> 5) and we need to select the bit which number is equal to the remainder of index/32 (index32). The bit is cleared to make sure that we see it as considered in the future.
Definition at line 456 of file flash_device.cc.
References unknownPages.
Referenced by accessDevice().
unsigned int FlashDevice::drain (DrainManager * dm) [virtual]
Checkpoint functions.
Drain; needed to enable checkpoints.
Reimplemented from SimObject.
Definition at line 591 of file flash_device.cc.
References X86ISA::count, DPRINTF, Drainable::Drained, Drainable::Draining, drainManager, planeEvent, Event::scheduled(), and Drainable::setDrainState().
bool FlashDevice::getUnknownPages (uint32_t index) [inline, private]
Function to test if a page is known.
getUnknownPages.
Verify wether a page is known
Definition at line 467 of file flash_device.cc.
References unknownPages.
Referenced by accessDevice().
void FlashDevice::initializeFlash (uint64_t disk_size, uint32_t sector_size) [private]
Initialization function; called when all disk specifics are known.
Initiates all the flash functions: initializes the lookup tables, age of the device, etc.
This can only be done once the disk image is known. Thats why it can't be done in the constructor.
Sanity information: check flash configuration
Garbage collection related
This is a bitmap. Every bit is a page unknownPages is a vector of 32 bit integers. If every page was an integer, the total size would be pagesPerDisk; since we can map one page per bit we need ceil(pagesPerDisk/32) entries. 32 = 1 << 5 hence it will do to just shift pagesPerDisk five positions and add one. This will allocate one integer to many for this data structure in the worst case.
Definition at line 112 of file flash_device.cc.
References blockEmptyEntries, blockSize, blocksPerDisk, blockValidEntries, X86ISA::count, dataDistribution, diskSize, DPRINTF, locationTable, pageSize, pagesPerBlock, pagesPerDisk, and unknownPages.
Referenced by initializeMemory().
virtual void FlashDevice::initializeMemory (uint64_t disk_size, uint32_t sector_size) [inline, private, virtual]
Device access functions Inherrited from AbstractNVM.
Implements AbstractNVM.
Definition at line 109 of file flash_device.hh.
References initializeFlash().
virtual void FlashDevice::readMemory (uint64_t address, uint32_t amount, Callback * event) [inline, private, virtual]
Access functions Access function to simulate a read/write access to the memory.
Once the action has completed, the Callback event should be called. Putting a NULL pointer as callback is valid syntax, and should result in the simulation of the access, but with no callback to the higher layer. This may be used to occupy the device, such that next actions will be delayed. The read/write function will schedule the incoming requests on a first come first serve basis.
Parameters:
address The logical address to a location in the Non-volatile memory.
amount The amount of data transfered from the NVM in bytes
event A pointer to a callback function that will perform the actions taken by the disk controller on successfull completion of the data transfer between the disk and the disk controller.
Implements AbstractNVM.
Definition at line 114 of file flash_device.hh.
References accessDevice(), and ActionRead.
void FlashDevice::regStats () [private, virtual]
Stats register function.
Amount of GC activations
Histogram of address accesses
Histogram of access latencies
Reimplemented from SimObject.
Definition at line 473 of file flash_device.cc.
References FlashDevice::FlashDeviceStats::fileSystemAccess, Stats::Histogram::init(), Stats::DataWrap< Derived, InfoProxyType >::name(), SimObject::name(), Stats::none, Stats::pdf, FlashDevice::FlashDeviceStats::readAccess, FlashDevice::FlashDeviceStats::readLatency, stats, FlashDevice::FlashDeviceStats::totalGCActivations, FlashDevice::FlashDeviceStats::writeAccess, and FlashDevice::FlashDeviceStats::writeLatency.
Tick FlashDevice::remap (uint64_t logic_page_addr) [private]
FTL functionality.
Handles the remapping of the pages.
It is a (I hope) sensible statistic approach. asumption: garbage collection happens when a clean is needed (may become stochastic function).
Are there any empty left in this Block, or do we need to do an erase
Definition at line 353 of file flash_device.cc.
References accessTimes(), ActionCopy, ActionErase, ActionWrite, blockEmptyEntries, X86ISA::count, DPRINTF, GCActivePercentage, locationTable, pageSize, pagesPerBlock, stats, and FlashDevice::FlashDeviceStats::totalGCActivations.
Referenced by accessDevice().
void FlashDevice::serialize (std::ostream & os) [virtual]
Serialize; needed to create checkpoints.
Reimplemented from Serializable.
Definition at line 521 of file flash_device.cc.
References blockEmptyEntries, blockValidEntries, X86ISA::count, locationTable, planeMask, SERIALIZE_SCALAR, and unknownPages.
void FlashDevice::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Unserialize; needed to restore from checkpoints.
Reimplemented from Serializable.
Definition at line 554 of file flash_device.cc.
References blockEmptyEntries, blockValidEntries, X86ISA::count, locationTable, planeMask, unknownPages, and UNSERIALIZE_SCALAR.
virtual void FlashDevice::writeMemory (uint64_t address, uint32_t amount, Callback * event) [inline, private, virtual]
Implements AbstractNVM.
Definition at line 119 of file flash_device.hh.
References accessDevice(), and ActionWrite.
Member Data Documentation
std::vector<uint32_t> FlashDevice::blockEmptyEntries [private]
number of empty entries
Definition at line 194 of file flash_device.hh.
Referenced by accessDevice(), initializeFlash(), remap(), serialize(), and unserialize().
const uint32_t FlashDevice::blockSize [private]
Definition at line 152 of file flash_device.hh.
Referenced by initializeFlash().
uint32_t FlashDevice::blocksPerDisk [private]
Definition at line 173 of file flash_device.hh.
Referenced by initializeFlash().
std::vector<uint32_t> FlashDevice::blockValidEntries [private]
number of valid entries per block
Definition at line 192 of file flash_device.hh.
Referenced by accessDevice(), accessTimes(), initializeFlash(), serialize(), and unserialize().
const Enums::DataDistribution FlashDevice::dataDistribution [private]
Flash organization.
Definition at line 164 of file flash_device.hh.
Referenced by initializeFlash().
uint64_t FlashDevice::diskSize [private]
Disk sizes in bytes.
Definition at line 151 of file flash_device.hh.
Referenced by initializeFlash().
DrainManager* FlashDevice::drainManager [private]
drain manager Needed to be able to implement checkpoint functionality
Definition at line 182 of file flash_device.hh.
Referenced by checkDrain(), and drain().
const Tick FlashDevice::eraseLatency [private]
Definition at line 161 of file flash_device.hh.
Referenced by accessTimes().
const uint32_t FlashDevice::GCActivePercentage [private]
Garbage collection algorithm emulator.
Definition at line 156 of file flash_device.hh.
Referenced by remap().
std::vector<struct PageMapEntry> FlashDevice::locationTable [private]
address to logic place has a block and a page field
Definition at line 190 of file flash_device.hh.
Referenced by accessDevice(), initializeFlash(), remap(), serialize(), and unserialize().
const uint32_t FlashDevice::numPlanes [private]
Definition at line 165 of file flash_device.hh.
Referenced by accessDevice(), actionComplete(), and FlashDevice().
const uint32_t FlashDevice::pageSize [private]
Definition at line 153 of file flash_device.hh.
Referenced by accessDevice(), initializeFlash(), and remap().
uint32_t FlashDevice::pagesPerBlock [private]
Disk dimensions in pages and blocks.
Definition at line 171 of file flash_device.hh.
Referenced by accessDevice(), initializeFlash(), and remap().
uint32_t FlashDevice::pagesPerDisk [private]
Definition at line 172 of file flash_device.hh.
Referenced by initializeFlash().
EventWrapper<FlashDevice, &FlashDevice::actionComplete> FlashDevice::planeEvent [private]
Completion event.
Definition at line 200 of file flash_device.hh.
Referenced by accessDevice(), actionComplete(), checkDrain(), and drain().
std::vector<std::deque<struct CallBackEntry> > FlashDevice::planeEventQueue [private]
This vector of queues keeps track of all the callbacks per plane.
Definition at line 197 of file flash_device.hh.
Referenced by accessDevice(), and actionComplete().
uint32_t FlashDevice::planeMask [private]
Definition at line 175 of file flash_device.hh.
Referenced by accessDevice(), FlashDevice(), serialize(), and unserialize().
const Tick FlashDevice::readLatency [private]
Access latencies.
Definition at line 159 of file flash_device.hh.
Referenced by accessTimes().
struct FlashDeviceStats FlashDevice::stats [read, private]
RequestHandler stats.
Definition at line 168 of file flash_device.hh.
Referenced by accessDevice(), regStats(), and remap().
std::vector<uint32_t> FlashDevice::unknownPages [private]
when the disk is first started we are unsure of the number of used pages, this variable will help determining what we do know.
Definition at line 188 of file flash_device.hh.
Referenced by clearUnknownPages(), getUnknownPages(), initializeFlash(), serialize(), and unserialize().
const Tick FlashDevice::writeLatency [private]
Definition at line 160 of file flash_device.hh.
Referenced by accessTimes().
The documentation for this class was generated from the following files:
dev/arm/flash_device.hh
dev/arm/flash_device.cc