gem5: Platform Class Reference
Platform Class Reference
#include <platform.hh>
Public Types
typedef PlatformParams Params
Public Member Functions
Platform (const Params *p)
virtual ~Platform ()
virtual void postConsoleInt ()=0
virtual void clearConsoleInt ()=0
virtual void postPciInt (int line)
virtual void clearPciInt (int line)
virtual Addr pciToDma (Addr pciAddr) const
virtual Addr calcPciConfigAddr (int bus, int dev, int func)=0
virtual Addr calcPciIOAddr (Addr addr)=0
virtual Addr calcPciMemAddr (Addr addr)=0
virtual void registerPciDevice (uint8_t bus, uint8_t dev, uint8_t func, uint8_t intr)
Public Attributes
IntrControl * intrctrl
Pointer to the interrupt controller.
Private Attributes
std::bitset< 256 > intLines
std::set< uint32_t > pciDevices
Detailed Description
Definition at line 52 of file platform.hh.
Member Typedef Documentation
typedef PlatformParams Platform::Params
Reimplemented from SimObject.
Reimplemented in Tsunami, RealView, Malta, T1000, and Pc.
Definition at line 59 of file platform.hh.
Constructor & Destructor Documentation
Platform::Platform (const Params * p)
Definition at line 39 of file platform.cc.
Platform::~Platform () [virtual]
Definition at line 44 of file platform.cc.
Member Function Documentation
virtual Addr Platform::calcPciConfigAddr (int bus, int dev, int func) [pure virtual]
Implemented in Tsunami, RealView, Malta, T1000, and Pc.
Referenced by PciDevice::PciConfigPort::PciConfigPort().
virtual Addr Platform::calcPciIOAddr (Addr addr) [pure virtual]
Implemented in Tsunami, RealView, Malta, T1000, and Pc.
Referenced by PciDevice::writeConfig().
virtual Addr Platform::calcPciMemAddr (Addr addr) [pure virtual]
Implemented in Tsunami, RealView, Malta, T1000, and Pc.
Referenced by PciDevice::writeConfig().
virtual void Platform::clearConsoleInt () [pure virtual]
Implemented in Tsunami, RealView, Malta, T1000, and Pc.
Referenced by Uart8250::read(), and Uart8250::write().
void Platform::clearPciInt (int line) [virtual]
Reimplemented in Tsunami, RealView, Malta, T1000, and Pc.
Definition at line 55 of file platform.cc.
References panic.
Referenced by PciDevice::intrClear().
Addr Platform::pciToDma (Addr pciAddr) const [virtual]
Reimplemented in Tsunami, RealView, Malta, T1000, and Pc.
Definition at line 61 of file platform.cc.
References panic.
Referenced by CopyEngine::CopyEngineChannel::fetchDescriptor(), CopyEngine::CopyEngineChannel::fetchNextAddr(), PciDevice::pciToDma(), IGbE::DescCache< iGbReg::RxDesc >::pciToDma(), CopyEngine::CopyEngineChannel::readCopyBytes(), CopyEngine::CopyEngineChannel::writeCompletionStatus(), and CopyEngine::CopyEngineChannel::writeCopyBytes().
virtual void Platform::postConsoleInt () [pure virtual]
Implemented in Tsunami, RealView, Malta, T1000, and Pc.
Referenced by Uart8250::dataAvailable(), and Uart8250::IntrEvent::process().
void Platform::postPciInt (int line) [virtual]
Reimplemented in Tsunami, RealView, Malta, T1000, and Pc.
Definition at line 49 of file platform.cc.
References panic.
Referenced by PciDevice::intrPost().
void Platform::registerPciDevice (uint8_t bus, uint8_t dev, uint8_t func, uint8_t intr) [virtual]
Definition at line 68 of file platform.cc.
References fatal, intLines, and pciDevices.
Referenced by PciDevice::PciDevice().
Member Data Documentation
std::bitset<256> Platform::intLines [private]
Definition at line 74 of file platform.hh.
Referenced by registerPciDevice().
IntrControl* Platform::intrctrl
Pointer to the interrupt controller.
Definition at line 56 of file platform.hh.
Referenced by TsunamiCChip::clearDRIR(), MaltaCChip::clearIntr(), TsunamiCChip::clearIPI(), TsunamiCChip::clearITI(), Pl390::driveLegFIQ(), Pl390::driveLegIRQ(), TsunamiCChip::postDRIR(), MaltaCChip::postIntr(), TsunamiCChip::postRTC(), VGic::PostVIntEvent::process(), Pl390::PostIntEvent::process(), Pl390::readCpu(), TsunamiCChip::reqIPI(), VGic::unPostVInt(), and TsunamiCChip::write().
std::set<uint32_t> Platform::pciDevices [private]
Definition at line 75 of file platform.hh.
Referenced by registerPciDevice().
The documentation for this class was generated from the following files:
dev/platform.hh
dev/platform.cc