gem5: Trace::NativeTrace Class Reference
Trace::NativeTrace Class Reference
#include <nativetrace.hh>
Public Member Functions
NativeTrace (const Params *p)
virtual ~NativeTrace ()
NativeTraceRecord * getInstRecord (Tick when, ThreadContext *tc, const StaticInstPtr staticInst, TheISA::PCState pc, const StaticInstPtr macroStaticInst=NULL)
template<class T >
bool checkReg (const char *regName, T &val, T &realVal)
void read (void *ptr, size_t size)
virtual void check (NativeTraceRecord *record)=0
Protected Attributes
int fd
ListenSocket native_listener
Detailed Description
Definition at line 68 of file nativetrace.hh.
Constructor & Destructor Documentation
Trace::NativeTrace::NativeTrace (const Params * p)
Definition at line 41 of file nativetrace.cc.
References ListenSocket::accept(), ListenSocket::allDisabled(), ccprintf(), DPRINTF, fatal, fd, ListenSocket::listen(), and native_listener.
virtual Trace::NativeTrace::~NativeTrace () [inline, virtual]
Definition at line 78 of file nativetrace.hh.
Member Function Documentation
virtual void Trace::NativeTrace::check (NativeTraceRecord * record) [pure virtual]
Implemented in Trace::ArmNativeTrace, Trace::SparcNativeTrace, and Trace::X86NativeTrace.
Referenced by Trace::NativeTraceRecord::dump().
template<class T > bool Trace::NativeTrace::checkReg (const char * regName, T & val, T & realVal) [inline]
Definition at line 91 of file nativetrace.hh.
References DPRINTFN.
Referenced by Trace::X86NativeTrace::check(), Trace::SparcNativeTrace::check(), Trace::X86NativeTrace::checkR11Reg(), and Trace::X86NativeTrace::checkRcxReg().
NativeTraceRecord* Trace::NativeTrace::getInstRecord (Tick when, ThreadContext * tc, const StaticInstPtr staticInst, TheISA::PCState pc, const StaticInstPtr macroStaticInst = NULL) [inline, virtual]
Reimplemented from Trace::ExeTracer.
Definition at line 81 of file nativetrace.hh.
void Trace::NativeTrace::read (void * ptr, size_t size) [inline]
Definition at line 103 of file nativetrace.hh.
References fd, and panic.
Referenced by Trace::SparcNativeTrace::check(), Trace::X86NativeTrace::ThreadState::update(), and Trace::ArmNativeTrace::ThreadState::update().
Member Data Documentation
int Trace::NativeTrace::fd [protected]
Definition at line 71 of file nativetrace.hh.
Referenced by NativeTrace(), and read().
ListenSocket Trace::NativeTrace::native_listener [protected]
Definition at line 73 of file nativetrace.hh.
Referenced by NativeTrace().
The documentation for this class was generated from the following files:
cpu/nativetrace.hh
cpu/nativetrace.cc