gem5: MultiLevelPageTable< ISAOps > Class Template Reference
MultiLevelPageTable< ISAOps > Class Template Reference
This class implements an in-memory multi-level page table that can be configured to follow ISA specifications.
#include <multi_level_page_table.hh>
Public Member Functions
MultiLevelPageTable (const std::string &__name, uint64_t _pid, System *_sys)
~MultiLevelPageTable ()
void initState (ThreadContext *tc)
void map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags=0)
Maps a virtual memory region to a physical memory region.
void remap (Addr vaddr, int64_t size, Addr new_vaddr)
void unmap (Addr vaddr, int64_t size)
bool isUnmapped (Addr vaddr, int64_t size)
Check if any pages in a region are already allocated.
bool lookup (Addr vaddr, TheISA::TlbEntry &entry)
Lookup function.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Private Member Functions
bool walk (Addr vaddr, bool allocate, Addr &PTE_addr)
Method for walking the page table.
Private Attributes
ISAOps pTableISAOps
ISA specific operations.
System * system
Pointer to System object.
Addr basePtr
Physical address to the last level of the page table.
const std::vector< uint8_t > logLevelSize
Vector with sizes of all levels in base 2 logarithmic.
const uint64_t numLevels
Number of levels contained by the page table.
Detailed Description
template<class ISAOps>
class MultiLevelPageTable< ISAOps >
This class implements an in-memory multi-level page table that can be configured to follow ISA specifications.
It can be used instead of the PageTable class in SE mode to allow CPU models (e.g. X86KvmCPU) to do a normal page table walk.
To reduce memory required to store the page table, a multi-level page table stores its translations similarly with a radix tree. Let n be the number of levels and {Ln, Ln-1, ..., L1, L0} a set that specifies the number of entries for each level as base 2 logarithm values. A multi-level page table will store its translations at level 0 (the leaves of the tree) and it will be layed out in memory in the following way:
+------------------------------+ level n |Ln-1_E0|Ln-1_E1|...|Ln-1_E2^Ln| +------------------------------+ / \ +------------------------+ +------------------------+ level n-1 |Ln-2_E0|...|Ln-2_E2^Ln-1| |Ln-2_E0|...|Ln-2_E2^Ln-1| +------------------------+ +------------------------+ / \ / \ / / \ +------------------+ +------------+ +------------+ level 1 |L0_E1|...|L0_E2^L1| |...|L0_E2^L1| ... |...|L0_E2^L1| +------------------+ +------------+ +------------+ , where +------------------------------+ |Lk-1_E0|Lk-1_E1|...|Lk-1_E2^Lk| +------------------------------+ is a level k entry that holds 2^Lk entries in Lk-1 level.
Essentially, a level n entry will contain 2^Ln level n-1 entries, a level n-1 entry will hold 2^Ln-1 level n-2 entries etc.
The virtual address is split into offsets that index into the different levels of the page table.
+--------------------------------+ |LnOffset|...|L1Offset|PageOffset| +--------------------------------+
For example L0Offset will be formed by the bits in range [log2(PageOffset), log2(PageOffset)+L0].
For every level of the page table, from n to 1, the base address of the entry is loaded, the offset in the virtual address for that particular level is used to index into the entry which will reveal the memory address of the entry in the next level.
See also:
MultiLevelPageTable
Definition at line 105 of file multi_level_page_table.hh.
Constructor & Destructor Documentation
template<class ISAOps > MultiLevelPageTable< ISAOps >::MultiLevelPageTable (const std::string & __name, uint64_t _pid, System * _sys) [inline]
Definition at line 52 of file multi_level_page_table_impl.hh.
template<class ISAOps > MultiLevelPageTable< ISAOps >::~MultiLevelPageTable () [inline]
Definition at line 61 of file multi_level_page_table_impl.hh.
Member Function Documentation
template<class ISAOps > void MultiLevelPageTable< ISAOps >::initState (ThreadContext * tc) [inline, virtual]
Implements PageTableBase.
Definition at line 67 of file multi_level_page_table_impl.hh.
References System::allocPhysPages(), MultiLevelPageTable< ISAOps >::basePtr, DPRINTF, floorLog2(), MultiLevelPageTable< ISAOps >::logLevelSize, PortProxy::memsetBlob(), MultiLevelPageTable< ISAOps >::numLevels, MipsISA::p, System::pagePtr, AlphaISA::PageShift, System::physProxy, MultiLevelPageTable< ISAOps >::pTableISAOps, and MultiLevelPageTable< ISAOps >::system.
template<class ISAOps > bool MultiLevelPageTable< ISAOps >::isUnmapped (Addr vaddr, int64_t size) [inline, virtual]
Check if any pages in a region are already allocated.
Parameters:
vaddr The starting virtual address of the region.
size The length of the region.
Returns:
True if no pages in the region are mapped.
Implements PageTableBase.
Definition at line 259 of file multi_level_page_table_impl.hh.
References MipsISA::p, PageTableBase::pageOffset(), PageTableBase::pageSize, System::physProxy, MultiLevelPageTable< ISAOps >::pTableISAOps, PortProxy::read(), MultiLevelPageTable< ISAOps >::system, and MultiLevelPageTable< ISAOps >::walk().
template<class ISAOps> bool MultiLevelPageTable< ISAOps >::lookup (Addr vaddr, TheISA::TlbEntry & entry) [virtual]
Lookup function.
Parameters:
vaddr The virtual address.
Returns:
entry The page table entry corresponding to vaddr.
Implements PageTableBase.
template<class ISAOps > void MultiLevelPageTable< ISAOps >::map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags = 0) [inline, virtual]
Maps a virtual memory region to a physical memory region.
Parameters:
vaddr The starting virtual address of the region.
paddr The starting physical address where the region is mapped.
size The length of the region.
flags Generic mapping flags that can be set by or-ing values from MappingFlags enum.
Implements PageTableBase.
Definition at line 139 of file multi_level_page_table_impl.hh.
References PageTableBase::Clobber, DPRINTF, PageTableBase::eraseCacheEntry(), fatal, PageTableBase::NotPresent, MipsISA::p, PageTableBase::pageOffset(), AlphaISA::PageShift, PageTableBase::pageSize, System::physProxy, PageTableBase::pid, MultiLevelPageTable< ISAOps >::pTableISAOps, X86ISA::PTE_NotPresent, X86ISA::PTE_ReadOnly, X86ISA::PTE_Uncacheable, PortProxy::read(), PageTableBase::ReadOnly, MultiLevelPageTable< ISAOps >::system, PageTableBase::Uncacheable, PageTableBase::updateCache(), MultiLevelPageTable< ISAOps >::walk(), and PortProxy::write().
Referenced by X86ISA::X86_64LiveProcess::initState().
template<class ISAOps > void MultiLevelPageTable< ISAOps >::remap (Addr vaddr, int64_t size, Addr new_vaddr) [inline, virtual]
Implements PageTableBase.
Definition at line 181 of file multi_level_page_table_impl.hh.
References DPRINTF, PageTableBase::eraseCacheEntry(), fatal, MipsISA::p, PageTableBase::pageOffset(), AlphaISA::PageShift, PageTableBase::pageSize, System::physProxy, PageTableBase::pid, MultiLevelPageTable< ISAOps >::pTableISAOps, PortProxy::read(), MultiLevelPageTable< ISAOps >::system, PageTableBase::updateCache(), MultiLevelPageTable< ISAOps >::walk(), and PortProxy::write().
template<class ISAOps > void MultiLevelPageTable< ISAOps >::serialize (std::ostream & os) [inline, virtual]
Since, the page table is stored in system memory which is serialized separately, we will serialize just the base pointer
Implements PageTableBase.
Definition at line 317 of file multi_level_page_table_impl.hh.
References MultiLevelPageTable< ISAOps >::basePtr, and paramOut().
template<class ISAOps > void MultiLevelPageTable< ISAOps >::unmap (Addr vaddr, int64_t size) [inline, virtual]
Implements PageTableBase.
Definition at line 229 of file multi_level_page_table_impl.hh.
References DPRINTF, PageTableBase::eraseCacheEntry(), fatal, MipsISA::p, PageTableBase::pageOffset(), PageTableBase::pageSize, System::physProxy, MultiLevelPageTable< ISAOps >::pTableISAOps, PortProxy::read(), MultiLevelPageTable< ISAOps >::system, MultiLevelPageTable< ISAOps >::walk(), and PortProxy::write().
template<class ISAOps > void MultiLevelPageTable< ISAOps >::unserialize (Checkpoint * cp, const std::string & section) [inline, virtual]
Implements PageTableBase.
Definition at line 328 of file multi_level_page_table_impl.hh.
References MultiLevelPageTable< ISAOps >::basePtr, and paramIn().
template<class ISAOps > bool MultiLevelPageTable< ISAOps >::walk (Addr vaddr, bool allocate, Addr & PTE_addr) [inline, private]
Method for walking the page table.
Parameters:
vaddr Virtual address that is being looked-up
allocate Specifies whether memory should be allocated while walking the page table
Returns:
PTE_addr The address of the found PTE
Return values:
true if the page table walk has succeded, false otherwhise
Definition at line 90 of file multi_level_page_table_impl.hh.
References System::allocPhysPages(), MultiLevelPageTable< ISAOps >::basePtr, DPRINTF, floorLog2(), ArmISA::i, MultiLevelPageTable< ISAOps >::logLevelSize, PortProxy::memsetBlob(), MultiLevelPageTable< ISAOps >::numLevels, MipsISA::p, AlphaISA::PageShift, System::physProxy, MultiLevelPageTable< ISAOps >::pTableISAOps, PortProxy::read(), MultiLevelPageTable< ISAOps >::system, and PortProxy::write().
Referenced by MultiLevelPageTable< ISAOps >::isUnmapped(), MultiLevelPageTable< ISAOps >::map(), MultiLevelPageTable< ISAOps >::remap(), and MultiLevelPageTable< ISAOps >::unmap().
Member Data Documentation
template<class ISAOps> Addr MultiLevelPageTable< ISAOps >::basePtr [private]
Physical address to the last level of the page table.
Definition at line 120 of file multi_level_page_table.hh.
Referenced by MultiLevelPageTable< ISAOps >::initState(), MultiLevelPageTable< ISAOps >::serialize(), MultiLevelPageTable< ISAOps >::unserialize(), and MultiLevelPageTable< ISAOps >::walk().
template<class ISAOps> const std::vector<uint8_t> MultiLevelPageTable< ISAOps >::logLevelSize [private]
Vector with sizes of all levels in base 2 logarithmic.
Definition at line 125 of file multi_level_page_table.hh.
Referenced by MultiLevelPageTable< ISAOps >::initState(), and MultiLevelPageTable< ISAOps >::walk().
template<class ISAOps> const uint64_t MultiLevelPageTable< ISAOps >::numLevels [private]
Number of levels contained by the page table.
Definition at line 130 of file multi_level_page_table.hh.
Referenced by MultiLevelPageTable< ISAOps >::initState(), and MultiLevelPageTable< ISAOps >::walk().
template<class ISAOps> ISAOps MultiLevelPageTable< ISAOps >::pTableISAOps [private]
ISA specific operations.
Definition at line 110 of file multi_level_page_table.hh.
Referenced by MultiLevelPageTable< ISAOps >::initState(), MultiLevelPageTable< ISAOps >::isUnmapped(), MultiLevelPageTable< ISAOps >::map(), MultiLevelPageTable< ISAOps >::remap(), MultiLevelPageTable< ISAOps >::unmap(), and MultiLevelPageTable< ISAOps >::walk().
template<class ISAOps> System* MultiLevelPageTable< ISAOps >::system [private]
Pointer to System object.
Definition at line 115 of file multi_level_page_table.hh.
Referenced by MultiLevelPageTable< ISAOps >::initState(), MultiLevelPageTable< ISAOps >::isUnmapped(), MultiLevelPageTable< ISAOps >::map(), MultiLevelPageTable< ISAOps >::remap(), MultiLevelPageTable< ISAOps >::unmap(), and MultiLevelPageTable< ISAOps >::walk().
The documentation for this class was generated from the following files:
mem/multi_level_page_table.hh
mem/multi_level_page_table_impl.hh