gem5: StubSlavePort Class Reference
StubSlavePort Class Reference
Implement a `stub' port which just responds to requests by printing a message.
Classes
class ResponseEvent
Public Member Functions
StubSlavePort (const std::string &name_, ExternalSlave &owner_)
Tick recvAtomic (PacketPtr packet)
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr packet)
Receive a functional request packet from the master port.
bool recvTimingReq (PacketPtr packet)
Receive a timing request from the master port.
bool recvTimingSnoopResp (PacketPtr packet)
Receive a timing snoop response from the master port.
void recvRespRetry ()
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
void recvFunctionalSnoop (PacketPtr packet)
Public Attributes
ResponseEvent responseEvent
PacketPtr responsePacket
Stub can handle a single request at a time.
bool mustRetry
Received a new request while processing a first.
Detailed Description
Implement a `stub' port which just responds to requests by printing a message.
The stub port can be used to configure and test a system where the external port is used for a peripheral before connecting the external port
Definition at line 50 of file external_slave.cc.
Constructor & Destructor Documentation
StubSlavePort::StubSlavePort (const std::string & name_, ExternalSlave & owner_) [inline]
Definition at line 73 of file external_slave.cc.
Member Function Documentation
Tick StubSlavePort::recvAtomic (PacketPtr pkt) [virtual]
Receive an atomic request packet from the master port.
Implements SlavePort.
Definition at line 104 of file external_slave.cc.
References DDUMP, DPRINTF, DTRACE, Packet::getAddr(), Packet::getConstPtr(), Packet::getSize(), and ArmISA::M5_VAR_USED.
Referenced by recvFunctional(), and recvTimingReq().
void StubSlavePort::recvFunctional (PacketPtr pkt) [virtual]
Receive a functional request packet from the master port.
Implements SlavePort.
Definition at line 118 of file external_slave.cc.
References recvAtomic().
void StubSlavePort::recvFunctionalSnoop (PacketPtr packet)
Definition at line 174 of file external_slave.cc.
References fatal.
void StubSlavePort::recvRespRetry () [virtual]
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements SlavePort.
Definition at line 164 of file external_slave.cc.
References StubSlavePort::ResponseEvent::process(), responseEvent, and responsePacket.
bool StubSlavePort::recvTimingReq (PacketPtr pkt) [virtual]
Receive a timing request from the master port.
Implements SlavePort.
Definition at line 140 of file external_slave.cc.
References curTick(), mustRetry, ExternalSlave::Port::owner, recvAtomic(), responseEvent, responsePacket, and EventManager::schedule().
bool StubSlavePort::recvTimingSnoopResp (PacketPtr pkt) [virtual]
Receive a timing snoop response from the master port.
Reimplemented from SlavePort.
Definition at line 157 of file external_slave.cc.
References fatal.
Member Data Documentation
bool StubSlavePort::mustRetry
Received a new request while processing a first.
Need to ask for a retry after completing this packet
Definition at line 71 of file external_slave.cc.
Referenced by StubSlavePort::ResponseEvent::process(), and recvTimingReq().
ResponseEvent StubSlavePort::responseEvent
Definition at line 63 of file external_slave.cc.
Referenced by recvRespRetry(), and recvTimingReq().
PacketPtr StubSlavePort::responsePacket
Stub can handle a single request at a time.
This will be NULL when no packet is in flight
Definition at line 67 of file external_slave.cc.
Referenced by StubSlavePort::ResponseEvent::process(), recvRespRetry(), and recvTimingReq().
The documentation for this class was generated from the following file:
mem/external_slave.cc