gem5: DMASequencer Class Reference
DMASequencer Class Reference
#include <DMASequencer.hh>
Classes
class MemSlavePort
Public Types
typedef DMASequencerParams Params
Public Member Functions
DMASequencer (const Params *)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
BaseSlavePort & getSlavePort (const std::string &if_name, PortID idx=InvalidPortID)
Get a slave port with a given name and index.
RequestStatus makeRequest (PacketPtr pkt)
bool busy ()
int outstandingCount () const
bool isDeadlockEventScheduled () const
void descheduleDeadlockEvent ()
void setController (AbstractController *_cntrl)
uint32_t getId ()
unsigned int drain (DrainManager *dm)
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
void dataCallback (const DataBlock &dblk)
void ackCallback ()
void recordRequestType (DMASequencerRequestType requestType)
Private Member Functions
void issueNext ()
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
unsigned int getChildDrainCount (DrainManager *dm)
Private Attributes
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
MemSlavePort slave_port
DrainManager * drainManager
System * system
bool retry
bool m_is_busy
uint64_t m_data_block_mask
DMARequest active_request
Detailed Description
Definition at line 58 of file DMASequencer.hh.
Member Typedef Documentation
typedef DMASequencerParams DMASequencer::Params
Reimplemented from MemObject.
Definition at line 61 of file DMASequencer.hh.
Constructor & Destructor Documentation
DMASequencer::DMASequencer (const Params * p)
Definition at line 40 of file DMASequencer.cc.
References m_version.
Member Function Documentation
void DMASequencer::ackCallback ()
Definition at line 353 of file DMASequencer.cc.
References issueNext().
bool DMASequencer::busy () [inline]
Definition at line 101 of file DMASequencer.hh.
References m_is_busy.
void DMASequencer::dataCallback (const DataBlock & dblk)
Definition at line 337 of file DMASequencer.cc.
References active_request, DMARequest::bytes_completed, DMARequest::bytes_issued, DMARequest::data, DataBlock::getData(), issueNext(), ArmISA::len, m_data_block_mask, m_is_busy, ArmISA::offset, DMARequest::start_paddr, and DMARequest::write.
void DMASequencer::descheduleDeadlockEvent () [inline]
Definition at line 104 of file DMASequencer.hh.
Referenced by drain().
unsigned int DMASequencer::drain (DrainManager * drainManger) [virtual]
Provide a default implementation of the drain interface that simply returns 0 (draining completed) and sets the drain state to Drained.
Reimplemented from SimObject.
Definition at line 173 of file DMASequencer.cc.
References descheduleDeadlockEvent(), DPRINTF, Drainable::Drained, Drainable::Draining, drainManager, getChildDrainCount(), isDeadlockEventScheduled(), outstandingCount(), and Drainable::setDrainState().
unsigned int DMASequencer::getChildDrainCount (DrainManager * dm) [private]
Definition at line 164 of file DMASequencer.cc.
References X86ISA::count, DPRINTF, QueuedSlavePort::drain(), and slave_port.
Referenced by drain().
uint32_t DMASequencer::getId () [inline]
Definition at line 109 of file DMASequencer.hh.
References m_version.
BaseSlavePort & DMASequencer::getSlavePort (const std::string & if_name, PortID idx = InvalidPortID) [virtual]
Get a slave port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic base master port.
Parameters:
if_name Port name
idx Index in the case of a VectorPort
Returns:
A reference to the given port
Reimplemented from MemObject.
Definition at line 64 of file DMASequencer.cc.
References slave_port.
void DMASequencer::init () [virtual]
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 51 of file DMASequencer.cc.
References RubySystem::getBlockSizeBits(), AbstractController::getMandatoryQueue(), m_controller, m_data_block_mask, m_is_busy, m_mandatory_q_ptr, SlavePort::sendRangeChange(), MessageBuffer::setSender(), and slave_port.
bool DMASequencer::isDeadlockEventScheduled () const [inline]
Definition at line 103 of file DMASequencer.hh.
Referenced by drain().
void DMASequencer::issueNext () [private]
Definition at line 286 of file DMASequencer.cc.
References active_request, DMARequest::bytes_completed, DMARequest::bytes_issued, ClockedObject::clockEdge(), DMARequest::data, DPRINTF, MessageBuffer::enqueue(), RubySystem::getBlockSizeBytes(), DMARequest::len, line_address(), m_data_block_mask, m_is_busy, m_mandatory_q_ptr, DMARequest::pkt, ruby_hit_callback(), DMARequest::start_paddr, and DMARequest::write.
Referenced by ackCallback(), and dataCallback().
RequestStatus DMASequencer::makeRequest (PacketPtr pkt)
Definition at line 240 of file DMASequencer.cc.
References active_request, DMARequest::bytes_completed, DMARequest::bytes_issued, ClockedObject::clockEdge(), DMARequest::data, MessageBuffer::enqueue(), Packet::getAddr(), RubySystem::getBlockSizeBytes(), Packet::getPtr(), Packet::getSize(), Packet::isWrite(), DMARequest::len, ArmISA::len, line_address(), m_data_block_mask, m_is_busy, m_mandatory_q_ptr, ArmISA::offset, DMARequest::pkt, DMARequest::start_paddr, and DMARequest::write.
int DMASequencer::outstandingCount () const [inline]
Definition at line 102 of file DMASequencer.hh.
References m_is_busy.
Referenced by drain(), and testDrainComplete().
void DMASequencer::recordRequestType (DMASequencerRequestType requestType)
Definition at line 359 of file DMASequencer.cc.
References DPRINTF.
bool DMASequencer::recvTimingResp (PacketPtr pkt, PortID master_port_id) [private]
Called by the PIO port when receiving a timing response.
Parameters:
pkt Response packet
master_port_id Port id of the PIO port
Returns:
Whether successfully sent
void DMASequencer::ruby_hit_callback (PacketPtr pkt) [private]
Definition at line 124 of file DMASequencer.cc.
References Packet::cmdString(), DPRINTF, Packet::getAddr(), DMASequencer::MemSlavePort::hitCallback(), System::isMemAddr(), Packet::isRequest(), Port::name(), retry, SlavePort::sendRetryReq(), slave_port, system, and testDrainComplete().
Referenced by issueNext().
void DMASequencer::setController (AbstractController * _cntrl) [inline]
Definition at line 108 of file DMASequencer.hh.
References m_controller.
void DMASequencer::testDrainComplete () [private]
Definition at line 148 of file DMASequencer.cc.
References DPRINTF, drainManager, outstandingCount(), and DrainManager::signalDrainDone().
Referenced by ruby_hit_callback().
Member Data Documentation
DMARequest DMASequencer::active_request [private]
Definition at line 148 of file DMASequencer.hh.
Referenced by dataCallback(), issueNext(), and makeRequest().
DrainManager* DMASequencer::drainManager [private]
Definition at line 142 of file DMASequencer.hh.
Referenced by drain(), and testDrainComplete().
AbstractController* DMASequencer::m_controller [private]
Definition at line 136 of file DMASequencer.hh.
Referenced by init(), and setController().
uint64_t DMASequencer::m_data_block_mask [private]
Definition at line 147 of file DMASequencer.hh.
Referenced by dataCallback(), init(), issueNext(), and makeRequest().
bool DMASequencer::m_is_busy [private]
Definition at line 146 of file DMASequencer.hh.
Referenced by busy(), dataCallback(), init(), issueNext(), makeRequest(), and outstandingCount().
MessageBuffer* DMASequencer::m_mandatory_q_ptr [private]
Definition at line 137 of file DMASequencer.hh.
Referenced by init(), issueNext(), and makeRequest().
bool DMASequencer::m_usingRubyTester [private]
Definition at line 138 of file DMASequencer.hh.
uint32_t DMASequencer::m_version [private]
Definition at line 135 of file DMASequencer.hh.
Referenced by DMASequencer(), and getId().
bool DMASequencer::retry [private]
Definition at line 145 of file DMASequencer.hh.
Referenced by ruby_hit_callback().
MemSlavePort DMASequencer::slave_port [private]
Definition at line 140 of file DMASequencer.hh.
Referenced by getChildDrainCount(), getSlavePort(), init(), and ruby_hit_callback().
System* DMASequencer::system [private]
Definition at line 143 of file DMASequencer.hh.
Referenced by DMASequencer::MemSlavePort::isPhysMemAddress(), and ruby_hit_callback().
The documentation for this class was generated from the following files:
mem/ruby/system/DMASequencer.hh
mem/ruby/system/DMASequencer.cc