gem5: AlphaISA::ISA Class Reference
AlphaISA::ISA Class Reference
#include <isa.hh>
Public Types
typedef uint64_t InternalProcReg
typedef AlphaISAParams Params
Public Member Functions
MiscReg readMiscRegNoEffect (int misc_reg, ThreadID tid=0) const
MiscReg readMiscReg (int misc_reg, ThreadContext *tc, ThreadID tid=0)
void setMiscRegNoEffect (int misc_reg, const MiscReg &val, ThreadID tid=0)
void setMiscReg (int misc_reg, const MiscReg &val, ThreadContext *tc, ThreadID tid=0)
void clear ()
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
const Params * params () const
ISA (Params *p)
void startup (ThreadContext *tc)
Protected Member Functions
InternalProcReg readIpr (int idx, ThreadContext *tc)
void setIpr (int idx, InternalProcReg val, ThreadContext *tc)
Protected Attributes
System * system
uint64_t fpcr
uint64_t uniq
bool lock_flag
Addr lock_addr
int intr_flag
InternalProcReg ipr [NumInternalProcRegs]
Detailed Description
Definition at line 52 of file isa.hh.
Member Typedef Documentation
typedef uint64_t AlphaISA::ISA::InternalProcReg
Definition at line 55 of file isa.hh.
typedef AlphaISAParams AlphaISA::ISA::Params
Reimplemented from SimObject.
Definition at line 56 of file isa.hh.
Constructor & Destructor Documentation
AlphaISA::ISA::ISA (Params * p)
Definition at line 42 of file isa.cc.
References clear(), and AlphaISA::initializeIprTable().
Member Function Documentation
void AlphaISA::ISA::clear () [inline]
Definition at line 85 of file isa.hh.
References fpcr, intr_flag, ipr, lock_addr, lock_flag, and uniq.
Referenced by ISA().
int AlphaISA::ISA::flattenCCIndex (int reg) const [inline]
Definition at line 112 of file isa.hh.
int AlphaISA::ISA::flattenFloatIndex (int reg) const [inline]
Definition at line 105 of file isa.hh.
int AlphaISA::ISA::flattenIntIndex (int reg) const [inline]
Definition at line 99 of file isa.hh.
int AlphaISA::ISA::flattenMiscIndex (int reg) const [inline]
Definition at line 118 of file isa.hh.
const AlphaISAParams * AlphaISA::ISA::params () const
Reimplemented from SimObject.
Definition at line 50 of file isa.cc.
References SimObject::_params.
MiscReg AlphaISA::ISA::readIpr (int idx, ThreadContext * tc) [protected]
Definition at line 93 of file ev5.cc.
References AlphaISA::TlbEntry::asma, AlphaISA::TlbEntry::asn, AlphaISA::TlbEntry::fonr, AlphaISA::TlbEntry::fonw, ThreadContext::getCpuPtr(), ThreadContext::getDTBPtr(), ipr, AlphaISA::IPR_ALT_MODE, AlphaISA::IPR_ASTER, AlphaISA::IPR_ASTRR, AlphaISA::IPR_CC, AlphaISA::IPR_DC_FLUSH, AlphaISA::IPR_DC_MODE, AlphaISA::IPR_DC_PERR_STAT, AlphaISA::IPR_DTB_CM, AlphaISA::IPR_DTB_IA, AlphaISA::IPR_DTB_IAP, AlphaISA::IPR_DTB_PTE, AlphaISA::IPR_EXC_ADDR, AlphaISA::IPR_EXC_MASK, AlphaISA::IPR_EXC_SUM, AlphaISA::IPR_HWINT_CLR, AlphaISA::IPR_IC_FLUSH, AlphaISA::IPR_IC_PERR_STAT, AlphaISA::IPR_ICM, AlphaISA::IPR_ICSR, AlphaISA::IPR_IFAULT_VA_FORM, AlphaISA::IPR_INTID, AlphaISA::IPR_IPLR, AlphaISA::IPR_ISR, AlphaISA::IPR_ITB_IA, AlphaISA::IPR_ITB_IAP, AlphaISA::IPR_IVPTBR, AlphaISA::IPR_MAF_MODE, AlphaISA::IPR_MCSR, AlphaISA::IPR_MM_STAT, AlphaISA::IPR_PAL_BASE, AlphaISA::IPR_PALtemp0, AlphaISA::IPR_PALtemp1, AlphaISA::IPR_PALtemp10, AlphaISA::IPR_PALtemp11, AlphaISA::IPR_PALtemp12, AlphaISA::IPR_PALtemp13, AlphaISA::IPR_PALtemp14, AlphaISA::IPR_PALtemp15, AlphaISA::IPR_PALtemp16, AlphaISA::IPR_PALtemp17, AlphaISA::IPR_PALtemp18, AlphaISA::IPR_PALtemp19, AlphaISA::IPR_PALtemp2, AlphaISA::IPR_PALtemp20, AlphaISA::IPR_PALtemp21, AlphaISA::IPR_PALtemp22, AlphaISA::IPR_PALtemp23, AlphaISA::IPR_PALtemp3, AlphaISA::IPR_PALtemp4, AlphaISA::IPR_PALtemp5, AlphaISA::IPR_PALtemp6, AlphaISA::IPR_PALtemp7, AlphaISA::IPR_PALtemp8, AlphaISA::IPR_PALtemp9, AlphaISA::IPR_PMCTR, AlphaISA::IPR_SIRR, AlphaISA::IPR_SL_XMIT, AlphaISA::IPR_VA, AlphaISA::IPR_VA_FORM, panic, AlphaISA::TlbEntry::ppn, ULL, AlphaISA::TlbEntry::xre, and AlphaISA::TlbEntry::xwe.
Referenced by readMiscReg().
MiscReg AlphaISA::ISA::readMiscReg (int misc_reg, ThreadContext * tc, ThreadID tid = 0)
Definition at line 97 of file isa.cc.
References fpcr, intr_flag, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, readIpr(), and uniq.
MiscReg AlphaISA::ISA::readMiscRegNoEffect (int misc_reg, ThreadID tid = 0) const
Definition at line 77 of file isa.cc.
References fpcr, intr_flag, ipr, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, AlphaISA::NumInternalProcRegs, and uniq.
void AlphaISA::ISA::serialize (std::ostream & os) [virtual]
Reimplemented from Serializable.
Definition at line 56 of file isa.cc.
References fpcr, ipr, lock_addr, lock_flag, AlphaISA::NumInternalProcRegs, SERIALIZE_ARRAY, SERIALIZE_SCALAR, and uniq.
void AlphaISA::ISA::setIpr (int idx, InternalProcReg val, ThreadContext * tc) [protected]
Definition at line 202 of file ev5.cc.
References AlphaISA::TlbEntry::asma, AlphaISA::TlbEntry::asn, AlphaISA::break_ipl, Debug::breakpoint(), AlphaISA::DTB_ASN_ASN(), AlphaISA::DTB_PTE_ASMA(), AlphaISA::DTB_PTE_FONR(), AlphaISA::DTB_PTE_FONW(), AlphaISA::DTB_PTE_GH(), AlphaISA::DTB_PTE_PPN(), AlphaISA::DTB_PTE_XRE(), AlphaISA::DTB_PTE_XWE(), AlphaISA::TlbEntry::fonr, AlphaISA::TlbEntry::fonw, ThreadContext::getDTBPtr(), ThreadContext::getITBPtr(), ThreadContext::getKernelStats(), ipr, AlphaISA::IPR_ALT_MODE, AlphaISA::IPR_ASTER, AlphaISA::IPR_ASTRR, AlphaISA::IPR_CC, AlphaISA::IPR_CC_CTL, AlphaISA::IPR_DC_FLUSH, AlphaISA::IPR_DC_MODE, AlphaISA::IPR_DC_PERR_STAT, AlphaISA::IPR_DC_TEST_CTL, AlphaISA::IPR_DTB_ASN, AlphaISA::IPR_DTB_CM, AlphaISA::IPR_DTB_IA, AlphaISA::IPR_DTB_IAP, AlphaISA::IPR_DTB_IS, AlphaISA::IPR_DTB_PTE, AlphaISA::IPR_DTB_PTE_TEMP, AlphaISA::IPR_DTB_TAG, AlphaISA::IPR_EXC_ADDR, AlphaISA::IPR_EXC_MASK, AlphaISA::IPR_EXC_SUM, AlphaISA::IPR_HWINT_CLR, AlphaISA::IPR_IC_FLUSH, AlphaISA::IPR_IC_PERR_STAT, AlphaISA::IPR_ICM, AlphaISA::IPR_ICSR, AlphaISA::IPR_INTID, AlphaISA::IPR_IPLR, AlphaISA::IPR_ITB_ASN, AlphaISA::IPR_ITB_IA, AlphaISA::IPR_ITB_IAP, AlphaISA::IPR_ITB_IS, AlphaISA::IPR_ITB_PTE, AlphaISA::IPR_ITB_PTE_TEMP, AlphaISA::IPR_ITB_TAG, AlphaISA::IPR_IVPTBR, AlphaISA::IPR_MAF_MODE, AlphaISA::IPR_MCSR, AlphaISA::IPR_MM_STAT, AlphaISA::IPR_MVPTBR, AlphaISA::IPR_PAL_BASE, AlphaISA::IPR_PALtemp0, AlphaISA::IPR_PALtemp1, AlphaISA::IPR_PALtemp10, AlphaISA::IPR_PALtemp11, AlphaISA::IPR_PALtemp12, AlphaISA::IPR_PALtemp13, AlphaISA::IPR_PALtemp14, AlphaISA::IPR_PALtemp15, AlphaISA::IPR_PALtemp16, AlphaISA::IPR_PALtemp17, AlphaISA::IPR_PALtemp18, AlphaISA::IPR_PALtemp19, AlphaISA::IPR_PALtemp2, AlphaISA::IPR_PALtemp20, AlphaISA::IPR_PALtemp21, AlphaISA::IPR_PALtemp22, AlphaISA::IPR_PALtemp23, AlphaISA::IPR_PALtemp3, AlphaISA::IPR_PALtemp4, AlphaISA::IPR_PALtemp5, AlphaISA::IPR_PALtemp6, AlphaISA::IPR_PALtemp7, AlphaISA::IPR_PALtemp8, AlphaISA::IPR_PALtemp9, AlphaISA::IPR_PMCTR, AlphaISA::IPR_SIRR, AlphaISA::IPR_SL_RCV, AlphaISA::IPR_SL_XMIT, AlphaISA::ITB_ASN_ASN(), AlphaISA::ITB_PTE_ASMA(), AlphaISA::ITB_PTE_FONR(), AlphaISA::ITB_PTE_FONW(), AlphaISA::ITB_PTE_GH(), AlphaISA::ITB_PTE_PPN(), AlphaISA::ITB_PTE_XRE(), AlphaISA::Kernel::kernel, panic, AlphaISA::TlbEntry::ppn, ULL, AlphaISA::Kernel::user, AlphaISA::TlbEntry::xre, and AlphaISA::TlbEntry::xwe.
Referenced by setMiscReg().
void AlphaISA::ISA::setMiscReg (int misc_reg, const MiscReg & val, ThreadContext * tc, ThreadID tid = 0)
Definition at line 142 of file isa.cc.
References fpcr, intr_flag, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, setIpr(), and uniq.
void AlphaISA::ISA::setMiscRegNoEffect (int misc_reg, const MiscReg & val, ThreadID tid = 0)
Definition at line 116 of file isa.cc.
References fpcr, intr_flag, ipr, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, AlphaISA::NumInternalProcRegs, and uniq.
void AlphaISA::ISA::startup (ThreadContext * tc) [inline]
Definition at line 127 of file isa.hh.
void AlphaISA::ISA::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented from Serializable.
Definition at line 66 of file isa.cc.
References fpcr, ipr, lock_addr, lock_flag, AlphaISA::NumInternalProcRegs, uniq, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Member Data Documentation
uint64_t AlphaISA::ISA::fpcr [protected]
Definition at line 62 of file isa.hh.
Referenced by clear(), readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
int AlphaISA::ISA::intr_flag [protected]
Definition at line 66 of file isa.hh.
Referenced by clear(), readMiscReg(), readMiscRegNoEffect(), setMiscReg(), and setMiscRegNoEffect().
InternalProcReg AlphaISA::ISA::ipr[NumInternalProcRegs] [protected]
Definition at line 68 of file isa.hh.
Referenced by clear(), readIpr(), readMiscRegNoEffect(), serialize(), setIpr(), setMiscRegNoEffect(), and unserialize().
Addr AlphaISA::ISA::lock_addr [protected]
Definition at line 65 of file isa.hh.
Referenced by clear(), readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
bool AlphaISA::ISA::lock_flag [protected]
Definition at line 64 of file isa.hh.
Referenced by clear(), readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
System* AlphaISA::ISA::system [protected]
Definition at line 60 of file isa.hh.
uint64_t AlphaISA::ISA::uniq [protected]
Definition at line 63 of file isa.hh.
Referenced by clear(), readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
The documentation for this class was generated from the following files:
arch/alpha/isa.hh
arch/alpha/ev5.cc
arch/alpha/isa.cc