gem5: Trace::InstRecord Class Reference
Trace::InstRecord Class Reference
#include <insttracer.hh>
Public Member Functions
InstRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
virtual ~InstRecord ()
void setWhen (Tick new_when)
void setMem (Addr a, Addr s, unsigned f)
void setData (Twin64_t d)
void setData (Twin32_t d)
void setData (uint64_t d)
void setData (uint32_t d)
void setData (uint16_t d)
void setData (uint8_t d)
void setData (int64_t d)
void setData (int32_t d)
void setData (int16_t d)
void setData (int8_t d)
void setData (double d)
void setFetchSeq (InstSeqNum seq)
void setCPSeq (InstSeqNum seq)
void setPredicate (bool val)
virtual void dump ()=0
Tick getWhen () const
ThreadContext * getThread () const
StaticInstPtr getStaticInst () const
TheISA::PCState getPCState () const
StaticInstPtr getMacroStaticInst () const
Addr getAddr () const
Addr getSize () const
unsigned getFlags () const
bool getMemValid () const
uint64_t getIntData () const
double getFloatData () const
int getDataStatus () const
InstSeqNum getFetchSeq () const
bool getFetchSeqValid () const
InstSeqNum getCpSeq () const
bool getCpSeqValid () const
Protected Types
enum {
DataInvalid = 0, DataInt8 = 1, DataInt16 = 2, DataInt32 = 4,
DataInt64 = 8, DataDouble = 3
}
What size of data was written?
Protected Attributes
Tick when
ThreadContext * thread
StaticInstPtr staticInst
TheISA::PCState pc
StaticInstPtr macroStaticInst
Addr addr
The address that was accessed.
Addr size
The size of the memory request.
unsigned flags
The flags that were assigned to the request.
union {
uint64_t as_int
double as_double
} data
InstSeqNum fetch_seq
InstSeqNum cp_seq
enum Trace::InstRecord:: { ... } data_status
What size of data was written?
bool mem_valid
Are the memory fields in the record valid?
bool fetch_seq_valid
Are the fetch sequence number fields valid?
bool cp_seq_valid
Are the commit sequence number fields valid?
bool predicate
is the predicate for execution this inst true or false (not execed)?
Detailed Description
Definition at line 58 of file insttracer.hh.
Constructor & Destructor Documentation
Trace::InstRecord::InstRecord (Tick _when, ThreadContext * _thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst = NULL) [inline]
Definition at line 145 of file insttracer.hh.
virtual Trace::InstRecord::~InstRecord () [inline, virtual]
Definition at line 155 of file insttracer.hh.
Member Function Documentation
virtual void Trace::InstRecord::dump () [pure virtual]
Implemented in Trace::ExeTracerRecord, Trace::InstPBTraceRecord, Trace::IntelTraceRecord, and Trace::NativeTraceRecord.
Referenced by BaseSimpleCPU::postExecute(), and Checker< Impl >::verify().
Addr Trace::InstRecord::getAddr () const [inline]
Definition at line 194 of file insttracer.hh.
References addr.
Referenced by Trace::InstPBTraceRecord::dump().
InstSeqNum Trace::InstRecord::getCpSeq () const [inline]
Definition at line 206 of file insttracer.hh.
References cp_seq.
bool Trace::InstRecord::getCpSeqValid () const [inline]
Definition at line 207 of file insttracer.hh.
References cp_seq_valid.
int Trace::InstRecord::getDataStatus () const [inline]
Definition at line 201 of file insttracer.hh.
References data_status.
InstSeqNum Trace::InstRecord::getFetchSeq () const [inline]
Definition at line 203 of file insttracer.hh.
References fetch_seq.
bool Trace::InstRecord::getFetchSeqValid () const [inline]
Definition at line 204 of file insttracer.hh.
References fetch_seq_valid.
unsigned Trace::InstRecord::getFlags () const [inline]
Definition at line 196 of file insttracer.hh.
References flags.
Referenced by Trace::InstPBTraceRecord::dump().
double Trace::InstRecord::getFloatData () const [inline]
Definition at line 200 of file insttracer.hh.
References data.
uint64_t Trace::InstRecord::getIntData () const [inline]
Definition at line 199 of file insttracer.hh.
References data.
StaticInstPtr Trace::InstRecord::getMacroStaticInst () const [inline]
Definition at line 192 of file insttracer.hh.
References macroStaticInst.
Referenced by Trace::ArmNativeTrace::check().
bool Trace::InstRecord::getMemValid () const [inline]
Definition at line 197 of file insttracer.hh.
References mem_valid.
Referenced by Trace::InstPBTraceRecord::dump(), and Trace::ExeTracerRecord::traceInst().
TheISA::PCState Trace::InstRecord::getPCState () const [inline]
Definition at line 191 of file insttracer.hh.
References pc.
Addr Trace::InstRecord::getSize () const [inline]
Definition at line 195 of file insttracer.hh.
References size.
Referenced by Trace::InstPBTraceRecord::dump().
StaticInstPtr Trace::InstRecord::getStaticInst () const [inline]
Definition at line 190 of file insttracer.hh.
References staticInst.
Referenced by Trace::X86NativeTrace::check(), and Trace::ArmNativeTrace::check().
ThreadContext* Trace::InstRecord::getThread () const [inline]
Definition at line 189 of file insttracer.hh.
References thread.
Referenced by Trace::X86NativeTrace::check(), Trace::SparcNativeTrace::check(), and Trace::ArmNativeTrace::check().
Tick Trace::InstRecord::getWhen () const [inline]
Definition at line 188 of file insttracer.hh.
References when.
void Trace::InstRecord::setCPSeq (InstSeqNum seq) [inline]
Definition at line 180 of file insttracer.hh.
References cp_seq, and cp_seq_valid.
void Trace::InstRecord::setData (double d) [inline]
Definition at line 175 of file insttracer.hh.
References data, data_status, and DataDouble.
void Trace::InstRecord::setData (int8_t d) [inline]
Definition at line 173 of file insttracer.hh.
References setData().
Referenced by setData().
void Trace::InstRecord::setData (int16_t d) [inline]
Definition at line 172 of file insttracer.hh.
References setData().
Referenced by setData().
void Trace::InstRecord::setData (int32_t d) [inline]
Definition at line 171 of file insttracer.hh.
References setData().
Referenced by setData().
void Trace::InstRecord::setData (int64_t d) [inline]
Definition at line 170 of file insttracer.hh.
References setData().
Referenced by setData().
void Trace::InstRecord::setData (uint8_t d) [inline]
Definition at line 168 of file insttracer.hh.
References data, data_status, and DataInt8.
void Trace::InstRecord::setData (uint16_t d) [inline]
Definition at line 167 of file insttracer.hh.
References data, data_status, and DataInt16.
void Trace::InstRecord::setData (uint32_t d) [inline]
Definition at line 166 of file insttracer.hh.
References data, data_status, and DataInt32.
void Trace::InstRecord::setData (uint64_t d) [inline]
Definition at line 165 of file insttracer.hh.
References data, data_status, and DataInt64.
void Trace::InstRecord::setData (Twin32_t d) [inline]
Definition at line 164 of file insttracer.hh.
References m5_twin32_t::a, data, data_status, and DataInt32.
void Trace::InstRecord::setData (Twin64_t d) [inline]
Definition at line 163 of file insttracer.hh.
References m5_twin64_t::a, data, data_status, and DataInt64.
Referenced by X86ISA::getMem(), getMem(), X86ISA::readMemAtomic(), readMemAtomic(), X86ISA::writeMemTiming(), and writeMemTiming().
void Trace::InstRecord::setFetchSeq (InstSeqNum seq) [inline]
Definition at line 177 of file insttracer.hh.
References fetch_seq, and fetch_seq_valid.
void Trace::InstRecord::setMem (Addr a, Addr s, unsigned f) [inline]
Definition at line 158 of file insttracer.hh.
References addr, flags, mem_valid, and size.
Referenced by TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), BaseDynInst< Impl >::readMem(), TimingSimpleCPU::writeMem(), AtomicSimpleCPU::writeMem(), and BaseDynInst< Impl >::writeMem().
void Trace::InstRecord::setPredicate (bool val) [inline]
Definition at line 183 of file insttracer.hh.
References predicate.
Referenced by BaseDynInst< Impl >::setPredicate(), and BaseSimpleCPU::setPredicate().
void Trace::InstRecord::setWhen (Tick new_when) [inline]
Definition at line 157 of file insttracer.hh.
References when.
Member Data Documentation
Addr Trace::InstRecord::addr [protected]
The address that was accessed.
Definition at line 83 of file insttracer.hh.
Referenced by Trace::IntelTraceRecord::dump(), getAddr(), setMem(), and Trace::ExeTracerRecord::traceInst().
double Trace::InstRecord::as_double
Definition at line 99 of file insttracer.hh.
uint64_t Trace::InstRecord::as_int
Definition at line 98 of file insttracer.hh.
InstSeqNum Trace::InstRecord::cp_seq [protected]
Definition at line 112 of file insttracer.hh.
Referenced by getCpSeq(), setCPSeq(), and Trace::ExeTracerRecord::traceInst().
union { ... } Trace::InstRecord::data [protected]
Referenced by getFloatData(), getIntData(), setData(), and Trace::ExeTracerRecord::traceInst().
InstSeqNum Trace::InstRecord::fetch_seq [protected]
Definition at line 106 of file insttracer.hh.
Referenced by getFetchSeq(), setFetchSeq(), and Trace::ExeTracerRecord::traceInst().
unsigned Trace::InstRecord::flags [protected]
The flags that were assigned to the request.
Definition at line 85 of file insttracer.hh.
Referenced by getFlags(), and setMem().
StaticInstPtr Trace::InstRecord::macroStaticInst [protected]
Definition at line 70 of file insttracer.hh.
Referenced by Trace::InstPBTraceRecord::dump(), Trace::ExeTracerRecord::dump(), and getMacroStaticInst().
bool Trace::InstRecord::mem_valid [protected]
Are the memory fields in the record valid?
Definition at line 129 of file insttracer.hh.
Referenced by getMemValid(), and setMem().
TheISA::PCState Trace::InstRecord::pc [protected]
Definition at line 69 of file insttracer.hh.
Referenced by Trace::IntelTraceRecord::dump(), Trace::InstPBTraceRecord::dump(), getPCState(), and Trace::ExeTracerRecord::traceInst().
bool Trace::InstRecord::predicate [protected]
is the predicate for execution this inst true or false (not execed)?
Definition at line 142 of file insttracer.hh.
Referenced by setPredicate(), and Trace::ExeTracerRecord::traceInst().
Addr Trace::InstRecord::size [protected]
The size of the memory request.
Definition at line 84 of file insttracer.hh.
Referenced by getSize(), and setMem().
StaticInstPtr Trace::InstRecord::staticInst [protected]
Definition at line 68 of file insttracer.hh.
Referenced by Trace::IntelTraceRecord::dump(), Trace::InstPBTraceRecord::dump(), Trace::ExeTracerRecord::dump(), Trace::NativeTraceRecord::dump(), and getStaticInst().
ThreadContext* Trace::InstRecord::thread [protected]
Definition at line 65 of file insttracer.hh.
Referenced by Trace::InstPBTraceRecord::dump(), getThread(), and Trace::ExeTracerRecord::traceInst().
Tick Trace::InstRecord::when [protected]
Definition at line 61 of file insttracer.hh.
Referenced by Trace::IntelTraceRecord::dump(), getWhen(), and setWhen().
The documentation for this class was generated from the following file:
sim/insttracer.hh