gem5: VirtIOConsole Class Reference
VirtIOConsole Class Reference
VirtIO console.
#include <console.hh>
Classes
struct Config
Console configuration structure.
class TermRecvQueue
Virtqueue for data going from the host to the guest.
class TermTransQueue
Virtqueue for data going from the guest to the host.
Public Types
typedef VirtIOConsoleParams Params
Public Member Functions
VirtIOConsole (Params *params)
virtual ~VirtIOConsole ()
void readConfig (PacketPtr pkt, Addr cfgOffset)
Read from the configuration space of a device.
Protected Attributes
struct VirtIOConsole::Config M5_ATTR_PACKED
Console configuration structure.
Config config
Currently active configuration (host byte order).
TermRecvQueue qRecv
Receive queue for port 0.
TermTransQueue qTrans
Transmit queue for port 0.
Terminal & term
MakeCallback
< VirtIOConsole::TermRecvQueue,&VirtIOConsole::TermRecvQueue::trySend > callbackDataAvail
Static Protected Attributes
static const DeviceId ID_CONSOLE = 0x03
VirtIO device ID.
Feature bits
static const FeatureBits F_SIZE = 0x01
Provides the size information.
static const FeatureBits F_MULTIPORT = 0x02
Supports the multi-port interface.
Detailed Description
VirtIO console.
The VirtIO console uses the following queues:
Port0 receive (from host to guest)
Port0 transmit (from guest to host)
Control receive (optional)
Control transmit (optional)
Port1 receive (optional)
Port1 transmit (optional)
This implementation implements the minimum of features for one port, which means that the multiport feature is not announced and only queue 0 and 1 are available.
See also:
https://github.com/rustyrussell/virtio-spec
http://docs.oasis-open.org/virtio/virtio/v1.0/virtio-v1.0.html
Definition at line 66 of file console.hh.
Member Typedef Documentation
typedef VirtIOConsoleParams VirtIOConsole::Params
Reimplemented from SimObject.
Definition at line 69 of file console.hh.
Constructor & Destructor Documentation
VirtIOConsole::VirtIOConsole (Params * params)
Definition at line 46 of file console.cc.
References callbackDataAvail, VirtIOConsole::Config::cols, config, qRecv, qTrans, Terminal::regDataAvailCallback(), VirtIODeviceBase::registerQueue(), VirtIOConsole::Config::rows, and term.
VirtIOConsole::~VirtIOConsole () [virtual]
Definition at line 62 of file console.cc.
Member Function Documentation
void VirtIOConsole::readConfig (PacketPtr pkt, Addr cfgOffset) [virtual]
Read from the configuration space of a device.
This method is called by the transport interface to read data from a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning:
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters:
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
Reimplemented from VirtIODeviceBase.
Definition at line 66 of file console.cc.
References VirtIOConsole::Config::cols, config, htov_legacy(), VirtIODeviceBase::readConfigBlob(), and VirtIOConsole::Config::rows.
Member Data Documentation
MakeCallback<VirtIOConsole::TermRecvQueue, &VirtIOConsole::TermRecvQueue::trySend> VirtIOConsole::callbackDataAvail [protected]
Definition at line 152 of file console.hh.
Referenced by VirtIOConsole().
Config VirtIOConsole::config [protected]
Currently active configuration (host byte order).
Definition at line 88 of file console.hh.
Referenced by readConfig(), and VirtIOConsole().
const FeatureBits VirtIOConsole::F_MULTIPORT = 0x02 [static, protected]
Supports the multi-port interface.
Definition at line 99 of file console.hh.
const FeatureBits VirtIOConsole::F_SIZE = 0x01 [static, protected]
Provides the size information.
Definition at line 97 of file console.hh.
const DeviceId VirtIOConsole::ID_CONSOLE = 0x03 [static, protected]
VirtIO device ID.
Definition at line 91 of file console.hh.
struct VirtIOConsole::Config VirtIOConsole::M5_ATTR_PACKED [protected]
Console configuration structure.
Note:
This needs to be changed if the multiport feature is announced!
TermRecvQueue VirtIOConsole::qRecv [protected]
Receive queue for port 0.
Definition at line 126 of file console.hh.
Referenced by VirtIOConsole().
TermTransQueue VirtIOConsole::qTrans [protected]
Transmit queue for port 0.
Definition at line 147 of file console.hh.
Referenced by VirtIOConsole().
Terminal& VirtIOConsole::term [protected]
Definition at line 150 of file console.hh.
Referenced by VirtIOConsole::TermTransQueue::onNotifyDescriptor(), VirtIOConsole::TermRecvQueue::trySend(), and VirtIOConsole().
The documentation for this class was generated from the following files:
dev/virtio/console.hh
dev/virtio/console.cc