gem5: Port Class Reference
Port Class Reference
Ports are used to interface memory objects to each other.
#include <port.hh>
Public Member Functions
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
Protected Member Functions
Port (const std::string &_name, MemObject &_owner, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Attributes
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
MemObject & owner
A reference to the MemObject that owns this port.
Private Attributes
std::string portName
Descriptive name (for DPRINTF output).
Detailed Description
Ports are used to interface memory objects to each other.
A port is either a master or a slave and the connected peer is always of the opposite role. Each port has a name, an owner, and an identifier.
Definition at line 63 of file port.hh.
Constructor & Destructor Documentation
Port::Port (const std::string & _name, MemObject & _owner, PortID _id) [protected]
Abstract base class for ports.
Parameters:
_name Port name including the owners name
_owner The MemObject that is the structural owner of this port
_id A port identifier for vector ports
Definition at line 53 of file port.cc.
Port::~Port () [protected, virtual]
Virtual destructor due to inheritance.
Reimplemented in ExternalMaster::Port, and ExternalSlave::Port.
Definition at line 58 of file port.cc.
Member Function Documentation
PortID Port::getId () const [inline]
Get the port id.
Definition at line 102 of file port.hh.
References id.
Referenced by SnoopFilter::portToMask().
const std::string Port::name () const [inline]
Return port name (for DPRINTF).
Definition at line 99 of file port.hh.
References portName.
Referenced by MasterPort::bind(), BaseSlavePort::getMasterPort(), BaseMasterPort::getSlavePort(), SnoopFilter::lookupRequest(), RespPacketQueue::name(), SnoopRespPacketQueue::name(), ReqPacketQueue::name(), MessageSlavePort::recvAtomic(), MasterPort::recvAtomicSnoop(), Bridge::BridgeSlavePort::recvFunctional(), MasterPort::recvFunctionalSnoop(), RubyTester::CpuPort::recvReqRetry(), RubyDirectedTester::CpuPort::recvReqRetry(), MasterPort::recvRetrySnoopResp(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), MasterPort::recvTimingSnoopReq(), SlavePort::recvTimingSnoopResp(), CoherentXBar::recvTimingSnoopResp(), DMASequencer::ruby_hit_callback(), SlavePort::sendRangeChange(), MasterPort::unbind(), SnoopFilter::updateRequest(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
Member Data Documentation
const PortID Port::id [protected]
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Definition at line 77 of file port.hh.
Referenced by getId(), RubyPort::MemSlavePort::recvTimingReq(), and DMASequencer::MemSlavePort::recvTimingReq().
MemObject& Port::owner [protected]
A reference to the MemObject that owns this port.
Reimplemented in ExternalMaster::Port, and ExternalSlave::Port.
Definition at line 80 of file port.hh.
Referenced by BaseCache::CacheSlavePort::clearBlocked(), RubyPort::PioSlavePort::getAddrRanges(), RubyPort::MemSlavePort::isPhysMemAddress(), DMASequencer::MemSlavePort::isPhysMemAddress(), AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop(), RubyPort::MemSlavePort::recvFunctional(), AtomicSimpleCPU::AtomicCPUDPort::recvFunctionalSnoop(), RubyPort::PioMasterPort::recvRangeChange(), RubyPort::MemSlavePort::recvTimingReq(), RubyPort::PioSlavePort::recvTimingReq(), DMASequencer::MemSlavePort::recvTimingReq(), RubyPort::PioMasterPort::recvTimingResp(), and BaseCache::CacheSlavePort::setBlocked().
std::string Port::portName [private]
Descriptive name (for DPRINTF output).
Definition at line 69 of file port.hh.
Referenced by name().
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc