gem5: sim/core.cc File Reference
sim/core.cc File Reference
#include <iostream>
#include <string>
#include "base/callback.hh"
#include "base/output.hh"
#include "sim/core.hh"
#include "sim/eventq.hh"
Namespaces
namespace SimClock
These are variables that are set based on the simulator frequency.
namespace SimClock::Float
namespace SimClock::Int
These variables equal the number of ticks in the unit of time they're named after in a 64 bit integer.
Functions
void setClockFrequency (Tick ticksPerSecond)
void setOutputDir (const string &dir)
CallbackQueue & exitCallbacks ()
Queue of C++ callbacks to invoke on simulator exit.
void registerExitCallback (Callback *callback)
Register an exit callback.
void doExitCleanup ()
Do C++ simulator exit processing.
Variables
Tick SimClock::Frequency
The simulated frequency of curTick(). (In ticks per second).
Tick SimClock::Int::s
second
Tick SimClock::Int::ms
millisecond
Tick SimClock::Int::us
microsecond
Tick SimClock::Int::ns
nanosecond
Tick SimClock::Int::ps
picosecond
double SimClock::Float::s
These variables equal the number of ticks in the unit of time they're named after in a double.
double SimClock::Float::ms
millisecond
double SimClock::Float::us
microsecond
double SimClock::Float::ns
nanosecond
double SimClock::Float::ps
picosecond
double SimClock::Float::Hz
These variables the inverse of above.
double SimClock::Float::kHz
kHz
double SimClock::Float::MHz
MHz.
double SimClock::Float::GHZ
GHz.
Function Documentation
void doExitCleanup ()
Do C++ simulator exit processing.
Exported to SWIG to be invoked when simulator terminates via Python's atexit mechanism.
Definition at line 125 of file core.cc.
References CallbackQueue::clear(), exitCallbacks(), and CallbackQueue::process().
CallbackQueue& exitCallbacks () [inline]
Queue of C++ callbacks to invoke on simulator exit.
Definition at line 105 of file core.cc.
Referenced by doExitCleanup(), and registerExitCallback().
void registerExitCallback (Callback * callback)
Register an exit callback.
Register a callback to be called when Python exits.
Definition at line 115 of file core.cc.
References CallbackQueue::add(), and exitCallbacks().
Referenced by CommMonitor::CommMonitor(), CowDiskImage::CowDiskImage(), Trace::InstPBTrace::createTraceFile(), InsertionProfiler::InsertionProfiler(), O3ThreadState< Impl >::O3ThreadState(), BaseTags::regStats(), and SimpleThread::SimpleThread().
void setClockFrequency (Tick ticksPerSecond)
Definition at line 72 of file core.cc.
References SimClock::Frequency, SimClock::Float::GHZ, SimClock::Float::Hz, SimClock::Float::kHz, SimClock::Float::MHz, SimClock::Float::ms, ArmISA::ns, ArmISA::ps, ArmISA::s, and SimClock::Float::us.
void setOutputDir (const string & dir)
Definition at line 96 of file core.cc.
References OutputDirectory::setDirectory(), and simout.