gem5: sim/core.hh File Reference
sim/core.hh File Reference
#include <string>
#include "base/types.hh"
#include "sim/eventq.hh"
Namespaces
namespace SimClock
These are variables that are set based on the simulator frequency.
namespace SimClock::Float
namespace SimClock::Int
These variables equal the number of ticks in the unit of time they're named after in a 64 bit integer.
Functions
Tick curTick ()
The universal simulation clock.
void setClockFrequency (Tick ticksPerSecond)
void setOutputDir (const std::string &dir)
void registerExitCallback (Callback *callback)
Register an exit callback.
void doExitCleanup ()
Do C++ simulator exit processing.
Variables
const Tick retryTime = 1000
Function Documentation
Tick curTick () [inline]
The universal simulation clock.
The current simulated tick.
Definition at line 47 of file core.hh.
References _curEventQueue, and EventQueue::getCurTick().
Referenced by __base_message_epilogue(), __exit_epilogue(), abortHandler(), DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), BaseSetAssoc::accessBlock(), FlashDevice::accessDevice(), FlashDevice::actionComplete(), SimpleThread::activate(), O3ThreadContext< Impl >::activate(), FullO3CPU< Impl >::activateContext(), Averager::add(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), CacheMemory::allocate(), ReusabilityProfiler::BlockSample::BlockSample(), DefaultFetch< Impl >::buildInst(), BaseXBar::calcPacketTiming(), VncInput::captureFrameBuffer(), Sinic::Device::changeConfig(), AlphaISA::Kernel::Statistics::changeMode(), FlashDevice::checkDrain(), DRAMCtrl::Rank::checkDrainDone(), IGbE::chkInterrupt(), Averager::clear(), BaseCache::CacheSlavePort::clearBlocked(), UFSHostDevice::clearInterrupt(), Intel8254Timer::Counter::CounterEvent::clocksLeft(), Minor::Execute::commit(), DefaultCommit< Impl >::commitHead(), MemTest::completeRequest(), LSQUnit< Impl >::completeStore(), BaseSetAssoc::computeStats(), Sinic::Base::cpuInterrupt(), NSGigE::cpuInterrupt(), Sinic::Base::cpuIntrPost(), NSGigE::cpuIntrPost(), IGbE::cpuPostInt(), DefaultDecode< Impl >::decodeInsts(), PacketQueue::deferredPacketReady(), SimpleMemory::dequeue(), Sinic::Device::devIntrChangeMask(), NSGigE::devIntrChangeMask(), Sinic::Device::devIntrPost(), NSGigE::devIntrPost(), DefaultIEW< Impl >::dispatchInsts(), Pl111::dmaDone(), IdeDisk::doDmaDataRead(), IdeDisk::doDmaDataWrite(), IdeDisk::doDmaRead(), IdeDisk::doDmaTransfer(), IdeDisk::doDmaWrite(), DRAMCtrl::doDRAMAccess(), ArmISA::TableWalker::doL1DescriptorWrapper(), ArmISA::TableWalker::doL2DescriptorWrapper(), ArmISA::TableWalker::doLongDescriptorWrapper(), doSimLoop(), SyscallDesc::doSyscall(), StoreTrace::downgrade(), DRAMCtrl::drain(), EventQueue::dump(), PCEventQueue::dump(), CheckerCPU::dumpAndExit(), EtherDump::dumpPacket(), TraceGen::enter(), TrafficGen::enterState(), Event::Event(), DefaultFetch< Impl >::fetch(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::fetchDescriptors1(), SnapMemCtrl::finalizeSnapshot(), UFSHostDevice::finalUTP(), FALRU::findVictim(), Minor::LSQ::SplitDataRequest::finish(), DefaultFetch< Impl >::finishTranslation(), ArmISA::flattenIntRegModeIndex(), getElapsedTimeMicro(), getElapsedTimeNano(), MSHRQueue::getNextMSHR(), Cache::getNextMSHR(), MipsISA::haltThread(), MipsISA::handleLockedWrite(), Checker< Impl >::handlePendingInt(), DmaPort::handleResp(), MSHR::handleSnoop(), Sequencer::hitCallback(), RubyPort::MemSlavePort::hitCallback(), DMASequencer::MemSlavePort::hitCallback(), RubyDirectedTester::hitCallback(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), Minor::Execute::issue(), Sequencer::issueRequest(), GDBListener::listen(), UFSHostDevice::LUNSignal(), MemTest::MemTest(), DRAMCtrl::minBankPrep(), TraceGen::nextPacketTick(), RandomGen::nextPacketTick(), LinearGen::nextPacketTick(), QueuedPrefetcher::notify(), BaseXBar::Layer< SrcType, DstType >::occupyLayer(), ArmISA::TableWalker::pendingChange(), DVFSHandler::perfLevel(), IGbE::TxDescCache::pktComplete(), IGbE::RxDescCache::pktComplete(), IGbE::postInterrupt(), BaseSimpleCPU::preExecute(), Stats::AvgSampleStor::prepare(), Stats::AvgStor::prepare(), Stats::StatEvent::process(), Stats::SimTicksReset::process(), GlobalSimLoopExitEvent::process(), GlobalSyncEvent::process(), Uart8250::IntrEvent::process(), MC146818::RTCTickEvent::process(), MC146818::RTCEvent::process(), EtherTap::process(), DumpStatsPCEvent::process(), DRAMCtrl::Rank::processActivateEvent(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::Rank::processPowerEvent(), DRAMCtrl::Rank::processPrechargeEvent(), DRAMCtrl::Rank::processRefreshEvent(), DRAMCtrl::processRespondEvent(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TableWalker::processWalkWrapper(), MSHR::promoteDeferredTargets(), MemChecker::ByteTracker::pruneTransactions(), Sp804::Timer::read(), CpuLocalTimer::Timer::read(), RealViewCtrl::read(), PL031::read(), LSQUnit< Impl >::read(), UFSHostDevice::readCallback(), DRAMSim2::readComplete(), Pl111::readFramebuffer(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), X86ISA::Interrupts::readReg(), SnapMemCtrl::recvAtomic(), CommMonitor::recvAtomic(), SnapMemCtrl::recvAtomicSnoop(), TrafficGen::recvReqRetry(), SimpleTimingPort::recvTimingReq(), SimpleMemory::recvTimingReq(), RubyPort::MemSlavePort::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), StubSlavePort::recvTimingReq(), DRAMCtrl::recvTimingReq(), CommMonitor::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), RubyPort::PioMasterPort::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), CommMonitor::recvTimingResp(), Cache::recvTimingResp(), HDLcd::renderPixel(), Request::Request(), UFSHostDevice::requestHandler(), ReusabilityProfiler::BlockSample::reset(), ReusabilityProfiler::reset(), Stats::AvgStor::reset(), ClockedObject::resetClock(), Sp804::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), CpuLocalTimer::Timer::restartWatchdogCounter(), MipsISA::restoreThread(), Stats::AvgStor::result(), PL031::resyncMatch(), EtherTap::retransmit(), StatTest::run(), Sinic::Device::rxKick(), NSGigE::rxKick(), ReusabilityProfiler::BlockSample::sample_as_dead(), ReusabilityProfiler::BlockSample::sample_as_reusable(), PolicySelector::sampleCounter(), Cacti::sampleLeak(), CommMonitor::samplePeriodic(), FLIP::samplePriorityPointer(), LRUProfiler::sampling(), FLIPProfiler::sampling(), PacketQueue::schedSendEvent(), PacketQueue::schedSendTiming(), Uart8250::IntrEvent::scheduleIntr(), MC146818::RTCEvent::scheduleIntr(), DRAMCtrl::Rank::schedulePowerEvent(), InstructionQueue< Impl >::scheduleReadyInsts(), EtherBus::send(), X86ISA::IntDevice::IntMasterPort::sendMessage(), DRAMSim2::sendResponse(), Globals::serialize(), RubySystem::serialize(), Sinic::Device::serialize(), Stats::AvgStor::set(), Request::setAccessLatency(), SystemCounter::setFreq(), Pl011::setInterrupts(), CacheMemory::setMRU(), X86ISA::Interrupts::setReg(), Intel8254Timer::Counter::CounterEvent::setTo(), Request::setTranslateLatency(), Request::setVirt(), Event::setWhen(), simulate(), SnapMemCtrl::SnapMemCtrl(), SnapMemCtrl::snapshot(), SnapMemCtrl::snapshotCycle(), DefaultRename< Impl >::sortInsts(), IdeDisk::startDma(), HDLcd::startFrame(), RubySystem::startup(), DRAMSim2::startup(), DRAMCtrl::Rank::startup(), DRAMCtrl::startup(), CommMonitor::startup(), LRUProfiler::startup(), FLIPProfiler::startup(), MC146818::startup(), Intel8254Timer::Counter::startup(), BaseKvmCPU::startup(), StoreTrace::store(), SimpleThread::suspend(), O3ThreadContext< Impl >::suspend(), Kernel::Statistics::swpipl(), tableFunc(), takeCheckpoint(), CacheMemory::testCacheAccess(), DRAMSim2::tick(), IGbE::tick(), NetworkTest::tick(), AtomicSimpleCPU::tick(), BaseKvmCPU::tick(), ReusabilityProfiler::tick_to_block(), timesFunc(), Root::timeSync(), Root::timeSyncEnable(), Trace::InstPBTrace::traceInst(), NSGigE::transmit(), EtherLink::Link::transmit(), BankedArray::tryAccess(), CacheMemory::tryCacheAccess(), Bridge::BridgeSlavePort::trySendTiming(), Bridge::BridgeMasterPort::trySendTiming(), EtherLink::Link::txDone(), Sinic::Device::txKick(), NSGigE::txKick(), Sinic::Device::unserialize(), NSGigE::unserialize(), ClockedObject::update(), TrafficGen::update(), ArchTimer::updateCounter(), DefaultIEW< Impl >::updateExeInstStats(), VGic::updateIntState(), Pl390::updateIntState(), Pl050::updateIntStatus(), FLIP::updatePriorityPointer(), Checker< Impl >::validateExecution(), Checker< Impl >::validateInst(), Checker< Impl >::validateState(), SystemCounter::value(), Checker< Impl >::verify(), RubyTester::wakeup(), RubyDirectedTester::wakeup(), ArmISA::TableWalker::walk(), System::workItemBegin(), System::workItemEnd(), Uart8250::write(), UFSHostDevice::write(), PL031::write(), EnergyCtrl::write(), AlphaBackdoor::write(), IGbE::DescCache< T >::writeback(), IGbE::DescCache< T >::writeback1(), Cache::writebackBlk(), LSQUnit< Impl >::writebackStores(), DRAMSim2::writeComplete(), MC146818::writeData(), UFSHostDevice::writeDevice(), AtomicSimpleCPU::writeMem(), CheckerCPU::writeMem(), and MipsISA::yieldThread().
void doExitCleanup ()
Do C++ simulator exit processing.
Exported to SWIG to be invoked when simulator terminates via Python's atexit mechanism.
Definition at line 125 of file core.cc.
References CallbackQueue::clear(), exitCallbacks(), and CallbackQueue::process().
void registerExitCallback (Callback * callback)
Register an exit callback.
Definition at line 115 of file core.cc.
void setClockFrequency (Tick ticksPerSecond)
Definition at line 72 of file core.cc.
References SimClock::Frequency, SimClock::Float::GHZ, SimClock::Float::Hz, SimClock::Float::kHz, SimClock::Float::MHz, SimClock::Float::ms, ArmISA::ns, ArmISA::ps, ArmISA::s, and SimClock::Float::us.
void setOutputDir (const std::string & dir)
Variable Documentation
const Tick retryTime = 1000
Definition at line 49 of file core.hh.
Referenced by EtherTap::process(), EtherTap::retransmit(), and NSGigE::transmit().