gem5: base/cprintf.hh File Reference
base/cprintf.hh File Reference
#include <ios>
#include <iostream>
#include <list>
#include <string>
#include "base/cprintf_formats.hh"
Classes
struct cp::Print
Namespaces
namespace cp
Functions
void ccprintf (cp::Print &print)
template<typename T , typename... Args>
void ccprintf (cp::Print &print, const T &value, const Args &...args)
template<typename... Args>
void ccprintf (std::ostream &stream, const char *format, const Args &...args)
template<typename... Args>
void cprintf (const char *format, const Args &...args)
template<typename... Args>
std::string csprintf (const char *format, const Args &...args)
template<typename... Args>
void ccprintf (std::ostream &stream, const std::string &format, const Args &...args)
template<typename... Args>
void cprintf (const std::string &format, const Args &...args)
template<typename... Args>
std::string csprintf (const std::string &format, const Args &...args)
Function Documentation
template<typename... Args> void ccprintf (std::ostream & stream, const std::string & format, const Args &... args) [inline]
Definition at line 174 of file cprintf.hh.
References ccprintf().
template<typename... Args> void ccprintf (std::ostream & stream, const char * format, const Args &... args) [inline]
Definition at line 146 of file cprintf.hh.
References ccprintf().
template<typename T , typename... Args> void ccprintf (cp::Print & print, const T & value, const Args &... args) [inline]
Definition at line 137 of file cprintf.hh.
References cp::Print::add_arg(), and ccprintf().
void ccprintf (cp::Print & print) [inline]
Definition at line 130 of file cprintf.hh.
References cp::Print::end_args().
Referenced by __base_message(), __base_message_epilogue(), __exit_epilogue(), __exit_message(), abortHandler(), Terminal::accept(), Stats::Text::begin(), ccprintf(), MemTest::completeRequest(), cprintf(), csprintf(), X86ISA::PageFault::describe(), X86ISA::X86FaultBase::describe(), Trace::Logger::dprintf(), Trace::IntelTraceRecord::dump(), Trace::Logger::dump(), Stats::Text::end(), AbstractMemory::functionalAccess(), X86ISA::RegOpImm::generateDisassembly(), X86ISA::X86MicroopBase::generateDisassembly(), X86ISA::MediaOpImm::generateDisassembly(), PowerISA::IntRotateOp::generateDisassembly(), PowerISA::IntShiftOp::generateDisassembly(), PowerISA::IntImmOp::generateDisassembly(), PowerISA::IntOp::generateDisassembly(), PowerISA::FloatOp::generateDisassembly(), PowerISA::CondMoveOp::generateDisassembly(), PowerISA::CondLogicOp::generateDisassembly(), PowerISA::BranchRegCond::generateDisassembly(), PowerISA::BranchNonPCRelCond::generateDisassembly(), PowerISA::BranchPCRelCond::generateDisassembly(), PowerISA::BranchNonPCRel::generateDisassembly(), PowerISA::BranchPCRel::generateDisassembly(), ArmISA::FpRegRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), ArmISA::FpCondSelOp::generateDisassembly(), ArmISA::FpCondCompRegOp::generateDisassembly(), PowerISA::PowerStaticInst::generateDisassembly(), ArmISA::PredMacroOp::generateDisassembly(), RegRegRegImmOp64::generateDisassembly(), RegRegImmImmOp64::generateDisassembly(), PowerISA::MiscOp::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), RegImmRegOp::generateDisassembly(), RegRegImmImmOp::generateDisassembly(), RegImmImmOp::generateDisassembly(), RegMiscRegImmOp::generateDisassembly(), MiscRegRegImmOp::generateDisassembly(), RegRegImmOp::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), RegImmOp::generateDisassembly(), ImmOp::generateDisassembly(), MsrImmOp::generateDisassembly(), ArmISA::MemoryLiteral64::generateDisassembly(), ArmISA::MemoryEx64::generateDisassembly(), ArmISA::MemoryRaw64::generateDisassembly(), ArmISA::MemoryReg64::generateDisassembly(), ArmISA::MemoryPostIndex64::generateDisassembly(), ArmISA::MemoryPreIndex64::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), ArmISA::MemoryImm64::generateDisassembly(), ArmISA::SysDC64::generateDisassembly(), PowerISA::MemDispOp::generateDisassembly(), ArmISA::MicroMemPairOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::MicroIntRegXOp::generateDisassembly(), ArmISA::MicroIntImmXOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), ArmISA::DataX3RegOp::generateDisassembly(), ArmISA::DataX2RegImmOp::generateDisassembly(), ArmISA::DataX2RegOp::generateDisassembly(), ArmISA::DataX1Reg2ImmOp::generateDisassembly(), ArmISA::DataX1RegImmOp::generateDisassembly(), ArmISA::DataX1RegOp::generateDisassembly(), ArmISA::DataXImmOnlyOp::generateDisassembly(), ArmISA::BranchImmImmReg64::generateDisassembly(), ArmISA::BranchImmReg64::generateDisassembly(), Terminal::listen(), TapListener::listen(), VncServer::listen(), GDBListener::listen(), Trace::OstreamLogger::logMessage(), main(), Trace::NativeTrace::NativeTrace(), Stats::DistPrint::operator()(), Stats::ScalarPrint::operator()(), Net::operator<<(), X86ISA::operator<<(), GenericISA::operator<<(), MSHR::print(), MSHR::TargetList::print(), CacheBlkPrintWrapper::print(), ArmISA::ArmStaticInst::printDataInst(), ArmISA::ArmStaticInst::printExtendOperand(), Packet::PrintReqState::printLabels(), X86ISA::X86StaticInst::printMem(), ArmISA::ArmStaticInst::printMemSymbol(), X86ISA::X86StaticInst::printMnemonic(), ArmISA::MemoryImm::printOffset(), ArmISA::MemoryReg::printOffset(), X86ISA::X86StaticInst::printReg(), PowerISA::PowerStaticInst::printReg(), ArmISA::ArmStaticInst::printReg(), X86ISA::X86StaticInst::printSegment(), ArmISA::ArmStaticInst::printTarget(), DumpStatsPCEvent::process(), System::regStats(), ArmISA::ArmStaticInst::shift_carry_imm(), ArmISA::ArmStaticInst::shift_carry_rs(), ArmISA::ArmStaticInst::shift_rm_imm(), ArmISA::ArmStaticInst::shift_rm_rs(), ArmISA::ArmStaticInst::shiftReg64(), ArmISA::Memory64::startDisassembly(), and Trace::ExeTracerRecord::traceInst().
template<typename... Args> void cprintf (const std::string & format, const Args &... args) [inline]
Definition at line 180 of file cprintf.hh.
References ccprintf().
template<typename... Args> void cprintf (const char * format, const Args &... args) [inline]
Definition at line 155 of file cprintf.hh.
References ccprintf().
Referenced by Stats::Info::baseCheck(), EventQueue::debugVerify(), Event::dump(), EventQueue::dump(), BPredUnit::dump(), PCEventQueue::dump(), StoreSet::dump(), DependencyGraph< DynInstPtr >::dump(), BaseDynInst< Impl >::dump(), ActivityRecorder::dump(), Trie< Addr, X86ISA::TlbEntry >::dump(), Trie< Key, Value >::Node::dump(), CircleBuf::dump(), Checker< Impl >::dumpAndExit(), dumpDebugFlags(), DefaultRename< Impl >::dumpHistory(), LSQUnit< Impl >::dumpInsts(), InstructionQueue< Impl >::dumpInsts(), Checker< Impl >::dumpInsts(), FullO3CPU< Impl >::dumpInsts(), MemDepUnit< MemDepPred, Impl >::dumpLists(), InstructionQueue< Impl >::dumpLists(), StatTest::init(), main(), and InstructionQueue< Impl >::~InstructionQueue().
template<typename... Args> std::string csprintf (const std::string & format, const Args &... args) [inline]
Definition at line 186 of file cprintf.hh.
References csprintf().
template<typename... Args> std::string csprintf (const char * format, const Args &... args) [inline]
Definition at line 161 of file cprintf.hh.
References ccprintf().
Referenced by PerfectSwitch::addInPort(), CxxConfigManager::bindMasterPort(), CxxConfigManager::bindObjectPorts(), CxxConfigManager::bindPort(), CoherentXBar::CoherentXBar(), MemChecker::completeRead(), csprintf(), Pl111::dmaDone(), SimpleThread::dumpFuncProfile(), O3ThreadState< Impl >::dumpFuncProfile(), HDLcd::endFrame(), CxxConfigManager::findObject(), CxxConfigManager::findObjectParams(), CxxConfigManager::findObjectType(), FlushPipeInst::generateDisassembly(), WarnUnimplemented::generateDisassembly(), FailUnimplemented::generateDisassembly(), DecoderFaultInst::generateDisassembly(), UnknownOp64::generateDisassembly(), UnknownOp::generateDisassembly(), PowerISA::MemOp::generateDisassembly(), getEventQueue(), CxxConfigManager::getObject(), MemDepUnit< MemDepPred, Impl >::init(), MachineIDToString(), Event::name(), Throttle::name(), PerfectSwitch::name(), DRAMCtrl::Rank::name(), CopyEngine::CopyEngineChannel::name(), SimpleThread::name(), NoncoherentXBar::NoncoherentXBar(), Set::print(), BaseSetAssoc::print(), CacheBlk::print(), ArmISA::TlbEntry::print(), Linux::procMeminfo(), Profiler::regStats(), GarnetNetwork::regStats(), BaseGarnetNetwork::regStats(), RubyDirectedTester::RubyDirectedTester(), RubyPort::RubyPort(), RubyTester::RubyTester(), FuncPageTable::serialize(), Iob::serialize(), Sinic::Device::serialize(), PciDevice::serialize(), IGbE::serialize(), IGbE::DescCache< T >::serialize(), CopyEngine::serialize(), VGic::serialize(), Sp804::serialize(), CpuLocalTimer::serialize(), GenericTimerMem::serialize(), GenericTimer::serialize(), VirtIODeviceBase::serialize(), ArmISA::PMU::serialize(), X86ISA::TLB::serialize(), SparcISA::TLB::serialize(), Process::serialize(), CxxConfigManager::setParam(), CxxConfigManager::setParamVector(), Stats::SumNode< Op >::str(), Stats::BinaryNode< Op >::str(), Stats::ConstVectorNode< T >::str(), Stats::ScalarProxy< Stat >::str(), AddrRange::to_string(), Trace::ExeTracerRecord::traceInst(), EventQueue::unserialize(), FuncPageTable::unserialize(), Iob::unserialize(), Sinic::Device::unserialize(), PciDevice::unserialize(), IGbE::unserialize(), IGbE::DescCache< T >::unserialize(), CopyEngine::unserialize(), VGic::unserialize(), Sp804::unserialize(), CpuLocalTimer::unserialize(), GenericTimerMem::unserialize(), GenericTimer::unserialize(), VirtIODeviceBase::unserialize(), ArmISA::PMU::unserialize(), X86ISA::TLB::unserialize(), SparcISA::TLB::unserialize(), and Process::unserialize().