gem5: dev/virtio/base.cc File Reference
dev/virtio/base.cc File Reference
#include "debug/VIO.hh"
#include "dev/virtio/base.hh"
#include "params/VirtIODeviceBase.hh"
Functions
_address (0)
memProxy (proxy)
avail (proxy, size)
used (proxy, size)
_last_avail (0)
Function Documentation
_address (0)
_last_avail (0)
Definition at line 228 of file base.cc.
References ArmISA::i.
avail (proxy , size)
memProxy (proxy)
used (proxy , size)
Referenced by SparcISA::TLB::demapAll(), SparcISA::TLB::demapContext(), and SparcISA::TLB::insert().