gem5: mem/fs_translating_port_proxy.hh File Reference
mem/fs_translating_port_proxy.hh File Reference
TranslatingPortProxy Object Declaration for FS.
#include "mem/port_proxy.hh"
Classes
class FSTranslatingPortProxy
A TranslatingPortProxy in FS mode translates a virtual address to a physical address and then calls the read/write functions of the port.
Functions
void CopyOut (ThreadContext *tc, void *dest, Addr src, size_t cplen)
void CopyIn (ThreadContext *tc, Addr dest, const void *source, size_t cplen)
void CopyStringOut (ThreadContext *tc, char *dst, Addr vaddr, size_t maxlen)
void CopyStringIn (ThreadContext *tc, const char *src, Addr vaddr)
Detailed Description
TranslatingPortProxy Object Declaration for FS.
Port proxies are used when non structural entities need access to the memory system. Proxy objects replace the previous FunctionalPort, TranslatingPort and VirtualPort objects, which provided the same functionality as the proxies, but were instances of ports not corresponding to real structural ports of the simulated system. Via the port proxies all the accesses go through an actual port and thus are transparent to a potentially distributed memory and automatically adhere to the memory map of the system.
Definition in file fs_translating_port_proxy.hh.
Function Documentation
void CopyIn (ThreadContext * tc, Addr dest, const void * source, size_t cplen)
Definition at line 132 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), and FSTranslatingPortProxy::writeBlob().
void CopyOut (ThreadContext * tc, void * dest, Addr src, size_t cplen)
Definition at line 125 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), and FSTranslatingPortProxy::readBlob().
Referenced by Linux::ThreadInfo::curTaskInfo(), Linux::ThreadInfo::curTaskMm(), Linux::ThreadInfo::curTaskPID(), Linux::ThreadInfo::curTaskStart(), Linux::ThreadInfo::curTaskTGID(), X86ISA::StackTrace::decodePrologue(), MipsISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), Linux::ThreadInfo::get_data(), and Arguments::operator T *().
void CopyStringIn (ThreadContext * tc, const char * src, Addr vaddr)
Definition at line 157 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), AlphaISA::PageBytes, and FSTranslatingPortProxy::writeBlob().
void CopyStringOut (ThreadContext * tc, char * dst, Addr vaddr, size_t maxlen)
Definition at line 139 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), and FSTranslatingPortProxy::readBlob().
Referenced by Linux::ThreadInfo::curTaskName(), X86ISA::ProcessInfo::name(), MipsISA::ProcessInfo::name(), ArmISA::ProcessInfo::name(), AlphaISA::ProcessInfo::name(), and Arguments::operator char *().