gem5: arch/generic/memhelpers.hh File Reference
arch/generic/memhelpers.hh File Reference
#include "base/types.hh"
#include "mem/request.hh"
#include "sim/byteswap.hh"
#include "sim/insttracer.hh"
Functions
template<class XC , class MemT >
Fault readMemTiming (XC *xc, Trace::InstRecord *traceData, Addr addr, MemT &mem, unsigned flags)
Read from memory in timing mode.
template<class MemT >
void getMem (PacketPtr pkt, MemT &mem, Trace::InstRecord *traceData)
Extract the data returned from a timing mode read.
template<class XC , class MemT >
Fault readMemAtomic (XC *xc, Trace::InstRecord *traceData, Addr addr, MemT &mem, unsigned flags)
Read from memory in atomic mode.
template<class XC , class MemT >
Fault writeMemTiming (XC *xc, Trace::InstRecord *traceData, MemT mem, Addr addr, unsigned flags, uint64_t *res)
Write to memory in timing mode.
template<class XC , class MemT >
Fault writeMemAtomic (XC *xc, Trace::InstRecord *traceData, const MemT &mem, Addr addr, unsigned flags, uint64_t *res)
Write to memory in atomic mode.
Function Documentation
template<class MemT > void getMem (PacketPtr pkt, MemT & mem, Trace::InstRecord * traceData) [inline]
Extract the data returned from a timing mode read.
Definition at line 63 of file memhelpers.hh.
References Packet::get(), and Trace::InstRecord::setData().
template<class XC , class MemT > Fault readMemAtomic (XC * xc, Trace::InstRecord * traceData, Addr addr, MemT & mem, unsigned flags) [inline]
Read from memory in atomic mode.
Definition at line 73 of file memhelpers.hh.
References BigEndianGuest::gtoh(), readMemTiming(), and Trace::InstRecord::setData().
template<class XC , class MemT > Fault readMemTiming (XC * xc, Trace::InstRecord * traceData, Addr addr, MemT & mem, unsigned flags) [inline]
Read from memory in timing mode.
Definition at line 54 of file memhelpers.hh.
Referenced by readMemAtomic().
template<class XC , class MemT > Fault writeMemAtomic (XC * xc, Trace::InstRecord * traceData, const MemT & mem, Addr addr, unsigned flags, uint64_t * res) [inline]
Write to memory in atomic mode.
Definition at line 102 of file memhelpers.hh.
References BigEndianGuest::gtoh(), Request::MEM_SWAP, Request::MEM_SWAP_COND, and writeMemTiming().
template<class XC , class MemT > Fault writeMemTiming (XC * xc, Trace::InstRecord * traceData, MemT mem, Addr addr, unsigned flags, uint64_t * res) [inline]
Write to memory in timing mode.
Definition at line 89 of file memhelpers.hh.
References BigEndianGuest::htog(), and Trace::InstRecord::setData().
Referenced by writeMemAtomic().