gem5: KVM low-level ioctl interface.
KVM low-level ioctl interface.
These methods provide a low-level interface to the underlying KVM layer.
Functions
int BaseKvmCPU::ioctl (int request, long p1) const
vCPU ioctl interface.
int BaseKvmCPU::ioctl (int request, void *p1) const
int BaseKvmCPU::ioctl (int request) const
int Kvm::ioctl (int request, long p1) const
Main VM ioctl interface.
int Kvm::ioctl (int request, void *p1) const
int Kvm::ioctl (int request) const
int KvmVM::ioctl (int request, long p1) const
KVM VM ioctl interface.
int KvmVM::ioctl (int request, void *p1) const
int KvmVM::ioctl (int request) const
Detailed Description
These methods provide a low-level interface to the underlying KVM layer.
Function Documentation
int KvmVM::ioctl (int request) const [inline, protected, inherited]
Definition at line 493 of file vm.hh.
References KvmVM::ioctl(), and X86ISA::L.
int KvmVM::ioctl (int request, void * p1) const [inline, protected, inherited]
Definition at line 490 of file vm.hh.
References KvmVM::ioctl().
int KvmVM::ioctl (int request, long p1) const [protected, inherited]
KVM VM ioctl interface.
Parameters:
request KVM VM request
p1 Optional request parameter
Returns:
-1 on error (error number in errno), ioctl dependent value otherwise.
Definition at line 535 of file vm.cc.
References KvmVM::vmFD.
Referenced by KvmVM::coalesceMMIO(), KvmVM::createDevice(), KvmVM::createIRQChip(), KvmVM::createVCPU(), KvmVM::ioctl(), KvmVM::setIRQLine(), KvmVM::setTSSAddress(), and KvmVM::setUserMemoryRegion().
int Kvm::ioctl (int request) const [inline, protected, inherited]
Definition at line 232 of file vm.hh.
References Kvm::ioctl(), and X86ISA::L.
int Kvm::ioctl (int request, void * p1) const [inline, protected, inherited]
Definition at line 229 of file vm.hh.
References Kvm::ioctl().
int Kvm::ioctl (int request, long p1) const [protected, inherited]
Main VM ioctl interface.
Parameters:
request KVM request
p1 Optional request parameter
Returns:
-1 on error (error number in errno), ioctl dependent value otherwise.
Definition at line 272 of file vm.cc.
References Kvm::kvmFD.
Referenced by Kvm::checkExtension(), Kvm::createVM(), Kvm::ioctl(), and Kvm::Kvm().
int BaseKvmCPU::ioctl (int request) const [inline, protected, inherited]
Definition at line 539 of file base.hh.
References BaseKvmCPU::ioctl(), and X86ISA::L.
int BaseKvmCPU::ioctl (int request, void * p1) const [inline, protected, inherited]
Definition at line 536 of file base.hh.
References BaseKvmCPU::ioctl().
int BaseKvmCPU::ioctl (int request, long p1) const [protected, inherited]
vCPU ioctl interface.
Parameters:
request KVM vCPU request
p1 Optional request parameter
Returns:
-1 on error (error number in errno), ioctl dependent value otherwise.
Definition at line 1061 of file base.cc.
References panic, and BaseKvmCPU::vcpuFD.
Referenced by X86KvmCPU::getDebugRegisters(), BaseKvmCPU::getFPUState(), X86KvmCPU::getMSRs(), BaseKvmCPU::getOneReg(), BaseKvmCPU::getRegisters(), BaseArmKvmCPU::getRegList(), ArmKvmCPU::getRegList(), BaseKvmCPU::getSpecialRegisters(), X86KvmCPU::getVCpuEvents(), X86KvmCPU::getXCRs(), X86KvmCPU::getXSave(), BaseKvmCPU::ioctl(), BaseKvmCPU::ioctlRun(), BaseArmKvmCPU::kvmArmVCpuInit(), ArmKvmCPU::kvmArmVCpuInit(), BaseKvmCPU::kvmInterrupt(), BaseKvmCPU::kvmNonMaskableInterrupt(), X86KvmCPU::setCPUID(), X86KvmCPU::setDebugRegisters(), BaseKvmCPU::setFPUState(), X86KvmCPU::setMSRs(), BaseKvmCPU::setOneReg(), BaseKvmCPU::setRegisters(), BaseKvmCPU::setSignalMask(), BaseKvmCPU::setSpecialRegisters(), X86KvmCPU::setVCpuEvents(), X86KvmCPU::setXCRs(), and X86KvmCPU::setXSave().