gem5: sim/init.hh File Reference
sim/init.hh File Reference
#include <Python.h>
#include <list>
#include <inttypes.h>
Classes
struct EmbeddedPython
struct EmbeddedSwig
Typedefs
typedef _object PyObject
Functions
int initM5Python ()
int m5Main (int argc, char **argv)
PyMODINIT_FUNC initm5 (void)
Typedef Documentation
typedef _object PyObject
Definition at line 44 of file init.hh.
Function Documentation
PyMODINIT_FUNC initm5 (void)
Definition at line 239 of file init.cc.
References initM5Python(), and PyCC.
int initM5Python ()
Definition at line 176 of file init.cc.
References EmbeddedPython::initAll(), and EmbeddedSwig::initAll().
Referenced by initm5(), and main().
int m5Main (int argc, char ** argv)
Definition at line 197 of file init.cc.
References m5MainCommands, panic, and PyCC.
Referenced by main().