gem5: base/intmath.hh File Reference
base/intmath.hh File Reference
#include <cassert>
#include "base/misc.hh"
#include "base/types.hh"
Functions
int prevPrime (int n)
template<class T >
bool isPrime (const T &n)
template<class T >
T leastSigBit (const T &n)
template<class T >
bool isPowerOf2 (const T &n)
uint64_t power (uint32_t n, uint32_t e)
int floorLog2 (unsigned x)
int floorLog2 (unsigned long x)
int floorLog2 (unsigned long long x)
int floorLog2 (int x)
int floorLog2 (long x)
int floorLog2 (long long x)
template<class T >
int ceilLog2 (const T &n)
template<class T >
T floorPow2 (const T &n)
template<class T >
T ceilPow2 (const T &n)
template<class T , class U >
T divCeil (const T &a, const U &b)
template<class T , class U >
T roundUp (const T &val, const U &align)
template<class T , class U >
T roundDown (const T &val, const U &align)
bool isHex (char c)
bool isOct (char c)
bool isDec (char c)
int hex2Int (char c)
Function Documentation
template<class T > int ceilLog2 (const T & n) [inline]
Definition at line 174 of file intmath.hh.
References floorLog2().
Referenced by DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), ceilPow2(), DRAMCtrl::DRAMCtrl(), TimingExprUn::eval(), DirectoryMemory::init(), Pl390::Pl390(), and DRAMCtrl::regStats().
template<class T > T ceilPow2 (const T & n) [inline]
Definition at line 191 of file intmath.hh.
References ceilLog2().
template<class T , class U > T divCeil (const T & a, const U & b) [inline]
Definition at line 198 of file intmath.hh.
Referenced by DRAMCtrl::activateBank(), Process::allocateMem(), BaseXBar::calcPacketTiming(), DRAMCtrl::doDRAMAccess(), DRAMPower::getDataRate(), DRAMPower::getTimingParams(), TrafficGen::parseConfig(), DRAMCtrl::prechargeBank(), DRAMCtrl::Rank::processRefreshEvent(), DRAMSim2::readComplete(), DRAMCtrl::recvTimingReq(), ClockedObject::resetClock(), DRAMCtrl::startup(), AtomicSimpleCPU::tick(), ClockedObject::ticksToCycles(), ClockedObject::update(), and DRAMSim2::writeComplete().
int floorLog2 (long long x) [inline]
Definition at line 166 of file intmath.hh.
References floorLog2().
int floorLog2 (long x) [inline]
Definition at line 159 of file intmath.hh.
References floorLog2().
int floorLog2 (int x) [inline]
Definition at line 152 of file intmath.hh.
References floorLog2().
int floorLog2 (unsigned long long x) [inline]
Definition at line 135 of file intmath.hh.
References ULL.
int floorLog2 (unsigned long x) [inline]
Definition at line 116 of file intmath.hh.
References ULL.
int floorLog2 (unsigned x) [inline]
Definition at line 100 of file intmath.hh.
Referenced by Histogram::add(), CheckTable::addCheck(), BankedArray::BankedArray(), BaseSetAssoc::BaseSetAssoc(), ceilLog2(), DefaultBTB::DefaultBTB(), DirectoryMemory::DirectoryMemory(), FALRU::FALRU(), floorLog2(), floorPow2(), Gicv2m::Gicv2m(), CacheMemory::init(), MultiLevelPageTable< ISAOps >::initState(), StridePrefetcher::pcHash(), RubySystem::RubySystem(), StackDistCalc::update(), and MultiLevelPageTable< ISAOps >::walk().
template<class T > T floorPow2 (const T & n) [inline]
Definition at line 184 of file intmath.hh.
References floorLog2().
int hex2Int (char c) [inline]
Definition at line 240 of file intmath.hh.
bool isDec (char c) [inline]
Definition at line 234 of file intmath.hh.
bool isHex (char c) [inline]
Definition at line 220 of file intmath.hh.
bool isOct (char c) [inline]
Definition at line 228 of file intmath.hh.
template<class T > bool isPowerOf2 (const T & n) [inline]
Definition at line 73 of file intmath.hh.
References leastSigBit().
Referenced by BaseSetAssoc::BaseSetAssoc(), BiModeBP::BiModeBP(), ChunkGenerator::ChunkGenerator(), DefaultBTB::DefaultBTB(), DRAMCtrl::DRAMCtrl(), FALRU::FALRU(), Gicv2m::Gicv2m(), LocalBP::LocalBP(), PageTableBase::PageTableBase(), PciDevice::PciDevice(), RubySystem::RubySystem(), StoreSet::StoreSet(), StridePrefetcher::StridePrefetcher(), TournamentBP::TournamentBP(), and StackDistCalc::updateTree().
template<class T > bool isPrime (const T & n) [inline]
Definition at line 45 of file intmath.hh.
References ArmISA::i.
Referenced by prevPrime().
template<class T > T leastSigBit (const T & n) [inline]
Definition at line 66 of file intmath.hh.
Referenced by isPowerOf2().
uint64_t power (uint32_t n, uint32_t e) [inline]
Definition at line 79 of file intmath.hh.
References warn, and X86ISA::x.
Referenced by Sp804::Timer::read(), CpuLocalTimer::Timer::read(), A9SCU::read(), Pl390::readDistributor(), Sp804::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), and CpuLocalTimer::Timer::restartWatchdogCounter().
int prevPrime (int n)
Definition at line 35 of file intmath.cc.
References isPrime().
template<class T , class U > T roundDown (const T & val, const U & align) [inline]
Definition at line 213 of file intmath.hh.
References ArmISA::mask.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), brkFunc(), Process::fixupStackFault(), Tru64::nxm_task_initFunc(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), BasePrefetcher::samePage(), BaseDynInst< Impl >::splitRequest(), Tru64::stack_createFunc(), SETranslatingPortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryWriteBlob(), TimingSimpleCPU::writeMem(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
template<class T , class U > T roundUp (const T & val, const U & align) [inline]
Definition at line 205 of file intmath.hh.
References ArmISA::mask.
Referenced by AlphaLiveProcess::AlphaLiveProcess(), X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), ArmLiveProcess32::ArmLiveProcess32(), ArmLiveProcess64::ArmLiveProcess64(), brkFunc(), ChunkGenerator::ChunkGenerator(), Tru64::getdirentriesFunc(), X86System::initState(), MipsLiveProcess::MipsLiveProcess(), mmapFunc(), mremapFunc(), Tru64::nxm_task_initFunc(), PowerLiveProcess::PowerLiveProcess(), SparcLiveProcess::SparcLiveProcess(), Tru64::stack_createFunc(), and X86ISA::X86LiveProcess::X86LiveProcess().