gem5: mem/ruby/network/MessageBuffer.hh File Reference
mem/ruby/network/MessageBuffer.hh File Reference
#include <algorithm>
#include <cassert>
#include <functional>
#include <iostream>
#include <string>
#include <vector>
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/Consumer.hh"
#include "mem/ruby/network/MessageBufferNode.hh"
#include "mem/ruby/slicc_interface/Message.hh"
#include "mem/packet.hh"
Classes
class MessageBuffer
Functions
Cycles random_time ()
std::ostream & operator<< (std::ostream &out, const MessageBuffer &obj)
Function Documentation
std::ostream& operator<< (std::ostream & out, const MessageBuffer & obj) [inline]
Definition at line 208 of file MessageBuffer.hh.
References MessageBuffer::print().
Cycles random_time ()
Definition at line 134 of file MessageBuffer.cc.
References Random::random(), and random_mt.
Referenced by MessageBuffer::enqueue().