gem5: BigEndianGuest Namespace Reference
BigEndianGuest Namespace Reference
Functions
template<typename T >
T gtole (T value)
template<typename T >
T letog (T value)
template<typename T >
T gtobe (T value)
template<typename T >
T betog (T value)
template<typename T >
T htog (T value)
template<typename T >
T gtoh (T value)
Variables
const ByteOrder GuestByteOrder = BigEndianByteOrder
Function Documentation
template<typename T > T BigEndianGuest::betog (T value) [inline]
Definition at line 176 of file byteswap.hh.
template<typename T > T BigEndianGuest::gtobe (T value) [inline]
Definition at line 174 of file byteswap.hh.
Referenced by ArmISA::ArmStaticInst::cSwap().
template<typename T > T BigEndianGuest::gtoh (T value) [inline]
Definition at line 180 of file byteswap.hh.
References betoh().
Referenced by Trace::SparcNativeTrace::check(), ArmISA::ArmStaticInst::cSwap(), Minor::Fetch2::evaluate(), DefaultFetch< Impl >::fetch(), Packet::get(), Linux::ThreadInfo::get_data(), X86ISA::handleIprWrite(), Tru64::init_thread_context(), Tru64::m5_cond_waitFunc(), Tru64::m5_lock_mutex(), Tru64::m5_mutex_trylockFunc(), Tru64::nxm_task_initFunc(), Tru64::nxm_thread_createFunc(), osf_setsysinfoFunc(), BaseSimpleCPU::preExecute(), X86ISA::readMemAtomic(), readMemAtomic(), Tru64::stack_createFunc(), sys_setsysinfoFunc(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), utimesFunc(), Checker< Impl >::verify(), vtoh_legacy(), X86ISA::Interrupts::write(), X86ISA::writeMemAtomic(), writeMemAtomic(), X86ISA::SMBios::SMBiosTable::writeOut(), and writevFunc().
template<typename T > T BigEndianGuest::gtole (T value) [inline]
Definition at line 170 of file byteswap.hh.
References betole().
Referenced by ArmISA::ArmStaticInst::cSwap().
template<typename T > T BigEndianGuest::htog (T value) [inline]
Definition at line 178 of file byteswap.hh.
References htobe().
Referenced by _llseekFunc(), X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), AuxVector< IntType >::AuxVector(), clock_gettimeFunc(), convertStat64Buf(), convertStatBuf(), Tru64::copyOutStatfsBuf(), copyStringArray(), ArmISA::ArmStaticInst::cSwap(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), Tru64::getdirentriesFunc(), SparcISA::getresuidFunc(), getrlimitFunc(), getrusageFunc(), getsysinfoFunc(), gettimeofdayFunc(), X86ISA::handleIprRead(), X86ISA::handleIprWrite(), htov_legacy(), X86System::initState(), LinuxX86System::initState(), AlphaSystem::initState(), Tru64::m5_lock_mutex(), Tru64::m5_mutex_trylockFunc(), Tru64::nxm_task_initFunc(), Tru64::nxm_thread_createFunc(), X86ISA::Interrupts::read(), Packet::set(), AlphaSystem::setAlphaAccess(), Tru64::sigreturnFunc(), tableFunc(), timeFunc(), timesFunc(), X86ISA::writeMemTiming(), writeMemTiming(), X86ISA::SMBios::SMBiosTable::writeOut(), X86ISA::SMBios::BiosInformation::writeOut(), X86ISA::SMBios::SMBiosStructure::writeOut(), writeOutField(), X86ISA::E820Table::writeTo(), and writeVal().
template<typename T > T BigEndianGuest::letog (T value) [inline]
Definition at line 172 of file byteswap.hh.
References letobe().
Variable Documentation
const ByteOrder BigEndianGuest::GuestByteOrder = BigEndianByteOrder
Definition at line 168 of file byteswap.hh.