gem5: LittleEndianGuest Namespace Reference
LittleEndianGuest Namespace Reference
Functions
template<typename T >
T gtole (T value)
template<typename T >
T letog (T value)
template<typename T >
T gtobe (T value)
template<typename T >
T betog (T value)
template<typename T >
T htog (T value)
template<typename T >
T gtoh (T value)
Variables
const ByteOrder GuestByteOrder = LittleEndianByteOrder
Function Documentation
template<typename T > T LittleEndianGuest::betog (T value) [inline]
Definition at line 193 of file byteswap.hh.
References betole().
template<typename T > T LittleEndianGuest::gtobe (T value) [inline]
Definition at line 191 of file byteswap.hh.
References letobe().
template<typename T > T LittleEndianGuest::gtoh (T value) [inline]
Definition at line 197 of file byteswap.hh.
References letoh().
template<typename T > T LittleEndianGuest::gtole (T value) [inline]
Definition at line 187 of file byteswap.hh.
template<typename T > T LittleEndianGuest::htog (T value) [inline]
Definition at line 195 of file byteswap.hh.
References htole().
Referenced by LinuxAlphaSystem::initState().
template<typename T > T LittleEndianGuest::letog (T value) [inline]
Definition at line 189 of file byteswap.hh.
Variable Documentation
const ByteOrder LittleEndianGuest::GuestByteOrder = LittleEndianByteOrder
Definition at line 185 of file byteswap.hh.