gem5: python/swig/pyobject.cc File Reference
python/swig/pyobject.cc File Reference
#include <Python.h>
#include <string>
#include "base/inifile.hh"
#include "base/output.hh"
#include "config/the_isa.hh"
#include "mem/ruby/slicc_interface/AbstractController.hh"
#include "mem/mem_object.hh"
#include "python/swig/pyobject.hh"
#include "sim/full_system.hh"
#include "sim/sim_object.hh"
Defines
#define PCC(s) const_cast<char *>(s)
Functions
int connectPorts (SimObject *o1, const std::string &name1, int i1, SimObject *o2, const std::string &name2, int i2)
Connect the described MemObject ports.
IniFile & inifile ()
SimObject * convertSwigSimObjectPtr (PyObject *)
Convert a pointer to the Python object that SWIG wraps around a C++ SimObject pointer back to the actual C++ pointer.
Checkpoint * getCheckpoint (const std::string &cpt_dir)
Variables
PythonSimObjectResolver pythonSimObjectResolver
Single instance of PythonSimObjectResolver as its action is effectively static but SimObjectResolver can use a non-persistent object.
Define Documentation
#define PCC (s) const_cast<char *>(s)
Definition at line 158 of file pyobject.cc.
Function Documentation
int connectPorts (SimObject * o1, const std::string & name1, int i1, SimObject * o2, const std::string & name2, int i2)
Connect the described MemObject ports.
Called from Python via SWIG. The indices i1 & i2 will be -1 for regular ports, >= 0 for vector ports. SimObject1 is the master, and SimObject2 is the slave
Definition at line 76 of file pyobject.cc.
References ArmISA::b, BaseMasterPort::bind(), FullSystem, MemObject::getMasterPort(), MemObject::getSlavePort(), lookupEthPort(), SimObject::name(), panic, AbstractController::setNetQueue(), and EtherInt::setPeer().
SimObject* convertSwigSimObjectPtr (PyObject *)
Convert a pointer to the Python object that SWIG wraps around a C++ SimObject pointer back to the actual C++ pointer.
See main.i.
Checkpoint* getCheckpoint (const std::string & cpt_dir)
Definition at line 196 of file pyobject.cc.
IniFile& inifile () [inline]
Definition at line 142 of file pyobject.cc.
Variable Documentation
PythonSimObjectResolver pythonSimObjectResolver
Single instance of PythonSimObjectResolver as its action is effectively static but SimObjectResolver can use a non-persistent object.
Definition at line 162 of file pyobject.cc.