gem5: mem/ruby/slicc_interface/RubySlicc_Util.hh File Reference
mem/ruby/slicc_interface/RubySlicc_Util.hh File Reference
#include <cassert>
#include "debug/RubySlicc.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/DataBlock.hh"
#include "mem/packet.hh"
Functions
Cycles zero_time ()
NodeID intToID (int nodenum)
int IDToInt (NodeID id)
Address setOffset (Address addr, int offset)
Address makeLineAddress (Address addr)
int addressOffset (Address addr)
int mod (int val, int mod)
int max_tokens ()
bool testAndRead (Address addr, DataBlock &blk, Packet *pkt)
This function accepts an address, a data block and a packet.
bool testAndWrite (Address addr, DataBlock &blk, Packet *pkt)
This function accepts an address, a data block and a packet.
Function Documentation
int addressOffset (Address addr) [inline]
Definition at line 78 of file RubySlicc_Util.hh.
References Address::getOffset().
int IDToInt (NodeID id) [inline]
Definition at line 53 of file RubySlicc_Util.hh.
NodeID intToID (int nodenum) [inline]
Definition at line 46 of file RubySlicc_Util.hh.
Address makeLineAddress (Address addr) [inline]
Definition at line 70 of file RubySlicc_Util.hh.
References Address::makeLineAddress().
int max_tokens () [inline]
Definition at line 89 of file RubySlicc_Util.hh.
int mod (int val, int mod) [inline]
Definition at line 84 of file RubySlicc_Util.hh.
Address setOffset (Address addr, int offset) [inline]
Definition at line 61 of file RubySlicc_Util.hh.
References Address::setOffset().
bool testAndRead (Address addr, DataBlock & blk, Packet * pkt) [inline]
This function accepts an address, a data block and a packet.
If the address range for the data block contains the address which the packet needs to read, then the data from the data block is written to the packet. True is returned if the data block was read, otherwise false is returned.
Definition at line 101 of file RubySlicc_Util.hh.
References Packet::getAddr(), Address::getAddress(), DataBlock::getByte(), Packet::getPtr(), Packet::getSize(), ArmISA::i, and Address::makeLineAddress().
bool testAndWrite (Address addr, DataBlock & blk, Packet * pkt) [inline]
This function accepts an address, a data block and a packet.
If the address range for the data block contains the address which the packet needs to write, then the data from the packet is written to the data block. True is returned if the data block was written, otherwise false is returned.
Definition at line 129 of file RubySlicc_Util.hh.
References Packet::getAddr(), Address::getAddress(), Packet::getConstPtr(), Packet::getSize(), ArmISA::i, Address::makeLineAddress(), and DataBlock::setByte().
Cycles zero_time () [inline]
Definition at line 43 of file RubySlicc_Util.hh.