gem5: mem/ruby/slicc_interface/RubySlicc_ComponentMapping.hh File Reference
mem/ruby/slicc_interface/RubySlicc_ComponentMapping.hh File Reference
#include "mem/protocol/MachineType.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/MachineID.hh"
#include "mem/ruby/common/NetDest.hh"
#include "mem/ruby/structures/DirectoryMemory.hh"
Functions
NodeID map_Address_to_DirectoryNode (const Address &addr)
MachineID map_Address_to_Directory (const Address &addr)
NetDest broadcast (MachineType type)
MachineID mapAddressToRange (const Address &addr, MachineType type, int low_bit, int num_bits, int cluster_id=0)
NodeID machineIDToNodeID (MachineID machID)
MachineType machineIDToMachineType (MachineID machID)
int machineCount (MachineType machType)
MachineID createMachineID (MachineType type, NodeID id)
Function Documentation
NetDest broadcast (MachineType type) [inline]
Definition at line 57 of file RubySlicc_ComponentMapping.hh.
References NetDest::add(), and ArmISA::i.
MachineID createMachineID (MachineType type, NodeID id) [inline]
Definition at line 99 of file RubySlicc_ComponentMapping.hh.
int machineCount (MachineType machType) [inline]
Definition at line 93 of file RubySlicc_ComponentMapping.hh.
MachineType machineIDToMachineType (MachineID machID) [inline]
Definition at line 87 of file RubySlicc_ComponentMapping.hh.
References MachineID::type.
NodeID machineIDToNodeID (MachineID machID) [inline]
Definition at line 81 of file RubySlicc_ComponentMapping.hh.
References MachineID::num.
MachineID map_Address_to_Directory (const Address & addr) [inline]
Definition at line 49 of file RubySlicc_ComponentMapping.hh.
References map_Address_to_DirectoryNode().
NodeID map_Address_to_DirectoryNode (const Address & addr) [inline]
Definition at line 41 of file RubySlicc_ComponentMapping.hh.
References DirectoryMemory::mapAddressToDirectoryVersion().
Referenced by map_Address_to_Directory().
MachineID mapAddressToRange (const Address & addr, MachineType type, int low_bit, int num_bits, int cluster_id = 0) [inline]
Definition at line 68 of file RubySlicc_ComponentMapping.hh.
References Address::bitSelect(), and MachineID::num.