gem5: sim/serialize.cc File Reference
sim/serialize.cc File Reference
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <cerrno>
#include <fstream>
#include <list>
#include <string>
#include <vector>
#include "base/inifile.hh"
#include "base/misc.hh"
#include "base/output.hh"
#include "base/str.hh"
#include "base/trace.hh"
#include "sim/eventq.hh"
#include "sim/serialize.hh"
#include "sim/sim_events.hh"
#include "sim/sim_exit.hh"
#include "sim/sim_object.hh"
#include "sim/stat_control.hh"
Classes
class Globals
Container for serializing global variables (not associated with any serialized object).
Defines
#define INSTANTIATE_PARAM_TEMPLATES(type)
Functions
template<class T >
bool parseParam (const string &s, T &value)
template<class T >
void showParam (ostream &os, const T &value)
template<>
void showParam (ostream &os, const char &value)
template<>
void showParam (ostream &os, const signed char &value)
template<>
void showParam (ostream &os, const unsigned char &value)
template<>
bool parseParam (const string &s, float &value)
template<>
bool parseParam (const string &s, double &value)
template<>
bool parseParam (const string &s, bool &value)
template<>
void showParam (ostream &os, const bool &value)
template<>
bool parseParam (const string &s, string &value)
template<class T >
void paramOut (ostream &os, const string &name, const T &param)
template<class T >
void arrayParamOut (ostream &os, const string &name, const vector< T > &param)
template<class T >
void arrayParamOut (ostream &os, const string &name, const list< T > &param)
template<class T >
void paramIn (Checkpoint *cp, const string &section, const string &name, T &param)
template<class T >
bool optParamIn (Checkpoint *cp, const string &section, const string &name, T &param)
template<class T >
void arrayParamOut (ostream &os, const string &name, const T *param, unsigned size)
template<class T >
void arrayParamIn (Checkpoint *cp, const string &section, const string &name, T *param, unsigned size)
template<class T >
void arrayParamIn (Checkpoint *cp, const string &section, const string &name, vector< T > &param)
template<class T >
void arrayParamIn (Checkpoint *cp, const string &section, const string &name, list< T > &param)
void objParamIn (Checkpoint *cp, const string &section, const string &name, SimObject *&param)
void debug_serialize (const string &cpt_dir)
Variables
Globals globals
The one and only instance of the Globals class.
Define Documentation
#define INSTANTIATE_PARAM_TEMPLATES (type)
Value:
template void                                                           \
paramOut(ostream &os, const string &name, type const &param);           \
template void                                                           \
paramIn(Checkpoint *cp, const string &section,                          \
        const string &name, type & param);                              \
template bool                                                           \
optParamIn(Checkpoint *cp, const string &section,                       \
        const string &name, type & param);                              \
template void                                                           \
arrayParamOut(ostream &os, const string &name,                          \
              type const *param, unsigned size);                        \
template void                                                           \
arrayParamIn(Checkpoint *cp, const string &section,                     \
             const string &name, type *param, unsigned size);           \
template void                                                           \
arrayParamOut(ostream &os, const string &name,                          \
              const vector<type> &param);                               \
template void                                                           \
arrayParamIn(Checkpoint *cp, const string &section,                     \
             const string &name, vector<type> &param);                  \
template void                                                           \
arrayParamOut(ostream &os, const string &name,                          \
              const list<type> &param);                                 \
template void                                                           \
arrayParamIn(Checkpoint *cp, const string &section,                     \
             const string &name, list<type> &param);
Definition at line 374 of file serialize.cc.
Function Documentation
template<class T > void arrayParamIn (Checkpoint * cp, const string & section, const string & name, list< T > & param) [inline]
Definition at line 335 of file serialize.cc.
References fatal, Checkpoint::find(), ArmISA::i, parseParam(), and tokenize().
template<class T > void arrayParamIn (Checkpoint * cp, const string & section, const string & name, vector< T > & param) [inline]
Definition at line 293 of file serialize.cc.
References fatal, Checkpoint::find(), ArmISA::i, parseParam(), and tokenize().
template<class T > void arrayParamIn (Checkpoint * cp, const string & section, const string & name, T * param, unsigned size) [inline]
Definition at line 249 of file serialize.cc.
References fatal, Checkpoint::find(), ArmISA::i, parseParam(), and tokenize().
Referenced by DVFSHandler::unserialize(), X86ISA::PS2Mouse::unserialize(), X86ISA::PS2Keyboard::unserialize(), IGbE::DescCache< T >::unserialize(), CopyEngine::CopyEngineChannel::unserialize(), Pl111::unserialize(), Pl050::unserialize(), HDLcd::unserialize(), and unserialize().
template<class T > void arrayParamOut (ostream & os, const string & name, const T * param, unsigned size) [inline]
Definition at line 234 of file serialize.cc.
References ArmISA::i, and showParam().
template<class T > void arrayParamOut (ostream & os, const string & name, const list< T > & param) [inline]
Definition at line 193 of file serialize.cc.
References showParam().
template<class T > void arrayParamOut (ostream & os, const string & name, const vector< T > & param) [inline]
Definition at line 178 of file serialize.cc.
References ArmISA::i, and showParam().
Referenced by DVFSHandler::serialize(), X86ISA::PS2Mouse::serialize(), X86ISA::PS2Keyboard::serialize(), IGbE::DescCache< T >::serialize(), CopyEngine::CopyEngineChannel::serialize(), Pl111::serialize(), Pl050::serialize(), HDLcd::serialize(), and serialize().
void debug_serialize (const string & cpt_dir)
Definition at line 510 of file serialize.cc.
References Serializable::serializeAll().
void objParamIn (Checkpoint * cp, const string & section, const string & name, SimObject *& param)
Definition at line 365 of file serialize.cc.
References fatal, and Checkpoint::findObj().
template<class T > bool optParamIn (Checkpoint * cp, const string & section, const string & name, T & param) [inline]
Definition at line 221 of file serialize.cc.
References Checkpoint::find(), parseParam(), and warn.
Referenced by optParamIn(), Ticked::unserialize(), and Random::unserialize().
template<class T > void paramIn (Checkpoint * cp, const string & section, const string & name, T & param) [inline]
Definition at line 211 of file serialize.cc.
References fatal, Checkpoint::find(), and parseParam().
template<class T > void paramOut (ostream & os, const string & name, const T & param) [inline]
Definition at line 169 of file serialize.cc.
References showParam().
template<> bool parseParam (const string & s, string & value) [inline]
Definition at line 145 of file serialize.cc.
template<> bool parseParam (const string & s, bool & value) [inline]
Definition at line 128 of file serialize.cc.
References to_bool().
template<> bool parseParam (const string & s, double & value) [inline]
Definition at line 121 of file serialize.cc.
References to_number().
template<> bool parseParam (const string & s, float & value) [inline]
Definition at line 114 of file serialize.cc.
References to_number().
template<class T > bool parseParam (const string & s, T & value) [inline]
Definition at line 67 of file serialize.cc.
References to_number().
Referenced by arrayParamIn(), optParamIn(), and paramIn().
template<> void showParam (ostream & os, const bool & value) [inline]
Definition at line 136 of file serialize.cc.
template<> void showParam (ostream & os, const unsigned char & value) [inline]
Definition at line 106 of file serialize.cc.
template<> void showParam (ostream & os, const signed char & value) [inline]
Definition at line 98 of file serialize.cc.
template<> void showParam (ostream & os, const char & value) [inline]
Definition at line 90 of file serialize.cc.
template<class T > void showParam (ostream & os, const T & value) [inline]
Definition at line 74 of file serialize.cc.
Referenced by arrayParamOut(), and paramOut().
Variable Documentation
Globals globals
The one and only instance of the Globals class.
Definition at line 432 of file serialize.cc.
Referenced by py_interact().