gem5: sim/sim_exit.hh File Reference
sim/sim_exit.hh File Reference
#include <string>
#include "base/types.hh"
#include "sim/core.hh"
Functions
void registerExitCallback (Callback *)
Register a callback to be called when Python exits.
void exitSimLoop (const std::string &message, int exit_code=0, Tick when=curTick(), Tick repeat=0, bool serialize=false)
Schedule an event to exit the simulation loop (returning to Python) at the end of the current cycle (curTick()).
Function Documentation
void exitSimLoop (const std::string & message, int exit_code = 0, Tick when = curTick(), Tick repeat = 0, bool serialize = false)
Schedule an event to exit the simulation loop (returning to Python) at the end of the current cycle (curTick()).
The message and exit_code parameters are saved in the SimLoopExitEvent to indicate why the exit occurred.
Definition at line 83 of file sim_events.cc.
References simQuantum.
Referenced by MemTest::completeRequest(), doSimLoop(), DrainManager::drainCycleDone(), exitFunc(), exitGroupFunc(), BaseCache::incMissCount(), CountedExitEvent::process(), LocalSimLoopExitEvent::process(), FullO3CPU< Impl >::simPalCheck(), SimpleThread::simPalCheck(), takeCheckpoint(), NetworkTest::tick(), RubyTester::wakeup(), RubyDirectedTester::wakeup(), and Pl011::write().
void registerExitCallback (Callback * callback)
Register a callback to be called when Python exits.
Defined in sim/main.cc.
Definition at line 115 of file core.cc.
References CallbackQueue::add(), and exitCallbacks().
Referenced by CommMonitor::CommMonitor(), CowDiskImage::CowDiskImage(), Trace::InstPBTrace::createTraceFile(), InsertionProfiler::InsertionProfiler(), O3ThreadState< Impl >::O3ThreadState(), BaseTags::regStats(), and SimpleThread::SimpleThread().