gem5: sim/simulate.hh File Reference
sim/simulate.hh File Reference
#include "base/types.hh"
#include "sim/sim_events.hh"
Functions
GlobalSimLoopExitEvent * simulate (Tick num_cycles=MaxTick)
Simulate for num_cycles additional cycles.
Variables
GlobalSimLoopExitEvent * simulate_limit_event
Function Documentation
GlobalSimLoopExitEvent* simulate (Tick num_cycles)
Simulate for num_cycles additional cycles.
If num_cycles is -1 (the default), do not limit simulation; some other event must terminate the loop. Exported to Python via SWIG.
Returns:
The SimLoopExitEvent that caused the loop to exit.
Delete the simulation quantum event.
Definition at line 82 of file simulate.cc.
References curTick(), BaseGlobalEvent::deschedule(), doSimLoop(), fatal, Event::globalEvent(), ArmISA::i, inform, inParallelMode, mainEventQueue, MaxTick, numMainEventQueues, EventBase::Progress_Event_Pri, BaseGlobalEvent::reschedule(), simQuantum, thread_loop(), and Barrier::wait().
Referenced by RubySystem::serialize(), and RubySystem::startup().
Variable Documentation
GlobalSimLoopExitEvent* simulate_limit_event
Definition at line 74 of file simulate.cc.