gem5: unittest/stattest.cc File Reference
unittest/stattest.cc File Reference
#include <iomanip>
#include <iostream>
#include <string>
#include "base/cprintf.hh"
#include "base/misc.hh"
#include "base/statistics.hh"
#include "base/types.hh"
#include "sim/core.hh"
#include "sim/stat_control.hh"
Classes
class TestClass
struct StatTest
Functions
double testfunc ()
StatTest & __stattest ()
void stattest_init ()
void stattest_run ()
Variables
const char * m5MainCommands []
Function Documentation
StatTest & __stattest ()
Definition at line 119 of file stattest.cc.
References ArmISA::st.
Referenced by stattest_init(), and stattest_run().
void stattest_init ()
Definition at line 126 of file stattest.cc.
References __stattest(), and StatTest::init().
void stattest_run ()
Definition at line 132 of file stattest.cc.
References __stattest(), and StatTest::run().
double testfunc ()
Definition at line 60 of file stattest.cc.
Referenced by StatTest::init().
Variable Documentation
const char* m5MainCommands[]
Initial value:
 {
    "import m5.stattestmain",
    "m5.stattestmain.main()",
    0
}
Definition at line 43 of file stattest.cc.
Referenced by m5Main().