gem5: base/str.hh File Reference
base/str.hh File Reference
#include <cstring>
#include <limits>
#include <locale>
#include <stdexcept>
#include <string>
#include <vector>
Functions
void eat_lead_white (std::string &s)
void eat_end_white (std::string &s)
void eat_white (std::string &s)
std::string to_lower (const std::string &s)
bool split_first (const std::string &s, std::string &lhs, std::string &rhs, char c)
bool split_last (const std::string &s, std::string &lhs, std::string &rhs, char c)
void tokenize (std::vector< std::string > &vector, const std::string &s, char token, bool ign=true)
template<class T >
bool to_number (const std::string &value, T &retval)
Turn a string representation of a number, either integral or floating point, into an actual number.
bool to_bool (const std::string &value, bool &retval)
Turn a string representation of a boolean into a boolean value.
std::string quote (const std::string &s)
bool startswith (const char *s, const char *prefix)
Return true if 's' starts with the prefix string 'prefix'.
bool startswith (const std::string &s, const char *prefix)
Return true if 's' starts with the prefix string 'prefix'.
bool startswith (const std::string &s, const std::string &prefix)
Return true if 's' starts with the prefix string 'prefix'.
String to number helper functions for signed and unsigned
integeral type, as well as floating-point types.
template<class T >
std::enable_if
< std::is_integral< T >::value
&&std::is_signed< T >::value,
T >::type __to_number (const std::string &value)
Function Documentation
template<class T > std::enable_if< std::is_floating_point< T >::value, T >::type __to_number (const std::string & value) [inline]
Definition at line 131 of file str.hh.
void eat_end_white (std::string & s) [inline]
Definition at line 53 of file str.hh.
Referenced by eat_white().
void eat_lead_white (std::string & s) [inline]
Definition at line 43 of file str.hh.
Referenced by eat_white().
void eat_white (std::string & s) [inline]
Definition at line 61 of file str.hh.
References eat_end_white(), and eat_lead_white().
Referenced by IniFile::Section::add().
std::string quote (const std::string & s) [inline]
Definition at line 184 of file str.hh.
bool split_first (const std::string & s, std::string & lhs, std::string & rhs, char c)
bool split_last (const std::string & s, std::string & lhs, std::string & rhs, char c)
bool startswith (const std::string & s, const std::string & prefix) [inline]
Return true if 's' starts with the prefix string 'prefix'.
Definition at line 225 of file str.hh.
bool startswith (const std::string & s, const char * prefix) [inline]
Return true if 's' starts with the prefix string 'prefix'.
Definition at line 215 of file str.hh.
bool startswith (const char * s, const char * prefix) [inline]
Return true if 's' starts with the prefix string 'prefix'.
Definition at line 205 of file str.hh.
Referenced by System::getMasterId(), openFunc(), and procInfo().
bool to_bool (const std::string & value, bool & retval) [inline]
Turn a string representation of a boolean into a boolean value.
Definition at line 167 of file str.hh.
References ArmISA::s, and to_lower().
Referenced by parseParam().
std::string to_lower (const std::string & s) [inline]
Definition at line 68 of file str.hh.
References ArmISA::c, and ArmISA::len.
Referenced by to_bool().
template<class T > bool to_number (const std::string & value, T & retval) [inline]
Turn a string representation of a number, either integral or floating point, into an actual number.
Parameters:
value The string representing the number
retval The resulting value
Returns:
True if the parsing was successful
Definition at line 151 of file str.hh.
Referenced by main(), and parseParam().
void tokenize (std::vector< std::string > & vector, const std::string & s, char token, bool ign = true)