gem5: Net::EthHdr Struct Reference
Net::EthHdr Struct Reference
#include <inet.hh>
Public Member Functions
bool isVlan () const
uint16_t type () const
uint16_t vlanId () const
const EthAddr & src () const
const EthAddr & dst () const
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 127 of file inet.hh.
Member Function Documentation
uint8_t* Net::EthHdr::bytes () [inline]
Definition at line 157 of file inet.hh.
const uint8_t* Net::EthHdr::bytes () const [inline]
Definition at line 155 of file inet.hh.
Referenced by payload().
const EthAddr& Net::EthHdr::dst () const [inline]
Definition at line 146 of file inet.hh.
Referenced by Sinic::Device::rxFilter().
bool Net::EthHdr::isVlan () const [inline]
Definition at line 129 of file inet.hh.
Referenced by Net::Ip6Ptr::set(), Net::IpPtr::set(), size(), type(), and vlanId().
uint8_t* Net::EthHdr::payload () [inline]
Definition at line 158 of file inet.hh.
References bytes(), and size().
const uint8_t* Net::EthHdr::payload () const [inline]
Definition at line 156 of file inet.hh.
References bytes(), and size().
int Net::EthHdr::size () const [inline]
Definition at line 148 of file inet.hh.
References isVlan().
Referenced by payload().
const EthAddr& Net::EthHdr::src () const [inline]
Definition at line 145 of file inet.hh.
uint16_t Net::EthHdr::type () const [inline]
Definition at line 130 of file inet.hh.
References isVlan().
Referenced by Sinic::Device::rxFilter(), Net::Ip6Ptr::set(), and Net::IpPtr::set().
uint16_t Net::EthHdr::vlanId () const [inline]
Definition at line 138 of file inet.hh.
References isVlan().
The documentation for this struct was generated from the following file:
base/inet.hh