gem5: Trace::ArmNativeTrace::ThreadState Struct Reference
Trace::ArmNativeTrace::ThreadState Struct Reference
#include <nativetrace.hh>
Public Member Functions
void update (NativeTrace *parent)
void update (ThreadContext *tc)
ThreadState ()
Public Attributes
bool changed [STATE_NUMVALS]
uint64_t state [2][STATE_NUMVALS]
uint64_t * newState
uint64_t * oldState
int current
Detailed Description
Definition at line 75 of file nativetrace.hh.
Constructor & Destructor Documentation
Trace::ArmNativeTrace::ThreadState::ThreadState () [inline]
Definition at line 84 of file nativetrace.hh.
References changed, current, ArmISA::i, newState, oldState, state, and Trace::ArmNativeTrace::STATE_NUMVALS.
Member Function Documentation
void Trace::ArmNativeTrace::ThreadState::update (ThreadContext * tc)
Definition at line 101 of file nativetrace.cc.
References ArmISA::CCREG_C, ArmISA::CCREG_FP, ArmISA::CCREG_GE, ArmISA::CCREG_NZ, ArmISA::CCREG_V, changed, ArmISA::cpsr, current, ArmISA::i, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_FPSCR, newState, ArmISA::NumFloatV7ArchRegs, oldState, ThreadContext::pcState(), ThreadContext::readCCReg(), ThreadContext::readFloatRegBits(), ThreadContext::readIntReg(), ThreadContext::readMiscReg(), ThreadContext::readMiscRegNoEffect(), state, Trace::ArmNativeTrace::STATE_CPSR, Trace::ArmNativeTrace::STATE_F0, Trace::ArmNativeTrace::STATE_FPSCR, and Trace::ArmNativeTrace::STATE_PC.
void Trace::ArmNativeTrace::ThreadState::update (NativeTrace * parent)
Definition at line 66 of file nativetrace.cc.
References changed, current, BigEndianGuest::gtoh(), ArmISA::i, newState, oldState, Trace::NativeTrace::read(), state, and Trace::ArmNativeTrace::STATE_NUMVALS.
Referenced by Trace::ArmNativeTrace::check().
Member Data Documentation
bool Trace::ArmNativeTrace::ThreadState::changed[STATE_NUMVALS]
Definition at line 76 of file nativetrace.hh.
Referenced by Trace::ArmNativeTrace::check(), ThreadState(), and update().
int Trace::ArmNativeTrace::ThreadState::current
Definition at line 80 of file nativetrace.hh.
Referenced by ThreadState(), and update().
uint64_t* Trace::ArmNativeTrace::ThreadState::newState
Definition at line 78 of file nativetrace.hh.
Referenced by Trace::ArmNativeTrace::check(), ThreadState(), and update().
uint64_t* Trace::ArmNativeTrace::ThreadState::oldState
Definition at line 79 of file nativetrace.hh.
Referenced by Trace::ArmNativeTrace::check(), ThreadState(), and update().
uint64_t Trace::ArmNativeTrace::ThreadState::state[2][STATE_NUMVALS]
Definition at line 77 of file nativetrace.hh.
Referenced by ThreadState(), and update().
The documentation for this struct was generated from the following files:
arch/arm/nativetrace.hh
arch/arm/nativetrace.cc