gem5: Net::Ip6Hdr Struct Reference
Net::Ip6Hdr Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t version () const
uint32_t flow () const
uint16_t plen () const
uint16_t hlen () const
uint8_t nxt () const
uint8_t hlim () const
const uint8_t * src () const
const uint8_t * dst () const
int extensionLength () const
const Ip6Opt * getExt (uint8_t ext) const
const Ip6Opt * fragmentExt () const
const Ip6Opt * rtTypeExt () const
const Ip6Opt * dstOptExt () const
uint8_t proto () const
void plen (uint16_t _plen)
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 364 of file inet.hh.
Member Function Documentation
uint8_t* Net::Ip6Hdr::bytes () [inline]
Definition at line 389 of file inet.hh.
const uint8_t* Net::Ip6Hdr::bytes () const [inline]
Definition at line 386 of file inet.hh.
Referenced by extensionLength(), getExt(), payload(), and proto().
const uint8_t* Net::Ip6Hdr::dst () const [inline]
Definition at line 374 of file inet.hh.
const Ip6Opt* Net::Ip6Hdr::dstOptExt () const [inline]
Definition at line 380 of file inet.hh.
References getExt().
int Net::Ip6Hdr::extensionLength () const
Definition at line 291 of file inet.cc.
References bytes(), ArmISA::ext, IP6_EXTENSION, Net::Ip6Opt::len(), ArmISA::len, Net::Ip6Opt::nxt(), nxt(), and plen().
Referenced by payload(), and size().
uint32_t Net::Ip6Hdr::flow () const [inline]
Definition at line 367 of file inet.hh.
const Ip6Opt* Net::Ip6Hdr::fragmentExt () const [inline]
Definition at line 378 of file inet.hh.
References getExt().
const Ip6Opt * Net::Ip6Hdr::getExt (uint8_t ext) const
Definition at line 314 of file inet.cc.
References bytes(), IP6_EXTENSION, Net::Ip6Opt::len(), Net::Ip6Opt::nxt(), nxt(), and plen().
Referenced by dstOptExt(), fragmentExt(), and rtTypeExt().
uint16_t Net::Ip6Hdr::hlen () const [inline]
Definition at line 369 of file inet.hh.
uint8_t Net::Ip6Hdr::hlim () const [inline]
Definition at line 371 of file inet.hh.
uint8_t Net::Ip6Hdr::nxt () const [inline]
Definition at line 370 of file inet.hh.
Referenced by extensionLength(), getExt(), and proto().
uint8_t* Net::Ip6Hdr::payload () [inline]
Definition at line 390 of file inet.hh.
References bytes(), and extensionLength().
const uint8_t* Net::Ip6Hdr::payload () const [inline]
Definition at line 387 of file inet.hh.
References bytes(), and extensionLength().
void Net::Ip6Hdr::plen (uint16_t _plen) [inline]
Definition at line 383 of file inet.hh.
uint16_t Net::Ip6Hdr::plen () const [inline]
Definition at line 368 of file inet.hh.
Referenced by extensionLength(), getExt(), and proto().
uint8_t Net::Ip6Hdr::proto () const
Definition at line 340 of file inet.cc.
References bytes(), ArmISA::ext, IP6_EXTENSION, Net::Ip6Opt::len(), Net::Ip6Opt::nxt(), nxt(), and plen().
const Ip6Opt* Net::Ip6Hdr::rtTypeExt () const [inline]
Definition at line 379 of file inet.hh.
References getExt().
int Net::Ip6Hdr::size () const [inline]
Definition at line 385 of file inet.hh.
References extensionLength().
const uint8_t* Net::Ip6Hdr::src () const [inline]
Definition at line 373 of file inet.hh.
uint8_t Net::Ip6Hdr::version () const [inline]
Definition at line 366 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc