gem5: MC146818::RTCTickEvent Struct Reference
MC146818::RTCTickEvent Struct Reference
Event for RTC periodic interrupt.
Public Member Functions
RTCTickEvent (MC146818 *_parent)
void process ()
Event process to occur at interrupt.
const char * description () const
Event description.
Public Attributes
MC146818 * parent
Tick offset
Detailed Description
Event for RTC periodic interrupt.
Definition at line 69 of file mc146818.hh.
Constructor & Destructor Documentation
MC146818::RTCTickEvent::RTCTickEvent (MC146818 * _parent) [inline]
Definition at line 74 of file mc146818.hh.
Member Function Documentation
const char * MC146818::RTCTickEvent::description () const [virtual]
Event description.
Reimplemented from Event.
Definition at line 347 of file mc146818.cc.
void MC146818::RTCTickEvent::process () [virtual]
Event process to occur at interrupt.
Implements Event.
Definition at line 339 of file mc146818.cc.
References curTick(), DPRINTF, parent, SimClock::Int::s, EventManager::schedule(), and MC146818::tickClock().
Member Data Documentation
Tick MC146818::RTCTickEvent::offset
Definition at line 72 of file mc146818.hh.
Referenced by MC146818::startup().
MC146818* MC146818::RTCTickEvent::parent
Definition at line 71 of file mc146818.hh.
Referenced by process().
The documentation for this struct was generated from the following files:
dev/mc146818.hh
dev/mc146818.cc