gem5: ArmISA::ISA Class Reference
ArmISA::ISA Class Reference
Some registers aliase with others, and therefore need to be translated.
#include <isa.hh>
Classes
struct MiscRegInitializerEntry
struct MiscRegLUTEntry
Register translation entry used in lookUpMiscReg.
Public Types
typedef ArmISAParams Params
Public Member Functions
void clear ()
void clear64 (const ArmISAParams *p)
MiscReg readMiscRegNoEffect (int misc_reg) const
MiscReg readMiscReg (int misc_reg, ThreadContext *tc)
void setMiscRegNoEffect (int misc_reg, const MiscReg &val)
void setMiscReg (int misc_reg, const MiscReg &val, ThreadContext *tc)
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
void startup (ThreadContext *tc)
const Params * params () const
ISA (Params *p)
Protected Member Functions
void updateRegMap (CPSR cpsr)
BaseISADevice & getGenericTimer (ThreadContext *tc)
Protected Attributes
ArmSystem * system
DummyISADevice dummyDevice
Dummy device for to handle non-existing ISA devices.
BaseISADevice * pmu
std::unique_ptr< BaseISADevice > timer
bool haveSecurity
bool haveLPAE
bool haveVirtualization
bool haveLargeAsid64
uint8_t physAddrRange64
std::vector< struct
MiscRegLUTEntry > lookUpMiscReg
Translation table accessible via the value of the register.
MiscReg miscRegs [NumMiscRegs]
const IntRegIndex * intRegMap
Static Protected Attributes
static struct
MiscRegInitializerEntry MiscRegSwitch [miscRegTranslateMax]
Register table noting all translations.
Private Member Functions
void assert32 (ThreadContext *tc)
void assert64 (ThreadContext *tc)
void tlbiVA (ThreadContext *tc, MiscReg newVal, uint16_t asid, bool secure_lookup, uint8_t target_el)
void tlbiALL (ThreadContext *tc, bool secure_lookup, uint8_t target_el)
void tlbiALLN (ThreadContext *tc, bool hyp, uint8_t target_el)
void tlbiMVA (ThreadContext *tc, MiscReg newVal, bool secure_lookup, bool hyp, uint8_t target_el)
Detailed Description
Some registers aliase with others, and therefore need to be translated.
For each entry: The first value is the misc register that is to be looked up the second value is the lower part of the translation the third the upper part
Definition at line 65 of file isa.cc.
Member Typedef Documentation
typedef ArmISAParams ArmISA::ISA::Params
Reimplemented from SimObject.
Definition at line 435 of file isa.hh.
Constructor & Destructor Documentation
ArmISA::ISA::ISA (Params * p)
Definition at line 127 of file isa.cc.
Member Function Documentation
void ArmISA::ISA::assert32 (ThreadContext * tc) [inline, private]
Definition at line 214 of file isa.hh.
References ArmISA::cpsr, ArmISA::M5_VAR_USED, ArmISA::MISCREG_CPSR, and readMiscReg().
void ArmISA::ISA::assert64 (ThreadContext * tc) [inline, private]
Definition at line 219 of file isa.hh.
References ArmISA::cpsr, ArmISA::M5_VAR_USED, ArmISA::MISCREG_CPSR, and readMiscReg().
void ArmISA::ISA::clear ()
void ArmISA::ISA::clear64 (const ArmISAParams * p)
int ArmISA::ISA::flattenCCIndex (int reg) const [inline]
Definition at line 284 of file isa.hh.
int ArmISA::ISA::flattenFloatIndex (int reg) const [inline]
Definition at line 277 of file isa.hh.
int ArmISA::ISA::flattenIntIndex (int reg) const [inline]
Definition at line 244 of file isa.hh.
References ArmISA::cpsr, ArmISA::el, ArmISA::EL0, ArmISA::EL1, ArmISA::EL3, ArmISA::flattenIntRegModeIndex(), ArmISA::INTREG_SP0, ArmISA::INTREG_SP1, ArmISA::INTREG_SP3, ArmISA::INTREG_SPX, intRegMap, ArmISA::MISCREG_CPSR, miscRegs, ArmISA::NUM_ARCH_INTREGS, ArmISA::NUM_INTREGS, ArmISA::opModeToEL(), and panic.
int ArmISA::ISA::flattenMiscIndex (int reg) const [inline]
Definition at line 291 of file isa.hh.
References ArmISA::cpsr, haveSecurity, ArmISA::inSecureState(), ArmISA::MISCREG_BANKED, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_MAIR0, ArmISA::MISCREG_MAIR1, ArmISA::MISCREG_MUTEX, ArmISA::MISCREG_NMRR, ArmISA::MISCREG_NMRR_MAIR1, ArmISA::MISCREG_NMRR_MAIR1_NS, ArmISA::MISCREG_NMRR_MAIR1_S, ArmISA::MISCREG_PMCCFILTR, ArmISA::MISCREG_PMSELR, ArmISA::MISCREG_PMXEVTYPER, ArmISA::MISCREG_PMXEVTYPER_PMCCFILTR, ArmISA::MISCREG_PRRR, ArmISA::MISCREG_PRRR_MAIR0, ArmISA::MISCREG_PRRR_MAIR0_NS, ArmISA::MISCREG_PRRR_MAIR0_S, ArmISA::MISCREG_SCR, ArmISA::MISCREG_SPSR, ArmISA::MISCREG_SPSR_ABT, ArmISA::MISCREG_SPSR_EL1, ArmISA::MISCREG_SPSR_EL2, ArmISA::MISCREG_SPSR_EL3, ArmISA::MISCREG_SPSR_FIQ, ArmISA::MISCREG_SPSR_HYP, ArmISA::MISCREG_SPSR_IRQ, ArmISA::MISCREG_SPSR_MON, ArmISA::MISCREG_SPSR_SVC, ArmISA::MISCREG_SPSR_UND, ArmISA::MISCREG_TTBCR, ArmISA::miscRegInfo, miscRegs, ArmISA::MODE_ABORT, ArmISA::MODE_EL0T, ArmISA::MODE_EL1H, ArmISA::MODE_EL1T, ArmISA::MODE_EL2H, ArmISA::MODE_EL2T, ArmISA::MODE_EL3H, ArmISA::MODE_EL3T, ArmISA::MODE_FIQ, ArmISA::MODE_HYP, ArmISA::MODE_IRQ, ArmISA::MODE_MON, ArmISA::MODE_SVC, ArmISA::MODE_UNDEFINED, ArmISA::MODE_USER, panic, readMiscRegNoEffect(), and warn.
BaseISADevice& ArmISA::ISA::getGenericTimer (ThreadContext * tc) [protected]
const Params* ArmISA::ISA::params () const
Reimplemented from SimObject.
MiscReg ArmISA::ISA::readMiscReg (int misc_reg, ThreadContext * tc)
Referenced by assert32(), and assert64().
MiscReg ArmISA::ISA::readMiscRegNoEffect (int misc_reg) const
Referenced by flattenMiscIndex(), and ArmISA::PMU::isFiltered().
void ArmISA::ISA::serialize (std::ostream & os) [inline, virtual]
Reimplemented from Serializable.
Definition at line 405 of file isa.hh.
References DPRINTF, haveLargeAsid64, haveLPAE, haveSecurity, haveVirtualization, miscRegs, ArmISA::NumMiscRegs, physAddrRange64, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
void ArmISA::ISA::setMiscReg (int misc_reg, const MiscReg & val, ThreadContext * tc)
void ArmISA::ISA::setMiscRegNoEffect (int misc_reg, const MiscReg & val)
void ArmISA::ISA::startup (ThreadContext * tc) [inline]
Definition at line 430 of file isa.hh.
void ArmISA::ISA::tlbiALL (ThreadContext * tc, bool secure_lookup, uint8_t target_el) [private]
void ArmISA::ISA::tlbiALLN (ThreadContext * tc, bool hyp, uint8_t target_el) [private]
void ArmISA::ISA::tlbiMVA (ThreadContext * tc, MiscReg newVal, bool secure_lookup, bool hyp, uint8_t target_el) [private]
void ArmISA::ISA::tlbiVA (ThreadContext * tc, MiscReg newVal, uint16_t asid, bool secure_lookup, uint8_t target_el) [private]
void ArmISA::ISA::unserialize (Checkpoint * cp, const std::string & section) [inline, virtual]
Reimplemented from Serializable.
Definition at line 416 of file isa.hh.
References DPRINTF, haveLargeAsid64, haveLPAE, haveSecurity, haveVirtualization, ArmISA::MISCREG_CPSR, miscRegs, ArmISA::NumMiscRegs, physAddrRange64, UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, and updateRegMap().
void ArmISA::ISA::updateRegMap (CPSR cpsr) [inline, protected]
Definition at line 173 of file isa.hh.
References ArmISA::IntReg64Map, ArmISA::IntRegAbtMap, ArmISA::IntRegFiqMap, ArmISA::IntRegHypMap, ArmISA::IntRegIrqMap, intRegMap, ArmISA::IntRegMonMap, ArmISA::IntRegSvcMap, ArmISA::IntRegUndMap, ArmISA::IntRegUsrMap, ArmISA::MODE_ABORT, ArmISA::MODE_FIQ, ArmISA::MODE_HYP, ArmISA::MODE_IRQ, ArmISA::MODE_MON, ArmISA::MODE_SVC, ArmISA::MODE_SYSTEM, ArmISA::MODE_UNDEFINED, ArmISA::MODE_USER, and panic.
Referenced by unserialize().
Member Data Documentation
DummyISADevice ArmISA::ISA::dummyDevice [protected]
Dummy device for to handle non-existing ISA devices.
Definition at line 136 of file isa.hh.
bool ArmISA::ISA::haveLargeAsid64 [protected]
Definition at line 148 of file isa.hh.
Referenced by serialize(), and unserialize().
bool ArmISA::ISA::haveLPAE [protected]
Definition at line 146 of file isa.hh.
Referenced by serialize(), and unserialize().
bool ArmISA::ISA::haveSecurity [protected]
Definition at line 145 of file isa.hh.
Referenced by flattenMiscIndex(), serialize(), and unserialize().
bool ArmISA::ISA::haveVirtualization [protected]
Definition at line 147 of file isa.hh.
Referenced by serialize(), and unserialize().
const IntRegIndex* ArmISA::ISA::intRegMap [protected]
Definition at line 170 of file isa.hh.
Referenced by flattenIntIndex(), and updateRegMap().
std::vector<struct MiscRegLUTEntry> ArmISA::ISA::lookUpMiscReg [protected]
Translation table accessible via the value of the register.
Definition at line 167 of file isa.hh.
MiscReg ArmISA::ISA::miscRegs[NumMiscRegs] [protected]
Definition at line 169 of file isa.hh.
Referenced by flattenIntIndex(), flattenMiscIndex(), serialize(), and unserialize().
struct MiscRegInitializerEntry ArmISA::ISA::MiscRegSwitch[miscRegTranslateMax] [static, read, protected]
Register table noting all translations.
Definition at line 163 of file isa.hh.
uint8_t ArmISA::ISA::physAddrRange64 [protected]
Definition at line 149 of file isa.hh.
Referenced by serialize(), and unserialize().
BaseISADevice* ArmISA::ISA::pmu [protected]
Definition at line 139 of file isa.hh.
ArmSystem* ArmISA::ISA::system [protected]
Definition at line 133 of file isa.hh.
std::unique_ptr<BaseISADevice> ArmISA::ISA::timer [protected]
Definition at line 142 of file isa.hh.
The documentation for this class was generated from the following files:
arch/arm/isa.cc
arch/arm/isa.hh