gem5: DVFSHandler::UpdateEvent Struct Reference
DVFSHandler::UpdateEvent Struct Reference
Update performance level event, encapsulates all the required information for a future call to change a domain's performance level.
Public Member Functions
UpdateEvent ()
void updatePerfLevel ()
Updates the performance level by modifying the clock and the voltage of the associated clocked objects.
void process ()
Public Attributes
DomainID domainIDToSet
ID of the domain that will be changed by the in-flight event.
PerfLevel perfLevelToSet
Target performance level of the in-flight event.
Static Public Attributes
static DVFSHandler * dvfsHandler
Static pointer to the single DVFS hander for all the update events.
Detailed Description
Update performance level event, encapsulates all the required information for a future call to change a domain's performance level.
Definition at line 250 of file dvfs_handler.hh.
Constructor & Destructor Documentation
DVFSHandler::UpdateEvent::UpdateEvent () [inline]
Definition at line 251 of file dvfs_handler.hh.
Member Function Documentation
void DVFSHandler::UpdateEvent::process () [inline, virtual]
Implements Event.
Definition at line 277 of file dvfs_handler.hh.
References updatePerfLevel().
void DVFSHandler::UpdateEvent::updatePerfLevel ()
Updates the performance level by modifying the clock and the voltage of the associated clocked objects.
Gets information from domainIDToSet and perfLevelToSet for easier calling through an event.
Definition at line 158 of file dvfs_handler.cc.
References ArmISA::d, domainIDToSet, Event::dump(), dvfsHandler, DVFSHandler::findDomain(), perfLevelToSet, and Stats::reset().
Referenced by process().
Member Data Documentation
DomainID DVFSHandler::UpdateEvent::domainIDToSet
ID of the domain that will be changed by the in-flight event.
Definition at line 262 of file dvfs_handler.hh.
Referenced by updatePerfLevel().
DVFSHandler * DVFSHandler::UpdateEvent::dvfsHandler [static]
Static pointer to the single DVFS hander for all the update events.
Definition at line 257 of file dvfs_handler.hh.
Referenced by DVFSHandler::DVFSHandler(), DVFSHandler::unserialize(), and updatePerfLevel().
PerfLevel DVFSHandler::UpdateEvent::perfLevelToSet
Target performance level of the in-flight event.
Definition at line 267 of file dvfs_handler.hh.
Referenced by DVFSHandler::perfLevel(), and updatePerfLevel().
The documentation for this struct was generated from the following files:
sim/dvfs_handler.hh
sim/dvfs_handler.cc