gem5: sim/syscall_emul.hh File Reference
sim/syscall_emul.hh File Reference
This file defines objects used to emulate syscalls from the target application on the host machine.
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <fcntl.h>
#include <cerrno>
#include <string>
#include "base/chunk_generator.hh"
#include "base/intmath.hh"
#include "base/misc.hh"
#include "base/trace.hh"
#include "base/types.hh"
#include "config/the_isa.hh"
#include "cpu/base.hh"
#include "cpu/thread_context.hh"
#include "debug/SyscallVerbose.hh"
#include "mem/page_table.hh"
#include "sim/byteswap.hh"
#include "sim/emul_driver.hh"
#include "sim/process.hh"
#include "sim/syscall_emul_buf.hh"
#include "sim/syscallreturn.hh"
#include "sim/system.hh"
Classes
class SyscallDesc
System call descriptor.
Defines
#define NO_STAT64
Typedefs
typedef struct stat hst_stat
typedef struct stat64 hst_stat64
Functions
SyscallReturn unimplementedFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Handler for unimplemented syscalls that we haven't thought about.
SyscallReturn ignoreFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.
SyscallReturn exitFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target exit() handler: terminate current context.
SyscallReturn exitGroupFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target exit_group() handler: terminate simulation. (exit all threads).
SyscallReturn getpagesizeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getpagesize() handler.
SyscallReturn brkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target brk() handler: set brk address.
SyscallReturn closeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target close() handler.
SyscallReturn readFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target read() handler.
SyscallReturn writeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target write() handler.
SyscallReturn lseekFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target lseek() handler.
SyscallReturn _llseekFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target _llseek() handler.
SyscallReturn munmapFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target munmap() handler.
SyscallReturn gethostnameFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target gethostname() handler.
SyscallReturn getcwdFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getcwd() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc, int index=0)
Target readlink() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target open() handler.
SyscallReturn unlinkHelper (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc, int index)
Target unlink() handler.
SyscallReturn unlinkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
SyscallReturn mkdirFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target mkdir() handler.
SyscallReturn renameFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target rename() handler.
SyscallReturn truncateFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target truncate() handler.
SyscallReturn ftruncateFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target ftruncate() handler.
SyscallReturn truncate64Func (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target truncate64() handler.
SyscallReturn ftruncate64Func (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target ftruncate64() handler.
SyscallReturn umaskFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target umask() handler.
SyscallReturn chownFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target chown() handler.
SyscallReturn fchownFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target fchown() handler.
SyscallReturn dupFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target dup() handler.
SyscallReturn fcntlFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target fnctl() handler.
SyscallReturn fcntl64Func (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target fcntl64() handler.
SyscallReturn setuidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target setuid() handler.
SyscallReturn getpidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getpid() handler.
SyscallReturn getuidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getuid() handler.
SyscallReturn getgidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getgid() handler.
SyscallReturn getppidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getppid() handler.
SyscallReturn geteuidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target geteuid() handler.
SyscallReturn getegidFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getegid() handler.
SyscallReturn cloneFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target clone() handler.
SyscallReturn accessFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target access() handler.
SyscallReturn accessFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc, int index)
template<class OS >
SyscallReturn futexFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Futex system call Implemented by Daniel Sanchez Used by printf's in multi-threaded apps.
SyscallReturn pipePseudoFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
SyscallReturn getpidPseudoFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getpidPseudo() handler.
SyscallReturn getuidPseudoFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getuidPseudo() handler.
SyscallReturn getgidPseudoFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getgidPseudo() handler.
template<class T1 , class T2 >
void getElapsedTimeMicro (T1 &sec, T2 &usec)
Helper function to convert current elapsed time to seconds and microseconds.
template<class T1 , class T2 >
void getElapsedTimeNano (T1 &sec, T2 &nsec)
Helper function to convert current elapsed time to seconds and nanoseconds.
template<typename target_stat , typename host_stat >
static void convertStatBuf (target_stat &tgt, host_stat *host, bool fakeTTY=false)
template<typename target_stat , typename host_stat64 >
static void convertStat64Buf (target_stat &tgt, host_stat64 *host, bool fakeTTY=false)
template<class OS >
static void copyOutStatBuf (SETranslatingPortProxy &mem, Addr addr, hst_stat *host, bool fakeTTY=false)
template<class OS >
static void copyOutStat64Buf (SETranslatingPortProxy &mem, Addr addr, hst_stat64 *host, bool fakeTTY=false)
template<class OS >
SyscallReturn ioctlFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target ioctl() handler.
template<class OS >
static SyscallReturn openFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc, int index)
template<class OS >
SyscallReturn openFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target open() handler.
template<class OS >
SyscallReturn openatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target openat() handler.
template<class OS >
SyscallReturn unlinkatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target unlinkat() handler.
template<class OS >
SyscallReturn faccessatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target facessat() handler.
template<class OS >
SyscallReturn readlinkatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target readlinkat() handler.
template<class OS >
SyscallReturn renameatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target renameat() handler.
template<class OS >
SyscallReturn sysinfoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target sysinfo() handler.
template<class OS >
SyscallReturn chmodFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target chmod() handler.
template<class OS >
SyscallReturn fchmodFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target fchmod() handler.
template<class OS >
SyscallReturn mremapFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target mremap() handler.
template<class OS >
SyscallReturn statFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target stat() handler.
template<class OS >
SyscallReturn stat64Func (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target stat64() handler.
template<class OS >
SyscallReturn fstatat64Func (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target fstatat64() handler.
template<class OS >
SyscallReturn fstat64Func (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target fstat64() handler.
template<class OS >
SyscallReturn lstatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target lstat() handler.
template<class OS >
SyscallReturn lstat64Func (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target lstat64() handler.
template<class OS >
SyscallReturn fstatFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target fstat() handler.
template<class OS >
SyscallReturn statfsFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target statfs() handler.
template<class OS >
SyscallReturn fstatfsFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target fstatfs() handler.
template<class OS >
SyscallReturn writevFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target writev() handler.
template<class OS >
SyscallReturn mmapFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target mmap() handler.
template<class OS >
SyscallReturn getrlimitFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getrlimit() handler.
template<class OS >
SyscallReturn clock_gettimeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target clock_gettime() function.
template<class OS >
SyscallReturn gettimeofdayFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target gettimeofday() handler.
template<class OS >
SyscallReturn utimesFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target utimes() handler.
template<class OS >
SyscallReturn getrusageFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getrusage() function.
template<class OS >
SyscallReturn timesFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target times() function.
template<class OS >
SyscallReturn timeFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target time() function.
Variables
const int one_million = 1000000
A readable name for 1,000,000, for converting microseconds to seconds.
const int one_billion = 1000000000
A readable name for 1,000,000,000, for converting nanoseconds to seconds.
const unsigned seconds_since_epoch = 1000000000
Approximate seconds since the epoch (1/1/1970).
Detailed Description
This file defines objects used to emulate syscalls from the target application on the host machine.
Definition in file syscall_emul.hh.
Define Documentation
#define NO_STAT64
Value:
(defined(__APPLE__) || defined(__OpenBSD__) || \
  defined(__FreeBSD__) || defined(__CYGWIN__) || \
  defined(__NetBSD__))
Definition at line 48 of file syscall_emul.hh.
Typedef Documentation
typedef struct stat hst_stat
Definition at line 445 of file syscall_emul.hh.
typedef struct stat64 hst_stat64
Definition at line 446 of file syscall_emul.hh.
Function Documentation
SyscallReturn _llseekFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target _llseek() handler.
Definition at line 277 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, ArmISA::offset, and Process::sim_fd().
SyscallReturn accessFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc, int index)
Definition at line 881 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), ArmISA::mode, and SETranslatingPortProxy::tryReadString().
Referenced by accessFunc(), and faccessatFunc().
SyscallReturn accessFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target access() handler.
Definition at line 898 of file syscall_emul.cc.
References accessFunc().
SyscallReturn brkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target brk() handler: set brk address.
Definition at line 165 of file syscall_emul.cc.
References Process::allocateMem(), Process::brk_point, DPRINTF, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, SETranslatingPortProxy::memsetBlob(), AlphaISA::PageBytes, Process::pTable, roundDown(), roundUp(), and PageTableBase::translate().
template<class OS > SyscallReturn chmodFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target chmod() handler.
Definition at line 776 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, ArmISA::mode, and SETranslatingPortProxy::tryReadString().
SyscallReturn chownFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target chown() handler.
Definition at line 550 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn clock_gettimeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc) [inline]
Target clock_gettime() function.
Definition at line 1342 of file syscall_emul.hh.
References getElapsedTimeNano(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, and seconds_since_epoch.
SyscallReturn cloneFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target clone() handler.
Definition at line 799 of file syscall_emul.cc.
References ThreadContext::activate(), SparcISA::ASI_PRIMARY, ThreadContext::clearArchRegs(), AlphaISA::copyMiscRegs(), AlphaISA::copyRegs(), DPRINTF, fatal, Process::findFreeContext(), LiveProcess::getSyscallArg(), MipsISA::index, SparcISA::MISCREG_ASI, SparcISA::MISCREG_CWP, SparcISA::MISCREG_TL, ThreadContext::nextInstAddr(), AlphaISA::NumIntArchRegs, SparcISA::NWindows, ThreadContext::pcState(), ThreadContext::readIntReg(), AlphaISA::ReturnValueReg, ThreadContext::setIntReg(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), AlphaISA::StackPointerReg, AlphaISA::SyscallPseudoReturnReg, AlphaISA::SyscallSuccessReg, and warn.
SyscallReturn closeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target close() handler.
Definition at line 210 of file syscall_emul.cc.
References Process::free_fd(), LiveProcess::getSyscallArg(), MipsISA::index, Process::sim_fd(), and ArmISA::status.
template<typename target_stat , typename host_stat64 > static void convertStat64Buf (target_stat & tgt, host_stat64 * host, bool fakeTTY = false) [inline, static]
Definition at line 504 of file syscall_emul.hh.
References BigEndianGuest::htog().
template<typename target_stat , typename host_stat > static void convertStatBuf (target_stat & tgt, host_stat * host, bool fakeTTY = false) [inline, static]
Definition at line 455 of file syscall_emul.hh.
References BigEndianGuest::htog().
template<class OS > static void copyOutStat64Buf (SETranslatingPortProxy & mem, Addr addr, hst_stat64 * host, bool fakeTTY = false) [inline, static]
Definition at line 537 of file syscall_emul.hh.
template<class OS > static void copyOutStatBuf (SETranslatingPortProxy & mem, Addr addr, hst_stat * host, bool fakeTTY = false) [inline, static]
Definition at line 526 of file syscall_emul.hh.
SyscallReturn dupFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target dup() handler.
Definition at line 592 of file syscall_emul.cc.
References Process::alloc_fd(), Process::FdMap::filename, Process::FdMap::flags, LiveProcess::getSyscallArg(), MipsISA::index, Process::FdMap::mode, Process::sim_fd(), and Process::sim_fd_obj().
SyscallReturn exitFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target exit() handler: terminate current context.
Definition at line 120 of file syscall_emul.cc.
References exitSimLoop(), LiveProcess::getSyscallArg(), ThreadContext::halt(), MipsISA::index, System::numRunningContexts(), and Process::system.
SyscallReturn exitGroupFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target exit_group() handler: terminate simulation. (exit all threads).
Definition at line 138 of file syscall_emul.cc.
References Process::contextIds, exitSimLoop(), LiveProcess::getSyscallArg(), System::getThreadContext(), ThreadContext::halt(), ArmISA::i, MipsISA::index, System::numRunningContexts(), and Process::system.
template<class OS > SyscallReturn faccessatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target facessat() handler.
Definition at line 695 of file syscall_emul.hh.
References accessFunc(), LiveProcess::getSyscallArg(), MipsISA::index, and warn.
template<class OS > SyscallReturn fchmodFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target fchmod() handler.
Definition at line 808 of file syscall_emul.hh.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, ArmISA::mode, and Process::sim_fd().
SyscallReturn fchownFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target fchown() handler.
Definition at line 572 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn fcntl64Func (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target fcntl64() handler.
Definition at line 652 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, Process::sim_fd(), and warn.
SyscallReturn fcntlFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target fnctl() handler.
Definition at line 609 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, Process::sim_fd(), and warn.
template<class OS > SyscallReturn fstat64Func (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target fstat64() handler.
Definition at line 1002 of file syscall_emul.hh.
References ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
template<class OS > SyscallReturn fstatat64Func (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target fstatat64() handler.
Definition at line 965 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, SETranslatingPortProxy::tryReadString(), and warn.
template<class OS > SyscallReturn fstatfsFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target fstatfs() handler.
Definition at line 1153 of file syscall_emul.hh.
References ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
template<class OS > SyscallReturn fstatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target fstat() handler.
Definition at line 1096 of file syscall_emul.hh.
References DPRINTF, ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn ftruncate64Func (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target ftruncate64() handler.
Definition at line 519 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn ftruncateFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target ftruncate() handler.
Definition at line 480 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
template<class OS > SyscallReturn futexFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Futex system call Implemented by Daniel Sanchez Used by printf's in multi-threaded apps.
Definition at line 306 of file syscall_emul.hh.
References DPRINTF, System::futexMap, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), ThreadContext::getSystemPtr(), X86ISA::op, SETranslatingPortProxy::readBlob(), ThreadContext::suspend(), X86ISA::val, and warn.
SyscallReturn getcwdFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getcwd() handler.
Definition at line 334 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), LiveProcess::getcwd(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and MipsISA::index.
SyscallReturn getegidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getegid() handler.
Definition at line 791 of file syscall_emul.cc.
References LiveProcess::egid().
template<class T1 , class T2 > void getElapsedTimeMicro (T1 & sec, T2 & usec) [inline]
Helper function to convert current elapsed time to seconds and microseconds.
Definition at line 416 of file syscall_emul.hh.
References curTick(), one_million, and SimClock::Int::us.
Referenced by getrusageFunc(), gettimeofdayFunc(), and timeFunc().
template<class T1 , class T2 > void getElapsedTimeNano (T1 & sec, T2 & nsec) [inline]
Helper function to convert current elapsed time to seconds and nanoseconds.
Definition at line 427 of file syscall_emul.hh.
References curTick(), SimClock::Int::ns, and one_billion.
Referenced by clock_gettimeFunc().
SyscallReturn geteuidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target geteuid() handler.
Definition at line 777 of file syscall_emul.cc.
References LiveProcess::euid().
SyscallReturn getgidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getgid() handler.
Definition at line 784 of file syscall_emul.cc.
References LiveProcess::gid().
SyscallReturn getgidPseudoFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getgidPseudo() handler.
Definition at line 731 of file syscall_emul.cc.
References LiveProcess::egid(), LiveProcess::gid(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn gethostnameFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target gethostname() handler.
Definition at line 319 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), hostname, MipsISA::index, and name().
SyscallReturn getpagesizeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getpagesize() handler.
Definition at line 158 of file syscall_emul.cc.
References AlphaISA::PageBytes.
SyscallReturn getpidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getpid() handler.
Definition at line 751 of file syscall_emul.cc.
References LiveProcess::pid(), LiveProcess::ppid(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn getpidPseudoFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getpidPseudo() handler.
Definition at line 705 of file syscall_emul.cc.
References LiveProcess::pid(), LiveProcess::ppid(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn getppidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getppid() handler.
Definition at line 763 of file syscall_emul.cc.
References LiveProcess::ppid().
template<class OS > SyscallReturn getrlimitFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target getrlimit() handler.
Definition at line 1307 of file syscall_emul.hh.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, and warn.
template<class OS > SyscallReturn getrusageFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target getrusage() function.
Definition at line 1416 of file syscall_emul.hh.
References getElapsedTimeMicro(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, and warn.
template<class OS > SyscallReturn gettimeofdayFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target gettimeofday() handler.
Definition at line 1361 of file syscall_emul.hh.
References getElapsedTimeMicro(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, and seconds_since_epoch.
SyscallReturn getuidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getuid() handler.
Definition at line 770 of file syscall_emul.cc.
References LiveProcess::uid().
SyscallReturn getuidPseudoFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getuidPseudo() handler.
Definition at line 718 of file syscall_emul.cc.
References LiveProcess::euid(), ThreadContext::setIntReg(), AlphaISA::SyscallPseudoReturnReg, and LiveProcess::uid().
SyscallReturn ignoreFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.
) and should not affect the correct behavior of the program. Print a warning only if the appropriate trace flag is enabled. Return success to the target program.
Definition at line 98 of file syscall_emul.cc.
References LiveProcess::getSyscallArg(), MipsISA::index, SyscallDesc::name, warn, SyscallDesc::warned, and SyscallDesc::warnOnce().
template<class OS > SyscallReturn ioctlFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target ioctl() handler.
For the most part, programs call ioctl() only to find out if their stdout is a tty, to determine whether to do line or block buffering. We always claim that output fds are not TTYs to provide repeatable results.
Definition at line 552 of file syscall_emul.hh.
References DPRINTF, Process::FdMap::driver, ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, EmulatedDriver::ioctl(), ThreadContext::pcState(), Process::sim_fd_obj(), and warn.
SyscallReturn lseekFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target lseek() handler.
Definition at line 262 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
template<class OS > SyscallReturn lstat64Func (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target lstat64() handler.
Definition at line 1062 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn lstatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target lstat() handler.
Definition at line 1033 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn mkdirFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target mkdir() handler.
Definition at line 422 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, ArmISA::mode, and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn mmapFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc) [inline]
Target mmap() handler.
We don't really handle mmap(). If the target is mmaping an anonymous region or /dev/zero, we can get away with doing basically nothing (since memory is initialized to zero and the simulator doesn't really check addresses anyway).
Definition at line 1224 of file syscall_emul.hh.
References Process::allocateMem(), Process::FdMap::fd, Process::FdMap::filename, LiveProcess::getSyscallArg(), MipsISA::index, PageTableBase::isUnmapped(), Process::mmap_end, ArmISA::offset, AlphaISA::PageBytes, Process::pTable, roundUp(), Process::sim_fd_obj(), and warn.
template<class OS > SyscallReturn mremapFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target mremap() handler.
Definition at line 835 of file syscall_emul.hh.
References Process::allocateMem(), LiveProcess::getSyscallArg(), MipsISA::index, Process::mmap_end, AlphaISA::PageBytes, Process::pTable, PageTableBase::remap(), roundUp(), PageTableBase::unmap(), and warn.
SyscallReturn munmapFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target munmap() handler.
Definition at line 309 of file syscall_emul.cc.
template<class OS > SyscallReturn openatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target openat() handler.
Definition at line 668 of file syscall_emul.hh.
References LiveProcess::getSyscallArg(), MipsISA::index, and warn.
template<class OS > SyscallReturn openFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target open() handler.
Definition at line 659 of file syscall_emul.hh.
template<class OS > static SyscallReturn openFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc, int index) [inline, static]
Definition at line 583 of file syscall_emul.hh.
References Process::alloc_fd(), DPRINTF, ArmISA::fd, LiveProcess::findDriver(), LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), ArmISA::i, ArmISA::mode, EmulatedDriver::open(), startswith(), SETranslatingPortProxy::tryReadString(), and warn.
SyscallReturn pipePseudoFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
Definition at line 682 of file syscall_emul.cc.
References Process::alloc_fd(), ThreadContext::setIntReg(), Process::setReadPipeSource(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn readFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target read() handler.
Definition at line 225 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
template<class OS > SyscallReturn readlinkatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target readlinkat() handler.
Definition at line 708 of file syscall_emul.hh.
References LiveProcess::getSyscallArg(), MipsISA::index, readlinkFunc(), and warn.
SyscallReturn readlinkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target open() handler.
Definition at line 368 of file syscall_emul.cc.
References readlinkFunc().
Referenced by readlinkatFunc(), and readlinkFunc().
SyscallReturn readlinkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc, int index = 0)
Target readlink() handler.
Definition at line 375 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn renameatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target renameat() handler.
Definition at line 721 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, SETranslatingPortProxy::tryReadString(), and warn.
SyscallReturn renameFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target rename() handler.
Definition at line 440 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn setuidFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target setuid() handler.
Definition at line 741 of file syscall_emul.cc.
References LiveProcess::getSyscallArg(), MipsISA::index, and warn.
template<class OS > SyscallReturn stat64Func (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target stat64() handler.
Definition at line 931 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn statfsFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target statfs() handler.
Definition at line 1123 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn statFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target stat() handler.
Definition at line 901 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
template<class OS > SyscallReturn sysinfoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target sysinfo() handler.
Definition at line 757 of file syscall_emul.hh.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, System::memSize(), seconds_since_epoch, and Process::system.
template<class OS > SyscallReturn timeFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target time() function.
Definition at line 1494 of file syscall_emul.hh.
References getElapsedTimeMicro(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, MipsISA::p, seconds_since_epoch, ArmISA::t, and SETranslatingPortProxy::writeBlob().
template<class OS > SyscallReturn timesFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target times() function.
Definition at line 1468 of file syscall_emul.hh.
References curTick(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, and SimClock::Int::s.
SyscallReturn truncate64Func (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target truncate64() handler.
Definition at line 496 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn truncateFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target truncate() handler.
Definition at line 462 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn umaskFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target umask() handler.
Definition at line 539 of file syscall_emul.cc.
SyscallReturn unimplementedFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Handler for unimplemented syscalls that we haven't thought about.
Definition at line 88 of file syscall_emul.cc.
References fatal, and SyscallDesc::name.
template<class OS > SyscallReturn unlinkatFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target unlinkat() handler.
Definition at line 681 of file syscall_emul.hh.
References LiveProcess::getSyscallArg(), MipsISA::index, unlinkHelper(), and warn.
SyscallReturn unlinkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Definition at line 399 of file syscall_emul.cc.
References unlinkHelper().
SyscallReturn unlinkHelper (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc, int index)
Target unlink() handler.
Definition at line 405 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and SETranslatingPortProxy::tryReadString().
Referenced by unlinkatFunc(), and unlinkFunc().
template<class OS > SyscallReturn utimesFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target utimes() handler.
Definition at line 1381 of file syscall_emul.hh.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::gtoh(), ArmISA::i, MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn writeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target write() handler.
Definition at line 243 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
template<class OS > SyscallReturn writevFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [inline]
Target writev() handler.
Definition at line 1178 of file syscall_emul.hh.
References X86ISA::count, ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::gtoh(), ArmISA::i, MipsISA::index, MipsISA::p, SETranslatingPortProxy::readBlob(), and Process::sim_fd().
Variable Documentation
const int one_billion = 1000000000
A readable name for 1,000,000,000, for converting nanoseconds to seconds.
Definition at line 405 of file syscall_emul.hh.
Referenced by getElapsedTimeNano().
const int one_million = 1000000
A readable name for 1,000,000, for converting microseconds to seconds.
Definition at line 403 of file syscall_emul.hh.
Referenced by getElapsedTimeMicro(), and tableFunc().
const unsigned seconds_since_epoch = 1000000000
Approximate seconds since the epoch (1/1/1970).
About a billion, by my reckoning. We want to keep this a constant (not use the real-world time) to keep simulations repeatable.
Definition at line 410 of file syscall_emul.hh.
Referenced by clock_gettimeFunc(), gettimeofdayFunc(), sysinfoFunc(), tableFunc(), and timeFunc().