gem5: sim/syscall_emul.cc File Reference
sim/syscall_emul.cc File Reference
#include <fcntl.h>
#include <unistd.h>
#include <cstdio>
#include <iostream>
#include <string>
#include "arch/utility.hh"
#include "base/chunk_generator.hh"
#include "base/trace.hh"
#include "config/the_isa.hh"
#include "cpu/base.hh"
#include "cpu/thread_context.hh"
#include "debug/SyscallVerbose.hh"
#include "mem/page_table.hh"
#include "sim/process.hh"
#include "sim/sim_exit.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
SyscallReturn unimplementedFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Handler for unimplemented syscalls that we haven't thought about.
SyscallReturn ignoreFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.
SyscallReturn exitFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target exit() handler: terminate current context.
SyscallReturn exitGroupFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target exit_group() handler: terminate simulation. (exit all threads).
SyscallReturn getpagesizeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getpagesize() handler.
SyscallReturn brkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target brk() handler: set brk address.
SyscallReturn closeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target close() handler.
SyscallReturn readFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target read() handler.
SyscallReturn writeFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target write() handler.
SyscallReturn lseekFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target lseek() handler.
SyscallReturn _llseekFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target _llseek() handler.
SyscallReturn munmapFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target munmap() handler.
SyscallReturn gethostnameFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target gethostname() handler.
SyscallReturn getcwdFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target getcwd() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target open() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc, int index)
Target readlink() handler.
SyscallReturn unlinkFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
SyscallReturn unlinkHelper (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc, int index)
Target unlink() handler.
SyscallReturn mkdirFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target mkdir() handler.
SyscallReturn renameFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target rename() handler.
SyscallReturn truncateFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target truncate() handler.
SyscallReturn ftruncateFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target ftruncate() handler.
SyscallReturn truncate64Func (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target truncate64() handler.
SyscallReturn ftruncate64Func (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target ftruncate64() handler.
SyscallReturn umaskFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target umask() handler.
SyscallReturn chownFunc (SyscallDesc *desc, int num, LiveProcess *p, ThreadContext *tc)
Target chown() handler.
SyscallReturn fchownFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target fchown() handler.
SyscallReturn dupFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target dup() handler.
SyscallReturn fcntlFunc (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target fnctl() handler.
SyscallReturn fcntl64Func (SyscallDesc *desc, int num, LiveProcess *process, ThreadContext *tc)
Target fcntl64() handler.
SyscallReturn pipePseudoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
SyscallReturn getpidPseudoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getpidPseudo() handler.
SyscallReturn getuidPseudoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getuidPseudo() handler.
SyscallReturn getgidPseudoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getgidPseudo() handler.
SyscallReturn setuidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target setuid() handler.
SyscallReturn getpidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getpid() handler.
SyscallReturn getppidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getppid() handler.
SyscallReturn getuidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getuid() handler.
SyscallReturn geteuidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target geteuid() handler.
SyscallReturn getgidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getgid() handler.
SyscallReturn getegidFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getegid() handler.
SyscallReturn cloneFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target clone() handler.
SyscallReturn accessFunc (SyscallDesc *desc, int callnum, LiveProcess *p, ThreadContext *tc, int index)
SyscallReturn accessFunc (SyscallDesc *desc, int callnum, LiveProcess *p, ThreadContext *tc)
Target access() handler.
Variables
const char * hostname = "m5.eecs.umich.edu"
Function Documentation
SyscallReturn _llseekFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target _llseek() handler.
Definition at line 277 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, ArmISA::offset, and Process::sim_fd().
SyscallReturn accessFunc (SyscallDesc * desc, int callnum, LiveProcess * p, ThreadContext * tc)
Target access() handler.
Definition at line 898 of file syscall_emul.cc.
References accessFunc().
SyscallReturn accessFunc (SyscallDesc * desc, int callnum, LiveProcess * p, ThreadContext * tc, int index)
Definition at line 881 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), ArmISA::mode, and SETranslatingPortProxy::tryReadString().
Referenced by accessFunc(), and faccessatFunc().
SyscallReturn brkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target brk() handler: set brk address.
Definition at line 165 of file syscall_emul.cc.
References Process::allocateMem(), Process::brk_point, DPRINTF, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, SETranslatingPortProxy::memsetBlob(), AlphaISA::PageBytes, Process::pTable, roundDown(), roundUp(), and PageTableBase::translate().
SyscallReturn chownFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target chown() handler.
Definition at line 550 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn cloneFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target clone() handler.
Definition at line 799 of file syscall_emul.cc.
References ThreadContext::activate(), SparcISA::ASI_PRIMARY, ThreadContext::clearArchRegs(), AlphaISA::copyMiscRegs(), AlphaISA::copyRegs(), DPRINTF, fatal, Process::findFreeContext(), LiveProcess::getSyscallArg(), MipsISA::index, SparcISA::MISCREG_ASI, SparcISA::MISCREG_CWP, SparcISA::MISCREG_TL, ThreadContext::nextInstAddr(), AlphaISA::NumIntArchRegs, SparcISA::NWindows, ThreadContext::pcState(), ThreadContext::readIntReg(), AlphaISA::ReturnValueReg, ThreadContext::setIntReg(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), AlphaISA::StackPointerReg, AlphaISA::SyscallPseudoReturnReg, AlphaISA::SyscallSuccessReg, and warn.
SyscallReturn closeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target close() handler.
Definition at line 210 of file syscall_emul.cc.
References Process::free_fd(), LiveProcess::getSyscallArg(), MipsISA::index, Process::sim_fd(), and ArmISA::status.
SyscallReturn dupFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target dup() handler.
Definition at line 592 of file syscall_emul.cc.
References Process::alloc_fd(), Process::FdMap::filename, Process::FdMap::flags, LiveProcess::getSyscallArg(), MipsISA::index, Process::FdMap::mode, Process::sim_fd(), and Process::sim_fd_obj().
SyscallReturn exitFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target exit() handler: terminate current context.
Definition at line 120 of file syscall_emul.cc.
References exitSimLoop(), LiveProcess::getSyscallArg(), ThreadContext::halt(), MipsISA::index, System::numRunningContexts(), and Process::system.
SyscallReturn exitGroupFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target exit_group() handler: terminate simulation. (exit all threads).
Definition at line 138 of file syscall_emul.cc.
References Process::contextIds, exitSimLoop(), LiveProcess::getSyscallArg(), System::getThreadContext(), ThreadContext::halt(), ArmISA::i, MipsISA::index, System::numRunningContexts(), and Process::system.
SyscallReturn fchownFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target fchown() handler.
Definition at line 572 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn fcntl64Func (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target fcntl64() handler.
Definition at line 652 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, Process::sim_fd(), and warn.
SyscallReturn fcntlFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target fnctl() handler.
Definition at line 609 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, Process::sim_fd(), and warn.
SyscallReturn ftruncate64Func (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target ftruncate64() handler.
Definition at line 519 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn ftruncateFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target ftruncate() handler.
Definition at line 480 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn getcwdFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getcwd() handler.
Definition at line 334 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), LiveProcess::getcwd(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and MipsISA::index.
SyscallReturn getegidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getegid() handler.
Definition at line 791 of file syscall_emul.cc.
References LiveProcess::egid().
SyscallReturn geteuidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target geteuid() handler.
Definition at line 777 of file syscall_emul.cc.
References LiveProcess::euid().
SyscallReturn getgidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getgid() handler.
Definition at line 784 of file syscall_emul.cc.
References LiveProcess::gid().
SyscallReturn getgidPseudoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getgidPseudo() handler.
Definition at line 731 of file syscall_emul.cc.
References LiveProcess::egid(), LiveProcess::gid(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn gethostnameFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target gethostname() handler.
Definition at line 319 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), hostname, MipsISA::index, and name().
SyscallReturn getpagesizeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target getpagesize() handler.
Definition at line 158 of file syscall_emul.cc.
References AlphaISA::PageBytes.
SyscallReturn getpidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getpid() handler.
Definition at line 751 of file syscall_emul.cc.
References LiveProcess::pid(), LiveProcess::ppid(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn getpidPseudoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getpidPseudo() handler.
Definition at line 705 of file syscall_emul.cc.
References LiveProcess::pid(), LiveProcess::ppid(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn getppidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getppid() handler.
Definition at line 763 of file syscall_emul.cc.
References LiveProcess::ppid().
SyscallReturn getuidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getuid() handler.
Definition at line 770 of file syscall_emul.cc.
References LiveProcess::uid().
SyscallReturn getuidPseudoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target getuidPseudo() handler.
Definition at line 718 of file syscall_emul.cc.
References LiveProcess::euid(), ThreadContext::setIntReg(), AlphaISA::SyscallPseudoReturnReg, and LiveProcess::uid().
SyscallReturn ignoreFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.
) and should not affect the correct behavior of the program. Print a warning only if the appropriate trace flag is enabled. Return success to the target program.
Definition at line 98 of file syscall_emul.cc.
References LiveProcess::getSyscallArg(), MipsISA::index, SyscallDesc::name, warn, SyscallDesc::warned, and SyscallDesc::warnOnce().
SyscallReturn lseekFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target lseek() handler.
Definition at line 262 of file syscall_emul.cc.
References ArmISA::fd, LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn mkdirFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target mkdir() handler.
Definition at line 422 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, ArmISA::mode, and SETranslatingPortProxy::tryReadString().
SyscallReturn munmapFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target munmap() handler.
Definition at line 309 of file syscall_emul.cc.
SyscallReturn pipePseudoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
Definition at line 682 of file syscall_emul.cc.
References Process::alloc_fd(), ThreadContext::setIntReg(), Process::setReadPipeSource(), and AlphaISA::SyscallPseudoReturnReg.
SyscallReturn readFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target read() handler.
Definition at line 225 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
SyscallReturn readlinkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc, int index)
Target readlink() handler.
Definition at line 375 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and SETranslatingPortProxy::tryReadString().
SyscallReturn readlinkFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target open() handler.
Definition at line 368 of file syscall_emul.cc.
References readlinkFunc().
Referenced by readlinkatFunc(), and readlinkFunc().
SyscallReturn renameFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target rename() handler.
Definition at line 440 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn setuidFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Target setuid() handler.
Definition at line 741 of file syscall_emul.cc.
References LiveProcess::getSyscallArg(), MipsISA::index, and warn.
SyscallReturn truncate64Func (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target truncate64() handler.
Definition at line 496 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn truncateFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target truncate() handler.
Definition at line 462 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and SETranslatingPortProxy::tryReadString().
SyscallReturn umaskFunc (SyscallDesc * desc, int num, LiveProcess * process, ThreadContext * tc)
Target umask() handler.
Definition at line 539 of file syscall_emul.cc.
SyscallReturn unimplementedFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc)
Handler for unimplemented syscalls that we haven't thought about.
Definition at line 88 of file syscall_emul.cc.
References fatal, and SyscallDesc::name.
SyscallReturn unlinkFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Definition at line 399 of file syscall_emul.cc.
References unlinkHelper().
SyscallReturn unlinkHelper (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc, int index)
Target unlink() handler.
Definition at line 405 of file syscall_emul.cc.
References LiveProcess::fullPath(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), and SETranslatingPortProxy::tryReadString().
Referenced by unlinkatFunc(), and unlinkFunc().
SyscallReturn writeFunc (SyscallDesc * desc, int num, LiveProcess * p, ThreadContext * tc)
Target write() handler.
Definition at line 243 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ArmISA::fd, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and Process::sim_fd().
Variable Documentation
const char* hostname = "m5.eecs.umich.edu"
Definition at line 316 of file syscall_emul.cc.
Referenced by gethostnameFunc(), and hostname().