gem5: cpu/thread_context.cc File Reference
cpu/thread_context.cc File Reference
#include "base/misc.hh"
#include "base/trace.hh"
#include "config/the_isa.hh"
#include "cpu/base.hh"
#include "cpu/quiesce_event.hh"
#include "cpu/thread_context.hh"
#include "debug/Context.hh"
#include "sim/full_system.hh"
Functions
void serialize (ThreadContext &tc, std::ostream &os)
Thread context serialization helpers.
void unserialize (ThreadContext &tc, Checkpoint *cp, const std::string &section)
void takeOverFrom (ThreadContext &ntc, ThreadContext &otc)
Copy state between thread contexts in preparation for CPU handover.
Function Documentation
void serialize (ThreadContext & tc, std::ostream & os)
Thread context serialization helpers.
These helper functions provide a way to the data in a ThreadContext. They are provided as separate helper function since implementing them as members of the ThreadContext interface would be confusing when the ThreadContext is exported via a proxy.
Definition at line 107 of file thread_context.cc.
References arrayParamOut(), ArmISA::i, AlphaISA::NumCCRegs, AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, ThreadContext::pcState(), ThreadContext::readCCRegFlat(), ThreadContext::readFloatRegBitsFlat(), ThreadContext::readIntRegFlat(), and SERIALIZE_ARRAY.
Referenced by ArmISA::EndBitUnion(), and X86ISA::EndBitUnion().
void takeOverFrom (ThreadContext & new_tc, ThreadContext & old_tc)
Copy state between thread contexts in preparation for CPU handover.
Note:
This method modifies the old thread contexts as well as the new thread context. The old thread context will have its quiesce event descheduled if it is scheduled and its status set to halted.
Parameters:
new_tc Destination ThreadContext.
old_tc Source ThreadContext.
Definition at line 167 of file thread_context.cc.
References ThreadContext::contextId(), ThreadContext::copyArchRegs(), FullSystem, ThreadContext::getCpuPtr(), ThreadContext::getProcessPtr(), ThreadContext::getQuiesceEvent(), ThreadContext::getSystemPtr(), ThreadContext::Halted, ThreadContext::setContextId(), ThreadContext::setStatus(), ThreadContext::setThreadId(), ThreadContext::status(), and ThreadContext::threadId().
void unserialize (ThreadContext & tc, Checkpoint * cp, const std::string & section)
Definition at line 136 of file thread_context.cc.
References arrayParamIn(), ArmISA::i, AlphaISA::NumCCRegs, AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, ThreadContext::pcState(), ThreadContext::setCCRegFlat(), ThreadContext::setFloatRegBitsFlat(), ThreadContext::setIntRegFlat(), and UNSERIALIZE_ARRAY.
Referenced by ArmISA::EndBitUnion(), and X86ISA::EndBitUnion().